import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'das lachende Kind', emoji: '😂', translation: l('the laughing child', 'gülen çocuk', 'das Kind, das lacht'), example: 'Das lachende Kind steckt alle an.' },
  { word: 'das gekochte Ei', emoji: '🥚', translation: l('the boiled egg', 'haşlanmış yumurta', 'das Ei, das gekocht wurde'), example: 'Ich esse morgens ein gekochtes Ei.' },
  { word: 'steigend', emoji: '📈', translation: l('rising', 'artan', 'wird mehr'), example: 'Die steigenden Preise sind ein Problem.' },
  { word: 'geöffnet', emoji: '🔓', translation: l('opened', 'açılmış', 'ist offen'), example: 'Bei geöffnetem Fenster schlafe ich besser.' },
  { word: 'fließend', emoji: '💧', translation: l('flowing / fluent', 'akan / akıcı', 'ohne Pause'), example: 'Sie spricht fließend Deutsch.' },
  { word: 'abgeschlossen', emoji: '🎓', translation: l('completed', 'tamamlanmış', 'fertig'), example: 'Sie hat ein abgeschlossenes Studium.' },
  { word: 'überzeugend', emoji: '💪', translation: l('convincing', 'ikna edici', 'überzeugt'), example: 'Das war ein überzeugendes Argument.' },
  { word: 'gestohlen', emoji: '🦹', translation: l('stolen', 'çalınmış', 'jemand hat es gestohlen'), example: 'Die Polizei fand das gestohlene Fahrrad.' },
  { word: 'kommend', emoji: '⏭️', translation: l('coming, next', 'gelecek', 'nächste'), example: 'In der kommenden Woche habe ich Urlaub.' },
  { word: 'verletzt', emoji: '🤕', translation: l('injured', 'yaralı', 'hat sich wehgetan'), example: 'Der verletzte Spieler musste raus.' },
  { word: 'spannend', emoji: '🎢', translation: l('exciting', 'heyecanlı', 'macht neugierig'), example: 'Das ist ein spannender Film.' },
  { word: 'gebraucht', emoji: '🚲', translation: l('used, second-hand', 'ikinci el', 'nicht neu'), example: 'Ich habe ein gebrauchtes Fahrrad gekauft.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Partizip', gender: 'n', plural: 'die Partizipien', translation: l('participle', 'ortaç', 'Partizip') },
  { word: 'Preis', gender: 'm', plural: 'die Preise', translation: l('price', 'fiyat', 'Preis') },
  { word: 'Studium', gender: 'n', plural: 'die Studien', translation: l('degree, studies', 'üniversite eğitimi', 'Studium') },
  { word: 'Spieler', gender: 'm', plural: 'die Spieler', translation: l('player', 'oyuncu', 'Spieler') },
  { word: 'Fenster', gender: 'n', plural: 'die Fenster', translation: l('window', 'pencere', 'Fenster') },
  { word: 'Zahl', gender: 'f', plural: 'die Zahlen', translation: l('number', 'sayı', 'Zahl') },
  { word: 'Ergebnis', gender: 'n', plural: 'die Ergebnisse', translation: l('result', 'sonuç', 'Ergebnis') },
  { word: 'Wagen', gender: 'm', plural: 'die Wagen', translation: l('car', 'araba', 'Wagen') },
]

/** [id, relative clause, right participle phrase, wrong] */
const PART: [string, string, string, [string, string]][] = [
  ['schlafen', 'das Baby, das schläft', 'das schlafende Baby', ['das geschlafene Baby', 'das schlafte Baby']],
  ['reparieren', 'das Auto, das repariert wurde', 'das reparierte Auto', ['das reparierende Auto', 'das reparieren Auto']],
  ['wachsen', 'die Stadt, die wächst', 'die wachsende Stadt', ['die gewachste Stadt', 'die wachsene Stadt']],
  ['schreiben', 'der Brief, der geschrieben wurde', 'der geschriebene Brief', ['der schreibende Brief', 'der geschreibte Brief']],
  ['weinen', 'die Frau, die weint', 'die weinende Frau', ['die geweinte Frau', 'die weinte Frau']],
  ['verkaufen', 'die Tickets, die verkauft wurden', 'die verkauften Tickets', ['die verkaufenden Tickets', 'die verkaufte Tickets']],
]

function partDrills(): Exercise[] {
  return PART.map(([id, clause, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `part-${id}`,
      type: 'multiple_choice' as const,
      topic: 'aktiv-passiv',
      concept: 'choose-participle',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: `„${clause}“ – kürzer:`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Active, happening now → Partizip I (-end). Passive / finished → Partizip II. → ${right}`,
        `Etken, şu an oluyor → Partizip I (-end). Edilgen / bitmiş → Partizip II. → ${right}`,
        `→ ${right}`
      ),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-partizip',
    type: 'matching',
    topic: 'partizip-i',
    concept: 'meaning',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the participle phrase and its meaning.', 'Ortaç ifadesini anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'das brennende Haus', right: 'the burning house' },
      { left: 'das verbrannte Haus', right: 'the burnt house' },
      { left: 'die singende Frau', right: 'the singing woman' },
      { left: 'das gesungene Lied', right: 'the sung song' },
      { left: 'der wartende Gast', right: 'the waiting guest' },
    ],
    explanation: l('-end = -ing (active, now); ge-…-t/-en = done (passive, finished).', '-end = -en/-an (etken, şimdi); ge-…-t/-en = yapılmış (edilgen, bitmiş).', 'Partizip I / II.'),
  },
  {
    id: 'sort-p1-p2',
    type: 'categorize',
    topic: 'aktiv-passiv',
    concept: 'p1-vs-p2',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Partizip I or Partizip II?', 'Partizip I mi Partizip II mi?', 'Partizip I oder II?'),
    categories: ['Partizip I (-end)', 'Partizip II'],
    items: [
      { text: 'die steigenden Kosten', category: 0 },
      { text: 'das gestohlene Rad', category: 1 },
      { text: 'ein spannender Krimi', category: 0 },
      { text: 'die geschlossene Tür', category: 1 },
      { text: 'das kommende Jahr', category: 0 },
      { text: 'ein gebrauchtes Handy', category: 1 },
    ],
    explanation: l('Partizip I = infinitive + d. Partizip II = ge- … -t / -en.', 'Partizip I = mastar + d. Partizip II = ge- … -t / -en.', 'Formen.'),
    practice: ['part-schlafen'],
  },
  {
    id: 'mc-endung',
    type: 'multiple_choice',
    topic: 'endungen',
    concept: 'adjective-endings',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Wir suchen eine Wohnung mit einem ___ Balkon.',
    options: ['überdachten', 'überdachte', 'überdacht'],
    answer: 0,
    explanation: l('Participles take normal adjective endings: mit einem (dative, masc.) → -en.', 'Ortaçlar normal sıfat ekleri alır: mit einem (Dativ, eril) → -en.', 'mit einem überdachten Balkon.'),
    examples: ['mit einem **überdachten** Balkon'],
    practice: ['fill-steigenden'],
  },
  {
    id: 'tf-aktiv',
    type: 'true_false',
    topic: 'aktiv-passiv',
    concept: 'p1-vs-p2',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Die gelesene Zeitung“ bedeutet: Die Zeitung liest gerade.',
    answer: false,
    explanation: l('gelesen = Partizip II = the newspaper has been read (passive).', 'gelesen = Partizip II = gazete okunmuş (edilgen).', 'Sie wurde gelesen.'),
  },
  {
    id: 'select-p1',
    type: 'multiple_select',
    topic: 'partizip-i',
    concept: 'forms',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which are correct Partizip I forms? Select all.', 'Hangileri doğru Partizip I biçimi? Hepsini seç.', 'Richtige Partizip-I-Formen?'),
    options: ['lachend', 'gelacht', 'fahrend', 'wartend', 'gewartet'],
    answers: [0, 2, 3],
    explanation: l('Partizip I = infinitive + d: lachend, fahrend, wartend.', 'Partizip I = mastar + d: lachend, fahrend, wartend.', '+ d.'),
  },
  {
    id: 'image-brennend',
    type: 'image_choice',
    topic: 'partizip-i',
    concept: 'meaning',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Auf dem Tisch steht eine brennende Kerze.',
    options: [
      { emoji: '🕯️', label: 'brennende Kerze' },
      { emoji: '🧊', label: 'gefrorenes Wasser' },
      { emoji: '📕', label: 'geschlossenes Buch' },
      { emoji: '🍳', label: 'gebratenes Ei' },
    ],
    answer: 0,
    explanation: l('brennend = burning (right now).', 'brennend = yanan (şu an).', 'brennend.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-steigenden',
    type: 'fill_blank',
    topic: 'endungen',
    concept: 'adjective-endings',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Viele Menschen leiden unter den ___ Mieten. (steigen)',
    accepted: ['steigenden'],
    base: 'steigen → Partizip I',
    explanation: l('steigend + -en (dative plural).', 'steigend + -en (Dativ çoğul).', 'steigenden.'),
    examples: ['… unter den **steigenden** Mieten.'],
  },
  {
    id: 'fill-gestohlene',
    type: 'fill_blank',
    topic: 'partizip-ii',
    concept: 'p2-adjective',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Polizei hat das ___ Auto gefunden. (stehlen)',
    accepted: ['gestohlene'],
    base: 'stehlen → Partizip II',
    explanation: l('gestohlen + -e (das … Auto, accusative).', 'gestohlen + -e (das … Auto, Akk).', 'gestohlene.'),
    examples: ['Die Polizei hat das **gestohlene** Auto gefunden.'],
  },
  {
    id: 'fill-fliessend',
    type: 'fill_blank',
    topic: 'partizip-i',
    concept: 'adverb',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Nach drei Jahren spricht er ___ Deutsch. (fließen)',
    accepted: ['fließend'],
    base: 'fließen',
    explanation: l('Used as an adverb → no ending: fließend.', 'Zarf olarak kullanılınca → ek yok: fließend.', 'fließend.'),
    examples: ['Er spricht **fließend** Deutsch.'],
  },
  {
    id: 'build-partizip1',
    type: 'sentence_builder',
    topic: 'partizip-i',
    concept: 'p1-adjective',
    skill: 'grammar',
    difficulty: 2,
    chips: ['die wartenden Fahrgäste', 'Der Busfahrer', 'begrüßt', 'freundlich'],
    answers: [['Der Busfahrer', 'begrüßt', 'die wartenden Fahrgäste', 'freundlich'], ['Der Busfahrer', 'begrüßt', 'freundlich', 'die wartenden Fahrgäste']],
    translation: l('The bus driver greets the waiting passengers in a friendly way.', 'Otobüs şoförü bekleyen yolcuları güler yüzle selamlıyor.', 'Der Busfahrer begrüßt die wartenden Fahrgäste freundlich.'),
    explanation: l('die wartenden Fahrgäste = die Fahrgäste, die warten.', 'die wartenden Fahrgäste = die Fahrgäste, die warten.', 'wartend.'),
    examples: ['Der Busfahrer begrüßt die **wartenden** Fahrgäste.'],
  },
  {
    id: 'build-partizip2',
    type: 'sentence_builder',
    topic: 'partizip-ii',
    concept: 'p2-adjective',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ein abgeschlossenes Studium', 'Für die Stelle', 'Sie', 'brauchen'],
    answers: [['Für die Stelle', 'brauchen', 'Sie', 'ein abgeschlossenes Studium']],
    translation: l('For the job you need a completed degree.', 'Bu iş için tamamlanmış bir üniversite eğitimine ihtiyacınız var.', 'Für die Stelle brauchen Sie ein abgeschlossenes Studium.'),
    explanation: l('ein abgeschlossenes Studium = a degree that has been completed.', 'ein abgeschlossenes Studium = tamamlanmış bir eğitim.', 'abgeschlossen.'),
    examples: ['Sie brauchen ein **abgeschlossenes** Studium.'],
  },
  {
    id: 'build-kommend',
    type: 'sentence_builder',
    topic: 'endungen',
    concept: 'adjective-endings',
    skill: 'grammar',
    difficulty: 2,
    chips: ['beginnt', 'In der kommenden Woche', 'mein neuer Job'],
    answers: [['In der kommenden Woche', 'beginnt', 'mein neuer Job']],
    translation: l('My new job starts next week.', 'Gelecek hafta yeni işim başlıyor.', 'In der kommenden Woche beginnt mein neuer Job.'),
    explanation: l('in der kommenden Woche = next week (formal).', 'in der kommenden Woche = gelecek hafta (resmî).', 'kommend.'),
    examples: ['In der **kommenden** Woche beginnt mein neuer Job.'],
  },
  {
    id: 'fix-endung',
    type: 'error_correction',
    topic: 'endungen',
    concept: 'adjective-endings',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das war ein sehr überzeugend Vortrag.',
    accepted: ['Das war ein sehr überzeugender Vortrag.'],
    explanation: l('Before a noun the participle needs an ending: ein überzeugender Vortrag.', 'İsimden önce ortaç ek alır: ein überzeugender Vortrag.', 'überzeugender.'),
    examples: ['Das war ein sehr **überzeugender** Vortrag.'],
  },
  {
    id: 'fix-p1-p2',
    type: 'error_correction',
    topic: 'aktiv-passiv',
    concept: 'p1-vs-p2',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich habe ein gebrauchendes Fahrrad gekauft.',
    accepted: ['Ich habe ein gebrauchtes Fahrrad gekauft.'],
    explanation: l('The bike has been used (passive) → Partizip II: gebrauchtes.', 'Bisiklet kullanılmış (edilgen) → Partizip II: gebrauchtes.', 'gebrauchtes.'),
    examples: ['Ich habe ein **gebrauchtes** Fahrrad gekauft.'],
  },
  {
    id: 'fix-spannend',
    type: 'error_correction',
    topic: 'partizip-i',
    concept: 'p1-adjective',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das ist ein gespannter Film.',
    accepted: ['Das ist ein spannender Film.'],
    explanation: l('The film creates excitement (active) → spannend. gespannt = (a person is) curious.', 'Film heyecan yaratır (etken) → spannend. gespannt = (bir kişi) meraklı.', 'spannend.'),
    examples: ['Das ist ein **spannender** Film.'],
  },
  {
    id: 'tr-schlafend',
    type: 'translation',
    topic: 'partizip-i',
    concept: 'p1-adjective',
    skill: 'writing',
    difficulty: 2,
    source: l('Don’t wake the sleeping child.', 'Uyuyan çocuğu uyandırma.', 'Don’t wake the sleeping child.'),
    accepted: ['Weck das schlafende Kind nicht.', 'Weck das schlafende Kind nicht!', 'Wecke das schlafende Kind nicht.', 'Wecke das schlafende Kind nicht!', 'Wecken Sie das schlafende Kind nicht.', 'Wecken Sie das schlafende Kind nicht!'],
    explanation: l('das schlafende Kind = the child that is sleeping.', 'das schlafende Kind = uyumakta olan çocuk.', 'schlafend.'),
    examples: ['Weck das **schlafende** Kind nicht!'],
  },
  {
    id: 'tr-repariert',
    type: 'translation',
    topic: 'partizip-ii',
    concept: 'p2-adjective',
    skill: 'writing',
    difficulty: 2,
    source: l('I picked up the repaired phone.', 'Tamir edilmiş telefonu aldım.', 'I picked up the repaired phone.'),
    accepted: ['Ich habe das reparierte Handy abgeholt.', 'Ich holte das reparierte Handy ab.', 'Ich habe das reparierte Telefon abgeholt.'],
    explanation: l('das reparierte Handy = the phone that was repaired.', 'das reparierte Handy = tamir edilmiş telefon.', 'repariert.'),
    examples: ['Ich habe das **reparierte** Handy abgeholt.'],
  },
  {
    id: 'ordering-zeitung',
    type: 'ordering',
    topic: 'partizip-ii',
    concept: 'text',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the short report in order.', 'Kısa haberi sırala.', 'Ordne die Meldung.'),
    items: ['Ein aufmerksamer Nachbar rief sofort die Polizei.', 'In der Nacht wurde ein geparktes Auto beschädigt.', 'Der verärgerte Besitzer hofft nun auf Zeugen.', 'Der flüchtende Täter konnte jedoch entkommen.'],
    answer: ['In der Nacht wurde ein geparktes Auto beschädigt.', 'Ein aufmerksamer Nachbar rief sofort die Polizei.', 'Der flüchtende Täter konnte jedoch entkommen.', 'Der verärgerte Besitzer hofft nun auf Zeugen.'],
    explanation: l('Event → reaction → result → outlook. Note the participles.', 'Olay → tepki → sonuç → beklenti. Ortaçlara dikkat et.', 'Chronologie.'),
  },
  {
    id: 'dialog-gespannt',
    type: 'dialogue',
    topic: 'partizip-i',
    concept: 'p1-adjective',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Wie war die Serie, die du empfohlen hast?' }],
    options: ['Total spannend! Die letzte Folge war einfach überraschend.', 'Total gespannt die Folge.', 'Die Serie war gesehen.'],
    answer: 0,
    explanation: l('spannend, überraschend = Partizip I used as adjectives.', 'spannend, überraschend = sıfat olarak Partizip I.', 'spannend.'),
  },
  {
    id: 'dialog-gebraucht',
    type: 'dialogue',
    topic: 'partizip-ii',
    concept: 'p2-adjective',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Verkäufer', de: 'Möchten Sie ein neues oder ein gebrauchtes Gerät?' }],
    options: ['Ein gebrauchtes, aber bitte ein geprüftes mit Garantie.', 'Ein brauchendes, bitte.', 'Gebraucht ist neu.'],
    answer: 0,
    explanation: l('gebraucht, geprüft = Partizip II (passive).', 'gebraucht, geprüft = Partizip II (edilgen).', 'Partizip II.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-was',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was wird verkauft?',
    options: ['Ein gebrauchtes Lastenrad.', 'Ein neues Auto.', 'Eine Wohnung.'],
    answer: 0,
    explanation: l('„Gebrauchtes Lastenrad zu verkaufen“', '„Gebrauchtes Lastenrad zu verkaufen“', 'Lastenrad.'),
  },
  {
    id: 'read-zustand',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    prompt: 'In welchem Zustand ist das Rad?',
    options: ['Gut – frisch gewartet, mit neuen Bremsen.', 'Kaputt.', 'Ganz neu und unbenutzt.'],
    answer: 0,
    explanation: l('„Frisch gewartet, neue Bremsen“', '„Frisch gewartet, neue Bremsen“', 'gewartet.'),
  },
  {
    id: 'read-kinder',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    statement: 'Im Rad haben zwei Kinder Platz.',
    answer: true,
    explanation: l('„Platz für zwei mitfahrende Kinder“', '„Platz für zwei mitfahrende Kinder“', 'richtig.'),
  },
  {
    id: 'read-grund',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum wird das Rad verkauft?',
    options: ['Die Familie zieht in eine andere Stadt.', 'Es ist zu langsam.', 'Die Kinder mögen es nicht.'],
    answer: 0,
    explanation: l('„Wegen eines bevorstehenden Umzugs …“', '„Wegen eines bevorstehenden Umzugs …“', 'Umzug.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-verspaetet',
    type: 'listening_choice',
    topic: 'partizip-ii',
    concept: 'p2-adjective',
    skill: 'listening',
    difficulty: 2,
    audio: 'Fahrgäste des verspäteten ICE nach München können den Regionalzug auf Gleis 4 benutzen.',
    question: l('Who can take the regional train?', 'Bölgesel treni kim kullanabilir?', 'Wer kann den Regionalzug nehmen?'),
    options: ['passengers of the delayed ICE', 'only children', 'nobody'],
    answer: 0,
    explanation: l('„des verspäteten ICE“', '„des verspäteten ICE“', 'verspätet.'),
  },
  {
    id: 'listen-preise',
    type: 'listening_choice',
    topic: 'partizip-i',
    concept: 'p1-adjective',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wegen der steigenden Energiepreise heizen viele Familien weniger.',
    question: l('Why do many families heat less?', 'Birçok aile neden daha az ısınıyor?', 'Warum heizen Familien weniger?'),
    options: ['rising energy prices', 'warm weather', 'new heaters'],
    answer: 0,
    explanation: l('„steigenden Energiepreise“', '„steigenden Energiepreise“', 'steigend.'),
  },
  {
    id: 'listen-fundbuero',
    type: 'listening_choice',
    topic: 'partizip-ii',
    concept: 'p2-adjective',
    skill: 'listening',
    difficulty: 2,
    audio: 'Verlorene Gegenstände können im Fundbüro im Erdgeschoss abgeholt werden.',
    question: l('Where can you pick up lost items?', 'Kayıp eşyalar nereden alınabilir?', 'Wo gibt es verlorene Sachen?'),
    options: ['at the lost-property office', 'at the ticket office', 'at the police'],
    answer: 0,
    explanation: l('„im Fundbüro im Erdgeschoss“', '„im Fundbüro im Erdgeschoss“', 'Fundbüro.'),
  },
  {
    id: 'listen-sprechend',
    type: 'listening_choice',
    topic: 'aktiv-passiv',
    concept: 'p1-vs-p2',
    skill: 'listening',
    difficulty: 3,
    audio: 'Gesucht wird eine Deutsch und Englisch fließend sprechende Assistenz für unser Büro.',
    question: l('What must the assistant be able to do?', 'Asistan ne yapabilmeli?', 'Was muss die Assistenz können?'),
    options: ['speak German and English fluently', 'drive a car', 'speak Turkish'],
    answer: 0,
    explanation: l('„Deutsch und Englisch fließend sprechende Assistenz“', '„Deutsch und Englisch fließend sprechende Assistenz“', 'fließend.'),
  },

  ...partDrills(),
]

export const UNIT_B2_03_PARTIZIPIEN: CourseUnit = {
  level: 'B2',
  number: 3,
  slug: 'partizipien',
  titleDe: 'Die lachenden Kinder',
  title: l('The laughing children', 'Gülen çocuklar', 'Die lachenden Kinder'),
  goal: l(
    'By the end of this unit you can use Partizip I (lachend) and Partizip II (gekocht) as adjectives with the right endings, and decide whether the meaning is active or passive.',
    'Bu ünitenin sonunda Partizip I’i (lachend) ve Partizip II’yi (gekocht) doğru eklerle sıfat olarak kullanabilir ve anlamın etken mi edilgen mi olduğuna karar verebilirsin.',
    'Am Ende dieser Einheit benutzt du Partizipien als Adjektive.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'partizip-i', label: l('Partizip I (-end)', 'Partizip I (-end)', 'Partizip I') },
    { key: 'partizip-ii', label: l('Partizip II as adjective', 'Sıfat olarak Partizip II', 'Partizip II') },
    { key: 'aktiv-passiv', label: l('Active or passive?', 'Etken mi edilgen mi?', 'Aktiv oder passiv?') },
    { key: 'endungen', label: l('Adjective endings', 'Sıfat ekleri', 'Endungen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Verbs that become adjectives.', 'Sıfata dönüşen fiiller.', 'Verben als Adjektive.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Partizip I: active, at the same time', 'Partizip I: etken, eşzamanlı', 'Partizip I: aktiv, gleichzeitig'),
          body: l(
            'Infinitive + d: lachen → lachend, warten → wartend. The noun does the action right now: das lachende Kind = das Kind, das lacht. Before a noun it takes the normal adjective ending.',
            'Mastar + d: lachen → lachend, warten → wartend. İsim eylemi şu anda yapıyor: das lachende Kind = das Kind, das lacht. İsimden önce normal sıfat ekini alır.',
            'Infinitiv + d.'
          ),
          examples: [
            { de: 'die **wartenden** Fahrgäste', translation: l('the waiting passengers', 'bekleyen yolcular', '') },
            { de: 'ein **spannender** Film', translation: l('an exciting film', 'heyecanlı bir film', '') },
          ],
        },
        {
          title: l('Partizip II: passive or finished', 'Partizip II: edilgen ya da bitmiş', 'Partizip II: passiv / abgeschlossen'),
          body: l(
            'The action has been done to the noun: das gekochte Ei = das Ei, das gekocht wurde. With intransitive verbs it means finished: der gestern angekommene Gast.',
            'Eylem isme yapılmış: das gekochte Ei = das Ei, das gekocht wurde. Geçişsiz fiillerde bitmiş anlamı verir: der gestern angekommene Gast.',
            'gekocht = wurde gekocht.'
          ),
          table: {
            head: [l('Relative clause', 'İlgi cümlesi', 'Relativsatz'), l('Participle', 'Ortaç', 'Partizip')],
            rows: [
              ['das Kind, das schläft', 'das schlafende Kind'],
              ['das Ei, das gekocht wurde', 'das gekochte Ei'],
              ['die Preise, die steigen', 'die steigenden Preise'],
              ['das Rad, das gestohlen wurde', 'das gestohlene Rad'],
            ],
          },
        },
        {
          title: l('Careful with pairs', 'Çiftlere dikkat', 'Achtung bei Paaren'),
          body: l(
            'spannend (the film is exciting) vs gespannt (I am curious). überraschend (surprising) vs überrascht (surprised). The -end form describes what causes the feeling.',
            'spannend (film heyecanlı) ile gespannt (ben meraklıyım). überraschend (şaşırtıcı) ile überrascht (şaşırmış). -end biçimi duyguya neyin sebep olduğunu anlatır.',
            'spannend ≠ gespannt.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two neighbours chat in the stairwell.', 'İki komşu merdivende sohbet ediyor.', 'Im Treppenhaus.'),
      dialogue: [
        { speaker: 'Frau Kaya', de: 'Haben Sie gehört? In der Nacht wurde ein **geparktes** Auto aufgebrochen.', translation: l('Did you hear? A parked car was broken into last night.', 'Duydunuz mu? Gece park halindeki bir araba soyulmuş.', '') },
        { speaker: 'Herr Lenz', de: 'Ja, und mein Fahrrad ist auch weg. Die Polizei sucht jetzt das **gestohlene** Rad.', translation: l('Yes, and my bike is gone too. The police are now looking for the stolen bike.', 'Evet, benim bisikletim de yok. Polis şimdi çalınan bisikleti arıyor.', '') },
        { speaker: 'Frau Kaya', de: 'Oh nein! Die **steigenden** Diebstahlzahlen machen mir Sorgen.', translation: l('Oh no! The rising theft figures worry me.', 'Olamaz! Artan hırsızlık sayıları beni endişelendiriyor.', '') },
        { speaker: 'Herr Lenz', de: 'Mir auch. Ab jetzt kommt mein Rad in den **abgeschlossenen** Keller.', translation: l('Me too. From now on my bike goes in the locked cellar.', 'Beni de. Bundan sonra bisikletim kilitli bodruma.', '') },
        { speaker: 'Frau Kaya', de: 'Gute Idee. Und in der **kommenden** Woche fragen wir den Vermieter nach einer Kamera.', translation: l('Good idea. And next week we’ll ask the landlord about a camera.', 'İyi fikir. Gelecek hafta da ev sahibine kamera soralım.', '') },
        { speaker: 'Herr Lenz', de: 'Ein **überzeugender** Vorschlag!', translation: l('A convincing suggestion!', 'İkna edici bir öneri!', '') },
      ],
      examples: [
        { de: 'das **lachende** Kind', translation: l('the laughing child', 'gülen çocuk', '') },
        { de: 'das **gekochte** Ei', translation: l('the boiled egg', 'haşlanmış yumurta', '') },
        { de: 'die **steigenden** Preise', translation: l('the rising prices', 'artan fiyatlar', '') },
        { de: 'ein **gebrauchtes** Handy', translation: l('a used phone', 'ikinci el bir telefon', '') },
        { de: 'Sie spricht **fließend** Deutsch.', translation: l('She speaks German fluently.', 'Akıcı Almanca konuşuyor.', '') },
        { de: 'ein **spannender** Krimi', translation: l('an exciting crime novel', 'heyecanlı bir polisiye', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Partizip I or II – active or passive?', 'Partizip I mi II mi – etken mi edilgen mi?', 'Partizip I oder II?'),
      exercises: ['match-partizip', 'sort-p1-p2', 'part-schlafen', 'part-reparieren', 'part-wachsen', 'mc-endung', 'tf-aktiv', 'select-p1', 'image-brennend'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Shorten sentences with participles.', 'Cümleleri ortaçlarla kısalt.', 'Kürzer mit Partizipien.'),
      exercises: [
        'fill-steigenden',
        'fill-gestohlene',
        'fill-fliessend',
        'build-partizip1',
        'build-partizip2',
        'build-kommend',
        'fix-endung',
        'fix-p1-p2',
        'fix-spannend',
        'tr-schlafend',
        'tr-repariert',
        'ordering-zeitung',
        'dialog-gespannt',
        'dialog-gebraucht',
        'part-schreiben',
        'part-weinen',
        'part-verkaufen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A classified ad.', 'Bir küçük ilan.', 'Eine Kleinanzeige.'),
      passage: [
        '**Gebrauchtes Lastenrad zu verkaufen**',
        'Zwei Jahre altes, regelmäßig **gewartetes** E-Lastenrad. Frisch **gewartet**, neue Bremsen, **geladener** Ersatzakku inklusive.',
        'Platz für zwei **mitfahrende** Kinder, mit **abnehmbarem** Regenverdeck.',
        'Wegen eines **bevorstehenden** Umzugs nach Hamburg leider abzugeben. Preis: 1.800 € (verhandelbar).',
      ],
      glossary: [
        { de: 'das Lastenrad', note: l('cargo bike', 'yük bisikleti', 'Fahrrad mit Kiste') },
        { de: 'warten (ein Gerät)', note: l('to service', 'bakımını yapmak', 'kontrollieren und reparieren') },
        { de: 'bevorstehend', note: l('upcoming', 'yaklaşan', 'kommt bald') },
        { de: 'verhandelbar', note: l('negotiable', 'pazarlığa açık', 'man kann den Preis besprechen') },
      ],
      exercises: ['read-was', 'read-zustand', 'read-kinder', 'read-grund'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Participles in everyday announcements.', 'Günlük anonslarda ortaçlar.', 'Partizipien im Alltag.'),
      exercises: ['listen-verspaetet', 'listen-preise', 'listen-fundbuero', 'listen-sprechend'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe a busy place (station, market, café) with participles.', 'Kalabalık bir yeri (istasyon, pazar, kafe) ortaçlarla anlat.', 'Beschreib einen belebten Ort.'),
      points: [
        l('Two Partizip I phrases: die wartenden Leute …', 'İki Partizip I ifadesi: die wartenden Leute …', 'Partizip I'),
        l('Two Partizip II phrases: frisch gebackenes Brot …', 'İki Partizip II ifadesi: frisch gebackenes Brot …', 'Partizip II'),
        l('One adverb: fließend, lächelnd …', 'Bir zarf: fließend, lächelnd …', 'Adverb'),
        l('How you feel there.', 'Orada kendini nasıl hissettiğin.', 'Gefühl'),
      ],
      model: [
        'Auf dem Wochenmarkt sieht man viele einkaufende Familien.',
        'Es riecht nach frisch gebackenem Brot und gegrilltem Gemüse.',
        'Ein lächelnder Verkäufer bietet mir ein Stück Käse an.',
        'Die spielenden Kinder und die singenden Straßenmusiker machen gute Laune.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a classified ad (at least 5 sentences) for something you want to sell. Use participles to describe it.',
        'Satmak istediğin bir şey için küçük ilan yaz (en az 5 cümle). Tanımlamak için ortaçlar kullan.',
        'Schreib eine Kleinanzeige (mindestens 5 Sätze) mit Partizipien.'
      ),
      minSentences: 5,
      checks: [
        { label: l('A Partizip I (-end + ending)', 'Bir Partizip I (-end + ek)', 'Partizip I'), pattern: '\\p{Ll}+end(e|er|es|en|em)?\\b' },
        { label: l('A Partizip II used as an adjective', 'Sıfat olarak bir Partizip II', 'Partizip II'), pattern: '\\b\\p{Ll}*(ge|er|be|ver|zer|ent)\\p{Ll}+(t|en)(e|er|es|en|em)\\b' },
        { label: l('A price or condition', 'Bir fiyat ya da durum', 'Preis / Zustand'), pattern: '(€|Euro|Zustand|Preis|neu)' },
      ],
      model: [
        'Ich verkaufe meinen gut erhaltenen Schreibtisch aus Holz.',
        'Er hat eine ausziehbare Platte und zwei abschließbare Schubladen.',
        'Der Tisch steht in einem nicht rauchenden Haushalt.',
        'Wegen meines bevorstehenden Umzugs muss er schnell weg.',
        'Preis: 80 Euro, nur an Selbstabholer.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Choose the right participle – 60 seconds.', 'Doğru ortacı seç – 60 saniye.', 'Partizip wählen – 60 Sekunden.'),
      seconds: 60,
      pool: [...PART.map(([id]) => `part-${id}`), 'mc-endung'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Partizip I = infinitive + d: lachend, wartend, steigend', 'Partizip I = mastar + d: lachend, wartend, steigend', 'Partizip I'),
      l('Partizip II as adjective: gekocht, gestohlen, gebraucht', 'Sıfat olarak Partizip II: gekocht, gestohlen, gebraucht', 'Partizip II'),
      l('Active/now (I) vs passive/finished (II)', 'Etken/şimdi (I) ile edilgen/bitmiş (II)', 'Aktiv vs. passiv'),
      l('Normal adjective endings before nouns', 'İsimden önce normal sıfat ekleri', 'Endungen'),
    ],
    mistakes: [
      { wrong: 'ein überzeugend Vortrag', right: 'ein überzeugender Vortrag', note: l('Ending needed.', 'Ek gerekli.', 'Endung.') },
      { wrong: 'ein gebrauchendes Fahrrad', right: 'ein gebrauchtes Fahrrad', note: l('Passive → Partizip II.', 'Edilgen → Partizip II.', 'Partizip II.') },
      { wrong: 'ein gespannter Film', right: 'ein spannender Film', note: l('spannend ≠ gespannt.', 'spannend ≠ gespannt.', 'spannend.') },
      { wrong: 'das gelesene Buch (= das Buch liest)', right: 'das lesende Kind / das gelesene Buch', note: l('Who does what?', 'Kim ne yapıyor?', 'Wer tut was?') },
    ],
  },
}
