import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'als ob', emoji: '🎭', translation: l('as if', 'sanki', 'irrealer Vergleich'), example: 'Er tut so, als ob er alles wüsste.' },
  { word: 'als wenn', emoji: '🎭', translation: l('as if', 'sanki', '= als ob'), example: 'Sie lacht, als wenn nichts passiert wäre.' },
  { word: 'als + Verb', emoji: '✂️', translation: l('as if (short form)', 'sanki (kısa biçim)', 'Verb direkt nach als'), example: 'Er sieht aus, als wäre er krank.' },
  { word: 'so tun, als ob', emoji: '🤥', translation: l('to pretend', '… gibi yapmak', 'nur spielen'), example: 'Tu nicht so, als ob du mich nicht kennst!' },
  { word: 'aussehen, als ob', emoji: '👀', translation: l('to look as if', '… gibi görünmek', 'Eindruck vom Aussehen'), example: 'Es sieht aus, als ob es gleich regnet.' },
  { word: 'sich anfühlen, als ob', emoji: '🤲', translation: l('to feel as if', '… gibi hissettirmek', 'Gefühl'), example: 'Es fühlt sich an, als ob ich zu Hause wäre.' },
  { word: 'klingen, als ob', emoji: '👂', translation: l('to sound as if', '… gibi duyulmak', 'Eindruck vom Hören'), example: 'Das klingt, als ob er sauer wäre.' },
  { word: 'der Eindruck', emoji: '💡', translation: l('impression', 'izlenim', 'was man denkt'), example: 'Ich habe den Eindruck, als ob sie traurig wäre.' },
  { word: 'irreal', emoji: '🌫️', translation: l('unreal', 'gerçek dışı', 'nicht wirklich'), example: 'Der Vergleich ist irreal – er weiß es nicht.' },
  { word: 'angeben', emoji: '🦚', translation: l('to show off', 'hava atmak', 'prahlen'), example: 'Er gibt an, als hätte er die Firma gegründet.' },
  { word: 'verhalten (sich)', emoji: '🧍', translation: l('to behave', 'davranmak', 'sich benehmen'), example: 'Sie verhält sich, als wäre sie die Chefin.' },
  { word: 'die Wirklichkeit', emoji: '🧭', translation: l('reality', 'gerçeklik', 'wie es wirklich ist'), example: 'In Wirklichkeit hat er keine Ahnung.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Eindruck', gender: 'm', plural: 'die Eindrücke', translation: l('impression', 'izlenim', 'Eindruck') },
  { word: 'Vergleich', gender: 'm', plural: 'die Vergleiche', translation: l('comparison', 'karşılaştırma', 'Vergleich') },
  { word: 'Wirklichkeit', gender: 'f', translation: l('reality', 'gerçeklik', 'Wirklichkeit') },
  { word: 'Ahnung', gender: 'f', plural: 'die Ahnungen', translation: l('idea, clue', 'fikir', 'Ahnung') },
  { word: 'Gespenst', gender: 'n', plural: 'die Gespenster', translation: l('ghost', 'hayalet', 'Gespenst') },
  { word: 'Verhalten', gender: 'n', translation: l('behaviour', 'davranış', 'Verhalten') },
  { word: 'Schauspieler', gender: 'm', plural: 'die Schauspieler', translation: l('actor', 'oyuncu', 'Schauspieler') },
  { word: 'Traum', gender: 'm', plural: 'die Träume', translation: l('dream', 'rüya', 'Traum') },
]

/** [id, sentence with gap, right, wrong] */
const ALS: [string, string, string, [string, string]][] = [
  ['wuesste', 'Er tut so, als ob er alles ___. (wissen)', 'wüsste', ['wusste', 'wissen']],
  ['waere', 'Sie sieht aus, als ___ sie krank.', 'wäre', ['war', 'sein']],
  ['gewesen', 'Er erzählt davon, als ob er selbst dabei gewesen ___.', 'wäre', ['hätte', 'würde']],
  ['geschlafen', 'Du siehst aus, als ob du nicht geschlafen ___.', 'hättest', ['wärst', 'würdest']],
  ['ob', 'Es fühlt sich an, als ___ ich wieder zu Hause wäre.', 'ob', ['dass', 'wie']],
  ['koennte', 'Sie redet, als ___ sie perfekt Chinesisch.', 'könnte', ['kann', 'konnte']],
]

function alsDrills(): Exercise[] {
  return ALS.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `als-${id}`,
      type: 'multiple_choice' as const,
      topic: 'formen',
      concept: 'k2-form',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'als ob / als wenn + Konjunktiv II, verb at the end. Short form: als + Konjunktiv II directly. Past: hätte / wäre + participle.',
        'als ob / als wenn + Konjunktiv II, fiil sonda. Kısa biçim: als + doğrudan Konjunktiv II. Geçmiş: hätte / wäre + ortaç.',
        `→ ${right}`
      ),
      examples: [sentence.replace(/ \(.*\)$/, '').replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-verben',
    type: 'matching',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the verb and the sense.', 'Fiili duyuyla eşleştir.', 'Verb und Sinn.'),
    pairs: [
      { left: 'aussehen, als ob', right: '👀 sehen' },
      { left: 'klingen, als ob', right: '👂 hören' },
      { left: 'sich anfühlen, als ob', right: '🤲 fühlen' },
      { left: 'riechen, als ob', right: '👃 riechen' },
      { left: 'so tun, als ob', right: '🎭 spielen' },
    ],
    explanation: l('Typical verbs before als ob.', 'als ob’tan önce gelen tipik fiiller.', 'Verben + als ob.'),
  },
  {
    id: 'sort-wortstellung',
    type: 'categorize',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('Long form (als ob) or short form (als + verb)?', 'Uzun biçim (als ob) mi kısa biçim (als + fiil) mi?', 'Lang oder kurz?'),
    categories: ['als ob … Verb am Ende', 'als + Verb direkt'],
    items: [
      { text: '…, als ob er müde wäre.', category: 0 },
      { text: '…, als wäre er müde.', category: 1 },
      { text: '…, als ob sie nichts gehört hätte.', category: 0 },
      { text: '…, als hätte sie nichts gehört.', category: 1 },
      { text: '…, als wenn es Sommer wäre.', category: 0 },
      { text: '…, als wäre es Sommer.', category: 1 },
    ],
    explanation: l('Both mean the same. In the short form the verb follows als directly.', 'İkisi de aynı anlama gelir. Kısa biçimde fiil doğrudan als’tan sonra gelir.', 'lang / kurz.'),
    practice: ['als-wuesste'],
  },
  {
    id: 'mc-irreal',
    type: 'multiple_choice',
    topic: 'bedeutung',
    concept: 'unreal',
    skill: 'reading',
    difficulty: 2,
    prompt: '„Er tut so, als ob er krank wäre.“ – Ist er krank?',
    options: ['Nein, wahrscheinlich nicht.', 'Ja, sicher.', 'Er war früher krank.'],
    answer: 0,
    explanation: l('als ob + Konjunktiv II = unreal / only appearance.', 'als ob + Konjunktiv II = gerçek dışı / sadece görünüş.', 'irreal.'),
    practice: ['fill-haette'],
  },
  {
    id: 'tf-umgang',
    type: 'true_false',
    topic: 'bedeutung',
    concept: 'register',
    skill: 'grammar',
    difficulty: 2,
    statement: 'In der Umgangssprache hört man auch „als ob“ mit Indikativ: „Es sieht aus, als ob es regnet.“',
    answer: true,
    explanation: l('Colloquially yes – when it is a real possibility. In writing Konjunktiv II is better.', 'Konuşma dilinde evet – gerçek bir olasılıksa. Yazıda Konjunktiv II daha iyidir.', 'Umgangssprache.'),
  },
  {
    id: 'select-korrekt',
    type: 'multiple_select',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche sind korrekt?'),
    options: ['Er tut, als ob er schliefe.', 'Er tut, als schliefe er.', 'Er tut, als ob schliefe er.', 'Er tut, als würde er schlafen.', 'Er tut, als er würde schlafen.'],
    answers: [0, 1, 3],
    explanation: l('als ob … verb at the end; als + verb + subject; würde + infinitive is also possible.', 'als ob … fiil sonda; als + fiil + özne; würde + mastar da mümkün.', 'Wortstellung.'),
  },
  {
    id: 'image-gespenst',
    type: 'image_choice',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Du bist so blass – du siehst aus, als hättest du ein Gespenst gesehen!',
    options: [
      { emoji: '👻', label: 'Gespenst' },
      { emoji: '🎂', label: 'Kuchen' },
      { emoji: '🚗', label: 'Auto' },
      { emoji: '🌞', label: 'Sonne' },
    ],
    answer: 0,
    explanation: l('Idiom: aussehen, als hätte man ein Gespenst gesehen = look very shocked.', 'Deyim: hayalet görmüş gibi görünmek = çok şaşkın görünmek.', 'Redewendung.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-haette',
    type: 'fill_blank',
    topic: 'formen',
    concept: 'k2-past',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Sie lächelt, als ob nichts passiert ___.',
    accepted: ['wäre'],
    base: 'passieren → ist passiert',
    explanation: l('Past: wäre + participle (passieren → sein).', 'Geçmiş: wäre + ortaç (passieren → sein).', 'wäre.'),
    examples: ['Sie lächelt, als ob nichts passiert **wäre**.'],
  },
  {
    id: 'fill-ob',
    type: 'fill_blank',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das klingt, als ___ du dich gar nicht freuen würdest.',
    accepted: ['ob', 'wenn'],
    base: 'als … (Verb am Ende)',
    explanation: l('Verb at the end → als ob / als wenn.', 'Fiil sonda → als ob / als wenn.', 'ob.'),
    examples: ['Das klingt, als **ob** du dich gar nicht freuen würdest.'],
  },
  {
    id: 'fill-waere',
    type: 'fill_blank',
    topic: 'formen',
    concept: 'k2-form',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Er gibt an, als ___ er der beste Fußballer der Welt.',
    accepted: ['wäre'],
    base: 'sein → Konjunktiv II',
    explanation: l('Short form: als + wäre.', 'Kısa biçim: als + wäre.', 'wäre.'),
    examples: ['Er gibt an, als **wäre** er der beste Fußballer der Welt.'],
  },
  {
    id: 'build-als-ob',
    type: 'sentence_builder',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'grammar',
    difficulty: 3,
    chips: ['als ob', 'Er tut so,', 'nichts gehört hätte', 'er'],
    answers: [['Er tut so,', 'als ob', 'er', 'nichts gehört hätte']],
    translation: l('He acts as if he hadn’t heard anything.', 'Hiçbir şey duymamış gibi davranıyor.', 'Er tut so, als ob er nichts gehört hätte.'),
    explanation: l('als ob … verb at the end.', 'als ob … fiil sonda.', '… gehört hätte.'),
    examples: ['Er tut so, **als ob** er nichts gehört **hätte**.'],
  },
  {
    id: 'build-kurz',
    type: 'sentence_builder',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'grammar',
    difficulty: 3,
    chips: ['als', 'Es ist so warm,', 'Juli', 'wäre es'],
    answers: [['Es ist so warm,', 'als', 'wäre es', 'Juli']],
    translation: l('It’s so warm, as if it were July.', 'O kadar sıcak ki sanki temmuz.', 'Es ist so warm, als wäre es Juli.'),
    explanation: l('Short form: als + verb + subject.', 'Kısa biçim: als + fiil + özne.', 'als wäre es.'),
    examples: ['Es ist so warm, **als wäre** es Juli.'],
  },
  {
    id: 'build-anfuehlen',
    type: 'sentence_builder',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'grammar',
    difficulty: 3,
    chips: ['Es fühlt sich an,', 'als ob', 'wir uns schon ewig kennen würden'],
    answers: [['Es fühlt sich an,', 'als ob', 'wir uns schon ewig kennen würden']],
    translation: l('It feels as if we had known each other forever.', 'Sanki birbirimizi ezelden beri tanıyormuşuz gibi.', 'Es fühlt sich an, als ob wir uns schon ewig kennen würden.'),
    explanation: l('sich anfühlen, als ob + würde + infinitive.', 'sich anfühlen, als ob + würde + mastar.', 'würden.'),
    examples: ['Es fühlt sich an, **als ob** wir uns schon ewig kennen **würden**.'],
  },
  {
    id: 'fix-ob-kurz',
    type: 'error_correction',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Sie tut so, als ob wäre sie die Chefin.',
    accepted: ['Sie tut so, als ob sie die Chefin wäre.', 'Sie tut so, als wäre sie die Chefin.'],
    explanation: l('Either als ob … wäre or als wäre … – not both.', 'Ya als ob … wäre ya da als wäre … – ikisi birden değil.', 'mischen nicht.'),
    examples: ['Sie tut so, **als wäre** sie die Chefin.'],
  },
  {
    id: 'fix-hat',
    type: 'error_correction',
    topic: 'formen',
    concept: 'k2-past',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Er redet, als ob er das Buch gelesen hat.',
    accepted: ['Er redet, als ob er das Buch gelesen hätte.', 'Er redet, als hätte er das Buch gelesen.'],
    explanation: l('Unreal → Konjunktiv II: hätte.', 'Gerçek dışı → Konjunktiv II: hätte.', 'hätte.'),
    examples: ['Er redet, als ob er das Buch gelesen **hätte**.'],
  },
  {
    id: 'fix-dass',
    type: 'error_correction',
    topic: 'bedeutung',
    concept: 'unreal',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Du siehst aus, als dass du müde wärst.',
    accepted: ['Du siehst aus, als ob du müde wärst.', 'Du siehst aus, als wärst du müde.', 'Du siehst aus, als wenn du müde wärst.'],
    explanation: l('als ob / als wenn – not als dass.', 'als ob / als wenn – als dass değil.', 'als ob.'),
    examples: ['Du siehst aus, **als ob** du müde wärst.'],
  },
  {
    id: 'tr-tun',
    type: 'translation',
    topic: 'bedeutung',
    concept: 'unreal',
    skill: 'writing',
    difficulty: 3,
    source: l('She acts as if she didn’t know me.', 'Beni tanımıyormuş gibi davranıyor.', 'She acts as if she didn’t know me.'),
    accepted: ['Sie tut so, als ob sie mich nicht kennen würde.', 'Sie tut so, als würde sie mich nicht kennen.', 'Sie tut so, als ob sie mich nicht kennte.', 'Sie tut so, als kennte sie mich nicht.', 'Sie tut so, als ob sie mich nicht kennt.'],
    explanation: l('so tun, als ob + Konjunktiv II.', 'so tun, als ob + Konjunktiv II.', 'als ob.'),
    examples: ['Sie tut so, **als ob** sie mich nicht kennen **würde**.'],
  },
  {
    id: 'tr-aussehen',
    type: 'translation',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'writing',
    difficulty: 3,
    source: l('You look as if you had seen a ghost.', 'Hayalet görmüş gibi görünüyorsun.', 'You look as if you had seen a ghost.'),
    accepted: ['Du siehst aus, als hättest du ein Gespenst gesehen.', 'Du siehst aus, als ob du ein Gespenst gesehen hättest.', 'Du siehst aus, als wenn du ein Gespenst gesehen hättest.'],
    explanation: l('Past unreal: hättest … gesehen.', 'Geçmiş gerçek dışı: hättest … gesehen.', 'hättest gesehen.'),
    examples: ['Du siehst aus, **als hättest** du ein Gespenst **gesehen**.'],
  },
  {
    id: 'ordering-geschichte',
    type: 'ordering',
    topic: 'bedeutung',
    concept: 'story',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the little story in order.', 'Küçük hikâyeyi sırala.', 'Ordne die Geschichte.'),
    items: ['Aber in Wirklichkeit hatte er nur einen kleinen Kratzer.', 'Mein Bruder fiel beim Fußball hin.', 'Er schrie, als hätte er sich das Bein gebrochen.', 'Fünf Minuten später spielte er weiter, als wäre nichts gewesen.'],
    answer: ['Mein Bruder fiel beim Fußball hin.', 'Er schrie, als hätte er sich das Bein gebrochen.', 'Aber in Wirklichkeit hatte er nur einen kleinen Kratzer.', 'Fünf Minuten später spielte er weiter, als wäre nichts gewesen.'],
    explanation: l('Event → (unreal) reaction → reality → ending.', 'Olay → (gerçek dışı) tepki → gerçek → son.', 'Geschichte.'),
  },
  {
    id: 'dialog-eindruck',
    type: 'dialogue',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Was ist denn mit Tom los?' }],
    options: ['Keine Ahnung, aber er sieht aus, als hätte er schlechte Nachrichten bekommen.', 'Tom ist als ob.', 'Er sieht aus, als ob er hat Nachrichten.'],
    answer: 0,
    explanation: l('Describe an impression with als + Konjunktiv II.', 'als + Konjunktiv II ile bir izlenimi anlat.', 'Eindruck.'),
  },
  {
    id: 'dialog-angeber',
    type: 'dialogue',
    topic: 'bedeutung',
    concept: 'unreal',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Freund', de: 'Der neue Kollege erzählt ständig von seinem Porsche.' }],
    options: ['Ja, er tut so, als wäre er reich – dabei fährt er jeden Tag mit dem Bus.', 'Er ist ein Porsche.', 'Als ob Porsche.'],
    answer: 0,
    explanation: l('Contrast appearance (als wäre) and reality (dabei …).', 'Görünüş (als wäre) ile gerçeği (dabei …) karşılaştır.', 'Schein vs. Sein.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-glosse',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Über wen schreibt der Autor?',
    options: ['Über seine Katze.', 'Über seinen Chef.', 'Über einen Schauspieler.'],
    answer: 0,
    explanation: l('„Meine Katze Mimi …“', '„Meine Katze Mimi …“', 'Katze.'),
  },
  {
    id: 'read-futter',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-glosse',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie benimmt sich Mimi morgens?',
    options: ['Als hätte sie seit Tagen nichts gegessen.', 'Als wäre sie sehr müde.', 'Als wäre sie ein Hund.'],
    answer: 0,
    explanation: l('„… miaut sie, als hätte sie seit Tagen nichts gegessen.“', '„… miaut sie, als hätte sie seit Tagen nichts gegessen.“', 'Hunger.'),
  },
  {
    id: 'read-wirklich',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-glosse',
    skill: 'reading',
    difficulty: 2,
    statement: 'In Wirklichkeit hat Mimi am Abend vorher gefressen.',
    answer: true,
    explanation: l('„Dabei hat sie am Abend vorher eine ganze Dose gefressen.“', '„Dabei hat sie am Abend vorher eine ganze Dose gefressen.“', 'richtig.'),
  },
  {
    id: 'read-chefin',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-glosse',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was denkt der Autor am Ende?',
    options: ['Mimi benimmt sich, als wäre sie die Chefin der Wohnung.', 'Er möchte eine zweite Katze.', 'Mimi ist sehr schüchtern.'],
    answer: 0,
    explanation: l('„Manchmal habe ich das Gefühl, als wäre ich nur ihr Angestellter.“', '„Manchmal habe ich das Gefühl, als wäre ich nur ihr Angestellter.“', 'Chefin.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-klingt',
    type: 'listening_choice',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'listening',
    difficulty: 2,
    audio: 'Deine Stimme klingt, als hättest du eine starke Erkältung.',
    question: l('What does the voice sound like?', 'Ses nasıl duyuluyor?', 'Wie klingt die Stimme?'),
    options: ['like a bad cold', 'very happy', 'very angry'],
    answer: 0,
    explanation: l('„als hättest du eine starke Erkältung“', '„als hättest du eine starke Erkältung“', 'Erkältung.'),
  },
  {
    id: 'listen-tun',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'unreal',
    skill: 'listening',
    difficulty: 2,
    audio: 'Mein Sohn tut immer so, als ob er schläft, wenn ich ins Zimmer komme. Aber das Handy leuchtet noch unter der Decke.',
    question: l('Is the son really sleeping?', 'Oğlan gerçekten uyuyor mu?', 'Schläft der Sohn wirklich?'),
    options: ['No, he is on his phone.', 'Yes, deeply.', 'He is reading a book.'],
    answer: 0,
    explanation: l('„Das Handy leuchtet noch“ → pretending.', '„Das Handy leuchtet noch“ → rol yapıyor.', 'so tun.'),
  },
  {
    id: 'listen-zuhause',
    type: 'listening_choice',
    topic: 'verben',
    concept: 'impression-verbs',
    skill: 'listening',
    difficulty: 2,
    audio: 'Bei meiner Gastfamilie fühlt es sich an, als wäre ich schon immer ein Teil der Familie gewesen.',
    question: l('How does the speaker feel?', 'Konuşan nasıl hissediyor?', 'Wie fühlt sich die Person?'),
    options: ['like part of the family', 'like a stranger', 'homesick'],
    answer: 0,
    explanation: l('„als wäre ich … ein Teil der Familie gewesen“', '„als wäre ich … ein Teil der Familie gewesen“', 'Teil der Familie.'),
  },
  {
    id: 'listen-wetter',
    type: 'listening_choice',
    topic: 'wortstellung',
    concept: 'long-short',
    skill: 'listening',
    difficulty: 2,
    audio: 'Heute ist es so kalt, als wäre schon Winter – dabei haben wir erst September.',
    question: l('What month is it?', 'Hangi aydayız?', 'Welcher Monat ist es?'),
    options: ['September', 'December', 'January'],
    answer: 0,
    explanation: l('„dabei haben wir erst September“', '„dabei haben wir erst September“', 'September.'),
  },

  ...alsDrills(),
]

export const UNIT_B2_11_ALS_OB: CourseUnit = {
  level: 'B2',
  number: 11,
  slug: 'als-ob',
  titleDe: 'Er tut so, als ob …',
  title: l('He acts as if …', 'Sanki … gibi davranıyor', 'Er tut so, als ob …'),
  goal: l(
    'By the end of this unit you can make unreal comparisons with als ob / als wenn and the short form als + verb, in the present and the past, and describe impressions (aussehen, klingen, sich anfühlen).',
    'Bu ünitenin sonunda als ob / als wenn ve kısa biçim als + fiil ile şimdiki ve geçmiş zamanda gerçek dışı karşılaştırmalar yapabilir ve izlenimleri anlatabilirsin (aussehen, klingen, sich anfühlen).',
    'Am Ende dieser Einheit bildest du irreale Vergleichssätze.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'bedeutung', label: l('Unreal comparisons', 'Gerçek dışı karşılaştırmalar', 'Bedeutung') },
    { key: 'formen', label: l('Konjunktiv II forms', 'Konjunktiv II biçimleri', 'Formen') },
    { key: 'wortstellung', label: l('als ob vs als + verb', 'als ob ve als + fiil', 'Wortstellung') },
    { key: 'verben', label: l('Impression verbs', 'İzlenim fiilleri', 'Verben') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Appearance and reality.', 'Görünüş ve gerçek.', 'Schein und Sein.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('als ob / als wenn + Konjunktiv II', 'als ob / als wenn + Konjunktiv II', 'als ob + Konjunktiv II'),
          body: l(
            'An unreal comparison: it seems like this, but it is (probably) not true. The verb goes to the end and is in Konjunktiv II: Er tut so, als ob er alles wüsste. Often with würde + infinitive: als ob er alles wissen würde.',
            'Gerçek dışı karşılaştırma: öyle görünüyor ama (muhtemelen) doğru değil. Fiil sona gider ve Konjunktiv II’dedir: Er tut so, als ob er alles wüsste. Sıklıkla würde + mastar ile: als ob er alles wissen würde.',
            'irreal → Konjunktiv II.'
          ),
          examples: [
            { de: 'Er tut so, **als ob** er krank **wäre**.', translation: l('He acts as if he were ill.', 'Hastaymış gibi davranıyor.', '') },
            { de: 'Sie lacht, **als wenn** nichts passiert **wäre**.', translation: l('She laughs as if nothing had happened.', 'Hiçbir şey olmamış gibi gülüyor.', '') },
          ],
        },
        {
          title: l('Short form: als + verb', 'Kısa biçim: als + fiil', 'Kurzform: als + Verb'),
          body: l(
            'Instead of „als ob“ you can put the verb directly after „als“: als ob er müde wäre → als wäre er müde. The meaning is the same; the short form is more elegant in writing.',
            '„als ob“ yerine fiili doğrudan „als“tan sonra koyabilirsin: als ob er müde wäre → als wäre er müde. Anlam aynı; kısa biçim yazıda daha zariftir.',
            'als wäre er müde.'
          ),
          table: {
            head: [l('Long form', 'Uzun biçim', 'Langform'), l('Short form', 'Kısa biçim', 'Kurzform')],
            rows: [
              ['als ob er müde wäre', 'als wäre er müde'],
              ['als ob sie es wüsste', 'als wüsste sie es'],
              ['als ob er gelaufen wäre', 'als wäre er gelaufen'],
              ['als ob sie geweint hätte', 'als hätte sie geweint'],
            ],
          },
        },
        {
          title: l('Present and past', 'Şimdiki ve geçmiş zaman', 'Gegenwart und Vergangenheit'),
          body: l(
            'Same time: wäre, hätte, würde + infinitive. Earlier: hätte / wäre + participle: Du siehst aus, als hättest du nicht geschlafen. Typical verbs: aussehen, klingen, sich anfühlen, so tun, sich verhalten.',
            'Aynı zaman: wäre, hätte, würde + mastar. Daha önce: hätte / wäre + ortaç: Du siehst aus, als hättest du nicht geschlafen. Tipik fiiller: aussehen, klingen, sich anfühlen, so tun, sich verhalten.',
            'hätte / wäre + Partizip II.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two flatmates in the kitchen in the morning.', 'İki ev arkadaşı sabah mutfakta.', 'Morgens in der WG-Küche.'),
      dialogue: [
        { speaker: 'Nina', de: 'Guten Morgen! Oh je, du siehst aus, **als hättest** du die ganze Nacht nicht **geschlafen**.', translation: l('Good morning! Oh dear, you look as if you hadn’t slept all night.', 'Günaydın! Eyvah, bütün gece uyumamış gibi görünüyorsun.', '') },
        { speaker: 'Ali', de: 'Hab ich auch nicht. Die Nachbarn haben gefeiert, **als ob** morgen Silvester **wäre**.', translation: l('I didn’t. The neighbours partied as if it were New Year’s Eve tomorrow.', 'Uyumadım zaten. Komşular sanki yarın yılbaşıymış gibi parti yaptı.', '') },
        { speaker: 'Nina', de: 'Und heute früh tun sie bestimmt so, **als wäre** nichts **gewesen**.', translation: l('And this morning they’ll surely act as if nothing had happened.', 'Bu sabah da kesin hiçbir şey olmamış gibi davranırlar.', '') },
        { speaker: 'Ali', de: 'Genau. Gestern im Treppenhaus hat der Mann gegrüßt, **als ob** wir beste Freunde **wären**.', translation: l('Exactly. Yesterday in the stairwell the man greeted me as if we were best friends.', 'Aynen. Dün merdivende adam sanki en iyi arkadaşlarmışız gibi selam verdi.', '') },
        { speaker: 'Nina', de: 'Hier, trink einen Kaffee. Danach fühlt es sich an, **als wärst** du ein neuer Mensch.', translation: l('Here, have a coffee. Afterwards you’ll feel like a new person.', 'Al, bir kahve iç. Sonra yeni bir insan olmuşsun gibi hissedeceksin.', '') },
        { speaker: 'Ali', de: 'Du redest, **als ob** Kaffee alle Probleme lösen **könnte**. – Aber danke!', translation: l('You talk as if coffee could solve all problems. – But thanks!', 'Sanki kahve bütün sorunları çözebilirmiş gibi konuşuyorsun. – Ama teşekkürler!', '') },
      ],
      examples: [
        { de: 'Er tut so, **als ob** er alles **wüsste**.', translation: l('He acts as if he knew everything.', 'Her şeyi biliyormuş gibi davranıyor.', '') },
        { de: 'Sie sieht aus, **als wäre** sie krank.', translation: l('She looks as if she were ill.', 'Hastaymış gibi görünüyor.', '') },
        { de: 'Das klingt, **als ob** er sauer **wäre**.', translation: l('That sounds as if he were angry.', 'Kızgınmış gibi duyuluyor.', '') },
        { de: 'Du siehst aus, **als hättest** du nicht **geschlafen**.', translation: l('You look as if you hadn’t slept.', 'Uyumamış gibi görünüyorsun.', '') },
        { de: 'Es fühlt sich an, **als ob** ich zu Hause **wäre**.', translation: l('It feels as if I were at home.', 'Evdeymişim gibi hissettiriyor.', '') },
        { de: 'Er gibt an, **als wäre** er Millionär.', translation: l('He shows off as if he were a millionaire.', 'Milyonermiş gibi hava atıyor.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Long form, short form, real or unreal?', 'Uzun biçim, kısa biçim, gerçek mi değil mi?', 'Lang, kurz, irreal?'),
      exercises: ['match-verben', 'sort-wortstellung', 'als-wuesste', 'als-waere', 'als-gewesen', 'mc-irreal', 'tf-umgang', 'select-korrekt', 'image-gespenst'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Describe appearances and pretending.', 'Görünüşleri ve rol yapmayı anlat.', 'Schein beschreiben.'),
      exercises: [
        'fill-haette',
        'fill-ob',
        'fill-waere',
        'build-als-ob',
        'build-kurz',
        'build-anfuehlen',
        'fix-ob-kurz',
        'fix-hat',
        'fix-dass',
        'tr-tun',
        'tr-aussehen',
        'ordering-geschichte',
        'dialog-eindruck',
        'dialog-angeber',
        'als-geschlafen',
        'als-ob',
        'als-koennte',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A humorous column about a cat.', 'Bir kedi hakkında mizahi bir köşe yazısı.', 'Eine Glosse.'),
      passage: [
        '**Die Chefin im Haus** – Meine Katze Mimi ist erst zwei Jahre alt, aber sie benimmt sich, **als gehörte** ihr die ganze Wohnung.',
        'Jeden Morgen um fünf miaut sie, **als hätte** sie seit Tagen nichts **gegessen**. Dabei hat sie am Abend vorher eine ganze Dose gefressen.',
        'Wenn ich am Computer arbeite, legt sie sich auf die Tastatur und schaut mich an, **als ob** ich etwas Verbotenes **täte**.',
        'Manchmal habe ich das Gefühl, **als wäre** ich nur ihr Angestellter. Aber wenn sie abends schnurrt, verzeihe ich ihr alles.',
      ],
      glossary: [
        { de: 'sich benehmen', note: l('to behave', 'davranmak', 'sich verhalten') },
        { de: 'fressen', note: l('to eat (animals)', 'yemek (hayvan)', 'essen (Tier)') },
        { de: 'schnurren', note: l('to purr', 'mırlamak', 'Katzengeräusch') },
        { de: 'verzeihen', note: l('to forgive', 'affetmek', 'nicht mehr böse sein') },
      ],
      exercises: ['read-thema', 'read-futter', 'read-wirklich', 'read-chefin'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Impressions and pretending.', 'İzlenimler ve rol yapma.', 'Eindrücke.'),
      exercises: ['listen-klingt', 'listen-tun', 'listen-zuhause', 'listen-wetter'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe a person you know who likes to pretend or show off – with als ob.', 'Rol yapmayı ya da hava atmayı seven tanıdığın birini als ob ile anlat.', 'Beschreibe einen Angeber.'),
      points: [
        l('What does the person pretend? „Er tut so, als ob …“', 'Kişi ne gibi davranıyor? „Er tut so, als ob …“', 'so tun'),
        l('How does he/she look or sound? „Er sieht aus / klingt, als …“', 'Nasıl görünüyor ya da duyuluyor? „Er sieht aus / klingt, als …“', 'Eindruck'),
        l('Use one past form: als hätte / wäre … + participle', 'Bir geçmiş biçim kullan: als hätte / wäre … + ortaç', 'Vergangenheit'),
        l('What is the reality? „In Wirklichkeit …“', 'Gerçek ne? „In Wirklichkeit …“', 'Wirklichkeit'),
      ],
      model: [
        'Mein Cousin tut immer so, als ob er ein Experte für alles wäre.',
        'Wenn er über Autos spricht, klingt er, als hätte er selbst Formel 1 gefahren.',
        'Er redet über Politik, als wäre er Minister.',
        'In Wirklichkeit liest er nur die Schlagzeilen – aber er ist trotzdem lustig.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short funny text (at least 5 sentences) about a pet, a child or a colleague who behaves strangely. Use als ob and the short form.',
        'Garip davranan bir evcil hayvan, çocuk ya da iş arkadaşı hakkında kısa komik bir metin yaz (en az 5 cümle). als ob ve kısa biçimi kullan.',
        'Schreib eine lustige Glosse (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('als ob / als wenn', 'als ob / als wenn', 'als ob'), pattern: '\\bals (ob|wenn)\\b' },
        { label: l('Short form: als + Konjunktiv II', 'Kısa biçim: als + Konjunktiv II', 'als + Verb'), pattern: '\\bals (wäre|wären|wärst|hätte|hätten|hättest|würde|würden|könnte|wüsste)\\b' },
        { label: l('A past form (hätte / wäre … participle)', 'Bir geçmiş biçim (hätte / wäre … ortaç)', 'Vergangenheit'), pattern: '\\b(hätte|hätten|hättest|wäre|wären|wärst)\\b[^.!?]*\\b\\p{Ll}*(ge|be|er|ver)\\p{Ll}+(t|en)\\b' },
      ],
      model: [
        'Unser Hund Bello ist ein echter Schauspieler.',
        'Wenn ich nach Hause komme, springt er herum, als ob er mich ein Jahr nicht gesehen hätte.',
        'Beim Tierarzt tut er so, als wäre er schwer krank.',
        'Aber sobald er eine Wurst riecht, rennt er, als wäre nichts gewesen.',
        'Trotzdem ist er der beste Hund der Welt.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('als ob – the right form – 60 seconds.', 'als ob – doğru biçim – 60 saniye.', 'als ob – 60 Sekunden.'),
      seconds: 60,
      pool: [...ALS.map(([id]) => `als-${id}`), 'mc-irreal'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('als ob / als wenn + Konjunktiv II, verb at the end', 'als ob / als wenn + Konjunktiv II, fiil sonda', 'als ob'),
      l('Short form: als wäre er …, als hätte sie …', 'Kısa biçim: als wäre er …, als hätte sie …', 'Kurzform'),
      l('Past: als hätte / wäre … + participle', 'Geçmiş: als hätte / wäre … + ortaç', 'Vergangenheit'),
      l('Impression verbs: aussehen, klingen, sich anfühlen, so tun', 'İzlenim fiilleri: aussehen, klingen, sich anfühlen, so tun', 'Verben'),
    ],
    mistakes: [
      { wrong: 'als ob wäre sie die Chefin', right: 'als ob sie die Chefin wäre / als wäre sie die Chefin', note: l('Don’t mix forms.', 'Biçimleri karıştırma.', 'nicht mischen.') },
      { wrong: 'als ob er das Buch gelesen hat', right: 'als ob er das Buch gelesen hätte', note: l('Konjunktiv II.', 'Konjunktiv II.', 'hätte.') },
      { wrong: 'als dass du müde wärst', right: 'als ob du müde wärst', note: l('als ob, not als dass.', 'als ob, als dass değil.', 'als ob.') },
      { wrong: 'Er tut, als er würde schlafen.', right: 'Er tut, als würde er schlafen.', note: l('Verb right after als.', 'Fiil als’tan hemen sonra.', 'als würde er.') },
    ],
  },
}
