import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Er wird wohl krank sein.', emoji: '🤒', translation: l('He’s probably ill.', 'Muhtemelen hastadır.', 'Vermutung (jetzt)'), example: 'Er geht nicht ans Telefon – er wird wohl krank sein.' },
  { word: 'Sie wird es vergessen haben.', emoji: '🙄', translation: l('She will have forgotten it.', 'Unutmuş olsa gerek.', 'Vermutung (Vergangenheit)'), example: 'Sie ist nicht gekommen – sie wird den Termin vergessen haben.' },
  { word: 'Bis Freitag werde ich fertig sein.', emoji: '🏁', translation: l('I will be finished by Friday.', 'Cumaya kadar bitirmiş olacağım.', 'Zukunft'), example: 'Bis Freitag werde ich den Bericht geschrieben haben.' },
  { word: 'wohl', emoji: '🤔', translation: l('probably', 'herhalde', 'ich glaube'), example: 'Das wird wohl stimmen.' },
  { word: 'sicher', emoji: '✅', translation: l('surely', 'kesin', 'ich bin sicher'), example: 'Sie wird sicher bald kommen.' },
  { word: 'bestimmt', emoji: '💯', translation: l('definitely', 'mutlaka', 'sehr sicher'), example: 'Das wird bestimmt ein schöner Abend.' },
  { word: 'vermutlich', emoji: '🔮', translation: l('presumably', 'tahminen', 'wahrscheinlich'), example: 'Er wird vermutlich im Stau stehen.' },
  { word: 'wahrscheinlich', emoji: '📊', translation: l('probably', 'muhtemelen', 'ziemlich sicher'), example: 'Es wird wahrscheinlich regnen.' },
  { word: 'die Prognose', emoji: '📈', translation: l('forecast', 'tahmin, öngörü', 'Vorhersage'), example: 'Die Prognose für 2030 ist positiv.' },
  { word: 'bis dahin', emoji: '⏳', translation: l('by then', 'o zamana kadar', 'bis zu diesem Zeitpunkt'), example: 'Bis dahin werden wir umgezogen sein.' },
  { word: 'die Zukunft', emoji: '🚀', translation: l('future', 'gelecek', 'was kommt'), example: 'In Zukunft werden wir mehr von zu Hause arbeiten.' },
  { word: 'voraussichtlich', emoji: '🗓️', translation: l('expected (to)', 'tahminen, beklendiği üzere', 'wie geplant'), example: 'Der Zug kommt voraussichtlich um acht an.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Prognose', gender: 'f', plural: 'die Prognosen', translation: l('forecast', 'öngörü', 'Prognose') },
  { word: 'Zukunft', gender: 'f', translation: l('future', 'gelecek', 'Zukunft') },
  { word: 'Zeitpunkt', gender: 'm', plural: 'die Zeitpunkte', translation: l('point in time', 'zaman noktası', 'Zeitpunkt') },
  { word: 'Entwicklung', gender: 'f', plural: 'die Entwicklungen', translation: l('development', 'gelişme', 'Entwicklung') },
  { word: 'Vorhersage', gender: 'f', plural: 'die Vorhersagen', translation: l('prediction', 'tahmin', 'Vorhersage') },
  { word: 'Jahrzehnt', gender: 'n', plural: 'die Jahrzehnte', translation: l('decade', 'on yıl', 'Jahrzehnt') },
  { word: 'Roboter', gender: 'm', plural: 'die Roboter', translation: l('robot', 'robot', 'Roboter') },
  { word: 'Gesellschaft', gender: 'f', plural: 'die Gesellschaften', translation: l('society', 'toplum', 'Gesellschaft') },
]

/** [id, statement, right future form, wrong] */
const FUT: [string, string, string, [string, string]][] = [
  ['futur1', 'Er ist wohl zu Hause.', 'Er wird wohl zu Hause sein.', ['Er wird wohl zu Hause gewesen.', 'Er ist wohl zu Hause werden.']],
  ['futur2-haben', 'Sie hat den Bus wohl verpasst.', 'Sie wird den Bus wohl verpasst haben.', ['Sie wird den Bus wohl verpasst sein.', 'Sie hat den Bus wohl verpassen werden.']],
  ['futur2-sein', 'Er ist wohl schon gegangen.', 'Er wird wohl schon gegangen sein.', ['Er wird wohl schon gegangen haben.', 'Er ist wohl schon gehen geworden.']],
  ['fertig', 'Bis Montag beende ich das Projekt.', 'Bis Montag werde ich das Projekt beendet haben.', ['Bis Montag werde ich das Projekt beendet sein.', 'Bis Montag habe ich das Projekt beenden werden.']],
  ['verspaetung', 'Der Zug hat vermutlich Verspätung.', 'Der Zug wird vermutlich Verspätung haben.', ['Der Zug wird vermutlich Verspätung gehabt.', 'Der Zug hat vermutlich Verspätung werden.']],
  ['schlafen', 'Die Kinder schlafen wohl schon.', 'Die Kinder werden wohl schon schlafen.', ['Die Kinder wird wohl schon schlafen.', 'Die Kinder werden wohl schon geschlafen.']],
]

function futDrills(): Exercise[] {
  return FUT.map(([id, statement, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `fut-${id}`,
      type: 'multiple_choice' as const,
      topic: 'formen',
      concept: 'build-future',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: `„${statement}“ – mit werden:`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Futur I: werden + infinitive. Futur II: werden + participle + haben/sein. → ${right}`,
        `Futur I: werden + mastar. Futur II: werden + ortaç + haben/sein. → ${right}`,
        `→ ${right}`
      ),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-funktion',
    type: 'matching',
    topic: 'funktion',
    concept: 'uses',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('What does the sentence express?', 'Cümle neyi ifade ediyor?', 'Was drückt der Satz aus?'),
    pairs: [
      { left: 'Er wird wohl müde sein.', right: 'Vermutung über jetzt' },
      { left: 'Er wird wohl gut geschlafen haben.', right: 'Vermutung über die Vergangenheit' },
      { left: 'Morgen wird es schneien.', right: 'Prognose für die Zukunft' },
      { left: 'Bis Juni werde ich umgezogen sein.', right: 'abgeschlossen in der Zukunft' },
      { left: 'Du wirst jetzt sofort aufräumen!', right: 'Aufforderung' },
    ],
    explanation: l('werden has many functions – context and wohl/sicher help.', 'werden’in birçok işlevi vardır – bağlam ve wohl/sicher yardımcı olur.', 'Funktionen.'),
  },
  {
    id: 'sort-futur',
    type: 'categorize',
    topic: 'formen',
    concept: 'f1-f2',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('Futur I or Futur II?', 'Futur I mi Futur II mi?', 'Futur I oder II?'),
    categories: ['Futur I', 'Futur II'],
    items: [
      { text: 'Sie wird schlafen.', category: 0 },
      { text: 'Sie wird geschlafen haben.', category: 1 },
      { text: 'Wir werden umziehen.', category: 0 },
      { text: 'Wir werden umgezogen sein.', category: 1 },
      { text: 'Es wird regnen.', category: 0 },
      { text: 'Es wird geregnet haben.', category: 1 },
    ],
    explanation: l('Futur II = werden + Partizip II + haben/sein.', 'Futur II = werden + Partizip II + haben/sein.', 'Futur II.'),
    practice: ['fut-futur1'],
  },
  {
    id: 'mc-wohl',
    type: 'multiple_choice',
    topic: 'funktion',
    concept: 'assumption-now',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Es klingelt. – Das ___ wohl der Paketbote sein.',
    options: ['wird', 'wurde', 'würde'],
    answer: 0,
    explanation: l('Assumption about now: wird wohl + infinitive.', 'Şu anla ilgili tahmin: wird wohl + mastar.', 'wird wohl.'),
    examples: ['Das **wird** wohl der Paketbote **sein**.'],
    practice: ['fill-haben'],
  },
  {
    id: 'tf-praesens',
    type: 'true_false',
    topic: 'funktion',
    concept: 'present-for-future',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Für geplante Zukunft benutzt man im Deutschen oft einfach das Präsens: „Morgen fahre ich nach Wien.“',
    answer: true,
    explanation: l('With a time word the present tense is enough. Futur I sounds more like a prediction or promise.', 'Zaman kelimesiyle şimdiki zaman yeterlidir. Futur I daha çok tahmin ya da söz gibi durur.', 'Präsens + Zeitangabe.'),
  },
  {
    id: 'select-vergangenheit',
    type: 'multiple_select',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which sentences are assumptions about the past? Select all.', 'Hangi cümleler geçmişe dair tahmin? Hepsini seç.', 'Vermutungen über die Vergangenheit?'),
    options: ['Er wird den Schlüssel verloren haben.', 'Sie wird wohl schon abgefahren sein.', 'Er wird morgen kommen.', 'Das wird ein Missverständnis gewesen sein.', 'Ich werde Lehrerin.'],
    answers: [0, 1, 3],
    explanation: l('Futur II + context → assumption about the past.', 'Futur II + bağlam → geçmişe dair tahmin.', 'Futur II.'),
  },
  {
    id: 'image-prognose',
    type: 'image_choice',
    topic: 'funktion',
    concept: 'prediction',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Laut Wetterbericht wird es morgen den ganzen Tag regnen.',
    options: [
      { emoji: '🌧️', label: 'Regen' },
      { emoji: '☀️', label: 'Sonne' },
      { emoji: '❄️', label: 'Schnee' },
      { emoji: '🌈', label: 'Regenbogen' },
    ],
    answer: 0,
    explanation: l('Prediction with Futur I.', 'Futur I ile tahmin.', 'Prognose.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-haben',
    type: 'fill_blank',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Tom ist nicht gekommen. Er wird den Termin vergessen ___.',
    accepted: ['haben'],
    base: 'Futur II',
    explanation: l('vergessen → haben: wird … vergessen haben.', 'vergessen → haben: wird … vergessen haben.', 'haben.'),
    examples: ['Er wird den Termin vergessen **haben**.'],
  },
  {
    id: 'fill-sein',
    type: 'fill_blank',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das Licht ist aus. Sie werden schon ins Bett gegangen ___.',
    accepted: ['sein'],
    base: 'gehen → sein',
    explanation: l('Verbs of movement → sein: gegangen sein.', 'Hareket fiilleri → sein: gegangen sein.', 'sein.'),
    examples: ['Sie werden schon ins Bett gegangen **sein**.'],
  },
  {
    id: 'fill-werden',
    type: 'fill_blank',
    topic: 'funktion',
    concept: 'prediction',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Experten glauben, dass Roboter in Zukunft viele Jobs übernehmen ___.',
    accepted: ['werden'],
    base: 'Futur I, Plural',
    explanation: l('dass-clause: … übernehmen werden (verb at the end).', 'dass cümlesi: … übernehmen werden (fiil sonda).', 'werden.'),
    examples: ['…, dass Roboter viele Jobs übernehmen **werden**.'],
  },
  {
    id: 'build-futur2',
    type: 'sentence_builder',
    topic: 'formen',
    concept: 'f1-f2',
    skill: 'grammar',
    difficulty: 3,
    chips: ['abgeschlossen haben', 'werde ich', 'Bis Ende Juni', 'mein Studium'],
    answers: [['Bis Ende Juni', 'werde ich', 'mein Studium', 'abgeschlossen haben']],
    translation: l('By the end of June I will have finished my degree.', 'Haziran sonuna kadar üniversiteyi bitirmiş olacağım.', 'Bis Ende Juni werde ich mein Studium abgeschlossen haben.'),
    explanation: l('Completed in the future: Futur II.', 'Gelecekte tamamlanmış: Futur II.', 'Futur II.'),
    examples: ['Bis Ende Juni **werde** ich mein Studium **abgeschlossen haben**.'],
  },
  {
    id: 'build-wohl',
    type: 'sentence_builder',
    topic: 'funktion',
    concept: 'assumption-now',
    skill: 'grammar',
    difficulty: 2,
    chips: ['im Stau stehen', 'Sie wird', 'wohl', 'noch'],
    answers: [['Sie wird', 'wohl', 'noch', 'im Stau stehen'], ['Sie wird', 'noch', 'wohl', 'im Stau stehen']],
    translation: l('She is probably still stuck in traffic.', 'Muhtemelen hâlâ trafikte.', 'Sie wird wohl noch im Stau stehen.'),
    explanation: l('wird wohl + infinitive at the end.', 'wird wohl + sonda mastar.', 'wird … stehen.'),
    examples: ['Sie **wird** wohl noch im Stau **stehen**.'],
  },
  {
    id: 'build-dass',
    type: 'sentence_builder',
    topic: 'funktion',
    concept: 'prediction',
    skill: 'grammar',
    difficulty: 3,
    chips: ['dass', 'Ich bin sicher,', 'du', 'die Prüfung bestehen wirst'],
    answers: [['Ich bin sicher,', 'dass', 'du', 'die Prüfung bestehen wirst']],
    translation: l('I’m sure you will pass the exam.', 'Sınavı geçeceğinden eminim.', 'Ich bin sicher, dass du die Prüfung bestehen wirst.'),
    explanation: l('In a dass-clause werden comes last.', 'dass cümlesinde werden en sona gelir.', '… bestehen wirst.'),
    examples: ['…, dass du die Prüfung bestehen **wirst**.'],
  },
  {
    id: 'fix-hat',
    type: 'error_correction',
    topic: 'formen',
    concept: 'f1-f2',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Er wird den Brief schon gelesen hat.',
    accepted: ['Er wird den Brief schon gelesen haben.'],
    explanation: l('Futur II: infinitive haben at the end.', 'Futur II: sonda mastar haben.', 'haben.'),
    examples: ['Er wird den Brief schon gelesen **haben**.'],
  },
  {
    id: 'fix-sein-haben',
    type: 'error_correction',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Zug wird schon abgefahren haben.',
    accepted: ['Der Zug wird schon abgefahren sein.'],
    explanation: l('abfahren → ist abgefahren → abgefahren sein.', 'abfahren → ist abgefahren → abgefahren sein.', 'sein.'),
    examples: ['Der Zug wird schon abgefahren **sein**.'],
  },
  {
    id: 'fix-wird',
    type: 'error_correction',
    topic: 'formen',
    concept: 'conjugation',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wir wird nächstes Jahr nach Kanada ziehen.',
    accepted: ['Wir werden nächstes Jahr nach Kanada ziehen.'],
    explanation: l('wir werden.', 'wir werden.', 'werden.'),
    examples: ['Wir **werden** nächstes Jahr nach Kanada ziehen.'],
  },
  {
    id: 'tr-vergessen',
    type: 'translation',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'writing',
    difficulty: 3,
    source: l('He will (probably) have forgotten it.', 'Herhalde unutmuştur.', 'He will (probably) have forgotten it.'),
    accepted: ['Er wird es vergessen haben.', 'Er wird es wohl vergessen haben.'],
    explanation: l('Futur II: wird … vergessen haben.', 'Futur II: wird … vergessen haben.', 'vergessen haben.'),
    examples: ['Er **wird** es wohl **vergessen haben**.'],
  },
  {
    id: 'tr-zukunft',
    type: 'translation',
    topic: 'funktion',
    concept: 'prediction',
    skill: 'writing',
    difficulty: 2,
    source: l('It will be very hot tomorrow.', 'Yarın çok sıcak olacak.', 'It will be very hot tomorrow.'),
    accepted: ['Morgen wird es sehr heiß.', 'Morgen wird es sehr heiß sein.', 'Es wird morgen sehr heiß.', 'Es wird morgen sehr heiß sein.'],
    explanation: l('Prediction: Futur I.', 'Tahmin: Futur I.', 'wird.'),
    examples: ['Morgen **wird** es sehr heiß.'],
  },
  {
    id: 'ordering-plan',
    type: 'ordering',
    topic: 'funktion',
    concept: 'completed-future',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Order Lea’s plan chronologically.', 'Lea’nın planını kronolojik sırala.', 'Ordne Leas Plan.'),
    items: ['Bis Dezember werde ich eine Wohnung in Berlin gefunden haben.', 'Im Sommer werde ich meinen Master beenden.', 'Im neuen Jahr werde ich dann meinen ersten Job anfangen.', 'Im Herbst werde ich mich bei Firmen bewerben.'],
    answer: ['Im Sommer werde ich meinen Master beenden.', 'Im Herbst werde ich mich bei Firmen bewerben.', 'Bis Dezember werde ich eine Wohnung in Berlin gefunden haben.', 'Im neuen Jahr werde ich dann meinen ersten Job anfangen.'],
    explanation: l('Summer → autumn → December → new year.', 'Yaz → sonbahar → aralık → yeni yıl.', 'Chronologie.'),
  },
  {
    id: 'dialog-vermutung',
    type: 'dialogue',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Mitbewohnerin', de: 'Die Milch ist leer! Wer war das?' }],
    options: ['Das wird wohl Jonas gewesen sein – er frühstückt immer so viel.', 'Das ist wohl Jonas gewesen werden.', 'Milch wird leer.'],
    answer: 0,
    explanation: l('Assumption about the past: wird … gewesen sein.', 'Geçmişe dair tahmin: wird … gewesen sein.', 'Futur II.'),
  },
  {
    id: 'dialog-zukunft',
    type: 'dialogue',
    topic: 'funktion',
    concept: 'prediction',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Interviewer', de: 'Wie wird die Arbeitswelt in zwanzig Jahren aussehen?' }],
    options: ['Ich glaube, viele Menschen werden nur noch drei oder vier Tage arbeiten.', 'Die Arbeitswelt sieht.', 'In zwanzig Jahren war es gut.'],
    answer: 0,
    explanation: l('Prediction: werden + infinitive.', 'Tahmin: werden + mastar.', 'Prognose.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-zukunft',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es im Text?',
    options: ['Wie wir im Jahr 2050 leben werden.', 'Wie man früher lebte.', 'Wie man ein Haus baut.'],
    answer: 0,
    explanation: l('„So werden wir 2050 leben“', '„So werden wir 2050 leben“', '2050.'),
  },
  {
    id: 'read-auto',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-zukunft',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was sagen die Forscher über Autos?',
    options: ['Die meisten werden selbst fahren.', 'Es wird keine Autos mehr geben.', 'Autos werden fliegen.'],
    answer: 0,
    explanation: l('„Die meisten Autos werden selbstständig fahren.“', '„Die meisten Autos werden selbstständig fahren.“', 'selbstständig.'),
  },
  {
    id: 'read-arbeit',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-zukunft',
    skill: 'reading',
    difficulty: 2,
    statement: 'Laut Text werden bis 2050 viele einfache Arbeiten von Maschinen übernommen worden sein.',
    answer: true,
    explanation: l('„Bis dahin werden Maschinen viele einfache Arbeiten übernommen haben.“', '„Bis dahin werden Maschinen viele einfache Arbeiten übernommen haben.“', 'richtig.'),
  },
  {
    id: 'read-kritik',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-zukunft',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was ist die Meinung der Autorin?',
    options: ['Viele Prognosen werden sich als falsch erwiesen haben.', 'Alle Prognosen stimmen sicher.', 'Die Zukunft ist langweilig.'],
    answer: 0,
    explanation: l('„Vermutlich werden sich viele dieser Prognosen als falsch erwiesen haben.“', '„Vermutlich werden sich viele dieser Prognosen als falsch erwiesen haben.“', 'falsch.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-paket',
    type: 'listening_choice',
    topic: 'vermutung-vergangenheit',
    concept: 'assumption-past',
    skill: 'listening',
    difficulty: 2,
    audio: 'Mein Paket ist immer noch nicht da. Der Bote wird es wohl beim Nachbarn abgegeben haben.',
    question: l('What does the speaker assume?', 'Konuşan ne tahmin ediyor?', 'Was vermutet die Person?'),
    options: ['The parcel was left with a neighbour.', 'The parcel was stolen.', 'The parcel never left the shop.'],
    answer: 0,
    explanation: l('„wird … beim Nachbarn abgegeben haben“', '„wird … beim Nachbarn abgegeben haben“', 'Nachbar.'),
  },
  {
    id: 'listen-wetter',
    type: 'listening_choice',
    topic: 'funktion',
    concept: 'prediction',
    skill: 'listening',
    difficulty: 1,
    audio: 'Am Wochenende wird es sonnig, aber am Montag werden die Temperaturen stark sinken.',
    question: l('What happens on Monday?', 'Pazartesi ne oluyor?', 'Was passiert am Montag?'),
    options: ['It gets much colder.', 'It gets sunny.', 'It snows all weekend.'],
    answer: 0,
    explanation: l('„Temperaturen stark sinken“', '„Temperaturen stark sinken“', 'kälter.'),
  },
  {
    id: 'listen-bis',
    type: 'listening_choice',
    topic: 'formen',
    concept: 'f1-f2',
    skill: 'listening',
    difficulty: 3,
    audio: 'Keine Sorge, bis zur Party werde ich die Wohnung aufgeräumt und eingekauft haben.',
    question: l('What will be done before the party?', 'Partiden önce ne yapılmış olacak?', 'Was ist bis zur Party erledigt?'),
    options: ['tidying and shopping', 'only cooking', 'nothing'],
    answer: 0,
    explanation: l('„aufgeräumt und eingekauft haben“', '„aufgeräumt und eingekauft haben“', 'aufgeräumt, eingekauft.'),
  },
  {
    id: 'listen-wohl',
    type: 'listening_choice',
    topic: 'funktion',
    concept: 'assumption-now',
    skill: 'listening',
    difficulty: 2,
    audio: 'Bei Familie Wagner brennt kein Licht. Die werden wohl im Urlaub sein.',
    question: l('What does the speaker think?', 'Konuşan ne düşünüyor?', 'Was denkt die Person?'),
    options: ['The Wagners are probably on holiday.', 'The Wagners have moved.', 'The lights are broken.'],
    answer: 0,
    explanation: l('„Die werden wohl im Urlaub sein.“', '„Die werden wohl im Urlaub sein.“', 'Urlaub.'),
  },

  ...futDrills(),
]

export const UNIT_B2_09_FUTUR_VERMUTUNG: CourseUnit = {
  level: 'B2',
  number: 9,
  slug: 'futur-vermutung',
  titleDe: 'Das wird wohl stimmen',
  title: l('That will probably be right', 'Muhtemelen doğrudur', 'Das wird wohl stimmen'),
  goal: l(
    'By the end of this unit you can use Futur I and Futur II for predictions and assumptions (Er wird wohl krank sein. Sie wird es vergessen haben.) and say what will be finished by a certain time.',
    'Bu ünitenin sonunda Futur I ve Futur II’yi tahminler ve varsayımlar için kullanabilir (Er wird wohl krank sein. Sie wird es vergessen haben.) ve belirli bir zamana kadar neyin bitmiş olacağını söyleyebilirsin.',
    'Am Ende dieser Einheit benutzt du Futur I und II für Vermutungen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'formen', label: l('Futur I and II forms', 'Futur I ve II biçimleri', 'Formen') },
    { key: 'funktion', label: l('Predictions and assumptions', 'Tahminler ve varsayımlar', 'Funktionen') },
    { key: 'vermutung-vergangenheit', label: l('Assumptions about the past', 'Geçmişe dair tahminler', 'Vergangenheit') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Talking about the future – and guessing.', 'Gelecekten bahsetmek – ve tahmin etmek.', 'Zukunft und Vermutung.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Futur I: werden + infinitive', 'Futur I: werden + mastar', 'Futur I'),
          body: l(
            'Used for predictions (Es wird regnen), promises (Ich werde dir helfen) and – with wohl, sicher, vermutlich – assumptions about now (Er wird wohl krank sein). For simple plans German often uses the present tense with a time word.',
            'Tahminler (Es wird regnen), sözler (Ich werde dir helfen) ve – wohl, sicher, vermutlich ile – şu ana dair varsayımlar (Er wird wohl krank sein) için kullanılır. Basit planlar için Almanca genelde zaman kelimesiyle şimdiki zamanı kullanır.',
            'werden + Infinitiv.'
          ),
          examples: [
            { de: 'Es **wird** morgen **regnen**.', translation: l('It will rain tomorrow.', 'Yarın yağmur yağacak.', '') },
            { de: 'Er **wird** wohl im Büro **sein**.', translation: l('He is probably at the office.', 'Muhtemelen ofistedir.', '') },
          ],
        },
        {
          title: l('Futur II: werden + participle + haben/sein', 'Futur II: werden + ortaç + haben/sein', 'Futur II'),
          body: l(
            'Two uses: (1) assumption about the past: Sie wird den Bus verpasst haben. (2) something completed before a future point: Bis Juni werde ich das Studium beendet haben. Choose haben or sein as in the Perfekt.',
            'İki kullanım: (1) geçmişe dair tahmin: Sie wird den Bus verpasst haben. (2) gelecekteki bir noktadan önce tamamlanmış olan: Bis Juni werde ich das Studium beendet haben. haben ya da sein’ı Perfekt’teki gibi seç.',
            'werden + Partizip II + haben/sein.'
          ),
          table: {
            head: [l('Form', 'Biçim', 'Form'), l('Example', 'Örnek', 'Beispiel'), l('Meaning', 'Anlam', 'Bedeutung')],
            rows: [
              ['Futur I', 'Er wird kommen.', 'Prognose'],
              ['Futur I + wohl', 'Er wird wohl da sein.', 'Vermutung jetzt'],
              ['Futur II', 'Er wird gegangen sein.', 'Vermutung früher'],
              ['Futur II + bis', 'Bis Mai werde ich es geschafft haben.', 'abgeschlossen'],
            ],
          },
        },
        {
          title: l('Word order', 'Kelime dizimi', 'Wortstellung'),
          body: l(
            'werden in position 2, the rest at the end: Sie wird den Termin vergessen haben. In subordinate clauses werden goes last: …, dass sie den Termin vergessen haben wird.',
            'werden 2. konumda, geri kalanı sonda: Sie wird den Termin vergessen haben. Yan cümlede werden en sona gider: …, dass sie den Termin vergessen haben wird.',
            'Satzklammer.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two friends wait for a third at the cinema.', 'İki arkadaş sinemada üçüncüsünü bekliyor.', 'Wo bleibt Tim?'),
      dialogue: [
        { speaker: 'Elif', de: 'Der Film fängt gleich an. Wo bleibt Tim?', translation: l('The film starts soon. Where is Tim?', 'Film birazdan başlıyor. Tim nerede kaldı?', '') },
        { speaker: 'Jan', de: 'Er **wird** wohl noch im Bus **sitzen**. Um diese Zeit ist immer viel Verkehr.', translation: l('He’s probably still on the bus. There’s always a lot of traffic at this time.', 'Herhalde hâlâ otobüstedir. Bu saatte trafik hep yoğun.', '') },
        { speaker: 'Elif', de: 'Oder er **wird** den Termin wieder **vergessen haben**.', translation: l('Or he’ll have forgotten the appointment again.', 'Ya da yine randevuyu unutmuştur.', '') },
        { speaker: 'Jan', de: 'Nein, heute nicht. Ich habe ihm heute Morgen noch geschrieben.', translation: l('No, not today. I texted him this morning.', 'Hayır, bugün değil. Bu sabah ona yazdım.', '') },
        { speaker: 'Elif', de: 'Na gut. Bis er kommt, **werden** wir die Werbung schon **gesehen haben**.', translation: l('Okay. By the time he comes, we’ll have already seen the adverts.', 'Peki. O gelene kadar reklamları çoktan izlemiş olacağız.', '') },
        { speaker: 'Jan', de: '(lacht) Dann **wird** er sich **freuen** – die Werbung hasst er sowieso.', translation: l('(laughs) Then he’ll be happy – he hates the adverts anyway.', '(güler) O zaman sevinir – reklamlardan zaten nefret ediyor.', '') },
      ],
      examples: [
        { de: 'Es **wird** morgen **schneien**.', translation: l('It will snow tomorrow.', 'Yarın kar yağacak.', '') },
        { de: 'Sie **wird** wohl müde **sein**.', translation: l('She’s probably tired.', 'Muhtemelen yorgundur.', '') },
        { de: 'Er **wird** den Zug **verpasst haben**.', translation: l('He’ll have missed the train.', 'Treni kaçırmıştır.', '') },
        { de: 'Sie **werden** schon **abgefahren sein**.', translation: l('They’ll have left already.', 'Çoktan yola çıkmışlardır.', '') },
        { de: 'Bis Juni **werde** ich **fertig sein**.', translation: l('I’ll be finished by June.', 'Hazirana kadar bitirmiş olacağım.', '') },
        { de: 'Ich bin sicher, dass du es schaffen **wirst**.', translation: l('I’m sure you’ll manage.', 'Başaracağından eminim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Futur I or II – prediction or assumption?', 'Futur I mi II mi – tahmin mi varsayım mı?', 'Futur I oder II?'),
      exercises: ['match-funktion', 'sort-futur', 'fut-futur1', 'fut-futur2-haben', 'fut-futur2-sein', 'mc-wohl', 'tf-praesens', 'select-vergangenheit', 'image-prognose'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Predict, guess and plan.', 'Tahmin et, varsay ve planla.', 'Vermuten und planen.'),
      exercises: [
        'fill-haben',
        'fill-sein',
        'fill-werden',
        'build-futur2',
        'build-wohl',
        'build-dass',
        'fix-hat',
        'fix-sein-haben',
        'fix-wird',
        'tr-vergessen',
        'tr-zukunft',
        'ordering-plan',
        'dialog-vermutung',
        'dialog-zukunft',
        'fut-fertig',
        'fut-verspaetung',
        'fut-schlafen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A magazine article about the future.', 'Gelecek hakkında bir dergi yazısı.', 'Ein Zukunftsartikel.'),
      passage: [
        '**So werden wir 2050 leben** – Forscher haben versucht, die Zukunft vorherzusagen.',
        'Die meisten Autos **werden** selbstständig **fahren**, und in den Städten **wird** es viel mehr Grün **geben**.',
        'Bis dahin **werden** Maschinen viele einfache Arbeiten **übernommen haben**. Die Menschen **werden** dafür mehr Zeit für Familie und Hobbys **haben**.',
        'Doch die Autorin bleibt skeptisch: „Vermutlich **werden** sich viele dieser Prognosen als falsch **erwiesen haben**, wenn wir 2050 zurückblicken.“',
      ],
      glossary: [
        { de: 'vorhersagen', note: l('to predict', 'öngörmek', 'sagen, was kommt') },
        { de: 'selbstständig', note: l('autonomously', 'kendi başına', 'ohne Hilfe') },
        { de: 'skeptisch', note: l('sceptical', 'şüpheci', 'zweifelnd') },
        { de: 'sich erweisen als', note: l('to turn out to be', '… olduğu ortaya çıkmak', 'sich zeigen als') },
      ],
      exercises: ['read-thema', 'read-auto', 'read-arbeit', 'read-kritik'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Predictions and guesses in everyday life.', 'Günlük hayatta tahminler ve varsayımlar.', 'Vermutungen im Alltag.'),
      exercises: ['listen-paket', 'listen-wetter', 'listen-bis', 'listen-wohl'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('How will your life look in ten years? What will you have achieved by then?', 'On yıl sonra hayatın nasıl olacak? O zamana kadar neleri başarmış olacaksın?', 'Dein Leben in zehn Jahren.'),
      points: [
        l('Two predictions with Futur I', 'Futur I ile iki tahmin', 'Futur I'),
        l('Two things you will have done (Futur II)', 'Yapmış olacağın iki şey (Futur II)', 'Futur II'),
        l('One uncertain guess: wohl / vermutlich', 'Bir belirsiz tahmin: wohl / vermutlich', 'wohl'),
        l('A wish or worry', 'Bir dilek ya da endişe', 'Wunsch'),
      ],
      model: [
        'In zehn Jahren werde ich wahrscheinlich in Hamburg wohnen.',
        'Bis dahin werde ich mein Studium abgeschlossen und mehrere Länder bereist haben.',
        'Ich werde vermutlich als Ärztin arbeiten.',
        'Ich hoffe, dass ich dann immer noch genug Zeit für meine Familie haben werde.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short text (at least 5 sentences): „My city in 2050“. Use Futur I and Futur II.',
        'Kısa bir metin yaz (en az 5 cümle): „2050’de şehrim“. Futur I ve Futur II kullan.',
        'Meine Stadt im Jahr 2050 (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Futur I (werden + infinitive)', 'Futur I (werden + mastar)', 'Futur I'), pattern: '\\b(wird|werden|werde|wirst)\\b[^.!?]*\\b\\p{Ll}+en\\b' },
        { label: l('Futur II (… participle + haben / sein)', 'Futur II (… ortaç + haben / sein)', 'Futur II'), pattern: '\\b\\p{Ll}+(t|en) (haben|sein)\\b' },
        { label: l('A certainty word (wohl, vermutlich, sicher, wahrscheinlich)', 'Bir kesinlik kelimesi (wohl, vermutlich, sicher, wahrscheinlich)', 'Sicherheit'), pattern: '\\b(wohl|vermutlich|sicher|wahrscheinlich|bestimmt)\\b' },
      ],
      model: [
        'Im Jahr 2050 wird meine Stadt ganz anders aussehen.',
        'Es wird wahrscheinlich kaum noch Autos in der Innenstadt geben.',
        'Bis dahin wird man viele Straßen in Parks umgewandelt haben.',
        'Die Menschen werden vermutlich mehr Fahrrad fahren.',
        'Ich hoffe, dass ich das alles noch erleben werde.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Build the future form – 60 seconds.', 'Gelecek biçimini kur – 60 saniye.', 'Futur bilden – 60 Sekunden.'),
      seconds: 60,
      pool: [...FUT.map(([id]) => `fut-${id}`), 'mc-wohl'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Futur I: predictions, promises, assumptions about now (wird wohl …)', 'Futur I: tahminler, sözler, şu ana dair varsayımlar (wird wohl …)', 'Futur I'),
      l('Futur II: assumptions about the past (wird … vergessen haben)', 'Futur II: geçmişe dair varsayımlar (wird … vergessen haben)', 'Futur II'),
      l('Futur II with bis: completed in the future', 'bis ile Futur II: gelecekte tamamlanmış', 'abgeschlossen'),
      l('Certainty words: wohl, vermutlich, sicher, bestimmt', 'Kesinlik kelimeleri: wohl, vermutlich, sicher, bestimmt', 'Sicherheit'),
    ],
    mistakes: [
      { wrong: 'Er wird den Brief gelesen hat.', right: 'Er wird den Brief gelesen haben.', note: l('Infinitive haben.', 'Mastar haben.', 'haben.') },
      { wrong: 'Der Zug wird abgefahren haben.', right: 'Der Zug wird abgefahren sein.', note: l('Movement → sein.', 'Hareket → sein.', 'sein.') },
      { wrong: 'Wir wird umziehen.', right: 'Wir werden umziehen.', note: l('Conjugation.', 'Çekim.', 'werden.') },
      { wrong: '…, dass du die Prüfung wirst bestehen.', right: '…, dass du die Prüfung bestehen wirst.', note: l('werden last.', 'werden en sonda.', 'Ende.') },
    ],
  },
}
