import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'ankommen → die Ankunft', emoji: '🛬', translation: l('to arrive → arrival', 'varmak → varış', 'Nominalisierung'), example: 'Nach der Ankunft gehen wir essen.' },
  { word: 'abfahren → die Abfahrt', emoji: '🚆', translation: l('to depart → departure', 'kalkmak → kalkış', 'Nominalisierung'), example: 'Vor der Abfahrt kaufen wir Tickets.' },
  { word: 'entscheiden → die Entscheidung', emoji: '⚖️', translation: l('to decide → decision', 'karar vermek → karar', '-ung'), example: 'Die Entscheidung fiel schwer.' },
  { word: 'beginnen → der Beginn', emoji: '▶️', translation: l('to begin → beginning', 'başlamak → başlangıç', 'ohne Endung'), example: 'Seit Beginn des Kurses lerne ich viel.' },
  { word: 'bei + Nomen', emoji: '📎', translation: l('in case of / during', '… durumunda / sırasında', '= wenn / als'), example: 'Bei Regen fällt das Fest aus.' },
  { word: 'nach + Nomen', emoji: '⏩', translation: l('after', '… -den sonra', '= nachdem'), example: 'Nach dem Essen machen wir einen Spaziergang.' },
  { word: 'vor + Nomen', emoji: '⏪', translation: l('before', '… -den önce', '= bevor'), example: 'Vor dem Schlafen lese ich.' },
  { word: 'wegen + Genitiv', emoji: '❓', translation: l('because of', '… yüzünden', '= weil'), example: 'Wegen des Streiks fahren keine Busse.' },
  { word: 'trotz + Genitiv', emoji: '🔄', translation: l('despite', '… -e rağmen', '= obwohl'), example: 'Trotz der Kälte gingen wir schwimmen.' },
  { word: 'zur + Nomen', emoji: '🎯', translation: l('for (purpose)', '… için (amaç)', '= um … zu'), example: 'Zur Verbesserung der Luft fahren wir Rad.' },
  { word: 'durch + Nomen', emoji: '🛤️', translation: l('through, by', '… yoluyla', '= indem'), example: 'Durch regelmäßiges Üben wird man besser.' },
  { word: 'der Nominalstil', emoji: '📄', translation: l('nominal style', 'isim ağırlıklı üslup', 'viele Nomen statt Verben'), example: 'Behörden schreiben oft im Nominalstil.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Ankunft', gender: 'f', translation: l('arrival', 'varış', 'Ankunft') },
  { word: 'Abfahrt', gender: 'f', plural: 'die Abfahrten', translation: l('departure', 'kalkış', 'Abfahrt') },
  { word: 'Entscheidung', gender: 'f', plural: 'die Entscheidungen', translation: l('decision', 'karar', 'Entscheidung') },
  { word: 'Beginn', gender: 'm', translation: l('beginning', 'başlangıç', 'Beginn') },
  { word: 'Verbesserung', gender: 'f', plural: 'die Verbesserungen', translation: l('improvement', 'iyileştirme', 'Verbesserung') },
  { word: 'Erhöhung', gender: 'f', plural: 'die Erhöhungen', translation: l('increase', 'artış', 'Erhöhung') },
  { word: 'Teilnahme', gender: 'f', translation: l('participation', 'katılım', 'Teilnahme') },
  { word: 'Antwort', gender: 'f', plural: 'die Antworten', translation: l('answer', 'cevap', 'Antwort') },
]

/** [id, verbal clause, right nominal phrase, wrong] */
const NOM: [string, string, string, [string, string]][] = [
  ['ankunft', 'nachdem der Zug angekommen ist', 'nach der Ankunft des Zuges', ['nach die Ankunft des Zuges', 'nach der Ankunft der Zug']],
  ['abfahrt', 'bevor wir abfahren', 'vor unserer Abfahrt', ['vor unsere Abfahrt', 'vor unser Abfahrt']],
  ['regen', 'weil es stark regnet', 'wegen des starken Regens', ['wegen des starke Regens', 'wegen den starken Regen']],
  ['studium', 'während er studierte', 'während seines Studiums', ['während sein Studium', 'während seines Studium']],
  ['preise', 'obwohl die Preise hoch sind', 'trotz der hohen Preise', ['trotz die hohen Preise', 'trotz der hoher Preise']],
  ['fragen', 'wenn Sie Fragen haben', 'bei Fragen', ['bei Fragen haben', 'beim Fragen hat']],
]

function nomDrills(): Exercise[] {
  return NOM.map(([id, verbal, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `nom-${id}`,
      type: 'multiple_choice' as const,
      topic: 'verbal-nominal',
      concept: 'clause-to-phrase',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: `„${verbal}“ – im Nominalstil:`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Conjunction → preposition, verb → noun, subject → genitive or possessive: ${right}.`,
        `Bağlaç → edat, fiil → isim, özne → Genitiv ya da iyelik: ${right}.`,
        `→ ${right}`
      ),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-nomen',
    type: 'matching',
    topic: 'nominalisierung',
    concept: 'verb-noun',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match verb and noun.', 'Fiili isimle eşleştir.', 'Verb und Nomen.'),
    pairs: [
      { left: 'teilnehmen', right: 'die Teilnahme' },
      { left: 'erhöhen', right: 'die Erhöhung' },
      { left: 'antworten', right: 'die Antwort' },
      { left: 'verlieren', right: 'der Verlust' },
      { left: 'abfahren', right: 'die Abfahrt' },
    ],
    explanation: l('Common patterns: -ung, no ending, sometimes a vowel change (verlieren → Verlust).', 'Yaygın kalıplar: -ung, eksiz, bazen ünlü değişimi (verlieren → Verlust).', 'Nominalisierung.'),
  },
  {
    id: 'sort-praep',
    type: 'categorize',
    topic: 'praepositionen',
    concept: 'conjunction-preposition',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('Which conjunction does the preposition replace?', 'Edat hangi bağlacın yerini tutuyor?', 'Welche Konjunktion?'),
    categories: ['weil', 'obwohl', 'wenn'],
    items: [
      { text: 'wegen', category: 0 },
      { text: 'trotz', category: 1 },
      { text: 'bei', category: 2 },
      { text: 'aufgrund', category: 0 },
      { text: 'ungeachtet', category: 1 },
      { text: 'im Falle', category: 2 },
    ],
    explanation: l('weil → wegen/aufgrund, obwohl → trotz, wenn → bei/im Falle.', 'weil → wegen/aufgrund, obwohl → trotz, wenn → bei/im Falle.', 'Konjunktion → Präposition.'),
    practice: ['nom-ankunft'],
  },
  {
    id: 'mc-zur',
    type: 'multiple_choice',
    topic: 'praepositionen',
    concept: 'purpose',
    skill: 'grammar',
    difficulty: 3,
    prompt: '„Um die Qualität zu verbessern, …“ = „___ Verbesserung der Qualität …“',
    options: ['Zur', 'Für die', 'Um die'],
    answer: 0,
    explanation: l('um … zu → zur / zum + noun.', 'um … zu → zur / zum + isim.', 'Zur Verbesserung.'),
    examples: ['**Zur** Verbesserung der Qualität …'],
    practice: ['fill-durch'],
  },
  {
    id: 'tf-genitiv',
    type: 'true_false',
    topic: 'nominalisierung',
    concept: 'subject-genitive',
    skill: 'grammar',
    difficulty: 3,
    statement: 'Beim Nominalisieren wird das Subjekt oft zu einem Genitiv: „Der Chef entscheidet“ → „die Entscheidung des Chefs“.',
    answer: true,
    explanation: l('Subject → genitive (or von + dative / possessive).', 'Özne → Genitiv (ya da von + Dativ / iyelik).', 'des Chefs.'),
  },
  {
    id: 'select-nominal',
    type: 'multiple_select',
    topic: 'stil',
    concept: 'recognize-style',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Which sentences are in nominal style? Select all.', 'Hangi cümleler isim ağırlıklı üslupta? Hepsini seç.', 'Welche Sätze sind Nominalstil?'),
    options: ['Nach Eingang Ihrer Zahlung erfolgt der Versand.', 'Wenn Sie bezahlt haben, schicken wir die Ware.', 'Bei Nichtbeachtung droht eine Strafe.', 'Zur Vermeidung von Wartezeiten bitten wir um Termine.', 'Ruf mich an, wenn du Zeit hast.'],
    answers: [0, 2, 3],
    explanation: l('Many nouns, prepositions, few verbs = nominal style (official texts).', 'Çok isim, edat, az fiil = isim ağırlıklı üslup (resmî metinler).', 'Nominalstil.'),
  },
  {
    id: 'image-amt',
    type: 'image_choice',
    topic: 'stil',
    concept: 'recognize-style',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Bei Verlust des Ausweises ist das Bürgeramt unverzüglich zu informieren.',
    options: [
      { emoji: '🏛️', label: 'Behördentext' },
      { emoji: '💌', label: 'Liebesbrief' },
      { emoji: '🎵', label: 'Liedtext' },
      { emoji: '🍕', label: 'Speisekarte' },
    ],
    answer: 0,
    explanation: l('Official texts love nominal style.', 'Resmî metinler isim ağırlıklı üslubu sever.', 'Behördensprache.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-durch',
    type: 'fill_blank',
    topic: 'praepositionen',
    concept: 'means',
    skill: 'grammar',
    difficulty: 3,
    sentence: '___ tägliches Training hat sie ihre Zeit verbessert.',
    accepted: ['Durch'],
    base: '= indem sie täglich trainierte',
    explanation: l('indem → durch + accusative.', 'indem → durch + Akk.', 'Durch.'),
    examples: ['**Durch** tägliches Training hat sie ihre Zeit verbessert.'],
  },
  {
    id: 'fill-beginn',
    type: 'fill_blank',
    topic: 'nominalisierung',
    concept: 'verb-noun',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Vor ___ der Prüfung müssen alle Handys ausgeschaltet werden. (beginnen)',
    accepted: ['Beginn', 'dem Beginn'],
    base: 'beginnen → Nomen',
    explanation: l('beginnen → der Beginn; vor (dem) Beginn.', 'beginnen → der Beginn; vor (dem) Beginn.', 'Beginn.'),
    examples: ['Vor **Beginn** der Prüfung …'],
  },
  {
    id: 'fill-teilnahme',
    type: 'fill_blank',
    topic: 'nominalisierung',
    concept: 'verb-noun',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Die ___ am Kurs ist kostenlos. (teilnehmen)',
    accepted: ['Teilnahme'],
    base: 'teilnehmen',
    explanation: l('teilnehmen → die Teilnahme (an + dative).', 'teilnehmen → die Teilnahme (an + Dativ).', 'Teilnahme.'),
    examples: ['Die **Teilnahme** am Kurs ist kostenlos.'],
  },
  {
    id: 'build-nach',
    type: 'sentence_builder',
    topic: 'verbal-nominal',
    concept: 'clause-to-phrase',
    skill: 'grammar',
    difficulty: 3,
    chips: ['erhalten Sie', 'Nach Eingang', 'Ihrer Bestellung', 'eine E-Mail'],
    answers: [['Nach Eingang', 'Ihrer Bestellung', 'erhalten Sie', 'eine E-Mail']],
    translation: l('After receipt of your order you will receive an email.', 'Siparişiniz alındıktan sonra bir e-posta alacaksınız.', 'Nach Eingang Ihrer Bestellung erhalten Sie eine E-Mail.'),
    explanation: l('Nach Eingang Ihrer Bestellung = Nachdem Ihre Bestellung eingegangen ist.', 'Nach Eingang Ihrer Bestellung = Nachdem Ihre Bestellung eingegangen ist.', 'Nominalstil.'),
    examples: ['**Nach Eingang** Ihrer Bestellung erhalten Sie eine E-Mail.'],
  },
  {
    id: 'build-trotz',
    type: 'sentence_builder',
    topic: 'praepositionen',
    concept: 'conjunction-preposition',
    skill: 'grammar',
    difficulty: 3,
    chips: ['fand das Konzert', 'Trotz des schlechten Wetters', 'statt'],
    answers: [['Trotz des schlechten Wetters', 'fand das Konzert', 'statt']],
    translation: l('Despite the bad weather the concert took place.', 'Kötü havaya rağmen konser yapıldı.', 'Trotz des schlechten Wetters fand das Konzert statt.'),
    explanation: l('trotz + genitive; then verb in position 2.', 'trotz + Genitiv; sonra fiil 2. konumda.', 'trotz.'),
    examples: ['**Trotz des schlechten Wetters** fand das Konzert statt.'],
  },
  {
    id: 'build-verbal',
    type: 'sentence_builder',
    topic: 'stil',
    concept: 'nominal-to-verbal',
    skill: 'grammar',
    difficulty: 3,
    chips: ['wenn', 'Sie können umtauschen,', 'die Ware', 'defekt ist'],
    answers: [['Sie können umtauschen,', 'wenn', 'die Ware', 'defekt ist']],
    translation: l('You can exchange if the goods are defective.', 'Ürün kusurluysa değiştirebilirsiniz.', 'Sie können umtauschen, wenn die Ware defekt ist.'),
    explanation: l('„bei Defekt der Ware“ in verbal style: wenn die Ware defekt ist.', '„bei Defekt der Ware“ fiil üslubunda: wenn die Ware defekt ist.', 'Verbalstil.'),
    examples: ['Sie können umtauschen, **wenn** die Ware defekt **ist**.'],
  },
  {
    id: 'fix-genitiv',
    type: 'error_correction',
    topic: 'nominalisierung',
    concept: 'subject-genitive',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wir warten auf die Entscheidung der Direktor.',
    accepted: ['Wir warten auf die Entscheidung des Direktors.'],
    explanation: l('Genitive masculine: des Direktors.', 'Eril Genitiv: des Direktors.', 'des Direktors.'),
    examples: ['… die Entscheidung **des Direktors**.'],
  },
  {
    id: 'fix-wegen',
    type: 'error_correction',
    topic: 'praepositionen',
    concept: 'conjunction-preposition',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wegen der Zug Verspätung hatte, kamen wir zu spät.',
    accepted: ['Wegen der Verspätung des Zuges kamen wir zu spät.', 'Weil der Zug Verspätung hatte, kamen wir zu spät.'],
    explanation: l('Either a clause (weil … hatte) or a phrase (wegen der Verspätung des Zuges) – don’t mix.', 'Ya yan cümle (weil … hatte) ya da öbek (wegen der Verspätung des Zuges) – karıştırma.', 'nicht mischen.'),
    examples: ['**Wegen der Verspätung des Zuges** kamen wir zu spät.'],
  },
  {
    id: 'fix-bei',
    type: 'error_correction',
    topic: 'praepositionen',
    concept: 'condition',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Bei schlecht Wetter fällt der Ausflug aus.',
    accepted: ['Bei schlechtem Wetter fällt der Ausflug aus.'],
    explanation: l('bei + dative, no article → schlechtem.', 'bei + Dativ, artikelsiz → schlechtem.', 'schlechtem.'),
    examples: ['Bei **schlechtem** Wetter fällt der Ausflug aus.'],
  },
  {
    id: 'tr-nach',
    type: 'translation',
    topic: 'verbal-nominal',
    concept: 'clause-to-phrase',
    skill: 'writing',
    difficulty: 3,
    source: l('Nominal style: „Nachdem er angekommen war, rief er an.“', 'İsim üslubu: „Nachdem er angekommen war, rief er an.“', 'Nominalstil: „Nachdem er angekommen war, rief er an.“'),
    accepted: ['Nach seiner Ankunft rief er an.'],
    explanation: l('nachdem er angekommen war → nach seiner Ankunft.', 'nachdem er angekommen war → nach seiner Ankunft.', 'Nach seiner Ankunft.'),
    examples: ['**Nach seiner Ankunft** rief er an.'],
  },
  {
    id: 'tr-verbal',
    type: 'translation',
    topic: 'stil',
    concept: 'nominal-to-verbal',
    skill: 'writing',
    difficulty: 3,
    source: l('Verbal style: „Bei Fragen rufen Sie uns an.“', 'Fiil üslubu: „Bei Fragen rufen Sie uns an.“', 'Verbalstil: „Bei Fragen rufen Sie uns an.“'),
    accepted: ['Wenn Sie Fragen haben, rufen Sie uns an.', 'Rufen Sie uns an, wenn Sie Fragen haben.'],
    explanation: l('bei Fragen → wenn Sie Fragen haben.', 'bei Fragen → wenn Sie Fragen haben.', 'wenn.'),
    examples: ['**Wenn Sie Fragen haben**, rufen Sie uns an.'],
  },
  {
    id: 'ordering-brief',
    type: 'ordering',
    topic: 'stil',
    concept: 'recognize-style',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the official letter in order.', 'Resmî mektubu sırala.', 'Ordne den Behördenbrief.'),
    items: ['Bei Rückfragen stehen wir Ihnen gern zur Verfügung.', 'Sehr geehrte Frau Aydın,', 'nach Prüfung Ihres Antrags freuen wir uns, Ihnen die Genehmigung zu erteilen.', 'Zur Abholung bringen Sie bitte Ihren Ausweis mit.'],
    answer: ['Sehr geehrte Frau Aydın,', 'nach Prüfung Ihres Antrags freuen wir uns, Ihnen die Genehmigung zu erteilen.', 'Zur Abholung bringen Sie bitte Ihren Ausweis mit.', 'Bei Rückfragen stehen wir Ihnen gern zur Verfügung.'],
    explanation: l('Greeting → decision → next step → offer of help.', 'Hitap → karar → sonraki adım → yardım teklifi.', 'Aufbau.'),
  },
  {
    id: 'dialog-erklaeren',
    type: 'dialogue',
    topic: 'stil',
    concept: 'nominal-to-verbal',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Mitbewohner', de: 'Hier steht „Bei Nichterscheinen wird eine Gebühr fällig.“ Was heißt das?' }],
    options: ['Wenn du nicht kommst, musst du eine Gebühr bezahlen.', 'Die Gebühr erscheint nicht.', 'Du musst erscheinen, weil es nichts kostet.'],
    answer: 0,
    explanation: l('bei Nichterscheinen = wenn man nicht erscheint.', 'bei Nichterscheinen = gelinmezse.', 'Verbalstil.'),
  },
  {
    id: 'dialog-stil',
    type: 'dialogue',
    topic: 'stil',
    concept: 'register',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freundin', de: 'Soll ich in meiner WhatsApp schreiben: „Nach Beendigung meiner Arbeit erfolgt mein Erscheinen“?' }],
    options: ['Lieber nicht! Schreib einfach: „Wenn ich mit der Arbeit fertig bin, komme ich.“', 'Ja, das ist perfekt für WhatsApp.', 'Schreib „Erscheinen erfolgt“.'],
    answer: 0,
    explanation: l('Nominal style is for formal texts – in chats use verbs.', 'İsim üslubu resmî metinler içindir – sohbette fiil kullan.', 'Register.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-was',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-hinweis',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was ist das für ein Text?',
    options: ['Hinweise einer Bibliothek.', 'Ein Kochrezept.', 'Eine Einladung zur Party.'],
    answer: 0,
    explanation: l('„Benutzungshinweise der Stadtbibliothek“', '„Benutzungshinweise der Stadtbibliothek“', 'Bibliothek.'),
  },
  {
    id: 'read-ausweis',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-hinweis',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was braucht man für die Anmeldung?',
    options: ['Einen Ausweis.', 'Ein Foto.', 'Eine Kreditkarte.'],
    answer: 0,
    explanation: l('„Zur Anmeldung ist ein gültiger Ausweis vorzulegen.“', '„Zur Anmeldung ist ein gültiger Ausweis vorzulegen.“', 'Ausweis.'),
  },
  {
    id: 'read-verlust',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-hinweis',
    skill: 'reading',
    difficulty: 2,
    statement: 'Wenn man ein Buch verliert, muss man es bezahlen.',
    answer: true,
    explanation: l('„Bei Verlust eines Mediums wird der Wiederbeschaffungswert berechnet.“', '„Bei Verlust eines Mediums wird der Wiederbeschaffungswert berechnet.“', 'richtig.'),
  },
  {
    id: 'read-verlaengern',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-hinweis',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wie kann man die Ausleihe verlängern?',
    options: ['Online, vor Ablauf der Frist.', 'Nur persönlich nach der Frist.', 'Gar nicht.'],
    answer: 0,
    explanation: l('„Eine Verlängerung ist vor Ablauf der Leihfrist online möglich.“', '„Eine Verlängerung ist vor Ablauf der Leihfrist online möglich.“', 'online.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-bahn',
    type: 'listening_choice',
    topic: 'praepositionen',
    concept: 'conjunction-preposition',
    skill: 'listening',
    difficulty: 2,
    audio: 'Aufgrund einer Weichenstörung verzögert sich die Abfahrt um etwa zwanzig Minuten.',
    question: l('Why is the train delayed?', 'Tren neden gecikiyor?', 'Warum Verspätung?'),
    options: ['a points failure', 'bad weather', 'a strike'],
    answer: 0,
    explanation: l('„Aufgrund einer Weichenstörung“', '„Aufgrund einer Weichenstörung“', 'Weichenstörung.'),
  },
  {
    id: 'listen-praxis',
    type: 'listening_choice',
    topic: 'praepositionen',
    concept: 'condition',
    skill: 'listening',
    difficulty: 2,
    audio: 'Bei Fieber über 39 Grad wenden Sie sich bitte sofort an den Notdienst.',
    question: l('When should you call the emergency service?', 'Acil servisi ne zaman aramalısın?', 'Wann Notdienst?'),
    options: ['with a fever over 39 °C', 'with a cold', 'on weekends'],
    answer: 0,
    explanation: l('„Bei Fieber über 39 Grad“ = wenn man Fieber über 39 Grad hat.', '„Bei Fieber über 39 Grad“ = 39 dereceden yüksek ateş varsa.', 'Fieber.'),
  },
  {
    id: 'listen-zur',
    type: 'listening_choice',
    topic: 'praepositionen',
    concept: 'purpose',
    skill: 'listening',
    difficulty: 2,
    audio: 'Zur Senkung der Energiekosten werden die Büros ab 18 Uhr nicht mehr beheizt.',
    question: l('Why are the offices not heated after 6 pm?', 'Ofisler neden saat 18’den sonra ısıtılmıyor?', 'Warum keine Heizung?'),
    options: ['to reduce energy costs', 'because nobody works', 'because it is warm'],
    answer: 0,
    explanation: l('„Zur Senkung der Energiekosten“ = um die Energiekosten zu senken.', '„Zur Senkung der Energiekosten“ = enerji maliyetini düşürmek için.', 'Kosten senken.'),
  },
  {
    id: 'listen-trotz',
    type: 'listening_choice',
    topic: 'verbal-nominal',
    concept: 'clause-to-phrase',
    skill: 'listening',
    difficulty: 3,
    audio: 'Trotz intensiver Verhandlungen konnten sich Gewerkschaft und Arbeitgeber nicht einigen.',
    question: l('What was the result of the negotiations?', 'Görüşmelerin sonucu ne oldu?', 'Ergebnis?'),
    options: ['no agreement', 'a new contract', 'a strike was cancelled'],
    answer: 0,
    explanation: l('„… konnten sich … nicht einigen“', '„… konnten sich … nicht einigen“', 'keine Einigung.'),
  },

  ...nomDrills(),
]

export const UNIT_B2_05_NOMINALSTIL: CourseUnit = {
  level: 'B2',
  number: 5,
  slug: 'nominalstil',
  titleDe: 'Nominalstil und Verbalstil',
  title: l('Nominal and verbal style', 'İsim ağırlıklı ve fiil ağırlıklı üslup', 'Nominalstil und Verbalstil'),
  goal: l(
    'By the end of this unit you can understand official and formal texts in nominal style, convert between clauses and noun phrases (nachdem → nach, weil → wegen, wenn → bei) and choose the right style for the situation.',
    'Bu ünitenin sonunda isim ağırlıklı resmî metinleri anlayabilir, yan cümlelerle isim öbekleri arasında dönüşüm yapabilir (nachdem → nach, weil → wegen, wenn → bei) ve duruma uygun üslubu seçebilirsin.',
    'Am Ende dieser Einheit wechselst du zwischen Nominal- und Verbalstil.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'nominalisierung', label: l('Nouns from verbs', 'Fiilden isim', 'Nominalisierung') },
    { key: 'praepositionen', label: l('Prepositions instead of conjunctions', 'Bağlaç yerine edat', 'Präpositionen') },
    { key: 'verbal-nominal', label: l('Clause → phrase', 'Cümle → öbek', 'Umformung') },
    { key: 'stil', label: l('Style and register', 'Üslup ve dil düzeyi', 'Stil') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('How official German packs information.', 'Resmî Almancanın bilgiyi nasıl paketlediği.', 'Behördendeutsch verstehen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('From clause to noun phrase', 'Yan cümleden isim öbeğine', 'Vom Nebensatz zur Nominalgruppe'),
          body: l(
            'Three steps: conjunction → preposition, verb → noun, subject → genitive (or possessive). Nachdem der Zug angekommen ist → nach der Ankunft des Zuges.',
            'Üç adım: bağlaç → edat, fiil → isim, özne → Genitiv (ya da iyelik). Nachdem der Zug angekommen ist → nach der Ankunft des Zuges.',
            'Konjunktion → Präposition, Verb → Nomen, Subjekt → Genitiv.'
          ),
          table: {
            head: [l('Conjunction', 'Bağlaç', 'Konjunktion'), l('Preposition', 'Edat', 'Präposition')],
            rows: [
              ['nachdem / bevor', 'nach / vor + Dat.'],
              ['weil', 'wegen / aufgrund + Gen.'],
              ['obwohl', 'trotz + Gen.'],
              ['wenn / als', 'bei + Dat.'],
              ['um … zu / damit', 'zur / zum + Dat.'],
              ['indem', 'durch + Akk.'],
            ],
          },
        },
        {
          title: l('Forming nouns', 'İsim türetmek', 'Nomen bilden'),
          body: l(
            'Most common: -ung (entscheiden → Entscheidung), stem without ending (beginnen → Beginn), vowel change (ankommen → Ankunft, verlieren → Verlust) or the infinitive as a noun (das Lernen).',
            'En yaygın: -ung (entscheiden → Entscheidung), eksiz kök (beginnen → Beginn), ünlü değişimi (ankommen → Ankunft, verlieren → Verlust) ya da isim olarak mastar (das Lernen).',
            '-ung, Stamm, Infinitiv.'
          ),
          examples: [
            { de: 'Wir warten auf die **Entscheidung** des Chefs.', translation: l('We are waiting for the boss’s decision.', 'Patronun kararını bekliyoruz.', '') },
            { de: '**Nach der Ankunft** gehen wir essen.', translation: l('After arriving we’ll go and eat.', 'Varıştan sonra yemeğe gidiyoruz.', '') },
          ],
        },
        {
          title: l('When to use which style', 'Hangi üslup ne zaman', 'Welcher Stil wann?'),
          body: l(
            'Nominal style: official letters, contracts, instructions, science – compact but heavy. Verbal style: conversation, emails to friends, stories – lively and easy. At B2 you should understand the first and use both appropriately.',
            'İsim üslubu: resmî mektuplar, sözleşmeler, talimatlar, bilim – yoğun ama ağır. Fiil üslubu: sohbet, arkadaşlara e-posta, hikâyeler – canlı ve kolay. B2’de ilkini anlamalı, ikisini de yerinde kullanmalısın.',
            'formell vs. alltäglich.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Nadia reads a letter from the immigration office with her neighbour Peter.', 'Nadia, göçmenlik dairesinden gelen bir mektubu komşusu Peter ile okuyor.', 'Ein Brief vom Amt.'),
      dialogue: [
        { speaker: 'Nadia', de: 'Hier steht: „**Nach Prüfung** Ihrer Unterlagen erfolgt die **Ausstellung** des Aufenthaltstitels.“ Hilfe!', translation: l('It says: „After examination of your documents, the residence permit will be issued.“ Help!', 'Burada yazıyor: „Belgeleriniz incelendikten sonra oturum izni düzenlenecek.“ İmdat!', '') },
        { speaker: 'Peter', de: 'Ganz einfach: **Nachdem** sie deine Unterlagen **geprüft haben**, **stellen** sie den Titel **aus**.', translation: l('Very simple: after they have checked your documents, they’ll issue the permit.', 'Çok basit: belgelerini kontrol ettikten sonra izni düzenleyecekler.', '') },
        { speaker: 'Nadia', de: 'Ah! Und: „**Bei Fragen** wenden Sie sich an …“?', translation: l('Ah! And: „In case of questions please contact …“?', 'Ha! Peki: „Sorularınız olursa … başvurun“?', '') },
        { speaker: 'Peter', de: '**Wenn** du Fragen **hast**, kannst du dort anrufen.', translation: l('If you have questions, you can call there.', 'Sorun olursa oraya arayabilirsin.', '') },
        { speaker: 'Nadia', de: 'Warum schreiben die nicht einfach so?', translation: l('Why don’t they just write it like that?', 'Neden öyle basitçe yazmıyorlar ki?', '') },
        { speaker: 'Peter', de: '(lacht) Das fragen sich die Deutschen auch. **Zur Beruhigung**: Du verstehst es jetzt!', translation: l('(laughs) Germans ask themselves that too. To reassure you: you understand it now!', '(güler) Almanlar da bunu soruyor. İçin rahat olsun: artık anlıyorsun!', '') },
      ],
      examples: [
        { de: '**Nach der Ankunft** des Zuges …', translation: l('After the train’s arrival …', 'Trenin varışından sonra …', '') },
        { de: '**Wegen des Streiks** fahren keine Busse.', translation: l('Because of the strike no buses are running.', 'Grev yüzünden otobüs çalışmıyor.', '') },
        { de: '**Trotz der Kälte** gingen wir raus.', translation: l('Despite the cold we went out.', 'Soğuğa rağmen dışarı çıktık.', '') },
        { de: '**Bei Regen** fällt das Fest aus.', translation: l('If it rains, the party is cancelled.', 'Yağmur yağarsa şenlik iptal.', '') },
        { de: '**Zur Verbesserung** der Luft …', translation: l('To improve the air …', 'Havayı iyileştirmek için …', '') },
        { de: '**Durch regelmäßiges Üben** wird man besser.', translation: l('Through regular practice you get better.', 'Düzenli pratikle daha iyi olunur.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Nouns, prepositions and style.', 'İsimler, edatlar ve üslup.', 'Nomen und Präpositionen.'),
      exercises: ['match-nomen', 'sort-praep', 'nom-ankunft', 'nom-abfahrt', 'mc-zur', 'tf-genitiv', 'select-nominal', 'image-amt', 'nom-regen'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Switch between the two styles.', 'İki üslup arasında geçiş yap.', 'Stile wechseln.'),
      exercises: [
        'fill-durch',
        'fill-beginn',
        'fill-teilnahme',
        'build-nach',
        'build-trotz',
        'build-verbal',
        'fix-genitiv',
        'fix-wegen',
        'fix-bei',
        'tr-nach',
        'tr-verbal',
        'ordering-brief',
        'dialog-erklaeren',
        'dialog-stil',
        'nom-studium',
        'nom-preise',
        'nom-fragen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Library rules in nominal style.', 'İsim üslubunda kütüphane kuralları.', 'Benutzungshinweise.'),
      passage: [
        '**Benutzungshinweise der Stadtbibliothek**',
        '**Zur Anmeldung** ist ein gültiger Ausweis vorzulegen. **Nach Erhalt** des Bibliotheksausweises ist die **Ausleihe** von bis zu 20 Medien möglich.',
        'Die Leihfrist beträgt vier Wochen. Eine **Verlängerung** ist **vor Ablauf** der Leihfrist online möglich.',
        '**Bei Überschreitung** der Frist wird eine Gebühr erhoben. **Bei Verlust** eines Mediums wird der Wiederbeschaffungswert berechnet.',
      ],
      glossary: [
        { de: 'vorlegen', note: l('to present', 'ibraz etmek', 'zeigen') },
        { de: 'die Leihfrist', note: l('loan period', 'ödünç süresi', 'Zeit zum Ausleihen') },
        { de: 'die Überschreitung', note: l('exceeding', 'aşma', 'zu lange') },
        { de: 'der Wiederbeschaffungswert', note: l('replacement value', 'yerine koyma bedeli', 'Preis für ein neues') },
      ],
      exercises: ['read-was', 'read-ausweis', 'read-verlust', 'read-verlaengern'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Nominal style in announcements.', 'Anonslarda isim üslubu.', 'Nominalstil in Durchsagen.'),
      exercises: ['listen-bahn', 'listen-praxis', 'listen-zur', 'listen-trotz'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Explain an official text (letter, contract, notice) in simple words to a friend.', 'Resmî bir metni (mektup, sözleşme, duyuru) arkadaşına basit kelimelerle açıkla.', 'Erkläre einen Behördentext.'),
      points: [
        l('Read one nominal sentence aloud.', 'İsim üslubundaki bir cümleyi yüksek sesle oku.', 'vorlesen'),
        l('Rephrase it with a conjunction (wenn, nachdem, weil).', 'Bir bağlaçla yeniden ifade et (wenn, nachdem, weil).', 'umformulieren'),
        l('Explain what the person has to do.', 'Kişinin ne yapması gerektiğini açıkla.', 'Was tun?'),
        l('Say what you think of this style.', 'Bu üslup hakkında ne düşündüğünü söyle.', 'Meinung'),
      ],
      model: [
        'Im Mietvertrag steht: „Bei Auszug ist die Wohnung in renoviertem Zustand zu übergeben.“',
        'Das heißt: Wenn du ausziehst, musst du die Wohnung renovieren.',
        'Du musst also streichen, bevor du den Schlüssel abgibst.',
        'Ich finde den Nominalstil sehr anstrengend, aber man gewöhnt sich daran.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short official notice (at least 5 sentences) for your building, sports club or office – in nominal style.',
        'Binan, spor kulübün ya da ofisin için isim üslubunda kısa bir resmî duyuru yaz (en az 5 cümle).',
        'Schreib eine Mitteilung im Nominalstil (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('A preposition + noun instead of a clause (bei, nach, vor, wegen, trotz, zur …)', 'Yan cümle yerine edat + isim (bei, nach, vor, wegen, trotz, zur …)', 'Präposition + Nomen'), pattern: '\\b([Bb]ei|[Nn]ach|[Vv]or|[Ww]egen|[Tt]rotz|[Zz]ur|[Zz]um|[Aa]ufgrund|[Ww]ährend)\\s+(\\p{Ll}+\\s+)?\\p{Lu}' },
        { label: l('A noun in -ung', '-ung ile biten bir isim', '-ung'), pattern: '\\p{Lu}\\p{Ll}+ung\\b' },
        { label: l('A genitive (des / der …)', 'Bir Genitiv (des / der …)', 'Genitiv'), pattern: '\\b(des|eines|der)\\s+(\\p{Ll}+\\s+)?\\p{Lu}\\p{Ll}+(s|es)?\\b' },
      ],
      model: [
        'Liebe Mitglieder, wegen der Renovierung der Halle bleibt das Studio vom 1. bis 14. August geschlossen.',
        'Während der Schließung finden alle Kurse im Park statt.',
        'Bei schlechtem Wetter entfallen die Kurse leider.',
        'Nach Abschluss der Arbeiten erwartet Sie eine neue Umkleide.',
        'Zur Information der Mitglieder hängt ein Plan am Eingang.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Clause → nominal style – 60 seconds.', 'Cümle → isim üslubu – 60 saniye.', 'Nominalstil – 60 Sekunden.'),
      seconds: 60,
      pool: [...NOM.map(([id]) => `nom-${id}`), 'mc-zur'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Nouns from verbs: -ung, stem, vowel change (Ankunft, Verlust)', 'Fiilden isim: -ung, kök, ünlü değişimi (Ankunft, Verlust)', 'Nominalisierung'),
      l('Conjunction → preposition: nachdem → nach, weil → wegen, obwohl → trotz, wenn → bei', 'Bağlaç → edat: nachdem → nach, weil → wegen, obwohl → trotz, wenn → bei', 'Präpositionen'),
      l('um … zu → zur / zum, indem → durch', 'um … zu → zur / zum, indem → durch', 'Zweck und Mittel'),
      l('Nominal style for official texts, verbal style for everyday life', 'Resmî metinler için isim üslubu, günlük hayat için fiil üslubu', 'Stil'),
    ],
    mistakes: [
      { wrong: 'die Entscheidung der Direktor', right: 'die Entscheidung des Direktors', note: l('Genitive.', 'Genitiv.', 'Genitiv.') },
      { wrong: 'Wegen der Zug Verspätung hatte …', right: 'Wegen der Verspätung des Zuges …', note: l('Don’t mix clause and phrase.', 'Cümle ve öbeği karıştırma.', 'nicht mischen.') },
      { wrong: 'bei schlecht Wetter', right: 'bei schlechtem Wetter', note: l('Dative ending.', 'Dativ eki.', 'Dativ.') },
      { wrong: 'trotz die hohen Preise', right: 'trotz der hohen Preise', note: l('trotz + genitive.', 'trotz + Genitiv.', 'Genitiv.') },
    ],
  },
}
