import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Erörterung', emoji: '📝', translation: l('argumentative essay', 'tartışmacı deneme', 'Text mit Pro und Contra'), example: 'In der Prüfung schreibt man eine kurze Erörterung.' },
  { word: 'In letzter Zeit wird oft diskutiert, ob …', emoji: '🗞️', translation: l('Recently there has often been discussion about whether …', 'Son zamanlarda sık sık … tartışılıyor', 'Einleitung'), example: 'In letzter Zeit wird oft diskutiert, ob Handys in Schulen verboten werden sollten.' },
  { word: 'Ein wichtiges Argument dafür ist …', emoji: '➕', translation: l('An important argument for it is …', 'Bunun lehine önemli bir argüman …', 'Pro-Argument'), example: 'Ein wichtiges Argument dafür ist der Umweltschutz.' },
  { word: 'Dagegen spricht, dass …', emoji: '➖', translation: l('What speaks against it is that …', 'Buna karşı olan şey, …', 'Contra-Argument'), example: 'Dagegen spricht, dass es sehr teuer ist.' },
  { word: 'Hinzu kommt, dass …', emoji: '➕➕', translation: l('In addition, …', 'Buna ek olarak …', 'weiteres Argument'), example: 'Hinzu kommt, dass viele Jobs entstehen würden.' },
  { word: 'zum Beispiel / beispielsweise', emoji: '💡', translation: l('for example', 'örneğin', 'Beispiel'), example: 'In Dänemark gibt es beispielsweise schon solche Regeln.' },
  { word: 'Einerseits … andererseits', emoji: '⚖️', translation: l('on the one hand … on the other', 'bir yandan … öte yandan', 'abwägen'), example: 'Einerseits spart man Zeit, andererseits fehlt der Kontakt.' },
  { word: 'abwägen', emoji: '⚖️', translation: l('to weigh up', 'tartmak', 'vergleichen'), example: 'Wägt man alle Argumente ab, überwiegen die Vorteile.' },
  { word: 'überwiegen', emoji: '🏋️', translation: l('to predominate', 'ağır basmak', 'stärker sein'), example: 'Meiner Meinung nach überwiegen die Nachteile.' },
  { word: 'Abschließend lässt sich sagen, dass …', emoji: '🏁', translation: l('In conclusion it can be said that …', 'Sonuç olarak … söylenebilir', 'Schluss'), example: 'Abschließend lässt sich sagen, dass es keine einfache Lösung gibt.' },
  { word: 'das Gegenargument', emoji: '🔁', translation: l('counter-argument', 'karşı argüman', 'Argument dagegen'), example: 'Ein häufiges Gegenargument sind die Kosten.' },
  { word: 'die These', emoji: '📌', translation: l('thesis, claim', 'tez', 'Behauptung'), example: 'Die These lautet: Homeoffice macht produktiver.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Erörterung', gender: 'f', plural: 'die Erörterungen', translation: l('argumentative essay', 'tartışmacı deneme', 'Erörterung') },
  { word: 'Argument', gender: 'n', plural: 'die Argumente', translation: l('argument', 'argüman', 'Argument') },
  { word: 'Gegenargument', gender: 'n', plural: 'die Gegenargumente', translation: l('counter-argument', 'karşı argüman', 'Gegenargument') },
  { word: 'These', gender: 'f', plural: 'die Thesen', translation: l('thesis', 'tez', 'These') },
  { word: 'Einleitung', gender: 'f', plural: 'die Einleitungen', translation: l('introduction', 'giriş', 'Einleitung') },
  { word: 'Schluss', gender: 'm', plural: 'die Schlüsse', translation: l('conclusion', 'sonuç', 'Schluss') },
  { word: 'Beleg', gender: 'm', plural: 'die Belege', translation: l('evidence', 'kanıt', 'Beleg') },
  { word: 'Standpunkt', gender: 'm', plural: 'die Standpunkte', translation: l('point of view', 'bakış açısı', 'Standpunkt') },
]

const PARTS = ['Einleitung', 'Hauptteil (Argument)', 'Schluss'] as const

/** [id, phrase, index of part] */
const ERO: [string, string, 0 | 1 | 2][] = [
  ['letzter-zeit', 'In letzter Zeit wird immer häufiger diskutiert, ob …', 0],
  ['argument', 'Ein wichtiges Argument dafür ist, dass …', 1],
  ['abschliessend', 'Abschließend lässt sich sagen, dass …', 2],
  ['frage', 'Viele Menschen stellen sich die Frage, ob …', 0],
  ['hinzu', 'Hinzu kommt, dass …', 1],
  ['abwaegen', 'Wägt man alle Argumente ab, so …', 2],
]

function eroDrills(): Exercise[] {
  return ERO.map(([id, phrase, right], i) => {
    const options = [...PARTS]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `ero-${id}`,
      type: 'multiple_choice' as const,
      topic: 'aufbau',
      concept: 'essay-parts',
      skill: 'writing' as const,
      difficulty: 2 as const,
      prompt: `„${phrase}“ – In welchen Teil passt das?`,
      options: ordered,
      answer: ordered.indexOf(PARTS[right]),
      explanation: l(`→ ${PARTS[right]}`, `→ ${PARTS[right]}`, `→ ${PARTS[right]}`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-redemittel',
    type: 'matching',
    topic: 'redemittel',
    concept: 'functions',
    skill: 'writing',
    difficulty: 2,
    instructions: l('Match the phrase and its function.', 'İfadeyi işleviyle eşleştir.', 'Redemittel und Funktion.'),
    pairs: [
      { left: 'Ein wichtiges Argument dafür ist …', right: 'Pro-Argument' },
      { left: 'Dagegen spricht, dass …', right: 'Contra-Argument' },
      { left: 'Hinzu kommt, dass …', right: 'weiteres Argument' },
      { left: 'beispielsweise', right: 'Beispiel' },
      { left: 'Abschließend …', right: 'Schluss' },
    ],
    explanation: l('Each part of the essay has typical phrases.', 'Denemenin her bölümünün tipik ifadeleri vardır.', 'Redemittel.'),
  },
  {
    id: 'sort-pro-contra',
    type: 'categorize',
    topic: 'argumente',
    concept: 'pro-contra',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Topic: „A four-day working week for everyone?“ – pro or contra?', 'Konu: „Herkes için dört günlük çalışma haftası?“ – lehte mi aleyhte mi?', 'Vier-Tage-Woche: Pro oder Contra?'),
    categories: ['Pro', 'Contra'],
    items: [
      { text: 'Mitarbeiter sind erholter und motivierter.', category: 0 },
      { text: 'In Krankenhäusern ist das kaum umsetzbar.', category: 1 },
      { text: 'Man hat mehr Zeit für die Familie.', category: 0 },
      { text: 'Die Arbeitstage werden länger und anstrengender.', category: 1 },
      { text: 'Studien zeigen eine höhere Produktivität.', category: 0 },
      { text: 'Kleine Firmen können sich das nicht leisten.', category: 1 },
    ],
    explanation: l('Collect pro and contra arguments before you write.', 'Yazmadan önce lehte ve aleyhte argümanları topla.', 'Argumente sammeln.'),
    practice: ['ero-letzter-zeit'],
  },
  {
    id: 'mc-dagegen',
    type: 'multiple_choice',
    topic: 'redemittel',
    concept: 'contra',
    skill: 'grammar',
    difficulty: 2,
    prompt: '___ spricht, dass die Umstellung sehr viel Geld kostet.',
    options: ['Dagegen', 'Deshalb', 'Darum'],
    answer: 0,
    explanation: l('Contra argument: Dagegen spricht, dass …', 'Aleyhte argüman: Dagegen spricht, dass …', 'Dagegen.'),
    examples: ['**Dagegen** spricht, dass …'],
    practice: ['fill-hinzu'],
  },
  {
    id: 'tf-meinung',
    type: 'true_false',
    topic: 'aufbau',
    concept: 'structure',
    skill: 'writing',
    difficulty: 2,
    statement: 'In einer dialektischen Erörterung nennt man zuerst die Argumente der Gegenseite und erst am Ende die eigene Meinung.',
    answer: true,
    explanation: l('Typically: introduction → counter-arguments → own arguments → conclusion with your opinion.', 'Tipik olarak: giriş → karşı argümanlar → kendi argümanların → fikrinle sonuç.', 'Aufbau.'),
  },
  {
    id: 'select-belege',
    type: 'multiple_select',
    topic: 'argumente',
    concept: 'support',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Which sentences support an argument with evidence or an example? Select all.', 'Hangi cümleler bir argümanı kanıt ya da örnekle destekliyor? Hepsini seç.', 'Welche Sätze belegen ein Argument?'),
    options: ['Eine Studie aus Island zeigt beispielsweise, dass …', 'So haben etwa in Dänemark viele Firmen gute Erfahrungen gemacht.', 'Das finde ich einfach blöd.', 'Laut Statistik ist die Zahl um 20 Prozent gestiegen.', 'Ich weiß nicht.'],
    answers: [0, 1, 3],
    explanation: l('Good arguments: claim + reason + example / evidence.', 'İyi argüman: iddia + sebep + örnek / kanıt.', 'Belege.'),
  },
  {
    id: 'image-waage',
    type: 'image_choice',
    topic: 'argumente',
    concept: 'weigh',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Wenn man alle Argumente abwägt, überwiegen die Vorteile.',
    options: [
      { emoji: '⚖️', label: 'abwägen' },
      { emoji: '🎲', label: 'raten' },
      { emoji: '🎨', label: 'malen' },
      { emoji: '🏃', label: 'laufen' },
    ],
    answer: 0,
    explanation: l('abwägen = to weigh up.', 'abwägen = tartmak.', 'abwägen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-hinzu',
    type: 'fill_blank',
    topic: 'redemittel',
    concept: 'adding',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: '___ kommt, dass Pendler viel Zeit im Stau verlieren.',
    accepted: ['Hinzu', 'Dazu'],
    base: 'weiteres Argument',
    explanation: l('Hinzu kommt, dass … = in addition.', 'Hinzu kommt, dass … = buna ek olarak.', 'Hinzu.'),
    examples: ['**Hinzu** kommt, dass …'],
  },
  {
    id: 'fill-ueberwiegen',
    type: 'fill_blank',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Meiner Meinung nach ___ die Vorteile deutlich.',
    accepted: ['überwiegen'],
    base: 'stärker sein',
    explanation: l('überwiegen = to outweigh / predominate.', 'überwiegen = ağır basmak.', 'überwiegen.'),
    examples: ['Meiner Meinung nach **überwiegen** die Vorteile.'],
  },
  {
    id: 'fill-diskutiert',
    type: 'fill_blank',
    topic: 'einleitung',
    concept: 'intro',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'In letzter Zeit wird oft ___, ob man Fleisch höher besteuern sollte. (diskutieren)',
    accepted: ['diskutiert'],
    base: 'Passiv',
    explanation: l('Impersonal passive: Es wird diskutiert, ob …', 'Öznesiz edilgen: Es wird diskutiert, ob …', 'diskutiert.'),
    examples: ['In letzter Zeit wird oft **diskutiert**, ob …'],
  },
  {
    id: 'build-einleitung',
    type: 'sentence_builder',
    topic: 'einleitung',
    concept: 'intro',
    skill: 'writing',
    difficulty: 3,
    chips: ['ob', 'Viele fragen sich,', 'abgeschafft werden sollten', 'Hausaufgaben'],
    answers: [['Viele fragen sich,', 'ob', 'Hausaufgaben', 'abgeschafft werden sollten']],
    translation: l('Many people wonder whether homework should be abolished.', 'Birçok kişi ödevlerin kaldırılıp kaldırılmaması gerektiğini merak ediyor.', 'Viele fragen sich, ob Hausaufgaben abgeschafft werden sollten.'),
    explanation: l('Introduce the question with ob.', 'Soruyu ob ile tanıt.', 'ob.'),
    examples: ['Viele fragen sich, **ob** Hausaufgaben abgeschafft werden sollten.'],
  },
  {
    id: 'build-argument',
    type: 'sentence_builder',
    topic: 'argumente',
    concept: 'pro-contra',
    skill: 'writing',
    difficulty: 3,
    chips: ['ist,', 'Ein wichtiges Argument dafür', 'dass Kinder mehr Freizeit hätten'],
    answers: [['Ein wichtiges Argument dafür', 'ist,', 'dass Kinder mehr Freizeit hätten']],
    translation: l('An important argument for it is that children would have more free time.', 'Bunun lehine önemli bir argüman, çocukların daha fazla boş zamanı olacağıdır.', 'Ein wichtiges Argument dafür ist, dass Kinder mehr Freizeit hätten.'),
    explanation: l('Argument + dass-clause.', 'Argüman + dass cümlesi.', 'dass.'),
    examples: ['Ein wichtiges Argument dafür **ist, dass** …'],
  },
  {
    id: 'build-schluss',
    type: 'sentence_builder',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'writing',
    difficulty: 3,
    chips: ['lässt sich sagen,', 'Abschließend', 'dass es Kompromisse braucht'],
    answers: [['Abschließend', 'lässt sich sagen,', 'dass es Kompromisse braucht']],
    translation: l('In conclusion it can be said that compromises are needed.', 'Sonuç olarak uzlaşmaların gerektiği söylenebilir.', 'Abschließend lässt sich sagen, dass es Kompromisse braucht.'),
    explanation: l('Typical conclusion phrase.', 'Tipik sonuç ifadesi.', 'Abschließend.'),
    examples: ['**Abschließend lässt sich sagen**, dass …'],
  },
  {
    id: 'fix-dafuer',
    type: 'error_correction',
    topic: 'redemittel',
    concept: 'pro',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Für spricht, dass man Geld spart.',
    accepted: ['Dafür spricht, dass man Geld spart.'],
    explanation: l('da-word: Dafür spricht / Dagegen spricht.', 'da-kelimesi: Dafür spricht / Dagegen spricht.', 'Dafür.'),
    examples: ['**Dafür** spricht, dass man Geld spart.'],
  },
  {
    id: 'fix-ich',
    type: 'error_correction',
    topic: 'aufbau',
    concept: 'style',
    skill: 'writing',
    difficulty: 3,
    sentence: 'Ich denke, Handys sind doof und ich finde das schlecht.',
    accepted: ['Meiner Meinung nach überwiegen die Nachteile von Handys in der Schule.', 'Meiner Meinung nach haben Handys in der Schule mehr Nachteile als Vorteile.'],
    explanation: l('In an essay: objective, precise language instead of „doof“.', 'Denemede: „doof“ yerine nesnel, kesin dil.', 'sachlich formulieren.'),
    examples: ['Meiner Meinung nach **überwiegen die Nachteile**.'],
  },
  {
    id: 'fix-einerseits',
    type: 'error_correction',
    topic: 'argumente',
    concept: 'weigh',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Einerseits das ist praktisch, andererseits es ist teuer.',
    accepted: ['Einerseits ist das praktisch, andererseits ist es teuer.'],
    explanation: l('Verb right after einerseits / andererseits.', 'einerseits / andererseits’ten hemen sonra fiil.', 'ist das / ist es.'),
    examples: ['Einerseits **ist** das praktisch, andererseits **ist** es teuer.'],
  },
  {
    id: 'tr-dagegen',
    type: 'translation',
    topic: 'redemittel',
    concept: 'contra',
    skill: 'writing',
    difficulty: 3,
    source: l('What speaks against it is that it is very expensive.', 'Buna karşı olan şey çok pahalı olması.', 'What speaks against it is that it is very expensive.'),
    accepted: ['Dagegen spricht, dass es sehr teuer ist.'],
    explanation: l('Dagegen spricht, dass …', 'Dagegen spricht, dass …', 'Dagegen spricht.'),
    examples: ['**Dagegen spricht**, dass es sehr teuer ist.'],
  },
  {
    id: 'tr-abschliessend',
    type: 'translation',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'writing',
    difficulty: 3,
    source: l('In conclusion, the advantages outweigh the disadvantages.', 'Sonuç olarak avantajlar dezavantajlardan ağır basıyor.', 'In conclusion, the advantages outweigh the disadvantages.'),
    accepted: ['Abschließend lässt sich sagen, dass die Vorteile überwiegen.', 'Abschließend überwiegen die Vorteile.', 'Zusammenfassend lässt sich sagen, dass die Vorteile überwiegen.'],
    explanation: l('Abschließend lässt sich sagen, dass die Vorteile überwiegen.', 'Abschließend lässt sich sagen, dass die Vorteile überwiegen.', 'überwiegen.'),
    examples: ['Abschließend lässt sich sagen, dass die Vorteile **überwiegen**.'],
  },
  {
    id: 'ordering-erorterung',
    type: 'ordering',
    topic: 'aufbau',
    concept: 'structure',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order the paragraphs of the essay.', 'Denemenin paragraflarını sırala.', 'Ordne die Erörterung.'),
    items: ['Andererseits sprechen die hohen Kosten dagegen.', 'In letzter Zeit wird oft diskutiert, ob der Nahverkehr kostenlos sein sollte.', 'Abschließend lässt sich sagen, dass ein günstiges Ticket ein guter Kompromiss wäre.', 'Einerseits würden mehr Menschen Bus und Bahn nutzen.'],
    answer: ['In letzter Zeit wird oft diskutiert, ob der Nahverkehr kostenlos sein sollte.', 'Einerseits würden mehr Menschen Bus und Bahn nutzen.', 'Andererseits sprechen die hohen Kosten dagegen.', 'Abschließend lässt sich sagen, dass ein günstiges Ticket ein guter Kompromiss wäre.'],
    explanation: l('Introduction → pro → contra → conclusion.', 'Giriş → lehte → aleyhte → sonuç.', 'Aufbau.'),
  },
  {
    id: 'dialog-gegenargument',
    type: 'dialogue',
    topic: 'argumente',
    concept: 'counter',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Lehrerin', de: 'Welches Gegenargument könnte man gegen ein Tempolimit auf der Autobahn nennen?' }],
    options: ['Dagegen spricht, dass viele Autofahrer die Freiheit schätzen, schnell zu fahren.', 'Ein Tempolimit ist ein Auto.', 'Dagegen ist dafür.'],
    answer: 0,
    explanation: l('Counter-argument with Dagegen spricht, dass …', 'Dagegen spricht, dass … ile karşı argüman.', 'Gegenargument.'),
  },
  {
    id: 'dialog-beispiel',
    type: 'dialogue',
    topic: 'argumente',
    concept: 'support',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Prüfer', de: 'Können Sie Ihr Argument mit einem Beispiel belegen?' }],
    options: ['Ja, in Luxemburg ist der Nahverkehr beispielsweise seit 2020 kostenlos.', 'Ja, Beispiel.', 'Nein, Argumente brauchen das nicht.'],
    answer: 0,
    explanation: l('Support with a concrete example: beispielsweise …', 'Somut bir örnekle destekle: beispielsweise …', 'Beleg.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-erorterung',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Welche Frage wird in der Erörterung diskutiert?',
    options: ['Ob es eine Pflicht zum sozialen Jahr geben sollte.', 'Ob man mehr Sport machen sollte.', 'Ob Schuluniformen schön sind.'],
    answer: 0,
    explanation: l('„… ob junge Menschen ein Pflichtjahr leisten sollten.“', '„… ob junge Menschen ein Pflichtjahr leisten sollten.“', 'soziales Jahr.'),
  },
  {
    id: 'read-pro',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-erorterung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welches Pro-Argument wird genannt?',
    options: ['Junge Menschen lernen Verantwortung.', 'Man verdient viel Geld.', 'Man kann reisen.'],
    answer: 0,
    explanation: l('„… lernen junge Menschen Verantwortung zu übernehmen.“', '„… lernen junge Menschen Verantwortung zu übernehmen.“', 'Verantwortung.'),
  },
  {
    id: 'read-contra',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-erorterung',
    skill: 'reading',
    difficulty: 2,
    statement: 'Ein Gegenargument ist, dass eine Pflicht die persönliche Freiheit einschränkt.',
    answer: true,
    explanation: l('„Dagegen spricht, dass eine Pflicht die persönliche Freiheit einschränkt.“', '„Dagegen spricht, dass eine Pflicht die persönliche Freiheit einschränkt.“', 'richtig.'),
  },
  {
    id: 'read-fazit',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-erorterung',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Zu welchem Ergebnis kommt der Autor?',
    options: ['Ein freiwilliges Jahr mit Anreizen ist besser als eine Pflicht.', 'Eine Pflicht ist die beste Lösung.', 'Man sollte das soziale Jahr abschaffen.'],
    answer: 0,
    explanation: l('„… ein freiwilliges Jahr mit besseren Anreizen der bessere Weg.“', '„… ein freiwilliges Jahr mit besseren Anreizen der bessere Weg.“', 'freiwillig.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-these',
    type: 'listening_choice',
    topic: 'einleitung',
    concept: 'intro',
    skill: 'listening',
    difficulty: 2,
    audio: 'Immer mehr Städte diskutieren, ob Autos aus der Innenstadt verbannt werden sollten.',
    question: l('What is being discussed?', 'Ne tartışılıyor?', 'Was wird diskutiert?'),
    options: ['banning cars from city centres', 'building more roads', 'cheaper petrol'],
    answer: 0,
    explanation: l('„Autos aus der Innenstadt verbannt“', '„Autos aus der Innenstadt verbannt“', 'autofrei.'),
  },
  {
    id: 'listen-hinzu',
    type: 'listening_choice',
    topic: 'redemittel',
    concept: 'adding',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ein Vorteil wäre die bessere Luft. Hinzu kommt, dass Kinder sicherer zur Schule gehen könnten.',
    question: l('What is the additional argument?', 'Ek argüman ne?', 'Welches Argument kommt hinzu?'),
    options: ['Children could walk to school more safely.', 'Shops would earn more.', 'Parking would be cheaper.'],
    answer: 0,
    explanation: l('„Hinzu kommt, dass Kinder sicherer zur Schule gehen könnten.“', '„Hinzu kommt, dass Kinder sicherer zur Schule gehen könnten.“', 'Kinder.'),
  },
  {
    id: 'listen-dagegen',
    type: 'listening_choice',
    topic: 'redemittel',
    concept: 'contra',
    skill: 'listening',
    difficulty: 2,
    audio: 'Dagegen spricht allerdings, dass ältere Menschen und Handwerker auf das Auto angewiesen sind.',
    question: l('Who depends on cars according to the speaker?', 'Konuşana göre kimler arabaya bağımlı?', 'Wer braucht das Auto?'),
    options: ['older people and tradespeople', 'students', 'tourists'],
    answer: 0,
    explanation: l('„ältere Menschen und Handwerker“', '„ältere Menschen und Handwerker“', 'Ältere, Handwerker.'),
  },
  {
    id: 'listen-fazit',
    type: 'listening_choice',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'listening',
    difficulty: 3,
    audio: 'Wägt man alle Argumente ab, so wäre eine autofreie Zone mit Ausnahmen für Lieferverkehr die beste Lösung.',
    question: l('What solution does the speaker propose?', 'Konuşan hangi çözümü öneriyor?', 'Welche Lösung?'),
    options: ['car-free zone with exceptions for deliveries', 'no changes', 'ban all vehicles'],
    answer: 0,
    explanation: l('„autofreie Zone mit Ausnahmen für Lieferverkehr“', '„autofreie Zone mit Ausnahmen für Lieferverkehr“', 'Kompromiss.'),
  },

  ...eroDrills(),
]

export const UNIT_B2_21_EROERTERUNG: CourseUnit = {
  level: 'B2',
  number: 21,
  slug: 'eroerterung',
  titleDe: 'Die Erörterung',
  title: l('The argumentative essay', 'Tartışmacı deneme', 'Die Erörterung'),
  goal: l(
    'By the end of this unit you can write a structured argumentative essay as in the B2 exam: introduce the question, present pro and contra arguments with examples, weigh them up and draw a conclusion.',
    'Bu ünitenin sonunda B2 sınavındaki gibi yapılandırılmış bir tartışmacı deneme yazabilirsin: soruyu tanıt, lehte ve aleyhte argümanları örneklerle sun, tart ve bir sonuca var.',
    'Am Ende dieser Einheit schreibst du eine Erörterung.'
  ),
  minutes: [25, 30],
  topics: [
    { key: 'aufbau', label: l('Structure', 'Yapı', 'Aufbau') },
    { key: 'einleitung', label: l('Introduction', 'Giriş', 'Einleitung') },
    { key: 'argumente', label: l('Arguments & evidence', 'Argümanlar ve kanıtlar', 'Argumente') },
    { key: 'redemittel', label: l('Linking phrases', 'Bağlantı ifadeleri', 'Redemittel') },
    { key: 'schluss', label: l('Conclusion', 'Sonuç', 'Schluss') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The toolkit for argumentative writing.', 'Tartışmacı yazı için araç seti.', 'Werkzeuge für die Erörterung.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Structure', 'Yapı', 'Aufbau'),
          body: l(
            'Introduction: present the topic and the question (In letzter Zeit wird oft diskutiert, ob …). Main part: arguments for and against, each with reason + example. Conclusion: weigh up and give your opinion (Abschließend lässt sich sagen …).',
            'Giriş: konuyu ve soruyu sun (In letzter Zeit wird oft diskutiert, ob …). Ana bölüm: lehte ve aleyhte argümanlar, her biri sebep + örnekle. Sonuç: tart ve fikrini söyle (Abschließend lässt sich sagen …).',
            'Einleitung → Hauptteil → Schluss.'
          ),
          table: {
            head: [l('Part', 'Bölüm', 'Teil'), l('Phrase', 'İfade', 'Redemittel')],
            rows: [
              ['Einleitung', 'Viele fragen sich, ob …'],
              ['Pro', 'Dafür spricht, dass …'],
              ['Contra', 'Dagegen spricht, dass …'],
              ['Schluss', 'Abschließend …'],
            ],
          },
        },
        {
          title: l('A strong argument', 'Güçlü bir argüman', 'Ein starkes Argument'),
          body: l(
            'Claim (These) + reason (Begründung, weil / denn) + example or evidence (Beispiel, beispielsweise, eine Studie zeigt …). Link arguments with: außerdem, hinzu kommt, darüber hinaus, ein weiterer Punkt ist …',
            'İddia (These) + sebep (Begründung, weil / denn) + örnek ya da kanıt (Beispiel, beispielsweise, eine Studie zeigt …). Argümanları bağla: außerdem, hinzu kommt, darüber hinaus, ein weiterer Punkt ist …',
            'These + Begründung + Beispiel.'
          ),
          examples: [
            { de: '**Dafür spricht, dass** Kinder mehr Freizeit hätten. **Beispielsweise** …', translation: l('What speaks for it is that children would have more free time. For example …', 'Bunun lehine olan şey çocukların daha fazla boş zamanı olması. Örneğin …', '') },
            { de: '**Hinzu kommt, dass** …', translation: l('In addition …', 'Buna ek olarak …', '') },
          ],
        },
        {
          title: l('Objective style', 'Nesnel üslup', 'Sachlicher Stil'),
          body: l(
            'Avoid colloquial words (doof, krass) and too much „ich“ in the main part. Use man, the passive and impersonal phrases: Es lässt sich feststellen … / Man darf nicht vergessen … Your own opinion belongs in the conclusion.',
            'Ana bölümde günlük kelimelerden (doof, krass) ve fazla „ich“ten kaçın. man, edilgen ve kişisiz ifadeler kullan: Es lässt sich feststellen … / Man darf nicht vergessen … Kendi fikrin sonuç bölümüne aittir.',
            'sachlich, unpersönlich.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two course participants prepare an essay together.', 'İki kursiyer birlikte bir deneme hazırlıyor.', 'Wir planen eine Erörterung.'),
      dialogue: [
        { speaker: 'Amir', de: 'Unser Thema: „Sollte Fleisch höher besteuert werden?“ Wie fangen wir an?', translation: l('Our topic: „Should meat be taxed more heavily?“ How do we start?', 'Konumuz: „Et daha yüksek vergilendirilmeli mi?“ Nasıl başlayalım?', '') },
        { speaker: 'Nele', de: 'Mit der Einleitung: „**In letzter Zeit wird oft diskutiert, ob** …“', translation: l('With the introduction: „Recently it has often been discussed whether …“', 'Girişle: „Son zamanlarda sık sık … tartışılıyor …“', '') },
        { speaker: 'Amir', de: 'Gut. **Dafür spricht**, dass weniger Fleisch gut fürs Klima wäre.', translation: l('Good. What speaks for it is that less meat would be good for the climate.', 'İyi. Lehte olan, daha az etin iklim için iyi olacağı.', '') },
        { speaker: 'Nele', de: 'Und ein **Beleg**? **Beispielsweise** verursacht Rindfleisch viel CO₂.', translation: l('And evidence? For example, beef causes a lot of CO₂.', 'Kanıt? Örneğin sığır eti çok CO₂ üretiyor.', '') },
        { speaker: 'Amir', de: '**Dagegen spricht**, dass Familien mit wenig Geld stärker belastet würden.', translation: l('What speaks against it is that families with little money would be burdened more.', 'Aleyhte olan, az paralı ailelerin daha fazla yük altına girmesi.', '') },
        { speaker: 'Nele', de: 'Genau. Und **abschließend** wägen wir ab und sagen unsere Meinung.', translation: l('Exactly. And finally we weigh it up and give our opinion.', 'Aynen. Son olarak tartıp fikrimizi söyleriz.', '') },
      ],
      examples: [
        { de: '**In letzter Zeit wird oft diskutiert, ob** …', translation: l('Recently it has often been discussed whether …', 'Son zamanlarda … sık sık tartışılıyor.', '') },
        { de: '**Dafür spricht, dass** …', translation: l('What speaks for it is that …', 'Lehte olan şey …', '') },
        { de: '**Dagegen spricht, dass** …', translation: l('What speaks against it is that …', 'Aleyhte olan şey …', '') },
        { de: '**Hinzu kommt, dass** …', translation: l('In addition …', 'Buna ek olarak …', '') },
        { de: '**Wägt man alle Argumente ab**, …', translation: l('Weighing up all arguments, …', 'Tüm argümanlar tartıldığında …', '') },
        { de: '**Abschließend lässt sich sagen, dass** …', translation: l('In conclusion it can be said that …', 'Sonuç olarak … söylenebilir.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which phrase belongs where?', 'Hangi ifade nereye ait?', 'Welcher Teil?'),
      exercises: ['match-redemittel', 'sort-pro-contra', 'ero-letzter-zeit', 'ero-argument', 'ero-abschliessend', 'mc-dagegen', 'tf-meinung', 'select-belege', 'image-waage'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Build an essay step by step.', 'Bir denemeyi adım adım kur.', 'Schritt für Schritt.'),
      exercises: [
        'fill-hinzu',
        'fill-ueberwiegen',
        'fill-diskutiert',
        'build-einleitung',
        'build-argument',
        'build-schluss',
        'fix-dafuer',
        'fix-ich',
        'fix-einerseits',
        'tr-dagegen',
        'tr-abschliessend',
        'ordering-erorterung',
        'dialog-gegenargument',
        'dialog-beispiel',
        'ero-frage',
        'ero-hinzu',
        'ero-abwaegen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A model essay.', 'Örnek bir deneme.', 'Eine Mustererörterung.'),
      passage: [
        '**Soziales Pflichtjahr für alle?** – In letzter Zeit wird oft diskutiert, ob junge Menschen nach der Schule ein Pflichtjahr in sozialen Einrichtungen leisten sollten.',
        '**Dafür spricht**, dass junge Menschen dabei lernen, Verantwortung zu übernehmen. **Hinzu kommt**, dass Pflegeheime und Krankenhäuser dringend Unterstützung brauchen.',
        '**Dagegen spricht**, dass eine Pflicht die persönliche Freiheit einschränkt. Außerdem würde sich der Start in Studium oder Beruf verzögern.',
        '**Wägt man alle Argumente ab**, ist meiner Meinung nach ein freiwilliges Jahr mit besseren Anreizen der bessere Weg – etwa mit Geld oder Vorteilen bei der Studienplatzvergabe.',
      ],
      glossary: [
        { de: 'leisten', note: l('to do, complete (service)', 'yerine getirmek', 'machen, absolvieren') },
        { de: 'einschränken', note: l('to restrict', 'kısıtlamak', 'begrenzen') },
        { de: 'sich verzögern', note: l('to be delayed', 'gecikmek', 'später passieren') },
        { de: 'der Anreiz', note: l('incentive', 'teşvik', 'Motivation') },
      ],
      exercises: ['read-thema', 'read-pro', 'read-contra', 'read-fazit'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('An argument in four steps.', 'Dört adımda bir argüman.', 'Eine Argumentation hören.'),
      exercises: ['listen-these', 'listen-hinzu', 'listen-dagegen', 'listen-fazit'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present both sides of a topic in one minute: „Should school start later in the morning?“', 'Bir konunun iki tarafını bir dakikada sun: „Okul sabahları daha geç başlamalı mı?“', 'Pro und Contra in einer Minute.'),
      points: [
        l('Introduce the question.', 'Soruyu tanıt.', 'Frage'),
        l('One pro argument + example.', 'Bir lehte argüman + örnek.', 'Pro'),
        l('One contra argument.', 'Bir aleyhte argüman.', 'Contra'),
        l('Weigh up and conclude.', 'Tart ve sonuca bağla.', 'Fazit'),
      ],
      model: [
        'Viele fragen sich, ob die Schule morgens später beginnen sollte.',
        'Dafür spricht, dass Jugendliche biologisch später müde werden – Studien aus den USA zeigen bessere Noten bei späterem Beginn.',
        'Dagegen spricht, dass Eltern oft früh zur Arbeit müssen und der Nachmittag kürzer würde.',
        'Wägt man alle Argumente ab, wäre ein Beginn um 8:30 Uhr ein guter Kompromiss.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write an argumentative essay (at least 8 sentences): „Should public transport be free?“',
        'Tartışmacı bir deneme yaz (en az 8 cümle): „Toplu taşıma ücretsiz olmalı mı?“',
        'Erörterung: Kostenloser Nahverkehr? (mindestens 8 Sätze)'
      ),
      minSentences: 8,
      checks: [
        { label: l('An introduction (diskutiert, ob / fragen sich, ob)', 'Bir giriş (diskutiert, ob / fragen sich, ob)', 'Einleitung'), pattern: '(diskutiert, ob|fragen sich, ob|stellt sich die Frage, ob)' },
        { label: l('Pro and contra (Dafür … / Dagegen … spricht)', 'Lehte ve aleyhte (Dafür … / Dagegen … spricht)', 'Pro / Contra'), pattern: '(Dafür|dafür)[\\s\\S]*(Dagegen|dagegen)|(Dagegen|dagegen)[\\s\\S]*(Dafür|dafür)' },
        { label: l('An example (beispielsweise / zum Beispiel / etwa)', 'Bir örnek (beispielsweise / zum Beispiel / etwa)', 'Beispiel'), pattern: '([Bb]eispielsweise|[Zz]um Beispiel|\\betwa\\b|[Ss]o zeigt)' },
        { label: l('A conclusion (Abschließend / Wägt man … ab / Zusammenfassend)', 'Bir sonuç (Abschließend / Wägt man … ab / Zusammenfassend)', 'Schluss'), pattern: '(Abschließend|[Zz]usammenfassend|Wägt man)' },
      ],
      model: [
        'In letzter Zeit wird oft diskutiert, ob Bus und Bahn kostenlos sein sollten.',
        'Dafür spricht vor allem der Klimaschutz, denn mehr Menschen würden das Auto stehen lassen.',
        'Beispielsweise ist der Nahverkehr in Luxemburg seit 2020 gratis.',
        'Hinzu kommt, dass Menschen mit wenig Geld mobiler wären.',
        'Dagegen spricht jedoch, dass das System sehr viel Geld kostet.',
        'Außerdem sind viele Busse schon jetzt überfüllt.',
        'Wägt man alle Argumente ab, wäre ein sehr günstiges Monatsticket ein guter Kompromiss.',
        'Abschließend lässt sich sagen, dass Investitionen in mehr Busse wichtiger sind als ein kostenloser Fahrschein.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Introduction, argument or conclusion? – 60 seconds.', 'Giriş, argüman mı sonuç mu? – 60 saniye.', 'Welcher Teil? – 60 Sekunden.'),
      seconds: 60,
      pool: [...ERO.map(([id]) => `ero-${id}`), 'mc-dagegen'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Structure: introduction → pro → contra → conclusion', 'Yapı: giriş → lehte → aleyhte → sonuç', 'Aufbau'),
      l('Phrases: Dafür / Dagegen spricht, dass … · Hinzu kommt … · beispielsweise', 'İfadeler: Dafür / Dagegen spricht, dass … · Hinzu kommt … · beispielsweise', 'Redemittel'),
      l('Conclusion: Wägt man … ab · Abschließend lässt sich sagen …', 'Sonuç: Wägt man … ab · Abschließend lässt sich sagen …', 'Schluss'),
      l('Objective style: man, passive, no colloquial words', 'Nesnel üslup: man, edilgen, günlük kelimeler yok', 'Stil'),
    ],
    mistakes: [
      { wrong: 'Für spricht, dass …', right: 'Dafür spricht, dass …', note: l('da-word.', 'da-kelimesi.', 'Dafür.') },
      { wrong: 'Handys sind doof.', right: 'Die Nachteile überwiegen.', note: l('Objective style.', 'Nesnel üslup.', 'sachlich.') },
      { wrong: 'Einerseits das ist praktisch …', right: 'Einerseits ist das praktisch …', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Position 2.') },
      { wrong: 'Abschließend ich finde …', right: 'Abschließend finde ich …', note: l('Inversion.', 'Devrik yapı.', 'Inversion.') },
    ],
  },
}
