import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'das Referat', emoji: '🎤', translation: l('presentation, talk (academic)', 'sunum (akademik)', 'Vortrag in Schule / Uni'), example: 'Morgen halte ich ein Referat über erneuerbare Energien.' },
  { word: 'Die Grafik veranschaulicht …', emoji: '📊', translation: l('The chart illustrates …', 'Grafik … gösteriyor', 'Grafik einleiten'), example: 'Die Grafik veranschaulicht die Entwicklung der Mieten.' },
  { word: 'auf der x-Achse / y-Achse', emoji: '📐', translation: l('on the x-axis / y-axis', 'x-ekseninde / y-ekseninde', 'horizontal / vertikal'), example: 'Auf der x-Achse sind die Jahre angegeben.' },
  { word: 'den Höchststand erreichen', emoji: '⛰️', translation: l('to reach a peak', 'zirveye ulaşmak', 'höchster Wert'), example: 'Im Jahr 2022 erreichte der Wert seinen Höchststand.' },
  { word: 'der Tiefstand', emoji: '🕳️', translation: l('low point', 'en düşük seviye', 'niedrigster Wert'), example: 'Der Tiefstand lag bei 3 Prozent.' },
  { word: 'sich verdoppeln', emoji: '✖️2️⃣', translation: l('to double', 'ikiye katlanmak', '× 2'), example: 'Die Zahl hat sich verdoppelt.' },
  { word: 'Laut … / Wie … betont, …', emoji: '📚', translation: l('According to … / As … emphasises, …', '… -e göre / … vurguladığı gibi', 'Quelle nennen'), example: 'Wie das Statistische Bundesamt betont, …' },
  { word: 'die Quelle', emoji: '🔍', translation: l('source', 'kaynak', 'woher die Info kommt'), example: 'Die Daten stammen aus einer Studie der OECD.' },
  { word: 'der Einwand', emoji: '✋', translation: l('objection', 'itiraz', 'Gegenargument'), example: 'Das ist ein berechtigter Einwand.' },
  { word: 'Das ist ein wichtiger Punkt.', emoji: '👍', translation: l('That’s an important point.', 'Bu önemli bir nokta.', 'Einwand würdigen'), example: 'Das ist ein wichtiger Punkt, allerdings …' },
  { word: 'Da muss ich etwas präzisieren: …', emoji: '🎯', translation: l('Let me clarify: …', 'Bir şeyi netleştirmem gerek: …', 'genauer erklären'), example: 'Da muss ich etwas präzisieren: Die Zahl bezieht sich nur auf Städte.' },
  { word: 'Zusammenfassend lässt sich sagen …', emoji: '🏁', translation: l('To sum up, …', 'Özetle …', 'Fazit'), example: 'Zusammenfassend lässt sich sagen, dass der Trend positiv ist.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Referat', gender: 'n', plural: 'die Referate', translation: l('presentation', 'sunum', 'Referat') },
  { word: 'Achse', gender: 'f', plural: 'die Achsen', translation: l('axis', 'eksen', 'Achse') },
  { word: 'Anteil', gender: 'm', plural: 'die Anteile', translation: l('share, proportion', 'pay', 'Anteil') },
  { word: 'Höchststand', gender: 'm', translation: l('peak', 'zirve', 'Höchststand') },
  { word: 'Quelle', gender: 'f', plural: 'die Quellen', translation: l('source', 'kaynak', 'Quelle') },
  { word: 'Einwand', gender: 'm', plural: 'die Einwände', translation: l('objection', 'itiraz', 'Einwand') },
  { word: 'Balkendiagramm', gender: 'n', plural: 'die Balkendiagramme', translation: l('bar chart', 'çubuk grafik', 'Balkendiagramm') },
  { word: 'Kreisdiagramm', gender: 'n', plural: 'die Kreisdiagramme', translation: l('pie chart', 'pasta grafik', 'Kreisdiagramm') },
]

const FUNCS = ['Grafik beschreiben', 'Quelle nennen', 'auf Einwände reagieren'] as const

/** [id, phrase, index] */
const REF: [string, string, 0 | 1 | 2][] = [
  ['achse', 'Auf der y-Achse sieht man den Anteil in Prozent.', 0],
  ['laut', 'Laut einer Studie des Umweltbundesamts …', 1],
  ['punkt', 'Das ist ein wichtiger Punkt, allerdings …', 2],
  ['hoechst', '2022 erreichte die Kurve ihren Höchststand.', 0],
  ['stammen', 'Die Daten stammen aus dem Jahr 2024.', 1],
  ['praezisieren', 'Da muss ich etwas präzisieren: …', 2],
]

function refDrills(): Exercise[] {
  return REF.map(([id, phrase, right], i) => {
    const options = [...FUNCS]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `ref-${id}`,
      type: 'multiple_choice' as const,
      topic: 'redemittel',
      concept: 'functions',
      skill: 'speaking' as const,
      difficulty: 2 as const,
      prompt: `„${phrase}“ – Wozu dient das?`,
      options: ordered,
      answer: ordered.indexOf(FUNCS[right]),
      explanation: l(`→ ${FUNCS[right]}`, `→ ${FUNCS[right]}`, `→ ${FUNCS[right]}`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-diagramme',
    type: 'matching',
    topic: 'grafik',
    concept: 'chart-types',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the chart type and the symbol.', 'Grafik türünü sembolle eşleştir.', 'Diagrammtyp und Symbol.'),
    pairs: [
      { left: 'das Balkendiagramm', right: '📊' },
      { left: 'das Kurvendiagramm', right: '📈' },
      { left: 'das Kreisdiagramm', right: '🥧' },
      { left: 'die Tabelle', right: '🗒️' },
    ],
    explanation: l('Name the type of chart first.', 'Önce grafik türünü söyle.', 'Diagrammtypen.'),
  },
  {
    id: 'sort-staerke',
    type: 'categorize',
    topic: 'grafik',
    concept: 'trend-strength',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Strong or slight change?', 'Güçlü mü hafif mi değişim?', 'Stark oder leicht?'),
    categories: ['stark', 'leicht'],
    items: [
      { text: 'drastisch gestiegen', category: 0 },
      { text: 'geringfügig gesunken', category: 1 },
      { text: 'sich verdoppelt', category: 0 },
      { text: 'leicht zugenommen', category: 1 },
      { text: 'rapide gefallen', category: 0 },
      { text: 'kaum verändert', category: 1 },
    ],
    explanation: l('Precise adverbs make a chart description B2-level.', 'Kesin zarflar grafik tanımını B2 düzeyine taşır.', 'Präzision.'),
    practice: ['ref-achse'],
  },
  {
    id: 'mc-anteil',
    type: 'multiple_choice',
    topic: 'grafik',
    concept: 'pie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Im Kreisdiagramm ist die Hälfte blau (Bahn). – Der Anteil der Bahn ___ bei 50 Prozent.',
    options: ['liegt', 'steht', 'geht'],
    answer: 0,
    explanation: l('Der Anteil liegt bei … Prozent.', 'Der Anteil liegt bei … Prozent.', 'liegt bei.'),
    examples: ['Der Anteil der Bahn **liegt bei** 50 Prozent.'],
    practice: ['fill-veranschaulicht'],
  },
  {
    id: 'tf-quelle',
    type: 'true_false',
    topic: 'quellen',
    concept: 'cite',
    skill: 'reading',
    difficulty: 1,
    statement: 'In einem Referat sollte man immer sagen, woher die Daten stammen.',
    answer: true,
    explanation: l('Always name your source: Laut … / Die Daten stammen aus …', 'Kaynağını her zaman belirt: Laut … / Die Daten stammen aus …', 'Quelle.'),
  },
  {
    id: 'select-einwand',
    type: 'multiple_select',
    topic: 'einwaende',
    concept: 'react',
    skill: 'speaking',
    difficulty: 2,
    promptL10n: l('Good reactions to an objection? Select all.', 'Bir itiraza iyi tepkiler? Hepsini seç.', 'Gute Reaktionen auf Einwände?'),
    options: ['Das ist ein berechtigter Einwand.', 'Da muss ich etwas präzisieren: …', 'Das stimmt nicht, Punkt.', 'Danke für den Hinweis – darauf gehe ich gleich ein.', 'Fragen bitte erst nächste Woche.'],
    answers: [0, 1, 3],
    explanation: l('Acknowledge, clarify, refer to later – stay polite.', 'Kabul et, netleştir, sonraya yönlendir – kibar kal.', 'Einwände.'),
  },
  {
    id: 'image-kurve',
    type: 'image_choice',
    topic: 'grafik',
    concept: 'trend-strength',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Kurve steigt bis 2022 an und fällt danach stark ab.',
    options: [
      { emoji: '⛰️', label: 'erst hoch, dann runter' },
      { emoji: '📉', label: 'nur runter' },
      { emoji: '📈', label: 'nur hoch' },
      { emoji: '➖', label: 'gleich' },
    ],
    answer: 0,
    explanation: l('Rise to a peak, then fall.', 'Zirveye kadar yükselme, sonra düşüş.', 'Höchststand.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-veranschaulicht',
    type: 'fill_blank',
    topic: 'grafik',
    concept: 'introduce',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Grafik ___ die Entwicklung der Strompreise seit 2015.',
    accepted: ['veranschaulicht', 'zeigt', 'stellt', 'beschreibt'],
    base: 'zeigen (formell)',
    explanation: l('veranschaulichen = to illustrate (formal).', 'veranschaulichen = göstermek (resmî).', 'veranschaulicht.'),
    examples: ['Die Grafik **veranschaulicht** die Entwicklung …'],
  },
  {
    id: 'fill-stammen',
    type: 'fill_blank',
    topic: 'quellen',
    concept: 'cite',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Daten ___ aus einer Umfrage des Statistischen Bundesamts.',
    accepted: ['stammen', 'kommen'],
    base: 'stammen aus',
    explanation: l('Die Daten stammen aus … = The data comes from …', 'Die Daten stammen aus … = Veriler … kaynaklı.', 'stammen.'),
    examples: ['Die Daten **stammen** aus einer Umfrage …'],
  },
  {
    id: 'fill-verdoppelt',
    type: 'fill_blank',
    topic: 'grafik',
    concept: 'trend-strength',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Zwischen 2010 und 2020 hat sich die Zahl der E-Autos ___.',
    accepted: ['verdoppelt', 'verdreifacht', 'vervielfacht'],
    base: '× 2',
    explanation: l('sich verdoppeln → hat sich verdoppelt.', 'sich verdoppeln → hat sich verdoppelt.', 'verdoppelt.'),
    examples: ['… hat sich die Zahl der E-Autos **verdoppelt**.'],
  },
  {
    id: 'build-achse',
    type: 'sentence_builder',
    topic: 'grafik',
    concept: 'axes',
    skill: 'grammar',
    difficulty: 2,
    chips: ['sind', 'Auf der x-Achse', 'von 2015 bis 2025', 'die Jahre'],
    answers: [['Auf der x-Achse', 'sind', 'die Jahre', 'von 2015 bis 2025']],
    translation: l('On the x-axis are the years from 2015 to 2025.', 'x-ekseninde 2015’ten 2025’e kadar yıllar var.', 'Auf der x-Achse sind die Jahre von 2015 bis 2025.'),
    explanation: l('Describe the axes before the trend.', 'Eğilimden önce eksenleri anlat.', 'Achsen.'),
    examples: ['**Auf der x-Achse** sind die Jahre …'],
  },
  {
    id: 'build-hoechststand',
    type: 'sentence_builder',
    topic: 'grafik',
    concept: 'peak',
    skill: 'grammar',
    difficulty: 3,
    chips: ['erreichte', 'Im Jahr 2022', 'seinen Höchststand', 'der Wert'],
    answers: [['Im Jahr 2022', 'erreichte', 'der Wert', 'seinen Höchststand']],
    translation: l('In 2022 the value reached its peak.', '2022’de değer zirveye ulaştı.', 'Im Jahr 2022 erreichte der Wert seinen Höchststand.'),
    explanation: l('den Höchststand erreichen.', 'den Höchststand erreichen.', 'Höchststand.'),
    examples: ['Im Jahr 2022 **erreichte** der Wert seinen **Höchststand**.'],
  },
  {
    id: 'build-einwand',
    type: 'sentence_builder',
    topic: 'einwaende',
    concept: 'react',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ein berechtigter Einwand,', 'Das ist', 'aber die Zahlen zeigen etwas anderes'],
    answers: [['Das ist', 'ein berechtigter Einwand,', 'aber die Zahlen zeigen etwas anderes']],
    translation: l('That is a fair objection, but the figures show something different.', 'Bu haklı bir itiraz ama rakamlar başka bir şey gösteriyor.', 'Das ist ein berechtigter Einwand, aber die Zahlen zeigen etwas anderes.'),
    explanation: l('Acknowledge + aber + evidence.', 'Kabul et + aber + kanıt.', 'Einwand würdigen.'),
    examples: ['Das ist ein berechtigter **Einwand**, **aber** …'],
  },
  {
    id: 'fix-liegt',
    type: 'error_correction',
    topic: 'grafik',
    concept: 'pie',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Der Anteil liegt an 30 Prozent.',
    accepted: ['Der Anteil liegt bei 30 Prozent.'],
    explanation: l('liegen bei + number.', 'liegen bei + sayı.', 'bei.'),
    examples: ['Der Anteil liegt **bei** 30 Prozent.'],
  },
  {
    id: 'fix-hat-sich',
    type: 'error_correction',
    topic: 'grafik',
    concept: 'trend-strength',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Zahl hat verdoppelt.',
    accepted: ['Die Zahl hat sich verdoppelt.'],
    explanation: l('Reflexive: sich verdoppeln.', 'Dönüşlü: sich verdoppeln.', 'sich.'),
    examples: ['Die Zahl hat **sich** verdoppelt.'],
  },
  {
    id: 'fix-laut',
    type: 'error_correction',
    topic: 'quellen',
    concept: 'cite',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Laut die Studie fahren mehr Menschen Rad.',
    accepted: ['Laut der Studie fahren mehr Menschen Rad.', 'Laut einer Studie fahren mehr Menschen Rad.'],
    explanation: l('laut + dative/genitive: laut der Studie.', 'laut + Dativ/Genitiv: laut der Studie.', 'der Studie.'),
    examples: ['**Laut der** Studie fahren mehr Menschen Rad.'],
  },
  {
    id: 'tr-grafik',
    type: 'translation',
    topic: 'grafik',
    concept: 'introduce',
    skill: 'writing',
    difficulty: 2,
    source: l('The chart shows the share of renewable energy.', 'Grafik yenilenebilir enerjinin payını gösteriyor.', 'The chart shows the share of renewable energy.'),
    accepted: ['Die Grafik zeigt den Anteil erneuerbarer Energien.', 'Die Grafik zeigt den Anteil der erneuerbaren Energien.', 'Die Grafik veranschaulicht den Anteil erneuerbarer Energien.'],
    explanation: l('der Anteil + genitive.', 'der Anteil + Genitiv.', 'Anteil.'),
    examples: ['Die Grafik zeigt **den Anteil** erneuerbarer Energien.'],
  },
  {
    id: 'tr-einwand',
    type: 'translation',
    topic: 'einwaende',
    concept: 'react',
    skill: 'writing',
    difficulty: 2,
    source: l('That is an important point.', 'Bu önemli bir nokta.', 'That is an important point.'),
    accepted: ['Das ist ein wichtiger Punkt.'],
    explanation: l('der Punkt → ein wichtiger Punkt.', 'der Punkt → ein wichtiger Punkt.', 'Punkt.'),
    examples: ['Das ist ein **wichtiger Punkt**.'],
  },
  {
    id: 'ordering-referat',
    type: 'ordering',
    topic: 'grafik',
    concept: 'structure',
    skill: 'speaking',
    difficulty: 3,
    promptL10n: l('Order the chart presentation.', 'Grafik sunumunu sırala.', 'Ordne die Grafikpräsentation.'),
    items: ['Danach stieg er bis 2024 deutlich auf 52 Prozent.', 'Die Grafik veranschaulicht den Anteil erneuerbarer Energien am Strom in Deutschland.', 'Zusammenfassend lässt sich sagen, dass sich der Anteil mehr als verdoppelt hat.', 'Im Jahr 2014 lag der Anteil bei etwa 25 Prozent.', 'Die Daten stammen vom Umweltbundesamt.'],
    answer: ['Die Grafik veranschaulicht den Anteil erneuerbarer Energien am Strom in Deutschland.', 'Die Daten stammen vom Umweltbundesamt.', 'Im Jahr 2014 lag der Anteil bei etwa 25 Prozent.', 'Danach stieg er bis 2024 deutlich auf 52 Prozent.', 'Zusammenfassend lässt sich sagen, dass sich der Anteil mehr als verdoppelt hat.'],
    explanation: l('Topic → source → start → development → conclusion.', 'Konu → kaynak → başlangıç → gelişme → sonuç.', 'Aufbau.'),
  },
  {
    id: 'dialog-kritik',
    type: 'dialogue',
    topic: 'einwaende',
    concept: 'react',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Zuhörer', de: 'Aber Ihre Daten sind doch schon fünf Jahre alt!' }],
    options: ['Das ist ein berechtigter Einwand. Neuere Zahlen zeigen allerdings denselben Trend.', 'Nein, sind sie nicht.', 'Das ist mir egal.'],
    answer: 0,
    explanation: l('Acknowledge + counter with evidence.', 'Kabul et + kanıtla karşılık ver.', 'würdigen + belegen.'),
  },
  {
    id: 'dialog-praezisieren',
    type: 'dialogue',
    topic: 'einwaende',
    concept: 'clarify',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Zuhörerin', de: 'Gilt das für ganz Deutschland?' }],
    options: ['Da muss ich etwas präzisieren: Die Zahlen beziehen sich nur auf Großstädte.', 'Ja, Deutschland.', 'Weiß nicht.'],
    answer: 0,
    explanation: l('Clarify the scope of your data.', 'Verilerinin kapsamını netleştir.', 'präzisieren.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-handout',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es im Handout?',
    options: ['Wie Studierende in Deutschland wohnen.', 'Wie man ein Referat hält.', 'Wie Autos funktionieren.'],
    answer: 0,
    explanation: l('„Wohnsituation von Studierenden“', '„Wohnsituation von Studierenden“', 'Wohnen.'),
  },
  {
    id: 'read-wg',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-handout',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welche Wohnform ist am häufigsten?',
    options: ['Die WG.', 'Das Wohnheim.', 'Bei den Eltern.'],
    answer: 0,
    explanation: l('„Die meisten, nämlich 31 Prozent, leben in einer WG.“', '„Die meisten, nämlich 31 Prozent, leben in einer WG.“', 'WG.'),
  },
  {
    id: 'read-miete',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-handout',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die durchschnittliche Miete für ein WG-Zimmer ist seit 2015 gesunken.',
    answer: false,
    explanation: l('„… ist seit 2015 um fast 40 Prozent gestiegen.“', '„… ist seit 2015 um fast 40 Prozent gestiegen.“', 'falsch.'),
  },
  {
    id: 'read-quelle',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-handout',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Woher stammen die Daten?',
    options: ['Aus einer Umfrage des Studierendenwerks.', 'Aus einem Roman.', 'Aus einer Werbung.'],
    answer: 0,
    explanation: l('„Quelle: Sozialerhebung des Deutschen Studierendenwerks“', '„Quelle: Sozialerhebung des Deutschen Studierendenwerks“', 'Studierendenwerk.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-kurve',
    type: 'listening_choice',
    topic: 'grafik',
    concept: 'peak',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Zahl der Neuanmeldungen erreichte 2021 ihren Höchststand und ist seitdem leicht zurückgegangen.',
    question: l('What happened after 2021?', '2021’den sonra ne oldu?', 'Was passierte nach 2021?'),
    options: ['It fell slightly.', 'It rose sharply.', 'It doubled.'],
    answer: 0,
    explanation: l('„seitdem leicht zurückgegangen“', '„seitdem leicht zurückgegangen“', 'leicht gesunken.'),
  },
  {
    id: 'listen-kreis',
    type: 'listening_choice',
    topic: 'grafik',
    concept: 'pie',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wie Sie im Kreisdiagramm sehen, entfällt fast ein Drittel der Ausgaben auf die Miete.',
    question: l('How much of spending goes on rent?', 'Harcamaların ne kadarı kiraya gidiyor?', 'Wie viel für Miete?'),
    options: ['almost a third', 'half', 'a tenth'],
    answer: 0,
    explanation: l('„fast ein Drittel“', '„fast ein Drittel“', 'ein Drittel.'),
  },
  {
    id: 'listen-quelle',
    type: 'listening_choice',
    topic: 'quellen',
    concept: 'cite',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Zahlen stammen aus dem aktuellen Bericht der Weltgesundheitsorganisation.',
    question: l('Where do the figures come from?', 'Rakamlar nereden geliyor?', 'Woher kommen die Zahlen?'),
    options: ['the World Health Organization', 'a newspaper', 'the speaker’s own survey'],
    answer: 0,
    explanation: l('„Bericht der Weltgesundheitsorganisation“', '„Bericht der Weltgesundheitsorganisation“', 'WHO.'),
  },
  {
    id: 'listen-einwand',
    type: 'listening_choice',
    topic: 'einwaende',
    concept: 'react',
    skill: 'listening',
    difficulty: 3,
    audio: 'Danke für den Hinweis. Darauf gehe ich am Ende meines Referats noch genauer ein.',
    question: l('What does the speaker do with the objection?', 'Konuşan itirazla ne yapıyor?', 'Was macht die Person mit dem Einwand?'),
    options: ['will deal with it at the end', 'ignores it', 'ends the talk'],
    answer: 0,
    explanation: l('„am Ende … genauer ein“ = will address it later.', '„am Ende … genauer ein“ = sonra ele alacak.', 'später.'),
  },

  ...refDrills(),
]

export const UNIT_B2_24_REFERAT: CourseUnit = {
  level: 'B2',
  number: 24,
  slug: 'referat',
  titleDe: 'Ein Referat halten',
  title: l('Giving a talk', 'Bir sunum (referat) yapmak', 'Ein Referat halten'),
  goal: l(
    'By the end of this unit you can present data in detail (axes, peaks, shares, trends), name your sources correctly and react confidently to objections from the audience – as in the B2 oral exam.',
    'Bu ünitenin sonunda verileri ayrıntılı sunabilir (eksenler, zirveler, paylar, eğilimler), kaynaklarını doğru gösterebilir ve dinleyicilerden gelen itirazlara kendinden emin tepki verebilirsin – B2 sözlü sınavındaki gibi.',
    'Am Ende dieser Einheit hältst du ein Referat mit Daten.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'grafik', label: l('Describing charts', 'Grafik anlatmak', 'Grafik') },
    { key: 'quellen', label: l('Citing sources', 'Kaynak göstermek', 'Quellen') },
    { key: 'einwaende', label: l('Handling objections', 'İtirazlarla başa çıkmak', 'Einwände') },
    { key: 'redemittel', label: l('Presentation phrases', 'Sunum kalıpları', 'Redemittel') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Presenting data like a pro.', 'Verileri profesyonel gibi sunmak.', 'Daten professionell präsentieren.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Describing a chart in detail', 'Bir grafiği ayrıntılı anlatmak', 'Grafiken detailliert beschreiben'),
          body: l(
            'Type + topic: Das Balkendiagramm veranschaulicht … Axes: Auf der x-Achse … Start and end: Im Jahr … lag der Wert bei … Development: stieg drastisch / leicht an, erreichte seinen Höchststand, hat sich verdoppelt. Conclusion: Zusammenfassend lässt sich sagen …',
            'Tür + konu: Das Balkendiagramm veranschaulicht … Eksenler: Auf der x-Achse … Başlangıç ve son: Im Jahr … lag der Wert bei … Gelişme: stieg drastisch / leicht an, erreichte seinen Höchststand, hat sich verdoppelt. Sonuç: Zusammenfassend lässt sich sagen …',
            'Typ → Achsen → Werte → Trend → Fazit.'
          ),
          table: {
            head: [l('Phrase', 'İfade', 'Ausdruck'), l('Meaning', 'Anlam', 'Bedeutung')],
            rows: [
              ['den Höchststand erreichen', 'Maximum'],
              ['einen Tiefstand erreichen', 'Minimum'],
              ['sich verdoppeln', '× 2'],
              ['entfällt auf', 'Anteil'],
            ],
          },
        },
        {
          title: l('Citing sources', 'Kaynak göstermek', 'Quellen nennen'),
          body: l(
            'Laut + dative/genitive (laut der Studie) – Die Daten stammen aus / von … – Wie … betont / zeigt, … – Einer Umfrage zufolge … Always say how current the data is.',
            'Laut + Dativ/Genitiv (laut der Studie) – Die Daten stammen aus / von … – Wie … betont / zeigt, … – Einer Umfrage zufolge … Verilerin ne kadar güncel olduğunu hep söyle.',
            'Quellen.'
          ),
          examples: [
            { de: '**Die Daten stammen aus** einer Studie der OECD von 2024.', translation: l('The data comes from a 2024 OECD study.', 'Veriler OECD’nin 2024 araştırmasından.', '') },
            { de: '**Einer Umfrage zufolge** …', translation: l('According to a survey …', 'Bir ankete göre …', '') },
          ],
        },
        {
          title: l('Reacting to objections', 'İtirazlara tepki vermek', 'Auf Einwände reagieren'),
          body: l(
            'Acknowledge: Das ist ein berechtigter Einwand / ein wichtiger Punkt. Clarify: Da muss ich etwas präzisieren … Counter: Allerdings zeigen die Zahlen … Postpone: Darauf gehe ich gleich noch ein.',
            'Kabul et: Das ist ein berechtigter Einwand / ein wichtiger Punkt. Netleştir: Da muss ich etwas präzisieren … Karşılık ver: Allerdings zeigen die Zahlen … Ertele: Darauf gehe ich gleich noch ein.',
            'würdigen → präzisieren → belegen.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Burak presents a chart in his seminar.', 'Burak seminerinde bir grafik sunuyor.', 'Referat im Seminar.'),
      dialogue: [
        { speaker: 'Burak', de: 'Das **Kurvendiagramm veranschaulicht** die Zahl der Fahrradpendler in Köln. **Die Daten stammen** von der Stadt Köln.', translation: l('The line chart illustrates the number of bike commuters in Cologne. The data comes from the city of Cologne.', 'Çizgi grafik Köln’deki bisikletle işe gidenlerin sayısını gösteriyor. Veriler Köln belediyesinden.', '') },
        { speaker: 'Burak', de: '**Auf der x-Achse** sehen Sie die Jahre, **auf der y-Achse** die Anzahl in Tausend.', translation: l('On the x-axis you see the years, on the y-axis the number in thousands.', 'x-ekseninde yılları, y-ekseninde bin cinsinden sayıyı görüyorsunuz.', '') },
        { speaker: 'Burak', de: '2015 **lag** die Zahl **bei** 40.000. Bis 2023 **hat** sie **sich** fast **verdoppelt**.', translation: l('In 2015 the number stood at 40,000. By 2023 it had almost doubled.', '2015’te sayı 40.000’deydi. 2023’e kadar neredeyse ikiye katlandı.', '') },
        { speaker: 'Studentin', de: 'Aber lag das nicht nur an der Pandemie?', translation: l('But wasn’t that just because of the pandemic?', 'Ama bu sadece pandemi yüzünden değil miydi?', '') },
        { speaker: 'Burak', de: '**Das ist ein berechtigter Einwand.** **Allerdings** ist die Zahl auch nach 2022 weiter gestiegen.', translation: l('That’s a fair objection. However, the number continued to rise after 2022.', 'Haklı bir itiraz. Ancak sayı 2022’den sonra da artmaya devam etti.', '') },
        { speaker: 'Burak', de: '**Zusammenfassend lässt sich sagen**, dass das Fahrrad in Köln immer wichtiger wird.', translation: l('To sum up, the bicycle is becoming more and more important in Cologne.', 'Özetle, bisiklet Köln’de giderek daha önemli hale geliyor.', '') },
      ],
      examples: [
        { de: 'Die Grafik **veranschaulicht** …', translation: l('The chart illustrates …', 'Grafik … gösteriyor.', '') },
        { de: '**Auf der x-Achse** sind die Jahre.', translation: l('The years are on the x-axis.', 'x-ekseninde yıllar var.', '') },
        { de: 'Der Wert **erreichte** 2022 **seinen Höchststand**.', translation: l('The value peaked in 2022.', 'Değer 2022’de zirve yaptı.', '') },
        { de: 'Die Zahl **hat sich verdoppelt**.', translation: l('The number has doubled.', 'Sayı ikiye katlandı.', '') },
        { de: '**Die Daten stammen aus** …', translation: l('The data comes from …', 'Veriler … kaynaklı.', '') },
        { de: 'Das ist ein **berechtigter Einwand**.', translation: l('That’s a fair objection.', 'Bu haklı bir itiraz.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Chart, source or objection?', 'Grafik, kaynak mı itiraz mı?', 'Grafik, Quelle, Einwand?'),
      exercises: ['match-diagramme', 'sort-staerke', 'ref-achse', 'ref-laut', 'ref-punkt', 'mc-anteil', 'tf-quelle', 'select-einwand', 'image-kurve'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Present data and defend it.', 'Verileri sun ve savun.', 'Daten präsentieren.'),
      exercises: [
        'fill-veranschaulicht',
        'fill-stammen',
        'fill-verdoppelt',
        'build-achse',
        'build-hoechststand',
        'build-einwand',
        'fix-liegt',
        'fix-hat-sich',
        'fix-laut',
        'tr-grafik',
        'tr-einwand',
        'ordering-referat',
        'dialog-kritik',
        'dialog-praezisieren',
        'ref-hoechst',
        'ref-stammen',
        'ref-praezisieren',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A handout for a seminar talk.', 'Bir seminer sunumu için bilgi notu.', 'Ein Handout.'),
      passage: [
        '**Handout: Wohnsituation von Studierenden in Deutschland** (Quelle: Sozialerhebung des Deutschen Studierendenwerks, 2023)',
        '1. Wohnform: Die meisten, nämlich 31 Prozent, leben in einer **WG**. 23 Prozent wohnen noch bei den Eltern, nur 10 Prozent im Wohnheim.',
        '2. Kosten: Die durchschnittliche Miete für ein WG-Zimmer **ist** seit 2015 **um fast 40 Prozent gestiegen**. In München **liegt** sie inzwischen **bei** über 700 Euro.',
        '3. Fazit: **Zusammenfassend lässt sich sagen**, dass bezahlbarer Wohnraum für Studierende immer knapper wird.',
      ],
      glossary: [
        { de: 'die Erhebung', note: l('survey', 'anket, araştırma', 'Umfrage, Studie') },
        { de: 'durchschnittlich', note: l('average', 'ortalama', 'im Mittel') },
        { de: 'der Wohnraum', note: l('housing', 'konut alanı', 'Wohnungen') },
        { de: 'knapp', note: l('scarce', 'kıt', 'nicht genug') },
      ],
      exercises: ['read-thema', 'read-wg', 'read-miete', 'read-quelle'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Excerpts from talks.', 'Sunumlardan kesitler.', 'Ausschnitte aus Referaten.'),
      exercises: ['listen-kurve', 'listen-kreis', 'listen-quelle', 'listen-einwand'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present a chart about a topic you know (e.g. smartphone use, prices, sport) and react to one objection.', 'Bildiğin bir konuda bir grafik sun (ör. akıllı telefon kullanımı, fiyatlar, spor) ve bir itiraza tepki ver.', 'Grafikpräsentation mit Einwand.'),
      points: [
        l('Type, topic and source', 'Tür, konu ve kaynak', 'Typ, Thema, Quelle'),
        l('Axes and key values', 'Eksenler ve önemli değerler', 'Achsen, Werte'),
        l('Trend with precise adverbs', 'Kesin zarflarla eğilim', 'Trend'),
        l('Reaction to an objection', 'Bir itiraza tepki', 'Einwand'),
      ],
      model: [
        'Das Balkendiagramm veranschaulicht die tägliche Handynutzung von Jugendlichen; die Daten stammen aus der JIM-Studie 2024.',
        'Auf der x-Achse sehen Sie die Altersgruppen, auf der y-Achse die Minuten pro Tag.',
        'Den Höchststand erreichen die 16- bis 17-Jährigen mit fast vier Stunden täglich.',
        'Das ist ein berechtigter Einwand – allerdings zählen hier auch Musik und Lernen am Handy mit.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write the script for a chart presentation (at least 6 sentences): „Share of e-cars among new cars: 2019 – 3 %, 2021 – 14 %, 2023 – 18 %, 2024 – 13 %.“ Source: Kraftfahrt-Bundesamt.',
        'Bir grafik sunumunun metnini yaz (en az 6 cümle): „Yeni arabalar içinde elektrikli arabaların payı: 2019 – %3, 2021 – %14, 2023 – %18, 2024 – %13.“ Kaynak: Kraftfahrt-Bundesamt.',
        'Skript für eine Grafikpräsentation (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Introduce the chart (veranschaulicht / zeigt)', 'Grafiği tanıt (veranschaulicht / zeigt)', 'Einleitung'), pattern: '(veranschaulicht|zeigt|stellt[\\s\\S]*dar)' },
        { label: l('Name the source (stammen / laut / Quelle)', 'Kaynağı belirt (stammen / laut / Quelle)', 'Quelle'), pattern: '(stammen|[Ll]aut|Quelle|zufolge)' },
        { label: l('Peak or low point (Höchststand / Tiefstand)', 'Zirve ya da dip (Höchststand / Tiefstand)', 'Höchststand'), pattern: '(Höchststand|Tiefstand|Höhepunkt|Maximum)' },
        { label: l('A conclusion (Zusammenfassend / Insgesamt)', 'Bir sonuç (Zusammenfassend / Insgesamt)', 'Fazit'), pattern: '([Zz]usammenfassend|[Ii]nsgesamt|Abschließend)' },
      ],
      model: [
        'Die Grafik veranschaulicht den Anteil von Elektroautos an allen Neuwagen in Deutschland.',
        'Die Daten stammen vom Kraftfahrt-Bundesamt.',
        'Im Jahr 2019 lag der Anteil bei nur 3 Prozent.',
        'Bis 2023 stieg er drastisch an und erreichte mit 18 Prozent seinen Höchststand.',
        'Im Jahr 2024 sank der Anteil jedoch deutlich auf 13 Prozent, vermutlich weil die staatliche Förderung wegfiel.',
        'Zusammenfassend lässt sich sagen, dass der Trend zwar positiv ist, aber stark von der Politik abhängt.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Chart, source or objection? – 60 seconds.', 'Grafik, kaynak mı itiraz mı? – 60 saniye.', 'Welche Funktion? – 60 Sekunden.'),
      seconds: 60,
      pool: [...REF.map(([id]) => `ref-${id}`), 'mc-anteil'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Charts: veranschaulichen, x-/y-Achse, Höchststand, sich verdoppeln, liegt bei', 'Grafikler: veranschaulichen, x-/y-Achse, Höchststand, sich verdoppeln, liegt bei', 'Grafik'),
      l('Sources: Die Daten stammen aus … / laut … / einer Umfrage zufolge', 'Kaynaklar: Die Daten stammen aus … / laut … / einer Umfrage zufolge', 'Quellen'),
      l('Objections: berechtigter Einwand, präzisieren, allerdings', 'İtirazlar: berechtigter Einwand, präzisieren, allerdings', 'Einwände'),
      l('Structure: topic → source → values → trend → conclusion', 'Yapı: konu → kaynak → değerler → eğilim → sonuç', 'Aufbau'),
    ],
    mistakes: [
      { wrong: 'Der Anteil liegt an 30 %.', right: 'Der Anteil liegt bei 30 %.', note: l('liegen bei.', 'liegen bei.', 'bei.') },
      { wrong: 'Die Zahl hat verdoppelt.', right: 'Die Zahl hat sich verdoppelt.', note: l('Reflexive.', 'Dönüşlü.', 'sich.') },
      { wrong: 'Laut die Studie …', right: 'Laut der Studie …', note: l('laut + dative/genitive.', 'laut + Dativ/Genitiv.', 'der.') },
      { wrong: 'Das stimmt nicht, Punkt.', right: 'Das ist ein berechtigter Einwand, allerdings …', note: l('Acknowledge first.', 'Önce kabul et.', 'würdigen.') },
    ],
  },
}
