import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Rezension', emoji: '📝', translation: l('review', 'eleştiri yazısı', 'Kritik eines Buches / Films'), example: 'Ich habe eine Rezension über den Film geschrieben.' },
  { word: 'handeln von', emoji: '📖', translation: l('to be about', '… hakkında olmak', 'das Thema ist'), example: 'Der Roman handelt von einer Familie im Krieg.' },
  { word: 'die Handlung', emoji: '🎬', translation: l('plot', 'olay örgüsü', 'was passiert'), example: 'Die Handlung spielt im Berlin der 20er-Jahre.' },
  { word: 'die Hauptfigur', emoji: '🦸', translation: l('main character', 'ana karakter', 'wichtigste Person'), example: 'Die Hauptfigur ist eine junge Ärztin.' },
  { word: 'spannend', emoji: '🎢', translation: l('exciting, gripping', 'heyecanlı', 'macht neugierig'), example: 'Das Buch ist von Anfang bis Ende spannend.' },
  { word: 'langatmig', emoji: '😴', translation: l('long-winded', 'sıkıcı derecede uzun', 'zu lang, langweilig'), example: 'Der Mittelteil ist leider etwas langatmig.' },
  { word: 'gelungen', emoji: '👏', translation: l('successful, well done', 'başarılı', 'gut gemacht'), example: 'Besonders gelungen ist die Musik.' },
  { word: 'überzeugen', emoji: '🎯', translation: l('to convince', 'ikna etmek', 'gut finden lassen'), example: 'Das Ende hat mich nicht überzeugt.' },
  { word: 'die Ausstellung', emoji: '🖼️', translation: l('exhibition', 'sergi', 'Kunst im Museum'), example: 'Die Ausstellung ist noch bis Mai zu sehen.' },
  { word: 'der Roman', emoji: '📚', translation: l('novel', 'roman', 'langes Buch, erfunden'), example: 'Ihr neuer Roman wurde ein Bestseller.' },
  { word: 'empfehlen', emoji: '👍', translation: l('to recommend', 'tavsiye etmek', 'als gut nennen'), example: 'Ich kann den Film nur empfehlen.' },
  { word: 'Geschmackssache', emoji: '🍨', translation: l('a matter of taste', 'zevk meselesi', 'jeder findet etwas anderes gut'), example: 'Ob einem das Ende gefällt, ist Geschmackssache.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Rezension', gender: 'f', plural: 'die Rezensionen', translation: l('review', 'eleştiri', 'Rezension') },
  { word: 'Handlung', gender: 'f', plural: 'die Handlungen', translation: l('plot', 'olay örgüsü', 'Handlung') },
  { word: 'Figur', gender: 'f', plural: 'die Figuren', translation: l('character', 'karakter', 'Figur') },
  { word: 'Roman', gender: 'm', plural: 'die Romane', translation: l('novel', 'roman', 'Roman') },
  { word: 'Gemälde', gender: 'n', plural: 'die Gemälde', translation: l('painting', 'tablo', 'Gemälde') },
  { word: 'Ausstellung', gender: 'f', plural: 'die Ausstellungen', translation: l('exhibition', 'sergi', 'Ausstellung') },
  { word: 'Regisseur', gender: 'm', plural: 'die Regisseure', translation: l('director', 'yönetmen', 'Regisseur') },
  { word: 'Schriftsteller', gender: 'm', plural: 'die Schriftsteller', translation: l('writer', 'yazar', 'Schriftsteller') },
]

const PARTS = ['Inhalt', 'positive Bewertung', 'negative Bewertung'] as const

/** [id, phrase, index of part] */
const REZ: [string, string, 0 | 1 | 2][] = [
  ['handelt', 'Der Film handelt von zwei Brüdern, die …', 0],
  ['gelungen', 'Besonders gelungen sind die Dialoge.', 1],
  ['langatmig', 'Leider ist der Mittelteil ziemlich langatmig.', 2],
  ['spielt', 'Die Geschichte spielt in Wien um 1900.', 0],
  ['empfehlen', 'Ich kann das Buch jedem nur empfehlen.', 1],
  ['ueberzeugt', 'Das Ende hat mich nicht überzeugt.', 2],
]

function rezDrills(): Exercise[] {
  return REZ.map(([id, phrase, right], i) => {
    const options = [...PARTS]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `rez-${id}`,
      type: 'multiple_choice' as const,
      topic: 'rezension',
      concept: 'review-parts',
      skill: 'reading' as const,
      difficulty: 2 as const,
      prompt: `„${phrase}“ – Was ist das?`,
      options: ordered,
      answer: ordered.indexOf(PARTS[right]),
      explanation: l(`→ ${PARTS[right]}`, `→ ${PARTS[right]}`, `→ ${PARTS[right]}`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-kunst',
    type: 'matching',
    topic: 'wortschatz',
    concept: 'culture-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match person and field.', 'Kişiyi alanıyla eşleştir.', 'Person und Bereich.'),
    pairs: [
      { left: 'der Regisseur', right: 'Film' },
      { left: 'der Schriftsteller', right: 'Buch' },
      { left: 'die Malerin', right: 'Gemälde' },
      { left: 'der Bildhauer', right: 'Skulptur' },
      { left: 'die Dirigentin', right: 'Orchester' },
    ],
    explanation: l('People in arts and culture.', 'Sanat ve kültürdeki insanlar.', 'Kulturberufe.'),
  },
  {
    id: 'sort-bewertung',
    type: 'categorize',
    topic: 'bewerten',
    concept: 'pos-neg',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Positive or negative evaluation?', 'Olumlu mu olumsuz mu değerlendirme?', 'Positiv oder negativ?'),
    categories: ['positiv 👍', 'negativ 👎'],
    items: [
      { text: 'mitreißend', category: 0 },
      { text: 'langatmig', category: 1 },
      { text: 'gelungen', category: 0 },
      { text: 'vorhersehbar', category: 1 },
      { text: 'beeindruckend', category: 0 },
      { text: 'oberflächlich', category: 1 },
    ],
    explanation: l('B2 evaluation adjectives.', 'B2 değerlendirme sıfatları.', 'Bewertungsadjektive.'),
    practice: ['rez-handelt'],
  },
  {
    id: 'mc-handelt',
    type: 'multiple_choice',
    topic: 'rezension',
    concept: 'content',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Der Roman handelt ___ einem Jungen, der seinen Vater sucht.',
    options: ['von', 'über', 'um'],
    answer: 0,
    explanation: l('handeln von + dative. (Es geht um + accusative.)', 'handeln von + Dativ. (Es geht um + Akk.)', 'von.'),
    examples: ['Der Roman handelt **von** einem Jungen …'],
    practice: ['fill-geht'],
  },
  {
    id: 'tf-geschmack',
    type: 'true_false',
    topic: 'bewerten',
    concept: 'nuance',
    skill: 'reading',
    difficulty: 2,
    statement: '„Das ist Geschmackssache“ bedeutet: Jeder kann das anders bewerten.',
    answer: true,
    explanation: l('Geschmackssache = a matter of taste.', 'Geschmackssache = zevk meselesi.', 'richtig.'),
  },
  {
    id: 'select-inhalt',
    type: 'multiple_select',
    topic: 'rezension',
    concept: 'content',
    skill: 'writing',
    difficulty: 2,
    promptL10n: l('Which phrases describe the content (not the opinion)? Select all.', 'Hangi ifadeler içeriği (fikri değil) anlatıyor? Hepsini seç.', 'Welche beschreiben den Inhalt?'),
    options: ['Es geht um eine Liebesgeschichte.', 'Die Handlung spielt in Hamburg.', 'Ich fand den Film großartig.', 'Die Hauptfigur ist ein Lehrer.', 'Das Ende war enttäuschend.'],
    answers: [0, 1, 3],
    explanation: l('Content: es geht um, spielt in, Hauptfigur. Opinion: fand … großartig, enttäuschend.', 'İçerik: es geht um, spielt in, Hauptfigur. Fikir: fand … großartig, enttäuschend.', 'Inhalt vs. Meinung.'),
  },
  {
    id: 'image-museum',
    type: 'image_choice',
    topic: 'wortschatz',
    concept: 'culture-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Ausstellung zeigt Gemälde aus dem 19. Jahrhundert.',
    options: [
      { emoji: '🖼️', label: 'Gemälde' },
      { emoji: '🎸', label: 'Gitarre' },
      { emoji: '🎮', label: 'Videospiel' },
      { emoji: '📺', label: 'Fernseher' },
    ],
    answer: 0,
    explanation: l('das Gemälde = painting.', 'das Gemälde = tablo.', 'Gemälde.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-geht',
    type: 'fill_blank',
    topic: 'rezension',
    concept: 'content',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'In dem Film geht es ___ eine Frau, die auswandert.',
    accepted: ['um'],
    base: 'es geht um',
    explanation: l('Es geht um + accusative.', 'Es geht um + Akk.', 'um.'),
    examples: ['In dem Film geht es **um** eine Frau …'],
  },
  {
    id: 'fill-ueberzeugt',
    type: 'fill_blank',
    topic: 'bewerten',
    concept: 'pos-neg',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Schauspieler haben mich total ___. (überzeugen)',
    accepted: ['überzeugt'],
    base: 'überzeugen',
    explanation: l('überzeugen (inseparable) → hat überzeugt.', 'überzeugen (ayrılmaz) → hat überzeugt.', 'überzeugt.'),
    examples: ['Die Schauspieler haben mich total **überzeugt**.'],
  },
  {
    id: 'fill-empfehlen',
    type: 'fill_blank',
    topic: 'bewerten',
    concept: 'recommend',
    skill: 'vocabulary',
    difficulty: 1,
    sentence: 'Ich kann das Buch nur ___ – es ist großartig!',
    accepted: ['empfehlen', 'weiterempfehlen'],
    base: 'als gut nennen',
    explanation: l('Ich kann … nur empfehlen = I can only recommend …', 'Ich kann … nur empfehlen = … ancak tavsiye edebilirim', 'empfehlen.'),
    examples: ['Ich kann das Buch nur **empfehlen**.'],
  },
  {
    id: 'build-spielt',
    type: 'sentence_builder',
    topic: 'rezension',
    concept: 'content',
    skill: 'grammar',
    difficulty: 2,
    chips: ['spielt', 'im Paris der 50er-Jahre', 'Die Handlung'],
    answers: [['Die Handlung', 'spielt', 'im Paris der 50er-Jahre']],
    translation: l('The story is set in 1950s Paris.', 'Hikâye 50’lerin Paris’inde geçiyor.', 'Die Handlung spielt im Paris der 50er-Jahre.'),
    explanation: l('spielen in = to be set in.', 'spielen in = … -de geçmek.', 'spielt in.'),
    examples: ['Die Handlung **spielt** im Paris der 50er-Jahre.'],
  },
  {
    id: 'build-gelungen',
    type: 'sentence_builder',
    topic: 'bewerten',
    concept: 'pos-neg',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ist', 'Besonders gelungen', 'die Musik'],
    answers: [['Besonders gelungen', 'ist', 'die Musik']],
    translation: l('The music is particularly successful.', 'Özellikle müzik çok başarılı.', 'Besonders gelungen ist die Musik.'),
    explanation: l('Emphasis in position 1 → verb next.', 'Vurgu 1. konumda → sonra fiil.', 'gelungen ist.'),
    examples: ['**Besonders gelungen** ist die Musik.'],
  },
  {
    id: 'build-obwohl',
    type: 'sentence_builder',
    topic: 'bewerten',
    concept: 'balanced',
    skill: 'grammar',
    difficulty: 3,
    chips: ['etwas langatmig ist', 'Obwohl der Film', 'hat er mir gefallen'],
    answers: [['Obwohl der Film', 'etwas langatmig ist', 'hat er mir gefallen']],
    translation: l('Although the film is a bit long-winded, I liked it.', 'Film biraz uzun olsa da hoşuma gitti.', 'Obwohl der Film etwas langatmig ist, hat er mir gefallen.'),
    explanation: l('Balanced evaluation with obwohl.', 'obwohl ile dengeli değerlendirme.', 'obwohl.'),
    examples: ['**Obwohl** der Film etwas langatmig ist, hat er mir gefallen.'],
  },
  {
    id: 'fix-handelt',
    type: 'error_correction',
    topic: 'rezension',
    concept: 'content',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das Buch handelt über einen Detektiv.',
    accepted: ['Das Buch handelt von einem Detektiv.'],
    explanation: l('handeln von + dative.', 'handeln von + Dativ.', 'von einem.'),
    examples: ['Das Buch handelt **von einem** Detektiv.'],
  },
  {
    id: 'fix-gefallen',
    type: 'error_correction',
    topic: 'bewerten',
    concept: 'pos-neg',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe der Film sehr gut gefallen.',
    accepted: ['Mir hat der Film sehr gut gefallen.', 'Der Film hat mir sehr gut gefallen.'],
    explanation: l('gefallen: the thing is the subject, the person is dative (mir).', 'gefallen: şey özne, kişi Dativ (mir).', 'mir.'),
    examples: ['Der Film hat **mir** sehr gut gefallen.'],
  },
  {
    id: 'fix-spannend',
    type: 'error_correction',
    topic: 'bewerten',
    concept: 'pos-neg',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Der Krimi war so gespannt, dass ich nicht schlafen konnte.',
    accepted: ['Der Krimi war so spannend, dass ich nicht schlafen konnte.'],
    explanation: l('The book is spannend; I am gespannt.', 'Kitap spannend; ben gespannt.', 'spannend.'),
    examples: ['Der Krimi war so **spannend**, …'],
  },
  {
    id: 'tr-handelt',
    type: 'translation',
    topic: 'rezension',
    concept: 'content',
    skill: 'writing',
    difficulty: 2,
    source: l('The film is about a friendship.', 'Film bir arkadaşlık hakkında.', 'The film is about a friendship.'),
    accepted: ['Der Film handelt von einer Freundschaft.', 'In dem Film geht es um eine Freundschaft.', 'Im Film geht es um eine Freundschaft.'],
    explanation: l('handeln von / es geht um.', 'handeln von / es geht um.', 'handelt von.'),
    examples: ['Der Film **handelt von** einer Freundschaft.'],
  },
  {
    id: 'tr-empfehlen',
    type: 'translation',
    topic: 'bewerten',
    concept: 'recommend',
    skill: 'writing',
    difficulty: 2,
    source: l('I can really recommend the exhibition.', 'Sergiyi gerçekten tavsiye ederim.', 'I can really recommend the exhibition.'),
    accepted: ['Ich kann die Ausstellung wirklich empfehlen.', 'Ich kann die Ausstellung nur empfehlen.'],
    explanation: l('empfehlen + accusative.', 'empfehlen + Akk.', 'empfehlen.'),
    examples: ['Ich kann die Ausstellung wirklich **empfehlen**.'],
  },
  {
    id: 'ordering-rezension',
    type: 'ordering',
    topic: 'rezension',
    concept: 'structure',
    skill: 'writing',
    difficulty: 2,
    promptL10n: l('Order a short review.', 'Kısa bir eleştiriyi sırala.', 'Ordne die Rezension.'),
    items: ['Fazit: ein Film, den man gesehen haben muss.', 'Der Film „Das Lehrerzimmer“ handelt von einer jungen Lehrerin.', 'Leider ist das Ende etwas offen.', 'Besonders gelungen ist die spannende Kameraführung.'],
    answer: ['Der Film „Das Lehrerzimmer“ handelt von einer jungen Lehrerin.', 'Besonders gelungen ist die spannende Kameraführung.', 'Leider ist das Ende etwas offen.', 'Fazit: ein Film, den man gesehen haben muss.'],
    explanation: l('Content → positive → negative → conclusion.', 'İçerik → olumlu → olumsuz → sonuç.', 'Aufbau.'),
  },
  {
    id: 'dialog-film',
    type: 'dialogue',
    topic: 'bewerten',
    concept: 'balanced',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Wie fandest du den Film gestern?' }],
    options: ['Die Schauspieler waren großartig, aber die Handlung war ziemlich vorhersehbar.', 'Der Film war gestern.', 'Ich fand gesehen.'],
    answer: 0,
    explanation: l('Balanced opinion: positive + aber + negative.', 'Dengeli fikir: olumlu + aber + olumsuz.', 'ausgewogen.'),
  },
  {
    id: 'dialog-ausstellung',
    type: 'dialogue',
    topic: 'bewerten',
    concept: 'recommend',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Lohnt sich die neue Ausstellung im Museum?' }],
    options: ['Auf jeden Fall! Die Fotos sind beeindruckend – geh unbedingt hin.', 'Die Ausstellung lohnt Museum.', 'Ja, Museum.'],
    answer: 0,
    explanation: l('Recommend with a reason.', 'Sebeple tavsiye et.', 'empfehlen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-rezension',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was wird hier rezensiert?',
    options: ['Ein Roman.', 'Ein Konzert.', 'Ein Restaurant.'],
    answer: 0,
    explanation: l('„Der neue Roman von …“', '„Der neue Roman von …“', 'Roman.'),
  },
  {
    id: 'read-handlung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-rezension',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wovon handelt das Buch?',
    options: ['Von drei Generationen einer Familie.', 'Von einer Reise zum Mond.', 'Von einem Fußballverein.'],
    answer: 0,
    explanation: l('„… erzählt die Geschichte von drei Generationen einer Familie.“', '„… erzählt die Geschichte von drei Generationen einer Familie.“', 'Familie.'),
  },
  {
    id: 'read-kritik',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-rezension',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Rezensentin findet den ganzen Roman spannend.',
    answer: false,
    explanation: l('„Der Mittelteil ist allerdings etwas langatmig.“', '„Der Mittelteil ist allerdings etwas langatmig.“', 'falsch.'),
  },
  {
    id: 'read-fazit',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-rezension',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie ist das Fazit?',
    options: ['Trotz kleiner Schwächen sehr lesenswert.', 'Nicht empfehlenswert.', 'Nur für Kinder.'],
    answer: 0,
    explanation: l('„Trotz kleiner Schwächen ein sehr lesenswertes Buch.“', '„Trotz kleiner Schwächen ein sehr lesenswertes Buch.“', 'lesenswert.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-kino',
    type: 'listening_choice',
    topic: 'bewerten',
    concept: 'pos-neg',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Film war optisch beeindruckend, aber die Geschichte war leider total vorhersehbar.',
    question: l('What was the weakness of the film?', 'Filmin zayıf yanı neydi?', 'Was war schwach?'),
    options: ['the predictable story', 'the pictures', 'the music'],
    answer: 0,
    explanation: l('„die Geschichte war … vorhersehbar“', '„die Geschichte war … vorhersehbar“', 'Geschichte.'),
  },
  {
    id: 'listen-museum',
    type: 'listening_choice',
    topic: 'wortschatz',
    concept: 'culture-words',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Ausstellung „Frauen in der Kunst“ ist noch bis Ende März zu sehen. Am ersten Sonntag im Monat ist der Eintritt frei.',
    question: l('When is entry free?', 'Giriş ne zaman ücretsiz?', 'Wann ist der Eintritt frei?'),
    options: ['on the first Sunday of the month', 'every Monday', 'never'],
    answer: 0,
    explanation: l('„Am ersten Sonntag im Monat“', '„Am ersten Sonntag im Monat“', 'erster Sonntag.'),
  },
  {
    id: 'listen-buch',
    type: 'listening_choice',
    topic: 'rezension',
    concept: 'content',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das Buch spielt in einem kleinen Dorf in den Alpen und handelt von einem Lehrer, der ein Geheimnis hat.',
    question: l('Where is the story set?', 'Hikâye nerede geçiyor?', 'Wo spielt die Geschichte?'),
    options: ['in a village in the Alps', 'in Berlin', 'on an island'],
    answer: 0,
    explanation: l('„in einem kleinen Dorf in den Alpen“', '„in einem kleinen Dorf in den Alpen“', 'Alpen.'),
  },
  {
    id: 'listen-geschmack',
    type: 'listening_choice',
    topic: 'bewerten',
    concept: 'nuance',
    skill: 'listening',
    difficulty: 3,
    audio: 'Ob man moderne Kunst mag, ist natürlich Geschmackssache. Ich persönlich konnte mit den Bildern wenig anfangen.',
    question: l('What does the speaker think of the pictures?', 'Konuşan resimler hakkında ne düşünüyor?', 'Wie findet die Person die Bilder?'),
    options: ['not much – they didn’t speak to him/her', 'brilliant', 'too expensive'],
    answer: 0,
    explanation: l('„mit etwas wenig anfangen können“ = not get much out of it.', '„mit etwas wenig anfangen können“ = pek bir şey ifade etmemek.', 'wenig anfangen.'),
  },

  ...rezDrills(),
]

export const UNIT_B2_20_KUNST_KULTUR: CourseUnit = {
  level: 'B2',
  number: 20,
  slug: 'kunst-kultur',
  titleDe: 'Kunst und Literatur',
  title: l('Art and literature', 'Sanat ve edebiyat', 'Kunst und Literatur'),
  goal: l(
    'By the end of this unit you can summarise a book or film (handelt von, es geht um, spielt in), evaluate it with differentiated adjectives and write a short review with content, positive and negative points and a conclusion.',
    'Bu ünitenin sonunda bir kitabı ya da filmi özetleyebilir (handelt von, es geht um, spielt in), ayrıntılı sıfatlarla değerlendirebilir ve içerik, olumlu ve olumsuz noktalar ile sonuç içeren kısa bir eleştiri yazabilirsin.',
    'Am Ende dieser Einheit schreibst du eine Rezension.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'wortschatz', label: l('Culture vocabulary', 'Kültür kelimeleri', 'Wortschatz') },
    { key: 'rezension', label: l('Describing content', 'İçeriği anlatmak', 'Inhalt wiedergeben') },
    { key: 'bewerten', label: l('Evaluating', 'Değerlendirmek', 'Bewerten') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Talking about books, films and art.', 'Kitaplar, filmler ve sanat hakkında konuşmak.', 'Über Kultur sprechen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Describing the content', 'İçeriği anlatmak', 'Den Inhalt beschreiben'),
          body: l(
            'Der Film/Roman handelt von + dative. – Es geht um + accusative. – Die Handlung spielt in … – Die Hauptfigur ist … – Im Mittelpunkt steht … Use the present tense for summaries.',
            'Der Film/Roman handelt von + Dativ. – Es geht um + Akk. – Die Handlung spielt in … – Die Hauptfigur ist … – Im Mittelpunkt steht … Özetlerde şimdiki zaman kullan.',
            'Inhalt im Präsens.'
          ),
          table: {
            head: [l('Phrase', 'İfade', 'Redemittel'), l('Case', 'Hal', 'Kasus')],
            rows: [
              ['handelt von', 'Dativ'],
              ['es geht um', 'Akkusativ'],
              ['spielt in', 'Dativ (Ort)'],
              ['im Mittelpunkt steht', 'Nominativ'],
            ],
          },
        },
        {
          title: l('Evaluating', 'Değerlendirmek', 'Bewerten'),
          body: l(
            'Positive: gelungen, mitreißend, beeindruckend, spannend. Negative: langatmig, vorhersehbar, oberflächlich, enttäuschend. Phrases: Besonders gelungen ist … / Mich hat … (nicht) überzeugt. / Leider …',
            'Olumlu: gelungen, mitreißend, beeindruckend, spannend. Olumsuz: langatmig, vorhersehbar, oberflächlich, enttäuschend. İfadeler: Besonders gelungen ist … / Mich hat … (nicht) überzeugt. / Leider …',
            'positiv / negativ.'
          ),
          examples: [
            { de: '**Besonders gelungen** ist die Musik.', translation: l('The music is particularly successful.', 'Özellikle müzik başarılı.', '') },
            { de: 'Das Ende hat mich **nicht überzeugt**.', translation: l('The ending didn’t convince me.', 'Son beni ikna etmedi.', '') },
          ],
        },
        {
          title: l('Structure of a review', 'Eleştirinin yapısı', 'Aufbau einer Rezension'),
          body: l(
            'Title, author/director → content (without spoiling the end) → strengths → weaknesses → conclusion and recommendation (Fazit: … / Ich kann … nur empfehlen.).',
            'Başlık, yazar/yönetmen → içerik (sonu söylemeden) → güçlü yanlar → zayıf yanlar → sonuç ve tavsiye (Fazit: … / Ich kann … nur empfehlen.).',
            'Inhalt → Bewertung → Fazit.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two friends leave the cinema.', 'İki arkadaş sinemadan çıkıyor.', 'Nach dem Kino.'),
      dialogue: [
        { speaker: 'Mina', de: 'Und? Wie hat dir der Film **gefallen**?', translation: l('So? How did you like the film?', 'Ee? Film nasıldı?', '') },
        { speaker: 'Felix', de: 'Gemischt. Die Schauspieler waren **beeindruckend**, aber die Handlung war ziemlich **vorhersehbar**.', translation: l('Mixed. The actors were impressive, but the plot was quite predictable.', 'Karışık. Oyuncular etkileyiciydi ama olay örgüsü oldukça tahmin edilebilirdi.', '') },
        { speaker: 'Mina', de: 'Echt? Ich fand die Geschichte **mitreißend**. Es **geht** ja **um** eine wahre Begebenheit.', translation: l('Really? I found the story gripping. It’s about a true story after all.', 'Gerçekten mi? Ben hikâyeyi sürükleyici buldum. Gerçek bir olay anlatılıyor sonuçta.', '') },
        { speaker: 'Felix', de: 'Stimmt. **Besonders gelungen** war die Musik – die hat mich total **überzeugt**.', translation: l('True. The music was particularly good – it totally convinced me.', 'Doğru. Özellikle müzik çok başarılıydı – beni tamamen ikna etti.', '') },
        { speaker: 'Mina', de: 'Und das Ende? Mich hat es zum Weinen gebracht.', translation: l('And the ending? It made me cry.', 'Peki son? Beni ağlattı.', '') },
        { speaker: 'Felix', de: 'Mir war es ein bisschen zu kitschig. Aber das ist wohl **Geschmackssache**.', translation: l('It was a bit too cheesy for me. But I guess that’s a matter of taste.', 'Bana biraz fazla klişe geldi. Ama sanırım zevk meselesi.', '') },
      ],
      examples: [
        { de: 'Der Roman **handelt von** einer Familie.', translation: l('The novel is about a family.', 'Roman bir aile hakkında.', '') },
        { de: 'Es **geht um** Liebe und Verrat.', translation: l('It’s about love and betrayal.', 'Aşk ve ihanet anlatılıyor.', '') },
        { de: 'Die Handlung **spielt in** Rom.', translation: l('The story is set in Rome.', 'Hikâye Roma’da geçiyor.', '') },
        { de: '**Besonders gelungen** ist die Kamera.', translation: l('The camera work is particularly good.', 'Özellikle kamera çalışması başarılı.', '') },
        { de: 'Der Mittelteil ist etwas **langatmig**.', translation: l('The middle part is a bit long-winded.', 'Orta kısım biraz uzun.', '') },
        { de: 'Ich kann den Film nur **empfehlen**.', translation: l('I can only recommend the film.', 'Filmi ancak tavsiye edebilirim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Content or evaluation?', 'İçerik mi değerlendirme mi?', 'Inhalt oder Bewertung?'),
      exercises: ['match-kunst', 'sort-bewertung', 'rez-handelt', 'rez-gelungen', 'rez-langatmig', 'mc-handelt', 'tf-geschmack', 'select-inhalt', 'image-museum'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Summarise and evaluate.', 'Özetle ve değerlendir.', 'Zusammenfassen und bewerten.'),
      exercises: [
        'fill-geht',
        'fill-ueberzeugt',
        'fill-empfehlen',
        'build-spielt',
        'build-gelungen',
        'build-obwohl',
        'fix-handelt',
        'fix-gefallen',
        'fix-spannend',
        'tr-handelt',
        'tr-empfehlen',
        'ordering-rezension',
        'dialog-film',
        'dialog-ausstellung',
        'rez-spielt',
        'rez-empfehlen',
        'rez-ueberzeugt',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A book review.', 'Bir kitap eleştirisi.', 'Eine Buchrezension.'),
      passage: [
        '**„Das Haus am See“** – Der neue Roman von Anna Berger erzählt die Geschichte von drei Generationen einer Familie.',
        'Die Handlung **spielt** in einem alten Haus am Bodensee zwischen 1945 und heute. Im Mittelpunkt steht die Großmutter Ilse, die ein Familiengeheimnis hütet.',
        '**Besonders gelungen** sind die lebendigen Figuren und die poetische Sprache. Der Mittelteil ist allerdings etwas **langatmig**.',
        '**Fazit**: Trotz kleiner Schwächen ein sehr lesenswertes Buch, das man so schnell nicht vergisst.',
      ],
      glossary: [
        { de: 'ein Geheimnis hüten', note: l('to keep a secret', 'bir sırrı saklamak', 'nichts verraten') },
        { de: 'lebendig', note: l('lively', 'canlı', 'wie echt') },
        { de: 'die Schwäche', note: l('weakness', 'zayıflık', 'etwas nicht so Gutes') },
        { de: 'lesenswert', note: l('worth reading', 'okunmaya değer', 'gut zum Lesen') },
      ],
      exercises: ['read-thema', 'read-handlung', 'read-kritik', 'read-fazit'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Opinions on films, books and exhibitions.', 'Filmler, kitaplar ve sergiler hakkında görüşler.', 'Kulturkritik.'),
      exercises: ['listen-kino', 'listen-museum', 'listen-buch', 'listen-geschmack'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present a book, film or series you like – as in a short review.', 'Sevdiğin bir kitabı, filmi ya da diziyi kısa bir eleştiri gibi sun.', 'Stell ein Buch oder einen Film vor.'),
      points: [
        l('Title and genre', 'Başlık ve tür', 'Titel, Genre'),
        l('Content: „Es geht um …“ / „Die Handlung spielt …“', 'İçerik: „Es geht um …“ / „Die Handlung spielt …“', 'Inhalt'),
        l('One strength and one weakness', 'Bir güçlü ve bir zayıf yan', 'Stärke / Schwäche'),
        l('Recommendation: „Ich kann … empfehlen, weil …“', 'Tavsiye: „Ich kann … empfehlen, weil …“', 'Fazit'),
      ],
      model: [
        'Ich möchte die Serie „Dark“ vorstellen – eine deutsche Mystery-Serie.',
        'Es geht um Zeitreisen in einer kleinen Stadt, die Handlung spielt in drei verschiedenen Zeiten.',
        'Besonders gelungen ist die düstere Atmosphäre, aber die vielen Figuren machen es manchmal kompliziert.',
        'Ich kann die Serie trotzdem empfehlen, weil sie unglaublich spannend ist.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a review (at least 6 sentences) of a book, film or exhibition you know.',
        'Bildiğin bir kitap, film ya da sergi hakkında bir eleştiri yaz (en az 6 cümle).',
        'Schreib eine Rezension (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Content (handelt von / es geht um / spielt in)', 'İçerik (handelt von / es geht um / spielt in)', 'Inhalt'), pattern: '(handelt von|geht es um|[Ee]s geht um|spielt in)' },
        { label: l('A positive evaluation (gelungen, spannend, beeindruckend …)', 'Olumlu değerlendirme (gelungen, spannend, beeindruckend …)', 'positiv'), pattern: '(gelungen|spannend|beeindruckend|mitreißend|überzeugend|großartig|überzeugt)' },
        { label: l('A negative point (leider / langatmig / vorhersehbar / aber)', 'Olumsuz nokta (leider / langatmig / vorhersehbar / aber)', 'negativ'), pattern: '([Ll]eider|langatmig|vorhersehbar|oberflächlich|enttäuschend|allerdings)' },
        { label: l('A conclusion / recommendation (Fazit / empfehlen)', 'Sonuç / tavsiye (Fazit / empfehlen)', 'Fazit'), pattern: '(Fazit|empfehlen|empfehlenswert|lesenswert|sehenswert)' },
      ],
      model: [
        'Der Film „Systemsprenger“ von Nora Fingscheidt handelt von einem neunjährigen Mädchen.',
        'Es geht um Benni, die so wütend ist, dass keine Einrichtung sie behalten will.',
        'Besonders gelungen ist die junge Hauptdarstellerin, die unglaublich überzeugend spielt.',
        'Leider sind manche Szenen sehr laut und anstrengend.',
        'Trotzdem hat mich der Film tief berührt.',
        'Fazit: ein wichtiger Film, den ich jedem empfehlen kann.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Content or evaluation? – 60 seconds.', 'İçerik mi değerlendirme mi? – 60 saniye.', 'Inhalt oder Bewertung? – 60 Sekunden.'),
      seconds: 60,
      pool: [...REZ.map(([id]) => `rez-${id}`), 'mc-handelt'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Content: handelt von (Dat.), es geht um (Akk.), spielt in', 'İçerik: handelt von (Dat.), es geht um (Akk.), spielt in', 'Inhalt'),
      l('Positive: gelungen, mitreißend, beeindruckend', 'Olumlu: gelungen, mitreißend, beeindruckend', 'positiv'),
      l('Negative: langatmig, vorhersehbar, oberflächlich', 'Olumsuz: langatmig, vorhersehbar, oberflächlich', 'negativ'),
      l('Review structure: content → strengths → weaknesses → Fazit', 'Eleştiri yapısı: içerik → güçlü yanlar → zayıf yanlar → Fazit', 'Rezension'),
    ],
    mistakes: [
      { wrong: 'handelt über einen Detektiv', right: 'handelt von einem Detektiv', note: l('von + dative.', 'von + Dativ.', 'von.') },
      { wrong: 'Ich habe der Film gefallen.', right: 'Der Film hat mir gefallen.', note: l('gefallen + dative.', 'gefallen + Dativ.', 'mir.') },
      { wrong: 'ein gespannter Krimi', right: 'ein spannender Krimi', note: l('spannend ≠ gespannt.', 'spannend ≠ gespannt.', 'spannend.') },
      { wrong: 'Es geht über Liebe.', right: 'Es geht um Liebe.', note: l('es geht um.', 'es geht um.', 'um.') },
    ],
  },
}
