import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die künstliche Intelligenz (KI)', emoji: '🤖', translation: l('artificial intelligence (AI)', 'yapay zekâ', 'Computer, die „denken“'), example: 'Künstliche Intelligenz verändert viele Berufe.' },
  { word: 'die Digitalisierung', emoji: '💻', translation: l('digitalisation', 'dijitalleşme', 'alles wird digital'), example: 'Die Digitalisierung der Schulen kommt nur langsam voran.' },
  { word: 'die Forschung', emoji: '🔬', translation: l('research', 'araştırma', 'Wissenschaftler untersuchen etwas'), example: 'Die Forschung zu Krebs macht Fortschritte.' },
  { word: 'herausfinden', emoji: '💡', translation: l('to find out', 'ortaya çıkarmak', 'entdecken'), example: 'Forscher haben herausgefunden, dass Schlaf das Gedächtnis stärkt.' },
  { word: 'die Erfindung', emoji: '⚙️', translation: l('invention', 'icat', 'etwas Neues'), example: 'Das Internet ist eine der wichtigsten Erfindungen.' },
  { word: 'entwickeln', emoji: '🛠️', translation: l('to develop', 'geliştirmek', 'neu machen'), example: 'Die Firma entwickelt eine neue App.' },
  { word: 'die Chance', emoji: '🍀', translation: l('opportunity', 'fırsat', 'gute Möglichkeit'), example: 'KI bietet große Chancen für die Medizin.' },
  { word: 'das Risiko', emoji: '⚠️', translation: l('risk', 'risk', 'Gefahr'), example: 'Aber es gibt auch Risiken für den Datenschutz.' },
  { word: 'der Datenschutz', emoji: '🔐', translation: l('data protection', 'veri koruma', 'Schutz persönlicher Daten'), example: 'Der Datenschutz ist in Deutschland sehr wichtig.' },
  { word: 'die Studie zeigt, dass …', emoji: '📑', translation: l('the study shows that …', 'araştırma gösteriyor ki …', 'Ergebnis wiedergeben'), example: 'Die Studie zeigt, dass Jugendliche zu wenig schlafen.' },
  { word: 'Laut Experten …', emoji: '👩‍🔬', translation: l('According to experts …', 'Uzmanlara göre …', 'Quelle nennen'), example: 'Laut Experten wird sich die Arbeitswelt stark verändern.' },
  { word: 'ersetzen', emoji: '🔁', translation: l('to replace', 'yerini almak', 'an die Stelle treten'), example: 'Werden Roboter Menschen ersetzen?' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Forschung', gender: 'f', translation: l('research', 'araştırma', 'Forschung') },
  { word: 'Wissenschaftler', gender: 'm', plural: 'die Wissenschaftler', translation: l('scientist', 'bilim insanı', 'Wissenschaftler') },
  { word: 'Erfindung', gender: 'f', plural: 'die Erfindungen', translation: l('invention', 'icat', 'Erfindung') },
  { word: 'Risiko', gender: 'n', plural: 'die Risiken', translation: l('risk', 'risk', 'Risiko') },
  { word: 'Daten', gender: 'f', plural: 'die Daten', translation: l('data', 'veri', 'Daten') },
  { word: 'Fortschritt', gender: 'm', plural: 'die Fortschritte', translation: l('progress', 'ilerleme', 'Fortschritt') },
  { word: 'Ergebnis', gender: 'n', plural: 'die Ergebnisse', translation: l('result', 'sonuç', 'Ergebnis') },
  { word: 'Experiment', gender: 'n', plural: 'die Experimente', translation: l('experiment', 'deney', 'Experiment') },
]

/** [id, definition, right word, wrong] */
const DEF: [string, string, string, [string, string]][] = [
  ['forschung', 'Wissenschaftler untersuchen systematisch eine Frage.', 'die Forschung', ['die Erfindung', 'der Datenschutz']],
  ['erfindung', 'Jemand hat etwas ganz Neues gebaut oder entwickelt.', 'die Erfindung', ['die Studie', 'das Risiko']],
  ['datenschutz', 'Persönliche Informationen werden vor Missbrauch geschützt.', 'der Datenschutz', ['die Digitalisierung', 'die Forschung']],
  ['risiko', 'Etwas könnte gefährlich sein oder schlecht ausgehen.', 'das Risiko', ['die Chance', 'der Fortschritt']],
  ['fortschritt', 'Etwas entwickelt sich positiv weiter.', 'der Fortschritt', ['das Risiko', 'der Datenschutz']],
  ['experiment', 'Man testet eine Idee unter kontrollierten Bedingungen.', 'das Experiment', ['die Erfindung', 'die Chance']],
]

function defDrills(): Exercise[] {
  return DEF.map(([id, definition, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `def-${id}`,
      type: 'multiple_choice' as const,
      topic: 'wortschatz',
      concept: 'definitions',
      skill: 'vocabulary' as const,
      difficulty: 2 as const,
      prompt: `„${definition}“ – Welches Wort passt?`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`→ ${right}`, `→ ${right}`, `→ ${right}`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-technik',
    type: 'matching',
    topic: 'wortschatz',
    concept: 'tech-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match German and meaning.', 'Almancayı anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'die künstliche Intelligenz', right: 'artificial intelligence' },
      { left: 'der Datenschutz', right: 'data protection' },
      { left: 'herausfinden', right: 'to find out' },
      { left: 'ersetzen', right: 'to replace' },
      { left: 'entwickeln', right: 'to develop' },
    ],
    explanation: l('Key words for science and technology.', 'Bilim ve teknoloji için temel kelimeler.', 'Wortschatz.'),
  },
  {
    id: 'sort-chance-risiko',
    type: 'categorize',
    topic: 'chancen-risiken',
    concept: 'pros-cons',
    skill: 'reading',
    difficulty: 2,
    instructions: l('AI: opportunity or risk?', 'Yapay zekâ: fırsat mı risk mi?', 'KI: Chance oder Risiko?'),
    categories: ['Chance ➕', 'Risiko ➖'],
    items: [
      { text: 'Ärzte erkennen Krankheiten früher.', category: 0 },
      { text: 'Viele Jobs könnten wegfallen.', category: 1 },
      { text: 'Langweilige Arbeit wird automatisiert.', category: 0 },
      { text: 'Falschinformationen werden leichter verbreitet.', category: 1 },
      { text: 'Übersetzungen werden schneller und billiger.', category: 0 },
      { text: 'Persönliche Daten werden missbraucht.', category: 1 },
    ],
    explanation: l('Weighing up opportunities and risks is typical for B2 discussions.', 'Fırsatları ve riskleri tartmak B2 tartışmalarına özgüdür.', 'Chancen und Risiken.'),
    practice: ['def-forschung'],
  },
  {
    id: 'mc-studie',
    type: 'multiple_choice',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Die Studie ___, dass Bildschirmzeit den Schlaf verschlechtert.',
    options: ['zeigt', 'sagt an', 'meint sich'],
    answer: 0,
    explanation: l('Reporting research: Die Studie zeigt / belegt / kommt zu dem Ergebnis, dass …', 'Araştırma aktarmak: Die Studie zeigt / belegt / kommt zu dem Ergebnis, dass …', 'zeigt.'),
    examples: ['Die Studie **zeigt**, dass …'],
    practice: ['fill-ergebnis'],
  },
  {
    id: 'tf-passiv',
    type: 'true_false',
    topic: 'redemittel',
    concept: 'passive-science',
    skill: 'grammar',
    difficulty: 2,
    statement: 'In wissenschaftlichen Texten benutzt man oft das Passiv: „Es wurde untersucht, ob …“',
    answer: true,
    explanation: l('The passive focuses on the process, not on the researcher.', 'Edilgen, araştırmacıya değil sürece odaklanır.', 'Passiv.'),
  },
  {
    id: 'select-quelle',
    type: 'multiple_select',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'writing',
    difficulty: 2,
    promptL10n: l('Which phrases introduce a source? Select all.', 'Hangi ifadeler bir kaynak tanıtıyor? Hepsini seç.', 'Welche nennen eine Quelle?'),
    options: ['Laut einer Studie der Uni Köln …', 'Forscher haben herausgefunden, dass …', 'Ich habe keine Lust.', 'Wie Experten betonen, …', 'Das ist mir egal.'],
    answers: [0, 1, 3],
    explanation: l('laut …, Forscher haben herausgefunden, wie … betonen.', 'laut …, Forscher haben herausgefunden, wie … betonen.', 'Quellen.'),
  },
  {
    id: 'image-roboter',
    type: 'image_choice',
    topic: 'wortschatz',
    concept: 'tech-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'In der Fabrik arbeiten immer mehr Roboter.',
    options: [
      { emoji: '🦾', label: 'Roboter' },
      { emoji: '🌳', label: 'Baum' },
      { emoji: '🐄', label: 'Kuh' },
      { emoji: '🎨', label: 'Malerei' },
    ],
    answer: 0,
    explanation: l('der Roboter.', 'der Roboter.', 'Roboter.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-ergebnis',
    type: 'fill_blank',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Forscher kamen zu dem ___, dass Bewegung gegen Stress hilft.',
    accepted: ['Ergebnis', 'Schluss'],
    base: 'zu dem … kommen',
    explanation: l('zu dem Ergebnis / Schluss kommen, dass …', 'zu dem Ergebnis / Schluss kommen, dass …', 'Ergebnis.'),
    examples: ['Die Forscher kamen zu dem **Ergebnis**, dass …'],
  },
  {
    id: 'fill-heraus',
    type: 'fill_blank',
    topic: 'wortschatz',
    concept: 'tech-words',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Wissenschaftler haben ___gefunden, dass Bienen Gesichter erkennen können.',
    accepted: ['heraus', 'raus'],
    base: 'herausfinden',
    explanation: l('herausfinden → herausgefunden.', 'herausfinden → herausgefunden.', 'heraus.'),
    examples: ['Wissenschaftler haben **heraus**gefunden, …'],
  },
  {
    id: 'fill-ersetzt',
    type: 'fill_blank',
    topic: 'chancen-risiken',
    concept: 'future-work',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Viele befürchten, dass Menschen in Zukunft durch Maschinen ___ werden.',
    accepted: ['ersetzt'],
    base: 'ersetzen → Passiv',
    explanation: l('Passive: ersetzt werden.', 'Edilgen: ersetzt werden.', 'ersetzt.'),
    examples: ['… durch Maschinen **ersetzt** werden.'],
  },
  {
    id: 'build-laut',
    type: 'sentence_builder',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'grammar',
    difficulty: 3,
    chips: ['wird', 'Laut Experten', 'die Arbeitswelt', 'sich stark verändern'],
    answers: [['Laut Experten', 'wird', 'die Arbeitswelt', 'sich stark verändern']],
    translation: l('According to experts the world of work will change a lot.', 'Uzmanlara göre çalışma dünyası çok değişecek.', 'Laut Experten wird die Arbeitswelt sich stark verändern.'),
    explanation: l('Laut … in position 1 → verb next.', 'Laut … 1. konumda → sonra fiil.', 'Laut … wird.'),
    examples: ['**Laut Experten** wird die Arbeitswelt sich stark verändern.'],
  },
  {
    id: 'build-einerseits',
    type: 'sentence_builder',
    topic: 'chancen-risiken',
    concept: 'pros-cons',
    skill: 'grammar',
    difficulty: 3,
    chips: ['bietet KI große Chancen,', 'Einerseits', 'andererseits gibt es Risiken'],
    answers: [['Einerseits', 'bietet KI große Chancen,', 'andererseits gibt es Risiken']],
    translation: l('On the one hand AI offers great opportunities, on the other there are risks.', 'Bir yandan yapay zekâ büyük fırsatlar sunuyor, öte yandan riskler var.', 'Einerseits bietet KI große Chancen, andererseits gibt es Risiken.'),
    explanation: l('einerseits … andererseits + verb in position 2.', 'einerseits … andererseits + fiil 2. konumda.', 'einerseits … andererseits.'),
    examples: ['**Einerseits** bietet KI große Chancen, **andererseits** gibt es Risiken.'],
  },
  {
    id: 'build-untersucht',
    type: 'sentence_builder',
    topic: 'redemittel',
    concept: 'passive-science',
    skill: 'grammar',
    difficulty: 3,
    chips: ['untersucht', 'wurden', 'In der Studie', '2.000 Personen'],
    answers: [['In der Studie', 'wurden', '2.000 Personen', 'untersucht']],
    translation: l('In the study 2,000 people were examined.', 'Araştırmada 2.000 kişi incelendi.', 'In der Studie wurden 2.000 Personen untersucht.'),
    explanation: l('Scientific passive: wurden … untersucht.', 'Bilimsel edilgen: wurden … untersucht.', 'Passiv.'),
    examples: ['In der Studie **wurden** 2.000 Personen **untersucht**.'],
  },
  {
    id: 'fix-studie',
    type: 'error_correction',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Studie zeigt, dass Kinder brauchen mehr Schlaf.',
    accepted: ['Die Studie zeigt, dass Kinder mehr Schlaf brauchen.'],
    explanation: l('dass → verb at the end.', 'dass → fiil sonda.', '… brauchen.'),
    examples: ['…, dass Kinder mehr Schlaf **brauchen**.'],
  },
  {
    id: 'fix-risiko',
    type: 'error_correction',
    topic: 'wortschatz',
    concept: 'plural',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Diese Technik hat viele Risikos.',
    accepted: ['Diese Technik hat viele Risiken.'],
    explanation: l('das Risiko → die Risiken.', 'das Risiko → die Risiken.', 'Risiken.'),
    examples: ['… viele **Risiken**.'],
  },
  {
    id: 'fix-laut',
    type: 'error_correction',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Laut der Experten ist das Problem lösbar.',
    accepted: ['Laut den Experten ist das Problem lösbar.', 'Laut Experten ist das Problem lösbar.', 'Laut der Expertin ist das Problem lösbar.'],
    explanation: l('laut + dative: laut den Experten (plural).', 'laut + Dativ: laut den Experten (çoğul).', 'laut den.'),
    examples: ['**Laut den** Experten ist das Problem lösbar.'],
  },
  {
    id: 'tr-ki',
    type: 'translation',
    topic: 'chancen-risiken',
    concept: 'pros-cons',
    skill: 'writing',
    difficulty: 3,
    source: l('AI can help doctors.', 'Yapay zekâ doktorlara yardım edebilir.', 'AI can help doctors.'),
    accepted: ['KI kann Ärzten helfen.', 'Künstliche Intelligenz kann Ärzten helfen.', 'Die KI kann Ärzten helfen.', 'KI kann Ärztinnen und Ärzten helfen.'],
    explanation: l('helfen + dative: Ärzten.', 'helfen + Dativ: Ärzten.', 'Ärzten.'),
    examples: ['KI kann **Ärzten** helfen.'],
  },
  {
    id: 'tr-studie',
    type: 'translation',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'writing',
    difficulty: 3,
    source: l('The study shows that music reduces stress.', 'Araştırma müziğin stresi azalttığını gösteriyor.', 'The study shows that music reduces stress.'),
    accepted: ['Die Studie zeigt, dass Musik Stress reduziert.', 'Die Studie zeigt, dass Musik Stress verringert.', 'Die Studie zeigt, dass Musik Stress abbaut.'],
    explanation: l('Die Studie zeigt, dass … + verb at the end.', 'Die Studie zeigt, dass … + fiil sonda.', 'zeigt, dass.'),
    examples: ['Die Studie zeigt, dass Musik Stress **reduziert**.'],
  },
  {
    id: 'ordering-studie',
    type: 'ordering',
    topic: 'redemittel',
    concept: 'summary',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order a summary of a study.', 'Bir araştırmanın özetini sırala.', 'Ordne die Zusammenfassung.'),
    items: ['Das Ergebnis: Wer mittags 20 Minuten schläft, konzentriert sich besser.', 'Forscher der Uni Freiburg haben untersucht, wie sich ein Mittagsschlaf auswirkt.', 'Die Forscher empfehlen deshalb kurze Pausen am Arbeitsplatz.', 'Dafür wurden 500 Angestellte vier Wochen lang beobachtet.'],
    answer: ['Forscher der Uni Freiburg haben untersucht, wie sich ein Mittagsschlaf auswirkt.', 'Dafür wurden 500 Angestellte vier Wochen lang beobachtet.', 'Das Ergebnis: Wer mittags 20 Minuten schläft, konzentriert sich besser.', 'Die Forscher empfehlen deshalb kurze Pausen am Arbeitsplatz.'],
    explanation: l('Question → method → result → recommendation.', 'Soru → yöntem → sonuç → öneri.', 'Aufbau einer Studie.'),
  },
  {
    id: 'dialog-ki',
    type: 'dialogue',
    topic: 'chancen-risiken',
    concept: 'opinion',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Moderatorin', de: 'Wie stehen Sie zu künstlicher Intelligenz in der Schule?' }],
    options: ['Ich sehe Chancen, zum Beispiel beim individuellen Lernen, aber man muss auf den Datenschutz achten.', 'KI ist ein Computer.', 'Schule ist künstlich.'],
    answer: 0,
    explanation: l('Balanced opinion: Chance + Risiko.', 'Dengeli fikir: fırsat + risk.', 'Chance + Risiko.'),
  },
  {
    id: 'dialog-quelle',
    type: 'dialogue',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollege', de: 'Woher weißt du, dass Kaffee gesund ist?' }],
    options: ['Laut einer neuen Studie senken drei Tassen am Tag das Risiko für einige Krankheiten.', 'Kaffee ist braun.', 'Ich weiß, weil Kaffee.'],
    answer: 0,
    explanation: l('Name a source: laut einer Studie …', 'Bir kaynak belirt: laut einer Studie …', 'Quelle.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es im Artikel?',
    options: ['Wie KI in Krankenhäusern eingesetzt wird.', 'Wie man Roboter baut.', 'Wie man Programmieren lernt.'],
    answer: 0,
    explanation: l('„KI im Krankenhaus“', '„KI im Krankenhaus“', 'Krankenhaus.'),
  },
  {
    id: 'read-roentgen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wobei hilft die KI den Ärzten?',
    options: ['Beim Auswerten von Röntgenbildern.', 'Beim Operieren.', 'Beim Kochen in der Kantine.'],
    answer: 0,
    explanation: l('„Die Software wertet Röntgenbilder aus …“', '„Die Software wertet Röntgenbilder aus …“', 'Röntgenbilder.'),
  },
  {
    id: 'read-entscheidung',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die KI trifft die endgültige Entscheidung über die Behandlung.',
    answer: false,
    explanation: l('„Die letzte Entscheidung trifft aber immer ein Mensch.“', '„Die letzte Entscheidung trifft aber immer ein Mensch.“', 'falsch.'),
  },
  {
    id: 'read-kritik',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was kritisieren Datenschützer?',
    options: ['Dass sensible Patientendaten gespeichert werden.', 'Dass die KI zu langsam ist.', 'Dass die Ärzte zu wenig verdienen.'],
    answer: 0,
    explanation: l('„Datenschützer warnen, dass sensible Patientendaten gespeichert werden.“', '„Datenschützer warnen, dass sensible Patientendaten gespeichert werden.“', 'Daten.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-studie',
    type: 'listening_choice',
    topic: 'redemittel',
    concept: 'report-research',
    skill: 'listening',
    difficulty: 2,
    audio: 'Eine neue Studie zeigt, dass Menschen, die zwei Sprachen sprechen, im Alter länger geistig fit bleiben.',
    question: l('What does the study show?', 'Araştırma neyi gösteriyor?', 'Was zeigt die Studie?'),
    options: ['Bilingual people stay mentally fit longer.', 'Learning languages is stressful.', 'Older people forget languages.'],
    answer: 0,
    explanation: l('„… im Alter länger geistig fit bleiben.“', '„… im Alter länger geistig fit bleiben.“', 'geistig fit.'),
  },
  {
    id: 'listen-erfindung',
    type: 'listening_choice',
    topic: 'wortschatz',
    concept: 'tech-words',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die wichtigste Erfindung meines Lebens? Ganz klar das Smartphone – ohne geht heute fast nichts mehr.',
    question: l('Which invention does the speaker name?', 'Konuşan hangi icadı söylüyor?', 'Welche Erfindung?'),
    options: ['the smartphone', 'the car', 'the internet'],
    answer: 0,
    explanation: l('„Ganz klar das Smartphone“', '„Ganz klar das Smartphone“', 'Smartphone.'),
  },
  {
    id: 'listen-datenschutz',
    type: 'listening_choice',
    topic: 'chancen-risiken',
    concept: 'pros-cons',
    skill: 'listening',
    difficulty: 3,
    audio: 'Ich nutze gern smarte Lautsprecher, aber ich mache mir Sorgen, dass sie alles mithören, was wir zu Hause sagen.',
    question: l('What worries the speaker?', 'Konuşanı ne endişelendiriyor?', 'Was ist die Sorge?'),
    options: ['that the speakers listen to everything', 'that they are expensive', 'that they break'],
    answer: 0,
    explanation: l('„… dass sie alles mithören …“ → data protection.', '„… dass sie alles mithören …“ → veri koruma.', 'Datenschutz.'),
  },
  {
    id: 'listen-forschung',
    type: 'listening_choice',
    topic: 'redemittel',
    concept: 'passive-science',
    skill: 'listening',
    difficulty: 3,
    audio: 'Für das Experiment wurden Mäuse zwei Wochen lang mit einer speziellen Diät gefüttert.',
    question: l('What was done in the experiment?', 'Deneyde ne yapıldı?', 'Was wurde gemacht?'),
    options: ['Mice were fed a special diet.', 'People ran every day.', 'Plants were grown in the dark.'],
    answer: 0,
    explanation: l('„wurden Mäuse … mit einer speziellen Diät gefüttert“', '„wurden Mäuse … mit einer speziellen Diät gefüttert“', 'Mäuse.'),
  },

  ...defDrills(),
]

export const UNIT_B2_14_WISSENSCHAFT_TECHNIK: CourseUnit = {
  level: 'B2',
  number: 14,
  slug: 'wissenschaft-technik',
  titleDe: 'Wissenschaft und Technik',
  title: l('Science and technology', 'Bilim ve teknoloji', 'Wissenschaft und Technik'),
  goal: l(
    'By the end of this unit you can talk about AI, digitalisation and research, report the results of a study with the right phrases (Die Studie zeigt …, Laut Experten …) and discuss opportunities and risks.',
    'Bu ünitenin sonunda yapay zekâ, dijitalleşme ve araştırma hakkında konuşabilir, bir araştırmanın sonuçlarını doğru kalıplarla aktarabilir (Die Studie zeigt …, Laut Experten …) ve fırsatları ve riskleri tartışabilirsin.',
    'Am Ende dieser Einheit sprichst du über Technik und gibst Studien wieder.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'wortschatz', label: l('Science vocabulary', 'Bilim kelimeleri', 'Wortschatz') },
    { key: 'redemittel', label: l('Reporting research', 'Araştırma aktarmak', 'Studien wiedergeben') },
    { key: 'chancen-risiken', label: l('Opportunities and risks', 'Fırsatlar ve riskler', 'Chancen und Risiken') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The language of science and tech.', 'Bilim ve teknoloji dili.', 'Sprache der Wissenschaft.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Reporting a study', 'Bir araştırmayı aktarmak', 'Eine Studie wiedergeben'),
          body: l(
            'Source: Laut einer Studie der Uni … / Forscher der Uni … haben untersucht, ob/wie … Method: Dafür wurden … befragt/untersucht. Result: Die Studie zeigt / belegt, dass … / Die Forscher kamen zu dem Ergebnis, dass …',
            'Kaynak: Laut einer Studie der Uni … / Forscher der Uni … haben untersucht, ob/wie … Yöntem: Dafür wurden … befragt/untersucht. Sonuç: Die Studie zeigt / belegt, dass … / Die Forscher kamen zu dem Ergebnis, dass …',
            'Quelle → Methode → Ergebnis.'
          ),
          table: {
            head: [l('Step', 'Adım', 'Schritt'), l('Phrase', 'Kalıp', 'Redemittel')],
            rows: [
              ['Quelle', 'Laut einer Studie …'],
              ['Frage', 'Es wurde untersucht, ob …'],
              ['Methode', 'Dafür wurden … befragt.'],
              ['Ergebnis', 'Die Studie zeigt, dass …'],
            ],
          },
        },
        {
          title: l('Opportunities and risks', 'Fırsatlar ve riskler', 'Chancen und Risiken'),
          body: l(
            'Ein großer Vorteil / eine Chance ist … – Ein Risiko / eine Gefahr besteht darin, dass … – Einerseits …, andererseits … – Man darf nicht vergessen, dass …',
            'Ein großer Vorteil / eine Chance ist … – Ein Risiko / eine Gefahr besteht darin, dass … – Einerseits …, andererseits … – Man darf nicht vergessen, dass …',
            'Chance vs. Risiko.'
          ),
          examples: [
            { de: 'Eine **Chance** ist, dass Krankheiten früher erkannt werden.', translation: l('One opportunity is that diseases are detected earlier.', 'Bir fırsat, hastalıkların daha erken tespit edilmesi.', '') },
            { de: 'Ein **Risiko** besteht darin, dass Daten missbraucht werden.', translation: l('One risk is that data is misused.', 'Bir risk, verilerin kötüye kullanılması.', '') },
          ],
        },
        {
          title: l('Passive in scientific texts', 'Bilimsel metinlerde edilgen', 'Passiv in der Wissenschaft'),
          body: l(
            'Science texts focus on what was done, not who did it: Es wurden 500 Personen befragt. Die Daten wurden ausgewertet. Remember Unit B1-03/04 and B2-02.',
            'Bilimsel metinler kimin yaptığına değil ne yapıldığına odaklanır: Es wurden 500 Personen befragt. Die Daten wurden ausgewertet. B1-03/04 ve B2-02 ünitelerini hatırla.',
            'wurde/wurden + Partizip II.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two students discuss an article about AI.', 'İki öğrenci yapay zekâ hakkındaki bir makaleyi tartışıyor.', 'Diskussion über KI.'),
      dialogue: [
        { speaker: 'Lina', de: 'Hast du den Artikel gelesen? **Laut einer Studie** werden in zehn Jahren 30 Prozent der Bürojobs von **KI** erledigt.', translation: l('Did you read the article? According to a study, in ten years 30 per cent of office jobs will be done by AI.', 'Makaleyi okudun mu? Bir araştırmaya göre on yıl içinde ofis işlerinin yüzde 30’u yapay zekâ tarafından yapılacak.', '') },
        { speaker: 'Murat', de: 'Das macht mir Angst. Werden wir alle **ersetzt**?', translation: l('That scares me. Will we all be replaced?', 'Bu beni korkutuyor. Hepimizin yerini mi alacak?', '') },
        { speaker: 'Lina', de: 'Nicht unbedingt. **Die Forscher kamen zu dem Ergebnis**, dass auch viele neue Jobs **entstehen**.', translation: l('Not necessarily. The researchers concluded that many new jobs will also be created.', 'Şart değil. Araştırmacılar birçok yeni işin de ortaya çıkacağı sonucuna vardı.', '') },
        { speaker: 'Murat', de: '**Einerseits** klingt das gut, **andererseits** muss man dafür ganz neue Dinge lernen.', translation: l('On the one hand that sounds good, on the other you have to learn completely new things.', 'Bir yandan iyi geliyor, öte yandan tamamen yeni şeyler öğrenmek gerekiyor.', '') },
        { speaker: 'Lina', de: 'Stimmt. Und **ein Risiko besteht darin**, dass der **Datenschutz** zu kurz kommt.', translation: l('True. And one risk is that data protection falls short.', 'Doğru. Bir risk de veri korumanın ihmal edilmesi.', '') },
        { speaker: 'Murat', de: 'Trotzdem: Die **Chancen** für die Medizin finde ich fantastisch.', translation: l('Still: I find the opportunities for medicine fantastic.', 'Yine de tıp için fırsatları harika buluyorum.', '') },
      ],
      examples: [
        { de: '**Die Studie zeigt**, dass …', translation: l('The study shows that …', 'Araştırma gösteriyor ki …', '') },
        { de: '**Laut Experten** …', translation: l('According to experts …', 'Uzmanlara göre …', '') },
        { de: 'Forscher haben **herausgefunden**, dass …', translation: l('Researchers have found out that …', 'Araştırmacılar … olduğunu ortaya çıkardı.', '') },
        { de: 'Es **wurden** 500 Personen **befragt**.', translation: l('500 people were surveyed.', '500 kişiye soru soruldu.', '') },
        { de: 'Eine **Chance** ist …', translation: l('One opportunity is …', 'Bir fırsat …', '') },
        { de: 'Ein **Risiko** besteht darin, dass …', translation: l('One risk is that …', 'Bir risk de …', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Vocabulary, opportunities and risks.', 'Kelimeler, fırsatlar ve riskler.', 'Wortschatz, Chancen, Risiken.'),
      exercises: ['match-technik', 'sort-chance-risiko', 'def-forschung', 'def-erfindung', 'def-datenschutz', 'mc-studie', 'tf-passiv', 'select-quelle', 'image-roboter'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Report studies and discuss technology.', 'Araştırmaları aktar ve teknolojiyi tartış.', 'Studien wiedergeben.'),
      exercises: [
        'fill-ergebnis',
        'fill-heraus',
        'fill-ersetzt',
        'build-laut',
        'build-einerseits',
        'build-untersucht',
        'fix-studie',
        'fix-risiko',
        'fix-laut',
        'tr-ki',
        'tr-studie',
        'ordering-studie',
        'dialog-ki',
        'dialog-quelle',
        'def-risiko',
        'def-fortschritt',
        'def-experiment',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A newspaper article about AI in hospitals.', 'Hastanelerde yapay zekâ hakkında bir gazete makalesi.', 'KI im Krankenhaus.'),
      passage: [
        '**KI im Krankenhaus** – Seit einem Jahr testet das Uniklinikum Essen eine neue Software.',
        'Die Software wertet Röntgenbilder aus und markiert auffällige Stellen. **Laut den Ärzten** werden so Tumore deutlich früher erkannt.',
        '**Die letzte Entscheidung trifft aber immer ein Mensch**, betont der Chefarzt. Die KI sei nur ein Werkzeug.',
        'Kritik kommt von Datenschützern: Sie warnen, dass sensible Patientendaten gespeichert werden. **Einerseits** rettet die Technik Leben, **andererseits** müsse der Schutz der Daten garantiert sein.',
      ],
      glossary: [
        { de: 'auswerten', note: l('to analyse', 'değerlendirmek', 'analysieren') },
        { de: 'auffällig', note: l('conspicuous', 'dikkat çekici', 'nicht normal') },
        { de: 'das Werkzeug', note: l('tool', 'araç', 'Hilfsmittel') },
        { de: 'sensibel', note: l('sensitive', 'hassas', 'sehr privat') },
      ],
      exercises: ['read-thema', 'read-roentgen', 'read-entscheidung', 'read-kritik'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Research news and everyday tech.', 'Araştırma haberleri ve günlük teknoloji.', 'Forschung und Alltag.'),
      exercises: ['listen-studie', 'listen-erfindung', 'listen-datenschutz', 'listen-forschung'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present a study or a technical development you find interesting and discuss it.', 'İlginç bulduğun bir araştırmayı ya da teknolojik gelişmeyi sun ve tartış.', 'Stell eine Studie vor.'),
      points: [
        l('Source and topic: „Laut einer Studie …“', 'Kaynak ve konu: „Laut einer Studie …“', 'Quelle'),
        l('Method (passive): „Es wurden … befragt.“', 'Yöntem (edilgen): „Es wurden … befragt.“', 'Methode'),
        l('Result: „Die Studie zeigt, dass …“', 'Sonuç: „Die Studie zeigt, dass …“', 'Ergebnis'),
        l('One chance and one risk', 'Bir fırsat ve bir risk', 'Chance + Risiko'),
      ],
      model: [
        'Laut einer Studie der Uni Hamburg nutzen 70 Prozent der Studierenden KI beim Lernen.',
        'Dafür wurden 3.000 Studierende online befragt.',
        'Die Studie zeigt, dass viele schneller lernen, aber weniger selbst schreiben.',
        'Eine Chance ist das individuelle Lernen, ein Risiko besteht darin, dass man das eigene Denken verlernt.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a forum post (at least 6 sentences): „Should AI be used in schools?“ Mention a study and weigh up opportunities and risks.',
        'Bir forum yazısı yaz (en az 6 cümle): „Okullarda yapay zekâ kullanılmalı mı?“ Bir araştırmadan bahset ve fırsatları ve riskleri tart.',
        'Forumsbeitrag: KI in der Schule (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('A source (laut / Studie / Forscher / Experten)', 'Bir kaynak (laut / Studie / Forscher / Experten)', 'Quelle'), pattern: '\\b([Ll]aut|Studie|Forscher|Experten)\\b' },
        { label: l('Chance / Vorteil and Risiko / Nachteil / Gefahr', 'Chance / Vorteil ve Risiko / Nachteil / Gefahr', 'Chance + Risiko'), pattern: '(Chance|Vorteil)[\\s\\S]*(Risiko|Nachteil|Gefahr)|(Risiko|Nachteil|Gefahr)[\\s\\S]*(Chance|Vorteil)' },
        { label: l('Your opinion', 'Fikrin', 'Meinung'), pattern: '([Ii]ch finde|Meiner Meinung nach|[Ii]ch bin der Ansicht|[Ii]ch glaube)' },
      ],
      model: [
        'KI ist heute überall, auch in der Schule.',
        'Laut einer Studie nutzen schon zwei Drittel der Schüler Chatbots für Hausaufgaben.',
        'Ein großer Vorteil ist, dass jeder in seinem eigenen Tempo lernen kann.',
        'Ein Risiko besteht aber darin, dass Schüler nicht mehr selbst nachdenken.',
        'Meiner Meinung nach sollte man KI erlauben, aber klare Regeln aufstellen.',
        'Lehrer müssen zeigen, wie man die Technik sinnvoll benutzt.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Which word fits the definition? – 60 seconds.', 'Hangi kelime tanıma uyuyor? – 60 saniye.', 'Definitionen – 60 Sekunden.'),
      seconds: 60,
      pool: [...DEF.map(([id]) => `def-${id}`), 'mc-studie'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Science words: Forschung, Erfindung, Datenschutz, KI, Digitalisierung', 'Bilim kelimeleri: Forschung, Erfindung, Datenschutz, KI, Digitalisierung', 'Wortschatz'),
      l('Reporting studies: Laut …, Die Studie zeigt, dass …, kam zu dem Ergebnis', 'Araştırma aktarmak: Laut …, Die Studie zeigt, dass …, kam zu dem Ergebnis', 'Studien'),
      l('Passive in science: Es wurden … befragt.', 'Bilimde edilgen: Es wurden … befragt.', 'Passiv'),
      l('Opportunities vs risks: Eine Chance ist … / Ein Risiko besteht darin, dass …', 'Fırsatlar ve riskler: Eine Chance ist … / Ein Risiko besteht darin, dass …', 'Chancen / Risiken'),
    ],
    mistakes: [
      { wrong: 'Die Studie zeigt, dass Kinder brauchen mehr Schlaf.', right: '…, dass Kinder mehr Schlaf brauchen.', note: l('Verb at the end.', 'Fiil sonda.', 'Verb am Ende.') },
      { wrong: 'viele Risikos', right: 'viele Risiken', note: l('Plural.', 'Çoğul.', 'Plural.') },
      { wrong: 'Laut der Experten', right: 'Laut den Experten', note: l('laut + dative.', 'laut + Dativ.', 'Dativ.') },
      { wrong: 'Ich habe herausgefinden.', right: 'Ich habe herausgefunden.', note: l('Participle.', 'Ortaç.', 'herausgefunden.') },
    ],
  },
}
