import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'indem', emoji: '🛠️', translation: l('by (doing)', '… yaparak', 'Mittel / Methode'), example: 'Man spart Geld, indem man selbst kocht.' },
  { word: 'dadurch, dass', emoji: '🔗', translation: l('by the fact that', '… sayesinde', '= indem'), example: 'Dadurch, dass er viel liest, ist sein Wortschatz groß.' },
  { word: 'sodass', emoji: '➡️', translation: l('so that (result)', 'öyle ki, bu yüzden', 'Folge'), example: 'Es schneite stark, sodass die Schule ausfiel.' },
  { word: 'so …, dass', emoji: '📏', translation: l('so … that', 'o kadar … ki', 'Folge mit Intensität'), example: 'Der Film war so spannend, dass ich nicht schlafen konnte.' },
  { word: 'falls', emoji: '☂️', translation: l('in case', 'şayet, … olursa', 'Bedingung'), example: 'Falls es regnet, nimm einen Schirm mit.' },
  { word: 'sofern', emoji: '✔️', translation: l('provided that', '… koşuluyla', 'Bedingung'), example: 'Wir kommen, sofern wir einen Babysitter finden.' },
  { word: 'es sei denn', emoji: '🚫', translation: l('unless', 'meğerki, … olmadıkça', 'Ausnahme'), example: 'Ich komme, es sei denn, ich muss arbeiten.' },
  { word: 'ohne dass', emoji: '🙈', translation: l('without (someone doing)', '… -meden', 'etwas passiert nicht'), example: 'Er ging, ohne dass es jemand merkte.' },
  { word: 'anstatt dass', emoji: '🔀', translation: l('instead of', '… yerine', 'Alternative'), example: 'Anstatt dass er hilft, schaut er fern.' },
  { word: 'je nachdem, ob', emoji: '⚖️', translation: l('depending on whether', '… -e bağlı olarak', 'abhängig von'), example: 'Je nachdem, ob es regnet, grillen wir oder gehen ins Kino.' },
  { word: 'die Folge', emoji: '🎯', translation: l('consequence', 'sonuç', 'Resultat'), example: 'Die Folge war ein langer Stau.' },
  { word: 'die Bedingung', emoji: '📋', translation: l('condition', 'koşul', 'muss erfüllt sein'), example: 'Unter einer Bedingung: Du hilfst mir.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Folge', gender: 'f', plural: 'die Folgen', translation: l('consequence', 'sonuç', 'Folge') },
  { word: 'Bedingung', gender: 'f', plural: 'die Bedingungen', translation: l('condition', 'koşul', 'Bedingung') },
  { word: 'Mittel', gender: 'n', plural: 'die Mittel', translation: l('means', 'araç', 'Mittel') },
  { word: 'Ausnahme', gender: 'f', plural: 'die Ausnahmen', translation: l('exception', 'istisna', 'Ausnahme') },
  { word: 'Methode', gender: 'f', plural: 'die Methoden', translation: l('method', 'yöntem', 'Methode') },
  { word: 'Ergebnis', gender: 'n', plural: 'die Ergebnisse', translation: l('result', 'sonuç', 'Ergebnis') },
  { word: 'Voraussetzung', gender: 'f', plural: 'die Voraussetzungen', translation: l('prerequisite', 'ön koşul', 'Voraussetzung') },
  { word: 'Zweck', gender: 'm', plural: 'die Zwecke', translation: l('purpose', 'amaç', 'Zweck') },
]

/** [id, sentence with gap, right, wrong] */
const KON: [string, string, string, [string, string]][] = [
  ['indem', 'Man lernt Vokabeln am besten, ___ man sie oft wiederholt.', 'indem', ['sodass', 'falls']],
  ['sodass', 'Es regnete stundenlang, ___ das Spiel abgesagt wurde.', 'sodass', ['indem', 'sofern']],
  ['falls', '___ du Hilfe brauchst, ruf mich einfach an.', 'Falls', ['Indem', 'Sodass']],
  ['sofern', 'Wir fahren ans Meer, ___ das Wetter mitspielt.', 'sofern', ['sodass', 'indem']],
  ['es-sei-denn', 'Ich komme pünktlich, ___, der Zug hat Verspätung.', 'es sei denn', ['sofern', 'indem']],
  ['ohne-dass', 'Er hat das Büro verlassen, ___ es jemand bemerkt hat.', 'ohne dass', ['sodass', 'indem']],
]

function konDrills(): Exercise[] {
  return KON.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `kon-${id}`,
      type: 'multiple_choice' as const,
      topic: 'bedeutung',
      concept: 'choose-connector',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'indem = method, sodass = result, falls / sofern = condition, es sei denn = exception, ohne dass = something does not happen.',
        'indem = yöntem, sodass = sonuç, falls / sofern = koşul, es sei denn = istisna, ohne dass = bir şey olmuyor.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-funktion',
    type: 'matching',
    topic: 'bedeutung',
    concept: 'functions',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Match connector and function.', 'Bağlacı işleviyle eşleştir.', 'Konnektor und Funktion.'),
    pairs: [
      { left: 'indem', right: 'Mittel (wie?)' },
      { left: 'sodass', right: 'Folge (mit welchem Ergebnis?)' },
      { left: 'falls', right: 'Bedingung (unter welcher Voraussetzung?)' },
      { left: 'es sei denn', right: 'Ausnahme' },
      { left: 'ohne dass', right: 'etwas passiert nicht' },
    ],
    explanation: l('Each connector answers a different question.', 'Her bağlaç farklı bir soruya cevap verir.', 'Funktionen.'),
  },
  {
    id: 'sort-wortstellung',
    type: 'categorize',
    topic: 'wortstellung',
    concept: 'verb-position',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('Where does the verb go?', 'Fiil nereye gider?', 'Wo steht das Verb?'),
    categories: ['Verb am Ende', 'Verb auf Position 2 (Hauptsatz)'],
    items: [
      { text: 'indem', category: 0 },
      { text: 'es sei denn', category: 1 },
      { text: 'sodass', category: 0 },
      { text: 'deshalb', category: 1 },
      { text: 'falls', category: 0 },
      { text: 'folglich', category: 1 },
    ],
    explanation: l('Careful: after „es sei denn,“ comes a main clause: …, es sei denn, der Zug hat Verspätung.', 'Dikkat: „es sei denn,“den sonra ana cümle gelir: …, es sei denn, der Zug hat Verspätung.', 'es sei denn + Hauptsatz.'),
    practice: ['kon-indem'],
  },
  {
    id: 'mc-dadurch',
    type: 'multiple_choice',
    topic: 'mittel',
    concept: 'dadurch-dass',
    skill: 'grammar',
    difficulty: 3,
    prompt: '___, dass sie täglich übt, macht sie schnelle Fortschritte.',
    options: ['Dadurch', 'Deshalb', 'Damit'],
    answer: 0,
    explanation: l('Dadurch, dass … = indem (method / cause).', 'Dadurch, dass … = indem (yöntem / sebep).', 'Dadurch, dass.'),
    examples: ['**Dadurch, dass** sie täglich übt, macht sie schnelle Fortschritte.'],
    practice: ['fill-so'],
  },
  {
    id: 'tf-falls-wenn',
    type: 'true_false',
    topic: 'bedingung',
    concept: 'falls-sofern',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Falls“ und „sofern“ bedeuten ungefähr dasselbe wie „wenn“ (Bedingung).',
    answer: true,
    explanation: l('falls = in case; sofern = provided that. Both are conditional like wenn.', 'falls = şayet; sofern = … koşuluyla. İkisi de wenn gibi koşul bildirir.', 'Bedingung.'),
  },
  {
    id: 'select-mittel',
    type: 'multiple_select',
    topic: 'mittel',
    concept: 'method',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences answer the question „How?“ (method)? Select all.', 'Hangi cümleler „Nasıl?“ (yöntem) sorusuna cevap veriyor? Hepsini seç.', 'Welche Sätze nennen ein Mittel?'),
    options: ['Er hat abgenommen, indem er mehr Sport gemacht hat.', 'Durch mehr Sport hat er abgenommen.', 'Er hat abgenommen, sodass ihm die Hose zu groß ist.', 'Dadurch, dass er Rad fährt, bleibt er fit.', 'Falls er Sport macht, nimmt er ab.'],
    answers: [0, 1, 3],
    explanation: l('indem / durch / dadurch, dass = method.', 'indem / durch / dadurch, dass = yöntem.', 'Mittel.'),
  },
  {
    id: 'image-folge',
    type: 'image_choice',
    topic: 'folge',
    concept: 'result',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Es hat die ganze Nacht geschneit, sodass die Straßen spiegelglatt sind.',
    options: [
      { emoji: '🧊', label: 'glatte Straßen' },
      { emoji: '☀️', label: 'Sonne' },
      { emoji: '🌴', label: 'Strand' },
      { emoji: '🌻', label: 'Blumen' },
    ],
    answer: 0,
    explanation: l('sodass → the result: icy roads.', 'sodass → sonuç: buzlu yollar.', 'Folge.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-so',
    type: 'fill_blank',
    topic: 'folge',
    concept: 'so-dass',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Musik war ___ laut, dass wir uns nicht unterhalten konnten.',
    accepted: ['so'],
    base: 'so …, dass',
    explanation: l('so + adjective …, dass = so … that.', 'so + sıfat …, dass = o kadar … ki.', 'so.'),
    examples: ['Die Musik war **so** laut, **dass** wir uns nicht unterhalten konnten.'],
  },
  {
    id: 'fill-indem',
    type: 'fill_blank',
    topic: 'mittel',
    concept: 'method',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Du kannst Energie sparen, ___ du die Heizung nachts herunterdrehst.',
    accepted: ['indem'],
    base: 'Wie?',
    explanation: l('Method → indem + verb at the end.', 'Yöntem → indem + fiil sonda.', 'indem.'),
    examples: ['…, **indem** du die Heizung nachts herunterdrehst.'],
  },
  {
    id: 'fill-ohne',
    type: 'fill_blank',
    topic: 'bedeutung',
    concept: 'ohne-dass',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Sie hat das Auto verkauft, ___ dass ihr Mann davon wusste.',
    accepted: ['ohne'],
    base: 'etwas passiert nicht',
    explanation: l('ohne dass = without someone else doing something.', 'ohne dass = başka biri bir şey yapmadan.', 'ohne dass.'),
    examples: ['…, **ohne dass** ihr Mann davon wusste.'],
  },
  {
    id: 'build-sofern',
    type: 'sentence_builder',
    topic: 'bedingung',
    concept: 'falls-sofern',
    skill: 'grammar',
    difficulty: 3,
    chips: ['nichts dagegen hast', 'sofern', 'Ich bringe meinen Hund mit,', 'du'],
    answers: [['Ich bringe meinen Hund mit,', 'sofern', 'du', 'nichts dagegen hast']],
    translation: l('I’ll bring my dog, provided you don’t mind.', 'Sakıncası yoksa köpeğimi getireceğim.', 'Ich bringe meinen Hund mit, sofern du nichts dagegen hast.'),
    explanation: l('sofern + verb at the end.', 'sofern + fiil sonda.', 'sofern … hast.'),
    examples: ['…, **sofern** du nichts dagegen **hast**.'],
  },
  {
    id: 'build-es-sei-denn',
    type: 'sentence_builder',
    topic: 'bedingung',
    concept: 'exception',
    skill: 'grammar',
    difficulty: 3,
    chips: ['es regnet', 'es sei denn,', 'Wir grillen am Samstag,'],
    answers: [['Wir grillen am Samstag,', 'es sei denn,', 'es regnet']],
    translation: l('We’ll have a barbecue on Saturday, unless it rains.', 'Cumartesi mangal yapıyoruz, yağmur yağmazsa.', 'Wir grillen am Samstag, es sei denn, es regnet.'),
    explanation: l('es sei denn + main clause word order (verb in position 2).', 'es sei denn + ana cümle dizimi (fiil 2. konumda).', 'es regnet.'),
    examples: ['…, **es sei denn**, es **regnet**.'],
  },
  {
    id: 'build-sodass',
    type: 'sentence_builder',
    topic: 'folge',
    concept: 'result',
    skill: 'grammar',
    difficulty: 3,
    chips: ['sodass', 'Der Akku war leer,', 'nicht anrufen konnte', 'ich'],
    answers: [['Der Akku war leer,', 'sodass', 'ich', 'nicht anrufen konnte']],
    translation: l('The battery was flat, so I couldn’t call.', 'Batarya bitmişti, bu yüzden arayamadım.', 'Der Akku war leer, sodass ich nicht anrufen konnte.'),
    explanation: l('sodass + verb at the end.', 'sodass + fiil sonda.', 'sodass … konnte.'),
    examples: ['Der Akku war leer, **sodass** ich nicht anrufen **konnte**.'],
  },
  {
    id: 'fix-es-sei-denn',
    type: 'error_correction',
    topic: 'wortstellung',
    concept: 'verb-position',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich bin morgen im Büro, es sei denn, ich krank bin.',
    accepted: ['Ich bin morgen im Büro, es sei denn, ich bin krank.'],
    explanation: l('After „es sei denn,“: main clause (verb in position 2).', '„es sei denn,“den sonra: ana cümle (fiil 2. konumda).', 'ich bin krank.'),
    examples: ['…, es sei denn, ich **bin** krank.'],
  },
  {
    id: 'fix-indem',
    type: 'error_correction',
    topic: 'mittel',
    concept: 'method',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Er hat Deutsch gelernt, indem er hat viele Serien geschaut.',
    accepted: ['Er hat Deutsch gelernt, indem er viele Serien geschaut hat.'],
    explanation: l('indem → verb at the end.', 'indem → fiil sonda.', '… geschaut hat.'),
    examples: ['…, indem er viele Serien geschaut **hat**.'],
  },
  {
    id: 'fix-damit-sodass',
    type: 'error_correction',
    topic: 'folge',
    concept: 'result',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Zug hatte Verspätung, damit ich den Anschluss verpasst habe.',
    accepted: ['Der Zug hatte Verspätung, sodass ich den Anschluss verpasst habe.'],
    explanation: l('Result, not purpose → sodass (damit = so that, purpose).', 'Amaç değil sonuç → sodass (damit = amaç).', 'sodass.'),
    examples: ['…, **sodass** ich den Anschluss verpasst habe.'],
  },
  {
    id: 'tr-indem',
    type: 'translation',
    topic: 'mittel',
    concept: 'method',
    skill: 'writing',
    difficulty: 3,
    source: l('You can improve your German by reading a lot.', 'Çok okuyarak Almancanı geliştirebilirsin.', 'You can improve your German by reading a lot.'),
    accepted: ['Du kannst dein Deutsch verbessern, indem du viel liest.', 'Man kann sein Deutsch verbessern, indem man viel liest.', 'Sie können Ihr Deutsch verbessern, indem Sie viel lesen.'],
    explanation: l('by + -ing = indem + clause.', '… yaparak = indem + yan cümle.', 'indem.'),
    examples: ['…, **indem** du viel **liest**.'],
  },
  {
    id: 'tr-falls',
    type: 'translation',
    topic: 'bedingung',
    concept: 'falls-sofern',
    skill: 'writing',
    difficulty: 2,
    source: l('In case you are late, text me.', 'Geç kalırsan bana mesaj at.', 'In case you are late, text me.'),
    accepted: ['Falls du zu spät kommst, schreib mir.', 'Falls du dich verspätest, schreib mir.', 'Falls du zu spät kommst, schreib mir eine Nachricht.', 'Falls du Verspätung hast, schreib mir.'],
    explanation: l('Falls …, + imperative.', 'Falls …, + emir.', 'Falls.'),
    examples: ['**Falls** du zu spät kommst, schreib mir.'],
  },
  {
    id: 'ordering-tipps',
    type: 'ordering',
    topic: 'bedeutung',
    concept: 'text',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Order the advice text logically.', 'Tavsiye metnini mantıklı sırala.', 'Ordne den Ratgeber.'),
    items: ['Falls das nicht hilft, sprechen Sie mit Ihrem Arzt.', 'Viele Menschen schlafen schlecht.', 'Man kann besser schlafen, indem man abends aufs Handy verzichtet.', 'Dadurch, dass der Körper zur Ruhe kommt, schläft man schneller ein.'],
    answer: ['Viele Menschen schlafen schlecht.', 'Man kann besser schlafen, indem man abends aufs Handy verzichtet.', 'Dadurch, dass der Körper zur Ruhe kommt, schläft man schneller ein.', 'Falls das nicht hilft, sprechen Sie mit Ihrem Arzt.'],
    explanation: l('Problem → method → explanation → alternative.', 'Sorun → yöntem → açıklama → alternatif.', 'Aufbau.'),
  },
  {
    id: 'dialog-bedingung',
    type: 'dialogue',
    topic: 'bedingung',
    concept: 'exception',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Kommst du am Samstag zum Umzug helfen?' }],
    options: ['Klar, es sei denn, mein Chef ruft mich zur Arbeit.', 'Klar, sodass Samstag.', 'Ich ziehe indem um.'],
    answer: 0,
    explanation: l('Yes + an exception: es sei denn, …', 'Evet + bir istisna: es sei denn, …', 'es sei denn.'),
  },
  {
    id: 'dialog-wie',
    type: 'dialogue',
    topic: 'mittel',
    concept: 'method',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Wie hast du es geschafft, so schnell Deutsch zu lernen?' }],
    options: ['Vor allem, indem ich jeden Tag mit Muttersprachlern gesprochen habe.', 'Sodass ich Deutsch kann.', 'Falls Deutsch.'],
    answer: 0,
    explanation: l('Answer „how?“ with indem.', '„Nasıl?“ sorusuna indem ile cevap ver.', 'indem.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es im Text?',
    options: ['Wie man im Alltag Geld sparen kann.', 'Wie man einen Kredit bekommt.', 'Wie man reich heiratet.'],
    answer: 0,
    explanation: l('„Sparen im Alltag – so geht’s“', '„Sparen im Alltag – so geht’s“', 'Sparen.'),
  },
  {
    id: 'read-einkauf',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie spart man beim Einkaufen?',
    options: ['Indem man mit Einkaufsliste und nicht hungrig einkauft.', 'Indem man nur online kauft.', 'Indem man nie einkauft.'],
    answer: 0,
    explanation: l('„… indem man mit einer Liste und nie hungrig einkaufen geht.“', '„… indem man mit einer Liste und nie hungrig einkaufen geht.“', 'Liste.'),
  },
  {
    id: 'read-abo',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 2,
    statement: 'Der Text empfiehlt, alle Abos sofort zu kündigen.',
    answer: false,
    explanation: l('„… es sei denn, man nutzt sie wirklich regelmäßig.“ – only unused ones.', '„… es sei denn, man nutzt sie wirklich regelmäßig.“ – sadece kullanılmayanlar.', 'falsch.'),
  },
  {
    id: 'read-folge',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was ist die Folge, wenn man Strom spart?',
    options: ['Man spart oft über 100 Euro im Jahr.', 'Die Wohnung wird kalt.', 'Man muss mehr bezahlen.'],
    answer: 0,
    explanation: l('„… sodass man oft über 100 Euro im Jahr spart.“', '„… sodass man oft über 100 Euro im Jahr spart.“', '100 Euro.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-sofern',
    type: 'listening_choice',
    topic: 'bedingung',
    concept: 'falls-sofern',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das Konzert findet im Park statt, sofern es nicht regnet. Sonst gehen wir in die Halle.',
    question: l('Where will the concert be if it rains?', 'Yağmur yağarsa konser nerede olacak?', 'Wo bei Regen?'),
    options: ['in the hall', 'in the park', 'it is cancelled'],
    answer: 0,
    explanation: l('„Sonst gehen wir in die Halle.“', '„Sonst gehen wir in die Halle.“', 'Halle.'),
  },
  {
    id: 'listen-indem',
    type: 'listening_choice',
    topic: 'mittel',
    concept: 'method',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich habe meine Angst vor dem Fliegen besiegt, indem ich einen Kurs am Flughafen gemacht habe.',
    question: l('How did the speaker overcome the fear of flying?', 'Konuşan uçma korkusunu nasıl yendi?', 'Wie?'),
    options: ['with a course at the airport', 'with medicine', 'by never flying'],
    answer: 0,
    explanation: l('„indem ich einen Kurs am Flughafen gemacht habe“', '„indem ich einen Kurs am Flughafen gemacht habe“', 'Kurs.'),
  },
  {
    id: 'listen-sodass',
    type: 'listening_choice',
    topic: 'folge',
    concept: 'result',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Server war zwei Stunden ausgefallen, sodass niemand arbeiten konnte.',
    question: l('What was the consequence?', 'Sonuç ne oldu?', 'Was war die Folge?'),
    options: ['Nobody could work.', 'Everyone went home happy.', 'The server got faster.'],
    answer: 0,
    explanation: l('„sodass niemand arbeiten konnte“', '„sodass niemand arbeiten konnte“', 'niemand.'),
  },
  {
    id: 'listen-ohne',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'ohne-dass',
    skill: 'listening',
    difficulty: 3,
    audio: 'Mein Mitbewohner hat meinen Joghurt gegessen, ohne dass er mich gefragt hat.',
    question: l('What is the problem?', 'Sorun ne?', 'Was ist das Problem?'),
    options: ['He ate it without asking.', 'He asked twice.', 'He bought new yoghurt.'],
    answer: 0,
    explanation: l('„ohne dass er mich gefragt hat“', '„ohne dass er mich gefragt hat“', 'ohne zu fragen.'),
  },

  ...konDrills(),
]

export const UNIT_B2_07_KONNEKTOREN_B2: CourseUnit = {
  level: 'B2',
  number: 7,
  slug: 'konnektoren-b2',
  titleDe: 'Indem, sodass, falls',
  title: l('By, so that, in case', '… yaparak, böylece, eğer', 'Indem, sodass, falls'),
  goal: l(
    'By the end of this unit you can express method (indem, dadurch, dass), result (sodass, so … dass), conditions (falls, sofern), exceptions (es sei denn) and missing actions (ohne dass) – with the correct word order.',
    'Bu ünitenin sonunda yöntem (indem, dadurch, dass), sonuç (sodass, so … dass), koşul (falls, sofern), istisna (es sei denn) ve gerçekleşmeyen eylemleri (ohne dass) doğru kelime dizimiyle ifade edebilirsin.',
    'Am Ende dieser Einheit benutzt du B2-Konnektoren sicher.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'mittel', label: l('Method (indem)', 'Yöntem (indem)', 'Mittel') },
    { key: 'folge', label: l('Result (sodass)', 'Sonuç (sodass)', 'Folge') },
    { key: 'bedingung', label: l('Condition & exception', 'Koşul ve istisna', 'Bedingung') },
    { key: 'bedeutung', label: l('Choosing the connector', 'Bağlaç seçmek', 'Bedeutung') },
    { key: 'wortstellung', label: l('Word order', 'Kelime dizimi', 'Wortstellung') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Connectors for precise arguments.', 'Kesin argümanlar için bağlaçlar.', 'Konnektoren für präzise Sätze.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Method and result', 'Yöntem ve sonuç', 'Mittel und Folge'),
          body: l(
            'indem / dadurch, dass answers „How?“: Man spart Geld, indem man selbst kocht. sodass / so …, dass describes the result: Es regnete, sodass das Spiel ausfiel. Don’t confuse sodass (result) with damit (purpose).',
            'indem / dadurch, dass „Nasıl?“ sorusunu cevaplar: Man spart Geld, indem man selbst kocht. sodass / so …, dass sonucu anlatır: Es regnete, sodass das Spiel ausfiel. sodass (sonuç) ile damit’i (amaç) karıştırma.',
            'indem = wie?; sodass = Folge.'
          ),
          examples: [
            { de: 'Er bleibt fit, **indem** er jeden Tag Rad **fährt**.', translation: l('He stays fit by cycling every day.', 'Her gün bisiklet sürerek formda kalıyor.', '') },
            { de: 'Es war **so** kalt, **dass** der See zufror.', translation: l('It was so cold that the lake froze.', 'O kadar soğuktu ki göl dondu.', '') },
          ],
        },
        {
          title: l('Conditions and exceptions', 'Koşullar ve istisnalar', 'Bedingung und Ausnahme'),
          body: l(
            'falls = in case, sofern = provided that (both like wenn, verb at the end). es sei denn = unless – followed by a main clause: Ich komme, es sei denn, ich bin krank.',
            'falls = şayet, sofern = … koşuluyla (ikisi de wenn gibi, fiil sonda). es sei denn = meğerki – ardından ana cümle gelir: Ich komme, es sei denn, ich bin krank.',
            'falls / sofern + Verb am Ende; es sei denn + Hauptsatz.'
          ),
          table: {
            head: [l('Connector', 'Bağlaç', 'Konnektor'), l('Function', 'İşlev', 'Funktion'), l('Verb', 'Fiil', 'Verb')],
            rows: [
              ['indem', 'Mittel', 'Ende'],
              ['sodass', 'Folge', 'Ende'],
              ['falls / sofern', 'Bedingung', 'Ende'],
              ['es sei denn,', 'Ausnahme', 'Position 2'],
              ['ohne dass', 'nicht passiert', 'Ende'],
            ],
          },
        },
        {
          title: l('ohne dass and anstatt dass', 'ohne dass ve anstatt dass', 'ohne dass / anstatt dass'),
          body: l(
            'With two different subjects use ohne dass / anstatt dass + clause. With the same subject use ohne … zu / anstatt … zu: Er ging, ohne sich zu verabschieden.',
            'İki farklı özne varsa ohne dass / anstatt dass + yan cümle kullan. Aynı özne varsa ohne … zu / anstatt … zu: Er ging, ohne sich zu verabschieden.',
            'verschiedene Subjekte → dass.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two flatmates plan to save money.', 'İki ev arkadaşı para biriktirmeyi planlıyor.', 'Wir müssen sparen!'),
      dialogue: [
        { speaker: 'Mara', de: 'Unsere Stromrechnung ist **so** hoch, **dass** ich fast umgefallen bin.', translation: l('Our electricity bill is so high that I almost fell over.', 'Elektrik faturamız o kadar yüksek ki neredeyse düşüp bayılacaktım.', '') },
        { speaker: 'Emre', de: 'Wir könnten sparen, **indem** wir die Geräte ganz ausschalten.', translation: l('We could save by switching the devices off completely.', 'Cihazları tamamen kapatarak tasarruf edebiliriz.', '') },
        { speaker: 'Mara', de: 'Gute Idee. Und **falls** das nicht reicht, wechseln wir den Anbieter.', translation: l('Good idea. And in case that’s not enough, we’ll change provider.', 'İyi fikir. Yetmezse de sağlayıcıyı değiştiririz.', '') },
        { speaker: 'Emre', de: 'Okay. Ich koche ab jetzt jeden Tag, **es sei denn**, ich habe Spätschicht.', translation: l('Okay. I’ll cook every day from now on, unless I have a late shift.', 'Tamam. Bundan sonra her gün yemek yaparım, geç vardiyam yoksa.', '') },
        { speaker: 'Mara', de: 'Super. Aber bitte nicht wieder meinen Käse essen, **ohne dass** du fragst!', translation: l('Great. But please don’t eat my cheese again without asking!', 'Süper. Ama lütfen yine sormadan peynirimi yeme!', '') },
        { speaker: 'Emre', de: '(lacht) Versprochen – **sofern** du meine Schokolade in Ruhe lässt.', translation: l('(laughs) Promise – provided you leave my chocolate alone.', '(güler) Söz – çikolatama dokunmazsan.', '') },
      ],
      examples: [
        { de: 'Man spart, **indem** man selbst kocht.', translation: l('You save by cooking yourself.', 'Kendin yemek yaparak tasarruf edersin.', '') },
        { de: 'Es regnete, **sodass** das Spiel ausfiel.', translation: l('It rained, so the match was cancelled.', 'Yağmur yağdı, bu yüzden maç iptal oldu.', '') },
        { de: '**Falls** du Zeit hast, komm vorbei.', translation: l('In case you have time, drop by.', 'Vaktin olursa uğra.', '') },
        { de: 'Wir kommen, **sofern** es nicht regnet.', translation: l('We’ll come provided it doesn’t rain.', 'Yağmur yağmazsa geliriz.', '') },
        { de: 'Ich helfe, **es sei denn**, ich muss arbeiten.', translation: l('I’ll help, unless I have to work.', 'Çalışmam gerekmezse yardım ederim.', '') },
        { de: 'Er ging, **ohne dass** es jemand merkte.', translation: l('He left without anyone noticing.', 'Kimse fark etmeden gitti.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which connector does what?', 'Hangi bağlaç ne yapar?', 'Welcher Konnektor?'),
      exercises: ['match-funktion', 'sort-wortstellung', 'kon-indem', 'kon-sodass', 'kon-falls', 'mc-dadurch', 'tf-falls-wenn', 'select-mittel', 'image-folge'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Connect ideas precisely.', 'Fikirleri kesin biçimde bağla.', 'Präzise verbinden.'),
      exercises: [
        'fill-so',
        'fill-indem',
        'fill-ohne',
        'build-sofern',
        'build-es-sei-denn',
        'build-sodass',
        'fix-es-sei-denn',
        'fix-indem',
        'fix-damit-sodass',
        'tr-indem',
        'tr-falls',
        'ordering-tipps',
        'dialog-bedingung',
        'dialog-wie',
        'kon-sofern',
        'kon-es-sei-denn',
        'kon-ohne-dass',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A guide to saving money.', 'Para biriktirme rehberi.', 'Ein Spar-Ratgeber.'),
      passage: [
        '**Sparen im Alltag – so geht’s**',
        'Beim Einkaufen spart man am meisten, **indem** man mit einer Liste und nie hungrig einkaufen geht.',
        'Prüfen Sie Ihre Abos: Kündigen Sie Streaming-Dienste und Zeitschriften, **es sei denn**, Sie nutzen sie wirklich regelmäßig.',
        'Geräte im Stand-by-Modus verbrauchen Strom, **ohne dass** man es merkt. Schalten Sie sie ganz aus, **sodass** Sie oft über 100 Euro im Jahr sparen. **Falls** Sie unsicher sind, hilft eine Energieberatung.',
      ],
      glossary: [
        { de: 'das Abo (Abonnement)', note: l('subscription', 'abonelik', 'regelmäßige Zahlung') },
        { de: 'der Stand-by-Modus', note: l('standby mode', 'bekleme modu', 'Gerät halb an') },
        { de: 'verbrauchen', note: l('to consume', 'tüketmek', 'benutzen') },
        { de: 'die Energieberatung', note: l('energy advice', 'enerji danışmanlığı', 'Beratung zum Sparen') },
      ],
      exercises: ['read-thema', 'read-einkauf', 'read-abo', 'read-folge'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Conditions, methods and results.', 'Koşullar, yöntemler ve sonuçlar.', 'Bedingungen und Folgen.'),
      exercises: ['listen-sofern', 'listen-indem', 'listen-sodass', 'listen-ohne'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Give tips: How can you learn a language / stay healthy / save money?', 'Tavsiye ver: Bir dil nasıl öğrenilir / nasıl sağlıklı kalınır / nasıl para biriktirilir?', 'Gib Tipps.'),
      points: [
        l('Two methods with indem', 'indem ile iki yöntem', 'indem'),
        l('A result with sodass', 'sodass ile bir sonuç', 'sodass'),
        l('A condition with falls / sofern', 'falls / sofern ile bir koşul', 'falls / sofern'),
        l('An exception with es sei denn', 'es sei denn ile bir istisna', 'es sei denn'),
      ],
      model: [
        'Man lernt eine Sprache am schnellsten, indem man jeden Tag ein bisschen übt.',
        'Ich habe Podcasts gehört, sodass ich heute fast alles verstehe.',
        'Falls du wenig Zeit hast, reichen zehn Minuten am Tag.',
        'Pausen sind okay, es sei denn, sie dauern mehrere Wochen.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short guide (at least 5 sentences): „How to sleep better“ or a topic of your choice. Use at least three different connectors from this unit.',
        'Kısa bir rehber yaz (en az 5 cümle): „Daha iyi nasıl uyunur“ ya da istediğin bir konu. Bu üniteden en az üç farklı bağlaç kullan.',
        'Schreib einen Ratgeber (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('indem / dadurch, dass', 'indem / dadurch, dass', 'indem'), pattern: '\\b(indem|[Dd]adurch, dass)\\b' },
        { label: l('sodass / so … dass', 'sodass / so … dass', 'sodass'), pattern: '\\b(sodass|so \\p{Ll}+, dass)\\b' },
        { label: l('A condition (falls / sofern / es sei denn)', 'Bir koşul (falls / sofern / es sei denn)', 'Bedingung'), pattern: '\\b([Ff]alls|[Ss]ofern|es sei denn)\\b' },
      ],
      model: [
        'Viele Menschen schlafen schlecht, weil sie abends zu viel am Handy sind.',
        'Man kann besser schlafen, indem man eine Stunde vorher das Handy weglegt.',
        'Außerdem sollte das Schlafzimmer kühl sein, sodass der Körper zur Ruhe kommt.',
        'Kaffee am Nachmittag ist tabu, es sei denn, man verträgt ihn gut.',
        'Falls das alles nicht hilft, sollte man zum Arzt gehen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Pick the connector – 60 seconds.', 'Bağlacı seç – 60 saniye.', 'Konnektor wählen – 60 Sekunden.'),
      seconds: 60,
      pool: [...KON.map(([id]) => `kon-${id}`), 'mc-dadurch'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Method: indem, dadurch, dass', 'Yöntem: indem, dadurch, dass', 'Mittel'),
      l('Result: sodass, so …, dass', 'Sonuç: sodass, so …, dass', 'Folge'),
      l('Condition / exception: falls, sofern, es sei denn', 'Koşul / istisna: falls, sofern, es sei denn', 'Bedingung'),
      l('ohne dass / anstatt dass with different subjects', 'Farklı öznelerle ohne dass / anstatt dass', 'ohne dass'),
    ],
    mistakes: [
      { wrong: '…, es sei denn, ich krank bin.', right: '…, es sei denn, ich bin krank.', note: l('Main clause after es sei denn.', 'es sei denn’den sonra ana cümle.', 'Hauptsatz.') },
      { wrong: '…, indem er hat viel gelesen.', right: '…, indem er viel gelesen hat.', note: l('Verb at the end.', 'Fiil sonda.', 'Verb am Ende.') },
      { wrong: 'Es regnete, damit das Spiel ausfiel.', right: 'Es regnete, sodass das Spiel ausfiel.', note: l('Result ≠ purpose.', 'Sonuç ≠ amaç.', 'sodass.') },
      { wrong: 'Er ging, ohne dass er sich verabschiedet.', right: 'Er ging, ohne sich zu verabschieden.', note: l('Same subject → ohne … zu.', 'Aynı özne → ohne … zu.', 'ohne … zu.') },
    ],
  },
}
