import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'aufgrund', emoji: '❓', translation: l('due to', '… nedeniyle', '= wegen'), example: 'Aufgrund des Wetters fällt der Flug aus.' },
  { word: 'infolge', emoji: '➡️', translation: l('as a result of', '… sonucunda', 'Folge'), example: 'Infolge des Unfalls gab es einen langen Stau.' },
  { word: 'angesichts', emoji: '👀', translation: l('in view of', '… karşısında, … göz önüne alındığında', 'wenn man … sieht'), example: 'Angesichts der Lage bleiben wir zu Hause.' },
  { word: 'innerhalb', emoji: '⏳', translation: l('within', '… içinde', 'in der Zeit von'), example: 'Bitte antworten Sie innerhalb einer Woche.' },
  { word: 'außerhalb', emoji: '🏞️', translation: l('outside (of)', '… dışında', 'nicht drinnen'), example: 'Wir wohnen außerhalb der Stadt.' },
  { word: 'trotz', emoji: '🔄', translation: l('despite', '… -e rağmen', 'Gegensatz'), example: 'Trotz des Regens gingen wir spazieren.' },
  { word: '(an)statt', emoji: '🔀', translation: l('instead of', '… yerine', 'Alternative'), example: 'Statt eines Autos kaufte er ein Fahrrad.' },
  { word: 'während', emoji: '⏱️', translation: l('during', '… sırasında', 'zur gleichen Zeit'), example: 'Während des Films schlief er ein.' },
  { word: 'bezüglich', emoji: '📌', translation: l('regarding', '… ile ilgili', 'zum Thema'), example: 'Bezüglich Ihrer Anfrage melden wir uns morgen.' },
  { word: 'mithilfe', emoji: '🤝', translation: l('with the help of', '… yardımıyla', 'durch'), example: 'Mithilfe einer App lernt sie Vokabeln.' },
  { word: 'zugunsten', emoji: '💚', translation: l('in favour of', '… lehine', 'für'), example: 'Das Konzert findet zugunsten der Tafel statt.' },
  { word: 'laut', emoji: '📰', translation: l('according to', '… -e göre', 'nach Angaben'), example: 'Laut des Berichts / Laut dem Bericht …' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Lage', gender: 'f', plural: 'die Lagen', translation: l('situation', 'durum', 'Lage') },
  { word: 'Unfall', gender: 'm', plural: 'die Unfälle', translation: l('accident', 'kaza', 'Unfall') },
  { word: 'Anfrage', gender: 'f', plural: 'die Anfragen', translation: l('inquiry', 'talep, sorgu', 'Anfrage') },
  { word: 'Frist', gender: 'f', plural: 'die Fristen', translation: l('deadline', 'süre', 'Frist') },
  { word: 'Sturm', gender: 'm', plural: 'die Stürme', translation: l('storm', 'fırtına', 'Sturm') },
  { word: 'Streik', gender: 'm', plural: 'die Streiks', translation: l('strike', 'grev', 'Streik') },
  { word: 'Umstand', gender: 'm', plural: 'die Umstände', translation: l('circumstance', 'koşul, durum', 'Umstand') },
  { word: 'Öffnungszeit', gender: 'f', plural: 'die Öffnungszeiten', translation: l('opening hours', 'çalışma saatleri', 'Öffnungszeit') },
]

/** [id, sentence with gap, right, wrong] */
const PRAEP: [string, string, string, [string, string]][] = [
  ['aufgrund', '___ des starken Windes wurde die Fähre gestrichen.', 'Aufgrund', ['Trotz', 'Statt']],
  ['trotz', '___ der Warnungen fuhren viele Leute in die Berge.', 'Trotz', ['Innerhalb', 'Mithilfe']],
  ['innerhalb', 'Bitte bezahlen Sie die Rechnung ___ einer Woche.', 'innerhalb', ['angesichts', 'zugunsten']],
  ['statt', '___ eines Autos kaufte er sich ein Lastenrad.', 'Statt', ['Infolge', 'Bezüglich']],
  ['waehrend', '___ des Fluges ist das Rauchen verboten.', 'Während', ['Zugunsten', 'Angesichts']],
  ['angesichts', '___ der hohen Preise verzichten viele auf Urlaub.', 'Angesichts', ['Innerhalb', 'Statt']],
]

function praepDrills(): Exercise[] {
  return PRAEP.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `praep-${id}`,
      type: 'multiple_choice' as const,
      topic: 'bedeutung',
      concept: 'choose-preposition',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'aufgrund = cause, trotz = contrast, innerhalb = time limit, statt = alternative, während = time, angesichts = in view of. All + genitive.',
        'aufgrund = sebep, trotz = karşıtlık, innerhalb = süre sınırı, statt = alternatif, während = zaman, angesichts = … göz önüne alındığında. Hepsi + Genitiv.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-bedeutung',
    type: 'matching',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match preposition and meaning.', 'Edatı anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'aufgrund', right: 'due to' },
      { left: 'infolge', right: 'as a result of' },
      { left: 'angesichts', right: 'in view of' },
      { left: 'bezüglich', right: 'regarding' },
      { left: 'zugunsten', right: 'in favour of' },
    ],
    explanation: l('Formal prepositions with genitive.', 'Genitiv alan resmî edatlar.', 'Präpositionen mit Genitiv.'),
  },
  {
    id: 'sort-funktion',
    type: 'categorize',
    topic: 'bedeutung',
    concept: 'groups',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Cause, time or place?', 'Sebep, zaman mı yer mi?', 'Grund, Zeit oder Ort?'),
    categories: ['Grund', 'Zeit', 'Ort'],
    items: [
      { text: 'aufgrund', category: 0 },
      { text: 'während', category: 1 },
      { text: 'außerhalb der Stadt', category: 2 },
      { text: 'infolge', category: 0 },
      { text: 'innerhalb einer Stunde', category: 1 },
      { text: 'oberhalb des Dorfes', category: 2 },
    ],
    explanation: l('innerhalb / außerhalb can refer to time or place.', 'innerhalb / außerhalb zaman ya da yer bildirebilir.', 'Gruppen.'),
    practice: ['praep-aufgrund'],
  },
  {
    id: 'mc-endung',
    type: 'multiple_choice',
    topic: 'genitiv-formen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Infolge ___ Streiks fielen viele Züge aus.',
    options: ['des', 'dem', 'den'],
    answer: 0,
    explanation: l('infolge + genitive: des Streiks (masculine: des + -s).', 'infolge + Genitiv: des Streiks (eril: des + -s).', 'des Streiks.'),
    examples: ['Infolge **des** Streiks fielen viele Züge aus.'],
    practice: ['fill-eines'],
  },
  {
    id: 'tf-umgangssprache',
    type: 'true_false',
    topic: 'stil',
    concept: 'register',
    skill: 'grammar',
    difficulty: 2,
    statement: 'In der Umgangssprache hört man oft „wegen dem Wetter“ – in formellen Texten schreibt man aber „wegen des Wetters“.',
    answer: true,
    explanation: l('Spoken German often uses dative; written/formal German uses genitive.', 'Konuşma dilinde sık sık Dativ kullanılır; yazılı/resmî dilde Genitiv.', 'Register.'),
  },
  {
    id: 'select-genitiv',
    type: 'multiple_select',
    topic: 'genitiv-formen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which phrases are correct (formal)? Select all.', 'Hangi öbekler doğru (resmî)? Hepsini seç.', 'Welche sind korrekt?'),
    options: ['aufgrund des Regens', 'trotz der Kälte', 'innerhalb drei Tagen', 'während des Urlaubs', 'angesichts die Situation'],
    answers: [0, 1, 3],
    explanation: l('innerhalb von drei Tagen / innerhalb dreier Tage; angesichts der Situation.', 'innerhalb von drei Tagen / innerhalb dreier Tage; angesichts der Situation.', 'Genitiv.'),
  },
  {
    id: 'image-sturm',
    type: 'image_choice',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Aufgrund eines Sturms bleiben alle Schulen geschlossen.',
    options: [
      { emoji: '🌪️', label: 'Sturm' },
      { emoji: '☀️', label: 'Sonne' },
      { emoji: '🎉', label: 'Fest' },
      { emoji: '🏖️', label: 'Ferien' },
    ],
    answer: 0,
    explanation: l('aufgrund = because of the storm.', 'aufgrund = fırtına yüzünden.', 'Sturm.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-eines',
    type: 'fill_blank',
    topic: 'genitiv-formen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Aufgrund ___ technischen Problems verspätet sich der Flug.',
    accepted: ['eines'],
    base: 'ein Problem (n.) → Genitiv',
    explanation: l('Neuter genitive: eines technischen Problems.', 'Nötr Genitiv: eines technischen Problems.', 'eines.'),
    examples: ['Aufgrund **eines** technischen Problems …'],
  },
  {
    id: 'fill-der',
    type: 'fill_blank',
    topic: 'genitiv-formen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wir wohnen außerhalb ___ Stadt.',
    accepted: ['der'],
    base: 'die Stadt → Genitiv',
    explanation: l('Feminine genitive: der Stadt.', 'Dişil Genitiv: der Stadt.', 'der.'),
    examples: ['Wir wohnen außerhalb **der** Stadt.'],
  },
  {
    id: 'fill-mithilfe',
    type: 'fill_blank',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: '___ einer Übersetzungs-App konnte sie den Brief verstehen.',
    accepted: ['Mithilfe', 'Mit Hilfe'],
    base: 'with the help of',
    explanation: l('mithilfe + genitive.', 'mithilfe + Genitiv.', 'Mithilfe.'),
    examples: ['**Mithilfe** einer Übersetzungs-App …'],
  },
  {
    id: 'build-infolge',
    type: 'sentence_builder',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ist die Straße', 'Infolge des Hochwassers', 'gesperrt'],
    answers: [['Infolge des Hochwassers', 'ist die Straße', 'gesperrt']],
    translation: l('As a result of the flood the road is closed.', 'Sel sonucunda yol kapalı.', 'Infolge des Hochwassers ist die Straße gesperrt.'),
    explanation: l('Prepositional phrase in position 1 → verb next.', 'Edat öbeği 1. konumda → sonra fiil.', 'Infolge … ist.'),
    examples: ['**Infolge des Hochwassers** ist die Straße gesperrt.'],
  },
  {
    id: 'build-bezueglich',
    type: 'sentence_builder',
    topic: 'stil',
    concept: 'formal-letter',
    skill: 'writing',
    difficulty: 3,
    chips: ['Ihrer Anfrage', 'Bezüglich', 'wir Ihnen mit', 'teilen', 'Folgendes'],
    answers: [['Bezüglich', 'Ihrer Anfrage', 'teilen', 'wir Ihnen mit', 'Folgendes']],
    translation: l('Regarding your inquiry we inform you of the following.', 'Talebinizle ilgili olarak size şunları bildiririz.', 'Bezüglich Ihrer Anfrage teilen wir Ihnen Folgendes mit.'),
    explanation: l('Typical formal letter opening.', 'Tipik resmî mektup girişi.', 'Bezüglich …'),
    examples: ['**Bezüglich** Ihrer Anfrage teilen wir Ihnen Folgendes mit.'],
  },
  {
    id: 'build-statt',
    type: 'sentence_builder',
    topic: 'bedeutung',
    concept: 'alternative',
    skill: 'grammar',
    difficulty: 2,
    chips: ['trinke ich', 'Statt eines Kaffees', 'heute', 'einen Tee'],
    answers: [['Statt eines Kaffees', 'trinke ich', 'heute', 'einen Tee']],
    translation: l('Instead of a coffee I’m drinking a tea today.', 'Bugün kahve yerine çay içiyorum.', 'Statt eines Kaffees trinke ich heute einen Tee.'),
    explanation: l('statt + genitive: eines Kaffees.', 'statt + Genitiv: eines Kaffees.', 'statt.'),
    examples: ['**Statt eines Kaffees** trinke ich heute einen Tee.'],
  },
  {
    id: 'fix-dativ',
    type: 'error_correction',
    topic: 'genitiv-formen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Angesichts der hohe Kosten wurde das Projekt gestoppt.',
    accepted: ['Angesichts der hohen Kosten wurde das Projekt gestoppt.'],
    explanation: l('Genitive plural: der hohen Kosten.', 'Genitiv çoğul: der hohen Kosten.', 'hohen.'),
    examples: ['Angesichts der **hohen** Kosten …'],
  },
  {
    id: 'fix-s',
    type: 'error_correction',
    topic: 'genitiv-formen',
    concept: 'masc-neut-s',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Während des Konzert war es sehr laut.',
    accepted: ['Während des Konzerts war es sehr laut.', 'Während des Konzertes war es sehr laut.'],
    explanation: l('Masculine/neuter genitive noun gets -s / -es: des Konzerts.', 'Eril/nötr Genitiv isme -s / -es eklenir: des Konzerts.', 'Konzerts.'),
    examples: ['Während des **Konzerts** war es sehr laut.'],
  },
  {
    id: 'fix-innerhalb',
    type: 'error_correction',
    topic: 'genitiv-formen',
    concept: 'von-plural',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Ware wird innerhalb zwei Tagen geliefert.',
    accepted: ['Die Ware wird innerhalb von zwei Tagen geliefert.', 'Die Ware wird innerhalb zweier Tage geliefert.'],
    explanation: l('Plural without article → von + dative: innerhalb von zwei Tagen.', 'Artikelsiz çoğul → von + Dativ: innerhalb von zwei Tagen.', 'innerhalb von.'),
    examples: ['… innerhalb **von** zwei Tagen …'],
  },
  {
    id: 'tr-aufgrund',
    type: 'translation',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'writing',
    difficulty: 2,
    source: l('Due to the strike the shops are closed.', 'Grev nedeniyle dükkânlar kapalı.', 'Due to the strike the shops are closed.'),
    accepted: ['Aufgrund des Streiks sind die Geschäfte geschlossen.', 'Wegen des Streiks sind die Geschäfte geschlossen.', 'Aufgrund des Streiks sind die Läden geschlossen.'],
    explanation: l('aufgrund + des Streiks.', 'aufgrund + des Streiks.', 'Aufgrund des Streiks.'),
    examples: ['**Aufgrund des Streiks** sind die Geschäfte geschlossen.'],
  },
  {
    id: 'tr-trotz',
    type: 'translation',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'writing',
    difficulty: 2,
    source: l('Despite the rain we went hiking.', 'Yağmura rağmen yürüyüşe gittik.', 'Despite the rain we went hiking.'),
    accepted: ['Trotz des Regens sind wir wandern gegangen.', 'Trotz des Regens gingen wir wandern.'],
    explanation: l('trotz + des Regens; then verb.', 'trotz + des Regens; sonra fiil.', 'Trotz des Regens.'),
    examples: ['**Trotz des Regens** sind wir wandern gegangen.'],
  },
  {
    id: 'ordering-mail',
    type: 'ordering',
    topic: 'stil',
    concept: 'formal-letter',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the formal email in order.', 'Resmî e-postayı sırala.', 'Ordne die E-Mail.'),
    items: ['Aufgrund einer Erkrankung kann ich leider nicht teilnehmen.', 'Sehr geehrte Frau Krause,', 'Mit freundlichen Grüßen', 'bezüglich des Seminars am Freitag muss ich Ihnen leider absagen.'],
    answer: ['Sehr geehrte Frau Krause,', 'bezüglich des Seminars am Freitag muss ich Ihnen leider absagen.', 'Aufgrund einer Erkrankung kann ich leider nicht teilnehmen.', 'Mit freundlichen Grüßen'],
    explanation: l('Greeting → topic (bezüglich) → reason (aufgrund) → closing.', 'Hitap → konu (bezüglich) → sebep (aufgrund) → kapanış.', 'Aufbau.'),
  },
  {
    id: 'dialog-formell',
    type: 'dialogue',
    topic: 'stil',
    concept: 'register',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kundenservice', de: 'Warum möchten Sie den Vertrag kündigen?' }],
    options: ['Aufgrund eines Umzugs ins Ausland brauche ich den Vertrag nicht mehr.', 'Wegen Ausland.', 'Aufgrund mir.'],
    answer: 0,
    explanation: l('Formal reason with aufgrund + genitive.', 'aufgrund + Genitiv ile resmî sebep.', 'aufgrund.'),
  },
  {
    id: 'dialog-oeffnung',
    type: 'dialogue',
    topic: 'bedeutung',
    concept: 'time',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kundin', de: 'Kann ich das Paket auch am Sonntag abholen?' }],
    options: ['Leider nein, außerhalb der Öffnungszeiten ist die Filiale geschlossen.', 'Ja, während Sonntag.', 'Innerhalb Sonntag.'],
    answer: 0,
    explanation: l('außerhalb der Öffnungszeiten = outside opening hours.', 'außerhalb der Öffnungszeiten = çalışma saatleri dışında.', 'außerhalb.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-was',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was ist das für ein Text?',
    options: ['Eine Information der Stadtwerke an die Bürger.', 'Eine Speisekarte.', 'Ein Kinoprogramm.'],
    answer: 0,
    explanation: l('„Information der Stadtwerke“', '„Information der Stadtwerke“', 'Stadtwerke.'),
  },
  {
    id: 'read-grund',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum gibt es kein Wasser?',
    options: ['Wegen Bauarbeiten an einer Leitung.', 'Wegen eines Streiks.', 'Wegen eines Sturms.'],
    answer: 0,
    explanation: l('„Aufgrund dringender Bauarbeiten an der Hauptleitung …“', '„Aufgrund dringender Bauarbeiten an der Hauptleitung …“', 'Bauarbeiten.'),
  },
  {
    id: 'read-zeit',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 2,
    statement: 'Das Wasser ist nur während des Vormittags abgestellt.',
    answer: true,
    explanation: l('„… am Dienstag zwischen 8 und 12 Uhr …“', '„… am Dienstag zwischen 8 und 12 Uhr …“', 'richtig.'),
  },
  {
    id: 'read-tipp',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wo kann man trotzdem Wasser bekommen?',
    options: ['An einem Wagen vor dem Rathaus.', 'Im Schwimmbad.', 'Nirgends.'],
    answer: 0,
    explanation: l('„Während der Arbeiten steht vor dem Rathaus ein Trinkwasserwagen.“', '„Während der Arbeiten steht vor dem Rathaus ein Trinkwasserwagen.“', 'Rathaus.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-flug',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'listening',
    difficulty: 2,
    audio: 'Aufgrund dichten Nebels verzögern sich alle Abflüge um mindestens eine Stunde.',
    question: l('Why are the flights delayed?', 'Uçuşlar neden gecikiyor?', 'Warum Verspätung?'),
    options: ['thick fog', 'a strike', 'a technical problem'],
    answer: 0,
    explanation: l('„Aufgrund dichten Nebels“', '„Aufgrund dichten Nebels“', 'Nebel.'),
  },
  {
    id: 'listen-innerhalb',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'time',
    skill: 'listening',
    difficulty: 2,
    audio: 'Sie können die Ware innerhalb von vierzehn Tagen ohne Angabe von Gründen zurückschicken.',
    question: l('How long can you return the goods?', 'Ürünü ne kadar süre içinde iade edebilirsin?', 'Wie lange Rückgabe?'),
    options: ['14 days', '4 days', '40 days'],
    answer: 0,
    explanation: l('„innerhalb von vierzehn Tagen“', '„innerhalb von vierzehn Tagen“', '14 Tage.'),
  },
  {
    id: 'listen-zugunsten',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Flohmarkt findet zugunsten des Kinderkrankenhauses statt.',
    question: l('Who gets the money?', 'Para kime gidiyor?', 'Wer bekommt das Geld?'),
    options: ['the children’s hospital', 'the sellers', 'the city'],
    answer: 0,
    explanation: l('zugunsten = for the benefit of.', 'zugunsten = … yararına.', 'Kinderkrankenhaus.'),
  },
  {
    id: 'listen-trotz',
    type: 'listening_choice',
    topic: 'stil',
    concept: 'register',
    skill: 'listening',
    difficulty: 3,
    audio: 'Trotz intensiver Suche konnte der vermisste Hund bisher nicht gefunden werden.',
    question: l('What is the status?', 'Durum ne?', 'Wie ist der Stand?'),
    options: ['The dog is still missing.', 'The dog was found.', 'Nobody is looking.'],
    answer: 0,
    explanation: l('„… konnte … bisher nicht gefunden werden.“', '„… konnte … bisher nicht gefunden werden.“', 'noch vermisst.'),
  },

  ...praepDrills(),
]

export const UNIT_B2_08_PRAEPOSITIONEN_GENITIV: CourseUnit = {
  level: 'B2',
  number: 8,
  slug: 'praepositionen-genitiv',
  titleDe: 'Aufgrund, infolge, angesichts',
  title: l('Due to, as a result of, in view of', '… nedeniyle, … sonucunda', 'Aufgrund, infolge, angesichts'),
  goal: l(
    'By the end of this unit you can use formal prepositions with the genitive (aufgrund, infolge, angesichts, innerhalb, bezüglich …), form the genitive correctly and recognise the difference between spoken and written style.',
    'Bu ünitenin sonunda Genitiv alan resmî edatları (aufgrund, infolge, angesichts, innerhalb, bezüglich …) kullanabilir, Genitiv’i doğru kurabilir ve konuşma ile yazı dili arasındaki farkı tanıyabilirsin.',
    'Am Ende dieser Einheit benutzt du Präpositionen mit Genitiv.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'bedeutung', label: l('Meaning of the prepositions', 'Edatların anlamı', 'Bedeutung') },
    { key: 'genitiv-formen', label: l('Genitive forms', 'Genitiv biçimleri', 'Genitivformen') },
    { key: 'stil', label: l('Formal style', 'Resmî üslup', 'Stil') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Prepositions for formal German.', 'Resmî Almanca için edatlar.', 'Präpositionen für formelle Texte.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Groups of genitive prepositions', 'Genitiv edatlarının grupları', 'Gruppen'),
          body: l(
            'Cause: aufgrund, infolge, angesichts, wegen. Contrast/alternative: trotz, (an)statt. Time: während, innerhalb, außerhalb. Topic: bezüglich, hinsichtlich. Means/benefit: mithilfe, zugunsten.',
            'Sebep: aufgrund, infolge, angesichts, wegen. Karşıtlık/alternatif: trotz, (an)statt. Zaman: während, innerhalb, außerhalb. Konu: bezüglich, hinsichtlich. Araç/yarar: mithilfe, zugunsten.',
            'Grund, Gegensatz, Zeit, Thema.'
          ),
          table: {
            head: [l('Group', 'Grup', 'Gruppe'), l('Prepositions', 'Edatlar', 'Präpositionen')],
            rows: [
              ['Grund', 'aufgrund, infolge, angesichts'],
              ['Gegensatz', 'trotz, statt'],
              ['Zeit / Ort', 'während, innerhalb, außerhalb'],
              ['Thema', 'bezüglich, hinsichtlich'],
            ],
          },
        },
        {
          title: l('Genitive forms', 'Genitiv biçimleri', 'Genitivformen'),
          body: l(
            'Masculine/neuter: des / eines + noun with -s or -es (des Streiks, eines Problems). Feminine and plural: der (der Stadt, der Kosten). Adjectives get -en: aufgrund des starken Regens.',
            'Eril/nötr: des / eines + -s ya da -es alan isim (des Streiks, eines Problems). Dişil ve çoğul: der (der Stadt, der Kosten). Sıfatlar -en alır: aufgrund des starken Regens.',
            'des …-s / der.'
          ),
          examples: [
            { de: 'aufgrund **des** schlecht**en** Wetter**s**', translation: l('due to the bad weather', 'kötü hava nedeniyle', '') },
            { de: 'innerhalb **einer** Woche', translation: l('within a week', 'bir hafta içinde', '') },
          ],
        },
        {
          title: l('Spoken vs written', 'Konuşma ve yazı', 'Gesprochen vs. geschrieben'),
          body: l(
            'In speech many people say „wegen dem“ or „trotz dem“. In letters, emails to authorities and exams use the genitive. Plural without article: von + dative (innerhalb von zwei Tagen).',
            'Konuşmada birçok kişi „wegen dem“ ya da „trotz dem“ der. Mektuplarda, resmî dairelere e-postalarda ve sınavlarda Genitiv kullan. Artikelsiz çoğul: von + Dativ (innerhalb von zwei Tagen).',
            'Schriftlich: Genitiv.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('An announcement at the train station and a conversation between two travellers.', 'Tren istasyonunda bir anons ve iki yolcu arasında bir konuşma.', 'Am Bahnhof.'),
      dialogue: [
        { speaker: 'Durchsage', de: '**Aufgrund** einer Signalstörung entfällt der RE 4. **Infolge** der Störung kommt es auch auf anderen Linien zu Verspätungen.', translation: l('Due to a signal failure the RE 4 is cancelled. As a result, other lines are also delayed.', 'Sinyal arızası nedeniyle RE 4 iptal edildi. Arızanın sonucunda diğer hatlarda da gecikmeler var.', '') },
        { speaker: 'Mehmet', de: 'Typisch! **Trotz** des neuen Fahrplans gibt es jeden Tag Probleme.', translation: l('Typical! Despite the new timetable there are problems every day.', 'Tipik! Yeni tarifeye rağmen her gün sorun var.', '') },
        { speaker: 'Julia', de: '**Statt** eines Zuges könnten wir den Bus nehmen.', translation: l('Instead of a train we could take the bus.', 'Tren yerine otobüse binebiliriz.', '') },
        { speaker: 'Mehmet', de: 'Gute Idee. Der fährt **innerhalb** der nächsten zehn Minuten.', translation: l('Good idea. It leaves within the next ten minutes.', 'İyi fikir. Önümüzdeki on dakika içinde kalkıyor.', '') },
        { speaker: 'Julia', de: '**Angesichts** der Lage schreibe ich meinem Chef, dass ich später komme.', translation: l('In view of the situation I’ll write to my boss that I’ll be late.', 'Bu durum karşısında patronuma geç kalacağımı yazıyorum.', '') },
        { speaker: 'Mehmet', de: 'Ich auch. **Während** der Fahrt habe ich ja Zeit.', translation: l('Me too. I’ll have time during the journey.', 'Ben de. Yolculuk sırasında zamanım var zaten.', '') },
      ],
      examples: [
        { de: '**Aufgrund des** Wetters fällt der Flug aus.', translation: l('Due to the weather the flight is cancelled.', 'Hava nedeniyle uçuş iptal.', '') },
        { de: '**Infolge des** Unfalls gab es Stau.', translation: l('As a result of the accident there was a traffic jam.', 'Kaza sonucunda trafik sıkışıklığı oldu.', '') },
        { de: '**Trotz der** Kälte gingen wir raus.', translation: l('Despite the cold we went out.', 'Soğuğa rağmen dışarı çıktık.', '') },
        { de: '**Innerhalb einer** Woche bekommen Sie Antwort.', translation: l('You will get an answer within a week.', 'Bir hafta içinde cevap alırsınız.', '') },
        { de: '**Bezüglich Ihrer** Anfrage …', translation: l('Regarding your inquiry …', 'Talebinizle ilgili olarak …', '') },
        { de: 'Wir wohnen **außerhalb der** Stadt.', translation: l('We live outside the city.', 'Şehir dışında oturuyoruz.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Meanings and forms.', 'Anlamlar ve biçimler.', 'Bedeutung und Form.'),
      exercises: ['match-bedeutung', 'sort-funktion', 'praep-aufgrund', 'praep-trotz', 'praep-innerhalb', 'mc-endung', 'tf-umgangssprache', 'select-genitiv', 'image-sturm'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Write formally with the genitive.', 'Genitiv ile resmî yaz.', 'Formell schreiben.'),
      exercises: [
        'fill-eines',
        'fill-der',
        'fill-mithilfe',
        'build-infolge',
        'build-bezueglich',
        'build-statt',
        'fix-dativ',
        'fix-s',
        'fix-innerhalb',
        'tr-aufgrund',
        'tr-trotz',
        'ordering-mail',
        'dialog-formell',
        'dialog-oeffnung',
        'praep-statt',
        'praep-waehrend',
        'praep-angesichts',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A notice from the local utility company.', 'Belediye hizmet şirketinden bir duyuru.', 'Eine Mitteilung der Stadtwerke.'),
      passage: [
        '**Information der Stadtwerke** – Liebe Bürgerinnen und Bürger,',
        '**aufgrund** dringender Bauarbeiten an der Hauptleitung wird am Dienstag zwischen 8 und 12 Uhr das Wasser in der Altstadt abgestellt.',
        '**Während** der Arbeiten steht vor dem Rathaus ein Trinkwasserwagen. **Außerhalb** dieser Zeit ist die Versorgung normal.',
        '**Bezüglich** möglicher Schäden wenden Sie sich bitte **innerhalb** einer Woche an unseren Kundenservice. Wir bitten **angesichts** der Umstände um Ihr Verständnis.',
      ],
      glossary: [
        { de: 'dringend', note: l('urgent', 'acil', 'sehr wichtig, sofort') },
        { de: 'die Hauptleitung', note: l('main pipe', 'ana boru hattı', 'große Wasserleitung') },
        { de: 'abstellen', note: l('to turn off', 'kesmek', 'ausmachen') },
        { de: 'die Versorgung', note: l('supply', 'tedarik', 'Lieferung von Wasser, Strom') },
      ],
      exercises: ['read-was', 'read-grund', 'read-zeit', 'read-tipp'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Formal announcements.', 'Resmî anonslar.', 'Durchsagen.'),
      exercises: ['listen-flug', 'listen-innerhalb', 'listen-zugunsten', 'listen-trotz'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('You are a spokesperson: announce a change (event cancelled, office closed …) formally.', 'Sözcüsün: bir değişikliği (etkinlik iptali, ofis kapanışı …) resmî bir dille duyur.', 'Formelle Ankündigung.'),
      points: [
        l('The reason: aufgrund / infolge', 'Sebep: aufgrund / infolge', 'Grund'),
        l('An alternative: statt', 'Bir alternatif: statt', 'Alternative'),
        l('A time frame: innerhalb / während', 'Bir zaman aralığı: innerhalb / während', 'Zeit'),
        l('A polite closing', 'Kibar bir kapanış', 'Schluss'),
      ],
      model: [
        'Aufgrund eines Wasserschadens bleibt die Bibliothek diese Woche geschlossen.',
        'Statt der geplanten Lesung bieten wir am Freitag einen Online-Termin an.',
        'Ausgeliehene Bücher können innerhalb der nächsten zwei Wochen ohne Gebühr zurückgegeben werden.',
        'Wir bitten angesichts der Umstände um Ihr Verständnis.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a formal email (at least 5 sentences) to cancel or postpone an appointment. Use at least three genitive prepositions.',
        'Bir randevuyu iptal etmek ya da ertelemek için resmî bir e-posta yaz (en az 5 cümle). En az üç Genitiv edatı kullan.',
        'Schreib eine formelle Absage (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('A cause (aufgrund / infolge / wegen / angesichts)', 'Bir sebep (aufgrund / infolge / wegen / angesichts)', 'Grund'), pattern: '\\b([Aa]ufgrund|[Ii]nfolge|[Ww]egen|[Aa]ngesichts)\\b' },
        { label: l('Another genitive preposition (bezüglich, innerhalb, während, statt, trotz …)', 'Başka bir Genitiv edatı (bezüglich, innerhalb, während, statt, trotz …)', 'Präposition'), pattern: '\\b([Bb]ezüglich|[Ii]nnerhalb|[Ww]ährend|[Ss]tatt|[Aa]nstatt|[Tt]rotz|[Aa]ußerhalb)\\b' },
        { label: l('A genitive article (des / eines / der …)', 'Bir Genitiv artikeli (des / eines / der …)', 'Genitiv'), pattern: '\\b(des|eines|meines|Ihres|der|einer|meiner|Ihrer)\\b' },
      ],
      model: [
        'Sehr geehrter Herr Wagner, bezüglich unseres Termins am Donnerstag muss ich mich leider melden.',
        'Aufgrund einer kurzfristigen Dienstreise kann ich nicht kommen.',
        'Statt des Treffens könnten wir auch telefonieren.',
        'Gern schlage ich einen neuen Termin innerhalb der nächsten Woche vor.',
        'Ich bitte um Ihr Verständnis. Mit freundlichen Grüßen, Selin Öztürk',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Pick the preposition – 60 seconds.', 'Edatı seç – 60 saniye.', 'Präposition wählen – 60 Sekunden.'),
      seconds: 60,
      pool: [...PRAEP.map(([id]) => `praep-${id}`), 'mc-endung'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Cause: aufgrund, infolge, angesichts', 'Sebep: aufgrund, infolge, angesichts', 'Grund'),
      l('Contrast / time: trotz, statt, während, innerhalb, außerhalb', 'Karşıtlık / zaman: trotz, statt, während, innerhalb, außerhalb', 'Gegensatz / Zeit'),
      l('Formal topic words: bezüglich, mithilfe, zugunsten', 'Resmî konu kelimeleri: bezüglich, mithilfe, zugunsten', 'formell'),
      l('Genitive: des …-s, eines …-s, der; adjectives -en', 'Genitiv: des …-s, eines …-s, der; sıfatlar -en', 'Genitiv'),
    ],
    mistakes: [
      { wrong: 'angesichts der hohe Kosten', right: 'angesichts der hohen Kosten', note: l('Adjective -en.', 'Sıfat -en.', '-en.') },
      { wrong: 'während des Konzert', right: 'während des Konzerts', note: l('Noun -s.', 'İsim -s.', '-s.') },
      { wrong: 'innerhalb zwei Tagen', right: 'innerhalb von zwei Tagen', note: l('von + dative.', 'von + Dativ.', 'von.') },
      { wrong: 'aufgrund dem Wetter (formell)', right: 'aufgrund des Wetters', note: l('Formal → genitive.', 'Resmî → Genitiv.', 'Genitiv.') },
    ],
  },
}
