import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'der seit Jahren leerstehende Bahnhof', emoji: '🏚️', translation: l('the station that has stood empty for years', 'yıllardır boş duran istasyon', 'der Bahnhof, der seit Jahren leer steht'), example: 'Der seit Jahren leerstehende Bahnhof wird ein Museum.' },
  { word: 'die gestern veröffentlichte Studie', emoji: '📑', translation: l('the study published yesterday', 'dün yayımlanan araştırma', 'die Studie, die gestern veröffentlicht wurde'), example: 'Die gestern veröffentlichte Studie sorgt für Diskussionen.' },
  { word: 'veröffentlichen', emoji: '📢', translation: l('to publish', 'yayımlamak', 'öffentlich machen'), example: 'Die Ergebnisse wurden im Mai veröffentlicht.' },
  { word: 'die Maßnahme', emoji: '🛠️', translation: l('measure', 'önlem', 'etwas, was man tut'), example: 'Die geplanten Maßnahmen kosten viel Geld.' },
  { word: 'umstritten', emoji: '⚔️', translation: l('controversial', 'tartışmalı', 'viele sind dagegen'), example: 'Das ist ein umstrittenes Projekt.' },
  { word: 'betroffen', emoji: '🎯', translation: l('affected', 'etkilenen', 'hat damit zu tun'), example: 'Die betroffenen Anwohner protestieren.' },
  { word: 'der Anwohner / die Anwohnerin', emoji: '🏘️', translation: l('resident', 'mahalle sakini', 'wohnt in der Nähe'), example: 'Die Anwohner beschweren sich über Lärm.' },
  { word: 'geplant', emoji: '🗓️', translation: l('planned', 'planlanmış', 'man hat es vor'), example: 'Der geplante Neubau beginnt im Herbst.' },
  { word: 'zunehmend', emoji: '📈', translation: l('increasing(ly)', 'giderek artan', 'immer mehr'), example: 'Der zunehmende Verkehr belastet die Stadt.' },
  { word: 'der Zeitungsstil', emoji: '🗞️', translation: l('newspaper style', 'gazete üslubu', 'Sprache in Zeitungen'), example: 'Im Zeitungsstil sind Sätze oft sehr kompakt.' },
  { word: 'die Untersuchung', emoji: '🔬', translation: l('investigation, study', 'inceleme', 'Studie'), example: 'Die Untersuchung dauert noch an.' },
  { word: 'renovieren', emoji: '🧱', translation: l('to renovate', 'yenilemek', 'neu machen'), example: 'Das frisch renovierte Gebäude ist wunderschön.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Maßnahme', gender: 'f', plural: 'die Maßnahmen', translation: l('measure', 'önlem', 'Maßnahme') },
  { word: 'Anwohner', gender: 'm', plural: 'die Anwohner', translation: l('resident', 'sakin', 'Anwohner') },
  { word: 'Studie', gender: 'f', plural: 'die Studien', translation: l('study', 'araştırma', 'Studie') },
  { word: 'Gebäude', gender: 'n', plural: 'die Gebäude', translation: l('building', 'bina', 'Gebäude') },
  { word: 'Gemeinde', gender: 'f', plural: 'die Gemeinden', translation: l('municipality', 'belediye', 'Gemeinde') },
  { word: 'Projekt', gender: 'n', plural: 'die Projekte', translation: l('project', 'proje', 'Projekt') },
  { word: 'Bericht', gender: 'm', plural: 'die Berichte', translation: l('report', 'rapor', 'Bericht') },
  { word: 'Entscheidung', gender: 'f', plural: 'die Entscheidungen', translation: l('decision', 'karar', 'Entscheidung') },
]

/** [id, relative clause, right attribute, wrong] */
const ATTR: [string, string, string, [string, string]][] = [
  ['bruecke', 'die Brücke, die 1890 gebaut wurde', 'die 1890 gebaute Brücke', ['die gebaute 1890 Brücke', 'die 1890 bauende Brücke']],
  ['kinder', 'die Kinder, die im Garten spielen', 'die im Garten spielenden Kinder', ['die spielenden im Garten Kinder', 'die im Garten gespielten Kinder']],
  ['gesetz', 'das Gesetz, das letzte Woche beschlossen wurde', 'das letzte Woche beschlossene Gesetz', ['das letzte Woche beschließende Gesetz', 'das beschlossene letzte Woche Gesetz']],
  ['preise', 'die Preise, die stark steigen', 'die stark steigenden Preise', ['die stark gestiegenen steigenden Preise', 'die steigenden stark Preise']],
  ['brief', 'der Brief, der an Sie adressiert ist', 'der an Sie adressierte Brief', ['der adressierte an Sie Brief', 'der an Sie adressierende Brief']],
  ['zug', 'der Zug, der aus Wien kommt', 'der aus Wien kommende Zug', ['der aus Wien gekommte Zug', 'der kommende aus Wien Zug']],
]

function attrDrills(): Exercise[] {
  return ATTR.map(([id, clause, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `attr-${id}`,
      type: 'multiple_choice' as const,
      topic: 'umformen',
      concept: 'clause-to-attribute',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: `„${clause}“ – als Partizipialattribut:`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Article + extra information + participle with ending + noun: ${right}.`,
        `Artikel + ek bilgi + ekli ortaç + isim: ${right}.`,
        `Artikel + Erweiterung + Partizip + Nomen.`
      ),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-attribut',
    type: 'matching',
    topic: 'erkennen',
    concept: 'match-meaning',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Match the attribute and the relative clause.', 'Sıfat öbeğini ilgi cümlesiyle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'die oft gestellte Frage', right: 'die Frage, die oft gestellt wird' },
      { left: 'der laut bellende Hund', right: 'der Hund, der laut bellt' },
      { left: 'das neu eröffnete Café', right: 'das Café, das neu eröffnet wurde' },
      { left: 'die vor Kurzem angekommenen Gäste', right: 'die Gäste, die vor Kurzem angekommen sind' },
    ],
    explanation: l('Read from the article to the noun – everything between belongs to the noun.', 'Artikelden isme kadar oku – aradaki her şey isme aittir.', 'Klammer: Artikel … Nomen.'),
  },
  {
    id: 'sort-gleichzeitig',
    type: 'categorize',
    topic: 'erkennen',
    concept: 'p1-p2-meaning',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('What does the attribute mean?', 'Sıfat öbeği ne anlama geliyor?', 'Was bedeutet das Attribut?'),
    categories: ['… , der/die/das … (aktiv)', '… , der/die/das … wurde (passiv)'],
    items: [
      { text: 'die im Park joggende Frau', category: 0 },
      { text: 'das von allen gelobte Buch', category: 1 },
      { text: 'der ständig klingelnde Wecker', category: 0 },
      { text: 'die schnell reparierte Heizung', category: 1 },
      { text: 'die auf den Bus wartenden Leute', category: 0 },
      { text: 'der gestern gewählte Präsident', category: 1 },
    ],
    explanation: l('-end → active (der/die … tut). ge-…-t/-en → passive (wurde …).', '-end → etken (der/die … tut). ge-…-t/-en → edilgen (wurde …).', 'aktiv / passiv.'),
    practice: ['attr-bruecke'],
  },
  {
    id: 'mc-nomen',
    type: 'multiple_choice',
    topic: 'erkennen',
    concept: 'find-noun',
    skill: 'reading',
    difficulty: 2,
    prompt: '„Die von der Regierung geplanten Maßnahmen …“ – Was ist das Nomen?',
    options: ['Maßnahmen', 'Regierung', 'geplanten'],
    answer: 0,
    explanation: l('The article „Die“ belongs to „Maßnahmen“; „von der Regierung geplanten“ describes it.', '„Die“ artikeli „Maßnahmen“e aittir; „von der Regierung geplanten“ onu tanımlar.', 'Die … Maßnahmen.'),
    practice: ['fill-geplanten'],
  },
  {
    id: 'tf-zeitung',
    type: 'true_false',
    topic: 'zeitungsstil',
    concept: 'style',
    skill: 'reading',
    difficulty: 2,
    statement: 'Partizipialattribute findet man vor allem in der gesprochenen Alltagssprache.',
    answer: false,
    explanation: l('They are typical of written, formal texts (newspapers, science). In speech we use relative clauses.', 'Yazılı ve resmî metinlere (gazete, bilim) özgüdür. Konuşmada ilgi cümlesi kullanılır.', 'Schriftsprache.'),
  },
  {
    id: 'select-korrekt',
    type: 'multiple_select',
    topic: 'umformen',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which phrases are correctly built? Select all.', 'Hangi öbekler doğru kurulmuş? Hepsini seç.', 'Welche sind korrekt?'),
    options: ['der seit Wochen erwartete Brief', 'die im Regal stehenden Bücher', 'die stehenden im Regal Bücher', 'das vom Wind beschädigte Dach', 'der erwartete seit Wochen Brief'],
    answers: [0, 1, 3],
    explanation: l('The participle stands directly before the noun; extra information comes before the participle.', 'Ortaç doğrudan ismin önünde durur; ek bilgi ortaçtan önce gelir.', 'Partizip direkt vor dem Nomen.'),
  },
  {
    id: 'image-baustelle',
    type: 'image_choice',
    topic: 'zeitungsstil',
    concept: 'context',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die seit Monaten gesperrte Brücke wird endlich repariert.',
    options: [
      { emoji: '🚧', label: 'gesperrte Brücke' },
      { emoji: '🎡', label: 'Riesenrad' },
      { emoji: '⛵', label: 'Segelboot' },
      { emoji: '🎂', label: 'Torte' },
    ],
    answer: 0,
    explanation: l('gesperrt = closed (for traffic).', 'gesperrt = kapatılmış (trafiğe).', 'gesperrt.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-geplanten',
    type: 'fill_blank',
    topic: 'umformen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Bürger protestieren gegen die von der Stadt ___ Autobahn. (planen)',
    accepted: ['geplante'],
    base: 'planen → Partizip II',
    explanation: l('gegen die (accusative, fem.) … geplante Autobahn.', 'gegen die (Akk, dişil) … geplante Autobahn.', 'geplante.'),
    examples: ['… gegen die von der Stadt **geplante** Autobahn.'],
  },
  {
    id: 'fill-wachsenden',
    type: 'fill_blank',
    topic: 'umformen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die immer schneller ___ Stadt braucht mehr Schulen. (wachsen)',
    accepted: ['wachsende'],
    base: 'wachsen → Partizip I',
    explanation: l('Die (nominative, fem.) … wachsende Stadt.', 'Die (Nominativ, dişil) … wachsende Stadt.', 'wachsende.'),
    examples: ['Die immer schneller **wachsende** Stadt braucht mehr Schulen.'],
  },
  {
    id: 'fill-betroffenen',
    type: 'fill_blank',
    topic: 'zeitungsstil',
    concept: 'vocab',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die vom Hochwasser ___ Familien bekommen Hilfe. (betreffen)',
    accepted: ['betroffenen'],
    base: 'betreffen → betroffen',
    explanation: l('Die (plural) … betroffenen Familien.', 'Die (çoğul) … betroffenen Familien.', 'betroffenen.'),
    examples: ['Die vom Hochwasser **betroffenen** Familien bekommen Hilfe.'],
  },
  {
    id: 'build-studie',
    type: 'sentence_builder',
    topic: 'umformen',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 3,
    chips: ['veröffentlichte', 'Die gestern', 'überrascht viele', 'Studie'],
    answers: [['Die gestern', 'veröffentlichte', 'Studie', 'überrascht viele']],
    translation: l('The study published yesterday surprises many.', 'Dün yayımlanan araştırma birçok kişiyi şaşırtıyor.', 'Die gestern veröffentlichte Studie überrascht viele.'),
    explanation: l('Article + time + participle + noun.', 'Artikel + zaman + ortaç + isim.', 'Die gestern veröffentlichte Studie.'),
    examples: ['**Die gestern veröffentlichte Studie** überrascht viele.'],
  },
  {
    id: 'build-anwohner',
    type: 'sentence_builder',
    topic: 'umformen',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 3,
    chips: ['wohnenden', 'Die direkt an der Straße', 'leiden unter dem Lärm', 'Anwohner'],
    answers: [['Die direkt an der Straße', 'wohnenden', 'Anwohner', 'leiden unter dem Lärm']],
    translation: l('The residents living right on the road suffer from the noise.', 'Doğrudan yol kenarında oturan sakinler gürültüden muzdarip.', 'Die direkt an der Straße wohnenden Anwohner leiden unter dem Lärm.'),
    explanation: l('Partizip I: the residents live there (active).', 'Partizip I: sakinler orada yaşıyor (etken).', 'wohnenden.'),
    examples: ['Die direkt an der Straße **wohnenden** Anwohner …'],
  },
  {
    id: 'build-gebaeude',
    type: 'sentence_builder',
    topic: 'zeitungsstil',
    concept: 'style',
    skill: 'grammar',
    difficulty: 3,
    chips: ['wird', 'Das 1905 errichtete Gebäude', 'renoviert', 'im Sommer'],
    answers: [['Das 1905 errichtete Gebäude', 'wird', 'im Sommer', 'renoviert']],
    translation: l('The building erected in 1905 will be renovated in summer.', '1905’te inşa edilen bina yazın yenilenecek.', 'Das 1905 errichtete Gebäude wird im Sommer renoviert.'),
    explanation: l('Attribute + passive – typical newspaper style.', 'Sıfat öbeği + edilgen – tipik gazete üslubu.', 'Zeitungsstil.'),
    examples: ['Das 1905 **errichtete** Gebäude wird im Sommer renoviert.'],
  },
  {
    id: 'fix-reihenfolge',
    type: 'error_correction',
    topic: 'umformen',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der reparierte gestern Aufzug funktioniert wieder.',
    accepted: ['Der gestern reparierte Aufzug funktioniert wieder.'],
    explanation: l('The participle stands right before the noun: der gestern reparierte Aufzug.', 'Ortaç ismin hemen önünde: der gestern reparierte Aufzug.', 'gestern reparierte.'),
    examples: ['Der **gestern reparierte** Aufzug funktioniert wieder.'],
  },
  {
    id: 'fix-endung',
    type: 'error_correction',
    topic: 'umformen',
    concept: 'endings',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wir sprachen mit den seit Stunden wartend Fahrgästen.',
    accepted: ['Wir sprachen mit den seit Stunden wartenden Fahrgästen.'],
    explanation: l('mit den (dative plural) → wartenden.', 'mit den (Dativ çoğul) → wartenden.', 'wartenden.'),
    examples: ['… mit den seit Stunden **wartenden** Fahrgästen.'],
  },
  {
    id: 'fix-aktiv',
    type: 'error_correction',
    topic: 'erkennen',
    concept: 'p1-p2-meaning',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das von vielen lesende Buch ist ein Bestseller.',
    accepted: ['Das von vielen gelesene Buch ist ein Bestseller.'],
    explanation: l('The book is read by many (passive) → gelesene.', 'Kitap birçok kişi tarafından okunuyor (edilgen) → gelesene.', 'gelesene.'),
    examples: ['Das von vielen **gelesene** Buch …'],
  },
  {
    id: 'tr-attribut',
    type: 'translation',
    topic: 'umformen',
    concept: 'clause-to-attribute',
    skill: 'writing',
    difficulty: 3,
    source: l('the house built by my grandfather', 'dedemin yaptığı ev', 'the house built by my grandfather'),
    accepted: ['das von meinem Großvater gebaute Haus', 'das von meinem Opa gebaute Haus'],
    explanation: l('das + von … + gebaute + Haus.', 'das + von … + gebaute + Haus.', 'das von meinem Großvater gebaute Haus.'),
    examples: ['das von meinem Großvater **gebaute** Haus'],
  },
  {
    id: 'tr-relativ',
    type: 'translation',
    topic: 'umformen',
    concept: 'attribute-to-clause',
    skill: 'writing',
    difficulty: 3,
    source: l('Rewrite as a relative clause: „die im Hafen liegenden Schiffe“', 'İlgi cümlesine çevir: „die im Hafen liegenden Schiffe“', 'Als Relativsatz: „die im Hafen liegenden Schiffe“'),
    accepted: ['die Schiffe, die im Hafen liegen'],
    explanation: l('Partizip I → present tense active: die Schiffe, die im Hafen liegen.', 'Partizip I → şimdiki zaman etken: die Schiffe, die im Hafen liegen.', 'die … liegen.'),
    examples: ['die Schiffe, **die im Hafen liegen**'],
  },
  {
    id: 'ordering-aufloesen',
    type: 'ordering',
    topic: 'erkennen',
    concept: 'reading-strategy',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Strategy: how do you decode a long attribute? Put the steps in order.', 'Strateji: uzun bir sıfat öbeğini nasıl çözersin? Adımları sırala.', 'Lesestrategie: Reihenfolge.'),
    items: ['Das Partizip direkt vor dem Nomen finden.', 'Den Artikel suchen.', 'Einen Relativsatz bilden.', 'Das passende Nomen dazu finden.'],
    answer: ['Den Artikel suchen.', 'Das passende Nomen dazu finden.', 'Das Partizip direkt vor dem Nomen finden.', 'Einen Relativsatz bilden.'],
    explanation: l('Article → noun → participle → rebuild as relative clause.', 'Artikel → isim → ortaç → ilgi cümlesi olarak yeniden kur.', 'Artikel → Nomen → Partizip → Relativsatz.'),
  },
  {
    id: 'dialog-umformen',
    type: 'dialogue',
    topic: 'umformen',
    concept: 'attribute-to-clause',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Kollegin', de: 'Was heißt „die von der Firma angebotenen Kurse“? Ich verstehe den Satz nicht.' }],
    options: ['Das sind die Kurse, die von der Firma angeboten werden.', 'Die Firma ist ein Kurs.', 'Das sind Kurse, die die Firma anbieten.'],
    answer: 0,
    explanation: l('Partizip II → passive relative clause: die angeboten werden.', 'Partizip II → edilgen ilgi cümlesi: die angeboten werden.', 'Relativsatz.'),
  },
  {
    id: 'dialog-einfach',
    type: 'dialogue',
    topic: 'zeitungsstil',
    concept: 'style',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Warum klingen Zeitungsartikel immer so kompliziert?' }],
    options: ['Weil sie viele Informationen in Partizipialattribute packen – das spart Platz.', 'Weil Zeitungen kompliziert sind.', 'Weil sie auf Englisch sind.'],
    answer: 0,
    explanation: l('Attributes make texts compact.', 'Sıfat öbekleri metinleri kısa ve yoğun yapar.', 'kompakt.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es im Artikel?',
    options: ['Ein alter Bahnhof wird zu einem Kulturzentrum.', 'Ein neuer Bahnhof wird gebaut.', 'Die Bahn wird teurer.'],
    answer: 0,
    explanation: l('„… wird zu einem Kulturzentrum umgebaut.“', '„… wird zu einem Kulturzentrum umgebaut.“', 'Kulturzentrum.'),
  },
  {
    id: 'read-leer',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Seit wann steht der Bahnhof leer?',
    options: ['Seit über zwanzig Jahren.', 'Seit letztem Monat.', 'Er war nie leer.'],
    answer: 0,
    explanation: l('„Der seit über zwanzig Jahren leerstehende Bahnhof …“', '„Der seit über zwanzig Jahren leerstehende Bahnhof …“', 'zwanzig Jahre.'),
  },
  {
    id: 'read-kritik',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    statement: 'Alle Anwohner sind mit dem Projekt zufrieden.',
    answer: false,
    explanation: l('„Die direkt neben dem Bahnhof wohnenden Anwohner befürchten mehr Lärm.“', '„Die direkt neben dem Bahnhof wohnenden Anwohner befürchten mehr Lärm.“', 'falsch.'),
  },
  {
    id: 'read-eroeffnung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wann soll das Zentrum eröffnen?',
    options: ['Im Frühjahr 2028.', 'Nächste Woche.', 'Das ist noch unklar.'],
    answer: 0,
    explanation: l('„Die für das Frühjahr 2028 geplante Eröffnung …“', '„Die für das Frühjahr 2028 geplante Eröffnung …“', '2028.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-studie',
    type: 'listening_choice',
    topic: 'zeitungsstil',
    concept: 'style',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die am Montag vorgestellte Studie zeigt, dass Jugendliche weniger Fleisch essen.',
    question: l('What does the study show?', 'Araştırma neyi gösteriyor?', 'Was zeigt die Studie?'),
    options: ['Young people eat less meat.', 'Young people eat more meat.', 'Young people skip breakfast.'],
    answer: 0,
    explanation: l('„… dass Jugendliche weniger Fleisch essen.“', '„… dass Jugendliche weniger Fleisch essen.“', 'weniger Fleisch.'),
  },
  {
    id: 'listen-bruecke',
    type: 'listening_choice',
    topic: 'erkennen',
    concept: 'find-noun',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die seit dem Unwetter gesperrte Brücke wird voraussichtlich ab Freitag wieder geöffnet.',
    question: l('What happens on Friday?', 'Cuma günü ne oluyor?', 'Was passiert am Freitag?'),
    options: ['The bridge reopens.', 'The bridge is closed.', 'A storm is coming.'],
    answer: 0,
    explanation: l('„… wird … ab Freitag wieder geöffnet.“', '„… wird … ab Freitag wieder geöffnet.“', 'geöffnet.'),
  },
  {
    id: 'listen-gaeste',
    type: 'listening_choice',
    topic: 'umformen',
    concept: 'p1-p2-meaning',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die aus ganz Europa angereisten Gäste wurden mit Musik empfangen.',
    question: l('Where did the guests come from?', 'Misafirler nereden geldi?', 'Woher kamen die Gäste?'),
    options: ['from all over Europe', 'from the city', 'from America'],
    answer: 0,
    explanation: l('„aus ganz Europa angereisten“', '„aus ganz Europa angereisten“', 'Europa.'),
  },
  {
    id: 'listen-verkehr',
    type: 'listening_choice',
    topic: 'zeitungsstil',
    concept: 'vocab',
    skill: 'listening',
    difficulty: 3,
    audio: 'Der immer weiter zunehmende Lieferverkehr stellt die Innenstädte vor große Probleme.',
    question: l('What is causing problems?', 'Sorunlara ne yol açıyor?', 'Was macht Probleme?'),
    options: ['increasing delivery traffic', 'too many bikes', 'empty shops'],
    answer: 0,
    explanation: l('„zunehmende Lieferverkehr“', '„zunehmende Lieferverkehr“', 'Lieferverkehr.'),
  },

  ...attrDrills(),
]

export const UNIT_B2_04_PARTIZIPIALATTRIBUTE: CourseUnit = {
  level: 'B2',
  number: 4,
  slug: 'partizipialattribute',
  titleDe: 'Der seit Jahren leerstehende Bahnhof',
  title: l('The station that has stood empty for years', 'Yıllardır boş duran istasyon', 'Der seit Jahren leerstehende Bahnhof'),
  goal: l(
    'By the end of this unit you can understand long participle phrases in newspaper and formal texts, turn them into relative clauses and build simple ones yourself.',
    'Bu ünitenin sonunda gazete ve resmî metinlerdeki uzun ortaç öbeklerini anlayabilir, onları ilgi cümlesine çevirebilir ve basit olanlarını kendin kurabilirsin.',
    'Am Ende dieser Einheit verstehst und bildest du Partizipialattribute.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'erkennen', label: l('Recognising attributes', 'Sıfat öbeklerini tanımak', 'Erkennen') },
    { key: 'umformen', label: l('Rewriting', 'Dönüştürmek', 'Umformen') },
    { key: 'zeitungsstil', label: l('Newspaper style', 'Gazete üslubu', 'Zeitungsstil') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Compact phrases from the newspaper.', 'Gazeteden yoğun ifadeler.', 'Kompakte Zeitungssprache.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('The bracket: article … noun', 'Parantez: artikel … isim', 'Die Klammer: Artikel … Nomen'),
          body: l(
            'A long attribute sits between the article and the noun. The participle (with ending) stands right before the noun; all extra information comes before it: die [gestern von der Stadt veröffentlichte] Studie.',
            'Uzun bir sıfat öbeği artikel ile isim arasında durur. Ortaç (ekli) ismin hemen önündedir; tüm ek bilgiler ondan önce gelir: die [gestern von der Stadt veröffentlichte] Studie.',
            'Artikel + Erweiterung + Partizip + Nomen.'
          ),
          examples: [
            { de: 'der **seit Jahren leerstehende** Bahnhof', translation: l('the station that has been empty for years', 'yıllardır boş duran istasyon', '') },
            { de: 'die **von der Stadt geplante** Straße', translation: l('the road planned by the city', 'belediyenin planladığı yol', '') },
          ],
        },
        {
          title: l('Turning it into a relative clause', 'İlgi cümlesine çevirmek', 'In einen Relativsatz umformen'),
          body: l(
            'Partizip I → active, same time: die im Park spielenden Kinder = die Kinder, die im Park spielen. Partizip II → passive or finished: das 1890 gebaute Haus = das Haus, das 1890 gebaut wurde.',
            'Partizip I → etken, aynı zaman: die im Park spielenden Kinder = die Kinder, die im Park spielen. Partizip II → edilgen ya da bitmiş: das 1890 gebaute Haus = das Haus, das 1890 gebaut wurde.',
            'Partizip I = aktiv; Partizip II = passiv.'
          ),
          table: {
            head: [l('Attribute', 'Sıfat öbeği', 'Attribut'), l('Relative clause', 'İlgi cümlesi', 'Relativsatz')],
            rows: [
              ['die wartenden Gäste', 'die Gäste, die warten'],
              ['die gestern angekommenen Gäste', 'die Gäste, die gestern angekommen sind'],
              ['das oft gelesene Buch', 'das Buch, das oft gelesen wird'],
            ],
          },
        },
        {
          title: l('Reading strategy', 'Okuma stratejisi', 'Lesestrategie'),
          body: l(
            'When an article is followed by a preposition or adverb instead of a noun, an attribute is starting. Jump to the next noun that fits the article, then read the middle part.',
            'Bir artikelden sonra isim yerine edat veya zarf geliyorsa bir sıfat öbeği başlıyordur. Artikele uyan bir sonraki isme atla, sonra ortadaki kısmı oku.',
            'Artikel → Nomen suchen → Mitte lesen.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Kerem reads the newspaper with his German friend Lisa.', 'Kerem, Alman arkadaşı Lisa ile gazete okuyor.', 'Zeitung lesen.'),
      dialogue: [
        { speaker: 'Kerem', de: 'Hier steht: „**Die von der Stadt geplanten** Maßnahmen …“ – das ist so lang!', translation: l('It says: „The measures planned by the city …“ – that’s so long!', 'Burada yazıyor: „Belediyenin planladığı önlemler …“ – çok uzun!', '') },
        { speaker: 'Lisa', de: 'Such zuerst das Nomen: „die … Maßnahmen“. Und dann: Welche Maßnahmen?', translation: l('First look for the noun: „the … measures“. Then: which measures?', 'Önce ismi bul: „die … Maßnahmen“. Sonra: hangi önlemler?', '') },
        { speaker: 'Kerem', de: 'Die Maßnahmen, **die von der Stadt geplant werden**. Ah, verstehe!', translation: l('The measures that are planned by the city. Ah, I see!', 'Belediye tarafından planlanan önlemler. Ha, anladım!', '') },
        { speaker: 'Lisa', de: 'Genau. Und hier: „**die seit Wochen streikenden** Busfahrer“?', translation: l('Exactly. And here: „the bus drivers who have been on strike for weeks“?', 'Aynen. Peki burada: „haftalardır grevde olan otobüs şoförleri“?', '') },
        { speaker: 'Kerem', de: 'Die Busfahrer, **die seit Wochen streiken**. Partizip I – also aktiv.', translation: l('The bus drivers who have been striking for weeks. Partizip I – so active.', 'Haftalardır grev yapan şoförler. Partizip I – yani etken.', '') },
        { speaker: 'Lisa', de: 'Perfekt! Bald liest du die Zeitung schneller als ich.', translation: l('Perfect! Soon you’ll read the paper faster than me.', 'Mükemmel! Yakında gazeteyi benden hızlı okuyacaksın.', '') },
      ],
      examples: [
        { de: 'die **gestern veröffentlichte** Studie', translation: l('the study published yesterday', 'dün yayımlanan araştırma', '') },
        { de: 'die **im Garten spielenden** Kinder', translation: l('the children playing in the garden', 'bahçede oynayan çocuklar', '') },
        { de: 'das **1905 errichtete** Gebäude', translation: l('the building erected in 1905', '1905’te inşa edilen bina', '') },
        { de: 'die **vom Hochwasser betroffenen** Familien', translation: l('the families affected by the flood', 'selden etkilenen aileler', '') },
        { de: 'der **immer weiter zunehmende** Verkehr', translation: l('the ever increasing traffic', 'giderek artan trafik', '') },
        { de: 'die **für Mai geplante** Eröffnung', translation: l('the opening planned for May', 'Mayıs’a planlanan açılış', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Find the noun, decode the middle.', 'İsmi bul, ortayı çöz.', 'Nomen finden, Mitte verstehen.'),
      exercises: ['match-attribut', 'sort-gleichzeitig', 'attr-bruecke', 'attr-kinder', 'mc-nomen', 'tf-zeitung', 'select-korrekt', 'image-baustelle', 'attr-gesetz'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Build and rewrite attributes.', 'Sıfat öbekleri kur ve dönüştür.', 'Attribute bilden und umformen.'),
      exercises: [
        'fill-geplanten',
        'fill-wachsenden',
        'fill-betroffenen',
        'build-studie',
        'build-anwohner',
        'build-gebaeude',
        'fix-reihenfolge',
        'fix-endung',
        'fix-aktiv',
        'tr-attribut',
        'tr-relativ',
        'ordering-aufloesen',
        'dialog-umformen',
        'dialog-einfach',
        'attr-preise',
        'attr-brief',
        'attr-zug',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A local newspaper article.', 'Yerel bir gazete haberi.', 'Ein Lokalartikel.'),
      passage: [
        '**Neues Leben im alten Bahnhof** – **Der seit über zwanzig Jahren leerstehende** Bahnhof in Neustadt wird zu einem Kulturzentrum umgebaut.',
        '**Die von der Stadt bereitgestellten** fünf Millionen Euro sollen für Konzertsaal, Café und Ateliers reichen.',
        'Nicht alle sind begeistert: **Die direkt neben dem Bahnhof wohnenden** Anwohner befürchten mehr Lärm und Verkehr.',
        '**Die für das Frühjahr 2028 geplante** Eröffnung soll mit einem großen Fest gefeiert werden.',
      ],
      glossary: [
        { de: 'umbauen', note: l('to convert', 'dönüştürmek', 'anders bauen') },
        { de: 'bereitstellen', note: l('to provide', 'sağlamak', 'geben') },
        { de: 'befürchten', note: l('to fear', 'korkmak, endişe etmek', 'Angst haben vor') },
        { de: 'das Atelier', note: l('studio', 'atölye', 'Raum für Künstler') },
      ],
      exercises: ['read-thema', 'read-leer', 'read-kritik', 'read-eroeffnung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Radio news in compact style.', 'Yoğun üslupta radyo haberleri.', 'Radionachrichten.'),
      exercises: ['listen-studie', 'listen-bruecke', 'listen-gaeste', 'listen-verkehr'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Explain a newspaper headline to a friend – turn the attributes into relative clauses.', 'Bir gazete manşetini arkadaşına açıkla – sıfat öbeklerini ilgi cümlesine çevir.', 'Erkläre eine Schlagzeile.'),
      points: [
        l('Read the headline aloud.', 'Manşeti yüksek sesle oku.', 'vorlesen'),
        l('Find the article and the noun.', 'Artikeli ve ismi bul.', 'Artikel + Nomen'),
        l('Say it as a relative clause.', 'İlgi cümlesi olarak söyle.', 'Relativsatz'),
        l('Give your opinion on the news.', 'Habere dair fikrini söyle.', 'Meinung'),
      ],
      model: [
        'Die Schlagzeile lautet: „Die seit Monaten geschlossene Schwimmhalle öffnet wieder.“',
        'Das Nomen ist „Schwimmhalle“.',
        'Also: Die Schwimmhalle, die seit Monaten geschlossen ist, öffnet wieder.',
        'Ich finde das super, weil ich gern schwimme.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short local news item (at least 5 sentences) with at least two extended participle phrases.',
        'En az iki genişletilmiş ortaç öbeği içeren kısa bir yerel haber yaz (en az 5 cümle).',
        'Schreib eine Lokalmeldung (mindestens 5 Sätze) mit Partizipialattributen.'
      ),
      minSentences: 5,
      checks: [
        { label: l('An extended attribute (der/die/das … participle + ending)', 'Genişletilmiş öbek (der/die/das … ortaç + ek)', 'Partizipialattribut'), pattern: '\\b([Dd](er|ie|as|en|em))\\s+(\\p{Ll}+\\s+){1,4}\\p{Ll}+(end|t|en)(e|er|es|en|em)\\s+\\p{Lu}' },
        { label: l('Partizip II (passive attribute)', 'Partizip II (edilgen öbek)', 'Partizip II'), pattern: '\\b\\p{Ll}*(ge|er|be|ver)\\p{Ll}+(t|en)(e|er|es|en|em)\\s+\\p{Lu}' },
        { label: l('Partizip I (-end- + ending)', 'Partizip I (-end- + ek)', 'Partizip I'), pattern: '\\p{Ll}+end(e|er|es|en|em)\\s+\\p{Lu}' },
      ],
      model: [
        'In unserer Stadt wurde am Samstag ein neuer Park eröffnet.',
        'Der lange von den Bürgern geforderte Park liegt direkt am Fluss.',
        'Die zahlreich erschienenen Besucher feierten bei Sonnenschein.',
        'Die im Park spielenden Kinder hatten besonders viel Spaß.',
        'Die Stadt plant schon den nächsten Park.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Clause → attribute – 60 seconds.', 'Cümle → öbek – 60 saniye.', 'Relativsatz → Attribut – 60 Sekunden.'),
      seconds: 60,
      pool: [...ATTR.map(([id]) => `attr-${id}`), 'mc-nomen'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('The bracket: article + extra info + participle + noun', 'Parantez: artikel + ek bilgi + ortaç + isim', 'Klammer'),
      l('Partizip I → active (die wartenden Gäste = die Gäste, die warten)', 'Partizip I → etken (die wartenden Gäste = die Gäste, die warten)', 'Partizip I'),
      l('Partizip II → passive (das gebaute Haus = das Haus, das gebaut wurde)', 'Partizip II → edilgen (das gebaute Haus = das Haus, das gebaut wurde)', 'Partizip II'),
      l('Reading strategy for newspaper texts', 'Gazete metinleri için okuma stratejisi', 'Lesestrategie'),
    ],
    mistakes: [
      { wrong: 'der reparierte gestern Aufzug', right: 'der gestern reparierte Aufzug', note: l('Participle before noun.', 'Ortaç isimden önce.', 'Partizip vor Nomen.') },
      { wrong: 'mit den wartend Fahrgästen', right: 'mit den wartenden Fahrgästen', note: l('Ending.', 'Ek.', 'Endung.') },
      { wrong: 'das von vielen lesende Buch', right: 'das von vielen gelesene Buch', note: l('Passive → Partizip II.', 'Edilgen → Partizip II.', 'Partizip II.') },
      { wrong: 'die Kurse, die die Firma anbieten', right: 'die Kurse, die die Firma anbietet', note: l('Subject = die Firma (singular).', 'Özne = die Firma (tekil).', 'Singular.') },
    ],
  },
}
