import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'ist zu + Infinitiv', emoji: '📌', translation: l('must / can be done', 'yapılmalı / yapılabilir', 'muss / kann gemacht werden'), example: 'Das Formular ist bis Freitag abzugeben.' },
  { word: 'lässt sich + Infinitiv', emoji: '🔧', translation: l('can be done', 'yapılabilir', 'kann gemacht werden'), example: 'Das Problem lässt sich leicht lösen.' },
  { word: 'lösbar', emoji: '🧩', translation: l('solvable', 'çözülebilir', 'kann gelöst werden'), example: 'Die Aufgabe ist lösbar.' },
  { word: 'machbar', emoji: '✅', translation: l('feasible', 'yapılabilir', 'kann gemacht werden'), example: 'Ist das bis Montag machbar?' },
  { word: 'unvermeidlich', emoji: '⛔', translation: l('unavoidable', 'kaçınılmaz', 'kann nicht vermieden werden'), example: 'Verspätungen sind leider unvermeidlich.' },
  { word: 'erreichbar', emoji: '📞', translation: l('reachable', 'ulaşılabilir', 'man kann ihn erreichen'), example: 'Ich bin ab 9 Uhr erreichbar.' },
  { word: 'die Gebrauchsanweisung', emoji: '📘', translation: l('instructions for use', 'kullanım kılavuzu', 'erklärt ein Gerät'), example: 'Laut Gebrauchsanweisung ist das Gerät trocken zu lagern.' },
  { word: 'die Vorschrift', emoji: '📜', translation: l('regulation', 'yönetmelik, kural', 'offizielle Regel'), example: 'Die Vorschriften sind unbedingt einzuhalten.' },
  { word: 'einhalten', emoji: '🤝', translation: l('to comply with', 'uymak', 'beachten'), example: 'Die Frist muss eingehalten werden.' },
  { word: 'man', emoji: '👤', translation: l('one, people', 'insanlar, -ılır', 'allgemeines Subjekt'), example: 'Hier spricht man Deutsch.' },
  { word: 'sich verkaufen', emoji: '🛍️', translation: l('to sell (well)', 'satılmak', 'wird gekauft'), example: 'Das Buch verkauft sich sehr gut.' },
  { word: 'nicht zu übersehen', emoji: '👀', translation: l('impossible to overlook', 'gözden kaçırılamaz', 'sehr deutlich'), example: 'Das Schild ist nicht zu übersehen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Vorschrift', gender: 'f', plural: 'die Vorschriften', translation: l('regulation', 'kural', 'Vorschrift') },
  { word: 'Anleitung', gender: 'f', plural: 'die Anleitungen', translation: l('instructions', 'talimat', 'Anleitung') },
  { word: 'Frist', gender: 'f', plural: 'die Fristen', translation: l('deadline', 'süre', 'Frist') },
  { word: 'Antrag', gender: 'm', plural: 'die Anträge', translation: l('application', 'başvuru', 'Antrag') },
  { word: 'Unterlagen', gender: 'f', plural: 'die Unterlagen', translation: l('documents', 'belgeler', 'Unterlagen') },
  { word: 'Gerät', gender: 'n', plural: 'die Geräte', translation: l('device', 'cihaz', 'Gerät') },
  { word: 'Lösung', gender: 'f', plural: 'die Lösungen', translation: l('solution', 'çözüm', 'Lösung') },
  { word: 'Hinweis', gender: 'm', plural: 'die Hinweise', translation: l('note, hint', 'not, uyarı', 'Hinweis') },
]

/** [id, passive sentence, right adjective sentence, wrong] */
const BAR: [string, string, string, [string, string]][] = [
  ['loesen', 'Das Problem kann gelöst werden.', 'Das Problem ist lösbar.', ['Das Problem ist löslich.', 'Das Problem ist gelöst.']],
  ['essen', 'Der Pilz kann gegessen werden.', 'Der Pilz ist essbar.', ['Der Pilz ist gegessen.', 'Der Pilz ist esslich.']],
  ['lesen', 'Die Schrift kann nicht gelesen werden.', 'Die Schrift ist unleserlich.', ['Die Schrift ist unlesbarlich.', 'Die Schrift ist ungelesen.']],
  ['erklaeren', 'Das kann man nicht erklären.', 'Das ist unerklärlich.', ['Das ist unerklärt.', 'Das ist erklärbarlich.']],
  ['trinken', 'Das Wasser kann getrunken werden.', 'Das Wasser ist trinkbar.', ['Das Wasser ist getrunken.', 'Das Wasser ist trinklich.']],
]

function barDrills(): Exercise[] {
  return BAR.map(([id, passive, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `bar-${id}`,
      type: 'multiple_choice' as const,
      topic: 'bar-lich',
      concept: 'bar-adjective',
      skill: 'vocabulary' as const,
      difficulty: 2 as const,
      prompt: `„${passive}“ – Was bedeutet dasselbe?`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `-bar / -lich = can be done: ${right} A participle (gelöst, gegessen) means it has already happened.`,
        `-bar / -lich = yapılabilir: ${right} Ortaç (gelöst, gegessen) ise işin zaten yapıldığını gösterir.`,
        `-bar / -lich = kann … werden → ${right}`
      ),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-ersatz',
    type: 'matching',
    topic: 'sein-zu',
    concept: 'forms-overview',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Match the alternative and the passive meaning.', 'Alternatif yapıyı edilgen anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Das ist zu prüfen.', right: 'Das muss geprüft werden.' },
      { left: 'Das lässt sich prüfen.', right: 'Das kann geprüft werden.' },
      { left: 'Das ist prüfbar.', right: 'Man kann das prüfen.' },
      { left: 'Hier prüft man alles.', right: 'Hier wird alles geprüft.' },
    ],
    explanation: l('Four ways to avoid the werden-passive.', 'werden-edilgeninden kaçınmanın dört yolu.', 'Passiversatz.'),
  },
  {
    id: 'sort-muss-kann',
    type: 'categorize',
    topic: 'sein-zu',
    concept: 'must-or-can',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('sein + zu: must or can? Look at the context.', 'sein + zu: zorunluluk mu olasılık mı? Bağlama bak.', 'muss oder kann?'),
    categories: ['muss … werden', 'kann … werden'],
    items: [
      { text: 'Die Miete ist bis zum 3. zu zahlen.', category: 0 },
      { text: 'Der Fehler ist leicht zu finden.', category: 1 },
      { text: 'Der Ausweis ist immer mitzuführen.', category: 0 },
      { text: 'Das Museum ist gut zu erreichen.', category: 1 },
      { text: 'Die Regeln sind einzuhalten.', category: 0 },
      { text: 'Der Text ist kaum zu verstehen.', category: 1 },
    ],
    explanation: l('Rules and deadlines → must. With leicht, gut, kaum, nicht → can.', 'Kurallar ve süreler → zorunluluk. leicht, gut, kaum, nicht ile → olasılık.', 'Kontext entscheidet.'),
    practice: ['bar-loesen'],
  },
  {
    id: 'mc-lassen',
    type: 'multiple_choice',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das Fenster ___ sich nicht öffnen.',
    options: ['lässt', 'ist', 'wird'],
    answer: 0,
    explanation: l('sich lassen + infinitive = can be done: Das Fenster lässt sich nicht öffnen.', 'sich lassen + mastar = yapılabilir: Das Fenster lässt sich nicht öffnen.', 'lässt sich.'),
    examples: ['Das Fenster **lässt sich** nicht **öffnen**.'],
    practice: ['fill-laesst'],
  },
  {
    id: 'tf-zu',
    type: 'true_false',
    topic: 'sein-zu',
    concept: 'separable-zu',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Bei trennbaren Verben steht „zu“ in der Mitte: abgeben → abzugeben.',
    answer: true,
    explanation: l('ab-zu-geben, ein-zu-halten, mit-zu-bringen.', 'ab-zu-geben, ein-zu-halten, mit-zu-bringen.', 'abzugeben.'),
  },
  {
    id: 'select-ersatz',
    type: 'multiple_select',
    topic: 'man-passiv',
    concept: 'forms-overview',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which sentences mean „The text can be translated easily“? Select all.', 'Hangi cümleler „Metin kolayca çevrilebilir“ anlamına geliyor? Hepsini seç.', 'Gleiche Bedeutung?'),
    options: ['Der Text lässt sich leicht übersetzen.', 'Der Text ist leicht zu übersetzen.', 'Der Text ist übersetzt.', 'Man kann den Text leicht übersetzen.', 'Der Text muss übersetzt werden.'],
    answers: [0, 1, 3],
    explanation: l('lässt sich / ist zu (with leicht) / man kann = can be done.', 'lässt sich / ist zu (leicht ile) / man kann = yapılabilir.', 'kann … werden.'),
  },
  {
    id: 'image-trinkbar',
    type: 'image_choice',
    topic: 'bar-lich',
    concept: 'bar-adjective',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Achtung: Dieses Wasser ist nicht trinkbar!',
    options: [
      { emoji: '🚱', label: 'kein Trinkwasser' },
      { emoji: '🚰', label: 'Trinkwasser' },
      { emoji: '🍷', label: 'Wein' },
      { emoji: '🥛', label: 'Milch' },
    ],
    answer: 0,
    explanation: l('nicht trinkbar = cannot be drunk.', 'nicht trinkbar = içilemez.', 'nicht trinkbar.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-laesst',
    type: 'fill_blank',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Dieser Termin ___ sich leider nicht verschieben.',
    accepted: ['lässt'],
    base: 'sich lassen',
    explanation: l('Der Termin lässt sich nicht verschieben = cannot be postponed.', 'Der Termin lässt sich nicht verschieben = ertelenemez.', 'lässt.'),
    examples: ['Dieser Termin **lässt** sich leider nicht verschieben.'],
  },
  {
    id: 'fill-abzugeben',
    type: 'fill_blank',
    topic: 'sein-zu',
    concept: 'separable-zu',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Antrag ist bis zum 30. Juni ___. (abgeben)',
    accepted: ['abzugeben'],
    base: 'abgeben',
    explanation: l('sein + zu + infinitive; separable: ab-zu-geben.', 'sein + zu + mastar; ayrılabilen: ab-zu-geben.', 'abzugeben.'),
    examples: ['Der Antrag ist bis zum 30. Juni **abzugeben**.'],
  },
  {
    id: 'fill-man',
    type: 'fill_blank',
    topic: 'man-passiv',
    concept: 'man',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'In der Schweiz spricht ___ vier Sprachen.',
    accepted: ['man'],
    base: 'allgemeines Subjekt',
    explanation: l('man + active verb = general statement (like a passive).', 'man + etken fiil = genel ifade (edilgen gibi).', 'man.'),
    examples: ['In der Schweiz spricht **man** vier Sprachen.'],
  },
  {
    id: 'build-zu',
    type: 'sentence_builder',
    topic: 'sein-zu',
    concept: 'must-or-can',
    skill: 'grammar',
    difficulty: 3,
    chips: ['einzuhalten', 'sind', 'Die Sicherheitsregeln', 'unbedingt'],
    answers: [['Die Sicherheitsregeln', 'sind', 'unbedingt', 'einzuhalten']],
    translation: l('The safety rules must be observed.', 'Güvenlik kurallarına mutlaka uyulmalıdır.', 'Die Sicherheitsregeln sind unbedingt einzuhalten.'),
    explanation: l('sein + zu + infinitive at the end = must be done.', 'sein + zu + sonda mastar = yapılmalı.', 'sind … einzuhalten.'),
    examples: ['Die Sicherheitsregeln **sind** unbedingt **einzuhalten**.'],
  },
  {
    id: 'build-lassen',
    type: 'sentence_builder',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'grammar',
    difficulty: 2,
    chips: ['reparieren', 'lässt sich', 'Der alte Drucker', 'nicht mehr'],
    answers: [['Der alte Drucker', 'lässt sich', 'nicht mehr', 'reparieren']],
    translation: l('The old printer can’t be repaired any more.', 'Eski yazıcı artık tamir edilemez.', 'Der alte Drucker lässt sich nicht mehr reparieren.'),
    explanation: l('lässt sich + infinitive at the end.', 'lässt sich + sonda mastar.', 'lässt sich … reparieren.'),
    examples: ['Der alte Drucker **lässt sich** nicht mehr **reparieren**.'],
  },
  {
    id: 'build-bar',
    type: 'sentence_builder',
    topic: 'bar-lich',
    concept: 'bar-adjective',
    skill: 'grammar',
    difficulty: 2,
    chips: ['bis Freitag', 'Ist das', 'für Sie', 'machbar'],
    answers: [['Ist das', 'für Sie', 'bis Freitag', 'machbar'], ['Ist das', 'bis Freitag', 'für Sie', 'machbar']],
    translation: l('Is that feasible for you by Friday?', 'Bu sizin için cumaya kadar yapılabilir mi?', 'Ist das für Sie bis Freitag machbar?'),
    explanation: l('machbar = can be done.', 'machbar = yapılabilir.', 'machbar.'),
    examples: ['Ist das für Sie bis Freitag **machbar**?'],
  },
  {
    id: 'fix-zu',
    type: 'error_correction',
    topic: 'sein-zu',
    concept: 'separable-zu',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Müll ist vor die Tür zu stellen ab.',
    accepted: ['Der Müll ist vor die Tür zu stellen.'],
    explanation: l('stellen is not separable here – just „zu stellen“ at the end.', 'stellen burada ayrılabilen değil – sonda sadece „zu stellen“.', 'zu stellen.'),
    examples: ['Der Müll ist vor die Tür **zu stellen**.'],
  },
  {
    id: 'fix-laesst',
    type: 'error_correction',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Tür lässt nicht schließen.',
    accepted: ['Die Tür lässt sich nicht schließen.'],
    explanation: l('Don’t forget the reflexive pronoun: lässt sich.', 'Dönüşlü zamiri unutma: lässt sich.', 'sich.'),
    examples: ['Die Tür lässt **sich** nicht schließen.'],
  },
  {
    id: 'fix-bar',
    type: 'error_correction',
    topic: 'bar-lich',
    concept: 'bar-adjective',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Aufgabe ist gelöst, aber sehr schwer.',
    accepted: ['Die Aufgabe ist lösbar, aber sehr schwer.'],
    explanation: l('Meaning: it can be solved → lösbar (gelöst = already solved).', 'Anlam: çözülebilir → lösbar (gelöst = zaten çözülmüş).', 'lösbar.'),
    examples: ['Die Aufgabe ist **lösbar**, aber sehr schwer.'],
  },
  {
    id: 'tr-zu',
    type: 'translation',
    topic: 'sein-zu',
    concept: 'must-or-can',
    skill: 'writing',
    difficulty: 3,
    source: l('The form must be signed.', 'Form imzalanmalıdır.', 'The form must be signed.'),
    accepted: ['Das Formular ist zu unterschreiben.', 'Das Formular muss unterschrieben werden.'],
    explanation: l('ist zu unterschreiben = muss unterschrieben werden.', 'ist zu unterschreiben = muss unterschrieben werden.', 'ist zu unterschreiben.'),
    examples: ['Das Formular **ist zu unterschreiben**.'],
  },
  {
    id: 'tr-lassen',
    type: 'translation',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'writing',
    difficulty: 3,
    source: l('That can easily be changed.', 'Bu kolayca değiştirilebilir.', 'That can easily be changed.'),
    accepted: ['Das lässt sich leicht ändern.', 'Das ist leicht zu ändern.', 'Das kann leicht geändert werden.'],
    explanation: l('lässt sich leicht ändern / ist leicht zu ändern.', 'lässt sich leicht ändern / ist leicht zu ändern.', 'lässt sich ändern.'),
    examples: ['Das **lässt sich** leicht **ändern**.'],
  },
  {
    id: 'ordering-anleitung',
    type: 'ordering',
    topic: 'man-passiv',
    concept: 'instructions',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the instructions for a coffee machine in order.', 'Bir kahve makinesinin talimatlarını sırala.', 'Ordne die Anleitung.'),
    items: ['Anschließend lässt sich die Taste „Start“ drücken.', 'Zuerst ist der Wassertank zu füllen.', 'Nach der Benutzung ist die Maschine auszuschalten.', 'Dann legt man eine Kapsel ein.'],
    answer: ['Zuerst ist der Wassertank zu füllen.', 'Dann legt man eine Kapsel ein.', 'Anschließend lässt sich die Taste „Start“ drücken.', 'Nach der Benutzung ist die Maschine auszuschalten.'],
    explanation: l('Instructions often use sein + zu, man and lassen sich.', 'Talimatlarda sık sık sein + zu, man ve lassen sich kullanılır.', 'Anleitungsstil.'),
  },
  {
    id: 'dialog-machbar',
    type: 'dialogue',
    topic: 'bar-lich',
    concept: 'feasibility',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Chefin', de: 'Schaffen Sie den Bericht bis morgen früh?' }],
    options: ['Das ist schwierig, aber machbar, wenn ich heute etwas länger bleibe.', 'Der Bericht ist morgen.', 'Ich bin machbar.'],
    answer: 0,
    explanation: l('machbar = feasible – plus a condition.', 'machbar = yapılabilir – artı bir koşul.', 'machbar.'),
  },
  {
    id: 'dialog-reparatur',
    type: 'dialogue',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kundin', de: 'Kann man das Display noch reparieren?' }],
    options: ['Leider nein, das lässt sich nicht mehr reparieren. Aber wir können es austauschen.', 'Das Display ist ein Handy.', 'Reparieren Sie es selbst.'],
    answer: 0,
    explanation: l('lässt sich nicht reparieren + an alternative.', 'lässt sich nicht reparieren + bir alternatif.', 'lässt sich nicht …'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-art',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-hinweise',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was für ein Text ist das?',
    options: ['Hinweise für neue Mitglieder eines Fitnessstudios.', 'Eine Speisekarte.', 'Ein Liebesbrief.'],
    answer: 0,
    explanation: l('„Hinweise für neue Mitglieder“', '„Hinweise für neue Mitglieder“', 'Fitnessstudio.'),
  },
  {
    id: 'read-handtuch',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-hinweise',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was muss man immer benutzen?',
    options: ['Ein Handtuch auf den Geräten.', 'Kopfhörer.', 'Eine Trinkflasche.'],
    answer: 0,
    explanation: l('„Auf allen Geräten ist ein Handtuch zu benutzen.“', '„Auf allen Geräten ist ein Handtuch zu benutzen.“', 'Handtuch.'),
  },
  {
    id: 'read-kurs',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-hinweise',
    skill: 'reading',
    difficulty: 2,
    statement: 'Kurse kann man online buchen.',
    answer: true,
    explanation: l('„Kurse lassen sich bequem über die App buchen.“', '„Kurse lassen sich bequem über die App buchen.“', 'richtig.'),
  },
  {
    id: 'read-kuendigung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-hinweise',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was gilt für die Kündigung?',
    options: ['Sie ist schriftlich und vier Wochen vorher einzureichen.', 'Sie ist jederzeit mündlich möglich.', 'Sie ist nicht möglich.'],
    answer: 0,
    explanation: l('„Eine Kündigung ist schriftlich und mindestens vier Wochen vor Vertragsende einzureichen.“', '„Eine Kündigung ist schriftlich und mindestens vier Wochen vor Vertragsende einzureichen.“', 'schriftlich.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-durchsage',
    type: 'listening_choice',
    topic: 'sein-zu',
    concept: 'must-or-can',
    skill: 'listening',
    difficulty: 2,
    audio: 'Liebe Fluggäste, Flüssigkeiten sind in einem durchsichtigen Beutel vorzuzeigen.',
    question: l('What must passengers do?', 'Yolcular ne yapmalı?', 'Was müssen die Fluggäste tun?'),
    options: ['Show liquids in a clear bag.', 'Throw away all liquids.', 'Buy a bag.'],
    answer: 0,
    explanation: l('„… sind … vorzuzeigen“ = must be shown.', '„… sind … vorzuzeigen“ = gösterilmeli.', 'vorzeigen.'),
  },
  {
    id: 'listen-software',
    type: 'listening_choice',
    topic: 'sich-lassen',
    concept: 'lassen-sich',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die neue Software lässt sich ganz einfach installieren – in nur drei Minuten.',
    question: l('What is said about the software?', 'Yazılım hakkında ne söyleniyor?', 'Was wird über die Software gesagt?'),
    options: ['It is easy to install.', 'It is expensive.', 'It doesn’t work.'],
    answer: 0,
    explanation: l('„lässt sich ganz einfach installieren“', '„lässt sich ganz einfach installieren“', 'einfach.'),
  },
  {
    id: 'listen-erreichbar',
    type: 'listening_choice',
    topic: 'bar-lich',
    concept: 'bar-adjective',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich bin bis zum 15. im Urlaub und nur per E-Mail erreichbar.',
    question: l('How can you contact the person?', 'Kişiye nasıl ulaşabilirsin?', 'Wie ist die Person erreichbar?'),
    options: ['only by email', 'only by phone', 'not at all'],
    answer: 0,
    explanation: l('„nur per E-Mail erreichbar“', '„nur per E-Mail erreichbar“', 'E-Mail.'),
  },
  {
    id: 'listen-man',
    type: 'listening_choice',
    topic: 'man-passiv',
    concept: 'man',
    skill: 'listening',
    difficulty: 2,
    audio: 'In diesem Restaurant isst man auf dem Boden – Stühle gibt es nicht.',
    question: l('What is special about the restaurant?', 'Restoranın özelliği ne?', 'Was ist besonders?'),
    options: ['People eat on the floor.', 'There is no food.', 'It is very expensive.'],
    answer: 0,
    explanation: l('„isst man auf dem Boden“', '„isst man auf dem Boden“', 'Boden.'),
  },

  ...barDrills(),
]

export const UNIT_B2_02_PASSIV_ERSATZ: CourseUnit = {
  level: 'B2',
  number: 2,
  slug: 'passiv-ersatz',
  titleDe: 'Das lässt sich lösen',
  title: l('That can be solved', 'Bu çözülebilir', 'Das lässt sich lösen'),
  goal: l(
    'By the end of this unit you can use the alternatives to the passive that appear in instructions, rules and formal texts: sein + zu, sich lassen, adjectives in -bar/-lich and man.',
    'Bu ünitenin sonunda talimatlarda, kurallarda ve resmî metinlerde görülen edilgen alternatiflerini kullanabilirsin: sein + zu, sich lassen, -bar/-lich sıfatları ve man.',
    'Am Ende dieser Einheit benutzt du Passiversatzformen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'sein-zu', label: l('sein + zu + infinitive', 'sein + zu + mastar', 'sein + zu') },
    { key: 'sich-lassen', label: l('sich lassen + infinitive', 'sich lassen + mastar', 'sich lassen') },
    { key: 'bar-lich', label: l('Adjectives in -bar / -lich', '-bar / -lich sıfatları', '-bar / -lich') },
    { key: 'man-passiv', label: l('man and instructions', 'man ve talimatlar', 'man') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The language of rules and instructions.', 'Kuralların ve talimatların dili.', 'Die Sprache der Regeln.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('sein + zu + infinitive', 'sein + zu + mastar', 'sein + zu + Infinitiv'),
          body: l(
            'Means „must be done“ (rules, deadlines) or „can be done“ (often with leicht, gut, kaum, nicht). Separable verbs: abzugeben, einzuhalten.',
            '„Yapılmalı“ (kurallar, süreler) ya da „yapılabilir“ (sıklıkla leicht, gut, kaum, nicht ile) anlamına gelir. Ayrılabilen fiiller: abzugeben, einzuhalten.',
            'muss oder kann … werden.'
          ),
          examples: [
            { de: 'Der Ausweis **ist** immer **mitzuführen**.', translation: l('ID must always be carried.', 'Kimlik her zaman yanında taşınmalıdır.', '') },
            { de: 'Der Weg **ist** leicht **zu finden**.', translation: l('The way is easy to find.', 'Yol kolayca bulunabilir.', '') },
          ],
        },
        {
          title: l('sich lassen + infinitive', 'sich lassen + mastar', 'sich lassen + Infinitiv'),
          body: l(
            'Means „can be done“: Das Problem lässt sich lösen = Das Problem kann gelöst werden. Often with nicht, leicht, gut.',
            '„Yapılabilir“ anlamına gelir: Das Problem lässt sich lösen = Das Problem kann gelöst werden. Sıklıkla nicht, leicht, gut ile.',
            'kann … werden.'
          ),
          table: {
            head: [l('Alternative', 'Alternatif', 'Ersatzform'), l('Passive meaning', 'Edilgen anlam', 'Passiv')],
            rows: [
              ['ist zu lösen', 'muss/kann gelöst werden'],
              ['lässt sich lösen', 'kann gelöst werden'],
              ['ist lösbar', 'kann gelöst werden'],
              ['man löst', 'wird gelöst'],
            ],
          },
        },
        {
          title: l('Adjectives in -bar and -lich', '-bar ve -lich sıfatları', 'Adjektive auf -bar / -lich'),
          body: l(
            'Verb stem + -bar = can be done: machbar, lösbar, essbar, erreichbar. Some use -lich: unerklärlich, unvermeidlich, verständlich. With un- = cannot be done.',
            'Fiil kökü + -bar = yapılabilir: machbar, lösbar, essbar, erreichbar. Bazıları -lich alır: unerklärlich, unvermeidlich, verständlich. un- ile = yapılamaz.',
            'Stamm + -bar.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Elena calls the IT helpdesk because her laptop won’t start.', 'Elena, dizüstü bilgisayarı açılmadığı için BT destek hattını arıyor.', 'IT-Support.'),
      dialogue: [
        { speaker: 'Elena', de: 'Hallo, mein Laptop **lässt sich** nicht mehr **einschalten**.', translation: l('Hello, my laptop won’t switch on any more.', 'Merhaba, dizüstü bilgisayarım artık açılmıyor.', '') },
        { speaker: 'IT', de: 'Okay. Ist der Akku geladen? Das Kabel **ist** fest **einzustecken**.', translation: l('Okay. Is the battery charged? The cable must be plugged in firmly.', 'Tamam. Batarya şarjlı mı? Kablo sıkıca takılmalı.', '') },
        { speaker: 'Elena', de: 'Ja, das habe ich gemacht. Nichts passiert.', translation: l('Yes, I did that. Nothing happens.', 'Evet, yaptım. Hiçbir şey olmuyor.', '') },
        { speaker: 'IT', de: 'Hm, das ist ungewöhnlich, aber sicher **lösbar**. Bringen Sie ihn bitte vorbei.', translation: l('Hm, that’s unusual, but surely solvable. Please bring it by.', 'Hım, bu alışılmadık ama kesin çözülebilir. Lütfen getirin.', '') },
        { speaker: 'Elena', de: 'Ist es **machbar**, dass ich ihn heute noch zurückbekomme?', translation: l('Is it feasible that I get it back today?', 'Bugün geri almam mümkün mü?', '') },
        { speaker: 'IT', de: 'Das **lässt sich** jetzt noch nicht **sagen**. Ich rufe Sie an – Sie sind doch telefonisch **erreichbar**?', translation: l('That can’t be said yet. I’ll call you – you can be reached by phone, right?', 'Bunu şu an söylemek mümkün değil. Sizi ararım – telefonla ulaşılabilir durumdasınız, değil mi?', '') },
      ],
      examples: [
        { de: 'Das Formular **ist** bis Freitag **abzugeben**.', translation: l('The form must be handed in by Friday.', 'Form cumaya kadar teslim edilmeli.', '') },
        { de: 'Der Fehler **ist** leicht **zu finden**.', translation: l('The mistake is easy to find.', 'Hata kolayca bulunabilir.', '') },
        { de: 'Das Fenster **lässt sich** nicht **öffnen**.', translation: l('The window can’t be opened.', 'Pencere açılamıyor.', '') },
        { de: 'Das Problem ist **lösbar**.', translation: l('The problem is solvable.', 'Sorun çözülebilir.', '') },
        { de: 'In Österreich zahlt **man** mit Euro.', translation: l('In Austria people pay in euros.', 'Avusturya’da euro ile ödenir.', '') },
        { de: 'Das ist leider **unvermeidlich**.', translation: l('That is unfortunately unavoidable.', 'Bu maalesef kaçınılmaz.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Must or can? And what does -bar mean?', 'Zorunluluk mu olasılık mı? -bar ne anlama gelir?', 'muss oder kann?'),
      exercises: ['match-ersatz', 'sort-muss-kann', 'bar-loesen', 'bar-essen', 'mc-lassen', 'tf-zu', 'select-ersatz', 'image-trinkbar', 'bar-trinken'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Write rules and instructions.', 'Kurallar ve talimatlar yaz.', 'Regeln und Anleitungen.'),
      exercises: [
        'fill-laesst',
        'fill-abzugeben',
        'fill-man',
        'build-zu',
        'build-lassen',
        'build-bar',
        'fix-zu',
        'fix-laesst',
        'fix-bar',
        'tr-zu',
        'tr-lassen',
        'ordering-anleitung',
        'dialog-machbar',
        'dialog-reparatur',
        'bar-lesen',
        'bar-erklaeren',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('House rules of a gym.', 'Bir spor salonunun kuralları.', 'Hausordnung im Fitnessstudio.'),
      passage: [
        '**Hinweise für neue Mitglieder** – Herzlich willkommen in unserem Studio!',
        'Auf allen Geräten **ist** ein Handtuch **zu benutzen**. Nach dem Training **sind** die Geräte **zu reinigen**. Taschen **lassen sich** in den Schließfächern **einschließen**.',
        'Kurse **lassen sich** bequem über die App **buchen**. Die Umkleiden **sind** bis 22 Uhr **nutzbar**.',
        'Eine Kündigung **ist** schriftlich und mindestens vier Wochen vor Vertragsende **einzureichen**. Bei Fragen ist unser Team jederzeit **erreichbar**.',
      ],
      glossary: [
        { de: 'das Schließfach', note: l('locker', 'kilitli dolap', 'kleiner Schrank zum Abschließen') },
        { de: 'die Umkleide', note: l('changing room', 'soyunma odası', 'Raum zum Umziehen') },
        { de: 'einreichen', note: l('to submit', 'teslim etmek', 'abgeben') },
        { de: 'das Vertragsende', note: l('end of contract', 'sözleşme bitişi', 'Ende des Vertrags') },
      ],
      exercises: ['read-art', 'read-handtuch', 'read-kurs', 'read-kuendigung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Announcements, adverts and voicemail.', 'Anonslar, reklamlar ve telesekreter.', 'Durchsagen und Ansagen.'),
      exercises: ['listen-durchsage', 'listen-software', 'listen-erreichbar', 'listen-man'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Explain the rules of your workplace, school or flat-share to a new person.', 'İş yerinin, okulunun ya da paylaşımlı evinin kurallarını yeni gelen birine anlat.', 'Erkläre die Regeln.'),
      points: [
        l('Two obligations with sein + zu', 'sein + zu ile iki zorunluluk', 'sein + zu'),
        l('Something that is easy / impossible: lässt sich …', 'Kolay / imkânsız olan bir şey: lässt sich …', 'lässt sich'),
        l('One -bar adjective (erreichbar, machbar …)', 'Bir -bar sıfatı (erreichbar, machbar …)', '-bar'),
        l('A general statement with man', 'man ile genel bir ifade', 'man'),
      ],
      model: [
        'Bei uns in der WG ist der Putzplan unbedingt einzuhalten.',
        'Der Müll ist jeden Dienstag rauszubringen.',
        'Die Waschmaschine lässt sich leider nur mit einem Trick einschalten.',
        'Unser Vermieter ist fast immer erreichbar, und abends kocht man oft zusammen.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write short instructions or rules (at least 5 sentences), e.g. for using a device, a library or a holiday flat.',
        'Kısa bir talimat ya da kurallar yaz (en az 5 cümle), ör. bir cihaz, kütüphane ya da tatil dairesi için.',
        'Schreib eine Anleitung oder Regeln (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('sein + zu (ist/sind … zu …)', 'sein + zu (ist/sind … zu …)', 'sein + zu'), pattern: '\\b(ist|sind)\\b[^.!?]*(\\bzu \\p{Ll}+en|\\b\\p{Ll}+zu\\p{Ll}+en)\\b' },
        { label: l('sich lassen (lässt/lassen sich)', 'sich lassen (lässt/lassen sich)', 'sich lassen'), pattern: '\\b(lässt|lassen) sich\\b' },
        { label: l('An adjective in -bar / -lich', '-bar / -lich ile biten bir sıfat', '-bar'), pattern: '\\p{Ll}+bar\\b' },
      ],
      model: [
        'Willkommen in unserer Ferienwohnung!',
        'Der Schlüssel ist bei der Abreise in den Briefkasten zu werfen.',
        'Die Heizung lässt sich mit dem Knopf am Fenster regulieren.',
        'Das WLAN ist im ganzen Haus nutzbar.',
        'Der Müll ist nach der deutschen Mülltrennung zu sortieren.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('-bar or not? – 60 seconds.', '-bar mı değil mi? – 60 saniye.', '-bar? – 60 Sekunden.'),
      seconds: 60,
      pool: [...BAR.map(([id]) => `bar-${id}`), 'mc-lassen'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('sein + zu: must / can be done (ist abzugeben, ist leicht zu finden)', 'sein + zu: yapılmalı / yapılabilir (ist abzugeben, ist leicht zu finden)', 'sein + zu'),
      l('sich lassen: can be done (lässt sich lösen)', 'sich lassen: yapılabilir (lässt sich lösen)', 'sich lassen'),
      l('-bar / -lich: machbar, lösbar, erreichbar, unvermeidlich', '-bar / -lich: machbar, lösbar, erreichbar, unvermeidlich', '-bar / -lich'),
      l('man for general statements and instructions', 'Genel ifadeler ve talimatlar için man', 'man'),
    ],
    mistakes: [
      { wrong: 'Die Tür lässt nicht schließen.', right: 'Die Tür lässt sich nicht schließen.', note: l('Reflexive pronoun.', 'Dönüşlü zamir.', 'sich.') },
      { wrong: 'ist zu abgeben', right: 'ist abzugeben', note: l('zu inside separable verbs.', 'Ayrılabilen fiilde zu ortada.', 'abzugeben.') },
      { wrong: 'Die Aufgabe ist gelöst (= kann gelöst werden)', right: 'Die Aufgabe ist lösbar.', note: l('-bar = possible.', '-bar = mümkün.', 'lösbar.') },
      { wrong: 'Das Wasser ist getrunken.', right: 'Das Wasser ist trinkbar.', note: l('Participle ≠ possibility.', 'Ortaç ≠ olasılık.', 'trinkbar.') },
    ],
  },
}
