import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Hose', gender: 'f', plural: 'die Hosen', emoji: '👖', translation: l('trousers', 'pantolon', 'Hose'), example: 'Die Hose ist blau.' },
  { word: 'Jacke', gender: 'f', plural: 'die Jacken', emoji: '🧥', translation: l('jacket', 'ceket, mont', 'Jacke'), example: 'Die Jacke ist warm.' },
  { word: 'Schuh', gender: 'm', plural: 'die Schuhe', emoji: '👟', translation: l('shoe', 'ayakkabı', 'Schuh'), example: 'Die Schuhe sind neu.' },
  { word: 'T-Shirt', gender: 'n', plural: 'die T-Shirts', emoji: '👕', translation: l('T-shirt', 'tişört', 'T-Shirt'), example: 'Das T-Shirt ist weiß.' },
  { word: 'Kleid', gender: 'n', plural: 'die Kleider', emoji: '👗', translation: l('dress', 'elbise', 'Kleid'), example: 'Das Kleid ist sehr schön.' },
  { word: 'Hemd', gender: 'n', plural: 'die Hemden', emoji: '👔', translation: l('shirt', 'gömlek', 'Hemd'), example: 'Er trägt ein Hemd.' },
  { word: 'Hut', gender: 'm', plural: 'die Hüte', emoji: '👒', translation: l('hat', 'şapka', 'Hut'), example: 'Der Hut ist gelb.' },
  { word: 'Schal', gender: 'm', plural: 'die Schals', emoji: '🧣', translation: l('scarf', 'atkı', 'Schal'), example: 'Der Schal ist rot.' },
  { word: 'Socke', gender: 'f', plural: 'die Socken', emoji: '🧦', translation: l('sock', 'çorap', 'Socke'), example: 'Die Socken sind grün.' },
  { word: 'Mütze', gender: 'f', plural: 'die Mützen', emoji: '🧢', translation: l('cap, woolly hat', 'bere, kep', 'Mütze'), example: 'Die Mütze ist schwarz.' },
  { word: 'Pullover', gender: 'm', plural: 'die Pullover', emoji: '🧶', translation: l('jumper, sweater', 'kazak', 'Pullover'), example: 'Der Pullover ist grau.' },
  { word: 'Rock', gender: 'm', plural: 'die Röcke', emoji: '🩳', translation: l('skirt', 'etek', 'Rock'), example: 'Der Rock ist kurz.' },
]

const COLORS: [string, string, ReturnType<typeof l>][] = [
  ['rot', '🔴', l('red', 'kırmızı', 'rot')],
  ['blau', '🔵', l('blue', 'mavi', 'blau')],
  ['grün', '🟢', l('green', 'yeşil', 'grün')],
  ['gelb', '🟡', l('yellow', 'sarı', 'gelb')],
  ['schwarz', '⚫', l('black', 'siyah', 'schwarz')],
  ['weiß', '⚪', l('white', 'beyaz', 'weiß')],
  ['braun', '🟤', l('brown', 'kahverengi', 'braun')],
  ['orange', '🟠', l('orange', 'turuncu', 'orange')],
  ['lila', '🟣', l('purple', 'mor', 'lila')],
]

const MORE_VOCAB: VocabItem[] = [
  ...COLORS.map(([word, emoji, translation]) => ({ word, emoji, translation })),
  { word: 'grau', translation: l('grey', 'gri', 'grau') },
  { word: 'tragen', translation: l('to wear', 'giymek (üzerinde olmak)', 'tragen') },
  { word: 'gefallen', translation: l('to please – „Das gefällt mir“ = I like it', 'hoşa gitmek – „Das gefällt mir“ = beğendim', 'gefallen') },
  { word: 'zu groß / zu klein', translation: l('too big / too small', 'çok büyük / çok küçük', 'zu groß / zu klein') },
  { word: 'Farbe', gender: 'f', plural: 'die Farben', translation: l('colour', 'renk', 'Farbe') },
  { word: 'Größe', gender: 'f', plural: 'die Größen', translation: l('size', 'beden', 'Größe') },
]

function colorDrills(): Exercise[] {
  const words = COLORS.map(([w]) => w)
  return COLORS.map(([word, emoji], i) => {
    const options = [word, words[(i + 2) % words.length], words[(i + 5) % words.length]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `farbe-${word}`,
      type: 'multiple_choice' as const,
      topic: 'colors',
      concept: 'colors',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `${emoji} = ___`,
      options: ordered,
      answer: ordered.indexOf(word),
      explanation: l(`${emoji} = ${word}`, `${emoji} = ${word}`, `${emoji} = ${word}`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'img-kleid',
    type: 'image_choice',
    topic: 'vocabulary',
    concept: 'clothes',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'das Kleid',
    options: [
      { emoji: '👗', label: 'das Kleid' },
      { emoji: '👔', label: 'das Hemd' },
      { emoji: '👖', label: 'die Hose' },
      { emoji: '🧥', label: 'die Jacke' },
    ],
    answer: 0,
    explanation: l('das Kleid = dress.', 'das Kleid = elbise.', 'das Kleid.'),
    examples: ['**Das Kleid** ist sehr schön.'],
  },
  {
    id: 'match-clothes',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'clothes',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match clothes and pictures.', 'Giysileri ve resimleri eşleştir.', 'Ordne Kleidung und Bilder zu.'),
    pairs: [
      { left: 'die Hose', right: '👖' },
      { left: 'das Hemd', right: '👔' },
      { left: 'der Schal', right: '🧣' },
      { left: 'die Socken', right: '🧦' },
      { left: 'die Mütze', right: '🧢' },
    ],
    explanation: l('Learn clothes with their article: die Hose, das Hemd, der Schal.', 'Giysileri artikeliyle öğren: die Hose, das Hemd, der Schal.', 'Mit Artikel lernen.'),
  },
  {
    id: 'match-colors',
    type: 'matching',
    topic: 'colors',
    concept: 'colors',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the colours.', 'Renkleri eşleştir.', 'Ordne die Farben zu.'),
    pairs: [
      { left: 'rot', right: '🔴' },
      { left: 'blau', right: '🔵' },
      { left: 'gelb', right: '🟡' },
      { left: 'grün', right: '🟢' },
      { left: 'schwarz', right: '⚫' },
    ],
    explanation: l('Colours are adjectives – lower case: rot, blau, gelb …', 'Renkler sıfattır – küçük harfle: rot, blau, gelb …', 'Farben sind Adjektive – klein geschrieben.'),
  },
  {
    id: 'mc-farbe',
    type: 'multiple_choice',
    topic: 'colors',
    concept: 'color-question',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Farbe hat dein Auto? – Es ist rot.',
    options: ['Welche', 'Wie', 'Was'],
    answer: 0,
    explanation: l('Asking about colour: Welche Farbe hat …?', 'Renk sormak: Welche Farbe hat …?', 'Welche Farbe hat …?'),
    examples: ['**Welche Farbe** hat dein Auto?'],
  },
  {
    id: 'mc-traegt',
    type: 'multiple_choice',
    topic: 'tragen',
    concept: 'tragen-forms',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Heute ___ Tom ein weißes Hemd.',
    options: ['trägt', 'tragt', 'trage'],
    answer: 0,
    explanation: l('tragen: du trägst, er trägt (a → ä, like fahren).', 'tragen: du trägst, er trägt (fahren gibi a → ä).', 'tragen: du trägst, er trägt.'),
    examples: ['Tom **trägt** ein Hemd.'],
    practice: ['fill-traegst'],
  },
  {
    id: 'sort-der-die-das',
    type: 'categorize',
    topic: 'vocabulary',
    concept: 'clothes-gender',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('der, die or das?', 'der, die mi das mı?', 'der, die oder das?'),
    categories: ['der', 'die', 'das'],
    items: [
      { text: 'Schal', category: 0 },
      { text: 'Hose', category: 1 },
      { text: 'Kleid', category: 2 },
      { text: 'Pullover', category: 0 },
      { text: 'Jacke', category: 1 },
      { text: 'Hemd', category: 2 },
    ],
    explanation: l('der Schal, der Pullover · die Hose, die Jacke · das Kleid, das Hemd.', 'der Schal, der Pullover · die Hose, die Jacke · das Kleid, das Hemd.', 'der Schal, die Hose, das Kleid …'),
  },
  {
    id: 'tf-gefaellt',
    type: 'true_false',
    topic: 'gefallen',
    concept: 'gefallen',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Die Jacke gefällt mir“ heißt: Ich finde die Jacke schön.',
    answer: true,
    explanation: l(
      'Die Jacke gefällt mir = I like the jacket (literally: the jacket pleases me). Plural: Die Schuhe gefallen mir.',
      'Die Jacke gefällt mir = Ceketi beğendim (kelimesi kelimesine: ceket bana hoş geliyor). Çoğul: Die Schuhe gefallen mir.',
      'Die Jacke gefällt mir = Ich finde sie schön.'
    ),
    examples: ['Die Jacke **gefällt mir**.', 'Die Schuhe **gefallen mir**.'],
  },
  {
    id: 'select-winter',
    type: 'multiple_select',
    topic: 'vocabulary',
    concept: 'clothes',
    skill: 'vocabulary',
    difficulty: 1,
    promptL10n: l('What do you wear in winter? Select all.', 'Kışın ne giyersin? Hepsini seç.', 'Was trägt man im Winter? Wähle alle.'),
    options: ['die Jacke', 'das T-Shirt', 'der Schal', 'der Rock', 'die Mütze'],
    answers: [0, 2, 4],
    explanation: l('Winter: Jacke, Schal, Mütze.', 'Kış: Jacke, Schal, Mütze.', 'Winter: Jacke, Schal, Mütze.'),
  },

  // --- Practice 2: use --------------------------------------------------
  {
    id: 'fill-ist-blau',
    type: 'fill_blank',
    topic: 'colors',
    concept: 'color-predicate',
    skill: 'grammar',
    difficulty: 1,
    visual: ['👖 🔵'],
    sentence: 'Die Hose ist ___.',
    accepted: ['blau'],
    explanation: l('Colour after „ist“ – no ending: Die Hose ist blau.', '„ist“ten sonra renk – ek yok: Die Hose ist blau.', 'Nach „ist“ ohne Endung: blau.'),
    examples: ['Die Hose ist **blau**.'],
  },
  {
    id: 'fill-sind',
    type: 'fill_blank',
    topic: 'colors',
    concept: 'color-predicate',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Meine Schuhe ___ schwarz.',
    accepted: ['sind'],
    base: 'sein',
    explanation: l('die Schuhe (plural) → sind.', 'die Schuhe (çoğul) → sind.', 'Plural → sind.'),
    examples: ['Meine Schuhe **sind** schwarz.'],
  },
  {
    id: 'fill-traegst',
    type: 'fill_blank',
    topic: 'tragen',
    concept: 'tragen-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Du ___ heute eine schöne Jacke!',
    accepted: ['trägst'],
    base: 'tragen',
    explanation: l('du trägst (a → ä).', 'du trägst (a → ä).', 'du trägst.'),
    examples: ['Du **trägst** eine schöne Jacke.'],
  },
  {
    id: 'mc-zu-gross',
    type: 'multiple_choice',
    topic: 'size',
    concept: 'zu-gross',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Hose ist leider ___ groß. Ich brauche Größe 38.',
    options: ['zu', 'sehr', 'nicht'],
    answer: 0,
    explanation: l('zu groß = too big (that’s a problem). sehr groß = very big.', 'zu groß = çok büyük (sorun). sehr groß = oldukça büyük.', 'zu groß = Problem.'),
    examples: ['Die Hose ist **zu groß**.'],
  },
  {
    id: 'build-gefaellt',
    type: 'sentence_builder',
    topic: 'gefallen',
    concept: 'gefallen',
    skill: 'grammar',
    difficulty: 2,
    chips: ['mir', 'gefällt', 'Das Kleid'],
    answers: [['Das Kleid', 'gefällt', 'mir']],
    translation: l('I like the dress.', 'Elbiseyi beğendim.', 'Das Kleid gefällt mir.'),
    explanation: l('The thing you like is the subject: Das Kleid gefällt mir.', 'Beğenilen şey öznedir: Das Kleid gefällt mir.', 'Das Kleid (Subjekt) gefällt mir.'),
    examples: ['Das Kleid **gefällt mir**.'],
  },
  {
    id: 'build-welche-farbe',
    type: 'sentence_builder',
    topic: 'colors',
    concept: 'color-question',
    skill: 'grammar',
    difficulty: 1,
    chips: ['hat', 'Welche Farbe', 'die Jacke'],
    answers: [['Welche Farbe', 'hat', 'die Jacke']],
    end: '?',
    translation: l('What colour is the jacket?', 'Ceket ne renk?', 'Welche Farbe hat die Jacke?'),
    explanation: l('Welche Farbe + hat + noun?', 'Welche Farbe + hat + isim?', 'Welche Farbe hat …?'),
    examples: ['**Welche Farbe** hat die Jacke?'],
  },
  {
    id: 'build-trage',
    type: 'sentence_builder',
    topic: 'tragen',
    concept: 'tragen-forms',
    skill: 'grammar',
    difficulty: 1,
    chips: ['einen Pullover', 'trage', 'Heute', 'ich'],
    answers: [['Heute', 'trage', 'ich', 'einen Pullover']],
    translation: l('Today I’m wearing a jumper.', 'Bugün kazak giyiyorum.', 'Heute trage ich einen Pullover.'),
    explanation: l('tragen + Akkusativ: der Pullover → einen Pullover.', 'tragen + Akkusativ: der Pullover → einen Pullover.', 'tragen + Akkusativ.'),
    examples: ['Heute **trage** ich {m:einen Pullover}.'],
  },
  {
    id: 'fix-gefallen',
    type: 'error_correction',
    topic: 'gefallen',
    concept: 'gefallen',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Schuhe gefällt mir.',
    accepted: ['Die Schuhe gefallen mir.'],
    explanation: l('die Schuhe (plural) → gefallen.', 'die Schuhe (çoğul) → gefallen.', 'Plural → gefallen.'),
    examples: ['Die Schuhe **gefallen** mir.'],
  },
  {
    id: 'fix-rot-gross',
    type: 'error_correction',
    topic: 'colors',
    concept: 'color-predicate',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Der Schal ist Rot.',
    accepted: ['Der Schal ist rot.'],
    explanation: l('Colours are adjectives → lower case: rot.', 'Renkler sıfattır → küçük harf: rot.', 'Farben klein: rot.'),
    examples: ['Der Schal ist **rot**.'],
  },
  {
    id: 'tr-jacke',
    type: 'translation',
    topic: 'colors',
    concept: 'color-predicate',
    skill: 'writing',
    difficulty: 1,
    source: l('The jacket is black.', 'Ceket siyah.', 'The jacket is black.'),
    accepted: ['Die Jacke ist schwarz.'],
    explanation: l('die Jacke + ist + schwarz.', 'die Jacke + ist + schwarz.', 'Die Jacke ist schwarz.'),
    examples: ['Die Jacke ist **schwarz**.'],
  },
  {
    id: 'tr-zu-klein',
    type: 'translation',
    topic: 'size',
    concept: 'zu-gross',
    skill: 'writing',
    difficulty: 2,
    source: l('The shoes are too small.', 'Ayakkabılar çok küçük.', 'The shoes are too small.'),
    accepted: ['Die Schuhe sind zu klein.'],
    explanation: l('die Schuhe (plural) + sind + zu klein.', 'die Schuhe (çoğul) + sind + zu klein.', 'Die Schuhe sind zu klein.'),
    examples: ['Die Schuhe sind **zu klein**.'],
  },
  {
    id: 'dialog-gefaellt',
    type: 'dialogue',
    topic: 'gefallen',
    concept: 'gefallen',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Freundin', de: 'Wie findest du das Kleid?' }],
    options: ['Es gefällt mir sehr!', 'Ich gefalle das Kleid.', 'Es gefällt ich.'],
    answer: 0,
    explanation: l('Es (das Kleid) gefällt mir.', 'Es (das Kleid) gefällt mir.', 'Es gefällt mir.'),
    examples: ['Es **gefällt mir** sehr!'],
  },
  {
    id: 'dialog-groesse',
    type: 'dialogue',
    topic: 'size',
    concept: 'zu-gross',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Verkäuferin', de: 'Passt die Jacke?' }],
    options: ['Nein, sie ist zu groß.', 'Nein, er ist zu groß.', 'Nein, es ist zu groß.'],
    answer: 0,
    explanation: l('die Jacke → sie (Unit 05: die → sie).', 'die Jacke → sie (Ünite 05: die → sie).', 'die Jacke → sie.'),
    examples: ['Nein, **sie** ist zu groß.'],
  },

  // --- Reading -----------------------------------------------------
  {
    id: 'read-schal',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-fundbuero',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Welche Farbe hat der Schal?',
    options: ['grün', 'rot', 'blau'],
    answer: 0,
    explanation: l('„Ein Schal – er ist grün und lang.“', '„Ein Schal – er ist grün und lang.“', '„er ist grün“'),
  },
  {
    id: 'read-schuhe',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-fundbuero',
    skill: 'reading',
    difficulty: 1,
    statement: 'Die Kinderschuhe sind weiß.',
    answer: false,
    explanation: l('„Kinderschuhe, Größe 28 – sie sind gelb.“', '„Kinderschuhe, Größe 28 – sie sind gelb.“', '„sie sind gelb“'),
  },
  {
    id: 'read-groesse',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-fundbuero',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welche Größe hat die Jacke?',
    options: ['M', 'S', 'L'],
    answer: 0,
    explanation: l('„Eine Jacke, Größe M – sie ist braun.“', '„Eine Jacke, Größe M – sie ist braun.“', '„Größe M“'),
  },
  {
    id: 'read-wann',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-fundbuero',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wann ist das Fundbüro geöffnet?',
    options: ['Montag bis Freitag, 9–16 Uhr', 'jeden Tag', 'nur am Wochenende'],
    answer: 0,
    explanation: l('„Öffnungszeiten: Mo–Fr 9–16 Uhr“', '„Öffnungszeiten: Mo–Fr 9–16 Uhr“', '„Mo–Fr 9–16 Uhr“'),
  },

  // --- Listening ---------------------------------------------------
  {
    id: 'listen-farbe',
    type: 'listening_choice',
    topic: 'colors',
    concept: 'colors',
    skill: 'listening',
    difficulty: 1,
    audio: 'Mein Auto ist rot.',
    question: l('What colour is the car?', 'Araba ne renk?', 'Welche Farbe hat das Auto?'),
    options: ['🔴', '🔵', '⚫'],
    answer: 0,
    explanation: l('rot = red.', 'rot = kırmızı.', 'rot.'),
  },
  {
    id: 'listen-traegt',
    type: 'listening_choice',
    topic: 'tragen',
    concept: 'tragen-forms',
    skill: 'listening',
    difficulty: 2,
    audio: 'Sie trägt ein gelbes Kleid und weiße Schuhe.',
    question: l('What is she wearing?', 'Ne giyiyor?', 'Was trägt sie?'),
    options: ['👗🟡 + 👟⚪', '👖🔵 + 👟⚫', '👔⚪ + 👟🟡'],
    answer: 0,
    explanation: l('yellow dress + white shoes.', 'sarı elbise + beyaz ayakkabı.', 'gelbes Kleid + weiße Schuhe.'),
  },
  {
    id: 'listen-gefaellt',
    type: 'listening_choice',
    topic: 'gefallen',
    concept: 'gefallen',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Jacke gefällt mir nicht. Sie ist zu teuer.',
    question: l('Does the person like the jacket?', 'Kişi ceketi beğeniyor mu?', 'Gefällt der Person die Jacke?'),
    options: ['Ja', 'Nein'],
    answer: 1,
    explanation: l('„gefällt mir nicht“', '„gefällt mir nicht“', '„gefällt mir nicht“'),
  },
  {
    id: 'listen-gross',
    type: 'listening_choice',
    topic: 'size',
    concept: 'zu-gross',
    skill: 'listening',
    difficulty: 1,
    audio: 'Die Schuhe sind zu klein. Haben Sie Größe 42?',
    question: l('What’s the problem?', 'Sorun ne?', 'Was ist das Problem?'),
    options: ['zu klein', 'zu groß', 'zu teuer'],
    answer: 0,
    explanation: l('„zu klein“', '„zu klein“', '„zu klein“'),
  },

  ...colorDrills(),
]

export const UNIT20_KLEIDUNG_FARBEN: CourseUnit = {
  level: 'A1',
  number: 20,
  slug: 'kleidung-farben',
  titleDe: 'Kleidung und Farben',
  title: l('Clothes and colours', 'Giysiler ve renkler', 'Kleidung und Farben'),
  goal: l(
    'By the end of this unit you can name clothes and colours, say what someone is wearing and say what you like (Das gefällt mir).',
    'Bu ünitenin sonunda giysileri ve renkleri söyleyebilir, birinin ne giydiğini anlatabilir ve neyi beğendiğini söyleyebilirsin (Das gefällt mir).',
    'Am Ende dieser Einheit benennst du Kleidung und Farben, sagst, was jemand trägt, und was dir gefällt.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'vocabulary', label: l('Clothes', 'Giysiler', 'Kleidung') },
    { key: 'colors', label: l('Colours', 'Renkler', 'Farben') },
    { key: 'tragen', label: l('tragen: du trägst', 'tragen: du trägst', 'tragen: du trägst') },
    { key: 'gefallen', label: l('Das gefällt mir', 'Das gefällt mir', 'Das gefällt mir') },
    { key: 'size', label: l('zu groß / zu klein', 'zu groß / zu klein', 'zu groß / zu klein') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Twelve pieces of clothing – the colours follow in the exercises.', 'On iki giysi – renkler alıştırmalarda geliyor.', 'Zwölf Kleidungsstücke – die Farben folgen in den Übungen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Colours after „ist“', '„ist“ten sonra renkler', 'Farben nach „ist“'),
          body: l(
            'After sein, colours have no ending and are written in lower case: Die Hose ist blau. Die Schuhe sind schwarz. Ask: Welche Farbe hat …?',
            'sein’den sonra renkler ek almaz ve küçük harfle yazılır: Die Hose ist blau. Die Schuhe sind schwarz. Soru: Welche Farbe hat …?',
            'Nach sein: ohne Endung, klein: Die Hose ist blau.'
          ),
          table: {
            head: [l('colour', 'renk', 'Farbe'), l('', '', ''), l('colour', 'renk', 'Farbe'), l('', '', '')],
            rows: [
              ['🔴', 'rot', '⚫', 'schwarz'],
              ['🔵', 'blau', '⚪', 'weiß'],
              ['🟢', 'grün', '🟤', 'braun'],
              ['🟡', 'gelb', '🟣', 'lila'],
            ],
          },
          tip: l(
            'Before a noun, colours get endings (eine blaue Hose) – you will practise that in A2. For now, use „ist“.',
            'İsimden önce renkler ek alır (eine blaue Hose) – bunu A2’de çalışacaksın. Şimdilik „ist“ kullan.',
            'Vor dem Nomen mit Endung (eine blaue Hose) – das kommt in A2.'
          ),
        },
        {
          title: l('tragen – to wear', 'tragen – giymek', 'tragen'),
          body: l(
            'tragen changes a → ä for du and er (like fahren): ich trage, du trägst, er trägt. What you wear is Akkusativ: Er trägt einen Hut.',
            'tragen du ve er için a → ä olur (fahren gibi): ich trage, du trägst, er trägt. Giyilen şey Akkusativ’dir: Er trägt einen Hut.',
            'tragen: du trägst, er trägt + Akkusativ.'
          ),
          examples: [
            { de: 'Ich **trage** heute {m:einen Pullover}.', translation: l('I’m wearing a jumper today.', 'Bugün kazak giyiyorum.', 'ich trage') },
            { de: 'Sie **trägt** {n:ein Kleid}.', translation: l('She is wearing a dress.', 'Elbise giyiyor.', 'sie trägt') },
          ],
        },
        {
          title: l('Das gefällt mir', 'Das gefällt mir', 'Das gefällt mir'),
          body: l(
            'To say you like a thing, German says „it pleases me“: Die Jacke gefällt mir. Plural: Die Schuhe gefallen mir. Not: Ich gefalle die Jacke!',
            'Bir şeyi beğendiğini söylemek için Almanca „bana hoş geliyor“ der: Die Jacke gefällt mir. Çoğul: Die Schuhe gefallen mir. Ich gefalle die Jacke değil!',
            'Die Jacke gefällt mir. Die Schuhe gefallen mir.'
          ),
        },
        {
          title: l('zu groß, zu klein, zu teuer', 'zu groß, zu klein, zu teuer', 'zu groß, zu klein, zu teuer'),
          body: l(
            'zu = too (a problem): Die Hose ist zu groß. sehr = very (not a problem): Die Hose ist sehr schön.',
            'zu = fazla (sorun): Die Hose ist zu groß. sehr = çok (sorun değil): Die Hose ist sehr schön.',
            'zu = Problem, sehr = verstärkt.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Elif and Sophie get ready for a party.', 'Elif ve Sophie bir partiye hazırlanıyor.', 'Elif und Sophie machen sich für eine Party fertig.'),
      dialogue: [
        { speaker: 'Sophie', de: 'Was **trägst** du heute Abend?', translation: l('What are you wearing tonight?', 'Bu akşam ne giyiyorsun?', '') },
        { speaker: 'Elif', de: 'Mein Kleid. Es ist **grün**. Und du?', translation: l('My dress. It’s green. And you?', 'Elbisemi. Yeşil. Ya sen?', '') },
        { speaker: 'Sophie', de: 'Ich weiß nicht. Diese Hose ist **zu klein**.', translation: l('I don’t know. These trousers are too small.', 'Bilmiyorum. Bu pantolon çok küçük.', '') },
        { speaker: 'Elif', de: 'Und das Hemd? Welche Farbe hat es?', translation: l('And the shirt? What colour is it?', 'Ya gömlek? Ne renk?', '') },
        { speaker: 'Sophie', de: 'Es ist **blau**. **Gefällt** es **dir**?', translation: l('It’s blue. Do you like it?', 'Mavi. Beğendin mi?', '') },
        { speaker: 'Elif', de: 'Ja, es **gefällt mir** sehr! Und die schwarzen Schuhe passen gut.', translation: l('Yes, I like it a lot! And the black shoes go well.', 'Evet, çok beğendim! Siyah ayakkabılar da çok yakışır.', '') },
      ],
      examples: [
        { de: 'Die Hose ist **blau**.', translation: l('The trousers are blue.', 'Pantolon mavi.', '') },
        { de: 'Die Schuhe sind **schwarz**.', translation: l('The shoes are black.', 'Ayakkabılar siyah.', '') },
        { de: 'Welche Farbe hat dein Auto? – **Rot**.', translation: l('What colour is your car? – Red.', 'Araban ne renk? – Kırmızı.', '') },
        { de: 'Er **trägt** {m:einen Hut}.', translation: l('He is wearing a hat.', 'Şapka takıyor.', '') },
        { de: 'Das Kleid **gefällt mir**.', translation: l('I like the dress.', 'Elbiseyi beğendim.', '') },
        { de: 'Die Jacke ist **zu teuer**.', translation: l('The jacket is too expensive.', 'Ceket çok pahalı.', '') },
        { de: 'Im Winter **trage** ich {f:eine Mütze}.', translation: l('In winter I wear a woolly hat.', 'Kışın bere takarım.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Clothes, colours and tragen.', 'Giysiler, renkler ve tragen.', 'Kleidung, Farben und tragen.'),
      exercises: ['img-kleid', 'match-clothes', 'match-colors', 'mc-farbe', 'mc-traegt', 'sort-der-die-das', 'tf-gefaellt', 'select-winter', 'farbe-weiß'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Describe clothes and say what you like.', 'Giysileri tarif et ve neyi beğendiğini söyle.', 'Beschreibe Kleidung und sag, was dir gefällt.'),
      exercises: [
        'fill-ist-blau',
        'fill-sind',
        'fill-traegst',
        'mc-zu-gross',
        'build-gefaellt',
        'build-welche-farbe',
        'build-trage',
        'fix-gefallen',
        'fix-rot-gross',
        'tr-jacke',
        'tr-zu-klein',
        'dialog-gefaellt',
        'dialog-groesse',
        'farbe-braun',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A notice from the lost property office.', 'Kayıp eşya bürosundan bir duyuru.', 'Ein Aushang vom Fundbüro.'),
      passage: [
        '**Fundbüro Stadtmitte** – Wir haben:',
        'einen Schal – er ist **grün** und lang · eine Mütze – sie ist **schwarz**',
        'eine Jacke, Größe M – sie ist **braun** · Kinderschuhe, Größe 28 – sie sind **gelb**',
        'Öffnungszeiten: Mo–Fr 9–16 Uhr',
      ],
      glossary: [
        { de: 'das Fundbüro', note: l('lost property office', 'kayıp eşya bürosu', 'Ort für verlorene Sachen') },
        { de: 'lang', note: l('long', 'uzun', 'nicht kurz') },
        { de: 'Kinderschuhe', note: l('children’s shoes', 'çocuk ayakkabısı', 'Schuhe für Kinder') },
      ],
      exercises: ['read-schal', 'read-schuhe', 'read-groesse', 'read-wann'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Colours and clothes in conversation.', 'Konuşmada renkler ve giysiler.', 'Farben und Kleidung im Gespräch.'),
      exercises: ['listen-farbe', 'listen-traegt', 'listen-gefaellt', 'listen-gross'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe what you are wearing today.', 'Bugün ne giydiğini anlat.', 'Beschreib, was du heute trägst.'),
      points: [
        l('„Heute trage ich …“', '„Heute trage ich …“', '„Heute trage ich …“'),
        l('Colours: „Die Hose ist … / Die Schuhe sind …“', 'Renkler: „Die Hose ist … / Die Schuhe sind …“', 'Farben'),
        l('What you like: „… gefällt mir.“', 'Beğendiğin: „… gefällt mir.“', 'Was dir gefällt'),
      ],
      model: ['Heute trage ich eine Jeans und einen Pullover.', 'Die Jeans ist blau und der Pullover ist grau.', 'Meine Schuhe sind weiß.', 'Mein Pullover gefällt mir sehr.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Describe your favourite clothes (at least 4 sentences).',
        'En sevdiğin giysileri anlat (en az 4 cümle).',
        'Beschreib deine Lieblingskleidung (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('Names clothes', 'Giysi adı veriyor', 'Nennt Kleidung'), pattern: '\\b(Hose|Jacke|Schuhe?|T-Shirt|Kleid|Hemd|Hut|Schal|Socken?|Mütze|Pullover|Rock|Jeans)\\b' },
        { label: l('Names colours', 'Renk adı veriyor', 'Nennt Farben'), pattern: '\\b(rot|blau|grün|gelb|schwarz|weiß|braun|orange|lila|grau)\\b' },
        { label: l('tragen or gefallen', 'tragen ya da gefallen', 'tragen oder gefallen'), pattern: '\\b(trage|trägst|trägt|tragen|gefällt|gefallen)\\b' },
      ],
      model: ['Mein Lieblingskleid ist rot.', 'Ich trage es im Sommer.', 'Meine Jacke ist schwarz und warm.', 'Die Jacke gefällt mir sehr.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Name the colours – 60 seconds!', 'Renkleri söyle – 60 saniye!', 'Benenne die Farben – 60 Sekunden!'),
      seconds: 60,
      pool: COLORS.map(([w]) => `farbe-${w}`),
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Clothes with articles', 'Artikelleriyle giysiler', 'Kleidung mit Artikel'),
      l('Colours: Die Hose ist blau.', 'Renkler: Die Hose ist blau.', 'Farben: Die Hose ist blau.'),
      l('tragen: ich trage, du trägst, er trägt', 'tragen: ich trage, du trägst, er trägt', 'tragen: du trägst, er trägt'),
      l('Das gefällt mir / Die Schuhe gefallen mir', 'Das gefällt mir / Die Schuhe gefallen mir', 'Das gefällt mir'),
      l('zu groß, zu klein, zu teuer', 'zu groß, zu klein, zu teuer', 'zu groß, zu klein, zu teuer'),
    ],
    mistakes: [
      { wrong: 'Die Hose ist Blau.', right: 'Die Hose ist blau.', note: l('Colours in lower case.', 'Renkler küçük harfle.', 'Farben klein.') },
      { wrong: 'Er tragt einen Hut.', right: 'Er trägt einen Hut.', note: l('a → ä', 'a → ä', 'a → ä') },
      { wrong: 'Ich gefalle die Jacke.', right: 'Die Jacke gefällt mir.', note: l('The thing is the subject.', 'Beğenilen şey öznedir.', 'Die Sache ist Subjekt.') },
      { wrong: 'Die Schuhe gefällt mir.', right: 'Die Schuhe gefallen mir.', note: l('Plural → gefallen.', 'Çoğul → gefallen.', 'Plural → gefallen.') },
    ],
  },
}
