import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Hunger haben', emoji: '🍽️', translation: l('to be hungry', 'acıkmak', 'Hunger haben'), example: 'Ich habe Hunger.' },
  { word: 'Durst haben', emoji: '🥤', translation: l('to be thirsty', 'susamak', 'Durst haben'), example: 'Hast du Durst?' },
  { word: 'Zeit haben', emoji: '⏰', translation: l('to have time', 'vakti olmak', 'Zeit haben'), example: 'Wir haben heute Zeit.' },
  { word: 'Angst haben', emoji: '😨', translation: l('to be afraid', 'korkmak', 'Angst haben'), example: 'Das Kind hat Angst.' },
  { word: 'Glück haben', emoji: '🍀', translation: l('to be lucky', 'şanslı olmak', 'Glück haben'), example: 'Du hast Glück!' },
  { word: 'Lust haben', emoji: '😊', translation: l('to feel like (doing)', 'canı istemek', 'Lust haben'), example: 'Hast du Lust auf Kino?' },
  { word: 'müde sein', emoji: '😴', translation: l('to be tired', 'yorgun olmak', 'müde sein'), example: 'Ich bin müde.' },
  { word: 'krank sein', emoji: '🤒', translation: l('to be ill', 'hasta olmak', 'krank sein'), example: 'Er ist krank.' },
  { word: 'glücklich sein', emoji: '😄', translation: l('to be happy', 'mutlu olmak', 'glücklich sein'), example: 'Wir sind glücklich.' },
  { word: 'zu Hause sein', emoji: '🏠', translation: l('to be at home', 'evde olmak', 'zu Hause sein'), example: 'Seid ihr zu Hause?' },
  { word: 'fertig sein', emoji: '✅', translation: l('to be finished / ready', 'bitirmiş / hazır olmak', 'fertig sein'), example: 'Bist du fertig?' },
  { word: 'Recht haben', emoji: '👍', translation: l('to be right', 'haklı olmak', 'Recht haben'), example: 'Sie haben Recht.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Kopfschmerzen (Pl.)', translation: l('headache', 'baş ağrısı', 'Kopfschmerzen') },
  { word: 'Erkältung', gender: 'f', plural: 'die Erkältungen', translation: l('cold (illness)', 'soğuk algınlığı', 'Erkältung') },
  { word: 'nett', translation: l('nice, kind', 'kibar, hoş', 'nett') },
  { word: 'hungrig', translation: l('hungry (adjective)', 'aç (sıfat)', 'hungrig') },
]

const SEIN = { ich: 'bin', du: 'bist', er: 'ist', wir: 'sind', ihr: 'seid', sie: 'sind' } as const
const HABEN = { ich: 'habe', du: 'hast', er: 'hat', wir: 'haben', ihr: 'habt', sie: 'haben' } as const
type Person = keyof typeof SEIN

/** All persons for sein and haben. */
function formDrills(): Exercise[] {
  const persons = Object.keys(SEIN) as Person[]
  return (['sein', 'haben'] as const).flatMap((verb, v) =>
    persons.map((person, i) => {
      const table = verb === 'sein' ? SEIN : HABEN
      const right = table[person]
      const others = [...new Set(Object.values(table))].filter((f) => f !== right)
      const options = [right, others[(i + v) % others.length], others[(i + v + 2) % others.length]]
      const rotation = (i + v) % 3
      const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
      return {
        id: `${verb}-${person}`,
        type: 'multiple_choice' as const,
        topic: verb === 'sein' ? 'sein-forms' : 'haben-forms',
        concept: `${verb}-forms`,
        skill: 'grammar' as const,
        difficulty: 1 as const,
        prompt: `${person} ___ (${verb})`,
        options: ordered,
        answer: ordered.indexOf(right),
        explanation: l(`${person} ${right}.`, `${person} ${right}.`, `${person} ${right}.`),
      }
    })
  )
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise ----------------------------------------------
  {
    id: 'img-hunger',
    type: 'image_choice',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Ich habe Hunger.',
    options: [
      { emoji: '🥤', label: 'Durst' },
      { emoji: '🍽️', label: 'Hunger' },
      { emoji: '😴', label: 'müde' },
      { emoji: '😨', label: 'Angst' },
    ],
    answer: 1,
    explanation: l(
      'German: „I have hunger“ – Ich habe Hunger (= I am hungry).',
      'Almancada „açlığım var“ denir: Ich habe Hunger (= acıktım).',
      'Ich habe Hunger = Ich möchte essen.'
    ),
    examples: ['Ich **habe** Hunger.'],
  },
  {
    id: 'sort-sein-haben',
    type: 'categorize',
    topic: 'contrast',
    concept: 'sein-or-haben',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('sein or haben? Sort.', 'sein mi haben mı? Ayır.', 'sein oder haben? Sortiere.'),
    categories: ['sein', 'haben'],
    items: [
      { text: 'müde', category: 0 },
      { text: 'Hunger', category: 1 },
      { text: 'krank', category: 0 },
      { text: 'Zeit', category: 1 },
      { text: 'glücklich', category: 0 },
      { text: 'Durst', category: 1 },
      { text: 'zu Hause', category: 0 },
      { text: 'Angst', category: 1 },
    ],
    explanation: l(
      'sein + adjective or place (müde, krank, zu Hause). haben + noun (Hunger, Zeit, Durst, Angst – capital letter!).',
      'sein + sıfat ya da yer (müde, krank, zu Hause). haben + isim (Hunger, Zeit, Durst, Angst – büyük harf!).',
      'sein + Adjektiv oder Ort. haben + Nomen (großgeschrieben!).'
    ),
  },
  {
    id: 'mc-seid',
    type: 'multiple_choice',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ihr ___ sehr nett!',
    options: ['seid', 'sind', 'seit'],
    answer: 0,
    explanation: l(
      'ihr seid (with d). „seit“ (with t) means „since“ – same sound, different word!',
      'ihr seid (d ile). „seit“ (t ile) „-den beri“ demektir – aynı ses, farklı kelime!',
      'ihr seid (mit d). „seit“ (mit t) ist eine Präposition!'
    ),
    examples: ['Ihr **seid** sehr nett.'],
    practice: ['sein-wir', 'sein-du'],
  },
  {
    id: 'mc-habt',
    type: 'multiple_choice',
    topic: 'haben-forms',
    concept: 'haben-forms',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ ihr heute Zeit?',
    options: ['Habt', 'Haben', 'Hast'],
    answer: 0,
    explanation: l('ihr habt – yes/no question: Habt ihr …?', 'ihr habt – evet/hayır sorusu: Habt ihr …?', 'ihr habt → Habt ihr …?'),
    examples: ['**Habt** ihr heute Zeit?'],
    practice: ['haben-er', 'haben-du'],
  },
  {
    id: 'tf-bin-hunger',
    type: 'true_false',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Ich bin Hunger.',
    answer: false,
    instructions: l('Is this sentence correct?', 'Bu cümle doğru mu?', 'Ist der Satz richtig?'),
    explanation: l('Hunger is a noun → haben: Ich habe Hunger. (Or: Ich bin hungrig.)', 'Hunger isimdir → haben: Ich habe Hunger. (Ya da: Ich bin hungrig.)', 'Hunger ist ein Nomen → Ich habe Hunger.'),
    examples: ['Ich **habe** Hunger.'],
  },
  {
    id: 'select-haben',
    type: 'multiple_select',
    topic: 'contrast',
    concept: 'sein-or-haben',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which words go with haben? Select all.', 'Hangi kelimeler haben ile kullanılır? Hepsini seç.', 'Welche Wörter gehen mit haben? Wähle alle.'),
    options: ['Durst', 'müde', 'Glück', 'krank', 'Lust', 'fertig'],
    answers: [0, 2, 4],
    explanation: l('haben + Durst, Glück, Lust (nouns). sein + müde, krank, fertig (adjectives).', 'haben + Durst, Glück, Lust (isimler). sein + müde, krank, fertig (sıfatlar).', 'haben + Nomen, sein + Adjektiv.'),
  },
  {
    id: 'match-sein',
    type: 'matching',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Match person and form of sein.', 'Kişi ve sein biçimini eşleştir.', 'Ordne Person und Form von sein zu.'),
    pairs: [
      { left: 'ich', right: 'bin' },
      { left: 'du', right: 'bist' },
      { left: 'er / sie', right: 'ist' },
      { left: 'ihr', right: 'seid' },
    ],
    explanation: l('ich bin, du bist, er ist, wir sind, ihr seid, sie sind.', 'ich bin, du bist, er ist, wir sind, ihr seid, sie sind.', 'ich bin, du bist, er ist, wir sind, ihr seid, sie sind.'),
  },
  {
    id: 'match-haben',
    type: 'matching',
    topic: 'haben-forms',
    concept: 'haben-forms',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Match person and form of haben.', 'Kişi ve haben biçimini eşleştir.', 'Ordne Person und Form von haben zu.'),
    pairs: [
      { left: 'ich', right: 'habe' },
      { left: 'du', right: 'hast' },
      { left: 'er / sie', right: 'hat' },
      { left: 'ihr', right: 'habt' },
    ],
    explanation: l('ich habe, du hast, er hat, wir haben, ihr habt, sie haben.', 'ich habe, du hast, er hat, wir haben, ihr habt, sie haben.', 'ich habe, du hast, er hat, wir haben, ihr habt, sie haben.'),
  },

  // --- Practice 2: use ---------------------------------------------------
  {
    id: 'fill-seid',
    type: 'fill_blank',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wo ___ ihr? – Wir sind im Park.',
    accepted: ['seid'],
    base: 'sein',
    explanation: l('ihr seid.', 'ihr seid.', 'ihr seid.'),
    examples: ['Wo **seid** ihr?'],
  },
  {
    id: 'fill-hat',
    type: 'fill_blank',
    topic: 'haben-forms',
    concept: 'haben-forms',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Er ___ heute keine Zeit.',
    accepted: ['hat'],
    base: 'haben',
    explanation: l('er hat.', 'er hat.', 'er hat.'),
    examples: ['Er **hat** keine Zeit.'],
  },
  {
    id: 'fill-sind',
    type: 'fill_blank',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Meine Eltern ___ zu Hause.',
    accepted: ['sind'],
    base: 'sein',
    explanation: l('meine Eltern = sie (plural) → sind.', 'meine Eltern = sie (çoğul) → sind.', 'meine Eltern = sie → sind.'),
    examples: ['Meine Eltern **sind** zu Hause.'],
  },
  {
    id: 'build-habt-zeit',
    type: 'sentence_builder',
    topic: 'haben-forms',
    concept: 'haben-forms',
    skill: 'grammar',
    difficulty: 1,
    chips: ['Zeit', 'ihr', 'Habt'],
    answers: [['Habt', 'ihr', 'Zeit']],
    end: '?',
    translation: l('Do you (pl.) have time?', 'Vaktiniz var mı?', 'Habt ihr Zeit?'),
    explanation: l('Yes/no question: Habt + ihr + Zeit?', 'Evet/hayır sorusu: Habt + ihr + Zeit?', 'Ja/Nein-Frage: Habt ihr Zeit?'),
    examples: ['**Habt** ihr Zeit?'],
  },
  {
    id: 'build-muede',
    type: 'sentence_builder',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 1,
    chips: ['müde', 'sind', 'Wir', 'heute'],
    answers: [['Wir', 'sind', 'heute', 'müde'], ['Heute', 'sind', 'wir', 'müde']],
    translation: l('We are tired today.', 'Bugün yorgunuz.', 'Wir sind heute müde.'),
    explanation: l('Wir + sind + heute + müde.', 'Wir + sind + heute + müde.', 'Wir + sind + heute + müde.'),
    examples: ['Wir **sind** heute müde.'],
  },
  {
    id: 'fix-bin-durst',
    type: 'error_correction',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich bin Durst.',
    accepted: ['Ich habe Durst.'],
    explanation: l('Durst (noun) → haben.', 'Durst (isim) → haben.', 'Durst (Nomen) → haben.'),
    examples: ['Ich **habe** Durst.'],
  },
  {
    id: 'fix-seit',
    type: 'error_correction',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ihr seit sehr nett.',
    accepted: ['Ihr seid sehr nett.'],
    explanation: l('ihr seid – with d.', 'ihr seid – d ile.', 'ihr seid – mit d.'),
    examples: ['Ihr **seid** sehr nett.'],
  },
  {
    id: 'fix-habe-muede',
    type: 'error_correction',
    topic: 'contrast',
    concept: 'sein-or-haben',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie hat krank.',
    accepted: ['Sie ist krank.'],
    explanation: l('krank (adjective) → sein.', 'krank (sıfat) → sein.', 'krank (Adjektiv) → sein.'),
    examples: ['Sie **ist** krank.'],
  },
  {
    id: 'tr-hunger',
    type: 'translation',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'writing',
    difficulty: 1,
    source: l('I am hungry.', 'Acıktım.', 'I am hungry.'),
    accepted: ['Ich habe Hunger.', 'Ich bin hungrig.'],
    explanation: l('Ich habe Hunger. (also: Ich bin hungrig.)', 'Ich habe Hunger. (ya da: Ich bin hungrig.)', 'Ich habe Hunger.'),
    examples: ['Ich **habe** Hunger.'],
  },
  {
    id: 'tr-seid-muede',
    type: 'translation',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'writing',
    difficulty: 2,
    source: l('Are you (pl., informal) tired?', 'Yorgun musunuz? (samimi çoğul)', 'Are you (pl., informal) tired?'),
    accepted: ['Seid ihr müde?'],
    explanation: l('Seid + ihr + müde?', 'Seid + ihr + müde?', 'Seid ihr müde?'),
    examples: ['**Seid** ihr müde?'],
  },
  {
    id: 'dialog-kino',
    type: 'dialogue',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Mia', de: 'Hast du Lust auf Kino?' }],
    options: ['Ja, gern! Ich habe Zeit.', 'Ja, gern! Ich bin Zeit.', 'Ja, gern! Ich habe müde.'],
    answer: 0,
    explanation: l('Zeit is a noun → haben.', 'Zeit isim → haben.', 'Zeit (Nomen) → haben.'),
    examples: ['Ich **habe** Zeit.'],
  },
  {
    id: 'dialog-krank',
    type: 'dialogue',
    topic: 'contrast',
    concept: 'sein-or-haben',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Chef', de: 'Wo ist Herr Kaya?' }],
    options: ['Er ist krank.', 'Er hat krank.', 'Er bist krank.'],
    answer: 0,
    explanation: l('er ist krank.', 'er ist krank.', 'er ist krank.'),
    examples: ['Er **ist** krank.'],
  },
  {
    id: 'mc-recht',
    type: 'multiple_choice',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'vocabulary',
    difficulty: 2,
    prompt: 'Du ___ Recht – das ist teuer!',
    options: ['hast', 'bist', 'habt'],
    answer: 0,
    explanation: l('Recht haben = to be right: du hast Recht.', 'Recht haben = haklı olmak: du hast Recht.', 'Recht haben: du hast Recht.'),
    examples: ['Du **hast** Recht.'],
  },

  // --- Reading ----------------------------------------------------------
  {
    id: 'read-tom',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tag',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie geht es Tom heute?',
    options: ['Er ist müde und krank.', 'Er ist glücklich.', 'Er hat Glück.'],
    answer: 0,
    explanation: l('„Tom ist müde. Er hat Kopfschmerzen …“', '„Tom ist müde. Er hat Kopfschmerzen …“', '„Tom ist müde …“'),
  },
  {
    id: 'read-hunger',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-tag',
    skill: 'reading',
    difficulty: 1,
    statement: 'Tom hat Hunger.',
    answer: false,
    explanation: l('„Er hat keinen Hunger, aber er hat Durst.“', '„Er hat keinen Hunger, aber er hat Durst.“', '„Er hat keinen Hunger, aber er hat Durst.“'),
  },
  {
    id: 'read-anna',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tag',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was macht Anna?',
    options: ['Sie bringt Tee und Suppe.', 'Sie ist auch krank.', 'Sie hat keine Zeit.'],
    answer: 0,
    explanation: l('„Seine Freundin Anna hat Zeit. Sie bringt Tee und Suppe.“', '„Seine Freundin Anna hat Zeit. Sie bringt Tee und Suppe.“', '„Sie bringt Tee und Suppe.“'),
  },
  {
    id: 'read-glueck',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tag',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum hat Tom Glück?',
    options: ['Er hat eine nette Freundin.', 'Er ist nicht krank.', 'Er hat frei.'],
    answer: 0,
    explanation: l('„Tom hat Glück – Anna ist sehr nett.“', '„Tom hat Glück – Anna ist sehr nett.“', '„Tom hat Glück – Anna ist sehr nett.“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-durst',
    type: 'listening_choice',
    topic: 'idioms',
    concept: 'haben-idiom',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich habe Durst. Hast du Wasser?',
    question: l('What does the person want?', 'Kişi ne istiyor?', 'Was möchte die Person?'),
    options: ['🥤 etwas trinken', '🍽️ etwas essen', '😴 schlafen'],
    answer: 0,
    explanation: l('Durst = thirst.', 'Durst = susuzluk.', 'Durst → trinken.'),
  },
  {
    id: 'listen-seid',
    type: 'listening_choice',
    topic: 'sein-forms',
    concept: 'sein-forms',
    skill: 'listening',
    difficulty: 2,
    audio: 'Seid ihr schon fertig?',
    question: l('Who is asked?', 'Kime soruluyor?', 'Wer wird gefragt?'),
    options: ['du', 'ihr', 'Sie'],
    answer: 1,
    explanation: l('„Seid ihr …?“', '„Seid ihr …?“', '„Seid ihr …?“'),
  },
  {
    id: 'listen-zeit',
    type: 'listening_choice',
    topic: 'haben-forms',
    concept: 'haben-forms',
    skill: 'listening',
    difficulty: 1,
    audio: 'Heute habe ich keine Zeit, aber morgen.',
    question: l('When does the person have time?', 'Kişinin ne zaman vakti var?', 'Wann hat die Person Zeit?'),
    options: ['heute', 'morgen', 'nie'],
    answer: 1,
    explanation: l('„… aber morgen.“', '„… aber morgen.“', '„… aber morgen.“'),
  },
  {
    id: 'listen-krank',
    type: 'listening_choice',
    topic: 'contrast',
    concept: 'sein-or-haben',
    skill: 'listening',
    difficulty: 1,
    audio: 'Meine Kinder sind krank. Sie haben Fieber.',
    question: l('Who is ill?', 'Kim hasta?', 'Wer ist krank?'),
    options: ['die Kinder', 'die Mutter', 'der Arzt'],
    answer: 0,
    explanation: l('„Meine Kinder sind krank.“', '„Meine Kinder sind krank.“', '„Meine Kinder sind krank.“'),
  },

  ...formDrills(),
]

export const UNIT10_HABEN_SEIN: CourseUnit = {
  level: 'A1',
  number: 10,
  slug: 'haben-sein',
  titleDe: 'Haben und Sein',
  title: l('To have and to be', 'Haben ve sein', 'Haben und Sein'),
  goal: l(
    'By the end of this unit you know all forms of sein and haben by heart and know which one to use – also in phrases like „Ich habe Hunger“.',
    'Bu ünitenin sonunda sein ve haben’in tüm biçimlerini ezbere bilir ve hangisini kullanacağını bilirsin – „Ich habe Hunger“ gibi kalıplarda da.',
    'Am Ende dieser Einheit kennst du alle Formen von sein und haben auswendig und weißt, welches Verb passt – auch in Wendungen wie „Ich habe Hunger“.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'sein-forms', label: l('sein: bin … seid', 'sein: bin … seid', 'sein: bin … seid') },
    { key: 'haben-forms', label: l('haben: habe … habt', 'haben: habe … habt', 'haben: habe … habt') },
    { key: 'contrast', label: l('sein or haben?', 'sein mi haben mı?', 'sein oder haben?') },
    { key: 'idioms', label: l('Hunger, Durst, Zeit …', 'Hunger, Durst, Zeit …', 'Hunger, Durst, Zeit …') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l(
        'Useful phrases with haben and sein. Notice: many feelings use haben in German.',
        'haben ve sein ile kullanışlı ifadeler. Dikkat: Almancada birçok his haben ile söylenir.',
        'Nützliche Wendungen mit haben und sein.'
      ),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('All forms', 'Tüm biçimler', 'Alle Formen'),
          body: l(
            'The two most important verbs – both irregular. Learn them as a song: bin – bist – ist – sind – seid – sind.',
            'En önemli iki fiil – ikisi de düzensiz. Şarkı gibi öğren: bin – bist – ist – sind – seid – sind.',
            'Die zwei wichtigsten Verben – beide unregelmäßig. Lerne sie wie ein Lied.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('sein', 'sein', 'sein'), l('haben', 'haben', 'haben')],
            rows: [
              ['ich', 'bin', 'habe'],
              ['du', 'bist', 'hast'],
              ['er / sie / es', 'ist', 'hat'],
              ['wir', 'sind', 'haben'],
              ['ihr', 'seid', 'habt'],
              ['sie / Sie', 'sind', 'haben'],
            ],
          },
          tip: l(
            'ihr seid (be) – seit (since). Same sound, different spelling.',
            'ihr seid (olmak) – seit (-den beri). Aynı ses, farklı yazım.',
            'ihr seid (sein) – seit (Präposition): gleicher Klang, andere Schreibung.'
          ),
        },
        {
          title: l('sein + adjective · haben + noun', 'sein + sıfat · haben + isim', 'sein + Adjektiv · haben + Nomen'),
          body: l(
            'sein describes: who/what/how someone is (müde, krank, Lehrer, zu Hause). haben possesses: a noun (Zeit, ein Auto, Hunger).',
            'sein tanımlar: biri kim/ne/nasıl (müde, krank, Lehrer, zu Hause). haben sahiplik bildirir: bir isim (Zeit, ein Auto, Hunger).',
            'sein beschreibt (müde, krank, Lehrer). haben besitzt ein Nomen (Zeit, ein Auto, Hunger).'
          ),
          table: {
            head: [l('sein', 'sein', 'sein'), l('haben', 'haben', 'haben')],
            rows: [
              ['Ich bin müde.', 'Ich habe Hunger.'],
              ['Er ist krank.', 'Er hat Fieber.'],
              ['Wir sind zu Hause.', 'Wir haben Zeit.'],
            ],
          },
        },
        {
          title: l('Feelings with haben', 'haben ile hisler', 'Gefühle mit haben'),
          body: l(
            'Where English and Turkish use „to be“ or a verb, German often uses haben + noun: Hunger haben (be hungry), Durst haben (be thirsty), Angst haben (be afraid), Recht haben (be right).',
            'İngilizce ve Türkçenin „olmak“ ya da bir fiil kullandığı yerde Almanca çoğu zaman haben + isim kullanır: Hunger haben (acıkmak), Durst haben (susamak), Angst haben (korkmak), Recht haben (haklı olmak).',
            'Hunger haben, Durst haben, Angst haben, Recht haben, Lust haben, Glück haben.'
          ),
          examples: [
            { de: 'Ich **habe** Hunger.', translation: l('I’m hungry.', 'Acıktım.', 'Hunger haben') },
            { de: '**Hast** du Lust auf Kino?', translation: l('Do you feel like the cinema?', 'Sinemaya gitmeye canın istiyor mu?', 'Lust haben') },
          ],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A phone call on Friday evening.', 'Cuma akşamı bir telefon görüşmesi.', 'Ein Telefonat am Freitagabend.'),
      dialogue: [
        { speaker: 'Mia', de: 'Hallo Tom! **Hast** du heute Abend Zeit?', translation: l('Hi Tom! Do you have time tonight?', 'Selam Tom! Bu akşam vaktin var mı?', '') },
        { speaker: 'Tom', de: 'Hm, ich **bin** sehr müde. Und ich **habe** Kopfschmerzen.', translation: l('Hm, I’m very tired. And I have a headache.', 'Hım, çok yorgunum. Ve başım ağrıyor.', '') },
        { speaker: 'Mia', de: 'Oh nein! **Bist** du krank?', translation: l('Oh no! Are you ill?', 'Olamaz! Hasta mısın?', '') },
        { speaker: 'Tom', de: 'Ich glaube, ja. Ich **habe** eine Erkältung.', translation: l('I think so. I have a cold.', 'Sanırım evet. Soğuk algınlığım var.', '') },
        { speaker: 'Mia', de: '**Hast** du Hunger? Ich bringe Suppe!', translation: l('Are you hungry? I’ll bring soup!', 'Acıktın mı? Çorba getiriyorum!', '') },
        { speaker: 'Tom', de: 'Danke, du **bist** so nett! Ich **habe** wirklich Glück.', translation: l('Thanks, you are so nice! I’m really lucky.', 'Teşekkürler, çok naziksin! Gerçekten şanslıyım.', '') },
      ],
      examples: [
        { de: 'Wir **sind** glücklich.', translation: l('We are happy.', 'Mutluyuz.', '') },
        { de: 'Ihr **seid** zu Hause.', translation: l('You (pl.) are at home.', 'Evdesiniz.', '') },
        { de: 'Sie **sind** Lehrer.', translation: l('They are teachers.', 'Onlar öğretmen.', '') },
        { de: 'Wir **haben** keine Zeit.', translation: l('We have no time.', 'Vaktimiz yok.', '') },
        { de: '**Habt** ihr Durst?', translation: l('Are you (pl.) thirsty?', 'Susadınız mı?', '') },
        { de: 'Das Kind **hat** Angst.', translation: l('The child is afraid.', 'Çocuk korkuyor.', '') },
        { de: 'Sie **haben** Recht.', translation: l('You are right. (formal)', 'Haklısınız.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('All forms – and when to use which verb.', 'Tüm biçimler – ve hangi fiilin ne zaman kullanılacağı.', 'Alle Formen – und wann welches Verb.'),
      exercises: ['img-hunger', 'sort-sein-haben', 'mc-seid', 'mc-habt', 'tf-bin-hunger', 'select-haben', 'match-sein', 'match-haben', 'sein-ihr'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Now say how you and others are.', 'Şimdi senin ve başkalarının nasıl olduğunu söyle.', 'Jetzt sagst du, wie es dir und anderen geht.'),
      exercises: [
        'fill-seid',
        'fill-hat',
        'fill-sind',
        'build-habt-zeit',
        'build-muede',
        'fix-bin-durst',
        'fix-seit',
        'fix-habe-muede',
        'tr-hunger',
        'tr-seid-muede',
        'dialog-kino',
        'dialog-krank',
        'mc-recht',
        'haben-ihr',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A bad day for Tom.', 'Tom için kötü bir gün.', 'Ein schlechter Tag für Tom.'),
      passage: [
        'Tom **ist** heute nicht glücklich. Er **ist** müde und **hat** Kopfschmerzen.',
        'Er **hat** keinen Hunger, aber er **hat** Durst.',
        'Seine Freundin Anna **hat** Zeit. Sie bringt Tee und Suppe.',
        'Tom **hat** Glück – Anna **ist** sehr nett.',
      ],
      glossary: [
        { de: 'keinen Hunger', note: l('not hungry (kein + masculine → keinen)', 'aç değil (kein + eril → keinen)', 'kein Hunger → keinen Hunger') },
        { de: 'bringen', note: l('to bring', 'getirmek', 'mitbringen') },
        { de: 'die Suppe', note: l('soup', 'çorba', 'Suppe') },
      ],
      exercises: ['read-tom', 'read-hunger', 'read-anna', 'read-glueck'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('How are they? Listen.', 'Nasıllar? Dinle.', 'Wie geht es ihnen? Hör zu.'),
      exercises: ['listen-durst', 'listen-seid', 'listen-zeit', 'listen-krank'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('How are you today? Talk about yourself and your family.', 'Bugün nasılsın? Kendinden ve ailenden bahset.', 'Wie geht es dir heute? Sprich über dich und deine Familie.'),
      points: [
        l('sein + adjective: „Ich bin … (müde / glücklich)“', 'sein + sıfat: „Ich bin … (müde / glücklich)“', 'sein + Adjektiv'),
        l('haben + noun: „Ich habe … (Hunger / Zeit)“', 'haben + isim: „Ich habe … (Hunger / Zeit)“', 'haben + Nomen'),
        l('Someone else: „Mein Bruder ist … / hat …“', 'Başka biri: „Mein Bruder ist … / hat …“', 'Eine andere Person'),
        l('A question: „Hast du / Habt ihr …?“', 'Bir soru: „Hast du / Habt ihr …?“', 'Eine Frage'),
      ],
      model: ['Heute bin ich glücklich, aber ein bisschen müde.', 'Ich habe Hunger!', 'Meine Kinder sind in der Schule.', 'Mein Mann hat heute keine Zeit.', 'Und du? Hast du Lust auf Kaffee?'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short message to a friend: how are you, what do you have, what do you feel like? (at least 4 sentences)',
        'Bir arkadaşına kısa bir mesaj yaz: nasılsın, neyin var, canın ne istiyor? (en az 4 cümle)',
        'Schreib eine kurze Nachricht an eine Freundin oder einen Freund (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('A form of sein', 'sein’in bir biçimi', 'Eine Form von sein'), pattern: '\\b(bin|bist|ist|sind|seid)\\b' },
        { label: l('A form of haben', 'haben’in bir biçimi', 'Eine Form von haben'), pattern: '\\b(habe|hast|hat|haben|habt)\\b' },
        { label: l('A phrase like Hunger / Zeit / Lust haben', 'Hunger / Zeit / Lust haben gibi bir kalıp', 'Eine Wendung wie Hunger / Zeit / Lust haben'), pattern: '\\b(Hunger|Durst|Zeit|Lust|Angst|Glück|Recht)\\b' },
      ],
      model: ['Hallo Lena!', 'Ich bin heute müde, aber glücklich.', 'Am Abend habe ich Zeit.', 'Hast du Lust auf Kino?', 'Mein Bruder ist auch zu Hause.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('All forms of sein and haben – 60 seconds.', 'sein ve haben’in tüm biçimleri – 60 saniye.', 'Alle Formen von sein und haben – 60 Sekunden.'),
      seconds: 60,
      pool: (['sein', 'haben'] as const).flatMap((verb) => (Object.keys(SEIN) as Person[]).map((p) => `${verb}-${p}`)),
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('sein: bin, bist, ist, sind, seid, sind', 'sein: bin, bist, ist, sind, seid, sind', 'sein: bin, bist, ist, sind, seid, sind'),
      l('haben: habe, hast, hat, haben, habt, haben', 'haben: habe, hast, hat, haben, habt, haben', 'haben: habe, hast, hat, haben, habt, haben'),
      l('sein + adjective, haben + noun', 'sein + sıfat, haben + isim', 'sein + Adjektiv, haben + Nomen'),
      l('Hunger, Durst, Zeit, Lust, Angst, Glück, Recht haben', 'Hunger, Durst, Zeit, Lust, Angst, Glück, Recht haben', 'Hunger, Durst, Zeit, Lust, Angst, Glück, Recht haben'),
    ],
    mistakes: [
      { wrong: 'Ich bin Hunger.', right: 'Ich habe Hunger.', note: l('Hunger → haben.', 'Hunger → haben.', 'Hunger → haben.') },
      { wrong: 'Ihr seit nett.', right: 'Ihr seid nett.', note: l('seid with d.', 'seid d ile.', 'seid mit d.') },
      { wrong: 'Er hat krank.', right: 'Er ist krank.', note: l('Adjective → sein.', 'Sıfat → sein.', 'Adjektiv → sein.') },
      { wrong: 'Ihr habet Zeit.', right: 'Ihr habt Zeit.', note: l('ihr habt', 'ihr habt', 'ihr habt') },
    ],
  },
}
