import type { CourseUnit, Exercise, Gender, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Markt', gender: 'm', plural: 'die Märkte', emoji: '🧺', translation: l('market', 'pazar', 'Markt'), example: 'Samstags kaufe ich auf dem Markt ein.' },
  { word: 'Kasse', gender: 'f', plural: 'die Kassen', emoji: '💳', translation: l('checkout, till', 'kasa', 'Kasse'), example: 'Bitte bezahlen Sie an der Kasse.' },
  { word: 'Kilo', gender: 'n', plural: 'die Kilo', emoji: '⚖️', translation: l('kilo', 'kilo', 'Kilo'), example: 'ein Kilo Äpfel' },
  { word: 'Liter', gender: 'm', plural: 'die Liter', emoji: '🥛', translation: l('litre', 'litre', 'Liter'), example: 'ein Liter Milch' },
  { word: 'Packung', gender: 'f', plural: 'die Packungen', emoji: '📦', translation: l('packet', 'paket', 'Packung'), example: 'eine Packung Reis' },
  { word: 'Dose', gender: 'f', plural: 'die Dosen', emoji: '🥫', translation: l('tin, can', 'konserve kutusu', 'Dose'), example: 'eine Dose Tomaten' },
  { word: 'Tüte', gender: 'f', plural: 'die Tüten', emoji: '🛍️', translation: l('bag (plastic/paper)', 'poşet', 'Tüte'), example: 'Brauchen Sie eine Tüte?' },
  { word: 'Angebot', gender: 'n', plural: 'die Angebote', emoji: '🏷️', translation: l('special offer', 'indirim, kampanya', 'Angebot'), example: 'Die Äpfel sind im Angebot.' },
  { word: 'Einkaufszettel', gender: 'm', plural: 'die Einkaufszettel', emoji: '📝', translation: l('shopping list', 'alışveriş listesi', 'Einkaufszettel'), example: 'Wo ist mein Einkaufszettel?' },
  { word: 'Wechselgeld', gender: 'n', emoji: '🪙', translation: l('change (money)', 'para üstü', 'Wechselgeld'), example: 'Hier ist Ihr Wechselgeld.' },
  { word: 'billig / teuer', emoji: '💸', translation: l('cheap / expensive', 'ucuz / pahalı', 'billig / teuer'), example: 'Das ist zu teuer!' },
  { word: 'Größe', gender: 'f', plural: 'die Größen', emoji: '📏', translation: l('size', 'beden', 'Größe'), example: 'Haben Sie das in Größe M?' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Gramm', gender: 'n', translation: l('gram', 'gram', 'Gramm') },
  { word: 'Käse', gender: 'm', translation: l('cheese', 'peynir', 'Käse') },
  { word: 'Apfel', gender: 'm', plural: 'die Äpfel', translation: l('apple', 'elma', 'Apfel') },
  { word: 'Tomate', gender: 'f', plural: 'die Tomaten', translation: l('tomato', 'domates', 'Tomate') },
  { word: 'Ei', gender: 'n', plural: 'die Eier', translation: l('egg', 'yumurta', 'Ei') },
  { word: 'Butter', gender: 'f', translation: l('butter', 'tereyağı', 'Butter') },
  { word: 'Pullover', gender: 'm', plural: 'die Pullover', translation: l('jumper', 'kazak', 'Pullover') },
  { word: 'Jacke', gender: 'f', plural: 'die Jacken', translation: l('jacket', 'ceket', 'Jacke') },
  { word: 'Hemd', gender: 'n', plural: 'die Hemden', translation: l('shirt', 'gömlek', 'Hemd') },
  { word: 'Was kostet …? / Wie viel kostet …?', translation: l('How much is …?', '… ne kadar?', 'Was kostet …?') },
  { word: 'Haben Sie …?', translation: l('Do you have …?', '… var mı?', 'Haben Sie …?') },
  { word: 'Das nehme ich.', translation: l('I’ll take it.', 'Bunu alıyorum.', 'Das nehme ich.') },
]

/** Quantity + product: ein Kilo Äpfel, ein Liter Milch … */
const QUANTITIES: [string, string, [string, string]][] = [
  ['ein Kilo', 'Äpfel', ['Milch', 'Wasser']],
  ['ein Liter', 'Milch', ['Käse', 'Brot']],
  ['200 Gramm', 'Käse', ['Wasser', 'Saft']],
  ['eine Dose', 'Tomaten', ['Brot', 'Eier']],
  ['eine Flasche', 'Wasser', ['Brot', 'Käse']],
  ['zehn', 'Eier', ['Milch', 'Butter']],
  ['eine Packung', 'Reis', ['Wasser', 'Eier']],
  ['ein Stück', 'Butter', ['Milch', 'Saft']],
]

function quantityDrills(): Exercise[] {
  return QUANTITIES.map(([quantity, product, wrong], i) => {
    const options = [product, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `menge-${i + 1}`,
      type: 'multiple_choice' as const,
      topic: 'quantities',
      concept: 'quantities',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `${quantity} ___`,
      options: ordered,
      answer: ordered.indexOf(product),
      explanation: l(
        `${quantity} ${product} – the product follows directly, without „of“.`,
        `${quantity} ${product} – ürün doğrudan arkadan gelir, „von“ yok.`,
        `${quantity} ${product} – ohne „von“.`
      ),
      examples: [`**${quantity} ${product}**`],
    }
  })
}

/** Den / Die / Das nehme ich – the pronoun follows the article (Akkusativ). */
const TAKE: [string, Gender | 'pl'][] = [
  ['Der Pullover', 'm'],
  ['Die Jacke', 'f'],
  ['Das Hemd', 'n'],
  ['Die Schuhe', 'pl'],
  ['Der Schal', 'm'],
  ['Das Kleid', 'n'],
]
const TAKE_PRONOUN: Record<Gender | 'pl', string> = { m: 'Den', f: 'Die', n: 'Das', pl: 'Die' }

function takeDrills(): Exercise[] {
  return TAKE.map(([noun, gender], i) => {
    const options = ['Den', 'Die', 'Das']
    const ordered = i % 2 === 0 ? options : [...options].reverse()
    const right = TAKE_PRONOUN[gender]
    return {
      id: `nehme-${i + 1}`,
      type: 'multiple_choice' as const,
      topic: 'take',
      concept: `take-${gender}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: `${noun} ${gender === 'pl' ? 'sind' : 'ist'} super! ___ nehme ich.`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `„${right} nehme ich“ – ${gender === 'm' ? 'masculine object → den (Akkusativ)' : 'feminine, neuter and plural stay the same'}.`,
        `„${right} nehme ich“ – ${gender === 'm' ? 'eril nesne → den (Akkusativ)' : 'dişil, nötr ve çoğul aynı kalır'}.`,
        `„${right} nehme ich“ – ${gender === 'm' ? 'maskulin → den' : 'bleibt gleich'}.`
      ),
      examples: [`**${right}** nehme ich.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise ----------------------------------------
  {
    id: 'img-dose',
    type: 'image_choice',
    topic: 'quantities',
    concept: 'containers',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'eine Dose Tomaten',
    options: [
      { emoji: '🥫', label: 'eine Dose' },
      { emoji: '📦', label: 'eine Packung' },
      { emoji: '🛍️', label: 'eine Tüte' },
      { emoji: '🍾', label: 'eine Flasche' },
    ],
    answer: 0,
    explanation: l('die Dose = tin/can.', 'die Dose = konserve kutusu.', 'die Dose.'),
    examples: ['**eine Dose** Tomaten'],
  },
  {
    id: 'match-phrases',
    type: 'matching',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('What do you say?', 'Ne dersin?', 'Was sagt man?'),
    pairs: [
      { left: l('You want to know the price.', 'Fiyatı öğrenmek istiyorsun.', 'Du willst den Preis wissen.'), right: 'Was kostet das?' },
      { left: l('You are looking for something.', 'Bir şey arıyorsun.', 'Du suchst etwas.'), right: 'Haben Sie …?' },
      { left: l('It costs too much.', 'Çok pahalı.', 'Es kostet zu viel.'), right: 'Das ist zu teuer.' },
      { left: l('You decide to buy it.', 'Almaya karar veriyorsun.', 'Du kaufst es.'), right: 'Das nehme ich.' },
    ].map((p) => ({ left: p.right, right: p.left })),
    explanation: l(
      'The four key shopping phrases: Was kostet das? · Haben Sie …? · Das ist zu teuer. · Das nehme ich.',
      'Dört temel alışveriş ifadesi: Was kostet das? · Haben Sie …? · Das ist zu teuer. · Das nehme ich.',
      'Was kostet das? · Haben Sie …? · Das ist zu teuer. · Das nehme ich.'
    ),
  },
  {
    id: 'mc-kostet',
    type: 'multiple_choice',
    topic: 'prices',
    concept: 'price-question',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Was ___ die Äpfel?',
    options: ['kosten', 'kostet', 'kostest'],
    answer: 0,
    explanation: l('die Äpfel (plural) → kosten. der Käse (singular) → kostet.', 'die Äpfel (çoğul) → kosten. der Käse (tekil) → kostet.', 'Plural → kosten.'),
    examples: ['Was **kosten** die Äpfel?', 'Was **kostet** der Käse?'],
    practice: ['fill-kostet'],
  },
  {
    id: 'mc-haben-sie',
    type: 'multiple_choice',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Haben Sie ___ Pullover in Größe L?',
    options: ['diesen', 'dieser', 'dieses'],
    answer: 0,
    explanation: l(
      'haben + Akkusativ: der Pullover → diesen Pullover (like den).',
      'haben + Akkusativ: der Pullover → diesen Pullover (den gibi).',
      'der Pullover → diesen Pullover.'
    ),
    examples: ['Haben Sie **diesen** Pullover in L?'],
  },
  {
    id: 'sort-singular-plural',
    type: 'categorize',
    topic: 'prices',
    concept: 'price-question',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('kostet or kosten?', 'kostet mi kosten mi?', 'kostet oder kosten?'),
    categories: ['kostet', 'kosten'],
    items: [
      { text: 'der Käse', category: 0 },
      { text: 'die Äpfel', category: 1 },
      { text: 'das Brot', category: 0 },
      { text: 'die Eier', category: 1 },
      { text: 'die Jacke', category: 0 },
      { text: 'die Schuhe', category: 1 },
    ],
    explanation: l('Singular → kostet. Plural → kosten. (die Jacke = singular!)', 'Tekil → kostet. Çoğul → kosten. (die Jacke = tekil!)', 'Singular → kostet, Plural → kosten.'),
  },
  {
    id: 'tf-zu-teuer',
    type: 'true_false',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'reading',
    difficulty: 1,
    statement: '„Das ist mir zu teuer.“ heißt: Ich kaufe es.',
    answer: false,
    explanation: l('zu teuer = too expensive → you don’t buy it.', 'zu teuer = çok pahalı → almıyorsun.', 'zu teuer → man kauft es nicht.'),
  },
  {
    id: 'select-quantities',
    type: 'multiple_select',
    topic: 'quantities',
    concept: 'quantities',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which combinations are correct? Select all.', 'Hangi kombinasyonlar doğru? Hepsini seç.', 'Welche Kombinationen sind richtig? Wähle alle.'),
    options: ['ein Liter Milch', 'ein Liter Brot', 'ein Kilo Kartoffeln', 'ein Kilo Wasser', '200 Gramm Schinken'],
    answers: [0, 2, 4],
    explanation: l('Liquids → Liter. Fruit/vegetables → Kilo. Cheese/ham → Gramm.', 'Sıvılar → Liter. Meyve/sebze → Kilo. Peynir/jambon → Gramm.', 'Flüssig → Liter, Obst/Gemüse → Kilo, Käse/Schinken → Gramm.'),
  },
  {
    id: 'ordering-einkauf',
    type: 'ordering',
    topic: 'phrases',
    concept: 'shopping-flow',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the market conversation in order.', 'Pazar konuşmasını sıraya koy.', 'Bring das Gespräch auf dem Markt in die richtige Reihenfolge.'),
    items: ['Das macht 3,40 Euro.', 'Guten Tag! Was darf es sein?', 'Ich hätte gern ein Kilo Äpfel.', 'Sonst noch etwas? – Nein, danke.'],
    answer: ['Guten Tag! Was darf es sein?', 'Ich hätte gern ein Kilo Äpfel.', 'Sonst noch etwas? – Nein, danke.', 'Das macht 3,40 Euro.'],
    explanation: l(
      'Greeting → order → „Anything else?“ → price.',
      'Selam → sipariş → „Başka bir şey?“ → fiyat.',
      'Begrüßung → Bestellung → Sonst noch etwas? → Preis.'
    ),
  },

  // --- Simulation: at the market and in the shop ----------------------
  {
    id: 'sim-1-markt',
    type: 'dialogue',
    topic: 'quantities',
    concept: 'quantities',
    skill: 'grammar',
    difficulty: 1,
    visual: ['🍎 🧀 🥚 🍅', '. 🧺 . .'],
    lines: [{ speaker: 'Verkäufer', de: 'Guten Morgen! Was darf es sein?' }],
    options: ['Ich hätte gern ein Kilo Äpfel.', 'Ich hätte gern ein Kilo von Äpfel.', 'Ich bin ein Kilo Äpfel.'],
    answer: 0,
    explanation: l('Quantity + product, no „von“: ein Kilo Äpfel.', 'Miktar + ürün, „von“ yok: ein Kilo Äpfel.', 'ein Kilo Äpfel – ohne „von“.'),
    examples: ['Ich hätte gern **ein Kilo Äpfel**.'],
  },
  {
    id: 'sim-2-kaese',
    type: 'dialogue',
    topic: 'quantities',
    concept: 'quantities',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Verkäufer', de: 'Gern. Sonst noch etwas?' }],
    options: ['Ja, 200 Gramm Käse, bitte.', 'Ja, 200 Gramm Käse ist.', 'Nein, zu teuer Käse.'],
    answer: 0,
    explanation: l('„Sonst noch etwas?“ = Anything else? → order the next thing.', '„Sonst noch etwas?“ = Başka bir şey? → sıradaki şeyi sipariş et.', 'Sonst noch etwas? → nächste Bestellung.'),
  },
  {
    id: 'sim-3-preis',
    type: 'dialogue',
    topic: 'prices',
    concept: 'price-question',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Du', de: '(Du möchtest den Preis wissen.)' }],
    options: ['Was kostet das zusammen?', 'Wie geht es Ihnen?', 'Das nehme ich.'],
    answer: 0,
    explanation: l('Was kostet das (zusammen)? = How much is it (altogether)?', 'Was kostet das (zusammen)? = (Toplam) ne kadar?', 'Was kostet das zusammen?'),
  },
  {
    id: 'sim-4-laden',
    type: 'dialogue',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'grammar',
    difficulty: 1,
    visual: ['👕 👖 🧥 👗'],
    lines: [{ speaker: 'Verkäuferin', de: 'Hallo! Kann ich Ihnen helfen?' }],
    options: ['Ja, ich suche einen Pullover.', 'Ja, ich suche ein Pullover.', 'Ja, ich bin einen Pullover.'],
    answer: 0,
    explanation: l('suchen + Akkusativ: der Pullover → einen Pullover.', 'suchen + Akkusativ: der Pullover → einen Pullover.', 'einen Pullover.'),
    examples: ['Ich suche {m:einen Pullover}.'],
  },
  {
    id: 'sim-5-groesse',
    type: 'dialogue',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Verkäuferin', de: 'Welche Größe brauchen Sie?' }],
    options: ['Größe M, bitte.', 'Rot, bitte.', 'Zwanzig Euro.'],
    answer: 0,
    explanation: l('Größe = size: S, M, L … or numbers (38, 40).', 'Größe = beden: S, M, L … ya da numara (38, 40).', 'Größe: S, M, L …'),
  },
  {
    id: 'sim-6-teuer',
    type: 'dialogue',
    topic: 'prices',
    concept: 'too-expensive',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Verkäuferin', de: 'Dieser Pullover kostet 89 Euro.' }],
    options: ['Oh, das ist mir zu teuer. Haben Sie etwas Billigeres?', 'Oh, das ist mir zu billig.', 'Oh, ich bin zu teuer.'],
    answer: 0,
    explanation: l(
      '„Das ist mir zu teuer“ = it’s too expensive for me. „etwas Billigeres“ = something cheaper.',
      '„Das ist mir zu teuer“ = bana çok pahalı. „etwas Billigeres“ = daha ucuz bir şey.',
      'zu teuer – etwas Billigeres.'
    ),
  },
  {
    id: 'sim-7-nehmen',
    type: 'dialogue',
    topic: 'take',
    concept: 'take-m',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Verkäuferin', de: 'Dieser hier ist im Angebot – nur 39 Euro.' }],
    options: ['Super, den nehme ich!', 'Super, der nehme ich!', 'Super, ich nehme!'],
    answer: 0,
    explanation: l(
      'der Pullover is the object → den nehme ich (Akkusativ). „Ich nehme“ alone needs an object.',
      'der Pullover nesnedir → den nehme ich (Akkusativ). „Ich nehme“ tek başına nesne ister.',
      'den nehme ich (Akkusativ).'
    ),
    examples: ['**Den** nehme ich!'],
  },

  // --- Practice 2: use ------------------------------------------------
  {
    id: 'fill-kostet',
    type: 'fill_blank',
    topic: 'prices',
    concept: 'price-question',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wie viel ___ die Jacke?',
    accepted: ['kostet'],
    base: 'kosten',
    explanation: l('die Jacke (singular) → kostet.', 'die Jacke (tekil) → kostet.', 'Singular → kostet.'),
    examples: ['Wie viel **kostet** die Jacke?'],
  },
  {
    id: 'fill-liter',
    type: 'fill_blank',
    topic: 'quantities',
    concept: 'quantities',
    skill: 'vocabulary',
    difficulty: 1,
    sentence: 'Ich brauche einen ___ Milch.',
    accepted: ['Liter'],
    explanation: l('Milk is measured in Liter: einen Liter Milch (der Liter → einen, Akkusativ).', 'Süt litre ile ölçülür: einen Liter Milch (der Liter → einen, Akkusativ).', 'einen Liter Milch.'),
    examples: ['Ich brauche **einen Liter** Milch.'],
  },
  {
    id: 'build-haben-sie',
    type: 'sentence_builder',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'grammar',
    difficulty: 1,
    chips: ['Sie', 'die Jacke', 'in Blau', 'Haben'],
    answers: [['Haben', 'Sie', 'die Jacke', 'in Blau']],
    end: '?',
    translation: l('Do you have the jacket in blue?', 'Ceketin mavisi var mı?', 'Haben Sie die Jacke in Blau?'),
    explanation: l('Haben Sie + product + in + colour?', 'Haben Sie + ürün + in + renk?', 'Haben Sie … in Blau?'),
    examples: ['**Haben Sie** die Jacke in Blau?'],
  },
  {
    id: 'build-zu-teuer',
    type: 'sentence_builder',
    topic: 'prices',
    concept: 'too-expensive',
    skill: 'grammar',
    difficulty: 1,
    chips: ['zu teuer', 'ist', 'Das'],
    answers: [['Das', 'ist', 'zu teuer']],
    translation: l('That is too expensive.', 'Bu çok pahalı.', 'Das ist zu teuer.'),
    explanation: l('Das + ist + zu teuer.', 'Das + ist + zu teuer.', 'Das ist zu teuer.'),
    examples: ['Das ist **zu teuer**.'],
  },
  {
    id: 'fix-von',
    type: 'error_correction',
    topic: 'quantities',
    concept: 'quantities',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich kaufe ein Kilo von Kartoffeln.',
    accepted: ['Ich kaufe ein Kilo Kartoffeln.'],
    explanation: l('No „von“ after quantities.', 'Miktarlardan sonra „von“ yok.', 'Ohne „von“.'),
    examples: ['Ich kaufe **ein Kilo Kartoffeln**.'],
  },
  {
    id: 'fix-der-nehme',
    type: 'error_correction',
    topic: 'take',
    concept: 'take-m',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Mantel ist schön. Der nehme ich.',
    accepted: ['Der Mantel ist schön. Den nehme ich.', 'Den nehme ich.'],
    explanation: l('der Mantel is the object → Den nehme ich.', 'der Mantel nesne → Den nehme ich.', 'Objekt → Den nehme ich.'),
    examples: ['**Den** nehme ich.'],
  },
  {
    id: 'tr-was-kostet',
    type: 'translation',
    topic: 'prices',
    concept: 'price-question',
    skill: 'writing',
    difficulty: 1,
    source: l('How much is the cheese?', 'Peynir ne kadar?', 'How much is the cheese?'),
    accepted: ['Was kostet der Käse?', 'Wie viel kostet der Käse?'],
    explanation: l('Was / Wie viel kostet der Käse?', 'Was / Wie viel kostet der Käse?', 'Was kostet der Käse?'),
    examples: ['**Was kostet** der Käse?'],
  },
  {
    id: 'tr-nehme',
    type: 'translation',
    topic: 'take',
    concept: 'take-n',
    skill: 'writing',
    difficulty: 2,
    source: l('I’ll take the shirt.', 'Gömleği alıyorum.', 'I’ll take the shirt.'),
    accepted: ['Ich nehme das Hemd.', 'Das Hemd nehme ich.'],
    explanation: l('nehmen + Akkusativ: das Hemd (no change).', 'nehmen + Akkusativ: das Hemd (değişmez).', 'Ich nehme das Hemd.'),
    examples: ['Ich **nehme** das Hemd.'],
  },

  // --- Reading -------------------------------------------------------
  {
    id: 'read-angebot',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-prospekt',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was kostet ein Kilo Äpfel?',
    options: ['1,99 €', '0,99 €', '2,49 €'],
    answer: 0,
    explanation: l('„Äpfel – 1 kg nur 1,99 €“', '„Äpfel – 1 kg nur 1,99 €“', '„1 kg nur 1,99 €“'),
  },
  {
    id: 'read-milch',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-prospekt',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie viel kostet die Milch?',
    options: ['1,19 € pro Liter', '1,99 € pro Kilo', '0,89 € pro Packung'],
    answer: 0,
    explanation: l('„Milch – 1 Liter 1,19 €“', '„Milch – 1 Liter 1,19 €“', '„1 Liter 1,19 €“'),
  },
  {
    id: 'read-sonntag',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-prospekt',
    skill: 'reading',
    difficulty: 2,
    statement: 'Der Supermarkt ist am Sonntag geöffnet.',
    answer: false,
    explanation: l('„Mo–Sa 7–21 Uhr“ – closed on Sunday.', '„Mo–Sa 7–21 Uhr“ – pazar kapalı.', 'Sonntag geschlossen.'),
  },
  {
    id: 'read-guenstig',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-prospekt',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist diese Woche im Angebot?',
    options: ['Äpfel und Käse', 'Brot und Wasser', 'Fleisch und Fisch'],
    answer: 0,
    explanation: l('„Angebote der Woche: Äpfel … Gouda …“', '„Angebote der Woche: Äpfel … Gouda …“', '„Angebote der Woche“'),
  },

  // --- Listening ------------------------------------------------------
  {
    id: 'listen-preis',
    type: 'listening_choice',
    topic: 'prices',
    concept: 'price-question',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das macht zusammen elf Euro fünfzig.',
    question: l('How much is it?', 'Ne kadar tutuyor?', 'Wie viel kostet es?'),
    options: ['11,50 €', '15,10 €', '50,11 €'],
    answer: 0,
    explanation: l('elf Euro fünfzig = 11,50 €.', 'elf Euro fünfzig = 11,50 €.', '11,50 €.'),
  },
  {
    id: 'listen-menge',
    type: 'listening_choice',
    topic: 'quantities',
    concept: 'quantities',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich hätte gern zwei Kilo Kartoffeln und sechs Eier.',
    question: l('How many eggs?', 'Kaç yumurta?', 'Wie viele Eier?'),
    options: ['2', '6', '10'],
    answer: 1,
    explanation: l('„sechs Eier“', '„sechs Eier“', '„sechs Eier“'),
  },
  {
    id: 'listen-teuer',
    type: 'listening_choice',
    topic: 'prices',
    concept: 'too-expensive',
    skill: 'listening',
    difficulty: 2,
    audio: 'Neunundsechzig Euro? Nein, das ist mir zu teuer.',
    question: l('Does the person buy it?', 'Kişi alıyor mu?', 'Kauft die Person es?'),
    options: ['Ja', 'Nein'],
    answer: 1,
    explanation: l('„zu teuer“ → no.', '„zu teuer“ → hayır.', '„zu teuer“ → nein.'),
  },
  {
    id: 'listen-tuete',
    type: 'listening_choice',
    topic: 'phrases',
    concept: 'shopping-phrases',
    skill: 'listening',
    difficulty: 1,
    audio: 'Brauchen Sie eine Tüte? – Nein, danke. Ich habe eine Tasche.',
    question: l('Does the customer take a bag?', 'Müşteri poşet alıyor mu?', 'Nimmt der Kunde eine Tüte?'),
    options: ['Ja', 'Nein'],
    answer: 1,
    explanation: l('„Nein, danke.“', '„Nein, danke.“', '„Nein, danke.“'),
  },

  ...quantityDrills(),
  ...takeDrills(),
]

export const UNIT21_EINKAUFEN: CourseUnit = {
  level: 'A1',
  number: 21,
  slug: 'einkaufen',
  titleDe: 'Einkaufen',
  title: l('Shopping', 'Alışveriş', 'Einkaufen'),
  goal: l(
    'By the end of this unit you can shop at the market and in a clothes shop: ask for prices and sizes, buy quantities, say „too expensive“ and „I’ll take it“.',
    'Bu ünitenin sonunda pazarda ve giyim mağazasında alışveriş yapabilirsin: fiyat ve beden sorabilir, miktar belirterek alabilir, „çok pahalı“ ve „bunu alıyorum“ diyebilirsin.',
    'Am Ende dieser Einheit kaufst du auf dem Markt und im Geschäft ein: nach Preis und Größe fragen, Mengen kaufen, „zu teuer“ und „Das nehme ich“.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'phrases', label: l('Shopping phrases', 'Alışveriş ifadeleri', 'Einkaufsdialoge') },
    { key: 'quantities', label: l('ein Kilo, ein Liter …', 'ein Kilo, ein Liter …', 'ein Kilo, ein Liter …') },
    { key: 'prices', label: l('Prices', 'Fiyatlar', 'Preise') },
    { key: 'take', label: l('Den / Die / Das nehme ich', 'Den / Die / Das nehme ich', 'Den / Die / Das nehme ich') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Words for the market, the supermarket and shops.', 'Pazar, süpermarket ve mağazalar için kelimeler.', 'Wörter für Markt, Supermarkt und Geschäfte.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Four key phrases', 'Dört temel ifade', 'Vier wichtige Sätze'),
          body: l(
            'With these four sentences you can manage almost any shopping situation.',
            'Bu dört cümleyle neredeyse her alışveriş durumunu idare edebilirsin.',
            'Mit diesen vier Sätzen schaffst du fast jede Einkaufssituation.'
          ),
          table: {
            head: [l('phrase', 'ifade', 'Satz'), l('meaning', 'anlam', 'Bedeutung')],
            rows: [
              ['Was kostet das? / Wie viel kostet …?', '💶 ?'],
              ['Haben Sie … (in Größe M / in Blau)?', '🔎'],
              ['Das ist (mir) zu teuer.', '💸 ✗'],
              ['Das nehme ich. / Den nehme ich.', '🛍️ ✓'],
            ],
          },
        },
        {
          title: l('Quantities', 'Miktarlar', 'Mengenangaben'),
          body: l(
            'Quantity + product, without „of“: ein Kilo Äpfel, ein Liter Milch, 200 Gramm Käse, eine Dose Tomaten, eine Packung Reis, zehn Eier.',
            'Miktar + ürün, „von“ olmadan: ein Kilo Äpfel, ein Liter Milch, 200 Gramm Käse, eine Dose Tomaten, eine Packung Reis, zehn Eier.',
            'Menge + Produkt, ohne „von“.'
          ),
          tip: l(
            'Kilo, Liter and Gramm don’t change in the plural: zwei Kilo, drei Liter, 500 Gramm.',
            'Kilo, Liter ve Gramm çoğulda değişmez: zwei Kilo, drei Liter, 500 Gramm.',
            'zwei Kilo, drei Liter, 500 Gramm – ohne Plural.'
          ),
        },
        {
          title: l('kostet or kosten?', 'kostet mi kosten mi?', 'kostet oder kosten?'),
          body: l(
            'One thing → kostet (Der Käse kostet 3 Euro). Several → kosten (Die Äpfel kosten 2 Euro).',
            'Tek şey → kostet (Der Käse kostet 3 Euro). Birden fazla → kosten (Die Äpfel kosten 2 Euro).',
            'Singular → kostet, Plural → kosten.'
          ),
        },
        {
          title: l('Den nehme ich!', 'Den nehme ich!', 'Den nehme ich!'),
          body: l(
            'To refer back to the thing: der → den (Akkusativ), die → die, das → das, plural → die. Den/Die/Das often goes to position 1 for emphasis.',
            'Söz konusu şeye geri dönmek için: der → den (Akkusativ), die → die, das → das, çoğul → die. Vurgu için Den/Die/Das sıkça 1. sıraya gelir.',
            'der → den, die → die, das → das (Akkusativ).'
          ),
          examples: [
            { de: 'Der Pullover ist schön. **Den** nehme ich.', translation: l('The jumper is nice. I’ll take it.', 'Kazak güzel. Onu alıyorum.', 'der → den') },
            { de: 'Die Jacke ist zu teuer. **Die** nehme ich nicht.', translation: l('The jacket is too expensive. I won’t take it.', 'Ceket çok pahalı. Onu almıyorum.', 'die → die') },
          ],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Saturday morning at the market.', 'Cumartesi sabahı pazarda.', 'Samstagmorgen auf dem Markt.'),
      dialogue: [
        { speaker: 'Verkäuferin', de: 'Guten Morgen! **Was darf es sein?**', translation: l('Good morning! What can I get you?', 'Günaydın! Ne arzu edersiniz?', '') },
        { speaker: 'Kemal', de: 'Ich hätte gern **ein Kilo Tomaten**. **Was kosten** die Tomaten?', translation: l('I’d like a kilo of tomatoes. How much are the tomatoes?', 'Bir kilo domates istiyorum. Domatesler ne kadar?', '') },
        { speaker: 'Verkäuferin', de: 'Ein Kilo **kostet** 2,80 Euro. Sonst noch etwas?', translation: l('One kilo is €2.80. Anything else?', 'Bir kilo 2,80 avro. Başka bir şey?', '') },
        { speaker: 'Kemal', de: '**Haben Sie** auch Erdbeeren?', translation: l('Do you also have strawberries?', 'Çilek de var mı?', '') },
        { speaker: 'Verkäuferin', de: 'Ja, die sind heute **im Angebot**: 500 Gramm für 3 Euro.', translation: l('Yes, they’re on offer today: 500 g for €3.', 'Evet, bugün indirimde: 500 gram 3 avro.', '') },
        { speaker: 'Kemal', de: 'Super, **die nehme ich**. **Was kostet das zusammen?**', translation: l('Great, I’ll take them. How much is it altogether?', 'Süper, onları alıyorum. Toplam ne kadar?', '') },
        { speaker: 'Verkäuferin', de: 'Das macht 5,80 Euro. Brauchen Sie **eine Tüte**?', translation: l('That’s €5.80. Do you need a bag?', '5,80 avro. Poşet ister misiniz?', '') },
      ],
      examples: [
        { de: '**Was kostet** der Käse?', translation: l('How much is the cheese?', 'Peynir ne kadar?', '') },
        { de: 'Die Äpfel **kosten** zwei Euro.', translation: l('The apples cost two euros.', 'Elmalar iki avro.', '') },
        { de: 'Ich hätte gern **ein Kilo** Äpfel.', translation: l('I’d like a kilo of apples.', 'Bir kilo elma istiyorum.', '') },
        { de: '**Haben Sie** die Jacke in Größe M?', translation: l('Do you have the jacket in size M?', 'Ceketin M bedeni var mı?', '') },
        { de: 'Das ist mir **zu teuer**.', translation: l('That’s too expensive for me.', 'Bu bana çok pahalı.', '') },
        { de: 'Der Pullover gefällt mir. **Den nehme ich**.', translation: l('I like the jumper. I’ll take it.', 'Kazağı beğendim. Onu alıyorum.', '') },
        { de: 'Kann ich mit Karte bezahlen?', translation: l('Can I pay by card?', 'Kartla ödeyebilir miyim?', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Phrases, quantities and prices.', 'İfadeler, miktarlar ve fiyatlar.', 'Sätze, Mengen und Preise.'),
      exercises: ['img-dose', 'match-phrases', 'mc-kostet', 'mc-haben-sie', 'sort-singular-plural', 'tf-zu-teuer', 'select-quantities', 'ordering-einkauf', 'menge-1'],
    },
    {
      key: 'simulation',
      kind: 'practice',
      title: l('Simulation · Shopping', 'Simülasyon · Alışveriş', 'Simulation · Einkaufen'),
      intro: l(
        'First the market, then a clothes shop. You are the customer – answer step by step.',
        'Önce pazar, sonra bir giyim mağazası. Müşteri sensin – adım adım cevap ver.',
        'Erst der Markt, dann ein Kleidungsgeschäft. Du bist die Kundin / der Kunde.'
      ),
      exercises: ['sim-1-markt', 'sim-2-kaese', 'sim-3-preis', 'sim-4-laden', 'sim-5-groesse', 'sim-6-teuer', 'sim-7-nehmen'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Now write and build shopping sentences.', 'Şimdi alışveriş cümleleri yaz ve kur.', 'Jetzt schreibst und baust du Einkaufssätze.'),
      exercises: ['fill-kostet', 'fill-liter', 'build-haben-sie', 'build-zu-teuer', 'fix-von', 'fix-der-nehme', 'tr-was-kostet', 'tr-nehme', 'nehme-1', 'nehme-2', 'menge-3'],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A supermarket flyer.', 'Bir süpermarket broşürü.', 'Ein Prospekt vom Supermarkt.'),
      passage: [
        '**FrischMarkt** – Angebote der Woche!',
        'Äpfel – 1 kg nur 1,99 € · Gouda – 200 g nur 1,49 €',
        'Milch – 1 Liter 1,19 € · Brot – 500 g 2,29 €',
        'Öffnungszeiten: Mo–Sa 7–21 Uhr',
      ],
      glossary: [
        { de: 'Angebote der Woche', note: l('this week’s offers', 'haftanın indirimleri', 'günstig diese Woche') },
        { de: 'nur', note: l('only', 'sadece', 'bloß') },
        { de: 'kg / g', note: l('Kilo / Gramm', 'kilo / gram', 'Kilogramm / Gramm') },
      ],
      exercises: ['read-angebot', 'read-milch', 'read-sonntag', 'read-guenstig'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('At the till and at the market stall.', 'Kasada ve pazar tezgâhında.', 'An der Kasse und am Marktstand.'),
      exercises: ['listen-preis', 'listen-menge', 'listen-teuer', 'listen-tuete'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Role play: buy three things at the market – then a jumper.', 'Canlandırma: pazardan üç şey al – sonra bir kazak.', 'Rollenspiel: Kauf drei Dinge auf dem Markt – dann einen Pullover.'),
      points: [
        l('Order with quantities: „Ich hätte gern ein Kilo …“', 'Miktarla sipariş ver: „Ich hätte gern ein Kilo …“', 'Mit Mengen bestellen'),
        l('Ask the price: „Was kostet …?“', 'Fiyat sor: „Was kostet …?“', 'Nach dem Preis fragen'),
        l('In the shop: size, „zu teuer“, „Den nehme ich.“', 'Mağazada: beden, „zu teuer“, „Den nehme ich.“', 'Im Geschäft: Größe, zu teuer, Den nehme ich.'),
      ],
      model: ['Guten Tag! Ich hätte gern ein Kilo Äpfel und 200 Gramm Käse.', 'Was kostet das zusammen?', 'Haben Sie diesen Pullover in Größe L?', 'Das ist mir zu teuer. Haben Sie etwas Billigeres?', 'Super, den nehme ich!'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write your shopping list as sentences – with quantities and one question (at least 4 sentences).',
        'Alışveriş listeni cümleler halinde yaz – miktarlarla ve bir soruyla (en az 4 cümle).',
        'Schreib deinen Einkaufszettel als Sätze – mit Mengen und einer Frage (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('Quantities (Kilo, Liter, Gramm …)', 'Miktarlar (Kilo, Liter, Gramm …)', 'Mengen (Kilo, Liter, Gramm …)'), pattern: '\\b(Kilo|Liter|Gramm|Dose|Packung|Flasche|Stück)\\b' },
        { label: l('A price question', 'Bir fiyat sorusu', 'Eine Preisfrage'), pattern: '\\b(kostet|kosten)\\b[^.!?]*\\?' },
        { label: l('brauche / möchte / hätte gern / kaufe', 'brauche / möchte / hätte gern / kaufe', 'brauche / möchte / hätte gern / kaufe'), pattern: '\\b(brauche|möchte|kaufe)\\b|hätte gern' },
      ],
      model: ['Heute brauche ich ein Kilo Kartoffeln.', 'Ich kaufe auch einen Liter Milch und zehn Eier.', 'Ich möchte 200 Gramm Käse.', 'Was kostet das Brot?'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Quantities and „den / die / das“ – 60 seconds.', 'Miktarlar ve „den / die / das“ – 60 saniye.', 'Mengen und „den / die / das“ – 60 Sekunden.'),
      seconds: 60,
      pool: [...QUANTITIES.map((_, i) => `menge-${i + 1}`), ...TAKE.map((_, i) => `nehme-${i + 1}`)],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Was kostet …? · Haben Sie …? · zu teuer · Das nehme ich.', 'Was kostet …? · Haben Sie …? · zu teuer · Das nehme ich.', 'Was kostet …? · Haben Sie …? · zu teuer · Das nehme ich.'),
      l('Quantities: ein Kilo, ein Liter, 200 Gramm, eine Dose', 'Miktarlar: ein Kilo, ein Liter, 200 Gramm, eine Dose', 'Mengen: ein Kilo, ein Liter, 200 Gramm'),
      l('kostet (singular) – kosten (plural)', 'kostet (tekil) – kosten (çoğul)', 'kostet – kosten'),
      l('Den / Die / Das nehme ich.', 'Den / Die / Das nehme ich.', 'Den / Die / Das nehme ich.'),
    ],
    mistakes: [
      { wrong: 'ein Kilo von Äpfeln', right: 'ein Kilo Äpfel', note: l('No „von“.', '„von“ yok.', 'Ohne „von“.') },
      { wrong: 'Was kostet die Äpfel?', right: 'Was kosten die Äpfel?', note: l('Plural → kosten.', 'Çoğul → kosten.', 'Plural → kosten.') },
      { wrong: 'Der nehme ich.', right: 'Den nehme ich.', note: l('Object → den.', 'Nesne → den.', 'Objekt → den.') },
      { wrong: 'Das ist zu billig für mich.', right: 'Das ist mir zu teuer.', note: l('zu teuer = too expensive.', 'zu teuer = çok pahalı.', 'zu teuer.') },
    ],
  },
}
