import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'links', emoji: '⬅️', translation: l('left', 'sol', 'links'), example: 'Gehen Sie links.' },
  { word: 'rechts', emoji: '➡️', translation: l('right', 'sağ', 'rechts'), example: 'Die Bank ist rechts.' },
  { word: 'geradeaus', emoji: '⬆️', translation: l('straight on', 'dümdüz', 'geradeaus'), example: 'Gehen Sie immer geradeaus.' },
  { word: 'hier', emoji: '📍', translation: l('here', 'burada', 'hier'), example: 'Die Post ist hier.' },
  { word: 'dort', emoji: '👉', translation: l('there', 'orada', 'dort'), example: 'Der Bahnhof ist dort.' },
  { word: 'Ampel', gender: 'f', plural: 'die Ampeln', emoji: '🚦', translation: l('traffic light', 'trafik lambası', 'Ampel'), example: 'An der Ampel gehen Sie rechts.' },
  { word: 'Kreuzung', gender: 'f', plural: 'die Kreuzungen', emoji: '🔀', translation: l('crossroads', 'kavşak', 'Kreuzung'), example: 'An der Kreuzung links.' },
  { word: 'Straße', gender: 'f', plural: 'die Straßen', emoji: '🛣️', translation: l('street', 'sokak, cadde', 'Straße'), example: 'Nehmen Sie die erste Straße rechts.' },
  { word: 'Haltestelle', gender: 'f', plural: 'die Haltestellen', emoji: '🚏', translation: l('(bus) stop', 'durak', 'Haltestelle'), example: 'Die Haltestelle ist dort.' },
  { word: 'Ecke', gender: 'f', plural: 'die Ecken', emoji: '↪️', translation: l('corner', 'köşe', 'Ecke'), example: 'Die Apotheke ist um die Ecke.' },
  { word: 'weit / nah', emoji: '📏', translation: l('far / near', 'uzak / yakın', 'weit / nah'), example: 'Ist es weit? – Nein, ganz nah.' },
  { word: 'gegenüber', emoji: '↔️', translation: l('opposite', 'karşısında', 'gegenüber'), example: 'Das Café ist gegenüber.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'abbiegen', translation: l('to turn (off)', 'dönmek, sapmak', 'abbiegen') },
  { word: 'die erste / zweite / dritte Straße', translation: l('the first / second / third street', 'birinci / ikinci / üçüncü sokak', 'die erste / zweite / dritte Straße') },
  { word: 'Wie komme ich zum / zur …?', translation: l('How do I get to …?', '…a nasıl giderim?', 'Wie komme ich zum / zur …?') },
  { word: 'Apotheke', gender: 'f', plural: 'die Apotheken', translation: l('pharmacy', 'eczane', 'Apotheke') },
  { word: 'Bahnhof', gender: 'm', plural: 'die Bahnhöfe', translation: l('station', 'istasyon', 'Bahnhof') },
  { word: 'Bank', gender: 'f', plural: 'die Banken', translation: l('bank', 'banka', 'Bank') },
  { word: 'Hotel', gender: 'n', plural: 'die Hotels', translation: l('hotel', 'otel', 'Hotel') },
  { word: 'Post', gender: 'f', translation: l('post office', 'postane', 'Post') },
]

/** Polite (Sie) imperatives for giving directions. */
const IMPERATIVES: [string, string, [string, string]][] = [
  ['Gehen', 'Gehen Sie geradeaus.', ['Geht', 'Gehst']],
  ['Nehmen', 'Nehmen Sie die erste Straße links.', ['Nimmt', 'Nehmt']],
  ['Biegen', 'Biegen Sie an der Ampel rechts ab.', ['Biegt', 'Biegst']],
  ['Fahren', 'Fahren Sie mit dem Bus.', ['Fährt', 'Fährst']],
  ['Gehen', 'Gehen Sie über die Kreuzung.', ['Gehst', 'Geht']],
  ['Nehmen', 'Nehmen Sie die zweite Straße rechts.', ['Nehmt', 'Nimmst']],
]

function imperativeDrills(): Exercise[] {
  return IMPERATIVES.map(([verb, sentence, wrong], i) => {
    const options = [verb, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `imp-${i + 1}`,
      type: 'multiple_choice' as const,
      topic: 'imperative',
      concept: 'imperative-sie',
      skill: 'grammar' as const,
      difficulty: 1 as const,
      prompt: sentence.replace(verb, '___'),
      options: ordered,
      answer: ordered.indexOf(verb),
      explanation: l(
        'Polite request (Sie): verb (infinitive form) first, then Sie: Gehen Sie …, Nehmen Sie …',
        'Kibar rica (Sie): önce fiil (mastar biçimi), sonra Sie: Gehen Sie …, Nehmen Sie …',
        'Imperativ mit Sie: Verb + Sie.'
      ),
      examples: [`**${sentence}**`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: read the map -----------------------------------------
  {
    id: 'map-links',
    type: 'multiple_choice',
    topic: 'directions',
    concept: 'left-right',
    skill: 'vocabulary',
    difficulty: 1,
    visual: ['💊 ⬆️ 🏦', '. 🚶 .'],
    prompt: 'Die Apotheke ist ___.',
    promptL10n: l('You 🚶 walk up the street ⬆️. Where is the pharmacy 💊?', 'Sen 🚶 caddede yukarı ⬆️ yürüyorsun. Eczane 💊 nerede?', 'Du 🚶 gehst die Straße hoch ⬆️. Wo ist die Apotheke 💊?'),
    options: ['links', 'rechts', 'geradeaus'],
    answer: 0,
    explanation: l('The pharmacy is on your left side: links.', 'Eczane sol tarafında: links.', 'Die Apotheke ist links.'),
    examples: ['Die Apotheke ist **links**, die Bank ist **rechts**.'],
    practice: ['map-rechts'],
  },
  {
    id: 'map-rechts',
    type: 'multiple_choice',
    topic: 'directions',
    concept: 'left-right',
    skill: 'vocabulary',
    difficulty: 1,
    visual: ['💊 ⬆️ 🏦', '. 🚶 .'],
    prompt: 'Die Bank ist ___.',
    promptL10n: l('Same street. Where is the bank 🏦?', 'Aynı cadde. Banka 🏦 nerede?', 'Gleiche Straße. Wo ist die Bank 🏦?'),
    options: ['links', 'rechts', 'gegenüber'],
    answer: 1,
    explanation: l('The bank is on your right: rechts.', 'Banka sağında: rechts.', 'Die Bank ist rechts.'),
    examples: ['Die Bank ist **rechts**.'],
  },
  {
    id: 'map-geradeaus',
    type: 'multiple_choice',
    topic: 'directions',
    concept: 'route',
    skill: 'grammar',
    difficulty: 1,
    visual: ['. 🏨 .', '. ⬆️ .', '. ⬆️ .', '. 🚶 .'],
    prompt: 'Wie komme ich zum Hotel? – ___',
    options: ['Gehen Sie geradeaus.', 'Gehen Sie links.', 'Gehen Sie rechts.'],
    answer: 0,
    explanation: l('The hotel is straight ahead: geradeaus.', 'Otel tam karşıda: geradeaus.', 'Das Hotel ist geradeaus.'),
    examples: ['Gehen Sie **geradeaus**.'],
  },
  {
    id: 'map-dann-links',
    type: 'multiple_choice',
    topic: 'directions',
    concept: 'route',
    skill: 'grammar',
    difficulty: 2,
    visual: ['🏫 ⬅️ ⬅️', '. . ⬆️', '. . 🚶'],
    prompt: 'Wie komme ich zur Schule? – ___',
    options: ['Gehen Sie geradeaus und dann links.', 'Gehen Sie links und dann geradeaus.', 'Gehen Sie geradeaus und dann rechts.'],
    answer: 0,
    explanation: l('First straight on ⬆️, then left ⬅️.', 'Önce dümdüz ⬆️, sonra sola ⬅️.', 'Zuerst geradeaus, dann links.'),
    examples: ['Gehen Sie **geradeaus** und dann **links**.'],
    practice: ['map-dann-rechts'],
  },
  {
    id: 'map-dann-rechts',
    type: 'multiple_choice',
    topic: 'directions',
    concept: 'route',
    skill: 'grammar',
    difficulty: 2,
    visual: ['🏣 ⬅️ . ➡️ 🏦', '. . ⬆️ . .', '. . 🚶 . .'],
    prompt: 'Wie komme ich zur Bank? – ___',
    options: ['Geradeaus und dann rechts.', 'Geradeaus und dann links.', 'Immer links.'],
    answer: 0,
    explanation: l('Straight on, then right ➡️ to the bank 🏦. (Left goes to the post office 🏣.)', 'Dümdüz, sonra sağa ➡️ bankaya 🏦. (Sol postaneye 🏣 gider.)', 'Geradeaus, dann rechts.'),
    examples: ['Gehen Sie geradeaus und dann **rechts**.'],
  },
  {
    id: 'sort-directions',
    type: 'categorize',
    topic: 'directions',
    concept: 'left-right',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Sort by direction.', 'Yöne göre ayır.', 'Sortiere nach Richtung.'),
    categories: ['⬅️ links', '➡️ rechts', '⬆️ geradeaus'],
    items: [
      { text: 'Biegen Sie links ab.', category: 0 },
      { text: 'Die zweite Straße rechts.', category: 1 },
      { text: 'Immer geradeaus.', category: 2 },
      { text: 'Die Post ist links.', category: 0 },
      { text: 'An der Ampel rechts.', category: 1 },
      { text: 'Gehen Sie weiter geradeaus.', category: 2 },
    ],
    explanation: l('links ⬅️, rechts ➡️, geradeaus ⬆️.', 'links ⬅️, rechts ➡️, geradeaus ⬆️.', 'links ⬅️, rechts ➡️, geradeaus ⬆️.'),
  },
  {
    id: 'tf-gegenueber',
    type: 'true_false',
    topic: 'directions',
    concept: 'gegenueber',
    skill: 'vocabulary',
    difficulty: 2,
    visual: ['☕ . 🏦', '. 🛣️ .'],
    statement: 'Das Café ist gegenüber der Bank.',
    answer: true,
    explanation: l(
      'gegenüber = opposite, on the other side of the street.',
      'gegenüber = karşısında, caddenin öbür tarafında.',
      'gegenüber = auf der anderen Straßenseite.'
    ),
    examples: ['Das Café ist **gegenüber** der Bank.'],
  },
  {
    id: 'match-ordinal',
    type: 'matching',
    topic: 'route',
    concept: 'ordinals',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the street numbers.', 'Sokak sıralarını eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'die erste Straße', right: '1.' },
      { left: 'die zweite Straße', right: '2.' },
      { left: 'die dritte Straße', right: '3.' },
    ],
    explanation: l('erste, zweite, dritte = first, second, third.', 'erste, zweite, dritte = birinci, ikinci, üçüncü.', 'erste, zweite, dritte.'),
  },
  {
    id: 'select-polite',
    type: 'multiple_select',
    topic: 'route',
    concept: 'asking-way',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('How can you ask for the way? Select all.', 'Yolu nasıl sorabilirsin? Hepsini seç.', 'Wie fragt man nach dem Weg? Wähle alle.'),
    options: ['Entschuldigung, wo ist der Bahnhof?', 'Bahnhof!', 'Wie komme ich zur Post?', 'Gehen Sie links.', 'Gibt es hier eine Apotheke?'],
    answers: [0, 2, 4],
    explanation: l(
      'Ask with Wo ist …? / Wie komme ich zum/zur …? / Gibt es hier …? – „Gehen Sie links“ is an answer.',
      'Wo ist …? / Wie komme ich zum/zur …? / Gibt es hier …? ile sor – „Gehen Sie links“ bir cevaptır.',
      'Wo ist …? / Wie komme ich zum/zur …? / Gibt es hier …?'
    ),
  },

  // --- Practice 2: give directions --------------------------------------
  {
    id: 'fill-geradeaus',
    type: 'fill_blank',
    topic: 'directions',
    concept: 'route',
    skill: 'grammar',
    difficulty: 1,
    visual: ['. 🚉 .', '. ⬆️ .', '. 🚶 .'],
    sentence: 'Gehen Sie ___, dann sehen Sie den Bahnhof.',
    accepted: ['geradeaus'],
    explanation: l('Straight on ⬆️ = geradeaus.', 'Dümdüz ⬆️ = geradeaus.', '⬆️ = geradeaus.'),
    examples: ['Gehen Sie **geradeaus**.'],
  },
  {
    id: 'fill-zweite',
    type: 'fill_blank',
    topic: 'route',
    concept: 'ordinals',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Nehmen Sie die ___ Straße links. (2.)',
    accepted: ['zweite'],
    explanation: l('2. = zweite.', '2. = zweite.', '2. = zweite.'),
    examples: ['Nehmen Sie die **zweite** Straße links.'],
  },
  {
    id: 'build-wie-komme',
    type: 'sentence_builder',
    topic: 'route',
    concept: 'asking-way',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ich', 'zum Bahnhof', 'Wie', 'komme'],
    answers: [['Wie', 'komme', 'ich', 'zum Bahnhof']],
    end: '?',
    translation: l('How do I get to the station?', 'İstasyona nasıl giderim?', 'Wie komme ich zum Bahnhof?'),
    explanation: l(
      'Wie komme ich + zum (der/das) / zur (die) + place? (zum/zur: more in Unit 19.)',
      'Wie komme ich + zum (der/das) / zur (die) + yer? (zum/zur: daha fazlası Ünite 19’da.)',
      'Wie komme ich zum / zur …?'
    ),
    examples: ['**Wie komme ich zum** Bahnhof?'],
  },
  {
    id: 'build-imperative',
    type: 'sentence_builder',
    topic: 'imperative',
    concept: 'imperative-sie',
    skill: 'grammar',
    difficulty: 2,
    chips: ['Sie', 'links', 'Gehen', 'an der Ampel'],
    answers: [['Gehen', 'Sie', 'an der Ampel', 'links']],
    translation: l('Go left at the traffic lights.', 'Trafik lambasında sola gidin.', 'Gehen Sie an der Ampel links.'),
    explanation: l('Imperative: verb + Sie + rest.', 'Emir kipi: fiil + Sie + geri kalan.', 'Imperativ: Verb + Sie + Rest.'),
    examples: ['**Gehen Sie** an der Ampel links.'],
  },
  {
    id: 'ordering-route',
    type: 'ordering',
    topic: 'route',
    concept: 'route',
    skill: 'reading',
    difficulty: 2,
    visual: ['. . 💊', '⬆️ ➡️ ⬆️', '⬆️ . .', '🚶 . .'],
    promptL10n: l('Put the directions to the pharmacy 💊 in order.', 'Eczaneye 💊 giden tarifi sıraya koy.', 'Bring den Weg zur Apotheke 💊 in die richtige Reihenfolge.'),
    items: ['Dann gehen Sie wieder geradeaus.', 'Gehen Sie zuerst geradeaus.', 'Die Apotheke ist dort.', 'An der Kreuzung biegen Sie rechts ab.'],
    answer: ['Gehen Sie zuerst geradeaus.', 'An der Kreuzung biegen Sie rechts ab.', 'Dann gehen Sie wieder geradeaus.', 'Die Apotheke ist dort.'],
    explanation: l('⬆️ straight on → ➡️ right at the crossroads → ⬆️ straight on → 💊.', '⬆️ dümdüz → ➡️ kavşakta sağa → ⬆️ dümdüz → 💊.', '⬆️ → ➡️ → ⬆️ → 💊.'),
  },
  {
    id: 'fix-imperative',
    type: 'error_correction',
    topic: 'imperative',
    concept: 'imperative-sie',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie gehen geradeaus!',
    accepted: ['Gehen Sie geradeaus!', 'Gehen Sie geradeaus.'],
    instructions: l('Make it a polite instruction.', 'Bunu kibar bir talimat yap.', 'Mach daraus eine höfliche Aufforderung.'),
    explanation: l(
      '„Sie gehen geradeaus“ is a statement. Instruction: verb first – Gehen Sie geradeaus!',
      '„Sie gehen geradeaus“ bir bildirim cümlesidir. Talimat için fiil başa: Gehen Sie geradeaus!',
      'Aufforderung: Verb zuerst – Gehen Sie geradeaus!'
    ),
    examples: ['**Gehen Sie** geradeaus!'],
  },
  {
    id: 'fix-abbiegen',
    type: 'error_correction',
    topic: 'imperative',
    concept: 'imperative-sie',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Abbiegen Sie links.',
    accepted: ['Biegen Sie links ab.'],
    explanation: l(
      'abbiegen is separable: Biegen Sie links ab. (prefix at the end, Unit 15)',
      'abbiegen ayrılabilen bir fiildir: Biegen Sie links ab. (ön ek sonda, Ünite 15)',
      'abbiegen ist trennbar: Biegen Sie links ab.'
    ),
    examples: ['**Biegen Sie** links **ab**.'],
  },
  {
    id: 'tr-links',
    type: 'translation',
    topic: 'directions',
    concept: 'route',
    skill: 'writing',
    difficulty: 2,
    source: l('Go straight on and then right.', 'Dümdüz gidin, sonra sağa.', 'Go straight on and then right.'),
    accepted: ['Gehen Sie geradeaus und dann rechts.', 'Geh geradeaus und dann rechts.'],
    explanation: l('Gehen Sie geradeaus und dann rechts.', 'Gehen Sie geradeaus und dann rechts.', 'Gehen Sie geradeaus und dann rechts.'),
    examples: ['Gehen Sie **geradeaus** und dann **rechts**.'],
  },
  {
    id: 'tr-wo-ist',
    type: 'translation',
    topic: 'route',
    concept: 'asking-way',
    skill: 'writing',
    difficulty: 1,
    source: l('Excuse me, where is the post office?', 'Affedersiniz, postane nerede?', 'Excuse me, where is the post office?'),
    accepted: ['Entschuldigung, wo ist die Post?'],
    explanation: l('Entschuldigung, wo ist die Post?', 'Entschuldigung, wo ist die Post?', 'Entschuldigung, wo ist die Post?'),
    examples: ['Entschuldigung, **wo ist** die Post?'],
  },
  {
    id: 'dialog-weit',
    type: 'dialogue',
    topic: 'route',
    concept: 'asking-way',
    skill: 'grammar',
    difficulty: 1,
    lines: [
      { speaker: 'Tourist', de: 'Wie komme ich zum Bahnhof?' },
      { speaker: 'Frau', de: 'Gehen Sie hier geradeaus und dann links.' },
    ],
    options: ['Ist es weit?', 'Gehen Sie rechts!', 'Ich bin der Bahnhof.'],
    answer: 0,
    explanation: l('A natural follow-up: Ist es weit? (Is it far?)', 'Doğal bir devam sorusu: Ist es weit? (Uzak mı?)', 'Ist es weit?'),
  },
  {
    id: 'dialog-danke',
    type: 'dialogue',
    topic: 'route',
    concept: 'asking-way',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Mann', de: 'Die Haltestelle ist dort, gegenüber vom Café.' }],
    options: ['Vielen Dank!', 'Bitte, links.', 'Gute Nacht.'],
    answer: 0,
    explanation: l('Thank the person: Vielen Dank! / Danke schön!', 'Teşekkür et: Vielen Dank! / Danke schön!', 'Vielen Dank!'),
  },

  // --- Reading ------------------------------------------------------
  {
    id: 'read-wohin',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wohin geht Maria?',
    options: ['zu Leas Wohnung', 'zum Bahnhof', 'in die Schule'],
    answer: 0,
    explanation: l('It is a message from Lea with directions to her flat.', 'Bu, Lea’dan evine yol tarifi içeren bir mesaj.', 'Lea beschreibt den Weg zu ihrer Wohnung.'),
  },
  {
    id: 'read-erste',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wo biegt Maria nach der Haltestelle ab?',
    options: ['an der Ampel rechts', 'an der Kreuzung links', 'gar nicht'],
    answer: 0,
    explanation: l('„An der Ampel biegst du rechts ab.“', '„An der Ampel biegst du rechts ab.“', '„An der Ampel biegst du rechts ab.“'),
  },
  {
    id: 'read-haus',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 2,
    statement: 'Leas Haus ist neben der Bäckerei.',
    answer: false,
    explanation: l('„Mein Haus ist gegenüber der Bäckerei.“ – opposite, not next to.', '„Mein Haus ist gegenüber der Bäckerei.“ – yanında değil, karşısında.', '„gegenüber der Bäckerei“'),
  },
  {
    id: 'read-zeit',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie lange braucht Maria zu Fuß?',
    options: ['fünf Minuten', 'eine Stunde', 'zwanzig Minuten'],
    answer: 0,
    explanation: l('„Das sind nur fünf Minuten zu Fuß.“', '„Das sind nur fünf Minuten zu Fuß.“', '„nur fünf Minuten zu Fuß“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-route',
    type: 'listening_choice',
    topic: 'directions',
    concept: 'route',
    skill: 'listening',
    difficulty: 2,
    audio: 'Gehen Sie geradeaus und dann die zweite Straße links.',
    question: l('Which route is it?', 'Hangi rota?', 'Welcher Weg ist das?'),
    options: ['⬆️ + 2. ⬅️', '⬆️ + 2. ➡️', '⬅️ + 2. ⬆️'],
    answer: 0,
    explanation: l('geradeaus ⬆️, then the second street left ⬅️.', 'dümdüz ⬆️, sonra ikinci sokaktan sola ⬅️.', 'geradeaus, dann die zweite links.'),
  },
  {
    id: 'listen-rechts',
    type: 'listening_choice',
    topic: 'directions',
    concept: 'left-right',
    skill: 'listening',
    difficulty: 1,
    audio: 'Die Apotheke ist hier rechts.',
    question: l('Where is the pharmacy?', 'Eczane nerede?', 'Wo ist die Apotheke?'),
    options: ['⬅️', '➡️', '⬆️'],
    answer: 1,
    explanation: l('rechts = ➡️.', 'rechts = ➡️.', 'rechts = ➡️.'),
  },
  {
    id: 'listen-ampel',
    type: 'listening_choice',
    topic: 'imperative',
    concept: 'imperative-sie',
    skill: 'listening',
    difficulty: 2,
    audio: 'An der Ampel biegen Sie links ab.',
    question: l('Where do you turn?', 'Nerede dönüyorsun?', 'Wo biegt man ab?'),
    options: ['🚦 an der Ampel', '🔀 an der Kreuzung', '🚏 an der Haltestelle'],
    answer: 0,
    explanation: l('„An der Ampel …“', '„An der Ampel …“', '„An der Ampel …“'),
  },
  {
    id: 'listen-weit',
    type: 'listening_choice',
    topic: 'directions',
    concept: 'route',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ist das weit? – Nein, das ist ganz nah. Nur zwei Minuten.',
    question: l('Is it far?', 'Uzak mı?', 'Ist es weit?'),
    options: ['Ja', 'Nein'],
    answer: 1,
    explanation: l('„ganz nah“ = very close.', '„ganz nah“ = çok yakın.', '„ganz nah“'),
  },

  ...imperativeDrills(),
]

export const UNIT18_RICHTUNGEN: CourseUnit = {
  level: 'A1',
  number: 18,
  slug: 'richtungen',
  titleDe: 'Richtungen',
  title: l('Directions', 'Yön tarifi', 'Richtungen'),
  goal: l(
    'By the end of this unit you can ask for the way, understand directions like „geradeaus und dann links“ and give simple directions yourself.',
    'Bu ünitenin sonunda yol sorabilir, „geradeaus und dann links“ gibi tarifleri anlayabilir ve kendin basit yol tarifi verebilirsin.',
    'Am Ende dieser Einheit fragst du nach dem Weg, verstehst Wegbeschreibungen und beschreibst selbst einen einfachen Weg.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'directions', label: l('links, rechts, geradeaus', 'links, rechts, geradeaus', 'links, rechts, geradeaus') },
    { key: 'route', label: l('Asking and giving the way', 'Yol sormak ve tarif etmek', 'Nach dem Weg fragen') },
    { key: 'imperative', label: l('Gehen Sie …!', 'Gehen Sie …!', 'Gehen Sie …!') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The words you need to find your way.', 'Yolunu bulmak için gereken kelimeler.', 'Wörter, um den Weg zu finden.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Asking for the way', 'Yol sormak', 'Nach dem Weg fragen'),
          body: l(
            'Start with „Entschuldigung“ – then: Wo ist …? / Wie komme ich zum (der/das) / zur (die) …? / Gibt es hier …?',
            '„Entschuldigung“ ile başla – sonra: Wo ist …? / Wie komme ich zum (der/das) / zur (die) …? / Gibt es hier …?',
            'Entschuldigung, wo ist …? / Wie komme ich zum / zur …?'
          ),
          examples: [
            { de: 'Entschuldigung, **wo ist** der Bahnhof?', translation: l('Excuse me, where is the station?', 'Affedersiniz, istasyon nerede?', 'Wo ist …?') },
            { de: '**Wie komme ich zur** Post?', translation: l('How do I get to the post office?', 'Postaneye nasıl giderim?', 'zur (die Post)') },
            { de: '**Wie komme ich zum** Hotel?', translation: l('How do I get to the hotel?', 'Otele nasıl giderim?', 'zum (das Hotel)') },
          ],
        },
        {
          title: l('Giving directions: Gehen Sie …!', 'Yol tarif etmek: Gehen Sie …!', 'Den Weg beschreiben: Gehen Sie …!'),
          body: l(
            'Polite instruction (imperative with Sie): verb first, then Sie. Separable verbs split as usual: Biegen Sie links ab.',
            'Kibar talimat (Sie ile emir kipi): önce fiil, sonra Sie. Ayrılabilen fiiller her zamanki gibi ayrılır: Biegen Sie links ab.',
            'Imperativ mit Sie: Verb + Sie. Trennbar: Biegen Sie links ab.'
          ),
          table: {
            head: [l('instruction', 'talimat', 'Aufforderung'), l('meaning', 'anlam', 'Bedeutung')],
            rows: [
              ['Gehen Sie geradeaus.', '⬆️'],
              ['Biegen Sie links ab.', '⬅️'],
              ['Nehmen Sie die erste Straße rechts.', '1. ➡️'],
              ['Gehen Sie über die Kreuzung.', '🔀 ⬆️'],
            ],
          },
          tip: l(
            'With friends (du): Geh geradeaus! Bieg links ab! – but Sie is safer with strangers.',
            'Arkadaşlarla (du): Geh geradeaus! Bieg links ab! – ama yabancılarla Sie daha güvenli.',
            'Mit du: Geh geradeaus! – mit Fremden lieber Sie.'
          ),
        },
        {
          title: l('First, second, third', 'Birinci, ikinci, üçüncü', 'erste, zweite, dritte'),
          body: l(
            'die erste Straße (1st), die zweite Straße (2nd), die dritte Straße (3rd).',
            'die erste Straße (1.), die zweite Straße (2.), die dritte Straße (3.).',
            'die erste, zweite, dritte Straße.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Daniel is new in town and needs the pharmacy.', 'Daniel şehirde yeni ve eczaneye ihtiyacı var.', 'Daniel ist neu in der Stadt und sucht die Apotheke.'),
      dialogue: [
        { speaker: 'Daniel', de: 'Entschuldigung, **wie komme ich zur** Apotheke?', translation: l('Excuse me, how do I get to the pharmacy?', 'Affedersiniz, eczaneye nasıl giderim?', '') },
        { speaker: 'Frau', de: '**Gehen Sie** hier **geradeaus** bis zur Ampel.', translation: l('Go straight on here as far as the traffic lights.', 'Buradan trafik lambasına kadar dümdüz gidin.', '') },
        { speaker: 'Daniel', de: 'Bis zur Ampel. Und dann?', translation: l('To the traffic lights. And then?', 'Trafik lambasına kadar. Sonra?', '') },
        { speaker: 'Frau', de: 'An der Ampel **biegen Sie links ab**. Dann **nehmen Sie** die **zweite** Straße **rechts**.', translation: l('Turn left at the lights. Then take the second street on the right.', 'Lambada sola dönün. Sonra ikinci sokaktan sağa girin.', '') },
        { speaker: 'Daniel', de: 'Ist es weit?', translation: l('Is it far?', 'Uzak mı?', '') },
        { speaker: 'Frau', de: 'Nein, nur fünf Minuten. Die Apotheke ist **gegenüber** der Post.', translation: l('No, only five minutes. The pharmacy is opposite the post office.', 'Hayır, sadece beş dakika. Eczane postanenin karşısında.', '') },
        { speaker: 'Daniel', de: 'Vielen Dank!', translation: l('Thank you very much!', 'Çok teşekkürler!', '') },
      ],
      examples: [
        { de: 'Gehen Sie **geradeaus**.', translation: l('Go straight on.', 'Dümdüz gidin.', '') },
        { de: 'Biegen Sie **links** ab.', translation: l('Turn left.', 'Sola dönün.', '') },
        { de: 'Nehmen Sie die **erste** Straße **rechts**.', translation: l('Take the first street on the right.', 'Birinci sokaktan sağa girin.', '') },
        { de: 'Die Bank ist **hier**, die Post ist **dort**.', translation: l('The bank is here, the post office is there.', 'Banka burada, postane orada.', '') },
        { de: 'Das Café ist **gegenüber**.', translation: l('The café is opposite.', 'Kafe karşıda.', '') },
        { de: 'Die Haltestelle ist **um die Ecke**.', translation: l('The stop is around the corner.', 'Durak köşede.', '') },
        { de: 'Ist es **weit**? – Nein, ganz **nah**.', translation: l('Is it far? – No, very close.', 'Uzak mı? – Hayır, çok yakın.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Read the map', 'Pratik 1 · Haritayı oku', 'Übung 1 · Karte lesen'),
      intro: l(
        'Look at the little maps: you are 🚶, the arrows show the way.',
        'Küçük haritalara bak: sen 🚶’sın, oklar yolu gösteriyor.',
        'Schau auf die Karten: Du bist 🚶, die Pfeile zeigen den Weg.'
      ),
      exercises: ['map-links', 'map-geradeaus', 'map-dann-links', 'sort-directions', 'tf-gegenueber', 'match-ordinal', 'select-polite', 'imp-1', 'imp-2'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Give directions', 'Pratik 2 · Yol tarif et', 'Übung 2 · Den Weg beschreiben'),
      intro: l('Now ask and give directions yourself.', 'Şimdi kendin yol sor ve tarif et.', 'Jetzt fragst und beschreibst du selbst.'),
      exercises: [
        'fill-geradeaus',
        'fill-zweite',
        'build-wie-komme',
        'build-imperative',
        'ordering-route',
        'fix-imperative',
        'fix-abbiegen',
        'tr-links',
        'tr-wo-ist',
        'dialog-weit',
        'dialog-danke',
        'imp-3',
        'imp-4',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A message from Lea: the way to her flat.', 'Lea’dan bir mesaj: evinin yolu.', 'Eine Nachricht von Lea: der Weg zu ihrer Wohnung.'),
      passage: [
        'Hallo Maria! So kommst du zu mir:',
        'Nimm den Bus 12 bis zur Haltestelle „Rosenplatz“. Dann geh **geradeaus**.',
        'An der Ampel biegst du **rechts** ab. Nimm dann die **erste** Straße **links**.',
        'Mein Haus ist Nummer 7, **gegenüber** der Bäckerei. Das sind nur fünf Minuten zu Fuß. Bis gleich!',
      ],
      glossary: [
        { de: 'So kommst du zu mir', note: l('This is how you get to my place', 'Bana böyle gelirsin', 'Das ist der Weg zu mir') },
        { de: 'bis zur Haltestelle', note: l('as far as the stop', 'durağa kadar', 'bis zum Halt') },
        { de: 'zu Fuß', note: l('on foot', 'yürüyerek', 'laufen') },
        { de: 'Bis gleich!', note: l('See you soon!', 'Birazdan görüşürüz!', 'Bis bald!') },
      ],
      exercises: ['read-wohin', 'read-erste', 'read-haus', 'read-zeit'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Follow the spoken directions.', 'Sözlü tarifi takip et.', 'Folge der Wegbeschreibung.'),
      exercises: ['listen-route', 'listen-rechts', 'listen-ampel', 'listen-weit'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l(
        'Describe the way from your home to the nearest supermarket or bus stop.',
        'Evinden en yakın süpermarkete ya da otobüs durağına giden yolu tarif et.',
        'Beschreib den Weg von deiner Wohnung zum nächsten Supermarkt oder zur Haltestelle.'
      ),
      points: [
        l('Start: „Gehen Sie / Geh zuerst …“', 'Başlangıç: „Gehen Sie / Geh zuerst …“', 'Start: „Gehen Sie zuerst …“'),
        l('Turns: links / rechts / an der Ampel / die erste Straße …', 'Dönüşler: links / rechts / an der Ampel / die erste Straße …', 'Abbiegen: links / rechts …'),
        l('Arrival: „Der Supermarkt ist dort / gegenüber …“', 'Varış: „Der Supermarkt ist dort / gegenüber …“', 'Ziel: „… ist dort.“'),
        l('Distance: „Das sind … Minuten zu Fuß.“', 'Mesafe: „Das sind … Minuten zu Fuß.“', 'Entfernung: „… Minuten zu Fuß.“'),
      ],
      model: ['Gehen Sie zuerst geradeaus bis zur Ampel.', 'Dann biegen Sie links ab.', 'Nehmen Sie die zweite Straße rechts.', 'Der Supermarkt ist dort, gegenüber der Bank.', 'Das sind nur fünf Minuten zu Fuß.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short message to a friend: how do they get to your flat? (at least 4 sentences)',
        'Bir arkadaşına kısa bir mesaj yaz: evine nasıl gelir? (en az 4 cümle)',
        'Schreib einer Freundin oder einem Freund: Wie kommt man zu deiner Wohnung? (mindestens 4 Sätze)'
      ),
      minSentences: 4,
      checks: [
        { label: l('links or rechts', 'links ya da rechts', 'links oder rechts'), pattern: '\\b(links|rechts)\\b' },
        { label: l('geradeaus', 'geradeaus', 'geradeaus'), pattern: '\\bgeradeaus\\b' },
        { label: l('An instruction (Geh … / Gehen Sie … / Nimm …)', 'Bir talimat (Geh … / Gehen Sie … / Nimm …)', 'Eine Aufforderung (Geh … / Gehen Sie … / Nimm …)'), pattern: '\\b(Geh|Gehen Sie|Nimm|Nehmen Sie|Bieg|Biegen Sie|Fahr|Fahren Sie)\\b' },
      ],
      model: ['Hallo Tom!', 'Nimm die U-Bahn bis zum Marktplatz.', 'Dann geh geradeaus bis zur Kreuzung.', 'Bieg an der Kreuzung rechts ab.', 'Mein Haus ist links, gegenüber dem Park.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Maps and instructions – 60 seconds.', 'Haritalar ve talimatlar – 60 saniye.', 'Karten und Aufforderungen – 60 Sekunden.'),
      seconds: 60,
      pool: [...IMPERATIVES.map((_, i) => `imp-${i + 1}`), 'map-links', 'map-rechts', 'map-geradeaus', 'map-dann-links', 'map-dann-rechts'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('links, rechts, geradeaus, hier, dort, gegenüber', 'links, rechts, geradeaus, hier, dort, gegenüber', 'links, rechts, geradeaus, hier, dort, gegenüber'),
      l('Wo ist …? Wie komme ich zum / zur …?', 'Wo ist …? Wie komme ich zum / zur …?', 'Wo ist …? Wie komme ich zum / zur …?'),
      l('Instructions: Gehen Sie …! Biegen Sie … ab!', 'Talimatlar: Gehen Sie …! Biegen Sie … ab!', 'Gehen Sie …! Biegen Sie … ab!'),
      l('die erste / zweite / dritte Straße', 'die erste / zweite / dritte Straße', 'die erste / zweite / dritte Straße'),
    ],
    mistakes: [
      { wrong: 'Sie gehen geradeaus!', right: 'Gehen Sie geradeaus!', note: l('Instruction: verb first.', 'Talimat: fiil başta.', 'Aufforderung: Verb zuerst.') },
      { wrong: 'Abbiegen Sie links.', right: 'Biegen Sie links ab.', note: l('abbiegen splits.', 'abbiegen ayrılır.', 'abbiegen ist trennbar.') },
      { wrong: 'die zwei Straße', right: 'die zweite Straße', note: l('Ordinal: zweite.', 'Sıra sayısı: zweite.', 'Ordinalzahl: zweite.') },
      { wrong: 'Wie komme ich zu Bahnhof?', right: 'Wie komme ich zum Bahnhof?', note: l('zu + dem = zum.', 'zu + dem = zum.', 'zu + dem = zum.') },
    ],
  },
}
