import type { CourseUnit, Exercise, Gender, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Vater', gender: 'm', plural: 'die Väter', emoji: '👨', translation: l('father', 'baba', 'Vater'), example: 'Mein Vater heißt Hasan.' },
  { word: 'Mutter', gender: 'f', plural: 'die Mütter', emoji: '👩', translation: l('mother', 'anne', 'Mutter'), example: 'Meine Mutter ist Ärztin.' },
  { word: 'Bruder', gender: 'm', plural: 'die Brüder', emoji: '👦', translation: l('brother', 'erkek kardeş / ağabey', 'Bruder'), example: 'Mein Bruder ist 19.' },
  { word: 'Schwester', gender: 'f', plural: 'die Schwestern', emoji: '👧', translation: l('sister', 'kız kardeş / abla', 'Schwester'), example: 'Meine Schwester heißt Elif.' },
  { word: 'Sohn', gender: 'm', plural: 'die Söhne', emoji: '🧒', translation: l('son', 'oğul', 'Sohn'), example: 'Mein Sohn ist drei Jahre alt.' },
  { word: 'Tochter', gender: 'f', plural: 'die Töchter', emoji: '👶', translation: l('daughter', 'kız evlat', 'Tochter'), example: 'Meine Tochter heißt Defne.' },
  { word: 'Großvater', gender: 'm', plural: 'die Großväter', emoji: '👴', translation: l('grandfather', 'büyükbaba', 'Großvater'), example: 'Mein Großvater ist 80.' },
  { word: 'Großmutter', gender: 'f', plural: 'die Großmütter', emoji: '👵', translation: l('grandmother', 'büyükanne', 'Großmutter'), example: 'Meine Großmutter wohnt in Izmir.' },
  { word: 'Mann', gender: 'm', plural: 'die Männer', emoji: '🤵', translation: l('husband; man', 'koca; adam', 'Ehemann; Mann'), example: 'Das ist mein Mann.' },
  { word: 'Frau', gender: 'f', plural: 'die Frauen', emoji: '👰', translation: l('wife; woman', 'karı, eş; kadın', 'Ehefrau; Frau'), example: 'Das ist meine Frau.' },
  { word: 'Kind', gender: 'n', plural: 'die Kinder', emoji: '🧒', translation: l('child', 'çocuk', 'Kind'), example: 'Mein Kind spielt.' },
  { word: 'die Eltern', emoji: '👨‍👩‍👧', translation: l('parents (plural only)', 'anne baba (yalnızca çoğul)', 'Mutter und Vater'), example: 'Meine Eltern wohnen in Ankara.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'die Geschwister', translation: l('siblings (plural)', 'kardeşler (çoğul)', 'Brüder und Schwestern') },
  { word: 'Familie', gender: 'f', plural: 'die Familien', translation: l('family', 'aile', 'Familie') },
  { word: 'Onkel', gender: 'm', plural: 'die Onkel', translation: l('uncle', 'amca, dayı', 'Onkel') },
  { word: 'Tante', gender: 'f', plural: 'die Tanten', translation: l('aunt', 'hala, teyze', 'Tante') },
  { word: 'Freund', gender: 'm', plural: 'die Freunde', translation: l('friend; boyfriend', 'arkadaş; erkek arkadaş', 'Freund') },
  { word: 'Freundin', gender: 'f', plural: 'die Freundinnen', translation: l('friend; girlfriend', 'kız arkadaş', 'Freundin') },
  { word: 'verheiratet', translation: l('married', 'evli', 'verheiratet') },
  { word: 'ledig', translation: l('single', 'bekâr', 'ledig') },
  { word: 'geschieden', translation: l('divorced', 'boşanmış', 'geschieden') },
  { word: 'Oma / Opa', translation: l('grandma / grandpa', 'nine / dede', 'Großmutter / Großvater') },
]

const POSSESSIVE_NOUNS: { noun: string; gender: Gender | 'pl' }[] = [
  { noun: 'Vater', gender: 'm' },
  { noun: 'Mutter', gender: 'f' },
  { noun: 'Bruder', gender: 'm' },
  { noun: 'Schwester', gender: 'f' },
  { noun: 'Sohn', gender: 'm' },
  { noun: 'Tochter', gender: 'f' },
  { noun: 'Kind', gender: 'n' },
  { noun: 'Eltern', gender: 'pl' },
  { noun: 'Onkel', gender: 'm' },
  { noun: 'Tante', gender: 'f' },
  { noun: 'Geschwister', gender: 'pl' },
  { noun: 'Großvater', gender: 'm' },
]

const ARTICLE: Record<Gender | 'pl', string> = { m: 'der', f: 'die', n: 'das', pl: 'die (Plural)' }

/** "___ Mutter → meine" drills for the speed round and review variations. */
function possessiveDrills(): Exercise[] {
  return POSSESSIVE_NOUNS.map(({ noun, gender }) => {
    const answer = gender === 'f' || gender === 'pl' ? 1 : 0
    return {
      id: `poss-${noun.toLowerCase()}`,
      type: 'multiple_choice' as const,
      topic: 'possessive',
      concept: answer === 1 ? 'possessive-meine' : 'possessive-mein',
      skill: 'grammar' as const,
      difficulty: 1 as const,
      prompt: `___ ${noun}`,
      options: ['mein', 'meine'],
      answer,
      explanation: l(
        `${ARTICLE[gender]} ${noun} → ${answer ? 'meine' : 'mein'} ${noun}.`,
        `${ARTICLE[gender]} ${noun} → ${answer ? 'meine' : 'mein'} ${noun}.`,
        `${ARTICLE[gender]} ${noun} → ${answer ? 'meine' : 'mein'} ${noun}.`
      ),
      examples: [gender === 'pl' ? `**Meine ${noun}** …` : `{${gender}:${answer ? 'Meine' : 'Mein'} ${noun}} …`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise ----------------------------------------------
  {
    id: 'img-grossmutter',
    type: 'image_choice',
    topic: 'vocabulary',
    concept: 'family-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'die Großmutter',
    options: [
      { emoji: '👴', label: 'der Großvater' },
      { emoji: '👵', label: 'die Großmutter' },
      { emoji: '👧', label: 'die Schwester' },
      { emoji: '👨', label: 'der Vater' },
    ],
    answer: 1,
    explanation: l(
      'groß (big) + Mutter = grandmother. Short and friendly: die Oma.',
      'groß (büyük) + Mutter = büyükanne. Kısa ve samimi: die Oma.',
      'Groß + Mutter = Großmutter. Kurz und lieb: die Oma.'
    ),
    examples: ['{f:Meine Großmutter} wohnt in Izmir.'],
  },
  {
    id: 'match-pairs',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'family-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Find the female partner of each word.', 'Her kelimenin kadın karşılığını bul.', 'Finde das weibliche Gegenstück.'),
    pairs: [
      { left: 'der Vater', right: 'die Mutter' },
      { left: 'der Bruder', right: 'die Schwester' },
      { left: 'der Sohn', right: 'die Tochter' },
      { left: 'der Großvater', right: 'die Großmutter' },
    ],
    explanation: l(
      'Men are der, women die – at least in the family this is logical!',
      'Erkekler der, kadınlar die – en azından ailede bu mantıklı!',
      'Männer: der, Frauen: die – in der Familie ist das logisch!'
    ),
  },
  {
    id: 'mc-mein-vater',
    type: 'multiple_choice',
    topic: 'possessive',
    concept: 'possessive-mein',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Das ist ___ Vater.',
    options: ['mein', 'meine'],
    answer: 0,
    explanation: l(
      'der Vater → mein Vater. mein works like ein: masculine and neuter → mein.',
      'der Vater → mein Vater. mein, ein gibi çalışır: eril ve nötr → mein.',
      'der Vater → mein Vater. mein funktioniert wie ein: maskulin und neutral → mein.'
    ),
    examples: ['Das ist {m:mein Vater}.'],
    practice: ['mc-meine-mutter', 'mc-meine-eltern'],
  },
  {
    id: 'mc-meine-mutter',
    type: 'multiple_choice',
    topic: 'possessive',
    concept: 'possessive-meine',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Das ist ___ Mutter.',
    options: ['mein', 'meine'],
    answer: 1,
    explanation: l('die Mutter → meine Mutter (like eine).', 'die Mutter → meine Mutter (eine gibi).', 'die Mutter → meine Mutter (wie eine).'),
    examples: ['Das ist {f:meine Mutter}.'],
  },
  {
    id: 'mc-meine-eltern',
    type: 'multiple_choice',
    topic: 'possessive',
    concept: 'possessive-meine',
    skill: 'grammar',
    difficulty: 2,
    prompt: '___ Eltern wohnen in Ankara.',
    options: ['Mein', 'Meine'],
    answer: 1,
    explanation: l(
      'Plural → meine: meine Eltern, meine Kinder.',
      'Çoğul → meine: meine Eltern, meine Kinder.',
      'Plural → meine: meine Eltern, meine Kinder.'
    ),
    examples: ['**Meine Eltern** wohnen in Ankara.'],
  },
  {
    id: 'sort-mein-meine',
    type: 'categorize',
    topic: 'possessive',
    concept: 'possessive-mixed',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('mein or meine? Sort the family words.', 'mein mi meine mi? Aile kelimelerini ayır.', 'mein oder meine? Sortiere.'),
    categories: ['mein', 'meine'],
    items: [
      { text: 'Bruder', category: 0 },
      { text: 'Schwester', category: 1 },
      { text: 'Kind', category: 0 },
      { text: 'Eltern', category: 1 },
      { text: 'Sohn', category: 0 },
      { text: 'Tochter', category: 1 },
    ],
    explanation: l(
      'mein: der Bruder, das Kind, der Sohn. meine: die Schwester, die Tochter, die Eltern (plural).',
      'mein: der Bruder, das Kind, der Sohn. meine: die Schwester, die Tochter, die Eltern (çoğul).',
      'mein: der Bruder, das Kind, der Sohn. meine: die Schwester, die Tochter, die Eltern (Plural).'
    ),
  },
  {
    id: 'tf-mein-schwester',
    type: 'true_false',
    topic: 'possessive',
    concept: 'possessive-meine',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Mein Schwester heißt Elif.',
    answer: false,
    instructions: l('Is this sentence correct?', 'Bu cümle doğru mu?', 'Ist der Satz richtig?'),
    explanation: l('die Schwester → Meine Schwester heißt Elif.', 'die Schwester → Meine Schwester heißt Elif.', 'die Schwester → Meine Schwester heißt Elif.'),
    examples: ['{f:Meine Schwester} heißt Elif.'],
  },
  {
    id: 'select-female',
    type: 'multiple_select',
    topic: 'vocabulary',
    concept: 'family-words',
    skill: 'vocabulary',
    difficulty: 1,
    promptL10n: l('Select all words with die.', 'die alan tüm kelimeleri seç.', 'Wähle alle Wörter mit die.'),
    options: ['Mutter', 'Vater', 'Tochter', 'Sohn', 'Großmutter', 'Bruder'],
    answers: [0, 2, 4],
    explanation: l('die Mutter, die Tochter, die Großmutter.', 'die Mutter, die Tochter, die Großmutter.', 'die Mutter, die Tochter, die Großmutter.'),
  },
  {
    id: 'match-plural',
    type: 'matching',
    topic: 'plural',
    concept: 'family-plural',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match singular and plural.', 'Tekil ve çoğulu eşleştir.', 'Ordne Singular und Plural zu.'),
    pairs: [
      { left: 'der Bruder', right: 'die Brüder' },
      { left: 'die Schwester', right: 'die Schwestern' },
      { left: 'das Kind', right: 'die Kinder' },
      { left: 'die Tochter', right: 'die Töchter' },
    ],
    explanation: l(
      'Many family plurals get an umlaut: Bruder → Brüder, Tochter → Töchter, Sohn → Söhne.',
      'Birçok aile çoğulu umlaut alır: Bruder → Brüder, Tochter → Töchter, Sohn → Söhne.',
      'Viele Familienwörter bekommen im Plural einen Umlaut: Brüder, Töchter, Söhne.'
    ),
  },

  // --- Practice 2: use -----------------------------------------------------
  {
    id: 'fill-dein-bruder',
    type: 'fill_blank',
    topic: 'possessive',
    concept: 'possessive-mein',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wie heißt ___ Bruder?',
    accepted: ['dein'],
    base: 'dein / deine',
    explanation: l('der Bruder → dein Bruder (your, informal).', 'der Bruder → dein Bruder (senin).', 'der Bruder → dein Bruder.'),
    examples: ['Wie heißt {m:dein Bruder}?'],
    practice: ['fill-deine-schwester'],
  },
  {
    id: 'fill-deine-schwester',
    type: 'fill_blank',
    topic: 'possessive',
    concept: 'possessive-meine',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wie heißt ___ Schwester?',
    accepted: ['deine'],
    base: 'dein / deine',
    explanation: l('die Schwester → deine Schwester.', 'die Schwester → deine Schwester.', 'die Schwester → deine Schwester.'),
    examples: ['Wie heißt {f:deine Schwester}?'],
  },
  {
    id: 'mc-ihr-sohn',
    type: 'multiple_choice',
    topic: 'possessive',
    concept: 'possessive-formal',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Frau Weber, wie heißt ___ Sohn?',
    options: ['Ihr', 'dein', 'Ihre'],
    answer: 0,
    explanation: l(
      'Formal Sie → Ihr / Ihre (capital I): der Sohn → Ihr Sohn.',
      'Resmi Sie → Ihr / Ihre (büyük I): der Sohn → Ihr Sohn.',
      'Höflich (Sie) → Ihr / Ihre (groß): der Sohn → Ihr Sohn.'
    ),
    examples: ['Wie heißt {m:Ihr Sohn}, Frau Weber?'],
  },
  {
    id: 'mc-einen-bruder',
    type: 'multiple_choice',
    topic: 'haben',
    concept: 'haben-family',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich habe ___ Bruder.',
    options: ['einen', 'eine', 'ein'],
    answer: 0,
    explanation: l(
      'After haben, masculine ein → einen: Ich habe einen Bruder. Feminine and neuter stay: eine Schwester, ein Kind. (Why? Unit 11.)',
      'haben’den sonra eril ein → einen: Ich habe einen Bruder. Dişil ve nötr değişmez: eine Schwester, ein Kind. (Nedeni Ünite 11’de.)',
      'Nach haben wird maskulines ein → einen: Ich habe einen Bruder. Feminin und neutral bleiben: eine Schwester, ein Kind. (Warum? Unit 11.)'
    ),
    examples: ['Ich habe {m:einen Bruder}.', 'Ich habe {f:eine Schwester}.'],
    practice: ['mc-eine-schwester'],
  },
  {
    id: 'mc-eine-schwester',
    type: 'multiple_choice',
    topic: 'haben',
    concept: 'haben-family',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich habe ___ Schwester.',
    options: ['einen', 'eine', 'ein'],
    answer: 1,
    explanation: l('die Schwester → eine Schwester (no change).', 'die Schwester → eine Schwester (değişmez).', 'die Schwester → eine Schwester.'),
    examples: ['Ich habe {f:eine Schwester}.'],
  },
  {
    id: 'fill-kinder',
    type: 'fill_blank',
    topic: 'plural',
    concept: 'family-plural',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe zwei ___.',
    accepted: ['Kinder'],
    base: 'das Kind',
    explanation: l('das Kind → die Kinder.', 'das Kind → die Kinder.', 'das Kind → die Kinder.'),
    examples: ['Ich habe zwei **Kinder**.'],
  },
  {
    id: 'build-mein-vater',
    type: 'sentence_builder',
    topic: 'possessive',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 1,
    chips: ['ist', 'Das', 'Vater', 'mein'],
    answers: [['Das', 'ist', 'mein', 'Vater']],
    translation: l('This is my father.', 'Bu benim babam.', 'Das ist mein Vater.'),
    explanation: l('Das ist + mein + noun.', 'Das ist + mein + isim.', 'Das ist + mein + Nomen.'),
    examples: ['Das ist {m:mein Vater}.'],
  },
  {
    id: 'build-eltern',
    type: 'sentence_builder',
    topic: 'plural',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 2,
    chips: ['wohnen', 'Meine Eltern', 'in Ankara'],
    answers: [['Meine Eltern', 'wohnen', 'in Ankara']],
    translation: l('My parents live in Ankara.', 'Annemle babam Ankara’da oturuyor.', 'Meine Eltern wohnen in Ankara.'),
    explanation: l(
      'Plural subject (meine Eltern = sie) → verb with -en: wohnen.',
      'Çoğul özne (meine Eltern = sie) → fiil -en ile: wohnen.',
      'Plural-Subjekt (meine Eltern = sie) → Verb auf -en: wohnen.'
    ),
    examples: ['**Meine Eltern** wohnen in Ankara.'],
  },
  {
    id: 'build-verheiratet',
    type: 'sentence_builder',
    topic: 'status',
    concept: 'status',
    skill: 'grammar',
    difficulty: 1,
    chips: ['verheiratet', 'Ich', 'bin'],
    answers: [['Ich', 'bin', 'verheiratet']],
    translation: l('I am married.', 'Evliyim.', 'Ich bin verheiratet.'),
    explanation: l('Marital status with sein: Ich bin verheiratet / ledig / geschieden.', 'Medeni durum sein ile: Ich bin verheiratet / ledig / geschieden.', 'Familienstand mit sein: Ich bin verheiratet / ledig / geschieden.'),
    examples: ['Ich **bin** verheiratet.'],
  },
  {
    id: 'fix-meine-bruder',
    type: 'error_correction',
    topic: 'possessive',
    concept: 'possessive-mein',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das ist meine Bruder.',
    accepted: ['Das ist mein Bruder.'],
    explanation: l('der Bruder → mein Bruder.', 'der Bruder → mein Bruder.', 'der Bruder → mein Bruder.'),
    examples: ['Das ist {m:mein Bruder}.'],
  },
  {
    id: 'fix-zwei-bruder',
    type: 'error_correction',
    topic: 'plural',
    concept: 'family-plural',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe zwei Bruder.',
    accepted: ['Ich habe zwei Brüder.'],
    explanation: l('Plural of Bruder: Brüder (with ü).', 'Bruder’in çoğulu: Brüder (ü ile).', 'Plural: Brüder (mit ü).'),
    examples: ['Ich habe zwei **Brüder**.'],
  },
  {
    id: 'tr-meine-mutter',
    type: 'translation',
    topic: 'possessive',
    concept: 'possessive-meine',
    skill: 'writing',
    difficulty: 1,
    source: l('This is my mother.', 'Bu benim annem.', 'This is my mother.'),
    accepted: ['Das ist meine Mutter.'],
    explanation: l('die Mutter → meine Mutter.', 'die Mutter → meine Mutter.', 'die Mutter → meine Mutter.'),
    examples: ['Das ist {f:meine Mutter}.'],
  },
  {
    id: 'tr-tochter',
    type: 'translation',
    topic: 'haben',
    concept: 'haben-family',
    skill: 'writing',
    difficulty: 2,
    source: l('I have a daughter.', 'Bir kızım var.', 'I have a daughter.'),
    accepted: ['Ich habe eine Tochter.'],
    explanation: l('die Tochter → eine Tochter.', 'die Tochter → eine Tochter.', 'die Tochter → eine Tochter.'),
    examples: ['Ich habe {f:eine Tochter}.'],
  },
  {
    id: 'dialog-geschwister',
    type: 'dialogue',
    topic: 'haben',
    concept: 'haben-family',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Lena', de: 'Hast du Geschwister?' }],
    options: ['Ja, ich habe einen Bruder.', 'Ja, ich bin einen Bruder.', 'Ja, ich habe ein Bruder.'],
    answer: 0,
    explanation: l('haben + einen Bruder.', 'haben + einen Bruder.', 'haben + einen Bruder.'),
    examples: ['Ja, ich habe {m:einen Bruder}.'],
  },
  {
    id: 'dialog-ledig',
    type: 'dialogue',
    topic: 'status',
    concept: 'status',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Herr Kaya', de: 'Sind Sie verheiratet?' }],
    options: ['Nein, ich bin ledig.', 'Nein, ich habe ledig.', 'Nein, mein ledig.'],
    answer: 0,
    explanation: l('Marital status → sein: ich bin ledig.', 'Medeni durum → sein: ich bin ledig.', 'Familienstand → sein: ich bin ledig.'),
  },
  {
    id: 'mc-eltern',
    type: 'multiple_choice',
    topic: 'vocabulary',
    concept: 'family-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Mein Vater und meine Mutter sind meine ___.',
    options: ['Eltern', 'Geschwister', 'Kinder'],
    answer: 0,
    explanation: l(
      'Vater + Mutter = die Eltern. Bruder + Schwester = die Geschwister.',
      'Vater + Mutter = die Eltern. Bruder + Schwester = die Geschwister.',
      'Vater + Mutter = die Eltern. Bruder + Schwester = die Geschwister.'
    ),
  },

  // --- Reading ------------------------------------------------------------
  {
    id: 'read-mutter',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-oemer',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was ist Ömers Mutter von Beruf?',
    options: ['Lehrerin', 'Ärztin', 'Köchin'],
    answer: 1,
    explanation: l('„Meine Mutter heißt Ayla, sie ist Ärztin.“', '„Meine Mutter heißt Ayla, sie ist Ärztin.“', '„Meine Mutter heißt Ayla, sie ist Ärztin.“'),
  },
  {
    id: 'read-schwestern',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-oemer',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie viele Schwestern hat Ömer?',
    options: ['eine', 'zwei', 'drei'],
    answer: 1,
    explanation: l('„… und zwei Schwestern.“', '„… und zwei Schwestern.“', '„… und zwei Schwestern.“'),
  },
  {
    id: 'read-emre',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-oemer',
    skill: 'reading',
    difficulty: 2,
    statement: 'Emre wohnt in Istanbul.',
    answer: false,
    explanation: l('Emre studies in Berlin – the sisters live in Istanbul.', 'Emre Berlin’de okuyor – kız kardeşler İstanbul’da oturuyor.', 'Emre studiert in Berlin – die Schwestern wohnen in Istanbul.'),
  },
  {
    id: 'read-tochter',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-oemer',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie heißt Ömers Tochter?',
    options: ['Ayla', 'Defne', 'Elif'],
    answer: 1,
    explanation: l('„Sie heißt Defne.“', '„Sie heißt Defne.“', '„Sie heißt Defne.“'),
  },

  // --- Listening ----------------------------------------------------------
  {
    id: 'listen-mia',
    type: 'listening_choice',
    topic: 'possessive',
    concept: 'possessive-meine',
    skill: 'listening',
    difficulty: 1,
    audio: 'Das ist meine Schwester. Sie heißt Mia.',
    question: l('Who is Mia?', 'Mia kim?', 'Wer ist Mia?'),
    options: ['die Schwester', 'die Mutter', 'die Tochter'],
    answer: 0,
    explanation: l('„meine Schwester“', '„meine Schwester“', '„meine Schwester“'),
  },
  {
    id: 'listen-kinder',
    type: 'listening_choice',
    topic: 'plural',
    concept: 'family-plural',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich habe zwei Söhne und eine Tochter.',
    question: l('How many children?', 'Kaç çocuk?', 'Wie viele Kinder?'),
    options: ['2', '3', '4'],
    answer: 1,
    explanation: l('zwei Söhne + eine Tochter = 3.', 'zwei Söhne + eine Tochter = 3.', 'zwei Söhne + eine Tochter = 3.'),
  },
  {
    id: 'listen-vater',
    type: 'listening_choice',
    topic: 'vocabulary',
    concept: 'family-words',
    skill: 'listening',
    difficulty: 2,
    audio: 'Mein Vater ist sechzig Jahre alt.',
    question: l('How old is the father?', 'Baba kaç yaşında?', 'Wie alt ist der Vater?'),
    options: ['16', '60', '66'],
    answer: 1,
    explanation: l('sechzig = 60 (sechzehn = 16).', 'sechzig = 60 (sechzehn = 16).', 'sechzig = 60 (sechzehn = 16).'),
  },
  {
    id: 'listen-ledig',
    type: 'listening_choice',
    topic: 'status',
    concept: 'status',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich bin nicht verheiratet. Ich bin ledig.',
    question: l('What is the marital status?', 'Medeni durumu ne?', 'Welchen Familienstand hat die Person?'),
    options: ['verheiratet', 'ledig', 'geschieden'],
    answer: 1,
    explanation: l('„Ich bin ledig.“ = single.', '„Ich bin ledig.“ = bekâr.', '„Ich bin ledig.“'),
  },

  ...possessiveDrills(),
]

export const UNIT04_FAMILIE: CourseUnit = {
  level: 'A1',
  number: 4,
  slug: 'familie',
  titleDe: 'Familie',
  title: l('Family', 'Aile', 'Familie'),
  goal: l(
    'By the end of this unit you can introduce your family, use mein/meine and dein/deine correctly and ask others about their family.',
    'Bu ünitenin sonunda aileni tanıtabilir, mein/meine ve dein/deine’yi doğru kullanabilir ve başkalarına ailelerini sorabilirsin.',
    'Am Ende dieser Einheit kannst du deine Familie vorstellen, mein/meine und dein/deine richtig verwenden und andere nach ihrer Familie fragen.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'possessive', label: l('mein / meine', 'mein / meine', 'mein / meine') },
    { key: 'haben', label: l('Ich habe einen …', 'Ich habe einen …', 'Ich habe einen …') },
    { key: 'plural', label: l('Family plurals', 'Aile çoğulları', 'Plural in der Familie') },
    { key: 'status', label: l('Marital status', 'Medeni durum', 'Familienstand') },
    { key: 'vocabulary', label: l('Family words', 'Aile kelimeleri', 'Familienwörter') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Your family in German – every word with its article.', 'Ailen Almanca – her kelime artikeliyle.', 'Deine Familie auf Deutsch – jedes Wort mit Artikel.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('The family', 'Aile', 'Die Familie'),
          body: l(
            'Male family members are der, female ones die. Two words exist only in the plural: die Eltern (parents), die Geschwister (siblings).',
            'Erkek aile üyeleri der, kadınlar die alır. İki kelime yalnızca çoğuldur: die Eltern (anne baba), die Geschwister (kardeşler).',
            'Männliche Familienmitglieder: der, weibliche: die. Nur im Plural: die Eltern, die Geschwister.'
          ),
          table: {
            head: [l('der', 'der', 'der'), l('die', 'die', 'die')],
            rows: [
              ['der Vater', 'die Mutter'],
              ['der Bruder', 'die Schwester'],
              ['der Sohn', 'die Tochter'],
              ['der Großvater', 'die Großmutter'],
              ['der Mann', 'die Frau'],
            ],
          },
          tip: l(
            'das Kind is neuter – for boys and girls.',
            'das Kind nötrdür – hem erkek hem kız çocuk için.',
            'das Kind ist neutral – für Jungen und Mädchen.'
          ),
        },
        {
          title: l('my / your: mein, meine – dein, deine', 'benim / senin: mein, meine – dein, deine', 'mein, meine – dein, deine'),
          body: l(
            'mein works exactly like ein: der/das → mein, die → meine. Plural always → meine. Same with dein (your, du) and Ihr (your, Sie).',
            'mein tam olarak ein gibi çalışır: der/das → mein, die → meine. Çoğul her zaman → meine. dein (senin, du) ve Ihr (sizin, Sie) de aynıdır.',
            'mein funktioniert wie ein: der/das → mein, die → meine. Plural immer → meine. Genauso dein (du) und Ihr (Sie).'
          ),
          table: {
            head: [l('', '', ''), l('ich', 'ich', 'ich'), l('du', 'du', 'du'), l('Sie', 'Sie', 'Sie')],
            rows: [
              ['der Vater', 'mein Vater', 'dein Vater', 'Ihr Vater'],
              ['die Mutter', 'meine Mutter', 'deine Mutter', 'Ihre Mutter'],
              ['das Kind', 'mein Kind', 'dein Kind', 'Ihr Kind'],
              ['die Eltern', 'meine Eltern', 'deine Eltern', 'Ihre Eltern'],
            ],
          },
        },
        {
          title: l('Ich habe einen Bruder', 'Ich habe einen Bruder', 'Ich habe einen Bruder'),
          body: l(
            'Learn this as a phrase: after haben, masculine ein becomes einen. eine and ein stay the same. You will learn the reason (Akkusativ) in Unit 11.',
            'Bunu kalıp olarak öğren: haben’dan sonra eril ein, einen olur. eine ve ein aynı kalır. Nedenini (Akkusativ) Ünite 11’de öğreneceksin.',
            'Lerne es als Wendung: Nach haben wird maskulines ein zu einen. eine und ein bleiben. Den Grund (Akkusativ) lernst du in Unit 11.'
          ),
          examples: [
            { de: 'Ich habe {m:einen Bruder}.', translation: l('I have a brother.', 'Bir erkek kardeşim var.', 'maskulin: einen') },
            { de: 'Ich habe {f:eine Schwester} und {n:ein Kind}.', translation: l('I have a sister and a child.', 'Bir kız kardeşim ve bir çocuğum var.', 'feminin/neutral: unverändert') },
            { de: 'Ich habe **keine Geschwister**.', translation: l('I have no siblings.', 'Hiç kardeşim yok.', 'kein im Plural: keine') },
          ],
        },
        {
          title: l('Plural in the family', 'Ailede çoğul', 'Plural in der Familie'),
          body: l(
            'Several family plurals add an umlaut: Bruder → Brüder, Sohn → Söhne, Tochter → Töchter, Mutter → Mütter. A plural subject takes the verb ending -en: Meine Eltern wohnen …',
            'Bazı aile çoğulları umlaut alır: Bruder → Brüder, Sohn → Söhne, Tochter → Töchter, Mutter → Mütter. Çoğul özne fiili -en ile alır: Meine Eltern wohnen …',
            'Mehrere Familienwörter bekommen einen Umlaut: Brüder, Söhne, Töchter, Mütter. Ein Plural-Subjekt hat das Verb auf -en: Meine Eltern wohnen …'
          ),
        },
        {
          title: l('Married, single, divorced', 'Evli, bekâr, boşanmış', 'Familienstand'),
          body: l(
            'With sein: Ich bin verheiratet / ledig / geschieden. Ask: Sind Sie verheiratet? / Bist du verheiratet?',
            'sein ile: Ich bin verheiratet / ledig / geschieden. Sorusu: Sind Sie verheiratet? / Bist du verheiratet?',
            'Mit sein: Ich bin verheiratet / ledig / geschieden. Frage: Sind Sie verheiratet?'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Ömer shows Lena photos of his family on his phone.', 'Ömer telefonunda Lena’ya ailesinin fotoğraflarını gösteriyor.', 'Ömer zeigt Lena Fotos von seiner Familie auf dem Handy.'),
      dialogue: [
        { speaker: 'Lena', de: 'Wer ist das?', translation: l('Who is that?', 'Bu kim?', '') },
        { speaker: 'Ömer', de: 'Das ist **meine Familie**. Hier ist {m:mein Vater} und das ist {f:meine Mutter}.', translation: l('That’s my family. Here is my father and that’s my mother.', 'Bu benim ailem. Burada babam, bu da annem.', '') },
        { speaker: 'Lena', de: 'Und ist das {m:dein Bruder}?', translation: l('And is that your brother?', 'Ya bu senin erkek kardeşin mi?', '') },
        { speaker: 'Ömer', de: 'Ja, das ist Emre. Er ist 19 und studiert in Berlin.', translation: l('Yes, that’s Emre. He’s 19 and studies in Berlin.', 'Evet, bu Emre. 19 yaşında ve Berlin’de okuyor.', '') },
        { speaker: 'Lena', de: 'Hast du auch {f:eine Schwester}?', translation: l('Do you also have a sister?', 'Bir kız kardeşin de var mı?', '') },
        { speaker: 'Ömer', de: 'Ich habe **zwei Schwestern**. **Meine Schwestern** wohnen in Istanbul.', translation: l('I have two sisters. My sisters live in Istanbul.', 'İki kız kardeşim var. Kız kardeşlerim İstanbul’da oturuyor.', '') },
        { speaker: 'Lena', de: 'Und bist du verheiratet?', translation: l('And are you married?', 'Peki evli misin?', '') },
        { speaker: 'Ömer', de: 'Ja. Das ist {f:meine Frau} und das ist {f:unsere Tochter} Defne.', translation: l('Yes. That’s my wife and that’s our daughter Defne.', 'Evet. Bu eşim, bu da kızımız Defne.', '') },
      ],
      examples: [
        { de: 'Das ist {m:mein Bruder}.', translation: l('This is my brother.', 'Bu benim erkek kardeşim.', '') },
        { de: '{f:Meine Schwester} heißt Elif.', translation: l('My sister’s name is Elif.', 'Kız kardeşimin adı Elif.', '') },
        { de: 'Wie heißt {f:deine Mutter}?', translation: l('What is your mother’s name?', 'Annenin adı ne?', '') },
        { de: '{n:Mein Kind} ist drei Jahre alt.', translation: l('My child is three.', 'Çocuğum üç yaşında.', '') },
        { de: '**Meine Eltern** wohnen in Ankara.', translation: l('My parents live in Ankara.', 'Annemle babam Ankara’da oturuyor.', '') },
        { de: 'Ich habe {m:einen Sohn} und {f:eine Tochter}.', translation: l('I have a son and a daughter.', 'Bir oğlum ve bir kızım var.', '') },
        { de: 'Ich **bin** verheiratet.', translation: l('I am married.', 'Evliyim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Family words and mein/meine – recognise first.', 'Aile kelimeleri ve mein/meine – önce tanı.', 'Familienwörter und mein/meine – erst erkennen.'),
      exercises: ['img-grossmutter', 'match-pairs', 'mc-mein-vater', 'mc-meine-mutter', 'sort-mein-meine', 'tf-mein-schwester', 'select-female', 'match-plural', 'mc-eltern'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Now talk about your own family.', 'Şimdi kendi ailen hakkında konuş.', 'Jetzt sprichst du über deine eigene Familie.'),
      exercises: [
        'fill-dein-bruder',
        'mc-ihr-sohn',
        'mc-einen-bruder',
        'fill-kinder',
        'build-mein-vater',
        'build-eltern',
        'build-verheiratet',
        'fix-meine-bruder',
        'fix-zwei-bruder',
        'tr-meine-mutter',
        'tr-tochter',
        'dialog-geschwister',
        'dialog-ledig',
        'mc-meine-eltern',
        'fill-deine-schwester',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Ömer writes about his family.', 'Ömer ailesini anlatıyor.', 'Ömer schreibt über seine Familie.'),
      passage: [
        'Ich heiße Ömer und komme aus Ankara. **Meine Familie** ist groß.',
        '{m:Mein Vater} heißt Hasan, er ist Lehrer. {f:Meine Mutter} heißt Ayla, sie ist Ärztin.',
        'Ich habe {m:einen Bruder} und **zwei Schwestern**.',
        '{m:Mein Bruder} Emre ist 19 und studiert in Berlin. **Meine Schwestern** wohnen in Istanbul.',
        'Ich bin verheiratet und habe {f:eine Tochter}. Sie heißt Defne.',
      ],
      glossary: [
        { de: 'groß', note: l('big', 'büyük', 'nicht klein') },
        { de: 'studieren', note: l('to study (at university)', 'üniversitede okumak', 'an der Universität lernen') },
      ],
      exercises: ['read-mutter', 'read-schwestern', 'read-emre', 'read-tochter'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('People talk about their families.', 'İnsanlar aileleri hakkında konuşuyor.', 'Menschen sprechen über ihre Familie.'),
      exercises: ['listen-mia', 'listen-kinder', 'listen-vater', 'listen-ledig'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Show a family photo and talk about your family.', 'Bir aile fotoğrafı göster ve aileni anlat.', 'Zeig ein Familienfoto und erzähl von deiner Familie.'),
      points: [
        l('Who is it? „Das ist mein … / meine …“', 'Kim? „Das ist mein … / meine …“', 'Wer ist das? „Das ist mein … / meine …“'),
        l('Name and age: „Er/Sie heißt … und ist … Jahre alt.“', 'Adı ve yaşı: „Er/Sie heißt … und ist … Jahre alt.“', 'Name und Alter: „Er/Sie heißt … und ist …“'),
        l('Siblings: „Ich habe einen Bruder / eine Schwester / keine Geschwister.“', 'Kardeşler: „Ich habe einen Bruder / eine Schwester / keine Geschwister.“', 'Geschwister: „Ich habe einen Bruder / eine Schwester / keine Geschwister.“'),
        l('Where do they live? „Meine Eltern wohnen in …“', 'Nerede oturuyorlar? „Meine Eltern wohnen in …“', 'Wo wohnen sie? „Meine Eltern wohnen in …“'),
      ],
      model: ['Das ist meine Familie.', 'Das ist mein Vater. Er heißt Hasan und ist 60.', 'Das ist meine Mutter Ayla. Sie ist Ärztin.', 'Ich habe einen Bruder und zwei Schwestern.', 'Meine Eltern wohnen in Ankara.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write at least 4 sentences about your family.',
        'Ailen hakkında en az 4 cümle yaz.',
        'Schreib mindestens 4 Sätze über deine Familie.'
      ),
      minSentences: 4,
      checks: [
        { label: l('Uses mein / meine', 'mein / meine kullanılmış', 'Mit mein / meine'), pattern: '\\b[Mm]eine?\\s+\\p{Lu}' },
        { label: l('Uses haben (Ich habe …)', 'haben kullanılmış (Ich habe …)', 'Mit haben (Ich habe …)'), pattern: '\\b(habe|hat|hast)\\b' },
        { label: l('Talks about several people (plural)', 'Birden fazla kişiden söz ediyor (çoğul)', 'Mehrere Personen (Plural)'), pattern: '\\b(Eltern|Geschwister|Kinder|Brüder|Schwestern|Söhne|Töchter)\\b' },
      ],
      model: ['Meine Familie ist klein.', 'Meine Eltern wohnen in Bursa.', 'Mein Vater ist Koch und meine Mutter ist Lehrerin.', 'Ich habe eine Schwester. Sie heißt Zeynep.', 'Ich bin ledig und habe keine Kinder.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('mein or meine? 60 seconds!', 'mein mi meine mi? 60 saniye!', 'mein oder meine? 60 Sekunden!'),
      seconds: 60,
      pool: POSSESSIVE_NOUNS.map(({ noun }) => `poss-${noun.toLowerCase()}`),
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Family words with der / die', 'der / die ile aile kelimeleri', 'Familienwörter mit der / die'),
      l('mein / meine, dein / deine, Ihr / Ihre', 'mein / meine, dein / deine, Ihr / Ihre', 'mein / meine, dein / deine, Ihr / Ihre'),
      l('Ich habe einen Bruder / eine Schwester / ein Kind', 'Ich habe einen Bruder / eine Schwester / ein Kind', 'Ich habe einen Bruder / eine Schwester / ein Kind'),
      l('Plurals: Brüder, Schwestern, Kinder, Eltern', 'Çoğullar: Brüder, Schwestern, Kinder, Eltern', 'Plural: Brüder, Schwestern, Kinder, Eltern'),
      l('Ich bin verheiratet / ledig / geschieden', 'Ich bin verheiratet / ledig / geschieden', 'Ich bin verheiratet / ledig / geschieden'),
    ],
    mistakes: [
      { wrong: 'meine Bruder', right: 'mein Bruder', note: l('der → mein', 'der → mein', 'der → mein') },
      { wrong: 'mein Eltern', right: 'meine Eltern', note: l('Plural → meine', 'Çoğul → meine', 'Plural → meine') },
      { wrong: 'Ich habe ein Bruder.', right: 'Ich habe einen Bruder.', note: l('haben + masculine → einen', 'haben + eril → einen', 'haben + maskulin → einen') },
      { wrong: 'zwei Bruder', right: 'zwei Brüder', note: l('Plural with umlaut', 'Umlautlu çoğul', 'Plural mit Umlaut') },
    ],
  },
}
