import type { CourseUnit, Exercise, Gender, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Bus', gender: 'm', plural: 'die Busse', emoji: '🚌', translation: l('bus', 'otobüs', 'Bus'), example: 'Ich fahre mit dem Bus.' },
  { word: 'U-Bahn', gender: 'f', plural: 'die U-Bahnen', emoji: '🚇', translation: l('underground', 'metro', 'U-Bahn'), example: 'Sie fährt mit der U-Bahn.' },
  { word: 'Straßenbahn', gender: 'f', plural: 'die Straßenbahnen', emoji: '🚋', translation: l('tram', 'tramvay', 'Straßenbahn'), example: 'Wir fahren mit der Straßenbahn.' },
  { word: 'Zug', gender: 'm', plural: 'die Züge', emoji: '🚆', translation: l('train', 'tren', 'Zug'), example: 'Er fährt mit dem Zug nach Berlin.' },
  { word: 'Auto', gender: 'n', plural: 'die Autos', emoji: '🚗', translation: l('car', 'araba', 'Auto'), example: 'Ich fahre mit dem Auto.' },
  { word: 'Fahrrad', gender: 'n', plural: 'die Fahrräder', emoji: '🚲', translation: l('bicycle', 'bisiklet', 'Fahrrad'), example: 'Sie fährt mit dem Fahrrad zur Arbeit.' },
  { word: 'Taxi', gender: 'n', plural: 'die Taxis', emoji: '🚕', translation: l('taxi', 'taksi', 'Taxi'), example: 'Wir nehmen ein Taxi.' },
  { word: 'Flugzeug', gender: 'n', plural: 'die Flugzeuge', emoji: '✈️', translation: l('plane', 'uçak', 'Flugzeug'), example: 'Sie fliegen mit dem Flugzeug.' },
  { word: 'zu Fuß', emoji: '🚶', translation: l('on foot', 'yürüyerek', 'zu Fuß'), example: 'Ich gehe zu Fuß.' },
  { word: 'Arbeit', gender: 'f', emoji: '💼', translation: l('work', 'iş', 'Arbeit'), example: 'Ich gehe zur Arbeit.' },
  { word: 'Friseur', gender: 'm', plural: 'die Friseure', emoji: '💇', translation: l('hairdresser', 'kuaför', 'Friseur'), example: 'Morgen gehe ich zum Friseur.' },
  { word: 'Freund', gender: 'm', plural: 'die Freunde', emoji: '👫', translation: l('friend', 'arkadaş', 'Freund'), example: 'Ich bin bei meinem Freund.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Arzt', gender: 'm', plural: 'die Ärzte', translation: l('doctor', 'doktor', 'Arzt') },
  { word: 'Schule', gender: 'f', plural: 'die Schulen', translation: l('school', 'okul', 'Schule') },
  { word: 'Bahnhof', gender: 'm', plural: 'die Bahnhöfe', translation: l('station', 'istasyon', 'Bahnhof') },
  { word: 'Post', gender: 'f', translation: l('post office', 'postane', 'Post') },
  { word: 'Supermarkt', gender: 'm', plural: 'die Supermärkte', translation: l('supermarket', 'süpermarket', 'Supermarkt') },
  { word: 'Bank', gender: 'f', plural: 'die Banken', translation: l('bank', 'banka', 'Bank') },
  { word: 'Mutter', gender: 'f', plural: 'die Mütter', translation: l('mother', 'anne', 'Mutter') },
  { word: 'Oma', gender: 'f', plural: 'die Omas', translation: l('grandma', 'nine', 'Oma') },
  { word: 'mit', translation: l('with, by (transport)', 'ile', 'mit') },
  { word: 'bei', translation: l('at (someone’s place)', '-de (birinin yanında)', 'bei') },
  { word: 'zu', translation: l('to', '-e, -a (yön)', 'zu') },
  { word: 'nach Hause / zu Hause', translation: l('(to) home / at home', 'eve / evde', 'nach Hause / zu Hause') },
]

const DAT: Record<Gender, string> = { m: 'dem', f: 'der', n: 'dem' }
const ZU: Record<Gender, string> = { m: 'zum', f: 'zur', n: 'zum' }
const VEHICLES = ['Bus', 'U-Bahn', 'Straßenbahn', 'Zug', 'Auto', 'Fahrrad', 'Taxi', 'Flugzeug']
const DESTINATIONS = ['Arzt', 'Arbeit', 'Schule', 'Bahnhof', 'Post', 'Supermarkt', 'Bank', 'Friseur']
const ALL = [...VOCAB, ...MORE_VOCAB]

function mitDrills(): Exercise[] {
  return VEHICLES.map((word, i) => {
    const v = ALL.find((x) => x.word === word)!
    const g = v.gender as Gender
    const options = i % 2 === 0 ? ['dem', 'der', 'den'] : ['der', 'den', 'dem']
    return {
      id: `mit-${word.toLowerCase()}`,
      type: 'multiple_choice' as const,
      topic: 'mit',
      concept: `dat-${g}`,
      skill: 'grammar' as const,
      difficulty: 1 as const,
      prompt: `${v.emoji} Ich fahre mit ___ ${word}.`,
      options,
      answer: options.indexOf(DAT[g]),
      explanation: l(
        `mit + Dativ: ${g === 'f' ? 'die' : g === 'm' ? 'der' : 'das'} ${word} → mit ${DAT[g]} ${word}.`,
        `mit + Dativ: ${g === 'f' ? 'die' : g === 'm' ? 'der' : 'das'} ${word} → mit ${DAT[g]} ${word}.`,
        `mit + Dativ: mit ${DAT[g]} ${word}.`
      ),
      examples: [`Ich fahre **mit ${DAT[g]} ${word}**.`],
    }
  })
}

function zuDrills(): Exercise[] {
  return DESTINATIONS.map((word, i) => {
    const v = ALL.find((x) => x.word === word)!
    const g = v.gender as Gender
    const options = i % 2 === 0 ? ['zum', 'zur', 'zu'] : ['zur', 'zu', 'zum']
    return {
      id: `zu-${word.toLowerCase()}`,
      type: 'multiple_choice' as const,
      topic: 'zu',
      concept: `zu-${g}`,
      skill: 'grammar' as const,
      difficulty: 1 as const,
      prompt: `${v.emoji ? `${v.emoji} ` : ''}Ich gehe ___ ${word}.`,
      options,
      answer: options.indexOf(ZU[g]),
      explanation: l(
        `zu + dem = zum (der/das), zu + der = zur (die): ${ZU[g]} ${word}.`,
        `zu + dem = zum (der/das), zu + der = zur (die): ${ZU[g]} ${word}.`,
        `zum (der/das), zur (die): ${ZU[g]} ${word}.`
      ),
      examples: [`Ich gehe **${ZU[g]} ${word}**.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'img-ubahn',
    type: 'image_choice',
    topic: 'mit',
    concept: 'transport',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'mit der U-Bahn',
    options: [
      { emoji: '🚌', label: 'mit dem Bus' },
      { emoji: '🚇', label: 'mit der U-Bahn' },
      { emoji: '🚲', label: 'mit dem Fahrrad' },
      { emoji: '🚶', label: 'zu Fuß' },
    ],
    answer: 1,
    explanation: l('die U-Bahn → mit der U-Bahn.', 'die U-Bahn → mit der U-Bahn.', 'die U-Bahn → mit der U-Bahn.'),
    examples: ['Sie fährt **mit der U-Bahn**.'],
  },
  {
    id: 'match-transport',
    type: 'matching',
    topic: 'mit',
    concept: 'transport',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('How do they travel?', 'Nasıl yolculuk ediyorlar?', 'Wie fahren sie?'),
    pairs: [
      { left: 'mit dem Zug', right: '🚆' },
      { left: 'mit dem Auto', right: '🚗' },
      { left: 'mit der Straßenbahn', right: '🚋' },
      { left: 'zu Fuß', right: '🚶' },
    ],
    explanation: l('mit + Dativ: dem Zug, dem Auto, der Straßenbahn. On foot = zu Fuß.', 'mit + Dativ: dem Zug, dem Auto, der Straßenbahn. Yürüyerek = zu Fuß.', 'mit + Dativ.'),
  },
  {
    id: 'mc-mit-dem-bus',
    type: 'multiple_choice',
    topic: 'mit',
    concept: 'dat-m',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich fahre mit ___ Bus.',
    options: ['dem', 'der', 'den'],
    answer: 0,
    explanation: l(
      'mit always takes the Dativ. der Bus → mit dem Bus. Learn it as one phrase.',
      'mit her zaman Dativ alır. der Bus → mit dem Bus. Tek bir kalıp olarak öğren.',
      'mit + Dativ: der Bus → mit dem Bus.'
    ),
    examples: ['Ich fahre **mit dem Bus**.'],
    practice: ['mit-u-bahn', 'mit-fahrrad'],
  },
  {
    id: 'mc-zur-arbeit',
    type: 'multiple_choice',
    topic: 'zu',
    concept: 'zu-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich gehe ___ Arbeit.',
    options: ['zur', 'zum', 'zu der'],
    answer: 0,
    explanation: l(
      'die Arbeit → zu der → zur Arbeit. (Germans always use the short form zur.)',
      'die Arbeit → zu der → zur Arbeit. (Almanlar her zaman kısa biçim zur’u kullanır.)',
      'die Arbeit → zur Arbeit.'
    ),
    examples: ['Ich gehe **zur Arbeit**.'],
    practice: ['zu-arzt', 'zu-schule'],
  },
  {
    id: 'sort-zum-zur',
    type: 'categorize',
    topic: 'zu',
    concept: 'zu-mixed',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('zum or zur?', 'zum mu zur mu?', 'zum oder zur?'),
    categories: ['zum', 'zur'],
    items: [
      { text: 'Arzt', category: 0 },
      { text: 'Schule', category: 1 },
      { text: 'Bahnhof', category: 0 },
      { text: 'Post', category: 1 },
      { text: 'Friseur', category: 0 },
      { text: 'Bank', category: 1 },
    ],
    explanation: l('der → zum (Arzt, Bahnhof, Friseur). die → zur (Schule, Post, Bank).', 'der → zum (Arzt, Bahnhof, Friseur). die → zur (Schule, Post, Bank).', 'der/das → zum, die → zur.'),
  },
  {
    id: 'tf-bei-meiner',
    type: 'true_false',
    topic: 'bei',
    concept: 'bei-possessive',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Am Wochenende bin ich bei meiner Oma.',
    answer: true,
    explanation: l(
      'bei + Dativ: die Oma → bei meiner Oma (meine → meiner).',
      'bei + Dativ: die Oma → bei meiner Oma (meine → meiner).',
      'bei + Dativ: bei meiner Oma.'
    ),
    examples: ['Ich bin **bei meiner Oma**.'],
  },
  {
    id: 'select-correct',
    type: 'multiple_select',
    topic: 'mit',
    concept: 'dat-mixed',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Select all correct phrases.', 'Tüm doğru ifadeleri seç.', 'Wähle alle richtigen Wendungen.'),
    options: ['mit dem Auto', 'mit das Auto', 'zur Schule', 'zum Schule', 'bei meinem Bruder', 'bei mein Bruder'],
    answers: [0, 2, 4],
    explanation: l('Dativ: dem Auto, zur Schule, meinem Bruder.', 'Dativ: dem Auto, zur Schule, meinem Bruder.', 'Dativ: dem Auto, zur Schule, meinem Bruder.'),
  },
  {
    id: 'match-forms',
    type: 'matching',
    topic: 'forms',
    concept: 'dat-forms',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Nominativ → Dativ', 'Nominativ → Dativ', 'Nominativ → Dativ'),
    pairs: [
      { left: 'der Bus', right: 'mit dem Bus' },
      { left: 'die U-Bahn', right: 'mit der U-Bahn' },
      { left: 'das Auto', right: 'mit dem Auto' },
      { left: 'mein Freund', right: 'mit meinem Freund' },
    ],
    explanation: l('der/das → dem, die → der, mein → meinem.', 'der/das → dem, die → der, mein → meinem.', 'der/das → dem, die → der.'),
  },

  // --- Practice 2: use --------------------------------------------------
  {
    id: 'fill-mit-dem',
    type: 'fill_blank',
    topic: 'mit',
    concept: 'dat-n',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Lena fährt mit ___ Fahrrad zur Uni.',
    accepted: ['dem'],
    base: 'das Fahrrad',
    explanation: l('das Fahrrad → mit dem Fahrrad.', 'das Fahrrad → mit dem Fahrrad.', 'das Fahrrad → mit dem Fahrrad.'),
    examples: ['Lena fährt **mit dem Fahrrad**.'],
  },
  {
    id: 'fill-zum',
    type: 'fill_blank',
    topic: 'zu',
    concept: 'zu-m',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Ich habe Zahnschmerzen. Ich gehe ___ Zahnarzt.',
    accepted: ['zum'],
    base: 'der Zahnarzt',
    explanation: l('der Zahnarzt → zum Zahnarzt.', 'der Zahnarzt → zum Zahnarzt.', 'der Zahnarzt → zum Zahnarzt.'),
    examples: ['Ich gehe **zum Zahnarzt**.'],
  },
  {
    id: 'fill-beim',
    type: 'fill_blank',
    topic: 'bei',
    concept: 'bei-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wo ist Paul? – Er ist ___ Friseur.',
    accepted: ['beim'],
    base: 'bei + dem',
    explanation: l('bei + dem = beim Friseur.', 'bei + dem = beim Friseur.', 'bei + dem = beim.'),
    examples: ['Er ist **beim Friseur**.'],
  },
  {
    id: 'build-mit-zug',
    type: 'sentence_builder',
    topic: 'mit',
    concept: 'dat-m',
    skill: 'grammar',
    difficulty: 1,
    chips: ['mit dem Zug', 'nach Berlin', 'fahre', 'Ich'],
    answers: [['Ich', 'fahre', 'mit dem Zug', 'nach Berlin']],
    translation: l('I’m going to Berlin by train.', 'Trenle Berlin’e gidiyorum.', 'Ich fahre mit dem Zug nach Berlin.'),
    explanation: l(
      'Order tip: how (mit dem Zug) before where to (nach Berlin).',
      'Sıralama ipucu: nasıl (mit dem Zug), nereye’den (nach Berlin) önce gelir.',
      'Erst wie (mit dem Zug), dann wohin (nach Berlin).'
    ),
    examples: ['Ich fahre **mit dem Zug** nach Berlin.'],
  },
  {
    id: 'build-zur-schule',
    type: 'sentence_builder',
    topic: 'zu',
    concept: 'zu-f',
    skill: 'grammar',
    difficulty: 1,
    chips: ['zur Schule', 'Die Kinder', 'gehen', 'zu Fuß'],
    answers: [['Die Kinder', 'gehen', 'zu Fuß', 'zur Schule']],
    translation: l('The children walk to school.', 'Çocuklar okula yürüyerek gidiyor.', 'Die Kinder gehen zu Fuß zur Schule.'),
    explanation: l('zu Fuß (how) + zur Schule (where to).', 'zu Fuß (nasıl) + zur Schule (nereye).', 'zu Fuß + zur Schule.'),
    examples: ['Die Kinder gehen **zu Fuß zur Schule**.'],
  },
  {
    id: 'build-bei',
    type: 'sentence_builder',
    topic: 'bei',
    concept: 'bei-possessive',
    skill: 'grammar',
    difficulty: 2,
    chips: ['bei meiner Mutter', 'wohnt', 'Mein Sohn'],
    answers: [['Mein Sohn', 'wohnt', 'bei meiner Mutter']],
    translation: l('My son lives with my mother.', 'Oğlum annemin yanında kalıyor.', 'Mein Sohn wohnt bei meiner Mutter.'),
    explanation: l('bei + meine Mutter → bei meiner Mutter.', 'bei + meine Mutter → bei meiner Mutter.', 'bei meiner Mutter.'),
    examples: ['Mein Sohn wohnt **bei meiner Mutter**.'],
  },
  {
    id: 'fix-mit-der-bus',
    type: 'error_correction',
    topic: 'mit',
    concept: 'dat-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich fahre mit der Bus.',
    accepted: ['Ich fahre mit dem Bus.'],
    explanation: l('der Bus (masculine) → mit dem Bus.', 'der Bus (eril) → mit dem Bus.', 'der Bus → mit dem Bus.'),
    examples: ['Ich fahre **mit dem Bus**.'],
  },
  {
    id: 'fix-zu-der',
    type: 'error_correction',
    topic: 'zu',
    concept: 'zu-f',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich gehe zum Post.',
    accepted: ['Ich gehe zur Post.'],
    explanation: l('die Post → zur Post.', 'die Post → zur Post.', 'die Post → zur Post.'),
    examples: ['Ich gehe **zur Post**.'],
  },
  {
    id: 'tr-arbeit',
    type: 'translation',
    topic: 'mit',
    concept: 'dat-f',
    skill: 'writing',
    difficulty: 2,
    source: l('I go to work by underground.', 'İşe metroyla gidiyorum.', 'I go to work by underground.'),
    accepted: ['Ich fahre mit der U-Bahn zur Arbeit.', 'Ich fahre mit der U-Bahn zur Arbeit'],
    hint: l('underground = die U-Bahn, by = mit', 'metro = die U-Bahn, ile = mit', 'underground = die U-Bahn'),
    explanation: l('mit der U-Bahn + zur Arbeit.', 'mit der U-Bahn + zur Arbeit.', 'mit der U-Bahn zur Arbeit.'),
    examples: ['Ich fahre **mit der U-Bahn zur Arbeit**.'],
  },
  {
    id: 'tr-arzt',
    type: 'translation',
    topic: 'zu',
    concept: 'zu-m',
    skill: 'writing',
    difficulty: 1,
    source: l('I’m going to the doctor.', 'Doktora gidiyorum.', 'I’m going to the doctor.'),
    accepted: ['Ich gehe zum Arzt.'],
    explanation: l('der Arzt → zum Arzt.', 'der Arzt → zum Arzt.', 'der Arzt → zum Arzt.'),
    examples: ['Ich gehe **zum Arzt**.'],
  },
  {
    id: 'dialog-wie-kommst',
    type: 'dialogue',
    topic: 'mit',
    concept: 'dat-mixed',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Kollegin', de: 'Wie kommst du zur Arbeit?' }],
    options: ['Mit dem Fahrrad.', 'Mit das Fahrrad.', 'Mit den Fahrrad.'],
    answer: 0,
    explanation: l('das Fahrrad → mit dem Fahrrad.', 'das Fahrrad → mit dem Fahrrad.', 'mit dem Fahrrad.'),
  },
  {
    id: 'dialog-wohin',
    type: 'dialogue',
    topic: 'zu',
    concept: 'zu-mixed',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Nachbar', de: 'Wohin gehst du?' }],
    options: ['Zum Supermarkt.', 'Zur Supermarkt.', 'Zu Supermarkt.'],
    answer: 0,
    explanation: l('der Supermarkt → zum Supermarkt.', 'der Supermarkt → zum Supermarkt.', 'zum Supermarkt.'),
  },
  {
    id: 'mc-hause',
    type: 'multiple_choice',
    topic: 'zu',
    concept: 'hause',
    skill: 'vocabulary',
    difficulty: 2,
    prompt: 'Es ist spät. Ich gehe jetzt ___.',
    options: ['nach Hause', 'zu Hause', 'zum Haus'],
    answer: 0,
    explanation: l(
      'Direction home = nach Hause. Being at home = zu Hause (Ich bin zu Hause).',
      'Eve doğru = nach Hause. Evde olmak = zu Hause (Ich bin zu Hause).',
      'nach Hause (Richtung) – zu Hause (Ort).'
    ),
    examples: ['Ich gehe **nach Hause**.', 'Ich bin **zu Hause**.'],
  },

  // --- Reading ------------------------------------------------------
  {
    id: 'read-anna',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie fährt Anna zur Arbeit?',
    options: ['mit der Straßenbahn', 'mit dem Auto', 'mit dem Fahrrad'],
    answer: 0,
    explanation: l('„Anna fährt mit der Straßenbahn zur Arbeit.“', '„Anna fährt mit der Straßenbahn zur Arbeit.“', '„mit der Straßenbahn“'),
  },
  {
    id: 'read-mann',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie kommt ihr Mann zur Arbeit?',
    options: ['mit dem Fahrrad', 'zu Fuß', 'mit dem Bus'],
    answer: 0,
    explanation: l('„Ihr Mann fährt mit dem Fahrrad.“', '„Ihr Mann fährt mit dem Fahrrad.“', '„mit dem Fahrrad“'),
  },
  {
    id: 'read-kinder',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 1,
    statement: 'Die Kinder fahren mit dem Bus zur Schule.',
    answer: false,
    explanation: l('„Die Kinder gehen zu Fuß zur Schule.“', '„Die Kinder gehen zu Fuß zur Schule.“', '„zu Fuß zur Schule“'),
  },
  {
    id: 'read-samstag',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-weg',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wo ist die Familie am Samstag?',
    options: ['bei Annas Eltern', 'beim Arzt', 'zu Hause'],
    answer: 0,
    explanation: l('„Am Samstag sind sie bei Annas Eltern in Potsdam.“', '„Am Samstag sind sie bei Annas Eltern in Potsdam.“', '„bei Annas Eltern“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-bus',
    type: 'listening_choice',
    topic: 'mit',
    concept: 'transport',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich fahre jeden Tag mit dem Bus.',
    question: l('How does the person travel?', 'Kişi nasıl gidiyor?', 'Wie fährt die Person?'),
    options: ['🚌', '🚆', '🚲'],
    answer: 0,
    explanation: l('„mit dem Bus“', '„mit dem Bus“', '„mit dem Bus“'),
  },
  {
    id: 'listen-zum',
    type: 'listening_choice',
    topic: 'zu',
    concept: 'zu-m',
    skill: 'listening',
    difficulty: 1,
    audio: 'Morgen gehe ich zum Friseur.',
    question: l('Where is the person going tomorrow?', 'Kişi yarın nereye gidiyor?', 'Wohin geht die Person morgen?'),
    options: ['💇 zum Friseur', '🩺 zum Arzt', '🏦 zur Bank'],
    answer: 0,
    explanation: l('„zum Friseur“', '„zum Friseur“', '„zum Friseur“'),
  },
  {
    id: 'listen-bei',
    type: 'listening_choice',
    topic: 'bei',
    concept: 'bei-possessive',
    skill: 'listening',
    difficulty: 2,
    audio: 'Heute Abend bin ich bei meinem Bruder.',
    question: l('Where is the person tonight?', 'Kişi bu akşam nerede?', 'Wo ist die Person heute Abend?'),
    options: ['beim Bruder', 'bei der Schwester', 'zu Hause'],
    answer: 0,
    explanation: l('„bei meinem Bruder“', '„bei meinem Bruder“', '„bei meinem Bruder“'),
  },
  {
    id: 'listen-fuss',
    type: 'listening_choice',
    topic: 'mit',
    concept: 'transport',
    skill: 'listening',
    difficulty: 1,
    audio: 'Die Schule ist nah. Wir gehen zu Fuß.',
    question: l('How do they get to school?', 'Okula nasıl gidiyorlar?', 'Wie kommen sie zur Schule?'),
    options: ['🚶', '🚗', '🚋'],
    answer: 0,
    explanation: l('„zu Fuß“ = on foot.', '„zu Fuß“ = yürüyerek.', '„zu Fuß“'),
  },

  ...mitDrills(),
  ...zuDrills(),
]

export const UNIT19_DATIV: CourseUnit = {
  level: 'A1',
  number: 19,
  slug: 'dativ',
  titleDe: 'Dativ – Einführung',
  title: l('Dative – introduction', 'Dativ – giriş', 'Dativ – Einführung'),
  goal: l(
    'By the end of this unit you can say how you travel (mit dem Bus), where you go (zum Arzt, zur Arbeit) and where you are (bei meinem Freund) – using the Dativ in everyday phrases.',
    'Bu ünitenin sonunda nasıl yolculuk ettiğini (mit dem Bus), nereye gittiğini (zum Arzt, zur Arbeit) ve nerede olduğunu (bei meinem Freund) söyleyebilirsin – günlük kalıplarda Dativ kullanarak.',
    'Am Ende dieser Einheit sagst du, womit du fährst, wohin du gehst und wo du bist – mit dem Dativ in Alltagswendungen.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'mit', label: l('mit dem / der', 'mit dem / der', 'mit dem / der') },
    { key: 'zu', label: l('zum / zur', 'zum / zur', 'zum / zur') },
    { key: 'bei', label: l('bei / beim', 'bei / beim', 'bei / beim') },
    { key: 'forms', label: l('Dativ forms', 'Dativ biçimleri', 'Dativformen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('How do you get around?', 'Nasıl ulaşım sağlıyorsun?', 'Wie bist du unterwegs?'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Learn the Dativ through phrases', 'Dativ’i kalıplarla öğren', 'Dativ in Wendungen'),
          body: l(
            'Some small words always take the Dativ: mit, bei, zu (also aus, nach, von, seit). Don’t learn a big table first – learn these phrases.',
            'Bazı küçük kelimeler her zaman Dativ alır: mit, bei, zu (ayrıca aus, nach, von, seit). Önce büyük bir tablo öğrenme – bu kalıpları öğren.',
            'mit, bei, zu (auch aus, nach, von, seit) + Dativ. Lerne Wendungen statt Tabellen.'
          ),
          examples: [
            { de: 'Ich fahre **mit dem Bus**.', translation: l('I go by bus.', 'Otobüsle gidiyorum.', 'mit') },
            { de: 'Ich bin **bei meinem Freund**.', translation: l('I’m at my friend’s place.', 'Arkadaşımın yanındayım.', 'bei') },
            { de: 'Ich gehe **zum Arzt**.', translation: l('I’m going to the doctor.', 'Doktora gidiyorum.', 'zu') },
          ],
        },
        {
          title: l('The pattern', 'Kalıp', 'Das Muster'),
          body: l(
            'In the Dativ: der and das become dem, die becomes der. The same with ein/mein: einem/meinem, einer/meiner.',
            'Dativ’de: der ve das → dem, die → der olur. ein/mein de aynı: einem/meinem, einer/meiner.',
            'Dativ: der/das → dem, die → der; einem/meinem, einer/meiner.'
          ),
          table: {
            head: [l('', '', ''), l('Nominativ', 'Nominativ', 'Nominativ'), l('Dativ', 'Dativ', 'Dativ')],
            rows: [
              ['maskulin', 'der / mein Bus', 'mit dem / meinem Bus'],
              ['feminin', 'die / meine U-Bahn', 'mit der / meiner U-Bahn'],
              ['neutral', 'das / mein Auto', 'mit dem / meinem Auto'],
            ],
          },
          tip: l(
            'Short forms: zu + dem = zum, zu + der = zur, bei + dem = beim, in + dem = im.',
            'Kısa biçimler: zu + dem = zum, zu + der = zur, bei + dem = beim, in + dem = im.',
            'zum, zur, beim, im.'
          ),
        },
        {
          title: l('Home: nach Hause or zu Hause?', 'Ev: nach Hause mı zu Hause mı?', 'nach Hause oder zu Hause?'),
          body: l(
            'Going home: Ich gehe nach Hause. Being at home: Ich bin zu Hause. On foot: zu Fuß (no article).',
            'Eve gitmek: Ich gehe nach Hause. Evde olmak: Ich bin zu Hause. Yürüyerek: zu Fuß (artikelsiz).',
            'nach Hause (Richtung), zu Hause (Ort), zu Fuß.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two neighbours meet in the morning.', 'İki komşu sabah karşılaşıyor.', 'Zwei Nachbarn treffen sich morgens.'),
      dialogue: [
        { speaker: 'Herr Lang', de: 'Guten Morgen! Gehen Sie **zur Arbeit**?', translation: l('Good morning! Are you going to work?', 'Günaydın! İşe mi gidiyorsunuz?', '') },
        { speaker: 'Frau Aydın', de: 'Nein, heute nicht. Ich gehe **zum Arzt**.', translation: l('No, not today. I’m going to the doctor.', 'Hayır, bugün değil. Doktora gidiyorum.', '') },
        { speaker: 'Herr Lang', de: 'Oh, fahren Sie **mit dem Bus**?', translation: l('Oh, are you going by bus?', 'Otobüsle mi gidiyorsunuz?', '') },
        { speaker: 'Frau Aydın', de: 'Nein, **mit der Straßenbahn**. Und Sie?', translation: l('No, by tram. And you?', 'Hayır, tramvayla. Ya siz?', '') },
        { speaker: 'Herr Lang', de: 'Ich gehe **zur Post** und dann **zum Friseur**. Ich gehe **zu Fuß**.', translation: l('I’m going to the post office and then to the hairdresser’s. I’m walking.', 'Postaneye, sonra kuaföre gidiyorum. Yürüyerek gidiyorum.', '') },
        { speaker: 'Frau Aydın', de: 'Und heute Abend? Sind Sie **zu Hause**?', translation: l('And this evening? Will you be at home?', 'Peki bu akşam? Evde misiniz?', '') },
        { speaker: 'Herr Lang', de: 'Nein, ich bin **bei meiner Tochter**.', translation: l('No, I’m at my daughter’s.', 'Hayır, kızımın yanındayım.', '') },
      ],
      examples: [
        { de: 'Ich fahre **mit dem Bus**.', translation: l('I go by bus.', 'Otobüsle gidiyorum.', '') },
        { de: 'Sie fährt **mit der U-Bahn**.', translation: l('She goes by underground.', 'Metroyla gidiyor.', '') },
        { de: 'Wir fahren **mit dem Auto** nach Hamburg.', translation: l('We drive to Hamburg.', 'Arabayla Hamburg’a gidiyoruz.', '') },
        { de: 'Ich gehe **zum Arzt**.', translation: l('I’m going to the doctor.', 'Doktora gidiyorum.', '') },
        { de: 'Die Kinder gehen **zur Schule**.', translation: l('The children go to school.', 'Çocuklar okula gidiyor.', '') },
        { de: 'Ich bin **bei meinem Freund**.', translation: l('I’m at my friend’s.', 'Arkadaşımın yanındayım.', '') },
        { de: 'Er ist **beim Friseur**.', translation: l('He’s at the hairdresser’s.', 'Kuaförde.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('mit, zu, bei – and the Dativ after them.', 'mit, zu, bei – ve onlardan sonra gelen Dativ.', 'mit, zu, bei – und der Dativ danach.'),
      exercises: ['img-ubahn', 'match-transport', 'mc-mit-dem-bus', 'mc-zur-arbeit', 'sort-zum-zur', 'tf-bei-meiner', 'select-correct', 'match-forms', 'mit-zug'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Say how you travel and where you go.', 'Nasıl gittiğini ve nereye gittiğini söyle.', 'Sag, wie und wohin du fährst.'),
      exercises: [
        'fill-mit-dem',
        'fill-zum',
        'fill-beim',
        'build-mit-zug',
        'build-zur-schule',
        'build-bei',
        'fix-mit-der-bus',
        'fix-zu-der',
        'tr-arbeit',
        'tr-arzt',
        'dialog-wie-kommst',
        'dialog-wohin',
        'mc-hause',
        'zu-bank',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('How does Anna’s family get around?', 'Anna’nın ailesi nasıl ulaşım sağlıyor?', 'Wie ist Annas Familie unterwegs?'),
      passage: [
        'Anna wohnt in Berlin. Sie fährt **mit der Straßenbahn** **zur Arbeit**.',
        'Ihr Mann fährt **mit dem Fahrrad**. Die Kinder gehen **zu Fuß** **zur Schule** – die Schule ist nah.',
        'Am Samstag fahren alle **mit dem Zug** nach Potsdam. Dort sind sie **bei Annas Eltern**.',
        'Am Sonntagabend fahren sie wieder **nach Hause**.',
      ],
      glossary: [
        { de: 'alle', note: l('everyone', 'herkes', 'jeder') },
        { de: 'dort', note: l('there', 'orada', 'an diesem Ort') },
        { de: 'wieder', note: l('again', 'yine', 'noch einmal') },
      ],
      exercises: ['read-anna', 'read-mann', 'read-kinder', 'read-samstag'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('How and where to?', 'Nasıl ve nereye?', 'Wie und wohin?'),
      exercises: ['listen-bus', 'listen-zum', 'listen-bei', 'listen-fuss'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Talk about your week on the move.', 'Haftan boyunca nerelere nasıl gittiğini anlat.', 'Erzähl, wie du in der Woche unterwegs bist.'),
      points: [
        l('How do you get to work/course? „Ich fahre mit …“', 'İşe/kursa nasıl gidiyorsun? „Ich fahre mit …“', 'Wie kommst du zur Arbeit? „Ich fahre mit …“'),
        l('Where do you go this week? „Ich gehe zum / zur …“', 'Bu hafta nereye gidiyorsun? „Ich gehe zum / zur …“', 'Wohin gehst du diese Woche?'),
        l('Who do you visit? „Ich bin bei …“', 'Kimi ziyaret ediyorsun? „Ich bin bei …“', 'Bei wem bist du?'),
      ],
      model: ['Ich fahre mit der U-Bahn zur Arbeit.', 'Am Dienstag gehe ich zum Arzt.', 'Am Freitag gehe ich zur Post.', 'Am Wochenende bin ich bei meinen Eltern.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write at least 4 sentences: how do you travel, where do you go, where are you this week?',
        'En az 4 cümle yaz: nasıl yolculuk ediyorsun, nereye gidiyorsun, bu hafta neredesin?',
        'Schreib mindestens 4 Sätze: Wie fährst du, wohin gehst du, wo bist du diese Woche?'
      ),
      minSentences: 4,
      checks: [
        { label: l('mit + Dativ', 'mit + Dativ', 'mit + Dativ'), pattern: '\\bmit (dem|der|einem|einer|meinem|meiner)\\b' },
        { label: l('zum / zur', 'zum / zur', 'zum / zur'), pattern: '\\b(zum|zur)\\b' },
        { label: l('bei / beim', 'bei / beim', 'bei / beim'), pattern: '\\b(bei|beim)\\b' },
      ],
      model: ['Ich fahre jeden Tag mit dem Bus zur Arbeit.', 'Am Montag gehe ich zum Friseur.', 'Am Mittwoch fahre ich mit der U-Bahn zur Schule.', 'Am Wochenende bin ich bei meiner Schwester.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('dem or der, zum or zur – 60 seconds.', 'dem mi der mi, zum mu zur mu – 60 saniye.', 'dem oder der, zum oder zur – 60 Sekunden.'),
      seconds: 60,
      pool: [...VEHICLES.map((w) => `mit-${w.toLowerCase()}`), ...DESTINATIONS.map((w) => `zu-${w.toLowerCase()}`)],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('mit + Dativ: mit dem Bus, mit der U-Bahn', 'mit + Dativ: mit dem Bus, mit der U-Bahn', 'mit dem Bus, mit der U-Bahn'),
      l('zu + Dativ: zum Arzt, zur Arbeit', 'zu + Dativ: zum Arzt, zur Arbeit', 'zum Arzt, zur Arbeit'),
      l('bei + Dativ: beim Friseur, bei meiner Mutter', 'bei + Dativ: beim Friseur, bei meiner Mutter', 'beim Friseur, bei meiner Mutter'),
      l('der/das → dem, die → der', 'der/das → dem, die → der', 'der/das → dem, die → der'),
      l('nach Hause / zu Hause / zu Fuß', 'nach Hause / zu Hause / zu Fuß', 'nach Hause / zu Hause / zu Fuß'),
    ],
    mistakes: [
      { wrong: 'mit der Bus', right: 'mit dem Bus', note: l('der Bus → dem.', 'der Bus → dem.', 'der Bus → dem.') },
      { wrong: 'zum Schule', right: 'zur Schule', note: l('die Schule → zur.', 'die Schule → zur.', 'die → zur.') },
      { wrong: 'mit das Auto', right: 'mit dem Auto', note: l('das → dem.', 'das → dem.', 'das → dem.') },
      { wrong: 'Ich gehe zu Hause.', right: 'Ich gehe nach Hause.', note: l('Direction → nach Hause.', 'Yön → nach Hause.', 'Richtung → nach Hause.') },
    ],
  },
}
