import type { CourseUnit, Exercise, Gender, VocabItem } from '../types'

const G: Record<Gender, string> = { m: 'der', f: 'die', n: 'das' }

/** Everyday objects – always taught together with their article. */
const VOCAB: VocabItem[] = [
  { word: 'Apfel', gender: 'm', plural: 'die Äpfel', emoji: '🍎', translation: { en: 'apple', tr: 'elma', de: 'Apfel' }, example: 'Der Apfel ist rot.' },
  { word: 'Hund', gender: 'm', plural: 'die Hunde', emoji: '🐕', translation: { en: 'dog', tr: 'köpek', de: 'Hund' }, example: 'Der Hund ist klein.' },
  { word: 'Stuhl', gender: 'm', plural: 'die Stühle', emoji: '🪑', translation: { en: 'chair', tr: 'sandalye', de: 'Stuhl' }, example: 'Der Stuhl ist bequem.' },
  { word: 'Schlüssel', gender: 'm', plural: 'die Schlüssel', emoji: '🔑', translation: { en: 'key', tr: 'anahtar', de: 'Schlüssel' }, example: 'Der Schlüssel ist alt.' },
  { word: 'Banane', gender: 'f', plural: 'die Bananen', emoji: '🍌', translation: { en: 'banana', tr: 'muz', de: 'Banane' }, example: 'Die Banane ist gelb.' },
  { word: 'Tür', gender: 'f', plural: 'die Türen', emoji: '🚪', translation: { en: 'door', tr: 'kapı', de: 'Tür' }, example: 'Die Tür ist offen.' },
  { word: 'Tasche', gender: 'f', plural: 'die Taschen', emoji: '👜', translation: { en: 'bag', tr: 'çanta', de: 'Tasche' }, example: 'Die Tasche ist neu.' },
  { word: 'Lampe', gender: 'f', plural: 'die Lampen', emoji: '💡', translation: { en: 'lamp', tr: 'lamba', de: 'Lampe' }, example: 'Die Lampe ist modern.' },
  { word: 'Haus', gender: 'n', plural: 'die Häuser', emoji: '🏠', translation: { en: 'house', tr: 'ev', de: 'Haus' }, example: 'Das Haus ist groß.' },
  { word: 'Handy', gender: 'n', plural: 'die Handys', emoji: '📱', translation: { en: 'mobile phone', tr: 'cep telefonu', de: 'Handy' }, example: 'Das Handy ist teuer.' },
  { word: 'Buch', gender: 'n', plural: 'die Bücher', emoji: '📖', translation: { en: 'book', tr: 'kitap', de: 'Buch' }, example: 'Das Buch ist spannend.' },
  { word: 'Auto', gender: 'n', plural: 'die Autos', emoji: '🚗', translation: { en: 'car', tr: 'araba', de: 'Auto' }, example: 'Das Auto ist schnell.' },
]

/** Further nouns used in the exercises (also shown in the word list). */
const MORE_VOCAB: VocabItem[] = [
  { word: 'Tisch', gender: 'm', plural: 'die Tische', translation: { en: 'table', tr: 'masa', de: 'Tisch' } },
  { word: 'Computer', gender: 'm', plural: 'die Computer', emoji: '💻', translation: { en: 'computer', tr: 'bilgisayar', de: 'Computer' } },
  { word: 'Katze', gender: 'f', plural: 'die Katzen', emoji: '🐈', translation: { en: 'cat', tr: 'kedi', de: 'Katze' } },
  { word: 'Uhr', gender: 'f', plural: 'die Uhren', emoji: '⌚', translation: { en: 'watch, clock', tr: 'saat', de: 'Uhr' } },
  { word: 'Flasche', gender: 'f', plural: 'die Flaschen', emoji: '🍾', translation: { en: 'bottle', tr: 'şişe', de: 'Flasche' } },
  { word: 'Fenster', gender: 'n', plural: 'die Fenster', emoji: '🪟', translation: { en: 'window', tr: 'pencere', de: 'Fenster' } },
  { word: 'Bett', gender: 'n', plural: 'die Betten', emoji: '🛏️', translation: { en: 'bed', tr: 'yatak', de: 'Bett' } },
  { word: 'Fahrrad', gender: 'n', plural: 'die Fahrräder', emoji: '🚲', translation: { en: 'bicycle', tr: 'bisiklet', de: 'Fahrrad' } },
  { word: 'Kind', gender: 'n', plural: 'die Kinder', emoji: '🧒', translation: { en: 'child', tr: 'çocuk', de: 'Kind' } },
]

const GENDER_WORD = {
  m: { en: 'masculine', tr: 'eril (maskulin)', de: 'maskulin' },
  f: { en: 'feminine', tr: 'dişil (feminin)', de: 'feminin' },
  n: { en: 'neuter', tr: 'nötr (neutrum)', de: 'neutral' },
} as const

/**
 * Generated drill: "___ Apfel" → der/die/das for every noun. Used by the
 * timed round and as fresh variations in spaced review, so learners don't
 * see the identical question again.
 */
function articleDrills(items: VocabItem[]): Exercise[] {
  return items
    .filter((v): v is VocabItem & { gender: Gender } => Boolean(v.gender))
    .map((v) => ({
      id: `art-${v.word.toLowerCase()}`,
      type: 'multiple_choice' as const,
      topic: 'articles',
      concept: `gender-${v.gender}`,
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `${v.emoji ? `${v.emoji} ` : ''}___ ${v.word}`,
      options: ['der', 'die', 'das'],
      answer: ['m', 'f', 'n'].indexOf(v.gender),
      explanation: {
        en: `${v.word} is ${GENDER_WORD[v.gender].en}: ${G[v.gender]} ${v.word}. Learn the noun together with its article.`,
        tr: `${v.word} ${GENDER_WORD[v.gender].tr}: ${G[v.gender]} ${v.word}. İsmi her zaman artikeliyle birlikte öğren.`,
        de: `${v.word} ist ${GENDER_WORD[v.gender].de}: ${G[v.gender]} ${v.word}. Lerne das Nomen immer mit Artikel.`,
      },
      examples: [`{${v.gender}:${G[v.gender].replace(/^./, (c) => c.toUpperCase())} ${v.word}} ist hier.`],
    }))
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise --------------------------------------------
  {
    id: 'img-tasche',
    type: 'image_choice',
    topic: 'vocabulary',
    concept: 'vocab-objects',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'die Tasche',
    options: [
      { emoji: '🔑', label: 'der Schlüssel' },
      { emoji: '👜', label: 'die Tasche' },
      { emoji: '📱', label: 'das Handy' },
      { emoji: '🍎', label: 'der Apfel' },
    ],
    answer: 1,
    instructions: { en: 'Which picture shows this word?', tr: 'Hangi resim bu kelimeyi gösteriyor?', de: 'Welches Bild passt zum Wort?' },
    explanation: {
      en: 'die Tasche = the bag. Always remember the noun with its article: die Tasche.',
      tr: 'die Tasche = çanta. İsmi her zaman artikeliyle hatırla: die Tasche.',
      de: 'die Tasche: Darin trägst du Sachen. Merke dir das Nomen immer mit Artikel.',
    },
    examples: ['{f:Die Tasche} ist neu.'],
  },
  {
    id: 'match-pictures',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'vocab-objects',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: { en: 'Match each word with its picture.', tr: 'Her kelimeyi resmiyle eşleştir.', de: 'Ordne jedem Wort das Bild zu.' },
    pairs: [
      { left: 'der Hund', right: '🐕' },
      { left: 'die Tasche', right: '👜' },
      { left: 'das Handy', right: '📱' },
      { left: 'der Schlüssel', right: '🔑' },
    ],
    explanation: {
      en: 'Each picture belongs to one noun – and each noun to one article: der Hund, die Tasche, das Handy, der Schlüssel.',
      tr: 'Her resim bir isme, her isim de bir artikele aittir: der Hund, die Tasche, das Handy, der Schlüssel.',
      de: 'Jedes Bild gehört zu einem Nomen – und jedes Nomen hat seinen Artikel: der Hund, die Tasche, das Handy, der Schlüssel.',
    },
  },
  {
    id: 'match-meaning',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'vocab-objects',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: { en: 'Match the German word with its meaning.', tr: 'Almanca kelimeyi anlamıyla eşleştir.', de: 'Ordne die Wörter den Bildern zu.' },
    pairs: [
      { left: 'der Apfel', right: { en: 'apple', tr: 'elma', de: '🍎' } },
      { left: 'die Tür', right: { en: 'door', tr: 'kapı', de: '🚪' } },
      { left: 'das Buch', right: { en: 'book', tr: 'kitap', de: '📖' } },
      { left: 'die Lampe', right: { en: 'lamp', tr: 'lamba', de: '💡' } },
      { left: 'das Auto', right: { en: 'car', tr: 'araba', de: '🚗' } },
    ],
    explanation: {
      en: 'Say the words out loud with their article – der Apfel, die Tür, das Buch – that is how they stick.',
      tr: 'Kelimeleri artikelleriyle birlikte sesli söyle – der Apfel, die Tür, das Buch – böylece akılda kalır.',
      de: 'Sprich die Wörter laut mit Artikel – der Apfel, die Tür, das Buch – so bleiben sie im Kopf.',
    },
  },
  {
    id: 'mc-hund',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Hund ist klein.',
    options: ['Der', 'Die', 'Das'],
    answer: 0,
    explanation: {
      en: 'Hund is masculine: der Hund. It is the subject of the sentence, so it stays der: Der Hund ist klein.',
      tr: 'Hund eril bir isimdir: der Hund. Cümlenin öznesi olduğu için der olarak kalır: Der Hund ist klein.',
      de: 'Hund ist maskulin: der Hund. Er ist das Subjekt im Satz, also bleibt es bei der: Der Hund ist klein.',
    },
    examples: ['{m:Der Hund} ist klein.', '{m:Der Hund} heißt Max.'],
    practice: ['mc-apfel', 'mc-schluessel'],
  },
  {
    id: 'mc-apfel',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Apfel ist rot.',
    options: ['Der', 'Die', 'Das'],
    answer: 0,
    explanation: {
      en: 'der Apfel – masculine. Der Apfel ist rot.',
      tr: 'der Apfel – eril. Der Apfel ist rot.',
      de: 'der Apfel – maskulin. Der Apfel ist rot.',
    },
    examples: ['{m:Der Apfel} ist süß.'],
  },
  {
    id: 'mc-schluessel',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Schlüssel ist alt.',
    options: ['Der', 'Die', 'Das'],
    answer: 0,
    explanation: {
      en: 'der Schlüssel – masculine. Der Schlüssel ist alt.',
      tr: 'der Schlüssel – eril. Der Schlüssel ist alt.',
      de: 'der Schlüssel – maskulin. Der Schlüssel ist alt.',
    },
    examples: ['{m:Der Schlüssel} ist hier.'],
  },
  {
    id: 'mc-banane',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Banane ist gelb.',
    options: ['Der', 'Die', 'Das'],
    answer: 1,
    explanation: {
      en: 'Banane is feminine: die Banane. Tip: many nouns ending in -e are feminine (die Lampe, die Tasche).',
      tr: 'Banane dişil bir isimdir: die Banane. İpucu: -e ile biten isimlerin çoğu dişildir (die Lampe, die Tasche).',
      de: 'Banane ist feminin: die Banane. Tipp: Viele Nomen auf -e sind feminin (die Lampe, die Tasche).',
    },
    examples: ['{f:Die Banane} ist gelb.', '{f:Die Banane} ist lecker.'],
    practice: ['mc-lampe', 'mc-tuer'],
  },
  {
    id: 'mc-lampe',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Lampe ist neu.',
    options: ['Der', 'Die', 'Das'],
    answer: 1,
    explanation: {
      en: 'die Lampe – feminine, and it ends in -e like die Banane.',
      tr: 'die Lampe – dişil; die Banane gibi -e ile bitiyor.',
      de: 'die Lampe – feminin, mit -e am Ende wie die Banane.',
    },
    examples: ['{f:Die Lampe} ist modern.'],
  },
  {
    id: 'mc-tuer',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Tür ist offen.',
    options: ['Der', 'Die', 'Das'],
    answer: 1,
    explanation: {
      en: 'die Tür – feminine. No -e at the end, so this one you simply have to learn.',
      tr: 'die Tür – dişil. Sonunda -e yok; bunu ezberlemek gerekiyor.',
      de: 'die Tür – feminin. Ohne -e am Ende – dieses Wort musst du einfach lernen.',
    },
    examples: ['{f:Die Tür} ist zu.'],
  },
  {
    id: 'mc-kind',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-n',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Kind spielt.',
    options: ['Der', 'Die', 'Das'],
    answer: 2,
    explanation: {
      en: 'Kind is neuter: das Kind – even though a child is a person. Grammar gender is not always natural gender.',
      tr: 'Kind nötr bir isimdir: das Kind – çocuk bir insan olsa da. Dilbilgisel cinsiyet her zaman gerçek cinsiyet değildir.',
      de: 'Kind ist neutral: das Kind – auch wenn ein Kind eine Person ist. Das grammatische Geschlecht ist nicht immer logisch.',
    },
    examples: ['{n:Das Kind} spielt.', '{n:Das Kind} ist fünf Jahre alt.'],
    practice: ['mc-buch', 'mc-auto'],
  },
  {
    id: 'mc-buch',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-n',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Buch ist spannend.',
    options: ['Der', 'Die', 'Das'],
    answer: 2,
    explanation: {
      en: 'das Buch – neuter.',
      tr: 'das Buch – nötr.',
      de: 'das Buch – neutral.',
    },
    examples: ['{n:Das Buch} ist dick.'],
  },
  {
    id: 'mc-auto',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-n',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Auto ist schnell.',
    options: ['Der', 'Die', 'Das'],
    answer: 2,
    explanation: {
      en: 'das Auto – neuter.',
      tr: 'das Auto – nötr.',
      de: 'das Auto – neutral.',
    },
    examples: ['{n:Das Auto} ist rot.'],
  },
  {
    id: 'sort-articles',
    type: 'categorize',
    topic: 'articles',
    concept: 'gender-mixed',
    skill: 'grammar',
    difficulty: 2,
    instructions: {
      en: 'Sort the nouns: der, die or das? Drag a card – or tap it, then tap a box.',
      tr: 'İsimleri ayır: der, die mi das mı? Kartı sürükle – ya da karta, sonra kutuya dokun.',
      de: 'Sortiere die Nomen: der, die oder das? Ziehe eine Karte – oder tippe sie an und dann eine Box.',
    },
    categories: ['der', 'die', 'das'],
    items: [
      { text: 'Hund', category: 0 },
      { text: 'Tasche', category: 1 },
      { text: 'Auto', category: 2 },
      { text: 'Tisch', category: 0 },
      { text: 'Lampe', category: 1 },
      { text: 'Kind', category: 2 },
      { text: 'Stuhl', category: 0 },
      { text: 'Uhr', category: 1 },
      { text: 'Bett', category: 2 },
    ],
    explanation: {
      en: 'der: Hund, Tisch, Stuhl · die: Tasche, Lampe, Uhr · das: Auto, Kind, Bett.',
      tr: 'der: Hund, Tisch, Stuhl · die: Tasche, Lampe, Uhr · das: Auto, Kind, Bett.',
      de: 'der: Hund, Tisch, Stuhl · die: Tasche, Lampe, Uhr · das: Auto, Kind, Bett.',
    },
  },
  {
    id: 'tf-tisch',
    type: 'true_false',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Das Tisch ist groß.',
    answer: false,
    instructions: { en: 'Is this sentence correct?', tr: 'Bu cümle doğru mu?', de: 'Ist der Satz richtig?' },
    explanation: {
      en: 'Tisch is masculine: der Tisch – so: Der Tisch ist groß. „Das Tisch“ is a very common mistake.',
      tr: 'Tisch eril: der Tisch – yani: Der Tisch ist groß. „Das Tisch“ çok yaygın bir hatadır.',
      de: 'Tisch ist maskulin: der Tisch – also: Der Tisch ist groß. „Das Tisch“ ist ein sehr typischer Fehler.',
    },
    examples: ['{m:Der Tisch} ist groß.', '{m:Der Tisch} ist neu.'],
  },
  {
    id: 'tf-tuer',
    type: 'true_false',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Die Tür ist offen.',
    answer: true,
    instructions: { en: 'Is this sentence correct?', tr: 'Bu cümle doğru mu?', de: 'Ist der Satz richtig?' },
    explanation: {
      en: 'Yes: die Tür is feminine.',
      tr: 'Evet: die Tür dişildir.',
      de: 'Ja: die Tür ist feminin.',
    },
    examples: ['{f:Die Tür} ist offen.'],
  },
  {
    id: 'select-feminine',
    type: 'multiple_select',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: {
      en: 'Select all feminine nouns (die).',
      tr: 'Tüm dişil isimleri seç (die).',
      de: 'Wähle alle femininen Nomen (die).',
    },
    options: ['Banane', 'Hund', 'Lampe', 'Handy', 'Tasche', 'Stuhl'],
    answers: [0, 2, 4],
    explanation: {
      en: 'die Banane, die Lampe, die Tasche – all three end in -e. der Hund, das Handy and der Stuhl are not feminine.',
      tr: 'die Banane, die Lampe, die Tasche – üçü de -e ile bitiyor. der Hund, das Handy ve der Stuhl dişil değil.',
      de: 'die Banane, die Lampe, die Tasche – alle drei enden auf -e. der Hund, das Handy und der Stuhl sind nicht feminin.',
    },
  },

  // --- Practice 2: use ---------------------------------------------------
  {
    id: 'fill-tasche',
    type: 'fill_blank',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 1,
    sentence: '___ Tasche ist neu.',
    accepted: ['Die'],
    instructions: { en: 'Type the article.', tr: 'Artikeli yaz.', de: 'Schreib den Artikel.' },
    hint: { en: 'Tasche ends in -e …', tr: 'Tasche -e ile bitiyor …', de: 'Tasche endet auf -e …' },
    explanation: {
      en: 'die Tasche – feminine. At the start of a sentence: Die.',
      tr: 'die Tasche – dişil. Cümle başında büyük harfle: Die.',
      de: 'die Tasche – feminin. Am Satzanfang groß: Die.',
    },
    examples: ['{f:Die Tasche} ist neu.'],
  },
  {
    id: 'mc-eine-lampe',
    type: 'multiple_choice',
    topic: 'indefinite',
    concept: 'indef-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Das ist ___ Lampe.',
    options: ['ein', 'eine', 'einen', 'der'],
    answer: 1,
    explanation: {
      en: 'die Lampe → eine Lampe. Feminine nouns get eine.',
      tr: 'die Lampe → eine Lampe. Dişil isimler eine alır.',
      de: 'die Lampe → eine Lampe. Feminine Nomen bekommen eine.',
    },
    examples: ['Das ist {f:eine Lampe}.', 'Das ist {f:eine Tasche}.'],
    practice: ['mc-eine-uhr'],
  },
  {
    id: 'mc-eine-uhr',
    type: 'multiple_choice',
    topic: 'indefinite',
    concept: 'indef-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Das ist ___ Uhr.',
    options: ['ein', 'eine', 'einen'],
    answer: 1,
    explanation: {
      en: 'die Uhr → eine Uhr.',
      tr: 'die Uhr → eine Uhr.',
      de: 'die Uhr → eine Uhr.',
    },
    examples: ['Das ist {f:eine Uhr}.'],
  },
  {
    id: 'mc-ein-apfel',
    type: 'multiple_choice',
    topic: 'indefinite',
    concept: 'indef-m',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das ist ___ Apfel.',
    options: ['ein', 'eine', 'einen', 'die'],
    answer: 0,
    explanation: {
      en: 'der Apfel → ein Apfel. After „Das ist …“ masculine nouns take ein. (einen comes after verbs like haben – that is Unit 11.)',
      tr: 'der Apfel → ein Apfel. „Das ist …“ yapısından sonra eril isimler ein alır. (einen, haben gibi fiillerden sonra gelir – Ünite 11.)',
      de: 'der Apfel → ein Apfel. Nach „Das ist …“ bekommen maskuline Nomen ein. (einen kommt nach Verben wie haben – das ist Unit 11.)',
    },
    examples: ['Das ist {m:ein Apfel}. {m:Der Apfel} ist rot.'],
    practice: ['fill-ein-handy'],
  },
  {
    id: 'fill-ein-handy',
    type: 'fill_blank',
    topic: 'indefinite',
    concept: 'indef-n',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Das ist ___ Handy.',
    accepted: ['ein'],
    base: 'ein / eine',
    explanation: {
      en: 'das Handy → ein Handy. Neuter and masculine both use ein.',
      tr: 'das Handy → ein Handy. Nötr ve eril isimler ikisi de ein alır.',
      de: 'das Handy → ein Handy. Neutrum und Maskulinum haben beide ein.',
    },
    examples: ['Das ist {n:ein Handy}. {n:Das Handy} ist teuer.'],
  },
  {
    id: 'mc-kein-apfel',
    type: 'multiple_choice',
    topic: 'negation',
    concept: 'kein',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das ist ___ Apfel. Das ist eine Banane.',
    options: ['kein', 'keine', 'nicht', 'ein'],
    answer: 0,
    explanation: {
      en: 'To say “not a …” before a noun, use kein: ein → kein, eine → keine. der Apfel → ein Apfel → kein Apfel.',
      tr: 'Bir ismin önünde “bir … değil” demek için kein kullanılır: ein → kein, eine → keine. der Apfel → ein Apfel → kein Apfel.',
      de: 'Vor einem Nomen verneinst du mit kein: ein → kein, eine → keine. der Apfel → ein Apfel → kein Apfel.',
    },
    examples: ['Das ist {m:kein Apfel}.', 'Das ist {f:keine Banane}.'],
    practice: ['mc-keine-lampe'],
  },
  {
    id: 'mc-keine-lampe',
    type: 'multiple_choice',
    topic: 'negation',
    concept: 'kein',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das ist ___ Lampe, das ist eine Uhr.',
    options: ['kein', 'keine', 'nicht'],
    answer: 1,
    explanation: {
      en: 'die Lampe → eine Lampe → keine Lampe.',
      tr: 'die Lampe → eine Lampe → keine Lampe.',
      de: 'die Lampe → eine Lampe → keine Lampe.',
    },
    examples: ['Das ist {f:keine Lampe}.'],
  },
  {
    id: 'fill-kein-auto',
    type: 'fill_blank',
    topic: 'negation',
    concept: 'kein',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe ___ Auto, aber ein Fahrrad.',
    accepted: ['kein'],
    base: 'kein / keine',
    explanation: {
      en: 'das Auto → ein Auto → kein Auto.',
      tr: 'das Auto → ein Auto → kein Auto.',
      de: 'das Auto → ein Auto → kein Auto.',
    },
    examples: ['Ich habe {n:kein Auto}.'],
  },
  {
    id: 'build-hund',
    type: 'sentence_builder',
    topic: 'articles',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 1,
    chips: ['ist', 'Der Hund', 'klein'],
    answers: [['Der Hund', 'ist', 'klein']],
    translation: { en: 'The dog is small.', tr: 'Köpek küçük.', de: 'Der Hund ist klein.' },
    explanation: {
      en: 'German statement: position 1 = subject (Der Hund), position 2 = verb (ist), then the rest.',
      tr: 'Almanca düz cümle: 1. pozisyon = özne (Der Hund), 2. pozisyon = fiil (ist), sonra geri kalanı.',
      de: 'Aussagesatz: Position 1 = Subjekt (Der Hund), Position 2 = Verb (ist), dann der Rest.',
    },
    examples: ['{m:Der Hund} **ist** klein.'],
  },
  {
    id: 'build-tasche',
    type: 'sentence_builder',
    topic: 'indefinite',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 1,
    chips: ['eine', 'ist', 'Tasche', 'Das'],
    answers: [['Das', 'ist', 'eine', 'Tasche']],
    translation: { en: 'That is a bag.', tr: 'Bu bir çanta.', de: 'Das ist eine Tasche.' },
    explanation: {
      en: '„Das ist …“ = “That is …”. The article stands right before its noun: eine Tasche.',
      tr: '„Das ist …“ = “Bu … dır”. Artikel isminin hemen önünde durur: eine Tasche.',
      de: '„Das ist …“ stellt etwas vor. Der Artikel steht direkt vor dem Nomen: eine Tasche.',
    },
    examples: ['Das **ist** {f:eine Tasche}.'],
  },
  {
    id: 'build-kein-handy',
    type: 'sentence_builder',
    topic: 'negation',
    concept: 'kein',
    skill: 'grammar',
    difficulty: 2,
    chips: ['Handy', 'habe', 'kein', 'Ich'],
    answers: [['Ich', 'habe', 'kein', 'Handy']],
    translation: { en: "I don't have a mobile phone.", tr: 'Cep telefonum yok.', de: 'Ich habe kein Handy.' },
    explanation: {
      en: 'Verb in position 2 (habe); kein goes right before the noun: kein Handy.',
      tr: 'Fiil 2. pozisyonda (habe); kein ismin hemen önüne gelir: kein Handy.',
      de: 'Verb auf Position 2 (habe); kein steht direkt vor dem Nomen: kein Handy.',
    },
    examples: ['Ich **habe** {n:kein Handy}.'],
  },
  {
    id: 'fix-tisch',
    type: 'error_correction',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das Tisch ist groß.',
    accepted: ['Der Tisch ist groß.'],
    instructions: { en: 'Find the mistake and write the correct sentence.', tr: 'Hatayı bul ve doğru cümleyi yaz.', de: 'Finde den Fehler und schreib den richtigen Satz.' },
    explanation: {
      en: 'der Tisch – masculine. Correct: Der Tisch ist groß.',
      tr: 'der Tisch – eril. Doğrusu: Der Tisch ist groß.',
      de: 'der Tisch – maskulin. Richtig: Der Tisch ist groß.',
    },
    examples: ['{m:Der Tisch} ist groß.'],
  },
  {
    id: 'fix-lampe',
    type: 'error_correction',
    topic: 'indefinite',
    concept: 'indef-f',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das ist ein Lampe.',
    accepted: ['Das ist eine Lampe.'],
    instructions: { en: 'Find the mistake and write the correct sentence.', tr: 'Hatayı bul ve doğru cümleyi yaz.', de: 'Finde den Fehler und schreib den richtigen Satz.' },
    explanation: {
      en: 'die Lampe is feminine, so: eine Lampe.',
      tr: 'die Lampe dişil, bu yüzden: eine Lampe.',
      de: 'die Lampe ist feminin, also: eine Lampe.',
    },
    examples: ['Das ist {f:eine Lampe}.'],
  },
  {
    id: 'match-plural',
    type: 'matching',
    topic: 'plural',
    concept: 'plural',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: { en: 'Match singular and plural.', tr: 'Tekil ve çoğulu eşleştir.', de: 'Ordne Singular und Plural zu.' },
    pairs: [
      { left: 'der Tisch', right: 'die Tische' },
      { left: 'die Lampe', right: 'die Lampen' },
      { left: 'das Kind', right: 'die Kinder' },
      { left: 'das Auto', right: 'die Autos' },
    ],
    explanation: {
      en: 'In the plural the article is always die – for der, die and das nouns. The ending varies: -e, -n, -er, -s.',
      tr: 'Çoğulda artikel her zaman die olur – der, die ve das isimlerinin hepsi için. Ek değişir: -e, -n, -er, -s.',
      de: 'Im Plural ist der Artikel immer die – egal ob der, die oder das. Die Endung variiert: -e, -n, -er, -s.',
    },
    examples: ['{m:der Tisch} → **die Tische**', '{n:das Kind} → **die Kinder**'],
  },
  {
    id: 'mc-plural-buch',
    type: 'multiple_choice',
    topic: 'plural',
    concept: 'plural',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'das Buch → ___',
    promptL10n: { en: 'What is the plural?', tr: 'Çoğulu nedir?', de: 'Was ist der Plural?' },
    options: ['die Bücher', 'das Bücher', 'die Buchs', 'der Bücher'],
    answer: 0,
    explanation: {
      en: 'Plural article: always die. das Buch → die Bücher (umlaut + -er).',
      tr: 'Çoğul artikeli: her zaman die. das Buch → die Bücher (umlaut + -er).',
      de: 'Plural-Artikel: immer die. das Buch → die Bücher (Umlaut + -er).',
    },
    examples: ['**Die Bücher** sind neu.'],
  },
  {
    id: 'mc-er',
    type: 'multiple_choice',
    topic: 'pronouns',
    concept: 'pronoun',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Der Stuhl ist alt. ___ ist aber bequem.',
    options: ['Er', 'Sie', 'Es'],
    answer: 0,
    explanation: {
      en: 'der → er, die → sie, das → es. der Stuhl → er. In German “it” depends on the article!',
      tr: 'der → er, die → sie, das → es. der Stuhl → er. Almancada “o” zamiri artikele göre değişir!',
      de: 'der → er, die → sie, das → es. der Stuhl → er.',
    },
    examples: ['{m:Der Stuhl} ist alt. **Er** ist bequem.'],
    practice: ['mc-sie', 'mc-es'],
  },
  {
    id: 'mc-sie',
    type: 'multiple_choice',
    topic: 'pronouns',
    concept: 'pronoun',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Die Uhr ist neu. ___ ist teuer.',
    options: ['Er', 'Sie', 'Es'],
    answer: 1,
    explanation: {
      en: 'die Uhr → sie.',
      tr: 'die Uhr → sie.',
      de: 'die Uhr → sie.',
    },
    examples: ['{f:Die Uhr} ist neu. **Sie** ist teuer.'],
  },
  {
    id: 'mc-es',
    type: 'multiple_choice',
    topic: 'pronouns',
    concept: 'pronoun',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das Fahrrad ist rot. ___ ist schnell.',
    options: ['Er', 'Sie', 'Es'],
    answer: 2,
    explanation: {
      en: 'das Fahrrad → es.',
      tr: 'das Fahrrad → es.',
      de: 'das Fahrrad → es.',
    },
    examples: ['{n:Das Fahrrad} ist rot. **Es** ist schnell.'],
  },
  {
    id: 'tr-schluessel',
    type: 'translation',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'writing',
    difficulty: 2,
    source: { en: 'The key is old.', tr: 'Anahtar eski.', de: 'The key is old.' },
    accepted: ['Der Schlüssel ist alt.'],
    instructions: { en: 'Write it in German.', tr: 'Almanca yaz.', de: 'Übersetze ins Deutsche.' },
    hint: { en: 'key = Schlüssel, old = alt', tr: 'anahtar = Schlüssel, eski = alt', de: 'key = Schlüssel, old = alt' },
    explanation: {
      en: 'der Schlüssel (masculine) + ist + alt: Der Schlüssel ist alt.',
      tr: 'der Schlüssel (eril) + ist + alt: Der Schlüssel ist alt.',
      de: 'der Schlüssel (maskulin) + ist + alt: Der Schlüssel ist alt.',
    },
    examples: ['{m:Der Schlüssel} ist alt.'],
  },
  {
    id: 'tr-kein-auto',
    type: 'translation',
    topic: 'negation',
    concept: 'kein',
    skill: 'writing',
    difficulty: 3,
    source: { en: "I don't have a car.", tr: 'Arabam yok.', de: "I don't have a car." },
    accepted: ['Ich habe kein Auto.'],
    instructions: { en: 'Write it in German.', tr: 'Almanca yaz.', de: 'Übersetze ins Deutsche.' },
    hint: { en: 'car = das Auto', tr: 'araba = das Auto', de: 'car = das Auto' },
    explanation: {
      en: 'German says “I have no car”: Ich habe kein Auto. (das Auto → kein Auto)',
      tr: 'Almanca “Hiç arabam yok” der: Ich habe kein Auto. (das Auto → kein Auto)',
      de: 'Ich habe kein Auto. (das Auto → ein Auto → kein Auto)',
    },
    examples: ['Ich habe {n:kein Auto}.'],
  },
  {
    id: 'dialog-uhr',
    type: 'dialogue',
    topic: 'indefinite',
    concept: 'indef-f',
    skill: 'grammar',
    difficulty: 2,
    lines: [
      { speaker: 'Lena', de: 'Oh, was ist das?' },
    ],
    options: ['Das ist ein Uhr.', 'Das ist eine Uhr.', 'Das ist einen Uhr.'],
    answer: 1,
    instructions: { en: 'Choose the best reply.', tr: 'En iyi cevabı seç.', de: 'Wähle die beste Antwort.' },
    explanation: {
      en: 'die Uhr is feminine → eine Uhr.',
      tr: 'die Uhr dişil → eine Uhr.',
      de: 'die Uhr ist feminin → eine Uhr.',
    },
    examples: ['Das ist {f:eine Uhr}. {f:Die Uhr} ist neu.'],
  },

  // --- Reading --------------------------------------------------------------
  {
    id: 'read-wo',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anna',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wo wohnt Anna?',
    options: ['In Berlin.', 'In Köln.', 'In Wien.'],
    answer: 1,
    explanation: {
      en: '„Anna wohnt in Köln.“ – second sentence.',
      tr: '„Anna wohnt in Köln.“ – ikinci cümle.',
      de: '„Anna wohnt in Köln.“ – zweiter Satz.',
    },
  },
  {
    id: 'read-hund',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anna',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie heißt der Hund?',
    options: ['Anna', 'Max', 'Moritz'],
    answer: 1,
    explanation: {
      en: '„Der Hund heißt Max.“',
      tr: '„Der Hund heißt Max.“',
      de: '„Der Hund heißt Max.“',
    },
  },
  {
    id: 'read-tisch',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-anna',
    skill: 'reading',
    difficulty: 1,
    statement: 'Der Tisch ist neu.',
    answer: false,
    explanation: {
      en: '„Die Lampe ist neu, aber der Tisch ist alt.“',
      tr: '„Die Lampe ist neu, aber der Tisch ist alt.“ – masa eski.',
      de: '„Die Lampe ist neu, aber der Tisch ist alt.“',
    },
  },
  {
    id: 'read-neu',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anna',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist neu?',
    options: ['der Tisch', 'die Lampe', 'das Bett'],
    answer: 1,
    explanation: {
      en: 'die Lampe – „Die Lampe ist neu.“',
      tr: 'die Lampe – „Die Lampe ist neu.“',
      de: 'die Lampe – „Die Lampe ist neu.“',
    },
  },

  // --- Listening -----------------------------------------------------------
  {
    id: 'listen-tasche',
    type: 'listening_choice',
    topic: 'indefinite',
    concept: 'indef-f',
    skill: 'listening',
    difficulty: 1,
    audio: 'Das ist eine Tasche.',
    question: { en: 'What do you hear?', tr: 'Ne duyuyorsun?', de: 'Was hörst du?' },
    options: ['Das ist ein Tasche.', 'Das ist eine Tasche.', 'Das ist keine Tasche.'],
    answer: 1,
    explanation: {
      en: 'Listen for the -e at the end: eine Tasche.',
      tr: 'Sondaki -e sesine dikkat et: eine Tasche.',
      de: 'Achte auf das -e am Ende: eine Tasche.',
    },
    examples: ['Das ist {f:eine Tasche}.'],
  },
  {
    id: 'listen-fahrrad',
    type: 'listening_choice',
    topic: 'negation',
    concept: 'kein',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich habe kein Auto, aber ich habe ein Fahrrad.',
    question: { en: 'What does the person have?', tr: 'Kişinin neyi var?', de: 'Was hat die Person?' },
    options: ['🚗 ein Auto', '🚲 ein Fahrrad', '📱 ein Handy'],
    answer: 1,
    explanation: {
      en: '„kein Auto“ = no car, „ein Fahrrad“ = a bike.',
      tr: '„kein Auto“ = araba yok, „ein Fahrrad“ = bir bisiklet var.',
      de: '„kein Auto“, aber „ein Fahrrad“.',
    },
    examples: ['Ich habe {n:kein Auto}, aber {n:ein Fahrrad}.'],
  },
  {
    id: 'listen-alt',
    type: 'listening_choice',
    topic: 'articles',
    concept: 'gender-m',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Lampe ist neu, aber der Stuhl ist alt.',
    question: { en: 'What is old?', tr: 'Ne eski?', de: 'Was ist alt?' },
    options: ['die Lampe', 'der Stuhl', 'das Bett'],
    answer: 1,
    explanation: {
      en: '„… aber der Stuhl ist alt.“',
      tr: '„… aber der Stuhl ist alt.“ – sandalye eski.',
      de: '„… aber der Stuhl ist alt.“',
    },
  },
  {
    id: 'listen-fenster',
    type: 'listening_choice',
    topic: 'articles',
    concept: 'gender-n',
    skill: 'listening',
    difficulty: 1,
    audio: 'das Fenster',
    question: { en: 'Which article do you hear?', tr: 'Hangi artikeli duyuyorsun?', de: 'Welchen Artikel hörst du?' },
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: {
      en: 'das Fenster – neuter.',
      tr: 'das Fenster – nötr.',
      de: 'das Fenster – neutral.',
    },
    examples: ['{n:Das Fenster} ist offen.'],
  },

  ...articleDrills([...VOCAB, ...MORE_VOCAB]),
]

export const UNIT05_ARTICLES: CourseUnit = {
  level: 'A1',
  number: 5,
  slug: 'articles',
  titleDe: 'Der, die oder das?',
  title: { en: 'Der, die or das?', tr: 'Der, die mi das mı?', de: 'Der, die oder das?' },
  goal: {
    en: 'By the end of this unit you can use der, die and das – and ein, eine, kein – correctly with common everyday nouns.',
    tr: 'Bu ünitenin sonunda der, die ve das – ayrıca ein, eine, kein – artikellerini günlük eşyalarla doğru kullanabileceksin.',
    de: 'Am Ende dieser Einheit kannst du der, die und das – und ein, eine, kein – mit häufigen Alltagswörtern richtig verwenden.',
  },
  minutes: [15, 20],
  topics: [
    { key: 'articles', label: { en: 'der / die / das', tr: 'der / die / das', de: 'der / die / das' } },
    { key: 'indefinite', label: { en: 'ein / eine', tr: 'ein / eine', de: 'ein / eine' } },
    { key: 'negation', label: { en: 'kein / keine', tr: 'kein / keine', de: 'kein / keine' } },
    { key: 'pronouns', label: { en: 'er / sie / es', tr: 'er / sie / es', de: 'er / sie / es' } },
    { key: 'plural', label: { en: 'Plural', tr: 'Çoğul', de: 'Plural' } },
    { key: 'vocabulary', label: { en: 'Vocabulary', tr: 'Kelime', de: 'Wortschatz' } },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: { en: 'Discover', tr: 'Keşfet', de: 'Entdecken' },
      intro: {
        en: 'Every German noun has an article. Explore these everyday things – tap a card to hear it and see its plural.',
        tr: 'Almancada her ismin bir artikeli vardır. Bu günlük eşyaları keşfet – dinlemek ve çoğulunu görmek için bir karta dokun.',
        de: 'Jedes deutsche Nomen hat einen Artikel. Entdecke diese Alltagsdinge – tippe auf eine Karte, um sie zu hören und den Plural zu sehen.',
      },
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: { en: 'Understand', tr: 'Anla', de: 'Verstehen' },
      rules: [
        {
          title: { en: 'Three articles: der, die, das', tr: 'Üç artikel: der, die, das', de: 'Drei Artikel: der, die, das' },
          body: {
            en: 'German nouns are masculine, feminine or neuter. You can rarely guess it – so never learn „Tisch“, always learn „der Tisch“.',
            tr: 'Almanca isimler eril, dişil ya da nötrdür. Çoğu zaman tahmin edemezsin – bu yüzden asla sadece „Tisch“ değil, her zaman „der Tisch“ öğren.',
            de: 'Deutsche Nomen sind maskulin, feminin oder neutral. Raten klappt selten – lerne also nie nur „Tisch“, sondern immer „der Tisch“.',
          },
          table: {
            head: [
              { en: 'Article', tr: 'Artikel', de: 'Artikel' },
              { en: 'Gender', tr: 'Cinsiyet', de: 'Genus' },
              { en: 'Example', tr: 'Örnek', de: 'Beispiel' },
            ],
            rows: [
              ['der', 'maskulin', 'der Hund'],
              ['die', 'feminin', 'die Tasche'],
              ['das', 'neutral', 'das Handy'],
            ],
          },
          tip: {
            en: 'Colour trick: imagine der-words in blue, die-words in red and das-words in green – like on this page.',
            tr: 'Renk hilesi: der kelimelerini mavi, die kelimelerini kırmızı, das kelimelerini yeşil hayal et – bu sayfadaki gibi.',
            de: 'Farb-Trick: Stell dir der-Wörter blau, die-Wörter rot und das-Wörter grün vor – wie auf dieser Seite.',
          },
        },
        {
          title: { en: 'A / an: ein and eine', tr: 'Bir: ein ve eine', de: 'Unbestimmt: ein und eine' },
          body: {
            en: 'When something is new or not specific, use ein / eine. Masculine and neuter → ein, feminine → eine.',
            tr: 'Bir şey yeni ya da belirsizse ein / eine kullanılır. Eril ve nötr → ein, dişil → eine.',
            de: 'Wenn etwas neu oder nicht bestimmt ist, nimmst du ein / eine. Maskulin und neutral → ein, feminin → eine.',
          },
          table: {
            head: [
              { en: 'der', tr: 'der', de: 'der' },
              { en: 'die', tr: 'die', de: 'die' },
              { en: 'das', tr: 'das', de: 'das' },
            ],
            rows: [['ein Hund', 'eine Tasche', 'ein Handy']],
          },
          examples: [
            { de: 'Das ist {m:ein Apfel}. {m:Der Apfel} ist rot.', translation: { en: 'That is an apple. The apple is red.', tr: 'Bu bir elma. Elma kırmızı.', de: 'Zuerst ein (neu), dann der (bekannt).' } },
          ],
        },
        {
          title: { en: 'Not a …: kein and keine', tr: 'Bir … değil: kein ve keine', de: 'Verneinung: kein und keine' },
          body: {
            en: 'Put a k in front of ein: ein → kein, eine → keine.',
            tr: 'ein kelimesinin önüne k ekle: ein → kein, eine → keine.',
            de: 'Setz ein k vor ein: ein → kein, eine → keine.',
          },
          examples: [
            { de: 'Das ist {m:kein Hund}. Das ist {f:eine Katze}.', translation: { en: "That's not a dog. That's a cat.", tr: 'Bu bir köpek değil. Bu bir kedi.', de: 'kein Hund, sondern eine Katze.' } },
            { de: 'Ich habe {n:kein Auto}.', translation: { en: "I don't have a car.", tr: 'Arabam yok.', de: 'kein Auto' } },
          ],
        },
        {
          title: { en: 'It = er, sie or es', tr: '“O” = er, sie ya da es', de: 'Pronomen: er, sie, es' },
          body: {
            en: 'English uses “it” for things. German uses the article: der → er, die → sie, das → es.',
            tr: 'Almancada eşyalar için kullanılan zamir artikele bağlıdır: der → er, die → sie, das → es.',
            de: 'Das Pronomen folgt dem Artikel: der → er, die → sie, das → es.',
          },
          examples: [
            { de: '{m:Der Stuhl} ist alt. **Er** ist bequem.', translation: { en: 'The chair is old. It is comfortable.', tr: 'Sandalye eski. (O) rahat.', de: 'der Stuhl → er' } },
            { de: '{f:Die Lampe} ist neu. **Sie** ist schön.', translation: { en: 'The lamp is new. It is beautiful.', tr: 'Lamba yeni. (O) güzel.', de: 'die Lampe → sie' } },
          ],
        },
        {
          title: { en: 'Helpful patterns', tr: 'İşe yarayan kalıplar', de: 'Hilfreiche Muster' },
          body: {
            en: 'Not rules, but good guesses: many nouns ending in -e are feminine (die Lampe). Nouns ending in -chen are always neuter (das Mädchen). In the plural, the article is always die (die Kinder).',
            tr: 'Kural değil ama iyi tahminler: -e ile biten isimlerin çoğu dişildir (die Lampe). -chen ile biten isimler her zaman nötrdür (das Mädchen). Çoğulda artikel her zaman die olur (die Kinder).',
            de: 'Keine Regeln, aber gute Tipps: Viele Nomen auf -e sind feminin (die Lampe). Nomen auf -chen sind immer neutral (das Mädchen). Im Plural ist der Artikel immer die (die Kinder).',
          },
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: { en: 'See it in context', tr: 'Bağlamda gör', de: 'Im Kontext' },
      scene: {
        en: 'Tom is helping his friend Mia unpack after her move.',
        tr: 'Tom, taşındıktan sonra arkadaşı Mia’nın eşyalarını açmasına yardım ediyor.',
        de: 'Tom hilft seiner Freundin Mia nach dem Umzug beim Auspacken.',
      },
      dialogue: [
        { speaker: 'Tom', de: 'Was ist das?', translation: { en: 'What is that?', tr: 'Bu ne?', de: '' } },
        { speaker: 'Mia', de: 'Das ist {f:eine Lampe}. {f:Die Lampe} ist neu.', translation: { en: "That's a lamp. The lamp is new.", tr: 'Bu bir lamba. Lamba yeni.', de: '' } },
        { speaker: 'Tom', de: 'Und das? Ist das {m:ein Schlüssel}?', translation: { en: 'And that? Is that a key?', tr: 'Ya bu? Bu bir anahtar mı?', de: '' } },
        { speaker: 'Mia', de: 'Ja. {m:Der Schlüssel} ist für {f:die Tür}.', translation: { en: 'Yes. The key is for the door.', tr: 'Evet. Anahtar kapı için.', de: '' } },
        { speaker: 'Tom', de: 'Und das hier? Ist das {n:ein Handy}?', translation: { en: 'And this one? Is that a phone?', tr: 'Ya bu? Bu bir telefon mu?', de: '' } },
        { speaker: 'Mia', de: 'Nein, das ist {n:kein Handy}. Das ist {f:eine Uhr}. **Sie** ist neu!', translation: { en: "No, that's not a phone. It's a watch. It's new!", tr: 'Hayır, bu bir telefon değil. Bu bir saat. (O) yeni!', de: '' } },
      ],
      examples: [
        { de: '{m:Der Hund} ist klein.', translation: { en: 'The dog is small.', tr: 'Köpek küçük.', de: '' } },
        { de: '{f:Die Tasche} ist neu.', translation: { en: 'The bag is new.', tr: 'Çanta yeni.', de: '' } },
        { de: '{n:Das Handy} ist teuer.', translation: { en: 'The phone is expensive.', tr: 'Telefon pahalı.', de: '' } },
        { de: 'Das ist {n:ein Buch}. {n:Das Buch} ist spannend.', translation: { en: "That's a book. The book is exciting.", tr: 'Bu bir kitap. Kitap heyecanlı.', de: '' } },
        { de: 'Das ist {m:kein Stuhl}, das ist {m:ein Tisch}.', translation: { en: "That's not a chair, that's a table.", tr: 'Bu bir sandalye değil, bu bir masa.', de: '' } },
        { de: '{f:Die Uhr} ist schön. **Sie** ist aus Berlin.', translation: { en: 'The watch is beautiful. It is from Berlin.', tr: 'Saat güzel. (O) Berlin’den.', de: '' } },
        { de: '**Die Kinder** spielen.', translation: { en: 'The children are playing.', tr: 'Çocuklar oynuyor.', de: '' } },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: { en: 'Practice 1 · Recognise', tr: 'Pratik 1 · Tanı', de: 'Übung 1 · Erkennen' },
      intro: {
        en: 'First recognise the right article. After each answer you get a short explanation – take your time.',
        tr: 'Önce doğru artikeli tanı. Her cevaptan sonra kısa bir açıklama göreceksin – acele etme.',
        de: 'Erkenne zuerst den richtigen Artikel. Nach jeder Antwort bekommst du eine kurze Erklärung – lass dir Zeit.',
      },
      exercises: ['img-tasche', 'match-pictures', 'mc-hund', 'mc-banane', 'mc-kind', 'sort-articles', 'tf-tisch', 'select-feminine', 'match-meaning'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: { en: 'Practice 2 · Use', tr: 'Pratik 2 · Kullan', de: 'Übung 2 · Anwenden' },
      intro: {
        en: 'Now produce the forms yourself: type, build sentences and fix mistakes.',
        tr: 'Şimdi biçimleri kendin üret: yaz, cümle kur ve hataları düzelt.',
        de: 'Jetzt bildest du die Formen selbst: schreiben, Sätze bauen, Fehler korrigieren.',
      },
      exercises: [
        'fill-tasche',
        'mc-eine-lampe',
        'mc-ein-apfel',
        'fill-ein-handy',
        'mc-kein-apfel',
        'fill-kein-auto',
        'build-hund',
        'build-tasche',
        'build-kein-handy',
        'fix-tisch',
        'fix-lampe',
        'match-plural',
        'mc-plural-buch',
        'mc-er',
        'tr-schluessel',
        'tr-kein-auto',
        'dialog-uhr',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: { en: 'Reading', tr: 'Okuma', de: 'Lesen' },
      intro: {
        en: 'Read the short text. Notice every article.',
        tr: 'Kısa metni oku. Her artikele dikkat et.',
        de: 'Lies den kurzen Text. Achte auf jeden Artikel.',
      },
      passage: [
        'Das ist Anna. Anna wohnt in Köln.',
        'Sie hat {n:ein Zimmer}. Im Zimmer sind {n:ein Bett}, {m:ein Tisch} und {f:eine Lampe}.',
        '{f:Die Lampe} ist neu, aber {m:der Tisch} ist alt.',
        'Anna hat auch {m:einen Hund}. {m:Der Hund} heißt Max.',
        'Max ist klein und sehr lieb.',
      ],
      glossary: [
        { de: 'das Zimmer', note: { en: 'room', tr: 'oda', de: 'Raum in einer Wohnung' } },
        { de: 'im Zimmer', note: { en: 'in the room', tr: 'odada', de: 'in dem Zimmer' } },
        {
          de: 'einen Hund',
          note: {
            en: 'After „haben“: ein → einen for masculine nouns. You will learn why in Unit 11.',
            tr: '„haben“ fiilinden sonra eril isimlerde ein → einen olur. Nedenini Ünite 11’de öğreneceksin.',
            de: 'Nach „haben“: ein → einen bei maskulinen Nomen. Mehr dazu in Unit 11.',
          },
        },
        { de: 'lieb', note: { en: 'sweet, kind', tr: 'tatlı, sevimli', de: 'nett, freundlich' } },
      ],
      exercises: ['read-wo', 'read-hund', 'read-tisch', 'read-neu'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: { en: 'Listening', tr: 'Dinleme', de: 'Hören' },
      intro: {
        en: 'Press play and listen. You can slow it down and replay as often as you like.',
        tr: 'Oynat’a bas ve dinle. İstediğin kadar yavaşlatıp tekrar dinleyebilirsin.',
        de: 'Drück auf Play und hör zu. Du kannst langsamer abspielen und beliebig oft wiederholen.',
      },
      exercises: ['listen-fenster', 'listen-tasche', 'listen-alt', 'listen-fahrrad'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: { en: 'Speaking', tr: 'Konuşma', de: 'Sprechen' },
      prompt: {
        en: 'Look around your room and talk about four things.',
        tr: 'Odana bak ve dört eşya hakkında konuş.',
        de: 'Schau dich in deinem Zimmer um und sprich über vier Dinge.',
      },
      points: [
        { en: 'Name things with ein / eine: „Das ist eine Lampe.“', tr: 'Eşyaları ein / eine ile söyle: „Das ist eine Lampe.“', de: 'Benenne Dinge mit ein / eine: „Das ist eine Lampe.“' },
        { en: 'Describe them with der / die / das: „Die Lampe ist neu.“', tr: 'der / die / das ile tarif et: „Die Lampe ist neu.“', de: 'Beschreibe sie mit der / die / das: „Die Lampe ist neu.“' },
        { en: 'Say one thing you don’t have: „Ich habe kein Auto.“', tr: 'Olmayan bir şeyi söyle: „Ich habe kein Auto.“', de: 'Sag, was du nicht hast: „Ich habe kein Auto.“' },
      ],
      model: [
        'Das ist ein Bett. Das Bett ist groß.',
        'Das ist eine Lampe. Die Lampe ist neu.',
        'Das ist ein Handy. Es ist teuer.',
        'Ich habe kein Auto, aber ich habe ein Fahrrad.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: { en: 'Writing', tr: 'Yazma', de: 'Schreiben' },
      prompt: {
        en: 'Write at least 4 short sentences about things in your room or bag.',
        tr: 'Odandaki ya da çantandaki eşyalar hakkında en az 4 kısa cümle yaz.',
        de: 'Schreib mindestens 4 kurze Sätze über Dinge in deinem Zimmer oder deiner Tasche.',
      },
      minSentences: 4,
      checks: [
        { label: { en: 'Uses ein or eine', tr: 'ein ya da eine kullanılmış', de: 'Mit ein oder eine' }, pattern: '\\b[Ee]ine?\\s+\\p{Lu}' },
        { label: { en: 'Uses der, die or das with a noun', tr: 'der, die ya da das bir isimle kullanılmış', de: 'Mit der, die oder das + Nomen' }, pattern: '\\b([Dd]er|[Dd]ie|[Dd]as)\\s+\\p{Lu}' },
        { label: { en: 'Uses kein or keine', tr: 'kein ya da keine kullanılmış', de: 'Mit kein oder keine' }, pattern: '\\b[Kk]eine?n?\\s+\\p{Lu}' },
      ],
      model: ['Das ist meine Tasche.', 'In der Tasche ist ein Handy.', 'Das Handy ist neu.', 'Das ist ein Buch. Es ist spannend.', 'Ich habe keine Uhr.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: { en: 'Speed round', tr: 'Hız turu', de: 'Schnellrunde' },
      intro: {
        en: 'How many articles can you get right in 60 seconds?',
        tr: '60 saniyede kaç artikeli doğru bilebilirsin?',
        de: 'Wie viele Artikel schaffst du in 60 Sekunden?',
      },
      seconds: 60,
      pool: [...VOCAB, ...MORE_VOCAB].map((v) => `art-${v.word.toLowerCase()}`),
    },
    {
      key: 'review',
      kind: 'review',
      title: { en: 'Review', tr: 'Tekrar', de: 'Wiederholung' },
      intro: {
        en: 'Your mistakes in this unit – with the correct form. Practise them once more now.',
        tr: 'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        de: 'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.',
      },
    },
    {
      key: 'summary',
      kind: 'summary',
      title: { en: 'Mastery', tr: 'Ustalık', de: 'Abschluss' },
    },
  ],
  summary: {
    learned: [
      { en: 'der / die / das – learn every noun with its article', tr: 'der / die / das – her ismi artikeliyle öğren', de: 'der / die / das – jedes Nomen mit Artikel lernen' },
      { en: 'ein / eine for new or non-specific things', tr: 'yeni ya da belirsiz şeyler için ein / eine', de: 'ein / eine für neue oder unbestimmte Dinge' },
      { en: 'kein / keine for “not a …”', tr: '“bir … değil” için kein / keine', de: 'kein / keine für die Verneinung' },
      { en: 'er / sie / es instead of the noun', tr: 'isim yerine er / sie / es', de: 'er / sie / es statt Nomen' },
      { en: 'Plural article: always die', tr: 'Çoğul artikeli: her zaman die', de: 'Plural-Artikel: immer die' },
    ],
    mistakes: [
      { wrong: 'das Tisch', right: 'der Tisch', note: { en: 'Tisch is masculine.', tr: 'Tisch eril.', de: 'Tisch ist maskulin.' } },
      { wrong: 'ein Lampe', right: 'eine Lampe', note: { en: 'Feminine nouns take eine.', tr: 'Dişil isimler eine alır.', de: 'Feminine Nomen: eine.' } },
      { wrong: 'nicht Auto', right: 'kein Auto', note: { en: 'Before a noun use kein, not nicht.', tr: 'İsimden önce nicht değil kein kullanılır.', de: 'Vor Nomen: kein, nicht nicht.' } },
      { wrong: 'Der Stuhl … Es ist bequem.', right: 'Der Stuhl … Er ist bequem.', note: { en: 'der → er.', tr: 'der → er.', de: 'der → er.' } },
    ],
  },
}
