import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Lehrer', gender: 'm', plural: 'die Lehrer', emoji: '🧑‍🏫', translation: l('teacher', 'öğretmen', 'Lehrer'), example: 'Er ist Lehrer. – Sie ist Lehrerin.' },
  { word: 'Arzt', gender: 'm', plural: 'die Ärzte', emoji: '🩺', translation: l('doctor', 'doktor', 'Arzt'), example: 'Er ist Arzt. – Sie ist Ärztin.' },
  { word: 'Koch', gender: 'm', plural: 'die Köche', emoji: '👨‍🍳', translation: l('cook, chef', 'aşçı', 'Koch'), example: 'Er ist Koch. – Sie ist Köchin.' },
  { word: 'Student', gender: 'm', plural: 'die Studenten', emoji: '🎓', translation: l('student', 'üniversite öğrencisi', 'Student'), example: 'Er ist Student. – Sie ist Studentin.' },
  { word: 'Verkäufer', gender: 'm', plural: 'die Verkäufer', emoji: '🛍️', translation: l('shop assistant', 'satış elemanı', 'Verkäufer'), example: 'Er ist Verkäufer. – Sie ist Verkäuferin.' },
  { word: 'Programmierer', gender: 'm', plural: 'die Programmierer', emoji: '💻', translation: l('programmer', 'yazılımcı', 'Programmierer'), example: 'Er ist Programmierer. – Sie ist Programmiererin.' },
  { word: 'Name', gender: 'm', plural: 'die Namen', emoji: '🪪', translation: l('name', 'ad, isim', 'Name'), example: 'Mein Name ist Karim.' },
  { word: 'Adresse', gender: 'f', plural: 'die Adressen', emoji: '🏠', translation: l('address', 'adres', 'Adresse'), example: 'Wie ist Ihre Adresse?' },
  { word: 'Telefonnummer', gender: 'f', plural: 'die Telefonnummern', emoji: '📞', translation: l('phone number', 'telefon numarası', 'Telefonnummer'), example: 'Wie ist deine Telefonnummer?' },
  { word: 'E-Mail-Adresse', gender: 'f', plural: 'die E-Mail-Adressen', emoji: '📧', translation: l('e-mail address', 'e-posta adresi', 'E-Mail-Adresse'), example: 'Haben Sie eine E-Mail-Adresse?' },
  { word: 'Alter', gender: 'n', emoji: '🎂', translation: l('age', 'yaş', 'Alter'), example: 'Alter: 31' },
  { word: 'Kind', gender: 'n', plural: 'die Kinder', emoji: '🧒', translation: l('child', 'çocuk', 'Kind'), example: 'Ich habe ein Kind.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Ärztin', gender: 'f', plural: 'die Ärztinnen', translation: l('doctor (woman)', 'kadın doktor', 'Ärztin') },
  { word: 'Lehrerin', gender: 'f', plural: 'die Lehrerinnen', translation: l('teacher (woman)', 'kadın öğretmen', 'Lehrerin') },
  { word: 'Vorname', gender: 'm', plural: 'die Vornamen', translation: l('first name', 'ad', 'Vorname') },
  { word: 'Nachname', gender: 'm', plural: 'die Nachnamen', translation: l('surname', 'soyad', 'Nachname') },
  { word: 'Beruf', gender: 'm', plural: 'die Berufe', translation: l('job, profession', 'meslek', 'Beruf') },
  { word: 'Straße', gender: 'f', plural: 'die Straßen', translation: l('street', 'sokak, cadde', 'Straße') },
  { word: 'haben', translation: l('to have', 'sahip olmak', 'haben') },
  { word: 'arbeiten', translation: l('to work', 'çalışmak', 'arbeiten') },
]

const SEIN = ['bin', 'bist', 'ist', 'sind'] as const
const HABEN = ['habe', 'hast', 'hat', 'haben'] as const
const PERSONS = ['ich', 'du', 'er', 'Sie'] as const

/** "er ___ (haben)" drills for the speed round and review variations. */
function seinHabenDrills(): Exercise[] {
  return (['sein', 'haben'] as const).flatMap((verb) =>
    PERSONS.map((person, p) => {
      const forms = verb === 'sein' ? SEIN : HABEN
      return {
        id: `${verb}-${person.toLowerCase()}`,
        type: 'multiple_choice' as const,
        topic: verb === 'sein' ? 'sein' : 'haben',
        concept: `${verb}-forms`,
        skill: 'grammar' as const,
        difficulty: 1 as const,
        prompt: `${person} ___ (${verb})`,
        options: [...forms],
        answer: p,
        explanation: l(
          `${verb}: ich ${forms[0]}, du ${forms[1]}, er/sie ${forms[2]}, Sie ${forms[3]}.`,
          `${verb}: ich ${forms[0]}, du ${forms[1]}, er/sie ${forms[2]}, Sie ${forms[3]}.`,
          `${verb}: ich ${forms[0]}, du ${forms[1]}, er/sie ${forms[2]}, Sie ${forms[3]}.`
        ),
        examples: [`${person === 'ich' ? 'Ich' : person === 'du' ? 'Du' : person === 'er' ? 'Er' : 'Sie'} **${forms[p]}** …`],
      }
    })
  )
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise ------------------------------------------------
  {
    id: 'img-arzt',
    type: 'image_choice',
    topic: 'vocabulary',
    concept: 'jobs',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Sie ist Ärztin.',
    options: [
      { emoji: '👨‍🍳', label: 'Köchin' },
      { emoji: '🧑‍🏫', label: 'Lehrerin' },
      { emoji: '🩺', label: 'Ärztin' },
      { emoji: '💻', label: 'Programmiererin' },
    ],
    answer: 2,
    explanation: l(
      'der Arzt → die Ärztin: the -in ending makes the female form (with umlaut here).',
      'der Arzt → die Ärztin: -in eki kadın biçimini yapar (burada umlaut ile).',
      'der Arzt → die Ärztin: Die Endung -in bildet die weibliche Form (hier mit Umlaut).'
    ),
    examples: ['Sie ist **Ärztin**.'],
  },
  {
    id: 'match-jobs',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'jobs',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the jobs with the pictures.', 'Meslekleri resimlerle eşleştir.', 'Ordne die Berufe den Bildern zu.'),
    pairs: [
      { left: 'Lehrerin', right: '🧑‍🏫' },
      { left: 'Koch', right: '👨‍🍳' },
      { left: 'Studentin', right: '🎓' },
      { left: 'Verkäufer', right: '🛍️' },
    ],
    explanation: l(
      'Male: Lehrer, Koch, Student, Verkäufer. Female: + -in → Lehrerin, Köchin, Studentin, Verkäuferin.',
      'Erkek: Lehrer, Koch, Student, Verkäufer. Kadın: + -in → Lehrerin, Köchin, Studentin, Verkäuferin.',
      'Männlich: Lehrer, Koch, Student, Verkäufer. Weiblich: + -in → Lehrerin, Köchin, Studentin, Verkäuferin.'
    ),
  },
  {
    id: 'mc-wohnt',
    type: 'multiple_choice',
    topic: 'third-person',
    concept: 'ending-er',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Karim ___ in Bremen.',
    options: ['wohne', 'wohnst', 'wohnt'],
    answer: 2,
    explanation: l(
      'Talking about another person (er, sie, Karim): verb + -t → er wohnt.',
      'Başka biri hakkında konuşurken (er, sie, Karim): fiil + -t → er wohnt.',
      'Über eine andere Person (er, sie, Karim): Verb + -t → er wohnt.'
    ),
    examples: ['Karim **wohnt** in Bremen.'],
    practice: ['mc-kommt', 'fix-wohnst'],
  },
  {
    id: 'mc-kommt',
    type: 'multiple_choice',
    topic: 'third-person',
    concept: 'ending-er',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Sofia ___ aus Spanien.',
    options: ['kommt', 'kommst', 'komme'],
    answer: 0,
    explanation: l('sie (Sofia) → -t: sie kommt.', 'sie (Sofia) → -t: sie kommt.', 'sie (Sofia) → -t: sie kommt.'),
    examples: ['Sofia **kommt** aus Spanien.'],
  },
  {
    id: 'mc-ist-aerztin',
    type: 'multiple_choice',
    topic: 'sein',
    concept: 'sein-forms',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Frau Klein ___ Ärztin.',
    options: ['bin', 'bist', 'ist', 'sind'],
    answer: 2,
    explanation: l('er/sie → ist.', 'er/sie → ist.', 'er/sie → ist.'),
    examples: ['Frau Klein **ist** Ärztin.'],
  },
  {
    id: 'tf-jahre',
    type: 'true_false',
    topic: 'sein',
    concept: 'age-sein',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Ich habe 25 Jahre.',
    answer: false,
    instructions: l('Is this sentence correct?', 'Bu cümle doğru mu?', 'Ist der Satz richtig?'),
    explanation: l(
      'Age uses sein, not haben: Ich bin 25 (Jahre alt).',
      'Yaş için haben değil sein kullanılır: Ich bin 25 (Jahre alt).',
      'Das Alter sagt man mit sein, nicht mit haben: Ich bin 25 (Jahre alt).'
    ),
    examples: ['Ich **bin** 25 Jahre alt.'],
  },
  {
    id: 'sort-sein-haben',
    type: 'categorize',
    topic: 'haben',
    concept: 'sein-or-haben',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('sein or haben? Sort the phrases.', 'sein mi haben mı? İfadeleri ayır.', 'sein oder haben? Sortiere.'),
    categories: ['sein', 'haben'],
    items: [
      { text: '30 Jahre alt', category: 0 },
      { text: 'zwei Kinder', category: 1 },
      { text: 'Lehrer', category: 0 },
      { text: 'ein Auto', category: 1 },
      { text: 'verheiratet', category: 0 },
      { text: 'Zeit', category: 1 },
    ],
    explanation: l(
      'sein: age, job, marital status (Ich bin 30 / Lehrer / verheiratet). haben: things and people you have (Ich habe zwei Kinder / ein Auto / Zeit).',
      'sein: yaş, meslek, medeni durum (Ich bin 30 / Lehrer / verheiratet). haben: sahip olunan şeyler ve kişiler (Ich habe zwei Kinder / ein Auto / Zeit).',
      'sein: Alter, Beruf, Familienstand (Ich bin 30 / Lehrer / verheiratet). haben: was man hat (Ich habe zwei Kinder / ein Auto / Zeit).'
    ),
  },
  {
    id: 'select-jobs',
    type: 'multiple_select',
    topic: 'vocabulary',
    concept: 'jobs',
    skill: 'vocabulary',
    difficulty: 1,
    promptL10n: l('Select all jobs.', 'Tüm meslekleri seç.', 'Wähle alle Berufe.'),
    options: ['Lehrer', 'Adresse', 'Köchin', 'Telefonnummer', 'Ärztin', 'Straße'],
    answers: [0, 2, 4],
    explanation: l(
      'Jobs: Lehrer, Köchin, Ärztin. Adresse, Telefonnummer and Straße are personal data.',
      'Meslekler: Lehrer, Köchin, Ärztin. Adresse, Telefonnummer ve Straße kişisel bilgilerdir.',
      'Berufe: Lehrer, Köchin, Ärztin. Adresse, Telefonnummer und Straße sind Personalien.'
    ),
  },
  {
    id: 'match-questions',
    type: 'matching',
    topic: 'w-questions',
    concept: 'w-answer',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Match each question with its answer.', 'Her soruyu cevabıyla eşleştir.', 'Ordne Fragen und Antworten zu.'),
    pairs: [
      { left: 'Wie heißt du?', right: 'Ich heiße Anna.' },
      { left: 'Wo wohnst du?', right: 'In Berlin.' },
      { left: 'Woher kommst du?', right: 'Aus der Türkei.' },
      { left: 'Wie alt bist du?', right: 'Ich bin 25.' },
      { left: 'Was bist du von Beruf?', right: 'Ich bin Koch.' },
    ],
    explanation: l(
      'Wie = how/what (name), Wo = where, Woher = where from, Wie alt = how old, Was = what (job).',
      'Wie = nasıl/ne (isim), Wo = nerede, Woher = nereden, Wie alt = kaç yaşında, Was = ne (meslek).',
      'Wie (Name), Wo (Ort), Woher (Herkunft), Wie alt (Alter), Was (Beruf).'
    ),
  },
  {
    id: 'mc-wo',
    type: 'multiple_choice',
    topic: 'w-questions',
    concept: 'w-word',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ wohnst du? – In Köln.',
    options: ['Wo', 'Woher', 'Wie'],
    answer: 0,
    explanation: l(
      'Wo = where (place). Woher = where from (origin).',
      'Wo = nerede (yer). Woher = nereden (köken).',
      'Wo = Ort. Woher = Herkunft.'
    ),
    examples: ['**Wo** wohnst du? – In Köln.'],
    practice: ['mc-wer', 'mc-woher'],
  },
  {
    id: 'mc-wer',
    type: 'multiple_choice',
    topic: 'w-questions',
    concept: 'w-word',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ ist das? – Das ist Frau Klein.',
    options: ['Wer', 'Was', 'Wo'],
    answer: 0,
    explanation: l('Wer = who (a person).', 'Wer = kim (bir kişi).', 'Wer fragt nach einer Person.'),
    examples: ['**Wer** ist das? – Das ist Frau Klein.'],
  },
  {
    id: 'mc-woher',
    type: 'multiple_choice',
    topic: 'w-questions',
    concept: 'w-word',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ kommt Herr Haddad? – Aus Marokko.',
    options: ['Woher', 'Wo', 'Wie'],
    answer: 0,
    explanation: l('Woher = where from → aus …', 'Woher = nereden → aus …', 'Woher → aus …'),
    examples: ['**Woher** kommt er? – **Aus** Marokko.'],
  },

  // --- Practice 2: use --------------------------------------------------------
  {
    id: 'fill-hast',
    type: 'fill_blank',
    topic: 'haben',
    concept: 'haben-forms',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Du ___ ein Auto.',
    accepted: ['hast'],
    base: 'haben',
    explanation: l(
      'haben is a little irregular: ich habe, du hast, er hat, Sie haben.',
      'haben biraz düzensizdir: ich habe, du hast, er hat, Sie haben.',
      'haben ist etwas unregelmäßig: ich habe, du hast, er hat, Sie haben.'
    ),
    examples: ['Du **hast** ein Auto.'],
    practice: ['mc-hat'],
  },
  {
    id: 'mc-hat',
    type: 'multiple_choice',
    topic: 'haben',
    concept: 'haben-forms',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Herr Klein ___ ein Fahrrad.',
    options: ['habe', 'hast', 'hat'],
    answer: 2,
    explanation: l('er → hat (no b!).', 'er → hat (b yok!).', 'er → hat (ohne b!).'),
    examples: ['Herr Klein **hat** ein Fahrrad.'],
  },
  {
    id: 'fill-ist-alt',
    type: 'fill_blank',
    topic: 'sein',
    concept: 'age-sein',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Er ___ 40 Jahre alt.',
    accepted: ['ist'],
    base: 'sein',
    explanation: l('Age with sein: er ist 40.', 'Yaş sein ile: er ist 40.', 'Alter mit sein: er ist 40.'),
    examples: ['Er **ist** 40 Jahre alt.'],
  },
  {
    id: 'fill-bist',
    type: 'fill_blank',
    topic: 'sein',
    concept: 'age-sein',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wie alt ___ du?',
    accepted: ['bist'],
    base: 'sein',
    explanation: l('du bist: Wie alt bist du?', 'du bist: Wie alt bist du?', 'du bist: Wie alt bist du?'),
    examples: ['Wie alt **bist** du?'],
  },
  {
    id: 'mc-beruf-ohne-artikel',
    type: 'multiple_choice',
    topic: 'job',
    concept: 'job-no-article',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Was sind Sie von Beruf? – Ich bin ___.',
    options: ['Lehrerin', 'die Lehrerin', 'eine Lehrerin'],
    answer: 0,
    explanation: l(
      'For jobs German uses no article: Ich bin Lehrerin. (English: I am a teacher.)',
      'Meslek söylerken artikel kullanılmaz: Ich bin Lehrerin.',
      'Beim Beruf steht kein Artikel: Ich bin Lehrerin.'
    ),
    examples: ['Ich bin **Lehrerin**.', 'Er ist **Koch**.'],
  },
  {
    id: 'mc-lehrerin',
    type: 'multiple_choice',
    topic: 'job',
    concept: 'job-female',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Peter ist Lehrer. Maria ist ___.',
    options: ['Lehrer', 'Lehrerin', 'Lehrerinnen'],
    answer: 1,
    explanation: l('Female form: Lehrer + -in = Lehrerin.', 'Kadın biçimi: Lehrer + -in = Lehrerin.', 'Weibliche Form: Lehrer + -in = Lehrerin.'),
    examples: ['Maria ist **Lehrerin**.'],
  },
  {
    id: 'build-wie-alt',
    type: 'sentence_builder',
    topic: 'w-questions',
    concept: 'w-question',
    skill: 'grammar',
    difficulty: 1,
    chips: ['bist', 'alt', 'Wie', 'du'],
    answers: [['Wie', 'alt', 'bist', 'du']],
    end: '?',
    translation: l('How old are you?', 'Kaç yaşındasın?', 'Wie alt bist du?'),
    explanation: l(
      '„Wie alt“ is the question word – it stays together at the start. Then the verb.',
      '„Wie alt“ soru kelimesidir – başta birlikte durur. Sonra fiil gelir.',
      '„Wie alt“ ist das Fragewort – es steht zusammen vorne. Dann das Verb.'
    ),
    examples: ['**Wie alt** bist du?'],
  },
  {
    id: 'build-koch',
    type: 'sentence_builder',
    topic: 'job',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 1,
    chips: ['ist', 'Er', 'Koch'],
    answers: [['Er', 'ist', 'Koch']],
    translation: l('He is a cook.', 'O aşçı.', 'Er ist Koch.'),
    explanation: l('Er + ist + job (no article).', 'Er + ist + meslek (artikelsiz).', 'Er + ist + Beruf (ohne Artikel).'),
    examples: ['Er **ist** Koch.'],
  },
  {
    id: 'build-beruf',
    type: 'sentence_builder',
    topic: 'w-questions',
    concept: 'w-question',
    skill: 'grammar',
    difficulty: 2,
    chips: ['Sie', 'von Beruf', 'sind', 'Was'],
    answers: [['Was', 'sind', 'Sie', 'von Beruf']],
    end: '?',
    translation: l('What is your job? (formal)', 'Mesleğiniz nedir? (resmi)', 'Was sind Sie von Beruf?'),
    explanation: l(
      'Was + verb + Sie + „von Beruf“ at the end.',
      'Was + fiil + Sie + sonda „von Beruf“.',
      'Was + Verb + Sie + „von Beruf“ am Ende.'
    ),
    examples: ['Was **sind** Sie von Beruf?'],
  },
  {
    id: 'build-bremen',
    type: 'sentence_builder',
    topic: 'third-person',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 1,
    chips: ['wohnt', 'Bremen', 'in', 'Karim'],
    answers: [['Karim', 'wohnt', 'in', 'Bremen']],
    translation: l('Karim lives in Bremen.', 'Karim Bremen’de oturuyor.', 'Karim wohnt in Bremen.'),
    explanation: l('Karim + wohnt (-t) + in + city.', 'Karim + wohnt (-t) + in + şehir.', 'Karim + wohnt (-t) + in + Stadt.'),
    examples: ['Karim **wohnt** in Bremen.'],
  },
  {
    id: 'fix-habe-alt',
    type: 'error_correction',
    topic: 'sein',
    concept: 'age-sein',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe 30 Jahre alt.',
    accepted: ['Ich bin 30 Jahre alt.'],
    explanation: l('Age → sein: Ich bin 30 Jahre alt.', 'Yaş → sein: Ich bin 30 Jahre alt.', 'Alter → sein: Ich bin 30 Jahre alt.'),
    examples: ['Ich **bin** 30 Jahre alt.'],
  },
  {
    id: 'fix-wohnst',
    type: 'error_correction',
    topic: 'third-person',
    concept: 'ending-er',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Er wohnst in Köln.',
    accepted: ['Er wohnt in Köln.'],
    explanation: l('er → -t: Er wohnt in Köln.', 'er → -t: Er wohnt in Köln.', 'er → -t: Er wohnt in Köln.'),
    examples: ['Er **wohnt** in Köln.'],
  },
  {
    id: 'tr-aerztin',
    type: 'translation',
    topic: 'job',
    concept: 'job-no-article',
    skill: 'writing',
    difficulty: 2,
    source: l('She is a doctor.', 'O (kadın) doktor.', 'She is a doctor.'),
    accepted: ['Sie ist Ärztin.'],
    hint: l('doctor (woman) = Ärztin', 'kadın doktor = Ärztin', 'doctor (woman) = Ärztin'),
    explanation: l('Sie ist Ärztin. – no article before the job.', 'Sie ist Ärztin. – meslekten önce artikel yok.', 'Sie ist Ärztin. – kein Artikel vor dem Beruf.'),
    examples: ['Sie ist **Ärztin**.'],
  },
  {
    id: 'tr-wie-alt',
    type: 'translation',
    topic: 'w-questions',
    concept: 'age-sein',
    skill: 'writing',
    difficulty: 1,
    source: l('How old are you?', 'Kaç yaşındasın?', 'How old are you?'),
    accepted: ['Wie alt bist du?'],
    explanation: l('Wie alt + bist + du?', 'Wie alt + bist + du?', 'Wie alt + bist + du?'),
    examples: ['Wie alt **bist** du?'],
  },
  {
    id: 'dialog-telefon',
    type: 'dialogue',
    topic: 'w-questions',
    concept: 'w-answer',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Frau Roth', de: 'Und wie ist Ihre Telefonnummer?' }],
    options: ['0176 23 45 67.', 'In Berlin.', 'Ich bin 30.'],
    answer: 0,
    explanation: l('Telefonnummer → a number.', 'Telefonnummer → bir numara.', 'Telefonnummer → eine Nummer.'),
  },
  {
    id: 'dialog-beruf',
    type: 'dialogue',
    topic: 'job',
    concept: 'job-no-article',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Lena', de: 'Was machst du beruflich?' }],
    options: ['Ich bin Student.', 'Ich habe Student.', 'Ich heiße Student.'],
    answer: 0,
    explanation: l(
      '„Was machst du beruflich?“ = What do you do? → Ich bin + job.',
      '„Was machst du beruflich?“ = Ne iş yapıyorsun? → Ich bin + meslek.',
      'Auf „Was machst du beruflich?“ antwortet man: Ich bin + Beruf.'
    ),
    examples: ['Ich **bin** Student.'],
  },

  // --- Reading --------------------------------------------------------------
  {
    id: 'read-alt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-karim',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie alt ist Karim?',
    options: ['29', '31', '35'],
    answer: 1,
    explanation: l('Alter: 31', 'Alter: 31', 'Alter: 31'),
  },
  {
    id: 'read-beruf',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-karim',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was ist Karim von Beruf?',
    options: ['Lehrer', 'Koch', 'Arzt'],
    answer: 1,
    explanation: l('„Er ist Koch in einem Restaurant.“', '„Er ist Koch in einem Restaurant.“', '„Er ist Koch in einem Restaurant.“'),
  },
  {
    id: 'read-sohn',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-karim',
    skill: 'reading',
    difficulty: 2,
    statement: 'Karim hat einen Sohn.',
    answer: false,
    explanation: l('„Er hat eine Tochter.“ – a daughter, not a son.', '„Er hat eine Tochter.“ – oğlu değil, kızı var.', '„Er hat eine Tochter.“'),
  },
  {
    id: 'read-woher',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-karim',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Woher kommt Karim?',
    options: ['Aus Marokko.', 'Aus Bremen.', 'Aus der Türkei.'],
    answer: 0,
    explanation: l('„Karim kommt aus Marokko.“', '„Karim kommt aus Marokko.“', '„Karim kommt aus Marokko.“'),
  },

  // --- Listening -----------------------------------------------------------
  {
    id: 'listen-alter',
    type: 'listening_choice',
    topic: 'sein',
    concept: 'age-sein',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich heiße Sofia. Ich bin siebenundzwanzig Jahre alt.',
    question: l('How old is Sofia?', 'Sofia kaç yaşında?', 'Wie alt ist Sofia?'),
    options: ['17', '27', '37'],
    answer: 1,
    explanation: l('siebenundzwanzig = 27 (seven-and-twenty).', 'siebenundzwanzig = 27 (yedi-ve-yirmi).', 'siebenundzwanzig = 27'),
  },
  {
    id: 'listen-beruf',
    type: 'listening_choice',
    topic: 'job',
    concept: 'jobs',
    skill: 'listening',
    difficulty: 1,
    audio: 'Guten Tag! Ich bin Ärztin.',
    question: l('What is her job?', 'Mesleği ne?', 'Was ist sie von Beruf?'),
    options: ['🩺 Ärztin', '🧑‍🏫 Lehrerin', '👨‍🍳 Köchin'],
    answer: 0,
    explanation: l('„Ich bin Ärztin.“', '„Ich bin Ärztin.“', '„Ich bin Ärztin.“'),
  },
  {
    id: 'listen-leipzig',
    type: 'listening_choice',
    topic: 'third-person',
    concept: 'ending-er',
    skill: 'listening',
    difficulty: 1,
    audio: 'Das ist Paul. Er wohnt in Leipzig.',
    question: l('Where does Paul live?', 'Paul nerede oturuyor?', 'Wo wohnt Paul?'),
    options: ['In Leipzig.', 'In Dresden.', 'In Berlin.'],
    answer: 0,
    explanation: l('„Er wohnt in Leipzig.“', '„Er wohnt in Leipzig.“', '„Er wohnt in Leipzig.“'),
  },
  {
    id: 'listen-kinder',
    type: 'listening_choice',
    topic: 'haben',
    concept: 'haben-forms',
    skill: 'listening',
    difficulty: 2,
    audio: 'Haben Sie Kinder? – Ja, ich habe zwei Kinder.',
    question: l('How many children?', 'Kaç çocuk?', 'Wie viele Kinder?'),
    options: ['1', '2', '3'],
    answer: 1,
    explanation: l('zwei = 2.', 'zwei = 2.', 'zwei = 2.'),
  },

  ...seinHabenDrills(),
]

export const UNIT02_WER_BIST_DU: CourseUnit = {
  level: 'A1',
  number: 2,
  slug: 'wer-bist-du',
  titleDe: 'Wer bist du?',
  title: l('Who are you?', 'Sen kimsin?', 'Wer bist du?'),
  goal: l(
    'By the end of this unit you can give and ask for personal information – age, job, address, phone number – and talk about another person.',
    'Bu ünitenin sonunda kişisel bilgileri – yaş, meslek, adres, telefon – sorup söyleyebilir ve başka biri hakkında konuşabilirsin.',
    'Am Ende dieser Einheit kannst du persönliche Angaben machen und erfragen – Alter, Beruf, Adresse, Telefonnummer – und über andere Personen sprechen.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'third-person', label: l('er / sie: -t', 'er / sie: -t', 'er / sie: -t') },
    { key: 'sein', label: l('sein & age', 'sein ve yaş', 'sein & Alter') },
    { key: 'haben', label: l('haben', 'haben', 'haben') },
    { key: 'job', label: l('Jobs', 'Meslekler', 'Berufe') },
    { key: 'w-questions', label: l('W-questions', 'Soru kelimeleri', 'W-Fragen') },
    { key: 'vocabulary', label: l('Vocabulary', 'Kelime', 'Wortschatz') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l(
        'Jobs and personal data. Every noun with its article – and jobs also in the female form.',
        'Meslekler ve kişisel bilgiler. Her isim artikeliyle – meslekler kadın biçimiyle de.',
        'Berufe und Personalien. Jedes Nomen mit Artikel – Berufe auch in der weiblichen Form.'
      ),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Talking about others: er / sie + -t', 'Başkaları hakkında: er / sie + -t', 'Über andere sprechen: er / sie + -t'),
          body: l(
            'For he/she (er, sie, a name) the verb ends in -t. Verbs with -t/-d in the stem add -et: er arbeitet.',
            'O (er, sie, bir isim) için fiil -t ile biter. Kökü -t/-d ile biten fiiller -et alır: er arbeitet.',
            'Bei er, sie oder einem Namen endet das Verb auf -t. Verben mit -t/-d im Stamm bekommen -et: er arbeitet.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('wohnen', 'wohnen', 'wohnen'), l('arbeiten', 'arbeiten', 'arbeiten')],
            rows: [
              ['ich', 'wohne', 'arbeite'],
              ['du', 'wohnst', 'arbeitest'],
              ['er / sie', 'wohnt', 'arbeitet'],
              ['Sie', 'wohnen', 'arbeiten'],
            ],
          },
        },
        {
          title: l('haben – to have', 'haben – sahip olmak', 'haben'),
          body: l(
            'Almost regular – only du hast and er hat lose the b.',
            'Neredeyse düzenli – yalnızca du hast ve er hat biçimlerinde b düşer.',
            'Fast regelmäßig – nur bei du hast und er hat fällt das b weg.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('haben', 'haben', 'haben'), l('sein', 'sein', 'sein')],
            rows: [
              ['ich', 'habe', 'bin'],
              ['du', 'hast', 'bist'],
              ['er / sie', 'hat', 'ist'],
              ['Sie', 'haben', 'sind'],
            ],
          },
        },
        {
          title: l('Age: sein, not haben', 'Yaş: haben değil sein', 'Alter: sein, nicht haben'),
          body: l(
            'Ich bin 25 (Jahre alt). Never „Ich habe 25 Jahre“.',
            'Ich bin 25 (Jahre alt). Asla „Ich habe 25 Jahre“ değil.',
            'Ich bin 25 (Jahre alt). Nie „Ich habe 25 Jahre“.'
          ),
          examples: [
            { de: 'Wie alt **bist** du? – Ich **bin** 25.', translation: l('How old are you? – I’m 25.', 'Kaç yaşındasın? – 25 yaşındayım.', 'Alter') },
            { de: 'Er **ist** 40 Jahre alt.', translation: l('He is 40 years old.', 'O 40 yaşında.', 'Alter') },
          ],
        },
        {
          title: l('Jobs: no article, female form with -in', 'Meslekler: artikelsiz, kadın biçimi -in ile', 'Berufe: ohne Artikel, weiblich mit -in'),
          body: l(
            'Ich bin Lehrer. / Ich bin Lehrerin. No „ein“. Ask: Was bist du von Beruf? / Was machen Sie beruflich?',
            'Ich bin Lehrer. / Ich bin Lehrerin. „ein“ yok. Sorusu: Was bist du von Beruf? / Was machen Sie beruflich?',
            'Ich bin Lehrer. / Ich bin Lehrerin. Ohne „ein“. Frage: Was bist du von Beruf? / Was machen Sie beruflich?'
          ),
          table: {
            head: [l('male', 'erkek', 'männlich'), l('female', 'kadın', 'weiblich')],
            rows: [
              ['Lehrer', 'Lehrerin'],
              ['Student', 'Studentin'],
              ['Arzt', 'Ärztin'],
              ['Koch', 'Köchin'],
            ],
          },
          tip: l(
            'Some female forms add an umlaut: Arzt → Ärztin, Koch → Köchin.',
            'Bazı kadın biçimleri umlaut alır: Arzt → Ärztin, Koch → Köchin.',
            'Manche weiblichen Formen bekommen einen Umlaut: Arzt → Ärztin, Koch → Köchin.'
          ),
        },
        {
          title: l('W-questions', 'Soru kelimeleri', 'W-Fragen'),
          body: l(
            'Question word first, verb second: Wie heißt du? Wo wohnst du? Woher kommst du? Wie alt bist du? Was bist du von Beruf? Wer ist das?',
            'Önce soru kelimesi, sonra fiil: Wie heißt du? Wo wohnst du? Woher kommst du? Wie alt bist du? Was bist du von Beruf? Wer ist das?',
            'Fragewort zuerst, Verb an zweiter Stelle: Wie heißt du? Wo wohnst du? Woher kommst du? Wie alt bist du? Was bist du von Beruf? Wer ist das?'
          ),
          tip: l(
            'Address and phone number: „Wie ist Ihre Adresse?“ – Germans say Wie, not Was.',
            'Adres ve telefon: „Wie ist Ihre Adresse?“ – Almanlar Was değil Wie der.',
            'Adresse und Telefonnummer: „Wie ist Ihre Adresse?“ – mit Wie, nicht mit Was.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l(
        'Karim registers for a German course. The secretary fills in the form.',
        'Karim bir Almanca kursuna kayıt oluyor. Sekreter formu dolduruyor.',
        'Karim meldet sich für einen Deutschkurs an. Die Sekretärin füllt das Formular aus.'
      ),
      dialogue: [
        { speaker: 'Frau Roth', de: 'Guten Tag. **Wie ist** Ihr Name, bitte?', translation: l('Hello. What is your name, please?', 'İyi günler. Adınız nedir, lütfen?', '') },
        { speaker: 'Karim', de: 'Mein Name ist Karim Haddad.', translation: l('My name is Karim Haddad.', 'Adım Karim Haddad.', '') },
        { speaker: 'Frau Roth', de: '**Wie alt sind** Sie, Herr Haddad?', translation: l('How old are you, Mr Haddad?', 'Kaç yaşındasınız, Bay Haddad?', '') },
        { speaker: 'Karim', de: 'Ich **bin** 31.', translation: l('I’m 31.', '31 yaşındayım.', '') },
        { speaker: 'Frau Roth', de: '**Was sind** Sie **von Beruf**?', translation: l('What is your job?', 'Mesleğiniz nedir?', '') },
        { speaker: 'Karim', de: 'Ich **bin** Koch.', translation: l('I’m a cook.', 'Aşçıyım.', '') },
        { speaker: 'Frau Roth', de: 'Und **wie ist** Ihre Adresse?', translation: l('And what is your address?', 'Peki adresiniz nedir?', '') },
        { speaker: 'Karim', de: 'Lindenstraße 12, in Bremen.', translation: l('Lindenstraße 12, in Bremen.', 'Lindenstraße 12, Bremen’de.', '') },
        { speaker: 'Frau Roth', de: '**Haben** Sie eine E-Mail-Adresse?', translation: l('Do you have an e-mail address?', 'E-posta adresiniz var mı?', '') },
        { speaker: 'Karim', de: 'Ja: karim.haddad@mail.de.', translation: l('Yes: karim.haddad@mail.de.', 'Evet: karim.haddad@mail.de.', '') },
      ],
      examples: [
        { de: 'Er **heißt** Tom. Er **ist** 30 Jahre alt.', translation: l('His name is Tom. He is 30.', 'Onun adı Tom. 30 yaşında.', '') },
        { de: 'Sie **ist** Ärztin.', translation: l('She is a doctor.', 'O doktor.', '') },
        { de: 'Ich **habe** zwei Kinder.', translation: l('I have two children.', 'İki çocuğum var.', '') },
        { de: 'Wie alt **bist** du?', translation: l('How old are you?', 'Kaç yaşındasın?', '') },
        { de: 'Was **sind** Sie von Beruf?', translation: l('What is your job?', 'Mesleğiniz nedir?', '') },
        { de: 'Er **wohnt** in Bremen und **arbeitet** in einem Restaurant.', translation: l('He lives in Bremen and works in a restaurant.', 'Bremen’de oturuyor ve bir restoranda çalışıyor.', '') },
        { de: '**Hast** du ein Handy? – Ja, natürlich.', translation: l('Do you have a phone? – Yes, of course.', 'Telefonun var mı? – Evet, tabii.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l(
        'Jobs, sein and haben, question words – recognise the right form.',
        'Meslekler, sein ve haben, soru kelimeleri – doğru biçimi tanı.',
        'Berufe, sein und haben, Fragewörter – erkenne die richtige Form.'
      ),
      exercises: ['img-arzt', 'match-jobs', 'mc-wohnt', 'mc-ist-aerztin', 'tf-jahre', 'sort-sein-haben', 'select-jobs', 'match-questions', 'mc-wo'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l(
        'Now fill in the forms yourself, ask questions and build sentences.',
        'Şimdi biçimleri kendin doldur, soru sor ve cümle kur.',
        'Jetzt ergänzt du selbst, stellst Fragen und baust Sätze.'
      ),
      exercises: [
        'fill-hast',
        'fill-ist-alt',
        'fill-bist',
        'mc-beruf-ohne-artikel',
        'mc-lehrerin',
        'build-wie-alt',
        'build-koch',
        'build-beruf',
        'build-bremen',
        'fix-habe-alt',
        'fix-wohnst',
        'tr-aerztin',
        'tr-wie-alt',
        'dialog-telefon',
        'dialog-beruf',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Karim’s registration form – and a short text about him.', 'Karim’in kayıt formu – ve onun hakkında kısa bir metin.', 'Karims Anmeldeformular – und ein kurzer Text über ihn.'),
      passage: [
        'Vorname: Karim · Nachname: Haddad · Alter: 31 · Beruf: Koch · Adresse: Lindenstraße 12, 28195 Bremen',
        'Karim **kommt** aus Marokko.',
        'Er **wohnt** seit zwei Jahren in Bremen.',
        'Er **ist** Koch in einem Restaurant.',
        'Er **hat** eine Tochter. Sie heißt Lina und ist fünf.',
      ],
      glossary: [
        { de: 'seit zwei Jahren', note: l('for two years', 'iki yıldır', 'zwei Jahre lang bis heute') },
        { de: 'in einem Restaurant', note: l('in a restaurant', 'bir restoranda', 'in einem Lokal') },
        { de: 'die Tochter', note: l('daughter (der Sohn = son)', 'kız evlat (der Sohn = oğul)', 'das Mädchen-Kind (der Sohn = Junge)') },
      ],
      exercises: ['read-alt', 'read-beruf', 'read-sohn', 'read-woher'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('People talk about themselves and others.', 'İnsanlar kendileri ve başkaları hakkında konuşuyor.', 'Menschen sprechen über sich und andere.'),
      exercises: ['listen-alter', 'listen-beruf', 'listen-leipzig', 'listen-kinder'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Introduce a friend or family member (er/sie).', 'Bir arkadaşını ya da aile üyeni tanıt (er/sie).', 'Stell eine Freundin, einen Freund oder ein Familienmitglied vor (er/sie).'),
      points: [
        l('Name: „Das ist … Er/Sie heißt …“', 'Adı: „Das ist … Er/Sie heißt …“', 'Name: „Das ist … Er/Sie heißt …“'),
        l('Age: „Er/Sie ist … Jahre alt.“', 'Yaşı: „Er/Sie ist … Jahre alt.“', 'Alter: „Er/Sie ist … Jahre alt.“'),
        l('Job: „Er ist Lehrer.“ / „Sie ist Lehrerin.“', 'Mesleği: „Er ist Lehrer.“ / „Sie ist Lehrerin.“', 'Beruf: „Er ist Lehrer.“ / „Sie ist Lehrerin.“'),
        l('City: „Er/Sie wohnt in …“', 'Şehri: „Er/Sie wohnt in …“', 'Wohnort: „Er/Sie wohnt in …“'),
      ],
      model: ['Das ist meine Freundin Elif.', 'Sie ist 28 Jahre alt.', 'Sie ist Programmiererin.', 'Sie wohnt in Hamburg und hat eine Katze.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short profile of a person you know (at least 4 sentences).',
        'Tanıdığın bir kişinin kısa profilini yaz (en az 4 cümle).',
        'Schreib ein kurzes Profil über eine Person, die du kennst (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('Age with sein (… ist … Jahre alt)', 'sein ile yaş (… ist … Jahre alt)', 'Alter mit sein (… ist … Jahre alt)'), pattern: '\\bist\\b[^.!?]*\\bJahre alt\\b' },
        { label: l('A verb with -t (wohnt, kommt, arbeitet …)', '-t ekli bir fiil (wohnt, kommt, arbeitet …)', 'Ein Verb auf -t (wohnt, kommt, arbeitet …)'), pattern: '\\b(wohnt|kommt|arbeitet|heißt|heisst|lernt|spricht)\\b' },
        { label: l('Uses haben (hat …)', 'haben kullanılmış (hat …)', 'Mit haben (hat …)'), pattern: '\\bhat\\b' },
      ],
      model: ['Das ist mein Bruder Can.', 'Er ist 35 Jahre alt.', 'Er ist Lehrer.', 'Er wohnt in Izmir und hat zwei Kinder.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('sein and haben – as fast as you can.', 'sein ve haben – olabildiğince hızlı.', 'sein und haben – so schnell du kannst.'),
      seconds: 60,
      pool: (['sein', 'haben'] as const).flatMap((verb) => PERSONS.map((person) => `${verb}-${person.toLowerCase()}`)),
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('er / sie + -t: er wohnt, sie kommt', 'er / sie + -t: er wohnt, sie kommt', 'er / sie + -t: er wohnt, sie kommt'),
      l('haben: ich habe, du hast, er hat, Sie haben', 'haben: ich habe, du hast, er hat, Sie haben', 'haben: ich habe, du hast, er hat, Sie haben'),
      l('Age with sein: Ich bin 25.', 'sein ile yaş: Ich bin 25.', 'Alter mit sein: Ich bin 25.'),
      l('Jobs without article, female form with -in', 'Meslekler artikelsiz, kadın biçimi -in ile', 'Berufe ohne Artikel, weiblich mit -in'),
      l('W-questions: Wer? Was? Wo? Woher? Wie alt?', 'Soru kelimeleri: Wer? Was? Wo? Woher? Wie alt?', 'W-Fragen: Wer? Was? Wo? Woher? Wie alt?'),
    ],
    mistakes: [
      { wrong: 'Ich habe 25 Jahre.', right: 'Ich bin 25 Jahre alt.', note: l('Age → sein.', 'Yaş → sein.', 'Alter → sein.') },
      { wrong: 'Er wohnst in Köln.', right: 'Er wohnt in Köln.', note: l('er → -t', 'er → -t', 'er → -t') },
      { wrong: 'Ich bin ein Lehrer.', right: 'Ich bin Lehrer.', note: l('No article for jobs.', 'Meslekte artikel yok.', 'Kein Artikel beim Beruf.') },
      { wrong: 'Er habt ein Auto.', right: 'Er hat ein Auto.', note: l('er hat', 'er hat', 'er hat') },
    ],
  },
}
