import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

/** A1 at a glance – one card per big milestone of the course. */
const VOCAB: VocabItem[] = [
  { word: 'der · die · das', emoji: '🔤', translation: l('articles (Units 05–06)', 'artikeller (Ünite 05–06)', 'Artikel (Einheit 05–06)'), example: 'Der Tisch ist neu.' },
  { word: 'ich bin · ich habe', emoji: '🙋', translation: l('sein & haben (Units 01, 02, 10)', 'sein ve haben (Ünite 01, 02, 10)', 'sein & haben'), example: 'Ich bin müde und habe Hunger.' },
  { word: 'Verb auf Position 2', emoji: '2️⃣', translation: l('word order (Unit 08)', 'cümle yapısı (Ünite 08)', 'Satzbau (Einheit 08)'), example: 'Heute lerne ich Deutsch.' },
  { word: 'Wo? Woher? Wohin?', emoji: '❓', translation: l('questions (Unit 09)', 'sorular (Ünite 09)', 'Fragen (Einheit 09)'), example: 'Woher kommst du?' },
  { word: 'einen · den', emoji: '🎯', translation: l('Akkusativ (Unit 11)', 'Akkusativ (Ünite 11)', 'Akkusativ (Einheit 11)'), example: 'Ich habe einen Hund.' },
  { word: 'mit dem · zum · zur', emoji: '🚌', translation: l('Dativ (Unit 19)', 'Dativ (Ünite 19)', 'Dativ (Einheit 19)'), example: 'Ich fahre mit dem Bus zur Arbeit.' },
  { word: 'kann · muss · möchte', emoji: '💪', translation: l('modal verbs (Unit 14)', 'modal fiiller (Ünite 14)', 'Modalverben (Einheit 14)'), example: 'Ich muss heute arbeiten.' },
  { word: 'stehe … auf', emoji: '✂️', translation: l('separable verbs (Unit 15)', 'ayrılabilen fiiller (Ünite 15)', 'trennbare Verben (Einheit 15)'), example: 'Ich stehe um sieben Uhr auf.' },
  { word: 'habe … gemacht', emoji: '⏮️', translation: l('past tense (Unit 24)', 'geçmiş zaman (Ünite 24)', 'Perfekt (Einheit 24)'), example: 'Gestern habe ich gekocht.' },
  { word: 'halb drei · 2,50 €', emoji: '🕒', translation: l('numbers & time (Unit 03)', 'sayılar ve saat (Ünite 03)', 'Zahlen & Uhrzeit (Einheit 03)'), example: 'Es ist halb drei.' },
  { word: 'Ich hätte gern …', emoji: '☕', translation: l('ordering & shopping (Units 12, 13, 21)', 'sipariş ve alışveriş (Ünite 12, 13, 21)', 'Bestellen & Einkaufen'), example: 'Ich hätte gern einen Tee.' },
  { word: 'Gute Besserung!', emoji: '🤒', translation: l('everyday situations (Units 17–23)', 'günlük durumlar (Ünite 17–23)', 'Alltagssituationen'), example: 'Ich habe Kopfschmerzen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Hund', gender: 'm', plural: 'die Hunde', translation: l('dog', 'köpek', 'Hund') },
  { word: 'Tisch', gender: 'm', plural: 'die Tische', translation: l('table', 'masa', 'Tisch') },
  { word: 'Wohnung', gender: 'f', plural: 'die Wohnungen', translation: l('flat', 'daire', 'Wohnung') },
  { word: 'Schwester', gender: 'f', plural: 'die Schwestern', translation: l('sister', 'kız kardeş', 'Schwester') },
  { word: 'Bruder', gender: 'm', plural: 'die Brüder', translation: l('brother', 'erkek kardeş', 'Bruder') },
  { word: 'Auto', gender: 'n', plural: 'die Autos', translation: l('car', 'araba', 'Auto') },
  { word: 'Buch', gender: 'n', plural: 'die Bücher', translation: l('book', 'kitap', 'Buch') },
  { word: 'Bus', gender: 'm', plural: 'die Busse', translation: l('bus', 'otobüs', 'Bus') },
  { word: 'U-Bahn', gender: 'f', plural: 'die U-Bahnen', translation: l('underground', 'metro', 'U-Bahn') },
  { word: 'Arbeit', gender: 'f', translation: l('work', 'iş', 'Arbeit') },
]

const EXERCISES: Exercise[] = [
  // --- Grammar: mixed, without topic labels ---------------------------
  {
    id: 'g-artikel',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'gender-f',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Wohnung ist hell.',
    options: ['Der', 'Die', 'Das'],
    answer: 1,
    explanation: l('die Wohnung (feminine, -ung → always die).', 'die Wohnung (dişil, -ung → her zaman die).', 'die Wohnung (-ung → die).'),
    examples: ['{f:Die Wohnung} ist hell.'],
  },
  {
    id: 'g-akk',
    type: 'multiple_choice',
    topic: 'cases',
    concept: 'akk-indef-m',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich habe ___ Bruder.',
    options: ['einen', 'ein', 'eine'],
    answer: 0,
    explanation: l('der Bruder + haben → Akkusativ: einen Bruder.', 'der Bruder + haben → Akkusativ: einen Bruder.', 'einen Bruder.'),
    examples: ['Ich habe {m:einen Bruder}.'],
  },
  {
    id: 'g-wohnen',
    type: 'fill_blank',
    topic: 'verbs',
    concept: 'ending-wir',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wir ___ in Graz.',
    accepted: ['wohnen'],
    base: 'wohnen',
    explanation: l('wir → -en.', 'wir → -en.', 'wir → -en.'),
    examples: ['Wir **wohnen** in Graz.'],
  },
  {
    id: 'g-sprichst',
    type: 'multiple_choice',
    topic: 'verbs',
    concept: 'stem-change',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Du ___ sehr gut Deutsch!',
    options: ['sprichst', 'sprechst', 'sprecht'],
    answer: 0,
    explanation: l('sprechen: du sprichst (e → i).', 'sprechen: du sprichst (e → i).', 'du sprichst.'),
    examples: ['Du **sprichst** sehr gut Deutsch.'],
  },
  {
    id: 'g-satz',
    type: 'sentence_builder',
    topic: 'word-order',
    concept: 'inversion',
    skill: 'grammar',
    difficulty: 2,
    chips: ['nicht', 'arbeite', 'Morgen', 'ich'],
    answers: [['Morgen', 'arbeite', 'ich', 'nicht']],
    translation: l('Tomorrow I’m not working.', 'Yarın çalışmıyorum.', 'Morgen arbeite ich nicht.'),
    explanation: l('Time (1) + verb (2) + subject + nicht.', 'Zaman (1) + fiil (2) + özne + nicht.', 'Zeit + Verb + Subjekt + nicht.'),
    examples: ['Morgen **arbeite** ich nicht.'],
  },
  {
    id: 'g-dativ',
    type: 'multiple_choice',
    topic: 'cases',
    concept: 'dat-f',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich fahre ___ U-Bahn zur Arbeit.',
    options: ['mit der', 'mit dem', 'mit die'],
    answer: 0,
    explanation: l('mit + Dativ: die U-Bahn → mit der U-Bahn.', 'mit + Dativ: die U-Bahn → mit der U-Bahn.', 'mit der U-Bahn.'),
    examples: ['Ich fahre **mit der U-Bahn**.'],
  },
  {
    id: 'g-modal',
    type: 'error_correction',
    topic: 'word-order',
    concept: 'modal-bracket',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich muss heute arbeiten nicht.',
    accepted: ['Ich muss heute nicht arbeiten.', 'Heute muss ich nicht arbeiten.'],
    explanation: l('Infinitive at the very end: … nicht arbeiten.', 'Mastar en sonda: … nicht arbeiten.', 'Infinitiv ganz am Ende.'),
    examples: ['Ich **muss** heute nicht **arbeiten**.'],
  },
  {
    id: 'g-perfekt',
    type: 'multiple_choice',
    topic: 'verbs',
    concept: 'haben-form',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Gestern ___ ich Fußball gespielt.',
    options: ['habe', 'bin', 'hatte'],
    answer: 0,
    explanation: l('Perfekt: habe … gespielt.', 'Perfekt: habe … gespielt.', 'habe … gespielt.'),
    examples: ['Gestern **habe** ich Fußball **gespielt**.'],
  },
  {
    id: 'g-trennbar',
    type: 'sentence_builder',
    topic: 'word-order',
    concept: 'separable',
    skill: 'grammar',
    difficulty: 2,
    chips: ['an', 'Der Film', 'um 20 Uhr', 'fängt'],
    answers: [['Der Film', 'fängt', 'um 20 Uhr', 'an']],
    translation: l('The film starts at 8 pm.', 'Film saat 20’de başlıyor.', 'Der Film fängt um 20 Uhr an.'),
    explanation: l('fängt (2) … an (end).', 'fängt (2) … an (son).', 'fängt … an.'),
    examples: ['Der Film **fängt** um 20 Uhr **an**.'],
  },
  {
    id: 'g-faelle',
    type: 'categorize',
    topic: 'cases',
    concept: 'cases-mixed',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('Nominativ, Akkusativ or Dativ? (all masculine)', 'Nominativ, Akkusativ mı Dativ mi? (hepsi eril)', 'Nominativ, Akkusativ oder Dativ? (alle maskulin)'),
    categories: ['Nominativ', 'Akkusativ', 'Dativ'],
    items: [
      { text: 'der Hund', category: 0 },
      { text: 'den Hund', category: 1 },
      { text: 'dem Hund', category: 2 },
      { text: 'ein Tisch', category: 0 },
      { text: 'einen Tisch', category: 1 },
      { text: 'einem Tisch', category: 2 },
    ],
    explanation: l(
      'Masculine: der/ein (subject) → den/einen (after haben, kaufen …) → dem/einem (after mit, bei, zu).',
      'Eril: der/ein (özne) → den/einen (haben, kaufen … sonrası) → dem/einem (mit, bei, zu sonrası).',
      'der → den → dem, ein → einen → einem.'
    ),
  },
  {
    id: 'g-wie-viele',
    type: 'true_false',
    topic: 'word-order',
    concept: 'wie-viel',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Wie viel Kinder hast du?',
    answer: false,
    instructions: l('Is this sentence correct?', 'Bu cümle doğru mu?', 'Ist der Satz richtig?'),
    explanation: l('Countable plural → Wie viele Kinder hast du?', 'Sayılabilen çoğul → Wie viele Kinder hast du?', 'Wie viele Kinder …?'),
    examples: ['**Wie viele** Kinder hast du?'],
  },
  {
    id: 'g-woher',
    type: 'multiple_choice',
    topic: 'word-order',
    concept: 'wo-woher-wohin',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ kommst du? – Aus Brasilien.',
    options: ['Woher', 'Wo', 'Wohin'],
    answer: 0,
    explanation: l('aus … → Woher?', 'aus … → Woher?', 'aus … → Woher?'),
    examples: ['**Woher** kommst du?'],
  },
  {
    id: 'g-kein',
    type: 'translation',
    topic: 'articles',
    concept: 'kein',
    skill: 'writing',
    difficulty: 2,
    source: l('We don’t have a car.', 'Arabamız yok.', 'We don’t have a car.'),
    accepted: ['Wir haben kein Auto.'],
    explanation: l('das Auto → kein Auto.', 'das Auto → kein Auto.', 'kein Auto.'),
    examples: ['Wir haben {n:kein Auto}.'],
  },
  {
    id: 'g-helfen',
    type: 'dialogue',
    topic: 'word-order',
    concept: 'modal-bracket',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Nachbarin', de: 'Kannst du mir morgen helfen?' }],
    options: ['Ja, gern! Um wie viel Uhr?', 'Ja, ich kann helfen dir.', 'Ja, ich helfe gern dich.'],
    answer: 0,
    explanation: l('A natural answer: Ja, gern! + a question.', 'Doğal bir cevap: Ja, gern! + bir soru.', 'Ja, gern!'),
  },
  {
    id: 'g-plural',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'plural',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'ein Buch, zwei ___',
    options: ['Bücher', 'Buchs', 'Buche'],
    answer: 0,
    explanation: l('das Buch → die Bücher.', 'das Buch → die Bücher.', 'die Bücher.'),
    examples: ['zwei **Bücher**'],
  },
  {
    id: 'g-eltern',
    type: 'error_correction',
    topic: 'verbs',
    concept: 'plural-verb',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Meine Eltern wohnt in Izmir.',
    accepted: ['Meine Eltern wohnen in Izmir.'],
    explanation: l('meine Eltern (plural) → wohnen.', 'meine Eltern (çoğul) → wohnen.', 'Plural → wohnen.'),
    examples: ['Meine Eltern **wohnen** in Izmir.'],
  },
  {
    id: 'g-meine',
    type: 'multiple_choice',
    topic: 'articles',
    concept: 'possessive-meine',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Das ist ___ Schwester.',
    options: ['meine', 'mein'],
    answer: 0,
    explanation: l('die Schwester → meine.', 'die Schwester → meine.', 'meine Schwester.'),
    examples: ['Das ist {f:meine Schwester}.'],
  },
  {
    id: 'g-sein',
    type: 'multiple_choice',
    topic: 'verbs',
    concept: 'sein-or-haben',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich ___ heute sehr müde.',
    options: ['bin', 'habe', 'ist'],
    answer: 0,
    explanation: l('müde (adjective) → sein: ich bin müde.', 'müde (sıfat) → sein: ich bin müde.', 'ich bin müde.'),
    examples: ['Ich **bin** müde.'],
  },

  // --- Vocabulary -----------------------------------------------------
  {
    id: 'v-bild',
    type: 'image_choice',
    topic: 'vocabulary',
    concept: 'mixed-vocab',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'die Apotheke',
    options: [
      { emoji: '🚉', label: 'der Bahnhof' },
      { emoji: '💊', label: 'die Apotheke' },
      { emoji: '🏦', label: 'die Bank' },
      { emoji: '🏫', label: 'die Schule' },
    ],
    answer: 1,
    explanation: l('die Apotheke = pharmacy.', 'die Apotheke = eczane.', 'die Apotheke.'),
  },
  {
    id: 'v-match',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'mixed-vocab',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match words from the whole course.', 'Tüm kurstan kelimeleri eşleştir.', 'Wörter aus dem ganzen Kurs.'),
    pairs: [
      { left: 'der Bahnhof', right: '🚉' },
      { left: 'die Hose', right: '👖' },
      { left: 'das Brot', right: '🍞' },
      { left: 'der Arzt', right: '🩺' },
      { left: 'die Uhr', right: '⌚' },
    ],
    explanation: l('der Bahnhof, die Hose, das Brot, der Arzt, die Uhr.', 'der Bahnhof, die Hose, das Brot, der Arzt, die Uhr.', 'Wortschatz-Mix.'),
  },
  {
    id: 'v-getraenke',
    type: 'multiple_select',
    topic: 'vocabulary',
    concept: 'food',
    skill: 'vocabulary',
    difficulty: 1,
    promptL10n: l('Which are drinks? Select all.', 'Hangileri içecek? Hepsini seç.', 'Was sind Getränke? Wähle alle.'),
    options: ['Kaffee', 'Brot', 'Saft', 'Käse', 'Wasser', 'Apfel'],
    answers: [0, 2, 4],
    explanation: l('Kaffee, Saft, Wasser.', 'Kaffee, Saft, Wasser.', 'Kaffee, Saft, Wasser.'),
  },
  {
    id: 'v-genus',
    type: 'categorize',
    topic: 'articles',
    concept: 'gender-mixed',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('der, die or das?', 'der, die mi das mı?', 'der, die oder das?'),
    categories: ['der', 'die', 'das'],
    items: [
      { text: 'Kühlschrank', category: 0 },
      { text: 'Küche', category: 1 },
      { text: 'Fenster', category: 2 },
      { text: 'Bahnhof', category: 0 },
      { text: 'Hose', category: 1 },
      { text: 'Hemd', category: 2 },
    ],
    explanation: l(
      'der Kühlschrank, der Bahnhof · die Küche, die Hose · das Fenster, das Hemd.',
      'der Kühlschrank, der Bahnhof · die Küche, die Hose · das Fenster, das Hemd.',
      'der Kühlschrank, die Küche, das Fenster …'
    ),
  },
  {
    id: 'v-uhr',
    type: 'multiple_choice',
    topic: 'vocabulary',
    concept: 'clock-viertel',
    skill: 'vocabulary',
    difficulty: 2,
    prompt: 'Es ist Viertel nach drei. = ___',
    options: ['3:15', '2:45', '3:45'],
    answer: 0,
    explanation: l('Viertel nach drei = 3:15.', 'Viertel nach drei = 3:15.', '3:15.'),
  },
  {
    id: 'v-monat',
    type: 'multiple_choice',
    topic: 'vocabulary',
    concept: 'months',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Welcher Monat kommt nach März?',
    options: ['April', 'Mai', 'Februar'],
    answer: 0,
    explanation: l('Januar, Februar, März, April …', 'Januar, Februar, März, April …', 'März → April.'),
  },
  {
    id: 'v-gegenteil',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'adjectives',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Find the opposites.', 'Zıt anlamlıları bul.', 'Finde die Gegenteile.'),
    pairs: [
      { left: 'groß', right: 'klein' },
      { left: 'teuer', right: 'billig' },
      { left: 'hell', right: 'dunkel' },
      { left: 'früh', right: 'spät' },
    ],
    explanation: l('groß–klein, teuer–billig, hell–dunkel, früh–spät.', 'groß–klein, teuer–billig, hell–dunkel, früh–spät.', 'Gegenteile.'),
  },
  {
    id: 'v-schmerzen',
    type: 'multiple_choice',
    topic: 'vocabulary',
    concept: 'schmerzen',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Mein Kopf tut weh. Ich habe ___.',
    options: ['Kopfschmerzen', 'Bauchschmerzen', 'Hunger'],
    answer: 0,
    explanation: l('Kopf + Schmerzen = Kopfschmerzen.', 'Kopf + Schmerzen = Kopfschmerzen.', 'Kopfschmerzen.'),
  },

  // --- Reading ---------------------------------------------------------
  {
    id: 'r-woher',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-elif',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Woher kommt Elif?',
    options: ['Aus der Türkei.', 'Aus Österreich.', 'Aus Berlin.'],
    answer: 0,
    explanation: l('„Ich komme aus der Türkei, aus Izmir.“', '„Ich komme aus der Türkei, aus Izmir.“', '„aus der Türkei“'),
  },
  {
    id: 'r-arbeit',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-elif',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie kommt Elif zur Arbeit?',
    options: ['mit der Straßenbahn', 'mit dem Auto', 'zu Fuß'],
    answer: 0,
    explanation: l('„Ich fahre mit der Straßenbahn zur Arbeit.“', '„Ich fahre mit der Straßenbahn zur Arbeit.“', '„mit der Straßenbahn“'),
  },
  {
    id: 'r-kinder',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-elif',
    skill: 'reading',
    difficulty: 1,
    statement: 'Elif hat zwei Kinder.',
    answer: false,
    explanation: l('„Wir haben eine Tochter.“ – one child.', '„Wir haben eine Tochter.“ – bir çocuk.', '„eine Tochter“'),
  },
  {
    id: 'r-muss',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-elif',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was muss Elif am Samstag machen?',
    options: ['einkaufen und aufräumen', 'arbeiten', 'zum Arzt gehen'],
    answer: 0,
    explanation: l('„Am Samstag muss ich einkaufen und die Wohnung aufräumen.“', '„Am Samstag muss ich einkaufen und die Wohnung aufräumen.“', '„einkaufen und aufräumen“'),
  },
  {
    id: 'r-gestern',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-elif',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was hat Elif gestern gemacht?',
    options: ['Sie hat einen Kuchen gebacken.', 'Sie hat Fußball gespielt.', 'Sie hat lange geschlafen.'],
    answer: 0,
    explanation: l('„Gestern habe ich einen Kuchen gebacken.“', '„Gestern habe ich einen Kuchen gebacken.“', '„einen Kuchen gebacken“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'l-vorstellung',
    type: 'listening_choice',
    topic: 'vocabulary',
    concept: 'introduce',
    skill: 'listening',
    difficulty: 1,
    audio: 'Hallo, ich heiße Marco. Ich komme aus Italien und wohne jetzt in München.',
    question: l('Where does Marco live now?', 'Marco şimdi nerede oturuyor?', 'Wo wohnt Marco jetzt?'),
    options: ['In München.', 'In Italien.', 'In Berlin.'],
    answer: 0,
    explanation: l('„… wohne jetzt in München.“', '„… wohne jetzt in München.“', '„in München“'),
  },
  {
    id: 'l-zeit',
    type: 'listening_choice',
    topic: 'vocabulary',
    concept: 'clock-halb',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Kurs beginnt um halb neun.',
    question: l('When does the course start?', 'Kurs ne zaman başlıyor?', 'Wann beginnt der Kurs?'),
    options: ['8:30', '9:30', '9:00'],
    answer: 0,
    explanation: l('halb neun = 8:30.', 'halb neun = 8:30.', 'halb neun = 8:30.'),
  },
  {
    id: 'l-cafe',
    type: 'listening_choice',
    topic: 'cases',
    concept: 'order-akk',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich hätte gern einen Kaffee und ein Stück Kuchen.',
    question: l('What is ordered?', 'Ne sipariş ediliyor?', 'Was wird bestellt?'),
    options: ['☕ + 🍰', '🍵 + 🥐', '🥛 + 🍎'],
    answer: 0,
    explanation: l('Kaffee + Kuchen.', 'Kaffee + Kuchen.', 'Kaffee + Kuchen.'),
  },
  {
    id: 'l-weg',
    type: 'listening_choice',
    topic: 'word-order',
    concept: 'route',
    skill: 'listening',
    difficulty: 2,
    audio: 'Gehen Sie geradeaus und dann die erste Straße rechts.',
    question: l('Which way?', 'Hangi yol?', 'Welcher Weg?'),
    options: ['⬆️ + 1. ➡️', '⬆️ + 1. ⬅️', '➡️ + ⬆️'],
    answer: 0,
    explanation: l('geradeaus, dann die erste rechts.', 'dümdüz, sonra birinci sağ.', 'geradeaus, erste rechts.'),
  },
  {
    id: 'l-gestern',
    type: 'listening_choice',
    topic: 'verbs',
    concept: 'present-or-past',
    skill: 'listening',
    difficulty: 2,
    audio: 'Am Wochenende habe ich meine Eltern besucht.',
    question: l('When did it happen?', 'Ne zaman oldu?', 'Wann war das?'),
    options: ['am Wochenende (Vergangenheit)', 'jetzt', 'morgen'],
    answer: 0,
    explanation: l('habe … besucht = past.', 'habe … besucht = geçmiş.', 'Perfekt = Vergangenheit.'),
  },
]

export const UNIT25_A1_REVIEW: CourseUnit = {
  level: 'A1',
  number: 25,
  slug: 'a1-review',
  titleDe: 'A1 Wiederholung & Abschluss',
  title: l('A1 review & mastery', 'A1 tekrar ve ustalık', 'A1 Wiederholung & Abschluss'),
  goal: l(
    'Show what you can do: a mixed review of the whole A1 course – grammar, vocabulary, reading, listening, writing and speaking – and see your strongest skill and your next focus.',
    'Neler yapabildiğini göster: A1 kursunun tamamının karma tekrarı – dilbilgisi, kelime, okuma, dinleme, yazma ve konuşma – ve en güçlü becerini ve sıradaki odağını gör.',
    'Zeig, was du kannst: gemischte Wiederholung des ganzen A1-Kurses – und dein Stärken-Profil am Ende.'
  ),
  minutes: [25, 35],
  topics: [
    { key: 'articles', label: l('Articles & nouns', 'Artikeller ve isimler', 'Artikel & Nomen') },
    { key: 'verbs', label: l('Verbs & tenses', 'Fiiller ve zamanlar', 'Verben & Zeiten') },
    { key: 'word-order', label: l('Word order & questions', 'Cümle yapısı ve sorular', 'Satzbau & Fragen') },
    { key: 'cases', label: l('Akkusativ & Dativ', 'Akkusativ ve Dativ', 'Akkusativ & Dativ') },
    { key: 'vocabulary', label: l('Vocabulary', 'Kelime', 'Wortschatz') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.8, minAccuracy: 0.75 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('A1 at a glance', 'Bir bakışta A1', 'A1 auf einen Blick'),
      intro: l(
        'Twelve milestones of your A1 course. Tap a card to hear an example sentence.',
        'A1 kursunun on iki kilometre taşı. Örnek cümleyi dinlemek için bir karta dokun.',
        'Zwölf Meilensteine deines A1-Kurses.'
      ),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Cheat sheet', 'Özet tablo', 'Spickzettel'),
      rules: [
        {
          title: l('Articles in three cases', 'Üç halde artikeller', 'Artikel in drei Fällen'),
          body: l(
            'Only masculine changes in the Akkusativ. In the Dativ everything changes. Plural: die / den …n (Dativ, later).',
            'Akkusativ’de yalnızca eril değişir. Dativ’de her şey değişir.',
            'Akkusativ: nur maskulin. Dativ: alles ändert sich.'
          ),
          table: {
            head: [l('', '', ''), l('Nominativ', 'Nominativ', 'Nominativ'), l('Akkusativ', 'Akkusativ', 'Akkusativ'), l('Dativ', 'Dativ', 'Dativ')],
            rows: [
              ['maskulin', 'der / ein', 'den / einen', 'dem / einem'],
              ['feminin', 'die / eine', 'die / eine', 'der / einer'],
              ['neutral', 'das / ein', 'das / ein', 'dem / einem'],
            ],
          },
        },
        {
          title: l('Where does the verb go?', 'Fiil nereye gider?', 'Wo steht das Verb?'),
          body: l(
            'Statement and W-question: verb in position 2. Yes/no question: verb first. With modal verbs and the Perfekt the second verb goes to the end. Separable prefixes go to the end.',
            'Düz cümle ve W-sorusu: fiil 2. sırada. Evet/hayır sorusu: fiil başta. Modal fiil ve Perfekt ile ikinci fiil sona gider. Ayrılabilen ön ekler sona gider.',
            'Position 2 · Ja/Nein: Position 1 · Modalverb/Perfekt/Vorsilbe: Ende.'
          ),
          table: {
            head: [l('1', '1', '1'), l('2', '2', '2'), l('…', '…', '…'), l('end', 'son', 'Ende')],
            rows: [
              ['Heute', 'lerne', 'ich Deutsch.', ''],
              ['Ich', 'kann', 'gut', 'schwimmen.'],
              ['Gestern', 'habe', 'ich Pizza', 'gegessen.'],
              ['Ich', 'stehe', 'um 7 Uhr', 'auf.'],
            ],
          },
        },
        {
          title: l('Verb endings', 'Fiil ekleri', 'Verbendungen'),
          body: l(
            'ich -e · du -st · er/sie/es -t · wir -en · ihr -t · sie/Sie -en. Irregular stars: sein (bin, bist, ist …), haben (habe, hast, hat …), and vowel changers (du fährst, er liest, sie nimmt).',
            'ich -e · du -st · er/sie/es -t · wir -en · ihr -t · sie/Sie -en. Düzensiz yıldızlar: sein (bin, bist, ist …), haben (habe, hast, hat …) ve sesli harf değiştirenler (du fährst, er liest, sie nimmt).',
            '-e, -st, -t, -en, -t, -en.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('Everything together', 'Hepsi bir arada', 'Alles zusammen'),
      scene: l('Two new colleagues get to know each other in the lunch break.', 'İki yeni iş arkadaşı öğle arasında tanışıyor.', 'Zwei neue Kolleginnen lernen sich in der Mittagspause kennen.'),
      dialogue: [
        { speaker: 'Lena', de: 'Hallo! Ich bin Lena. **Woher kommst** du?', translation: l('Hi! I’m Lena. Where are you from?', 'Selam! Ben Lena. Nerelisin?', '') },
        { speaker: 'Elif', de: 'Ich **komme aus** der Türkei. Ich **wohne** seit zwei Jahren hier.', translation: l('I’m from Turkey. I’ve lived here for two years.', 'Türkiye’denim. İki yıldır burada oturuyorum.', '') },
        { speaker: 'Lena', de: 'Und wie **kommst** du zur Arbeit?', translation: l('And how do you get to work?', 'Peki işe nasıl geliyorsun?', '') },
        { speaker: 'Elif', de: 'Ich **fahre mit der Straßenbahn**. Ich **habe kein Auto**.', translation: l('I take the tram. I don’t have a car.', 'Tramvayla geliyorum. Arabam yok.', '') },
        { speaker: 'Lena', de: 'Was **hast** du am Wochenende **gemacht**?', translation: l('What did you do at the weekend?', 'Hafta sonu ne yaptın?', '') },
        { speaker: 'Elif', de: 'Ich **habe** {m:einen Kuchen} **gebacken** und meine Tochter **hat** Freunde **eingeladen**.', translation: l('I baked a cake and my daughter invited friends.', 'Pasta yaptım, kızım da arkadaşlarını davet etti.', '') },
        { speaker: 'Lena', de: 'Toll! **Möchtest** du morgen mit mir Mittag **essen**?', translation: l('Great! Would you like to have lunch with me tomorrow?', 'Harika! Yarın benimle öğle yemeği yemek ister misin?', '') },
        { speaker: 'Elif', de: 'Sehr gern! Morgen **kann** ich um zwölf.', translation: l('I’d love to! Tomorrow I can at twelve.', 'Çok isterim! Yarın on ikide olur.', '') },
      ],
      examples: [
        { de: '{m:Der Tisch} ist neu. Ich kaufe {m:einen Tisch}. Ich sitze an {m:dem Tisch}.', translation: l('Nominativ – Akkusativ – Dativ', 'Nominativ – Akkusativ – Dativ', '') },
        { de: 'Heute **lerne** ich Deutsch.', translation: l('Today I’m learning German.', 'Bugün Almanca öğreniyorum.', '') },
        { de: '**Kannst** du mir **helfen**?', translation: l('Can you help me?', 'Bana yardım edebilir misin?', '') },
        { de: 'Ich **stehe** um sieben Uhr **auf**.', translation: l('I get up at seven.', 'Yedide kalkıyorum.', '') },
        { de: 'Gestern **habe** ich viel **gearbeitet**.', translation: l('Yesterday I worked a lot.', 'Dün çok çalıştım.', '') },
        { de: 'Ich fahre **mit dem Bus zur** Arbeit.', translation: l('I go to work by bus.', 'İşe otobüsle gidiyorum.', '') },
        { de: 'Ich hätte gern {f:eine Tasse} Tee, bitte.', translation: l('I’d like a cup of tea, please.', 'Bir fincan çay rica ediyorum.', '') },
      ],
    },
    {
      key: 'practice-grammar',
      kind: 'practice',
      title: l('Review · Grammar', 'Tekrar · Dilbilgisi', 'Wiederholung · Grammatik'),
      intro: l(
        'Mixed questions from all units – no topic labels. Recognise the structure yourself.',
        'Tüm ünitelerden karışık sorular – konu etiketi yok. Yapıyı kendin tanı.',
        'Gemischte Fragen aus allen Einheiten – ohne Themenangabe.'
      ),
      exercises: [
        'g-artikel',
        'g-akk',
        'g-wohnen',
        'g-sprichst',
        'g-satz',
        'g-dativ',
        'g-modal',
        'g-perfekt',
        'g-trennbar',
        'g-faelle',
        'g-wie-viele',
        'g-woher',
        'g-kein',
        'g-helfen',
        'g-plural',
        'g-eltern',
        'g-meine',
        'g-sein',
      ],
    },
    {
      key: 'practice-vocabulary',
      kind: 'practice',
      title: l('Review · Vocabulary', 'Tekrar · Kelime', 'Wiederholung · Wortschatz'),
      intro: l('Words from the whole course.', 'Tüm kurstan kelimeler.', 'Wörter aus dem ganzen Kurs.'),
      exercises: ['v-bild', 'v-match', 'v-getraenke', 'v-genus', 'v-uhr', 'v-monat', 'v-gegenteil', 'v-schmerzen'],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Review · Reading', 'Tekrar · Okuma', 'Wiederholung · Lesen'),
      intro: l('A longer A1 text – take your time.', 'Daha uzun bir A1 metni – acele etme.', 'Ein längerer A1-Text – lass dir Zeit.'),
      passage: [
        'Hallo! Ich heiße Elif und bin 34 Jahre alt. Ich **komme aus** der Türkei, aus Izmir.',
        'Seit zwei Jahren **wohne** ich mit meinem Mann und unserer Tochter in Wien. Wir **haben** {f:eine Wohnung} mit drei Zimmern.',
        'Ich bin Krankenpflegerin. Ich **fahre mit der Straßenbahn** zur Arbeit. Mein Mann **fährt** mit dem Fahrrad.',
        'Am Samstag **muss** ich einkaufen und die Wohnung **aufräumen**. Am Sonntag **gehen** wir oft in den Park.',
        'Gestern **habe** ich {m:einen Kuchen} **gebacken** – meine Tochter **hatte** Geburtstag!',
      ],
      glossary: [
        { de: 'Krankenpflegerin', note: l('nurse (woman)', 'hemşire (kadın)', 'Pflegerin im Krankenhaus') },
        { de: 'mit drei Zimmern', note: l('with three rooms (Dativ plural)', 'üç odalı (Dativ çoğul)', 'Dativ Plural') },
        { de: 'gebacken (backen)', note: l('baked', 'pişirdi (fırında)', 'backen → gebacken') },
        { de: 'hatte', note: l('had (haben, past)', 'vardı (haben, geçmiş)', 'Präteritum von haben') },
      ],
      exercises: ['r-woher', 'r-arbeit', 'r-kinder', 'r-muss', 'r-gestern'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Review · Listening', 'Tekrar · Dinleme', 'Wiederholung · Hören'),
      intro: l('Five short recordings from everyday life.', 'Günlük hayattan beş kısa kayıt.', 'Fünf kurze Aufnahmen aus dem Alltag.'),
      exercises: ['l-vorstellung', 'l-zeit', 'l-cafe', 'l-weg', 'l-gestern'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Review · Speaking', 'Tekrar · Konuşma', 'Wiederholung · Sprechen'),
      prompt: l(
        'Final speaking task: introduce yourself completely – about one minute.',
        'Son konuşma görevi: kendini eksiksiz tanıt – yaklaşık bir dakika.',
        'Abschluss: Stell dich ausführlich vor – etwa eine Minute.'
      ),
      points: [
        l('Name, age, origin, city', 'Ad, yaş, köken, şehir', 'Name, Alter, Herkunft, Wohnort'),
        l('Family and job', 'Aile ve meslek', 'Familie und Beruf'),
        l('Your day and how you travel', 'Günün ve nasıl ulaşım sağladığın', 'Dein Tag und wie du fährst'),
        l('Hobbies (gern) and something from last weekend (Perfekt)', 'Hobiler (gern) ve geçen hafta sonundan bir şey (Perfekt)', 'Hobbys und das letzte Wochenende'),
        l('A wish: „Ich möchte …“', 'Bir istek: „Ich möchte …“', 'Ein Wunsch: „Ich möchte …“'),
      ],
      model: [
        'Hallo! Ich heiße Emre und bin 29 Jahre alt.',
        'Ich komme aus der Türkei und wohne jetzt in Hamburg.',
        'Ich bin verheiratet und habe einen Sohn.',
        'Ich bin Programmierer. Ich fahre mit der U-Bahn zur Arbeit.',
        'In meiner Freizeit spiele ich gern Fußball.',
        'Am Wochenende habe ich meine Eltern besucht.',
        'Ich möchte bald B1 lernen!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Review · Writing', 'Tekrar · Yazma', 'Wiederholung · Schreiben'),
      prompt: l(
        'Final writing task: write a self-introduction of at least 6 sentences for a new German course.',
        'Son yazma görevi: yeni bir Almanca kursu için en az 6 cümlelik bir tanıtım yazısı yaz.',
        'Abschluss: Schreib eine Vorstellung (mindestens 6 Sätze) für einen neuen Deutschkurs.'
      ),
      minSentences: 6,
      checks: [
        { label: l('Name / origin (Ich heiße …, Ich komme aus …)', 'Ad / köken (Ich heiße …, Ich komme aus …)', 'Name / Herkunft'), pattern: '([Ii]ch heiße|[Ii]ch komme aus|[Mm]ein Name ist)' },
        { label: l('haben + Akkusativ (einen / eine / ein …)', 'haben + Akkusativ (einen / eine / ein …)', 'haben + Akkusativ'), pattern: '\\b(habe|hat|haben)\\b[^.!?]*\\b(einen|eine|ein|keinen|keine|kein)\\b' },
        { label: l('Something you like (… gern)', 'Sevdiğin bir şey (… gern)', 'Etwas mit gern'), pattern: '\\bgerne?\\b' },
        { label: l('A sentence in the past (habe … ge…t / ge…en)', 'Geçmiş zamanda bir cümle (habe … ge…t / ge…en)', 'Ein Satz im Perfekt'), pattern: '\\b(habe|hat|haben)\\b[^.!?]*\\b\\p{Ll}*ge\\p{Ll}+(t|en)[.!?]' },
      ],
      model: [
        'Hallo, ich heiße Emre.',
        'Ich komme aus der Türkei und wohne jetzt in Hamburg.',
        'Ich bin verheiratet und habe einen Sohn.',
        'Ich arbeite als Programmierer und fahre mit der U-Bahn zur Arbeit.',
        'In meiner Freizeit spiele ich gern Fußball.',
        'Letzte Woche habe ich mit meinen Eltern Kuchen gegessen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Final speed round', 'Son hız turu', 'Finale Schnellrunde'),
      intro: l('A1 mixed – how many in 60 seconds?', 'Karma A1 – 60 saniyede kaç tane?', 'A1 gemischt – wie viele in 60 Sekunden?'),
      seconds: 60,
      pool: ['g-artikel', 'g-akk', 'g-sprichst', 'g-dativ', 'g-perfekt', 'g-woher', 'g-plural', 'g-meine', 'g-sein', 'v-uhr', 'v-monat', 'v-schmerzen'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Your weak areas', 'Zayıf alanların', 'Deine Schwachstellen'),
      intro: l(
        'All your mistakes in the final review – practise them now. Your mistake bank keeps bringing them back.',
        'Son tekrardaki tüm hataların – şimdi çalış. Hata bankan onları geri getirmeye devam edecek.',
        'Alle Fehler der Abschlusswiederholung – übe sie jetzt.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('A1 mastered?', 'A1’de ustalaştın mı?', 'A1 geschafft?') },
  ],
  summary: {
    learned: [
      l('Introduce yourself, your family and your job', 'Kendini, aileni ve mesleğini tanıtmak', 'Sich, Familie und Beruf vorstellen'),
      l('Articles and the three cases Nominativ, Akkusativ, Dativ', 'Artikeller ve üç hal: Nominativ, Akkusativ, Dativ', 'Artikel und drei Fälle'),
      l('Verb position, questions, modal verbs, separable verbs, Perfekt', 'Fiil yeri, sorular, modal fiiller, ayrılabilen fiiller, Perfekt', 'Satzbau, Fragen, Modalverben, trennbare Verben, Perfekt'),
      l('Everyday situations: café, shopping, directions, doctor, flat', 'Günlük durumlar: kafe, alışveriş, yol tarifi, doktor, ev', 'Alltag: Café, Einkaufen, Weg, Arzt, Wohnung'),
      l('Numbers, time, dates and prices', 'Sayılar, saat, tarih ve fiyatlar', 'Zahlen, Uhrzeit, Datum, Preise'),
    ],
    mistakes: [
      { wrong: 'Ich habe ein Hund.', right: 'Ich habe einen Hund.', note: l('Akkusativ: der → einen.', 'Akkusativ: der → einen.', 'Akkusativ.') },
      { wrong: 'Heute ich lerne Deutsch.', right: 'Heute lerne ich Deutsch.', note: l('Verb in position 2.', 'Fiil 2. sırada.', 'Verb Position 2.') },
      { wrong: 'Ich fahre mit der Bus.', right: 'Ich fahre mit dem Bus.', note: l('Dativ: der → dem.', 'Dativ: der → dem.', 'Dativ.') },
      { wrong: 'Ich habe gegessen eine Pizza.', right: 'Ich habe eine Pizza gegessen.', note: l('Participle at the end.', 'Ortaç sonda.', 'Partizip am Ende.') },
    ],
  },
}
