import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Kopf', gender: 'm', plural: 'die Köpfe', emoji: '🤕', translation: l('head', 'baş', 'Kopf'), example: 'Mein Kopf tut weh.' },
  { word: 'Auge', gender: 'n', plural: 'die Augen', emoji: '👁️', translation: l('eye', 'göz', 'Auge'), example: 'Meine Augen sind müde.' },
  { word: 'Ohr', gender: 'n', plural: 'die Ohren', emoji: '👂', translation: l('ear', 'kulak', 'Ohr'), example: 'Ich habe Ohrenschmerzen.' },
  { word: 'Nase', gender: 'f', plural: 'die Nasen', emoji: '👃', translation: l('nose', 'burun', 'Nase'), example: 'Meine Nase läuft.' },
  { word: 'Mund', gender: 'm', plural: 'die Münder', emoji: '👄', translation: l('mouth', 'ağız', 'Mund'), example: 'Öffnen Sie bitte den Mund.' },
  { word: 'Zahn', gender: 'm', plural: 'die Zähne', emoji: '🦷', translation: l('tooth', 'diş', 'Zahn'), example: 'Ich habe Zahnschmerzen.' },
  { word: 'Hand', gender: 'f', plural: 'die Hände', emoji: '✋', translation: l('hand', 'el', 'Hand'), example: 'Meine Hand tut weh.' },
  { word: 'Arm', gender: 'm', plural: 'die Arme', emoji: '💪', translation: l('arm', 'kol', 'Arm'), example: 'Mein Arm tut weh.' },
  { word: 'Bein', gender: 'n', plural: 'die Beine', emoji: '🦵', translation: l('leg', 'bacak', 'Bein'), example: 'Mein Bein tut weh.' },
  { word: 'Fuß', gender: 'm', plural: 'die Füße', emoji: '🦶', translation: l('foot', 'ayak', 'Fuß'), example: 'Meine Füße tun weh.' },
  { word: 'Tablette', gender: 'f', plural: 'die Tabletten', emoji: '💊', translation: l('tablet, pill', 'hap, tablet', 'Tablette'), example: 'Nehmen Sie eine Tablette.' },
  { word: 'Fieber', gender: 'n', emoji: '🤒', translation: l('fever', 'ateş', 'Fieber'), example: 'Das Kind hat Fieber.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Bauch', gender: 'm', plural: 'die Bäuche', translation: l('stomach, belly', 'karın', 'Bauch') },
  { word: 'Hals', gender: 'm', plural: 'die Hälse', translation: l('throat, neck', 'boğaz, boyun', 'Hals') },
  { word: 'Rücken', gender: 'm', plural: 'die Rücken', translation: l('back', 'sırt', 'Rücken') },
  { word: 'Arzt / Ärztin', gender: 'm', translation: l('doctor', 'doktor', 'Arzt / Ärztin') },
  { word: 'Termin', gender: 'm', plural: 'die Termine', translation: l('appointment', 'randevu', 'Termin') },
  { word: 'Praxis', gender: 'f', plural: 'die Praxen', translation: l('(doctor’s) practice', 'muayenehane', 'Praxis') },
  { word: 'Apotheke', gender: 'f', plural: 'die Apotheken', translation: l('pharmacy', 'eczane', 'Apotheke') },
  { word: 'Krankenversicherungskarte', gender: 'f', translation: l('health insurance card', 'sağlık sigortası kartı', 'Versichertenkarte') },
  { word: 'krank / gesund', translation: l('ill / healthy', 'hasta / sağlıklı', 'krank / gesund') },
  { word: 'Gute Besserung!', translation: l('Get well soon!', 'Geçmiş olsun!', 'Gute Besserung!') },
  { word: 'Was fehlt Ihnen?', translation: l('What’s the matter?', 'Neyiniz var?', 'Was fehlt Ihnen?') },
  { word: 'wehtun – es tut weh', translation: l('to hurt – it hurts', 'ağrımak – ağrıyor', 'wehtun') },
]

/** Mein Kopf tut weh = Ich habe Kopfschmerzen. */
const PAINS: [string, string, [string, string]][] = [
  ['Mein Kopf tut weh.', 'Kopfschmerzen', ['Bauchschmerzen', 'Zahnschmerzen']],
  ['Mein Bauch tut weh.', 'Bauchschmerzen', ['Kopfschmerzen', 'Halsschmerzen']],
  ['Mein Hals tut weh.', 'Halsschmerzen', ['Ohrenschmerzen', 'Rückenschmerzen']],
  ['Mein Zahn tut weh.', 'Zahnschmerzen', ['Kopfschmerzen', 'Bauchschmerzen']],
  ['Mein Rücken tut weh.', 'Rückenschmerzen', ['Halsschmerzen', 'Zahnschmerzen']],
  ['Meine Ohren tun weh.', 'Ohrenschmerzen', ['Rückenschmerzen', 'Kopfschmerzen']],
]

function painDrills(): Exercise[] {
  return PAINS.map(([sentence, pain, wrong], i) => {
    const options = [pain, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `schmerz-${i + 1}`,
      type: 'multiple_choice' as const,
      topic: 'pain',
      concept: 'schmerzen',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `${sentence} = Ich habe ___.`,
      options: ordered,
      answer: ordered.indexOf(pain),
      explanation: l(
        `Body part + Schmerzen = one word: ${pain}.`,
        `Vücut bölümü + Schmerzen = tek kelime: ${pain}.`,
        `Körperteil + Schmerzen: ${pain}.`
      ),
      examples: [`Ich habe **${pain}**.`],
    }
  })
}

/** tut weh (singular) or tun weh (plural)? */
const HURTS: [string, boolean][] = [
  ['Mein Bein', false],
  ['Meine Füße', true],
  ['Meine Hand', false],
  ['Meine Augen', true],
  ['Mein Arm', false],
  ['Meine Zähne', true],
]

function hurtDrills(): Exercise[] {
  return HURTS.map(([subject, plural], i) => {
    const options = i % 2 === 0 ? ['tut', 'tun'] : ['tun', 'tut']
    const right = plural ? 'tun' : 'tut'
    return {
      id: `weh-${i + 1}`,
      type: 'multiple_choice' as const,
      topic: 'pain',
      concept: 'wehtun',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: `${subject} ___ weh.`,
      options,
      answer: options.indexOf(right),
      explanation: l(
        `${plural ? 'Plural → tun weh' : 'Singular → tut weh'}: ${subject} ${right} weh.`,
        `${plural ? 'Çoğul → tun weh' : 'Tekil → tut weh'}: ${subject} ${right} weh.`,
        `${plural ? 'Plural → tun weh' : 'Singular → tut weh'}.`
      ),
      examples: [`${subject} **${right} weh**.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise ---------------------------------------
  {
    id: 'img-zahn',
    type: 'image_choice',
    topic: 'body',
    concept: 'body-parts',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'der Zahn',
    options: [
      { emoji: '👂', label: 'das Ohr' },
      { emoji: '🦷', label: 'der Zahn' },
      { emoji: '👃', label: 'die Nase' },
      { emoji: '👁️', label: 'das Auge' },
    ],
    answer: 1,
    explanation: l('der Zahn = tooth (plural: die Zähne).', 'der Zahn = diş (çoğul: die Zähne).', 'der Zahn, die Zähne.'),
    examples: ['**Der Zahn** tut weh.'],
  },
  {
    id: 'match-body',
    type: 'matching',
    topic: 'body',
    concept: 'body-parts',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match body parts and pictures.', 'Vücut bölümlerini ve resimleri eşleştir.', 'Ordne Körperteile und Bilder zu.'),
    pairs: [
      { left: 'die Hand', right: '✋' },
      { left: 'das Bein', right: '🦵' },
      { left: 'der Fuß', right: '🦶' },
      { left: 'das Auge', right: '👁️' },
      { left: 'der Mund', right: '👄' },
    ],
    explanation: l('die Hand, das Bein, der Fuß, das Auge, der Mund.', 'die Hand, das Bein, der Fuß, das Auge, der Mund.', 'Körperteile mit Artikel.'),
  },
  {
    id: 'mc-kopfschmerzen',
    type: 'multiple_choice',
    topic: 'pain',
    concept: 'schmerzen',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich habe ___. Mein Kopf tut weh.',
    options: ['Kopfschmerzen', 'Kopf Schmerzen', 'Kopfschmerz haben'],
    answer: 0,
    explanation: l(
      'One word, plural: Kopfschmerzen. (Ich habe Kopfschmerzen = I have a headache.)',
      'Tek kelime, çoğul: Kopfschmerzen. (Ich habe Kopfschmerzen = Başım ağrıyor.)',
      'Ein Wort: Kopfschmerzen.'
    ),
    examples: ['Ich habe **Kopfschmerzen**.'],
    practice: ['schmerz-2', 'schmerz-4'],
  },
  {
    id: 'mc-tut-weh',
    type: 'multiple_choice',
    topic: 'pain',
    concept: 'wehtun',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Meine Füße ___ weh.',
    options: ['tun', 'tut'],
    answer: 0,
    explanation: l('die Füße (plural) → tun weh. Mein Fuß (singular) → tut weh.', 'die Füße (çoğul) → tun weh. Mein Fuß (tekil) → tut weh.', 'Plural → tun weh.'),
    examples: ['Meine Füße **tun weh**.', 'Mein Fuß **tut weh**.'],
    practice: ['weh-1', 'weh-3'],
  },
  {
    id: 'sort-singular-plural',
    type: 'categorize',
    topic: 'body',
    concept: 'body-plural',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('One or two? Sort the body parts.', 'Bir mi iki mi? Vücut bölümlerini ayır.', 'Eins oder zwei? Sortiere.'),
    categories: ['Singular', 'Plural'],
    items: [
      { text: 'der Kopf', category: 0 },
      { text: 'die Augen', category: 1 },
      { text: 'die Nase', category: 0 },
      { text: 'die Hände', category: 1 },
      { text: 'der Mund', category: 0 },
      { text: 'die Füße', category: 1 },
    ],
    explanation: l(
      'Plural forms: Augen, Hände (ä!), Füße (ü!). Singular: Kopf, Nase, Mund.',
      'Çoğul biçimler: Augen, Hände (ä!), Füße (ü!). Tekil: Kopf, Nase, Mund.',
      'Plural: Augen, Hände, Füße.'
    ),
  },
  {
    id: 'tf-besserung',
    type: 'true_false',
    topic: 'doctor',
    concept: 'phrases',
    skill: 'vocabulary',
    difficulty: 1,
    statement: 'Zu einer kranken Person sagt man: „Gute Besserung!“',
    answer: true,
    explanation: l('Gute Besserung! = Get well soon!', 'Gute Besserung! = Geçmiş olsun!', 'Gute Besserung!'),
  },
  {
    id: 'select-symptoms',
    type: 'multiple_select',
    topic: 'doctor',
    concept: 'symptoms',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which sentences describe a cold? Select all.', 'Hangi cümleler soğuk algınlığını anlatıyor? Hepsini seç.', 'Welche Sätze passen zu einer Erkältung?'),
    options: ['Ich habe Halsschmerzen.', 'Mein Fuß tut weh.', 'Meine Nase läuft.', 'Ich habe Zahnschmerzen.', 'Ich habe Fieber.'],
    answers: [0, 2, 4],
    explanation: l('A cold (Erkältung): sore throat, runny nose, fever.', 'Soğuk algınlığı (Erkältung): boğaz ağrısı, burun akıntısı, ateş.', 'Erkältung: Hals, Nase, Fieber.'),
  },
  {
    id: 'match-doctor',
    type: 'matching',
    topic: 'doctor',
    concept: 'phrases',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Doctor’s question – patient’s answer.', 'Doktorun sorusu – hastanın cevabı.', 'Frage der Ärztin – Antwort.'),
    pairs: [
      { left: 'Was fehlt Ihnen?', right: 'Ich habe Bauchschmerzen.' },
      { left: 'Seit wann?', right: 'Seit zwei Tagen.' },
      { left: 'Haben Sie Fieber?', right: 'Ja, 38,5 Grad.' },
      { left: 'Nehmen Sie Medikamente?', right: 'Nein, nichts.' },
    ],
    explanation: l(
      'Was fehlt Ihnen? = What’s wrong? · Seit wann? = Since when?',
      'Was fehlt Ihnen? = Neyiniz var? · Seit wann? = Ne zamandan beri?',
      'Was fehlt Ihnen? · Seit wann?'
    ),
  },

  // --- Simulation: appointment, doctor, pharmacy ----------------------
  {
    id: 'sim-1-termin',
    type: 'dialogue',
    topic: 'doctor',
    concept: 'appointment',
    skill: 'grammar',
    difficulty: 1,
    visual: ['📞 🩺 📆'],
    lines: [{ speaker: 'Praxis', de: 'Praxis Dr. Berg, guten Morgen!' }],
    options: ['Guten Morgen, ich brauche einen Termin, bitte.', 'Guten Morgen, ich bin einen Termin.', 'Gute Besserung!'],
    answer: 0,
    explanation: l('brauchen + Akkusativ: der Termin → einen Termin.', 'brauchen + Akkusativ: der Termin → einen Termin.', 'einen Termin.'),
    examples: ['Ich brauche {m:einen Termin}.'],
  },
  {
    id: 'sim-2-wann',
    type: 'dialogue',
    topic: 'doctor',
    concept: 'appointment',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Praxis', de: 'Können Sie heute um 15 Uhr kommen?' }],
    options: ['Ja, das passt gut.', 'Ja, ich kann kommen um 15 Uhr nicht.', 'Nein, ich habe Kopf.'],
    answer: 0,
    explanation: l('„Das passt gut“ = that suits me.', '„Das passt gut“ = bana uyar.', '„Das passt gut.“'),
  },
  {
    id: 'sim-3-fehlt',
    type: 'dialogue',
    topic: 'pain',
    concept: 'schmerzen',
    skill: 'grammar',
    difficulty: 1,
    visual: ['🩺 👩‍⚕️ 🤒'],
    lines: [{ speaker: 'Ärztin', de: 'Was fehlt Ihnen?' }],
    options: ['Ich habe Halsschmerzen und Fieber.', 'Ich bin Halsschmerzen.', 'Mein Hals hat weh.'],
    answer: 0,
    explanation: l('Ich habe + …schmerzen / Fieber.', 'Ich habe + …schmerzen / Fieber.', 'Ich habe Halsschmerzen.'),
    examples: ['Ich **habe** Halsschmerzen und Fieber.'],
  },
  {
    id: 'sim-4-seit',
    type: 'dialogue',
    topic: 'doctor',
    concept: 'phrases',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Ärztin', de: 'Seit wann haben Sie das?' }],
    options: ['Seit drei Tagen.', 'Um drei Uhr.', 'Drei Tabletten.'],
    answer: 0,
    explanation: l('Seit wann? → seit + time: seit drei Tagen (for three days).', 'Seit wann? → seit + zaman: seit drei Tagen (üç gündür).', 'Seit wann? → seit drei Tagen.'),
  },
  {
    id: 'sim-5-rat',
    type: 'dialogue',
    topic: 'doctor',
    concept: 'advice',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Ärztin', de: 'Sie haben eine Erkältung. Sie müssen viel trinken und im Bett bleiben.' }],
    options: ['Brauche ich Tabletten?', 'Ich muss tanzen.', 'Gute Besserung!'],
    answer: 0,
    explanation: l(
      'A good question to the doctor: Brauche ich Tabletten? („Gute Besserung“ is what the doctor says to you.)',
      'Doktora iyi bir soru: Brauche ich Tabletten? („Gute Besserung“ doktorun sana söylediğidir.)',
      'Brauche ich Tabletten?'
    ),
  },
  {
    id: 'sim-6-apotheke',
    type: 'dialogue',
    topic: 'doctor',
    concept: 'pharmacy',
    skill: 'grammar',
    difficulty: 1,
    visual: ['💊 🏥 🙋'],
    lines: [{ speaker: 'Apothekerin', de: 'Guten Tag! Was kann ich für Sie tun?' }],
    options: ['Ich brauche etwas gegen Halsschmerzen.', 'Ich bin etwas gegen Halsschmerzen.', 'Ich habe etwas gegen Apotheke.'],
    answer: 0,
    explanation: l('„etwas gegen …“ = something for (against) …', '„etwas gegen …“ = … için bir şey', '„etwas gegen Halsschmerzen“'),
    examples: ['Ich brauche **etwas gegen** Halsschmerzen.'],
  },
  {
    id: 'sim-7-wie-oft',
    type: 'dialogue',
    topic: 'doctor',
    concept: 'pharmacy',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Apothekerin', de: 'Nehmen Sie dreimal täglich eine Tablette. Gute Besserung!' }],
    options: ['Danke schön! Auf Wiedersehen.', 'Bitte, gute Besserung!', 'Ich nehme dreimal Tablette täglich.'],
    answer: 0,
    explanation: l(
      'dreimal täglich = three times a day. Answer politely: Danke schön!',
      'dreimal täglich = günde üç kez. Kibarca cevap ver: Danke schön!',
      'dreimal täglich. Danke schön!'
    ),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-zahnschmerzen',
    type: 'fill_blank',
    topic: 'pain',
    concept: 'schmerzen',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Mein Zahn tut weh. Ich habe ___.',
    accepted: ['Zahnschmerzen'],
    explanation: l('Zahn + Schmerzen = Zahnschmerzen.', 'Zahn + Schmerzen = Zahnschmerzen.', 'Zahnschmerzen.'),
    examples: ['Ich habe **Zahnschmerzen**.'],
  },
  {
    id: 'fill-tut',
    type: 'fill_blank',
    topic: 'pain',
    concept: 'wehtun',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Mein Rücken ___ weh.',
    accepted: ['tut'],
    explanation: l('Singular → tut weh.', 'Tekil → tut weh.', 'Singular → tut weh.'),
    examples: ['Mein Rücken **tut weh**.'],
  },
  {
    id: 'fill-muessen',
    type: 'fill_blank',
    topic: 'doctor',
    concept: 'advice',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie ___ zwei Tage im Bett bleiben.',
    accepted: ['müssen'],
    base: 'müssen',
    explanation: l('Advice/obligation: Sie müssen … bleiben (Unit 14).', 'Tavsiye/zorunluluk: Sie müssen … bleiben (Ünite 14).', 'Sie müssen … bleiben.'),
    examples: ['Sie **müssen** im Bett **bleiben**.'],
  },
  {
    id: 'build-termin',
    type: 'sentence_builder',
    topic: 'doctor',
    concept: 'appointment',
    skill: 'grammar',
    difficulty: 1,
    chips: ['einen Termin', 'brauche', 'Ich'],
    answers: [['Ich', 'brauche', 'einen Termin']],
    translation: l('I need an appointment.', 'Randevuya ihtiyacım var.', 'Ich brauche einen Termin.'),
    explanation: l('der Termin → einen Termin.', 'der Termin → einen Termin.', 'einen Termin.'),
    examples: ['Ich brauche {m:einen Termin}.'],
  },
  {
    id: 'build-krank',
    type: 'sentence_builder',
    topic: 'doctor',
    concept: 'phrases',
    skill: 'grammar',
    difficulty: 1,
    chips: ['krank', 'heute', 'bin', 'Ich'],
    answers: [['Ich', 'bin', 'heute', 'krank']],
    translation: l('I’m ill today.', 'Bugün hastayım.', 'Ich bin heute krank.'),
    explanation: l('krank (adjective) → sein: Ich bin krank.', 'krank (sıfat) → sein: Ich bin krank.', 'Ich bin krank.'),
    examples: ['Ich **bin** heute krank.'],
  },
  {
    id: 'fix-bin-kopf',
    type: 'error_correction',
    topic: 'pain',
    concept: 'schmerzen',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich bin Kopfschmerzen.',
    accepted: ['Ich habe Kopfschmerzen.'],
    explanation: l('Kopfschmerzen (noun) → haben.', 'Kopfschmerzen (isim) → haben.', 'Kopfschmerzen → haben.'),
    examples: ['Ich **habe** Kopfschmerzen.'],
  },
  {
    id: 'fix-tut-plural',
    type: 'error_correction',
    topic: 'pain',
    concept: 'wehtun',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Meine Augen tut weh.',
    accepted: ['Meine Augen tun weh.'],
    explanation: l('die Augen (plural) → tun weh.', 'die Augen (çoğul) → tun weh.', 'Plural → tun weh.'),
    examples: ['Meine Augen **tun weh**.'],
  },
  {
    id: 'tr-fieber',
    type: 'translation',
    topic: 'doctor',
    concept: 'symptoms',
    skill: 'writing',
    difficulty: 1,
    source: l('My son has a fever.', 'Oğlumun ateşi var.', 'My son has a fever.'),
    accepted: ['Mein Sohn hat Fieber.'],
    explanation: l('Fieber haben (no article).', 'Fieber haben (artikelsiz).', 'Fieber haben.'),
    examples: ['Mein Sohn **hat Fieber**.'],
  },
  {
    id: 'tr-arzt',
    type: 'translation',
    topic: 'doctor',
    concept: 'appointment',
    skill: 'writing',
    difficulty: 2,
    source: l('I need a doctor.', 'Bir doktora ihtiyacım var.', 'I need a doctor.'),
    accepted: ['Ich brauche einen Arzt.', 'Ich brauche eine Ärztin.'],
    explanation: l('der Arzt → einen Arzt (Akkusativ).', 'der Arzt → einen Arzt (Akkusativ).', 'einen Arzt.'),
    examples: ['Ich brauche {m:einen Arzt}.'],
  },

  // --- Reading -----------------------------------------------------
  {
    id: 'read-krank',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-email',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Warum kommt Herr Novak nicht zur Arbeit?',
    options: ['Er ist krank.', 'Er hat Urlaub.', 'Sein Kind ist krank.'],
    answer: 0,
    explanation: l('„Ich bin leider krank.“', '„Ich bin leider krank.“', '„Ich bin leider krank.“'),
  },
  {
    id: 'read-symptome',
    type: 'multiple_select',
    topic: 'reading',
    concept: 'reading-email',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('What symptoms does he have? Select all.', 'Hangi belirtileri var? Hepsini seç.', 'Welche Symptome hat er? Wähle alle.'),
    options: ['Fieber', 'Zahnschmerzen', 'Kopfschmerzen', 'Rückenschmerzen', 'Halsschmerzen'],
    answers: [0, 2, 4],
    explanation: l('„Ich habe Fieber, Kopfschmerzen und Halsschmerzen.“', '„Ich habe Fieber, Kopfschmerzen und Halsschmerzen.“', '„Fieber, Kopfschmerzen und Halsschmerzen“'),
  },
  {
    id: 'read-arzt',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-email',
    skill: 'reading',
    difficulty: 1,
    statement: 'Herr Novak geht heute zum Arzt.',
    answer: true,
    explanation: l('„Heute um 11 Uhr gehe ich zum Arzt.“', '„Heute um 11 Uhr gehe ich zum Arzt.“', '„Heute … zum Arzt.“'),
  },
  {
    id: 'read-wann',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-email',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wann kommt er vielleicht wieder?',
    options: ['am Donnerstag', 'morgen', 'nächste Woche'],
    answer: 0,
    explanation: l('„Ich komme hoffentlich am Donnerstag wieder.“', '„Ich komme hoffentlich am Donnerstag wieder.“', '„am Donnerstag“'),
  },

  // --- Listening ------------------------------------------------------
  {
    id: 'listen-bauch',
    type: 'listening_choice',
    topic: 'pain',
    concept: 'schmerzen',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich habe seit gestern Bauchschmerzen.',
    question: l('What hurts?', 'Neresi ağrıyor?', 'Was tut weh?'),
    options: ['der Bauch', 'der Kopf', 'der Hals'],
    answer: 0,
    explanation: l('Bauchschmerzen = stomach ache.', 'Bauchschmerzen = karın ağrısı.', 'Bauchschmerzen.'),
  },
  {
    id: 'listen-termin',
    type: 'listening_choice',
    topic: 'doctor',
    concept: 'appointment',
    skill: 'listening',
    difficulty: 2,
    audio: 'Sie haben einen Termin am Mittwoch um halb zehn.',
    question: l('When is the appointment?', 'Randevu ne zaman?', 'Wann ist der Termin?'),
    options: ['Mi 9:30', 'Mi 10:30', 'Mo 9:30'],
    answer: 0,
    explanation: l('Mittwoch, halb zehn = 9:30.', 'Mittwoch, halb zehn = 9:30.', 'Mittwoch, 9:30.'),
  },
  {
    id: 'listen-tabletten',
    type: 'listening_choice',
    topic: 'doctor',
    concept: 'pharmacy',
    skill: 'listening',
    difficulty: 2,
    audio: 'Nehmen Sie zweimal täglich eine Tablette.',
    question: l('How often?', 'Ne sıklıkla?', 'Wie oft?'),
    options: ['2× täglich', '3× täglich', '1× täglich'],
    answer: 0,
    explanation: l('zweimal täglich = twice a day.', 'zweimal täglich = günde iki kez.', 'zweimal täglich.'),
  },
  {
    id: 'listen-besserung',
    type: 'listening_choice',
    topic: 'doctor',
    concept: 'phrases',
    skill: 'listening',
    difficulty: 1,
    audio: 'Du bist krank? Oh nein! Gute Besserung!',
    question: l('What does the person wish?', 'Kişi ne diliyor?', 'Was wünscht die Person?'),
    options: ['Get well soon', 'Happy birthday', 'Good night'],
    answer: 0,
    explanation: l('Gute Besserung = get well soon.', 'Gute Besserung = geçmiş olsun.', 'Gute Besserung.'),
  },

  ...painDrills(),
  ...hurtDrills(),
]

export const UNIT23_GESUNDHEIT: CourseUnit = {
  level: 'A1',
  number: 23,
  slug: 'gesundheit',
  titleDe: 'Gesundheit',
  title: l('Health', 'Sağlık', 'Gesundheit'),
  goal: l(
    'By the end of this unit you can name body parts, say what hurts, make a doctor’s appointment and get help at the pharmacy.',
    'Bu ünitenin sonunda vücut bölümlerini sayabilir, neresinin ağrıdığını söyleyebilir, doktordan randevu alabilir ve eczanede yardım isteyebilirsin.',
    'Am Ende dieser Einheit benennst du Körperteile, sagst, was wehtut, machst einen Arzttermin und bekommst Hilfe in der Apotheke.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'body', label: l('Body parts', 'Vücut bölümleri', 'Körperteile') },
    { key: 'pain', label: l('…schmerzen / tut weh', '…schmerzen / tut weh', '…schmerzen / tut weh') },
    { key: 'doctor', label: l('Doctor & pharmacy', 'Doktor ve eczane', 'Arzt & Apotheke') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Body parts – and two things for when you are ill.', 'Vücut bölümleri – ve hastayken lazım olan iki şey.', 'Körperteile – und zwei Wörter für Krankheit.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Two ways to say what hurts', 'Ağrıyı söylemenin iki yolu', 'Zwei Wege, Schmerzen zu sagen'),
          body: l(
            'Ich habe + body part + schmerzen (one word): Ich habe Kopfschmerzen. Or: body part + tut / tun weh: Mein Kopf tut weh. Meine Füße tun weh.',
            'Ich habe + vücut bölümü + schmerzen (tek kelime): Ich habe Kopfschmerzen. Ya da: vücut bölümü + tut / tun weh: Mein Kopf tut weh. Meine Füße tun weh.',
            'Ich habe Kopfschmerzen. / Mein Kopf tut weh.'
          ),
          table: {
            head: [l('…schmerzen', '…schmerzen', '…schmerzen'), l('… tut / tun weh', '… tut / tun weh', '… tut / tun weh')],
            rows: [
              ['Ich habe Kopfschmerzen.', 'Mein Kopf tut weh.'],
              ['Ich habe Halsschmerzen.', 'Mein Hals tut weh.'],
              ['Ich habe Bauchschmerzen.', 'Mein Bauch tut weh.'],
              ['–', 'Meine Füße tun weh.'],
            ],
          },
          tip: l(
            'Turkish says „başım ağrıyor“ – German: „Mein Kopf tut weh“ or „Ich habe Kopfschmerzen“.',
            'Türkçe „başım ağrıyor“ der – Almanca: „Mein Kopf tut weh“ ya da „Ich habe Kopfschmerzen“.',
            'Mein Kopf tut weh = Ich habe Kopfschmerzen.'
          ),
        },
        {
          title: l('At the doctor’s', 'Doktorda', 'Beim Arzt'),
          body: l(
            'Typical questions: Was fehlt Ihnen? (What’s wrong?) · Seit wann? (Since when?) · Haben Sie Fieber? Advice uses müssen: Sie müssen viel trinken / im Bett bleiben.',
            'Tipik sorular: Was fehlt Ihnen? (Neyiniz var?) · Seit wann? (Ne zamandan beri?) · Haben Sie Fieber? Tavsiyeler müssen ile: Sie müssen viel trinken / im Bett bleiben.',
            'Was fehlt Ihnen? · Seit wann? · Sie müssen …'
          ),
          examples: [
            { de: 'Ich brauche {m:einen Termin}.', translation: l('I need an appointment.', 'Randevuya ihtiyacım var.', 'Termin') },
            { de: 'Ich habe **seit zwei Tagen** Fieber.', translation: l('I’ve had a fever for two days.', 'İki gündür ateşim var.', 'seit') },
            { de: 'Sie **müssen** im Bett **bleiben**.', translation: l('You have to stay in bed.', 'Yatakta kalmanız gerekiyor.', 'Rat') },
          ],
        },
        {
          title: l('At the pharmacy', 'Eczanede', 'In der Apotheke'),
          body: l(
            'Ich brauche etwas gegen Kopfschmerzen / Husten / Fieber. Instructions: dreimal täglich eine Tablette (three times a day).',
            'Ich brauche etwas gegen Kopfschmerzen / Husten / Fieber. Talimatlar: dreimal täglich eine Tablette (günde üç kez).',
            'etwas gegen … · dreimal täglich.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Mr Novak at the doctor’s.', 'Bay Novak doktorda.', 'Herr Novak bei der Ärztin.'),
      dialogue: [
        { speaker: 'Ärztin', de: 'Guten Tag, Herr Novak. **Was fehlt Ihnen?**', translation: l('Hello, Mr Novak. What’s the matter?', 'İyi günler Bay Novak. Neyiniz var?', '') },
        { speaker: 'Herr Novak', de: 'Ich habe **Kopfschmerzen** und mein **Hals tut weh**.', translation: l('I have a headache and my throat hurts.', 'Başım ağrıyor ve boğazım ağrıyor.', '') },
        { speaker: 'Ärztin', de: '**Seit wann** haben Sie das?', translation: l('Since when have you had that?', 'Ne zamandan beri?', '') },
        { speaker: 'Herr Novak', de: 'Seit zwei Tagen. Und ich habe **Fieber**.', translation: l('For two days. And I have a fever.', 'İki gündür. Bir de ateşim var.', '') },
        { speaker: 'Ärztin', de: 'Öffnen Sie bitte den Mund … Sie haben eine Erkältung.', translation: l('Open your mouth, please … You have a cold.', 'Ağzınızı açın lütfen … Soğuk algınlığınız var.', '') },
        { speaker: 'Ärztin', de: 'Sie **müssen** viel trinken und drei Tage im Bett **bleiben**.', translation: l('You must drink a lot and stay in bed for three days.', 'Bol sıvı almalı ve üç gün yatakta kalmalısınız.', '') },
        { speaker: 'Herr Novak', de: 'Danke, Frau Doktor. – **Gute Besserung!**', translation: l('Thank you, doctor. – Get well soon!', 'Teşekkürler doktor hanım. – Geçmiş olsun!', '') },
      ],
      examples: [
        { de: 'Ich habe **Kopfschmerzen**.', translation: l('I have a headache.', 'Başım ağrıyor.', '') },
        { de: 'Mein Bauch **tut weh**.', translation: l('My stomach hurts.', 'Karnım ağrıyor.', '') },
        { de: 'Meine Füße **tun weh**.', translation: l('My feet hurt.', 'Ayaklarım ağrıyor.', '') },
        { de: 'Das Kind hat **Fieber**.', translation: l('The child has a fever.', 'Çocuğun ateşi var.', '') },
        { de: 'Ich bin **krank**.', translation: l('I’m ill.', 'Hastayım.', '') },
        { de: 'Ich brauche {m:einen Arzt}.', translation: l('I need a doctor.', 'Doktora ihtiyacım var.', '') },
        { de: 'Ich brauche **etwas gegen** Husten.', translation: l('I need something for a cough.', 'Öksürük için bir şey lazım.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Body parts and pain.', 'Vücut bölümleri ve ağrı.', 'Körperteile und Schmerzen.'),
      exercises: ['img-zahn', 'match-body', 'mc-kopfschmerzen', 'mc-tut-weh', 'sort-singular-plural', 'tf-besserung', 'select-symptoms', 'match-doctor', 'schmerz-3'],
    },
    {
      key: 'simulation',
      kind: 'practice',
      title: l('Simulation · Appointment, doctor, pharmacy', 'Simülasyon · Randevu, doktor, eczane', 'Simulation · Termin, Arzt, Apotheke'),
      intro: l(
        'You are ill. Phone the practice, see the doctor, then go to the pharmacy.',
        'Hastasın. Muayenehaneyi ara, doktora git, sonra eczaneye uğra.',
        'Du bist krank. Ruf in der Praxis an, geh zur Ärztin und dann in die Apotheke.'
      ),
      exercises: ['sim-1-termin', 'sim-2-wann', 'sim-3-fehlt', 'sim-4-seit', 'sim-5-rat', 'sim-6-apotheke', 'sim-7-wie-oft'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Say what hurts and ask for help.', 'Neresinin ağrıdığını söyle ve yardım iste.', 'Sag, was wehtut, und bitte um Hilfe.'),
      exercises: ['fill-zahnschmerzen', 'fill-tut', 'fill-muessen', 'build-termin', 'build-krank', 'fix-bin-kopf', 'fix-tut-plural', 'tr-fieber', 'tr-arzt', 'weh-2', 'weh-4'],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Mr Novak writes to his boss.', 'Bay Novak patronuna yazıyor.', 'Herr Novak schreibt seiner Chefin.'),
      passage: [
        'Liebe Frau Weiß,',
        'ich bin leider **krank**. Ich habe **Fieber**, **Kopfschmerzen** und **Halsschmerzen**.',
        'Heute um 11 Uhr gehe ich zum Arzt. Ich komme hoffentlich am Donnerstag wieder.',
        'Viele Grüße, Pavel Novak',
      ],
      glossary: [
        { de: 'Liebe Frau Weiß', note: l('Dear Ms Weiß', 'Sevgili Bayan Weiß', 'Anrede') },
        { de: 'hoffentlich', note: l('hopefully', 'umarım', 'ich hoffe') },
        { de: 'Viele Grüße', note: l('Best regards', 'Selamlar', 'Gruß') },
      ],
      exercises: ['read-krank', 'read-symptome', 'read-arzt', 'read-wann'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('At the practice and the pharmacy.', 'Muayenehanede ve eczanede.', 'In der Praxis und in der Apotheke.'),
      exercises: ['listen-bauch', 'listen-termin', 'listen-tabletten', 'listen-besserung'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Phone the doctor’s practice: you are ill and need an appointment.', 'Muayenehaneyi ara: hastasın ve randevuya ihtiyacın var.', 'Ruf in der Arztpraxis an: Du bist krank und brauchst einen Termin.'),
      points: [
        l('Greet and give your name.', 'Selam ver ve adını söyle.', 'Begrüße und sag deinen Namen.'),
        l('Say what is wrong: „Ich habe … / Mein … tut weh.“', 'Neyin olduğunu söyle: „Ich habe … / Mein … tut weh.“', 'Sag, was du hast.'),
        l('Since when: „Seit … Tagen.“', 'Ne zamandan beri: „Seit … Tagen.“', 'Seit wann?'),
        l('Ask for an appointment: „Ich brauche einen Termin.“', 'Randevu iste: „Ich brauche einen Termin.“', 'Bitte um einen Termin.'),
      ],
      model: ['Guten Morgen, hier ist Ayşe Kaya.', 'Ich bin krank. Ich habe Fieber und Halsschmerzen.', 'Seit gestern.', 'Ich brauche bitte heute einen Termin.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short message: you are ill and cannot come to work or the course (at least 3 sentences).',
        'Kısa bir mesaj yaz: hastasın ve işe ya da kursa gelemiyorsun (en az 3 cümle).',
        'Schreib eine kurze Nachricht: Du bist krank und kannst nicht zur Arbeit oder zum Kurs kommen (mindestens 3 Sätze).'
      ),
      minSentences: 3,
      checks: [
        { label: l('Ich bin krank', 'Ich bin krank', 'Ich bin krank'), pattern: '\\bkrank\\b' },
        { label: l('A symptom (…schmerzen, Fieber, tut weh)', 'Bir belirti (…schmerzen, Fieber, tut weh)', 'Ein Symptom (…schmerzen, Fieber, tut weh)'), pattern: '(schmerzen|Fieber|tut weh|tun weh)' },
        { label: l('kann nicht … kommen', 'kann nicht … kommen', 'kann nicht … kommen'), pattern: '\\bkann\\b[^.!?]*\\bnicht\\b' },
      ],
      model: ['Liebe Frau Weiß,', 'ich bin leider krank und habe Fieber.', 'Mein Kopf tut sehr weh.', 'Ich kann heute nicht kommen.', 'Viele Grüße, Ayşe'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('…schmerzen and tut/tun weh – 60 seconds.', '…schmerzen ve tut/tun weh – 60 saniye.', '…schmerzen und tut/tun weh – 60 Sekunden.'),
      seconds: 60,
      pool: [...PAINS.map((_, i) => `schmerz-${i + 1}`), ...HURTS.map((_, i) => `weh-${i + 1}`)],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Body parts with articles and plurals', 'Artikel ve çoğullarıyla vücut bölümleri', 'Körperteile mit Artikel und Plural'),
      l('Ich habe Kopfschmerzen / Mein Kopf tut weh', 'Ich habe Kopfschmerzen / Mein Kopf tut weh', 'Kopfschmerzen / tut weh'),
      l('Making an appointment: Ich brauche einen Termin.', 'Randevu almak: Ich brauche einen Termin.', 'Termin machen'),
      l('Doctor: Was fehlt Ihnen? Seit wann? Sie müssen …', 'Doktor: Was fehlt Ihnen? Seit wann? Sie müssen …', 'Arzt: Was fehlt Ihnen? Seit wann?'),
      l('Pharmacy: etwas gegen …, dreimal täglich', 'Eczane: etwas gegen …, dreimal täglich', 'Apotheke: etwas gegen …'),
    ],
    mistakes: [
      { wrong: 'Ich bin Kopfschmerzen.', right: 'Ich habe Kopfschmerzen.', note: l('…schmerzen → haben.', '…schmerzen → haben.', '…schmerzen → haben.') },
      { wrong: 'Meine Füße tut weh.', right: 'Meine Füße tun weh.', note: l('Plural → tun.', 'Çoğul → tun.', 'Plural → tun.') },
      { wrong: 'Mein Kopf hat weh.', right: 'Mein Kopf tut weh.', note: l('wehtun, not haben.', 'haben değil wehtun.', 'wehtun.') },
      { wrong: 'Ich brauche ein Termin.', right: 'Ich brauche einen Termin.', note: l('der Termin → einen.', 'der Termin → einen.', 'einen Termin.') },
    ],
  },
}
