import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Brot', gender: 'n', plural: 'die Brote', emoji: '🍞', translation: l('bread', 'ekmek', 'Brot'), example: 'Ich esse Brot mit Käse.' },
  { word: 'Wasser', gender: 'n', emoji: '💧', translation: l('water', 'su', 'Wasser'), example: 'Ich möchte ein Wasser, bitte.' },
  { word: 'Kaffee', gender: 'm', emoji: '☕', translation: l('coffee', 'kahve', 'Kaffee'), example: 'Ich trinke morgens Kaffee.' },
  { word: 'Tee', gender: 'm', emoji: '🍵', translation: l('tea', 'çay', 'Tee'), example: 'Möchtest du einen Tee?' },
  { word: 'Milch', gender: 'f', emoji: '🥛', translation: l('milk', 'süt', 'Milch'), example: 'Kaffee mit Milch, bitte.' },
  { word: 'Käse', gender: 'm', emoji: '🧀', translation: l('cheese', 'peynir', 'Käse'), example: 'Ich mag Käse.' },
  { word: 'Fleisch', gender: 'n', emoji: '🥩', translation: l('meat', 'et', 'Fleisch'), example: 'Ich esse kein Fleisch.' },
  { word: 'Gemüse', gender: 'n', emoji: '🥦', translation: l('vegetables', 'sebze', 'Gemüse'), example: 'Gemüse ist gesund.' },
  { word: 'Fisch', gender: 'm', plural: 'die Fische', emoji: '🐟', translation: l('fish', 'balık', 'Fisch'), example: 'Magst du Fisch?' },
  { word: 'Obst', gender: 'n', emoji: '🍇', translation: l('fruit', 'meyve', 'Obst'), example: 'Ich kaufe Obst.' },
  { word: 'Frühstück', gender: 'n', emoji: '🥐', translation: l('breakfast', 'kahvaltı', 'Frühstück'), example: 'Das Frühstück ist um acht.' },
  { word: 'Abendessen', gender: 'n', emoji: '🍽️', translation: l('dinner', 'akşam yemeği', 'Abendessen'), example: 'Zum Abendessen gibt es Suppe.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Mittagessen', gender: 'n', translation: l('lunch', 'öğle yemeği', 'Mittagessen') },
  { word: 'Apfel', gender: 'm', plural: 'die Äpfel', translation: l('apple', 'elma', 'Apfel') },
  { word: 'Banane', gender: 'f', plural: 'die Bananen', translation: l('banana', 'muz', 'Banane') },
  { word: 'Suppe', gender: 'f', plural: 'die Suppen', translation: l('soup', 'çorba', 'Suppe') },
  { word: 'Saft', gender: 'm', plural: 'die Säfte', translation: l('juice', 'meyve suyu', 'Saft') },
  { word: 'Salat', gender: 'm', plural: 'die Salate', translation: l('salad', 'salata', 'Salat') },
  { word: 'Ei', gender: 'n', plural: 'die Eier', translation: l('egg', 'yumurta', 'Ei') },
  { word: 'möchten', translation: l('would like', 'istemek (kibar)', 'möchten') },
  { word: 'mögen', translation: l('to like', 'sevmek', 'mögen') },
  { word: 'Ich hätte gern …', translation: l('I would like … (polite)', '… rica ediyorum (kibar)', 'Ich hätte gern …') },
  { word: 'gesund', translation: l('healthy', 'sağlıklı', 'gesund') },
  { word: 'lecker', translation: l('tasty', 'lezzetli', 'lecker') },
]

const MOECHTEN = { ich: 'möchte', du: 'möchtest', er: 'möchte', wir: 'möchten', ihr: 'möchtet', sie: 'möchten' } as const
const MOEGEN = { ich: 'mag', du: 'magst', er: 'mag', wir: 'mögen', ihr: 'mögt', sie: 'mögen' } as const
type Person = keyof typeof MOECHTEN

function verbDrills(): Exercise[] {
  const persons = Object.keys(MOECHTEN) as Person[]
  return (['möchten', 'mögen'] as const).flatMap((verb, v) =>
    persons.map((person, i) => {
      const table = verb === 'möchten' ? MOECHTEN : MOEGEN
      const right = table[person]
      const others = [...new Set(Object.values(table))].filter((f) => f !== right)
      const options = [right, others[(i + v) % others.length], others[(i + v + 1) % others.length]]
      const rotation = (i + v) % 3
      const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
      return {
        id: `${verb === 'möchten' ? 'moechten' : 'moegen'}-${person}`,
        type: 'multiple_choice' as const,
        topic: verb === 'möchten' ? 'moechten' : 'moegen',
        concept: `${verb}-forms`,
        skill: 'grammar' as const,
        difficulty: 1 as const,
        prompt: `${person} ___ (${verb})`,
        options: ordered,
        answer: ordered.indexOf(right),
        explanation: l(
          `${verb}: ${person} ${right}. Note: ich and er have the same form.`,
          `${verb}: ${person} ${right}. Dikkat: ich ve er aynı biçimi alır.`,
          `${verb}: ${person} ${right}. ich und er haben dieselbe Form.`
        ),
      }
    })
  )
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise ----------------------------------------------
  {
    id: 'img-kaese',
    type: 'image_choice',
    topic: 'vocabulary',
    concept: 'food',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'der Käse',
    options: [
      { emoji: '🍞', label: 'das Brot' },
      { emoji: '🧀', label: 'der Käse' },
      { emoji: '🥩', label: 'das Fleisch' },
      { emoji: '🥦', label: 'das Gemüse' },
    ],
    answer: 1,
    explanation: l('der Käse = cheese.', 'der Käse = peynir.', 'der Käse.'),
    examples: ['Ich mag **Käse**.'],
  },
  {
    id: 'match-food',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'food',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match food and pictures.', 'Yiyecekleri ve resimleri eşleştir.', 'Ordne Lebensmittel und Bilder zu.'),
    pairs: [
      { left: 'das Brot', right: '🍞' },
      { left: 'die Milch', right: '🥛' },
      { left: 'der Fisch', right: '🐟' },
      { left: 'das Obst', right: '🍇' },
      { left: 'der Tee', right: '🍵' },
    ],
    explanation: l('Always learn food with its article: das Brot, die Milch, der Fisch.', 'Yiyecekleri her zaman artikeliyle öğren: das Brot, die Milch, der Fisch.', 'Lerne Lebensmittel mit Artikel.'),
  },
  {
    id: 'sort-drinks',
    type: 'categorize',
    topic: 'vocabulary',
    concept: 'food',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Food or drink?', 'Yiyecek mi içecek mi?', 'Essen oder Trinken?'),
    categories: ['essen 🍴', 'trinken 🥤'],
    items: [
      { text: 'Brot', category: 0 },
      { text: 'Kaffee', category: 1 },
      { text: 'Käse', category: 0 },
      { text: 'Saft', category: 1 },
      { text: 'Gemüse', category: 0 },
      { text: 'Milch', category: 1 },
    ],
    explanation: l('essen: Brot, Käse, Gemüse · trinken: Kaffee, Saft, Milch.', 'essen: Brot, Käse, Gemüse · trinken: Kaffee, Saft, Milch.', 'essen: Brot, Käse, Gemüse · trinken: Kaffee, Saft, Milch.'),
  },
  {
    id: 'mc-moechte',
    type: 'multiple_choice',
    topic: 'moechten',
    concept: 'möchten-forms',
    skill: 'grammar',
    difficulty: 1,
    prompt: 'Ich ___ einen Kaffee, bitte.',
    options: ['möchte', 'möchtest', 'möchten'],
    answer: 0,
    explanation: l(
      'möchten = would like – polite. ich möchte (no -e ending added: möchte already ends in -e).',
      'möchten = istemek (kibar). ich möchte.',
      'möchten = höflicher Wunsch: ich möchte.'
    ),
    examples: ['Ich **möchte** {m:einen Kaffee}, bitte.'],
    practice: ['moechten-du', 'moechten-wir'],
  },
  {
    id: 'mc-magst',
    type: 'multiple_choice',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ du Fisch?',
    options: ['Magst', 'Mag', 'Mögt'],
    answer: 0,
    explanation: l('mögen: ich mag, du magst, er mag.', 'mögen: ich mag, du magst, er mag.', 'mögen: ich mag, du magst, er mag.'),
    examples: ['**Magst** du Fisch?'],
    practice: ['moegen-ich', 'moegen-wir'],
  },
  {
    id: 'tf-moechte-mag',
    type: 'true_false',
    topic: 'moechten',
    concept: 'möchte-vs-mag',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Ich mag Kaffee“ heißt: Ich bestelle jetzt einen Kaffee.',
    answer: false,
    explanation: l(
      'Ich mag Kaffee = I like coffee (in general). Ich möchte einen Kaffee = I would like a coffee (now).',
      'Ich mag Kaffee = Kahveyi severim (genel olarak). Ich möchte einen Kaffee = Bir kahve istiyorum (şimdi).',
      'Ich mag Kaffee = allgemein. Ich möchte einen Kaffee = jetzt.'
    ),
    examples: ['Ich **mag** Kaffee.', 'Ich **möchte** jetzt {m:einen Kaffee}.'],
  },
  {
    id: 'select-polite',
    type: 'multiple_select',
    topic: 'ordering',
    concept: 'polite-order',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which are polite ways to order? Select all.', 'Hangileri kibar sipariş biçimleri? Hepsini seç.', 'Welche Bestellungen sind höflich? Wähle alle.'),
    options: ['Ich möchte einen Tee, bitte.', 'Tee!', 'Ich hätte gern einen Salat.', 'Ich will Wasser.', 'Ein Wasser, bitte.'],
    answers: [0, 2, 4],
    explanation: l(
      'Polite: Ich möchte … / Ich hätte gern … / … , bitte. „Ich will“ sounds rude when ordering.',
      'Kibar: Ich möchte … / Ich hätte gern … / … , bitte. Sipariş verirken „Ich will“ kaba durur.',
      'Höflich: Ich möchte … / Ich hätte gern … / …, bitte. „Ich will“ klingt unhöflich.'
    ),
  },
  {
    id: 'match-meals',
    type: 'matching',
    topic: 'vocabulary',
    concept: 'meals',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Which meal at which time?', 'Hangi öğün hangi saatte?', 'Welche Mahlzeit um welche Uhrzeit?'),
    pairs: [
      { left: 'das Frühstück', right: '🕗 08:00' },
      { left: 'das Mittagessen', right: '🕐 13:00' },
      { left: 'das Abendessen', right: '🕖 19:00' },
    ],
    explanation: l('Frühstück (morning), Mittagessen (noon), Abendessen (evening).', 'Frühstück (sabah), Mittagessen (öğle), Abendessen (akşam).', 'Frühstück, Mittagessen, Abendessen.'),
  },

  // --- Practice 2: use -----------------------------------------------------
  {
    id: 'fill-moechtest',
    type: 'fill_blank',
    topic: 'moechten',
    concept: 'möchten-forms',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Was ___ du trinken?',
    accepted: ['möchtest'],
    base: 'möchten',
    explanation: l('du möchtest. (möchten + infinitive at the end: trinken)', 'du möchtest. (möchten + sonda mastar: trinken)', 'du möchtest – Infinitiv am Ende.'),
    examples: ['Was **möchtest** du trinken?'],
  },
  {
    id: 'fill-mag',
    type: 'fill_blank',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Mein Sohn ___ keine Milch.',
    accepted: ['mag'],
    base: 'mögen',
    explanation: l('er mag (no ending for er!).', 'er mag (er için ek yok!).', 'er mag (ohne Endung!).'),
    examples: ['Mein Sohn **mag** keine Milch.'],
  },
  {
    id: 'mc-einen-tee',
    type: 'multiple_choice',
    topic: 'ordering',
    concept: 'order-akk',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich hätte gern ___ Tee.',
    options: ['einen', 'ein', 'eine'],
    answer: 0,
    explanation: l(
      'der Tee → Akkusativ: einen Tee (Unit 11).',
      'der Tee → Akkusativ: einen Tee (Ünite 11).',
      'der Tee → einen Tee (Akkusativ).'
    ),
    examples: ['Ich hätte gern {m:einen Tee}.'],
  },
  {
    id: 'build-moechte',
    type: 'sentence_builder',
    topic: 'moechten',
    concept: 'möchten-forms',
    skill: 'grammar',
    difficulty: 1,
    chips: ['ein Wasser', 'möchte', 'Ich', 'bitte'],
    answers: [['Ich', 'möchte', 'ein Wasser', 'bitte']],
    translation: l('I would like a water, please.', 'Bir su rica ediyorum, lütfen.', 'Ich möchte ein Wasser, bitte.'),
    explanation: l('Ich + möchte + ein Wasser (das Wasser → ein).', 'Ich + möchte + ein Wasser (das Wasser → ein).', 'Ich + möchte + ein Wasser.'),
    examples: ['Ich **möchte** {n:ein Wasser}, bitte.'],
  },
  {
    id: 'build-magst',
    type: 'sentence_builder',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'grammar',
    difficulty: 1,
    chips: ['Gemüse', 'du', 'Magst'],
    answers: [['Magst', 'du', 'Gemüse']],
    end: '?',
    translation: l('Do you like vegetables?', 'Sebze sever misin?', 'Magst du Gemüse?'),
    explanation: l('Yes/no question: Magst + du + Gemüse?', 'Evet/hayır sorusu: Magst + du + Gemüse?', 'Magst du Gemüse?'),
    examples: ['**Magst** du Gemüse?'],
  },
  {
    id: 'build-trinken',
    type: 'sentence_builder',
    topic: 'moechten',
    concept: 'möchten-infinitive',
    skill: 'grammar',
    difficulty: 2,
    chips: ['trinken', 'Wir', 'Saft', 'möchten'],
    answers: [['Wir', 'möchten', 'Saft', 'trinken']],
    translation: l('We would like to drink juice.', 'Meyve suyu içmek istiyoruz.', 'Wir möchten Saft trinken.'),
    explanation: l(
      'möchten in position 2, second verb (infinitive) at the very end.',
      'möchten 2. sırada, ikinci fiil (mastar) en sonda.',
      'möchten auf Position 2, Infinitiv am Ende.'
    ),
    examples: ['Wir **möchten** Saft **trinken**.'],
  },
  {
    id: 'fix-moechtest',
    type: 'error_correction',
    topic: 'moechten',
    concept: 'möchten-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Er möchtet einen Salat.',
    accepted: ['Er möchte einen Salat.'],
    explanation: l('er möchte – same as ich.', 'er möchte – ich ile aynı.', 'er möchte – wie ich.'),
    examples: ['Er **möchte** {m:einen Salat}.'],
  },
  {
    id: 'fix-mage',
    type: 'error_correction',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich mage Käse.',
    accepted: ['Ich mag Käse.'],
    explanation: l('ich mag – no ending.', 'ich mag – ek yok.', 'ich mag – ohne Endung.'),
    examples: ['Ich **mag** Käse.'],
  },
  {
    id: 'tr-moechte-kaffee',
    type: 'translation',
    topic: 'ordering',
    concept: 'order-akk',
    skill: 'writing',
    difficulty: 2,
    source: l('I would like a coffee with milk.', 'Sütlü bir kahve rica ediyorum.', 'I would like a coffee with milk.'),
    accepted: ['Ich möchte einen Kaffee mit Milch.', 'Ich hätte gern einen Kaffee mit Milch.'],
    explanation: l('möchte + einen Kaffee + mit Milch.', 'möchte + einen Kaffee + mit Milch.', 'möchte + einen Kaffee + mit Milch.'),
    examples: ['Ich möchte {m:einen Kaffee} mit Milch.'],
  },
  {
    id: 'tr-kein-fleisch',
    type: 'translation',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'writing',
    difficulty: 2,
    source: l('I don’t like meat.', 'Et sevmiyorum.', 'I don’t like meat.'),
    accepted: ['Ich mag kein Fleisch.', 'Ich mag Fleisch nicht.'],
    explanation: l(
      'Ich mag kein Fleisch. (also: Ich mag Fleisch nicht.)',
      'Ich mag kein Fleisch. (ya da: Ich mag Fleisch nicht.)',
      'Ich mag kein Fleisch.'
    ),
    examples: ['Ich mag {n:kein Fleisch}.'],
  },
  {
    id: 'dialog-bestellen',
    type: 'dialogue',
    topic: 'ordering',
    concept: 'polite-order',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Kellner', de: 'Was darf es sein?' }],
    options: ['Ich hätte gern eine Suppe, bitte.', 'Ich mag eine Suppe.', 'Suppe ist gesund.'],
    answer: 0,
    explanation: l(
      '„Was darf es sein?“ = What would you like? → order politely: Ich hätte gern …',
      '„Was darf es sein?“ = Ne arzu edersiniz? → kibarca sipariş ver: Ich hätte gern …',
      'Auf „Was darf es sein?“ bestellt man höflich: Ich hätte gern …'
    ),
    examples: ['Ich hätte gern {f:eine Suppe}, bitte.'],
  },
  {
    id: 'dialog-magst',
    type: 'dialogue',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Eva', de: 'Magst du Fisch?' }],
    options: ['Nein, ich mag keinen Fisch.', 'Nein, ich möchte Fisch.', 'Nein, ich mögen Fisch.'],
    answer: 0,
    explanation: l('der Fisch → keinen Fisch (Akkusativ).', 'der Fisch → keinen Fisch (Akkusativ).', 'der Fisch → keinen Fisch.'),
    examples: ['Ich mag {m:keinen Fisch}.'],
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-suppe',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-karte',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was kostet die Tomatensuppe?',
    options: ['4,50 €', '5,40 €', '3,90 €'],
    answer: 0,
    explanation: l('Tomatensuppe … 4,50 €', 'Tomatensuppe … 4,50 €', 'Tomatensuppe … 4,50 €'),
  },
  {
    id: 'read-vegetarisch',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-karte',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welches Gericht ist ohne Fleisch und Fisch?',
    options: ['Gemüsepfanne mit Reis', 'Schnitzel mit Pommes', 'Lachs mit Kartoffeln'],
    answer: 0,
    explanation: l('Gemüsepfanne = vegetables – no meat, no fish.', 'Gemüsepfanne = sebze – et yok, balık yok.', 'Gemüsepfanne – ohne Fleisch und Fisch.'),
  },
  {
    id: 'read-guenstig',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-karte',
    skill: 'reading',
    difficulty: 2,
    statement: 'Der Lachs ist teurer als das Schnitzel.',
    answer: true,
    explanation: l('Lachs 14,90 € – Schnitzel 12,50 €.', 'Lachs 14,90 € – Schnitzel 12,50 €.', 'Lachs 14,90 € – Schnitzel 12,50 €.'),
  },
  {
    id: 'read-getraenk',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-karte',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was ist das billigste Getränk?',
    options: ['Wasser', 'Apfelsaft', 'Kaffee'],
    answer: 0,
    explanation: l('Wasser 2,20 € – the cheapest.', 'Wasser 2,20 € – en ucuz.', 'Wasser 2,20 €.'),
  },

  // --- Listening ---------------------------------------------------
  {
    id: 'listen-order',
    type: 'listening_choice',
    topic: 'ordering',
    concept: 'order-akk',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich hätte gern einen Tee und ein Stück Kuchen.',
    question: l('What does the person order?', 'Kişi ne sipariş ediyor?', 'Was bestellt die Person?'),
    options: ['🍵 + 🍰', '☕ + 🍰', '🍵 + 🥐'],
    answer: 0,
    explanation: l('Tee + Kuchen.', 'Tee + Kuchen.', 'Tee + Kuchen.'),
  },
  {
    id: 'listen-mag-nicht',
    type: 'listening_choice',
    topic: 'moegen',
    concept: 'mögen-forms',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich mag Fisch, aber ich mag kein Fleisch.',
    question: l('What doesn’t the person like?', 'Kişi neyi sevmiyor?', 'Was mag die Person nicht?'),
    options: ['🐟 Fisch', '🥩 Fleisch', '🥦 Gemüse'],
    answer: 1,
    explanation: l('„kein Fleisch“', '„kein Fleisch“', '„kein Fleisch“'),
  },
  {
    id: 'listen-fruehstueck',
    type: 'listening_choice',
    topic: 'vocabulary',
    concept: 'meals',
    skill: 'listening',
    difficulty: 1,
    audio: 'Zum Frühstück esse ich Brot mit Käse und trinke Kaffee.',
    question: l('Which meal is it?', 'Hangi öğün?', 'Welche Mahlzeit ist das?'),
    options: ['Frühstück', 'Mittagessen', 'Abendessen'],
    answer: 0,
    explanation: l('„Zum Frühstück …“', '„Zum Frühstück …“', '„Zum Frühstück …“'),
  },
  {
    id: 'listen-preis',
    type: 'listening_choice',
    topic: 'ordering',
    concept: 'polite-order',
    skill: 'listening',
    difficulty: 2,
    audio: 'Zwei Wasser und eine Suppe – das macht neun Euro zwanzig.',
    question: l('How much is it?', 'Ne kadar tutuyor?', 'Wie viel kostet das?'),
    options: ['9,20 €', '2,90 €', '12,90 €'],
    answer: 0,
    explanation: l('neun Euro zwanzig = 9,20 €.', 'neun Euro zwanzig = 9,20 €.', 'neun Euro zwanzig = 9,20 €.'),
  },

  ...verbDrills(),
]

export const UNIT12_ESSEN_TRINKEN: CourseUnit = {
  level: 'A1',
  number: 12,
  slug: 'essen-trinken',
  titleDe: 'Essen und Trinken',
  title: l('Food and drink', 'Yiyecek ve içecek', 'Essen und Trinken'),
  goal: l(
    'By the end of this unit you can talk about food you like, order politely with „möchte“ and „hätte gern“, and read a simple menu.',
    'Bu ünitenin sonunda sevdiğin yiyeceklerden bahsedebilir, „möchte“ ve „hätte gern“ ile kibarca sipariş verebilir ve basit bir menüyü okuyabilirsin.',
    'Am Ende dieser Einheit sprichst du über Essen, bestellst höflich mit „möchte“ und „hätte gern“ und liest eine einfache Speisekarte.'
  ),
  minutes: [15, 20],
  topics: [
    { key: 'vocabulary', label: l('Food & meals', 'Yiyecekler ve öğünler', 'Essen & Mahlzeiten') },
    { key: 'moechten', label: l('möchten', 'möchten', 'möchten') },
    { key: 'moegen', label: l('mögen', 'mögen', 'mögen') },
    { key: 'ordering', label: l('Ordering politely', 'Kibarca sipariş', 'Höflich bestellen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('What’s on the table? Tap the food.', 'Masada ne var? Yiyeceklere dokun.', 'Was steht auf dem Tisch? Tippe auf das Essen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('möchten – would like', 'möchten – istemek (kibar)', 'möchten'),
          body: l(
            'Use möchten to say what you want – politely. ich and er have the same form (möchte). With a second verb, it goes to the end: Ich möchte Kaffee trinken.',
            'Ne istediğini kibarca söylemek için möchten kullan. ich ve er aynı biçimi alır (möchte). İkinci bir fiil varsa sona gider: Ich möchte Kaffee trinken.',
            'möchten = höflicher Wunsch. ich und er: möchte. Zweites Verb am Ende: Ich möchte Kaffee trinken.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('möchten', 'möchten', 'möchten'), l('mögen', 'mögen', 'mögen')],
            rows: [
              ['ich', 'möchte', 'mag'],
              ['du', 'möchtest', 'magst'],
              ['er / sie / es', 'möchte', 'mag'],
              ['wir', 'möchten', 'mögen'],
              ['ihr', 'möchtet', 'mögt'],
              ['sie / Sie', 'möchten', 'mögen'],
            ],
          },
        },
        {
          title: l('mögen – to like', 'mögen – sevmek', 'mögen'),
          body: l(
            'mögen says what you like in general: Ich mag Käse. Ich mag keinen Fisch. Careful: ich mag and er mag have no ending.',
            'mögen genel olarak neyi sevdiğini söyler: Ich mag Käse. Ich mag keinen Fisch. Dikkat: ich mag ve er mag ek almaz.',
            'mögen = gernhaben (allgemein). ich mag und er mag – ohne Endung.'
          ),
          examples: [
            { de: 'Ich **mag** Käse. → allgemein', translation: l('I like cheese (in general).', 'Peyniri severim (genel olarak).', 'mögen') },
            { de: 'Ich **möchte** {m:einen Käse}toast. → jetzt', translation: l('I would like a cheese toast (now).', 'Bir peynirli tost istiyorum (şimdi).', 'möchten') },
          ],
        },
        {
          title: l('Ordering politely', 'Kibarca sipariş', 'Höflich bestellen'),
          body: l(
            'Ich möchte … · Ich hätte gern … · Ein …, bitte. Avoid „Ich will …“ – it sounds demanding. The thing you order is Akkusativ: einen Tee, eine Suppe, ein Wasser.',
            'Ich möchte … · Ich hätte gern … · Ein …, bitte. „Ich will …“ demekten kaçın – buyurgan durur. Sipariş edilen şey Akkusativ’dir: einen Tee, eine Suppe, ein Wasser.',
            'Ich möchte … · Ich hätte gern … · Ein …, bitte. Kein „Ich will …“. Akkusativ: einen Tee.'
          ),
        },
        {
          title: l('Food often without an article', 'Yiyecekler çoğu zaman artikelsiz', 'Essen oft ohne Artikel'),
          body: l(
            'When you talk about food in general: Ich esse Brot. Ich trinke Wasser. When you order one portion: ein Wasser, einen Kaffee.',
            'Yiyecekten genel olarak bahsederken: Ich esse Brot. Ich trinke Wasser. Bir porsiyon sipariş ederken: ein Wasser, einen Kaffee.',
            'Allgemein: Ich esse Brot. Eine Portion: ein Wasser, einen Kaffee.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Breakfast at Eva’s place. Her friend Tarik is visiting.', 'Eva’nın evinde kahvaltı. Arkadaşı Tarik ziyarette.', 'Frühstück bei Eva. Ihr Freund Tarik ist zu Besuch.'),
      dialogue: [
        { speaker: 'Eva', de: 'Was **möchtest** du trinken? Kaffee oder Tee?', translation: l('What would you like to drink? Coffee or tea?', 'Ne içmek istersin? Kahve mi çay mı?', '') },
        { speaker: 'Tarik', de: 'Ich **möchte** {m:einen Tee}, bitte.', translation: l('I’d like a tea, please.', 'Bir çay rica ediyorum.', '') },
        { speaker: 'Eva', de: '**Magst** du Käse? Oder lieber Marmelade?', translation: l('Do you like cheese? Or rather jam?', 'Peynir sever misin? Yoksa reçel mi tercih edersin?', '') },
        { speaker: 'Tarik', de: 'Ich **mag** Käse sehr! Und ich **möchte** {n:ein Ei}.', translation: l('I love cheese! And I’d like an egg.', 'Peyniri çok severim! Ve bir yumurta istiyorum.', '') },
        { speaker: 'Eva', de: 'Hier, bitte. Und Obst? Ich habe Äpfel und Bananen.', translation: l('Here you are. And fruit? I have apples and bananas.', 'Buyur. Meyve? Elma ve muzum var.', '') },
        { speaker: 'Tarik', de: 'Danke, {f:eine Banane}, bitte. Das Frühstück ist super!', translation: l('Thanks, a banana, please. Breakfast is great!', 'Teşekkürler, bir muz lütfen. Kahvaltı süper!', '') },
      ],
      examples: [
        { de: 'Ich **möchte** {m:einen Kaffee}.', translation: l('I’d like a coffee.', 'Bir kahve istiyorum.', '') },
        { de: 'Was **möchtest** du essen?', translation: l('What would you like to eat?', 'Ne yemek istersin?', '') },
        { de: 'Wir **möchten** bezahlen.', translation: l('We would like to pay.', 'Ödemek istiyoruz.', '') },
        { de: 'Ich **mag** Gemüse.', translation: l('I like vegetables.', 'Sebze severim.', '') },
        { de: 'Er **mag** {m:keinen Fisch}.', translation: l('He doesn’t like fish.', 'Balık sevmez.', '') },
        { de: 'Ich hätte gern {f:eine Suppe}.', translation: l('I’d like a soup.', 'Bir çorba rica ediyorum.', '') },
        { de: '{n:Ein Wasser}, bitte.', translation: l('A water, please.', 'Bir su, lütfen.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Food words, möchten and mögen.', 'Yiyecek kelimeleri, möchten ve mögen.', 'Lebensmittel, möchten und mögen.'),
      exercises: ['img-kaese', 'match-food', 'sort-drinks', 'mc-moechte', 'mc-magst', 'tf-moechte-mag', 'select-polite', 'match-meals', 'moechten-ihr'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Order food and talk about what you like.', 'Yemek sipariş et ve neyi sevdiğinden bahset.', 'Bestelle Essen und sag, was du magst.'),
      exercises: [
        'fill-moechtest',
        'fill-mag',
        'mc-einen-tee',
        'build-moechte',
        'build-magst',
        'build-trinken',
        'fix-moechtest',
        'fix-mage',
        'tr-moechte-kaffee',
        'tr-kein-fleisch',
        'dialog-bestellen',
        'dialog-magst',
        'moegen-ihr',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('The menu of the café „Zur Linde“.', '„Zur Linde“ kafesinin menüsü.', 'Die Speisekarte vom Café „Zur Linde“.'),
      passage: [
        '**Speisekarte – Café „Zur Linde“**',
        'Tomatensuppe 4,50 € · Salat mit Käse 7,80 €',
        'Gemüsepfanne mit Reis 9,50 € · Schnitzel mit Pommes 12,50 € · Lachs mit Kartoffeln 14,90 €',
        'Getränke: Wasser 2,20 € · Apfelsaft 2,80 € · Kaffee 2,90 € · Tee 2,60 €',
      ],
      glossary: [
        { de: 'die Speisekarte', note: l('menu', 'menü', 'Liste mit Essen') },
        { de: 'die Pfanne / der Reis', note: l('pan / rice', 'tava / pirinç', 'Pfanne / Reis') },
        { de: 'der Lachs', note: l('salmon', 'somon', 'ein Fisch') },
        { de: 'die Getränke', note: l('drinks', 'içecekler', 'zum Trinken') },
        { de: 'teurer als', note: l('more expensive than', '…den daha pahalı', 'kostet mehr als') },
      ],
      exercises: ['read-suppe', 'read-vegetarisch', 'read-guenstig', 'read-getraenk'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('At the table and in the café.', 'Sofrada ve kafede.', 'Am Tisch und im Café.'),
      exercises: ['listen-order', 'listen-mag-nicht', 'listen-fruehstueck', 'listen-preis'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Talk about your eating habits – and order in a café.', 'Yemek alışkanlıklarını anlat – ve bir kafede sipariş ver.', 'Sprich über dein Essen – und bestelle im Café.'),
      points: [
        l('What do you eat for breakfast?', 'Kahvaltıda ne yersin?', 'Was isst du zum Frühstück?'),
        l('What do you like / not like? (Ich mag … / Ich mag kein …)', 'Neyi seversin / sevmezsin? (Ich mag … / Ich mag kein …)', 'Was magst du (nicht)?'),
        l('Order: „Ich hätte gern …“ / „Ich möchte …“', 'Sipariş ver: „Ich hätte gern …“ / „Ich möchte …“', 'Bestelle höflich.'),
      ],
      model: ['Zum Frühstück esse ich Brot mit Käse.', 'Ich mag Obst, aber ich mag keinen Fisch.', 'Ich hätte gern einen Tee und eine Suppe, bitte.'],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write about food: what do you like, what don’t you like, what would you like to eat today? (at least 4 sentences)',
        'Yiyecekler hakkında yaz: neyi seversin, neyi sevmezsin, bugün ne yemek istersin? (en az 4 cümle)',
        'Schreib über Essen: Was magst du, was nicht, was möchtest du heute essen? (mindestens 4 Sätze)'
      ),
      minSentences: 4,
      checks: [
        { label: l('Uses mögen (mag …)', 'mögen kullanılmış (mag …)', 'Mit mögen (mag …)'), pattern: '\\b(mag|magst|mögen|mögt)\\b' },
        { label: l('Uses möchten / hätte gern', 'möchten / hätte gern kullanılmış', 'Mit möchten / hätte gern'), pattern: '\\b(möchte|möchtest|möchten|möchtet)\\b|hätte gern' },
        { label: l('Names food', 'Yiyecek adı veriyor', 'Nennt Lebensmittel'), pattern: '\\b(Brot|Wasser|Kaffee|Tee|Milch|Käse|Fleisch|Gemüse|Fisch|Obst|Apfel|Äpfel|Banane|Bananen|Suppe|Salat|Saft|Ei|Eier)\\b' },
      ],
      model: ['Ich mag Käse und Obst.', 'Ich mag keinen Fisch.', 'Zum Frühstück trinke ich Tee.', 'Heute möchte ich eine Suppe essen.'],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('möchten and mögen – all forms in 60 seconds.', 'möchten ve mögen – 60 saniyede tüm biçimler.', 'möchten und mögen – alle Formen in 60 Sekunden.'),
      seconds: 60,
      pool: ['moechten', 'moegen'].flatMap((verb) => (Object.keys(MOECHTEN) as Person[]).map((p) => `${verb}-${p}`)),
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Food and drink with articles', 'Artikelleriyle yiyecek ve içecekler', 'Essen und Getränke mit Artikel'),
      l('möchten: ich möchte, du möchtest …', 'möchten: ich möchte, du möchtest …', 'möchten: ich möchte, du möchtest …'),
      l('mögen: ich mag, du magst …', 'mögen: ich mag, du magst …', 'mögen: ich mag, du magst …'),
      l('Polite orders: Ich hätte gern …', 'Kibar sipariş: Ich hätte gern …', 'Höflich: Ich hätte gern …'),
      l('Frühstück, Mittagessen, Abendessen', 'Frühstück, Mittagessen, Abendessen', 'Frühstück, Mittagessen, Abendessen'),
    ],
    mistakes: [
      { wrong: 'Ich mage Käse.', right: 'Ich mag Käse.', note: l('ich mag – no ending.', 'ich mag – ek yok.', 'ich mag – ohne Endung.') },
      { wrong: 'Er möchtet Tee.', right: 'Er möchte Tee.', note: l('er möchte', 'er möchte', 'er möchte') },
      { wrong: 'Ich will einen Kaffee.', right: 'Ich möchte einen Kaffee.', note: l('Polite: möchte.', 'Kibar: möchte.', 'Höflich: möchte.') },
      { wrong: 'Ich möchte ein Kaffee.', right: 'Ich möchte einen Kaffee.', note: l('der Kaffee → einen.', 'der Kaffee → einen.', 'der Kaffee → einen.') },
    ],
  },
}
