import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'warten auf + Akk.', emoji: '⏳', translation: l('to wait for', '… beklemek', 'warten'), example: 'Ich warte auf den Bus.' },
  { word: 'sich freuen auf + Akk.', emoji: '🤩', translation: l('to look forward to', '… dört gözle beklemek', 'Vorfreude'), example: 'Ich freue mich auf die Ferien.' },
  { word: 'sich freuen über + Akk.', emoji: '🎁', translation: l('to be happy about', '…-e sevinmek', 'Freude über etwas Jetziges'), example: 'Sie freut sich über das Geschenk.' },
  { word: 'sich interessieren für + Akk.', emoji: '🔭', translation: l('to be interested in', '… ile ilgilenmek', 'Interesse'), example: 'Ich interessiere mich für Politik.' },
  { word: 'denken an + Akk.', emoji: '💭', translation: l('to think of', '… düşünmek', 'im Kopf haben'), example: 'Ich denke oft an meine Familie.' },
  { word: 'sich ärgern über + Akk.', emoji: '😤', translation: l('to be annoyed about', '…-e sinirlenmek', 'Ärger'), example: 'Er ärgert sich über das Wetter.' },
  { word: 'sprechen über + Akk.', emoji: '🗣️', translation: l('to talk about', '… hakkında konuşmak', 'Thema'), example: 'Wir sprechen über den Film.' },
  { word: 'träumen von + Dat.', emoji: '💤', translation: l('to dream of', '… hayal etmek', 'Traum'), example: 'Ich träume von einem Haus am Meer.' },
  { word: 'Angst haben vor + Dat.', emoji: '😨', translation: l('to be afraid of', '…-den korkmak', 'Angst'), example: 'Mein Sohn hat Angst vor Hunden.' },
  { word: 'sich kümmern um + Akk.', emoji: '🧸', translation: l('to take care of', '… ile ilgilenmek, bakmak', 'sorgen für'), example: 'Wer kümmert sich um die Katze?' },
  { word: 'Worauf? – Darauf.', emoji: '🔎', translation: l('What for? – For that.', 'Neyi? – Onu.', 'Frage und Antwort bei Sachen'), example: 'Worauf wartest du? – Auf den Bus. Ich warte schon lange darauf.' },
  { word: 'Auf wen? – Auf ihn.', emoji: '👤', translation: l('For whom? – For him.', 'Kimi? – Onu.', 'Frage und Antwort bei Personen'), example: 'Auf wen wartest du? – Auf meinen Bruder.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Ferien', translation: l('holidays (plural)', 'tatil (çoğul)', 'Ferien') },
  { word: 'Geschenk', gender: 'n', plural: 'die Geschenke', translation: l('present', 'hediye', 'Geschenk') },
  { word: 'Politik', gender: 'f', translation: l('politics', 'siyaset', 'Politik') },
  { word: 'Antwort', gender: 'f', plural: 'die Antworten', translation: l('answer', 'cevap', 'Antwort') },
  { word: 'Spinne', gender: 'f', plural: 'die Spinnen', translation: l('spider', 'örümcek', 'Spinne') },
  { word: 'Zukunft', gender: 'f', translation: l('future', 'gelecek', 'Zukunft') },
]

/** [id, sentence with ___ for the preposition, right preposition, two distractors] */
const PREP_DRILLS: [string, string, string, [string, string]][] = [
  ['warten', 'Wir warten schon zwanzig Minuten ___ den Zug.', 'auf', ['für', 'an']],
  ['interessieren', 'Interessierst du dich ___ Fußball?', 'für', ['über', 'an']],
  ['denken', 'Ich denke oft ___ meine Kindheit.', 'an', ['über', 'von']],
  ['traeumen', 'Sie träumt ___ einer Weltreise.', 'von', ['über', 'auf']],
  ['angst', 'Hast du Angst ___ Spinnen?', 'vor', ['von', 'für']],
  ['kuemmern', 'Meine Oma kümmert sich ___ den Garten.', 'um', ['für', 'auf']],
  ['sprechen', 'Wir sprechen ___ das Wetter.', 'über', ['von', 'auf']],
  ['freuen-auf', 'Ich freue mich schon ___ deinen Besuch nächste Woche!', 'auf', ['über', 'für']],
]

function prepDrills(): Exercise[] {
  return PREP_DRILLS.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `vp-${id}`,
      type: 'multiple_choice' as const,
      topic: 'prepositions',
      concept: `vp-${id}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `This verb always goes with „${right}“ – learn verb and preposition together.`,
        `Bu fiil her zaman „${right}“ ile kullanılır – fiili ve edatı birlikte öğren.`,
        `Verb + „${right}“ – zusammen lernen.`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-verbs',
    type: 'matching',
    topic: 'prepositions',
    concept: 'verb-prep-pairs',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Which preposition goes with the verb?', 'Fiille hangi edat kullanılır?', 'Welche Präposition passt?'),
    pairs: [
      { left: 'warten', right: 'auf' },
      { left: 'sich interessieren', right: 'für' },
      { left: 'denken', right: 'an' },
      { left: 'träumen', right: 'von' },
      { left: 'Angst haben', right: 'vor' },
    ],
    explanation: l('warten auf, sich interessieren für, denken an, träumen von, Angst haben vor.', 'warten auf, sich interessieren für, denken an, träumen von, Angst haben vor.', 'Verb + Präposition.'),
    practice: ['vp-warten', 'vp-denken'],
  },
  {
    id: 'mc-auf-ueber',
    type: 'multiple_choice',
    topic: 'prepositions',
    concept: 'freuen-auf-ueber',
    skill: 'grammar',
    difficulty: 3,
    prompt: 'Danke für die Blumen! Ich freue mich sehr ___ sie.',
    options: ['über', 'auf', 'an'],
    answer: 0,
    explanation: l(
      'sich freuen über = happy about something now/past (the flowers are here). sich freuen auf = looking forward to the future.',
      'sich freuen über = şimdi/geçmişteki bir şeye sevinmek (çiçekler burada). sich freuen auf = geleceği dört gözle beklemek.',
      'über = jetzt · auf = Zukunft.'
    ),
    examples: ['Ich freue mich **über** die Blumen.', 'Ich freue mich **auf** den Urlaub.'],
    practice: ['sort-auf-ueber'],
  },
  {
    id: 'sort-auf-ueber',
    type: 'categorize',
    topic: 'prepositions',
    concept: 'freuen-auf-ueber',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('sich freuen auf (future) or über (now/past)?', 'sich freuen auf (gelecek) mu über (şimdi/geçmiş) mi?', 'sich freuen auf oder über?'),
    categories: ['auf (Zukunft)', 'über (jetzt)'],
    items: [
      { text: '… den Urlaub im Sommer', category: 0 },
      { text: '… das Geschenk (gerade bekommen)', category: 1 },
      { text: '… das Wochenende', category: 0 },
      { text: '… die gute Note (heute bekommen)', category: 1 },
      { text: '… deinen Besuch morgen', category: 0 },
      { text: '… deinen Anruf (gerade eben)', category: 1 },
    ],
    explanation: l('auf → something coming. über → something that has happened / is here.', 'auf → gelecek bir şey. über → olmuş / burada olan bir şey.', 'auf = kommt noch · über = ist da.'),
  },
  {
    id: 'select-akk',
    type: 'multiple_select',
    topic: 'cases',
    concept: 'prep-case',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which are correct? Select all.', 'Hangileri doğru? Hepsini seç.', 'Was ist richtig? Wähle alle.'),
    options: ['Ich warte auf den Bus.', 'Ich warte auf dem Bus.', 'Er träumt von einem Auto.', 'Er träumt von ein Auto.', 'Wir sprechen über den Film.'],
    answers: [0, 2, 4],
    explanation: l('auf/über/für/um/an + Akkusativ (with these verbs). von/vor + Dativ.', 'auf/über/für/um/an + Akkusativ (bu fiillerle). von/vor + Dativ.', 'auf/über + Akk · von/vor + Dat.'),
  },
  {
    id: 'tf-worauf',
    type: 'true_false',
    topic: 'wo-da',
    concept: 'wor-question',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Für Sachen fragt man „Worauf wartest du?“, für Personen „Auf wen wartest du?“',
    answer: true,
    explanation: l('Things → wo(r) + preposition: Worauf? Wofür? Wovon? People → preposition + wen/wem: Auf wen? Mit wem?', 'Şeyler → wo(r) + edat: Worauf? Wofür? Wovon? Kişiler → edat + wen/wem: Auf wen? Mit wem?', 'Sachen: Worauf? · Personen: Auf wen?'),
  },
  {
    id: 'image-angst',
    type: 'image_choice',
    topic: 'prepositions',
    concept: 'vp-angst',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Ich habe Angst vor Spinnen.',
    options: [
      { emoji: '🕷️', label: 'Spinnen' },
      { emoji: '🐕', label: 'Hunde' },
      { emoji: '🐍', label: 'Schlangen' },
      { emoji: '🦈', label: 'Haie' },
    ],
    answer: 0,
    explanation: l('die Spinne = spider 🕷️.', 'die Spinne = örümcek 🕷️.', 'die Spinne.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-fuer',
    type: 'fill_blank',
    topic: 'prepositions',
    concept: 'vp-interessieren',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Mein Sohn interessiert sich sehr ___ Dinosaurier.',
    accepted: ['für'],
    base: 'Präposition',
    explanation: l('sich interessieren für + Akk.', 'sich interessieren für + Akk.', 'sich interessieren für.'),
    examples: ['Mein Sohn interessiert sich **für** Dinosaurier.'],
  },
  {
    id: 'fill-darauf',
    type: 'fill_blank',
    topic: 'wo-da',
    concept: 'dar-answer',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Freust du dich auf den Urlaub? – Ja, ich freue mich sehr ___!',
    accepted: ['darauf'],
    base: 'da(r) + auf',
    explanation: l('Instead of repeating „auf den Urlaub“ → darauf (da + r + auf, because auf starts with a vowel).', '„auf den Urlaub“ tekrarlamak yerine → darauf (da + r + auf, çünkü auf sesli harfle başlar).', 'darauf.'),
    examples: ['Ich freue mich sehr **darauf**!'],
  },
  {
    id: 'fill-wovon',
    type: 'fill_blank',
    topic: 'wo-da',
    concept: 'wor-question',
    skill: 'grammar',
    difficulty: 3,
    sentence: '___ träumst du? – Von einem eigenen Café.',
    accepted: ['Wovon'],
    base: 'wo + von',
    explanation: l('träumen von + thing → Wovon?', 'träumen von + şey → Wovon?', 'Wovon?'),
    examples: ['**Wovon** träumst du?'],
  },
  {
    id: 'build-warten',
    type: 'sentence_builder',
    topic: 'prepositions',
    concept: 'vp-warten',
    skill: 'grammar',
    difficulty: 2,
    chips: ['auf', 'Antwort', 'deine', 'Ich', 'warte'],
    answers: [['Ich', 'warte', 'auf', 'deine', 'Antwort']],
    translation: l('I’m waiting for your answer.', 'Cevabını bekliyorum.', 'Ich warte auf deine Antwort.'),
    explanation: l('warten auf + Akkusativ.', 'warten auf + Akkusativ.', 'warten auf.'),
    examples: ['Ich warte **auf** deine Antwort.'],
  },
  {
    id: 'build-kuemmern',
    type: 'sentence_builder',
    topic: 'prepositions',
    concept: 'vp-kuemmern',
    skill: 'grammar',
    difficulty: 2,
    chips: ['um', 'Wer', 'die Kinder', 'sich', 'kümmert'],
    answers: [['Wer', 'kümmert', 'sich', 'um', 'die Kinder']],
    end: '?',
    translation: l('Who is taking care of the children?', 'Çocuklarla kim ilgileniyor?', 'Wer kümmert sich um die Kinder?'),
    explanation: l('sich kümmern um + Akkusativ.', 'sich kümmern um + Akkusativ.', 'sich kümmern um.'),
    examples: ['Wer kümmert sich **um** die Kinder?'],
  },
  {
    id: 'build-denke',
    type: 'sentence_builder',
    topic: 'prepositions',
    concept: 'vp-denken',
    skill: 'grammar',
    difficulty: 2,
    chips: ['an', 'dich', 'denke', 'Ich', 'oft'],
    answers: [['Ich', 'denke', 'oft', 'an', 'dich']],
    translation: l('I often think of you.', 'Seni sık sık düşünüyorum.', 'Ich denke oft an dich.'),
    explanation: l('denken an + Akkusativ: an dich.', 'denken an + Akkusativ: an dich.', 'an dich.'),
    examples: ['Ich denke oft **an dich**.'],
  },
  {
    id: 'fix-warten-fuer',
    type: 'error_correction',
    topic: 'prepositions',
    concept: 'vp-warten',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich warte für dich vor dem Kino.',
    accepted: ['Ich warte auf dich vor dem Kino.', 'Ich warte vor dem Kino auf dich.'],
    explanation: l('warten auf (not für – that’s English „wait for“).', 'warten auf (für değil – bu İngilizcedeki „wait for“).', 'warten auf.'),
    examples: ['Ich warte **auf** dich vor dem Kino.'],
  },
  {
    id: 'fix-interessiere',
    type: 'error_correction',
    topic: 'prepositions',
    concept: 'vp-interessieren',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich interessiere mich an Kunst.',
    accepted: ['Ich interessiere mich für Kunst.'],
    explanation: l('sich interessieren für.', 'sich interessieren für.', 'für Kunst.'),
    examples: ['Ich interessiere mich **für** Kunst.'],
  },
  {
    id: 'fix-angst',
    type: 'error_correction',
    topic: 'cases',
    concept: 'prep-case',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das Kind hat Angst vor den Hund.',
    accepted: ['Das Kind hat Angst vor dem Hund.'],
    explanation: l('Angst haben vor + Dativ: vor dem Hund.', 'Angst haben vor + Dativ: vor dem Hund.', 'vor dem Hund.'),
    examples: ['Das Kind hat Angst **vor dem** Hund.'],
  },
  {
    id: 'tr-freue',
    type: 'translation',
    topic: 'prepositions',
    concept: 'freuen-auf-ueber',
    skill: 'writing',
    difficulty: 2,
    source: l('I’m looking forward to the weekend.', 'Hafta sonunu dört gözle bekliyorum.', 'I’m looking forward to the weekend.'),
    accepted: ['Ich freue mich auf das Wochenende.', 'Ich freue mich aufs Wochenende.'],
    explanation: l('Future → sich freuen auf.', 'Gelecek → sich freuen auf.', 'auf das Wochenende.'),
    examples: ['Ich freue mich **auf** das Wochenende.'],
  },
  {
    id: 'tr-sprechen',
    type: 'translation',
    topic: 'prepositions',
    concept: 'vp-sprechen',
    skill: 'writing',
    difficulty: 2,
    source: l('We are talking about the problem.', 'Sorun hakkında konuşuyoruz.', 'We are talking about the problem.'),
    accepted: ['Wir sprechen über das Problem.', 'Wir reden über das Problem.'],
    explanation: l('sprechen über + Akkusativ.', 'sprechen über + Akkusativ.', 'über das Problem.'),
    examples: ['Wir sprechen **über** das Problem.'],
  },
  {
    id: 'dialog-worauf',
    type: 'dialogue',
    topic: 'wo-da',
    concept: 'wor-question',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Du siehst so glücklich aus! Worauf freust du dich?' }],
    options: ['Auf meinen Urlaub in Portugal!', 'Über meinen Urlaub in Portugal!', 'Für meinen Urlaub in Portugal!'],
    answer: 0,
    explanation: l('Worauf? → Auf … (future).', 'Worauf? → Auf … (gelecek).', 'Auf meinen Urlaub.'),
  },
  {
    id: 'dialog-wen',
    type: 'dialogue',
    topic: 'wo-da',
    concept: 'wen-question',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Kellner', de: 'Möchten Sie schon bestellen?' }],
    options: ['Noch nicht, danke. Ich warte noch auf eine Freundin.', 'Noch nicht, danke. Ich warte noch für eine Freundin.', 'Noch nicht, danke. Ich warte noch darauf eine Freundin.'],
    answer: 0,
    explanation: l('Person → warten auf + person.', 'Kişi → warten auf + kişi.', 'auf eine Freundin.'),
  },
  {
    id: 'ordering-frage',
    type: 'ordering',
    topic: 'wo-da',
    concept: 'wor-question',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Build the question.', 'Soruyu kur.', 'Bilde die Frage.'),
    items: ['du', 'Wofür', 'dich', 'interessierst'],
    answer: ['Wofür', 'interessierst', 'du', 'dich'],
    explanation: l('Wofür (1) – verb (2) – subject – sich.', 'Wofür (1) – fiil (2) – özne – sich.', 'Wofür interessierst du dich?'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-traum',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-profil',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wovon träumt Sofia?',
    options: ['Von einer Reise nach Japan.', 'Von einem eigenen Haus.', 'Von einem neuen Job.'],
    answer: 0,
    explanation: l('„Ich träume von einer Reise nach Japan.“', '„Ich träume von einer Reise nach Japan.“', '„von einer Reise nach Japan“'),
  },
  {
    id: 'read-interesse',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-profil',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wofür interessiert sich Sofia?',
    options: ['Für Fotografie und Kochen.', 'Für Fußball.', 'Für Politik.'],
    answer: 0,
    explanation: l('„Ich interessiere mich für Fotografie und Kochen.“', '„Ich interessiere mich für Fotografie und Kochen.“', '„Fotografie und Kochen“'),
  },
  {
    id: 'read-angst',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-profil',
    skill: 'reading',
    difficulty: 2,
    statement: 'Sofia hat Angst vor dem Fliegen.',
    answer: true,
    explanation: l('„Leider habe ich ein bisschen Angst vor dem Fliegen.“', '„Leider habe ich ein bisschen Angst vor dem Fliegen.“', '„Angst vor dem Fliegen“'),
  },
  {
    id: 'read-katze',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-profil',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wer kümmert sich um die Katze, wenn Sofia weg ist?',
    options: ['Ihr Nachbar.', 'Ihre Mutter.', 'Niemand.'],
    answer: 0,
    explanation: l('„Um meine Katze kümmert sich dann mein Nachbar.“', '„Um meine Katze kümmert sich dann mein Nachbar.“', '„mein Nachbar“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-warten',
    type: 'listening_choice',
    topic: 'prepositions',
    concept: 'vp-warten',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich warte schon eine halbe Stunde auf den Techniker.',
    question: l('Who is the person waiting for?', 'Kişi kimi bekliyor?', 'Auf wen wartet die Person?'),
    options: ['den Techniker', 'den Bus', 'die Post'],
    answer: 0,
    explanation: l('„auf den Techniker“', '„auf den Techniker“', '„auf den Techniker“'),
  },
  {
    id: 'listen-freut',
    type: 'listening_choice',
    topic: 'prepositions',
    concept: 'freuen-auf-ueber',
    skill: 'listening',
    difficulty: 2,
    audio: 'Meine Tochter freut sich so auf ihren Geburtstag nächste Woche.',
    question: l('Has the birthday happened yet?', 'Doğum günü oldu mu?', 'War der Geburtstag schon?'),
    options: ['Nein, er kommt noch.', 'Ja, gestern.'],
    answer: 0,
    explanation: l('freuen auf + nächste Woche → future.', 'freuen auf + nächste Woche → gelecek.', 'auf → Zukunft.'),
  },
  {
    id: 'listen-sprechen',
    type: 'listening_choice',
    topic: 'prepositions',
    concept: 'vp-sprechen',
    skill: 'listening',
    difficulty: 2,
    audio: 'In der Pause sprechen wir meistens über unsere Kinder.',
    question: l('What do they talk about?', 'Ne hakkında konuşuyorlar?', 'Worüber sprechen sie?'),
    options: ['über die Kinder', 'über die Arbeit', 'über das Wetter'],
    answer: 0,
    explanation: l('„über unsere Kinder“', '„über unsere Kinder“', '„über unsere Kinder“'),
  },
  {
    id: 'listen-aerger',
    type: 'listening_choice',
    topic: 'prepositions',
    concept: 'vp-aergern',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich ärgere mich total über meinen Nachbarn. Er macht jede Nacht laute Musik.',
    question: l('Why is the person annoyed?', 'Kişi neden sinirli?', 'Warum ärgert sich die Person?'),
    options: ['🎵 laute Musik', '🐕 ein Hund', '🚗 ein Auto'],
    answer: 0,
    explanation: l('„laute Musik“', '„laute Musik“', '„laute Musik“'),
  },

  ...prepDrills(),
]

export const UNIT_A2_11_VERBEN_PRAEPOSITIONEN: CourseUnit = {
  level: 'A2',
  number: 11,
  slug: 'verben-praepositionen',
  titleDe: 'Ich warte auf dich',
  title: l('I’m waiting for you', 'Seni bekliyorum', 'Ich warte auf dich'),
  goal: l(
    'By the end of this unit you can talk about feelings, interests and dreams with verbs + prepositions (warten auf, sich freuen auf/über, sich interessieren für) and ask with Worauf? / Auf wen?',
    'Bu ünitenin sonunda duygularını, ilgi alanlarını ve hayallerini fiil + edatlarla (warten auf, sich freuen auf/über, sich interessieren für) anlatabilir ve Worauf? / Auf wen? ile soru sorabilirsin.',
    'Am Ende dieser Einheit sprichst du über Gefühle und Interessen mit Verben mit Präpositionen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'prepositions', label: l('Verb + preposition', 'Fiil + edat', 'Verb + Präposition') },
    { key: 'cases', label: l('Akkusativ or Dativ?', 'Akkusativ mı Dativ mi?', 'Akkusativ oder Dativ?') },
    { key: 'wo-da', label: l('Worauf? – Darauf.', 'Worauf? – Darauf.', 'Worauf? – Darauf.') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Verbs that always come with a fixed preposition.', 'Her zaman sabit bir edatla gelen fiiller.', 'Verben mit fester Präposition.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Learn verb + preposition + case together', 'Fiili, edatı ve hali birlikte öğren', 'Verb + Präposition + Kasus zusammen lernen'),
          body: l(
            'Many verbs have a fixed preposition – often different from English or Turkish. Learn them as a unit: warten auf + Akk. (not „für“!).',
            'Birçok fiilin sabit bir edatı vardır – çoğu zaman İngilizce ya da Türkçeden farklı. Onları bir bütün olarak öğren: warten auf + Akk. („für“ değil!).',
            'Als Einheit lernen.'
          ),
          table: {
            head: [l('Verb', 'Fiil', 'Verb'), l('+ Akkusativ', '+ Akkusativ', '+ Akkusativ'), l('Verb', 'Fiil', 'Verb'), l('+ Dativ', '+ Dativ', '+ Dativ')],
            rows: [
              ['warten', 'auf', 'träumen', 'von'],
              ['sich freuen', 'auf / über', 'Angst haben', 'vor'],
              ['sich interessieren', 'für', 'sprechen', 'mit (Person)'],
              ['denken', 'an', 'fragen', 'nach'],
              ['sich kümmern', 'um', 'teilnehmen', 'an'],
            ],
          },
        },
        {
          title: l('Questions and answers: things vs. people', 'Sorular ve cevaplar: şeyler ve kişiler', 'Fragen: Sachen und Personen'),
          body: l(
            'Things: wo(r) + preposition: Worauf wartest du? → Darauf. Wofür interessierst du dich? → Dafür. (r before a vowel). People: preposition + wen/wem: Auf wen wartest du? → Auf ihn.',
            'Şeyler: wo(r) + edat: Worauf wartest du? → Darauf. Wofür interessierst du dich? → Dafür. (sesli harften önce r). Kişiler: edat + wen/wem: Auf wen wartest du? → Auf ihn.',
            'Sachen: worauf/darauf · Personen: auf wen/auf ihn.'
          ),
          examples: [
            { de: '**Worauf** wartest du? – Auf den Bus. Ich warte schon lange **darauf**.', translation: l('What are you waiting for? – The bus. I’ve been waiting for it for a long time.', 'Neyi bekliyorsun? – Otobüsü. Uzun zamandır onu bekliyorum.', '') },
            { de: '**Auf wen** wartest du? – Auf Ben. Ich warte **auf ihn**.', translation: l('Who are you waiting for? – For Ben. I’m waiting for him.', 'Kimi bekliyorsun? – Ben’i. Onu bekliyorum.', '') },
          ],
        },
        {
          title: l('sich freuen auf or über?', 'sich freuen auf mu über mu?', 'sich freuen auf oder über?'),
          body: l('auf → something in the future. über → something that is happening now or has happened.', 'auf → gelecekteki bir şey. über → şu an olan ya da olmuş bir şey.', 'auf: Zukunft · über: jetzt/vorbei.'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('At the bus stop, two neighbours chat.', 'Otobüs durağında iki komşu sohbet ediyor.', 'An der Bushaltestelle.'),
      dialogue: [
        { speaker: 'Frau Berg', de: 'Guten Morgen! **Warten** Sie auch **auf** den 12er?', translation: l('Good morning! Are you waiting for the number 12 too?', 'Günaydın! Siz de 12 numarayı mı bekliyorsunuz?', '') },
        { speaker: 'Herr Demir', de: 'Ja, schon zehn Minuten. Ich **ärgere mich** jeden Tag **über** die Verspätungen.', translation: l('Yes, for ten minutes already. I’m annoyed about the delays every day.', 'Evet, on dakikadır. Her gün gecikmelere sinirleniyorum.', '') },
        { speaker: 'Frau Berg', de: 'Ich auch. Aber heute **freue** ich **mich über** die Sonne!', translation: l('Me too. But today I’m happy about the sunshine!', 'Ben de. Ama bugün güneşe seviniyorum!', '') },
        { speaker: 'Herr Demir', de: 'Stimmt. Und ich **freue mich auf** das Wochenende – meine Tochter kommt zu Besuch.', translation: l('True. And I’m looking forward to the weekend – my daughter is coming to visit.', 'Doğru. Ben de hafta sonunu dört gözle bekliyorum – kızım ziyarete geliyor.', '') },
        { speaker: 'Frau Berg', de: 'Wie schön! **Wer kümmert sich** dann **um** Ihren Hund?', translation: l('How nice! Who’ll take care of your dog then?', 'Ne güzel! O zaman köpeğinizle kim ilgilenecek?', '') },
        { speaker: 'Herr Demir', de: 'Meine Tochter! Sie **interessiert sich** sehr **für** Tiere. Ah, da kommt der Bus!', translation: l('My daughter! She’s very interested in animals. Ah, here comes the bus!', 'Kızım! Hayvanlarla çok ilgileniyor. Ah, otobüs geliyor!', '') },
      ],
      examples: [
        { de: 'Ich **warte auf** den Bus.', translation: l('I’m waiting for the bus.', 'Otobüsü bekliyorum.', '') },
        { de: 'Wir **freuen uns auf** die Ferien.', translation: l('We’re looking forward to the holidays.', 'Tatili dört gözle bekliyoruz.', '') },
        { de: 'Sie **freut sich über** die Blumen.', translation: l('She’s happy about the flowers.', 'Çiçeklere seviniyor.', '') },
        { de: 'Er **interessiert sich für** Geschichte.', translation: l('He’s interested in history.', 'Tarihle ilgileniyor.', '') },
        { de: 'Ich **denke an** dich.', translation: l('I’m thinking of you.', 'Seni düşünüyorum.', '') },
        { de: 'Sie **träumt von** einem Haus am Meer.', translation: l('She dreams of a house by the sea.', 'Deniz kenarında bir ev hayal ediyor.', '') },
        { de: '**Worauf** wartest du? – **Darauf**, dass du fertig bist!', translation: l('What are you waiting for? – For you to be ready!', 'Neyi bekliyorsun? – Senin hazır olmanı!', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which preposition goes with which verb?', 'Hangi edat hangi fiille gider?', 'Welche Präposition passt zu welchem Verb?'),
      exercises: ['match-verbs', 'vp-warten', 'vp-interessieren', 'mc-auf-ueber', 'sort-auf-ueber', 'select-akk', 'tf-worauf', 'image-angst', 'vp-denken'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about feelings and interests.', 'Duygular ve ilgi alanlarından bahset.', 'Sprich über Gefühle und Interessen.'),
      exercises: [
        'fill-fuer',
        'fill-darauf',
        'fill-wovon',
        'build-warten',
        'build-kuemmern',
        'build-denke',
        'fix-warten-fuer',
        'fix-interessiere',
        'fix-angst',
        'tr-freue',
        'tr-sprechen',
        'dialog-worauf',
        'dialog-wen',
        'ordering-frage',
        'vp-traeumen',
        'vp-angst',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Sofia’s profile on a language-exchange website.', 'Sofia’nın bir dil değişim sitesindeki profili.', 'Sofias Profil auf einer Tandem-Website.'),
      passage: [
        'Hallo! Ich bin Sofia, 27, aus Mailand. **Ich interessiere mich für** Fotografie und Kochen.',
        '**Ich träume von** einer Reise nach Japan – leider **habe** ich ein bisschen **Angst vor** dem Fliegen!',
        'Im Moment **denke** ich oft **an** meine Zukunft: Ich möchte in Deutschland arbeiten. Deshalb suche ich einen Tandempartner.',
        'Im August fahre ich zwei Wochen nach Berlin. **Um** meine Katze **kümmert sich** dann mein Nachbar. Ich **freue mich auf** deine Nachricht!',
      ],
      glossary: [
        { de: 'der Tandempartner', note: l('language exchange partner', 'dil değişim partneri', 'Partner zum Sprachenlernen') },
        { de: 'im Moment', note: l('at the moment', 'şu anda', 'jetzt') },
        { de: 'die Nachricht', note: l('message', 'mesaj', 'Mitteilung') },
      ],
      exercises: ['read-traum', 'read-interesse', 'read-angst', 'read-katze'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for the verb and its preposition.', 'Fiile ve edatına kulak ver.', 'Hör auf Verb und Präposition.'),
      exercises: ['listen-warten', 'listen-freut', 'listen-sprechen', 'listen-aerger'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Introduce yourself for a language exchange: interests, dreams, fears.', 'Bir dil değişimi için kendini tanıt: ilgi alanları, hayaller, korkular.', 'Stell dich für ein Tandem vor.'),
      points: [
        l('„Ich interessiere mich für …“', '„Ich interessiere mich für …“', 'Interessen'),
        l('„Ich träume von …“', '„Ich träume von …“', 'Träume'),
        l('„Ich habe (keine) Angst vor …“', '„Ich habe (keine) Angst vor …“', 'Ängste'),
        l('„Ich freue mich auf …“', '„Ich freue mich auf …“', 'Vorfreude'),
      ],
      model: [
        'Ich heiße Ali und interessiere mich für Musik und Geschichte.',
        'Ich träume von einer Reise durch Südamerika.',
        'Ich habe ein bisschen Angst vor großen Hunden.',
        'Im Moment freue ich mich auf den Sommer.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write your own profile for a language-exchange website (at least 5 sentences).',
        'Bir dil değişim sitesi için kendi profilini yaz (en az 5 cümle).',
        'Schreib dein Tandem-Profil (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('sich interessieren für', 'sich interessieren für', 'sich interessieren für'), pattern: 'interessiere mich für' },
        { label: l('sich freuen auf / über', 'sich freuen auf / über', 'sich freuen auf/über'), pattern: 'freue mich (sehr |schon )?(auf|über)' },
        { label: l('Another verb + preposition (träumen von, Angst vor, denken an …)', 'Başka bir fiil + edat (träumen von, Angst vor, denken an …)', 'Noch ein Verb mit Präposition'), pattern: '(träume von|Angst vor|denke (oft |viel )?an|warte auf|kümmere mich um|spreche (gern )?über)' },
      ],
      model: [
        'Hallo, ich bin Mehmet und komme aus Ankara.',
        'Ich interessiere mich für Fotografie und Fußball.',
        'Ich träume von einem eigenen Restaurant.',
        'Ich suche einen Tandempartner, weil ich mehr sprechen möchte.',
        'Ich freue mich auf deine Nachricht!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Which preposition? – 60 seconds.', 'Hangi edat? – 60 saniye.', 'Welche Präposition? – 60 Sekunden.'),
      seconds: 60,
      pool: [...PREP_DRILLS.map(([id]) => `vp-${id}`), 'mc-auf-ueber'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('warten auf, sich interessieren für, denken an, sich kümmern um (+ Akk.)', 'warten auf, sich interessieren für, denken an, sich kümmern um (+ Akk.)', '+ Akkusativ'),
      l('träumen von, Angst haben vor (+ Dat.)', 'träumen von, Angst haben vor (+ Dat.)', '+ Dativ'),
      l('sich freuen auf (future) / über (now)', 'sich freuen auf (gelecek) / über (şimdi)', 'auf / über'),
      l('Worauf? – Darauf. · Auf wen? – Auf ihn.', 'Worauf? – Darauf. · Auf wen? – Auf ihn.', 'Worauf? / Auf wen?'),
    ],
    mistakes: [
      { wrong: 'Ich warte für den Bus.', right: 'Ich warte auf den Bus.', note: l('warten auf.', 'warten auf.', 'warten auf.') },
      { wrong: 'Ich interessiere mich an Musik.', right: 'Ich interessiere mich für Musik.', note: l('sich interessieren für.', 'sich interessieren für.', 'für.') },
      { wrong: 'Ich freue mich auf das Geschenk (gerade bekommen).', right: 'Ich freue mich über das Geschenk.', note: l('Already here → über.', 'Zaten burada → über.', 'über.') },
      { wrong: 'Auf was wartest du?', right: 'Worauf wartest du?', note: l('Things → wor- + preposition.', 'Şeyler → wor- + edat.', 'Worauf?') },
    ],
  },
}
