import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'das Bürgeramt', emoji: '🏛️', translation: l('citizens’ office', 'nüfus müdürlüğü / belediye hizmet bürosu', 'Amt für Anmeldung, Ausweis …'), example: 'Ich muss zum Bürgeramt.' },
  { word: 'sich anmelden', emoji: '📝', translation: l('to register (address)', '(adres) kaydı yaptırmak', 'die Adresse melden'), example: 'Nach dem Umzug muss man sich anmelden.' },
  { word: 'das Formular', emoji: '📋', translation: l('form', 'form', 'Papier zum Ausfüllen'), example: 'Bitte füllen Sie das Formular aus.' },
  { word: 'ausfüllen', emoji: '✍️', translation: l('to fill in', 'doldurmak', 'Formular schreiben'), example: 'Ich fülle das Formular aus.' },
  { word: 'unterschreiben', emoji: '🖊️', translation: l('to sign', 'imzalamak', 'den Namen schreiben'), example: 'Unterschreiben Sie bitte hier.' },
  { word: 'der Ausweis / Reisepass', emoji: '🪪', translation: l('ID card / passport', 'kimlik / pasaport', 'Dokument mit Foto'), example: 'Haben Sie Ihren Ausweis dabei?' },
  { word: 'die Unterlagen', emoji: '🗂️', translation: l('documents', 'belgeler', 'Papiere'), example: 'Welche Unterlagen brauche ich?' },
  { word: 'einen Termin vereinbaren', emoji: '📅', translation: l('to make an appointment', 'randevu almak', 'einen Termin machen'), example: 'Sie müssen online einen Termin vereinbaren.' },
  { word: 'die Wartenummer', emoji: '🔢', translation: l('queue number', 'sıra numarası', 'Nummer zum Warten'), example: 'Ziehen Sie bitte eine Wartenummer.' },
  { word: 'das Konto', emoji: '🏦', translation: l('bank account', 'banka hesabı', 'Bankkonto'), example: 'Ich möchte ein Konto eröffnen.' },
  { word: 'das Paket', emoji: '📦', translation: l('parcel', 'koli', 'Päckchen'), example: 'Ich möchte ein Paket in die Türkei schicken.' },
  { word: 'man muss …', emoji: '☝️', translation: l('you have to … (in general)', '… gerekir (genel)', 'allgemeine Regel'), example: 'Man muss eine Nummer ziehen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Amt', gender: 'n', plural: 'die Ämter', translation: l('office (public)', 'resmî daire', 'Amt') },
  { word: 'Formular', gender: 'n', plural: 'die Formulare', translation: l('form', 'form', 'Formular') },
  { word: 'Ausweis', gender: 'm', plural: 'die Ausweise', translation: l('ID card', 'kimlik', 'Ausweis') },
  { word: 'Termin', gender: 'm', plural: 'die Termine', translation: l('appointment', 'randevu', 'Termin') },
  { word: 'Unterschrift', gender: 'f', plural: 'die Unterschriften', translation: l('signature', 'imza', 'Unterschrift') },
  { word: 'Geburtsdatum', gender: 'n', translation: l('date of birth', 'doğum tarihi', 'Geburtsdatum') },
  { word: 'Staatsangehörigkeit', gender: 'f', translation: l('nationality', 'uyruk', 'Staatsangehörigkeit') },
  { word: 'Mietvertrag', gender: 'm', plural: 'die Mietverträge', translation: l('rental contract', 'kira sözleşmesi', 'Mietvertrag') },
  { word: 'Konto', gender: 'n', plural: 'die Konten', translation: l('account', 'hesap', 'Konto') },
  { word: 'Paket', gender: 'n', plural: 'die Pakete', translation: l('parcel', 'koli', 'Paket') },
]

/** [id, form field, value] */
const FORM: [string, string, string][] = [
  ['vorname', 'Vorname', 'Ayşe'],
  ['nachname', 'Nachname / Familienname', 'Yılmaz'],
  ['geburtsdatum', 'Geburtsdatum', '14.03.1992'],
  ['geburtsort', 'Geburtsort', 'Ankara'],
  ['staat', 'Staatsangehörigkeit', 'türkisch'],
  ['familienstand', 'Familienstand', 'verheiratet'],
]

function formDrills(): Exercise[] {
  return FORM.map(([id, field, value], i) => {
    const others = FORM.filter(([o]) => o !== id)
    const options = [value, others[i % others.length][2], others[(i + 2) % others.length][2]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `form-${id}`,
      type: 'multiple_choice' as const,
      topic: 'formular',
      concept: 'form-fields',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      visual: ['🪪 Ayşe Yılmaz · * 14.03.1992 in Ankara · 🇹🇷 · 💍'],
      prompt: `${field}: ___`,
      options: ordered,
      answer: ordered.indexOf(value),
      explanation: l(`${field} → ${value}.`, `${field} → ${value}.`, `${field}: ${value}.`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-wo',
    type: 'matching',
    topic: 'behoerden',
    concept: 'which-office',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Where do you go?', 'Nereye gidersin?', 'Wohin gehst du?'),
    pairs: [
      { left: 'Ich bin umgezogen.', right: 'zum Bürgeramt' },
      { left: 'Ich möchte ein Konto eröffnen.', right: 'zur Bank' },
      { left: 'Ich möchte ein Paket schicken.', right: 'zur Post' },
      { left: 'Ich brauche eine Arbeitserlaubnis.', right: 'zur Ausländerbehörde' },
    ],
    explanation: l('zum/zur + office. Bürgeramt: address, ID. Ausländerbehörde: visa, residence permit.', 'zum/zur + daire. Bürgeramt: adres, kimlik. Ausländerbehörde: vize, oturum izni.', 'zum Bürgeramt, zur Bank, zur Post.'),
  },
  {
    id: 'mc-man',
    type: 'multiple_choice',
    topic: 'man-muss',
    concept: 'man-verb',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Auf dem Amt ___ man oft lange warten.',
    options: ['muss', 'müssen', 'musst'],
    answer: 0,
    explanation: l('man = people in general; verb like er/sie/es: man muss, man kann, man darf.', 'man = genel olarak insanlar; fiil er/sie/es gibi: man muss, man kann, man darf.', 'man muss.'),
    examples: ['Auf dem Amt **muss man** oft lange warten.'],
    practice: ['fill-man'],
  },
  {
    id: 'sort-unterlagen',
    type: 'categorize',
    topic: 'formular',
    concept: 'documents',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('What do you need to register your address (Anmeldung)?', 'Adres kaydı (Anmeldung) için neye ihtiyacın var?', 'Was brauchst du für die Anmeldung?'),
    categories: ['brauche ich', 'brauche ich nicht'],
    items: [
      { text: 'Ausweis oder Reisepass', category: 0 },
      { text: 'Wohnungsgeberbestätigung', category: 0 },
      { text: 'Anmeldeformular', category: 0 },
      { text: 'Fahrkarte', category: 1 },
      { text: 'Schulzeugnis', category: 1 },
      { text: 'Kochbuch', category: 1 },
    ],
    explanation: l('For the Anmeldung: ID/passport, the landlord’s confirmation and the form.', 'Anmeldung için: kimlik/pasaport, ev sahibinin onayı ve form.', 'Ausweis, Bestätigung, Formular.'),
  },
  {
    id: 'tf-termin',
    type: 'true_false',
    topic: 'termin',
    concept: 'appointment',
    skill: 'reading',
    difficulty: 1,
    statement: 'In vielen deutschen Ämtern braucht man vorher einen Termin.',
    answer: true,
    explanation: l('Many offices only work with appointments (online or by phone).', 'Birçok daire yalnızca randevuyla çalışır (internetten ya da telefonla).', 'Termin vorher.'),
  },
  {
    id: 'select-man',
    type: 'multiple_select',
    topic: 'man-muss',
    concept: 'man-verb',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche Sätze sind richtig?'),
    options: ['Hier darf man nicht rauchen.', 'Hier dürfen man nicht rauchen.', 'Man kann online einen Termin machen.', 'Man muss das Formular unterschreiben.', 'Man müssen warten.'],
    answers: [0, 2, 3],
    explanation: l('man + singular verb: darf, kann, muss.', 'man + tekil fiil: darf, kann, muss.', 'man darf / kann / muss.'),
  },
  {
    id: 'image-unterschrift',
    type: 'image_choice',
    topic: 'formular',
    concept: 'form-actions',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Bitte unterschreiben Sie hier.',
    options: [
      { emoji: '🖊️', label: 'unterschreiben' },
      { emoji: '📷', label: 'fotografieren' },
      { emoji: '💶', label: 'bezahlen' },
      { emoji: '📞', label: 'anrufen' },
    ],
    answer: 0,
    explanation: l('unterschreiben = sign 🖊️.', 'unterschreiben = imzalamak 🖊️.', 'unterschreiben.'),
  },

  // --- Simulation: Bürgeramt -------------------------------------------
  {
    id: 'dialog-anmelden',
    type: 'dialogue',
    topic: 'termin',
    concept: 'at-the-office',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Beamtin', de: 'Guten Tag. Was kann ich für Sie tun?' }],
    options: ['Guten Tag, ich möchte mich anmelden. Ich bin letzte Woche umgezogen.', 'Ich will Amt.', 'Ich bin anmelden umgezogen.'],
    answer: 0,
    explanation: l('Say what you need + the reason.', 'Neye ihtiyacın olduğunu + sebebini söyle.', 'Anliegen + Grund.'),
  },
  {
    id: 'dialog-unterlagen',
    type: 'dialogue',
    topic: 'termin',
    concept: 'at-the-office',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Beamtin', de: 'Haben Sie Ihren Ausweis und die Wohnungsgeberbestätigung dabei?' }],
    options: ['Ja, hier bitte. Und das Formular habe ich schon ausgefüllt.', 'Ja, ich habe dabei.', 'Nein, ich bin Ausweis.'],
    answer: 0,
    explanation: l('Hand over the documents politely: Ja, hier bitte.', 'Belgeleri kibarca ver: Ja, hier bitte.', 'Ja, hier bitte.'),
  },
  {
    id: 'dialog-unterschreiben',
    type: 'dialogue',
    topic: 'formular',
    concept: 'form-actions',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Beamtin', de: 'Danke. Bitte unterschreiben Sie hier unten.' }],
    options: ['Gern. Bekomme ich auch eine Bestätigung?', 'Ich schreibe unter.', 'Wo ist hier?'],
    answer: 0,
    explanation: l('Ask for a confirmation – you often need it later.', 'Bir onay belgesi iste – sonradan çoğu zaman gerekir.', 'Bestätigung?'),
  },
  {
    id: 'fill-ausfuellen',
    type: 'fill_blank',
    topic: 'formular',
    concept: 'form-actions',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Bitte füllen Sie dieses Formular ___.',
    accepted: ['aus'],
    base: 'aus|füllen',
    explanation: l('aus|füllen is separable: füllen … aus.', 'aus|füllen ayrılabilen bir fiildir: füllen … aus.', 'füllen … aus.'),
    examples: ['Bitte **füllen** Sie dieses Formular **aus**.'],
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-man',
    type: 'fill_blank',
    topic: 'man-muss',
    concept: 'man-verb',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Im Bürgeramt ___ man eine Wartenummer ziehen.',
    accepted: ['muss'],
    base: 'müssen',
    explanation: l('man → muss (like er).', 'man → muss (er gibi).', 'man muss.'),
    examples: ['Im Bürgeramt **muss man** eine Wartenummer ziehen.'],
  },
  {
    id: 'fill-zum',
    type: 'fill_blank',
    topic: 'behoerden',
    concept: 'which-office',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Morgen muss ich ___ Bürgeramt.',
    accepted: ['zum'],
    base: 'zu + dem',
    explanation: l('das Bürgeramt → zu dem → zum.', 'das Bürgeramt → zu dem → zum.', 'zum Bürgeramt.'),
    examples: ['Morgen muss ich **zum** Bürgeramt.'],
  },
  {
    id: 'build-termin',
    type: 'sentence_builder',
    topic: 'termin',
    concept: 'appointment',
    skill: 'grammar',
    difficulty: 2,
    chips: ['vereinbaren', 'einen Termin', 'Man', 'online', 'kann'],
    answers: [['Man', 'kann', 'online', 'einen Termin', 'vereinbaren']],
    translation: l('You can make an appointment online.', 'İnternetten randevu alınabilir.', 'Man kann online einen Termin vereinbaren.'),
    explanation: l('man + modal (2) + infinitive (end).', 'man + modal (2) + mastar (son).', 'Man kann … vereinbaren.'),
    examples: ['**Man kann** online einen Termin **vereinbaren**.'],
  },
  {
    id: 'build-konto',
    type: 'sentence_builder',
    topic: 'behoerden',
    concept: 'bank',
    skill: 'grammar',
    difficulty: 2,
    chips: ['eröffnen', 'ein Konto', 'gern', 'Ich', 'würde'],
    answers: [['Ich', 'würde', 'gern', 'ein Konto', 'eröffnen']],
    translation: l('I’d like to open an account.', 'Bir hesap açmak istiyorum.', 'Ich würde gern ein Konto eröffnen.'),
    explanation: l('Polite: würde gern + infinitive.', 'Kibar: würde gern + mastar.', 'würde gern … eröffnen.'),
    examples: ['Ich **würde gern** ein Konto **eröffnen**.'],
  },
  {
    id: 'build-paket',
    type: 'sentence_builder',
    topic: 'behoerden',
    concept: 'post',
    skill: 'grammar',
    difficulty: 2,
    chips: ['in die Türkei', 'kostet', 'ein Paket', 'Was'],
    answers: [['Was', 'kostet', 'ein Paket', 'in die Türkei']],
    end: '?',
    translation: l('How much is a parcel to Turkey?', 'Türkiye’ye bir koli ne kadar?', 'Was kostet ein Paket in die Türkei?'),
    explanation: l('W-question: Was kostet …?', 'W-sorusu: Was kostet …?', 'Was kostet …?'),
    examples: ['**Was kostet** ein Paket in die Türkei?'],
  },
  {
    id: 'fix-man-muessen',
    type: 'error_correction',
    topic: 'man-muss',
    concept: 'man-verb',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Man müssen hier eine Nummer ziehen.',
    accepted: ['Man muss hier eine Nummer ziehen.'],
    explanation: l('man → muss (singular).', 'man → muss (tekil).', 'man muss.'),
    examples: ['**Man muss** hier eine Nummer ziehen.'],
  },
  {
    id: 'fix-unterschreiben',
    type: 'error_correction',
    topic: 'formular',
    concept: 'form-actions',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich schreibe das Formular unter.',
    accepted: ['Ich unterschreibe das Formular.'],
    explanation: l('unterschreiben is NOT separable: ich unterschreibe.', 'unterschreiben ayrılabilen DEĞİLDİR: ich unterschreibe.', 'ich unterschreibe.'),
    examples: ['Ich **unterschreibe** das Formular.'],
  },
  {
    id: 'fix-anmelden',
    type: 'error_correction',
    topic: 'formular',
    concept: 'sich-anmelden',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich möchte anmelden.',
    accepted: ['Ich möchte mich anmelden.'],
    explanation: l('sich anmelden is reflexive: Ich möchte mich anmelden.', 'sich anmelden dönüşlüdür: Ich möchte mich anmelden.', 'mich anmelden.'),
    examples: ['Ich möchte **mich** anmelden.'],
  },
  {
    id: 'tr-unterlagen',
    type: 'translation',
    topic: 'formular',
    concept: 'documents',
    skill: 'writing',
    difficulty: 2,
    source: l('Which documents do I need?', 'Hangi belgelere ihtiyacım var?', 'Which documents do I need?'),
    accepted: ['Welche Unterlagen brauche ich?', 'Welche Dokumente brauche ich?'],
    explanation: l('Welche Unterlagen brauche ich?', 'Welche Unterlagen brauche ich?', 'Welche Unterlagen …?'),
    examples: ['**Welche Unterlagen** brauche ich?'],
  },
  {
    id: 'tr-termin',
    type: 'translation',
    topic: 'termin',
    concept: 'appointment',
    skill: 'writing',
    difficulty: 2,
    source: l('I have an appointment at 10 o’clock.', 'Saat 10’da randevum var.', 'I have an appointment at 10 o’clock.'),
    accepted: ['Ich habe um 10 Uhr einen Termin.', 'Ich habe einen Termin um 10 Uhr.', 'Ich habe um zehn Uhr einen Termin.', 'Ich habe einen Termin um zehn Uhr.'],
    explanation: l('einen Termin haben (Akkusativ).', 'einen Termin haben (Akkusativ).', 'einen Termin.'),
    examples: ['Ich habe um 10 Uhr **einen Termin**.'],
  },
  {
    id: 'ordering-amt',
    type: 'ordering',
    topic: 'termin',
    concept: 'office-steps',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the steps at the Bürgeramt in order.', 'Bürgeramt’taki adımları sıraya koy.', 'Bring die Schritte im Bürgeramt in Ordnung.'),
    items: ['Formular unterschreiben', 'online einen Termin vereinbaren', 'die Bestätigung mitnehmen', 'Unterlagen zeigen'],
    answer: ['online einen Termin vereinbaren', 'Unterlagen zeigen', 'Formular unterschreiben', 'die Bestätigung mitnehmen'],
    explanation: l('appointment → documents → sign → confirmation.', 'randevu → belgeler → imza → onay belgesi.', 'Termin → Unterlagen → Unterschrift → Bestätigung.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-frist',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Bis wann muss man sich nach dem Umzug anmelden?',
    options: ['Innerhalb von zwei Wochen.', 'Innerhalb von zwei Monaten.', 'Wann man will.'],
    answer: 0,
    explanation: l('„innerhalb von 14 Tagen“', '„innerhalb von 14 Tagen“', '14 Tage.'),
  },
  {
    id: 'read-mitbringen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was muss man mitbringen?',
    options: ['Ausweis, Bestätigung vom Vermieter und Formular.', 'Nur ein Foto.', 'Geld und Mietvertrag.'],
    answer: 0,
    explanation: l('„Bringen Sie Ihren Ausweis, die Wohnungsgeberbestätigung und das ausgefüllte Formular mit.“', '„Bringen Sie Ihren Ausweis, die Wohnungsgeberbestätigung und das ausgefüllte Formular mit.“', 'Ausweis, Bestätigung, Formular.'),
  },
  {
    id: 'read-kosten',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 1,
    statement: 'Die Anmeldung kostet nichts.',
    answer: true,
    explanation: l('„Die Anmeldung ist kostenlos.“', '„Die Anmeldung ist kostenlos.“', 'kostenlos.'),
  },
  {
    id: 'read-termin',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-info',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie bekommt man einen Termin?',
    options: ['Online oder telefonisch.', 'Nur persönlich.', 'Per Post.'],
    answer: 0,
    explanation: l('„Termine bekommen Sie online oder unter der Telefonnummer 115.“', '„Termine bekommen Sie online oder unter der Telefonnummer 115.“', 'online / Telefon.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-nummer',
    type: 'listening_choice',
    topic: 'termin',
    concept: 'queue',
    skill: 'listening',
    difficulty: 1,
    audio: 'Wartenummer zweihundertvierzehn bitte zu Schalter drei.',
    question: l('Which number and counter?', 'Hangi numara ve gişe?', 'Welche Nummer, welcher Schalter?'),
    options: ['214 → 3', '240 → 3', '214 → 13'],
    answer: 0,
    explanation: l('zweihundertvierzehn = 214, Schalter drei.', 'zweihundertvierzehn = 214, üç numaralı gişe.', '214, Schalter 3.'),
  },
  {
    id: 'listen-fehlt',
    type: 'listening_choice',
    topic: 'formular',
    concept: 'documents',
    skill: 'listening',
    difficulty: 2,
    audio: 'Leider fehlt hier noch die Unterschrift von Ihrem Vermieter.',
    question: l('What is missing?', 'Ne eksik?', 'Was fehlt?'),
    options: ['the landlord’s signature', 'the passport', 'a photo'],
    answer: 0,
    explanation: l('„die Unterschrift von Ihrem Vermieter“', '„die Unterschrift von Ihrem Vermieter“', 'Unterschrift.'),
  },
  {
    id: 'listen-post',
    type: 'listening_choice',
    topic: 'behoerden',
    concept: 'post',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ein Paket bis fünf Kilo in die Türkei kostet achtunddreißig Euro neunundneunzig.',
    question: l('How much does it cost?', 'Ne kadar tutuyor?', 'Was kostet es?'),
    options: ['38,99 €', '28,99 €', '38,19 €'],
    answer: 0,
    explanation: l('achtunddreißig Euro neunundneunzig = 38,99 €.', 'achtunddreißig Euro neunundneunzig = 38,99 €.', '38,99 €.'),
  },
  {
    id: 'listen-man',
    type: 'listening_choice',
    topic: 'man-muss',
    concept: 'man-verb',
    skill: 'listening',
    difficulty: 2,
    audio: 'Hier darf man nicht telefonieren. Bitte gehen Sie nach draußen.',
    question: l('What’s not allowed?', 'Ne yasak?', 'Was darf man nicht?'),
    options: ['📵 telefonieren', '🚬 rauchen', '🍔 essen'],
    answer: 0,
    explanation: l('„darf man nicht telefonieren“', '„darf man nicht telefonieren“', 'telefonieren.'),
  },

  ...formDrills(),
]

export const UNIT_A2_22_BEHOERDEN: CourseUnit = {
  level: 'A2',
  number: 22,
  slug: 'behoerden',
  titleDe: 'Auf dem Amt',
  title: l('At the public office', 'Resmî dairede', 'Auf dem Amt'),
  goal: l(
    'By the end of this unit you can register at the Bürgeramt, understand and fill in a form, ask which documents you need, and talk about general rules with „man muss / man kann / man darf“.',
    'Bu ünitenin sonunda Bürgeramt’ta adres kaydı yaptırabilir, bir formu anlayıp doldurabilir, hangi belgelere ihtiyacın olduğunu sorabilir ve „man muss / man kann / man darf“ ile genel kurallardan bahsedebilirsin.',
    'Am Ende dieser Einheit meldest du dich beim Bürgeramt an und füllst Formulare aus.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'behoerden', label: l('Offices, bank, post', 'Daireler, banka, postane', 'Ämter, Bank, Post') },
    { key: 'formular', label: l('Forms & documents', 'Formlar ve belgeler', 'Formulare & Unterlagen') },
    { key: 'termin', label: l('Appointments', 'Randevular', 'Termine') },
    { key: 'man-muss', label: l('man muss / kann / darf', 'man muss / kann / darf', 'man muss / kann / darf') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('German bureaucracy in twelve words.', 'On iki kelimede Alman bürokrasisi.', 'Bürokratie in zwölf Wörtern.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('man = people in general', 'man = genel olarak insanlar', 'man = alle, allgemein'),
          body: l(
            'Rules and procedures use man (one, you, people). The verb is like er/sie/es: man muss, man kann, man darf (nicht), man braucht.',
            'Kurallar ve işlemler man (insan, kişi) ile anlatılır. Fiil er/sie/es gibidir: man muss, man kann, man darf (nicht), man braucht.',
            'man + Verb wie er.'
          ),
          examples: [
            { de: 'Hier **darf man** nicht rauchen.', translation: l('You can’t smoke here.', 'Burada sigara içilmez.', '') },
            { de: 'Nach dem Umzug **muss man** sich anmelden.', translation: l('After moving you have to register.', 'Taşındıktan sonra adres kaydı yaptırmak gerekir.', '') },
          ],
          tip: l('man is NOT der Mann (the man)!', 'man, der Mann (adam) DEĞİLDİR!', 'man ≠ Mann.'),
        },
        {
          title: l('Forms', 'Formlar', 'Formulare'),
          body: l(
            'Vorname (first name), Nachname/Familienname (surname), Geburtsdatum, Geburtsort, Staatsangehörigkeit (nationality), Familienstand (ledig, verheiratet, geschieden), Anschrift (address), Unterschrift (signature).',
            'Vorname (ad), Nachname/Familienname (soyad), Geburtsdatum (doğum tarihi), Geburtsort (doğum yeri), Staatsangehörigkeit (uyruk), Familienstand (bekâr, evli, boşanmış), Anschrift (adres), Unterschrift (imza).',
            'Formularwörter.'
          ),
          table: {
            head: [l('Field', 'Alan', 'Feld'), l('Example', 'Örnek', 'Beispiel')],
            rows: FORM.map(([, f, v]) => [f, v]),
          },
        },
        {
          title: l('Useful verbs', 'Faydalı fiiller', 'Nützliche Verben'),
          body: l(
            'aus|füllen (separable: Ich fülle das Formular aus), unterschreiben (NOT separable: Ich unterschreibe), sich an|melden (Ich melde mich an), einen Termin vereinbaren.',
            'aus|füllen (ayrılabilen: Ich fülle das Formular aus), unterschreiben (ayrılmaz: Ich unterschreibe), sich an|melden (Ich melde mich an), einen Termin vereinbaren.',
            'ausfüllen, unterschreiben, sich anmelden.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Simulation: Ayşe registers her new address at the Bürgeramt.', 'Simülasyon: Ayşe Bürgeramt’ta yeni adresini kaydettiriyor.', 'Simulation: Anmeldung im Bürgeramt.'),
      dialogue: [
        { speaker: 'Beamtin', de: 'Guten Tag. Nummer 214? Bitte setzen Sie sich. Was kann ich für Sie tun?', translation: l('Hello. Number 214? Please sit down. What can I do for you?', 'İyi günler. 214 numara mı? Lütfen oturun. Size nasıl yardımcı olabilirim?', '') },
        { speaker: 'Ayşe', de: 'Ich möchte **mich anmelden**. Ich bin letzte Woche nach Köln umgezogen.', translation: l('I’d like to register. I moved to Cologne last week.', 'Adres kaydı yaptırmak istiyorum. Geçen hafta Köln’e taşındım.', '') },
        { speaker: 'Beamtin', de: 'Gut. Haben Sie Ihren **Ausweis** und die Wohnungsgeberbestätigung dabei?', translation: l('Good. Do you have your ID and the landlord’s confirmation with you?', 'İyi. Kimliğiniz ve ev sahibi onay belgesi yanınızda mı?', '') },
        { speaker: 'Ayşe', de: 'Ja, hier bitte. Das **Formular** habe ich schon **ausgefüllt**.', translation: l('Yes, here you are. I’ve already filled in the form.', 'Evet, buyurun. Formu da zaten doldurdum.', '') },
        { speaker: 'Beamtin', de: 'Prima. Ihr Familienstand ist … verheiratet?', translation: l('Great. Your marital status is … married?', 'Harika. Medeni durumunuz … evli mi?', '') },
        { speaker: 'Ayşe', de: 'Genau. Mein Mann kommt nächsten Monat. **Muss man** sich dann noch einmal anmelden?', translation: l('Exactly. My husband is coming next month. Does one have to register again then?', 'Evet. Eşim gelecek ay geliyor. O zaman bir daha kayıt yaptırmak gerekiyor mu?', '') },
        { speaker: 'Beamtin', de: 'Ja, er muss selbst kommen. **Man kann** online einen Termin vereinbaren. So, bitte hier **unterschreiben**.', translation: l('Yes, he has to come himself. You can make an appointment online. Now, please sign here.', 'Evet, kendisi gelmeli. İnternetten randevu alınabiliyor. Şimdi lütfen buraya imza atın.', '') },
        { speaker: 'Ayşe', de: 'Gern. Und ich bekomme eine Bestätigung, oder?', translation: l('Of course. And I get a confirmation, right?', 'Tabii. Bir onay belgesi alıyorum, değil mi?', '') },
      ],
      examples: [
        { de: 'Ich möchte **mich anmelden**.', translation: l('I’d like to register.', 'Adres kaydı yaptırmak istiyorum.', '') },
        { de: 'Bitte **füllen** Sie das Formular **aus**.', translation: l('Please fill in the form.', 'Lütfen formu doldurun.', '') },
        { de: 'Bitte **unterschreiben** Sie hier.', translation: l('Please sign here.', 'Lütfen buraya imza atın.', '') },
        { de: '**Welche Unterlagen** brauche ich?', translation: l('Which documents do I need?', 'Hangi belgelere ihtiyacım var?', '') },
        { de: '**Man muss** online einen Termin vereinbaren.', translation: l('You have to make an appointment online.', 'İnternetten randevu almak gerekiyor.', '') },
        { de: 'Ich würde gern **ein Konto eröffnen**.', translation: l('I’d like to open an account.', 'Bir hesap açmak istiyorum.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Offices, forms and rules.', 'Daireler, formlar ve kurallar.', 'Ämter, Formulare, Regeln.'),
      exercises: ['match-wo', 'form-vorname', 'form-geburtsdatum', 'form-familienstand', 'mc-man', 'sort-unterlagen', 'tf-termin', 'select-man', 'image-unterschrift'],
    },
    {
      key: 'practice-amt',
      kind: 'practice',
      title: l('Simulation · At the Bürgeramt', 'Simülasyon · Bürgeramt’ta', 'Simulation · Im Bürgeramt'),
      intro: l('You register your new address.', 'Yeni adresini kaydettiriyorsun.', 'Du meldest dich an.'),
      exercises: ['dialog-anmelden', 'dialog-unterlagen', 'fill-ausfuellen', 'dialog-unterschreiben', 'form-nachname', 'form-geburtsort', 'form-staat'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Bank, post and rules.', 'Banka, postane ve kurallar.', 'Bank, Post, Regeln.'),
      exercises: ['fill-man', 'fill-zum', 'build-termin', 'build-konto', 'build-paket', 'fix-man-muessen', 'fix-unterschreiben', 'fix-anmelden', 'tr-unterlagen', 'tr-termin', 'ordering-amt'],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Information from the city’s website.', 'Şehrin internet sitesinden bilgiler.', 'Infos von der Website der Stadt.'),
      passage: [
        '**Anmeldung einer Wohnung** – Wer umzieht, **muss** sich innerhalb von 14 Tagen beim Bürgeramt **anmelden**.',
        'Termine bekommen Sie online oder unter der Telefonnummer 115.',
        'Bringen Sie Ihren **Ausweis** oder Reisepass, die **Wohnungsgeberbestätigung** (vom Vermieter) und das ausgefüllte **Formular** mit.',
        'Die Anmeldung ist kostenlos. Sie bekommen sofort eine **Bestätigung**.',
      ],
      glossary: [
        { de: 'innerhalb von', note: l('within', 'içinde', 'in der Zeit von') },
        { de: 'der Vermieter', note: l('landlord', 'ev sahibi', 'Besitzer der Wohnung') },
        { de: 'kostenlos', note: l('free of charge', 'ücretsiz', 'gratis') },
        { de: 'die Bestätigung', note: l('confirmation', 'onay belgesi', 'Papier als Beweis') },
      ],
      exercises: ['read-frist', 'read-mitbringen', 'read-kosten', 'read-termin'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('At the office, bank and post.', 'Dairede, bankada ve postanede.', 'Amt, Bank, Post.'),
      exercises: ['listen-nummer', 'listen-fehlt', 'listen-post', 'listen-man'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Role play: you want to open a bank account. Talk to the bank clerk.', 'Rol oyunu: banka hesabı açmak istiyorsun. Banka görevlisiyle konuş.', 'Rollenspiel: ein Konto eröffnen.'),
      points: [
        l('Say what you want (Ich würde gern …)', 'Ne istediğini söyle (Ich würde gern …)', 'Anliegen'),
        l('Ask which documents you need', 'Hangi belgelere ihtiyacın olduğunu sor', 'Unterlagen?'),
        l('Ask a question with „Kann man …?“', '„Kann man …?“ ile bir soru sor', 'Kann man …?'),
        l('Give your details: name, date of birth, address', 'Bilgilerini ver: ad, doğum tarihi, adres', 'Daten'),
      ],
      model: [
        'Guten Tag, ich würde gern ein Konto eröffnen.',
        'Welche Unterlagen brauche ich dafür?',
        'Kann man das Konto auch online benutzen?',
        'Ich heiße Ayşe Yılmaz, ich bin am 14. März 1992 geboren und wohne in der Lindenstraße 8.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write an e-mail to the Bürgeramt (at least 4 sentences): ask for an appointment and which documents you need.',
        'Bürgeramt’a bir e-posta yaz (en az 4 cümle): randevu iste ve hangi belgelere ihtiyacın olduğunu sor.',
        'Schreib eine E-Mail an das Bürgeramt (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('Formal greeting', 'Resmî hitap', 'Formelle Anrede'), pattern: 'Sehr geehrte' },
        { label: l('Termin', 'Termin', 'Termin'), pattern: '\\bTermin\\b' },
        { label: l('Unterlagen / Dokumente', 'Unterlagen / Dokumente', 'Unterlagen'), pattern: '(Unterlagen|Dokumente|Papiere)' },
        { label: l('Formal closing', 'Resmî kapanış', 'Formeller Gruß'), pattern: 'Mit freundlichen Grüßen' },
      ],
      model: [
        'Sehr geehrte Damen und Herren, ich bin am 1. Juni nach Köln umgezogen.',
        'Ich möchte mich anmelden und brauche einen Termin.',
        'Können Sie mir sagen, welche Unterlagen ich mitbringen muss?',
        'Vielen Dank im Voraus.',
        'Mit freundlichen Grüßen, Ayşe Yılmaz',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Form fields – 60 seconds.', 'Form alanları – 60 saniye.', 'Formularfelder – 60 Sekunden.'),
      seconds: 60,
      pool: [...FORM.map(([id]) => `form-${id}`), 'mc-man'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Bürgeramt: sich anmelden, Termin, Unterlagen, Ausweis', 'Bürgeramt: sich anmelden, Termin, Unterlagen, Ausweis', 'Bürgeramt'),
      l('Forms: Vorname, Nachname, Geburtsdatum, Familienstand …', 'Formlar: Vorname, Nachname, Geburtsdatum, Familienstand …', 'Formulare'),
      l('ausfüllen (separable) · unterschreiben (not separable)', 'ausfüllen (ayrılabilen) · unterschreiben (ayrılmaz)', 'ausfüllen / unterschreiben'),
      l('man muss / kann / darf', 'man muss / kann / darf', 'man'),
    ],
    mistakes: [
      { wrong: 'Man müssen warten.', right: 'Man muss warten.', note: l('man + singular.', 'man + tekil.', 'man muss.') },
      { wrong: 'Ich schreibe unter.', right: 'Ich unterschreibe.', note: l('Not separable.', 'Ayrılmaz.', 'untrennbar.') },
      { wrong: 'Ich möchte anmelden.', right: 'Ich möchte mich anmelden.', note: l('Reflexive.', 'Dönüşlü.', 'mich.') },
      { wrong: 'Ich muss zu Bürgeramt.', right: 'Ich muss zum Bürgeramt.', note: l('zu + dem = zum.', 'zu + dem = zum.', 'zum.') },
    ],
  },
}
