import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Du solltest …', emoji: '👉', translation: l('You should …', '… -malısın', 'Ratschlag'), example: 'Du solltest mehr Wasser trinken.' },
  { word: 'Sie sollten …', emoji: '🩺', translation: l('You should … (formal)', '… -malısınız', 'Ratschlag (formell)'), example: 'Sie sollten sich ausruhen.' },
  { word: 'An deiner Stelle würde ich …', emoji: '🤔', translation: l('If I were you, I would …', 'Senin yerinde olsam …', 'Ratschlag'), example: 'An deiner Stelle würde ich zum Arzt gehen.' },
  { word: 'Es ist besser, wenn …', emoji: '✅', translation: l('It’s better if …', '… daha iyi olur', 'Ratschlag'), example: 'Es ist besser, wenn du heute zu Hause bleibst.' },
  { word: 'erkältet sein', emoji: '🤧', translation: l('to have a cold', 'nezle olmak', 'Schnupfen, Husten'), example: 'Ich bin seit Montag erkältet.' },
  { word: 'Fieber haben', emoji: '🌡️', translation: l('to have a temperature', 'ateşi olmak', 'hohe Temperatur'), example: 'Das Kind hat 39 Grad Fieber.' },
  { word: 'der Stress', emoji: '😩', translation: l('stress', 'stres', 'Druck'), example: 'Ich habe viel Stress bei der Arbeit.' },
  { word: 'schlecht schlafen', emoji: '😵‍💫', translation: l('to sleep badly', 'kötü uyumak', 'nicht gut schlafen'), example: 'Ich schlafe seit Wochen schlecht.' },
  { word: 'sich bewegen', emoji: '🚶', translation: l('to move, exercise', 'hareket etmek', 'Sport machen, laufen'), example: 'Du solltest dich mehr bewegen.' },
  { word: 'gesund essen', emoji: '🥗', translation: l('to eat healthily', 'sağlıklı beslenmek', 'Obst und Gemüse essen'), example: 'Wir sollten gesünder essen.' },
  { word: 'eine Pause machen', emoji: '⏸️', translation: l('to take a break', 'mola vermek', 'kurz aufhören'), example: 'Mach doch mal eine Pause!' },
  { word: 'Gute Besserung!', emoji: '💐', translation: l('Get well soon!', 'Geçmiş olsun!', 'Wunsch für Kranke'), example: 'Gute Besserung und bis bald!' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Rücken', gender: 'm', translation: l('back', 'sırt', 'Rücken') },
  { word: 'Husten', gender: 'm', translation: l('cough', 'öksürük', 'Husten') },
  { word: 'Halsschmerzen', translation: l('sore throat (plural)', 'boğaz ağrısı (çoğul)', 'Halsschmerzen') },
  { word: 'Tee', gender: 'm', plural: 'die Tees', translation: l('tea', 'çay', 'Tee') },
  { word: 'Medikament', gender: 'n', plural: 'die Medikamente', translation: l('medicine', 'ilaç', 'Medikament') },
  { word: 'Arzt', gender: 'm', plural: 'die Ärzte', translation: l('doctor', 'doktor', 'Arzt') },
  { word: 'Bildschirm', gender: 'm', plural: 'die Bildschirme', translation: l('screen', 'ekran', 'Bildschirm') },
]

/** [id, problem, advice infinitive phrase (…, infinitive), person] */
const ADVICE: [string, string, string, string, 'du' | 'Sie' | 'ihr' | 'er'][] = [
  ['muede', 'Ich bin immer müde.', 'früher ins Bett', 'gehen', 'du'],
  ['ruecken', 'Mein Rücken tut weh.', 'nicht so lange', 'sitzen', 'du'],
  ['husten', 'Ich habe Husten.', 'viel Tee', 'trinken', 'Sie'],
  ['stress', 'Wir haben so viel Stress.', 'öfter eine Pause', 'machen', 'ihr'],
  ['fieber', 'Tom hat hohes Fieber.', 'zum Arzt', 'gehen', 'er'],
]

const SOLLTE: Record<string, string> = { du: 'solltest', Sie: 'sollten', ihr: 'solltet', er: 'sollte' }
const WRONG_SOLLTE: Record<string, [string, string]> = {
  du: ['sollst', 'sollte'],
  Sie: ['sollen', 'solltet'],
  ihr: ['sollt', 'sollten'],
  er: ['solltest', 'soll'],
}

function adviceDrills(): Exercise[] {
  return ADVICE.map(([id, problem, middle, inf, person], i) => {
    const right = SOLLTE[person]
    const options = [right, ...WRONG_SOLLTE[person]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const subject = person === 'er' ? 'Er' : person === 'Sie' ? 'Sie' : person === 'ihr' ? 'Ihr' : 'Du'
    const sentence = `${subject} ___ ${middle} ${inf}.`
    return {
      id: `rat-${id}`,
      type: 'multiple_choice' as const,
      topic: 'sollte',
      concept: `sollte-${person}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: `„${problem}“ – ${sentence}`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Advice: sollte + infinitive. ${person} → ${right}.`,
        `Tavsiye: sollte + mastar. ${person} → ${right}.`,
        `Ratschlag: ${person} ${right} … ${inf}.`
      ),
      examples: [`${subject} **${right}** ${middle} **${inf}**.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-problem',
    type: 'matching',
    topic: 'probleme',
    concept: 'problem-advice',
    skill: 'reading',
    difficulty: 1,
    instructions: l('Match the problem and the advice.', 'Sorunu tavsiyeyle eşleştir.', 'Ordne Problem und Ratschlag zu.'),
    pairs: [
      { left: 'Ich habe Halsschmerzen.', right: 'Du solltest Tee mit Honig trinken.' },
      { left: 'Ich schlafe schlecht.', right: 'Du solltest abends kein Handy benutzen.' },
      { left: 'Ich bin zu dick.', right: 'Du solltest dich mehr bewegen.' },
      { left: 'Meine Augen tun weh.', right: 'Du solltest eine Pause vom Bildschirm machen.' },
    ],
    explanation: l('Problem → logical advice with „Du solltest …“.', 'Sorun → „Du solltest …“ ile mantıklı tavsiye.', 'Problem → Ratschlag.'),
    practice: ['rat-muede'],
  },
  {
    id: 'mc-sollst-solltest',
    type: 'multiple_choice',
    topic: 'sollte',
    concept: 'sollst-or-solltest',
    skill: 'grammar',
    difficulty: 3,
    prompt: 'Ich glaube, du ___ mal Urlaub machen. Du siehst so müde aus.',
    options: ['solltest', 'sollst', 'musst'],
    answer: 0,
    explanation: l(
      'Friendly advice → solltest (Konjunktiv II). sollst = someone else (e.g. the doctor) wants it. musst = obligation.',
      'Dostça tavsiye → solltest (Konjunktiv II). sollst = başkası (örneğin doktor) bunu istiyor. musst = zorunluluk.',
      'Ratschlag: solltest.'
    ),
    examples: ['Du **solltest** mal Urlaub machen.', 'Der Arzt sagt, du **sollst** im Bett bleiben.'],
  },
  {
    id: 'sort-gut-schlecht',
    type: 'categorize',
    topic: 'gesundheit',
    concept: 'healthy-habits',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Healthy or unhealthy?', 'Sağlıklı mı sağlıksız mı?', 'Gesund oder ungesund?'),
    categories: ['gesund', 'ungesund'],
    items: [
      { text: 'viel Wasser trinken', category: 0 },
      { text: 'bis 3 Uhr nachts am Handy sein', category: 1 },
      { text: 'jeden Tag spazieren gehen', category: 0 },
      { text: 'jeden Tag Fast Food essen', category: 1 },
      { text: 'Obst und Gemüse essen', category: 0 },
      { text: 'ohne Pause arbeiten', category: 1 },
    ],
    explanation: l('Good habits = good advice: Du solltest viel Wasser trinken.', 'İyi alışkanlıklar = iyi tavsiye: Du solltest viel Wasser trinken.', 'gesund / ungesund.'),
  },
  {
    id: 'select-ratschlag',
    type: 'multiple_select',
    topic: 'sollte',
    concept: 'advice-forms',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are pieces of advice? Select all.', 'Hangi cümleler tavsiye? Hepsini seç.', 'Welche Sätze sind Ratschläge?'),
    options: ['Du solltest mehr schlafen.', 'An deiner Stelle würde ich zum Arzt gehen.', 'Ich habe Kopfschmerzen.', 'Es ist besser, wenn du heute zu Hause bleibst.', 'Gestern war ich krank.'],
    answers: [0, 1, 3],
    explanation: l('Advice: Du solltest …, An deiner Stelle würde ich …, Es ist besser, wenn …', 'Tavsiye: Du solltest …, An deiner Stelle würde ich …, Es ist besser, wenn …', 'Ratschläge.'),
  },
  {
    id: 'tf-stelle',
    type: 'true_false',
    topic: 'sollte',
    concept: 'an-deiner-stelle',
    skill: 'grammar',
    difficulty: 2,
    statement: '„An deiner Stelle würde ich …“ bedeutet: If I were you, I would …',
    answer: true,
    explanation: l('An deiner Stelle = in your place. Verb (würde) comes right after it.', 'An deiner Stelle = senin yerinde. Fiil (würde) hemen ardından gelir.', 'An deiner Stelle würde ich …'),
  },
  {
    id: 'image-besserung',
    type: 'image_choice',
    topic: 'gesundheit',
    concept: 'get-well',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Gute Besserung!',
    options: [
      { emoji: '🤒', label: 'für Kranke' },
      { emoji: '🎂', label: 'zum Geburtstag' },
      { emoji: '💍', label: 'zur Hochzeit' },
      { emoji: '🎓', label: 'zum Abschluss' },
    ],
    answer: 0,
    explanation: l('Gute Besserung = Get well soon (for sick people).', 'Gute Besserung = Geçmiş olsun (hastalar için).', 'für Kranke.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-solltest',
    type: 'fill_blank',
    topic: 'sollte',
    concept: 'sollte-du',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Du hast Fieber. Du ___ im Bett bleiben.',
    accepted: ['solltest'],
    base: 'sollen (Ratschlag)',
    explanation: l('du → solltest.', 'du → solltest.', 'du solltest.'),
    examples: ['Du **solltest** im Bett bleiben.'],
  },
  {
    id: 'fill-sollten',
    type: 'fill_blank',
    topic: 'sollte',
    concept: 'sollte-Sie',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Frau Berg, Sie ___ weniger Kaffee trinken.',
    accepted: ['sollten'],
    base: 'sollen (Ratschlag)',
    explanation: l('Sie → sollten.', 'Sie → sollten.', 'Sie sollten.'),
    examples: ['Sie **sollten** weniger Kaffee trinken.'],
  },
  {
    id: 'fill-wuerde',
    type: 'fill_blank',
    topic: 'sollte',
    concept: 'an-deiner-stelle',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'An deiner Stelle ___ ich mit dem Chef sprechen.',
    accepted: ['würde'],
    base: 'werden → Konjunktiv II',
    explanation: l('An deiner Stelle würde ich … + infinitive.', 'An deiner Stelle würde ich … + mastar.', 'würde ich … sprechen.'),
    examples: ['An deiner Stelle **würde** ich mit dem Chef **sprechen**.'],
  },
  {
    id: 'build-solltest',
    type: 'sentence_builder',
    topic: 'sollte',
    concept: 'sollte-du',
    skill: 'grammar',
    difficulty: 2,
    chips: ['bewegen', 'mehr', 'dich', 'Du', 'solltest'],
    answers: [['Du', 'solltest', 'dich', 'mehr', 'bewegen']],
    translation: l('You should exercise more.', 'Daha çok hareket etmelisin.', 'Du solltest dich mehr bewegen.'),
    explanation: l('solltest (2) – reflexive – … – infinitive (end).', 'solltest (2) – dönüşlü – … – mastar (son).', 'Du solltest dich … bewegen.'),
    examples: ['Du **solltest** dich mehr **bewegen**.'],
  },
  {
    id: 'build-stelle',
    type: 'sentence_builder',
    topic: 'sollte',
    concept: 'an-deiner-stelle',
    skill: 'grammar',
    difficulty: 3,
    chips: ['würde', 'zum Arzt', 'An deiner Stelle', 'gehen', 'ich'],
    answers: [['An deiner Stelle', 'würde', 'ich', 'zum Arzt', 'gehen']],
    translation: l('If I were you, I’d go to the doctor.', 'Senin yerinde olsam doktora giderdim.', 'An deiner Stelle würde ich zum Arzt gehen.'),
    explanation: l('An deiner Stelle (1) – würde (2) – ich – … – infinitive.', 'An deiner Stelle (1) – würde (2) – ich – … – mastar.', 'An deiner Stelle würde ich …'),
    examples: ['An deiner Stelle **würde** ich zum Arzt **gehen**.'],
  },
  {
    id: 'build-besser',
    type: 'sentence_builder',
    topic: 'sollte',
    concept: 'es-ist-besser',
    skill: 'grammar',
    difficulty: 3,
    chips: ['bleibst', 'Es ist besser,', 'zu Hause', 'du', 'wenn'],
    answers: [['Es ist besser,', 'wenn', 'du', 'zu Hause', 'bleibst']],
    translation: l('It’s better if you stay at home.', 'Evde kalman daha iyi olur.', 'Es ist besser, wenn du zu Hause bleibst.'),
    explanation: l('wenn → verb at the end.', 'wenn → fiil sonda.', 'wenn … bleibst.'),
    examples: ['Es ist besser, **wenn** du zu Hause **bleibst**.'],
  },
  {
    id: 'fix-solltest-zu',
    type: 'error_correction',
    topic: 'sollte',
    concept: 'sollte-du',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Du solltest zu schlafen mehr.',
    accepted: ['Du solltest mehr schlafen.'],
    explanation: l('Modal verb + infinitive without zu, at the end.', 'Modal fiil + zu’suz mastar, sonda.', 'solltest … schlafen.'),
    examples: ['Du solltest mehr **schlafen**.'],
  },
  {
    id: 'fix-sollte-du',
    type: 'error_correction',
    topic: 'sollte',
    concept: 'sollte-du',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Du sollte mehr Obst essen.',
    accepted: ['Du solltest mehr Obst essen.'],
    explanation: l('du → solltest (-st).', 'du → solltest (-st).', 'du solltest.'),
    examples: ['Du **solltest** mehr Obst essen.'],
  },
  {
    id: 'fix-stelle',
    type: 'error_correction',
    topic: 'sollte',
    concept: 'an-deiner-stelle',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'An deiner Stelle ich würde nicht so viel arbeiten.',
    accepted: ['An deiner Stelle würde ich nicht so viel arbeiten.'],
    explanation: l('An deiner Stelle is position 1 → würde comes next.', 'An deiner Stelle 1. pozisyondur → ardından würde gelir.', 'An deiner Stelle würde ich …'),
    examples: ['An deiner Stelle **würde ich** nicht so viel arbeiten.'],
  },
  {
    id: 'tr-solltest',
    type: 'translation',
    topic: 'sollte',
    concept: 'sollte-du',
    skill: 'writing',
    difficulty: 2,
    source: l('You should drink more water. (du)', 'Daha çok su içmelisin. (du)', 'You should drink more water. (du)'),
    accepted: ['Du solltest mehr Wasser trinken.'],
    explanation: l('Du solltest … trinken.', 'Du solltest … trinken.', 'Du solltest mehr Wasser trinken.'),
    examples: ['Du **solltest** mehr Wasser **trinken**.'],
  },
  {
    id: 'tr-besserung',
    type: 'translation',
    topic: 'gesundheit',
    concept: 'get-well',
    skill: 'writing',
    difficulty: 1,
    source: l('Get well soon!', 'Geçmiş olsun!', 'Get well soon!'),
    accepted: ['Gute Besserung!', 'Gute Besserung'],
    explanation: l('Gute Besserung!', 'Gute Besserung!', 'Gute Besserung!'),
  },
  {
    id: 'ordering-gespraech',
    type: 'ordering',
    topic: 'probleme',
    concept: 'advice-dialogue',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the conversation in order.', 'Konuşmayı sıraya koy.', 'Bring das Gespräch in Ordnung.'),
    items: ['Das ist eine gute Idee. Danke!', 'Was ist los? Du siehst müde aus.', 'Ich schlafe seit Tagen schlecht.', 'Du solltest abends einen Tee trinken und kein Handy benutzen.'],
    answer: ['Was ist los? Du siehst müde aus.', 'Ich schlafe seit Tagen schlecht.', 'Du solltest abends einen Tee trinken und kein Handy benutzen.', 'Das ist eine gute Idee. Danke!'],
    explanation: l('Ask → problem → advice → reaction.', 'Sor → sorun → tavsiye → tepki.', 'Frage → Problem → Ratschlag → Reaktion.'),
  },
  {
    id: 'dialog-rat',
    type: 'dialogue',
    topic: 'probleme',
    concept: 'problem-advice',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Ich habe so viel Stress im Moment. Was soll ich machen?' }],
    options: ['Du solltest mal ein paar Tage Urlaub nehmen.', 'Du sollst Stress haben.', 'Ich habe auch Stress gehabt gestern.'],
    answer: 0,
    explanation: l('Give advice with Du solltest …', 'Du solltest … ile tavsiye ver.', 'Du solltest …'),
  },
  {
    id: 'dialog-reaktion',
    type: 'dialogue',
    topic: 'probleme',
    concept: 'react-advice',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Freund', de: 'Du solltest wirklich zum Arzt gehen.' }],
    options: ['Du hast recht. Ich rufe morgen an.', 'Du solltest recht.', 'Ich bin Arzt gehen.'],
    answer: 0,
    explanation: l('Accept advice: Du hast recht. / Das ist eine gute Idee.', 'Tavsiyeyi kabul et: Du hast recht. / Das ist eine gute Idee.', 'Du hast recht.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-problem',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was ist Leonies Problem?',
    options: ['Sie schläft sehr schlecht.', 'Sie hat Fieber.', 'Sie hat keine Arbeit.'],
    answer: 0,
    explanation: l('„Seit Wochen schlafe ich ganz schlecht.“', '„Seit Wochen schlafe ich ganz schlecht.“', '„schlafe schlecht“'),
  },
  {
    id: 'read-handy',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was rät Max?',
    options: ['Eine Stunde vor dem Schlafen kein Handy.', 'Mehr Kaffee trinken.', 'Später ins Bett gehen.'],
    answer: 0,
    explanation: l('„Du solltest eine Stunde vor dem Schlafen kein Handy mehr benutzen.“', '„Du solltest eine Stunde vor dem Schlafen kein Handy mehr benutzen.“', '„kein Handy“'),
  },
  {
    id: 'read-sport',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    statement: 'Aylin empfiehlt, spät am Abend Sport zu machen.',
    answer: false,
    explanation: l('„Sport ist gut – aber nicht spät am Abend!“', '„Sport ist gut – aber nicht spät am Abend!“', 'nicht spät am Abend.'),
  },
  {
    id: 'read-arzt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was würde Dr. Weiß machen?',
    options: ['Zum Arzt gehen, wenn es nicht besser wird.', 'Schlaftabletten nehmen.', 'Nichts.'],
    answer: 0,
    explanation: l('„Wenn es nicht besser wird, würde ich an Ihrer Stelle zum Arzt gehen.“', '„Wenn es nicht besser wird, würde ich an Ihrer Stelle zum Arzt gehen.“', '„zum Arzt gehen“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-rat',
    type: 'listening_choice',
    topic: 'sollte',
    concept: 'sollte-du',
    skill: 'listening',
    difficulty: 1,
    audio: 'Du hast Rückenschmerzen? Dann solltest du nicht so lange am Computer sitzen.',
    question: l('What’s the advice?', 'Tavsiye ne?', 'Was ist der Ratschlag?'),
    options: ['less time at the computer', 'more coffee', 'more computer games'],
    answer: 0,
    explanation: l('„nicht so lange am Computer sitzen“', '„nicht so lange am Computer sitzen“', 'weniger Computer.'),
  },
  {
    id: 'listen-arzt',
    type: 'listening_choice',
    topic: 'gesundheit',
    concept: 'doctor-advice',
    skill: 'listening',
    difficulty: 2,
    audio: 'Sie sollten drei Tage im Bett bleiben und viel trinken. Und nehmen Sie diese Tabletten zweimal am Tag.',
    question: l('How often should the tablets be taken?', 'Haplar ne sıklıkla alınmalı?', 'Wie oft soll man die Tabletten nehmen?'),
    options: ['2× pro Tag', '3× pro Tag', '1× pro Tag'],
    answer: 0,
    explanation: l('„zweimal am Tag“', '„zweimal am Tag“', '2×.'),
  },
  {
    id: 'listen-stelle',
    type: 'listening_choice',
    topic: 'sollte',
    concept: 'an-deiner-stelle',
    skill: 'listening',
    difficulty: 2,
    audio: 'An deiner Stelle würde ich die Wohnung nicht nehmen. Sie ist viel zu teuer.',
    question: l('What does the speaker advise?', 'Konuşmacı ne tavsiye ediyor?', 'Was rät die Person?'),
    options: ['not to take the flat', 'to take the flat', 'to buy a house'],
    answer: 0,
    explanation: l('„würde ich die Wohnung nicht nehmen“', '„würde ich die Wohnung nicht nehmen“', 'nicht nehmen.'),
  },
  {
    id: 'listen-symptom',
    type: 'listening_choice',
    topic: 'gesundheit',
    concept: 'symptoms',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich bin seit gestern erkältet. Ich habe Husten und Halsschmerzen.',
    question: l('What’s wrong?', 'Sorun ne?', 'Was hat die Person?'),
    options: ['🤧 eine Erkältung', '🦶 Fußschmerzen', '🤕 einen Unfall'],
    answer: 0,
    explanation: l('erkältet, Husten, Halsschmerzen = a cold.', 'erkältet, Husten, Halsschmerzen = nezle.', 'Erkältung.'),
  },

  ...adviceDrills(),
]

export const UNIT_A2_16_RATSCHLAEGE: CourseUnit = {
  level: 'A2',
  number: 16,
  slug: 'ratschlaege',
  titleDe: 'Du solltest mehr schlafen',
  title: l('You should sleep more', 'Daha çok uyumalısın', 'Du solltest mehr schlafen'),
  goal: l(
    'By the end of this unit you can describe small health problems and give advice: Du solltest …, Sie sollten …, An deiner Stelle würde ich …, Es ist besser, wenn …',
    'Bu ünitenin sonunda küçük sağlık sorunlarını anlatabilir ve tavsiye verebilirsin: Du solltest …, Sie sollten …, An deiner Stelle würde ich …, Es ist besser, wenn …',
    'Am Ende dieser Einheit gibst du Ratschläge.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'sollte', label: l('Giving advice', 'Tavsiye vermek', 'Ratschläge geben') },
    { key: 'probleme', label: l('Problems & reactions', 'Sorunlar ve tepkiler', 'Probleme & Reaktionen') },
    { key: 'gesundheit', label: l('Health & habits', 'Sağlık ve alışkanlıklar', 'Gesundheit') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('How to give advice – and the problems you need it for.', 'Nasıl tavsiye verilir – ve hangi sorunlar için.', 'Ratschläge und Probleme.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('sollte + infinitive', 'sollte + mastar', 'sollte + Infinitiv'),
          body: l(
            'For friendly advice use the Konjunktiv II of sollen: sollte. It works like a modal verb: sollte in position 2, infinitive at the end.',
            'Dostça tavsiye için sollen’in Konjunktiv II’si kullanılır: sollte. Modal fiil gibi çalışır: sollte 2. sırada, mastar sonda.',
            'sollte = Ratschlag.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('sollte', 'sollte', 'sollte'), l('Example', 'Örnek', 'Beispiel')],
            rows: [
              ['ich', 'sollte', 'Ich sollte mehr schlafen.'],
              ['du', 'solltest', 'Du solltest zum Arzt gehen.'],
              ['er / sie', 'sollte', 'Sie sollte eine Pause machen.'],
              ['wir', 'sollten', 'Wir sollten gesünder essen.'],
              ['ihr', 'solltet', 'Ihr solltet früher ins Bett gehen.'],
              ['sie / Sie', 'sollten', 'Sie sollten viel trinken.'],
            ],
          },
          tip: l('sollst (present) = someone else wants it: „Der Arzt sagt, du sollst …“. solltest = my advice.', 'sollst (şimdiki) = başkası istiyor: „Der Arzt sagt, du sollst …“. solltest = benim tavsiyem.', 'sollst ≠ solltest.'),
        },
        {
          title: l('More ways to give advice', 'Tavsiye vermenin diğer yolları', 'Weitere Ratschläge'),
          body: l(
            'An deiner Stelle würde ich … (If I were you, I’d …) – Es ist besser, wenn du … (verb at the end) – Mach doch mal …! (friendly imperative)',
            'An deiner Stelle würde ich … (Senin yerinde olsam …) – Es ist besser, wenn du … (fiil sonda) – Mach doch mal …! (dostça emir)',
            'An deiner Stelle würde ich … · Es ist besser, wenn …'
          ),
        },
        {
          title: l('Reacting to advice', 'Tavsiyeye tepki vermek', 'Auf Ratschläge reagieren'),
          body: l('Positive: Das ist eine gute Idee! / Du hast recht. – Negative: Das geht leider nicht, weil … / Das habe ich schon probiert.', 'Olumlu: Das ist eine gute Idee! / Du hast recht. – Olumsuz: Das geht leider nicht, weil … / Das habe ich schon probiert.', 'Gute Idee! / Das geht nicht, weil …'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two colleagues in the coffee kitchen.', 'İki iş arkadaşı çay ocağında.', 'Zwei Kollegen in der Kaffeeküche.'),
      dialogue: [
        { speaker: 'Jonas', de: 'Was ist los, Sara? Du siehst so müde aus.', translation: l('What’s wrong, Sara? You look so tired.', 'Ne oldu Sara? Çok yorgun görünüyorsun.', '') },
        { speaker: 'Sara', de: 'Ich schlafe seit Wochen schlecht. Und ich habe so viel **Stress**.', translation: l('I’ve been sleeping badly for weeks. And I have so much stress.', 'Haftalardır kötü uyuyorum. Bir de çok stresim var.', '') },
        { speaker: 'Jonas', de: 'Du **solltest** abends nicht so lange am Handy **sein**.', translation: l('You shouldn’t be on your phone so late in the evening.', 'Akşamları o kadar uzun telefonda olmamalısın.', '') },
        { speaker: 'Sara', de: 'Ja, das stimmt. Aber der Stress …', translation: l('Yes, that’s true. But the stress …', 'Evet, doğru. Ama stres …', '') },
        { speaker: 'Jonas', de: '**An deiner Stelle würde ich** mit der Chefin **sprechen**. Vielleicht kann jemand dir helfen.', translation: l('If I were you, I’d talk to the boss. Maybe someone can help you.', 'Senin yerinde olsam patronla konuşurdum. Belki biri sana yardım edebilir.', '') },
        { speaker: 'Sara', de: '**Das ist eine gute Idee.** Und am Wochenende mache ich mal gar nichts!', translation: l('That’s a good idea. And at the weekend I’ll do nothing at all!', 'Bu iyi bir fikir. Hafta sonu da hiçbir şey yapmayacağım!', '') },
        { speaker: 'Jonas', de: 'Genau. **Es ist besser, wenn** du dich mal **ausruhst**.', translation: l('Exactly. It’s better if you get some rest.', 'Aynen. Biraz dinlenmen daha iyi olur.', '') },
      ],
      examples: [
        { de: 'Du **solltest** mehr Wasser **trinken**.', translation: l('You should drink more water.', 'Daha çok su içmelisin.', '') },
        { de: 'Sie **sollten** sich **ausruhen**.', translation: l('You should rest.', 'Dinlenmelisiniz.', '') },
        { de: 'Wir **sollten** öfter Sport **machen**.', translation: l('We should exercise more often.', 'Daha sık spor yapmalıyız.', '') },
        { de: '**An deiner Stelle würde ich** zum Arzt **gehen**.', translation: l('If I were you, I’d go to the doctor.', 'Senin yerinde olsam doktora giderdim.', '') },
        { de: '**Es ist besser, wenn** du zu Hause **bleibst**.', translation: l('It’s better if you stay at home.', 'Evde kalman daha iyi olur.', '') },
        { de: '**Gute Besserung!**', translation: l('Get well soon!', 'Geçmiş olsun!', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Problems and advice.', 'Sorunlar ve tavsiyeler.', 'Probleme und Ratschläge.'),
      exercises: ['match-problem', 'rat-muede', 'rat-husten', 'mc-sollst-solltest', 'sort-gut-schlecht', 'select-ratschlag', 'tf-stelle', 'image-besserung', 'rat-fieber'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Give advice to friends and colleagues.', 'Arkadaşlara ve iş arkadaşlarına tavsiye ver.', 'Gib Ratschläge.'),
      exercises: [
        'fill-solltest',
        'fill-sollten',
        'fill-wuerde',
        'build-solltest',
        'build-stelle',
        'build-besser',
        'fix-solltest-zu',
        'fix-sollte-du',
        'fix-stelle',
        'tr-solltest',
        'tr-besserung',
        'ordering-gespraech',
        'dialog-rat',
        'dialog-reaktion',
        'rat-ruecken',
        'rat-stress',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A health forum: Leonie can’t sleep.', 'Bir sağlık forumu: Leonie uyuyamıyor.', 'Ein Gesundheitsforum.'),
      passage: [
        '**Leonie, 24:** Seit Wochen schlafe ich ganz schlecht. Ich bin jeden Morgen total müde. Was soll ich machen?',
        '**Max:** Du **solltest** eine Stunde vor dem Schlafen kein Handy mehr **benutzen**. Bei mir hat das geholfen!',
        '**Aylin:** Trink abends keinen Kaffee! Und Sport ist gut – aber nicht spät am Abend!',
        '**Dr. Weiß:** Wenn es nicht besser wird, **würde** ich an Ihrer Stelle zum Arzt **gehen**. Gute Besserung!',
      ],
      glossary: [
        { de: 'total', note: l('totally, very', 'tamamen', 'sehr') },
        { de: 'geholfen (helfen)', note: l('helped', 'yardımcı oldu', 'helfen → hat geholfen') },
        { de: 'an Ihrer Stelle', note: l('if I were you (formal)', 'sizin yerinizde', 'formell') },
      ],
      exercises: ['read-problem', 'read-handy', 'read-sport', 'read-arzt'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Problems and advice in everyday life.', 'Günlük hayatta sorunlar ve tavsiyeler.', 'Probleme und Ratschläge.'),
      exercises: ['listen-rat', 'listen-arzt', 'listen-stelle', 'listen-symptom'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('A friend has a problem (stress, bad sleep or a cold). Give at least three pieces of advice.', 'Bir arkadaşının sorunu var (stres, kötü uyku ya da nezle). En az üç tavsiye ver.', 'Gib einem Freund drei Ratschläge.'),
      points: [
        l('Show you care: „Oh, das tut mir leid!“', 'İlgini göster: „Oh, das tut mir leid!“', 'Mitgefühl'),
        l('„Du solltest …“', '„Du solltest …“', 'Du solltest …'),
        l('„An deiner Stelle würde ich …“', '„An deiner Stelle würde ich …“', 'An deiner Stelle …'),
        l('„Es ist besser, wenn du …“', '„Es ist besser, wenn du …“', 'Es ist besser, wenn …'),
        l('End with a wish: „Gute Besserung!“', 'Bir dilekle bitir: „Gute Besserung!“', 'Gute Besserung!'),
      ],
      model: [
        'Oh, das tut mir leid! Du bist erkältet?',
        'Du solltest viel Tee mit Honig trinken.',
        'An deiner Stelle würde ich morgen nicht zur Arbeit gehen.',
        'Es ist besser, wenn du dich ein paar Tage ausruhst.',
        'Gute Besserung!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Answer Leonie in the forum (at least 4 sentences). Give her advice.',
        'Forumda Leonie’ye cevap yaz (en az 4 cümle). Ona tavsiye ver.',
        'Antworte Leonie im Forum (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('sollte (du solltest / Sie sollten)', 'sollte (du solltest / Sie sollten)', 'sollte'), pattern: '\\bsollte(st|n|t)?\\b' },
        { label: l('Another form (An deiner Stelle / Es ist besser, wenn)', 'Başka bir biçim (An deiner Stelle / Es ist besser, wenn)', 'Weitere Form'), pattern: '([Aa]n deiner Stelle|[Aa]n Ihrer Stelle|[Ee]s ist besser, wenn)' },
        { label: l('Infinitive at the end (… trinken. / … gehen.)', 'Mastar sonda (… trinken. / … gehen.)', 'Infinitiv am Ende'), pattern: '\\p{Ll}+en[.!]' },
      ],
      model: [
        'Hallo Leonie, das kenne ich gut!',
        'Du solltest abends keinen Kaffee mehr trinken.',
        'An deiner Stelle würde ich vor dem Schlafen ein Buch lesen.',
        'Es ist besser, wenn du jeden Tag zur gleichen Zeit ins Bett gehst.',
        'Gute Nacht und viel Glück!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('sollte – 60 seconds.', 'sollte – 60 saniye.', 'sollte – 60 Sekunden.'),
      seconds: 60,
      pool: [...ADVICE.map(([id]) => `rat-${id}`), 'mc-sollst-solltest'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Advice: sollte, solltest, sollten + infinitive', 'Tavsiye: sollte, solltest, sollten + mastar', 'sollte + Infinitiv'),
      l('An deiner Stelle würde ich … · Es ist besser, wenn …', 'An deiner Stelle würde ich … · Es ist besser, wenn …', 'weitere Ratschläge'),
      l('Reactions: Gute Idee! / Du hast recht.', 'Tepkiler: Gute Idee! / Du hast recht.', 'Reaktionen'),
      l('Gute Besserung!', 'Gute Besserung!', 'Gute Besserung!'),
    ],
    mistakes: [
      { wrong: 'Du sollte mehr schlafen.', right: 'Du solltest mehr schlafen.', note: l('du → solltest.', 'du → solltest.', 'solltest.') },
      { wrong: 'Du solltest zu schlafen.', right: 'Du solltest schlafen.', note: l('No zu after modal verbs.', 'Modal fiilden sonra zu yok.', 'kein zu.') },
      { wrong: 'An deiner Stelle ich würde …', right: 'An deiner Stelle würde ich …', note: l('Verb in position 2.', 'Fiil 2. sırada.', 'Verb Position 2.') },
      { wrong: 'Es ist besser, wenn du bleibst zu Hause.', right: 'Es ist besser, wenn du zu Hause bleibst.', note: l('wenn → verb at the end.', 'wenn → fiil sonda.', 'Verb am Ende.') },
    ],
  },
}
