import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Es regnet.', emoji: '🌧️', translation: l('It’s raining.', 'Yağmur yağıyor.', 'Regen'), example: 'Es regnet schon den ganzen Tag.' },
  { word: 'Es schneit.', emoji: '❄️', translation: l('It’s snowing.', 'Kar yağıyor.', 'Schnee'), example: 'Im Januar schneit es oft.' },
  { word: 'Die Sonne scheint.', emoji: '☀️', translation: l('The sun is shining.', 'Güneş parlıyor.', 'Sonne'), example: 'Heute scheint die Sonne.' },
  { word: 'Es ist sonnig.', emoji: '😎', translation: l('It’s sunny.', 'Hava güneşli.', 'viel Sonne'), example: 'Morgen ist es sonnig und warm.' },
  { word: 'Es ist bewölkt.', emoji: '☁️', translation: l('It’s cloudy.', 'Hava bulutlu.', 'viele Wolken'), example: 'Am Nachmittag ist es bewölkt.' },
  { word: 'Es ist windig.', emoji: '🌬️', translation: l('It’s windy.', 'Hava rüzgârlı.', 'viel Wind'), example: 'An der Nordsee ist es oft windig.' },
  { word: 'Es gibt ein Gewitter.', emoji: '⛈️', translation: l('There’s a thunderstorm.', 'Fırtına var.', 'Blitz und Donner'), example: 'Am Abend gibt es ein Gewitter.' },
  { word: 'Es ist neblig.', emoji: '🌫️', translation: l('It’s foggy.', 'Hava sisli.', 'Nebel'), example: 'Am Morgen ist es neblig.' },
  { word: 'minus fünf Grad', emoji: '🥶', translation: l('minus five degrees', 'eksi beş derece', '−5 °C'), example: 'Heute Nacht sind es minus fünf Grad.' },
  { word: 'die Wettervorhersage', emoji: '📺', translation: l('weather forecast', 'hava tahmini', 'Wetterbericht'), example: 'Laut Wettervorhersage wird es morgen warm.' },
  { word: 'der Frühling · Sommer · Herbst · Winter', emoji: '🌸', translation: l('spring · summer · autumn · winter', 'ilkbahar · yaz · sonbahar · kış', 'Jahreszeiten'), example: 'Im Herbst fallen die Blätter.' },
  { word: 'es wird …', emoji: '📈', translation: l('it’s getting / it will be …', '… oluyor / olacak', 'Veränderung'), example: 'Es wird kalt.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Wetter', gender: 'n', translation: l('weather', 'hava', 'Wetter') },
  { word: 'Regen', gender: 'm', translation: l('rain', 'yağmur', 'Regen') },
  { word: 'Schnee', gender: 'm', translation: l('snow', 'kar', 'Schnee') },
  { word: 'Wolke', gender: 'f', plural: 'die Wolken', translation: l('cloud', 'bulut', 'Wolke') },
  { word: 'Gewitter', gender: 'n', plural: 'die Gewitter', translation: l('thunderstorm', 'gök gürültülü fırtına', 'Gewitter') },
  { word: 'Grad', gender: 'n', translation: l('degree', 'derece', 'Grad') },
  { word: 'Jahreszeit', gender: 'f', plural: 'die Jahreszeiten', translation: l('season', 'mevsim', 'Jahreszeit') },
  { word: 'Regenschirm', gender: 'm', plural: 'die Regenschirme', translation: l('umbrella', 'şemsiye', 'Regenschirm') },
]

/** [id, emoji, right sentence, two wrong sentences] */
const WEATHER: [string, string, string, [string, string]][] = [
  ['regen', '🌧️', 'Es regnet.', ['Es ist regnet.', 'Es Regen.']],
  ['schnee', '❄️', 'Es schneit.', ['Es ist Schnee.', 'Es schneien.']],
  ['sonne', '☀️', 'Es ist sonnig.', ['Es sonnig.', 'Es ist Sonne.']],
  ['wolken', '☁️', 'Es ist bewölkt.', ['Es wolkt.', 'Es ist Wolken.']],
  ['wind', '🌬️', 'Es ist windig.', ['Es windet.', 'Es ist Wind.']],
  ['nebel', '🌫️', 'Es ist neblig.', ['Es nebelt ist.', 'Es Nebel.']],
]

function weatherDrills(): Exercise[] {
  return WEATHER.map(([id, emoji, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const verb = right === 'Es regnet.' || right === 'Es schneit.'
    return {
      id: `wetter-${id}`,
      type: 'multiple_choice' as const,
      topic: 'wetter',
      concept: verb ? 'weather-verb' : 'weather-adj',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      visual: [emoji],
      prompt: 'Wie ist das Wetter?',
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: verb
        ? l('regnen and schneien are verbs: es regnet, es schneit (no „ist“).', 'regnen ve schneien fiildir: es regnet, es schneit („ist“ yok).', 'Es regnet / Es schneit.')
        : l('Adjective → es ist + adjective (-ig): sonnig, bewölkt, windig, neblig.', 'Sıfat → es ist + sıfat (-ig): sonnig, bewölkt, windig, neblig.', 'Es ist + Adjektiv.'),
      examples: [right],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-noun-adj',
    type: 'matching',
    topic: 'wetter',
    concept: 'noun-adjective',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Noun → adjective.', 'İsim → sıfat.', 'Nomen → Adjektiv.'),
    pairs: [
      { left: 'die Sonne', right: 'sonnig' },
      { left: 'der Wind', right: 'windig' },
      { left: 'der Nebel', right: 'neblig' },
      { left: 'die Wolke', right: 'bewölkt' },
      { left: 'der Regen', right: 'regnerisch' },
    ],
    explanation: l('Many weather adjectives end in -ig or -isch.', 'Hava durumu sıfatlarının çoğu -ig ya da -isch ile biter.', '-ig / -isch.'),
  },
  {
    id: 'sort-jahreszeit',
    type: 'categorize',
    topic: 'jahreszeiten',
    concept: 'seasons',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Which season? (Germany)', 'Hangi mevsim? (Almanya)', 'Welche Jahreszeit? (Deutschland)'),
    categories: ['Frühling', 'Sommer', 'Herbst', 'Winter'],
    items: [
      { text: 'Die Blumen blühen.', category: 0 },
      { text: 'Wir gehen schwimmen.', category: 1 },
      { text: 'Die Blätter fallen.', category: 2 },
      { text: 'Es schneit.', category: 3 },
      { text: 'Ostern', category: 0 },
      { text: 'Weihnachten', category: 3 },
    ],
    explanation: l('im Frühling, im Sommer, im Herbst, im Winter (im = in dem).', 'im Frühling, im Sommer, im Herbst, im Winter (im = in dem).', 'im + Jahreszeit.'),
  },
  {
    id: 'mc-im',
    type: 'multiple_choice',
    topic: 'jahreszeiten',
    concept: 'im-season',
    skill: 'grammar',
    difficulty: 1,
    prompt: '___ Sommer fahren wir ans Meer.',
    options: ['Im', 'Am', 'Um'],
    answer: 0,
    explanation: l('Seasons and months: im (im Sommer, im Juli). Days: am (am Montag). Times: um (um 8 Uhr).', 'Mevsimler ve aylar: im (im Sommer, im Juli). Günler: am (am Montag). Saatler: um (um 8 Uhr).', 'im Sommer.'),
    examples: ['**Im** Sommer fahren wir ans Meer.'],
  },
  {
    id: 'mc-wird',
    type: 'multiple_choice',
    topic: 'vorhersage',
    concept: 'es-wird',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Morgen ___ es wärmer – bis zu 25 Grad.',
    options: ['wird', 'ist geworden', 'wurde'],
    answer: 0,
    explanation: l('Forecast / change: es wird + adjective (it’s going to be …).', 'Tahmin / değişim: es wird + sıfat (… olacak).', 'es wird wärmer.'),
    examples: ['Morgen **wird** es wärmer.'],
  },
  {
    id: 'tf-minus',
    type: 'true_false',
    topic: 'vorhersage',
    concept: 'temperature',
    skill: 'reading',
    difficulty: 1,
    visual: ['🌡️ −3 °C'],
    statement: 'Es sind minus drei Grad. Es ist warm.',
    answer: false,
    explanation: l('−3 °C = minus drei Grad → kalt.', '−3 °C = eksi üç derece → soğuk.', 'kalt.'),
  },
  {
    id: 'select-kalt',
    type: 'multiple_select',
    topic: 'wetter',
    concept: 'cold-weather',
    skill: 'vocabulary',
    difficulty: 1,
    promptL10n: l('What do you typically hear in winter? Select all.', 'Kışın tipik olarak ne duyarsın? Hepsini seç.', 'Was hört man im Winter? Wähle alle.'),
    options: ['Es schneit.', 'Es ist glatt.', 'Es ist heiß.', 'Es friert.', 'Wir gehen baden.'],
    answers: [0, 1, 3],
    explanation: l('Winter: schneien, glatt (icy), frieren (freeze).', 'Kış: schneien, glatt (kaygan), frieren (donmak).', 'Winterwetter.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-regnet',
    type: 'fill_blank',
    topic: 'wetter',
    concept: 'weather-verb',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Nimm einen Schirm mit! Es ___.',
    accepted: ['regnet'],
    base: 'regnen',
    explanation: l('regnen → es regnet.', 'regnen → es regnet.', 'es regnet.'),
    examples: ['Es **regnet**.'],
  },
  {
    id: 'fill-scheint',
    type: 'fill_blank',
    topic: 'wetter',
    concept: 'sun-shines',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Heute ___ die Sonne – lass uns in den Park gehen!',
    accepted: ['scheint'],
    base: 'scheinen',
    explanation: l('die Sonne scheint (the sun shines).', 'die Sonne scheint (güneş parlıyor).', 'scheint.'),
    examples: ['Heute **scheint** die Sonne.'],
  },
  {
    id: 'fill-grad',
    type: 'fill_blank',
    topic: 'vorhersage',
    concept: 'temperature',
    skill: 'vocabulary',
    difficulty: 1,
    sentence: 'In Berlin sind es heute 28 ___.',
    accepted: ['Grad'],
    base: '°C',
    explanation: l('Grad has no plural ending: 28 Grad.', 'Grad çoğul eki almaz: 28 Grad.', '28 Grad.'),
    examples: ['Es sind 28 **Grad**.'],
  },
  {
    id: 'build-vorhersage',
    type: 'sentence_builder',
    topic: 'vorhersage',
    concept: 'es-wird',
    skill: 'grammar',
    difficulty: 2,
    chips: ['es', 'Am Wochenende', 'kalt und windig', 'wird'],
    answers: [['Am Wochenende', 'wird', 'es', 'kalt und windig']],
    translation: l('At the weekend it’s going to be cold and windy.', 'Hafta sonu hava soğuk ve rüzgârlı olacak.', 'Am Wochenende wird es kalt und windig.'),
    explanation: l('Time (1) – wird (2) – es – adjectives.', 'Zaman (1) – wird (2) – es – sıfatlar.', 'Am Wochenende wird es …'),
    examples: ['Am Wochenende **wird es** kalt und windig.'],
  },
  {
    id: 'build-wenn',
    type: 'sentence_builder',
    topic: 'jahreszeiten',
    concept: 'weather-plans',
    skill: 'grammar',
    difficulty: 3,
    chips: ['Ski', 'fahren', 'wir', 'Wenn es schneit,'],
    answers: [['Wenn es schneit,', 'fahren', 'wir', 'Ski']],
    translation: l('When it snows, we go skiing.', 'Kar yağdığında kayak yaparız.', 'Wenn es schneit, fahren wir Ski.'),
    explanation: l('wenn-clause first → verb, verb.', 'Önce wenn-cümlesi → fiil, fiil.', 'Wenn …, fahren wir …'),
    examples: ['Wenn es schneit, **fahren** wir Ski.'],
  },
  {
    id: 'build-lieblings',
    type: 'sentence_builder',
    topic: 'jahreszeiten',
    concept: 'seasons',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ist', 'der Herbst', 'Meine Lieblingsjahreszeit', 'bunt', 'weil', 'alles', 'ist'],
    answers: [['Meine Lieblingsjahreszeit', 'ist', 'der Herbst', 'weil', 'alles', 'bunt', 'ist']],
    translation: l('My favourite season is autumn, because everything is colourful.', 'En sevdiğim mevsim sonbahar, çünkü her şey rengârenk.', 'Meine Lieblingsjahreszeit ist der Herbst, weil alles bunt ist.'),
    explanation: l('weil → verb at the end.', 'weil → fiil sonda.', 'weil alles bunt ist.'),
    examples: ['Meine Lieblingsjahreszeit ist der Herbst, **weil** alles bunt **ist**.'],
  },
  {
    id: 'fix-ist-regnet',
    type: 'error_correction',
    topic: 'wetter',
    concept: 'weather-verb',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Heute ist es regnet.',
    accepted: ['Heute regnet es.'],
    explanation: l('regnen is a verb: Heute regnet es (no ist).', 'regnen bir fiildir: Heute regnet es (ist yok).', 'Heute regnet es.'),
    examples: ['Heute **regnet** es.'],
  },
  {
    id: 'fix-sonne',
    type: 'error_correction',
    topic: 'wetter',
    concept: 'weather-adj',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Es ist Sonne.',
    accepted: ['Es ist sonnig.', 'Die Sonne scheint.'],
    explanation: l('Es ist + adjective: sonnig. Or: Die Sonne scheint.', 'Es ist + sıfat: sonnig. Ya da: Die Sonne scheint.', 'Es ist sonnig.'),
    examples: ['Es ist **sonnig**.'],
  },
  {
    id: 'fix-am-winter',
    type: 'error_correction',
    topic: 'jahreszeiten',
    concept: 'im-season',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Am Winter ist es sehr kalt.',
    accepted: ['Im Winter ist es sehr kalt.'],
    explanation: l('Seasons → im.', 'Mevsimler → im.', 'im Winter.'),
    examples: ['**Im** Winter ist es sehr kalt.'],
  },
  {
    id: 'tr-schneit',
    type: 'translation',
    topic: 'wetter',
    concept: 'weather-verb',
    skill: 'writing',
    difficulty: 1,
    source: l('It’s snowing in the mountains.', 'Dağlarda kar yağıyor.', 'It’s snowing in the mountains.'),
    accepted: ['In den Bergen schneit es.', 'Es schneit in den Bergen.'],
    explanation: l('In den Bergen schneit es.', 'In den Bergen schneit es.', 'Es schneit.'),
    examples: ['In den Bergen **schneit** es.'],
  },
  {
    id: 'tr-wird',
    type: 'translation',
    topic: 'vorhersage',
    concept: 'es-wird',
    skill: 'writing',
    difficulty: 2,
    source: l('Tomorrow it will be warm.', 'Yarın hava sıcak olacak.', 'Tomorrow it will be warm.'),
    accepted: ['Morgen wird es warm.', 'Es wird morgen warm.'],
    explanation: l('Morgen wird es warm.', 'Morgen wird es warm.', 'wird es warm.'),
    examples: ['Morgen **wird** es warm.'],
  },
  {
    id: 'ordering-tag',
    type: 'ordering',
    topic: 'vorhersage',
    concept: 'forecast-day',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the forecast in order of the day.', 'Tahmini günün sırasına koy.', 'Bring die Vorhersage in die Tagesreihenfolge.'),
    items: ['Am Abend gibt es Gewitter.', 'Am Morgen ist es neblig.', 'In der Nacht wird es kühl.', 'Mittags scheint die Sonne.'],
    answer: ['Am Morgen ist es neblig.', 'Mittags scheint die Sonne.', 'Am Abend gibt es Gewitter.', 'In der Nacht wird es kühl.'],
    explanation: l('morning → noon → evening → night.', 'sabah → öğle → akşam → gece.', 'Morgen → Mittag → Abend → Nacht.'),
  },
  {
    id: 'dialog-wetter',
    type: 'dialogue',
    topic: 'wetter',
    concept: 'smalltalk',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Nachbarin', de: 'Was für ein Wetter heute, oder?' }],
    options: ['Ja, furchtbar! Es regnet schon seit heute Morgen.', 'Ja, es ist Regen heute Morgen seit.', 'Nein, ich bin Wetter.'],
    answer: 0,
    explanation: l('Small talk about the weather – very German!', 'Hava hakkında sohbet – tam Alman usulü!', 'Smalltalk.'),
  },
  {
    id: 'dialog-ausflug',
    type: 'dialogue',
    topic: 'vorhersage',
    concept: 'weather-plans',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Machen wir am Sonntag eine Radtour?' }],
    options: ['Gern, aber laut Wettervorhersage gibt es Gewitter. Vielleicht Samstag?', 'Gern, Gewitter ist sonnig.', 'Nein, Sonntag regnet ist.'],
    answer: 0,
    explanation: l('Use the forecast to make plans.', 'Plan yapmak için hava tahminini kullan.', 'laut Wettervorhersage …'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-heute',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-vorhersage',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie ist das Wetter heute im Norden?',
    options: ['Bewölkt und windig, manchmal Regen.', 'Sonnig und heiß.', 'Es schneit.'],
    answer: 0,
    explanation: l('„Im Norden ist es bewölkt und windig, ab und zu regnet es.“', '„Im Norden ist es bewölkt und windig, ab und zu regnet es.“', 'bewölkt, windig.'),
  },
  {
    id: 'read-sueden',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-vorhersage',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie warm wird es im Süden?',
    options: ['Bis 24 Grad.', 'Bis 14 Grad.', 'Minus 2 Grad.'],
    answer: 0,
    explanation: l('„Im Süden scheint die Sonne bei bis zu 24 Grad.“', '„Im Süden scheint die Sonne bei bis zu 24 Grad.“', '24 Grad.'),
  },
  {
    id: 'read-gewitter',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-vorhersage',
    skill: 'reading',
    difficulty: 2,
    statement: 'Am Abend gibt es im Süden Gewitter.',
    answer: true,
    explanation: l('„Am Abend kann es im Süden Gewitter geben.“', '„Am Abend kann es im Süden Gewitter geben.“', 'Gewitter am Abend.'),
  },
  {
    id: 'read-morgen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-vorhersage',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Und morgen?',
    options: ['Es wird überall kühler.', 'Es wird heißer.', 'Es schneit.'],
    answer: 0,
    explanation: l('„Morgen wird es in ganz Deutschland kühler.“', '„Morgen wird es in ganz Deutschland kühler.“', 'kühler.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-vorhersage',
    type: 'listening_choice',
    topic: 'vorhersage',
    concept: 'temperature',
    skill: 'listening',
    difficulty: 2,
    audio: 'Morgen wird es sonnig bei Temperaturen bis zu dreißig Grad.',
    question: l('What’s the weather tomorrow?', 'Yarın hava nasıl?', 'Wie wird das Wetter morgen?'),
    options: ['☀️ 30 °C', '🌧️ 13 °C', '❄️ −3 °C'],
    answer: 0,
    explanation: l('„sonnig … dreißig Grad“', '„sonnig … dreißig Grad“', 'sonnig, 30 Grad.'),
  },
  {
    id: 'listen-schirm',
    type: 'listening_choice',
    topic: 'wetter',
    concept: 'weather-verb',
    skill: 'listening',
    difficulty: 1,
    audio: 'Vergiss deinen Regenschirm nicht, es regnet in Strömen!',
    question: l('What’s the weather like?', 'Hava nasıl?', 'Wie ist das Wetter?'),
    options: ['🌧️', '☀️', '❄️'],
    answer: 0,
    explanation: l('„es regnet in Strömen“ = it’s pouring.', '„es regnet in Strömen“ = bardaktan boşanırcasına yağıyor.', 'Regen.'),
  },
  {
    id: 'listen-jahreszeit',
    type: 'listening_choice',
    topic: 'jahreszeiten',
    concept: 'seasons',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich liebe diese Jahreszeit: Die Blätter sind rot und gelb, und es riecht nach Regen.',
    question: l('Which season?', 'Hangi mevsim?', 'Welche Jahreszeit?'),
    options: ['🍂 Herbst', '🌸 Frühling', '☀️ Sommer'],
    answer: 0,
    explanation: l('Red and yellow leaves → autumn.', 'Kırmızı ve sarı yapraklar → sonbahar.', 'Herbst.'),
  },
  {
    id: 'listen-glatt',
    type: 'listening_choice',
    topic: 'vorhersage',
    concept: 'cold-weather',
    skill: 'listening',
    difficulty: 2,
    audio: 'Achtung, heute Nacht friert es. Die Straßen sind morgen früh glatt.',
    question: l('What’s the warning?', 'Uyarı ne?', 'Was ist die Warnung?'),
    options: ['icy roads', 'heat', 'thunderstorm'],
    answer: 0,
    explanation: l('frieren + glatt = icy.', 'frieren + glatt = buzlu yollar.', 'glatt.'),
  },

  ...weatherDrills(),
]

export const UNIT_A2_20_WETTER_NATUR: CourseUnit = {
  level: 'A2',
  number: 20,
  slug: 'wetter-natur',
  titleDe: 'Wetter und Jahreszeiten',
  title: l('Weather and seasons', 'Hava durumu ve mevsimler', 'Wetter und Jahreszeiten'),
  goal: l(
    'By the end of this unit you can describe the weather (es regnet, es ist sonnig), understand a forecast (es wird …, Grad) and talk about seasons and plans.',
    'Bu ünitenin sonunda havayı tarif edebilir (es regnet, es ist sonnig), bir hava tahminini anlayabilir (es wird …, Grad) ve mevsimler ve planlar hakkında konuşabilirsin.',
    'Am Ende dieser Einheit sprichst du über Wetter und Jahreszeiten.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'wetter', label: l('Weather', 'Hava', 'Wetter') },
    { key: 'vorhersage', label: l('Forecast & temperature', 'Tahmin ve sıcaklık', 'Vorhersage & Temperatur') },
    { key: 'jahreszeiten', label: l('Seasons', 'Mevsimler', 'Jahreszeiten') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Talking about the weather – Germans love it!', 'Hava hakkında konuşmak – Almanlar bayılır!', 'Übers Wetter reden.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('es + weather verb or es ist + adjective', 'es + hava fiili ya da es ist + sıfat', 'es + Verb oder es ist + Adjektiv'),
          body: l(
            'Weather sentences use es. Some weather words are verbs (es regnet, es schneit, es friert, es donnert) – no „ist“! Others are adjectives (es ist sonnig, bewölkt, windig, neblig, heiß, kalt). Also: Die Sonne scheint. Es gibt ein Gewitter.',
            'Hava cümleleri es kullanır. Bazı hava kelimeleri fiildir (es regnet, es schneit, es friert, es donnert) – „ist“ yok! Diğerleri sıfattır (es ist sonnig, bewölkt, windig, neblig, heiß, kalt). Ayrıca: Die Sonne scheint. Es gibt ein Gewitter.',
            'es regnet · es ist sonnig.'
          ),
          table: {
            head: [l('Noun', 'İsim', 'Nomen'), l('Verb', 'Fiil', 'Verb'), l('Adjective', 'Sıfat', 'Adjektiv')],
            rows: [
              ['der Regen', 'es regnet', 'regnerisch'],
              ['der Schnee', 'es schneit', '–'],
              ['die Sonne', 'die Sonne scheint', 'sonnig'],
              ['der Wind', '–', 'windig'],
              ['die Wolke', '–', 'bewölkt'],
            ],
          },
        },
        {
          title: l('Forecast: es wird …', 'Tahmin: es wird …', 'Vorhersage: es wird …'),
          body: l(
            'For changes and forecasts use werden: Es wird kalt. Morgen wird es sonnig. Temperatures: Es sind 20 Grad. / Minus 5 Grad.',
            'Değişim ve tahminler için werden kullan: Es wird kalt. Morgen wird es sonnig. Sıcaklıklar: Es sind 20 Grad. / Minus 5 Grad.',
            'Es wird … · 20 Grad.'
          ),
        },
        {
          title: l('Seasons and months: im', 'Mevsimler ve aylar: im', 'Jahreszeiten und Monate: im'),
          body: l('im Frühling, im Sommer, im Herbst, im Winter · im Januar … – but am Montag, um 8 Uhr.', 'im Frühling, im Sommer, im Herbst, im Winter · im Januar … – ama am Montag, um 8 Uhr.', 'im + Jahreszeit/Monat.'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Planning a hiking trip – with the weather app.', 'Hava durumu uygulamasıyla bir yürüyüş gezisi planlamak.', 'Eine Wanderung planen.'),
      dialogue: [
        { speaker: 'Nora', de: 'Wollen wir am Samstag in die Berge fahren?', translation: l('Shall we go to the mountains on Saturday?', 'Cumartesi dağlara gidelim mi?', '') },
        { speaker: 'Ali', de: 'Gute Idee! Wie wird das Wetter? Schau mal in die App.', translation: l('Good idea! What will the weather be like? Check the app.', 'İyi fikir! Hava nasıl olacak? Uygulamaya bir bak.', '') },
        { speaker: 'Nora', de: 'Samstag: Am Morgen **ist es neblig**, aber mittags **scheint die Sonne**. 18 **Grad**.', translation: l('Saturday: foggy in the morning, but sunny at noon. 18 degrees.', 'Cumartesi: Sabah sisli, ama öğlen güneşli. 18 derece.', '') },
        { speaker: 'Ali', de: 'Perfekt. Und am Sonntag?', translation: l('Perfect. And on Sunday?', 'Mükemmel. Ya pazar?', '') },
        { speaker: 'Nora', de: 'Sonntag **regnet es** den ganzen Tag, und am Abend **gibt es** ein **Gewitter**.', translation: l('On Sunday it rains all day, and in the evening there’s a thunderstorm.', 'Pazar bütün gün yağmur yağıyor, akşam da fırtına var.', '') },
        { speaker: 'Ali', de: 'Dann lieber Samstag. In den Bergen **wird es** schnell kalt – nimm eine Jacke mit!', translation: l('Then Saturday is better. It gets cold quickly in the mountains – take a jacket!', 'O zaman cumartesi daha iyi. Dağlarda hava çabuk soğuyor – yanına ceket al!', '') },
      ],
      examples: [
        { de: 'Es **regnet**.', translation: l('It’s raining.', 'Yağmur yağıyor.', '') },
        { de: 'Es **ist sonnig** und warm.', translation: l('It’s sunny and warm.', 'Hava güneşli ve sıcak.', '') },
        { de: 'Die Sonne **scheint**.', translation: l('The sun is shining.', 'Güneş parlıyor.', '') },
        { de: 'Morgen **wird es** kälter.', translation: l('Tomorrow it will be colder.', 'Yarın hava daha soğuk olacak.', '') },
        { de: 'Es sind **minus fünf Grad**.', translation: l('It’s minus five degrees.', 'Eksi beş derece.', '') },
        { de: '**Im** Winter schneit es oft.', translation: l('In winter it often snows.', 'Kışın sık sık kar yağar.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Weather and seasons.', 'Hava ve mevsimler.', 'Wetter und Jahreszeiten.'),
      exercises: ['wetter-regen', 'wetter-sonne', 'match-noun-adj', 'sort-jahreszeit', 'mc-im', 'mc-wird', 'tf-minus', 'select-kalt', 'wetter-schnee'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about the weather and make plans.', 'Hava hakkında konuş ve plan yap.', 'Rede übers Wetter.'),
      exercises: [
        'fill-regnet',
        'fill-scheint',
        'fill-grad',
        'build-vorhersage',
        'build-wenn',
        'build-lieblings',
        'fix-ist-regnet',
        'fix-sonne',
        'fix-am-winter',
        'tr-schneit',
        'tr-wird',
        'ordering-tag',
        'dialog-wetter',
        'dialog-ausflug',
        'wetter-wolken',
        'wetter-wind',
        'wetter-nebel',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Today’s weather forecast.', 'Bugünün hava tahmini.', 'Die Wettervorhersage.'),
      passage: [
        '**Das Wetter heute:** Im Norden **ist es bewölkt und windig**, ab und zu **regnet es**. Höchstwerte: 14 Grad.',
        'Im Süden **scheint die Sonne** bei bis zu 24 Grad. Am Abend kann es im Süden **Gewitter** geben.',
        'In der Nacht **wird es** kühl: 5 bis 10 Grad.',
        '**Und morgen?** Morgen **wird es** in ganz Deutschland kühler und regnerisch. Vergessen Sie Ihren Schirm nicht!',
      ],
      glossary: [
        { de: 'ab und zu', note: l('now and then', 'arada sırada', 'manchmal') },
        { de: 'der Höchstwert', note: l('maximum (temperature)', 'en yüksek değer', 'höchste Temperatur') },
        { de: 'kühl', note: l('cool', 'serin', 'ein bisschen kalt') },
      ],
      exercises: ['read-heute', 'read-sueden', 'read-gewitter', 'read-morgen'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Weather reports and small talk.', 'Hava raporları ve sohbet.', 'Wetterberichte und Smalltalk.'),
      exercises: ['listen-vorhersage', 'listen-schirm', 'listen-jahreszeit', 'listen-glatt'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe the weather in your home country in different seasons – and your favourite season.', 'Memleketindeki havayı farklı mevsimlerde anlat – ve en sevdiğin mevsimi.', 'Beschreib das Wetter in deinem Heimatland.'),
      points: [
        l('Summer: „Im Sommer ist es …“', 'Yaz: „Im Sommer ist es …“', 'Sommer'),
        l('Winter: „Im Winter … es …“', 'Kış: „Im Winter … es …“', 'Winter'),
        l('Today’s weather where you are', 'Bugün bulunduğun yerdeki hava', 'Heute'),
        l('Your favourite season and why (weil …)', 'En sevdiğin mevsim ve neden (weil …)', 'Lieblingsjahreszeit'),
      ],
      model: [
        'In der Türkei ist es im Sommer sehr heiß, oft über 35 Grad.',
        'Im Winter regnet es viel, und in den Bergen schneit es.',
        'Heute ist es hier in Hamburg bewölkt und windig.',
        'Meine Lieblingsjahreszeit ist der Frühling, weil alles grün wird.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a postcard from a holiday (at least 4 sentences): describe the weather and what you do.',
        'Tatilden bir kartpostal yaz (en az 4 cümle): havayı ve ne yaptığını anlat.',
        'Schreib eine Urlaubskarte (mindestens 4 Sätze) mit Wetter.'
      ),
      minSentences: 4,
      checks: [
        { label: l('A weather verb (regnet, schneit, scheint)', 'Bir hava fiili (regnet, schneit, scheint)', 'Ein Wetterverb'), pattern: '\\b(regnet|schneit|scheint|friert|donnert|geregnet|geschneit|geschienen)\\b' },
        { label: l('es ist + adjective (sonnig, windig …)', 'es ist + sıfat (sonnig, windig …)', 'es ist + Adjektiv'), pattern: '\\b(ist|war) (es )?(sehr |total |ziemlich )?(sonnig|bewölkt|windig|neblig|heiß|warm|kalt|kühl|regnerisch)\\b' },
        { label: l('A temperature (… Grad)', 'Bir sıcaklık (… Grad)', 'Eine Temperatur'), pattern: '\\b(\\d+|\\p{Ll}+) Grad\\b' },
      ],
      model: [
        'Liebe Mama, viele Grüße aus Mallorca!',
        'Das Wetter ist super: Es ist sonnig und heiß, jeden Tag 30 Grad.',
        'Nur gestern Abend hat es ein bisschen geregnet.',
        'Wir gehen jeden Tag schwimmen und essen viel Eis.',
        'Bis bald, deine Sara',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Weather – 60 seconds.', 'Hava – 60 saniye.', 'Wetter – 60 Sekunden.'),
      seconds: 60,
      pool: [...WEATHER.map(([id]) => `wetter-${id}`), 'mc-im', 'mc-wird'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('es regnet / es schneit (verbs, no ist)', 'es regnet / es schneit (fiil, ist yok)', 'Wetterverben'),
      l('es ist sonnig, bewölkt, windig, neblig', 'es ist sonnig, bewölkt, windig, neblig', 'es ist + Adjektiv'),
      l('Forecast: es wird … · 20 Grad · minus 5 Grad', 'Tahmin: es wird … · 20 Grad · minus 5 Grad', 'Vorhersage'),
      l('im Frühling / Sommer / Herbst / Winter', 'im Frühling / Sommer / Herbst / Winter', 'Jahreszeiten'),
    ],
    mistakes: [
      { wrong: 'Es ist regnet.', right: 'Es regnet.', note: l('regnen is a verb.', 'regnen bir fiildir.', 'Verb.') },
      { wrong: 'Es ist Sonne.', right: 'Es ist sonnig.', note: l('Adjective: sonnig.', 'Sıfat: sonnig.', 'sonnig.') },
      { wrong: 'Am Sommer …', right: 'Im Sommer …', note: l('Seasons → im.', 'Mevsimler → im.', 'im.') },
      { wrong: '20 Grade', right: '20 Grad', note: l('No plural ending.', 'Çoğul eki yok.', 'Grad.') },
    ],
  },
}
