import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'neu', emoji: '✨', translation: l('new', 'yeni', 'neu'), example: 'Der neue Kollege heißt Max.' },
  { word: 'alt', emoji: '🏚️', translation: l('old', 'eski, yaşlı', 'alt'), example: 'Das alte Haus ist sehr schön.' },
  { word: 'groß', emoji: '🦒', translation: l('big, tall', 'büyük, uzun boylu', 'groß'), example: 'Die große Frau ist meine Chefin.' },
  { word: 'klein', emoji: '🐭', translation: l('small', 'küçük', 'klein'), example: 'Ich nehme die kleine Tasche.' },
  { word: 'jung', emoji: '🧒', translation: l('young', 'genç', 'jung'), example: 'Der junge Mann arbeitet im Café.' },
  { word: 'freundlich', emoji: '😊', translation: l('friendly', 'güler yüzlü', 'nett'), example: 'Die freundliche Nachbarin hilft mir.' },
  { word: 'lustig', emoji: '😂', translation: l('funny', 'komik, eğlenceli', 'witzig'), example: 'Der lustige Film war super.' },
  { word: 'ruhig', emoji: '🤫', translation: l('quiet, calm', 'sakin', 'still'), example: 'Ich mag die ruhige Kollegin.' },
  { word: 'blond', emoji: '👱', translation: l('blond', 'sarışın', 'blond'), example: 'Das blonde Mädchen ist meine Nichte.' },
  { word: 'lang', emoji: '📏', translation: l('long', 'uzun', 'lang'), example: 'Die Frau mit den langen Haaren ist Lisa.' },
  { word: 'kurz', emoji: '✂️', translation: l('short', 'kısa', 'kurz'), example: 'Der Mann mit den kurzen Haaren ist Tim.' },
  { word: 'nett', emoji: '🤗', translation: l('nice, kind', 'kibar, hoş', 'freundlich'), example: 'Mit dem netten Chef arbeite ich gern.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Kollege', gender: 'm', plural: 'die Kollegen', translation: l('colleague (m)', 'iş arkadaşı (erkek)', 'Kollege') },
  { word: 'Kollegin', gender: 'f', plural: 'die Kolleginnen', translation: l('colleague (f)', 'iş arkadaşı (kadın)', 'Kollegin') },
  { word: 'Chef', gender: 'm', plural: 'die Chefs', translation: l('boss (m)', 'patron (erkek)', 'Chef') },
  { word: 'Chefin', gender: 'f', plural: 'die Chefinnen', translation: l('boss (f)', 'patron (kadın)', 'Chefin') },
  { word: 'Büro', gender: 'n', plural: 'die Büros', translation: l('office', 'ofis', 'Büro') },
  { word: 'Mann', gender: 'm', plural: 'die Männer', translation: l('man', 'adam', 'Mann') },
  { word: 'Frau', gender: 'f', plural: 'die Frauen', translation: l('woman', 'kadın', 'Frau') },
  { word: 'Mädchen', gender: 'n', plural: 'die Mädchen', translation: l('girl', 'kız çocuğu', 'Mädchen') },
  { word: 'Brille', gender: 'f', plural: 'die Brillen', translation: l('glasses', 'gözlük', 'Brille') },
  { word: 'Haare', translation: l('hair (plural)', 'saç (çoğul)', 'Haare') },
]

/** [id, sentence with ___ for the ending, adjective stem, right ending, case label] */
const ENDING_DRILLS: [string, string, string, 'e' | 'en', string][] = [
  ['nom-m', 'Der neu___ Kollege kommt aus Spanien.', 'neu', 'e', 'Nominativ maskulin'],
  ['nom-f', 'Die nett___ Nachbarin heißt Frau Kaya.', 'nett', 'e', 'Nominativ feminin'],
  ['nom-n', 'Das klein___ Büro ist im ersten Stock.', 'klein', 'e', 'Nominativ neutral'],
  ['akk-m', 'Kennst du den neu___ Chef?', 'neu', 'en', 'Akkusativ maskulin'],
  ['akk-f', 'Ich nehme die rot___ Jacke.', 'rot', 'e', 'Akkusativ feminin'],
  ['akk-n', 'Wir kaufen das groß___ Sofa.', 'groß', 'e', 'Akkusativ neutral'],
  ['dat-m', 'Ich spreche mit dem jung___ Mann.', 'jung', 'en', 'Dativ maskulin'],
  ['dat-f', 'Er arbeitet mit der freundlich___ Kollegin.', 'freundlich', 'en', 'Dativ feminin'],
  ['dat-n', 'Wir helfen dem klein___ Mädchen.', 'klein', 'en', 'Dativ neutral'],
  ['pl', 'Die alt___ Fotos sind schön.', 'alt', 'en', 'Plural'],
]

function endingDrills(): Exercise[] {
  return ENDING_DRILLS.map(([id, sentence, stem, ending, label], i) => {
    const options = [`${stem}e`, `${stem}en`, `${stem}er`]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const prompt = sentence.replace(`${stem}___`, '___')
    return {
      id: `adj-${id}`,
      type: 'multiple_choice' as const,
      topic: ending === 'e' ? 'ending-e' : 'ending-en',
      concept: `adj-def-${id}`,
      skill: 'grammar' as const,
      difficulty: (id.startsWith('nom') ? 1 : 2) as 1 | 2,
      prompt,
      options: ordered,
      answer: ordered.indexOf(`${stem}${ending}`),
      explanation: l(
        `${label} after der/die/das → -${ending}.`,
        `der/die/das sonrası ${label} → -${ending}.`,
        `${label} → -${ending}.`
      ),
      examples: [sentence.replace('___', `**${ending}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-opposites',
    type: 'matching',
    topic: 'describe',
    concept: 'adjective-pairs',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Find the opposites.', 'Zıt anlamlıları bul.', 'Finde die Gegenteile.'),
    pairs: [
      { left: 'alt', right: 'jung' },
      { left: 'groß', right: 'klein' },
      { left: 'lang', right: 'kurz' },
      { left: 'laut', right: 'ruhig' },
      { left: 'unfreundlich', right: 'nett' },
    ],
    explanation: l('alt ↔ jung (people) / neu (things), groß ↔ klein, lang ↔ kurz, laut ↔ ruhig.', 'alt ↔ jung (insan) / neu (eşya), groß ↔ klein, lang ↔ kurz, laut ↔ ruhig.', 'Gegenteile.'),
  },
  {
    id: 'sort-e-en',
    type: 'categorize',
    topic: 'ending-e',
    concept: 'e-or-en',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Ending -e or -en?', '-e mi -en mi?', 'Endung -e oder -en?'),
    categories: ['-e', '-en'],
    items: [
      { text: 'der neu… Chef (Nom.)', category: 0 },
      { text: 'den neu… Chef (Akk.)', category: 1 },
      { text: 'die neu… Chefin (Nom.)', category: 0 },
      { text: 'mit der neu… Chefin', category: 1 },
      { text: 'das neu… Büro (Akk.)', category: 0 },
      { text: 'die neu… Kollegen (Pl.)', category: 1 },
    ],
    explanation: l(
      '-e: der/die/das in the Nominativ, die/das in the Akkusativ. Everything else (den, dem, der in Dativ, plural) → -en.',
      '-e: Nominativ’de der/die/das, Akkusativ’de die/das. Geri kalan her şey (den, dem, Dativ’de der, çoğul) → -en.',
      '-e: 5 Formen. Sonst -en.'
    ),
    practice: ['adj-akk-m', 'adj-dat-f'],
  },
  {
    id: 'select-en',
    type: 'multiple_select',
    topic: 'ending-en',
    concept: 'e-or-en',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which forms are correct? Select all.', 'Hangi biçimler doğru? Hepsini seç.', 'Welche Formen sind richtig? Wähle alle.'),
    options: ['mit dem alten Auto', 'den alte Mann', 'die netten Leute', 'das kleine Kind', 'der jungen Mann (Nom.)', 'die neue Wohnung'],
    answers: [0, 2, 3, 5],
    explanation: l('den alten Mann (Akk m → -en), der junge Mann (Nom → -e).', 'den alten Mann (Akk eril → -en), der junge Mann (Nom → -e).', 'den alten Mann, der junge Mann.'),
  },
  {
    id: 'tf-plural',
    type: 'true_false',
    topic: 'ending-en',
    concept: 'adj-def-pl',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Im Plural (die …) ist die Endung immer -en.',
    answer: true,
    explanation: l('die neuen Kollegen, die alten Fotos – plural after die is always -en.', 'die neuen Kollegen, die alten Fotos – die’den sonra çoğul her zaman -en.', 'Plural: -en.'),
    examples: ['die **neuen** Kollegen'],
  },
  {
    id: 'image-brille',
    type: 'image_choice',
    topic: 'describe',
    concept: 'describe-people',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'der Mann mit der Brille und den kurzen Haaren',
    options: [
      { emoji: '👨‍🦰', label: 'rote Haare' },
      { emoji: '🧔', label: 'Bart' },
      { emoji: '👨‍🦲', label: 'keine Haare' },
      { emoji: '🤓', label: 'Brille' },
    ],
    answer: 3,
    explanation: l('die Brille = glasses 🤓.', 'die Brille = gözlük 🤓.', 'die Brille.'),
  },
  {
    id: 'mc-welcher',
    type: 'multiple_choice',
    topic: 'describe',
    concept: 'welcher',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Welche Jacke nimmst du? – Die ___.',
    options: ['blaue', 'blauen', 'blau'],
    answer: 0,
    explanation: l('Die (Jacke) blaue – Akkusativ feminin → -e. The noun can be left out.', 'Die (Jacke) blaue – Akkusativ dişil → -e. İsim söylenmeyebilir.', 'Die blaue.'),
    examples: ['Welche Jacke? – **Die blaue**.'],
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-akk-m',
    type: 'fill_blank',
    topic: 'ending-en',
    concept: 'adj-def-akk-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Hast du den lustig___ Film gesehen?',
    accepted: ['en'],
    base: '-e / -en',
    explanation: l('den (Akk m) → -en: den lustigen Film.', 'den (Akk eril) → -en: den lustigen Film.', 'den lustigen Film.'),
    examples: ['Hast du den **lustigen** Film gesehen?'],
  },
  {
    id: 'fill-nom-f',
    type: 'fill_blank',
    topic: 'ending-e',
    concept: 'adj-def-nom-f',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Die ruhig___ Kollegin heißt Petra.',
    accepted: ['e'],
    base: '-e / -en',
    explanation: l('die (Nom f) → -e.', 'die (Nom dişil) → -e.', 'die ruhige Kollegin.'),
    examples: ['Die **ruhige** Kollegin heißt Petra.'],
  },
  {
    id: 'fill-dat',
    type: 'fill_blank',
    topic: 'ending-en',
    concept: 'adj-def-dat',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich wohne in dem groß___ Haus an der Ecke.',
    accepted: ['en'],
    base: '-e / -en',
    explanation: l('dem (Dativ) → always -en.', 'dem (Dativ) → her zaman -en.', 'dem großen Haus.'),
    examples: ['Ich wohne in dem **großen** Haus.'],
  },
  {
    id: 'build-chef',
    type: 'sentence_builder',
    topic: 'ending-en',
    concept: 'adj-def-akk-m',
    skill: 'grammar',
    difficulty: 2,
    chips: ['nicht', 'neuen', 'Ich', 'kenne', 'den', 'Chef'],
    answers: [['Ich', 'kenne', 'den', 'neuen', 'Chef', 'nicht']],
    translation: l('I don’t know the new boss.', 'Yeni patronu tanımıyorum.', 'Ich kenne den neuen Chef nicht.'),
    explanation: l('Article – adjective – noun. den → -en.', 'Artikel – sıfat – isim. den → -en.', 'den neuen Chef.'),
    examples: ['Ich kenne **den neuen** Chef nicht.'],
  },
  {
    id: 'build-frau',
    type: 'sentence_builder',
    topic: 'describe',
    concept: 'describe-people',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ist', 'mit', 'langen', 'den', 'Haaren', 'Die Frau', 'meine Schwester'],
    answers: [['Die Frau', 'mit', 'den', 'langen', 'Haaren', 'ist', 'meine Schwester']],
    translation: l('The woman with the long hair is my sister.', 'Uzun saçlı kadın benim kız kardeşim.', 'Die Frau mit den langen Haaren ist meine Schwester.'),
    explanation: l('mit + Dativ plural: den langen Haaren.', 'mit + Dativ çoğul: den langen Haaren.', 'mit den langen Haaren.'),
    examples: ['Die Frau **mit den langen Haaren** ist meine Schwester.'],
  },
  {
    id: 'build-welches',
    type: 'sentence_builder',
    topic: 'describe',
    concept: 'welcher',
    skill: 'grammar',
    difficulty: 2,
    chips: ['dir', 'gefällt', 'Welches', 'besser', 'Kleid'],
    answers: [['Welches', 'Kleid', 'gefällt', 'dir', 'besser']],
    end: '?',
    translation: l('Which dress do you like better?', 'Hangi elbiseyi daha çok beğendin?', 'Welches Kleid gefällt dir besser?'),
    explanation: l('welcher/welche/welches works like der/die/das.', 'welcher/welche/welches der/die/das gibi çekimlenir.', 'welches Kleid (das Kleid).'),
    examples: ['**Welches** Kleid gefällt dir besser?'],
  },
  {
    id: 'fix-den-neue',
    type: 'error_correction',
    topic: 'ending-en',
    concept: 'adj-def-akk-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wir besuchen den neue Kollegen.',
    accepted: ['Wir besuchen den neuen Kollegen.'],
    explanation: l('den → -en: den neuen Kollegen.', 'den → -en: den neuen Kollegen.', 'den neuen Kollegen.'),
    examples: ['Wir besuchen den **neuen** Kollegen.'],
  },
  {
    id: 'fix-der-alten',
    type: 'error_correction',
    topic: 'ending-e',
    concept: 'adj-def-nom-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Der alten Mann wohnt neben uns.',
    accepted: ['Der alte Mann wohnt neben uns.'],
    explanation: l('Nominativ der → -e: der alte Mann.', 'Nominativ der → -e: der alte Mann.', 'der alte Mann.'),
    examples: ['Der **alte** Mann wohnt neben uns.'],
  },
  {
    id: 'fix-mit-der',
    type: 'error_correction',
    topic: 'ending-en',
    concept: 'adj-def-dat',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich telefoniere mit der nette Chefin.',
    accepted: ['Ich telefoniere mit der netten Chefin.'],
    explanation: l('mit + Dativ: der netten Chefin (-en).', 'mit + Dativ: der netten Chefin (-en).', 'mit der netten Chefin.'),
    examples: ['Ich telefoniere mit der **netten** Chefin.'],
  },
  {
    id: 'tr-neue',
    type: 'translation',
    topic: 'ending-e',
    concept: 'adj-def-nom-f',
    skill: 'writing',
    difficulty: 2,
    source: l('The new flat is very big.', 'Yeni daire çok büyük.', 'The new flat is very big.'),
    accepted: ['Die neue Wohnung ist sehr groß.'],
    explanation: l('Before a noun: die neue Wohnung. After sein: … ist groß (no ending).', 'İsimden önce: die neue Wohnung. sein’den sonra: … ist groß (ek yok).', 'die neue Wohnung … ist groß.'),
    examples: ['Die **neue** Wohnung ist sehr **groß**.'],
  },
  {
    id: 'tr-den-roten',
    type: 'translation',
    topic: 'ending-en',
    concept: 'adj-def-akk-m',
    skill: 'writing',
    difficulty: 2,
    source: l('I’ll take the red pullover.', 'Kırmızı kazağı alıyorum.', 'I’ll take the red pullover.'),
    accepted: ['Ich nehme den roten Pullover.'],
    explanation: l('der Pullover → Akk: den roten Pullover.', 'der Pullover → Akk: den roten Pullover.', 'den roten Pullover.'),
    examples: ['Ich nehme den **roten** Pullover.'],
  },
  {
    id: 'mc-predicative',
    type: 'multiple_choice',
    topic: 'ending-e',
    concept: 'predicative',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Der Film ist ___.',
    options: ['lustig', 'lustige', 'lustigen'],
    answer: 0,
    explanation: l('After sein (no noun after it) the adjective has no ending.', 'sein’den sonra (arkasında isim yoksa) sıfat ek almaz.', 'ist lustig – keine Endung.'),
    examples: ['Der Film ist **lustig**. – Der **lustige** Film.'],
  },
  {
    id: 'dialog-wer',
    type: 'dialogue',
    topic: 'describe',
    concept: 'describe-people',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Wer ist das?' }],
    options: ['Das ist der neue Praktikant aus Polen.', 'Das ist der neuen Praktikant aus Polen.', 'Das ist den neue Praktikant aus Polen.'],
    answer: 0,
    explanation: l('Nominativ der → -e.', 'Nominativ der → -e.', 'der neue Praktikant.'),
  },
  {
    id: 'dialog-welche',
    type: 'dialogue',
    topic: 'ending-en',
    concept: 'welcher',
    skill: 'grammar',
    difficulty: 2,
    lines: [
      { speaker: 'Verkäufer', de: 'Welche Schuhe möchten Sie anprobieren?' },
    ],
    options: ['Die schwarzen, bitte.', 'Die schwarze, bitte.', 'Den schwarzen, bitte.'],
    answer: 0,
    explanation: l('die Schuhe (plural) → die schwarzen.', 'die Schuhe (çoğul) → die schwarzen.', 'die schwarzen.'),
  },
  {
    id: 'ordering-beschreibung',
    type: 'ordering',
    topic: 'describe',
    concept: 'describe-order',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Build the noun phrase in the right order.', 'İsim öbeğini doğru sırayla kur.', 'Bilde die Nominalgruppe in der richtigen Reihenfolge.'),
    items: ['Kollegin', 'mit', 'die', 'Brille', 'der', 'neue'],
    answer: ['die', 'neue', 'Kollegin', 'mit', 'der', 'Brille'],
    explanation: l('article – adjective – noun – (mit + Dativ).', 'artikel – sıfat – isim – (mit + Dativ).', 'die neue Kollegin mit der Brille.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-chef',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-team',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie ist der neue Chef?',
    options: ['Ruhig und sehr freundlich.', 'Laut und streng.', 'Jung und lustig.'],
    answer: 0,
    explanation: l('„Der neue Chef ist ruhig und sehr freundlich.“', '„Der neue Chef ist ruhig und sehr freundlich.“', '„ruhig und sehr freundlich“'),
  },
  {
    id: 'read-mittag',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-team',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Mit wem isst Amira mittags?',
    options: ['Mit der lustigen Kollegin aus Brasilien.', 'Mit dem neuen Chef.', 'Mit dem jungen Praktikanten.'],
    answer: 0,
    explanation: l('„Mittags esse ich mit der lustigen Kollegin aus Brasilien.“', '„Mittags esse ich mit der lustigen Kollegin aus Brasilien.“', '„mit der lustigen Kollegin“'),
  },
  {
    id: 'read-buero',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-team',
    skill: 'reading',
    difficulty: 2,
    statement: 'Amira findet das kleine Büro schlecht.',
    answer: false,
    explanation: l('„Das kleine Büro ist hell und gemütlich.“', '„Das kleine Büro ist hell und gemütlich.“', '„hell und gemütlich“'),
  },
  {
    id: 'read-problem',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-team',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist das Problem?',
    options: ['Die alte Kaffeemaschine funktioniert nicht.', 'Der Chef ist unfreundlich.', 'Das Büro ist zu laut.'],
    answer: 0,
    explanation: l('„Nur die alte Kaffeemaschine funktioniert nie!“', '„Nur die alte Kaffeemaschine funktioniert nie!“', '„die alte Kaffeemaschine“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-ending',
    type: 'listening_choice',
    topic: 'ending-en',
    concept: 'adj-def-akk-m',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich suche den blauen Rucksack.',
    question: l('Which ending do you hear?', 'Hangi eki duyuyorsun?', 'Welche Endung hörst du?'),
    options: ['blauen', 'blaue', 'blauer'],
    answer: 0,
    explanation: l('„den blauen“', '„den blauen“', '„den blauen“'),
  },
  {
    id: 'listen-wer',
    type: 'listening_choice',
    topic: 'describe',
    concept: 'describe-people',
    skill: 'listening',
    difficulty: 1,
    audio: 'Der Mann mit dem Bart ist mein Onkel.',
    question: l('Who is the uncle?', 'Amca hangisi?', 'Wer ist der Onkel?'),
    options: ['🧔', '👱', '👨‍🦲'],
    answer: 0,
    explanation: l('der Bart = beard 🧔.', 'der Bart = sakal 🧔.', 'der Bart.'),
  },
  {
    id: 'listen-welche',
    type: 'listening_choice',
    topic: 'describe',
    concept: 'welcher',
    skill: 'listening',
    difficulty: 2,
    audio: 'Nein, nicht die kleine Tasche. Ich möchte die große, schwarze.',
    question: l('Which bag does the person want?', 'Kişi hangi çantayı istiyor?', 'Welche Tasche möchte die Person?'),
    options: ['die große schwarze', 'die kleine', 'die große rote'],
    answer: 0,
    explanation: l('„die große, schwarze“', '„die große, schwarze“', '„die große, schwarze“'),
  },
  {
    id: 'listen-mit',
    type: 'listening_choice',
    topic: 'ending-en',
    concept: 'adj-def-dat',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich fahre am liebsten mit dem alten Fahrrad.',
    question: l('Which bike?', 'Hangi bisiklet?', 'Welches Fahrrad?'),
    options: ['das alte', 'das neue', 'das rote'],
    answer: 0,
    explanation: l('„mit dem alten Fahrrad“', '„mit dem alten Fahrrad“', '„dem alten“'),
  },

  ...endingDrills(),
]

export const UNIT_A2_05_ADJEKTIVE_DER: CourseUnit = {
  level: 'A2',
  number: 5,
  slug: 'adjektive-der',
  titleDe: 'Der neue Kollege',
  title: l('The new colleague', 'Yeni iş arkadaşı', 'Der neue Kollege'),
  goal: l(
    'By the end of this unit you can describe people and things with adjectives after der/die/das: der neue Kollege, den neuen Kollegen, mit dem neuen Kollegen.',
    'Bu ünitenin sonunda der/die/das’dan sonra sıfatlarla insanları ve eşyaları tarif edebilirsin: der neue Kollege, den neuen Kollegen, mit dem neuen Kollegen.',
    'Am Ende dieser Einheit beschreibst du Personen und Dinge mit Adjektiven nach dem bestimmten Artikel.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'ending-e', label: l('Ending -e', '-e eki', 'Endung -e') },
    { key: 'ending-en', label: l('Ending -en', '-en eki', 'Endung -en') },
    { key: 'describe', label: l('Describing people', 'İnsanları tarif etmek', 'Personen beschreiben') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Twelve adjectives to describe people and things.', 'İnsanları ve eşyaları tarif etmek için on iki sıfat.', 'Zwölf Adjektive.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Only two endings: -e or -en', 'Yalnızca iki ek: -e ya da -en', 'Nur zwei Endungen: -e oder -en'),
          body: l(
            'After der, die, das (and dieser, welcher) the adjective ends in -e in five places – everywhere else in -en.',
            'der, die, das’dan (ve dieser, welcher’den) sonra sıfat beş yerde -e alır – geri kalan her yerde -en.',
            'Fünfmal -e, sonst -en.'
          ),
          table: {
            head: [l('', '', ''), l('maskulin', 'eril', 'maskulin'), l('feminin', 'dişil', 'feminin'), l('neutral', 'nötr', 'neutral'), l('Plural', 'çoğul', 'Plural')],
            rows: [
              ['Nom.', 'der neue Chef', 'die neue Chefin', 'das neue Büro', 'die neuen Kollegen'],
              ['Akk.', 'den neuen Chef', 'die neue Chefin', 'das neue Büro', 'die neuen Kollegen'],
              ['Dat.', 'dem neuen Chef', 'der neuen Chefin', 'dem neuen Büro', 'den neuen Kollegen'],
            ],
          },
          tip: l(
            'Memory trick: -e only where the article is der/die/das in the Nominativ or die/das in the Akkusativ.',
            'Hafıza hilesi: -e yalnızca Nominativ’de der/die/das ya da Akkusativ’de die/das varsa.',
            'Merke: -e nur bei der/die/das (Nom.) und die/das (Akk.).'
          ),
        },
        {
          title: l('Before the noun vs. after sein', 'İsimden önce ve sein’den sonra', 'Vor dem Nomen – nach sein'),
          body: l(
            'Only an adjective before a noun gets an ending. After sein, werden, finden it stays without an ending: Der Chef ist nett. – Der nette Chef.',
            'Yalnızca isimden önceki sıfat ek alır. sein, werden, finden’den sonra eksiz kalır: Der Chef ist nett. – Der nette Chef.',
            'Der Chef ist nett. – der nette Chef.'
          ),
        },
        {
          title: l('welcher? – dieser', 'welcher? – dieser', 'welcher? – dieser'),
          body: l(
            'welcher/welche/welches (which?) and dieser/diese/dieses (this) have the same endings as der/die/das – and so do the adjectives after them.',
            'welcher/welche/welches (hangi?) ve dieser/diese/dieses (bu) der/die/das ile aynı ekleri alır – arkalarındaki sıfatlar da öyle.',
            'welcher/dieser wie der/die/das.'
          ),
          examples: [{ de: '**Welcher** Pullover? – **Dieser** blau**e** hier.', translation: l('Which pullover? – This blue one here.', 'Hangi kazak? – Şu mavi olan.', '') }],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('First day at a new job: Amira asks her colleague Paul about the team.', 'Yeni işte ilk gün: Amira iş arkadaşı Paul’a ekibi soruyor.', 'Erster Arbeitstag: Amira fragt Paul nach dem Team.'),
      dialogue: [
        { speaker: 'Amira', de: 'Paul, wer ist **die** groß**e** Frau da?', translation: l('Paul, who is the tall woman there?', 'Paul, oradaki uzun boylu kadın kim?', '') },
        { speaker: 'Paul', de: 'Das ist Frau Berger, **die** neu**e** Chefin. Sie ist sehr nett.', translation: l('That’s Ms Berger, the new boss. She’s very nice.', 'O Bayan Berger, yeni patron. Çok kibar.', '') },
        { speaker: 'Amira', de: 'Und **der** jung**e** Mann mit **der** Brille?', translation: l('And the young man with the glasses?', 'Ya gözlüklü genç adam?', '') },
        { speaker: 'Paul', de: 'Das ist Leon, **der** neu**e** Praktikant. Kennst du schon **den** lustig**en** Kollegen aus der IT?', translation: l('That’s Leon, the new intern. Do you already know the funny colleague from IT?', 'O Leon, yeni stajyer. BT’deki komik iş arkadaşını tanıyor musun?', '') },
        { speaker: 'Amira', de: 'Nein, noch nicht. Wo ist eigentlich **das** klein**e** Büro für mich?', translation: l('No, not yet. Where is the small office for me, actually?', 'Hayır, henüz değil. Bu arada benim için olan küçük ofis nerede?', '') },
        { speaker: 'Paul', de: 'Da hinten, neben **dem** groß**en** Besprechungsraum. Komm, ich zeige es dir!', translation: l('Back there, next to the big meeting room. Come, I’ll show you!', 'Şurada arkada, büyük toplantı odasının yanında. Gel, sana göstereyim!', '') },
      ],
      examples: [
        { de: '**Der** neu**e** Kollege kommt aus Spanien.', translation: l('The new colleague is from Spain.', 'Yeni iş arkadaşı İspanya’dan.', '') },
        { de: 'Kennst du **den** neu**en** Kollegen?', translation: l('Do you know the new colleague?', 'Yeni iş arkadaşını tanıyor musun?', '') },
        { de: 'Ich arbeite mit **dem** neu**en** Kollegen.', translation: l('I work with the new colleague.', 'Yeni iş arkadaşıyla çalışıyorum.', '') },
        { de: '**Die** freundlich**e** Chefin hilft mir.', translation: l('The friendly boss helps me.', 'Güler yüzlü patron bana yardım ediyor.', '') },
        { de: 'Ich nehme **das** klein**e** Büro.', translation: l('I’ll take the small office.', 'Küçük ofisi alıyorum.', '') },
        { de: '**Die** neu**en** Kollegen sind nett.', translation: l('The new colleagues are nice.', 'Yeni iş arkadaşları kibar.', '') },
        { de: 'Der Kaffee ist **heiß**.', translation: l('The coffee is hot. (no ending after sein)', 'Kahve sıcak. (sein’den sonra ek yok)', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('-e or -en?', '-e mi -en mi?', '-e oder -en?'),
      exercises: ['match-opposites', 'sort-e-en', 'adj-nom-m', 'adj-akk-m', 'select-en', 'tf-plural', 'image-brille', 'adj-dat-f', 'mc-welcher', 'mc-predicative'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Describe people and things.', 'İnsanları ve eşyaları tarif et.', 'Beschreibe Personen und Dinge.'),
      exercises: [
        'fill-akk-m',
        'fill-nom-f',
        'fill-dat',
        'build-chef',
        'build-frau',
        'build-welches',
        'fix-den-neue',
        'fix-der-alten',
        'fix-mit-der',
        'tr-neue',
        'tr-den-roten',
        'dialog-wer',
        'dialog-welche',
        'ordering-beschreibung',
        'adj-pl',
        'adj-dat-n',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Amira writes to a friend about her new job.', 'Amira bir arkadaşına yeni işini anlatıyor.', 'Amira schreibt über ihre neue Arbeit.'),
      passage: [
        'Liebe Jana, die erste Woche im neuen Job ist vorbei! **Der neue Chef** ist ruhig und sehr freundlich.',
        '**Das kleine Büro** ist hell und gemütlich. Ich sitze am Fenster, neben **der netten Kollegin** aus der Buchhaltung.',
        'Mittags esse ich mit **der lustigen Kollegin** aus Brasilien. Sie kennt **die besten Restaurants** in der Gegend!',
        'Nur **die alte Kaffeemaschine** funktioniert nie! Aber sonst bin ich sehr zufrieden. Liebe Grüße, Amira',
      ],
      glossary: [
        { de: 'vorbei', note: l('over, finished', 'bitti, geçti', 'zu Ende') },
        { de: 'die Buchhaltung', note: l('accounting', 'muhasebe', 'Finanzabteilung') },
        { de: 'die Gegend', note: l('area, neighbourhood', 'civar, bölge', 'Umgebung') },
        { de: 'zufrieden', note: l('satisfied', 'memnun', 'glücklich mit etwas') },
      ],
      exercises: ['read-chef', 'read-buero', 'read-mittag', 'read-problem'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for the endings – and who or what is meant.', 'Eklere – ve kimin ya da neyin kastedildiğine – kulak ver.', 'Hör auf die Endungen.'),
      exercises: ['listen-ending', 'listen-wer', 'listen-welche', 'listen-mit'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe three people at your work, school or in your family.', 'İşyerinden, okulundan ya da ailenden üç kişiyi tarif et.', 'Beschreib drei Personen aus Arbeit, Schule oder Familie.'),
      points: [
        l('Who? „Der/Die … ist …“', 'Kim? „Der/Die … ist …“', 'Wer?'),
        l('Looks: „der Mann mit den kurzen Haaren / der Brille“', 'Görünüş: „der Mann mit den kurzen Haaren / der Brille“', 'Aussehen'),
        l('Character: nett, lustig, ruhig …', 'Karakter: nett, lustig, ruhig …', 'Charakter'),
        l('Your opinion: „Ich mag den/die/das …“', 'Fikrin: „Ich mag den/die/das …“', 'Deine Meinung'),
      ],
      model: [
        'Der neue Kollege heißt Max. Er ist sehr lustig.',
        'Die Frau mit den langen Haaren ist meine Chefin. Sie ist ruhig und nett.',
        'Ich mag den jungen Praktikanten, er hilft mir oft.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write an e-mail (at least 5 sentences) about your colleagues, classmates or neighbours. Use adjectives after der/die/das.',
        'İş arkadaşların, sınıf arkadaşların ya da komşuların hakkında bir e-posta yaz (en az 5 cümle). der/die/das’dan sonra sıfat kullan.',
        'Schreib eine E-Mail (mindestens 5 Sätze) über deine Kollegen, Mitschüler oder Nachbarn.'
      ),
      minSentences: 5,
      checks: [
        { label: l('Nominativ with -e (der/die/das …e)', '-e ile Nominativ (der/die/das …e)', 'Nominativ mit -e'), pattern: '\\b([Dd]er|[Dd]ie|[Dd]as) \\p{Ll}+e \\p{Lu}' },
        { label: l('-en after den/dem (den neuen …, dem netten …)', 'den/dem’den sonra -en (den neuen …, dem netten …)', '-en nach den/dem'), pattern: '\\b(den|dem) \\p{Ll}+en \\p{Lu}' },
        { label: l('An adjective after sein (… ist nett)', 'sein’den sonra bir sıfat (… ist nett)', 'Adjektiv nach sein'), pattern: '\\b(ist|sind|bin|bist)( sehr| total| ziemlich)? \\p{Ll}+[.!,]' },
      ],
      model: [
        'Hallo Tom, meine neue Arbeit ist super!',
        'Die neue Chefin heißt Frau Lang.',
        'Sie ist sehr nett.',
        'Ich arbeite oft mit dem jungen Kollegen aus Italien.',
        'Nur den alten Computer mag ich nicht.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('-e or -en? – 60 seconds.', '-e mi -en mi? – 60 saniye.', '-e oder -en? – 60 Sekunden.'),
      seconds: 60,
      pool: [...ENDING_DRILLS.map(([id]) => `adj-${id}`), 'mc-predicative', 'mc-welcher'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('After der/die/das: -e (5×) or -en (everything else)', 'der/die/das sonrası: -e (5 kez) ya da -en (geri kalan her şey)', '-e oder -en'),
      l('den, dem, Dativ and plural → always -en', 'den, dem, Dativ ve çoğul → her zaman -en', 'den/dem/Plural → -en'),
      l('No ending after sein: Der Chef ist nett.', 'sein’den sonra ek yok: Der Chef ist nett.', 'ist nett'),
      l('welcher? dieser – like der/die/das', 'welcher? dieser – der/die/das gibi', 'welcher, dieser'),
    ],
    mistakes: [
      { wrong: 'Ich kenne den neue Kollegen.', right: 'Ich kenne den neuen Kollegen.', note: l('den → -en.', 'den → -en.', '-en.') },
      { wrong: 'Der alten Mann wohnt hier.', right: 'Der alte Mann wohnt hier.', note: l('Nom. der → -e.', 'Nom. der → -e.', '-e.') },
      { wrong: 'mit der nette Frau', right: 'mit der netten Frau', note: l('Dativ → -en.', 'Dativ → -en.', '-en.') },
      { wrong: 'Der Film ist lustige.', right: 'Der Film ist lustig.', note: l('After sein: no ending.', 'sein’den sonra: ek yok.', 'keine Endung.') },
    ],
  },
}
