import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'weil', emoji: '❓', translation: l('because (verb at the end)', 'çünkü (fiil sonda)', 'Grund, Verb am Ende'), example: 'Ich lerne Deutsch, weil ich in Wien arbeite.' },
  { word: 'denn', emoji: '➡️', translation: l('because (normal word order)', 'çünkü (normal dizilim)', 'Grund, Verb Position 2'), example: 'Ich lerne Deutsch, denn ich arbeite in Wien.' },
  { word: 'dass', emoji: '💭', translation: l('that (verb at the end)', 'ki, -dığını (fiil sonda)', 'Inhalt, Verb am Ende'), example: 'Ich glaube, dass der Kurs gut ist.' },
  { word: 'Warum?', emoji: '🤔', translation: l('Why?', 'Neden?', 'Frage nach dem Grund'), example: 'Warum lernst du Deutsch?' },
  { word: 'ich glaube, dass …', emoji: '🙂', translation: l('I think that …', 'sanırım ki …', 'Meinung'), example: 'Ich glaube, dass es morgen regnet.' },
  { word: 'ich finde, dass …', emoji: '👍', translation: l('I find / think that …', 'bence …', 'Meinung'), example: 'Ich finde, dass Deutsch schön ist.' },
  { word: 'ich weiß, dass …', emoji: '💡', translation: l('I know that …', 'biliyorum ki …', 'Wissen'), example: 'Ich weiß, dass du müde bist.' },
  { word: 'ich hoffe, dass …', emoji: '🤞', translation: l('I hope that …', 'umarım …', 'Hoffnung'), example: 'Ich hoffe, dass du bald kommst.' },
  { word: 'Es ist wichtig, dass …', emoji: '❗', translation: l('It’s important that …', '… önemli', 'Wichtigkeit'), example: 'Es ist wichtig, dass du jeden Tag übst.' },
  { word: 'der Grund', emoji: '🔍', translation: l('reason', 'sebep', 'warum'), example: 'Der Grund ist, dass ich müde bin.' },
  { word: 'deshalb', emoji: '🔁', translation: l('that’s why, therefore', 'bu yüzden', 'Folge'), example: 'Ich bin krank, deshalb bleibe ich zu Hause.' },
  { word: 'die Meinung', emoji: '🗣️', translation: l('opinion', 'fikir', 'was man denkt'), example: 'Meiner Meinung nach ist das richtig.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Kurs', gender: 'm', plural: 'die Kurse', translation: l('course', 'kurs', 'Kurs') },
  { word: 'Prüfung', gender: 'f', plural: 'die Prüfungen', translation: l('exam', 'sınav', 'Prüfung') },
  { word: 'Arbeit', gender: 'f', translation: l('work', 'iş', 'Arbeit') },
  { word: 'Zeit', gender: 'f', translation: l('time', 'zaman', 'Zeit') },
  { word: 'Stelle', gender: 'f', plural: 'die Stellen', translation: l('job, position', 'iş, pozisyon', 'Stelle') },
  { word: 'Kollege', gender: 'm', plural: 'die Kollegen', translation: l('colleague', 'iş arkadaşı', 'Kollege') },
]

/** [id, main clause, conjunction, clause parts in normal order (subject, rest…, verb)] */
const CLAUSES: [string, string, 'weil' | 'dass', string[]][] = [
  ['krank', 'Ich bleibe zu Hause,', 'weil', ['ich', 'krank', 'bin']],
  ['arbeit', 'Sie lernt Deutsch,', 'weil', ['sie', 'in Berlin', 'arbeitet']],
  ['zeit', 'Wir kommen nicht,', 'weil', ['wir', 'keine Zeit', 'haben']],
  ['kurs', 'Ich glaube,', 'dass', ['der Kurs', 'sehr gut', 'ist']],
  ['regen', 'Ich hoffe,', 'dass', ['es', 'morgen nicht', 'regnet']],
  ['muede', 'Ich weiß,', 'dass', ['du', 'müde', 'bist']],
]

function clauseDrills(): Exercise[] {
  return CLAUSES.map(([id, main, conj, parts], i) => {
    const [subject, middle, verb] = parts
    const right = `${main} ${conj} ${subject} ${middle} ${verb}.`
    const wrongA = `${main} ${conj} ${subject} ${verb} ${middle}.`
    const wrongB = `${main} ${conj} ${verb} ${subject} ${middle}.`
    const options = [right, wrongA, wrongB]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `ns-${id}`,
      type: 'multiple_choice' as const,
      topic: conj,
      concept: `${conj}-verb-end`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: `${main} ${conj} …`,
      promptL10n: l('Which sentence is correct?', 'Hangi cümle doğru?', 'Welcher Satz ist richtig?'),
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `After „${conj}“ the conjugated verb goes to the very end: … ${conj} ${subject} ${middle} ${verb}.`,
        `„${conj}“tan sonra çekimli fiil en sona gider: … ${conj} ${subject} ${middle} ${verb}.`,
        `Nach „${conj}“ steht das Verb am Ende.`
      ),
      examples: [`${main} **${conj}** ${subject} ${middle} **${verb}**.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'mc-weil-denn',
    type: 'multiple_choice',
    topic: 'weil',
    concept: 'weil-denn',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich lerne Deutsch, ___ ich arbeite in Wien.',
    options: ['denn', 'weil', 'dass'],
    answer: 0,
    explanation: l(
      'The verb „arbeite“ is in position 2 → denn. With weil the verb goes to the end: …, weil ich in Wien arbeite.',
      '„arbeite“ fiili 2. sırada → denn. weil ile fiil sona gider: …, weil ich in Wien arbeite.',
      'Verb Position 2 → denn.'
    ),
    examples: ['…, **denn** ich **arbeite** in Wien.', '…, **weil** ich in Wien **arbeite**.'],
    practice: ['sort-weil-denn'],
  },
  {
    id: 'sort-weil-denn',
    type: 'categorize',
    topic: 'weil',
    concept: 'weil-denn',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Which word fits: weil or denn?', 'Hangisi uyar: weil mi denn mi?', 'Was passt: weil oder denn?'),
    categories: ['weil', 'denn'],
    items: [
      { text: '…, ___ ich müde bin.', category: 0 },
      { text: '…, ___ ich bin müde.', category: 1 },
      { text: '…, ___ es regnet.', category: 0 },
      { text: '…, ___ es regnet heute.', category: 1 },
      { text: '…, ___ wir keine Zeit haben.', category: 0 },
      { text: '…, ___ wir haben keine Zeit.', category: 1 },
    ],
    explanation: l('weil → verb at the end. denn → normal order (verb in position 2).', 'weil → fiil sonda. denn → normal dizilim (fiil 2. sırada).', 'weil: Ende · denn: Position 2.'),
  },
  {
    id: 'match-meinung',
    type: 'matching',
    topic: 'dass',
    concept: 'dass-verbs',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the beginning and the meaning.', 'Başlangıcı anlamıyla eşleştir.', 'Ordne Satzanfang und Bedeutung zu.'),
    pairs: [
      { left: 'Ich glaube, dass …', right: l('I think (not sure) that …', 'Sanırım (emin değilim) …', 'Vermutung') },
      { left: 'Ich weiß, dass …', right: l('I know that …', 'Biliyorum ki …', 'sicheres Wissen') },
      { left: 'Ich hoffe, dass …', right: l('I hope that …', 'Umarım …', 'Wunsch') },
      { left: 'Ich finde, dass …', right: l('In my opinion …', 'Bence …', 'Meinung') },
    ],
    explanation: l('All of them are followed by a dass-clause with the verb at the end.', 'Hepsinin ardından fiili sonda olan bir dass-cümlesi gelir.', 'dass + Verb am Ende.'),
  },
  {
    id: 'tf-komma',
    type: 'true_false',
    topic: 'dass',
    concept: 'comma',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Vor „weil“ und „dass“ steht immer ein Komma.',
    answer: true,
    explanation: l('In German there is always a comma before a subordinate clause: Ich glaube, dass …', 'Almancada yan cümleden önce her zaman virgül vardır: Ich glaube, dass …', 'Komma vor weil/dass.'),
  },
  {
    id: 'select-correct',
    type: 'multiple_select',
    topic: 'weil',
    concept: 'weil-verb-end',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche Sätze sind richtig? Wähle alle.'),
    options: [
      'Ich gehe früh ins Bett, weil ich morgen arbeite.',
      'Ich gehe früh ins Bett, weil ich arbeite morgen.',
      'Ich weiß, dass er Arzt ist.',
      'Ich weiß, dass er ist Arzt.',
      'Er kommt nicht, denn er ist krank.',
    ],
    answers: [0, 2, 4],
    explanation: l('weil/dass → verb at the end. denn → normal order.', 'weil/dass → fiil sonda. denn → normal dizilim.', 'weil/dass: Verb am Ende.'),
  },
  {
    id: 'image-warum',
    type: 'image_choice',
    topic: 'weil',
    concept: 'reasons',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Ich nehme einen Regenschirm mit, weil es regnet.',
    options: [
      { emoji: '☀️', label: 'sonnig' },
      { emoji: '🌧️', label: 'Regen' },
      { emoji: '❄️', label: 'Schnee' },
      { emoji: '🌪️', label: 'Sturm' },
    ],
    answer: 1,
    explanation: l('weil es regnet = because it’s raining.', 'weil es regnet = çünkü yağmur yağıyor.', 'Regen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-bin',
    type: 'fill_blank',
    topic: 'weil',
    concept: 'weil-verb-end',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Ich trinke Kaffee, weil ich sehr müde ___.',
    accepted: ['bin'],
    base: 'sein',
    explanation: l('weil → verb at the end: … müde bin.', 'weil → fiil sonda: … müde bin.', '… müde bin.'),
    examples: ['…, weil ich sehr müde **bin**.'],
  },
  {
    id: 'fill-dass',
    type: 'fill_blank',
    topic: 'dass',
    concept: 'dass-verbs',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Ich hoffe, ___ du bald wieder gesund bist.',
    accepted: ['dass'],
    base: 'weil / dass',
    explanation: l('After hoffen, glauben, wissen → dass.', 'hoffen, glauben, wissen’den sonra → dass.', 'Ich hoffe, dass …'),
    examples: ['Ich hoffe, **dass** du bald wieder gesund bist.'],
  },
  {
    id: 'fill-modal',
    type: 'fill_blank',
    topic: 'weil',
    concept: 'weil-modal',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich komme später, weil ich noch arbeiten ___.',
    accepted: ['muss'],
    base: 'müssen',
    explanation: l('With a modal verb: infinitive + modal at the very end: … arbeiten muss.', 'Modal fiille: mastar + modal en sonda: … arbeiten muss.', '… arbeiten muss.'),
    examples: ['…, weil ich noch **arbeiten muss**.'],
  },
  {
    id: 'build-weil',
    type: 'sentence_builder',
    topic: 'weil',
    concept: 'weil-verb-end',
    skill: 'grammar',
    difficulty: 2,
    chips: ['habe', 'weil', 'ich', 'Ich lerne Deutsch,', 'einen Job in Wien'],
    answers: [['Ich lerne Deutsch,', 'weil', 'ich', 'einen Job in Wien', 'habe']],
    translation: l('I’m learning German because I have a job in Vienna.', 'Almanca öğreniyorum çünkü Viyana’da bir işim var.', 'Ich lerne Deutsch, weil ich einen Job in Wien habe.'),
    explanation: l('weil – subject – … – verb at the end.', 'weil – özne – … – fiil sonda.', 'weil … habe.'),
    examples: ['Ich lerne Deutsch, **weil** ich einen Job in Wien **habe**.'],
  },
  {
    id: 'build-dass',
    type: 'sentence_builder',
    topic: 'dass',
    concept: 'dass-verb-end',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ist', 'dass', 'Deutsch', 'Ich finde,', 'nicht so schwer'],
    answers: [['Ich finde,', 'dass', 'Deutsch', 'nicht so schwer', 'ist']],
    translation: l('I think German isn’t that difficult.', 'Bence Almanca o kadar zor değil.', 'Ich finde, dass Deutsch nicht so schwer ist.'),
    explanation: l('dass – subject – … – verb at the end.', 'dass – özne – … – fiil sonda.', 'dass … ist.'),
    examples: ['Ich finde, **dass** Deutsch nicht so schwer **ist**.'],
  },
  {
    id: 'build-perfekt',
    type: 'sentence_builder',
    topic: 'weil',
    concept: 'weil-perfekt',
    skill: 'grammar',
    difficulty: 3,
    chips: ['verpasst', 'Ich bin zu spät,', 'habe', 'weil', 'ich', 'den Bus'],
    answers: [['Ich bin zu spät,', 'weil', 'ich', 'den Bus', 'verpasst', 'habe']],
    translation: l('I’m late because I missed the bus.', 'Geç kaldım çünkü otobüsü kaçırdım.', 'Ich bin zu spät, weil ich den Bus verpasst habe.'),
    explanation: l('Perfekt in a weil-clause: participle + haben at the end: … verpasst habe.', 'weil-cümlesinde Perfekt: ortaç + haben sonda: … verpasst habe.', '… verpasst habe.'),
    examples: ['…, weil ich den Bus **verpasst habe**.'],
  },
  {
    id: 'fix-weil',
    type: 'error_correction',
    topic: 'weil',
    concept: 'weil-verb-end',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich kann nicht kommen, weil ich habe einen Termin.',
    accepted: ['Ich kann nicht kommen, weil ich einen Termin habe.', 'Ich kann nicht kommen, denn ich habe einen Termin.'],
    explanation: l('weil → verb at the end: …, weil ich einen Termin habe. (Or: denn ich habe …)', 'weil → fiil sonda: …, weil ich einen Termin habe. (Ya da: denn ich habe …)', 'weil … habe.'),
    examples: ['…, weil ich einen Termin **habe**.'],
  },
  {
    id: 'fix-dass',
    type: 'error_correction',
    topic: 'dass',
    concept: 'dass-verb-end',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich glaube, dass er kommt heute nicht.',
    accepted: ['Ich glaube, dass er heute nicht kommt.'],
    explanation: l('dass → verb at the end: … heute nicht kommt.', 'dass → fiil sonda: … heute nicht kommt.', 'dass … kommt.'),
    examples: ['Ich glaube, dass er heute nicht **kommt**.'],
  },
  {
    id: 'fix-modal',
    type: 'error_correction',
    topic: 'weil',
    concept: 'weil-modal',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Sie ist zu Hause, weil sie muss lernen.',
    accepted: ['Sie ist zu Hause, weil sie lernen muss.'],
    explanation: l('Modal verb at the very end: … lernen muss.', 'Modal fiil en sonda: … lernen muss.', '… lernen muss.'),
    examples: ['…, weil sie **lernen muss**.'],
  },
  {
    id: 'tr-weil',
    type: 'translation',
    topic: 'weil',
    concept: 'weil-verb-end',
    skill: 'writing',
    difficulty: 2,
    source: l('I’m staying at home because I’m ill.', 'Evde kalıyorum çünkü hastayım.', 'I’m staying at home because I’m ill.'),
    accepted: ['Ich bleibe zu Hause, weil ich krank bin.', 'Ich bleibe zuhause, weil ich krank bin.'],
    explanation: l('…, weil ich krank bin.', '…, weil ich krank bin.', '…, weil ich krank bin.'),
    examples: ['Ich bleibe zu Hause, **weil** ich krank **bin**.'],
  },
  {
    id: 'tr-dass',
    type: 'translation',
    topic: 'dass',
    concept: 'dass-verb-end',
    skill: 'writing',
    difficulty: 2,
    source: l('I know that you are right.', 'Haklı olduğunu biliyorum.', 'I know that you are right.'),
    accepted: ['Ich weiß, dass du recht hast.', 'Ich weiß, dass du Recht hast.'],
    explanation: l('recht haben = to be right. dass … recht hast.', 'recht haben = haklı olmak. dass … recht hast.', 'dass du recht hast.'),
    examples: ['Ich weiß, **dass** du recht **hast**.'],
  },
  {
    id: 'ordering-weil',
    type: 'ordering',
    topic: 'weil',
    concept: 'weil-verb-end',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Build the weil-clause.', 'weil-cümlesini kur.', 'Bilde den weil-Satz.'),
    items: ['möchte', 'weil', 'studieren', 'ich', 'in Deutschland'],
    answer: ['weil', 'ich', 'in Deutschland', 'studieren', 'möchte'],
    explanation: l('weil – subject – place – infinitive – modal (end).', 'weil – özne – yer – mastar – modal (son).', 'weil ich in Deutschland studieren möchte.'),
  },
  {
    id: 'dialog-warum',
    type: 'dialogue',
    topic: 'weil',
    concept: 'reasons',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Lehrerin', de: 'Warum lernen Sie Deutsch?' }],
    options: ['Weil ich in Deutschland arbeiten möchte.', 'Weil ich möchte in Deutschland arbeiten.', 'Dass ich in Deutschland arbeiten möchte.'],
    answer: 0,
    explanation: l('A short answer to Warum? can start with Weil … (verb at the end).', 'Warum?’a kısa cevap Weil … ile başlayabilir (fiil sonda).', 'Weil … möchte.'),
  },
  {
    id: 'dialog-meinung',
    type: 'dialogue',
    topic: 'dass',
    concept: 'dass-verbs',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Kollege', de: 'Was denkst du über das neue Büro?' }],
    options: ['Ich finde, dass es zu klein ist.', 'Ich finde, dass es ist zu klein.', 'Ich finde, weil es zu klein ist.'],
    answer: 0,
    explanation: l('Opinion: Ich finde, dass … (verb at the end).', 'Fikir: Ich finde, dass … (fiil sonda).', 'Ich finde, dass … ist.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-warum',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Warum lernt Ana Deutsch?',
    options: ['Weil ihr Mann aus Österreich kommt.', 'Weil sie in Berlin studiert.', 'Weil sie eine Prüfung hat.'],
    answer: 0,
    explanation: l('„Ich lerne Deutsch, weil mein Mann aus Österreich kommt.“', '„Ich lerne Deutsch, weil mein Mann aus Österreich kommt.“', '„mein Mann aus Österreich“'),
  },
  {
    id: 'read-kemal',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum braucht Kemal Deutsch?',
    options: ['Für seine Arbeit im Krankenhaus.', 'Für seine Urlaube.', 'Weil er Bücher liebt.'],
    answer: 0,
    explanation: l('„… weil ich als Pfleger in einem Krankenhaus arbeiten möchte.“', '„… weil ich als Pfleger in einem Krankenhaus arbeiten möchte.“', '„im Krankenhaus arbeiten“'),
  },
  {
    id: 'read-schwer',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    statement: 'Lin findet, dass Deutsch sehr leicht ist.',
    answer: false,
    explanation: l('„Ich finde, dass die Grammatik ziemlich schwer ist.“', '„Ich finde, dass die Grammatik ziemlich schwer ist.“', '„ziemlich schwer“'),
  },
  {
    id: 'read-tipp',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist Lins Tipp?',
    options: ['Jeden Tag ein bisschen üben.', 'Viele Filme ohne Untertitel sehen.', 'Nur Grammatik lernen.'],
    answer: 0,
    explanation: l('„Ich glaube, dass man jeden Tag ein bisschen üben muss.“', '„Ich glaube, dass man jeden Tag ein bisschen üben muss.“', '„jeden Tag ein bisschen üben“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-grund',
    type: 'listening_choice',
    topic: 'weil',
    concept: 'reasons',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich komme heute nicht ins Büro, weil mein Sohn krank ist.',
    question: l('Why isn’t the person coming?', 'Kişi neden gelmiyor?', 'Warum kommt die Person nicht?'),
    options: ['Der Sohn ist krank.', 'Die Person ist krank.', 'Der Bus kommt nicht.'],
    answer: 0,
    explanation: l('„weil mein Sohn krank ist“', '„weil mein Sohn krank ist“', '„mein Sohn ist krank“'),
  },
  {
    id: 'listen-hoffe',
    type: 'listening_choice',
    topic: 'dass',
    concept: 'dass-verbs',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich hoffe, dass ich die Prüfung bestehe.',
    question: l('What does the person hope?', 'Kişi ne umuyor?', 'Was hofft die Person?'),
    options: ['die Prüfung zu bestehen', 'Urlaub zu machen', 'einen Job zu finden'],
    answer: 0,
    explanation: l('bestehen = to pass (an exam).', 'bestehen = (sınavı) geçmek.', 'die Prüfung bestehen.'),
  },
  {
    id: 'listen-denn',
    type: 'listening_choice',
    topic: 'weil',
    concept: 'weil-denn',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wir fahren mit dem Zug, denn das Auto ist kaputt.',
    question: l('Why do they take the train?', 'Neden trenle gidiyorlar?', 'Warum fahren sie mit dem Zug?'),
    options: ['Das Auto ist kaputt.', 'Der Zug ist billiger.', 'Sie haben kein Auto.'],
    answer: 0,
    explanation: l('„denn das Auto ist kaputt“', '„denn das Auto ist kaputt“', '„das Auto ist kaputt“'),
  },
  {
    id: 'listen-glaube',
    type: 'listening_choice',
    topic: 'dass',
    concept: 'dass-verb-end',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich glaube, dass der Supermarkt sonntags geschlossen ist.',
    question: l('What does the person think?', 'Kişi ne düşünüyor?', 'Was glaubt die Person?'),
    options: ['Der Supermarkt ist sonntags zu.', 'Der Supermarkt ist sonntags offen.', 'Der Supermarkt ist neu.'],
    answer: 0,
    explanation: l('geschlossen = closed.', 'geschlossen = kapalı.', 'geschlossen = zu.'),
  },

  ...clauseDrills(),
]

export const UNIT_A2_08_WEIL_DASS: CourseUnit = {
  level: 'A2',
  number: 8,
  slug: 'weil-dass',
  titleDe: 'Ich lerne Deutsch, weil …',
  title: l('I learn German because …', 'Almanca öğreniyorum, çünkü …', 'Ich lerne Deutsch, weil …'),
  goal: l(
    'By the end of this unit you can give reasons with weil and denn and express opinions with dass – with the verb at the end of the subordinate clause.',
    'Bu ünitenin sonunda weil ve denn ile sebep belirtebilir, dass ile fikrini ifade edebilirsin – yan cümlede fiil sonda.',
    'Am Ende dieser Einheit begründest du mit weil/denn und sagst deine Meinung mit dass.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'weil', label: l('weil & denn', 'weil ve denn', 'weil & denn') },
    { key: 'dass', label: l('dass-clauses', 'dass-cümleleri', 'dass-Sätze') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Small words that send the verb to the end.', 'Fiili sona gönderen küçük kelimeler.', 'Kleine Wörter, die das Verb ans Ende schicken.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Subordinate clause: verb at the end', 'Yan cümle: fiil sonda', 'Nebensatz: Verb am Ende'),
          body: l(
            'weil (because) and dass (that) start a subordinate clause. The conjugated verb goes to the very end. Always put a comma before it.',
            'weil (çünkü) ve dass (ki, -dığı) bir yan cümle başlatır. Çekimli fiil en sona gider. Önüne her zaman virgül koy.',
            'weil/dass: Verb am Ende, Komma davor.'
          ),
          table: {
            head: [l('Main clause', 'Ana cümle', 'Hauptsatz'), l('Conjunction', 'Bağlaç', 'Konjunktion'), l('…', '…', '…'), l('Verb (end)', 'Fiil (son)', 'Verb (Ende)')],
            rows: [
              ['Ich bleibe zu Hause,', 'weil', 'ich krank', 'bin.'],
              ['Ich glaube,', 'dass', 'er heute', 'kommt.'],
              ['Ich komme später,', 'weil', 'ich noch arbeiten', 'muss.'],
              ['Ich bin müde,', 'weil', 'ich schlecht geschlafen', 'habe.'],
            ],
          },
          tip: l('With a modal verb or the Perfekt, the conjugated verb is the very last word: … arbeiten muss, … geschlafen habe.', 'Modal fiil ya da Perfekt ile çekimli fiil en son kelimedir: … arbeiten muss, … geschlafen habe.', 'Konjugiertes Verb ganz am Ende.'),
        },
        {
          title: l('weil or denn?', 'weil mi denn mi?', 'weil oder denn?'),
          body: l(
            'Both mean „because“. weil → verb at the end. denn → normal word order (verb in position 2). In spoken German, weil is more common.',
            'İkisi de „çünkü“ demektir. weil → fiil sonda. denn → normal dizilim (fiil 2. sırada). Konuşma dilinde weil daha yaygındır.',
            'weil: Ende · denn: Position 2.'
          ),
          examples: [
            { de: 'Ich lerne viel, **weil** ich eine Prüfung **habe**.', translation: l('I study a lot because I have an exam.', 'Çok çalışıyorum çünkü sınavım var.', '') },
            { de: 'Ich lerne viel, **denn** ich **habe** eine Prüfung.', translation: l('I study a lot, because I have an exam.', 'Çok çalışıyorum, çünkü sınavım var.', '') },
          ],
        },
        {
          title: l('dass after verbs of thinking and saying', 'Düşünme ve söyleme fiillerinden sonra dass', 'dass nach Verben des Denkens und Sagens'),
          body: l(
            'glauben, finden, denken, wissen, hoffen, sagen + dass. Also: Es ist wichtig/schön, dass …',
            'glauben, finden, denken, wissen, hoffen, sagen + dass. Ayrıca: Es ist wichtig/schön, dass …',
            'glauben, finden, wissen, hoffen + dass.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('First lesson of a new German course: everyone says why they learn German.', 'Yeni bir Almanca kursunun ilk dersi: herkes neden Almanca öğrendiğini söylüyor.', 'Erste Kursstunde: Warum lernen Sie Deutsch?'),
      dialogue: [
        { speaker: 'Lehrerin', de: 'Warum lernen Sie Deutsch, Herr Silva?', translation: l('Why are you learning German, Mr Silva?', 'Neden Almanca öğreniyorsunuz Bay Silva?', '') },
        { speaker: 'Herr Silva', de: 'Ich lerne Deutsch, **weil** ich in Hamburg eine neue Stelle **habe**.', translation: l('I’m learning German because I have a new job in Hamburg.', 'Almanca öğreniyorum çünkü Hamburg’da yeni bir işim var.', '') },
        { speaker: 'Lehrerin', de: 'Und Sie, Frau Novak?', translation: l('And you, Ms Novak?', 'Ya siz Bayan Novak?', '') },
        { speaker: 'Frau Novak', de: '**Weil** meine Kinder hier zur Schule **gehen**. Ich möchte mit den Lehrern sprechen.', translation: l('Because my children go to school here. I want to talk to the teachers.', 'Çünkü çocuklarım burada okula gidiyor. Öğretmenlerle konuşmak istiyorum.', '') },
        { speaker: 'Lehrerin', de: 'Sehr gut. Und was denken Sie über Deutsch?', translation: l('Very good. And what do you think about German?', 'Çok iyi. Peki Almanca hakkında ne düşünüyorsunuz?', '') },
        { speaker: 'Herr Silva', de: 'Ich finde, **dass** die Aussprache schwer **ist**. Aber ich glaube, **dass** ich es schaffen **kann**!', translation: l('I think the pronunciation is difficult. But I believe I can do it!', 'Bence telaffuz zor. Ama başarabileceğime inanıyorum!', '') },
        { speaker: 'Lehrerin', de: 'Da bin ich sicher. Es ist wichtig, **dass** Sie jeden Tag ein bisschen **üben**.', translation: l('I’m sure of it. It’s important that you practise a little every day.', 'Bundan eminim. Her gün biraz pratik yapmanız önemli.', '') },
      ],
      examples: [
        { de: 'Ich bleibe zu Hause, **weil** ich krank **bin**.', translation: l('I’m staying at home because I’m ill.', 'Evde kalıyorum çünkü hastayım.', '') },
        { de: 'Ich trinke Kaffee, **denn** ich **bin** müde.', translation: l('I’m drinking coffee because I’m tired.', 'Kahve içiyorum çünkü yorgunum.', '') },
        { de: 'Ich glaube, **dass** es morgen **regnet**.', translation: l('I think it will rain tomorrow.', 'Sanırım yarın yağmur yağacak.', '') },
        { de: 'Ich weiß, **dass** du recht **hast**.', translation: l('I know you’re right.', 'Haklı olduğunu biliyorum.', '') },
        { de: 'Ich komme später, **weil** ich noch **arbeiten muss**.', translation: l('I’ll come later because I still have to work.', 'Daha sonra geleceğim çünkü hâlâ çalışmam gerekiyor.', '') },
        { de: 'Er ist müde, **weil** er schlecht **geschlafen hat**.', translation: l('He’s tired because he slept badly.', 'Yorgun çünkü kötü uyudu.', '') },
        { de: 'Es ist schön, **dass** du **da bist**.', translation: l('It’s nice that you’re here.', 'Burada olman güzel.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Where is the verb?', 'Fiil nerede?', 'Wo steht das Verb?'),
      exercises: ['mc-weil-denn', 'sort-weil-denn', 'ns-krank', 'ns-kurs', 'match-meinung', 'tf-komma', 'select-correct', 'image-warum', 'ns-arbeit'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Give reasons and opinions.', 'Sebep ve fikir belirt.', 'Begründe und sag deine Meinung.'),
      exercises: [
        'fill-bin',
        'fill-dass',
        'fill-modal',
        'build-weil',
        'build-dass',
        'build-perfekt',
        'fix-weil',
        'fix-dass',
        'fix-modal',
        'tr-weil',
        'tr-dass',
        'ordering-weil',
        'dialog-warum',
        'dialog-meinung',
        'ns-regen',
        'ns-muede',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A forum: „Why are you learning German?“', 'Bir forum: „Neden Almanca öğreniyorsun?“', 'Forum: Warum lernst du Deutsch?'),
      passage: [
        '**Ana (Portugal):** Ich lerne Deutsch, **weil** mein Mann aus Österreich **kommt**. Seine Familie spricht kein Englisch!',
        '**Kemal (Türkei):** Ich brauche Deutsch, **weil** ich als Pfleger in einem Krankenhaus **arbeiten möchte**. Ich hoffe, **dass** ich die B1-Prüfung im Sommer **bestehe**.',
        '**Lin (China):** Ich finde, **dass** die Grammatik ziemlich schwer **ist**. Aber ich glaube, **dass** man jeden Tag ein bisschen **üben muss** – dann klappt es!',
      ],
      glossary: [
        { de: 'der Pfleger', note: l('nurse (m)', 'hemşire (erkek)', 'arbeitet im Krankenhaus') },
        { de: 'bestehen', note: l('to pass (an exam)', '(sınavı) geçmek', 'eine Prüfung schaffen') },
        { de: 'ziemlich', note: l('quite, rather', 'oldukça', 'relativ') },
        { de: 'es klappt', note: l('it works out', 'olur, başarılır', 'es funktioniert') },
      ],
      exercises: ['read-warum', 'read-kemal', 'read-schwer', 'read-tipp'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for the reason – and the verb at the end.', 'Sebebe – ve sondaki fiile – kulak ver.', 'Hör auf den Grund.'),
      exercises: ['listen-grund', 'listen-hoffe', 'listen-denn', 'listen-glaube'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Why are you learning German? Give at least three reasons and one opinion.', 'Neden Almanca öğreniyorsun? En az üç sebep ve bir fikir söyle.', 'Warum lernst du Deutsch? Drei Gründe und eine Meinung.'),
      points: [
        l('„Ich lerne Deutsch, weil …“', '„Ich lerne Deutsch, weil …“', 'weil …'),
        l('„Außerdem …, denn …“', '„Außerdem …, denn …“', 'denn …'),
        l('Opinion: „Ich finde, dass Deutsch … ist.“', 'Fikir: „Ich finde, dass Deutsch … ist.“', 'Meinung mit dass'),
        l('Hope: „Ich hoffe, dass …“', 'Umut: „Ich hoffe, dass …“', 'Hoffnung'),
      ],
      model: [
        'Ich lerne Deutsch, weil ich in Deutschland studieren möchte.',
        'Außerdem lerne ich Deutsch, denn meine Freundin kommt aus München.',
        'Ich finde, dass die Artikel sehr schwer sind.',
        'Aber ich hoffe, dass ich bald gut sprechen kann.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a forum post (at least 5 sentences): Why are you learning German, and what do you think about it?',
        'Bir forum yazısı yaz (en az 5 cümle): Neden Almanca öğreniyorsun ve bu konuda ne düşünüyorsun?',
        'Schreib einen Forumsbeitrag (mindestens 5 Sätze): Warum lernst du Deutsch?'
      ),
      minSentences: 5,
      checks: [
        { label: l('A weil-clause', 'Bir weil-cümlesi', 'Ein weil-Satz'), pattern: '\\b[Ww]eil\\b' },
        { label: l('A dass-clause', 'Bir dass-cümlesi', 'Ein dass-Satz'), pattern: '\\b[Dd]ass\\b' },
        { label: l('A comma before weil/dass', 'weil/dass’tan önce virgül', 'Komma vor weil/dass'), pattern: ', (weil|dass)\\b' },
        { label: l('Verb at the end of the clause (… bin. / … habe. / … ist.)', 'Yan cümlenin sonunda fiil (… bin. / … habe. / … ist.)', 'Verb am Ende'), pattern: '(weil|dass)\\b[^.!?]*\\b(bin|bist|ist|sind|habe|hat|haben|kann|muss|möchte|will|\\p{Ll}+e|\\p{Ll}+t|\\p{Ll}+en)[.!?]' },
      ],
      model: [
        'Hallo zusammen!',
        'Ich lerne Deutsch, weil ich in Wien arbeite.',
        'Meine Kollegen sprechen nur Deutsch mit mir.',
        'Ich finde, dass die Grammatik manchmal schwer ist.',
        'Aber ich glaube, dass ich jeden Tag besser werde.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Verb at the end? – 60 seconds.', 'Fiil sonda mı? – 60 saniye.', 'Verb am Ende? – 60 Sekunden.'),
      seconds: 60,
      pool: [...CLAUSES.map(([id]) => `ns-${id}`), 'mc-weil-denn'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('weil + verb at the end: …, weil ich krank bin.', 'weil + fiil sonda: …, weil ich krank bin.', 'weil … bin.'),
      l('denn + normal order: …, denn ich bin krank.', 'denn + normal dizilim: …, denn ich bin krank.', 'denn ich bin …'),
      l('dass after glauben, finden, wissen, hoffen', 'glauben, finden, wissen, hoffen’den sonra dass', 'dass-Sätze'),
      l('Modal/Perfekt: … arbeiten muss / … geschlafen habe', 'Modal/Perfekt: … arbeiten muss / … geschlafen habe', 'Verb ganz am Ende'),
    ],
    mistakes: [
      { wrong: '…, weil ich bin müde.', right: '…, weil ich müde bin.', note: l('weil → verb at the end.', 'weil → fiil sonda.', 'Verb am Ende.') },
      { wrong: 'Ich glaube, dass er kommt heute.', right: 'Ich glaube, dass er heute kommt.', note: l('dass → verb at the end.', 'dass → fiil sonda.', 'Verb am Ende.') },
      { wrong: '…, weil ich muss arbeiten.', right: '…, weil ich arbeiten muss.', note: l('Modal at the very end.', 'Modal en sonda.', 'Modal am Ende.') },
      { wrong: 'Ich glaube dass …', right: 'Ich glaube, dass …', note: l('Comma before dass.', 'dass’tan önce virgül.', 'Komma.') },
    ],
  },
}
