import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'ein schöner Tag', emoji: '☀️', translation: l('a beautiful day (m, -er)', 'güzel bir gün (eril, -er)', 'der Tag → ein schöner Tag'), example: 'Heute ist ein schöner Tag.' },
  { word: 'eine kleine Küche', emoji: '🍳', translation: l('a small kitchen (f, -e)', 'küçük bir mutfak (dişil, -e)', 'die Küche → eine kleine Küche'), example: 'Wir haben eine kleine Küche.' },
  { word: 'ein neues Auto', emoji: '🚙', translation: l('a new car (n, -es)', 'yeni bir araba (nötr, -es)', 'das Auto → ein neues Auto'), example: 'Mein Bruder hat ein neues Auto.' },
  { word: 'einen warmen Pullover', emoji: '🧶', translation: l('a warm pullover (Akk m, -en)', 'sıcak bir kazak (Akk eril, -en)', 'Akkusativ maskulin'), example: 'Ich brauche einen warmen Pullover.' },
  { word: 'mit einer guten Freundin', emoji: '👭', translation: l('with a good friend (Dat, -en)', 'iyi bir arkadaşla (Dat, -en)', 'Dativ → -en'), example: 'Ich gehe mit einer guten Freundin ins Kino.' },
  { word: 'keine teuren Schuhe', emoji: '👟', translation: l('no expensive shoes (pl, -en)', 'pahalı ayakkabı yok (çoğul, -en)', 'Plural → -en'), example: 'Ich kaufe keine teuren Schuhe.' },
  { word: 'bequem', emoji: '🛋️', translation: l('comfortable', 'rahat', 'angenehm'), example: 'Das ist ein bequemes Sofa.' },
  { word: 'modern', emoji: '🏙️', translation: l('modern', 'modern', 'modern'), example: 'Sie trägt eine moderne Jacke.' },
  { word: 'günstig', emoji: '🏷️', translation: l('cheap, good value', 'uygun fiyatlı', 'billig'), example: 'Ich suche einen günstigen Laptop.' },
  { word: 'praktisch', emoji: '🧰', translation: l('practical', 'pratik', 'nützlich'), example: 'Das ist ein praktisches Geschenk.' },
  { word: 'gestreift', emoji: '🦓', translation: l('striped', 'çizgili', 'mit Streifen'), example: 'Er trägt ein gestreiftes Hemd.' },
  { word: 'kariert', emoji: '🏁', translation: l('checked', 'kareli', 'mit Karos'), example: 'Ich mag meinen karierten Schal.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Pullover', gender: 'm', plural: 'die Pullover', translation: l('pullover', 'kazak', 'Pullover') },
  { word: 'Schal', gender: 'm', plural: 'die Schals', translation: l('scarf', 'atkı', 'Schal') },
  { word: 'Hemd', gender: 'n', plural: 'die Hemden', translation: l('shirt', 'gömlek', 'Hemd') },
  { word: 'Jacke', gender: 'f', plural: 'die Jacken', translation: l('jacket', 'ceket', 'Jacke') },
  { word: 'Geschenk', gender: 'n', plural: 'die Geschenke', translation: l('present', 'hediye', 'Geschenk') },
  { word: 'Laptop', gender: 'm', plural: 'die Laptops', translation: l('laptop', 'dizüstü bilgisayar', 'Laptop') },
  { word: 'Tasche', gender: 'f', plural: 'die Taschen', translation: l('bag', 'çanta', 'Tasche') },
  { word: 'Kleid', gender: 'n', plural: 'die Kleider', translation: l('dress', 'elbise', 'Kleid') },
  { word: 'Uhr', gender: 'f', plural: 'die Uhren', translation: l('watch', 'saat', 'Uhr') },
]

/** [id, sentence with ___ for the adjective, adjective stem, ending, label] */
const ENDING_DRILLS: [string, string, string, 'er' | 'e' | 'es' | 'en', string][] = [
  ['nom-m', 'Das ist ein ___ Pullover.', 'warm', 'er', 'Nominativ maskulin: ein … -er'],
  ['nom-f', 'Das ist eine ___ Tasche.', 'praktisch', 'e', 'Nominativ feminin: eine … -e'],
  ['nom-n', 'Das ist ein ___ Kleid.', 'schön', 'es', 'Nominativ neutral: ein … -es'],
  ['akk-m', 'Ich suche einen ___ Laptop.', 'günstig', 'en', 'Akkusativ maskulin: einen … -en'],
  ['akk-f', 'Sie kauft eine ___ Uhr.', 'teur', 'e', 'Akkusativ feminin: eine … -e'],
  ['akk-n', 'Er trägt ein ___ Hemd.', 'gestreift', 'es', 'Akkusativ neutral: ein … -es'],
  ['dat-m', 'Ich wohne bei einem ___ Freund.', 'alt', 'en', 'Dativ: einem … -en'],
  ['dat-f', 'Er spricht mit einer ___ Kundin.', 'freundlich', 'en', 'Dativ: einer … -en'],
  ['pl', 'Wir haben keine ___ Stühle.', 'bequem', 'en', 'Plural nach keine/meine: -en'],
  ['poss-n', 'Das ist mein ___ Fahrrad.', 'neu', 'es', 'mein = ein: Nominativ neutral -es'],
]

function endingDrills(): Exercise[] {
  return ENDING_DRILLS.map(([id, sentence, stem, ending, label], i) => {
    const set = new Set([`${stem}${ending}`, `${stem}en`, `${stem}er`, `${stem}es`, `${stem}e`])
    const pool = [...set].filter((o) => o !== `${stem}${ending}`)
    const options = [`${stem}${ending}`, pool[(i + 0) % pool.length], pool[(i + 1) % pool.length]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `ein-${id}`,
      type: 'multiple_choice' as const,
      topic: id.startsWith('nom') || id === 'poss-n' ? 'nominativ' : id.startsWith('akk') ? 'akkusativ' : 'dativ-plural',
      concept: `adj-indef-${id}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(`${stem}${ending}`),
      explanation: l(`${label}.`, `${label}.`, `${label}.`),
      examples: [sentence.replace('___', `**${stem}${ending}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'sort-nom',
    type: 'categorize',
    topic: 'nominativ',
    concept: 'nom-er-e-es',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Nominativ: which ending?', 'Nominativ: hangi ek?', 'Nominativ: welche Endung?'),
    categories: ['-er (der)', '-e (die)', '-es (das)'],
    items: [
      { text: 'ein neu… Schal', category: 0 },
      { text: 'eine neu… Jacke', category: 1 },
      { text: 'ein neu… Hemd', category: 2 },
      { text: 'mein alt… Laptop', category: 0 },
      { text: 'meine alt… Uhr', category: 1 },
      { text: 'mein alt… Kleid', category: 2 },
    ],
    explanation: l(
      'ein has no ending for der/das words – so the adjective shows the gender: ein neuer (der), ein neues (das), eine neue (die).',
      'ein, der/das kelimelerinde ek almaz – bu yüzden cinsiyeti sıfat gösterir: ein neuer (der), ein neues (das), eine neue (die).',
      'ein neuer (der), eine neue (die), ein neues (das).'
    ),
    practice: ['ein-nom-m', 'ein-nom-n'],
  },
  {
    id: 'match-endings',
    type: 'matching',
    topic: 'nominativ',
    concept: 'der-er-das-es',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Match: definite → indefinite.', 'Eşleştir: belirli → belirsiz.', 'Ordne zu: bestimmt → unbestimmt.'),
    pairs: [
      { left: 'der warme Schal', right: 'ein warmer Schal' },
      { left: 'das warme Hemd', right: 'ein warmes Hemd' },
      { left: 'die warme Jacke', right: 'eine warme Jacke' },
      { left: 'den warmen Schal', right: 'einen warmen Schal' },
    ],
    explanation: l('Trick: the -r of der and the -s of das jump to the adjective: der → ein …er, das → ein …es.', 'Hile: der’deki -r ve das’taki -s sıfata atlar: der → ein …er, das → ein …es.', 'der → -er, das → -es.'),
  },
  {
    id: 'image-gestreift',
    type: 'image_choice',
    topic: 'describe-things',
    concept: 'patterns',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'ein kariertes Hemd',
    options: [
      { emoji: '🦓', label: 'gestreift' },
      { emoji: '🏁', label: 'kariert' },
      { emoji: '⚪', label: 'einfarbig' },
      { emoji: '🌸', label: 'geblümt' },
    ],
    answer: 1,
    explanation: l('kariert = checked 🏁.', 'kariert = kareli 🏁.', 'kariert.'),
  },
  {
    id: 'select-right',
    type: 'multiple_select',
    topic: 'akkusativ',
    concept: 'akk-indef',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Ich kaufe … – which forms are correct? Select all.', 'Ich kaufe … – hangi biçimler doğru? Hepsini seç.', 'Ich kaufe … – welche Formen sind richtig?'),
    options: ['einen neuen Laptop', 'ein neuer Laptop', 'eine neue Tasche', 'ein neues Kleid', 'einen neues Hemd', 'neue Schuhe'],
    answers: [0, 2, 3, 5],
    explanation: l('Akkusativ: einen neuen (m), eine neue (f), ein neues (n), neue Schuhe (pl. without article: -e).', 'Akkusativ: einen neuen (eril), eine neue (dişil), ein neues (nötr), neue Schuhe (artikelsiz çoğul: -e).', 'einen neuen, eine neue, ein neues.'),
  },
  {
    id: 'tf-dativ',
    type: 'true_false',
    topic: 'dativ-plural',
    concept: 'dat-en',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Im Dativ ist die Adjektivendung nach einem/einer immer -en.',
    answer: true,
    explanation: l('mit einem alten Freund, mit einer alten Freundin, mit einem alten Auto – always -en.', 'mit einem alten Freund, mit einer alten Freundin, mit einem alten Auto – her zaman -en.', 'Dativ: -en.'),
  },
  {
    id: 'mc-kein',
    type: 'multiple_choice',
    topic: 'dativ-plural',
    concept: 'kein-plural',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Leider habe ich keine ___ Fotos von der Reise.',
    options: ['guten', 'gute', 'guter'],
    answer: 0,
    explanation: l('Plural after keine/meine → -en.', 'keine/meine’den sonra çoğul → -en.', 'keine guten Fotos.'),
    examples: ['Ich habe keine **guten** Fotos.'],
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-nom-m',
    type: 'fill_blank',
    topic: 'nominativ',
    concept: 'adj-indef-nom-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Heute ist ein schön___ Tag.',
    accepted: ['er'],
    base: 'der Tag',
    explanation: l('ein + der-word (Nom) → -er.', 'ein + der-kelimesi (Nom) → -er.', 'ein schöner Tag.'),
    examples: ['Heute ist ein **schöner** Tag.'],
  },
  {
    id: 'fill-akk-n',
    type: 'fill_blank',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-n',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wir suchen ein günstig___ Hotel.',
    accepted: ['es'],
    base: 'das Hotel',
    explanation: l('ein + das-word → -es (Nom. and Akk.).', 'ein + das-kelimesi → -es (Nom. ve Akk.).', 'ein günstiges Hotel.'),
    examples: ['Wir suchen ein **günstiges** Hotel.'],
  },
  {
    id: 'fill-dat',
    type: 'fill_blank',
    topic: 'dativ-plural',
    concept: 'adj-indef-dat',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich fahre mit meinem neu___ Fahrrad zur Arbeit.',
    accepted: ['en'],
    base: 'Dativ',
    explanation: l('meinem (Dativ) → -en.', 'meinem (Dativ) → -en.', 'mit meinem neuen Fahrrad.'),
    examples: ['Ich fahre mit meinem **neuen** Fahrrad.'],
  },
  {
    id: 'build-geschenk',
    type: 'sentence_builder',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-n',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ein', 'Geschenk', 'Ich', 'praktisches', 'suche'],
    answers: [['Ich', 'suche', 'ein', 'praktisches', 'Geschenk']],
    translation: l('I’m looking for a practical present.', 'Pratik bir hediye arıyorum.', 'Ich suche ein praktisches Geschenk.'),
    explanation: l('das Geschenk → ein praktisches Geschenk.', 'das Geschenk → ein praktisches Geschenk.', 'ein praktisches Geschenk.'),
    examples: ['Ich suche **ein praktisches** Geschenk.'],
  },
  {
    id: 'build-pullover',
    type: 'sentence_builder',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-m',
    skill: 'grammar',
    difficulty: 2,
    chips: ['Pullover', 'warmen', 'Im Winter', 'brauche', 'ich', 'einen'],
    answers: [['Im Winter', 'brauche', 'ich', 'einen', 'warmen', 'Pullover']],
    translation: l('In winter I need a warm pullover.', 'Kışın sıcak bir kazağa ihtiyacım var.', 'Im Winter brauche ich einen warmen Pullover.'),
    explanation: l('einen (Akk m) → -en.', 'einen (Akk eril) → -en.', 'einen warmen Pullover.'),
    examples: ['Im Winter brauche ich **einen warmen** Pullover.'],
  },
  {
    id: 'build-freundin',
    type: 'sentence_builder',
    topic: 'dativ-plural',
    concept: 'adj-indef-dat',
    skill: 'grammar',
    difficulty: 3,
    chips: ['mit', 'alten', 'einer', 'Freundin', 'Am Samstag', 'ich', 'koche'],
    answers: [['Am Samstag', 'koche', 'ich', 'mit', 'einer', 'alten', 'Freundin']],
    translation: l('On Saturday I’m cooking with an old friend.', 'Cumartesi eski bir arkadaşımla yemek yapıyorum.', 'Am Samstag koche ich mit einer alten Freundin.'),
    explanation: l('mit + Dativ: einer alten Freundin.', 'mit + Dativ: einer alten Freundin.', 'mit einer alten Freundin.'),
    examples: ['Am Samstag koche ich **mit einer alten** Freundin.'],
  },
  {
    id: 'fix-ein-neue',
    type: 'error_correction',
    topic: 'nominativ',
    concept: 'adj-indef-nom-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das ist ein neue Laptop.',
    accepted: ['Das ist ein neuer Laptop.'],
    explanation: l('der Laptop → ein neuer Laptop (-er).', 'der Laptop → ein neuer Laptop (-er).', 'ein neuer Laptop.'),
    examples: ['Das ist ein **neuer** Laptop.'],
  },
  {
    id: 'fix-einen-schoen',
    type: 'error_correction',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich wünsche dir einen schöner Abend!',
    accepted: ['Ich wünsche dir einen schönen Abend!', 'Ich wünsche dir einen schönen Abend.'],
    explanation: l('einen (Akk m) → -en: einen schönen Abend.', 'einen (Akk eril) → -en: einen schönen Abend.', 'einen schönen Abend.'),
    examples: ['Ich wünsche dir einen **schönen** Abend!'],
  },
  {
    id: 'fix-kleines',
    type: 'error_correction',
    topic: 'nominativ',
    concept: 'adj-indef-nom-f',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wir haben eine kleines Wohnung.',
    accepted: ['Wir haben eine kleine Wohnung.'],
    explanation: l('die Wohnung → eine kleine Wohnung (-e).', 'die Wohnung → eine kleine Wohnung (-e).', 'eine kleine Wohnung.'),
    examples: ['Wir haben eine **kleine** Wohnung.'],
  },
  {
    id: 'tr-auto',
    type: 'translation',
    topic: 'nominativ',
    concept: 'adj-indef-nom-n',
    skill: 'writing',
    difficulty: 2,
    source: l('My sister has a new car.', 'Kız kardeşimin yeni bir arabası var.', 'My sister has a new car.'),
    accepted: ['Meine Schwester hat ein neues Auto.'],
    explanation: l('das Auto → ein neues Auto.', 'das Auto → ein neues Auto.', 'ein neues Auto.'),
    examples: ['Meine Schwester hat ein **neues** Auto.'],
  },
  {
    id: 'tr-wochenende',
    type: 'translation',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-n',
    skill: 'writing',
    difficulty: 2,
    source: l('Have a nice weekend! (Ich wünsche dir …)', 'İyi hafta sonları! (Ich wünsche dir …)', 'Have a nice weekend! (Ich wünsche dir …)'),
    accepted: ['Ich wünsche dir ein schönes Wochenende!', 'Ich wünsche dir ein schönes Wochenende.', 'Ich wünsche dir ein schönes Wochenende'],
    explanation: l('das Wochenende → ein schönes Wochenende.', 'das Wochenende → ein schönes Wochenende.', 'ein schönes Wochenende.'),
    examples: ['Ich wünsche dir ein **schönes** Wochenende!'],
  },
  {
    id: 'match-wishes',
    type: 'matching',
    topic: 'describe-things',
    concept: 'wishes',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the wish and the situation.', 'Dileği durumla eşleştir.', 'Ordne Wunsch und Situation zu.'),
    pairs: [
      { left: 'Einen schönen Tag noch!', right: l('leaving a shop', 'mağazadan çıkarken', 'beim Verlassen eines Ladens') },
      { left: 'Ein schönes Wochenende!', right: l('on Friday', 'cuma günü', 'am Freitag') },
      { left: 'Eine gute Reise!', right: l('before a trip', 'yolculuktan önce', 'vor einer Reise') },
      { left: 'Einen guten Appetit!', right: l('before eating', 'yemekten önce', 'vor dem Essen') },
    ],
    explanation: l('Wishes are Akkusativ (Ich wünsche dir …): einen schönen Tag, ein schönes Wochenende, eine gute Reise.', 'Dilekler Akkusativ’tir (Ich wünsche dir …): einen schönen Tag, ein schönes Wochenende, eine gute Reise.', 'Wünsche im Akkusativ.'),
  },
  {
    id: 'dialog-laden',
    type: 'dialogue',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-m',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Verkäufer', de: 'Kann ich Ihnen helfen?' }],
    options: ['Ja, ich suche einen leichten Mantel.', 'Ja, ich suche ein leichter Mantel.', 'Ja, ich suche einen leichter Mantel.'],
    answer: 0,
    explanation: l('der Mantel → Akk: einen leichten Mantel.', 'der Mantel → Akk: einen leichten Mantel.', 'einen leichten Mantel.'),
  },
  {
    id: 'dialog-geburtstag',
    type: 'dialogue',
    topic: 'nominativ',
    concept: 'adj-indef-nom-n',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Freundin', de: 'Was hast du zum Geburtstag bekommen?' }],
    options: ['Ein tolles Buch und eine schöne Tasche!', 'Ein toller Buch und eine schönes Tasche!', 'Einen tollen Buch und eine schöne Tasche!'],
    answer: 0,
    explanation: l('das Buch → ein tolles Buch; die Tasche → eine schöne Tasche.', 'das Buch → ein tolles Buch; die Tasche → eine schöne Tasche.', 'ein tolles Buch, eine schöne Tasche.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-was',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was verkauft Familie Yıldız?',
    options: ['Ein großes Sofa und einen alten Tisch.', 'Ein neues Auto.', 'Eine kleine Küche.'],
    answer: 0,
    explanation: l('„Wir verkaufen ein großes Sofa … und einen alten Holztisch.“', '„Wir verkaufen ein großes Sofa … und einen alten Holztisch.“', '„ein großes Sofa … einen alten Holztisch“'),
  },
  {
    id: 'read-sofa',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie ist das Sofa?',
    options: ['Bequem und fast neu.', 'Alt und kaputt.', 'Klein und modern.'],
    answer: 0,
    explanation: l('„… ein großes Sofa – sehr bequem und fast neu.“', '„… ein großes Sofa – sehr bequem und fast neu.“', '„bequem und fast neu“'),
  },
  {
    id: 'read-preis',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    statement: 'Der Tisch kostet nichts.',
    answer: false,
    explanation: l('„Der Tisch kostet nur 30 Euro.“', '„Der Tisch kostet nur 30 Euro.“', '„30 Euro“'),
  },
  {
    id: 'read-warum',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum verkauft die Familie die Möbel?',
    options: ['Sie ziehen in eine kleinere Wohnung.', 'Die Möbel sind kaputt.', 'Sie brauchen Geld für ein Auto.'],
    answer: 0,
    explanation: l('„Wir ziehen in eine kleinere Wohnung.“', '„Wir ziehen in eine kleinere Wohnung.“', '„in eine kleinere Wohnung“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-ending',
    type: 'listening_choice',
    topic: 'nominativ',
    concept: 'adj-indef-nom-m',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das ist ein wirklich schöner Schal.',
    question: l('Which ending do you hear?', 'Hangi eki duyuyorsun?', 'Welche Endung hörst du?'),
    options: ['schöner', 'schönen', 'schönes'],
    answer: 0,
    explanation: l('„ein schöner Schal“', '„ein schöner Schal“', '„schöner“'),
  },
  {
    id: 'listen-was',
    type: 'listening_choice',
    topic: 'describe-things',
    concept: 'patterns',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich trage heute ein gestreiftes Hemd und eine blaue Hose.',
    question: l('What is the person wearing?', 'Kişi ne giyiyor?', 'Was trägt die Person?'),
    options: ['gestreiftes Hemd + blaue Hose', 'kariertes Hemd + schwarze Hose', 'weißes Hemd + blaue Jeans'],
    answer: 0,
    explanation: l('„ein gestreiftes Hemd und eine blaue Hose“', '„ein gestreiftes Hemd und eine blaue Hose“', 'gestreift + blau.'),
  },
  {
    id: 'listen-sucht',
    type: 'listening_choice',
    topic: 'akkusativ',
    concept: 'adj-indef-akk-m',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wir suchen einen günstigen Kühlschrank für unsere kleine Küche.',
    question: l('What are they looking for?', 'Ne arıyorlar?', 'Was suchen sie?'),
    options: ['einen günstigen Kühlschrank', 'eine große Küche', 'einen teuren Herd'],
    answer: 0,
    explanation: l('„einen günstigen Kühlschrank“', '„einen günstigen Kühlschrank“', '„einen günstigen Kühlschrank“'),
  },
  {
    id: 'listen-wunsch',
    type: 'listening_choice',
    topic: 'describe-things',
    concept: 'wishes',
    skill: 'listening',
    difficulty: 1,
    audio: 'Tschüss und einen schönen Tag noch!',
    question: l('When do you say this?', 'Bunu ne zaman söylersin?', 'Wann sagt man das?'),
    options: ['when leaving', 'when arriving', 'when eating'],
    answer: 0,
    explanation: l('A wish when saying goodbye.', 'Vedalaşırken bir dilek.', 'Beim Abschied.'),
  },

  ...endingDrills(),
]

export const UNIT_A2_06_ADJEKTIVE_EIN: CourseUnit = {
  level: 'A2',
  number: 6,
  slug: 'adjektive-ein',
  titleDe: 'Ein schöner Tag',
  title: l('A beautiful day', 'Güzel bir gün', 'Ein schöner Tag'),
  goal: l(
    'By the end of this unit you can describe clothes, presents and things with ein/kein/mein + adjective: ein neuer Laptop, eine kleine Küche, ein neues Auto – and wish people a nice day.',
    'Bu ünitenin sonunda kıyafetleri, hediyeleri ve eşyaları ein/kein/mein + sıfat ile tarif edebilirsin: ein neuer Laptop, eine kleine Küche, ein neues Auto – ve insanlara iyi günler dileyebilirsin.',
    'Am Ende dieser Einheit beschreibst du Dinge mit ein/kein/mein + Adjektiv.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'nominativ', label: l('ein neuer / eine neue / ein neues', 'ein neuer / eine neue / ein neues', 'Nominativ') },
    { key: 'akkusativ', label: l('einen neuen …', 'einen neuen …', 'Akkusativ') },
    { key: 'dativ-plural', label: l('Dativ & plural: -en', 'Dativ ve çoğul: -en', 'Dativ & Plural') },
    { key: 'describe-things', label: l('Clothes & wishes', 'Kıyafetler ve dilekler', 'Kleidung & Wünsche') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Adjectives after ein – look at the endings!', 'ein’den sonra sıfatlar – eklere dikkat!', 'Adjektive nach ein – achte auf die Endungen!'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('The adjective shows the gender', 'Cinsiyeti sıfat gösterir', 'Das Adjektiv zeigt das Genus'),
          body: l(
            'ein has no ending for der- and das-words. So the adjective takes the signal: der → ein …er, das → ein …es. After eine it is -e, after einen/einem/einer and in the plural always -en.',
            'ein, der- ve das-kelimelerinde ek almaz. Bu yüzden işareti sıfat taşır: der → ein …er, das → ein …es. eine’den sonra -e, einen/einem/einer’den sonra ve çoğulda her zaman -en.',
            'der → -er, das → -es, die → -e; sonst -en.'
          ),
          table: {
            head: [l('', '', ''), l('maskulin', 'eril', 'maskulin'), l('feminin', 'dişil', 'feminin'), l('neutral', 'nötr', 'neutral'), l('Plural', 'çoğul', 'Plural')],
            rows: [
              ['Nom.', 'ein neuer Schal', 'eine neue Jacke', 'ein neues Hemd', 'meine neuen Schuhe'],
              ['Akk.', 'einen neuen Schal', 'eine neue Jacke', 'ein neues Hemd', 'meine neuen Schuhe'],
              ['Dat.', 'einem neuen Schal', 'einer neuen Jacke', 'einem neuen Hemd', 'meinen neuen Schuhen'],
            ],
          },
          tip: l('kein, mein, dein, sein, ihr, unser … work exactly like ein.', 'kein, mein, dein, sein, ihr, unser … tıpkı ein gibi çalışır.', 'kein/mein/dein … wie ein.'),
        },
        {
          title: l('Wishes: Akkusativ', 'Dilekler: Akkusativ', 'Wünsche: Akkusativ'),
          body: l(
            'Many wishes are short for „Ich wünsche dir/Ihnen …“ + Akkusativ: Einen schönen Tag! Ein schönes Wochenende! Eine gute Reise! Viel Spaß!',
            'Birçok dilek „Ich wünsche dir/Ihnen …“ + Akkusativ’in kısaltmasıdır: Einen schönen Tag! Ein schönes Wochenende! Eine gute Reise! Viel Spaß!',
            'Einen schönen Tag! Ein schönes Wochenende!'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Finding a birthday present in a department store.', 'Bir mağazada doğum günü hediyesi aramak.', 'Ein Geburtstagsgeschenk im Kaufhaus suchen.'),
      dialogue: [
        { speaker: 'Verkäuferin', de: 'Guten Tag! Suchen Sie etwas Bestimmtes?', translation: l('Hello! Are you looking for something in particular?', 'İyi günler! Özel bir şey mi arıyorsunuz?', '') },
        { speaker: 'Murat', de: 'Ja, ich suche **ein schönes** Geschenk für meine Frau.', translation: l('Yes, I’m looking for a nice present for my wife.', 'Evet, eşim için güzel bir hediye arıyorum.', '') },
        { speaker: 'Verkäuferin', de: 'Vielleicht **einen warmen** Schal? Oder **eine elegante** Tasche?', translation: l('Maybe a warm scarf? Or an elegant bag?', 'Belki sıcak bir atkı? Ya da şık bir çanta?', '') },
        { speaker: 'Murat', de: 'Sie hat schon **einen karierten** Schal. Was kostet die rote Tasche?', translation: l('She already has a checked scarf. How much is the red bag?', 'Zaten kareli bir atkısı var. Kırmızı çanta ne kadar?', '') },
        { speaker: 'Verkäuferin', de: '89 Euro. Das ist **ein tolles** Modell – sehr praktisch!', translation: l('89 euros. It’s a great model – very practical!', '89 euro. Harika bir model – çok pratik!', '') },
        { speaker: 'Murat', de: 'Gut, ich nehme sie. Haben Sie auch **eine kleine** Karte?', translation: l('OK, I’ll take it. Do you also have a small card?', 'Tamam, alıyorum. Küçük bir kartınız da var mı?', '') },
        { speaker: 'Verkäuferin', de: 'Natürlich. Bitte schön – und **einen schönen** Tag noch!', translation: l('Of course. Here you are – and have a nice day!', 'Elbette. Buyurun – iyi günler!', '') },
      ],
      examples: [
        { de: 'Das ist **ein neuer** Laptop.', translation: l('That’s a new laptop.', 'Bu yeni bir dizüstü bilgisayar.', '') },
        { de: 'Wir haben **eine kleine** Küche.', translation: l('We have a small kitchen.', 'Küçük bir mutfağımız var.', '') },
        { de: 'Er fährt **ein altes** Auto.', translation: l('He drives an old car.', 'Eski bir araba kullanıyor.', '') },
        { de: 'Ich brauche **einen warmen** Pullover.', translation: l('I need a warm pullover.', 'Sıcak bir kazağa ihtiyacım var.', '') },
        { de: 'Ich wohne bei **einer netten** Familie.', translation: l('I live with a nice family.', 'Kibar bir ailenin yanında kalıyorum.', '') },
        { de: 'Das sind **meine neuen** Schuhe.', translation: l('These are my new shoes.', 'Bunlar yeni ayakkabılarım.', '') },
        { de: '**Ein schönes** Wochenende!', translation: l('Have a nice weekend!', 'İyi hafta sonları!', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('-er, -e, -es or -en?', '-er, -e, -es ya da -en?', '-er, -e, -es oder -en?'),
      exercises: ['sort-nom', 'match-endings', 'ein-nom-m', 'ein-nom-n', 'image-gestreift', 'select-right', 'tf-dativ', 'mc-kein', 'ein-akk-m'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Shopping, presents and wishes.', 'Alışveriş, hediyeler ve dilekler.', 'Einkaufen, Geschenke, Wünsche.'),
      exercises: [
        'fill-nom-m',
        'fill-akk-n',
        'fill-dat',
        'build-geschenk',
        'build-pullover',
        'build-freundin',
        'fix-ein-neue',
        'fix-einen-schoen',
        'fix-kleines',
        'tr-auto',
        'tr-wochenende',
        'match-wishes',
        'dialog-laden',
        'dialog-geburtstag',
        'ein-dat-f',
        'ein-poss-n',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('An online ad for second-hand furniture.', 'İkinci el mobilya için bir internet ilanı.', 'Eine Kleinanzeige.'),
      passage: [
        '**Zu verkaufen!** Wir ziehen in eine kleinere Wohnung und verkaufen deshalb einige Möbel.',
        'Wir verkaufen **ein großes** Sofa – sehr bequem und fast neu. Preis: 250 Euro.',
        'Außerdem haben wir **einen alten** Holztisch mit vier Stühlen. Der Tisch kostet nur 30 Euro.',
        'Und für Kinder: **ein kleines** Bett mit **einer weichen** Matratze – gratis! Kontakt: Familie Yıldız, Tel. 0151 234567',
      ],
      glossary: [
        { de: 'zu verkaufen', note: l('for sale', 'satılık', 'man kann es kaufen') },
        { de: 'kleiner', note: l('smaller', 'daha küçük', 'Komparativ von klein') },
        { de: 'der Holztisch', note: l('wooden table', 'ahşap masa', 'Tisch aus Holz') },
        { de: 'weich', note: l('soft', 'yumuşak', 'nicht hart') },
        { de: 'gratis', note: l('free', 'bedava', 'kostenlos') },
      ],
      exercises: ['read-was', 'read-sofa', 'read-preis', 'read-warum'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for -er, -es, -en.', '-er, -es, -en eklerine kulak ver.', 'Hör auf -er, -es, -en.'),
      exercises: ['listen-ending', 'listen-was', 'listen-sucht', 'listen-wunsch'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe your favourite clothes – and a present you once got.', 'En sevdiğin kıyafetleri – ve bir zamanlar aldığın bir hediyeyi – anlat.', 'Beschreib deine Lieblingskleidung und ein Geschenk.'),
      points: [
        l('„Ich trage gern einen/eine/ein …“', '„Ich trage gern einen/eine/ein …“', 'Was trägst du gern?'),
        l('„Mein Lieblingsstück ist ein/eine …“', '„Mein Lieblingsstück ist ein/eine …“', 'Lieblingsstück'),
        l('A present: „Ich habe einmal ein/eine/einen … bekommen.“', 'Bir hediye: „Ich habe einmal ein/eine/einen … bekommen.“', 'Ein Geschenk'),
      ],
      model: [
        'Ich trage gern einen bequemen Pullover und eine alte Jeans.',
        'Mein Lieblingsstück ist ein kariertes Hemd von meinem Opa.',
        'Zum Geburtstag habe ich einmal eine schöne Uhr bekommen.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a small ad (at least 4 sentences): sell three things and describe them with adjectives.',
        'Küçük bir ilan yaz (en az 4 cümle): üç eşya sat ve onları sıfatlarla tarif et.',
        'Schreib eine Kleinanzeige (mindestens 4 Sätze): drei Dinge mit Adjektiven.'
      ),
      minSentences: 4,
      checks: [
        { label: l('ein …er or ein …es (Nom./Akk.)', 'ein …er ya da ein …es (Nom./Akk.)', 'ein …er / ein …es'), pattern: '\\b([Ee]in|[Mm]ein|[Kk]ein) \\p{Ll}+(er|es) \\p{Lu}' },
        { label: l('einen …en', 'einen …en', 'einen …en'), pattern: '\\b([Ee]inen|[Mm]einen|[Kk]einen) \\p{Ll}+en \\p{Lu}' },
        { label: l('eine …e', 'eine …e', 'eine …e'), pattern: '\\b([Ee]ine|[Mm]eine|[Kk]eine) \\p{Ll}+e \\p{Lu}' },
      ],
      model: [
        'Ich verkaufe einen warmen Wintermantel, Größe M.',
        'Außerdem habe ich ein neues Fahrrad für Kinder.',
        'Es ist rot und sehr praktisch.',
        'Und ich verkaufe eine kleine Lampe für den Schreibtisch.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Endings after ein – 60 seconds.', 'ein’den sonra ekler – 60 saniye.', 'Endungen nach ein – 60 Sekunden.'),
      seconds: 60,
      pool: [...ENDING_DRILLS.map(([id]) => `ein-${id}`), 'mc-kein'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('ein neuer (m) · eine neue (f) · ein neues (n)', 'ein neuer (eril) · eine neue (dişil) · ein neues (nötr)', 'ein neuer / eine neue / ein neues'),
      l('einen neuen (Akk m) – Dativ & plural: -en', 'einen neuen (Akk eril) – Dativ ve çoğul: -en', 'einen neuen; Dativ/Plural -en'),
      l('kein, mein, dein … like ein', 'kein, mein, dein … ein gibi', 'kein/mein wie ein'),
      l('Wishes: Einen schönen Tag! Ein schönes Wochenende!', 'Dilekler: Einen schönen Tag! Ein schönes Wochenende!', 'Wünsche'),
    ],
    mistakes: [
      { wrong: 'Das ist ein neue Laptop.', right: 'Das ist ein neuer Laptop.', note: l('der → -er.', 'der → -er.', '-er.') },
      { wrong: 'ein schöne Wochenende', right: 'ein schönes Wochenende', note: l('das → -es.', 'das → -es.', '-es.') },
      { wrong: 'Ich suche einen kleine Tisch.', right: 'Ich suche einen kleinen Tisch.', note: l('einen → -en.', 'einen → -en.', '-en.') },
      { wrong: 'mit einer alte Freundin', right: 'mit einer alten Freundin', note: l('Dativ → -en.', 'Dativ → -en.', '-en.') },
    ],
  },
}
