import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Könnten Sie …?', emoji: '🙏', translation: l('Could you …?', '… -abilir misiniz?', 'höfliche Bitte'), example: 'Könnten Sie mir bitte helfen?' },
  { word: 'Ich würde gern …', emoji: '💬', translation: l('I would like to …', '… -mek isterim', 'höflicher Wunsch'), example: 'Ich würde gern ein Zimmer reservieren.' },
  { word: 'Ich hätte gern …', emoji: '☕', translation: l('I would like (to have) …', '… isterim', 'höflich bestellen'), example: 'Ich hätte gern ein Einzelzimmer.' },
  { word: 'Wäre es möglich, …?', emoji: '🤞', translation: l('Would it be possible …?', '… mümkün olur mu?', 'sehr höflich'), example: 'Wäre es möglich, später auszuchecken?' },
  { word: 'das Einzelzimmer', emoji: '🛏️', translation: l('single room', 'tek kişilik oda', 'Zimmer für eine Person'), example: 'Ein Einzelzimmer kostet 79 Euro.' },
  { word: 'das Doppelzimmer', emoji: '🛌', translation: l('double room', 'çift kişilik oda', 'Zimmer für zwei'), example: 'Wir möchten ein Doppelzimmer mit Balkon.' },
  { word: 'mit Frühstück', emoji: '🥐', translation: l('with breakfast', 'kahvaltı dahil', 'inklusive Frühstück'), example: 'Ist das Zimmer mit Frühstück?' },
  { word: 'einchecken / auschecken', emoji: '🔑', translation: l('to check in / out', 'giriş / çıkış yapmak', 'ankommen / abreisen'), example: 'Ab wann kann man einchecken?' },
  { word: 'die Rezeption', emoji: '🛎️', translation: l('reception', 'resepsiyon', 'Empfang im Hotel'), example: 'Bitte melden Sie sich an der Rezeption.' },
  { word: 'funktioniert nicht', emoji: '🚫', translation: l('doesn’t work', 'çalışmıyor', 'ist kaputt'), example: 'Die Heizung funktioniert nicht.' },
  { word: 'zu laut / zu kalt', emoji: '🔊', translation: l('too loud / too cold', 'çok gürültülü / çok soğuk', 'mehr als gut ist'), example: 'Das Zimmer ist zu laut.' },
  { word: 'sich beschweren', emoji: '😤', translation: l('to complain', 'şikâyet etmek', 'Kritik sagen'), example: 'Ich möchte mich beschweren.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Zimmer', gender: 'n', plural: 'die Zimmer', translation: l('room', 'oda', 'Zimmer') },
  { word: 'Schlüssel', gender: 'm', plural: 'die Schlüssel', translation: l('key', 'anahtar', 'Schlüssel') },
  { word: 'Heizung', gender: 'f', plural: 'die Heizungen', translation: l('heating', 'kalorifer', 'Heizung') },
  { word: 'Dusche', gender: 'f', plural: 'die Duschen', translation: l('shower', 'duş', 'Dusche') },
  { word: 'Handtuch', gender: 'n', plural: 'die Handtücher', translation: l('towel', 'havlu', 'Handtuch') },
  { word: 'Aufzug', gender: 'm', plural: 'die Aufzüge', translation: l('lift', 'asansör', 'Aufzug') },
  { word: 'Rechnung', gender: 'f', plural: 'die Rechnungen', translation: l('bill', 'hesap, fatura', 'Rechnung') },
  { word: 'Nacht', gender: 'f', plural: 'die Nächte', translation: l('night', 'gece', 'Nacht') },
]

/** [id, direct (impolite) sentence, polite form, two wrong options] */
const POLITE: [string, string, string, [string, string]][] = [
  ['handtuch', 'Bringen Sie mir ein Handtuch!', 'Könnten Sie mir bitte ein Handtuch bringen?', ['Können Sie mir bitte ein Handtuch gebracht?', 'Könnten Sie mir bitte ein Handtuch bringt?']],
  ['zimmer', 'Ich will ein anderes Zimmer.', 'Ich hätte gern ein anderes Zimmer.', ['Ich habe gern ein anderes Zimmer.', 'Ich würde gern ein anderes Zimmer haben gern.']],
  ['wecken', 'Wecken Sie mich um sechs!', 'Könnten Sie mich bitte um sechs wecken?', ['Könnten Sie mich bitte um sechs wecken Sie?', 'Könnten Sie wecken mich bitte um sechs?']],
  ['reservieren', 'Ich will einen Tisch reservieren.', 'Ich würde gern einen Tisch reservieren.', ['Ich würde gern einen Tisch reserviere.', 'Ich würde einen Tisch gern reservieren würde.']],
  ['auschecken', 'Ich checke um 14 Uhr aus.', 'Wäre es möglich, um 14 Uhr auszuchecken?', ['Wäre es möglich, um 14 Uhr checke aus?', 'Ist möglich, um 14 Uhr auschecken?']],
]

function politeDrills(): Exercise[] {
  return POLITE.map(([id, direct, polite, wrong], i) => {
    const options = [polite, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `hoeflich-${id}`,
      type: 'multiple_choice' as const,
      topic: 'hoeflich',
      concept: 'polite-forms',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: direct,
      promptL10n: l('Say it politely.', 'Kibarca söyle.', 'Sag es höflich.'),
      options: ordered,
      answer: ordered.indexOf(polite),
      explanation: l(
        'Polite forms: Könnten Sie …? / Ich würde gern … / Ich hätte gern … – the infinitive goes to the end.',
        'Kibar biçimler: Könnten Sie …? / Ich würde gern … / Ich hätte gern … – mastar sona gider.',
        'Könnten Sie …? / würde gern … / hätte gern …'
      ),
      examples: [polite],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-hotel',
    type: 'matching',
    topic: 'hotel',
    concept: 'hotel-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the words.', 'Kelimeleri eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'das Einzelzimmer', right: '🛏️' },
      { left: 'der Schlüssel', right: '🔑' },
      { left: 'die Rezeption', right: '🛎️' },
      { left: 'das Frühstück', right: '🥐' },
      { left: 'der Aufzug', right: '🛗' },
    ],
    explanation: l('Hotel vocabulary.', 'Otel kelimeleri.', 'Hotelwortschatz.'),
  },
  {
    id: 'sort-hoeflich',
    type: 'categorize',
    topic: 'hoeflich',
    concept: 'polite-or-not',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Polite or rather rude?', 'Kibar mı, yoksa kaba mı?', 'Höflich oder unhöflich?'),
    categories: ['höflich', 'unhöflich'],
    items: [
      { text: 'Könnten Sie mir helfen?', category: 0 },
      { text: 'Helfen Sie mir!', category: 1 },
      { text: 'Ich hätte gern einen Kaffee.', category: 0 },
      { text: 'Ich will Kaffee.', category: 1 },
      { text: 'Wäre es möglich, das Fenster zu öffnen?', category: 0 },
      { text: 'Fenster auf!', category: 1 },
    ],
    explanation: l('Konjunktiv II (könnten, hätte, würde, wäre) makes requests polite.', 'Konjunktiv II (könnten, hätte, würde, wäre) ricaları kibar yapar.', 'Konjunktiv II = höflich.'),
    practice: ['hoeflich-handtuch', 'hoeflich-zimmer'],
  },
  {
    id: 'match-forms',
    type: 'matching',
    topic: 'hoeflich',
    concept: 'k2-forms',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Present → polite form (Konjunktiv II).', 'Şimdiki zaman → kibar biçim (Konjunktiv II).', 'Präsens → Konjunktiv II.'),
    pairs: [
      { left: 'können', right: 'könnten' },
      { left: 'haben', right: 'hätte' },
      { left: 'sein', right: 'wäre' },
      { left: 'werden', right: 'würde' },
    ],
    explanation: l('Umlaut forms: können → könnte, haben → hätte, sein → wäre, werden → würde.', 'Umlaut’lu biçimler: können → könnte, haben → hätte, sein → wäre, werden → würde.', 'könnte, hätte, wäre, würde.'),
  },
  {
    id: 'mc-einzel',
    type: 'multiple_choice',
    topic: 'hotel',
    concept: 'room-types',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Wir sind zu zweit. Wir brauchen ein ___.',
    options: ['Doppelzimmer', 'Einzelzimmer', 'Badezimmer'],
    answer: 0,
    explanation: l('Two people → Doppelzimmer.', 'İki kişi → Doppelzimmer.', 'zu zweit → Doppelzimmer.'),
  },
  {
    id: 'select-problem',
    type: 'multiple_select',
    topic: 'beschwerde',
    concept: 'complaints',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which sentences are complaints? Select all.', 'Hangi cümleler şikâyet? Hepsini seç.', 'Welche Sätze sind Beschwerden?'),
    options: ['Die Heizung funktioniert nicht.', 'Das Frühstück war super.', 'Das Zimmer ist zu laut.', 'Es gibt keine Handtücher.', 'Vielen Dank für alles!'],
    answers: [0, 2, 3],
    explanation: l('funktioniert nicht, zu laut, es gibt keine … – typical problems.', 'funktioniert nicht, zu laut, es gibt keine … – tipik sorunlar.', 'Probleme.'),
  },
  {
    id: 'tf-zu',
    type: 'true_false',
    topic: 'beschwerde',
    concept: 'zu-adj',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Das Zimmer ist zu klein“ ist positiv.',
    answer: false,
    explanation: l('zu + adjective = more than is OK → negative.', 'zu + sıfat = olması gerekenden fazla → olumsuz.', 'zu = negativ.'),
    examples: ['Das Zimmer ist **zu** klein.'],
  },

  // --- Simulation: hotel -----------------------------------------------
  {
    id: 'dialog-checkin',
    type: 'dialogue',
    topic: 'hotel',
    concept: 'check-in',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Rezeption', de: 'Guten Abend! Haben Sie reserviert?' }],
    options: ['Ja, auf den Namen Demir. Ein Einzelzimmer für drei Nächte.', 'Ja, ich bin reserviert Demir.', 'Nein, ich will Zimmer.'],
    answer: 0,
    explanation: l('auf den Namen … = under the name …', 'auf den Namen … = … adına', 'auf den Namen …'),
  },
  {
    id: 'dialog-fruehstueck',
    type: 'dialogue',
    topic: 'hotel',
    concept: 'check-in',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Rezeption', de: 'Hier ist Ihr Schlüssel, Zimmer 214. Haben Sie noch Fragen?' }],
    options: ['Ja: Von wann bis wann gibt es Frühstück?', 'Ja: Wann gibt Frühstück es?', 'Nein, ich frage nicht.'],
    answer: 0,
    explanation: l('Von wann bis wann …? = From when to when …?', 'Von wann bis wann …? = Saat kaçtan kaça …?', 'Von wann bis wann?'),
  },
  {
    id: 'dialog-heizung',
    type: 'dialogue',
    topic: 'beschwerde',
    concept: 'complaints',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Rezeption', de: 'Rezeption, guten Abend. Was kann ich für Sie tun?' }],
    options: ['Entschuldigung, in Zimmer 214 funktioniert die Heizung nicht. Könnten Sie jemanden schicken?', 'Heizung kaputt. Machen Sie das!', 'Die Heizung funktioniert nicht, das ist gut.'],
    answer: 0,
    explanation: l('Problem + polite request (Könnten Sie …?).', 'Sorun + kibar rica (Könnten Sie …?).', 'Problem + höfliche Bitte.'),
  },
  {
    id: 'build-koennten',
    type: 'sentence_builder',
    topic: 'hoeflich',
    concept: 'koennten',
    skill: 'grammar',
    difficulty: 2,
    chips: ['bitte', 'Könnten', 'ein Taxi', 'Sie', 'rufen'],
    answers: [['Könnten', 'Sie', 'bitte', 'ein Taxi', 'rufen']],
    end: '?',
    translation: l('Could you call a taxi, please?', 'Lütfen bir taksi çağırabilir misiniz?', 'Könnten Sie bitte ein Taxi rufen?'),
    explanation: l('Könnten first (question), infinitive at the end.', 'Könnten başta (soru), mastar sonda.', 'Könnten Sie … rufen?'),
    examples: ['**Könnten** Sie bitte ein Taxi **rufen**?'],
  },
  {
    id: 'build-wuerde',
    type: 'sentence_builder',
    topic: 'hoeflich',
    concept: 'wuerde-gern',
    skill: 'grammar',
    difficulty: 2,
    chips: ['verlängern', 'gern', 'um eine Nacht', 'würde', 'Ich'],
    answers: [['Ich', 'würde', 'gern', 'um eine Nacht', 'verlängern']],
    translation: l('I’d like to extend by one night.', 'Bir gece uzatmak isterim.', 'Ich würde gern um eine Nacht verlängern.'),
    explanation: l('würde (2) + gern + … + infinitive (end).', 'würde (2) + gern + … + mastar (son).', 'würde gern … verlängern.'),
    examples: ['Ich **würde gern** um eine Nacht **verlängern**.'],
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-haette',
    type: 'fill_blank',
    topic: 'hoeflich',
    concept: 'haette-gern',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Guten Tag, ich ___ gern ein Doppelzimmer für zwei Nächte.',
    accepted: ['hätte'],
    base: 'haben → Konjunktiv II',
    explanation: l('Ich hätte gern … = I’d like …', 'Ich hätte gern … = … isterim', 'Ich hätte gern …'),
    examples: ['Ich **hätte** gern ein Doppelzimmer.'],
  },
  {
    id: 'fill-waere',
    type: 'fill_blank',
    topic: 'hoeflich',
    concept: 'waere',
    skill: 'grammar',
    difficulty: 2,
    sentence: '___ es möglich, das Gepäck hier zu lassen?',
    accepted: ['Wäre'],
    base: 'sein → Konjunktiv II',
    explanation: l('Wäre es möglich, … zu …? = Would it be possible …?', 'Wäre es möglich, … zu …? = … mümkün olur mu?', 'Wäre es möglich …?'),
    examples: ['**Wäre** es möglich, das Gepäck hier zu lassen?'],
  },
  {
    id: 'fill-koennten',
    type: 'fill_blank',
    topic: 'hoeflich',
    concept: 'koennten',
    skill: 'grammar',
    difficulty: 1,
    sentence: '___ Sie mir bitte die Rechnung geben?',
    accepted: ['Könnten', 'Können'],
    base: 'können (höflich)',
    explanation: l('Könnten Sie …? is the most polite form (Können Sie …? is also OK).', 'Könnten Sie …? en kibar biçimdir (Können Sie …? de olur).', 'Könnten Sie …?'),
    examples: ['**Könnten** Sie mir bitte die Rechnung geben?'],
  },
  {
    id: 'fix-wuerde',
    type: 'error_correction',
    topic: 'hoeflich',
    concept: 'wuerde-gern',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich würde gern bezahle mit Karte.',
    accepted: ['Ich würde gern mit Karte bezahlen.'],
    explanation: l('würde + infinitive at the end: … mit Karte bezahlen.', 'würde + mastar sonda: … mit Karte bezahlen.', 'würde … bezahlen.'),
    examples: ['Ich würde gern mit Karte **bezahlen**.'],
  },
  {
    id: 'fix-funktioniert',
    type: 'error_correction',
    topic: 'beschwerde',
    concept: 'complaints',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Dusche nicht funktioniert.',
    accepted: ['Die Dusche funktioniert nicht.'],
    explanation: l('Verb in position 2, nicht after it.', 'Fiil 2. sırada, nicht ardından.', 'funktioniert nicht.'),
    examples: ['Die Dusche **funktioniert nicht**.'],
  },
  {
    id: 'fix-haben-gern',
    type: 'error_correction',
    topic: 'hoeflich',
    concept: 'haette-gern',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe gern ein Zimmer mit Balkon.',
    accepted: ['Ich hätte gern ein Zimmer mit Balkon.'],
    explanation: l('Polite wish: hätte gern (not habe gern).', 'Kibar istek: hätte gern (habe gern değil).', 'hätte gern.'),
    examples: ['Ich **hätte** gern ein Zimmer mit Balkon.'],
  },
  {
    id: 'tr-koennten',
    type: 'translation',
    topic: 'hoeflich',
    concept: 'koennten',
    skill: 'writing',
    difficulty: 2,
    source: l('Could you wake me at seven, please?', 'Beni saat yedide uyandırabilir misiniz lütfen?', 'Could you wake me at seven, please?'),
    accepted: ['Könnten Sie mich bitte um sieben wecken?', 'Könnten Sie mich um sieben Uhr wecken?', 'Könnten Sie mich bitte um sieben Uhr wecken?', 'Könnten Sie mich um sieben wecken?'],
    explanation: l('Könnten Sie mich … wecken?', 'Könnten Sie mich … wecken?', 'Könnten Sie mich … wecken?'),
    examples: ['**Könnten** Sie mich bitte um sieben **wecken**?'],
  },
  {
    id: 'tr-laut',
    type: 'translation',
    topic: 'beschwerde',
    concept: 'zu-adj',
    skill: 'writing',
    difficulty: 1,
    source: l('The room is too loud.', 'Oda çok gürültülü.', 'The room is too loud.'),
    accepted: ['Das Zimmer ist zu laut.'],
    explanation: l('zu laut = too loud.', 'zu laut = fazla gürültülü.', 'zu laut.'),
    examples: ['Das Zimmer ist **zu** laut.'],
  },
  {
    id: 'ordering-checkin',
    type: 'ordering',
    topic: 'hotel',
    concept: 'check-in',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the hotel stay in order.', 'Otel konaklamasını sıraya koy.', 'Bring den Hotelaufenthalt in Ordnung.'),
    items: ['an der Rezeption auschecken', 'ein Zimmer online reservieren', 'den Schlüssel bekommen', 'im Hotel einchecken'],
    answer: ['ein Zimmer online reservieren', 'im Hotel einchecken', 'den Schlüssel bekommen', 'an der Rezeption auschecken'],
    explanation: l('reserve → check in → key → check out.', 'rezervasyon → giriş → anahtar → çıkış.', 'reservieren → einchecken → Schlüssel → auschecken.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-zimmer',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-bewertung',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was hat Familie Nowak gebucht?',
    options: ['Ein Doppelzimmer mit Balkon.', 'Ein Einzelzimmer.', 'Eine Ferienwohnung.'],
    answer: 0,
    explanation: l('„Wir hatten ein Doppelzimmer mit Balkon gebucht …“', '„Wir hatten ein Doppelzimmer mit Balkon gebucht …“', '„Doppelzimmer mit Balkon“'),
  },
  {
    id: 'read-problem',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-bewertung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was war das Problem?',
    options: ['Das Zimmer war zur Straße und sehr laut.', 'Das Frühstück war schlecht.', 'Der Aufzug war kaputt.'],
    answer: 0,
    explanation: l('„… aber das Zimmer lag direkt an der Straße und war sehr laut.“', '„… aber das Zimmer lag direkt an der Straße und war sehr laut.“', '„sehr laut“'),
  },
  {
    id: 'read-loesung',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-bewertung',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Rezeption hat das Problem gelöst.',
    answer: true,
    explanation: l('„Die Dame an der Rezeption hat uns sofort ein ruhiges Zimmer gegeben.“', '„Die Dame an der Rezeption hat uns sofort ein ruhiges Zimmer gegeben.“', '„sofort ein ruhiges Zimmer“'),
  },
  {
    id: 'read-sterne',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-bewertung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie bewertet die Familie das Hotel?',
    options: ['Gut – 4 von 5 Sternen.', 'Schlecht – 1 Stern.', 'Sie sagen es nicht.'],
    answer: 0,
    explanation: l('„★★★★☆ – Wir kommen gern wieder!“', '„★★★★☆ – Wir kommen gern wieder!“', '4 Sterne.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-fruehstueck',
    type: 'listening_choice',
    topic: 'hotel',
    concept: 'hotel-info',
    skill: 'listening',
    difficulty: 1,
    audio: 'Frühstück gibt es von halb sieben bis zehn Uhr im Erdgeschoss.',
    question: l('When is breakfast?', 'Kahvaltı ne zaman?', 'Wann gibt es Frühstück?'),
    options: ['6:30–10:00', '7:00–10:30', '6:00–9:30'],
    answer: 0,
    explanation: l('halb sieben = 6:30, bis zehn = 10:00.', 'halb sieben = 6:30, bis zehn = 10:00.', '6:30–10:00.'),
  },
  {
    id: 'listen-bitte',
    type: 'listening_choice',
    topic: 'hoeflich',
    concept: 'polite-forms',
    skill: 'listening',
    difficulty: 2,
    audio: 'Entschuldigung, könnten Sie mir noch zwei Handtücher bringen?',
    question: l('What does the guest want?', 'Misafir ne istiyor?', 'Was möchte der Gast?'),
    options: ['two towels', 'a key', 'breakfast'],
    answer: 0,
    explanation: l('„zwei Handtücher“', '„zwei Handtücher“', '„zwei Handtücher“'),
  },
  {
    id: 'listen-auschecken',
    type: 'listening_choice',
    topic: 'hotel',
    concept: 'check-out',
    skill: 'listening',
    difficulty: 2,
    audio: 'Auschecken ist bis elf Uhr. Wenn Sie später gehen möchten, kostet das zwanzig Euro extra.',
    question: l('What’s the check-out time?', 'Çıkış saati kaç?', 'Bis wann muss man auschecken?'),
    options: ['11:00', '12:00', '10:00'],
    answer: 0,
    explanation: l('„bis elf Uhr“', '„bis elf Uhr“', '11 Uhr.'),
  },
  {
    id: 'listen-beschwerde',
    type: 'listening_choice',
    topic: 'beschwerde',
    concept: 'complaints',
    skill: 'listening',
    difficulty: 2,
    audio: 'Guten Morgen. Leider gibt es in meinem Zimmer kein warmes Wasser.',
    question: l('What’s the problem?', 'Sorun ne?', 'Was ist das Problem?'),
    options: ['no hot water', 'too loud', 'no towels'],
    answer: 0,
    explanation: l('„kein warmes Wasser“', '„kein warmes Wasser“', '„kein warmes Wasser“'),
  },

  ...politeDrills(),
]

export const UNIT_A2_15_HOTEL: CourseUnit = {
  level: 'A2',
  number: 15,
  slug: 'hotel',
  titleDe: 'Im Hotel',
  title: l('At the hotel', 'Otelde', 'Im Hotel'),
  goal: l(
    'By the end of this unit you can book and check into a hotel, ask for things politely (Könnten Sie …? Ich würde gern … Ich hätte gern …) and complain about a problem in your room.',
    'Bu ünitenin sonunda otel rezervasyonu yapıp giriş yapabilir, bir şeyi kibarca isteyebilir (Könnten Sie …? Ich würde gern … Ich hätte gern …) ve odandaki bir sorundan şikâyet edebilirsin.',
    'Am Ende dieser Einheit buchst du ein Hotel, bittest höflich und beschwerst dich.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'hotel', label: l('Hotel words', 'Otel kelimeleri', 'Hotelwortschatz') },
    { key: 'hoeflich', label: l('Polite requests', 'Kibar ricalar', 'Höfliche Bitten') },
    { key: 'beschwerde', label: l('Complaints', 'Şikâyetler', 'Beschwerden') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Polite phrases and hotel words.', 'Kibar ifadeler ve otel kelimeleri.', 'Höfliche Sätze und Hotelwörter.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Being polite: Konjunktiv II', 'Kibar olmak: Konjunktiv II', 'Höflich sein: Konjunktiv II'),
          body: l(
            'Germans make requests polite with special forms: könnte (from können), hätte (haben), wäre (sein), würde (werden) + infinitive. „Ich will …“ sounds rude in a hotel or shop.',
            'Almanlar ricaları özel biçimlerle kibar yapar: könnte (können’den), hätte (haben), wäre (sein), würde (werden) + mastar. „Ich will …“ otelde ya da mağazada kaba duyulur.',
            'könnte, hätte, wäre, würde.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('können', 'können', 'können'), l('haben', 'haben', 'haben'), l('werden', 'werden', 'werden')],
            rows: [
              ['ich', 'könnte', 'hätte', 'würde'],
              ['du', 'könntest', 'hättest', 'würdest'],
              ['er / sie', 'könnte', 'hätte', 'würde'],
              ['wir / Sie', 'könnten', 'hätten', 'würden'],
            ],
          },
        },
        {
          title: l('Three patterns', 'Üç kalıp', 'Drei Muster'),
          body: l(
            'Asking someone: Könnten Sie (bitte) … + infinitive? – Wishes: Ich würde gern … + infinitive. – Things: Ich hätte gern + Akkusativ. – Very polite: Wäre es möglich, … zu + infinitive?',
            'Birinden rica: Könnten Sie (bitte) … + mastar? – İstekler: Ich würde gern … + mastar. – Şeyler: Ich hätte gern + Akkusativ. – Çok kibar: Wäre es möglich, … zu + mastar?',
            'Könnten Sie …? · würde gern … · hätte gern …'
          ),
          examples: [
            { de: '**Könnten** Sie mir bitte helfen?', translation: l('Could you help me, please?', 'Bana yardım edebilir misiniz lütfen?', '') },
            { de: 'Ich **würde gern** später auschecken.', translation: l('I’d like to check out later.', 'Daha geç çıkış yapmak istiyorum.', '') },
            { de: 'Ich **hätte gern** ein ruhiges Zimmer.', translation: l('I’d like a quiet room.', 'Sakin bir oda istiyorum.', '') },
          ],
        },
        {
          title: l('Complaining politely', 'Kibarca şikâyet etmek', 'Höflich beschweren'),
          body: l(
            'Entschuldigung, … funktioniert nicht. / Das Zimmer ist zu laut/kalt. / Es gibt keine Handtücher. + a polite request: Könnten Sie …?',
            'Entschuldigung, … funktioniert nicht. / Das Zimmer ist zu laut/kalt. / Es gibt keine Handtücher. + kibar bir rica: Könnten Sie …?',
            'Problem + Könnten Sie …?'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Mr Demir checks in – and later calls reception.', 'Bay Demir otele giriş yapıyor – ve daha sonra resepsiyonu arıyor.', 'Herr Demir checkt ein und ruft später die Rezeption an.'),
      dialogue: [
        { speaker: 'Rezeption', de: 'Guten Abend! Haben Sie reserviert?', translation: l('Good evening! Do you have a reservation?', 'İyi akşamlar! Rezervasyonunuz var mı?', '') },
        { speaker: 'Herr Demir', de: 'Ja, auf den Namen Demir. Ein **Einzelzimmer** für drei Nächte.', translation: l('Yes, under the name Demir. A single room for three nights.', 'Evet, Demir adına. Üç gecelik tek kişilik oda.', '') },
        { speaker: 'Rezeption', de: 'Genau. Zimmer 214, im zweiten Stock. Hier ist Ihr Schlüssel.', translation: l('Exactly. Room 214, on the second floor. Here is your key.', 'Evet. 214 numaralı oda, ikinci katta. Anahtarınız burada.', '') },
        { speaker: 'Herr Demir', de: 'Danke. **Könnten** Sie mich morgen um sechs **wecken**?', translation: l('Thank you. Could you wake me at six tomorrow?', 'Teşekkürler. Yarın beni saat altıda uyandırabilir misiniz?', '') },
        { speaker: 'Rezeption', de: 'Natürlich. Frühstück gibt es ab halb sieben.', translation: l('Of course. Breakfast is from 6:30.', 'Elbette. Kahvaltı altı buçuktan itibaren.', '') },
        { speaker: 'Herr Demir', de: '(später, am Telefon) Entschuldigung, die **Heizung funktioniert nicht**. Es ist **zu kalt**.', translation: l('(later, on the phone) Excuse me, the heating doesn’t work. It’s too cold.', '(daha sonra, telefonda) Affedersiniz, kalorifer çalışmıyor. Çok soğuk.', '') },
        { speaker: 'Rezeption', de: 'Oh, das tut mir leid! Ich schicke sofort jemanden.', translation: l('Oh, I’m sorry! I’ll send someone right away.', 'Ah, çok üzgünüm! Hemen birini gönderiyorum.', '') },
        { speaker: 'Herr Demir', de: 'Danke. Und **ich hätte gern** noch eine Decke.', translation: l('Thanks. And I’d like another blanket.', 'Teşekkürler. Bir battaniye daha istiyorum.', '') },
      ],
      examples: [
        { de: '**Könnten** Sie mir bitte helfen?', translation: l('Could you help me?', 'Bana yardım edebilir misiniz?', '') },
        { de: 'Ich **hätte gern** ein Doppelzimmer.', translation: l('I’d like a double room.', 'Çift kişilik bir oda istiyorum.', '') },
        { de: 'Ich **würde gern** um eine Nacht verlängern.', translation: l('I’d like to stay one more night.', 'Bir gece uzatmak isterim.', '') },
        { de: '**Wäre** es möglich, später auszuchecken?', translation: l('Would it be possible to check out later?', 'Daha geç çıkış yapmak mümkün olur mu?', '') },
        { de: 'Die Dusche **funktioniert nicht**.', translation: l('The shower doesn’t work.', 'Duş çalışmıyor.', '') },
        { de: 'Das Zimmer ist **zu laut**.', translation: l('The room is too noisy.', 'Oda çok gürültülü.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Hotel words and polite forms.', 'Otel kelimeleri ve kibar biçimler.', 'Hotelwörter und höfliche Formen.'),
      exercises: ['match-hotel', 'sort-hoeflich', 'match-forms', 'mc-einzel', 'select-problem', 'tf-zu', 'hoeflich-handtuch', 'hoeflich-zimmer'],
    },
    {
      key: 'practice-hotel',
      kind: 'practice',
      title: l('Simulation · Check-in & a problem', 'Simülasyon · Giriş ve bir sorun', 'Simulation · Check-in & Problem'),
      intro: l('You arrive at the hotel. Later something is wrong in your room.', 'Otele varıyorsun. Daha sonra odanda bir sorun çıkıyor.', 'Du kommst im Hotel an.'),
      exercises: ['dialog-checkin', 'dialog-fruehstueck', 'build-koennten', 'dialog-heizung', 'build-wuerde', 'fill-waere'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Ask politely – in any situation.', 'Her durumda kibarca rica et.', 'Höflich bitten.'),
      exercises: ['fill-haette', 'fill-koennten', 'fix-wuerde', 'fix-funktioniert', 'fix-haben-gern', 'tr-koennten', 'tr-laut', 'ordering-checkin', 'hoeflich-wecken', 'hoeflich-reservieren', 'hoeflich-auschecken'],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A hotel review on the internet.', 'İnternette bir otel yorumu.', 'Eine Hotelbewertung.'),
      passage: [
        '**★★★★☆ Hotel Lindenhof, Dresden** – Familie Nowak',
        'Wir hatten ein Doppelzimmer mit Balkon gebucht. Das Zimmer war sauber und schön, aber es lag direkt an der Straße und war sehr **laut**.',
        'Die Dame an der Rezeption war sehr freundlich und hat uns sofort ein ruhiges Zimmer zum Hof gegeben.',
        'Das Frühstück war super, besonders der Kuchen! Wir kommen gern wieder.',
      ],
      glossary: [
        { de: 'gebucht (buchen)', note: l('booked', 'rezerve etti', 'reserviert') },
        { de: 'lag (liegen)', note: l('was situated', 'bulunuyordu', 'Präteritum von liegen') },
        { de: 'der Hof', note: l('courtyard', 'avlu', 'Platz hinter dem Haus') },
      ],
      exercises: ['read-zimmer', 'read-problem', 'read-loesung', 'read-sterne'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Hotel information, requests and problems.', 'Otel bilgileri, ricalar ve sorunlar.', 'Infos, Bitten, Probleme.'),
      exercises: ['listen-fruehstueck', 'listen-bitte', 'listen-auschecken', 'listen-beschwerde'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Role play: check into a hotel, ask two questions and report a problem.', 'Rol oyunu: otele giriş yap, iki soru sor ve bir sorunu bildir.', 'Rollenspiel: einchecken, fragen, Problem melden.'),
      points: [
        l('Check in: name, room type, nights', 'Giriş: ad, oda tipi, gece sayısı', 'Einchecken'),
        l('Ask about breakfast or Wi-Fi', 'Kahvaltı ya da Wi-Fi hakkında sor', 'Frühstück / WLAN'),
        l('A problem: „… funktioniert nicht / ist zu …“', 'Bir sorun: „… funktioniert nicht / ist zu …“', 'Ein Problem'),
        l('A polite request: „Könnten Sie …?“', 'Kibar bir rica: „Könnten Sie …?“', 'Könnten Sie …?'),
      ],
      model: [
        'Guten Abend, ich habe ein Doppelzimmer auf den Namen Yılmaz reserviert.',
        'Von wann bis wann gibt es Frühstück? Und wie ist das WLAN-Passwort?',
        'Entschuldigung, in unserem Zimmer funktioniert das Licht im Bad nicht.',
        'Könnten Sie bitte jemanden schicken? Vielen Dank!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write an e-mail to a hotel (at least 4 sentences): book a room and ask for two things politely.',
        'Bir otele e-posta yaz (en az 4 cümle): bir oda ayırt ve iki şeyi kibarca iste.',
        'Schreib eine E-Mail an ein Hotel (mindestens 4 Sätze): Zimmer buchen, zwei höfliche Bitten.'
      ),
      minSentences: 4,
      checks: [
        { label: l('ich hätte gern / ich würde gern', 'ich hätte gern / ich würde gern', 'hätte/würde gern'), pattern: '\\b(hätte|würde)n? gern' },
        { label: l('Könnten Sie …? / Wäre es möglich …?', 'Könnten Sie …? / Wäre es möglich …?', 'Könnten Sie / Wäre es möglich'), pattern: '(Könnten Sie|Wäre es möglich)' },
        { label: l('Room type (Einzelzimmer / Doppelzimmer)', 'Oda tipi (Einzelzimmer / Doppelzimmer)', 'Zimmertyp'), pattern: '(Einzelzimmer|Doppelzimmer)' },
      ],
      model: [
        'Sehr geehrte Damen und Herren, ich hätte gern ein Doppelzimmer vom 12. bis 14. Mai.',
        'Wir würden gern ein ruhiges Zimmer mit Balkon haben.',
        'Wäre es möglich, schon um 12 Uhr einzuchecken?',
        'Könnten Sie mir auch sagen, ob es einen Parkplatz gibt?',
        'Mit freundlichen Grüßen, Ayşe Yılmaz',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Say it politely – 60 seconds.', 'Kibarca söyle – 60 saniye.', 'Sag es höflich – 60 Sekunden.'),
      seconds: 60,
      pool: [...POLITE.map(([id]) => `hoeflich-${id}`), 'mc-einzel'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Könnten Sie …? · Ich würde gern … · Ich hätte gern … · Wäre es möglich …?', 'Könnten Sie …? · Ich würde gern … · Ich hätte gern … · Wäre es möglich …?', 'höfliche Bitten'),
      l('Hotel: Einzel-/Doppelzimmer, einchecken, Rezeption, Frühstück', 'Otel: Einzel-/Doppelzimmer, einchecken, Rezeption, Frühstück', 'Hotel'),
      l('Complaints: funktioniert nicht, zu laut, es gibt kein …', 'Şikâyetler: funktioniert nicht, zu laut, es gibt kein …', 'Beschwerden'),
    ],
    mistakes: [
      { wrong: 'Ich will ein Zimmer.', right: 'Ich hätte gern ein Zimmer.', note: l('More polite.', 'Daha kibar.', 'höflicher.') },
      { wrong: 'Könnten Sie mir helfen bitte?', right: 'Könnten Sie mir bitte helfen?', note: l('Infinitive at the end.', 'Mastar sonda.', 'Infinitiv am Ende.') },
      { wrong: 'Ich würde gern bezahle.', right: 'Ich würde gern bezahlen.', note: l('würde + infinitive.', 'würde + mastar.', 'würde + Infinitiv.') },
      { wrong: 'Die Heizung nicht funktioniert.', right: 'Die Heizung funktioniert nicht.', note: l('Verb in position 2.', 'Fiil 2. sırada.', 'Verb Position 2.') },
    ],
  },
}
