import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'das Handy / Smartphone', emoji: '📱', translation: l('mobile phone', 'cep telefonu', 'Telefon'), example: 'Mein Handy ist leer.' },
  { word: 'herunterladen', emoji: '⬇️', translation: l('to download', 'indirmek', 'downloaden'), example: 'Lade die App herunter!' },
  { word: 'installieren', emoji: '⚙️', translation: l('to install', 'kurmak, yüklemek', 'auf das Gerät bringen'), example: 'Installieren Sie das Update.' },
  { word: 'klicken / tippen', emoji: '👆', translation: l('to click / tap', 'tıklamak / dokunmak', 'drücken'), example: 'Tippen Sie auf „Weiter“.' },
  { word: 'speichern', emoji: '💾', translation: l('to save', 'kaydetmek', 'sichern'), example: 'Speicher die Datei!' },
  { word: 'das Passwort', emoji: '🔒', translation: l('password', 'şifre', 'Geheimwort'), example: 'Gib dein Passwort ein.' },
  { word: 'sich anmelden / einloggen', emoji: '🔑', translation: l('to log in', 'giriş yapmak', 'einloggen'), example: 'Melden Sie sich mit Ihrer E-Mail an.' },
  { word: 'aufladen', emoji: '🔌', translation: l('to charge', 'şarj etmek', 'Akku voll machen'), example: 'Ich muss mein Handy aufladen.' },
  { word: 'der Akku', emoji: '🔋', translation: l('battery', 'pil, batarya', 'Batterie'), example: 'Der Akku ist fast leer.' },
  { word: 'das WLAN', emoji: '📶', translation: l('Wi-Fi', 'kablosuz internet', 'Internet ohne Kabel'), example: 'Wie ist das WLAN-Passwort?' },
  { word: 'schicken / senden', emoji: '📤', translation: l('to send', 'göndermek', 'senden'), example: 'Schick mir ein Foto!' },
  { word: 'die Nachricht', emoji: '💬', translation: l('message; news', 'mesaj; haber', 'SMS, Chat / Nachrichten im TV'), example: 'Ich habe deine Nachricht bekommen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'App', gender: 'f', plural: 'die Apps', translation: l('app', 'uygulama', 'App') },
  { word: 'Datei', gender: 'f', plural: 'die Dateien', translation: l('file', 'dosya', 'Datei') },
  { word: 'Bildschirm', gender: 'm', plural: 'die Bildschirme', translation: l('screen', 'ekran', 'Bildschirm') },
  { word: 'Ladekabel', gender: 'n', plural: 'die Ladekabel', translation: l('charging cable', 'şarj kablosu', 'Ladekabel') },
  { word: 'Passwort', gender: 'n', plural: 'die Passwörter', translation: l('password', 'şifre', 'Passwort') },
  { word: 'Nachricht', gender: 'f', plural: 'die Nachrichten', translation: l('message', 'mesaj', 'Nachricht') },
  { word: 'Handy', gender: 'n', plural: 'die Handys', translation: l('mobile phone', 'cep telefonu', 'Handy') },
]

/** [infinitive, du-imperative, ihr-imperative, Sie-imperative, rest of sentence] */
const IMPERATIVES: [string, string, string, string, string][] = [
  ['klicken', 'Klick', 'Klickt', 'Klicken Sie', 'auf „Speichern“!'],
  ['lesen', 'Lies', 'Lest', 'Lesen Sie', 'die Anleitung!'],
  ['nehmen', 'Nimm', 'Nehmt', 'Nehmen Sie', 'das Ladekabel mit!'],
  ['geben', 'Gib', 'Gebt', 'Geben Sie', 'das Passwort ein!'],
  ['schicken', 'Schick', 'Schickt', 'Schicken Sie', 'mir eine Nachricht!'],
  ['sein', 'Sei', 'Seid', 'Seien Sie', 'bitte vorsichtig!'],
  ['fahren', 'Fahr', 'Fahrt', 'Fahren Sie', 'den Computer herunter!'],
]

function imperativeDrills(): Exercise[] {
  return IMPERATIVES.map(([inf, du, ihr, , rest], i) => {
    const duForm: Record<string, string> = { lesen: 'Liest', sein: 'Bist', fahren: 'Fährst' }
    const wrongA = duForm[inf] ?? `${du}st`
    const wrongB = inf === 'lesen' ? 'Les' : inf === 'nehmen' ? 'Nehm' : inf === 'geben' ? 'Geb' : inf === 'fahren' ? 'Fähr' : ihr
    const options = [du, wrongA, wrongB]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const changes = ['lesen', 'nehmen', 'geben'].includes(inf)
    return {
      id: `imp-${inf}`,
      type: 'multiple_choice' as const,
      topic: 'imperativ',
      concept: changes ? 'imp-e-i' : inf === 'sein' ? 'imp-sein' : 'imp-du',
      skill: 'grammar' as const,
      difficulty: (changes || inf === 'sein' ? 2 : 1) as 1 | 2,
      prompt: `(du, ${inf}) ___ ${rest}`,
      options: ordered,
      answer: ordered.indexOf(du),
      explanation: changes
        ? l(`e → i(e) verbs keep the change: du ${inf === 'lesen' ? 'liest' : inf === 'nehmen' ? 'nimmst' : 'gibst'} → ${du}!`, `e → i(e) fiilleri değişimi korur: du ${inf === 'lesen' ? 'liest' : inf === 'nehmen' ? 'nimmst' : 'gibst'} → ${du}!`, `${du}!`)
        : inf === 'sein'
          ? l('sein is irregular: Sei! Seid! Seien Sie!', 'sein düzensizdir: Sei! Seid! Seien Sie!', 'Sei!')
          : inf === 'fahren'
            ? l('a → ä does NOT stay in the imperative: du fährst → Fahr!', 'a → ä emir kipinde KALMAZ: du fährst → Fahr!', 'Fahr! (ohne Umlaut)')
            : l(`du-form without -st and without du: du ${inf.replace(/en$/, '')}st → ${du}!`, `-st ve du olmadan du-biçimi: du ${inf.replace(/en$/, '')}st → ${du}!`, `${du}!`),
      examples: [`**${du}** ${rest}`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-medien',
    type: 'matching',
    topic: 'medien',
    concept: 'media-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match word and symbol.', 'Kelimeyi sembolle eşleştir.', 'Ordne Wort und Symbol zu.'),
    pairs: [
      { left: 'herunterladen', right: '⬇️' },
      { left: 'speichern', right: '💾' },
      { left: 'das WLAN', right: '📶' },
      { left: 'der Akku', right: '🔋' },
      { left: 'das Passwort', right: '🔒' },
    ],
    explanation: l('Basic tech vocabulary.', 'Temel teknoloji kelimeleri.', 'Technik-Wortschatz.'),
  },
  {
    id: 'sort-person',
    type: 'categorize',
    topic: 'imperativ',
    concept: 'imp-persons',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Who is spoken to: du, ihr or Sie?', 'Kime hitap ediliyor: du, ihr mi Sie mi?', 'Wer ist gemeint: du, ihr oder Sie?'),
    categories: ['du', 'ihr', 'Sie'],
    items: [
      { text: 'Klick hier!', category: 0 },
      { text: 'Klickt hier!', category: 1 },
      { text: 'Klicken Sie hier!', category: 2 },
      { text: 'Nimm das Kabel!', category: 0 },
      { text: 'Nehmt das Kabel!', category: 1 },
      { text: 'Nehmen Sie das Kabel!', category: 2 },
    ],
    explanation: l('du: stem (Klick!), ihr: -t (Klickt!), Sie: infinitive + Sie (Klicken Sie!).', 'du: kök (Klick!), ihr: -t (Klickt!), Sie: mastar + Sie (Klicken Sie!).', 'Klick! Klickt! Klicken Sie!'),
    practice: ['imp-klicken', 'imp-nehmen'],
  },
  {
    id: 'ordering-anleitung',
    type: 'ordering',
    topic: 'anleitung',
    concept: 'instructions-order',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the instructions for a new app in order.', 'Yeni bir uygulamanın talimatlarını sıraya koy.', 'Bring die Anleitung in Ordnung.'),
    items: ['Melden Sie sich mit Ihrer E-Mail an.', 'Laden Sie die App herunter.', 'Fertig! Jetzt können Sie die App benutzen.', 'Öffnen Sie die App.'],
    answer: ['Laden Sie die App herunter.', 'Öffnen Sie die App.', 'Melden Sie sich mit Ihrer E-Mail an.', 'Fertig! Jetzt können Sie die App benutzen.'],
    explanation: l('download → open → log in → done.', 'indir → aç → giriş yap → bitti.', 'herunterladen → öffnen → anmelden → fertig.'),
  },
  {
    id: 'tf-imperativ',
    type: 'true_false',
    topic: 'imperativ',
    concept: 'imp-du',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Im Imperativ mit „du“ sagt man das Wort „du“ nicht: „Komm!“, nicht „Komm du!“',
    answer: true,
    explanation: l('du and ihr disappear in the imperative. Only Sie stays.', 'du ve ihr emir kipinde düşer. Yalnızca Sie kalır.', 'Kein du/ihr; aber Sie bleibt.'),
  },
  {
    id: 'select-sie',
    type: 'multiple_select',
    topic: 'imperativ',
    concept: 'imp-sie',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which are correct formal (Sie) imperatives? Select all.', 'Hangileri doğru resmî (Sie) emir? Hepsini seç.', 'Welche Sie-Imperative sind richtig?'),
    options: ['Geben Sie Ihr Passwort ein!', 'Gib Sie Ihr Passwort ein!', 'Laden Sie die App herunter!', 'Sie klicken hier!', 'Speichern Sie die Datei!'],
    answers: [0, 2, 4],
    explanation: l('Sie-imperative: infinitive + Sie + … (+ prefix at the end).', 'Sie emri: mastar + Sie + … (+ ön ek sonda).', 'Infinitiv + Sie.'),
  },
  {
    id: 'image-akku',
    type: 'image_choice',
    topic: 'medien',
    concept: 'media-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Der Akku ist leer. Lade das Handy auf!',
    options: [
      { emoji: '🔌', label: 'aufladen' },
      { emoji: '💾', label: 'speichern' },
      { emoji: '📤', label: 'senden' },
      { emoji: '🔒', label: 'sperren' },
    ],
    answer: 0,
    explanation: l('aufladen = to charge 🔌.', 'aufladen = şarj etmek 🔌.', 'aufladen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-lies',
    type: 'fill_blank',
    topic: 'imperativ',
    concept: 'imp-e-i',
    skill: 'grammar',
    difficulty: 2,
    sentence: '___ bitte zuerst die E-Mail! (lesen, du)',
    accepted: ['Lies'],
    base: 'lesen',
    explanation: l('du liest → Lies!', 'du liest → Lies!', 'Lies!'),
    examples: ['**Lies** bitte zuerst die E-Mail!'],
  },
  {
    id: 'fill-ladet',
    type: 'fill_blank',
    topic: 'imperativ',
    concept: 'imp-ihr',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Kinder, ___ eure Tablets heute Abend auf! (laden, ihr)',
    accepted: ['ladet'],
    base: 'auf|laden',
    explanation: l('ihr-imperative = ihr-form without ihr: ihr ladet → Ladet … auf!', 'ihr emri = ihr olmadan ihr-biçimi: ihr ladet → Ladet … auf!', 'Ladet … auf!'),
    examples: ['Kinder, **ladet** eure Tablets **auf**!'],
  },
  {
    id: 'fill-sie',
    type: 'fill_blank',
    topic: 'imperativ',
    concept: 'imp-sie',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Bitte ___ Sie das Formular. (speichern)',
    accepted: ['speichern'],
    base: 'speichern',
    explanation: l('Sie-imperative: infinitive + Sie.', 'Sie emri: mastar + Sie.', 'speichern Sie.'),
    examples: ['Bitte **speichern Sie** das Formular.'],
  },
  {
    id: 'build-herunter',
    type: 'sentence_builder',
    topic: 'anleitung',
    concept: 'imp-separable',
    skill: 'grammar',
    difficulty: 2,
    chips: ['herunter', 'die App', 'Sie', 'Laden'],
    answers: [['Laden', 'Sie', 'die App', 'herunter']],
    end: '!',
    translation: l('Download the app!', 'Uygulamayı indirin!', 'Laden Sie die App herunter!'),
    explanation: l('Imperative first, separable prefix at the end.', 'Emir başta, ayrılabilen ön ek sonda.', 'Laden Sie … herunter!'),
    examples: ['**Laden** Sie die App **herunter**!'],
  },
  {
    id: 'build-schick',
    type: 'sentence_builder',
    topic: 'imperativ',
    concept: 'imp-du',
    skill: 'grammar',
    difficulty: 1,
    chips: ['bitte', 'das Foto', 'mir', 'Schick'],
    answers: [['Schick', 'mir', 'bitte', 'das Foto'], ['Schick', 'mir', 'das Foto', 'bitte']],
    end: '!',
    translation: l('Please send me the photo!', 'Lütfen bana fotoğrafı gönder!', 'Schick mir bitte das Foto!'),
    explanation: l('du-imperative first: Schick …!', 'du emri başta: Schick …!', 'Schick mir …!'),
    examples: ['**Schick** mir bitte das Foto!'],
  },
  {
    id: 'build-sei',
    type: 'sentence_builder',
    topic: 'imperativ',
    concept: 'imp-sein',
    skill: 'grammar',
    difficulty: 2,
    chips: ['nicht', 'Sei', 'so', 'traurig'],
    answers: [['Sei', 'nicht', 'so', 'traurig']],
    end: '!',
    translation: l('Don’t be so sad!', 'Bu kadar üzülme!', 'Sei nicht so traurig!'),
    explanation: l('sein → Sei!', 'sein → Sei!', 'Sei!'),
    examples: ['**Sei** nicht so traurig!'],
  },
  {
    id: 'fix-gibst',
    type: 'error_correction',
    topic: 'imperativ',
    concept: 'imp-e-i',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Gibst mir bitte das Ladekabel!',
    accepted: ['Gib mir bitte das Ladekabel!', 'Gib mir bitte das Ladekabel.'],
    explanation: l('Imperative without -st: Gib!', 'Emir -st olmadan: Gib!', 'Gib!'),
    examples: ['**Gib** mir bitte das Ladekabel!'],
  },
  {
    id: 'fix-faehr',
    type: 'error_correction',
    topic: 'imperativ',
    concept: 'imp-du',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Fähr bitte langsam!',
    accepted: ['Fahr bitte langsam!', 'Fahr bitte langsam.', 'Fahre bitte langsam!'],
    explanation: l('a → ä is not used in the imperative: Fahr!', 'a → ä emir kipinde kullanılmaz: Fahr!', 'Fahr!'),
    examples: ['**Fahr** bitte langsam!'],
  },
  {
    id: 'fix-sie-position',
    type: 'error_correction',
    topic: 'imperativ',
    concept: 'imp-sie',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie installieren bitte das Update!',
    accepted: ['Installieren Sie bitte das Update!', 'Installieren Sie bitte das Update.', 'Bitte installieren Sie das Update!'],
    explanation: l('Imperative: verb first, then Sie.', 'Emir: önce fiil, sonra Sie.', 'Installieren Sie …!'),
    examples: ['**Installieren Sie** bitte das Update!'],
  },
  {
    id: 'tr-passwort',
    type: 'translation',
    topic: 'imperativ',
    concept: 'imp-e-i',
    skill: 'writing',
    difficulty: 2,
    source: l('Enter your password! (du)', 'Şifreni gir! (du)', 'Enter your password! (du)'),
    accepted: ['Gib dein Passwort ein!', 'Gib dein Passwort ein.', 'Gib dein Passwort ein'],
    explanation: l('ein|geben, du: Gib … ein!', 'ein|geben, du: Gib … ein!', 'Gib … ein!'),
    examples: ['**Gib** dein Passwort **ein**!'],
  },
  {
    id: 'tr-speichern',
    type: 'translation',
    topic: 'imperativ',
    concept: 'imp-sie',
    skill: 'writing',
    difficulty: 1,
    source: l('Please save the file. (Sie)', 'Lütfen dosyayı kaydedin. (Sie)', 'Please save the file. (Sie)'),
    accepted: ['Bitte speichern Sie die Datei.', 'Speichern Sie bitte die Datei.', 'Speichern Sie bitte die Datei!', 'Bitte speichern Sie die Datei!'],
    explanation: l('Speichern Sie …!', 'Speichern Sie …!', 'Speichern Sie …'),
    examples: ['**Speichern Sie** bitte die Datei.'],
  },
  {
    id: 'dialog-hilfe',
    type: 'dialogue',
    topic: 'anleitung',
    concept: 'tech-help',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Oma', de: 'Wie schicke ich dir ein Foto?' }],
    options: ['Öffne die App, tipp auf das Foto und dann auf „Senden“.', 'Öffnest die App und tippst Senden.', 'Du öffnen die App!'],
    answer: 0,
    explanation: l('Step-by-step with du-imperatives.', 'du emirleriyle adım adım.', 'Öffne …, tipp …'),
  },
  {
    id: 'dialog-wlan',
    type: 'dialogue',
    topic: 'medien',
    concept: 'media-words',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Gast', de: 'Entschuldigung, gibt es hier WLAN?' }],
    options: ['Ja, das Passwort steht auf der Karte am Tisch.', 'Ja, das WLAN ist ein Passwort.', 'Nein, hier gibt es Akku.'],
    answer: 0,
    explanation: l('A natural answer about the Wi-Fi password.', 'WLAN şifresi hakkında doğal bir cevap.', 'Passwort auf der Karte.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-zuerst',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anleitung',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was soll man zuerst machen?',
    options: ['Die App „StadtBus“ herunterladen.', 'Ein Ticket kaufen.', 'Den Busfahrer fragen.'],
    answer: 0,
    explanation: l('„1. Laden Sie die App „StadtBus“ herunter.“', '„1. Laden Sie die App „StadtBus“ herunter.“', 'herunterladen.'),
  },
  {
    id: 'read-bezahlen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anleitung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie kann man bezahlen?',
    options: ['Mit Karte oder PayPal.', 'Nur bar.', 'Gar nicht.'],
    answer: 0,
    explanation: l('„Bezahlen Sie mit Karte oder PayPal.“', '„Bezahlen Sie mit Karte oder PayPal.“', 'Karte oder PayPal.'),
  },
  {
    id: 'read-zeigen',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-anleitung',
    skill: 'reading',
    difficulty: 2,
    statement: 'Man muss das Ticket im Bus zeigen.',
    answer: true,
    explanation: l('„Zeigen Sie das Ticket im Bus auf dem Handy.“', '„Zeigen Sie das Ticket im Bus auf dem Handy.“', 'zeigen.'),
  },
  {
    id: 'read-akku',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anleitung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist der Tipp am Ende?',
    options: ['Den Akku vorher aufladen.', 'Das Passwort aufschreiben.', 'Das Ticket ausdrucken.'],
    answer: 0,
    explanation: l('„Tipp: Laden Sie Ihr Handy vorher auf!“', '„Tipp: Laden Sie Ihr Handy vorher auf!“', 'aufladen.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-anleitung',
    type: 'listening_choice',
    topic: 'anleitung',
    concept: 'instructions-order',
    skill: 'listening',
    difficulty: 2,
    audio: 'Klicken Sie zuerst auf „Anmelden“ und geben Sie dann Ihre E-Mail-Adresse ein.',
    question: l('What do you do first?', 'Önce ne yapıyorsun?', 'Was macht man zuerst?'),
    options: ['click „Anmelden“', 'enter the e-mail', 'download the app'],
    answer: 0,
    explanation: l('„zuerst auf ‚Anmelden‘“', '„zuerst auf ‚Anmelden‘“', 'zuerst klicken.'),
  },
  {
    id: 'listen-person',
    type: 'listening_choice',
    topic: 'imperativ',
    concept: 'imp-persons',
    skill: 'listening',
    difficulty: 2,
    audio: 'Macht bitte eure Handys aus!',
    question: l('Who is spoken to?', 'Kime hitap ediliyor?', 'Wer ist gemeint?'),
    options: ['ihr (several people)', 'du (one friend)', 'Sie (formal)'],
    answer: 0,
    explanation: l('„Macht … eure“ → ihr.', '„Macht … eure“ → ihr.', 'ihr.'),
  },
  {
    id: 'listen-akku',
    type: 'listening_choice',
    topic: 'medien',
    concept: 'media-words',
    skill: 'listening',
    difficulty: 1,
    audio: 'Mein Akku ist leer. Hast du ein Ladekabel für mich?',
    question: l('What does the person need?', 'Kişinin neye ihtiyacı var?', 'Was braucht die Person?'),
    options: ['🔌', '💾', '📶'],
    answer: 0,
    explanation: l('Ladekabel = charging cable 🔌.', 'Ladekabel = şarj kablosu 🔌.', 'Ladekabel.'),
  },
  {
    id: 'listen-nachricht',
    type: 'listening_choice',
    topic: 'medien',
    concept: 'message',
    skill: 'listening',
    difficulty: 2,
    audio: 'Schick mir bitte eine Nachricht, wenn du angekommen bist.',
    question: l('When should the message be sent?', 'Mesaj ne zaman gönderilmeli?', 'Wann soll die Nachricht kommen?'),
    options: ['after arriving', 'before leaving', 'in the morning'],
    answer: 0,
    explanation: l('„wenn du angekommen bist“', '„wenn du angekommen bist“', 'nach der Ankunft.'),
  },

  ...imperativeDrills(),
]

export const UNIT_A2_19_MEDIEN: CourseUnit = {
  level: 'A2',
  number: 19,
  slug: 'medien',
  titleDe: 'Handy, Internet & Co.',
  title: l('Phones, internet & co.', 'Telefon, internet ve diğerleri', 'Handy, Internet & Co.'),
  goal: l(
    'By the end of this unit you can talk about phones and apps, understand simple instructions and give them yourself with the imperative: Klick! Klickt! Klicken Sie!',
    'Bu ünitenin sonunda telefonlar ve uygulamalar hakkında konuşabilir, basit talimatları anlayabilir ve emir kipiyle kendin verebilirsin: Klick! Klickt! Klicken Sie!',
    'Am Ende dieser Einheit verstehst und gibst du Anleitungen mit dem Imperativ.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'medien', label: l('Media & tech', 'Medya ve teknoloji', 'Medien & Technik') },
    { key: 'imperativ', label: l('Imperative', 'Emir kipi', 'Imperativ') },
    { key: 'anleitung', label: l('Instructions', 'Talimatlar', 'Anleitungen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Twelve words for your phone and computer.', 'Telefonun ve bilgisayarın için on iki kelime.', 'Zwölf Wörter für Handy und Computer.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('The imperative: du, ihr, Sie', 'Emir kipi: du, ihr, Sie', 'Imperativ: du, ihr, Sie'),
          body: l(
            'du: the du-form without -st and without du (du klickst → Klick!). ihr: the ihr-form without ihr (Klickt!). Sie: infinitive + Sie (Klicken Sie!). The verb comes first; separable prefixes go to the end.',
            'du: -st ve du olmadan du-biçimi (du klickst → Klick!). ihr: ihr olmadan ihr-biçimi (Klickt!). Sie: mastar + Sie (Klicken Sie!). Fiil başa gelir; ayrılabilen ön ekler sona gider.',
            'Klick! · Klickt! · Klicken Sie!'
          ),
          table: {
            head: [l('Verb', 'Fiil', 'Verb'), l('du', 'du', 'du'), l('ihr', 'ihr', 'ihr'), l('Sie', 'Sie', 'Sie')],
            rows: IMPERATIVES.map(([inf, du, ihr, sie]) => [inf, `${du}!`, `${ihr}!`, `${sie}!`]),
          },
        },
        {
          title: l('Special cases', 'Özel durumlar', 'Besonderheiten'),
          body: l(
            'e → i(e) stays: du liest → Lies!, du nimmst → Nimm!, du gibst → Gib! – a → ä does not: du fährst → Fahr! – sein: Sei! Seid! Seien Sie!',
            'e → i(e) korunur: du liest → Lies!, du nimmst → Nimm!, du gibst → Gib! – a → ä korunmaz: du fährst → Fahr! – sein: Sei! Seid! Seien Sie!',
            'Lies! Nimm! Gib! – Fahr! – Sei!'
          ),
          tip: l('Make it friendlier with bitte, doch or mal: Klick doch mal hier!', 'bitte, doch ya da mal ile daha samimi yap: Klick doch mal hier!', 'bitte / doch / mal.'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Tim helps his grandmother with her new smartphone.', 'Tim büyükannesine yeni akıllı telefonunda yardım ediyor.', 'Tim hilft Oma mit dem Smartphone.'),
      dialogue: [
        { speaker: 'Oma', de: 'Tim, ich möchte dir ein Foto schicken. Wie geht das?', translation: l('Tim, I want to send you a photo. How does that work?', 'Tim, sana bir fotoğraf göndermek istiyorum. Nasıl yapılıyor?', '') },
        { speaker: 'Tim', de: 'Ganz einfach, Oma. **Öffne** zuerst die Foto-App.', translation: l('Very easy, Grandma. First open the photo app.', 'Çok kolay babaanne. Önce fotoğraf uygulamasını aç.', '') },
        { speaker: 'Oma', de: 'Okay … Und jetzt?', translation: l('OK … And now?', 'Tamam … Şimdi?', '') },
        { speaker: 'Tim', de: '**Tipp** auf das Foto und dann auf das Symbol mit dem Pfeil.', translation: l('Tap the photo and then the symbol with the arrow.', 'Fotoğrafa, sonra oklu simgeye dokun.', '') },
        { speaker: 'Oma', de: 'Hier? Oh, jetzt fragt es nach einem **Passwort**!', translation: l('Here? Oh, now it’s asking for a password!', 'Burası mı? Ah, şimdi şifre soruyor!', '') },
        { speaker: 'Tim', de: 'Keine Panik! **Gib** dein Passwort **ein** – das steht auf dem Zettel. Und **sei** nicht so nervös!', translation: l('Don’t panic! Enter your password – it’s on the note. And don’t be so nervous!', 'Panik yok! Şifreni gir – kâğıtta yazıyor. Bu kadar da gerilme!', '') },
        { speaker: 'Oma', de: 'Geschafft! Ach, und mein **Akku** ist fast leer …', translation: l('Done! Oh, and my battery is almost empty …', 'Başardım! Ah, bir de pilim neredeyse bitmiş …', '') },
        { speaker: 'Tim', de: 'Dann **lade** das Handy heute Abend **auf**. **Nimm** dieses Kabel!', translation: l('Then charge the phone tonight. Take this cable!', 'O zaman telefonu bu akşam şarj et. Bu kabloyu al!', '') },
      ],
      examples: [
        { de: '**Klick** auf „Weiter“!', translation: l('Click on „Next“! (du)', '„İleri“ye tıkla!', '') },
        { de: '**Klickt** auf „Weiter“!', translation: l('Click on „Next“! (ihr)', '„İleri“ye tıklayın! (ihr)', '') },
        { de: '**Klicken Sie** auf „Weiter“!', translation: l('Click on „Next“! (Sie)', '„İleri“ye tıklayın! (Sie)', '') },
        { de: '**Lies** die Anleitung!', translation: l('Read the instructions!', 'Talimatları oku!', '') },
        { de: '**Lade** die App **herunter**!', translation: l('Download the app!', 'Uygulamayı indir!', '') },
        { de: '**Sei** bitte leise!', translation: l('Please be quiet!', 'Lütfen sessiz ol!', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Tech words and imperatives.', 'Teknoloji kelimeleri ve emirler.', 'Technikwörter und Imperative.'),
      exercises: ['match-medien', 'sort-person', 'imp-klicken', 'imp-lesen', 'ordering-anleitung', 'tf-imperativ', 'select-sie', 'image-akku', 'imp-nehmen'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Give instructions.', 'Talimat ver.', 'Gib Anweisungen.'),
      exercises: [
        'fill-lies',
        'fill-ladet',
        'fill-sie',
        'build-herunter',
        'build-schick',
        'build-sei',
        'fix-gibst',
        'fix-faehr',
        'fix-sie-position',
        'tr-passwort',
        'tr-speichern',
        'dialog-hilfe',
        'dialog-wlan',
        'imp-geben',
        'imp-sein',
        'imp-fahren',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('How to buy a bus ticket with an app.', 'Uygulamayla otobüs bileti nasıl alınır.', 'Busticket per App.'),
      passage: [
        '**So kaufen Sie Ihr Busticket mit dem Handy:**',
        '1. **Laden** Sie die App „StadtBus“ **herunter**. 2. **Melden** Sie **sich** mit Ihrer E-Mail-Adresse **an**.',
        '3. **Wählen** Sie Ihr Ticket. 4. **Bezahlen** Sie mit Karte oder PayPal. 5. **Zeigen** Sie das Ticket im Bus auf dem Handy.',
        'Tipp: **Laden** Sie Ihr Handy vorher **auf** – ohne Akku kein Ticket!',
      ],
      glossary: [
        { de: 'wählen', note: l('to choose', 'seçmek', 'aussuchen') },
        { de: 'zeigen', note: l('to show', 'göstermek', 'sehen lassen') },
        { de: 'vorher', note: l('beforehand', 'önceden', 'davor') },
      ],
      exercises: ['read-zuerst', 'read-bezahlen', 'read-zeigen', 'read-akku'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Instructions and tech problems.', 'Talimatlar ve teknoloji sorunları.', 'Anweisungen und Technikprobleme.'),
      exercises: ['listen-anleitung', 'listen-person', 'listen-akku', 'listen-nachricht'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Explain to a friend (du) how to do something on the phone – e.g. send a photo or download an app.', 'Bir arkadaşına (du) telefonda bir şeyi nasıl yapacağını anlat – örneğin fotoğraf göndermek ya da uygulama indirmek.', 'Erklär einem Freund etwas am Handy.'),
      points: [
        l('Step 1: „Öffne zuerst …“', '1. adım: „Öffne zuerst …“', 'zuerst …'),
        l('Step 2: „Dann tipp auf …“', '2. adım: „Dann tipp auf …“', 'dann …'),
        l('Step 3: a separable verb (Gib … ein / Lade … herunter)', '3. adım: ayrılabilen bir fiil (Gib … ein / Lade … herunter)', 'trennbares Verb'),
        l('Encourage: „Sei nicht nervös – das ist ganz einfach!“', 'Cesaret ver: „Sei nicht nervös – das ist ganz einfach!“', 'Mut machen'),
      ],
      model: [
        'Öffne zuerst den App Store.',
        'Dann tipp oben auf die Suche und schreib den Namen der App.',
        'Lade die App herunter und gib dein Passwort ein.',
        'Sei nicht nervös – das ist ganz einfach!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write short instructions (at least 4 sentences) for guests in your flat: Wi-Fi, TV, coffee machine … Use Sie or ihr.',
        'Evindeki misafirler için kısa talimatlar yaz (en az 4 cümle): WLAN, televizyon, kahve makinesi … Sie ya da ihr kullan.',
        'Schreib eine kurze Anleitung (mindestens 4 Sätze) für Gäste.'
      ),
      minSentences: 4,
      checks: [
        { label: l('A Sie- or ihr-imperative', 'Bir Sie- ya da ihr- emri', 'Ein Sie- oder ihr-Imperativ'), pattern: '(^|[.!?]\\s+)(\\p{Lu}\\p{Ll}+en Sie|\\p{Lu}\\p{Ll}+t)\\b' },
        { label: l('A separable verb (… ein / … an / … aus)', 'Ayrılabilen bir fiil (… ein / … an / … aus)', 'Ein trennbares Verb'), pattern: '\\b(ein|an|aus|auf|herunter|ab)[.!]' },
        { label: l('bitte', 'bitte', 'bitte'), pattern: '\\b[Bb]itte\\b' },
      ],
      model: [
        'Herzlich willkommen in unserer Wohnung!',
        'Das WLAN-Passwort steht auf dem Router – geben Sie es bitte genau so ein.',
        'Für den Fernseher nehmen Sie die schwarze Fernbedienung.',
        'Machen Sie die Kaffeemaschine nach dem Frühstück bitte aus.',
        'Viel Spaß in Berlin!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('du-imperatives – 60 seconds.', 'du emirleri – 60 saniye.', 'du-Imperative – 60 Sekunden.'),
      seconds: 60,
      pool: IMPERATIVES.map(([inf]) => `imp-${inf}`),
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Imperative: Klick! (du) · Klickt! (ihr) · Klicken Sie! (Sie)', 'Emir: Klick! (du) · Klickt! (ihr) · Klicken Sie! (Sie)', 'Imperativ'),
      l('Lies! Nimm! Gib! · Fahr! · Sei!', 'Lies! Nimm! Gib! · Fahr! · Sei!', 'Besonderheiten'),
      l('Separable: Lade … herunter! Gib … ein!', 'Ayrılabilen: Lade … herunter! Gib … ein!', 'trennbar'),
      l('Tech: herunterladen, speichern, WLAN, Akku, Passwort', 'Teknoloji: herunterladen, speichern, WLAN, Akku, Passwort', 'Technik'),
    ],
    mistakes: [
      { wrong: 'Gibst mir das Handy!', right: 'Gib mir das Handy!', note: l('No -st.', '-st yok.', 'ohne -st.') },
      { wrong: 'Lese den Text!', right: 'Lies den Text!', note: l('e → ie stays.', 'e → ie korunur.', 'Lies!') },
      { wrong: 'Fähr langsam!', right: 'Fahr langsam!', note: l('No umlaut.', 'Umlaut yok.', 'ohne Umlaut.') },
      { wrong: 'Sie klicken hier!', right: 'Klicken Sie hier!', note: l('Verb first.', 'Önce fiil.', 'Verb zuerst.') },
    ],
  },
}
