import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'schnell – schneller – am schnellsten', emoji: '🐆', translation: l('fast – faster – fastest', 'hızlı – daha hızlı – en hızlı', 'schnell'), example: 'Der Zug ist schneller als der Bus.' },
  { word: 'billig – billiger – am billigsten', emoji: '🏷️', translation: l('cheap – cheaper – cheapest', 'ucuz – daha ucuz – en ucuz', 'billig'), example: 'Das Fahrrad ist am billigsten.' },
  { word: 'teuer – teurer – am teuersten', emoji: '💎', translation: l('expensive – more – most', 'pahalı – daha pahalı – en pahalı', 'teuer'), example: 'Das Taxi ist teurer als die U-Bahn.' },
  { word: 'groß – größer – am größten', emoji: '🐘', translation: l('big – bigger – biggest', 'büyük – daha büyük – en büyük', 'groß'), example: 'Berlin ist größer als München.' },
  { word: 'alt – älter – am ältesten', emoji: '👴', translation: l('old – older – oldest', 'yaşlı – daha yaşlı – en yaşlı', 'alt'), example: 'Mein Bruder ist älter als ich.' },
  { word: 'jung – jünger – am jüngsten', emoji: '👶', translation: l('young – younger – youngest', 'genç – daha genç – en genç', 'jung'), example: 'Lena ist am jüngsten.' },
  { word: 'warm – wärmer – am wärmsten', emoji: '🌡️', translation: l('warm – warmer – warmest', 'sıcak – daha sıcak – en sıcak', 'warm'), example: 'Im Juli ist es am wärmsten.' },
  { word: 'gut – besser – am besten', emoji: '🏆', translation: l('good – better – best', 'iyi – daha iyi – en iyi', 'gut'), example: 'Dein Deutsch ist besser als meins.' },
  { word: 'gern – lieber – am liebsten', emoji: '❤️', translation: l('like – prefer – like most', 'severek – daha çok – en çok', 'gern'), example: 'Ich trinke lieber Tee als Kaffee.' },
  { word: 'viel – mehr – am meisten', emoji: '📦', translation: l('much – more – most', 'çok – daha çok – en çok', 'viel'), example: 'Wer arbeitet am meisten?' },
  { word: 'so … wie', emoji: '🟰', translation: l('as … as', '… kadar …', 'gleich'), example: 'Tom ist so groß wie sein Vater.' },
  { word: '… als', emoji: '⚖️', translation: l('… than', '…-den daha', 'Vergleich'), example: 'Der Tee ist heißer als der Kaffee.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Zug', gender: 'm', plural: 'die Züge', translation: l('train', 'tren', 'Zug') },
  { word: 'Bus', gender: 'm', plural: 'die Busse', translation: l('bus', 'otobüs', 'Bus') },
  { word: 'Stadt', gender: 'f', plural: 'die Städte', translation: l('city', 'şehir', 'Stadt') },
  { word: 'Dorf', gender: 'n', plural: 'die Dörfer', translation: l('village', 'köy', 'Dorf') },
  { word: 'Wetter', gender: 'n', translation: l('weather', 'hava', 'Wetter') },
  { word: 'Miete', gender: 'f', plural: 'die Mieten', translation: l('rent', 'kira', 'Miete') },
  { word: 'Fahrrad', gender: 'n', plural: 'die Fahrräder', translation: l('bicycle', 'bisiklet', 'Fahrrad') },
  { word: 'laut', translation: l('loud, noisy', 'gürültülü', 'laut') },
  { word: 'ruhig', translation: l('quiet', 'sakin', 'ruhig') },
]

/** [adjective, comparative, superlative (am …)] */
const FORMS: [string, string, string][] = [
  ['klein', 'kleiner', 'am kleinsten'],
  ['schnell', 'schneller', 'am schnellsten'],
  ['billig', 'billiger', 'am billigsten'],
  ['alt', 'älter', 'am ältesten'],
  ['groß', 'größer', 'am größten'],
  ['jung', 'jünger', 'am jüngsten'],
  ['teuer', 'teurer', 'am teuersten'],
  ['gut', 'besser', 'am besten'],
  ['gern', 'lieber', 'am liebsten'],
  ['viel', 'mehr', 'am meisten'],
]

const WRONG_COMP: Record<string, [string, string]> = {
  klein: ['kleinerer', 'mehr klein'],
  schnell: ['schnellerer', 'mehr schnell'],
  billig: ['billigerer', 'mehr billig'],
  alt: ['alter', 'mehr alt'],
  groß: ['großer', 'größerer'],
  jung: ['junger', 'mehr jung'],
  teuer: ['teuerer', 'mehr teuer'],
  gut: ['guter', 'mehr gut'],
  gern: ['gerner', 'mehr gern'],
  viel: ['vieler', 'mehrer'],
}

function comparativeDrills(): Exercise[] {
  return FORMS.map(([adj, comp], i) => {
    const options = [comp, ...WRONG_COMP[adj]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const irregular = ['gut', 'gern', 'viel'].includes(adj)
    const umlaut = comp.includes('ä') || comp.includes('ö') || comp.includes('ü')
    return {
      id: `komp-${adj}`,
      type: 'multiple_choice' as const,
      topic: 'komparativ',
      concept: irregular ? 'comp-irregular' : umlaut ? 'comp-umlaut' : 'comp-regular',
      skill: 'grammar' as const,
      difficulty: (irregular || umlaut ? 2 : 1) as 1 | 2,
      prompt: `${adj} → ___ als`,
      options: ordered,
      answer: ordered.indexOf(comp),
      explanation: irregular
        ? l(`${adj} is irregular: ${comp}.`, `${adj} düzensizdir: ${comp}.`, `${adj} → ${comp} (unregelmäßig).`)
        : umlaut
          ? l(`Short adjective with a/o/u gets an umlaut: ${adj} → ${comp}.`, `a/o/u içeren kısa sıfatlar umlaut alır: ${adj} → ${comp}.`, `${adj} → ${comp} (Umlaut).`)
          : l(`Add -er: ${adj} → ${comp}. Never „mehr ${adj}“.`, `-er ekle: ${adj} → ${comp}. Asla „mehr ${adj}“ değil.`, `${adj} → ${comp}.`),
      examples: [`… **${comp}** als …`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-forms',
    type: 'matching',
    topic: 'komparativ',
    concept: 'comp-irregular',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the base form and the comparative.', 'Yalın hali ve karşılaştırma hâlini eşleştir.', 'Ordne Grundform und Komparativ zu.'),
    pairs: [
      { left: 'gut', right: 'besser' },
      { left: 'gern', right: 'lieber' },
      { left: 'viel', right: 'mehr' },
      { left: 'hoch', right: 'höher' },
      { left: 'nah', right: 'näher' },
    ],
    explanation: l('Irregular: gut → besser, gern → lieber, viel → mehr, hoch → höher, nah → näher.', 'Düzensiz: gut → besser, gern → lieber, viel → mehr, hoch → höher, nah → näher.', 'Unregelmäßige Formen.'),
    practice: ['komp-gut', 'komp-gern'],
  },
  {
    id: 'sort-umlaut',
    type: 'categorize',
    topic: 'komparativ',
    concept: 'comp-umlaut',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Comparative with or without umlaut?', 'Umlaut’lu mu umlaut’suz mu?', 'Komparativ mit oder ohne Umlaut?'),
    categories: ['mit Umlaut', 'ohne Umlaut'],
    items: [
      { text: 'alt', category: 0 },
      { text: 'schnell', category: 1 },
      { text: 'warm', category: 0 },
      { text: 'billig', category: 1 },
      { text: 'jung', category: 0 },
      { text: 'schön', category: 1 },
    ],
    explanation: l(
      'Many short adjectives with a/o/u get an umlaut: älter, wärmer, jünger. schnell → schneller, billig → billiger, schön → schöner (already ö).',
      'a/o/u içeren birçok kısa sıfat umlaut alır: älter, wärmer, jünger. schnell → schneller, billig → billiger, schön → schöner (zaten ö).',
      'älter, wärmer, jünger – aber schneller, billiger.'
    ),
  },
  {
    id: 'mc-als-wie',
    type: 'multiple_choice',
    topic: 'als-wie',
    concept: 'als-or-wie',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Mein Bruder ist so groß ___ mein Vater.',
    options: ['wie', 'als', 'wenn'],
    answer: 0,
    explanation: l('Equal → so … wie. Different → comparative + als.', 'Eşit → so … wie. Farklı → karşılaştırma + als.', 'so groß wie / größer als.'),
    examples: ['Mein Bruder ist **so** groß **wie** mein Vater.', 'Mein Bruder ist größ**er als** ich.'],
    practice: ['mc-als'],
  },
  {
    id: 'mc-als',
    type: 'multiple_choice',
    topic: 'als-wie',
    concept: 'als-or-wie',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Der Zug ist schneller ___ das Auto.',
    options: ['als', 'wie', 'so'],
    answer: 0,
    explanation: l('Comparative (schneller) + als.', 'Karşılaştırma (schneller) + als.', 'schneller als.'),
    examples: ['Der Zug ist schneller **als** das Auto.'],
  },
  {
    id: 'tf-mehr',
    type: 'true_false',
    topic: 'komparativ',
    concept: 'comp-regular',
    skill: 'grammar',
    difficulty: 1,
    statement: '„Das ist mehr interessant“ ist richtig.',
    answer: false,
    explanation: l('German never uses „mehr“ + adjective. Even long adjectives add -er: interessanter.', 'Almancada asla „mehr“ + sıfat kullanılmaz. Uzun sıfatlar bile -er alır: interessanter.', 'interessanter.'),
    examples: ['Das ist **interessanter**.'],
  },
  {
    id: 'image-groesste',
    type: 'image_choice',
    topic: 'superlativ',
    concept: 'sup-am',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Welches Tier ist am größten?',
    options: [
      { emoji: '🐁', label: 'die Maus' },
      { emoji: '🐈', label: 'die Katze' },
      { emoji: '🐘', label: 'der Elefant' },
      { emoji: '🐕', label: 'der Hund' },
    ],
    answer: 2,
    explanation: l('Der Elefant ist am größten.', 'Fil en büyüğü: Der Elefant ist am größten.', 'Der Elefant ist am größten.'),
  },
  {
    id: 'ordering-preis',
    type: 'ordering',
    topic: 'superlativ',
    concept: 'compare-three',
    skill: 'vocabulary',
    difficulty: 2,
    visual: ['🚲 0 €', '🚌 3 €', '🚕 25 €'],
    promptL10n: l('From cheapest to most expensive.', 'En ucuzdan en pahalıya.', 'Vom billigsten zum teuersten.'),
    items: ['das Taxi', 'das Fahrrad', 'der Bus'],
    answer: ['das Fahrrad', 'der Bus', 'das Taxi'],
    explanation: l('Das Fahrrad ist am billigsten, der Bus ist teurer, das Taxi ist am teuersten.', 'Bisiklet en ucuz, otobüs daha pahalı, taksi en pahalı.', 'Fahrrad < Bus < Taxi.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-aelter',
    type: 'fill_blank',
    topic: 'komparativ',
    concept: 'comp-umlaut',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Meine Schwester ist drei Jahre ___ als ich.',
    accepted: ['älter'],
    base: 'alt',
    explanation: l('alt → älter (umlaut).', 'alt → älter (umlaut).', 'älter.'),
    examples: ['Meine Schwester ist drei Jahre **älter** als ich.'],
  },
  {
    id: 'fill-am-liebsten',
    type: 'fill_blank',
    topic: 'superlativ',
    concept: 'sup-irregular',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich esse gern Pizza, aber am ___ esse ich Döner.',
    accepted: ['liebsten'],
    base: 'gern',
    explanation: l('gern – lieber – am liebsten.', 'gern – lieber – am liebsten.', 'am liebsten.'),
    examples: ['Am **liebsten** esse ich Döner.'],
  },
  {
    id: 'fill-besten',
    type: 'fill_blank',
    topic: 'superlativ',
    concept: 'sup-irregular',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wer spricht in der Klasse am ___ Deutsch?',
    accepted: ['besten'],
    base: 'gut',
    explanation: l('gut – besser – am besten.', 'gut – besser – am besten.', 'am besten.'),
    examples: ['Wer spricht am **besten** Deutsch?'],
  },
  {
    id: 'build-lieber',
    type: 'sentence_builder',
    topic: 'komparativ',
    concept: 'comp-irregular',
    skill: 'grammar',
    difficulty: 2,
    chips: ['als', 'Ich', 'Tee', 'Kaffee', 'trinke', 'lieber'],
    answers: [['Ich', 'trinke', 'lieber', 'Tee', 'als', 'Kaffee']],
    translation: l('I prefer tea to coffee.', 'Çayı kahveye tercih ederim.', 'Ich trinke lieber Tee als Kaffee.'),
    explanation: l('lieber (prefer) + als.', 'lieber (tercih) + als.', 'lieber … als.'),
    examples: ['Ich trinke **lieber** Tee **als** Kaffee.'],
  },
  {
    id: 'build-am-schnellsten',
    type: 'sentence_builder',
    topic: 'superlativ',
    concept: 'sup-am',
    skill: 'grammar',
    difficulty: 2,
    chips: ['am schnellsten', 'Mit dem Zug', 'man', 'ist', 'in Hamburg'],
    answers: [['Mit dem Zug', 'ist', 'man', 'am schnellsten', 'in Hamburg']],
    translation: l('By train you get to Hamburg fastest.', 'Hamburg’a en hızlı trenle gidilir.', 'Mit dem Zug ist man am schnellsten in Hamburg.'),
    explanation: l('Superlative after a verb: am + -sten.', 'Fiilden sonra en üstünlük: am + -sten.', 'am schnellsten.'),
    examples: ['Mit dem Zug ist man **am schnellsten** in Hamburg.'],
  },
  {
    id: 'build-so-wie',
    type: 'sentence_builder',
    topic: 'als-wie',
    concept: 'so-wie',
    skill: 'grammar',
    difficulty: 2,
    chips: ['wie', 'so', 'Hier', 'teuer', 'ist es nicht', 'in München'],
    answers: [['Hier', 'ist es nicht', 'so', 'teuer', 'wie', 'in München']],
    translation: l('Here it isn’t as expensive as in Munich.', 'Burası Münih kadar pahalı değil.', 'Hier ist es nicht so teuer wie in München.'),
    explanation: l('nicht so … wie = not as … as.', 'nicht so … wie = … kadar … değil.', 'nicht so teuer wie.'),
    examples: ['Hier ist es **nicht so** teuer **wie** in München.'],
  },
  {
    id: 'fix-mehr-gut',
    type: 'error_correction',
    topic: 'komparativ',
    concept: 'comp-irregular',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Dein Deutsch ist mehr gut als meins.',
    accepted: ['Dein Deutsch ist besser als meins.'],
    explanation: l('gut → besser.', 'gut → besser.', 'besser.'),
    examples: ['Dein Deutsch ist **besser** als meins.'],
  },
  {
    id: 'fix-wie',
    type: 'error_correction',
    topic: 'als-wie',
    concept: 'als-or-wie',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Berlin ist größer wie Hamburg.',
    accepted: ['Berlin ist größer als Hamburg.'],
    explanation: l('Comparative + als (wie only with so … wie).', 'Karşılaştırma + als (wie yalnızca so … wie ile).', 'größer als.'),
    examples: ['Berlin ist größer **als** Hamburg.'],
  },
  {
    id: 'fix-am-groesste',
    type: 'error_correction',
    topic: 'superlativ',
    concept: 'sup-am',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Im August ist es am wärmste.',
    accepted: ['Im August ist es am wärmsten.'],
    explanation: l('am … -sten (always with -n).', 'am … -sten (her zaman -n ile).', 'am wärmsten.'),
    examples: ['Im August ist es **am wärmsten**.'],
  },
  {
    id: 'tr-billiger',
    type: 'translation',
    topic: 'komparativ',
    concept: 'comp-regular',
    skill: 'writing',
    difficulty: 2,
    source: l('The bus is cheaper than the taxi.', 'Otobüs taksiden daha ucuz.', 'The bus is cheaper than the taxi.'),
    accepted: ['Der Bus ist billiger als das Taxi.', 'Der Bus ist günstiger als das Taxi.'],
    explanation: l('billiger als.', 'billiger als.', 'billiger als.'),
    examples: ['Der Bus ist **billiger als** das Taxi.'],
  },
  {
    id: 'tr-meisten',
    type: 'translation',
    topic: 'superlativ',
    concept: 'sup-irregular',
    skill: 'writing',
    difficulty: 2,
    source: l('Who works the most?', 'En çok kim çalışıyor?', 'Who works the most?'),
    accepted: ['Wer arbeitet am meisten?', 'Wer arbeitet am meisten'],
    explanation: l('viel – mehr – am meisten.', 'viel – mehr – am meisten.', 'am meisten.'),
    examples: ['Wer arbeitet **am meisten**?'],
  },
  {
    id: 'select-correct',
    type: 'multiple_select',
    topic: 'superlativ',
    concept: 'sup-forms',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which superlatives are correct? Select all.', 'Hangi en üstünlük biçimleri doğru? Hepsini seç.', 'Welche Superlative sind richtig? Wähle alle.'),
    options: ['am ältesten', 'am besten', 'am gutesten', 'am teuersten', 'am meisten', 'am vielsten'],
    answers: [0, 1, 3, 4],
    explanation: l('After -t, -s, -ß, -z an extra e: am ältesten, am teuersten. Irregular: am besten, am meisten.', '-t, -s, -ß, -z’den sonra ek bir e: am ältesten, am teuersten. Düzensiz: am besten, am meisten.', 'am ältesten, am besten, am meisten.'),
  },
  {
    id: 'dialog-wohnung',
    type: 'dialogue',
    topic: 'komparativ',
    concept: 'compare-two',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Welche Wohnung nimmst du – die in der Stadt oder die auf dem Land?' }],
    options: ['Die auf dem Land. Sie ist größer und ruhiger.', 'Die auf dem Land. Sie ist mehr groß und mehr ruhig.', 'Die auf dem Land. Sie ist am größer.'],
    answer: 0,
    explanation: l('größer, ruhiger – comparative with -er.', 'größer, ruhiger – -er ile karşılaştırma.', 'größer und ruhiger.'),
  },
  {
    id: 'dialog-lieblings',
    type: 'dialogue',
    topic: 'superlativ',
    concept: 'sup-irregular',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Kollegin', de: 'Was machst du am Wochenende am liebsten?' }],
    options: ['Am liebsten wandere ich in den Bergen.', 'Am liebsten ich wandere in den Bergen.', 'Am gernsten wandere ich in den Bergen.'],
    answer: 0,
    explanation: l('Am liebsten (1) + verb (2).', 'Am liebsten (1) + fiil (2).', 'Am liebsten wandere ich …'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-groesser',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-staedte',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Welche Stadt ist größer?',
    options: ['Köln', 'Freiburg', 'Beide sind gleich groß.'],
    answer: 0,
    explanation: l('„Köln ist viel größer als Freiburg.“', '„Köln ist viel größer als Freiburg.“', '„Köln ist viel größer“'),
  },
  {
    id: 'read-miete',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-staedte',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie sind die Mieten?',
    options: ['In beiden Städten ungefähr gleich hoch.', 'In Köln viel höher.', 'In Freiburg viel billiger.'],
    answer: 0,
    explanation: l('„Die Mieten sind in Freiburg fast so hoch wie in Köln.“', '„Die Mieten sind in Freiburg fast so hoch wie in Köln.“', '„fast so hoch wie“'),
  },
  {
    id: 'read-wetter',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-staedte',
    skill: 'reading',
    difficulty: 2,
    statement: 'In Freiburg ist das Wetter wärmer als in Köln.',
    answer: true,
    explanation: l('„Freiburg ist die wärmste Stadt Deutschlands.“', '„Freiburg ist die wärmste Stadt Deutschlands.“', '„die wärmste Stadt“'),
  },
  {
    id: 'read-entscheidung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-staedte',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wo möchte Emre am liebsten wohnen?',
    options: ['In Freiburg.', 'In Köln.', 'In Berlin.'],
    answer: 0,
    explanation: l('„Am liebsten möchte ich in Freiburg wohnen.“', '„Am liebsten möchte ich in Freiburg wohnen.“', '„in Freiburg“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-wer',
    type: 'listening_choice',
    topic: 'komparativ',
    concept: 'compare-two',
    skill: 'listening',
    difficulty: 1,
    audio: 'Anna ist älter als Ben, aber Ben ist größer als Anna.',
    question: l('Who is older?', 'Kim daha yaşlı?', 'Wer ist älter?'),
    options: ['Anna', 'Ben', 'beide gleich'],
    answer: 0,
    explanation: l('„Anna ist älter als Ben“', '„Anna ist älter als Ben“', '„Anna ist älter“'),
  },
  {
    id: 'listen-transport',
    type: 'listening_choice',
    topic: 'superlativ',
    concept: 'sup-am',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das Auto ist schnell, aber mit dem Fahrrad bin ich in der Stadt am schnellsten.',
    question: l('What is fastest in the city?', 'Şehirde en hızlı ne?', 'Was ist in der Stadt am schnellsten?'),
    options: ['🚲', '🚗', '🚌'],
    answer: 0,
    explanation: l('„mit dem Fahrrad … am schnellsten“', '„mit dem Fahrrad … am schnellsten“', '„Fahrrad“'),
  },
  {
    id: 'listen-gleich',
    type: 'listening_choice',
    topic: 'als-wie',
    concept: 'so-wie',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die blaue Jacke ist so teuer wie die rote.',
    question: l('Which jacket is more expensive?', 'Hangi ceket daha pahalı?', 'Welche Jacke ist teurer?'),
    options: ['beide kosten gleich viel', 'die blaue', 'die rote'],
    answer: 0,
    explanation: l('so … wie = the same.', 'so … wie = aynı.', 'gleich teuer.'),
  },
  {
    id: 'listen-lieber',
    type: 'listening_choice',
    topic: 'komparativ',
    concept: 'comp-irregular',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich sehe gern Filme, aber ich lese lieber Bücher.',
    question: l('What does the person prefer?', 'Kişi neyi tercih ediyor?', 'Was macht die Person lieber?'),
    options: ['📚', '🎬', '⚽'],
    answer: 0,
    explanation: l('„lieber Bücher“', '„lieber Bücher“', '„lese lieber Bücher“'),
  },

  ...comparativeDrills(),
]

export const UNIT_A2_07_VERGLEICHE: CourseUnit = {
  level: 'A2',
  number: 7,
  slug: 'vergleiche',
  titleDe: 'Größer, schneller, am besten',
  title: l('Bigger, faster, the best', 'Daha büyük, daha hızlı, en iyi', 'Größer, schneller, am besten'),
  goal: l(
    'By the end of this unit you can compare cities, prices and people: größer als, so groß wie, am größten – and say what you like most: am liebsten.',
    'Bu ünitenin sonunda şehirleri, fiyatları ve insanları karşılaştırabilirsin: größer als, so groß wie, am größten – ve en çok neyi sevdiğini söyleyebilirsin: am liebsten.',
    'Am Ende dieser Einheit vergleichst du Städte, Preise und Personen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'komparativ', label: l('Comparative (-er)', 'Karşılaştırma (-er)', 'Komparativ') },
    { key: 'superlativ', label: l('Superlative (am -sten)', 'En üstünlük (am -sten)', 'Superlativ') },
    { key: 'als-wie', label: l('als or wie?', 'als mı wie mi?', 'als oder wie?') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Three forms of each adjective – and the little words als and wie.', 'Her sıfatın üç biçimi – ve als ile wie kelimecikleri.', 'Drei Formen pro Adjektiv.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Comparative: -er + als', 'Karşılaştırma: -er + als', 'Komparativ: -er + als'),
          body: l(
            'Add -er to the adjective – even long ones: schnell → schneller, interessant → interessanter. Never use „mehr“ + adjective. Many short adjectives with a, o, u get an umlaut: alt → älter, groß → größer, jung → jünger.',
            'Sıfata -er ekle – uzun olanlara bile: schnell → schneller, interessant → interessanter. Asla „mehr“ + sıfat kullanma. a, o, u içeren birçok kısa sıfat umlaut alır: alt → älter, groß → größer, jung → jünger.',
            '-er; oft Umlaut: älter, größer, jünger.'
          ),
          table: {
            head: [l('Base', 'Yalın', 'Grundform'), l('Comparative', 'Karşılaştırma', 'Komparativ'), l('Superlative', 'En üstünlük', 'Superlativ')],
            rows: [
              ['schnell', 'schneller', 'am schnellsten'],
              ['alt', 'älter', 'am ältesten'],
              ['teuer', 'teurer', 'am teuersten'],
              ['gut', 'besser', 'am besten'],
              ['gern', 'lieber', 'am liebsten'],
              ['viel', 'mehr', 'am meisten'],
            ],
          },
        },
        {
          title: l('Superlative: am …-sten', 'En üstünlük: am …-sten', 'Superlativ: am …-sten'),
          body: l(
            'After a verb: am + adjective + -sten. After -t, -d, -s, -ß, -z add an e: am ältesten, am heißesten. Before a noun it is an adjective with an ending: die wärmste Stadt, der beste Freund.',
            'Fiilden sonra: am + sıfat + -sten. -t, -d, -s, -ß, -z’den sonra e ekle: am ältesten, am heißesten. İsimden önce ekli bir sıfattır: die wärmste Stadt, der beste Freund.',
            'am …-sten; vor Nomen: der beste Freund.'
          ),
        },
        {
          title: l('als or wie?', 'als mı wie mi?', 'als oder wie?'),
          body: l(
            'Different → comparative + als: größer als. Equal → so + adjective + wie: so groß wie. Not equal → nicht so … wie.',
            'Farklı → karşılaştırma + als: größer als. Eşit → so + sıfat + wie: so groß wie. Eşit değil → nicht so … wie.',
            'größer als · so groß wie.'
          ),
          examples: [
            { de: 'Tom ist **größer als** Lisa.', translation: l('Tom is taller than Lisa.', 'Tom Lisa’dan daha uzun.', '') },
            { de: 'Tom ist **so groß wie** sein Vater.', translation: l('Tom is as tall as his father.', 'Tom babası kadar uzun.', '') },
          ],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two friends compare ways to get to work.', 'İki arkadaş işe gitme yollarını karşılaştırıyor.', 'Zwei Freunde vergleichen den Weg zur Arbeit.'),
      dialogue: [
        { speaker: 'Max', de: 'Fährst du immer mit dem Auto zur Arbeit?', translation: l('Do you always drive to work?', 'İşe hep arabayla mı gidiyorsun?', '') },
        { speaker: 'Elif', de: 'Nein, mit dem Fahrrad bin ich **schneller**. Es ist auch **billiger als** das Auto!', translation: l('No, by bike I’m faster. It’s also cheaper than the car!', 'Hayır, bisikletle daha hızlıyım. Arabadan daha ucuz da!', '') },
        { speaker: 'Max', de: 'Und im Winter? Da ist der Bus doch **bequemer**.', translation: l('And in winter? The bus is more comfortable then.', 'Ya kışın? O zaman otobüs daha rahat.', '') },
        { speaker: 'Elif', de: 'Ja, aber der Bus ist **nicht so pünktlich wie** mein Fahrrad.', translation: l('Yes, but the bus isn’t as punctual as my bike.', 'Evet ama otobüs bisikletim kadar dakik değil.', '') },
        { speaker: 'Max', de: 'Und was magst du **am liebsten**?', translation: l('And what do you like best?', 'Peki en çok neyi seviyorsun?', '') },
        { speaker: 'Elif', de: '**Am liebsten** gehe ich zu Fuß – das ist **am gesündesten**!', translation: l('Best of all I like walking – that’s the healthiest!', 'En çok yürümeyi seviyorum – en sağlıklısı bu!', '') },
      ],
      examples: [
        { de: 'Der Zug ist **schneller als** der Bus.', translation: l('The train is faster than the bus.', 'Tren otobüsten daha hızlı.', '') },
        { de: 'Mein Bruder ist **älter als** ich.', translation: l('My brother is older than me.', 'Ağabeyim benden büyük.', '') },
        { de: 'Hamburg ist **nicht so groß wie** Berlin.', translation: l('Hamburg isn’t as big as Berlin.', 'Hamburg Berlin kadar büyük değil.', '') },
        { de: 'Ich trinke **lieber** Tee **als** Kaffee.', translation: l('I prefer tea to coffee.', 'Çayı kahveye tercih ederim.', '') },
        { de: 'Im Juli ist es **am wärmsten**.', translation: l('It’s warmest in July.', 'En sıcak temmuzda.', '') },
        { de: 'Sie spricht **am besten** Deutsch.', translation: l('She speaks German best.', 'En iyi o Almanca konuşuyor.', '') },
        { de: 'Das ist **der beste** Döner der Stadt!', translation: l('That’s the best kebab in town!', 'Şehrin en iyi döneri bu!', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Comparative and superlative forms.', 'Karşılaştırma ve en üstünlük biçimleri.', 'Komparativ und Superlativ.'),
      exercises: ['match-forms', 'sort-umlaut', 'komp-klein', 'komp-alt', 'komp-gut', 'mc-als-wie', 'mc-als', 'tf-mehr', 'image-groesste', 'ordering-preis'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Compare cities, prices and people.', 'Şehirleri, fiyatları ve insanları karşılaştır.', 'Vergleiche Städte, Preise und Personen.'),
      exercises: [
        'fill-aelter',
        'fill-am-liebsten',
        'fill-besten',
        'build-lieber',
        'build-am-schnellsten',
        'build-so-wie',
        'fix-mehr-gut',
        'fix-wie',
        'fix-am-groesste',
        'tr-billiger',
        'tr-meisten',
        'select-correct',
        'dialog-wohnung',
        'dialog-lieblings',
        'komp-teuer',
        'komp-gern',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Emre has two job offers and compares two cities.', 'Emre’nin iki iş teklifi var ve iki şehri karşılaştırıyor.', 'Emre vergleicht zwei Städte.'),
      passage: [
        'Ich habe zwei Jobangebote: eins in Köln und eins in Freiburg. Was ist **besser**?',
        'Köln ist viel **größer als** Freiburg und hat mehr Kultur. Aber Köln ist auch **lauter**.',
        'Die Mieten sind in Freiburg fast **so hoch wie** in Köln. Dafür ist Freiburg **die wärmste** Stadt Deutschlands, und der Schwarzwald ist ganz nah!',
        'Ich wandere sehr gern. Deshalb möchte ich **am liebsten** in Freiburg wohnen.',
      ],
      glossary: [
        { de: 'das Jobangebot', note: l('job offer', 'iş teklifi', 'Angebot für eine Stelle') },
        { de: 'dafür', note: l('on the other hand, in return', 'buna karşılık', 'aber positiv') },
        { de: 'der Schwarzwald', note: l('the Black Forest', 'Kara Orman', 'Gebirge in Süddeutschland') },
        { de: 'wandern', note: l('to hike', 'doğa yürüyüşü yapmak', 'zu Fuß in der Natur gehen') },
      ],
      exercises: ['read-groesser', 'read-miete', 'read-wetter', 'read-entscheidung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Who or what is more … or the most …?', 'Kim ya da ne daha … ya da en …?', 'Wer oder was ist mehr … oder am …?'),
      exercises: ['listen-wer', 'listen-transport', 'listen-gleich', 'listen-lieber'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Compare your home town with the city where you live now (or another city).', 'Memleketini şimdi yaşadığın şehirle (ya da başka bir şehirle) karşılaştır.', 'Vergleiche deine Heimatstadt mit deiner jetzigen Stadt.'),
      points: [
        l('Size and people: „… ist größer/kleiner als …“', 'Büyüklük ve insanlar: „… ist größer/kleiner als …“', 'Größe'),
        l('Weather and prices: „Das Wetter ist wärmer, die Mieten sind …“', 'Hava ve fiyatlar: „Das Wetter ist wärmer, die Mieten sind …“', 'Wetter und Preise'),
        l('Something equal: „… ist so … wie …“', 'Eşit bir şey: „… ist so … wie …“', 'so … wie'),
        l('Your favourite: „Am liebsten …“', 'Favorin: „Am liebsten …“', 'Am liebsten …'),
      ],
      model: [
        'Ich komme aus Izmir und wohne jetzt in Dortmund.',
        'Izmir ist größer als Dortmund, und das Wetter ist viel wärmer.',
        'Die Mieten in Dortmund sind nicht so hoch wie in Izmir.',
        'Aber am liebsten bin ich am Meer – deshalb vermisse ich Izmir.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short text (at least 5 sentences): compare two things – two cities, two jobs, two means of transport …',
        'Kısa bir metin yaz (en az 5 cümle): iki şeyi karşılaştır – iki şehir, iki iş, iki ulaşım aracı …',
        'Schreib einen Text (mindestens 5 Sätze) und vergleiche zwei Dinge.'
      ),
      minSentences: 5,
      checks: [
        { label: l('Comparative + als', 'Karşılaştırma + als', 'Komparativ + als'), pattern: '\\p{Ll}+er als\\b|\\b(besser|lieber|mehr) als\\b' },
        { label: l('so … wie', 'so … wie', 'so … wie'), pattern: '\\bso \\p{Ll}+ wie\\b' },
        { label: l('Superlative (am …sten)', 'En üstünlük (am …sten)', 'Superlativ'), pattern: '\\b[Aa]m \\p{Ll}+sten\\b' },
      ],
      model: [
        'Ich fahre mit dem Zug oder mit dem Auto zur Arbeit.',
        'Der Zug ist billiger als das Auto.',
        'Mit dem Auto bin ich aber schneller.',
        'Der Zug ist leider nicht so pünktlich wie mein Auto.',
        'Am liebsten fahre ich trotzdem mit dem Zug, denn da kann ich lesen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Comparatives – 60 seconds.', 'Karşılaştırma biçimleri – 60 saniye.', 'Komparative – 60 Sekunden.'),
      seconds: 60,
      pool: [...FORMS.map(([adj]) => `komp-${adj}`), 'mc-als', 'mc-als-wie'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Comparative: -er (+ umlaut): schneller, älter, größer', 'Karşılaştırma: -er (+ umlaut): schneller, älter, größer', 'Komparativ: -er'),
      l('Superlative: am …-sten: am schnellsten, am ältesten', 'En üstünlük: am …-sten: am schnellsten, am ältesten', 'Superlativ: am …-sten'),
      l('gut – besser – am besten · gern – lieber – am liebsten · viel – mehr – am meisten', 'gut – besser – am besten · gern – lieber – am liebsten · viel – mehr – am meisten', 'unregelmäßig'),
      l('größer als · so groß wie', 'größer als · so groß wie', 'als / wie'),
    ],
    mistakes: [
      { wrong: 'Das ist mehr interessant.', right: 'Das ist interessanter.', note: l('Never mehr + adjective.', 'Asla mehr + sıfat.', '-er.') },
      { wrong: 'Er ist größer wie ich.', right: 'Er ist größer als ich.', note: l('Comparative + als.', 'Karşılaştırma + als.', 'als.') },
      { wrong: 'Das ist mehr gut.', right: 'Das ist besser.', note: l('gut → besser.', 'gut → besser.', 'besser.') },
      { wrong: 'am schönste', right: 'am schönsten', note: l('am … -sten.', 'am … -sten.', '-sten.') },
    ],
  },
}
