import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'der Freund / die Freundin', emoji: '🧑‍🤝‍🧑', translation: l('friend; boyfriend / girlfriend', 'arkadaş; erkek / kız arkadaş', 'Freund'), example: 'Ich gehe mit meiner Freundin ins Kino.' },
  { word: 'der Nachbar / die Nachbarin', emoji: '🏘️', translation: l('neighbour', 'komşu', 'wohnt nebenan'), example: 'Unsere Nachbarin ist sehr nett.' },
  { word: 'der Bekannte', emoji: '👋', translation: l('acquaintance', 'tanıdık', 'man kennt sich ein bisschen'), example: 'Er ist kein Freund, nur ein Bekannter.' },
  { word: 'sich verstehen', emoji: '🤝', translation: l('to get on (with each other)', 'anlaşmak', 'gut miteinander sein'), example: 'Wir verstehen uns sehr gut.' },
  { word: 'sich streiten', emoji: '😤', translation: l('to argue', 'tartışmak, kavga etmek', 'Streit haben'), example: 'Meine Geschwister streiten sich oft.' },
  { word: 'sich entschuldigen', emoji: '🙇', translation: l('to apologise', 'özür dilemek', 'Entschuldigung sagen'), example: 'Ich möchte mich entschuldigen.' },
  { word: 'sich kennenlernen', emoji: '💞', translation: l('to get to know each other', 'tanışmak', 'zum ersten Mal treffen'), example: 'Wir haben uns im Deutschkurs kennengelernt.' },
  { word: 'zuverlässig', emoji: '🛡️', translation: l('reliable', 'güvenilir', 'man kann ihm vertrauen'), example: 'Mein bester Freund ist sehr zuverlässig.' },
  { word: 'hilfsbereit', emoji: '🤲', translation: l('helpful', 'yardımsever', 'hilft gern'), example: 'Die Nachbarn sind sehr hilfsbereit.' },
  { word: 'ehrlich', emoji: '💯', translation: l('honest', 'dürüst', 'sagt die Wahrheit'), example: 'Ich mag ehrliche Menschen.' },
  { word: 'mit meinem / meiner / meinen', emoji: '👨‍👩‍👧', translation: l('with my (Dativ)', 'benim … ile (Dativ)', 'Possessiv im Dativ'), example: 'Ich telefoniere oft mit meinen Eltern.' },
  { word: 'der Streit', emoji: '⚡', translation: l('argument, quarrel', 'kavga, tartışma', 'Konflikt'), example: 'Es gab Streit wegen der Musik.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Freund', gender: 'm', plural: 'die Freunde', translation: l('friend (m)', 'arkadaş (erkek)', 'Freund') },
  { word: 'Freundin', gender: 'f', plural: 'die Freundinnen', translation: l('friend (f)', 'arkadaş (kadın)', 'Freundin') },
  { word: 'Nachbar', gender: 'm', plural: 'die Nachbarn', translation: l('neighbour (m)', 'komşu (erkek)', 'Nachbar') },
  { word: 'Nachbarin', gender: 'f', plural: 'die Nachbarinnen', translation: l('neighbour (f)', 'komşu (kadın)', 'Nachbarin') },
  { word: 'Kind', gender: 'n', plural: 'die Kinder', translation: l('child', 'çocuk', 'Kind') },
  { word: 'Bruder', gender: 'm', plural: 'die Brüder', translation: l('brother', 'erkek kardeş', 'Bruder') },
  { word: 'Schwester', gender: 'f', plural: 'die Schwestern', translation: l('sister', 'kız kardeş', 'Schwester') },
  { word: 'Musik', gender: 'f', translation: l('music', 'müzik', 'Musik') },
]

type G = 'm' | 'f' | 'n' | 'pl'
/** [id, sentence with ___ (possessive in Dativ), possessive stem, gender] */
const POSS: [string, string, string, G][] = [
  ['bruder', 'Ich spiele oft Tennis mit ___ Bruder.', 'mein', 'm'],
  ['schwester', 'Am Wochenende fahre ich zu ___ Schwester.', 'mein', 'f'],
  ['kind', 'Sie spricht nur Türkisch mit ___ Kind.', 'ihr', 'n'],
  ['eltern', 'Wir wohnen noch bei ___ Eltern.', 'unser', 'pl'],
  ['freundin', 'Er geht mit ___ Freundin ins Konzert.', 'sein', 'f'],
  ['nachbar', 'Hast du schon mit ___ Nachbarn gesprochen? (m, Sg.)', 'dein', 'm'],
]

const END: Record<G, string> = { m: 'em', f: 'er', n: 'em', pl: 'en' }

function possDrills(): Exercise[] {
  return POSS.map(([id, sentence, stem, g], i) => {
    const form = (end: string) => (stem === 'unser' ? `unser${end}` : `${stem}${end}`)
    const right = form(END[g])
    const pool = [form('em'), form('er'), form('en'), form('e')].filter((o) => o !== right)
    const options = [right, pool[i % pool.length], pool[(i + 1) % pool.length]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const gl = g === 'm' ? 'maskulin' : g === 'f' ? 'feminin' : g === 'n' ? 'neutral' : 'Plural'
    return {
      id: `poss-${id}`,
      type: 'multiple_choice' as const,
      topic: 'possessiv-dativ',
      concept: `poss-dat-${g}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Dativ ${gl}: ${stem} + -${END[g]} = ${right} (like dem/der/den).`,
        `Dativ ${gl}: ${stem} + -${END[g]} = ${right} (dem/der/den gibi).`,
        `Dativ ${gl}: ${right}.`
      ),
      examples: [sentence.replace(/ \(.*\)$/, '').replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-endungen',
    type: 'matching',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-table',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Match article and possessive in the Dativ.', 'Dativ’de artikeli ve iyelik sözcüğünü eşleştir.', 'Ordne Artikel und Possessiv im Dativ zu.'),
    pairs: [
      { left: 'mit dem Bruder', right: 'mit meinem Bruder' },
      { left: 'mit der Schwester', right: 'mit meiner Schwester' },
      { left: 'mit dem Kind', right: 'mit meinem Kind' },
      { left: 'mit den Eltern', right: 'mit meinen Eltern' },
    ],
    explanation: l('The ending copies the article: dem → meinem, der → meiner, den → meinen.', 'Ek artikeli taklit eder: dem → meinem, der → meiner, den → meinen.', 'dem → -em, der → -er, den → -en.'),
    practice: ['poss-bruder', 'poss-schwester'],
  },
  {
    id: 'sort-eigenschaften',
    type: 'categorize',
    topic: 'beschreiben',
    concept: 'character',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Positive or negative quality?', 'Olumlu mu olumsuz mu bir özellik?', 'Positive oder negative Eigenschaft?'),
    categories: ['positiv', 'negativ'],
    items: [
      { text: 'zuverlässig', category: 0 },
      { text: 'unhöflich', category: 1 },
      { text: 'hilfsbereit', category: 0 },
      { text: 'egoistisch', category: 1 },
      { text: 'ehrlich', category: 0 },
      { text: 'unpünktlich', category: 1 },
    ],
    explanation: l('un- often makes the opposite: höflich → unhöflich, pünktlich → unpünktlich.', 'un- çoğu zaman zıt anlam yapar: höflich → unhöflich, pünktlich → unpünktlich.', 'un- = Gegenteil.'),
  },
  {
    id: 'mc-uns',
    type: 'multiple_choice',
    topic: 'reziprok',
    concept: 'sich-reciprocal',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Meine Schwester und ich verstehen ___ sehr gut.',
    options: ['uns', 'sich', 'euch'],
    answer: 0,
    explanation: l('meine Schwester und ich = wir → uns.', 'meine Schwester und ich = wir → uns.', 'wir → uns.'),
    examples: ['Wir verstehen **uns** sehr gut.'],
  },
  {
    id: 'tf-kennengelernt',
    type: 'true_false',
    topic: 'reziprok',
    concept: 'kennenlernen',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Wir haben uns im Urlaub kennengelernt.“ = We met (for the first time) on holiday.',
    answer: true,
    explanation: l('sich kennenlernen = to meet for the first time.', 'sich kennenlernen = ilk kez tanışmak.', 'kennenlernen = zum ersten Mal treffen.'),
  },
  {
    id: 'select-dativ',
    type: 'multiple_select',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-mixed',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which are correct? Select all.', 'Hangileri doğru? Hepsini seç.', 'Was ist richtig? Wähle alle.'),
    options: ['mit meiner Mutter', 'mit meinem Mutter', 'bei unseren Freunden', 'zu seinem Vater', 'mit ihre Kinder'],
    answers: [0, 2, 3],
    explanation: l('meiner Mutter (f), unseren Freunden (pl, + -n), seinem Vater (m).', 'meiner Mutter (dişil), unseren Freunden (çoğul, + -n), seinem Vater (eril).', 'meiner, unseren, seinem.'),
  },
  {
    id: 'image-streit',
    type: 'image_choice',
    topic: 'konflikt',
    concept: 'conflict-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Nachbarn streiten sich.',
    options: [
      { emoji: '😤', label: 'Streit' },
      { emoji: '🥳', label: 'Party' },
      { emoji: '🤝', label: 'Freundschaft' },
      { emoji: '😴', label: 'Ruhe' },
    ],
    answer: 0,
    explanation: l('sich streiten = to argue 😤.', 'sich streiten = kavga etmek 😤.', 'Streit.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-meinen',
    type: 'fill_blank',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-pl',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich telefoniere jeden Sonntag mit mein___ Eltern.',
    accepted: ['en'],
    base: 'Dativ Plural',
    explanation: l('Dativ plural → -en: meinen Eltern.', 'Dativ çoğul → -en: meinen Eltern.', 'meinen Eltern.'),
    examples: ['… mit **meinen** Eltern.'],
  },
  {
    id: 'fill-ihrer',
    type: 'fill_blank',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-f',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Lena wohnt seit einem Jahr bei ihr___ Tante.',
    accepted: ['er'],
    base: 'die Tante',
    explanation: l('bei + Dativ, die Tante → ihrer Tante.', 'bei + Dativ, die Tante → ihrer Tante.', 'ihrer Tante.'),
    examples: ['Lena wohnt bei **ihrer** Tante.'],
  },
  {
    id: 'fill-entschuldigen',
    type: 'fill_blank',
    topic: 'konflikt',
    concept: 'apologise',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Es tut mir leid. Ich möchte mich bei Ihnen ___.',
    accepted: ['entschuldigen'],
    base: 'sich entschuldigen',
    explanation: l('sich bei jemandem entschuldigen = to apologise to someone.', 'sich bei jemandem entschuldigen = birinden özür dilemek.', 'mich … entschuldigen.'),
    examples: ['Ich möchte mich bei Ihnen **entschuldigen**.'],
  },
  {
    id: 'build-kennengelernt',
    type: 'sentence_builder',
    topic: 'reziprok',
    concept: 'kennenlernen',
    skill: 'grammar',
    difficulty: 2,
    chips: ['kennengelernt', 'uns', 'Wir', 'im Deutschkurs', 'haben'],
    answers: [['Wir', 'haben', 'uns', 'im Deutschkurs', 'kennengelernt']],
    translation: l('We met in the German course.', 'Almanca kursunda tanıştık.', 'Wir haben uns im Deutschkurs kennengelernt.'),
    explanation: l('Perfekt: haben + uns + … + kennengelernt.', 'Perfekt: haben + uns + … + kennengelernt.', 'haben uns … kennengelernt.'),
    examples: ['Wir **haben uns** im Deutschkurs **kennengelernt**.'],
  },
  {
    id: 'build-verstehe',
    type: 'sentence_builder',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-m',
    skill: 'grammar',
    difficulty: 2,
    chips: ['mich', 'Ich', 'mit meinem Chef', 'gut', 'verstehe'],
    answers: [['Ich', 'verstehe', 'mich', 'gut', 'mit meinem Chef']],
    translation: l('I get on well with my boss.', 'Patronumla iyi anlaşıyorum.', 'Ich verstehe mich gut mit meinem Chef.'),
    explanation: l('sich verstehen mit + Dativ: mit meinem Chef.', 'sich verstehen mit + Dativ: mit meinem Chef.', 'mit meinem Chef.'),
    examples: ['Ich verstehe mich gut **mit meinem** Chef.'],
  },
  {
    id: 'build-streit',
    type: 'sentence_builder',
    topic: 'konflikt',
    concept: 'conflict-words',
    skill: 'grammar',
    difficulty: 3,
    chips: ['sich', 'oft', 'Die Kinder', 'streiten', 'wegen des Fernsehers'],
    answers: [['Die Kinder', 'streiten', 'sich', 'oft', 'wegen des Fernsehers']],
    translation: l('The children often argue about the TV.', 'Çocuklar sık sık televizyon yüzünden kavga ediyor.', 'Die Kinder streiten sich oft wegen des Fernsehers.'),
    explanation: l('sich streiten (reflexive). wegen = because of.', 'sich streiten (dönüşlü). wegen = … yüzünden.', 'streiten sich.'),
    examples: ['Die Kinder **streiten sich** oft.'],
  },
  {
    id: 'fix-mit-meine',
    type: 'error_correction',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-f',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich fahre mit meine Freundin nach Paris.',
    accepted: ['Ich fahre mit meiner Freundin nach Paris.'],
    explanation: l('mit + Dativ: die Freundin → meiner Freundin.', 'mit + Dativ: die Freundin → meiner Freundin.', 'meiner Freundin.'),
    examples: ['Ich fahre mit **meiner** Freundin nach Paris.'],
  },
  {
    id: 'fix-mit-mein',
    type: 'error_correction',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-m',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Er spricht mit sein Vater.',
    accepted: ['Er spricht mit seinem Vater.'],
    explanation: l('mit + Dativ: der Vater → seinem Vater.', 'mit + Dativ: der Vater → seinem Vater.', 'seinem Vater.'),
    examples: ['Er spricht mit **seinem** Vater.'],
  },
  {
    id: 'fix-freunden',
    type: 'error_correction',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-pl',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wir feiern mit unseren Freunde.',
    accepted: ['Wir feiern mit unseren Freunden.'],
    explanation: l('Dativ plural: the noun also gets -n: Freunden.', 'Dativ çoğul: isim de -n alır: Freunden.', 'Freunden.'),
    examples: ['Wir feiern mit unseren **Freunden**.'],
  },
  {
    id: 'tr-verstehen',
    type: 'translation',
    topic: 'reziprok',
    concept: 'sich-reciprocal',
    skill: 'writing',
    difficulty: 2,
    source: l('We get on very well.', 'Çok iyi anlaşıyoruz.', 'We get on very well.'),
    accepted: ['Wir verstehen uns sehr gut.'],
    explanation: l('sich verstehen: wir verstehen uns.', 'sich verstehen: wir verstehen uns.', 'Wir verstehen uns.'),
    examples: ['Wir **verstehen uns** sehr gut.'],
  },
  {
    id: 'tr-schwester',
    type: 'translation',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-f',
    skill: 'writing',
    difficulty: 2,
    source: l('I live with my sister.', 'Kız kardeşimle yaşıyorum.', 'I live with my sister.'),
    accepted: ['Ich wohne mit meiner Schwester.', 'Ich wohne bei meiner Schwester.', 'Ich lebe mit meiner Schwester.'],
    explanation: l('mit/bei + Dativ: meiner Schwester.', 'mit/bei + Dativ: meiner Schwester.', 'meiner Schwester.'),
    examples: ['Ich wohne mit **meiner** Schwester.'],
  },
  {
    id: 'ordering-konflikt',
    type: 'ordering',
    topic: 'konflikt',
    concept: 'conflict-solve',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the neighbour conversation in order.', 'Komşu konuşmasını sıraya koy.', 'Bring das Nachbargespräch in Ordnung.'),
    items: ['Oh, das tut mir leid! Ich mache die Musik leiser.', 'Entschuldigung, Ihre Musik ist sehr laut. Mein Baby kann nicht schlafen.', 'Kein Problem. Vielen Dank!', 'Guten Abend, Herr Lang. Haben Sie kurz Zeit?'],
    answer: ['Guten Abend, Herr Lang. Haben Sie kurz Zeit?', 'Entschuldigung, Ihre Musik ist sehr laut. Mein Baby kann nicht schlafen.', 'Oh, das tut mir leid! Ich mache die Musik leiser.', 'Kein Problem. Vielen Dank!'],
    explanation: l('Greet → problem → apology → thanks.', 'Selam → sorun → özür → teşekkür.', 'Gruß → Problem → Entschuldigung → Dank.'),
  },
  {
    id: 'dialog-konflikt',
    type: 'dialogue',
    topic: 'konflikt',
    concept: 'conflict-solve',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Nachbarin', de: 'Entschuldigung, Ihr Fahrrad steht schon wieder vor meiner Tür.' }],
    options: ['Oh, das tut mir leid! Ich stelle es sofort in den Keller.', 'Das ist mir egal.', 'Mein Fahrrad steht gern da.'],
    answer: 0,
    explanation: l('Apologise + offer a solution.', 'Özür dile + bir çözüm öner.', 'Entschuldigung + Lösung.'),
  },
  {
    id: 'dialog-beschreiben',
    type: 'dialogue',
    topic: 'beschreiben',
    concept: 'character',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Kollege', de: 'Wie ist denn deine neue Mitbewohnerin?' }],
    options: ['Sehr nett! Sie ist ehrlich und hilfsbereit.', 'Sie ist eine Mitbewohnerin.', 'Ich bin hilfsbereit sie.'],
    answer: 0,
    explanation: l('Describe her character with adjectives.', 'Karakterini sıfatlarla tarif et.', 'ehrlich, hilfsbereit.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-kennen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-freundschaft',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wo haben sich Jana und Fatma kennengelernt?',
    options: ['Im Kindergarten.', 'In der Uni.', 'Im Urlaub.'],
    answer: 0,
    explanation: l('„Wir haben uns schon im Kindergarten kennengelernt.“', '„Wir haben uns schon im Kindergarten kennengelernt.“', 'Kindergarten.'),
  },
  {
    id: 'read-warum',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-freundschaft',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum ist Fatma für Jana die beste Freundin?',
    options: ['Sie ist ehrlich und immer für sie da.', 'Sie wohnt neben ihr.', 'Sie hat viel Geld.'],
    answer: 0,
    explanation: l('„Sie ist ehrlich und immer für mich da.“', '„Sie ist ehrlich und immer für mich da.“', 'ehrlich, immer da.'),
  },
  {
    id: 'read-streit',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-freundschaft',
    skill: 'reading',
    difficulty: 2,
    statement: 'Jana und Fatma streiten sich nie.',
    answer: false,
    explanation: l('„Natürlich streiten wir uns manchmal …“', '„Natürlich streiten wir uns manchmal …“', 'manchmal Streit.'),
  },
  {
    id: 'read-heute',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-freundschaft',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie halten sie heute Kontakt?',
    options: ['Sie telefonieren jede Woche.', 'Sie schreiben Briefe.', 'Gar nicht.'],
    answer: 0,
    explanation: l('„Heute wohnt sie in München, aber wir telefonieren jede Woche.“', '„Heute wohnt sie in München, aber wir telefonieren jede Woche.“', 'jede Woche telefonieren.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-mit-wem',
    type: 'listening_choice',
    topic: 'possessiv-dativ',
    concept: 'poss-dat-m',
    skill: 'listening',
    difficulty: 2,
    audio: 'Am Wochenende gehe ich mit meinem Cousin Fußball spielen.',
    question: l('With whom?', 'Kiminle?', 'Mit wem?'),
    options: ['with a cousin', 'with a sister', 'with friends'],
    answer: 0,
    explanation: l('„mit meinem Cousin“', '„mit meinem Cousin“', 'Cousin.'),
  },
  {
    id: 'listen-entschuldigung',
    type: 'listening_choice',
    topic: 'konflikt',
    concept: 'apologise',
    skill: 'listening',
    difficulty: 2,
    audio: 'Entschuldige bitte, dass ich gestern so unfreundlich war. Ich hatte einen schlechten Tag.',
    question: l('What is the person doing?', 'Kişi ne yapıyor?', 'Was macht die Person?'),
    options: ['apologising', 'complaining', 'inviting'],
    answer: 0,
    explanation: l('„Entschuldige bitte, dass …“', '„Entschuldige bitte, dass …“', 'sich entschuldigen.'),
  },
  {
    id: 'listen-eigenschaft',
    type: 'listening_choice',
    topic: 'beschreiben',
    concept: 'character',
    skill: 'listening',
    difficulty: 1,
    audio: 'Mein Nachbar hilft allen im Haus. Er trägt sogar die Einkäufe von Frau Klein.',
    question: l('What’s the neighbour like?', 'Komşu nasıl biri?', 'Wie ist der Nachbar?'),
    options: ['hilfsbereit', 'unhöflich', 'faul'],
    answer: 0,
    explanation: l('He helps everyone → hilfsbereit.', 'Herkese yardım ediyor → hilfsbereit.', 'hilfsbereit.'),
  },
  {
    id: 'listen-verstehen',
    type: 'listening_choice',
    topic: 'reziprok',
    concept: 'sich-reciprocal',
    skill: 'listening',
    difficulty: 2,
    audio: 'Mein Bruder und ich verstehen uns leider nicht so gut. Wir streiten uns oft.',
    question: l('How do the brothers get on?', 'Kardeşler nasıl anlaşıyor?', 'Wie verstehen sich die Brüder?'),
    options: ['not well', 'very well', 'they never see each other'],
    answer: 0,
    explanation: l('„verstehen uns nicht so gut … streiten uns oft“', '„verstehen uns nicht so gut … streiten uns oft“', 'nicht gut.'),
  },

  ...possDrills(),
]

export const UNIT_A2_23_BEZIEHUNGEN: CourseUnit = {
  level: 'A2',
  number: 23,
  slug: 'beziehungen',
  titleDe: 'Freunde und Nachbarn',
  title: l('Friends and neighbours', 'Arkadaşlar ve komşular', 'Freunde und Nachbarn'),
  goal: l(
    'By the end of this unit you can describe friends and neighbours, talk about relationships (sich verstehen, sich kennenlernen, sich streiten), use possessives in the Dativ (mit meinem Bruder) and solve a small conflict politely.',
    'Bu ünitenin sonunda arkadaşları ve komşuları tarif edebilir, ilişkilerden bahsedebilir (sich verstehen, sich kennenlernen, sich streiten), Dativ’de iyelik sözcüklerini kullanabilir (mit meinem Bruder) ve küçük bir anlaşmazlığı kibarca çözebilirsin.',
    'Am Ende dieser Einheit sprichst du über Beziehungen und löst Konflikte.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'possessiv-dativ', label: l('mit meinem / meiner / meinen', 'mit meinem / meiner / meinen', 'Possessiv im Dativ') },
    { key: 'reziprok', label: l('sich verstehen, sich kennenlernen', 'sich verstehen, sich kennenlernen', 'sich verstehen …') },
    { key: 'beschreiben', label: l('Character', 'Karakter', 'Charakter') },
    { key: 'konflikt', label: l('Conflicts', 'Anlaşmazlıklar', 'Konflikte') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('People in your life – and how you get on with them.', 'Hayatındaki insanlar – ve onlarla nasıl anlaştığın.', 'Menschen in deinem Leben.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Possessives in the Dativ', 'Dativ’de iyelik sözcükleri', 'Possessivartikel im Dativ'),
          body: l(
            'After mit, bei, zu, von, aus, seit the possessive takes Dativ endings – the same as the article: dem → meinem, der → meiner, den → meinen (+ -n on the plural noun).',
            'mit, bei, zu, von, aus, seit’ten sonra iyelik sözcüğü Dativ eki alır – artikelle aynı: dem → meinem, der → meiner, den → meinen (+ çoğul isimde -n).',
            'meinem, meiner, meinen.'
          ),
          table: {
            head: [l('', '', ''), l('maskulin', 'eril', 'maskulin'), l('feminin', 'dişil', 'feminin'), l('neutral', 'nötr', 'neutral'), l('Plural', 'çoğul', 'Plural')],
            rows: [
              ['Artikel', 'dem Bruder', 'der Schwester', 'dem Kind', 'den Eltern'],
              ['mein', 'meinem Bruder', 'meiner Schwester', 'meinem Kind', 'meinen Eltern'],
              ['sein / ihr', 'seinem / ihrem', 'seiner / ihrer', 'seinem / ihrem', 'seinen / ihren'],
              ['unser', 'unserem', 'unserer', 'unserem', 'unseren'],
            ],
          },
        },
        {
          title: l('Each other: uns, euch, sich', 'Birbirini: uns, euch, sich', 'gegenseitig: uns, euch, sich'),
          body: l(
            'With plural subjects some reflexive verbs mean „each other“: Wir verstehen uns gut. Habt ihr euch gestritten? Sie haben sich im Kurs kennengelernt.',
            'Çoğul öznelerle bazı dönüşlü fiiller „birbirini“ anlamına gelir: Wir verstehen uns gut. Habt ihr euch gestritten? Sie haben sich im Kurs kennengelernt.',
            'Wir verstehen uns.'
          ),
        },
        {
          title: l('Solving a conflict politely', 'Bir anlaşmazlığı kibarca çözmek', 'Konflikte höflich lösen'),
          body: l(
            'Start politely: Entschuldigung, haben Sie kurz Zeit? – Describe the problem: Ihre Musik ist sehr laut. – React: Das tut mir leid! Ich … – End: Kein Problem. Danke für Ihr Verständnis.',
            'Kibarca başla: Entschuldigung, haben Sie kurz Zeit? – Sorunu anlat: Ihre Musik ist sehr laut. – Tepki ver: Das tut mir leid! Ich … – Bitir: Kein Problem. Danke für Ihr Verständnis.',
            'höflich → Problem → Entschuldigung → Dank.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('In the stairwell: a small problem between neighbours.', 'Merdiven boşluğunda: komşular arasında küçük bir sorun.', 'Im Treppenhaus: ein kleines Problem.'),
      dialogue: [
        { speaker: 'Frau Kaya', de: 'Guten Abend, Herr Lang. Haben Sie kurz Zeit?', translation: l('Good evening, Mr Lang. Do you have a moment?', 'İyi akşamlar Bay Lang. Bir dakikanız var mı?', '') },
        { speaker: 'Herr Lang', de: 'Natürlich. Was gibt’s?', translation: l('Of course. What’s up?', 'Elbette. Ne oldu?', '') },
        { speaker: 'Frau Kaya', de: 'Ihre Musik war gestern bis Mitternacht sehr laut. **Mein** Baby konnte nicht schlafen.', translation: l('Your music was very loud until midnight yesterday. My baby couldn’t sleep.', 'Dün gece yarısına kadar müziğiniz çok yüksekti. Bebeğim uyuyamadı.', '') },
        { speaker: 'Herr Lang', de: 'Oh, das tut mir wirklich leid! Ich habe **mit meinen** Freunden Geburtstag gefeiert.', translation: l('Oh, I’m really sorry! I was celebrating my birthday with my friends.', 'Ah, gerçekten çok üzgünüm! Arkadaşlarımla doğum günümü kutluyordum.', '') },
        { speaker: 'Frau Kaya', de: 'Ach so, herzlichen Glückwunsch! Kein Problem – nur bitte nicht so spät.', translation: l('Oh, happy birthday! No problem – just please not so late.', 'Ha, iyi ki doğdunuz! Sorun değil – sadece lütfen o kadar geç değil.', '') },
        { speaker: 'Herr Lang', de: 'Versprochen. Ich **entschuldige mich** auch bei **Ihrem** Mann. Möchten Sie ein Stück Kuchen? Es ist noch viel übrig!', translation: l('I promise. I’ll apologise to your husband too. Would you like a piece of cake? There’s lots left!', 'Söz veriyorum. Eşinizden de özür dileyeceğim. Bir dilim pasta ister misiniz? Hâlâ çok var!', '') },
        { speaker: 'Frau Kaya', de: 'Gern, danke! Ich glaube, wir **verstehen uns** gut. 😊', translation: l('Gladly, thanks! I think we get on well. 😊', 'Memnuniyetle, teşekkürler! Sanırım iyi anlaşıyoruz. 😊', '') },
      ],
      examples: [
        { de: 'Ich wohne **bei meiner** Tante.', translation: l('I live at my aunt’s.', 'Teyzemin yanında kalıyorum.', '') },
        { de: 'Er spielt **mit seinem** Sohn.', translation: l('He plays with his son.', 'Oğluyla oynuyor.', '') },
        { de: 'Wir telefonieren **mit unseren** Eltern.', translation: l('We phone our parents.', 'Ailemizle telefonlaşıyoruz.', '') },
        { de: 'Wir **verstehen uns** sehr gut.', translation: l('We get on very well.', 'Çok iyi anlaşıyoruz.', '') },
        { de: 'Sie haben **sich** im Kurs **kennengelernt**.', translation: l('They met in the course.', 'Kursta tanıştılar.', '') },
        { de: 'Ich möchte **mich entschuldigen**.', translation: l('I’d like to apologise.', 'Özür dilemek istiyorum.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Endings, relationships, character.', 'Ekler, ilişkiler, karakter.', 'Endungen, Beziehungen, Charakter.'),
      exercises: ['match-endungen', 'poss-bruder', 'poss-schwester', 'sort-eigenschaften', 'mc-uns', 'tf-kennengelernt', 'select-dativ', 'image-streit', 'poss-eltern'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about people – and solve conflicts.', 'İnsanlardan bahset – ve anlaşmazlıkları çöz.', 'Über Menschen sprechen, Konflikte lösen.'),
      exercises: [
        'fill-meinen',
        'fill-ihrer',
        'fill-entschuldigen',
        'build-kennengelernt',
        'build-verstehe',
        'build-streit',
        'fix-mit-meine',
        'fix-mit-mein',
        'fix-freunden',
        'tr-verstehen',
        'tr-schwester',
        'ordering-konflikt',
        'dialog-konflikt',
        'dialog-beschreiben',
        'poss-kind',
        'poss-freundin',
        'poss-nachbar',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Jana writes about her best friend.', 'Jana en yakın arkadaşını anlatıyor.', 'Jana schreibt über ihre beste Freundin.'),
      passage: [
        'Meine beste Freundin heißt Fatma. Wir **haben uns** schon im Kindergarten **kennengelernt**.',
        'Fatma ist ehrlich und immer für mich da. Wenn ich ein Problem **mit meinen** Eltern oder **meinem** Freund habe, rufe ich zuerst sie an.',
        'Natürlich **streiten** wir **uns** manchmal – aber nie lange!',
        'Heute wohnt sie in München, aber wir telefonieren jede Woche. Im Sommer fahre ich **zu ihr** – darauf freue ich mich schon!',
      ],
      glossary: [
        { de: 'der Kindergarten', note: l('nursery school', 'anaokulu', 'für Kinder von 3–6') },
        { de: 'für jemanden da sein', note: l('to be there for someone', 'birinin yanında olmak', 'helfen, unterstützen') },
        { de: 'nie lange', note: l('never for long', 'asla uzun sürmez', 'immer nur kurz') },
      ],
      exercises: ['read-kennen', 'read-warum', 'read-streit', 'read-heute'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('People, relationships and apologies.', 'İnsanlar, ilişkiler ve özürler.', 'Menschen, Beziehungen, Entschuldigungen.'),
      exercises: ['listen-mit-wem', 'listen-entschuldigung', 'listen-eigenschaft', 'listen-verstehen'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe an important person in your life (friend, family member, neighbour).', 'Hayatındaki önemli bir kişiyi anlat (arkadaş, aile üyesi, komşu).', 'Beschreib eine wichtige Person.'),
      points: [
        l('Who? How did you meet? („Wir haben uns … kennengelernt.“)', 'Kim? Nasıl tanıştınız? („Wir haben uns … kennengelernt.“)', 'Wer? Wie kennengelernt?'),
        l('What’s the person like? (3 adjectives)', 'Nasıl biri? (3 sıfat)', 'Wie ist die Person?'),
        l('What do you do together? („mit meinem/meiner …“)', 'Birlikte ne yapıyorsunuz? („mit meinem/meiner …“)', 'Was macht ihr zusammen?'),
        l('Do you ever argue?', 'Hiç tartışıyor musunuz?', 'Streitet ihr manchmal?'),
      ],
      model: [
        'Mein bester Freund heißt Kerem. Wir haben uns an der Uni kennengelernt.',
        'Er ist lustig, ehrlich und sehr hilfsbereit.',
        'Am Wochenende spiele ich oft mit ihm und seinem Bruder Basketball.',
        'Wir streiten uns selten – und wenn, dann nur über Fußball!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a polite note to a neighbour about a problem (at least 4 sentences).',
        'Bir komşuya bir sorun hakkında kibar bir not yaz (en az 4 cümle).',
        'Schreib eine höfliche Nachricht an einen Nachbarn (mindestens 4 Sätze).'
      ),
      minSentences: 4,
      checks: [
        { label: l('Polite start (Liebe/r …, Entschuldigung …)', 'Kibar başlangıç (Liebe/r …, Entschuldigung …)', 'Höflicher Anfang'), pattern: '(Liebe[r]?|Hallo|Sehr geehrte|Entschuldigung)' },
        { label: l('A possessive in the Dativ (meinem, meiner, meinen …)', 'Dativ’de bir iyelik (meinem, meiner, meinen …)', 'Possessiv im Dativ'), pattern: '\\b(mein|dein|sein|ihr|unser|euer|Ihr)(em|er|en)\\b' },
        { label: l('A polite request (Könnten Sie / bitte)', 'Kibar bir rica (Könnten Sie / bitte)', 'Höfliche Bitte'), pattern: '(Könnten Sie|Könntest du|bitte)' },
      ],
      model: [
        'Liebe Frau Schulz, entschuldigen Sie die Störung.',
        'Ihr Hund bellt jeden Morgen sehr laut.',
        'Dann wacht auch das Baby von meiner Schwester schon um fünf Uhr auf.',
        'Könnten Sie bitte eine Lösung finden?',
        'Vielen Dank und viele Grüße, Ihre Nachbarin Ayşe Kaya',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Possessives in the Dativ – 60 seconds.', 'Dativ’de iyelik – 60 saniye.', 'Possessiv im Dativ – 60 Sekunden.'),
      seconds: 60,
      pool: [...POSS.map(([id]) => `poss-${id}`), 'mc-uns'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('mit meinem (m/n) · meiner (f) · meinen (pl + -n)', 'mit meinem (eril/nötr) · meiner (dişil) · meinen (çoğul + -n)', 'Possessiv im Dativ'),
      l('sich verstehen, sich kennenlernen, sich streiten', 'sich verstehen, sich kennenlernen, sich streiten', 'reziproke Verben'),
      l('Character: zuverlässig, hilfsbereit, ehrlich', 'Karakter: zuverlässig, hilfsbereit, ehrlich', 'Charakter'),
      l('Polite conflict talk: Das tut mir leid! / Könnten Sie bitte …?', 'Kibar anlaşmazlık konuşması: Das tut mir leid! / Könnten Sie bitte …?', 'Konflikte'),
    ],
    mistakes: [
      { wrong: 'mit meine Freundin', right: 'mit meiner Freundin', note: l('Dativ f → -er.', 'Dativ dişil → -er.', '-er.') },
      { wrong: 'mit mein Bruder', right: 'mit meinem Bruder', note: l('Dativ m → -em.', 'Dativ eril → -em.', '-em.') },
      { wrong: 'mit meinen Freunde', right: 'mit meinen Freunden', note: l('Dativ plural noun + -n.', 'Dativ çoğul isim + -n.', '+ -n.') },
      { wrong: 'Wir verstehen gut.', right: 'Wir verstehen uns gut.', note: l('sich verstehen.', 'sich verstehen.', 'uns.') },
    ],
  },
}
