import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'wenn', emoji: '🔀', translation: l('if, when(ever)', 'eğer, -dığında', 'Bedingung / Zeit'), example: 'Wenn ich Zeit habe, gehe ich schwimmen.' },
  { word: 'dann', emoji: '➡️', translation: l('then', 'o zaman', 'danach / in diesem Fall'), example: 'Wenn es regnet, dann bleiben wir zu Hause.' },
  { word: 'deshalb', emoji: '🔁', translation: l('that’s why, so', 'bu yüzden', 'Folge'), example: 'Ich bin krank, deshalb bleibe ich im Bett.' },
  { word: 'trotzdem', emoji: '💪', translation: l('nevertheless, still', 'yine de', 'Gegensatz'), example: 'Es regnet, trotzdem gehe ich joggen.' },
  { word: 'aber', emoji: '↔️', translation: l('but', 'ama', 'Gegensatz'), example: 'Ich bin müde, aber ich muss noch lernen.' },
  { word: 'oder', emoji: '🔃', translation: l('or', 'ya da', 'Alternative'), example: 'Kommst du mit oder bleibst du hier?' },
  { word: 'falls', emoji: '☂️', translation: l('in case', 'olur da …-se', 'wenn vielleicht'), example: 'Nimm einen Schirm mit, falls es regnet.' },
  { word: 'Zeit haben', emoji: '⏳', translation: l('to have time', 'vakti olmak', 'nicht beschäftigt sein'), example: 'Wenn du Zeit hast, ruf mich an.' },
  { word: 'Lust haben', emoji: '😃', translation: l('to feel like', 'canı istemek', 'etwas gern tun wollen'), example: 'Hast du Lust auf Kino?' },
  { word: 'schönes Wetter', emoji: '🌤️', translation: l('nice weather', 'güzel hava', 'Sonne'), example: 'Wenn schönes Wetter ist, grillen wir.' },
  { word: 'krank sein', emoji: '🤒', translation: l('to be ill', 'hasta olmak', 'nicht gesund'), example: 'Wenn ich krank bin, gehe ich zum Arzt.' },
  { word: 'frei haben', emoji: '🏖️', translation: l('to have time off', 'izinli olmak', 'nicht arbeiten'), example: 'Wenn ich frei habe, schlafe ich lange.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Schirm', gender: 'm', plural: 'die Schirme', translation: l('umbrella', 'şemsiye', 'Regenschirm') },
  { word: 'Ausflug', gender: 'm', plural: 'die Ausflüge', translation: l('excursion', 'gezi', 'Ausflug') },
  { word: 'Wochenende', gender: 'n', plural: 'die Wochenenden', translation: l('weekend', 'hafta sonu', 'Wochenende') },
  { word: 'Party', gender: 'f', plural: 'die Partys', translation: l('party', 'parti', 'Party') },
  { word: 'Grillen', gender: 'n', translation: l('barbecue', 'mangal', 'Grillen') },
]

/** [id, wenn-clause, main-clause verb, rest of main clause (subject …)] */
const WENN_FIRST: [string, string, string, string][] = [
  ['zeit', 'Wenn ich Zeit habe,', 'gehe', 'ich ins Kino'],
  ['regen', 'Wenn es regnet,', 'bleiben', 'wir zu Hause'],
  ['muede', 'Wenn er müde ist,', 'trinkt', 'er Kaffee'],
  ['frei', 'Wenn wir frei haben,', 'fahren', 'wir ans Meer'],
  ['krank', 'Wenn du krank bist,', 'musst', 'du im Bett bleiben'],
  ['lust', 'Wenn ihr Lust habt,', 'kommt', 'ihr am Samstag vorbei'],
]

function wennDrills(): Exercise[] {
  return WENN_FIRST.map(([id, clause, verb, rest], i) => {
    const [subject, ...more] = rest.split(' ')
    const right = `${clause} ${verb} ${rest}.`
    const wrongA = `${clause} ${subject} ${verb} ${more.join(' ')}.`
    const wrongB = `${clause} dann ${subject} ${verb} ${more.join(' ')}.`
    const options = [right, wrongA, wrongB]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `wenn-${id}`,
      type: 'multiple_choice' as const,
      topic: 'nebensatz-zuerst',
      concept: 'verb-comma-verb',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: `${clause} …`,
      promptL10n: l('Which sentence is correct?', 'Hangi cümle doğru?', 'Welcher Satz ist richtig?'),
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `The wenn-clause is position 1, so the main-clause verb comes right after the comma: „…, ${verb} ${subject} …“ (verb, verb).`,
        `wenn-cümlesi 1. pozisyondur, bu yüzden ana cümlenin fiili virgülden hemen sonra gelir: „…, ${verb} ${subject} …“ (fiil, fiil).`,
        `Nebensatz = Position 1 → „…, ${verb} ${subject} …“.`
      ),
      examples: [`${clause.replace(/(\S+),$/, '**$1**,')} **${verb}** ${rest}.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-halves',
    type: 'matching',
    topic: 'wenn',
    concept: 'wenn-meaning',
    skill: 'reading',
    difficulty: 1,
    instructions: l('Match the halves.', 'Yarımları eşleştir.', 'Ordne die Satzhälften zu.'),
    pairs: [
      { left: 'Wenn ich Hunger habe,', right: 'esse ich ein Brot.' },
      { left: 'Wenn es kalt ist,', right: 'trage ich einen Mantel.' },
      { left: 'Wenn ich müde bin,', right: 'gehe ich früh ins Bett.' },
      { left: 'Wenn die Sonne scheint,', right: 'gehen wir in den Park.' },
    ],
    explanation: l('wenn = condition → main clause = what happens then. Note: verb, verb.', 'wenn = koşul → ana cümle = o zaman olan. Dikkat: fiil, fiil.', 'Wenn …, Verb …'),
  },
  {
    id: 'mc-verb-position',
    type: 'multiple_choice',
    topic: 'wenn',
    concept: 'wenn-verb-end',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich rufe dich an, wenn ich zu Hause ___.',
    options: ['bin', 'ist', 'sein'],
    answer: 0,
    explanation: l('wenn → verb at the end; ich → bin.', 'wenn → fiil sonda; ich → bin.', 'wenn ich zu Hause bin.'),
    examples: ['Ich rufe dich an, wenn ich zu Hause **bin**.'],
  },
  {
    id: 'sort-deshalb-trotzdem',
    type: 'categorize',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-or-trotzdem',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('deshalb (consequence) or trotzdem (contrast)?', 'deshalb (sonuç) mu trotzdem (karşıtlık) mu?', 'deshalb oder trotzdem?'),
    categories: ['deshalb', 'trotzdem'],
    items: [
      { text: 'Ich bin krank, ___ bleibe ich zu Hause.', category: 0 },
      { text: 'Ich bin krank, ___ gehe ich zur Arbeit.', category: 1 },
      { text: 'Es regnet, ___ nehme ich den Schirm.', category: 0 },
      { text: 'Es regnet, ___ gehen wir spazieren.', category: 1 },
      { text: 'Das Essen ist teuer, ___ kaufe ich es nicht.', category: 0 },
      { text: 'Das Essen ist teuer, ___ kaufe ich es.', category: 1 },
    ],
    explanation: l(
      'deshalb = logical result (so). trotzdem = unexpected result (nevertheless). Both are position 1 → verb comes next.',
      'deshalb = mantıklı sonuç (bu yüzden). trotzdem = beklenmedik sonuç (yine de). İkisi de 1. pozisyondur → ardından fiil gelir.',
      'deshalb = Folge · trotzdem = Gegensatz.'
    ),
    practice: ['mc-trotzdem'],
  },
  {
    id: 'mc-trotzdem',
    type: 'multiple_choice',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-or-trotzdem',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich habe wenig Geld, ___ fahre ich in den Urlaub.',
    options: ['trotzdem', 'deshalb', 'weil'],
    answer: 0,
    explanation: l('Little money but still a holiday → unexpected → trotzdem.', 'Az para ama yine de tatil → beklenmedik → trotzdem.', 'trotzdem.'),
    examples: ['Ich habe wenig Geld, **trotzdem fahre** ich in den Urlaub.'],
  },
  {
    id: 'tf-deshalb',
    type: 'true_false',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-position',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Ich habe Hunger, deshalb ich esse eine Pizza.',
    answer: false,
    instructions: l('Is this sentence correct?', 'Bu cümle doğru mu?', 'Ist der Satz richtig?'),
    explanation: l('deshalb is position 1 → verb in position 2: deshalb esse ich …', 'deshalb 1. pozisyondur → fiil 2. sırada: deshalb esse ich …', 'deshalb esse ich.'),
    examples: ['Ich habe Hunger, **deshalb esse** ich eine Pizza.'],
  },
  {
    id: 'image-wenn',
    type: 'image_choice',
    topic: 'wenn',
    concept: 'wenn-meaning',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Wenn es schneit, bauen die Kinder einen Schneemann.',
    options: [
      { emoji: '⛄', label: 'Schneemann' },
      { emoji: '🏖️', label: 'Strand' },
      { emoji: '🌻', label: 'Blume' },
      { emoji: '🍂', label: 'Herbst' },
    ],
    answer: 0,
    explanation: l('schneien → Schneemann ⛄.', 'schneien (kar yağmak) → kardan adam ⛄.', 'Schneemann.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-wenn',
    type: 'fill_blank',
    topic: 'wenn',
    concept: 'wenn-verb-end',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wenn ich Zeit ___, besuche ich dich.',
    accepted: ['habe'],
    base: 'haben',
    explanation: l('wenn → verb at the end: Wenn ich Zeit habe, …', 'wenn → fiil sonda: Wenn ich Zeit habe, …', 'Wenn ich Zeit habe, …'),
    examples: ['Wenn ich Zeit **habe**, **besuche** ich dich.'],
  },
  {
    id: 'fill-main',
    type: 'fill_blank',
    topic: 'nebensatz-zuerst',
    concept: 'verb-comma-verb',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wenn das Wetter schön ist, ___ wir im Garten.',
    accepted: ['grillen'],
    base: 'grillen',
    explanation: l('After the wenn-clause the main verb comes first: …, grillen wir.', 'wenn-cümlesinden sonra ana fiil başta gelir: …, grillen wir.', '…, grillen wir.'),
    examples: ['Wenn das Wetter schön ist, **grillen** wir im Garten.'],
  },
  {
    id: 'fill-falls',
    type: 'fill_blank',
    topic: 'wenn',
    concept: 'falls',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Hier ist meine Nummer, ___ du Hilfe brauchst.',
    accepted: ['falls', 'wenn'],
    base: 'in case',
    explanation: l('falls = in case (a possibility). wenn also works.', 'falls = olur da (bir olasılık). wenn de olur.', 'falls / wenn.'),
    examples: ['Hier ist meine Nummer, **falls** du Hilfe brauchst.'],
  },
  {
    id: 'build-wenn-first',
    type: 'sentence_builder',
    topic: 'nebensatz-zuerst',
    concept: 'verb-comma-verb',
    skill: 'grammar',
    difficulty: 2,
    chips: ['schlafe', 'Wenn ich frei habe,', 'lange', 'ich'],
    answers: [['Wenn ich frei habe,', 'schlafe', 'ich', 'lange']],
    translation: l('When I have time off, I sleep late.', 'İzinli olduğumda geç saate kadar uyurum.', 'Wenn ich frei habe, schlafe ich lange.'),
    explanation: l('wenn-clause (1) – verb (2) – subject.', 'wenn-cümlesi (1) – fiil (2) – özne.', 'Wenn …, schlafe ich …'),
    examples: ['Wenn ich frei habe, **schlafe** ich lange.'],
  },
  {
    id: 'build-wenn-second',
    type: 'sentence_builder',
    topic: 'wenn',
    concept: 'wenn-verb-end',
    skill: 'grammar',
    difficulty: 2,
    chips: ['Lust', 'Ich komme mit,', 'habe', 'ich', 'wenn'],
    answers: [['Ich komme mit,', 'wenn', 'ich', 'Lust', 'habe']],
    translation: l('I’ll come along if I feel like it.', 'Canım isterse gelirim.', 'Ich komme mit, wenn ich Lust habe.'),
    explanation: l('Main clause first, then wenn + verb at the end.', 'Önce ana cümle, sonra wenn + fiil sonda.', '…, wenn ich Lust habe.'),
    examples: ['Ich komme mit, **wenn** ich Lust **habe**.'],
  },
  {
    id: 'build-trotzdem',
    type: 'sentence_builder',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-position',
    skill: 'grammar',
    difficulty: 2,
    chips: ['zur Arbeit', 'gehe', 'trotzdem', 'ich', 'Ich bin erkältet,'],
    answers: [['Ich bin erkältet,', 'trotzdem', 'gehe', 'ich', 'zur Arbeit']],
    translation: l('I have a cold, but I’m still going to work.', 'Nezleyim, yine de işe gidiyorum.', 'Ich bin erkältet, trotzdem gehe ich zur Arbeit.'),
    explanation: l('trotzdem (1) – verb (2) – subject.', 'trotzdem (1) – fiil (2) – özne.', 'trotzdem gehe ich.'),
    examples: ['Ich bin erkältet, **trotzdem gehe** ich zur Arbeit.'],
  },
  {
    id: 'fix-wenn',
    type: 'error_correction',
    topic: 'nebensatz-zuerst',
    concept: 'verb-comma-verb',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wenn ich Hunger habe, ich koche Nudeln.',
    accepted: ['Wenn ich Hunger habe, koche ich Nudeln.'],
    explanation: l('After the wenn-clause: verb first → koche ich.', 'wenn-cümlesinden sonra: önce fiil → koche ich.', '…, koche ich.'),
    examples: ['Wenn ich Hunger habe, **koche** ich Nudeln.'],
  },
  {
    id: 'fix-wenn-end',
    type: 'error_correction',
    topic: 'wenn',
    concept: 'wenn-verb-end',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich gehe spazieren, wenn scheint die Sonne.',
    accepted: ['Ich gehe spazieren, wenn die Sonne scheint.'],
    explanation: l('wenn → verb at the end: wenn die Sonne scheint.', 'wenn → fiil sonda: wenn die Sonne scheint.', 'wenn die Sonne scheint.'),
    examples: ['…, wenn die Sonne **scheint**.'],
  },
  {
    id: 'fix-deshalb',
    type: 'error_correction',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-position',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Der Bus kommt nicht, deshalb wir nehmen ein Taxi.',
    accepted: ['Der Bus kommt nicht, deshalb nehmen wir ein Taxi.'],
    explanation: l('deshalb + verb + subject.', 'deshalb + fiil + özne.', 'deshalb nehmen wir.'),
    examples: ['Der Bus kommt nicht, **deshalb nehmen** wir ein Taxi.'],
  },
  {
    id: 'tr-wenn',
    type: 'translation',
    topic: 'nebensatz-zuerst',
    concept: 'verb-comma-verb',
    skill: 'writing',
    difficulty: 2,
    source: l('When it rains, I stay at home.', 'Yağmur yağdığında evde kalırım.', 'When it rains, I stay at home.'),
    accepted: ['Wenn es regnet, bleibe ich zu Hause.', 'Wenn es regnet, bleibe ich zuhause.'],
    explanation: l('Wenn es regnet, bleibe ich … (verb, verb).', 'Wenn es regnet, bleibe ich … (fiil, fiil).', 'Wenn es regnet, bleibe ich zu Hause.'),
    examples: ['Wenn es **regnet**, **bleibe** ich zu Hause.'],
  },
  {
    id: 'tr-deshalb',
    type: 'translation',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-position',
    skill: 'writing',
    difficulty: 2,
    source: l('I’m tired, so I’m going to bed.', 'Yorgunum, bu yüzden yatmaya gidiyorum.', 'I’m tired, so I’m going to bed.'),
    accepted: ['Ich bin müde, deshalb gehe ich ins Bett.'],
    explanation: l('deshalb gehe ich …', 'deshalb gehe ich …', 'deshalb gehe ich ins Bett.'),
    examples: ['Ich bin müde, **deshalb gehe** ich ins Bett.'],
  },
  {
    id: 'ordering-plan',
    type: 'ordering',
    topic: 'nebensatz-zuerst',
    concept: 'verb-comma-verb',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Build the sentence.', 'Cümleyi kur.', 'Bilde den Satz.'),
    items: ['fahren', 'Wenn es warm ist,', 'an den See', 'wir'],
    answer: ['Wenn es warm ist,', 'fahren', 'wir', 'an den See'],
    explanation: l('wenn-clause – verb – subject – rest.', 'wenn-cümlesi – fiil – özne – geri kalan.', 'Wenn …, fahren wir …'),
  },
  {
    id: 'dialog-wochenende',
    type: 'dialogue',
    topic: 'wenn',
    concept: 'wenn-meaning',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Freundin', de: 'Machen wir am Samstag einen Ausflug?' }],
    options: ['Gern, wenn das Wetter gut ist.', 'Gern, wenn ist das Wetter gut.', 'Gern, wenn das Wetter ist gut.'],
    answer: 0,
    explanation: l('wenn → verb at the end.', 'wenn → fiil sonda.', 'wenn das Wetter gut ist.'),
  },
  {
    id: 'dialog-trotzdem',
    type: 'dialogue',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-or-trotzdem',
    skill: 'grammar',
    difficulty: 2,
    lines: [
      { speaker: 'Kollege', de: 'Es ist schon 22 Uhr. Gehst du nicht nach Hause?' },
    ],
    options: ['Doch, aber ich bin noch nicht fertig. Trotzdem gehe ich jetzt.', 'Doch, aber ich bin noch nicht fertig. Trotzdem ich gehe jetzt.', 'Doch, trotzdem ich bin nicht fertig.'],
    answer: 0,
    explanation: l('Trotzdem + verb + subject.', 'Trotzdem + fiil + özne.', 'Trotzdem gehe ich.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-sonne',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-familie',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was macht Familie Wagner, wenn die Sonne scheint?',
    options: ['Sie fahren mit dem Fahrrad an den See.', 'Sie gehen ins Museum.', 'Sie bleiben zu Hause.'],
    answer: 0,
    explanation: l('„Wenn die Sonne scheint, fahren wir mit dem Fahrrad an den See.“', '„Wenn die Sonne scheint, fahren wir mit dem Fahrrad an den See.“', '„an den See“'),
  },
  {
    id: 'read-regen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-familie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Und wenn es regnet?',
    options: ['Sie spielen Brettspiele oder gehen ins Museum.', 'Sie fahren trotzdem an den See.', 'Sie schlafen den ganzen Tag.'],
    answer: 0,
    explanation: l('„Wenn es regnet, spielen wir Brettspiele oder gehen ins Museum.“', '„Wenn es regnet, spielen wir Brettspiele oder gehen ins Museum.“', '„Brettspiele … Museum“'),
  },
  {
    id: 'read-papa',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-familie',
    skill: 'reading',
    difficulty: 2,
    statement: 'Der Vater arbeitet am Wochenende nie.',
    answer: false,
    explanation: l('„Manchmal muss Papa samstags arbeiten. Trotzdem …“', '„Manchmal muss Papa samstags arbeiten. Trotzdem …“', '„muss Papa samstags arbeiten“'),
  },
  {
    id: 'read-sonntag',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-familie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum frühstücken sie sonntags lange?',
    options: ['Weil alle Zeit haben.', 'Weil Oma kommt.', 'Weil es regnet.'],
    answer: 0,
    explanation: l('„Sonntags haben alle Zeit, deshalb frühstücken wir lange.“', '„Sonntags haben alle Zeit, deshalb frühstücken wir lange.“', '„alle haben Zeit“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-wenn',
    type: 'listening_choice',
    topic: 'wenn',
    concept: 'wenn-meaning',
    skill: 'listening',
    difficulty: 1,
    audio: 'Wenn ich morgen früh fertig bin, komme ich zum Mittagessen.',
    question: l('When will the person come to lunch?', 'Kişi öğle yemeğine ne zaman gelecek?', 'Wann kommt die Person zum Essen?'),
    options: ['if they finish early', 'never', 'in the evening'],
    answer: 0,
    explanation: l('„Wenn ich … fertig bin“ = if I’m finished.', '„Wenn ich … fertig bin“ = işim biterse.', 'wenn … fertig.'),
  },
  {
    id: 'listen-trotzdem',
    type: 'listening_choice',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-or-trotzdem',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Film hat schlechte Kritiken. Trotzdem möchte ich ihn sehen.',
    question: l('Will the person watch the film?', 'Kişi filmi izleyecek mi?', 'Sieht die Person den Film?'),
    options: ['Ja', 'Nein'],
    answer: 0,
    explanation: l('trotzdem = still → yes.', 'trotzdem = yine de → evet.', 'trotzdem → ja.'),
  },
  {
    id: 'listen-deshalb',
    type: 'listening_choice',
    topic: 'deshalb-trotzdem',
    concept: 'deshalb-or-trotzdem',
    skill: 'listening',
    difficulty: 2,
    audio: 'Mein Auto ist in der Werkstatt, deshalb fahre ich diese Woche mit dem Bus.',
    question: l('How does the person travel this week?', 'Kişi bu hafta nasıl ulaşım sağlıyor?', 'Wie fährt die Person diese Woche?'),
    options: ['🚌', '🚗', '🚲'],
    answer: 0,
    explanation: l('„deshalb fahre ich … mit dem Bus“', '„deshalb fahre ich … mit dem Bus“', '„mit dem Bus“'),
  },
  {
    id: 'listen-falls',
    type: 'listening_choice',
    topic: 'wenn',
    concept: 'falls',
    skill: 'listening',
    difficulty: 2,
    audio: 'Nimm eine Jacke mit, falls es am Abend kalt wird.',
    question: l('What should you take?', 'Ne almalısın?', 'Was soll man mitnehmen?'),
    options: ['🧥', '☂️', '🕶️'],
    answer: 0,
    explanation: l('eine Jacke 🧥 – in case it gets cold.', 'bir ceket 🧥 – soğuk olursa diye.', 'eine Jacke.'),
  },

  ...wennDrills(),
]

export const UNIT_A2_09_WENN_DANN: CourseUnit = {
  level: 'A2',
  number: 9,
  slug: 'wenn-dann',
  titleDe: 'Wenn ich Zeit habe, …',
  title: l('When I have time, …', 'Vaktim olduğunda …', 'Wenn ich Zeit habe, …'),
  goal: l(
    'By the end of this unit you can talk about conditions and plans with wenn, start a sentence with the subordinate clause („Wenn …, gehe ich …“) and connect ideas with deshalb and trotzdem.',
    'Bu ünitenin sonunda wenn ile koşulları ve planları anlatabilir, cümleye yan cümleyle başlayabilir („Wenn …, gehe ich …“) ve fikirleri deshalb ve trotzdem ile bağlayabilirsin.',
    'Am Ende dieser Einheit sprichst du über Bedingungen mit wenn und verbindest Sätze mit deshalb/trotzdem.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'wenn', label: l('wenn-clauses', 'wenn-cümleleri', 'wenn-Sätze') },
    { key: 'nebensatz-zuerst', label: l('„Wenn …, gehe ich …“', '„Wenn …, gehe ich …“', 'Nebensatz zuerst') },
    { key: 'deshalb-trotzdem', label: l('deshalb & trotzdem', 'deshalb ve trotzdem', 'deshalb & trotzdem') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Words to connect ideas – and conditions you need for plans.', 'Fikirleri bağlayan kelimeler – ve planlar için koşullar.', 'Wörter zum Verbinden.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('wenn: verb at the end', 'wenn: fiil sonda', 'wenn: Verb am Ende'),
          body: l(
            'wenn (if / whenever) starts a subordinate clause like weil and dass: the verb goes to the end. Ich gehe schwimmen, wenn ich Zeit habe.',
            'wenn (eğer / -dığında) weil ve dass gibi bir yan cümle başlatır: fiil sona gider. Ich gehe schwimmen, wenn ich Zeit habe.',
            'wenn … Verb am Ende.'
          ),
        },
        {
          title: l('Subordinate clause first: verb, verb', 'Önce yan cümle: fiil, fiil', 'Nebensatz zuerst: Verb, Verb'),
          body: l(
            'If the wenn-clause comes first, it counts as position 1. So the main-clause verb comes immediately after the comma – you get two verbs next to each other.',
            'wenn-cümlesi başa gelirse 1. pozisyon sayılır. Bu yüzden ana cümlenin fiili virgülden hemen sonra gelir – yan yana iki fiil olur.',
            'Nebensatz = Position 1 → Verb, Verb.'
          ),
          table: {
            head: [l('Position 1', '1. pozisyon', 'Position 1'), l('Verb (2)', 'Fiil (2)', 'Verb (2)'), l('Subject', 'Özne', 'Subjekt'), l('…', '…', '…')],
            rows: [
              ['Am Wochenende', 'gehe', 'ich', 'schwimmen.'],
              ['Wenn ich Zeit habe,', 'gehe', 'ich', 'schwimmen.'],
              ['Wenn es regnet,', 'bleiben', 'wir', 'zu Hause.'],
            ],
          },
          tip: l('Remember: „…habe, gehe ich …“ – verb, comma, verb.', 'Unutma: „…habe, gehe ich …“ – fiil, virgül, fiil.', 'Verb, Komma, Verb.'),
        },
        {
          title: l('deshalb and trotzdem: position 1', 'deshalb ve trotzdem: 1. pozisyon', 'deshalb und trotzdem: Position 1'),
          body: l(
            'deshalb (so, that’s why) and trotzdem (nevertheless) take position 1 in a main clause – the verb follows directly: deshalb bleibe ich, trotzdem gehe ich.',
            'deshalb (bu yüzden) ve trotzdem (yine de) ana cümlede 1. pozisyonu alır – fiil hemen ardından gelir: deshalb bleibe ich, trotzdem gehe ich.',
            'deshalb/trotzdem + Verb + Subjekt.'
          ),
          examples: [
            { de: 'Es regnet, **deshalb bleibe** ich zu Hause.', translation: l('It’s raining, so I’m staying at home.', 'Yağmur yağıyor, bu yüzden evde kalıyorum.', '') },
            { de: 'Es regnet, **trotzdem gehe** ich joggen.', translation: l('It’s raining, but I’m still going jogging.', 'Yağmur yağıyor, yine de koşuya gidiyorum.', '') },
          ],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two friends plan the weekend.', 'İki arkadaş hafta sonunu planlıyor.', 'Zwei Freunde planen das Wochenende.'),
      dialogue: [
        { speaker: 'Jan', de: 'Was machst du am Wochenende?', translation: l('What are you doing at the weekend?', 'Hafta sonu ne yapıyorsun?', '') },
        { speaker: 'Mira', de: '**Wenn** das Wetter schön **ist**, **fahre** ich mit dem Rad an den See.', translation: l('If the weather is nice, I’m cycling to the lake.', 'Hava güzel olursa bisikletle göle gidiyorum.', '') },
        { speaker: 'Jan', de: 'Und **wenn** es **regnet**?', translation: l('And if it rains?', 'Peki yağmur yağarsa?', '') },
        { speaker: 'Mira', de: 'Dann **gehe** ich ins Kino. Kommst du mit, **wenn** du Zeit **hast**?', translation: l('Then I’ll go to the cinema. Will you come along if you have time?', 'O zaman sinemaya giderim. Vaktin olursa gelir misin?', '') },
        { speaker: 'Jan', de: 'Ich muss am Samstag arbeiten, **trotzdem komme** ich gern am Sonntag mit.', translation: l('I have to work on Saturday, but I’d still like to come along on Sunday.', 'Cumartesi çalışmam gerekiyor, yine de pazar seve seve gelirim.', '') },
        { speaker: 'Mira', de: 'Super! Am Sonntag ist das Kino billiger, **deshalb ist** es dann aber auch voll.', translation: l('Great! On Sunday the cinema is cheaper, so it’s full then, too.', 'Harika! Pazar günü sinema daha ucuz, bu yüzden o zaman da dolu oluyor.', '') },
        { speaker: 'Jan', de: '**Wenn** du die Karten online **kaufst**, **haben** wir sicher Plätze.', translation: l('If you buy the tickets online, we’ll definitely get seats.', 'Biletleri internetten alırsan kesin yerimiz olur.', '') },
      ],
      examples: [
        { de: '**Wenn** ich Zeit **habe**, **besuche** ich meine Oma.', translation: l('When I have time, I visit my grandma.', 'Vaktim olduğunda büyükannemi ziyaret ederim.', '') },
        { de: 'Ich besuche meine Oma, **wenn** ich Zeit **habe**.', translation: l('I visit my grandma when I have time.', 'Vaktim olduğunda büyükannemi ziyaret ederim.', '') },
        { de: '**Wenn** es kalt **ist**, **trinke** ich Tee.', translation: l('When it’s cold, I drink tea.', 'Hava soğuk olduğunda çay içerim.', '') },
        { de: 'Ich bin krank, **deshalb bleibe** ich im Bett.', translation: l('I’m ill, so I’m staying in bed.', 'Hastayım, bu yüzden yatakta kalıyorum.', '') },
        { de: 'Ich bin krank, **trotzdem gehe** ich zur Arbeit.', translation: l('I’m ill, but I’m still going to work.', 'Hastayım, yine de işe gidiyorum.', '') },
        { de: 'Nimm einen Schirm mit, **falls** es **regnet**.', translation: l('Take an umbrella in case it rains.', 'Yağmur yağarsa diye şemsiye al.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Conditions, consequences, contrasts.', 'Koşullar, sonuçlar, karşıtlıklar.', 'Bedingungen, Folgen, Gegensätze.'),
      exercises: ['match-halves', 'mc-verb-position', 'wenn-zeit', 'wenn-regen', 'sort-deshalb-trotzdem', 'mc-trotzdem', 'tf-deshalb', 'image-wenn', 'wenn-muede'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Make plans – with conditions.', 'Koşullu planlar yap.', 'Mach Pläne – mit Bedingungen.'),
      exercises: [
        'fill-wenn',
        'fill-main',
        'fill-falls',
        'build-wenn-first',
        'build-wenn-second',
        'build-trotzdem',
        'fix-wenn',
        'fix-wenn-end',
        'fix-deshalb',
        'tr-wenn',
        'tr-deshalb',
        'ordering-plan',
        'dialog-wochenende',
        'dialog-trotzdem',
        'wenn-frei',
        'wenn-krank',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Lukas (12) writes about weekends with his family.', 'Lukas (12) ailesiyle geçen hafta sonlarını anlatıyor.', 'Lukas (12) schreibt über Wochenenden.'),
      passage: [
        'Unsere Wochenenden sind immer anders. **Wenn** die Sonne **scheint**, **fahren** wir mit dem Fahrrad an den See.',
        '**Wenn** es **regnet**, **spielen** wir Brettspiele oder gehen ins Museum.',
        'Manchmal muss Papa samstags arbeiten. **Trotzdem macht** er am Abend immer Pizza für uns!',
        'Sonntags haben alle Zeit, **deshalb frühstücken** wir lange – manchmal bis zwölf Uhr.',
      ],
      glossary: [
        { de: 'das Brettspiel', note: l('board game', 'masa oyunu', 'Spiel mit Brett und Figuren') },
        { de: 'samstags', note: l('on Saturdays', 'cumartesileri', 'jeden Samstag') },
        { de: 'frühstücken', note: l('to have breakfast', 'kahvaltı yapmak', 'morgens essen') },
      ],
      exercises: ['read-sonne', 'read-regen', 'read-papa', 'read-sonntag'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Condition, result or contrast?', 'Koşul, sonuç ya da karşıtlık?', 'Bedingung, Folge oder Gegensatz?'),
      exercises: ['listen-wenn', 'listen-trotzdem', 'listen-deshalb', 'listen-falls'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('What do you do when …? Talk about your habits.', '… olduğunda ne yaparsın? Alışkanlıklarından bahset.', 'Was machst du, wenn …? Sprich über deine Gewohnheiten.'),
      points: [
        l('„Wenn ich frei habe, …“', '„Wenn ich frei habe, …“', 'Wenn ich frei habe …'),
        l('„Wenn es regnet, …“', '„Wenn es regnet, …“', 'Wenn es regnet …'),
        l('„Wenn ich gestresst bin, …“', '„Wenn ich gestresst bin, …“', 'Wenn ich gestresst bin …'),
        l('One sentence with deshalb or trotzdem', 'deshalb ya da trotzdem ile bir cümle', 'deshalb / trotzdem'),
      ],
      model: [
        'Wenn ich frei habe, schlafe ich lange und treffe Freunde.',
        'Wenn es regnet, lese ich ein Buch oder sehe Serien.',
        'Wenn ich gestresst bin, gehe ich joggen.',
        'Ich jogge nicht gern im Winter, trotzdem mache ich es.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a message to a friend (at least 5 sentences) about your plans for the weekend – with conditions.',
        'Bir arkadaşına hafta sonu planların hakkında bir mesaj yaz (en az 5 cümle) – koşullarla.',
        'Schreib eine Nachricht (mindestens 5 Sätze) über deine Pläne fürs Wochenende.'
      ),
      minSentences: 5,
      checks: [
        { label: l('A wenn-clause', 'Bir wenn-cümlesi', 'Ein wenn-Satz'), pattern: '\\b[Ww]enn\\b' },
        { label: l('wenn-clause first: „Wenn …, verb …“', 'Önce wenn-cümlesi: „Wenn …, fiil …“', 'Wenn …, Verb …'), pattern: '[Ww]enn [^,.!?]+, \\p{Ll}+ (ich|du|er|sie|es|wir|ihr|man)\\b' },
        { label: l('deshalb or trotzdem', 'deshalb ya da trotzdem', 'deshalb oder trotzdem'), pattern: '\\b([Dd]eshalb|[Tt]rotzdem)\\b' },
      ],
      model: [
        'Hallo Sara, was machst du am Wochenende?',
        'Wenn das Wetter schön ist, fahre ich mit dem Rad an den See.',
        'Wenn es regnet, gehe ich ins Kino.',
        'Am Samstag muss ich arbeiten, trotzdem habe ich am Abend Zeit.',
        'Komm doch mit, wenn du Lust hast!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Verb, comma, verb – 60 seconds.', 'Fiil, virgül, fiil – 60 saniye.', 'Verb, Komma, Verb – 60 Sekunden.'),
      seconds: 60,
      pool: [...WENN_FIRST.map(([id]) => `wenn-${id}`), 'mc-verb-position', 'mc-trotzdem'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('wenn + verb at the end', 'wenn + fiil sonda', 'wenn … Verb am Ende'),
      l('Subordinate clause first → „Wenn …, gehe ich …“ (verb, verb)', 'Önce yan cümle → „Wenn …, gehe ich …“ (fiil, fiil)', 'Verb, Komma, Verb'),
      l('deshalb (so) and trotzdem (still) + verb + subject', 'deshalb (bu yüzden) ve trotzdem (yine de) + fiil + özne', 'deshalb/trotzdem + Verb'),
      l('falls = in case', 'falls = olur da', 'falls'),
    ],
    mistakes: [
      { wrong: 'Wenn ich Zeit habe, ich gehe ins Kino.', right: 'Wenn ich Zeit habe, gehe ich ins Kino.', note: l('Verb, comma, verb.', 'Fiil, virgül, fiil.', 'Verb, Verb.') },
      { wrong: '…, wenn ich habe Zeit.', right: '…, wenn ich Zeit habe.', note: l('wenn → verb at the end.', 'wenn → fiil sonda.', 'Verb am Ende.') },
      { wrong: '…, deshalb ich bleibe zu Hause.', right: '…, deshalb bleibe ich zu Hause.', note: l('deshalb + verb.', 'deshalb + fiil.', 'deshalb + Verb.') },
      { wrong: 'Ich bin krank, deshalb gehe ich zur Arbeit.', right: 'Ich bin krank, trotzdem gehe ich zur Arbeit.', note: l('Unexpected → trotzdem.', 'Beklenmedik → trotzdem.', 'Gegensatz → trotzdem.') },
    ],
  },
}
