import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Ich arbeite als …', emoji: '🧑‍💼', translation: l('I work as a …', '… olarak çalışıyorum', 'Beruf nennen'), example: 'Ich arbeite als Krankenpflegerin.' },
  { word: 'Ich arbeite bei …', emoji: '🏢', translation: l('I work at (company) …', '… şirketinde çalışıyorum', 'Firma nennen'), example: 'Ich arbeite bei Siemens.' },
  { word: 'zuständig für', emoji: '📋', translation: l('responsible for', '…-den sorumlu', 'verantwortlich'), example: 'Ich bin für die Kunden zuständig.' },
  { word: 'die Besprechung', emoji: '🗓️', translation: l('meeting', 'toplantı', 'Meeting'), example: 'Die Besprechung beginnt um zehn.' },
  { word: 'der Termin', emoji: '📅', translation: l('appointment', 'randevu', 'feste Zeit'), example: 'Ich habe um drei einen Termin.' },
  { word: 'Kann ich etwas ausrichten?', emoji: '📝', translation: l('Can I take a message?', 'Bir mesaj iletebilir miyim?', 'Nachricht weitergeben'), example: 'Frau Roth ist nicht da. Kann ich etwas ausrichten?' },
  { word: 'Ich verbinde Sie.', emoji: '🔌', translation: l('I’ll put you through.', 'Sizi bağlıyorum.', 'am Telefon weiterleiten'), example: 'Einen Moment, ich verbinde Sie.' },
  { word: 'zurückrufen', emoji: '📞', translation: l('to call back', 'geri aramak', 'noch einmal anrufen'), example: 'Kann sie mich zurückrufen?' },
  { word: 'Am Apparat.', emoji: '☎️', translation: l('Speaking. (on the phone)', 'Benim. (telefonda)', 'Ich bin am Telefon.'), example: 'Müller am Apparat.' },
  { word: 'Sehr geehrte Damen und Herren,', emoji: '✉️', translation: l('Dear Sir or Madam,', 'Sayın ilgili,', 'formelle Anrede'), example: 'Sehr geehrte Damen und Herren, …' },
  { word: 'Mit freundlichen Grüßen', emoji: '🖊️', translation: l('Yours sincerely', 'Saygılarımla', 'formeller Gruß'), example: 'Mit freundlichen Grüßen, Anna Weber' },
  { word: 'die Kollegin / der Kollege', emoji: '👥', translation: l('colleague', 'iş arkadaşı', 'Mitarbeiter'), example: 'Meine Kollegin hilft mir oft.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Firma', gender: 'f', plural: 'die Firmen', translation: l('company', 'şirket', 'Firma') },
  { word: 'Kunde', gender: 'm', plural: 'die Kunden', translation: l('customer', 'müşteri', 'Kunde') },
  { word: 'Abteilung', gender: 'f', plural: 'die Abteilungen', translation: l('department', 'departman', 'Abteilung') },
  { word: 'Rechnung', gender: 'f', plural: 'die Rechnungen', translation: l('invoice', 'fatura', 'Rechnung') },
  { word: 'Drucker', gender: 'm', plural: 'die Drucker', translation: l('printer', 'yazıcı', 'Drucker') },
  { word: 'Telefonnummer', gender: 'f', plural: 'die Telefonnummern', translation: l('phone number', 'telefon numarası', 'Telefonnummer') },
  { word: 'Nachricht', gender: 'f', plural: 'die Nachrichten', translation: l('message', 'mesaj', 'Nachricht') },
  { word: 'Büro', gender: 'n', plural: 'die Büros', translation: l('office', 'ofis', 'Büro') },
  { word: 'Besprechung', gender: 'f', plural: 'die Besprechungen', translation: l('meeting', 'toplantı', 'Besprechung') },
  { word: 'Termin', gender: 'm', plural: 'die Termine', translation: l('appointment', 'randevu', 'Termin') },
]

/** [id, job (masculine), job (feminine), workplace, task] */
const JOBS: [string, string, string, string, string][] = [
  ['koch', 'Koch', 'Köchin', 'im Restaurant', 'kocht das Essen'],
  ['arzt', 'Arzt', 'Ärztin', 'in der Praxis', 'untersucht Patienten'],
  ['lehrer', 'Lehrer', 'Lehrerin', 'in der Schule', 'unterrichtet Kinder'],
  ['verkaeufer', 'Verkäufer', 'Verkäuferin', 'im Geschäft', 'berät Kunden'],
  ['mechaniker', 'Mechaniker', 'Mechanikerin', 'in der Werkstatt', 'repariert Autos'],
  ['pfleger', 'Krankenpfleger', 'Krankenpflegerin', 'im Krankenhaus', 'pflegt Patienten'],
]

function jobDrills(): Exercise[] {
  return JOBS.map(([id, masc, , place, task], i) => {
    const others = JOBS.filter(([other]) => other !== id)
    const options = [masc, others[i % others.length][1], others[(i + 2) % others.length][1]]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `job-${id}`,
      type: 'multiple_choice' as const,
      topic: 'berufe',
      concept: 'job-task',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `Er arbeitet ${place} und ${task}. Er ist ___.`,
      options: ordered,
      answer: ordered.indexOf(masc),
      explanation: l(`${place}, ${task} → ${masc}.`, `${place}, ${task} → ${masc}.`, `${masc}.`),
      examples: [`Er ist **${masc}**. Er arbeitet ${place}.`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-jobs',
    type: 'matching',
    topic: 'berufe',
    concept: 'job-female',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the masculine and feminine job titles.', 'Eril ve dişil meslek adlarını eşleştir.', 'Ordne die männliche und weibliche Form zu.'),
    pairs: JOBS.slice(0, 5).map(([, m, f]) => ({ left: m, right: f })),
    explanation: l('Feminine: usually -in (Lehrerin), sometimes with umlaut (Ärztin, Köchin).', 'Dişil: genellikle -in (Lehrerin), bazen umlaut ile (Ärztin, Köchin).', 'meist -in, manchmal Umlaut.'),
  },
  {
    id: 'mc-als-bei',
    type: 'multiple_choice',
    topic: 'arbeiten',
    concept: 'als-bei',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich arbeite als Ingenieurin ___ BMW.',
    options: ['bei', 'in', 'als'],
    answer: 0,
    explanation: l('arbeiten als + job (no article!), bei + company, in + place (in einem Büro).', 'arbeiten als + meslek (artikelsiz!), bei + şirket, in + yer (in einem Büro).', 'als + Beruf, bei + Firma.'),
    examples: ['Ich arbeite **als** Ingenieurin **bei** BMW.'],
    practice: ['fill-als'],
  },
  {
    id: 'sort-telefon',
    type: 'categorize',
    topic: 'telefon',
    concept: 'phone-roles',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Who says it: the caller or the person in the office?', 'Kim söylüyor: arayan mı, ofisteki kişi mi?', 'Wer sagt das: Anrufer oder Büro?'),
    categories: ['Anrufer', 'Büro'],
    items: [
      { text: 'Kann ich bitte Frau Roth sprechen?', category: 0 },
      { text: 'Firma Klein, Weber am Apparat.', category: 1 },
      { text: 'Einen Moment, ich verbinde Sie.', category: 1 },
      { text: 'Können Sie ihr etwas ausrichten?', category: 0 },
      { text: 'Sie ist leider in einer Besprechung.', category: 1 },
      { text: 'Sie kann mich unter 0170 … zurückrufen.', category: 0 },
    ],
    explanation: l('The office answers with company + name. The caller asks for someone and leaves a message.', 'Ofis şirket + isimle cevap verir. Arayan birini ister ve mesaj bırakır.', 'Büro: Firma + Name. Anrufer: fragt, hinterlässt Nachricht.'),
  },
  {
    id: 'ordering-telefonat',
    type: 'ordering',
    topic: 'telefon',
    concept: 'phone-flow',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the phone call in order.', 'Telefon görüşmesini sıraya koy.', 'Bring das Telefonat in Ordnung.'),
    items: ['Ja, gern. Sie soll mich bitte zurückrufen.', 'Guten Tag, hier ist Kaya. Kann ich Herrn Lang sprechen?', 'Firma Mayer, Schmidt am Apparat.', 'Herr Lang ist leider nicht da. Kann ich etwas ausrichten?'],
    answer: ['Firma Mayer, Schmidt am Apparat.', 'Guten Tag, hier ist Kaya. Kann ich Herrn Lang sprechen?', 'Herr Lang ist leider nicht da. Kann ich etwas ausrichten?', 'Ja, gern. Sie soll mich bitte zurückrufen.'],
    explanation: l('Answer → ask for someone → not there, message? → leave a message.', 'Cevap → birini iste → burada değil, mesaj? → mesaj bırak.', 'Melden → fragen → nicht da → Nachricht.'),
  },
  {
    id: 'tf-email',
    type: 'true_false',
    topic: 'email',
    concept: 'formal-email',
    skill: 'writing',
    difficulty: 1,
    statement: 'Eine formelle E-Mail endet mit „Mit freundlichen Grüßen“.',
    answer: true,
    explanation: l('Formal: Sehr geehrte/r … – Mit freundlichen Grüßen. Informal: Liebe/r … – Viele Grüße.', 'Resmî: Sehr geehrte/r … – Mit freundlichen Grüßen. Gayriresmî: Liebe/r … – Viele Grüße.', 'formell: Mit freundlichen Grüßen.'),
  },
  {
    id: 'mc-anrede',
    type: 'multiple_choice',
    topic: 'email',
    concept: 'formal-email',
    skill: 'writing',
    difficulty: 2,
    prompt: '___ Herr Wagner, vielen Dank für Ihre E-Mail.',
    options: ['Sehr geehrter', 'Sehr geehrte', 'Lieber'],
    answer: 0,
    explanation: l('Formal + man → Sehr geehrter Herr …; woman → Sehr geehrte Frau …', 'Resmî + erkek → Sehr geehrter Herr …; kadın → Sehr geehrte Frau …', 'Sehr geehrter Herr Wagner.'),
    examples: ['**Sehr geehrter** Herr Wagner, …', '**Sehr geehrte** Frau Roth, …'],
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-als',
    type: 'fill_blank',
    topic: 'arbeiten',
    concept: 'als-bei',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Meine Schwester arbeitet ___ Ärztin in einem Krankenhaus.',
    accepted: ['als'],
    base: 'als / bei',
    explanation: l('Job → als (without article).', 'Meslek → als (artikelsiz).', 'als Ärztin.'),
    examples: ['Sie arbeitet **als** Ärztin.'],
  },
  {
    id: 'fill-zustaendig',
    type: 'fill_blank',
    topic: 'arbeiten',
    concept: 'zustaendig',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Herr Özdemir ist ___ die Rechnungen zuständig.',
    accepted: ['für'],
    base: 'Präposition',
    explanation: l('zuständig für + Akk. = responsible for.', 'zuständig für + Akk. = …-den sorumlu.', 'zuständig für.'),
    examples: ['Er ist **für** die Rechnungen zuständig.'],
  },
  {
    id: 'fill-zurueck',
    type: 'fill_blank',
    topic: 'telefon',
    concept: 'phone-phrases',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Frau Roth ruft Sie heute Nachmittag ___.',
    accepted: ['zurück'],
    base: 'zurück|rufen',
    explanation: l('zurück|rufen is separable: sie ruft … zurück.', 'zurück|rufen ayrılabilen bir fiildir: sie ruft … zurück.', 'ruft … zurück.'),
    examples: ['Frau Roth **ruft** Sie heute Nachmittag **zurück**.'],
  },
  {
    id: 'build-sprechen',
    type: 'sentence_builder',
    topic: 'telefon',
    concept: 'phone-phrases',
    skill: 'grammar',
    difficulty: 1,
    chips: ['sprechen', 'Kann', 'bitte', 'Frau Roth', 'ich'],
    answers: [['Kann', 'ich', 'bitte', 'Frau Roth', 'sprechen']],
    end: '?',
    translation: l('Could I speak to Ms Roth, please?', 'Bayan Roth ile görüşebilir miyim lütfen?', 'Kann ich bitte Frau Roth sprechen?'),
    explanation: l('Polite request on the phone: Kann ich bitte … sprechen?', 'Telefonda kibar rica: Kann ich bitte … sprechen?', 'Kann ich … sprechen?'),
    examples: ['**Kann** ich bitte Frau Roth **sprechen**?'],
  },
  {
    id: 'build-ausrichten',
    type: 'sentence_builder',
    topic: 'telefon',
    concept: 'phone-phrases',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ihm', 'Können', 'etwas', 'Sie', 'ausrichten'],
    answers: [['Können', 'Sie', 'ihm', 'etwas', 'ausrichten']],
    end: '?',
    translation: l('Could you give him a message?', 'Ona bir mesaj iletebilir misiniz?', 'Können Sie ihm etwas ausrichten?'),
    explanation: l('ausrichten + Dativ person: ihm.', 'ausrichten + Dativ kişi: ihm.', 'ihm etwas ausrichten.'),
    examples: ['Können Sie **ihm** etwas **ausrichten**?'],
  },
  {
    id: 'build-besprechung',
    type: 'sentence_builder',
    topic: 'arbeiten',
    concept: 'office-life',
    skill: 'grammar',
    difficulty: 2,
    chips: ['in einer Besprechung', 'ist', 'Sie', 'gerade', 'leider'],
    answers: [['Sie', 'ist', 'leider', 'gerade', 'in einer Besprechung'], ['Sie', 'ist', 'gerade', 'leider', 'in einer Besprechung']],
    translation: l('Unfortunately she’s in a meeting right now.', 'Maalesef şu anda toplantıda.', 'Sie ist leider gerade in einer Besprechung.'),
    explanation: l('Verb in position 2, adverbs before the place.', 'Fiil 2. sırada, zarflar yerden önce.', 'Sie ist leider gerade …'),
    examples: ['Sie ist leider gerade **in einer Besprechung**.'],
  },
  {
    id: 'fix-als-ein',
    type: 'error_correction',
    topic: 'arbeiten',
    concept: 'als-bei',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich arbeite als ein Programmierer.',
    accepted: ['Ich arbeite als Programmierer.'],
    explanation: l('No article after als: als Programmierer.', 'als’tan sonra artikel yok: als Programmierer.', 'als Programmierer.'),
    examples: ['Ich arbeite **als** Programmierer.'],
  },
  {
    id: 'fix-bei',
    type: 'error_correction',
    topic: 'arbeiten',
    concept: 'als-bei',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Er arbeitet in Bosch.',
    accepted: ['Er arbeitet bei Bosch.'],
    explanation: l('Company → bei: bei Bosch.', 'Şirket → bei: bei Bosch.', 'bei Bosch.'),
    examples: ['Er arbeitet **bei** Bosch.'],
  },
  {
    id: 'fix-gruss',
    type: 'error_correction',
    topic: 'email',
    concept: 'formal-email',
    skill: 'writing',
    difficulty: 2,
    sentence: 'Mit freundliche Grüße',
    accepted: ['Mit freundlichen Grüßen'],
    explanation: l('mit + Dativ plural: mit freundlichen Grüßen.', 'mit + Dativ çoğul: mit freundlichen Grüßen.', 'Mit freundlichen Grüßen.'),
    examples: ['**Mit freundlichen Grüßen**'],
  },
  {
    id: 'tr-arbeite',
    type: 'translation',
    topic: 'arbeiten',
    concept: 'als-bei',
    skill: 'writing',
    difficulty: 2,
    source: l('I work as a cook in a hotel.', 'Bir otelde aşçı olarak çalışıyorum.', 'I work as a cook in a hotel.'),
    accepted: ['Ich arbeite als Koch in einem Hotel.', 'Ich arbeite als Köchin in einem Hotel.'],
    explanation: l('als + job, in + Dativ.', 'als + meslek, in + Dativ.', 'als Koch in einem Hotel.'),
    examples: ['Ich arbeite **als** Koch **in einem** Hotel.'],
  },
  {
    id: 'tr-verbinde',
    type: 'translation',
    topic: 'telefon',
    concept: 'phone-phrases',
    skill: 'writing',
    difficulty: 1,
    source: l('One moment, I’ll put you through.', 'Bir dakika, sizi bağlıyorum.', 'One moment, I’ll put you through.'),
    accepted: ['Einen Moment, ich verbinde Sie.', 'Einen Moment bitte, ich verbinde Sie.', 'Moment, ich verbinde Sie.'],
    explanation: l('Einen Moment, ich verbinde Sie.', 'Einen Moment, ich verbinde Sie.', 'Ich verbinde Sie.'),
    examples: ['Einen Moment, ich **verbinde** Sie.'],
  },
  {
    id: 'dialog-telefon',
    type: 'dialogue',
    topic: 'telefon',
    concept: 'phone-flow',
    skill: 'speaking',
    difficulty: 1,
    lines: [
      { speaker: 'Büro', de: 'Firma Klein, Weber am Apparat. Guten Tag!' },
    ],
    options: ['Guten Tag, hier ist Aydın. Kann ich bitte Herrn Klein sprechen?', 'Hallo, wer bist du?', 'Ich bin Herr Klein sprechen.'],
    answer: 0,
    explanation: l('Greet, say your name, ask for the person.', 'Selamla, adını söyle, kişiyi iste.', 'Gruß + Name + Bitte.'),
  },
  {
    id: 'dialog-nachricht',
    type: 'dialogue',
    topic: 'telefon',
    concept: 'phone-flow',
    skill: 'speaking',
    difficulty: 2,
    lines: [
      { speaker: 'Büro', de: 'Herr Klein ist leider nicht im Büro. Kann ich etwas ausrichten?' },
    ],
    options: ['Ja, bitte. Er soll mich zurückrufen. Meine Nummer ist 0151 223344.', 'Nein, ich richte nichts.', 'Ja, ich rufe ihn zurück aus.'],
    answer: 0,
    explanation: l('Leave a message: who should call back + your number.', 'Mesaj bırak: kim geri arasın + numaran.', 'Rückruf + Nummer.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-beruf',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-notiz',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wer hat angerufen?',
    options: ['Herr Petrović von der Firma Baumann.', 'Frau Roth.', 'Ein Kunde aus Berlin.'],
    answer: 0,
    explanation: l('„Herr Petrović von der Firma Baumann hat um 10:15 Uhr angerufen.“', '„Herr Petrović von der Firma Baumann hat um 10:15 Uhr angerufen.“', '„Herr Petrović“'),
  },
  {
    id: 'read-grund',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-notiz',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum hat er angerufen?',
    options: ['Eine Rechnung ist falsch.', 'Er möchte einen Termin.', 'Der Drucker ist kaputt.'],
    answer: 0,
    explanation: l('„Die Rechnung vom 3. März ist leider falsch.“', '„Die Rechnung vom 3. März ist leider falsch.“', '„Rechnung … falsch“'),
  },
  {
    id: 'read-rueckruf',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-notiz',
    skill: 'reading',
    difficulty: 2,
    statement: 'Frau Roth soll ihn heute vor 16 Uhr zurückrufen.',
    answer: true,
    explanation: l('„Bitte heute bis 16 Uhr zurückrufen.“', '„Bitte heute bis 16 Uhr zurückrufen.“', '„bis 16 Uhr“'),
  },
  {
    id: 'read-nummer',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-notiz',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wo ist er erreichbar?',
    options: ['Unter 0221 456 78 90.', 'Per E-Mail.', 'Gar nicht.'],
    answer: 0,
    explanation: l('„Tel.: 0221 456 78 90“', '„Tel.: 0221 456 78 90“', '„0221 …“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-wer',
    type: 'listening_choice',
    topic: 'telefon',
    concept: 'phone-phrases',
    skill: 'listening',
    difficulty: 1,
    audio: 'Autohaus Becker, Sie sprechen mit Julia Wolf. Was kann ich für Sie tun?',
    question: l('Who answers the phone?', 'Telefonu kim açıyor?', 'Wer meldet sich?'),
    options: ['Julia Wolf vom Autohaus Becker', 'Herr Becker', 'eine Kundin'],
    answer: 0,
    explanation: l('Company + name: Autohaus Becker, Julia Wolf.', 'Şirket + isim: Autohaus Becker, Julia Wolf.', 'Julia Wolf.'),
  },
  {
    id: 'listen-besprechung',
    type: 'listening_choice',
    topic: 'telefon',
    concept: 'phone-flow',
    skill: 'listening',
    difficulty: 2,
    audio: 'Herr Graf ist bis elf Uhr in einer Besprechung. Soll er Sie zurückrufen?',
    question: l('Why can’t Mr Graf speak?', 'Bay Graf neden konuşamıyor?', 'Warum kann Herr Graf nicht sprechen?'),
    options: ['Er ist in einer Besprechung.', 'Er ist krank.', 'Er ist im Urlaub.'],
    answer: 0,
    explanation: l('„in einer Besprechung“ = in a meeting.', '„in einer Besprechung“ = toplantıda.', 'Besprechung.'),
  },
  {
    id: 'listen-beruf',
    type: 'listening_choice',
    topic: 'berufe',
    concept: 'job-task',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich arbeite in einer Werkstatt und repariere jeden Tag Autos.',
    question: l('What’s the person’s job?', 'Kişinin mesleği ne?', 'Was ist die Person von Beruf?'),
    options: ['🔧 Mechaniker', '👨‍🍳 Koch', '👨‍🏫 Lehrer'],
    answer: 0,
    explanation: l('Werkstatt + Autos reparieren → Mechaniker.', 'Atölye + araba tamiri → tamirci.', 'Mechaniker.'),
  },
  {
    id: 'listen-nummer',
    type: 'listening_choice',
    topic: 'telefon',
    concept: 'phone-number',
    skill: 'listening',
    difficulty: 2,
    audio: 'Meine Nummer ist null eins sieben null, drei vier fünf, sechs sieben acht.',
    question: l('Which number?', 'Hangi numara?', 'Welche Nummer?'),
    options: ['0170 345 678', '0170 354 687', '0107 345 678'],
    answer: 0,
    explanation: l('null eins sieben null – drei vier fünf – sechs sieben acht.', 'sıfır bir yedi sıfır – üç dört beş – altı yedi sekiz.', '0170 345 678.'),
  },

  ...jobDrills(),
]

export const UNIT_A2_12_BERUF_ARBEIT: CourseUnit = {
  level: 'A2',
  number: 12,
  slug: 'beruf-arbeit',
  titleDe: 'Im Büro',
  title: l('At the office', 'Ofiste', 'Im Büro'),
  goal: l(
    'By the end of this unit you can talk about jobs and tasks (Ich arbeite als … bei …), make and answer a work phone call, leave a message and write a short formal e-mail.',
    'Bu ünitenin sonunda meslekler ve görevler hakkında konuşabilir (Ich arbeite als … bei …), iş telefonu açıp cevaplayabilir, mesaj bırakabilir ve kısa resmî bir e-posta yazabilirsin.',
    'Am Ende dieser Einheit sprichst du über Berufe, telefonierst im Büro und schreibst eine formelle E-Mail.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'berufe', label: l('Jobs', 'Meslekler', 'Berufe') },
    { key: 'arbeiten', label: l('als / bei / zuständig für', 'als / bei / zuständig für', 'als / bei / zuständig für') },
    { key: 'telefon', label: l('On the phone', 'Telefonda', 'Am Telefon') },
    { key: 'email', label: l('Formal e-mail', 'Resmî e-posta', 'Formelle E-Mail') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Phrases you hear every day at work.', 'İşte her gün duyduğun ifadeler.', 'Sätze aus dem Arbeitsalltag.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Talking about your job', 'Mesleğinden bahsetmek', 'Über den Beruf sprechen'),
          body: l(
            'Ich bin Lehrerin. / Ich arbeite als Lehrerin. (no article!) – bei + company: bei Siemens – in/an + place: in einer Schule, an der Uni – zuständig für + Akk.: für die Kunden.',
            'Ich bin Lehrerin. / Ich arbeite als Lehrerin. (artikelsiz!) – bei + şirket: bei Siemens – in/an + yer: in einer Schule, an der Uni – zuständig für + Akk.: für die Kunden.',
            'als + Beruf · bei + Firma · zuständig für.'
          ),
          table: {
            head: [l('Question', 'Soru', 'Frage'), l('Answer', 'Cevap', 'Antwort')],
            rows: [
              ['Was sind Sie von Beruf?', 'Ich bin Koch.'],
              ['Als was arbeiten Sie?', 'Ich arbeite als Koch.'],
              ['Wo arbeiten Sie?', 'Bei Hotel Adler / in einem Hotel.'],
              ['Wofür sind Sie zuständig?', 'Für die Küche und die Bestellungen.'],
            ],
          },
        },
        {
          title: l('On the phone', 'Telefonda', 'Am Telefon'),
          body: l(
            'Answering: Firma …, Name (am Apparat). Asking: Kann ich bitte … sprechen? Not there: … ist leider nicht da / in einer Besprechung. Message: Kann ich etwas ausrichten? – Er/Sie soll mich bitte zurückrufen.',
            'Cevap verme: Firma …, isim (am Apparat). Rica: Kann ich bitte … sprechen? Yok: … ist leider nicht da / in einer Besprechung. Mesaj: Kann ich etwas ausrichten? – Er/Sie soll mich bitte zurückrufen.',
            'Melden – fragen – ausrichten – zurückrufen.'
          ),
        },
        {
          title: l('Formal e-mails', 'Resmî e-postalar', 'Formelle E-Mails'),
          body: l(
            'Sehr geehrte Frau Roth, / Sehr geehrter Herr Lang, / Sehr geehrte Damen und Herren, … Mit freundlichen Grüßen. Always Sie/Ihnen/Ihr (capital!).',
            'Sehr geehrte Frau Roth, / Sehr geehrter Herr Lang, / Sehr geehrte Damen und Herren, … Mit freundlichen Grüßen. Her zaman Sie/Ihnen/Ihr (büyük harfle!).',
            'Sehr geehrte … – Mit freundlichen Grüßen.'
          ),
          tip: l('After the comma in the greeting, continue with a small letter: „Sehr geehrte Frau Roth, vielen Dank …“', 'Hitaptaki virgülden sonra küçük harfle devam et: „Sehr geehrte Frau Roth, vielen Dank …“', 'Nach dem Komma klein weiter.'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Simulation: You call a company. Ms Roth is not available.', 'Simülasyon: Bir şirketi arıyorsun. Bayan Roth müsait değil.', 'Simulation: Ein Anruf in der Firma.'),
      dialogue: [
        { speaker: 'Empfang', de: 'Firma Baumann, Schmidt **am Apparat**. Guten Tag!', translation: l('Baumann company, Schmidt speaking. Good afternoon!', 'Baumann şirketi, Schmidt. İyi günler!', '') },
        { speaker: 'Du', de: 'Guten Tag, hier ist Petrović. **Kann ich bitte** Frau Roth **sprechen**?', translation: l('Hello, this is Petrović. Could I speak to Ms Roth, please?', 'İyi günler, ben Petrović. Bayan Roth ile görüşebilir miyim?', '') },
        { speaker: 'Empfang', de: 'Einen Moment, **ich verbinde Sie** … Oh, sie ist leider **in einer Besprechung**.', translation: l('One moment, I’ll put you through … Oh, unfortunately she’s in a meeting.', 'Bir dakika, sizi bağlıyorum … Ah, maalesef toplantıda.', '') },
        { speaker: 'Du', de: 'Schade. Wann ist sie wieder erreichbar?', translation: l('Pity. When can I reach her again?', 'Yazık. Ne zaman tekrar ulaşılabilir?', '') },
        { speaker: 'Empfang', de: 'Ab 14 Uhr. **Kann ich etwas ausrichten?**', translation: l('From 2 pm. Can I take a message?', 'Saat 14’ten itibaren. Bir mesaj iletebilir miyim?', '') },
        { speaker: 'Du', de: 'Ja, bitte. Es geht um die Rechnung vom 3. März. Sie soll mich bitte **zurückrufen**.', translation: l('Yes, please. It’s about the invoice from 3 March. Could she call me back, please?', 'Evet, lütfen. 3 Mart tarihli fatura hakkında. Beni geri arasın lütfen.', '') },
        { speaker: 'Empfang', de: 'Gern. Wie ist Ihre Telefonnummer?', translation: l('Of course. What’s your phone number?', 'Elbette. Telefon numaranız nedir?', '') },
        { speaker: 'Du', de: '0221 456 78 90. Vielen Dank und auf Wiederhören!', translation: l('0221 456 78 90. Thank you and goodbye!', '0221 456 78 90. Çok teşekkürler, hoşça kalın!', '') },
      ],
      examples: [
        { de: 'Ich arbeite **als** Verkäuferin **bei** H&M.', translation: l('I work as a shop assistant at H&M.', 'H&M’de satış elemanı olarak çalışıyorum.', '') },
        { de: 'Ich bin **für** die Kunden **zuständig**.', translation: l('I’m responsible for the customers.', 'Müşterilerden sorumluyum.', '') },
        { de: 'Kann ich bitte Herrn Lang **sprechen**?', translation: l('Could I speak to Mr Lang, please?', 'Bay Lang ile görüşebilir miyim?', '') },
        { de: 'Er ist leider **nicht da**.', translation: l('Unfortunately he isn’t here.', 'Maalesef burada değil.', '') },
        { de: 'Kann ich etwas **ausrichten**?', translation: l('Can I take a message?', 'Bir mesaj iletebilir miyim?', '') },
        { de: 'Er soll mich bitte **zurückrufen**.', translation: l('Could he call me back, please?', 'Beni geri arasın lütfen.', '') },
        { de: '**Auf Wiederhören!**', translation: l('Goodbye! (on the phone)', 'Hoşça kalın! (telefonda)', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Jobs, phone phrases, e-mail.', 'Meslekler, telefon ifadeleri, e-posta.', 'Berufe, Telefon, E-Mail.'),
      exercises: ['match-jobs', 'job-koch', 'job-arzt', 'mc-als-bei', 'sort-telefon', 'ordering-telefonat', 'tf-email', 'mc-anrede', 'job-mechaniker'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Simulation · On the phone', 'Simülasyon · Telefonda', 'Simulation · Am Telefon'),
      intro: l('Make the call yourself.', 'Aramayı kendin yap.', 'Telefoniere selbst.'),
      exercises: [
        'dialog-telefon',
        'build-sprechen',
        'build-besprechung',
        'dialog-nachricht',
        'build-ausrichten',
        'fill-zurueck',
        'tr-verbinde',
      ],
    },
    {
      key: 'practice-use-2',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about your work.', 'İşinden bahset.', 'Sprich über deine Arbeit.'),
      exercises: ['fill-als', 'fill-zustaendig', 'fix-als-ein', 'fix-bei', 'fix-gruss', 'tr-arbeite', 'job-lehrer', 'job-verkaeufer', 'job-pfleger'],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A phone note on Ms Roth’s desk.', 'Bayan Roth’un masasındaki telefon notu.', 'Eine Telefonnotiz.'),
      passage: [
        '**Telefonnotiz** – für: Frau Roth, Buchhaltung',
        'Herr Petrović von der Firma Baumann hat um 10:15 Uhr angerufen.',
        'Es geht um die Rechnung vom 3. März. Die Rechnung ist leider falsch – der Preis stimmt nicht.',
        'Bitte heute bis 16 Uhr zurückrufen. Tel.: 0221 456 78 90. – J. Schmidt, Empfang',
      ],
      glossary: [
        { de: 'die Buchhaltung', note: l('accounting', 'muhasebe', 'Finanzabteilung') },
        { de: 'es geht um', note: l('it’s about', 'konu …', 'das Thema ist') },
        { de: 'stimmt nicht', note: l('isn’t correct', 'doğru değil', 'ist falsch') },
        { de: 'der Empfang', note: l('reception', 'resepsiyon', 'Rezeption') },
      ],
      exercises: ['read-beruf', 'read-grund', 'read-rueckruf', 'read-nummer'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Phone calls and jobs.', 'Telefon görüşmeleri ve meslekler.', 'Telefonate und Berufe.'),
      exercises: ['listen-wer', 'listen-besprechung', 'listen-beruf', 'listen-nummer'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Role play: call a company and ask for Mr Lang. He isn’t there – leave a message.', 'Rol oyunu: bir şirketi ara ve Bay Lang’ı iste. Burada değil – mesaj bırak.', 'Rollenspiel: Anruf, Herr Lang ist nicht da.'),
      points: [
        l('Greet and say your name', 'Selamla ve adını söyle', 'Begrüßung + Name'),
        l('Ask for Mr Lang', 'Bay Lang’ı iste', 'Nach Herrn Lang fragen'),
        l('Say what it is about: „Es geht um …“', 'Konuyu söyle: „Es geht um …“', '„Es geht um …“'),
        l('Ask for a call back and give your number', 'Geri aranmayı iste ve numaranı ver', 'Rückruf + Nummer'),
        l('Say goodbye: „Auf Wiederhören!“', 'Vedalaş: „Auf Wiederhören!“', 'Auf Wiederhören!'),
      ],
      model: [
        'Guten Tag, hier ist Selin Arslan.',
        'Kann ich bitte Herrn Lang sprechen?',
        'Ach so, er ist nicht da. Können Sie ihm etwas ausrichten?',
        'Es geht um meinen Termin am Freitag.',
        'Er soll mich bitte zurückrufen. Meine Nummer ist 0176 123 456.',
        'Vielen Dank, auf Wiederhören!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short formal e-mail (at least 4 sentences) to Ms Roth: you can’t come to the meeting on Monday. Give a reason and suggest another date.',
        'Bayan Roth’a kısa ve resmî bir e-posta yaz (en az 4 cümle): pazartesi toplantıya gelemiyorsun. Bir sebep belirt ve başka bir tarih öner.',
        'Schreib eine formelle E-Mail (mindestens 4 Sätze) an Frau Roth: Du kannst nicht zur Besprechung kommen.'
      ),
      minSentences: 4,
      checks: [
        { label: l('Formal greeting (Sehr geehrte/r …)', 'Resmî hitap (Sehr geehrte/r …)', 'Formelle Anrede'), pattern: 'Sehr geehrte(r)? ' },
        { label: l('A reason (weil / denn / leider)', 'Bir sebep (weil / denn / leider)', 'Ein Grund'), pattern: '\\b(weil|denn|leider)\\b' },
        { label: l('Formal closing (Mit freundlichen Grüßen)', 'Resmî kapanış (Mit freundlichen Grüßen)', 'Formeller Gruß'), pattern: 'Mit freundlichen Grüßen' },
        { label: l('Polite Sie/Ihnen (capital)', 'Kibar Sie/Ihnen (büyük harf)', 'Sie/Ihnen groß'), pattern: '\\b(Sie|Ihnen|Ihr|Ihre)\\b' },
      ],
      model: [
        'Sehr geehrte Frau Roth, leider kann ich am Montag nicht zur Besprechung kommen.',
        'Ich habe an diesem Tag einen Arzttermin.',
        'Passt Ihnen vielleicht Dienstag um 10 Uhr?',
        'Ich freue mich auf Ihre Antwort.',
        'Mit freundlichen Grüßen, Ahmet Kaya',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Which job? – 60 seconds.', 'Hangi meslek? – 60 saniye.', 'Welcher Beruf? – 60 Sekunden.'),
      seconds: 60,
      pool: [...JOBS.map(([id]) => `job-${id}`), 'mc-als-bei', 'mc-anrede'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Ich arbeite als … (no article) bei … / in …', 'Ich arbeite als … (artikelsiz) bei … / in …', 'als / bei / in'),
      l('Phone: am Apparat, Kann ich … sprechen?, ausrichten, zurückrufen', 'Telefon: am Apparat, Kann ich … sprechen?, ausrichten, zurückrufen', 'Telefon'),
      l('Formal e-mail: Sehr geehrte … – Mit freundlichen Grüßen', 'Resmî e-posta: Sehr geehrte … – Mit freundlichen Grüßen', 'formelle E-Mail'),
      l('Jobs: -in for women (Lehrerin, Ärztin)', 'Meslekler: kadınlar için -in (Lehrerin, Ärztin)', '-in'),
    ],
    mistakes: [
      { wrong: 'Ich arbeite als ein Lehrer.', right: 'Ich arbeite als Lehrer.', note: l('No article after als.', 'als’tan sonra artikel yok.', 'kein Artikel.') },
      { wrong: 'Ich arbeite in Siemens.', right: 'Ich arbeite bei Siemens.', note: l('Company → bei.', 'Şirket → bei.', 'bei.') },
      { wrong: 'Sehr geehrte Herr Lang,', right: 'Sehr geehrter Herr Lang,', note: l('Man → geehrter.', 'Erkek → geehrter.', 'geehrter.') },
      { wrong: 'Er soll mich zurückanrufen.', right: 'Er soll mich zurückrufen.', note: l('zurückrufen – no „an“.', 'zurückrufen – „an“ yok.', 'zurückrufen.') },
    ],
  },
}
