import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'sich waschen', emoji: '🧼', translation: l('to wash (oneself)', 'yıkanmak', 'sich sauber machen'), example: 'Ich wasche mich jeden Morgen.' },
  { word: 'sich duschen', emoji: '🚿', translation: l('to take a shower', 'duş almak', 'unter der Dusche'), example: 'Er duscht sich nach dem Sport.' },
  { word: 'sich anziehen', emoji: '👕', translation: l('to get dressed', 'giyinmek', 'Kleidung anziehen'), example: 'Die Kinder ziehen sich schnell an.' },
  { word: 'sich ausziehen', emoji: '🧦', translation: l('to get undressed', 'soyunmak', 'Kleidung ausziehen'), example: 'Ich ziehe mich aus und gehe ins Bett.' },
  { word: 'sich kämmen', emoji: '🪮', translation: l('to comb one’s hair', 'saç taramak', 'die Haare kämmen'), example: 'Sie kämmt sich vor dem Spiegel.' },
  { word: 'sich beeilen', emoji: '🏃', translation: l('to hurry', 'acele etmek', 'schnell machen'), example: 'Beeil dich, der Bus kommt!' },
  { word: 'sich freuen', emoji: '😄', translation: l('to be happy, glad', 'sevinmek', 'froh sein'), example: 'Ich freue mich über dein Geschenk.' },
  { word: 'sich ärgern', emoji: '😠', translation: l('to be annoyed', 'sinirlenmek', 'böse sein'), example: 'Er ärgert sich über den Stau.' },
  { word: 'sich ausruhen', emoji: '🛋️', translation: l('to rest', 'dinlenmek', 'Pause machen'), example: 'Am Sonntag ruhe ich mich aus.' },
  { word: 'sich fühlen', emoji: '🙂', translation: l('to feel', 'kendini hissetmek', 'Gefühl'), example: 'Wie fühlst du dich heute?' },
  { word: 'sich treffen', emoji: '🤝', translation: l('to meet (each other)', 'buluşmak', 'zusammenkommen'), example: 'Wir treffen uns um acht.' },
  { word: 'sich setzen', emoji: '🪑', translation: l('to sit down', 'oturmak (oturmaya geçmek)', 'Platz nehmen'), example: 'Bitte setzen Sie sich!' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Spiegel', gender: 'm', plural: 'die Spiegel', translation: l('mirror', 'ayna', 'Spiegel') },
  { word: 'Zahnbürste', gender: 'f', plural: 'die Zahnbürsten', translation: l('toothbrush', 'diş fırçası', 'Zahnbürste') },
  { word: 'Handtuch', gender: 'n', plural: 'die Handtücher', translation: l('towel', 'havlu', 'Handtuch') },
  { word: 'Morgen', gender: 'm', plural: 'die Morgen', translation: l('morning', 'sabah', 'Morgen') },
  { word: 'Stau', gender: 'm', plural: 'die Staus', translation: l('traffic jam', 'trafik sıkışıklığı', 'Stau') },
  { word: 'Dusche', gender: 'f', plural: 'die Duschen', translation: l('shower', 'duş', 'Dusche') },
]

const REFLEXIVE: Record<string, string> = { ich: 'mich', du: 'dich', er: 'sich', sie: 'sich', wir: 'uns', ihr: 'euch', 'sie (Pl.)': 'sich', Sie: 'sich' }

/** [id, sentence with ___ for the pronoun, person, distractors] */
const PRONOUN_DRILLS: [string, string, string, [string, string]][] = [
  ['ich', 'Ich wasche ___ jeden Morgen.', 'ich', ['mir', 'sich']],
  ['du', 'Warum beeilst du ___ nicht?', 'du', ['dir', 'sich']],
  ['er', 'Mein Bruder rasiert ___ jeden Tag.', 'er', ['ihn', 'ihm']],
  ['wir', 'Wir treffen ___ vor dem Kino.', 'wir', ['sich', 'unser']],
  ['ihr', 'Freut ihr ___ auf die Ferien?', 'ihr', ['sich', 'euer']],
  ['sie-pl', 'Die Kinder ziehen ___ an.', 'sie (Pl.)', ['ihnen', 'sie']],
  ['Sie', 'Bitte setzen Sie ___!', 'Sie', ['Ihnen', 'Sie']],
]

function pronounDrills(): Exercise[] {
  return PRONOUN_DRILLS.map(([id, sentence, person, wrong], i) => {
    const right = REFLEXIVE[person]
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `refl-${id}`,
      type: 'multiple_choice' as const,
      topic: 'pronouns',
      concept: `refl-${id}`,
      skill: 'grammar' as const,
      difficulty: 1 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `${person} → reflexive pronoun: ${right}.${right === 'sich' ? ' er/sie/es/sie/Sie all use sich.' : ''}`,
        `${person} → dönüşlü zamir: ${right}.${right === 'sich' ? ' er/sie/es/sie/Sie hepsi sich kullanır.' : ''}`,
        `${person} → ${right}.`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-pronouns',
    type: 'matching',
    topic: 'pronouns',
    concept: 'refl-table',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Match person and reflexive pronoun.', 'Kişiyi ve dönüşlü zamiri eşleştir.', 'Ordne Person und Reflexivpronomen zu.'),
    pairs: [
      { left: 'ich', right: 'mich' },
      { left: 'du', right: 'dich' },
      { left: 'er / sie / es', right: 'sich' },
      { left: 'wir', right: 'uns' },
      { left: 'ihr', right: 'euch' },
    ],
    explanation: l('mich, dich, sich, uns, euch, sich. Only the 3rd person and Sie are new: sich.', 'mich, dich, sich, uns, euch, sich. Yalnızca 3. kişi ve Sie yenidir: sich.', 'mich, dich, sich, uns, euch, sich.'),
    practice: ['refl-ich', 'refl-er'],
  },
  {
    id: 'image-routine',
    type: 'image_choice',
    topic: 'routine',
    concept: 'routine-verbs',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Er kämmt sich.',
    options: [
      { emoji: '🪮', label: 'kämmen' },
      { emoji: '🚿', label: 'duschen' },
      { emoji: '🪒', label: 'rasieren' },
      { emoji: '👔', label: 'anziehen' },
    ],
    answer: 0,
    explanation: l('sich kämmen = to comb one’s hair 🪮.', 'sich kämmen = saç taramak 🪮.', 'sich kämmen.'),
  },
  {
    id: 'ordering-morgen',
    type: 'ordering',
    topic: 'routine',
    concept: 'routine-order',
    skill: 'reading',
    difficulty: 1,
    promptL10n: l('Put the morning routine in a logical order.', 'Sabah rutinini mantıklı bir sıraya koy.', 'Bring die Morgenroutine in eine logische Reihenfolge.'),
    items: ['Ich ziehe mich an.', 'Ich stehe auf.', 'Ich beeile mich zum Bus.', 'Ich dusche mich.'],
    answer: ['Ich stehe auf.', 'Ich dusche mich.', 'Ich ziehe mich an.', 'Ich beeile mich zum Bus.'],
    explanation: l('aufstehen → duschen → anziehen → zum Bus.', 'kalkmak → duş → giyinmek → otobüse.', 'aufstehen, duschen, anziehen, Bus.'),
  },
  {
    id: 'sort-reflexive',
    type: 'categorize',
    topic: 'pronouns',
    concept: 'reflexive-or-not',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Is the action done to oneself or to someone else?', 'Eylem kişinin kendisine mi, başkasına mı yapılıyor?', 'Für sich selbst oder für jemand anderen?'),
    categories: ['sich selbst', 'jemand anderen'],
    items: [
      { text: 'Ich wasche mich.', category: 0 },
      { text: 'Ich wasche das Auto.', category: 1 },
      { text: 'Sie zieht sich an.', category: 0 },
      { text: 'Sie zieht das Baby an.', category: 1 },
      { text: 'Er ärgert sich.', category: 0 },
      { text: 'Er ärgert seine Schwester.', category: 1 },
    ],
    explanation: l('With mich/dich/sich the action goes back to the subject. With another object it doesn’t.', 'mich/dich/sich ile eylem özneye geri döner. Başka bir nesneyle dönmez.', 'Reflexiv = zurück zum Subjekt.'),
  },
  {
    id: 'mc-sich',
    type: 'multiple_choice',
    topic: 'pronouns',
    concept: 'refl-sie',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Frau Klein freut ___ über die Blumen.',
    options: ['sich', 'ihr', 'sie'],
    answer: 0,
    explanation: l('3rd person (er/sie/es) → sich.', '3. kişi (er/sie/es) → sich.', 'sie → sich.'),
    examples: ['Frau Klein freut **sich** über die Blumen.'],
  },
  {
    id: 'tf-mir',
    type: 'true_false',
    topic: 'dativ-reflexive',
    concept: 'mir-haende',
    skill: 'grammar',
    difficulty: 3,
    statement: '„Ich wasche mir die Hände“ ist richtig.',
    answer: true,
    explanation: l(
      'If there is another object (die Hände), the reflexive pronoun is Dativ: ich wasche mir die Hände, du putzt dir die Zähne.',
      'Başka bir nesne varsa (die Hände), dönüşlü zamir Dativ olur: ich wasche mir die Hände, du putzt dir die Zähne.',
      'Mit Objekt: mir/dir.'
    ),
    examples: ['Ich wasche **mir** die Hände.', 'Putz **dir** die Zähne!'],
  },
  {
    id: 'select-reflexive',
    type: 'multiple_select',
    topic: 'routine',
    concept: 'routine-verbs',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which verbs are reflexive (with sich)? Select all.', 'Hangi fiiller dönüşlü (sich ile)? Hepsini seç.', 'Welche Verben sind reflexiv? Wähle alle.'),
    options: ['sich beeilen', 'frühstücken', 'sich freuen', 'schlafen', 'sich ausruhen', 'arbeiten'],
    answers: [0, 2, 4],
    explanation: l('sich beeilen, sich freuen, sich ausruhen. Learn the sich with the verb!', 'sich beeilen, sich freuen, sich ausruhen. sich’i fiille birlikte öğren!', 'sich beeilen, sich freuen, sich ausruhen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-mich',
    type: 'fill_blank',
    topic: 'pronouns',
    concept: 'refl-ich',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Nach der Arbeit ruhe ich ___ aus.',
    accepted: ['mich'],
    base: 'ich',
    explanation: l('ich → mich. aus|ruhen is also separable: ruhe … aus.', 'ich → mich. aus|ruhen ayrılabilen bir fiildir: ruhe … aus.', 'ruhe mich aus.'),
    examples: ['Nach der Arbeit ruhe ich **mich** aus.'],
  },
  {
    id: 'fill-uns',
    type: 'fill_blank',
    topic: 'pronouns',
    concept: 'refl-wir',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Am Samstag treffen wir ___ im Park.',
    accepted: ['uns'],
    base: 'wir',
    explanation: l('wir → uns.', 'wir → uns.', 'wir → uns.'),
    examples: ['Am Samstag treffen wir **uns** im Park.'],
  },
  {
    id: 'fill-dir',
    type: 'fill_blank',
    topic: 'dativ-reflexive',
    concept: 'mir-haende',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Putz ___ bitte die Zähne!',
    accepted: ['dir'],
    base: 'du',
    explanation: l('Another object (die Zähne) → Dativ reflexive: dir.', 'Başka bir nesne (die Zähne) → Dativ dönüşlü: dir.', 'Putz dir die Zähne!'),
    examples: ['Putz **dir** bitte die Zähne!'],
  },
  {
    id: 'build-freue',
    type: 'sentence_builder',
    topic: 'pronouns',
    concept: 'refl-ich',
    skill: 'grammar',
    difficulty: 2,
    chips: ['auf', 'freue', 'Ich', 'den Urlaub', 'mich'],
    answers: [['Ich', 'freue', 'mich', 'auf', 'den Urlaub']],
    translation: l('I’m looking forward to the holiday.', 'Tatili dört gözle bekliyorum.', 'Ich freue mich auf den Urlaub.'),
    explanation: l('The reflexive pronoun comes right after the verb.', 'Dönüşlü zamir fiilden hemen sonra gelir.', 'Verb + mich.'),
    examples: ['Ich freue **mich** auf den Urlaub.'],
  },
  {
    id: 'build-inversion',
    type: 'sentence_builder',
    topic: 'routine',
    concept: 'refl-word-order',
    skill: 'grammar',
    difficulty: 2,
    chips: ['ich', 'mich', 'Morgens', 'dusche', 'kalt'],
    answers: [['Morgens', 'dusche', 'ich', 'mich', 'kalt']],
    translation: l('In the mornings I take a cold shower.', 'Sabahları soğuk duş alırım.', 'Morgens dusche ich mich kalt.'),
    explanation: l('Time – verb – subject – reflexive pronoun.', 'Zaman – fiil – özne – dönüşlü zamir.', 'Morgens dusche ich mich …'),
    examples: ['Morgens **dusche** ich **mich** kalt.'],
  },
  {
    id: 'build-anziehen',
    type: 'sentence_builder',
    topic: 'routine',
    concept: 'refl-separable',
    skill: 'grammar',
    difficulty: 3,
    chips: ['an', 'sich', 'zieht', 'schnell', 'Mia'],
    answers: [['Mia', 'zieht', 'sich', 'schnell', 'an']],
    translation: l('Mia gets dressed quickly.', 'Mia çabucak giyiniyor.', 'Mia zieht sich schnell an.'),
    explanation: l('sich an|ziehen: verb in position 2, prefix an at the end.', 'sich an|ziehen: fiil 2. sırada, an ön eki sonda.', 'zieht sich … an.'),
    examples: ['Mia **zieht** sich schnell **an**.'],
  },
  {
    id: 'fix-mich-du',
    type: 'error_correction',
    topic: 'pronouns',
    concept: 'refl-du',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Du musst mich beeilen!',
    accepted: ['Du musst dich beeilen!', 'Du musst dich beeilen.'],
    explanation: l('du → dich.', 'du → dich.', 'du → dich.'),
    examples: ['Du musst **dich** beeilen!'],
  },
  {
    id: 'fix-ihn',
    type: 'error_correction',
    topic: 'pronouns',
    concept: 'refl-er',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Tom ärgert ihn über den Stau.',
    accepted: ['Tom ärgert sich über den Stau.'],
    explanation: l('Tom is annoyed himself → sich (ihn would be another person).', 'Tom kendisi sinirleniyor → sich (ihn başka biri olurdu).', 'Tom ärgert sich.'),
    examples: ['Tom ärgert **sich** über den Stau.'],
  },
  {
    id: 'fix-missing',
    type: 'error_correction',
    topic: 'pronouns',
    concept: 'refl-ich',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich freue auf das Wochenende.',
    accepted: ['Ich freue mich auf das Wochenende.', 'Ich freue mich aufs Wochenende.'],
    explanation: l('sich freuen always needs the pronoun: ich freue mich.', 'sich freuen her zaman zamire ihtiyaç duyar: ich freue mich.', 'Ich freue mich.'),
    examples: ['Ich freue **mich** auf das Wochenende.'],
  },
  {
    id: 'tr-fuehlen',
    type: 'translation',
    topic: 'pronouns',
    concept: 'refl-du',
    skill: 'writing',
    difficulty: 2,
    source: l('How do you feel? (du)', 'Kendini nasıl hissediyorsun? (du)', 'How do you feel? (du)'),
    accepted: ['Wie fühlst du dich?', 'Wie fühlst du dich'],
    explanation: l('sich fühlen: du fühlst dich.', 'sich fühlen: du fühlst dich.', 'Wie fühlst du dich?'),
    examples: ['Wie fühlst du **dich**?'],
  },
  {
    id: 'tr-setzen',
    type: 'translation',
    topic: 'pronouns',
    concept: 'refl-Sie',
    skill: 'writing',
    difficulty: 1,
    source: l('Please sit down. (Sie)', 'Lütfen oturun. (Sie)', 'Please sit down. (Sie)'),
    accepted: ['Bitte setzen Sie sich.', 'Setzen Sie sich bitte.', 'Bitte setzen Sie sich!', 'Setzen Sie sich bitte!'],
    explanation: l('Formal imperative: Setzen Sie sich!', 'Resmî emir: Setzen Sie sich!', 'Setzen Sie sich!'),
    examples: ['Bitte setzen Sie **sich**!'],
  },
  {
    id: 'dialog-morgen',
    type: 'dialogue',
    topic: 'routine',
    concept: 'refl-du',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Mutter', de: 'Leon, es ist schon halb acht!' }],
    options: ['Ja, ich beeile mich!', 'Ja, ich beeile mir!', 'Ja, ich beeile!'],
    answer: 0,
    explanation: l('sich beeilen: ich beeile mich.', 'sich beeilen: ich beeile mich.', 'Ich beeile mich.'),
  },
  {
    id: 'dialog-treffen',
    type: 'dialogue',
    topic: 'pronouns',
    concept: 'refl-wir',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Wo treffen wir uns morgen?' }],
    options: ['Am besten treffen wir uns vor dem Bahnhof.', 'Am besten treffen wir sich vor dem Bahnhof.', 'Am besten wir treffen uns vor dem Bahnhof.'],
    answer: 0,
    explanation: l('wir → uns; verb in position 2.', 'wir → uns; fiil 2. sırada.', 'treffen wir uns.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-wann',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-morgen',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wann steht Herr Schulz auf?',
    options: ['Um 5:30 Uhr.', 'Um 7 Uhr.', 'Um 6:30 Uhr.'],
    answer: 0,
    explanation: l('„Ich stehe um halb sechs auf.“', '„Ich stehe um halb sechs auf.“', '„um halb sechs“'),
  },
  {
    id: 'read-kinder',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-morgen',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist das Problem mit den Kindern?',
    options: ['Sie ziehen sich sehr langsam an.', 'Sie wollen nicht frühstücken.', 'Sie stehen zu früh auf.'],
    answer: 0,
    explanation: l('„Die Kinder ziehen sich sooo langsam an!“', '„Die Kinder ziehen sich sooo langsam an!“', '„ziehen sich langsam an“'),
  },
  {
    id: 'read-aerger',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-morgen',
    skill: 'reading',
    difficulty: 2,
    statement: 'Herr Schulz ärgert sich oft über den Stau.',
    answer: true,
    explanation: l('„Im Auto ärgere ich mich oft über den Stau.“', '„Im Auto ärgere ich mich oft über den Stau.“', '„ärgere mich über den Stau“'),
  },
  {
    id: 'read-abend',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-morgen',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was macht er am Abend?',
    options: ['Er ruht sich auf dem Sofa aus.', 'Er geht ins Fitnessstudio.', 'Er trifft sich mit Kollegen.'],
    answer: 0,
    explanation: l('„Am Abend ruhe ich mich auf dem Sofa aus.“', '„Am Abend ruhe ich mich auf dem Sofa aus.“', '„ruhe mich aus“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-pronoun',
    type: 'listening_choice',
    topic: 'pronouns',
    concept: 'refl-ihr',
    skill: 'listening',
    difficulty: 1,
    audio: 'Kinder, beeilt euch bitte!',
    question: l('Which pronoun do you hear?', 'Hangi zamiri duyuyorsun?', 'Welches Pronomen hörst du?'),
    options: ['euch', 'uns', 'sich'],
    answer: 0,
    explanation: l('ihr → euch.', 'ihr → euch.', '„euch“'),
  },
  {
    id: 'listen-freut',
    type: 'listening_choice',
    topic: 'routine',
    concept: 'feelings',
    skill: 'listening',
    difficulty: 2,
    audio: 'Meine Oma freut sich sehr, weil wir sie besuchen.',
    question: l('How does grandma feel?', 'Büyükanne nasıl hissediyor?', 'Wie fühlt sich die Oma?'),
    options: ['😄', '😠', '😴'],
    answer: 0,
    explanation: l('sich freuen = to be happy 😄.', 'sich freuen = sevinmek 😄.', 'Sie freut sich.'),
  },
  {
    id: 'listen-zuerst',
    type: 'listening_choice',
    topic: 'routine',
    concept: 'routine-order',
    skill: 'listening',
    difficulty: 2,
    audio: 'Zuerst dusche ich mich, dann ziehe ich mich an und dann frühstücke ich.',
    question: l('What does the person do first?', 'Kişi önce ne yapıyor?', 'Was macht die Person zuerst?'),
    options: ['🚿', '👕', '🥐'],
    answer: 0,
    explanation: l('„Zuerst dusche ich mich“', '„Zuerst dusche ich mich“', '„zuerst duschen“'),
  },
  {
    id: 'listen-fuehlt',
    type: 'listening_choice',
    topic: 'pronouns',
    concept: 'feelings',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich fühle mich heute nicht so gut. Ich glaube, ich bin erkältet.',
    question: l('How does the person feel?', 'Kişi kendini nasıl hissediyor?', 'Wie fühlt sich die Person?'),
    options: ['not well', 'very well', 'happy'],
    answer: 0,
    explanation: l('„nicht so gut … erkältet“ = not well, has a cold.', '„nicht so gut … erkältet“ = iyi değil, nezle.', 'nicht gut.'),
  },

  ...pronounDrills(),
]

export const UNIT_A2_10_REFLEXIVE_VERBEN: CourseUnit = {
  level: 'A2',
  number: 10,
  slug: 'reflexive-verben',
  titleDe: 'Ich freue mich!',
  title: l('I’m looking forward to it!', 'Seviniyorum!', 'Ich freue mich!'),
  goal: l(
    'By the end of this unit you can describe your daily routine and feelings with reflexive verbs: ich wasche mich, du beeilst dich, wir treffen uns – and ich putze mir die Zähne.',
    'Bu ünitenin sonunda günlük rutinini ve duygularını dönüşlü fiillerle anlatabilirsin: ich wasche mich, du beeilst dich, wir treffen uns – ve ich putze mir die Zähne.',
    'Am Ende dieser Einheit beschreibst du deine Routine und Gefühle mit reflexiven Verben.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'pronouns', label: l('mich, dich, sich …', 'mich, dich, sich …', 'mich, dich, sich …') },
    { key: 'routine', label: l('Daily routine', 'Günlük rutin', 'Tagesroutine') },
    { key: 'dativ-reflexive', label: l('mir die Hände', 'mir die Hände', 'mir die Hände') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Twelve verbs that come with sich.', 'sich ile gelen on iki fiil.', 'Zwölf Verben mit sich.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Reflexive pronouns', 'Dönüşlü zamirler', 'Reflexivpronomen'),
          body: l(
            'Reflexive verbs have a pronoun that refers back to the subject. Most forms are the same as the Akkusativ – only the 3rd person is new: sich.',
            'Dönüşlü fiillerin özneye geri dönen bir zamiri vardır. Biçimlerin çoğu Akkusativ ile aynıdır – yalnızca 3. kişi yenidir: sich.',
            'Wie Akkusativ, nur 3. Person: sich.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('sich waschen', 'sich waschen', 'sich waschen'), l('sich freuen', 'sich freuen', 'sich freuen')],
            rows: [
              ['ich', 'wasche mich', 'freue mich'],
              ['du', 'wäschst dich', 'freust dich'],
              ['er / sie / es', 'wäscht sich', 'freut sich'],
              ['wir', 'waschen uns', 'freuen uns'],
              ['ihr', 'wascht euch', 'freut euch'],
              ['sie / Sie', 'waschen sich', 'freuen sich'],
            ],
          },
        },
        {
          title: l('Word order', 'Cümle yapısı', 'Satzstellung'),
          body: l(
            'The reflexive pronoun usually comes right after the conjugated verb – or after the subject if the subject follows the verb: Ich dusche mich. Morgens dusche ich mich. Separable verbs: Ich ziehe mich an.',
            'Dönüşlü zamir genellikle çekimli fiilden hemen sonra gelir – özne fiilden sonra geliyorsa öznenin ardından: Ich dusche mich. Morgens dusche ich mich. Ayrılabilen fiiller: Ich ziehe mich an.',
            'Verb + (Subjekt) + Reflexivpronomen.'
          ),
        },
        {
          title: l('mir/dir when there is another object', 'Başka bir nesne varsa mir/dir', 'mir/dir bei einem weiteren Objekt'),
          body: l(
            'If the sentence has another Akkusativ object (die Hände, die Zähne, die Haare), the reflexive pronoun is Dativ: Ich wasche mir die Hände. Du kämmst dir die Haare.',
            'Cümlede başka bir Akkusativ nesne varsa (die Hände, die Zähne, die Haare), dönüşlü zamir Dativ olur: Ich wasche mir die Hände. Du kämmst dir die Haare.',
            'Ich wasche mir die Hände.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A stressful morning in the Yılmaz family.', 'Yılmaz ailesinde stresli bir sabah.', 'Ein stressiger Morgen bei Familie Yılmaz.'),
      dialogue: [
        { speaker: 'Mama', de: 'Aylin, Can! Es ist schon sieben Uhr! **Beeilt euch**!', translation: l('Aylin, Can! It’s already seven! Hurry up!', 'Aylin, Can! Saat yedi oldu! Acele edin!', '') },
        { speaker: 'Aylin', de: 'Ich **dusche mich** gerade! Can, **zieh dich** schon **an**!', translation: l('I’m in the shower! Can, get dressed!', 'Duş alıyorum! Can, sen giyin!', '') },
        { speaker: 'Can', de: 'Mama, ich **fühle mich** nicht gut …', translation: l('Mum, I don’t feel well …', 'Anne, kendimi iyi hissetmiyorum …', '') },
        { speaker: 'Mama', de: 'Wirklich? Oder hast du heute einen Test?', translation: l('Really? Or do you have a test today?', 'Gerçekten mi? Yoksa bugün sınavın mı var?', '') },
        { speaker: 'Can', de: 'Na gut … Ich **putze mir** die Zähne und komme.', translation: l('Oh well … I’ll brush my teeth and come.', 'Peki … Dişlerimi fırçalayıp geliyorum.', '') },
        { speaker: 'Papa', de: 'Und ich **ärgere mich** jeden Morgen über den Stau. **Freut ihr euch** auf das Wochenende?', translation: l('And I get annoyed about the traffic every morning. Are you looking forward to the weekend?', 'Ben de her sabah trafiğe sinirleniyorum. Hafta sonunu dört gözle bekliyor musunuz?', '') },
        { speaker: 'Alle', de: 'Jaaa! Da **ruhen** wir **uns** endlich **aus**!', translation: l('Yes! Then we’ll finally rest!', 'Eveet! O zaman sonunda dinleneceğiz!', '') },
      ],
      examples: [
        { de: 'Ich **wasche mich**.', translation: l('I wash (myself).', 'Yıkanıyorum.', '') },
        { de: 'Du **beeilst dich**.', translation: l('You hurry.', 'Acele ediyorsun.', '') },
        { de: 'Er **freut sich** auf den Urlaub.', translation: l('He’s looking forward to the holiday.', 'Tatili dört gözle bekliyor.', '') },
        { de: 'Wir **treffen uns** um acht.', translation: l('We meet at eight.', 'Sekizde buluşuyoruz.', '') },
        { de: '**Zieht euch** warm **an**!', translation: l('Dress warmly! (ihr)', 'Sıkı giyinin!', '') },
        { de: 'Ich **putze mir** die Zähne.', translation: l('I brush my teeth.', 'Dişlerimi fırçalıyorum.', '') },
        { de: 'Bitte **setzen Sie sich**.', translation: l('Please sit down.', 'Lütfen oturun.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('mich, dich, sich …', 'mich, dich, sich …', 'mich, dich, sich …'),
      exercises: ['match-pronouns', 'image-routine', 'ordering-morgen', 'refl-ich', 'refl-er', 'sort-reflexive', 'mc-sich', 'select-reflexive', 'tf-mir', 'refl-wir'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Your day and your feelings.', 'Günün ve duyguların.', 'Dein Tag und deine Gefühle.'),
      exercises: [
        'fill-mich',
        'fill-uns',
        'fill-dir',
        'build-freue',
        'build-inversion',
        'build-anziehen',
        'fix-mich-du',
        'fix-ihn',
        'fix-missing',
        'tr-fuehlen',
        'tr-setzen',
        'dialog-morgen',
        'dialog-treffen',
        'refl-ihr',
        'refl-Sie',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Herr Schulz describes a normal working day.', 'Bay Schulz normal bir iş gününü anlatıyor.', 'Herr Schulz beschreibt seinen Tag.'),
      passage: [
        'Ich stehe um halb sechs auf. Zuerst **dusche** ich **mich**, dann **rasiere** ich **mich** und **ziehe mich an**.',
        'Dann wecke ich die Kinder. Die Kinder **ziehen sich** sooo langsam **an**! Ich sage jeden Morgen: „**Beeilt euch**!“',
        'Um sieben fahre ich zur Arbeit. Im Auto **ärgere** ich **mich** oft über den Stau.',
        'Am Abend **ruhe** ich **mich** auf dem Sofa **aus**. Und am Wochenende? Da **freue** ich **mich** auf lange Frühstücke!',
      ],
      glossary: [
        { de: 'sich rasieren', note: l('to shave', 'tıraş olmak', 'Bart entfernen') },
        { de: 'wecken', note: l('to wake (someone)', '(birini) uyandırmak', 'jemanden aufwecken') },
        { de: 'sooo', note: l('sooo (emphasis)', 'çooook (vurgu)', 'sehr (betont)') },
      ],
      exercises: ['read-wann', 'read-kinder', 'read-aerger', 'read-abend'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for the reflexive pronouns.', 'Dönüşlü zamirlere kulak ver.', 'Hör auf die Reflexivpronomen.'),
      exercises: ['listen-pronoun', 'listen-freut', 'listen-zuerst', 'listen-fuehlt'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe your morning routine and say what you’re looking forward to.', 'Sabah rutinini anlat ve neyi dört gözle beklediğini söyle.', 'Beschreib deine Morgenroutine.'),
      points: [
        l('Get up, shower, get dressed: „Ich … mich …“', 'Kalkmak, duş, giyinmek: „Ich … mich …“', 'Morgenroutine'),
        l('Do you have to hurry? „Ich muss mich beeilen, weil …“', 'Acele etmek zorunda mısın? „Ich muss mich beeilen, weil …“', 'Beeilen?'),
        l('What annoys you? „Ich ärgere mich über …“', 'Seni ne sinirlendiriyor? „Ich ärgere mich über …“', 'Ärger'),
        l('What are you looking forward to? „Ich freue mich auf …“', 'Neyi dört gözle bekliyorsun? „Ich freue mich auf …“', 'Vorfreude'),
      ],
      model: [
        'Ich stehe um sieben Uhr auf und dusche mich.',
        'Dann ziehe ich mich an und putze mir die Zähne.',
        'Ich muss mich immer beeilen, weil der Bus um halb acht fährt.',
        'Ich ärgere mich, wenn der Bus zu spät kommt.',
        'Ich freue mich schon auf den Urlaub im Juli!',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write about your typical morning (at least 5 sentences). Use at least three reflexive verbs.',
        'Tipik sabahını yaz (en az 5 cümle). En az üç dönüşlü fiil kullan.',
        'Schreib über deinen Morgen (mindestens 5 Sätze) mit drei reflexiven Verben.'
      ),
      minSentences: 5,
      checks: [
        { label: l('A reflexive pronoun (mich, dich, sich, uns, euch)', 'Bir dönüşlü zamir (mich, dich, sich, uns, euch)', 'Ein Reflexivpronomen'), pattern: '\\b(mich|dich|sich|uns|euch)\\b' },
        { label: l('A routine verb (waschen, duschen, anziehen …)', 'Bir rutin fiili (waschen, duschen, anziehen …)', 'Ein Routineverb'), pattern: '\\b(wasche|dusche|ziehe|kämme|rasiere|schminke|putze)\\b' },
        { label: l('A feeling (freuen, ärgern, fühlen …)', 'Bir duygu (freuen, ärgern, fühlen …)', 'Ein Gefühl'), pattern: '\\b(freue|ärgere|fühle|ruhe)\\b' },
      ],
      model: [
        'Ich stehe jeden Tag um halb sieben auf.',
        'Zuerst dusche ich mich und dann ziehe ich mich an.',
        'Ich putze mir die Zähne und frühstücke schnell.',
        'Oft muss ich mich beeilen, weil ich spät aufstehe.',
        'Am Wochenende ruhe ich mich aus und freue mich über die Zeit.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Reflexive pronouns – 60 seconds.', 'Dönüşlü zamirler – 60 saniye.', 'Reflexivpronomen – 60 Sekunden.'),
      seconds: 60,
      pool: [...PRONOUN_DRILLS.map(([id]) => `refl-${id}`), 'mc-sich'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('mich, dich, sich, uns, euch, sich', 'mich, dich, sich, uns, euch, sich', 'Reflexivpronomen'),
      l('Routine: sich waschen, duschen, anziehen, beeilen', 'Rutin: sich waschen, duschen, anziehen, beeilen', 'Routine'),
      l('Feelings: sich freuen, ärgern, fühlen, ausruhen', 'Duygular: sich freuen, ärgern, fühlen, ausruhen', 'Gefühle'),
      l('With another object: ich putze mir die Zähne', 'Başka bir nesneyle: ich putze mir die Zähne', 'mir die Zähne'),
    ],
    mistakes: [
      { wrong: 'Ich freue auf den Urlaub.', right: 'Ich freue mich auf den Urlaub.', note: l('Don’t forget the pronoun.', 'Zamiri unutma.', 'mich nicht vergessen.') },
      { wrong: 'Er wäscht ihn.', right: 'Er wäscht sich.', note: l('Same person → sich.', 'Aynı kişi → sich.', 'sich.') },
      { wrong: 'Du musst mich beeilen.', right: 'Du musst dich beeilen.', note: l('du → dich.', 'du → dich.', 'dich.') },
      { wrong: 'Ich wasche mich die Hände.', right: 'Ich wasche mir die Hände.', note: l('Another object → mir.', 'Başka nesne → mir.', 'mir.') },
    ],
  },
}
