import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'gefallen', emoji: '😍', translation: l('to please, be liked by', 'hoşa gitmek', 'gut finden'), example: 'Das Kleid gefällt mir.' },
  { word: 'schmecken', emoji: '😋', translation: l('to taste (good) to', 'lezzetli gelmek', 'gut schmecken'), example: 'Die Suppe schmeckt mir.' },
  { word: 'gehören', emoji: '🔑', translation: l('to belong to', 'ait olmak', 'besitzen'), example: 'Gehört der Schlüssel dir?' },
  { word: 'helfen', emoji: '🤝', translation: l('to help', 'yardım etmek', 'unterstützen'), example: 'Kannst du mir helfen?' },
  { word: 'passen', emoji: '👖', translation: l('to fit, suit', 'uymak (beden/zaman)', 'die richtige Größe haben'), example: 'Die Hose passt mir nicht.' },
  { word: 'stehen', emoji: '🪞', translation: l('to look good on (clothes)', 'yakışmak', 'gut aussehen an'), example: 'Die Farbe steht dir gut!' },
  { word: 'danken', emoji: '🙏', translation: l('to thank', 'teşekkür etmek', 'Danke sagen'), example: 'Ich danke Ihnen.' },
  { word: 'gratulieren', emoji: '🎂', translation: l('to congratulate', 'tebrik etmek', 'Glückwünsche sagen'), example: 'Wir gratulieren dir zum Geburtstag!' },
  { word: 'antworten', emoji: '💬', translation: l('to answer', 'cevap vermek', 'eine Antwort geben'), example: 'Bitte antworte mir schnell.' },
  { word: 'fehlen', emoji: '💔', translation: l('to be missing; to be missed', 'eksik olmak; özlenmek', 'nicht da sein'), example: 'Du fehlst mir.' },
  { word: 'wehtun', emoji: '🤕', translation: l('to hurt', 'acımak', 'Schmerzen machen'), example: 'Mir tut der Kopf weh.' },
  { word: 'Wie geht es dir?', emoji: '🙂', translation: l('How are you?', 'Nasılsın?', 'Wie geht’s?'), example: 'Wie geht es Ihnen? – Mir geht es gut.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Kleid', gender: 'n', plural: 'die Kleider', translation: l('dress', 'elbise', 'Kleid') },
  { word: 'Jacke', gender: 'f', plural: 'die Jacken', translation: l('jacket', 'ceket', 'Jacke') },
  { word: 'Schlüssel', gender: 'm', plural: 'die Schlüssel', translation: l('key', 'anahtar', 'Schlüssel') },
  { word: 'Suppe', gender: 'f', plural: 'die Suppen', translation: l('soup', 'çorba', 'Suppe') },
  { word: 'Farbe', gender: 'f', plural: 'die Farben', translation: l('colour', 'renk', 'Farbe') },
  { word: 'Geschenk', gender: 'n', plural: 'die Geschenke', translation: l('present', 'hediye', 'Geschenk') },
  { word: 'Film', gender: 'm', plural: 'die Filme', translation: l('film', 'film', 'Film') },
  { word: 'Hose', gender: 'f', plural: 'die Hosen', translation: l('trousers', 'pantolon', 'Hose') },
]

/** Nominativ → Dativ personal pronouns. */
export const DATIVE_PRONOUN: Record<string, string> = {
  ich: 'mir',
  du: 'dir',
  er: 'ihm',
  sie: 'ihr',
  es: 'ihm',
  wir: 'uns',
  ihr: 'euch',
  'sie (Pl.)': 'ihnen',
  Sie: 'Ihnen',
}

/** [id, sentence with ___, pronoun (nominative hint), answer, two distractors] */
const PRONOUN_DRILLS: [string, string, string, string, [string, string]][] = [
  ['ich', 'Der Film gefällt ___ sehr.', 'ich', 'mir', ['mich', 'ich']],
  ['du', 'Steht ___ die Jacke?', 'du', 'dir', ['dich', 'du']],
  ['er', 'Ich helfe ___ bei den Hausaufgaben.', 'er', 'ihm', ['ihn', 'er']],
  ['sie', 'Das Geschenk gefällt ___ bestimmt.', 'sie (Sg.)', 'ihr', ['sie', 'ihm']],
  ['wir', 'Das Essen schmeckt ___ super.', 'wir', 'uns', ['wir', 'unser']],
  ['ihr', 'Gehört das Auto ___?', 'ihr', 'euch', ['ihr', 'eure']],
  ['sie-pl', 'Die Kinder sind müde. Ich lese ___ eine Geschichte vor.', 'sie (Pl.)', 'ihnen', ['sie', 'ihr']],
  ['Sie', 'Kann ich ___ helfen?', 'Sie', 'Ihnen', ['Sie', 'Ihr']],
]

function pronounDrills(): Exercise[] {
  return PRONOUN_DRILLS.map(([id, sentence, nom, answer, wrong], i) => {
    const options = [answer, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `dat-${id}`,
      type: 'multiple_choice' as const,
      topic: 'pronouns',
      concept: `dat-pronoun-${id}`,
      skill: 'grammar' as const,
      difficulty: 1 as const,
      prompt: sentence,
      promptL10n: l(`(${nom}) Choose the Dativ form.`, `(${nom}) Dativ biçimini seç.`, `(${nom}) Wähle die Dativform.`),
      options: ordered,
      answer: ordered.indexOf(answer),
      explanation: l(
        `${nom} → Dativ: ${answer}. The verb needs the Dativ.`,
        `${nom} → Dativ: ${answer}. Fiil Dativ ister.`,
        `${nom} → ${answer} (Dativ).`
      ),
      examples: [sentence.replace('___', `**${answer}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-pronouns',
    type: 'matching',
    topic: 'pronouns',
    concept: 'dat-pronoun-table',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Nominativ → Dativ', 'Nominativ → Dativ', 'Nominativ → Dativ'),
    pairs: [
      { left: 'ich', right: 'mir' },
      { left: 'du', right: 'dir' },
      { left: 'er', right: 'ihm' },
      { left: 'wir', right: 'uns' },
      { left: 'Sie', right: 'Ihnen' },
    ],
    explanation: l('ich → mir, du → dir, er/es → ihm, sie → ihr, wir → uns, ihr → euch, sie/Sie → ihnen/Ihnen.', 'ich → mir, du → dir, er/es → ihm, sie → ihr, wir → uns, ihr → euch, sie/Sie → ihnen/Ihnen.', 'mir, dir, ihm, ihr, uns, euch, ihnen.'),
    practice: ['dat-ich', 'dat-Sie'],
  },
  {
    id: 'sort-akk-dat',
    type: 'categorize',
    topic: 'pronouns',
    concept: 'akk-vs-dat',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Akkusativ or Dativ pronoun?', 'Akkusativ mı Dativ zamiri mi?', 'Akkusativ- oder Dativpronomen?'),
    categories: ['Akkusativ', 'Dativ'],
    items: [
      { text: 'mich', category: 0 },
      { text: 'mir', category: 1 },
      { text: 'dich', category: 0 },
      { text: 'dir', category: 1 },
      { text: 'ihn', category: 0 },
      { text: 'ihm', category: 1 },
    ],
    explanation: l(
      'Akkusativ: mich, dich, ihn. Dativ: mir, dir, ihm. Tip: Dativ masculine ends in -m like dem.',
      'Akkusativ: mich, dich, ihn. Dativ: mir, dir, ihm. İpucu: Dativ eril, dem gibi -m ile biter.',
      'mich/dich/ihn – mir/dir/ihm.'
    ),
  },
  {
    id: 'select-dat-verbs',
    type: 'multiple_select',
    topic: 'dat-verbs',
    concept: 'dat-verb-list',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which verbs take the Dativ? Select all.', 'Hangi fiiller Dativ alır? Hepsini seç.', 'Welche Verben haben Dativ? Wähle alle.'),
    options: ['helfen', 'sehen', 'gefallen', 'kaufen', 'danken', 'gehören'],
    answers: [0, 2, 4, 5],
    explanation: l('helfen, gefallen, danken, gehören + Dativ. sehen, kaufen + Akkusativ.', 'helfen, gefallen, danken, gehören + Dativ. sehen, kaufen + Akkusativ.', 'helfen, gefallen, danken, gehören + Dativ.'),
  },
  {
    id: 'mc-gefaellt',
    type: 'multiple_choice',
    topic: 'dat-verbs',
    concept: 'gefallen-form',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Die Schuhe ___ mir.',
    options: ['gefallen', 'gefällt', 'gefalle'],
    answer: 0,
    explanation: l(
      'The thing you like is the subject! die Schuhe (plural) → gefallen. Das Kleid → gefällt.',
      'Beğenilen şey öznedir! die Schuhe (çoğul) → gefallen. Das Kleid → gefällt.',
      'Subjekt = die Schuhe → gefallen.'
    ),
    examples: ['Die Schuhe **gefallen** mir.', 'Das Kleid **gefällt** mir.'],
    practice: ['fix-gefalle'],
  },
  {
    id: 'tf-helfen',
    type: 'true_false',
    topic: 'dat-verbs',
    concept: 'helfen-dat',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Kannst du mich helfen?',
    answer: false,
    instructions: l('Is this sentence correct?', 'Bu cümle doğru mu?', 'Ist der Satz richtig?'),
    explanation: l('helfen + Dativ: Kannst du mir helfen?', 'helfen + Dativ: Kannst du mir helfen?', 'helfen + Dativ → mir.'),
    examples: ['Kannst du **mir** helfen?'],
  },
  {
    id: 'image-weh',
    type: 'image_choice',
    topic: 'dat-verbs',
    concept: 'wehtun',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Mir tut der Zahn weh.',
    options: [
      { emoji: '🦷', label: 'der Zahn' },
      { emoji: '🦶', label: 'der Fuß' },
      { emoji: '👂', label: 'das Ohr' },
      { emoji: '🖐️', label: 'die Hand' },
    ],
    answer: 0,
    explanation: l('der Zahn = tooth. Mir tut … weh = my … hurts.', 'der Zahn = diş. Mir tut … weh = … ağrıyor.', 'der Zahn.'),
  },
  {
    id: 'match-meaning',
    type: 'matching',
    topic: 'dat-verbs',
    concept: 'dat-verb-meaning',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the sentence and its meaning.', 'Cümleyi anlamıyla eşleştir.', 'Ordne Satz und Bedeutung zu.'),
    pairs: [
      { left: 'Das schmeckt mir.', right: l('I like the taste.', 'Tadını beğendim.', 'Das Essen ist lecker.') },
      { left: 'Das passt mir.', right: l('That fits / suits my schedule.', 'Bana uyar.', 'Größe / Zeit ist richtig.') },
      { left: 'Das steht dir.', right: l('That looks good on you.', 'Sana yakıştı.', 'Du siehst gut aus darin.') },
      { left: 'Du fehlst mir.', right: l('I miss you.', 'Seni özlüyorum.', 'Ich vermisse dich.') },
    ],
    explanation: l(
      'All these verbs use the Dativ for the person: mir, dir …',
      'Bu fiillerin hepsi kişi için Dativ kullanır: mir, dir …',
      'Person im Dativ.'
    ),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-ihnen',
    type: 'fill_blank',
    topic: 'pronouns',
    concept: 'dat-pronoun-Sie',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Wie geht es ___, Frau Weber?',
    accepted: ['Ihnen'],
    base: 'Sie',
    explanation: l('Formal Sie → Ihnen (capital I).', 'Resmî Sie → Ihnen (büyük I).', 'Sie → Ihnen.'),
    examples: ['Wie geht es **Ihnen**, Frau Weber?'],
  },
  {
    id: 'fill-ihm',
    type: 'fill_blank',
    topic: 'pronouns',
    concept: 'dat-pronoun-er',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Tim hat Geburtstag. Wir gratulieren ___.',
    accepted: ['ihm'],
    base: 'er',
    explanation: l('gratulieren + Dativ: er → ihm.', 'gratulieren + Dativ: er → ihm.', 'er → ihm.'),
    examples: ['Wir gratulieren **ihm**.'],
  },
  {
    id: 'fill-gehoert',
    type: 'fill_blank',
    topic: 'dat-verbs',
    concept: 'gehoeren',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wem ___ die Tasche? – Sie gehört mir.',
    accepted: ['gehört'],
    base: 'gehören',
    explanation: l('die Tasche (it) → gehört. Wem? = to whom (Dativ question word).', 'die Tasche (o) → gehört. Wem? = kime (Dativ soru kelimesi).', 'Wem gehört …?'),
    examples: ['**Wem** gehört die Tasche?'],
  },
  {
    id: 'build-steht',
    type: 'sentence_builder',
    topic: 'dat-verbs',
    concept: 'stehen-dat',
    skill: 'grammar',
    difficulty: 1,
    chips: ['wirklich gut', 'dir', 'Die Jacke', 'steht'],
    answers: [['Die Jacke', 'steht', 'dir', 'wirklich gut']],
    translation: l('The jacket really suits you.', 'Ceket sana gerçekten yakışıyor.', 'Die Jacke steht dir wirklich gut.'),
    explanation: l('Subject (die Jacke) – verb – Dativ person.', 'Özne (die Jacke) – fiil – Dativ kişi.', 'Die Jacke steht dir.'),
    examples: ['Die Jacke **steht dir** wirklich gut.'],
  },
  {
    id: 'build-mir-gefaellt',
    type: 'sentence_builder',
    topic: 'dat-verbs',
    concept: 'gefallen-form',
    skill: 'grammar',
    difficulty: 2,
    chips: ['nicht', 'gefällt', 'Mir', 'die Farbe'],
    answers: [['Mir', 'gefällt', 'die Farbe', 'nicht']],
    translation: l('I don’t like the colour.', 'Rengi beğenmiyorum.', 'Mir gefällt die Farbe nicht.'),
    explanation: l('The Dativ can come first – the verb stays in position 2.', 'Dativ başa gelebilir – fiil 2. sırada kalır.', 'Mir gefällt …'),
    examples: ['**Mir** gefällt die Farbe nicht.'],
  },
  {
    id: 'build-helfen',
    type: 'sentence_builder',
    topic: 'pronouns',
    concept: 'helfen-dat',
    skill: 'grammar',
    difficulty: 2,
    chips: ['helfen', 'Können', 'uns', 'Sie'],
    answers: [['Können', 'Sie', 'uns', 'helfen']],
    end: '?',
    translation: l('Can you help us?', 'Bize yardım edebilir misiniz?', 'Können Sie uns helfen?'),
    explanation: l('Modal first (question), helfen at the end, uns = Dativ.', 'Modal başta (soru), helfen sonda, uns = Dativ.', 'Können Sie uns helfen?'),
    examples: ['Können Sie **uns** helfen?'],
  },
  {
    id: 'fix-gefalle',
    type: 'error_correction',
    topic: 'dat-verbs',
    concept: 'gefallen-form',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich gefalle das Buch.',
    accepted: ['Mir gefällt das Buch.', 'Das Buch gefällt mir.'],
    explanation: l(
      'In German the book is the subject: Das Buch gefällt mir (literally: The book pleases me).',
      'Almancada kitap öznedir: Das Buch gefällt mir (kelimesi kelimesine: Kitap bana hoş geliyor).',
      'Das Buch gefällt mir.'
    ),
    examples: ['Das Buch **gefällt mir**.'],
  },
  {
    id: 'fix-danke-dich',
    type: 'error_correction',
    topic: 'pronouns',
    concept: 'dat-pronoun-du',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich danke dich für die Hilfe.',
    accepted: ['Ich danke dir für die Hilfe.'],
    explanation: l('danken + Dativ: du → dir.', 'danken + Dativ: du → dir.', 'Ich danke dir.'),
    examples: ['Ich danke **dir** für die Hilfe.'],
  },
  {
    id: 'tr-schmeckt',
    type: 'translation',
    topic: 'dat-verbs',
    concept: 'schmecken',
    skill: 'writing',
    difficulty: 2,
    source: l('Does the soup taste good (to you)? (du)', 'Çorba hoşuna gitti mi? (du)', 'Does the soup taste good to you? (du)'),
    accepted: ['Schmeckt dir die Suppe?', 'Schmeckt dir die Suppe'],
    explanation: l('schmecken + Dativ: Schmeckt dir die Suppe?', 'schmecken + Dativ: Schmeckt dir die Suppe?', 'Schmeckt dir die Suppe?'),
    examples: ['**Schmeckt dir** die Suppe?'],
  },
  {
    id: 'tr-fehlst',
    type: 'translation',
    topic: 'dat-verbs',
    concept: 'fehlen',
    skill: 'writing',
    difficulty: 2,
    source: l('I miss you. (du)', 'Seni özlüyorum. (du)', 'I miss you. (du)'),
    accepted: ['Du fehlst mir.', 'Ich vermisse dich.'],
    explanation: l('Du fehlst mir (you are missing to me) – or: Ich vermisse dich.', 'Du fehlst mir (bana eksiksin) – ya da: Ich vermisse dich.', 'Du fehlst mir.'),
    examples: ['Du **fehlst mir**.'],
  },
  {
    id: 'ordering-dialog',
    type: 'ordering',
    topic: 'dat-verbs',
    concept: 'shop-dialogue',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the shop dialogue in order.', 'Mağaza diyaloğunu sıraya koy.', 'Bring das Gespräch im Laden in Ordnung.'),
    items: ['Ja, sie passt mir. Ich nehme sie!', 'Kann ich Ihnen helfen?', 'Gern. Passt sie Ihnen?', 'Ja, die blaue Jacke gefällt mir. Kann ich sie anprobieren?'],
    answer: ['Kann ich Ihnen helfen?', 'Ja, die blaue Jacke gefällt mir. Kann ich sie anprobieren?', 'Gern. Passt sie Ihnen?', 'Ja, sie passt mir. Ich nehme sie!'],
    explanation: l('Offer help → like → try on → fits → buy.', 'Yardım teklifi → beğeni → deneme → uyuyor → satın alma.', 'helfen → gefallen → passen → nehmen.'),
  },
  {
    id: 'dialog-wie-gehts',
    type: 'dialogue',
    topic: 'pronouns',
    concept: 'dat-pronoun-ich',
    skill: 'grammar',
    difficulty: 1,
    lines: [{ speaker: 'Nachbar', de: 'Guten Morgen! Wie geht es Ihnen?' }],
    options: ['Danke, mir geht es gut. Und Ihnen?', 'Danke, ich geht es gut. Und Sie?', 'Danke, mich geht es gut. Und Ihr?'],
    answer: 0,
    explanation: l('es geht + Dativ: mir geht es gut. Und Ihnen?', 'es geht + Dativ: mir geht es gut. Und Ihnen?', 'Mir geht es gut. Und Ihnen?'),
  },
  {
    id: 'dialog-geschenk',
    type: 'dialogue',
    topic: 'dat-verbs',
    concept: 'gefallen-form',
    skill: 'grammar',
    difficulty: 2,
    lines: [{ speaker: 'Mutter', de: 'Gefällt dir das Geschenk?' }],
    options: ['Ja, es gefällt mir sehr. Danke!', 'Ja, ich gefalle es sehr. Danke!', 'Ja, es gefällt mich sehr. Danke!'],
    answer: 0,
    explanation: l('es (das Geschenk) gefällt mir.', 'es (das Geschenk) gefällt mir.', 'Es gefällt mir.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-schmeckt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-blog',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was schmeckt Deniz in Deutschland nicht so gut?',
    options: ['Der Kaffee.', 'Das Brot.', 'Der Tee.'],
    answer: 0,
    explanation: l('„Das Brot schmeckt mir super, aber der Kaffee schmeckt mir nicht.“', '„Das Brot schmeckt mir super, aber der Kaffee schmeckt mir nicht.“', '„der Kaffee schmeckt mir nicht“'),
  },
  {
    id: 'read-fehlt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-blog',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wer fehlt Deniz?',
    options: ['Seine Familie.', 'Sein Kollege.', 'Seine Nachbarin.'],
    answer: 0,
    explanation: l('„Meine Familie fehlt mir sehr.“', '„Meine Familie fehlt mir sehr.“', '„Meine Familie fehlt mir.“'),
  },
  {
    id: 'read-nachbarin',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-blog',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Nachbarin hilft Deniz beim Deutschlernen.',
    answer: true,
    explanation: l('„Meine Nachbarin hilft mir oft – sie erklärt mir die Grammatik.“', '„Meine Nachbarin hilft mir oft – sie erklärt mir die Grammatik.“', '„hilft mir“'),
  },
  {
    id: 'read-stadt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-blog',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie findet Deniz die Stadt?',
    options: ['Sie gefällt ihm sehr.', 'Sie gefällt ihm nicht.', 'Er weiß es noch nicht.'],
    answer: 0,
    explanation: l('„Die Stadt gefällt mir sehr.“', '„Die Stadt gefällt mir sehr.“', '„gefällt mir sehr“'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-pronoun',
    type: 'listening_choice',
    topic: 'pronouns',
    concept: 'dat-pronoun-du',
    skill: 'listening',
    difficulty: 1,
    audio: 'Das Kleid steht dir super!',
    question: l('Which pronoun do you hear?', 'Hangi zamiri duyuyorsun?', 'Welches Pronomen hörst du?'),
    options: ['dir', 'dich', 'mir'],
    answer: 0,
    explanation: l('„steht dir“', '„steht dir“', '„dir“'),
  },
  {
    id: 'listen-gehoert',
    type: 'listening_choice',
    topic: 'dat-verbs',
    concept: 'gehoeren',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Schlüssel gehört nicht mir, er gehört meinem Bruder.',
    question: l('Whose key is it?', 'Anahtar kimin?', 'Wem gehört der Schlüssel?'),
    options: ['dem Bruder', 'der Person', 'der Mutter'],
    answer: 0,
    explanation: l('„er gehört meinem Bruder“', '„er gehört meinem Bruder“', '„meinem Bruder“'),
  },
  {
    id: 'listen-weh',
    type: 'listening_choice',
    topic: 'dat-verbs',
    concept: 'wehtun',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich kann heute nicht kommen. Mir tut der Rücken weh.',
    question: l('What hurts?', 'Neresi ağrıyor?', 'Was tut weh?'),
    options: ['der Rücken', 'der Kopf', 'der Bauch'],
    answer: 0,
    explanation: l('„Mir tut der Rücken weh.“', '„Mir tut der Rücken weh.“', '„der Rücken“'),
  },
  {
    id: 'listen-passt',
    type: 'listening_choice',
    topic: 'dat-verbs',
    concept: 'passen',
    skill: 'listening',
    difficulty: 2,
    audio: 'Dienstag passt mir leider nicht. Geht auch Mittwoch?',
    question: l('Which day works?', 'Hangi gün uygun?', 'Welcher Tag passt?'),
    options: ['Mittwoch (vielleicht)', 'Dienstag', 'Montag'],
    answer: 0,
    explanation: l('Tuesday doesn’t suit – Wednesday is suggested.', 'Salı uymuyor – çarşamba öneriliyor.', 'Dienstag passt nicht → Mittwoch?'),
  },

  ...pronounDrills(),
]

export const UNIT_A2_03_MIR_GEFAELLT: CourseUnit = {
  level: 'A2',
  number: 3,
  slug: 'mir-gefaellt',
  titleDe: 'Das gefällt mir!',
  title: l('I like that!', 'Bunu beğendim!', 'Das gefällt mir!'),
  goal: l(
    'By the end of this unit you can give opinions and talk about people with the Dativ pronouns (mir, dir, ihm, ihr, uns, euch, ihnen) and verbs like gefallen, schmecken, helfen and gehören.',
    'Bu ünitenin sonunda Dativ zamirleriyle (mir, dir, ihm, ihr, uns, euch, ihnen) ve gefallen, schmecken, helfen, gehören gibi fiillerle fikrini söyleyebilirsin.',
    'Am Ende dieser Einheit sagst du deine Meinung mit Dativpronomen und Verben wie gefallen, schmecken, helfen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'pronouns', label: l('mir, dir, ihm …', 'mir, dir, ihm …', 'mir, dir, ihm …') },
    { key: 'dat-verbs', label: l('Verbs with Dativ', 'Dativ alan fiiller', 'Verben mit Dativ') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Twelve everyday expressions – all of them with the Dativ.', 'On iki günlük ifade – hepsi Dativ ile.', 'Zwölf Alltagsausdrücke – alle mit Dativ.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Personal pronouns in the Dativ', 'Dativ’de şahıs zamirleri', 'Personalpronomen im Dativ'),
          body: l(
            'Some verbs need the person in the Dativ. The pronouns change:',
            'Bazı fiiller kişiyi Dativ’de ister. Zamirler değişir:',
            'Manche Verben brauchen die Person im Dativ:'
          ),
          table: {
            head: [l('Nominativ', 'Nominativ', 'Nominativ'), l('Akkusativ', 'Akkusativ', 'Akkusativ'), l('Dativ', 'Dativ', 'Dativ')],
            rows: [
              ['ich', 'mich', 'mir'],
              ['du', 'dich', 'dir'],
              ['er / es', 'ihn / es', 'ihm'],
              ['sie', 'sie', 'ihr'],
              ['wir', 'uns', 'uns'],
              ['ihr', 'euch', 'euch'],
              ['sie / Sie', 'sie / Sie', 'ihnen / Ihnen'],
            ],
          },
          tip: l('Remember the pairs: mich – mir, dich – dir, ihn – ihm.', 'Çiftleri ezberle: mich – mir, dich – dir, ihn – ihm.', 'mich–mir, dich–dir, ihn–ihm.'),
        },
        {
          title: l('Verbs with the Dativ', 'Dativ alan fiiller', 'Verben mit Dativ'),
          body: l(
            'helfen, danken, antworten, gratulieren, gehören, gefallen, schmecken, passen, stehen, fehlen, wehtun. Also: Wie geht es dir? – Mir geht es gut.',
            'helfen, danken, antworten, gratulieren, gehören, gefallen, schmecken, passen, stehen, fehlen, wehtun. Ayrıca: Wie geht es dir? – Mir geht es gut.',
            'helfen, danken, gefallen, schmecken, gehören, passen …'
          ),
          examples: [
            { de: 'Ich helfe **dir**.', translation: l('I’ll help you.', 'Sana yardım ediyorum.', '') },
            { de: 'Der Schlüssel gehört **ihm**.', translation: l('The key belongs to him.', 'Anahtar onun.', '') },
          ],
        },
        {
          title: l('gefallen & schmecken: the thing is the subject', 'gefallen ve schmecken: şey öznedir', 'gefallen & schmecken: die Sache ist das Subjekt'),
          body: l(
            'Das Kleid gefällt mir = I like the dress (literally: The dress pleases me). The verb agrees with the thing: Das Kleid gefällt mir. Die Schuhe gefallen mir.',
            'Das Kleid gefällt mir = Elbiseyi beğeniyorum (kelimesi kelimesine: Elbise bana hoş geliyor). Fiil şeye uyar: Das Kleid gefällt mir. Die Schuhe gefallen mir.',
            'Die Sache = Subjekt; Person = Dativ.'
          ),
          examples: [{ de: 'Die Schuhe **gefallen** mir. Die Suppe **schmeckt** uns.', translation: l('I like the shoes. We like the soup.', 'Ayakkabıları beğeniyorum. Çorbayı beğeniyoruz.', '') }],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Shopping for clothes with a friend.', 'Bir arkadaşla kıyafet alışverişi.', 'Kleidung kaufen mit einer Freundin.'),
      dialogue: [
        { speaker: 'Verkäuferin', de: 'Guten Tag! Kann ich **Ihnen** helfen?', translation: l('Hello! Can I help you?', 'İyi günler! Size yardım edebilir miyim?', '') },
        { speaker: 'Ayşe', de: 'Danke, wir schauen nur. – Sara, wie **gefällt dir** die Jacke?', translation: l('Thanks, we’re just looking. – Sara, how do you like the jacket?', 'Teşekkürler, sadece bakıyoruz. – Sara, ceketi nasıl buldun?', '') },
        { speaker: 'Sara', de: 'Die Farbe **gefällt mir**, aber sie **passt mir** nicht. Sie ist zu klein.', translation: l('I like the colour, but it doesn’t fit me. It’s too small.', 'Rengini beğendim ama bana uymuyor. Çok küçük.', '') },
        { speaker: 'Ayşe', de: 'Probier mal Größe 40! … Oh, die **steht dir** super!', translation: l('Try size 40! … Oh, that looks great on you!', 'Bir de 40 bedeni dene! … Ah, sana harika yakıştı!', '') },
        { speaker: 'Sara', de: 'Wirklich? Dann nehme ich sie. Und **dir**? **Gefallen dir** die Schuhe hier?', translation: l('Really? Then I’ll take it. And you? Do you like the shoes here?', 'Gerçekten mi? O zaman alıyorum. Ya sen? Buradaki ayakkabıları beğendin mi?', '') },
        { speaker: 'Ayşe', de: 'Ja, aber sie sind zu teuer. **Mir tun** auch schon die Füße **weh** – Kaffee?', translation: l('Yes, but they’re too expensive. My feet already hurt too – coffee?', 'Evet ama çok pahalı. Ayaklarım da ağrımaya başladı – kahve?', '') },
      ],
      examples: [
        { de: 'Die Jacke **gefällt mir**.', translation: l('I like the jacket.', 'Ceketi beğeniyorum.', '') },
        { de: 'Die Schuhe **passen ihm** nicht.', translation: l('The shoes don’t fit him.', 'Ayakkabılar ona uymuyor.', '') },
        { de: 'Die Farbe **steht dir** gut.', translation: l('The colour suits you.', 'Renk sana yakışıyor.', '') },
        { de: 'Kannst du **mir** helfen?', translation: l('Can you help me?', 'Bana yardım edebilir misin?', '') },
        { de: 'Wie geht es **Ihnen**?', translation: l('How are you? (formal)', 'Nasılsınız?', '') },
        { de: 'Das Essen **schmeckt uns**.', translation: l('We like the food.', 'Yemeği beğeniyoruz.', '') },
        { de: '**Wem** gehört das Handy? – Es gehört **ihr**.', translation: l('Whose phone is it? – It belongs to her.', 'Telefon kimin? – Onun.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Dativ pronouns and Dativ verbs.', 'Dativ zamirleri ve Dativ fiilleri.', 'Dativpronomen und Dativverben.'),
      exercises: ['match-pronouns', 'sort-akk-dat', 'select-dat-verbs', 'dat-ich', 'dat-du', 'dat-er', 'mc-gefaellt', 'tf-helfen', 'image-weh', 'match-meaning'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Say what you like – and help others.', 'Neyi beğendiğini söyle – ve başkalarına yardım et.', 'Sag, was dir gefällt.'),
      exercises: [
        'fill-ihnen',
        'fill-ihm',
        'fill-gehoert',
        'build-steht',
        'build-mir-gefaellt',
        'build-helfen',
        'fix-gefalle',
        'fix-danke-dich',
        'tr-schmeckt',
        'tr-fehlst',
        'ordering-dialog',
        'dialog-wie-gehts',
        'dialog-geschenk',
        'dat-sie-pl',
        'dat-ihr',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Deniz writes about his first months in Germany.', 'Deniz Almanya’daki ilk aylarını anlatıyor.', 'Deniz schreibt über seine ersten Monate in Deutschland.'),
      passage: [
        'Seit drei Monaten wohne ich in Leipzig. Die Stadt **gefällt mir** sehr – sie ist grün und nicht so laut.',
        'Das Brot **schmeckt mir** super, aber der Kaffee **schmeckt mir** nicht. Ich trinke lieber Tee!',
        'Meine Nachbarin Frau Krause **hilft mir** oft. Sie erklärt **mir** die Grammatik, und ich koche **ihr** manchmal türkisches Essen.',
        'Nur eins ist schwer: Meine Familie **fehlt mir** sehr. Zum Glück telefonieren wir jeden Sonntag.',
      ],
      glossary: [
        { de: 'seit drei Monaten', note: l('for three months', 'üç aydır', 'drei Monate bis heute') },
        { de: 'erklärt', note: l('explains', 'açıklıyor', 'erklären') },
        { de: 'zum Glück', note: l('luckily', 'neyse ki', 'glücklicherweise') },
      ],
      exercises: ['read-stadt', 'read-schmeckt', 'read-nachbarin', 'read-fehlt'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for mir, dir, ihm …', 'mir, dir, ihm … zamirlerine kulak ver.', 'Hör auf mir, dir, ihm …'),
      exercises: ['listen-pronoun', 'listen-gehoert', 'listen-weh', 'listen-passt'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Talk about your taste: food, clothes, films, your city.', 'Zevkinden bahset: yemek, kıyafet, filmler, şehrin.', 'Sprich über deinen Geschmack: Essen, Kleidung, Filme, deine Stadt.'),
      points: [
        l('Food: „… schmeckt mir (nicht).“', 'Yemek: „… schmeckt mir (nicht).“', 'Essen'),
        l('Clothes or colours: „… gefällt mir / steht mir.“', 'Kıyafet ya da renkler: „… gefällt mir / steht mir.“', 'Kleidung'),
        l('Your city: „Die Stadt gefällt mir, weil …“', 'Şehrin: „Die Stadt gefällt mir …“', 'Deine Stadt'),
        l('Who or what do you miss? „… fehlt mir.“', 'Kimi ya da neyi özlüyorsun? „… fehlt mir.“', 'Was fehlt dir?'),
      ],
      model: [
        'Türkisches Essen schmeckt mir am besten, besonders Linsensuppe.',
        'Blau gefällt mir sehr, und die Farbe steht mir auch gut.',
        'Meine Stadt gefällt mir, sie ist klein und ruhig.',
        'Meine Freunde in Izmir fehlen mir manchmal.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a message to a friend (at least 5 sentences) about your new flat, city or job: what do you like, what not?',
        'Bir arkadaşına yeni evin, şehrin ya da işin hakkında bir mesaj yaz (en az 5 cümle): neyi beğeniyorsun, neyi beğenmiyorsun?',
        'Schreib einer Freundin (mindestens 5 Sätze): Was gefällt dir, was nicht?'
      ),
      minSentences: 5,
      checks: [
        { label: l('gefallen (gefällt / gefallen mir …)', 'gefallen (gefällt / gefallen mir …)', 'gefallen'), pattern: '\\b(gefällt|gefallen)\\b' },
        { label: l('A Dativ pronoun (mir, dir, ihm, ihr, uns, euch, ihnen)', 'Bir Dativ zamiri (mir, dir, ihm, ihr, uns, euch, ihnen)', 'Ein Dativpronomen'), pattern: '\\b([Mm]ir|[Dd]ir|[Ii]hm|[Uu]ns|[Ee]uch|[Ii]hnen)\\b' },
        { label: l('Another Dativ verb (helfen, schmecken, passen, fehlen …)', 'Başka bir Dativ fiili (helfen, schmecken, passen, fehlen …)', 'Noch ein Dativverb'), pattern: '\\b(hilf|helf|schmeck|pass|fehl|gehör|steht|danke|antwort)\\p{Ll}*' },
      ],
      model: [
        'Liebe Mia, meine neue Wohnung gefällt mir sehr.',
        'Die Küche ist groß und die Zimmer sind hell.',
        'Der Nachbar hilft mir oft beim Deutschlernen.',
        'Nur das Wetter gefällt mir nicht, es regnet so viel.',
        'Du fehlst mir!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Dativ pronouns – 60 seconds.', 'Dativ zamirleri – 60 saniye.', 'Dativpronomen – 60 Sekunden.'),
      seconds: 60,
      pool: [...PRONOUN_DRILLS.map(([id]) => `dat-${id}`), 'mc-gefaellt'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Dativ pronouns: mir, dir, ihm, ihr, uns, euch, ihnen/Ihnen', 'Dativ zamirleri: mir, dir, ihm, ihr, uns, euch, ihnen/Ihnen', 'mir, dir, ihm, ihr, uns, euch, ihnen'),
      l('Dativ verbs: helfen, danken, gehören, gefallen, schmecken, passen, stehen, fehlen', 'Dativ fiilleri: helfen, danken, gehören, gefallen, schmecken, passen, stehen, fehlen', 'Verben mit Dativ'),
      l('Das gefällt mir: the thing is the subject', 'Das gefällt mir: şey öznedir', 'Sache = Subjekt'),
      l('Wem? = to whom', 'Wem? = kime', 'Wem?'),
    ],
    mistakes: [
      { wrong: 'Kannst du mich helfen?', right: 'Kannst du mir helfen?', note: l('helfen + Dativ.', 'helfen + Dativ.', 'helfen + Dativ.') },
      { wrong: 'Ich gefalle die Jacke.', right: 'Die Jacke gefällt mir.', note: l('The jacket is the subject.', 'Ceket öznedir.', 'Jacke = Subjekt.') },
      { wrong: 'Die Schuhe gefällt mir.', right: 'Die Schuhe gefallen mir.', note: l('Plural subject → gefallen.', 'Çoğul özne → gefallen.', 'Plural.') },
      { wrong: 'Wie geht es Sie?', right: 'Wie geht es Ihnen?', note: l('es geht + Dativ.', 'es geht + Dativ.', 'Ihnen.') },
    ],
  },
}
