import type { UnitOutline } from '../types'

/**
 * The complete C1 curriculum. Units with content are registered in ../registry.
 * Slugs are unique across all levels (exercise keys are `slug:id`).
 */
export const C1_OUTLINE: UnitOutline[] = [
  {
    number: 1,
    slug: 'redewiedergabe',
    titleDe: 'Wie der Sprecher betonte …',
    title: { en: 'As the spokesperson emphasised …', tr: 'Sözcünün vurguladığı gibi …', de: 'Wie der Sprecher betonte …' },
    focus: ['Redewiedergabe ohne Konjunktiv: laut, zufolge, wie … berichtet', 'Distanz ausdrücken: angeblich, vermeintlich', 'Pressesprache verstehen'],
  },
  {
    number: 2,
    slug: 'passiv-c1',
    titleDe: 'Es wird gefeiert',
    title: { en: 'There is celebrating', tr: 'Kutlama yapılıyor', de: 'Es wird gefeiert' },
    focus: ['Zustandspassiv: ist geöffnet', 'Passiv mit Modalverben in der Vergangenheit', 'Unpersönliches Passiv'],
  },
  {
    number: 3,
    slug: 'konjunktiv-ii-c1',
    titleDe: 'Hätte ich das gewusst …',
    title: { en: 'Had I known …', tr: 'Bunu bilseydim …', de: 'Hätte ich das gewusst …' },
    focus: ['Konditionalsätze ohne wenn', 'Konjunktiv II im Passiv', 'Höflichkeit und Distanz'],
  },
  {
    number: 4,
    slug: 'konnektoren-c1',
    titleDe: 'Zumal, wohingegen, geschweige denn',
    title: { en: 'Especially since, whereas, let alone', tr: '… olduğundan, oysa, şöyle dursun', de: 'Zumal, wohingegen, geschweige denn' },
    focus: ['zumal, wohingegen, insofern', 'geschweige denn, ohnehin', 'präzise argumentieren'],
  },
  {
    number: 5,
    slug: 'funktionsverbgefuege',
    titleDe: 'Zur Verfügung stellen',
    title: { en: 'To make available', tr: 'Kullanıma sunmak', de: 'Zur Verfügung stellen' },
    focus: ['Funktionsverbgefüge erkennen', 'in Kraft treten, Kritik üben, Rücksicht nehmen', 'Verb oder Gefüge?'],
  },
  {
    number: 6,
    slug: 'modalitaetsverben',
    titleDe: 'Das scheint zu stimmen',
    title: { en: 'That seems to be true', tr: 'Doğru gibi görünüyor', de: 'Das scheint zu stimmen' },
    focus: ['scheinen, drohen, versprechen + zu', 'brauchen nicht zu, haben zu', 'pflegen zu, vermögen zu'],
  },
  {
    number: 7,
    slug: 'partizipialsaetze',
    titleDe: 'Am Ziel angekommen …',
    title: { en: 'Having arrived at the destination …', tr: 'Hedefe vardıktan sonra …', de: 'Am Ziel angekommen …' },
    focus: ['Partizipialsätze verstehen', 'in Nebensätze umformen', 'literarischer und journalistischer Stil'],
  },
  {
    number: 8,
    slug: 'textkohaerenz',
    titleDe: 'Ein roter Faden',
    title: { en: 'A common thread', tr: 'Kırmızı bir iplik (tutarlılık)', de: 'Ein roter Faden' },
    focus: ['Verweiswörter: dieser, Letzterer, dessen', 'Textstruktur und Übergänge', 'Wiederholungen vermeiden'],
  },
  {
    number: 9,
    slug: 'redewendungen',
    titleDe: 'Den Nagel auf den Kopf treffen',
    title: { en: 'To hit the nail on the head', tr: 'Taşı gediğine koymak', de: 'Den Nagel auf den Kopf treffen' },
    focus: ['Häufige Redewendungen', 'Bedeutung aus dem Kontext erschließen', 'passend einsetzen'],
  },
  {
    number: 10,
    slug: 'register-stil',
    titleDe: 'Umgangssprache, Standard, gehoben',
    title: { en: 'Colloquial, standard, elevated', tr: 'Günlük, standart, yüksek üslup', de: 'Umgangssprache, Standard, gehoben' },
    focus: ['Stilebenen unterscheiden', 'Synonyme mit unterschiedlichem Register', 'angemessen formulieren'],
  },
  {
    number: 11,
    slug: 'new-work',
    titleDe: 'Die Arbeitswelt von morgen',
    title: { en: 'The working world of tomorrow', tr: 'Yarının çalışma dünyası', de: 'Die Arbeitswelt von morgen' },
    focus: ['New Work und Führung', 'Flexibilität vs. Entgrenzung', 'Positionen differenziert darstellen'],
  },
  {
    number: 12,
    slug: 'wissenschaftssprache',
    titleDe: 'Wissenschaftlich schreiben',
    title: { en: 'Academic writing', tr: 'Akademik yazım', de: 'Wissenschaftlich schreiben' },
    focus: ['Hypothesen formulieren', 'Zitieren und paraphrasieren', 'unpersönlicher Stil'],
  },
  {
    number: 13,
    slug: 'ethik',
    titleDe: 'Darf man alles, was man kann?',
    title: { en: 'Should we do everything we can?', tr: 'Yapabildiğimiz her şeyi yapmalı mıyız?', de: 'Darf man alles, was man kann?' },
    focus: ['Ethische Fragen der Technik', 'Dilemmata diskutieren', 'Werte begründen'],
  },
  {
    number: 14,
    slug: 'medienkritik',
    titleDe: 'Filterblasen und Fake News',
    title: { en: 'Filter bubbles and fake news', tr: 'Filtre balonları ve yalan haberler', de: 'Filterblasen und Fake News' },
    focus: ['Manipulation erkennen', 'Medienkompetenz', 'Quellen kritisch prüfen'],
  },
  {
    number: 15,
    slug: 'klimapolitik',
    titleDe: 'Klimapolitik zwischen Anspruch und Wirklichkeit',
    title: { en: 'Climate policy: aspiration and reality', tr: 'İklim politikası: hedef ve gerçek', de: 'Klimapolitik' },
    focus: ['Maßnahmen bewerten', 'Zielkonflikte benennen', 'komplexe Zusammenhänge erklären'],
  },
  {
    number: 16,
    slug: 'sprache-identitaet',
    titleDe: 'Sprache und Identität',
    title: { en: 'Language and identity', tr: 'Dil ve kimlik', de: 'Sprache und Identität' },
    focus: ['Dialekte und Sprachwandel', 'gendergerechte Sprache', 'Anglizismen'],
  },
  {
    number: 17,
    slug: 'gesundheitssystem',
    titleDe: 'Das Gesundheitssystem',
    title: { en: 'The healthcare system', tr: 'Sağlık sistemi', de: 'Das Gesundheitssystem' },
    focus: ['Kranken- und Pflegeversicherung', 'Fachkräftemangel in der Pflege', 'Reformvorschläge'],
  },
  {
    number: 18,
    slug: 'recht-justiz',
    titleDe: 'Recht und Gerechtigkeit',
    title: { en: 'Law and justice', tr: 'Hukuk ve adalet', de: 'Recht und Gerechtigkeit' },
    focus: ['Rechtssprache verstehen', 'Rechte und Pflichten', 'ein Urteil kommentieren'],
  },
  {
    number: 19,
    slug: 'glueck',
    titleDe: 'Was ist ein gutes Leben?',
    title: { en: 'What is a good life?', tr: 'İyi bir hayat nedir?', de: 'Was ist ein gutes Leben?' },
    focus: ['Glück und Lebenssinn', 'philosophische Positionen', 'abstrakt argumentieren'],
  },
  {
    number: 20,
    slug: 'stadtentwicklung',
    titleDe: 'Die Stadt der Zukunft',
    title: { en: 'The city of the future', tr: 'Geleceğin şehri', de: 'Die Stadt der Zukunft' },
    focus: ['Gentrifizierung', 'Mobilität und Wohnraum', 'Bürgerbeteiligung'],
  },
  {
    number: 21,
    slug: 'zusammenfassung',
    titleDe: 'Texte zusammenfassen',
    title: { en: 'Summarising texts', tr: 'Metin özetlemek', de: 'Texte zusammenfassen' },
    focus: ['Kernaussagen erkennen', 'mit eigenen Worten wiedergeben', 'neutral bleiben'],
    scenario: { en: 'Summarise an article (exam style)', tr: 'Bir makaleyi özetle (sınav tarzı)', de: 'Einen Artikel zusammenfassen' },
  },
  {
    number: 22,
    slug: 'stellungnahme',
    titleDe: 'Eine Stellungnahme schreiben',
    title: { en: 'Writing a statement', tr: 'Görüş bildirisi yazmak', de: 'Eine Stellungnahme schreiben' },
    focus: ['Position beziehen', 'Gegenpositionen entkräften', 'überzeugend schließen'],
    scenario: { en: 'Write a statement on a controversial issue', tr: 'Tartışmalı bir konuda görüş bildir', de: 'Stellung nehmen' },
  },
  {
    number: 23,
    slug: 'moderation',
    titleDe: 'Eine Diskussion moderieren',
    title: { en: 'Moderating a discussion', tr: 'Bir tartışmayı yönetmek', de: 'Eine Diskussion moderieren' },
    focus: ['Diskussion eröffnen und strukturieren', 'Wort erteilen und unterbrechen', 'Ergebnisse zusammenfassen'],
    scenario: { en: 'Moderate a panel discussion', tr: 'Bir panel tartışmasını yönet', de: 'Eine Podiumsdiskussion leiten' },
  },
  {
    number: 24,
    slug: 'vorstellungsgespraech',
    titleDe: 'Das Vorstellungsgespräch',
    title: { en: 'The job interview', tr: 'İş görüşmesi', de: 'Das Vorstellungsgespräch' },
    focus: ['Stärken überzeugend darstellen', 'schwierige Fragen souverän beantworten', 'Gehalt und Bedingungen verhandeln'],
    scenario: { en: 'A job interview for a management position', tr: 'Yönetici pozisyonu için iş görüşmesi', de: 'Bewerbung als Führungskraft' },
  },
  {
    number: 25,
    slug: 'c1-review',
    titleDe: 'C1 Wiederholung & Prüfungstraining',
    title: { en: 'C1 review & exam practice', tr: 'C1 tekrar ve sınav hazırlığı', de: 'C1 Wiederholung & Prüfungstraining' },
    focus: ['Gemischte Wiederholung', 'Prüfungsformat Goethe/telc C1', 'Bereit für C2?'],
  },
]
