import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Entgrenzung', emoji: '🌀', translation: l('blurring of boundaries (work/private life)', 'sınırların bulanıklaşması (iş/özel hayat)', 'Arbeit und Freizeit vermischen sich'), example: 'Homeoffice kann zur Entgrenzung der Arbeit führen.' },
  { word: 'die Vertrauensarbeitszeit', emoji: '🤝', translation: l('trust-based working hours', 'güvene dayalı çalışma saatleri', 'keine Zeiterfassung'), example: 'Bei uns gilt Vertrauensarbeitszeit.' },
  { word: 'flache Hierarchien', emoji: '📏', translation: l('flat hierarchies', 'düz hiyerarşiler', 'wenige Führungsebenen'), example: 'Start-ups setzen oft auf flache Hierarchien.' },
  { word: 'die Eigenverantwortung', emoji: '🧭', translation: l('personal responsibility', 'öz sorumluluk', 'selbst verantwortlich sein'), example: 'New Work verlangt viel Eigenverantwortung.' },
  { word: 'die Work-Life-Balance', emoji: '⚖️', translation: l('work-life balance', 'iş-yaşam dengesi', 'Gleichgewicht'), example: 'Eine gute Work-Life-Balance ist vielen wichtig.' },
  { word: 'ständig erreichbar sein', emoji: '📱', translation: l('to be constantly reachable', 'sürekli ulaşılabilir olmak', 'immer online'), example: 'Viele fühlen sich verpflichtet, ständig erreichbar zu sein.' },
  { word: 'die Viertagewoche', emoji: '📅', translation: l('four-day week', 'dört günlük hafta', 'vier Arbeitstage'), example: 'Einige Firmen testen die Viertagewoche.' },
  { word: 'die Führungskraft', emoji: '👩‍💼', translation: l('manager, leader', 'yönetici', 'Chef, Leitung'), example: 'Führungskräfte sollten eher coachen als kontrollieren.' },
  { word: 'einerseits … andererseits', emoji: '↔️', translation: l('on the one hand … on the other hand', 'bir yandan … öte yandan', 'zwei Seiten'), example: 'Einerseits ist es flexibel, andererseits fehlt der Kontakt.' },
  { word: 'Befürworter / Kritiker', emoji: '🗣️', translation: l('supporters / critics', 'savunucular / eleştirmenler', 'dafür / dagegen'), example: 'Befürworter betonen die Freiheit, Kritiker warnen vor Stress.' },
  { word: 'zu bedenken geben', emoji: '🤔', translation: l('to point out (as a concern)', 'dikkat çekmek, hatırlatmak', 'einwenden'), example: 'Gewerkschaften geben zu bedenken, dass …' },
  { word: 'die Sinnhaftigkeit', emoji: '✨', translation: l('meaningfulness', 'anlamlılık', 'Sinn'), example: 'Junge Menschen suchen Sinnhaftigkeit im Job.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Arbeitgeber', gender: 'm', plural: 'die Arbeitgeber', translation: l('employer', 'işveren', 'Arbeitgeber') },
  { word: 'Arbeitnehmer', gender: 'm', plural: 'die Arbeitnehmer', translation: l('employee', 'çalışan', 'Arbeitnehmer') },
  { word: 'Gewerkschaft', gender: 'f', plural: 'die Gewerkschaften', translation: l('trade union', 'sendika', 'Gewerkschaft') },
  { word: 'Zeiterfassung', gender: 'f', translation: l('time tracking', 'mesai kaydı', 'Zeiterfassung') },
  { word: 'Produktivität', gender: 'f', translation: l('productivity', 'verimlilik', 'Produktivität') },
  { word: 'Erschöpfung', gender: 'f', translation: l('exhaustion', 'tükenmişlik', 'Erschöpfung') },
  { word: 'Präsenzpflicht', gender: 'f', translation: l('obligation to be present', 'işyerinde bulunma zorunluluğu', 'Präsenzpflicht') },
  { word: 'Selbstbestimmung', gender: 'f', translation: l('self-determination', 'kendi kaderini belirleme', 'Selbstbestimmung') },
]

/** [id, sentence with gap, right, wrong] */
const NW: [string, string, string, [string, string]][] = [
  ['einerseits', '___ schätze ich die Freiheit im Homeoffice, andererseits vermisse ich meine Kollegen.', 'Einerseits', ['Erstens', 'Entweder']],
  ['entgrenzung', 'Wenn man abends noch Mails beantwortet, spricht man von einer ___ der Arbeit.', 'Entgrenzung', ['Begrenzung', 'Abgrenzung']],
  ['befuerworter', '___ der Viertagewoche argumentieren, dass die Produktivität steigt.', 'Befürworter', ['Gegner', 'Kritiker']],
  ['bedenken', 'Die Gewerkschaft gibt zu ___, dass viele Beschäftigte überlastet sind.', 'bedenken', ['denken', 'überlegen']],
  ['erreichbar', 'Viele Beschäftigte haben das Gefühl, ständig ___ sein zu müssen.', 'erreichbar', ['erreicht', 'erreichend']],
  ['zwar', 'Die Viertagewoche ist ___ attraktiv, aber nicht in jeder Branche umsetzbar.', 'zwar', ['sowohl', 'weder']],
]

function nwDrills(): Exercise[] {
  return NW.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `nw-${id}`,
      type: 'multiple_choice' as const,
      topic: 'positionen',
      concept: 'nuance',
      skill: 'vocabulary' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Presenting positions in a nuanced way: einerseits … andererseits, zwar … aber, Befürworter (pro) vs. Kritiker / Gegner (contra), zu bedenken geben = to raise a concern. Entgrenzung = work spilling into private life.',
        'Görüşleri dengeli sunmak: einerseits … andererseits, zwar … aber, Befürworter (lehte) ve Kritiker / Gegner (aleyhte), zu bedenken geben = bir endişeyi dile getirmek. Entgrenzung = işin özel hayata taşması.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-begriffe',
    type: 'matching',
    topic: 'new-work',
    concept: 'terms',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the term and its explanation.', 'Terimi açıklamasıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Vertrauensarbeitszeit', right: 'keine Zeiterfassung' },
      { left: 'flache Hierarchien', right: 'wenige Führungsebenen' },
      { left: 'Entgrenzung', right: 'Arbeit dringt in die Freizeit ein' },
      { left: 'Präsenzpflicht', right: 'man muss im Büro sein' },
      { left: 'Viertagewoche', right: 'vier Arbeitstage' },
    ],
    explanation: l('Key terms of the debate about New Work.', 'New Work tartışmasının temel terimleri.', 'Begriffe.'),
  },
  {
    id: 'sort-pro-contra',
    type: 'categorize',
    topic: 'flexibilitaet',
    concept: 'pro-contra',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Advantage or risk of flexible work?', 'Esnek çalışmanın avantajı mı riski mi?', 'Vorteil oder Risiko?'),
    categories: ['Vorteil ✅', 'Risiko ⚠️'],
    items: [
      { text: 'mehr Selbstbestimmung', category: 0 },
      { text: 'ständige Erreichbarkeit', category: 1 },
      { text: 'kein Pendeln', category: 0 },
      { text: 'soziale Isolation', category: 1 },
      { text: 'bessere Vereinbarkeit von Familie und Beruf', category: 0 },
      { text: 'Erschöpfung durch Überstunden', category: 1 },
    ],
    explanation: l('Flexibility brings freedom – and the risk of Entgrenzung.', 'Esneklik özgürlük getirir – ve sınırların bulanıklaşması riskini.', 'Pro und Contra.'),
    practice: ['nw-entgrenzung'],
  },
  {
    id: 'mc-differenziert',
    type: 'multiple_choice',
    topic: 'positionen',
    concept: 'nuance',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welche Aussage ist am differenziertesten?',
    options: ['Homeoffice bietet zwar Freiheit, kann aber bei fehlenden Regeln zu Überlastung führen.', 'Homeoffice ist einfach super.', 'Homeoffice ist der Untergang der Arbeitswelt.'],
    answer: 0,
    explanation: l('zwar … aber names both sides and a condition.', 'zwar … aber iki tarafı ve bir koşulu belirtir.', 'differenziert.'),
    practice: ['fill-zwar'],
  },
  {
    id: 'tf-vertrauen',
    type: 'true_false',
    topic: 'new-work',
    concept: 'terms',
    skill: 'vocabulary',
    difficulty: 2,
    statement: 'Bei Vertrauensarbeitszeit stempelt man jeden Morgen genau um 8 Uhr ein.',
    answer: false,
    explanation: l('Trust-based hours = no time tracking.', 'Güvene dayalı saat = mesai kaydı yok.', 'falsch.'),
  },
  {
    id: 'select-fuehrung',
    type: 'multiple_select',
    topic: 'new-work',
    concept: 'leadership',
    skill: 'vocabulary',
    difficulty: 3,
    promptL10n: l('Which characteristics fit modern leadership in New Work? Select all.', 'Hangi özellikler New Work’teki modern liderliğe uyar? Hepsini seç.', 'Moderne Führung?'),
    options: ['Vertrauen statt Kontrolle', 'Mitarbeitende coachen', 'strenge Anwesenheitskontrolle', 'Entscheidungen gemeinsam treffen', 'Befehle ohne Begründung'],
    answers: [0, 1, 3],
    explanation: l('Trust, coaching and participation.', 'Güven, koçluk ve katılım.', 'Führung.'),
  },
  {
    id: 'image-homeoffice',
    type: 'image_choice',
    topic: 'flexibilitaet',
    concept: 'homeoffice',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'das Homeoffice',
    options: [
      { emoji: '🏡', label: 'Homeoffice' },
      { emoji: '🏭', label: 'Fabrik' },
      { emoji: '🏢', label: 'Großraumbüro' },
      { emoji: '🚆', label: 'Pendeln' },
    ],
    answer: 0,
    explanation: l('Homeoffice = working from home.', 'Homeoffice = evden çalışma.', 'Homeoffice.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-zwar',
    type: 'fill_blank',
    topic: 'positionen',
    concept: 'concession',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Flache Hierarchien fördern zwar die Kreativität, ___ sie führen manchmal zu unklaren Zuständigkeiten.',
    accepted: ['aber', 'doch', 'jedoch'],
    base: 'zwar …',
    explanation: l('zwar … aber / doch = admittedly … but.', 'zwar … aber / doch = gerçi … ama.', 'zwar … aber.'),
    examples: ['… fördern **zwar** die Kreativität, **aber** …'],
  },
  {
    id: 'fill-andererseits',
    type: 'fill_blank',
    topic: 'positionen',
    concept: 'two-sides',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Einerseits spart man Zeit, ___ fehlt der persönliche Austausch.',
    accepted: ['andererseits', 'anderseits'],
    base: 'einerseits …',
    explanation: l('einerseits … andererseits (+ verb in position 2).', 'einerseits … andererseits (+ 2. konumda fiil).', 'andererseits.'),
    examples: ['Einerseits spart man Zeit, **andererseits fehlt** …'],
  },
  {
    id: 'fill-eigenverantwortung',
    type: 'fill_blank',
    topic: 'new-work',
    concept: 'terms',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Wer ohne feste Arbeitszeiten arbeitet, braucht viel Eigen___.',
    accepted: ['verantwortung'],
    base: 'selbst verantwortlich sein',
    explanation: l('die Eigenverantwortung = personal responsibility.', 'die Eigenverantwortung = öz sorumluluk.', 'Eigenverantwortung.'),
    examples: ['… braucht viel **Eigenverantwortung**.'],
  },
  {
    id: 'build-kritiker',
    type: 'sentence_builder',
    topic: 'positionen',
    concept: 'pro-contra',
    skill: 'writing',
    difficulty: 3,
    chips: ['warnen', 'Kritiker', 'hingegen', 'vor ständiger Erreichbarkeit'],
    answers: [['Kritiker', 'warnen', 'hingegen', 'vor ständiger Erreichbarkeit'], ['Kritiker', 'hingegen', 'warnen', 'vor ständiger Erreichbarkeit']],
    translation: l('Critics, on the other hand, warn of constant availability.', 'Eleştirmenler ise sürekli ulaşılabilirliğe karşı uyarıyor.', 'Kritiker warnen hingegen vor ständiger Erreichbarkeit.'),
    explanation: l('warnen vor + dative.', 'warnen vor + Dativ.', 'warnen vor.'),
    examples: ['Kritiker **warnen** hingegen **vor** ständiger Erreichbarkeit.'],
  },
  {
    id: 'build-studie',
    type: 'sentence_builder',
    topic: 'flexibilitaet',
    concept: 'evidence',
    skill: 'writing',
    difficulty: 3,
    chips: ['dass die Produktivität', 'Studien zeigen,', 'gestiegen ist', 'in der Viertagewoche'],
    answers: [['Studien zeigen,', 'dass die Produktivität', 'in der Viertagewoche', 'gestiegen ist']],
    translation: l('Studies show that productivity has increased in the four-day week.', 'Araştırmalar dört günlük haftada verimliliğin arttığını gösteriyor.', 'Studien zeigen, dass die Produktivität in der Viertagewoche gestiegen ist.'),
    explanation: l('dass-clause: conjugated verb at the end.', 'dass yan cümlesi: çekimli fiil sonda.', 'dass.'),
    examples: ['…, dass die Produktivität … **gestiegen ist**.'],
  },
  {
    id: 'build-sinn',
    type: 'sentence_builder',
    topic: 'new-work',
    concept: 'values',
    skill: 'writing',
    difficulty: 3,
    chips: ['legen', 'Viele junge Menschen', 'auf Sinnhaftigkeit', 'großen Wert'],
    answers: [['Viele junge Menschen', 'legen', 'großen Wert', 'auf Sinnhaftigkeit']],
    translation: l('Many young people attach great importance to meaningful work.', 'Birçok genç anlamlılığa büyük önem veriyor.', 'Viele junge Menschen legen großen Wert auf Sinnhaftigkeit.'),
    explanation: l('Wert legen auf + accusative.', 'Wert legen auf + Akkusativ.', 'Wert legen auf.'),
    examples: ['Viele junge Menschen **legen** großen **Wert auf** Sinnhaftigkeit.'],
  },
  {
    id: 'fix-einerseits',
    type: 'error_correction',
    topic: 'positionen',
    concept: 'two-sides',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Einerseits ist das Modell flexibel, andererseits es ist schwer zu kontrollieren.',
    accepted: ['Einerseits ist das Modell flexibel, andererseits ist es schwer zu kontrollieren.'],
    explanation: l('andererseits takes position 1 → verb next.', 'andererseits 1. konumu alır → sonra fiil.', 'Verbposition.'),
    examples: ['…, andererseits **ist es** schwer zu kontrollieren.'],
  },
  {
    id: 'fix-warnen',
    type: 'error_correction',
    topic: 'positionen',
    concept: 'pro-contra',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Gewerkschaften warnen über die Entgrenzung der Arbeit.',
    accepted: ['Gewerkschaften warnen vor der Entgrenzung der Arbeit.'],
    explanation: l('warnen vor + dative.', 'warnen vor + Dativ.', 'vor.'),
    examples: ['Gewerkschaften warnen **vor der** Entgrenzung.'],
  },
  {
    id: 'fix-erreichbar',
    type: 'error_correction',
    topic: 'flexibilitaet',
    concept: 'availability',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Viele fühlen sich verpflichtet, ständig erreichbar sein.',
    accepted: ['Viele fühlen sich verpflichtet, ständig erreichbar zu sein.'],
    explanation: l('sich verpflichtet fühlen, … zu + infinitive.', 'sich verpflichtet fühlen, … zu + mastar.', 'zu sein.'),
    examples: ['…, ständig erreichbar **zu sein**.'],
  },
  {
    id: 'tr-viertage',
    type: 'translation',
    topic: 'flexibilitaet',
    concept: 'four-day-week',
    skill: 'writing',
    difficulty: 3,
    source: l('Some companies are testing the four-day week.', 'Bazı şirketler dört günlük haftayı deniyor.', 'Some companies are testing the four-day week.'),
    accepted: ['Einige Firmen testen die Viertagewoche.', 'Einige Unternehmen testen die Viertagewoche.', 'Manche Firmen testen die Viertagewoche.', 'Manche Unternehmen testen die Viertagewoche.', 'Einige Firmen erproben die Viertagewoche.'],
    explanation: l('die Viertagewoche testen / erproben.', 'die Viertagewoche testen / erproben.', 'Viertagewoche.'),
    examples: ['Einige Firmen **testen** die Viertagewoche.'],
  },
  {
    id: 'tr-vertrauen',
    type: 'translation',
    topic: 'new-work',
    concept: 'leadership',
    skill: 'writing',
    difficulty: 3,
    source: l('Managers should rely on trust instead of control.', 'Yöneticiler kontrol yerine güvene dayanmalı.', 'Managers should rely on trust instead of control.'),
    accepted: ['Führungskräfte sollten auf Vertrauen statt auf Kontrolle setzen.', 'Führungskräfte sollten auf Vertrauen statt Kontrolle setzen.', 'Führungskräfte sollten Vertrauen statt Kontrolle nutzen.'],
    explanation: l('setzen auf + accusative = to rely on.', 'setzen auf + Akkusativ = -e dayanmak.', 'setzen auf.'),
    examples: ['Führungskräfte sollten **auf Vertrauen** statt auf Kontrolle **setzen**.'],
  },
  {
    id: 'ordering-eroerterung',
    type: 'ordering',
    topic: 'positionen',
    concept: 'structure',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order the short discussion.', 'Kısa tartışma metnini sırala.', 'Ordne die Erörterung.'),
    items: ['Kritiker geben hingegen zu bedenken, dass die Grenze zwischen Arbeit und Freizeit verschwimmt.', 'Ist Homeoffice die Zukunft der Arbeit?', 'Abwägend lässt sich sagen: Mit klaren Regeln überwiegen die Vorteile.', 'Befürworter betonen, dass Beschäftigte Zeit und Geld für das Pendeln sparen.'],
    answer: ['Ist Homeoffice die Zukunft der Arbeit?', 'Befürworter betonen, dass Beschäftigte Zeit und Geld für das Pendeln sparen.', 'Kritiker geben hingegen zu bedenken, dass die Grenze zwischen Arbeit und Freizeit verschwimmt.', 'Abwägend lässt sich sagen: Mit klaren Regeln überwiegen die Vorteile.'],
    explanation: l('Question → pro → contra → balanced conclusion.', 'Soru → lehte → aleyhte → dengeli sonuç.', 'Erörterung.'),
  },
  {
    id: 'dialog-viertage',
    type: 'dialogue',
    topic: 'positionen',
    concept: 'nuance',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Kollege', de: 'Die Viertagewoche sollte sofort überall eingeführt werden!' }],
    options: ['Das klingt zwar verlockend, aber in der Pflege wäre das kaum umsetzbar.', 'Zwar das ist gut, aber nicht.', 'Ja, total, überall, sofort, immer.'],
    answer: 0,
    explanation: l('Agree partly, then name a limit: zwar … aber.', 'Kısmen katıl, sonra bir sınır belirt: zwar … aber.', 'differenziert.'),
  },
  {
    id: 'dialog-erreichbar',
    type: 'dialogue',
    topic: 'flexibilitaet',
    concept: 'boundaries',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Teamleiterin', de: 'Können Sie am Wochenende kurz auf Mails reagieren?' }],
    options: ['Ich würde das gern vermeiden. Könnten wir für Notfälle eine Vertretungsregel vereinbaren?', 'Nein. Tschüss.', 'Wochenende ich nicht erreichen.'],
    answer: 0,
    explanation: l('Set a boundary politely and suggest a solution.', 'Kibarca sınır çiz ve bir çözüm öner.', 'Grenze ziehen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-newwork',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Artikel?',
    options: ['Um Chancen und Risiken neuer Arbeitsmodelle.', 'Um die Geschichte der Gewerkschaften.', 'Um Büromöbel.'],
    answer: 0,
    explanation: l('„New Work – Freiheit oder Falle?“', '„New Work – Freiheit oder Falle?“', 'Chancen und Risiken.'),
  },
  {
    id: 'read-bergmann',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-newwork',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was wollte Frithjof Bergmann mit „New Work“ erreichen?',
    options: ['dass Menschen eine Arbeit tun, die sie wirklich wollen', 'dass alle mehr Überstunden machen', 'dass Büros abgeschafft werden'],
    answer: 0,
    explanation: l('„… Arbeit, die man wirklich, wirklich will.“', '„… Arbeit, die man wirklich, wirklich will.“', 'Sinn.'),
  },
  {
    id: 'read-umfrage',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-newwork',
    skill: 'reading',
    difficulty: 3,
    statement: 'Laut Umfrage beantwortet weniger als ein Drittel der Beschäftigten abends dienstliche Nachrichten.',
    answer: false,
    explanation: l('„… fast die Hälfte …“', '„… fast die Hälfte …“', 'falsch.'),
  },
  {
    id: 'read-fazit',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-newwork',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was ist laut Text entscheidend?',
    options: ['klare Regeln und eine Kultur, die Pausen respektiert', 'möglichst wenig Freiheit', 'eine Rückkehr zur Präsenzpflicht'],
    answer: 0,
    explanation: l('„Entscheidend sind klare Regeln …“', '„Entscheidend sind klare Regeln …“', 'Regeln.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-studie',
    type: 'listening_choice',
    topic: 'flexibilitaet',
    concept: 'evidence',
    skill: 'listening',
    difficulty: 3,
    audio: 'In dem Pilotprojekt arbeiteten die Beschäftigten nur vier Tage pro Woche – bei gleichem Gehalt. Die Krankmeldungen sanken um ein Drittel.',
    question: l('What was one result of the pilot?', 'Pilot projenin bir sonucu neydi?', 'Ergebnis?'),
    options: ['fewer sick days', 'lower salaries', 'more overtime'],
    answer: 0,
    explanation: l('Krankmeldungen sanken = sick notes decreased.', 'Krankmeldungen sanken = hastalık raporları azaldı.', 'weniger krank.'),
  },
  {
    id: 'listen-fuehrung',
    type: 'listening_choice',
    topic: 'new-work',
    concept: 'leadership',
    skill: 'listening',
    difficulty: 3,
    audio: 'Ich sehe mich weniger als Chefin, sondern eher als Coach. Mein Team entscheidet vieles selbst.',
    question: l('How does she see her role?', 'Rolünü nasıl görüyor?', 'Wie sieht sie ihre Rolle?'),
    options: ['as a coach', 'as a strict boss', 'as an observer only'],
    answer: 0,
    explanation: l('eher als Coach = rather as a coach.', 'eher als Coach = daha çok bir koç olarak.', 'Coach.'),
  },
  {
    id: 'listen-grenze',
    type: 'listening_choice',
    topic: 'flexibilitaet',
    concept: 'boundaries',
    skill: 'listening',
    difficulty: 3,
    audio: 'Seit ich zu Hause arbeite, klappe ich den Laptop um 18 Uhr zu. Sonst würde ich nie Feierabend machen.',
    question: l('Why does the speaker close the laptop at 6 pm?', 'Konuşan dizüstünü neden saat 18’de kapatıyor?', 'Warum um 18 Uhr?'),
    options: ['to separate work and free time', 'because the battery is empty', 'because the boss says so'],
    answer: 0,
    explanation: l('A clear end to avoid Entgrenzung.', 'Sınırların bulanıklaşmasını önlemek için net bir bitiş.', 'Feierabend.'),
  },
  {
    id: 'listen-kritik',
    type: 'listening_choice',
    topic: 'positionen',
    concept: 'pro-contra',
    skill: 'listening',
    difficulty: 3,
    audio: 'Flache Hierarchien sind zwar modern, doch am Ende weiß oft niemand, wer eigentlich entscheidet.',
    question: l('What is the criticism?', 'Eleştiri nedir?', 'Was ist die Kritik?'),
    options: ['Responsibilities are unclear.', 'Hierarchies are too steep.', 'Salaries are too low.'],
    answer: 0,
    explanation: l('zwar … doch: modern, but unclear responsibility.', 'zwar … doch: modern, ama sorumluluk belirsiz.', 'unklar.'),
  },

  ...nwDrills(),
]

export const UNIT_C1_11_NEW_WORK: CourseUnit = {
  level: 'C1',
  number: 11,
  slug: 'new-work',
  titleDe: 'Die Arbeitswelt von morgen',
  title: l('The working world of tomorrow', 'Yarının çalışma dünyası', 'Die Arbeitswelt von morgen'),
  goal: l(
    'By the end of this unit you can discuss new working models (New Work, Homeoffice, Viertagewoche), weigh flexibility against the blurring of boundaries and present positions in a nuanced way with einerseits … andererseits and zwar … aber.',
    'Bu ünitenin sonunda yeni çalışma modellerini (New Work, Homeoffice, Viertagewoche) tartışabilir, esnekliği sınırların bulanıklaşmasıyla tartabilir ve einerseits … andererseits ile zwar … aber kullanarak görüşleri dengeli biçimde sunabilirsin.',
    'Am Ende dieser Einheit diskutierst du differenziert über neue Arbeitsmodelle.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'new-work', label: l('New Work and leadership', 'New Work ve liderlik', 'New Work und Führung') },
    { key: 'flexibilitaet', label: l('Flexibility vs. blurred boundaries', 'Esneklik ve sınırların bulanıklaşması', 'Flexibilität vs. Entgrenzung') },
    { key: 'positionen', label: l('Presenting positions', 'Görüşleri sunmak', 'Positionen darstellen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Homeoffice, four-day week, flat hierarchies.', 'Evden çalışma, dört günlük hafta, düz hiyerarşiler.', 'Neue Arbeitswelt.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('What is New Work?', 'New Work nedir?', 'Was ist New Work?'),
          body: l(
            'The philosopher Frithjof Bergmann coined the term: work should be meaningful and self-determined. Today it stands for flexible hours, Homeoffice, flat hierarchies and leaders who coach rather than control.',
            'Terimi filozof Frithjof Bergmann ortaya attı: iş anlamlı ve kendi belirlediğimiz biçimde olmalı. Bugün esnek saatler, evden çalışma, düz hiyerarşiler ve kontrol etmek yerine koçluk yapan yöneticiler anlamına geliyor.',
            'New Work.'
          ),
          table: {
            head: [l('Traditional', 'Geleneksel', 'Klassisch'), l('New Work', 'New Work', 'New Work')],
            rows: [
              ['Präsenzpflicht', 'Homeoffice / mobiles Arbeiten'],
              ['feste Arbeitszeiten', 'Vertrauensarbeitszeit'],
              ['steile Hierarchien', 'flache Hierarchien'],
              ['Kontrolle', 'Vertrauen und Eigenverantwortung'],
            ],
          },
        },
        {
          title: l('Presenting both sides', 'İki tarafı sunmak', 'Beide Seiten darstellen'),
          body: l(
            'At C1 you show nuance: einerseits … andererseits (two sides), zwar … aber / doch (concession), Befürworter betonen … / Kritiker geben zu bedenken … (positions of others), abwägend lässt sich sagen … (balanced conclusion).',
            'C1’de dengeli düşünce gösterirsin: einerseits … andererseits (iki taraf), zwar … aber / doch (kabul), Befürworter betonen … / Kritiker geben zu bedenken … (başkalarının görüşleri), abwägend lässt sich sagen … (dengeli sonuç).',
            'differenziert.'
          ),
          examples: [
            { de: '**Einerseits** spart man Zeit, **andererseits** fehlt der Kontakt.', translation: l('On the one hand you save time, on the other hand contact is missing.', 'Bir yandan zaman kazanılır, öte yandan iletişim eksik kalır.', '') },
            { de: 'Das Modell ist **zwar** flexibel, **aber** schwer umzusetzen.', translation: l('The model is flexible, admittedly, but difficult to implement.', 'Model gerçi esnek ama uygulaması zor.', '') },
          ],
        },
        {
          title: l('The risk: Entgrenzung', 'Risk: sınırların bulanıklaşması', 'Das Risiko: Entgrenzung'),
          body: l(
            'Flexibility can blur the line between work and free time: emails in the evening, constant availability, exhaustion. Clear rules (e.g. no emails after 6 pm) help.',
            'Esneklik iş ile boş zaman arasındaki sınırı bulanıklaştırabilir: akşam e-postaları, sürekli ulaşılabilirlik, tükenmişlik. Net kurallar (ör. 18:00’den sonra e-posta yok) yardımcı olur.',
            'Entgrenzung.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A radio discussion about the four-day week.', 'Dört günlük hafta hakkında bir radyo tartışması.', 'Radiodiskussion.'),
      dialogue: [
        { speaker: 'Moderator', de: 'Frau Albers, Ihre Firma testet die **Viertagewoche**. Mit welchem Ergebnis?', translation: l('Ms Albers, your company is testing the four-day week. With what result?', 'Bayan Albers, şirketiniz dört günlük haftayı deniyor. Sonuç ne?', '') },
        { speaker: 'Frau Albers', de: 'Die Mitarbeitenden sind motivierter, und die **Produktivität** ist sogar gestiegen.', translation: l('Employees are more motivated, and productivity has even risen.', 'Çalışanlar daha motive ve verimlilik bile arttı.', '') },
        { speaker: 'Herr Kunz', de: 'Das ist **zwar** erfreulich, **aber** in der Pflege oder im Handel kaum umsetzbar.', translation: l('That is pleasing, admittedly, but hardly feasible in care or retail.', 'Bu gerçi sevindirici ama bakım ya da perakende sektöründe neredeyse uygulanamaz.', '') },
        { speaker: 'Frau Albers', de: 'Natürlich passt das Modell nicht überall. **Einerseits** braucht es Planung, **andererseits** gewinnen wir neue Fachkräfte.', translation: l('Of course the model doesn’t fit everywhere. On the one hand it needs planning, on the other hand we gain new skilled workers.', 'Tabii model her yere uymaz. Bir yandan planlama gerektiriyor, öte yandan yeni nitelikli çalışanlar kazanıyoruz.', '') },
        { speaker: 'Herr Kunz', de: 'Ich **gebe** außerdem **zu bedenken**, dass viele dann an vier Tagen zehn Stunden arbeiten.', translation: l('I would also point out that many then work ten hours on four days.', 'Ayrıca şunu hatırlatmak isterim: birçoğu o zaman dört gün on saat çalışıyor.', '') },
        { speaker: 'Moderator', de: 'Also eine Frage der **Ausgestaltung**. Vielen Dank Ihnen beiden.', translation: l('So a question of how it is designed. Thank you both.', 'Yani bir uygulama biçimi meselesi. İkinize de teşekkürler.', '') },
      ],
      examples: [
        { de: '**Befürworter** betonen die Freiheit.', translation: l('Supporters emphasise freedom.', 'Savunucular özgürlüğü vurguluyor.', '') },
        { de: '**Kritiker** warnen vor **Entgrenzung**.', translation: l('Critics warn of blurred boundaries.', 'Eleştirmenler sınırların bulanıklaşmasına karşı uyarıyor.', '') },
        { de: 'Bei uns gilt **Vertrauensarbeitszeit**.', translation: l('We have trust-based working hours.', 'Bizde güvene dayalı çalışma saati geçerli.', '') },
        { de: 'Viele fühlen sich gezwungen, **ständig erreichbar** zu sein.', translation: l('Many feel forced to be constantly reachable.', 'Birçoğu sürekli ulaşılabilir olmak zorunda hissediyor.', '') },
        { de: 'Junge Menschen legen Wert auf **Sinnhaftigkeit**.', translation: l('Young people value meaningful work.', 'Gençler anlamlılığa önem veriyor.', '') },
        { de: '**Abwägend lässt sich sagen**, dass …', translation: l('Weighing everything up, one can say that …', 'Her şeyi tartınca şunu söyleyebiliriz: …', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Terms and positions of the debate.', 'Tartışmanın terimleri ve görüşleri.', 'Begriffe und Positionen.'),
      exercises: ['match-begriffe', 'sort-pro-contra', 'nw-einerseits', 'nw-entgrenzung', 'nw-befuerworter', 'mc-differenziert', 'tf-vertrauen', 'select-fuehrung', 'image-homeoffice'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Argue in a nuanced way.', 'Dengeli biçimde tartış.', 'Differenziert argumentieren.'),
      exercises: [
        'fill-zwar',
        'fill-andererseits',
        'fill-eigenverantwortung',
        'build-kritiker',
        'build-studie',
        'build-sinn',
        'fix-einerseits',
        'fix-warnen',
        'fix-erreichbar',
        'tr-viertage',
        'tr-vertrauen',
        'ordering-eroerterung',
        'dialog-viertage',
        'dialog-erreichbar',
        'nw-bedenken',
        'nw-erreichbar',
        'nw-zwar',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A newspaper article about New Work.', 'New Work hakkında bir gazete makalesi.', 'Ein Zeitungsartikel.'),
      passage: [
        '**New Work – Freiheit oder Falle?** Der Begriff geht auf den Philosophen Frithjof Bergmann zurück. Sein Ziel: Menschen sollten eine Arbeit tun, „die sie wirklich, wirklich wollen“.',
        'Heute verbinden viele mit New Work vor allem **Homeoffice**, **Vertrauensarbeitszeit** und **flache Hierarchien**. Befürworter betonen, dass Beschäftigte dadurch selbstbestimmter und motivierter arbeiten.',
        'Kritiker geben **hingegen** zu bedenken, dass die Grenzen verschwimmen. Laut einer aktuellen Umfrage beantwortet fast die Hälfte der Beschäftigten auch abends dienstliche Nachrichten.',
        '**Entscheidend sind** daher klare Regeln und eine Unternehmenskultur, die Pausen respektiert. Nur so wird Freiheit nicht zur Falle.',
      ],
      glossary: [
        { de: 'zurückgehen auf', note: l('to go back to, originate from', '-e dayanmak', 'stammen von') },
        { de: 'verschwimmen', note: l('to blur', 'bulanıklaşmak', 'unklar werden') },
        { de: 'dienstlich', note: l('work-related', 'işle ilgili', 'beruflich') },
        { de: 'die Falle', note: l('trap', 'tuzak', 'Gefahr') },
      ],
      exercises: ['read-thema', 'read-bergmann', 'read-umfrage', 'read-fazit'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Voices from the new working world.', 'Yeni çalışma dünyasından sesler.', 'Stimmen zur Arbeitswelt.'),
      exercises: ['listen-studie', 'listen-fuehrung', 'listen-grenze', 'listen-kritik'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Should Homeoffice become a legal right? Present both sides and give your own view.', 'Evden çalışma yasal bir hak olmalı mı? İki tarafı sun ve kendi görüşünü belirt.', 'Recht auf Homeoffice?'),
      points: [
        l('Supporters: „Befürworter betonen, …“', 'Savunucular: „Befürworter betonen, …“', 'pro'),
        l('Critics: „Kritiker geben zu bedenken, …“', 'Eleştirmenler: „Kritiker geben zu bedenken, …“', 'contra'),
        l('A concession: „zwar … aber“', 'Bir kabul: „zwar … aber“', 'zwar'),
        l('Your conclusion: „Abwägend …“', 'Sonucun: „Abwägend …“', 'Fazit'),
      ],
      model: [
        'Befürworter betonen, dass ein Recht auf Homeoffice die Vereinbarkeit von Familie und Beruf verbessert.',
        'Kritiker geben hingegen zu bedenken, dass nicht jede Tätigkeit von zu Hause möglich ist.',
        'Ein solches Gesetz wäre zwar ein starkes Signal, aber es müsste viele Ausnahmen enthalten.',
        'Abwägend halte ich ein Recht auf zwei Homeoffice-Tage pro Woche für sinnvoll.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short discussion (at least 6 sentences): „Die Viertagewoche – ein Modell für alle?“ Present both sides and draw a balanced conclusion.',
        'Kısa bir tartışma yazısı yaz (en az 6 cümle): „Die Viertagewoche – ein Modell für alle?“ İki tarafı sun ve dengeli bir sonuca var.',
        'Erörterung (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Two sides (einerseits … andererseits / zwar … aber)', 'İki taraf (einerseits … andererseits / zwar … aber)', 'zwei Seiten'), pattern: '([Ee]inerseits|\\bzwar\\b)' },
        { label: l('Positions of others (Befürworter, Kritiker, Gegner)', 'Başkalarının görüşleri (Befürworter, Kritiker, Gegner)', 'Positionen'), pattern: '(Befürworter|Kritiker|Gegner)' },
        { label: l('A conclusion (abwägend, insgesamt, zusammenfassend)', 'Bir sonuç (abwägend, insgesamt, zusammenfassend)', 'Fazit'), pattern: '([Aa]bwägend|[Ii]nsgesamt|[Zz]usammenfassend|[Aa]bschließend)' },
      ],
      model: [
        'Immer mehr Unternehmen testen die Viertagewoche.',
        'Befürworter betonen, dass die Beschäftigten erholter und motivierter sind.',
        'Kritiker geben hingegen zu bedenken, dass sich die Arbeit dann auf weniger Tage verdichtet.',
        'Einerseits zeigen Studien eine höhere Produktivität, andererseits fehlen Daten aus Pflege und Handel.',
        'Das Modell ist zwar attraktiv, aber nicht in jeder Branche umsetzbar.',
        'Abwägend lässt sich sagen, dass die Viertagewoche eine Chance ist, aber kein Modell für alle.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Nuanced positions – 60 seconds.', 'Dengeli görüşler – 60 saniye.', 'Positionen – 60 Sekunden.'),
      seconds: 60,
      pool: [...NW.map(([id]) => `nw-${id}`), 'mc-differenziert'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('New Work: Homeoffice, Vertrauensarbeitszeit, flache Hierarchien', 'New Work: Homeoffice, Vertrauensarbeitszeit, flache Hierarchien', 'New Work'),
      l('Entgrenzung = work spilling into free time', 'Entgrenzung = işin boş zamana taşması', 'Entgrenzung'),
      l('Nuance: einerseits … andererseits, zwar … aber', 'Dengeli ifade: einerseits … andererseits, zwar … aber', 'differenziert'),
      l('Positions: Befürworter betonen … / Kritiker geben zu bedenken …', 'Görüşler: Befürworter betonen … / Kritiker geben zu bedenken …', 'Positionen'),
    ],
    mistakes: [
      { wrong: '…, andererseits es ist schwer.', right: '…, andererseits ist es schwer.', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Verbposition.') },
      { wrong: 'Kritiker warnen über Stress.', right: 'Kritiker warnen vor Stress.', note: l('warnen vor + dative.', 'warnen vor + Dativ.', 'vor.') },
      { wrong: 'Zwar es ist gut, aber teuer.', right: 'Es ist zwar gut, aber teuer.', note: l('zwar usually stands in the middle field.', 'zwar genellikle orta alanda durur.', 'zwar.') },
      { wrong: 'Sie legen Wert für Sinn.', right: 'Sie legen Wert auf Sinn.', note: l('Wert legen auf.', 'Wert legen auf.', 'auf.') },
    ],
  },
}
