import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'dessen / deren', emoji: '🔗', translation: l('whose', '… -in (ilgi)', 'Relativpronomen im Genitiv'), example: 'Die Autorin, deren Roman ich lese, kommt nach Köln.' },
  { word: 'Letzterer / Letztere', emoji: '2️⃣', translation: l('the latter', 'sonuncusu', 'das zuletzt Genannte'), example: 'Ich traf Ben und Lisa. Letztere erzählte von ihrer Reise.' },
  { word: 'Ersterer / Erstere', emoji: '1️⃣', translation: l('the former', 'ilki', 'das zuerst Genannte'), example: 'Rom und Paris – Ersteres gefällt mir besser.' },
  { word: 'dies / das', emoji: '👉', translation: l('this (refers to a whole statement)', 'bu (bütün bir ifadeye atıf)', 'Verweis auf einen Satz'), example: 'Die Mieten steigen. Dies führt zu Protesten.' },
  { word: 'Erstens …, zweitens …', emoji: '🔢', translation: l('Firstly …, secondly …', 'Birincisi …, ikincisi …', 'Aufzählung'), example: 'Erstens ist es teuer, zweitens fehlt die Zeit.' },
  { word: 'hingegen', emoji: '↔️', translation: l('on the other hand, however', 'buna karşın', 'Gegensatz (Adverb)'), example: 'Er liebt Sport. Seine Schwester hingegen liest lieber.' },
  { word: 'darüber hinaus', emoji: '➕', translation: l('in addition', 'bunun ötesinde', 'außerdem'), example: 'Darüber hinaus spart man Zeit.' },
  { word: 'folglich', emoji: '➡️', translation: l('consequently', 'sonuç olarak', 'deshalb'), example: 'Es regnete, folglich fiel das Spiel aus.' },
  { word: 'im Folgenden', emoji: '⬇️', translation: l('in the following', 'aşağıda', 'danach im Text'), example: 'Im Folgenden werden drei Lösungen vorgestellt.' },
  { word: 'wie bereits erwähnt', emoji: '⬆️', translation: l('as already mentioned', 'daha önce belirtildiği gibi', 'Rückverweis'), example: 'Wie bereits erwähnt, sind die Kosten hoch.' },
  { word: 'der rote Faden', emoji: '🧵', translation: l('the common thread', 'ana fikir, tutarlılık', 'klare Struktur'), example: 'Dem Text fehlt der rote Faden.' },
  { word: 'Synonyme verwenden', emoji: '🔄', translation: l('to use synonyms', 'eş anlamlılar kullanmak', 'Wiederholungen vermeiden'), example: 'Statt „Auto“ immer wieder: Wagen, Fahrzeug.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Zusammenhang', gender: 'm', plural: 'die Zusammenhänge', translation: l('coherence, connection', 'bağlam, tutarlılık', 'Zusammenhang') },
  { word: 'Verweis', gender: 'm', plural: 'die Verweise', translation: l('reference', 'atıf', 'Verweis') },
  { word: 'Absatz', gender: 'm', plural: 'die Absätze', translation: l('paragraph', 'paragraf', 'Absatz') },
  { word: 'Übergang', gender: 'm', plural: 'die Übergänge', translation: l('transition', 'geçiş', 'Übergang') },
  { word: 'Wiederholung', gender: 'f', plural: 'die Wiederholungen', translation: l('repetition', 'tekrar', 'Wiederholung') },
  { word: 'Gliederung', gender: 'f', plural: 'die Gliederungen', translation: l('structure, outline', 'ana hatlar', 'Gliederung') },
  { word: 'Fahrzeug', gender: 'n', plural: 'die Fahrzeuge', translation: l('vehicle', 'taşıt', 'Fahrzeug') },
  { word: 'Leser', gender: 'm', plural: 'die Leser', translation: l('reader', 'okur', 'Leser') },
]

/** [id, sentence with gap, right, wrong] */
const KOH: [string, string, string, [string, string]][] = [
  ['dessen', 'Der Autor, ___ Buch ich gerade lese, kommt nächste Woche nach Köln.', 'dessen', ['deren', 'dem']],
  ['deren', 'Die Firma, ___ Gewinne stark gestiegen sind, stellt neue Leute ein.', 'deren', ['dessen', 'der']],
  ['dies', 'Die Mieten steigen seit Jahren. ___ führt zu großen Protesten.', 'Dies', ['Dieser', 'Diese']],
  ['erstens', '___ ist das Projekt zu teuer, zweitens fehlt uns die Zeit.', 'Erstens', ['Zuletzt', 'Schließlich']],
  ['hingegen', 'Peter liebt Fußball. Seine Schwester ___ interessiert sich nur für Musik.', 'hingegen', ['deshalb', 'außerdem']],
  ['folglich', 'Der Zug fiel aus, ___ kamen wir zu spät zur Konferenz.', 'folglich', ['hingegen', 'erstens']],
]

function kohDrills(): Exercise[] {
  return KOH.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `koh-${id}`,
      type: 'multiple_choice' as const,
      topic: 'verweise',
      concept: 'choose-link',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'dessen = whose (masc./neuter owner), deren = whose (fem./plural owner). dies refers to a whole statement. erstens … zweitens lists, hingegen contrasts, folglich concludes.',
        'dessen = … -in (eril/nötr sahip), deren = … -in (dişil/çoğul sahip). dies bütün bir ifadeye atıf yapar. erstens … zweitens sıralar, hingegen karşılaştırır, folglich sonuç bildirir.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-funktion',
    type: 'matching',
    topic: 'uebergaenge',
    concept: 'functions',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Match the linking word and its function.', 'Bağlantı kelimesini işleviyle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'darüber hinaus', right: 'ergänzen' },
      { left: 'hingegen', right: 'Gegensatz' },
      { left: 'folglich', right: 'Folge' },
      { left: 'wie bereits erwähnt', right: 'Rückverweis' },
      { left: 'im Folgenden', right: 'Vorverweis' },
    ],
    explanation: l('Linking words guide the reader through the text.', 'Bağlantı kelimeleri okuru metin boyunca yönlendirir.', 'Übergänge.'),
  },
  {
    id: 'sort-verweis',
    type: 'categorize',
    topic: 'verweise',
    concept: 'back-forward',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Does it point back or forward in the text?', 'Metinde geriye mi ileriye mi işaret ediyor?', 'Rück- oder Vorverweis?'),
    categories: ['zurück ⬆️', 'voraus ⬇️'],
    items: [
      { text: 'wie oben beschrieben', category: 0 },
      { text: 'im Folgenden', category: 1 },
      { text: 'Letzterer', category: 0 },
      { text: 'Folgendes ist zu beachten:', category: 1 },
      { text: 'dies', category: 0 },
      { text: 'wie unten dargestellt', category: 1 },
    ],
    explanation: l('Back-references connect to what was said; forward references announce what comes.', 'Geri atıflar söylenene bağlanır; ileri atıflar geleceği duyurur.', 'Verweise.'),
    practice: ['koh-dessen'],
  },
  {
    id: 'mc-letztere',
    type: 'multiple_choice',
    topic: 'verweise',
    concept: 'former-latter',
    skill: 'reading',
    difficulty: 3,
    prompt: '„Ich habe einen Hund und eine Katze. Letztere schläft den ganzen Tag.“ – Wer schläft?',
    options: ['die Katze', 'der Hund', 'beide'],
    answer: 0,
    explanation: l('Letztere = the latter (the last one mentioned, feminine) → die Katze.', 'Letztere = sonuncusu (en son anılan, dişil) → die Katze.', 'Letztere.'),
    practice: ['fill-dessen'],
  },
  {
    id: 'tf-wiederholung',
    type: 'true_false',
    topic: 'wiederholung',
    concept: 'synonyms',
    skill: 'writing',
    difficulty: 2,
    statement: 'In guten deutschen Texten vermeidet man es, dasselbe Nomen in jedem Satz zu wiederholen.',
    answer: true,
    explanation: l('Use pronouns, synonyms and reference words instead.', 'Bunun yerine zamirler, eş anlamlılar ve atıf kelimeleri kullan.', 'Synonyme.'),
  },
  {
    id: 'select-synonyme',
    type: 'multiple_select',
    topic: 'wiederholung',
    concept: 'synonyms',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which words can replace „Auto“ in a text? Select all.', 'Bir metinde „Auto“nun yerine hangi kelimeler kullanılabilir? Hepsini seç.', 'Synonyme für „Auto“?'),
    options: ['das Fahrzeug', 'der Wagen', 'das Fahrrad', 'der Pkw', 'die Straße'],
    answers: [0, 1, 3],
    explanation: l('Fahrzeug, Wagen, Pkw – but not Fahrrad or Straße.', 'Fahrzeug, Wagen, Pkw – Fahrrad ya da Straße değil.', 'Synonyme.'),
  },
  {
    id: 'image-faden',
    type: 'image_choice',
    topic: 'struktur',
    concept: 'coherence',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Ein guter Text hat einen roten Faden.',
    options: [
      { emoji: '🧵', label: 'roter Faden' },
      { emoji: '🧶', label: 'Wollknäuel' },
      { emoji: '🪡', label: 'Nadel' },
      { emoji: '✂️', label: 'Schere' },
    ],
    answer: 0,
    explanation: l('der rote Faden = a clear common thread.', 'der rote Faden = açık bir ana fikir.', 'roter Faden.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-dessen',
    type: 'fill_blank',
    topic: 'verweise',
    concept: 'relative-genitive',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das Unternehmen, ___ Chef zurückgetreten ist, sucht einen Nachfolger.',
    accepted: ['dessen'],
    base: 'das Unternehmen → Genitiv',
    explanation: l('Neuter owner → dessen.', 'Nötr sahip → dessen.', 'dessen.'),
    examples: ['Das Unternehmen, **dessen** Chef zurückgetreten ist, …'],
  },
  {
    id: 'fill-hinaus',
    type: 'fill_blank',
    topic: 'uebergaenge',
    concept: 'adding',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Das Konzept ist günstig. Darüber ___ ist es umweltfreundlich.',
    accepted: ['hinaus'],
    base: 'außerdem',
    explanation: l('darüber hinaus = in addition.', 'darüber hinaus = bunun ötesinde.', 'hinaus.'),
    examples: ['Darüber **hinaus** ist es umweltfreundlich.'],
  },
  {
    id: 'fill-erwaehnt',
    type: 'fill_blank',
    topic: 'uebergaenge',
    concept: 'back-reference',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Wie bereits ___, sind die Kosten das größte Problem.',
    accepted: ['erwähnt', 'gesagt', 'beschrieben'],
    base: 'Rückverweis',
    explanation: l('wie bereits erwähnt = as already mentioned.', 'wie bereits erwähnt = daha önce belirtildiği gibi.', 'erwähnt.'),
    examples: ['Wie bereits **erwähnt**, sind die Kosten …'],
  },
  {
    id: 'build-folgenden',
    type: 'sentence_builder',
    topic: 'struktur',
    concept: 'forward-reference',
    skill: 'writing',
    difficulty: 3,
    chips: ['werden', 'Im Folgenden', 'drei Lösungen', 'vorgestellt'],
    answers: [['Im Folgenden', 'werden', 'drei Lösungen', 'vorgestellt']],
    translation: l('In the following, three solutions are presented.', 'Aşağıda üç çözüm sunulmaktadır.', 'Im Folgenden werden drei Lösungen vorgestellt.'),
    explanation: l('Announce the structure with a forward reference.', 'Yapıyı ileri atıfla duyur.', 'Vorverweis.'),
    examples: ['**Im Folgenden** werden drei Lösungen vorgestellt.'],
  },
  {
    id: 'build-dies',
    type: 'sentence_builder',
    topic: 'verweise',
    concept: 'statement-reference',
    skill: 'grammar',
    difficulty: 3,
    chips: ['hat', 'Dies', 'schwere Folgen', 'für die Umwelt'],
    answers: [['Dies', 'hat', 'schwere Folgen', 'für die Umwelt'], ['Dies', 'hat', 'für die Umwelt', 'schwere Folgen']],
    translation: l('This has serious consequences for the environment.', 'Bunun çevre için ciddi sonuçları var.', 'Dies hat schwere Folgen für die Umwelt.'),
    explanation: l('dies refers to the whole previous statement.', 'dies önceki ifadenin tamamına atıf yapar.', 'dies.'),
    examples: ['**Dies** hat schwere Folgen für die Umwelt.'],
  },
  {
    id: 'build-hingegen',
    type: 'sentence_builder',
    topic: 'uebergaenge',
    concept: 'contrast',
    skill: 'grammar',
    difficulty: 3,
    chips: ['hingegen', 'sinken die Preise', 'In der Stadt steigen die Mieten,', 'auf dem Land'],
    answers: [['In der Stadt steigen die Mieten,', 'auf dem Land', 'sinken die Preise', 'hingegen'], ['In der Stadt steigen die Mieten,', 'auf dem Land', 'hingegen', 'sinken die Preise']],
    translation: l('In the city rents are rising, in the countryside, however, prices are falling.', 'Şehirde kiralar artıyor, kırsalda ise fiyatlar düşüyor.', 'In der Stadt steigen die Mieten, auf dem Land sinken die Preise hingegen.'),
    explanation: l('hingegen is an adverb – it can stand in the middle or at the end.', 'hingegen bir zarftır – ortada ya da sonda durabilir.', 'hingegen.'),
    examples: ['…, auf dem Land sinken die Preise **hingegen**.'],
  },
  {
    id: 'fix-deren',
    type: 'error_correction',
    topic: 'verweise',
    concept: 'relative-genitive',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Studentin, dessen Arbeit ausgezeichnet wurde, kommt aus Graz.',
    accepted: ['Die Studentin, deren Arbeit ausgezeichnet wurde, kommt aus Graz.'],
    explanation: l('Feminine owner → deren.', 'Dişil sahip → deren.', 'deren.'),
    examples: ['Die Studentin, **deren** Arbeit ausgezeichnet wurde, …'],
  },
  {
    id: 'fix-wiederholung',
    type: 'error_correction',
    topic: 'wiederholung',
    concept: 'synonyms',
    skill: 'writing',
    difficulty: 3,
    sentence: 'Das Auto ist neu. Das Auto ist schnell. Das Auto ist teuer.',
    accepted: ['Das Auto ist neu. Es ist schnell, aber teuer.', 'Das Auto ist neu, schnell und teuer.', 'Das neue Auto ist schnell, aber teuer.'],
    explanation: l('Avoid repetition: pronouns or combine sentences.', 'Tekrardan kaçın: zamir kullan ya da cümleleri birleştir.', 'Wiederholung vermeiden.'),
    examples: ['Das Auto ist neu. **Es** ist schnell, aber teuer.'],
  },
  {
    id: 'fix-dies',
    type: 'error_correction',
    topic: 'verweise',
    concept: 'statement-reference',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Viele Menschen arbeiten im Homeoffice. Dieser spart Zeit.',
    accepted: ['Viele Menschen arbeiten im Homeoffice. Dies spart Zeit.', 'Viele Menschen arbeiten im Homeoffice. Das spart Zeit.'],
    explanation: l('Reference to a whole statement → dies / das (neuter).', 'Bütün bir ifadeye atıf → dies / das (nötr).', 'Dies.'),
    examples: ['**Dies** spart Zeit.'],
  },
  {
    id: 'tr-letztere',
    type: 'translation',
    topic: 'verweise',
    concept: 'former-latter',
    skill: 'writing',
    difficulty: 3,
    source: l('I visited Rome and Paris. I liked the latter more.', 'Roma ve Paris’i ziyaret ettim. Sonuncusunu daha çok beğendim.', 'I visited Rome and Paris. I liked the latter more.'),
    accepted: ['Ich habe Rom und Paris besucht. Letzteres hat mir besser gefallen.', 'Ich habe Rom und Paris besucht. Letzteres gefiel mir besser.', 'Ich besuchte Rom und Paris. Letzteres hat mir besser gefallen.'],
    explanation: l('Cities are neuter → Letzteres.', 'Şehirler nötrdür → Letzteres.', 'Letzteres.'),
    examples: ['**Letzteres** hat mir besser gefallen.'],
  },
  {
    id: 'tr-folglich',
    type: 'translation',
    topic: 'uebergaenge',
    concept: 'consequence',
    skill: 'writing',
    difficulty: 2,
    source: l('It rained; consequently the match was cancelled.', 'Yağmur yağdı; sonuç olarak maç iptal edildi.', 'It rained; consequently the match was cancelled.'),
    accepted: ['Es regnete, folglich fiel das Spiel aus.', 'Es hat geregnet, folglich ist das Spiel ausgefallen.', 'Es regnete, folglich wurde das Spiel abgesagt.'],
    explanation: l('folglich + verb in position 2.', 'folglich + 2. konumda fiil.', 'folglich.'),
    examples: ['Es regnete, **folglich fiel** das Spiel aus.'],
  },
  {
    id: 'ordering-absatz',
    type: 'ordering',
    topic: 'struktur',
    concept: 'paragraph',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Order the paragraph so that it has a red thread.', 'Paragrafı tutarlı olacak şekilde sırala.', 'Ordne den Absatz.'),
    items: ['Erstens sparen die Beschäftigten den langen Arbeitsweg.', 'Immer mehr Firmen erlauben ihren Mitarbeitern, von zu Hause zu arbeiten.', 'Zusammenfassend lässt sich sagen, dass beide Seiten profitieren.', 'Zweitens können Unternehmen dadurch Bürokosten senken.'],
    answer: ['Immer mehr Firmen erlauben ihren Mitarbeitern, von zu Hause zu arbeiten.', 'Erstens sparen die Beschäftigten den langen Arbeitsweg.', 'Zweitens können Unternehmen dadurch Bürokosten senken.', 'Zusammenfassend lässt sich sagen, dass beide Seiten profitieren.'],
    explanation: l('Topic → first point → second point → conclusion.', 'Konu → birinci nokta → ikinci nokta → sonuç.', 'Gliederung.'),
  },
  {
    id: 'dialog-feedback',
    type: 'dialogue',
    topic: 'struktur',
    concept: 'feedback',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Kommilitonin', de: 'Kannst du mir sagen, was an meinem Essay nicht stimmt?' }],
    options: ['Die Ideen sind gut, aber es fehlt der rote Faden. Verbinde die Absätze mit Übergängen.', 'Fehlt Faden rot dein Essay.', 'Dein Essay hat zu viele roten Fäden gefehlt.'],
    answer: 0,
    explanation: l('Constructive feedback: good ideas, missing structure, concrete tip.', 'Yapıcı geri bildirim: iyi fikirler, eksik yapı, somut öneri.', 'Feedback.'),
  },
  {
    id: 'dialog-letzteres',
    type: 'dialogue',
    topic: 'verweise',
    concept: 'former-latter',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Freund', de: 'Willst du lieber ans Meer oder in die Berge?' }],
    options: ['Letzteres – ich wandere einfach lieber, als am Strand zu liegen.', 'Letzterer Berge ich will.', 'Die Letzte bitte in Meer.'],
    answer: 0,
    explanation: l('Letzteres refers to the second option (a whole idea → neuter).', 'Letzteres ikinci seçeneğe atıf yapar (bir fikir → nötr).', 'Letzteres.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Text?',
    options: ['Um Tipps, wie man zusammenhängende Texte schreibt.', 'Um die Geschichte des Buchdrucks.', 'Um eine Reise nach Italien.'],
    answer: 0,
    explanation: l('„Was macht einen guten Text aus?“', '„Was macht einen guten Text aus?“', 'Schreibtipps.'),
  },
  {
    id: 'read-gliederung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was sollte man laut Text zuerst tun?',
    options: ['eine klare Gliederung erstellen', 'sofort losschreiben', 'möglichst viele Fremdwörter sammeln'],
    answer: 0,
    explanation: l('„Erstens braucht jeder Text eine klare Gliederung.“', '„Erstens braucht jeder Text eine klare Gliederung.“', 'Gliederung.'),
  },
  {
    id: 'read-wiederholung',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 3,
    statement: 'Laut Text sollte man ein wichtiges Wort möglichst oft wiederholen.',
    answer: false,
    explanation: l('„Wiederholungen hingegen ermüden den Leser.“', '„Wiederholungen hingegen ermüden den Leser.“', 'falsch.'),
  },
  {
    id: 'read-leser',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-ratgeber',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Warum sind Übergänge wichtig?',
    options: ['Sie führen den Leser durch den Text.', 'Sie machen den Text länger.', 'Sie ersetzen die Gliederung.'],
    answer: 0,
    explanation: l('„Übergänge … führen den Leser sicher durch den Text.“', '„Übergänge … führen den Leser sicher durch den Text.“', 'Leserführung.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-letztere',
    type: 'listening_choice',
    topic: 'verweise',
    concept: 'former-latter',
    skill: 'listening',
    difficulty: 3,
    audio: 'Zur Wahl standen ein Tablet und ein Laptop. Ich habe mich für Letzteren entschieden, weil ich viel schreibe.',
    question: l('What did the speaker choose?', 'Konuşan neyi seçti?', 'Was wurde gewählt?'),
    options: ['the laptop', 'the tablet', 'neither'],
    answer: 0,
    explanation: l('Letzteren = the latter (der Laptop, accusative).', 'Letzteren = sonuncusu (der Laptop, Akkusativ).', 'Laptop.'),
  },
  {
    id: 'listen-deren',
    type: 'listening_choice',
    topic: 'verweise',
    concept: 'relative-genitive',
    skill: 'listening',
    difficulty: 3,
    audio: 'Wir suchen eine Wohnung für eine Familie, deren Haus bei dem Brand zerstört wurde.',
    question: l('What was destroyed?', 'Ne yok oldu?', 'Was wurde zerstört?'),
    options: ['the family’s house', 'the flat', 'a shop'],
    answer: 0,
    explanation: l('deren Haus = the family’s house.', 'deren Haus = ailenin evi.', 'Haus.'),
  },
  {
    id: 'listen-folgenden',
    type: 'listening_choice',
    topic: 'uebergaenge',
    concept: 'forward-reference',
    skill: 'listening',
    difficulty: 2,
    audio: 'Im Folgenden möchte ich Ihnen die drei wichtigsten Ergebnisse unserer Studie vorstellen.',
    question: l('What comes next in the talk?', 'Konuşmada sırada ne var?', 'Was kommt jetzt?'),
    options: ['the three main results', 'a coffee break', 'the questions from the audience'],
    answer: 0,
    explanation: l('im Folgenden = in what follows.', 'im Folgenden = aşağıda / şimdi.', 'Ergebnisse.'),
  },
  {
    id: 'listen-hingegen',
    type: 'listening_choice',
    topic: 'uebergaenge',
    concept: 'contrast',
    skill: 'listening',
    difficulty: 2,
    audio: 'In Norddeutschland regnet es heute viel. Im Süden hingegen scheint den ganzen Tag die Sonne.',
    question: l('What is the weather like in the south?', 'Güneyde hava nasıl?', 'Wetter im Süden?'),
    options: ['sunny all day', 'rainy', 'stormy'],
    answer: 0,
    explanation: l('hingegen marks the contrast with the north.', 'hingegen kuzeyle karşıtlığı gösterir.', 'sonnig.'),
  },

  ...kohDrills(),
]

export const UNIT_C1_08_TEXTKOHAERENZ: CourseUnit = {
  level: 'C1',
  number: 8,
  slug: 'textkohaerenz',
  titleDe: 'Ein roter Faden',
  title: l('A common thread', 'Bir ana fikir', 'Ein roter Faden'),
  goal: l(
    'By the end of this unit you can write coherent texts: you use reference words (dessen, deren, dies, Letzterer), structure paragraphs with transitions (erstens, darüber hinaus, hingegen, folglich) and avoid repetition with pronouns and synonyms.',
    'Bu ünitenin sonunda tutarlı metinler yazabilirsin: atıf kelimeleri (dessen, deren, dies, Letzterer) kullanır, paragrafları geçişlerle (erstens, darüber hinaus, hingegen, folglich) yapılandırır ve zamir ve eş anlamlılarla tekrardan kaçınırsın.',
    'Am Ende dieser Einheit schreibst du zusammenhängende Texte.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'verweise', label: l('Reference words', 'Atıf kelimeleri', 'Verweiswörter') },
    { key: 'uebergaenge', label: l('Transitions', 'Geçişler', 'Übergänge') },
    { key: 'wiederholung', label: l('Avoiding repetition', 'Tekrardan kaçınma', 'Wiederholungen vermeiden') },
    { key: 'struktur', label: l('Text structure', 'Metin yapısı', 'Textstruktur') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The small words that hold a text together.', 'Bir metni bir arada tutan küçük kelimeler.', 'Kleine Wörter, großer Zusammenhang.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Reference words', 'Atıf kelimeleri', 'Verweiswörter'),
          body: l(
            'They point to something already mentioned. dessen / deren = whose (owner masculine/neuter → dessen, feminine/plural → deren). dies / das = a whole previous statement. Ersterer / Letzterer = the former / the latter – the ending follows the gender of the noun.',
            'Daha önce anılan bir şeye işaret ederler. dessen / deren = … -in (sahip eril/nötr → dessen, dişil/çoğul → deren). dies / das = önceki ifadenin tamamı. Ersterer / Letzterer = ilki / sonuncusu – ek, ismin cinsiyetine göre değişir.',
            'Verweise.'
          ),
          table: {
            head: [l('Owner', 'Sahip', 'Besitzer'), l('Example', 'Örnek', 'Beispiel')],
            rows: [
              ['der Autor → dessen', 'der Autor, dessen Buch …'],
              ['das Kind → dessen', 'das Kind, dessen Mutter …'],
              ['die Firma → deren', 'die Firma, deren Chef …'],
              ['die Leute → deren', 'die Leute, deren Haus …'],
            ],
          },
        },
        {
          title: l('Transitions', 'Geçişler', 'Übergänge'),
          body: l(
            'Transitions show the logic between sentences: listing (erstens, zweitens, schließlich), adding (darüber hinaus, zudem), contrast (hingegen, dagegen), consequence (folglich, somit), references in the text (wie bereits erwähnt, im Folgenden). Adverbs at the start take the verb in position 2.',
            'Geçişler cümleler arasındaki mantığı gösterir: sıralama (erstens, zweitens, schließlich), ekleme (darüber hinaus, zudem), karşıtlık (hingegen, dagegen), sonuç (folglich, somit), metin içi atıflar (wie bereits erwähnt, im Folgenden). Başta duran zarflardan sonra fiil 2. konumdadır.',
            'Übergänge.'
          ),
          examples: [
            { de: '**Darüber hinaus** spart man Zeit.', translation: l('In addition, you save time.', 'Bunun ötesinde zaman kazanılır.', '') },
            { de: 'Es regnete, **folglich** fiel das Spiel aus.', translation: l('It rained, so the game was cancelled.', 'Yağmur yağdı, sonuç olarak maç iptal edildi.', '') },
          ],
        },
        {
          title: l('Avoiding repetition', 'Tekrardan kaçınma', 'Wiederholungen vermeiden'),
          body: l(
            'German style avoids repeating the same noun. Use pronouns (es, sie), synonyms (das Auto → der Wagen, das Fahrzeug) or more general words (die Maßnahme, dieser Schritt).',
            'Alman üslubu aynı ismi tekrar etmekten kaçınır. Zamirler (es, sie), eş anlamlılar (das Auto → der Wagen, das Fahrzeug) ya da daha genel kelimeler (die Maßnahme, dieser Schritt) kullan.',
            'Synonyme.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A writing tutor gives feedback on a student’s essay.', 'Bir yazma eğitmeni bir öğrencinin denemesine geri bildirim veriyor.', 'In der Schreibberatung.'),
      dialogue: [
        { speaker: 'Tutorin', de: 'Ihre Argumente sind stark, aber der Text wirkt etwas sprunghaft.', translation: l('Your arguments are strong, but the text feels a bit jumpy.', 'Argümanlarınız güçlü ama metin biraz kopuk görünüyor.', '') },
        { speaker: 'Jonas', de: 'Was kann ich da machen?', translation: l('What can I do about that?', 'Bu konuda ne yapabilirim?', '') },
        { speaker: 'Tutorin', de: 'Verbinden Sie die Absätze. Zum Beispiel: „**Darüber hinaus** …“ oder „**Wie bereits erwähnt** …“.', translation: l('Connect the paragraphs. For example: „In addition …“ or „As already mentioned …“.', 'Paragrafları birbirine bağlayın. Örneğin: „Bunun ötesinde …“ ya da „Daha önce belirtildiği gibi …“.', '') },
        { speaker: 'Jonas', de: 'Und hier wiederhole ich dreimal „Klimawandel“.', translation: l('And here I repeat „climate change“ three times.', 'Burada da üç kez „iklim değişikliği“ yazmışım.', '') },
        { speaker: 'Tutorin', de: 'Genau. Schreiben Sie beim zweiten Mal „**dieses Problem**“ und beim dritten Mal „**die Erderwärmung**“.', translation: l('Exactly. The second time write „this problem“ and the third time „global warming“.', 'Evet. İkinci seferde „bu sorun“, üçüncüde „küresel ısınma“ yazın.', '') },
        { speaker: 'Jonas', de: 'Super. **Dies** macht den Text sofort flüssiger.', translation: l('Great. That makes the text more fluent right away.', 'Harika. Bu metni hemen daha akıcı yapıyor.', '') },
      ],
      examples: [
        { de: 'Die Autorin, **deren** Roman ich lese, …', translation: l('The author whose novel I’m reading …', 'Romanını okuduğum yazar …', '') },
        { de: 'Die Preise steigen. **Dies** belastet viele Familien.', translation: l('Prices are rising. This puts a strain on many families.', 'Fiyatlar artıyor. Bu birçok aileyi zorluyor.', '') },
        { de: 'Ben und Lisa kamen. **Letztere** brachte Kuchen mit.', translation: l('Ben and Lisa came. The latter brought cake.', 'Ben ve Lisa geldi. Sonuncusu pasta getirdi.', '') },
        { de: '**Erstens** …, **zweitens** …, **schließlich** …', translation: l('Firstly …, secondly …, finally …', 'Birincisi …, ikincisi …, son olarak …', '') },
        { de: 'Er arbeitet viel. Sie **hingegen** hat Zeit.', translation: l('He works a lot. She, however, has time.', 'O çok çalışıyor. Kadının ise zamanı var.', '') },
        { de: '**Im Folgenden** werden die Ergebnisse dargestellt.', translation: l('In the following, the results are presented.', 'Aşağıda sonuçlar sunulmaktadır.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Spot the connections.', 'Bağlantıları fark et.', 'Verbindungen erkennen.'),
      exercises: ['match-funktion', 'sort-verweis', 'koh-dessen', 'koh-deren', 'koh-dies', 'mc-letztere', 'tf-wiederholung', 'select-synonyme', 'image-faden'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Connect sentences and paragraphs.', 'Cümleleri ve paragrafları bağla.', 'Sätze verbinden.'),
      exercises: [
        'fill-dessen',
        'fill-hinaus',
        'fill-erwaehnt',
        'build-folgenden',
        'build-dies',
        'build-hingegen',
        'fix-deren',
        'fix-wiederholung',
        'fix-dies',
        'tr-letztere',
        'tr-folglich',
        'ordering-absatz',
        'dialog-feedback',
        'dialog-letzteres',
        'koh-erstens',
        'koh-hingegen',
        'koh-folglich',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A guide for better texts.', 'Daha iyi metinler için bir rehber.', 'Ein Schreibratgeber.'),
      passage: [
        '**Was macht einen guten Text aus?** – Viele Studierende haben gute Ideen, **deren** Wirkung jedoch verpufft, weil der Text keinen roten Faden hat.',
        '**Erstens** braucht jeder Text eine klare Gliederung: Einleitung, Hauptteil und Schluss. **Dies** klingt banal, wird aber oft vergessen.',
        '**Zweitens** sind Übergänge entscheidend. Wörter wie „**darüber hinaus**“ oder „**folglich**“ führen den Leser sicher durch den Text.',
        '**Schließlich** sollte man auf Abwechslung achten. Synonyme und Pronomen machen einen Text lebendig; Wiederholungen **hingegen** ermüden den Leser.',
      ],
      glossary: [
        { de: 'verpuffen', note: l('to fizzle out', 'boşa gitmek', 'wirkungslos bleiben') },
        { de: 'banal', note: l('trivial', 'basit, sıradan', 'selbstverständlich') },
        { de: 'entscheidend', note: l('crucial', 'belirleyici', 'sehr wichtig') },
        { de: 'ermüden', note: l('to tire', 'yormak', 'müde machen') },
      ],
      exercises: ['read-thema', 'read-gliederung', 'read-wiederholung', 'read-leser'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('References and transitions in talks and reports.', 'Konuşma ve haberlerde atıflar ve geçişler.', 'Verweise hören.'),
      exercises: ['listen-letztere', 'listen-deren', 'listen-folgenden', 'listen-hingegen'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Give a short structured statement: Should cities ban cars from the centre?', 'Kısa ve yapılandırılmış bir görüş bildir: Şehirler merkezde arabaları yasaklamalı mı?', 'Strukturierte Stellungnahme.'),
      points: [
        l('Introduce the topic: „Im Folgenden …“', 'Konuyu tanıt: „Im Folgenden …“', 'Einleitung'),
        l('Two arguments: „Erstens … Zweitens …“', 'İki argüman: „Erstens … Zweitens …“', 'Argumente'),
        l('A contrast: „… hingegen …“', 'Bir karşıtlık: „… hingegen …“', 'Gegensatz'),
        l('A conclusion: „Folglich …“', 'Bir sonuç: „Folglich …“', 'Schluss'),
      ],
      model: [
        'Im Folgenden möchte ich kurz erklären, warum ich für autofreie Innenstädte bin.',
        'Erstens wird die Luft sauberer. Zweitens gewinnen Fußgänger und Radfahrer Platz.',
        'Viele Händler befürchten hingegen, dass weniger Kunden kommen.',
        'Studien zeigen jedoch das Gegenteil. Folglich überwiegen die Vorteile.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short, well-structured paragraph (at least 6 sentences) on the topic „Online-Unterricht“. Use transitions and at least one reference word.',
        '„Online-Unterricht“ konusunda kısa ve iyi yapılandırılmış bir paragraf yaz (en az 6 cümle). Geçişler ve en az bir atıf kelimesi kullan.',
        'Strukturierter Absatz (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('A listing (erstens / zweitens / schließlich)', 'Bir sıralama (erstens / zweitens / schließlich)', 'Aufzählung'), pattern: '([Ee]rstens|[Zz]weitens|[Ss]chließlich)' },
        { label: l('A transition (darüber hinaus, hingegen, folglich, zudem)', 'Bir geçiş (darüber hinaus, hingegen, folglich, zudem)', 'Übergang'), pattern: '([Dd]arüber hinaus|[Hh]ingegen|[Ff]olglich|[Zz]udem|[Ss]omit|[Dd]agegen)' },
        { label: l('A reference word (dies, dessen, deren, Letzteres)', 'Bir atıf kelimesi (dies, dessen, deren, Letzteres)', 'Verweis'), pattern: '\\b([Dd]ies|[Dd]essen|[Dd]eren|[Ll]etzter(e|er|es|en)?|[Ee]rster(e|er|es|en)?)\\b' },
      ],
      model: [
        'Online-Unterricht ist seit einigen Jahren an vielen Schulen üblich.',
        'Erstens können Schüler von überall aus teilnehmen.',
        'Zweitens lassen sich viele Materialien digital besser nutzen.',
        'Der persönliche Kontakt fehlt hingegen oft, und dies kann die Motivation senken.',
        'Darüber hinaus haben nicht alle Familien eine gute Internetverbindung.',
        'Folglich sollte Online-Unterricht den Präsenzunterricht ergänzen, aber nicht ersetzen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Pick the right link – 60 seconds.', 'Doğru bağlantıyı seç – 60 saniye.', 'Verbindung wählen – 60 Sekunden.'),
      seconds: 60,
      pool: [...KOH.map(([id]) => `koh-${id}`), 'mc-letztere'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('dessen (der/das) / deren (die/plural) = whose', 'dessen (der/das) / deren (die/çoğul) = … -in', 'dessen / deren'),
      l('dies refers to a whole statement; Ersterer / Letzterer', 'dies bütün bir ifadeye atıf yapar; Ersterer / Letzterer', 'Verweise'),
      l('Transitions: erstens, darüber hinaus, hingegen, folglich', 'Geçişler: erstens, darüber hinaus, hingegen, folglich', 'Übergänge'),
      l('Avoid repetition: pronouns and synonyms', 'Tekrardan kaçın: zamirler ve eş anlamlılar', 'Synonyme'),
    ],
    mistakes: [
      { wrong: 'Die Studentin, dessen Arbeit …', right: 'Die Studentin, deren Arbeit …', note: l('Feminine owner → deren.', 'Dişil sahip → deren.', 'deren.') },
      { wrong: 'Die Preise steigen. Dieser belastet uns.', right: 'Die Preise steigen. Dies belastet uns.', note: l('Whole statement → dies.', 'Bütün ifade → dies.', 'dies.') },
      { wrong: 'Folglich das Spiel fiel aus.', right: 'Folglich fiel das Spiel aus.', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Verbposition.') },
      { wrong: 'Das Auto ist neu. Das Auto ist schnell.', right: 'Das Auto ist neu. Es ist schnell.', note: l('Avoid repetition.', 'Tekrardan kaçın.', 'Pronomen.') },
    ],
  },
}
