import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'zur Verfügung stellen', emoji: '🎁', translation: l('to make available', 'kullanıma sunmak', '= bereitstellen'), example: 'Die Firma stellt allen Mitarbeitern einen Laptop zur Verfügung.' },
  { word: 'in Kraft treten', emoji: '📜', translation: l('to come into force', 'yürürlüğe girmek', 'gültig werden'), example: 'Das neue Gesetz tritt im Januar in Kraft.' },
  { word: 'Kritik üben an', emoji: '☝️', translation: l('to criticise', 'eleştirmek', '= kritisieren'), example: 'Die Opposition übte scharfe Kritik an dem Plan.' },
  { word: 'Rücksicht nehmen auf', emoji: '🤝', translation: l('to show consideration for', '… -i dikkate almak', 'beachten'), example: 'Bitte nehmen Sie Rücksicht auf die Nachbarn.' },
  { word: 'eine Entscheidung treffen', emoji: '⚖️', translation: l('to make a decision', 'karar vermek', '= entscheiden'), example: 'Wir müssen bald eine Entscheidung treffen.' },
  { word: 'zum Ausdruck bringen', emoji: '💬', translation: l('to express', 'ifade etmek', '= ausdrücken'), example: 'Sie brachte ihre Enttäuschung deutlich zum Ausdruck.' },
  { word: 'in Frage kommen', emoji: '❓', translation: l('to be an option', 'söz konusu olmak', 'möglich sein'), example: 'Ein Umzug kommt für uns nicht in Frage.' },
  { word: 'Bescheid geben / sagen', emoji: '📣', translation: l('to let someone know', 'haber vermek', 'informieren'), example: 'Gib mir bitte Bescheid, wenn du ankommst.' },
  { word: 'zur Sprache bringen', emoji: '🗣️', translation: l('to raise (a topic)', 'gündeme getirmek', 'ansprechen'), example: 'Ich möchte ein Problem zur Sprache bringen.' },
  { word: 'Einfluss nehmen auf', emoji: '🎯', translation: l('to influence', 'etkilemek', '= beeinflussen'), example: 'Lobbyisten nehmen Einfluss auf die Politik.' },
  { word: 'in Anspruch nehmen', emoji: '🙋', translation: l('to make use of, take up', 'yararlanmak', 'nutzen'), example: 'Sie können eine kostenlose Beratung in Anspruch nehmen.' },
  { word: 'zu Ende bringen', emoji: '🏁', translation: l('to finish', 'bitirmek', '= beenden'), example: 'Ich möchte das Projekt erst zu Ende bringen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Verfügung', gender: 'f', translation: l('disposal', 'kullanım', 'Verfügung') },
  { word: 'Kraft', gender: 'f', plural: 'die Kräfte', translation: l('force', 'güç, yürürlük', 'Kraft') },
  { word: 'Rücksicht', gender: 'f', translation: l('consideration', 'saygı, dikkate alma', 'Rücksicht') },
  { word: 'Ausdruck', gender: 'm', plural: 'die Ausdrücke', translation: l('expression', 'ifade', 'Ausdruck') },
  { word: 'Anspruch', gender: 'm', plural: 'die Ansprüche', translation: l('claim', 'hak, talep', 'Anspruch') },
  { word: 'Einfluss', gender: 'm', plural: 'die Einflüsse', translation: l('influence', 'etki', 'Einfluss') },
  { word: 'Bescheid', gender: 'm', plural: 'die Bescheide', translation: l('notice, information', 'haber, bildirim', 'Bescheid') },
  { word: 'Gefüge', gender: 'n', plural: 'die Gefüge', translation: l('structure', 'yapı', 'Gefüge') },
]

/** [id, noun phrase with gap, right verb, wrong] */
const FVG: [string, string, string, [string, string]][] = [
  ['kritik', 'Kritik ___ (= kritisieren)', 'üben', ['machen', 'geben']],
  ['entscheidung', 'eine Entscheidung ___ (= entscheiden)', 'treffen', ['machen', 'stellen']],
  ['ruecksicht', 'Rücksicht ___ (= beachten)', 'nehmen', ['geben', 'tun']],
  ['kraft', 'in Kraft ___ (= gültig werden)', 'treten', ['gehen', 'kommen']],
  ['ausdruck', 'zum Ausdruck ___ (= ausdrücken)', 'bringen', ['nehmen', 'stellen']],
  ['verfuegung', 'zur Verfügung ___ (= bereitstellen)', 'stellen', ['bringen', 'treten']],
]

function fvgDrills(): Exercise[] {
  return FVG.map(([id, phrase, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `fvg-${id}`,
      type: 'multiple_choice' as const,
      topic: 'kollokationen',
      concept: 'choose-verb',
      skill: 'vocabulary' as const,
      difficulty: 3 as const,
      prompt: phrase,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Fixed combination: the verb cannot be exchanged → ${right}. Learn noun + verb together.`,
        `Kalıplaşmış birleşim: fiil değiştirilemez → ${right}. İsim + fiili birlikte öğren.`,
        `→ ${right}`
      ),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-verb',
    type: 'matching',
    topic: 'umformen',
    concept: 'fvg-to-verb',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the noun-verb combination with the simple verb.', 'İsim-fiil birleşimini basit fiille eşleştir.', 'Gefüge und Verb.'),
    pairs: [
      { left: 'Kritik üben', right: 'kritisieren' },
      { left: 'eine Entscheidung treffen', right: 'entscheiden' },
      { left: 'zum Ausdruck bringen', right: 'ausdrücken' },
      { left: 'Einfluss nehmen', right: 'beeinflussen' },
      { left: 'zu Ende bringen', right: 'beenden' },
    ],
    explanation: l('Many combinations have a simple verb equivalent.', 'Birçok birleşimin basit fiil karşılığı vardır.', 'Entsprechungen.'),
  },
  {
    id: 'sort-verb',
    type: 'categorize',
    topic: 'kollokationen',
    concept: 'verb-groups',
    skill: 'vocabulary',
    difficulty: 3,
    instructions: l('Which verb belongs to the noun?', 'İsme hangi fiil ait?', 'Welches Verb passt?'),
    categories: ['nehmen', 'bringen', 'stellen'],
    items: [
      { text: 'Rücksicht …', category: 0 },
      { text: 'zur Sprache …', category: 1 },
      { text: 'zur Verfügung …', category: 2 },
      { text: 'in Anspruch …', category: 0 },
      { text: 'zu Ende …', category: 1 },
      { text: 'eine Frage …', category: 2 },
    ],
    explanation: l('nehmen, bringen and stellen are typical function verbs.', 'nehmen, bringen ve stellen tipik işlev fiilleridir.', 'Funktionsverben.'),
    practice: ['fvg-kritik'],
  },
  {
    id: 'mc-kraft',
    type: 'multiple_choice',
    topic: 'kontext',
    concept: 'legal',
    skill: 'grammar',
    difficulty: 3,
    prompt: 'Die neue Regelung ___ am 1. Januar in Kraft.',
    options: ['tritt', 'geht', 'bringt'],
    answer: 0,
    explanation: l('in Kraft treten = come into force (legal language).', 'in Kraft treten = yürürlüğe girmek (hukuk dili).', 'tritt.'),
    examples: ['Die neue Regelung **tritt** am 1. Januar in Kraft.'],
    practice: ['fill-verfuegung'],
  },
  {
    id: 'tf-stil',
    type: 'true_false',
    topic: 'kontext',
    concept: 'register',
    skill: 'reading',
    difficulty: 2,
    statement: 'Funktionsverbgefüge findet man besonders häufig in formellen und schriftlichen Texten.',
    answer: true,
    explanation: l('Typical for official, legal and journalistic texts.', 'Resmî, hukuki ve gazetecilik metinlerine özgüdür.', 'formell.'),
  },
  {
    id: 'select-korrekt',
    type: 'multiple_select',
    topic: 'kollokationen',
    concept: 'choose-verb',
    skill: 'vocabulary',
    difficulty: 3,
    promptL10n: l('Which combinations are correct? Select all.', 'Hangi birleşimler doğru? Hepsini seç.', 'Welche sind korrekt?'),
    options: ['eine Frage stellen', 'Bescheid geben', 'Kritik machen', 'in Frage kommen', 'eine Entscheidung machen'],
    answers: [0, 1, 3],
    explanation: l('Kritik üben, eine Entscheidung treffen – not machen.', 'Kritik üben, eine Entscheidung treffen – machen değil.', 'Kollokationen.'),
  },
  {
    id: 'image-gesetz',
    type: 'image_choice',
    topic: 'kontext',
    concept: 'legal',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Das Gesetz ist seit gestern in Kraft.',
    options: [
      { emoji: '📜', label: 'Gesetz gilt' },
      { emoji: '💪', label: 'Krafttraining' },
      { emoji: '⚡', label: 'Strom' },
      { emoji: '🏋️', label: 'Fitness' },
    ],
    answer: 0,
    explanation: l('in Kraft = valid (law).', 'in Kraft = yürürlükte (kanun).', 'gültig.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-verfuegung',
    type: 'fill_blank',
    topic: 'kollokationen',
    concept: 'choose-verb',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Für Rückfragen stehe ich Ihnen gern zur ___.',
    accepted: ['Verfügung'],
    base: 'zur … stehen',
    explanation: l('zur Verfügung stehen = to be available.', 'zur Verfügung stehen = hazır olmak.', 'Verfügung.'),
    examples: ['… stehe ich Ihnen gern zur **Verfügung**.'],
  },
  {
    id: 'fill-bescheid',
    type: 'fill_blank',
    topic: 'alltag',
    concept: 'everyday',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Sag mir bitte ___, ob du morgen kommst.',
    accepted: ['Bescheid'],
    base: 'informieren',
    explanation: l('Bescheid sagen / geben = to let know.', 'Bescheid sagen / geben = haber vermek.', 'Bescheid.'),
    examples: ['Sag mir bitte **Bescheid**, …'],
  },
  {
    id: 'fill-anspruch',
    type: 'fill_blank',
    topic: 'kontext',
    concept: 'official',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Sie können eine kostenlose Rechtsberatung in ___ nehmen.',
    accepted: ['Anspruch'],
    base: 'nutzen',
    explanation: l('in Anspruch nehmen = to make use of.', 'in Anspruch nehmen = yararlanmak.', 'Anspruch.'),
    examples: ['… eine kostenlose Rechtsberatung in **Anspruch** nehmen.'],
  },
  {
    id: 'build-kritik',
    type: 'sentence_builder',
    topic: 'umformen',
    concept: 'verb-to-fvg',
    skill: 'grammar',
    difficulty: 3,
    chips: ['übten', 'an dem neuen Gesetz', 'scharfe Kritik', 'Die Verbände'],
    answers: [['Die Verbände', 'übten', 'scharfe Kritik', 'an dem neuen Gesetz'], ['Die Verbände', 'übten', 'an dem neuen Gesetz', 'scharfe Kritik']],
    translation: l('The associations sharply criticised the new law.', 'Dernekler yeni yasayı sert biçimde eleştirdi.', 'Die Verbände übten scharfe Kritik an dem neuen Gesetz.'),
    explanation: l('Kritik üben an + dative.', 'Kritik üben an + Dativ.', 'Kritik üben.'),
    examples: ['Die Verbände **übten** scharfe **Kritik** an dem neuen Gesetz.'],
  },
  {
    id: 'build-ruecksicht',
    type: 'sentence_builder',
    topic: 'alltag',
    concept: 'everyday',
    skill: 'grammar',
    difficulty: 2,
    chips: ['auf die Nachbarn', 'Bitte nehmen Sie', 'Rücksicht'],
    answers: [['Bitte nehmen Sie', 'Rücksicht', 'auf die Nachbarn']],
    translation: l('Please be considerate of the neighbours.', 'Lütfen komşuları dikkate alın.', 'Bitte nehmen Sie Rücksicht auf die Nachbarn.'),
    explanation: l('Rücksicht nehmen auf + accusative.', 'Rücksicht nehmen auf + Akk.', 'Rücksicht nehmen.'),
    examples: ['Bitte **nehmen** Sie **Rücksicht** auf die Nachbarn.'],
  },
  {
    id: 'build-sprache',
    type: 'sentence_builder',
    topic: 'umformen',
    concept: 'verb-to-fvg',
    skill: 'grammar',
    difficulty: 3,
    chips: ['zur Sprache bringen', 'Ich möchte', 'heute', 'ein schwieriges Thema'],
    answers: [['Ich möchte', 'heute', 'ein schwieriges Thema', 'zur Sprache bringen']],
    translation: l('I would like to raise a difficult topic today.', 'Bugün zor bir konuyu gündeme getirmek istiyorum.', 'Ich möchte heute ein schwieriges Thema zur Sprache bringen.'),
    explanation: l('zur Sprache bringen = ansprechen (formal).', 'zur Sprache bringen = gündeme getirmek (resmî).', 'zur Sprache.'),
    examples: ['Ich möchte heute ein schwieriges Thema **zur Sprache bringen**.'],
  },
  {
    id: 'fix-entscheidung',
    type: 'error_correction',
    topic: 'kollokationen',
    concept: 'choose-verb',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Wir müssen bis Freitag eine Entscheidung machen.',
    accepted: ['Wir müssen bis Freitag eine Entscheidung treffen.'],
    explanation: l('eine Entscheidung treffen.', 'eine Entscheidung treffen.', 'treffen.'),
    examples: ['… eine Entscheidung **treffen**.'],
  },
  {
    id: 'fix-kritik',
    type: 'error_correction',
    topic: 'kollokationen',
    concept: 'choose-verb',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Der Bürgermeister machte Kritik an dem Projekt.',
    accepted: ['Der Bürgermeister übte Kritik an dem Projekt.', 'Der Bürgermeister kritisierte das Projekt.'],
    explanation: l('Kritik üben (or simply kritisieren).', 'Kritik üben (ya da kısaca kritisieren).', 'übte.'),
    examples: ['Der Bürgermeister **übte** Kritik an dem Projekt.'],
  },
  {
    id: 'fix-frage',
    type: 'error_correction',
    topic: 'kollokationen',
    concept: 'choose-verb',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Ein Umzug geht für uns nicht in Frage.',
    accepted: ['Ein Umzug kommt für uns nicht in Frage.', 'Ein Umzug kommt für uns nicht infrage.'],
    explanation: l('in Frage kommen.', 'in Frage kommen.', 'kommt.'),
    examples: ['Ein Umzug **kommt** für uns nicht in Frage.'],
  },
  {
    id: 'tr-verfuegung',
    type: 'translation',
    topic: 'kontext',
    concept: 'official',
    skill: 'writing',
    difficulty: 3,
    source: l('The company provides all employees with a laptop.', 'Şirket tüm çalışanlara bir dizüstü bilgisayar sağlıyor.', 'The company provides all employees with a laptop.'),
    accepted: ['Die Firma stellt allen Mitarbeitern einen Laptop zur Verfügung.', 'Das Unternehmen stellt allen Mitarbeitern einen Laptop zur Verfügung.', 'Die Firma stellt allen Mitarbeitenden einen Laptop zur Verfügung.'],
    explanation: l('jemandem etwas zur Verfügung stellen.', 'jemandem etwas zur Verfügung stellen.', 'zur Verfügung stellen.'),
    examples: ['Die Firma **stellt** allen Mitarbeitern einen Laptop **zur Verfügung**.'],
  },
  {
    id: 'tr-ausdruck',
    type: 'translation',
    topic: 'umformen',
    concept: 'verb-to-fvg',
    skill: 'writing',
    difficulty: 3,
    source: l('She clearly expressed her disappointment. (use: zum Ausdruck bringen)', 'Hayal kırıklığını açıkça ifade etti. (zum Ausdruck bringen kullan)', 'She clearly expressed her disappointment.'),
    accepted: ['Sie brachte ihre Enttäuschung deutlich zum Ausdruck.', 'Sie hat ihre Enttäuschung deutlich zum Ausdruck gebracht.', 'Sie brachte ihre Enttäuschung klar zum Ausdruck.'],
    explanation: l('etwas zum Ausdruck bringen.', 'etwas zum Ausdruck bringen.', 'zum Ausdruck bringen.'),
    examples: ['Sie **brachte** ihre Enttäuschung deutlich **zum Ausdruck**.'],
  },
  {
    id: 'ordering-brief',
    type: 'ordering',
    topic: 'kontext',
    concept: 'official',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order the formal letter from the city.', 'Belediyenin resmî mektubunu sırala.', 'Ordne das Schreiben.'),
    items: ['Für Rückfragen stehen wir Ihnen gern zur Verfügung.', 'Sehr geehrte Anwohnerinnen und Anwohner,', 'Wir bitten Sie, in dieser Zeit Rücksicht auf die Bauarbeiter zu nehmen.', 'am 1. Mai tritt die neue Parkordnung in Kraft.'],
    answer: ['Sehr geehrte Anwohnerinnen und Anwohner,', 'am 1. Mai tritt die neue Parkordnung in Kraft.', 'Wir bitten Sie, in dieser Zeit Rücksicht auf die Bauarbeiter zu nehmen.', 'Für Rückfragen stehen wir Ihnen gern zur Verfügung.'],
    explanation: l('Greeting → news → request → offer of help.', 'Hitap → haber → rica → yardım teklifi.', 'Aufbau.'),
  },
  {
    id: 'dialog-meeting',
    type: 'dialogue',
    topic: 'umformen',
    concept: 'verb-to-fvg',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Moderator', de: 'Gibt es noch weitere Punkte?' }],
    options: ['Ja, ich möchte noch die Arbeitszeiten zur Sprache bringen.', 'Ja, ich möchte die Arbeitszeiten zur Sprache machen.', 'Ja, Punkte.'],
    answer: 0,
    explanation: l('zur Sprache bringen (not machen).', 'zur Sprache bringen (machen değil).', 'bringen.'),
  },
  {
    id: 'dialog-bescheid',
    type: 'dialogue',
    topic: 'alltag',
    concept: 'everyday',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollege', de: 'Ich weiß noch nicht, ob ich morgen kommen kann.' }],
    options: ['Kein Problem, gib mir einfach bis heute Abend Bescheid.', 'Gib mir Bescheid machen.', 'Morgen kommt.'],
    answer: 0,
    explanation: l('Bescheid geben = let know.', 'Bescheid geben = haber vermek.', 'Bescheid geben.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-meldung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in der Meldung?',
    options: ['Um ein neues Gesetz zum Homeoffice.', 'Um einen Sportverein.', 'Um ein Konzert.'],
    answer: 0,
    explanation: l('„Neues Homeoffice-Gesetz tritt in Kraft“', '„Neues Homeoffice-Gesetz tritt in Kraft“', 'Gesetz.'),
  },
  {
    id: 'read-firmen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-meldung',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was müssen Arbeitgeber künftig tun?',
    options: ['Die nötige Ausstattung zur Verfügung stellen.', 'Allen mehr Gehalt zahlen.', 'Büros schließen.'],
    answer: 0,
    explanation: l('„… müssen die nötige Ausstattung zur Verfügung stellen.“', '„… müssen die nötige Ausstattung zur Verfügung stellen.“', 'Ausstattung.'),
  },
  {
    id: 'read-kritik',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-meldung',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Arbeitgeberverbände haben das Gesetz kritisiert.',
    answer: true,
    explanation: l('„Die Arbeitgeberverbände übten scharfe Kritik …“', '„Die Arbeitgeberverbände übten scharfe Kritik …“', 'richtig.'),
  },
  {
    id: 'read-anspruch',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-meldung',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wer kann eine Beratung in Anspruch nehmen?',
    options: ['Beschäftigte mit Fragen zum Gesetz.', 'Nur Arbeitgeber.', 'Niemand.'],
    answer: 0,
    explanation: l('„Beschäftigte können eine kostenlose Beratung in Anspruch nehmen.“', '„Beschäftigte können eine kostenlose Beratung in Anspruch nehmen.“', 'Beschäftigte.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-kraft',
    type: 'listening_choice',
    topic: 'kontext',
    concept: 'legal',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ab dem ersten März tritt das neue Rauchverbot in allen Bahnhöfen in Kraft.',
    question: l('When does the ban come into force?', 'Yasak ne zaman yürürlüğe giriyor?', 'Ab wann gilt das Verbot?'),
    options: ['from 1 March', 'from today', 'next year'],
    answer: 0,
    explanation: l('„Ab dem ersten März tritt … in Kraft.“', '„Ab dem ersten März tritt … in Kraft.“', '1. März.'),
  },
  {
    id: 'listen-entscheidung',
    type: 'listening_choice',
    topic: 'kollokationen',
    concept: 'choose-verb',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Jury hat ihre Entscheidung getroffen: Der Preis geht an eine junge Autorin aus Wien.',
    question: l('Who wins the prize?', 'Ödülü kim kazanıyor?', 'Wer gewinnt?'),
    options: ['a young author from Vienna', 'a painter from Berlin', 'nobody yet'],
    answer: 0,
    explanation: l('„an eine junge Autorin aus Wien“', '„an eine junge Autorin aus Wien“', 'Autorin.'),
  },
  {
    id: 'listen-ruecksicht',
    type: 'listening_choice',
    topic: 'alltag',
    concept: 'everyday',
    skill: 'listening',
    difficulty: 2,
    audio: 'Liebe Fahrgäste, bitte nehmen Sie Rücksicht auf ältere Menschen und bieten Sie Ihren Sitzplatz an.',
    question: l('What are passengers asked to do?', 'Yolculardan ne isteniyor?', 'Was sollen die Fahrgäste tun?'),
    options: ['offer their seats to older people', 'buy tickets', 'leave the train'],
    answer: 0,
    explanation: l('„bieten Sie Ihren Sitzplatz an“', '„bieten Sie Ihren Sitzplatz an“', 'Sitzplatz.'),
  },
  {
    id: 'listen-einfluss',
    type: 'listening_choice',
    topic: 'umformen',
    concept: 'fvg-to-verb',
    skill: 'listening',
    difficulty: 3,
    audio: 'Kritiker werfen den Konzernen vor, zu viel Einfluss auf politische Entscheidungen zu nehmen.',
    question: l('What are the corporations accused of?', 'Şirketler neyle suçlanıyor?', 'Was wird den Konzernen vorgeworfen?'),
    options: ['too much influence on politics', 'paying too little tax', 'polluting rivers'],
    answer: 0,
    explanation: l('Einfluss nehmen auf = beeinflussen.', 'Einfluss nehmen auf = etkilemek.', 'Einfluss.'),
  },

  ...fvgDrills(),
]

export const UNIT_C1_05_FUNKTIONSVERBGEFUEGE: CourseUnit = {
  level: 'C1',
  number: 5,
  slug: 'funktionsverbgefuege',
  titleDe: 'Zur Verfügung stellen',
  title: l('To make available', 'Kullanıma sunmak', 'Zur Verfügung stellen'),
  goal: l(
    'By the end of this unit you can recognise and use common noun-verb combinations (zur Verfügung stellen, in Kraft treten, Kritik üben, eine Entscheidung treffen) and choose between them and simple verbs depending on the register.',
    'Bu ünitenin sonunda yaygın isim-fiil birleşimlerini (zur Verfügung stellen, in Kraft treten, Kritik üben, eine Entscheidung treffen) tanıyıp kullanabilir ve dil düzeyine göre bunlarla basit fiiller arasında seçim yapabilirsin.',
    'Am Ende dieser Einheit benutzt du Funktionsverbgefüge sicher.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'kollokationen', label: l('Noun + verb', 'İsim + fiil', 'Kollokationen') },
    { key: 'umformen', label: l('Combination vs simple verb', 'Birleşim ve basit fiil', 'Umformen') },
    { key: 'kontext', label: l('Official and legal language', 'Resmî ve hukuki dil', 'Kontext') },
    { key: 'alltag', label: l('Everyday combinations', 'Günlük birleşimler', 'Alltag') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Nouns and verbs that belong together.', 'Birbirine ait isimler ve fiiller.', 'Feste Verbindungen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('What is a Funktionsverbgefüge?', 'Funktionsverbgefüge nedir?', 'Was ist ein Funktionsverbgefüge?'),
          body: l(
            'A noun carries the meaning, a „weak“ verb (bringen, nehmen, stellen, treten, kommen, üben, treffen) carries the grammar: eine Entscheidung treffen = entscheiden. The verb is fixed – you cannot choose another one.',
            'Anlamı isim taşır, dilbilgisini „zayıf“ bir fiil (bringen, nehmen, stellen, treten, kommen, üben, treffen) taşır: eine Entscheidung treffen = entscheiden. Fiil sabittir – başka bir fiil seçemezsin.',
            'Nomen = Bedeutung, Verb = Grammatik.'
          ),
          table: {
            head: [l('Combination', 'Birleşim', 'Gefüge'), l('Simple verb', 'Basit fiil', 'Verb')],
            rows: [
              ['Kritik üben', 'kritisieren'],
              ['eine Entscheidung treffen', 'entscheiden'],
              ['zum Ausdruck bringen', 'ausdrücken'],
              ['Einfluss nehmen', 'beeinflussen'],
              ['zur Verfügung stellen', 'bereitstellen'],
            ],
          },
        },
        {
          title: l('Style and register', 'Üslup ve dil düzeyi', 'Stil und Register'),
          body: l(
            'Funktionsverbgefüge sound formal and are typical of official letters, laws and news. In everyday speech the simple verb is often more natural – but some combinations are common everywhere: Bescheid sagen, eine Frage stellen, in Frage kommen.',
            'Funktionsverbgefüge resmî duyulur ve resmî mektuplar, kanunlar ve haberler için tipiktir. Günlük konuşmada basit fiil genelde daha doğaldır – ama bazı birleşimler her yerde yaygındır: Bescheid sagen, eine Frage stellen, in Frage kommen.',
            'formell vs. alltäglich.'
          ),
          examples: [
            { de: 'Das Gesetz **tritt** im Mai **in Kraft**.', translation: l('The law comes into force in May.', 'Kanun mayısta yürürlüğe giriyor.', '') },
            { de: 'Sag mir bitte **Bescheid**.', translation: l('Please let me know.', 'Lütfen bana haber ver.', '') },
          ],
        },
        {
          title: l('Learning tip', 'Öğrenme ipucu', 'Lerntipp'),
          body: l(
            'Always learn the whole combination with its preposition: Kritik üben an + Dat., Rücksicht nehmen auf + Akk., Einfluss nehmen auf + Akk., in Anspruch nehmen.',
            'Birleşimi her zaman edatıyla birlikte öğren: Kritik üben an + Dat., Rücksicht nehmen auf + Akk., Einfluss nehmen auf + Akk., in Anspruch nehmen.',
            'als Ganzes lernen.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A team meeting about new working rules.', 'Yeni çalışma kuralları hakkında bir ekip toplantısı.', 'Teambesprechung.'),
      dialogue: [
        { speaker: 'Chefin', de: 'Ab Juli **tritt** eine neue Homeoffice-Regel **in Kraft**. Jeder kann zwei Tage von zu Hause arbeiten.', translation: l('From July a new home office rule comes into force. Everyone can work from home two days a week.', 'Temmuzdan itibaren yeni bir ev ofisi kuralı yürürlüğe giriyor. Herkes iki gün evden çalışabilir.', '') },
        { speaker: 'Paul', de: 'Super! **Stellt** die Firma uns auch Bildschirme **zur Verfügung**?', translation: l('Great! Will the company also provide us with monitors?', 'Süper! Şirket bize monitör de sağlayacak mı?', '') },
        { speaker: 'Chefin', de: 'Ja. Sie können außerdem eine Beratung zur Ergonomie **in Anspruch nehmen**.', translation: l('Yes. You can also make use of ergonomic advice.', 'Evet. Ayrıca ergonomi danışmanlığından yararlanabilirsiniz.', '') },
        { speaker: 'Aylin', de: 'Ich möchte noch ein Problem **zur Sprache bringen**: Viele Meetings finden sehr spät statt.', translation: l('I’d like to raise another problem: many meetings take place very late.', 'Bir sorunu daha gündeme getirmek istiyorum: birçok toplantı çok geç yapılıyor.', '') },
        { speaker: 'Chefin', de: 'Guter Punkt. Wir sollten mehr **Rücksicht auf** Eltern **nehmen**. Ich **treffe** bis Freitag **eine Entscheidung**.', translation: l('Good point. We should be more considerate of parents. I’ll make a decision by Friday.', 'İyi nokta. Ebeveynleri daha çok dikkate almalıyız. Cumaya kadar bir karar vereceğim.', '') },
        { speaker: 'Aylin', de: 'Danke! **Geben** Sie uns dann bitte **Bescheid**.', translation: l('Thank you! Please let us know then.', 'Teşekkürler! O zaman lütfen bize haber verin.', '') },
      ],
      examples: [
        { de: 'Die Firma **stellt** Laptops **zur Verfügung**.', translation: l('The company provides laptops.', 'Şirket dizüstü bilgisayar sağlıyor.', '') },
        { de: 'Das Gesetz **tritt in Kraft**.', translation: l('The law comes into force.', 'Kanun yürürlüğe giriyor.', '') },
        { de: 'Die Opposition **übt Kritik an** dem Plan.', translation: l('The opposition criticises the plan.', 'Muhalefet planı eleştiriyor.', '') },
        { de: 'Wir müssen **eine Entscheidung treffen**.', translation: l('We have to make a decision.', 'Bir karar vermemiz gerekiyor.', '') },
        { de: 'Bitte **nehmen** Sie **Rücksicht**.', translation: l('Please be considerate.', 'Lütfen saygılı olun.', '') },
        { de: 'Das **kommt nicht in Frage**.', translation: l('That’s out of the question.', 'Bu söz konusu olamaz.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which verb belongs to which noun?', 'Hangi fiil hangi isme ait?', 'Welches Verb passt?'),
      exercises: ['match-verb', 'sort-verb', 'fvg-kritik', 'fvg-entscheidung', 'fvg-ruecksicht', 'mc-kraft', 'tf-stil', 'select-korrekt', 'image-gesetz'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Use the combinations in context.', 'Birleşimleri bağlam içinde kullan.', 'Im Kontext anwenden.'),
      exercises: [
        'fill-verfuegung',
        'fill-bescheid',
        'fill-anspruch',
        'build-kritik',
        'build-ruecksicht',
        'build-sprache',
        'fix-entscheidung',
        'fix-kritik',
        'fix-frage',
        'tr-verfuegung',
        'tr-ausdruck',
        'ordering-brief',
        'dialog-meeting',
        'dialog-bescheid',
        'fvg-kraft',
        'fvg-ausdruck',
        'fvg-verfuegung',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A news report about a new law.', 'Yeni bir kanun hakkında haber.', 'Eine Meldung.'),
      passage: [
        '**Neues Homeoffice-Gesetz tritt in Kraft** – Ab dem 1. Juli haben Beschäftigte das Recht, mindestens einen Tag pro Woche von zu Hause zu arbeiten.',
        'Arbeitgeber müssen künftig die nötige Ausstattung **zur Verfügung stellen**. Die Regierung **brachte** ihre Hoffnung **zum Ausdruck**, dass Familie und Beruf so besser vereinbar werden.',
        'Die Arbeitgeberverbände **übten** scharfe **Kritik**: Die Kosten seien zu hoch, kleine Firmen könnten die Regel kaum umsetzen.',
        'Beschäftigte mit Fragen können eine kostenlose Beratung bei den Gewerkschaften **in Anspruch nehmen**.',
      ],
      glossary: [
        { de: 'die Ausstattung', note: l('equipment', 'donanım', 'Geräte, Möbel') },
        { de: 'vereinbar', note: l('compatible', 'bağdaşabilir', 'passt zusammen') },
        { de: 'umsetzen', note: l('to implement', 'uygulamak', 'realisieren') },
        { de: 'die Gewerkschaft', note: l('trade union', 'sendika', 'Arbeitnehmervertretung') },
      ],
      exercises: ['read-thema', 'read-firmen', 'read-kritik', 'read-anspruch'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Announcements and news.', 'Anonslar ve haberler.', 'Durchsagen und Nachrichten.'),
      exercises: ['listen-kraft', 'listen-entscheidung', 'listen-ruecksicht', 'listen-einfluss'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('You are team leader: announce a new rule at work and react to concerns – use noun-verb combinations.', 'Ekip liderisin: işte yeni bir kuralı duyur ve endişelere yanıt ver – isim-fiil birleşimleri kullan.', 'Eine neue Regel ankündigen.'),
      points: [
        l('When does it come into force? (in Kraft treten)', 'Ne zaman yürürlüğe giriyor? (in Kraft treten)', 'in Kraft'),
        l('What does the company provide? (zur Verfügung stellen)', 'Şirket ne sağlıyor? (zur Verfügung stellen)', 'Verfügung'),
        l('React to criticism (Kritik üben, Rücksicht nehmen)', 'Eleştiriye yanıt ver (Kritik üben, Rücksicht nehmen)', 'Kritik'),
        l('Next steps (eine Entscheidung treffen, Bescheid geben)', 'Sonraki adımlar (eine Entscheidung treffen, Bescheid geben)', 'nächste Schritte'),
      ],
      model: [
        'Ab Oktober tritt bei uns eine neue Regel für flexible Arbeitszeiten in Kraft.',
        'Die Firma stellt dafür allen eine App zur Zeiterfassung zur Verfügung.',
        'Ich verstehe, dass einige Kollegen Kritik an der Kontrolle üben – wir nehmen Rücksicht auf den Datenschutz.',
        'Nach dem Probemonat treffen wir gemeinsam eine Entscheidung, und ich gebe Ihnen rechtzeitig Bescheid.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write an official notice (at least 6 sentences) from a city or company about a new regulation. Use at least four noun-verb combinations.',
        'Bir belediye ya da şirketten yeni bir düzenleme hakkında resmî bir duyuru yaz (en az 6 cümle). En az dört isim-fiil birleşimi kullan.',
        'Offizielle Mitteilung mit Funktionsverbgefügen (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('in Kraft treten', 'in Kraft treten', 'in Kraft'), pattern: 'in Kraft' },
        { label: l('zur Verfügung stellen / stehen', 'zur Verfügung stellen / stehen', 'Verfügung'), pattern: 'zur Verfügung' },
        { label: l('Another combination (Rücksicht, Anspruch, Bescheid, Entscheidung, Kritik …)', 'Başka bir birleşim (Rücksicht, Anspruch, Bescheid, Entscheidung, Kritik …)', 'weiteres Gefüge'), pattern: '(Rücksicht|in Anspruch|Bescheid|Entscheidung (getroffen|treffen)|Kritik|zur Sprache|zum Ausdruck)' },
      ],
      model: [
        'Sehr geehrte Bürgerinnen und Bürger, ab dem 1. April tritt in der Innenstadt eine neue Parkregelung in Kraft.',
        'Die Stadt stellt dafür zusätzliche Parkplätze am Stadtrand zur Verfügung.',
        'Anwohner können einen kostenlosen Parkausweis in Anspruch nehmen.',
        'Wir bitten alle Autofahrer, Rücksicht auf Fußgänger und Radfahrer zu nehmen.',
        'Die Entscheidung wurde nach langer Diskussion im Stadtrat getroffen.',
        'Für Rückfragen stehen wir Ihnen jederzeit zur Verfügung.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Which verb? – 60 seconds.', 'Hangi fiil? – 60 saniye.', 'Welches Verb? – 60 Sekunden.'),
      seconds: 60,
      pool: [...FVG.map(([id]) => `fvg-${id}`), 'mc-kraft'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Noun carries meaning, verb carries grammar: eine Entscheidung treffen', 'Anlamı isim, dilbilgisini fiil taşır: eine Entscheidung treffen', 'Prinzip'),
      l('Common combinations: zur Verfügung stellen, in Kraft treten, Kritik üben, Rücksicht nehmen', 'Yaygın birleşimler: zur Verfügung stellen, in Kraft treten, Kritik üben, Rücksicht nehmen', 'Gefüge'),
      l('Formal register vs simple verbs in everyday speech', 'Resmî dil düzeyi ve günlük konuşmada basit fiiller', 'Register'),
      l('Learn with preposition: Einfluss nehmen auf, Kritik üben an', 'Edatla öğren: Einfluss nehmen auf, Kritik üben an', 'Präpositionen'),
    ],
    mistakes: [
      { wrong: 'eine Entscheidung machen', right: 'eine Entscheidung treffen', note: l('treffen.', 'treffen.', 'treffen.') },
      { wrong: 'Kritik machen', right: 'Kritik üben', note: l('üben.', 'üben.', 'üben.') },
      { wrong: 'nicht in Frage gehen', right: 'nicht in Frage kommen', note: l('kommen.', 'kommen.', 'kommen.') },
      { wrong: 'zur Sprache machen', right: 'zur Sprache bringen', note: l('bringen.', 'bringen.', 'bringen.') },
    ],
  },
}
