import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'den Nagel auf den Kopf treffen', emoji: '🔨', translation: l('to hit the nail on the head', 'taşı gediğine koymak', 'genau das Richtige sagen'), example: 'Mit dieser Bemerkung hast du den Nagel auf den Kopf getroffen.' },
  { word: 'ins Fettnäpfchen treten', emoji: '🙊', translation: l('to put one’s foot in it', 'pot kırmak', 'etwas Peinliches sagen'), example: 'Mit der Frage nach seinem Alter bin ich ins Fettnäpfchen getreten.' },
  { word: 'auf dem Holzweg sein', emoji: '🪵', translation: l('to be on the wrong track', 'yanlış yolda olmak', 'sich irren'), example: 'Wenn du glaubst, das wird billig, bist du auf dem Holzweg.' },
  { word: 'die Daumen drücken', emoji: '🤞', translation: l('to keep one’s fingers crossed', 'şans dilemek', 'Glück wünschen'), example: 'Ich drücke dir für die Prüfung die Daumen!' },
  { word: 'etwas auf die lange Bank schieben', emoji: '🪑', translation: l('to put something off', 'bir işi sürekli ertelemek', 'aufschieben'), example: 'Die Steuererklärung schiebt er immer auf die lange Bank.' },
  { word: 'Tomaten auf den Augen haben', emoji: '🍅', translation: l('to be blind to something obvious', 'gözünün önündekini görmemek', 'etwas Offensichtliches nicht sehen'), example: 'Hast du Tomaten auf den Augen? Der Schlüssel liegt doch da!' },
  { word: 'jemandem auf den Wecker gehen', emoji: '⏰', translation: l('to get on someone’s nerves', 'birinin sinirine dokunmak', 'nerven'), example: 'Der Lärm geht mir echt auf den Wecker.' },
  { word: 'die Katze im Sack kaufen', emoji: '🐱', translation: l('to buy a pig in a poke', 'görmeden almak', 'ungeprüft kaufen'), example: 'Ohne Probefahrt kaufe ich doch nicht die Katze im Sack.' },
  { word: 'unter vier Augen', emoji: '👀', translation: l('in private', 'baş başa', 'privat, allein'), example: 'Können wir das unter vier Augen besprechen?' },
  { word: 'etwas aus dem Ärmel schütteln', emoji: '🧥', translation: l('to do something effortlessly', 'kolayca yapıvermek', 'mühelos machen'), example: 'So eine Rede kann man nicht aus dem Ärmel schütteln.' },
  { word: 'ins Gras beißen', emoji: '🌱', translation: l('to bite the dust', 'nalları dikmek', 'sterben (salopp)'), example: 'Mein alter Laptop hat endlich ins Gras gebissen.' },
  { word: 'Schwein haben', emoji: '🐷', translation: l('to be lucky', 'şanslı olmak', 'Glück haben'), example: 'Der Bus war noch da – da hatte ich Schwein!' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Redewendung', gender: 'f', plural: 'die Redewendungen', translation: l('idiom', 'deyim', 'Redewendung') },
  { word: 'Sprichwort', gender: 'n', plural: 'die Sprichwörter', translation: l('proverb', 'atasözü', 'Sprichwort') },
  { word: 'Bedeutung', gender: 'f', plural: 'die Bedeutungen', translation: l('meaning', 'anlam', 'Bedeutung') },
  { word: 'Herkunft', gender: 'f', translation: l('origin', 'köken', 'Herkunft') },
  { word: 'Fettnäpfchen', gender: 'n', plural: 'die Fettnäpfchen', translation: l('faux pas (lit. little pot of fat)', 'gaf (kelimesi kelimesine: yağ kabı)', 'Fettnäpfchen') },
  { word: 'Holzweg', gender: 'm', plural: 'die Holzwege', translation: l('dead-end path (lit. timber track)', 'çıkmaz yol', 'Holzweg') },
  { word: 'Ärmel', gender: 'm', plural: 'die Ärmel', translation: l('sleeve', 'kol (giysi)', 'Ärmel') },
  { word: 'Wecker', gender: 'm', plural: 'die Wecker', translation: l('alarm clock', 'çalar saat', 'Wecker') },
]

/** [id, sentence with gap, right, wrong] */
const RW: [string, string, string, [string, string]][] = [
  ['nagel', 'Genau so ist es! Du hast den Nagel auf den ___ getroffen.', 'Kopf', ['Fuß', 'Tisch']],
  ['daumen', 'Morgen ist dein Vorstellungsgespräch? Ich drücke dir die ___!', 'Daumen', ['Finger', 'Hände']],
  ['holzweg', 'Wenn er glaubt, ohne Lernen zu bestehen, ist er auf dem ___.', 'Holzweg', ['Waldweg', 'Feldweg']],
  ['bank', 'Er schiebt die unangenehmen Aufgaben immer auf die lange ___.', 'Bank', ['Bahn', 'Liste']],
  ['schwein', 'Ich habe den letzten Zug noch erwischt – da hatte ich echt ___!', 'Schwein', ['Hund', 'Huhn']],
  ['augen', 'Darüber möchte ich lieber unter vier ___ sprechen.', 'Augen', ['Ohren', 'Wänden']],
]

function rwDrills(): Exercise[] {
  return RW.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `rw-${id}`,
      type: 'multiple_choice' as const,
      topic: 'bedeutung',
      concept: 'complete-idiom',
      skill: 'vocabulary' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Idioms are fixed – you can’t swap the words. Learn them as a whole: den Nagel auf den Kopf treffen, die Daumen drücken, auf dem Holzweg sein, auf die lange Bank schieben, Schwein haben, unter vier Augen.',
        'Deyimler kalıptır – kelimeleri değiştiremezsin. Bütün olarak öğren: den Nagel auf den Kopf treffen, die Daumen drücken, auf dem Holzweg sein, auf die lange Bank schieben, Schwein haben, unter vier Augen.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-bedeutung',
    type: 'matching',
    topic: 'bedeutung',
    concept: 'meanings',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the idiom and its meaning.', 'Deyimi anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'ins Fettnäpfchen treten', right: 'etwas Peinliches sagen' },
      { left: 'auf dem Holzweg sein', right: 'sich irren' },
      { left: 'Schwein haben', right: 'Glück haben' },
      { left: 'auf den Wecker gehen', right: 'nerven' },
      { left: 'unter vier Augen', right: 'privat, allein' },
    ],
    explanation: l('The literal meaning rarely helps – learn the figurative meaning.', 'Kelime anlamı nadiren yardımcı olur – mecazi anlamı öğren.', 'Bedeutungen.'),
  },
  {
    id: 'sort-gefuehl',
    type: 'categorize',
    topic: 'kontext',
    concept: 'positive-negative',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Is the situation positive or negative?', 'Durum olumlu mu olumsuz mu?', 'Positiv oder negativ?'),
    categories: ['positiv 😊', 'negativ 😕'],
    items: [
      { text: 'Schwein haben', category: 0 },
      { text: 'ins Fettnäpfchen treten', category: 1 },
      { text: 'den Nagel auf den Kopf treffen', category: 0 },
      { text: 'jemandem auf den Wecker gehen', category: 1 },
      { text: 'die Daumen drücken', category: 0 },
      { text: 'die Katze im Sack kaufen', category: 1 },
    ],
    explanation: l('Knowing the tone helps you use idioms correctly.', 'Tonu bilmek deyimleri doğru kullanmana yardım eder.', 'Ton.'),
    practice: ['rw-schwein'],
  },
  {
    id: 'mc-fettnaepfchen',
    type: 'multiple_choice',
    topic: 'kontext',
    concept: 'infer',
    skill: 'reading',
    difficulty: 3,
    prompt: '„Ich habe sie gefragt, wann das Baby kommt – dabei war sie gar nicht schwanger.“ Was ist passiert?',
    options: ['Er ist ins Fettnäpfchen getreten.', 'Er hat Schwein gehabt.', 'Er hat den Nagel auf den Kopf getroffen.'],
    answer: 0,
    explanation: l('An embarrassing remark → ins Fettnäpfchen treten.', 'Utandırıcı bir söz → ins Fettnäpfchen treten.', 'Fettnäpfchen.'),
    practice: ['fill-fettnaepfchen'],
  },
  {
    id: 'tf-woertlich',
    type: 'true_false',
    topic: 'bedeutung',
    concept: 'figurative',
    skill: 'vocabulary',
    difficulty: 2,
    statement: '„Tomaten auf den Augen haben“ bedeutet, dass jemand eine Augenkrankheit hat.',
    answer: false,
    explanation: l('It means: not seeing something obvious.', 'Anlamı: apaçık bir şeyi görmemek.', 'bildlich.'),
  },
  {
    id: 'select-glueck',
    type: 'multiple_select',
    topic: 'bedeutung',
    concept: 'synonyms',
    skill: 'vocabulary',
    difficulty: 3,
    promptL10n: l('Which expressions mean „to be lucky“? Select all.', 'Hangi ifadeler „şanslı olmak“ anlamına gelir? Hepsini seç.', 'Was bedeutet „Glück haben“?'),
    options: ['Schwein haben', 'Glück im Unglück haben', 'ins Gras beißen', 'auf dem Holzweg sein', 'einen Glückstreffer landen'],
    answers: [0, 1, 4],
    explanation: l('Schwein haben, Glück im Unglück haben, einen Glückstreffer landen.', 'Schwein haben, Glück im Unglück haben, einen Glückstreffer landen.', 'Glück.'),
  },
  {
    id: 'image-daumen',
    type: 'image_choice',
    topic: 'bedeutung',
    concept: 'gesture',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Ich drücke dir die Daumen!',
    options: [
      { emoji: '✊', label: 'Daumen gedrückt' },
      { emoji: '👍', label: 'Daumen hoch' },
      { emoji: '👎', label: 'Daumen runter' },
      { emoji: '👋', label: 'winken' },
    ],
    answer: 0,
    explanation: l('In Germany you wish luck by pressing your thumbs inside your fist.', 'Almanya’da başparmağı yumruğun içine bastırarak şans dilenir.', 'Daumen drücken.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-fettnaepfchen',
    type: 'fill_blank',
    topic: 'kontext',
    concept: 'complete',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Mit der Frage nach seinem Gehalt bin ich voll ins ___ getreten.',
    accepted: ['Fettnäpfchen', 'Fettnaepfchen'],
    base: 'etwas Peinliches sagen',
    explanation: l('ins Fettnäpfchen treten = to put one’s foot in it.', 'ins Fettnäpfchen treten = pot kırmak.', 'Fettnäpfchen.'),
    examples: ['… bin ich voll ins **Fettnäpfchen** getreten.'],
  },
  {
    id: 'fill-wecker',
    type: 'fill_blank',
    topic: 'kontext',
    concept: 'complete',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Sein ständiges Jammern geht mir langsam auf den ___.',
    accepted: ['Wecker', 'Keks', 'Geist', 'Senkel'],
    base: 'nerven',
    explanation: l('auf den Wecker / Keks / Geist gehen = to get on someone’s nerves.', 'auf den Wecker / Keks / Geist gehen = sinirine dokunmak.', 'Wecker.'),
    examples: ['… geht mir auf den **Wecker**.'],
  },
  {
    id: 'fill-aermel',
    type: 'fill_blank',
    topic: 'verwenden',
    concept: 'complete',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'So eine Präsentation kann man nicht einfach aus dem ___ schütteln.',
    accepted: ['Ärmel', 'Aermel'],
    base: 'mühelos machen',
    explanation: l('aus dem Ärmel schütteln = to do effortlessly.', 'aus dem Ärmel schütteln = kolayca yapıvermek.', 'Ärmel.'),
    examples: ['… nicht einfach aus dem **Ärmel** schütteln.'],
  },
  {
    id: 'build-katze',
    type: 'sentence_builder',
    topic: 'verwenden',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 3,
    chips: ['nicht', 'Ich kaufe', 'die Katze', 'im Sack'],
    answers: [['Ich kaufe', 'nicht', 'die Katze', 'im Sack'], ['Ich kaufe', 'die Katze', 'nicht', 'im Sack'], ['Ich kaufe', 'die Katze', 'im Sack', 'nicht']],
    translation: l('I won’t buy a pig in a poke.', 'Görmeden bir şey almam.', 'Ich kaufe nicht die Katze im Sack.'),
    explanation: l('The verb conjugates normally inside the idiom.', 'Fiil deyimin içinde normal çekimlenir.', 'Konjugation.'),
    examples: ['Ich **kaufe** doch nicht die Katze im Sack.'],
  },
  {
    id: 'build-bank',
    type: 'sentence_builder',
    topic: 'verwenden',
    concept: 'perfect',
    skill: 'grammar',
    difficulty: 3,
    chips: ['auf die lange Bank', 'Sie hat', 'geschoben', 'die Entscheidung'],
    answers: [['Sie hat', 'die Entscheidung', 'auf die lange Bank', 'geschoben']],
    translation: l('She put off the decision.', 'Kararı sürekli erteledi.', 'Sie hat die Entscheidung auf die lange Bank geschoben.'),
    explanation: l('Perfect tense: hat … geschoben (participle at the end).', 'Perfekt: hat … geschoben (ortaç sonda).', 'Perfekt.'),
    examples: ['Sie **hat** die Entscheidung auf die lange Bank **geschoben**.'],
  },
  {
    id: 'build-nagel',
    type: 'sentence_builder',
    topic: 'verwenden',
    concept: 'perfect',
    skill: 'grammar',
    difficulty: 3,
    chips: ['getroffen', 'Mit dem Kommentar', 'den Nagel auf den Kopf', 'hast du'],
    answers: [['Mit dem Kommentar', 'hast du', 'den Nagel auf den Kopf', 'getroffen']],
    translation: l('With that comment you hit the nail on the head.', 'O yorumla taşı gediğine koydun.', 'Mit dem Kommentar hast du den Nagel auf den Kopf getroffen.'),
    explanation: l('treffen → getroffen.', 'treffen → getroffen.', 'getroffen.'),
    examples: ['Mit dem Kommentar **hast** du den Nagel auf den Kopf **getroffen**.'],
  },
  {
    id: 'fix-daumen',
    type: 'error_correction',
    topic: 'verwenden',
    concept: 'fixed-words',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Ich drücke dir die Finger für die Prüfung.',
    accepted: ['Ich drücke dir die Daumen für die Prüfung.', 'Ich drücke dir für die Prüfung die Daumen.'],
    explanation: l('In German you press your thumbs, not your fingers.', 'Almancada parmak değil başparmak bastırılır.', 'Daumen.'),
    examples: ['Ich drücke dir die **Daumen**.'],
  },
  {
    id: 'fix-schwein',
    type: 'error_correction',
    topic: 'verwenden',
    concept: 'fixed-words',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Da hast du aber Kuh gehabt!',
    accepted: ['Da hast du aber Schwein gehabt!', 'Da hast du aber Schwein gehabt.'],
    explanation: l('Schwein haben = to be lucky (a pig was a prize at fairs).', 'Schwein haben = şanslı olmak (eskiden panayırlarda ödül domuzdu).', 'Schwein.'),
    examples: ['Da hast du aber **Schwein** gehabt!'],
  },
  {
    id: 'fix-holzweg',
    type: 'error_correction',
    topic: 'verwenden',
    concept: 'fixed-words',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Mit dieser Theorie bist du auf den Holzweg.',
    accepted: ['Mit dieser Theorie bist du auf dem Holzweg.'],
    explanation: l('auf dem Holzweg sein – location → dative.', 'auf dem Holzweg sein – konum → Dativ.', 'dem.'),
    examples: ['… bist du auf **dem** Holzweg.'],
  },
  {
    id: 'tr-augen',
    type: 'translation',
    topic: 'verwenden',
    concept: 'translate',
    skill: 'writing',
    difficulty: 3,
    source: l('Can we talk about this in private?', 'Bunu baş başa konuşabilir miyiz?', 'Can we talk about this in private?'),
    accepted: ['Können wir das unter vier Augen besprechen?', 'Können wir darüber unter vier Augen sprechen?', 'Können wir das unter vier Augen bereden?', 'Können wir unter vier Augen darüber sprechen?'],
    explanation: l('in private = unter vier Augen.', 'baş başa = unter vier Augen.', 'unter vier Augen.'),
    examples: ['Können wir das **unter vier Augen** besprechen?'],
  },
  {
    id: 'tr-tomaten',
    type: 'translation',
    topic: 'verwenden',
    concept: 'translate',
    skill: 'writing',
    difficulty: 3,
    source: l('Are you blind? The key is right there!', 'Gözün görmüyor mu? Anahtar tam orada!', 'Are you blind? The key is right there!'),
    accepted: ['Hast du Tomaten auf den Augen? Der Schlüssel liegt doch da!', 'Hast du Tomaten auf den Augen? Der Schlüssel liegt direkt da!', 'Hast du Tomaten auf den Augen? Der Schlüssel liegt genau da!'],
    explanation: l('Tomaten auf den Augen haben = not seeing the obvious.', 'Tomaten auf den Augen haben = apaçık olanı görmemek.', 'Tomaten.'),
    examples: ['Hast du **Tomaten auf den Augen**?'],
  },
  {
    id: 'ordering-geschichte',
    type: 'ordering',
    topic: 'kontext',
    concept: 'story',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Order the anecdote.', 'Anekdotu sırala.', 'Ordne die Anekdote.'),
    items: ['Zum Glück lachte er nur – da hatte ich noch einmal Schwein.', 'Beim Firmenessen saß ich neben einem älteren Herrn.', 'Später erfuhr ich, dass er der neue Chef war.', 'Ich erzählte ihm, wie chaotisch die Chefetage sei – und trat damit voll ins Fettnäpfchen.'],
    answer: ['Beim Firmenessen saß ich neben einem älteren Herrn.', 'Ich erzählte ihm, wie chaotisch die Chefetage sei – und trat damit voll ins Fettnäpfchen.', 'Später erfuhr ich, dass er der neue Chef war.', 'Zum Glück lachte er nur – da hatte ich noch einmal Schwein.'],
    explanation: l('Situation → faux pas → discovery → lucky ending.', 'Durum → gaf → fark ediş → şanslı son.', 'Chronologie.'),
  },
  {
    id: 'dialog-pruefung',
    type: 'dialogue',
    topic: 'verwenden',
    concept: 'react',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Kollegin', de: 'Morgen habe ich endlich mein Vorstellungsgespräch bei der Bank.' }],
    options: ['Toll! Ich drücke dir ganz fest die Daumen.', 'Toll! Ich drücke dir die Finger.', 'Toll! Ich trete dir ins Fettnäpfchen.'],
    answer: 0,
    explanation: l('Wishing luck → die Daumen drücken.', 'Şans dilemek → die Daumen drücken.', 'Daumen.'),
  },
  {
    id: 'dialog-aufschieben',
    type: 'dialogue',
    topic: 'verwenden',
    concept: 'react',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Mitbewohner', de: 'Die Steuererklärung mache ich nächsten Monat … oder übernächsten.' }],
    options: ['Schieb das nicht schon wieder auf die lange Bank!', 'Schieb das nicht auf den langen Tisch!', 'Du hast den Nagel auf den Kopf getroffen!'],
    answer: 0,
    explanation: l('Putting off → auf die lange Bank schieben.', 'Ertelemek → auf die lange Bank schieben.', 'aufschieben.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-herkunft',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Text?',
    options: ['Um die Herkunft bekannter Redewendungen.', 'Um ein Kochrezept mit Tomaten.', 'Um die Geschichte der Landwirtschaft.'],
    answer: 0,
    explanation: l('„Woher kommen eigentlich unsere Redewendungen?“', '„Woher kommen eigentlich unsere Redewendungen?“', 'Herkunft.'),
  },
  {
    id: 'read-schwein',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-herkunft',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Warum bedeutet „Schwein haben“ Glück?',
    options: ['Weil man früher bei Wettkämpfen ein Schwein als Preis bekam.', 'Weil Schweine besonders klug sind.', 'Weil Schweine teuer waren und Unglück brachten.'],
    answer: 0,
    explanation: l('„… bekam der Letzte oft ein Schwein als Trostpreis.“', '„… bekam der Letzte oft ein Schwein als Trostpreis.“', 'Trostpreis.'),
  },
  {
    id: 'read-fett',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-herkunft',
    skill: 'reading',
    difficulty: 3,
    statement: 'Das Fettnäpfchen stand früher in der Nähe der Haustür.',
    answer: true,
    explanation: l('„… stand ein Napf mit Fett neben der Tür …“', '„… stand ein Napf mit Fett neben der Tür …“', 'richtig.'),
  },
  {
    id: 'read-holz',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-herkunft',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wohin führte ein Holzweg?',
    options: ['nur in den Wald, nicht ins nächste Dorf', 'direkt in die Stadt', 'zum Fluss'],
    answer: 0,
    explanation: l('„Holzwege führten nur zu den Holzfällern in den Wald.“', '„Holzwege führten nur zu den Holzfällern in den Wald.“', 'Wald.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-wecker',
    type: 'listening_choice',
    topic: 'kontext',
    concept: 'infer',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Nachbar bohrt schon seit sechs Uhr. Das geht mir total auf den Wecker!',
    question: l('How does the speaker feel?', 'Konuşan nasıl hissediyor?', 'Wie fühlt sich die Person?'),
    options: ['annoyed', 'happy', 'tired but calm'],
    answer: 0,
    explanation: l('auf den Wecker gehen = to annoy.', 'auf den Wecker gehen = sinir etmek.', 'genervt.'),
  },
  {
    id: 'listen-katze',
    type: 'listening_choice',
    topic: 'kontext',
    concept: 'infer',
    skill: 'listening',
    difficulty: 3,
    audio: 'Ich kaufe kein Auto ohne Probefahrt. Ich will doch nicht die Katze im Sack kaufen.',
    question: l('What does the speaker want to do first?', 'Konuşan önce ne yapmak istiyor?', 'Was will die Person zuerst?'),
    options: ['test-drive the car', 'buy a cat', 'sell the car'],
    answer: 0,
    explanation: l('die Katze im Sack kaufen = buy without checking.', 'die Katze im Sack kaufen = kontrol etmeden almak.', 'Probefahrt.'),
  },
  {
    id: 'listen-aermel',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'listening',
    difficulty: 3,
    audio: 'Der Vortrag sah so leicht aus, aber in Wahrheit hat sie wochenlang daran gearbeitet. So etwas schüttelt man nicht aus dem Ärmel.',
    question: l('What is true about the talk?', 'Sunum hakkında ne doğru?', 'Was stimmt?'),
    options: ['It took weeks of work.', 'It was improvised.', 'It was boring.'],
    answer: 0,
    explanation: l('nicht aus dem Ärmel schütteln = not effortless.', 'nicht aus dem Ärmel schütteln = zahmetsiz değil.', 'Arbeit.'),
  },
  {
    id: 'listen-gras',
    type: 'listening_choice',
    topic: 'bedeutung',
    concept: 'meaning',
    skill: 'listening',
    difficulty: 3,
    audio: 'Meine alte Waschmaschine hat gestern endgültig ins Gras gebissen.',
    question: l('What happened to the washing machine?', 'Çamaşır makinesine ne oldu?', 'Was ist passiert?'),
    options: ['It broke down for good.', 'It was moved to the garden.', 'It was repaired.'],
    answer: 0,
    explanation: l('ins Gras beißen = to die / to break down for good.', 'ins Gras beißen = ölmek / tamamen bozulmak.', 'kaputt.'),
  },

  ...rwDrills(),
]

export const UNIT_C1_09_REDEWENDUNGEN: CourseUnit = {
  level: 'C1',
  number: 9,
  slug: 'redewendungen',
  titleDe: 'Den Nagel auf den Kopf treffen',
  title: l('To hit the nail on the head', 'Taşı gediğine koymak', 'Den Nagel auf den Kopf treffen'),
  goal: l(
    'By the end of this unit you know common German idioms (Schwein haben, ins Fettnäpfchen treten, auf dem Holzweg sein …), can work out their meaning from context and use them naturally.',
    'Bu ünitenin sonunda yaygın Almanca deyimleri (Schwein haben, ins Fettnäpfchen treten, auf dem Holzweg sein …) bilir, anlamlarını bağlamdan çıkarabilir ve doğal şekilde kullanabilirsin.',
    'Am Ende dieser Einheit kennst und verwendest du häufige Redewendungen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'bedeutung', label: l('Meaning of idioms', 'Deyimlerin anlamı', 'Bedeutung') },
    { key: 'kontext', label: l('Meaning from context', 'Bağlamdan anlam', 'Kontext') },
    { key: 'verwenden', label: l('Using idioms correctly', 'Deyimleri doğru kullanmak', 'Verwenden') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Pigs, tomatoes and thumbs – German idioms.', 'Domuzlar, domatesler ve başparmaklar – Almanca deyimler.', 'Redewendungen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Figurative meaning', 'Mecazi anlam', 'Bildliche Bedeutung'),
          body: l(
            'An idiom means more than its words. Schwein haben has nothing to do with pigs – it means to be lucky. Learn each idiom together with a typical situation.',
            'Bir deyim kelimelerinden fazlasını anlatır. Schwein haben’ın domuzla ilgisi yoktur – şanslı olmak demektir. Her deyimi tipik bir durumla birlikte öğren.',
            'bildlich.'
          ),
          table: {
            head: [l('Idiom', 'Deyim', 'Redewendung'), l('Meaning', 'Anlam', 'Bedeutung')],
            rows: [
              ['Schwein haben', 'Glück haben'],
              ['ins Fettnäpfchen treten', 'etwas Peinliches sagen'],
              ['auf dem Holzweg sein', 'sich irren'],
              ['auf die lange Bank schieben', 'aufschieben'],
              ['auf den Wecker gehen', 'nerven'],
            ],
          },
        },
        {
          title: l('Fixed form, flexible verb', 'Kalıp sabit, fiil esnek', 'Feste Form, flexibles Verb'),
          body: l(
            'You cannot change the nouns (Daumen, not Finger), but the verb is conjugated normally and follows the usual word order: Ich habe die Entscheidung auf die lange Bank geschoben.',
            'İsimleri değiştiremezsin (Daumen, Finger değil), ama fiil normal çekimlenir ve olağan sözcük dizimini izler: Ich habe die Entscheidung auf die lange Bank geschoben.',
            'feste Form.'
          ),
          examples: [
            { de: 'Ich **drücke** dir die **Daumen**.', translation: l('I’ll keep my fingers crossed for you.', 'Sana şans diliyorum.', '') },
            { de: 'Er **ist** ins Fettnäpfchen **getreten**.', translation: l('He put his foot in it.', 'Pot kırdı.', '') },
          ],
        },
        {
          title: l('Register', 'Üslup', 'Register'),
          body: l(
            'Many idioms are colloquial (ins Gras beißen, auf den Wecker gehen). Use them with friends, not in a formal letter. Neutral ones like unter vier Augen or den Nagel auf den Kopf treffen also work at work.',
            'Birçok deyim günlük dildir (ins Gras beißen, auf den Wecker gehen). Bunları arkadaşlarla kullan, resmî bir mektupta değil. unter vier Augen ya da den Nagel auf den Kopf treffen gibi nötr olanlar iş ortamında da uygundur.',
            'Register.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two colleagues chat after a meeting.', 'İki iş arkadaşı bir toplantıdan sonra sohbet ediyor.', 'Nach dem Meeting.'),
      dialogue: [
        { speaker: 'Sara', de: 'Dein Kommentar zum Budget – da hast du **den Nagel auf den Kopf getroffen**.', translation: l('Your comment on the budget – you hit the nail on the head.', 'Bütçe hakkındaki yorumun – taşı gediğine koydun.', '') },
        { speaker: 'Tim', de: 'Danke. Aber bei der Frage an Herrn Kraus bin ich **ins Fettnäpfchen getreten**.', translation: l('Thanks. But with the question to Mr Kraus I put my foot in it.', 'Teşekkürler. Ama Bay Kraus’a sorduğum soruyla pot kırdım.', '') },
        { speaker: 'Sara', de: 'Ach, er hat doch gelacht. Da hattest du **Schwein**.', translation: l('Oh, he laughed. You were lucky.', 'Yok canım, güldü. Şanslıydın.', '') },
        { speaker: 'Tim', de: 'Stimmt. Was mir **auf den Wecker geht**: Die Entscheidung wird wieder **auf die lange Bank geschoben**.', translation: l('True. What annoys me: the decision is being put off again.', 'Doğru. Beni sinir eden şu: karar yine erteleniyor.', '') },
        { speaker: 'Sara', de: 'Sprich doch mal **unter vier Augen** mit der Chefin.', translation: l('Why don’t you talk to the boss in private?', 'Patronla baş başa konuşsana.', '') },
        { speaker: 'Tim', de: 'Gute Idee. **Drück mir die Daumen!**', translation: l('Good idea. Keep your fingers crossed for me!', 'İyi fikir. Bana şans dile!', '') },
      ],
      examples: [
        { de: 'Da hast du **Schwein gehabt**!', translation: l('You were lucky there!', 'Şanslıymışsın!', '') },
        { de: 'Du bist **auf dem Holzweg**.', translation: l('You’re on the wrong track.', 'Yanlış yoldasın.', '') },
        { de: 'Hast du **Tomaten auf den Augen**?', translation: l('Are you blind?', 'Gözün görmüyor mu?', '') },
        { de: 'Das kann man nicht **aus dem Ärmel schütteln**.', translation: l('You can’t just do that off the cuff.', 'Bu öyle kolayca yapılamaz.', '') },
        { de: 'Ich kaufe nicht **die Katze im Sack**.', translation: l('I won’t buy a pig in a poke.', 'Görmeden almam.', '') },
        { de: 'Der Drucker hat **ins Gras gebissen**.', translation: l('The printer has bitten the dust.', 'Yazıcı nalları dikti.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('What does it really mean?', 'Gerçekte ne anlama geliyor?', 'Was bedeutet das?'),
      exercises: ['match-bedeutung', 'sort-gefuehl', 'rw-nagel', 'rw-daumen', 'rw-holzweg', 'mc-fettnaepfchen', 'tf-woertlich', 'select-glueck', 'image-daumen'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Use idioms in the right situation.', 'Deyimleri doğru durumda kullan.', 'Redewendungen anwenden.'),
      exercises: [
        'fill-fettnaepfchen',
        'fill-wecker',
        'fill-aermel',
        'build-katze',
        'build-bank',
        'build-nagel',
        'fix-daumen',
        'fix-schwein',
        'fix-holzweg',
        'tr-augen',
        'tr-tomaten',
        'ordering-geschichte',
        'dialog-pruefung',
        'dialog-aufschieben',
        'rw-bank',
        'rw-schwein',
        'rw-augen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Where do our idioms come from?', 'Deyimlerimiz nereden geliyor?', 'Herkunft von Redewendungen.'),
      passage: [
        '**Woher kommen eigentlich unsere Redewendungen?** Viele stammen aus dem Mittelalter und erzählen vom Alltag früherer Zeiten.',
        '**Schwein haben**: Bei Wettkämpfen auf Volksfesten bekam der Letzte oft ein Schwein als Trostpreis. Er hatte also unverdient Glück.',
        '**Ins Fettnäpfchen treten**: In Bauernhäusern stand ein Napf mit Fett neben der Tür, um nasse Stiefel einzufetten. Wer hineintrat, machte den Boden schmutzig – und die Hausfrau wütend.',
        '**Auf dem Holzweg sein**: Holzwege führten nur zu den Holzfällern in den Wald – nicht ins nächste Dorf. Wer sie nahm, war falsch unterwegs.',
      ],
      glossary: [
        { de: 'das Mittelalter', note: l('the Middle Ages', 'Orta Çağ', 'ca. 500–1500') },
        { de: 'der Trostpreis', note: l('consolation prize', 'teselli ödülü', 'Preis für den Letzten') },
        { de: 'der Napf', note: l('bowl', 'kâse, kap', 'kleine Schüssel') },
        { de: 'der Holzfäller', note: l('lumberjack', 'oduncu', 'fällt Bäume') },
      ],
      exercises: ['read-thema', 'read-schwein', 'read-fett', 'read-holz'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Idioms in everyday conversations.', 'Günlük konuşmalarda deyimler.', 'Redewendungen im Alltag.'),
      exercises: ['listen-wecker', 'listen-katze', 'listen-aermel', 'listen-gras'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Tell a short anecdote about an embarrassing or lucky moment – use at least three idioms.', 'Utanç verici ya da şanslı bir an hakkında kısa bir anekdot anlat – en az üç deyim kullan.', 'Erzähl eine Anekdote.'),
      points: [
        l('The situation', 'Durum', 'Situation'),
        l('What went wrong: „… ins Fettnäpfchen getreten“', 'Ne ters gitti: „… ins Fettnäpfchen getreten“', 'Fettnäpfchen'),
        l('The lucky turn: „… Schwein gehabt“', 'Şanslı dönüş: „… Schwein gehabt“', 'Schwein'),
        l('Your lesson from it', 'Çıkardığın ders', 'Fazit'),
      ],
      model: [
        'Letztes Jahr bin ich auf einer Hochzeit richtig ins Fettnäpfchen getreten.',
        'Ich habe die Braut gefragt, ob sie die Schwester des Bräutigams ist.',
        'Zum Glück fand sie es lustig – da hatte ich echt Schwein.',
        'Seitdem denke ich zweimal nach, bevor ich etwas frage.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short message to a friend (at least 6 sentences) about a stressful week. Use at least three idioms from this unit.',
        'Bir arkadaşına stresli bir hafta hakkında kısa bir mesaj yaz (en az 6 cümle). Bu üniteden en az üç deyim kullan.',
        'Nachricht an einen Freund (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Luck or bad luck (Schwein, Daumen)', 'Şans ya da şanssızlık (Schwein, Daumen)', 'Glück'), pattern: '(Schwein|Daumen)' },
        { label: l('Annoyance or delay (Wecker, lange Bank)', 'Sinir ya da erteleme (Wecker, lange Bank)', 'Ärger'), pattern: '(Wecker|lange[n]? Bank|Keks)' },
        { label: l('Another idiom (Fettnäpfchen, Holzweg, Nagel, Ärmel, vier Augen, Tomaten)', 'Başka bir deyim (Fettnäpfchen, Holzweg, Nagel, Ärmel, vier Augen, Tomaten)', 'Redewendung'), pattern: '(Fettnäpfchen|Holzweg|Nagel|Ärmel|vier Augen|Tomaten|Katze im Sack|Gras)' },
      ],
      model: [
        'Hallo Lena, was für eine Woche!',
        'Mein Kollege geht mir mit seinen ständigen Fragen total auf den Wecker.',
        'Außerdem habe ich die Präsentation immer wieder auf die lange Bank geschoben.',
        'Am Montag bin ich dann noch beim Chef ins Fettnäpfchen getreten.',
        'Zum Glück hat er nur gelacht – da hatte ich echt Schwein.',
        'Drück mir die Daumen, dass die Präsentation am Freitag klappt!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Complete the idiom – 60 seconds.', 'Deyimi tamamla – 60 saniye.', 'Redewendung ergänzen – 60 Sekunden.'),
      seconds: 60,
      pool: [...RW.map(([id]) => `rw-${id}`), 'mc-fettnaepfchen'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Idioms have a figurative meaning (Schwein haben = Glück haben)', 'Deyimlerin mecazi anlamı vardır (Schwein haben = Glück haben)', 'bildlich'),
      l('The nouns are fixed, the verb is conjugated normally', 'İsimler sabittir, fiil normal çekimlenir', 'feste Form'),
      l('Infer the meaning from context and tone', 'Anlamı bağlam ve tondan çıkar', 'Kontext'),
      l('Many idioms are colloquial – watch the register', 'Birçok deyim günlük dildir – üsluba dikkat et', 'Register'),
    ],
    mistakes: [
      { wrong: 'Ich drücke dir die Finger.', right: 'Ich drücke dir die Daumen.', note: l('Thumbs, not fingers.', 'Parmak değil başparmak.', 'Daumen.') },
      { wrong: 'Du bist auf den Holzweg.', right: 'Du bist auf dem Holzweg.', note: l('Location → dative.', 'Konum → Dativ.', 'Dativ.') },
      { wrong: 'Da hast du Glück-Schwein gehabt.', right: 'Da hast du Schwein gehabt.', note: l('Keep the idiom fixed.', 'Deyimi olduğu gibi kullan.', 'feste Form.') },
      { wrong: 'Sehr geehrte Damen und Herren, das geht mir auf den Wecker.', right: 'Sehr geehrte Damen und Herren, das ärgert mich sehr.', note: l('Colloquial idioms don’t fit formal letters.', 'Günlük deyimler resmî mektuplara uymaz.', 'Register.') },
    ],
  },
}
