import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Filterblase', emoji: '🫧', translation: l('filter bubble', 'filtre balonu', 'man sieht nur passende Inhalte'), example: 'Algorithmen können uns in eine Filterblase einschließen.' },
  { word: 'die Falschmeldung', emoji: '🚫', translation: l('false report, fake news', 'yalan haber', 'Fake News'), example: 'Die Falschmeldung verbreitete sich rasend schnell.' },
  { word: 'manipulieren', emoji: '🎭', translation: l('to manipulate', 'manipüle etmek', 'heimlich beeinflussen'), example: 'Bilder lassen sich heute leicht manipulieren.' },
  { word: 'die Medienkompetenz', emoji: '🧠', translation: l('media literacy', 'medya okuryazarlığı', 'kritisch mit Medien umgehen'), example: 'Medienkompetenz sollte schon in der Grundschule vermittelt werden.' },
  { word: 'die Quelle überprüfen', emoji: '🔍', translation: l('to check the source', 'kaynağı kontrol etmek', 'prüfen, woher etwas kommt'), example: 'Bevor man etwas teilt, sollte man die Quelle überprüfen.' },
  { word: 'seriös', emoji: '🗞️', translation: l('reputable, serious', 'güvenilir, ciddi', 'vertrauenswürdig'), example: 'Seriöse Zeitungen trennen Nachricht und Meinung.' },
  { word: 'der Algorithmus', emoji: '⚙️', translation: l('algorithm', 'algoritma', 'Rechenregel'), example: 'Der Algorithmus zeigt uns, was wir sehen wollen.' },
  { word: 'die Schlagzeile', emoji: '📰', translation: l('headline', 'manşet', 'Überschrift'), example: 'Reißerische Schlagzeilen sollen Klicks erzeugen.' },
  { word: 'reißerisch', emoji: '💥', translation: l('sensationalist', 'sansasyonel', 'übertrieben dramatisch'), example: 'Der Artikel war sehr reißerisch formuliert.' },
  { word: 'angeblich', emoji: '🤨', translation: l('allegedly', 'güya, iddiaya göre', 'nicht bewiesen'), example: 'Der Politiker soll angeblich Geld genommen haben.' },
  { word: 'der Faktencheck', emoji: '✔️', translation: l('fact check', 'doğruluk kontrolü', 'Prüfung von Fakten'), example: 'Ein Faktencheck widerlegte die Behauptung.' },
  { word: 'aus dem Zusammenhang gerissen', emoji: '✂️', translation: l('taken out of context', 'bağlamından koparılmış', 'ohne Kontext'), example: 'Das Zitat wurde aus dem Zusammenhang gerissen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Behauptung', gender: 'f', plural: 'die Behauptungen', translation: l('claim', 'iddia', 'Behauptung') },
  { word: 'Verschwörungstheorie', gender: 'f', plural: 'die Verschwörungstheorien', translation: l('conspiracy theory', 'komplo teorisi', 'Verschwörungstheorie') },
  { word: 'Glaubwürdigkeit', gender: 'f', translation: l('credibility', 'inanılırlık', 'Glaubwürdigkeit') },
  { word: 'Desinformation', gender: 'f', translation: l('disinformation', 'dezenformasyon', 'Desinformation') },
  { word: 'Impressum', gender: 'n', translation: l('legal notice (website)', 'künye', 'Impressum') },
  { word: 'Beitrag', gender: 'm', plural: 'die Beiträge', translation: l('post, article', 'gönderi, yazı', 'Beitrag') },
  { word: 'Meinungsmache', gender: 'f', translation: l('propaganda, opinion-shaping', 'kamuoyu manipülasyonu', 'Meinungsmache') },
  { word: 'Berichterstattung', gender: 'f', translation: l('reporting, coverage', 'haber yapma', 'Berichterstattung') },
]

/** [id, sentence with gap, right, wrong] */
const MK: [string, string, string, [string, string]][] = [
  ['soll', 'Der Minister ___ angeblich Steuern hinterzogen haben – bewiesen ist das nicht.', 'soll', ['muss', 'will']],
  ['will', 'Der Zeuge ___ den Täter gesehen haben, aber niemand glaubt ihm.', 'will', ['soll', 'kann']],
  ['angeblich', 'Das Foto zeigt ___ den Präsidenten – es ist jedoch eine Fälschung.', 'angeblich', ['tatsächlich', 'eindeutig']],
  ['quelle', 'Bevor du den Beitrag teilst, solltest du die ___ überprüfen.', 'Quelle', ['Brunnen', 'Wurzel']],
  ['zusammenhang', 'Das Zitat wurde aus dem ___ gerissen und dadurch verfälscht.', 'Zusammenhang', ['Zusammenhalt', 'Zusammenbruch']],
  ['serioes', 'Eine ___ Nachrichtenseite hat immer ein Impressum.', 'seriöse', ['seriös', 'seriösen']],
]

function mkDrills(): Exercise[] {
  return MK.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `mk-${id}`,
      type: 'multiple_choice' as const,
      topic: 'manipulation',
      concept: 'distance',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Expressing distance from unproven claims: sollen + perfect infinitive = others claim it (Er soll gelogen haben). wollen + perfect infinitive = the person claims it about himself (Er will es gesehen haben). angeblich = allegedly.',
        'Kanıtlanmamış iddialara mesafe koymak: sollen + geçmiş mastar = başkaları iddia ediyor (Er soll gelogen haben). wollen + geçmiş mastar = kişi bunu kendisi hakkında iddia ediyor (Er will es gesehen haben). angeblich = güya.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-tricks',
    type: 'matching',
    topic: 'manipulation',
    concept: 'techniques',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Match the manipulation technique and its description.', 'Manipülasyon tekniğini açıklamasıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'reißerische Schlagzeile', right: 'soll Klicks erzeugen' },
      { left: 'aus dem Zusammenhang gerissen', right: 'Zitat ohne Kontext' },
      { left: 'manipuliertes Foto', right: 'Bild wurde verändert' },
      { left: 'Filterblase', right: 'man sieht nur die eigene Meinung' },
      { left: 'Bot-Netzwerk', right: 'künstliche Accounts verbreiten Inhalte' },
    ],
    explanation: l('Knowing the tricks helps you spot manipulation.', 'Hileleri bilmek manipülasyonu fark etmeye yardım eder.', 'Tricks.'),
  },
  {
    id: 'sort-serioes',
    type: 'categorize',
    topic: 'quellen',
    concept: 'credibility',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Sign of a reputable or dubious source?', 'Güvenilir mi şüpheli mi kaynak işareti?', 'Seriös oder unseriös?'),
    categories: ['seriös ✅', 'unseriös ⚠️'],
    items: [
      { text: 'Impressum mit Adresse', category: 0 },
      { text: 'nur Großbuchstaben und Ausrufezeichen', category: 1 },
      { text: 'mehrere unabhängige Quellen', category: 0 },
      { text: '„Das verschweigen die Medien!“', category: 1 },
      { text: 'Trennung von Nachricht und Kommentar', category: 0 },
      { text: 'kein Autor, kein Datum', category: 1 },
    ],
    explanation: l('Transparency and multiple sources = credibility.', 'Şeffaflık ve birden fazla kaynak = güvenilirlik.', 'Glaubwürdigkeit.'),
    practice: ['mk-quelle'],
  },
  {
    id: 'mc-soll',
    type: 'multiple_choice',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'reading',
    difficulty: 3,
    prompt: '„Der Sänger soll die Konzerte abgesagt haben.“ Was bedeutet das?',
    options: ['Es wird behauptet, ist aber nicht bestätigt.', 'Der Sänger muss die Konzerte absagen.', 'Der Sänger hat es selbst gesagt.'],
    answer: 0,
    explanation: l('sollen + perfect infinitive = rumour / report by others.', 'sollen + geçmiş mastar = söylenti / başkalarının aktarımı.', 'soll.'),
    practice: ['fill-soll'],
  },
  {
    id: 'tf-filterblase',
    type: 'true_false',
    topic: 'medienkompetenz',
    concept: 'filter-bubble',
    skill: 'reading',
    difficulty: 2,
    statement: 'In einer Filterblase sieht man vor allem Inhalte, die der eigenen Meinung widersprechen.',
    answer: false,
    explanation: l('The opposite: you mainly see content that confirms your view.', 'Tersi: daha çok görüşünü doğrulayan içerikleri görürsün.', 'falsch.'),
  },
  {
    id: 'select-pruefen',
    type: 'multiple_select',
    topic: 'quellen',
    concept: 'check',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('How can you check whether a news item is true? Select all.', 'Bir haberin doğru olup olmadığını nasıl kontrol edebilirsin? Hepsini seç.', 'Wie prüft man eine Nachricht?'),
    options: ['bei anderen Medien gegenrecherchieren', 'Bilder per Rückwärtssuche prüfen', 'nur die Schlagzeile lesen', 'Faktencheck-Seiten nutzen', 'die Anzahl der Likes zählen'],
    answers: [0, 1, 3],
    explanation: l('Cross-check, reverse image search, fact-check sites.', 'Çapraz kontrol, tersine görsel arama, doğruluk kontrol siteleri.', 'prüfen.'),
  },
  {
    id: 'image-blase',
    type: 'image_choice',
    topic: 'medienkompetenz',
    concept: 'filter-bubble',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'die Filterblase',
    options: [
      { emoji: '🫧', label: 'Blase' },
      { emoji: '📺', label: 'Fernseher' },
      { emoji: '📻', label: 'Radio' },
      { emoji: '📬', label: 'Briefkasten' },
    ],
    answer: 0,
    explanation: l('die Blase = bubble.', 'die Blase = baloncuk.', 'Blase.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-soll',
    type: 'fill_blank',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Laut Gerüchten ___ der Konzern Daten an Dritte verkauft haben.',
    accepted: ['soll'],
    base: 'sollen (Distanz)',
    explanation: l('sollen + perfect infinitive = it is said that …', 'sollen + geçmiş mastar = … olduğu söyleniyor', 'soll.'),
    examples: ['Der Konzern **soll** Daten verkauft **haben**.'],
  },
  {
    id: 'fill-ueberpruefen',
    type: 'fill_blank',
    topic: 'quellen',
    concept: 'check',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Journalisten müssen jede Information sorgfältig ___.',
    accepted: ['überprüfen', 'prüfen', 'ueberpruefen'],
    base: 'kontrollieren',
    explanation: l('Informationen (über)prüfen = to check information.', 'Informationen (über)prüfen = bilgiyi kontrol etmek.', 'überprüfen.'),
    examples: ['… jede Information sorgfältig **überprüfen**.'],
  },
  {
    id: 'fill-angeblich',
    type: 'fill_blank',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Das Video zeigt ___ einen Angriff – in Wahrheit stammt es aus einem Film.',
    accepted: ['angeblich', 'vermeintlich', 'scheinbar'],
    base: 'nicht bewiesen',
    explanation: l('angeblich = allegedly (a claim, not a fact).', 'angeblich = güya (gerçek değil, iddia).', 'angeblich.'),
    examples: ['Das Video zeigt **angeblich** einen Angriff.'],
  },
  {
    id: 'build-algorithmus',
    type: 'sentence_builder',
    topic: 'medienkompetenz',
    concept: 'filter-bubble',
    skill: 'writing',
    difficulty: 3,
    chips: ['die unsere Meinung bestätigen', 'Algorithmen', 'vor allem Inhalte,', 'zeigen uns'],
    answers: [['Algorithmen', 'zeigen uns', 'vor allem Inhalte,', 'die unsere Meinung bestätigen']],
    translation: l('Algorithms mainly show us content that confirms our opinion.', 'Algoritmalar bize çoğunlukla görüşümüzü doğrulayan içerikleri gösteriyor.', 'Algorithmen zeigen uns vor allem Inhalte, die unsere Meinung bestätigen.'),
    explanation: l('Relative clause with verb at the end.', 'Fiili sonda olan ilgi cümlesi.', 'Relativsatz.'),
    examples: ['…, die unsere Meinung **bestätigen**.'],
  },
  {
    id: 'build-teilen',
    type: 'sentence_builder',
    topic: 'quellen',
    concept: 'check',
    skill: 'writing',
    difficulty: 3,
    chips: ['sollte man', 'Bevor man etwas teilt,', 'prüfen', 'die Quelle'],
    answers: [['Bevor man etwas teilt,', 'sollte man', 'die Quelle', 'prüfen']],
    translation: l('Before sharing something, you should check the source.', 'Bir şeyi paylaşmadan önce kaynağı kontrol etmelisin.', 'Bevor man etwas teilt, sollte man die Quelle prüfen.'),
    explanation: l('Subordinate clause first → verb of the main clause comes next.', 'Önce yan cümle → ardından ana cümlenin fiili.', 'Verb zuerst.'),
    examples: ['Bevor man etwas teilt, **sollte** man die Quelle prüfen.'],
  },
  {
    id: 'build-medienkompetenz',
    type: 'sentence_builder',
    topic: 'medienkompetenz',
    concept: 'education',
    skill: 'writing',
    difficulty: 3,
    chips: ['in der Schule', 'Medienkompetenz', 'vermittelt werden', 'sollte'],
    answers: [['Medienkompetenz', 'sollte', 'in der Schule', 'vermittelt werden']],
    translation: l('Media literacy should be taught at school.', 'Medya okuryazarlığı okulda öğretilmeli.', 'Medienkompetenz sollte in der Schule vermittelt werden.'),
    explanation: l('Modal + passive infinitive: sollte vermittelt werden.', 'Modal + edilgen mastar: sollte vermittelt werden.', 'Passiv.'),
    examples: ['Medienkompetenz **sollte** in der Schule **vermittelt werden**.'],
  },
  {
    id: 'fix-soll',
    type: 'error_correction',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Politiker soll gestern gelogen.',
    accepted: ['Der Politiker soll gestern gelogen haben.'],
    explanation: l('Past claim: soll + participle + haben.', 'Geçmiş iddia: soll + ortaç + haben.', 'haben.'),
    examples: ['Der Politiker soll gestern gelogen **haben**.'],
  },
  {
    id: 'fix-will',
    type: 'error_correction',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Sie soll das UFO selbst gesehen haben, behauptet sie.',
    accepted: ['Sie will das UFO selbst gesehen haben.', 'Sie will das UFO selbst gesehen haben, behauptet sie.'],
    explanation: l('She claims it about herself → wollen.', 'Kendisi hakkında iddia ediyor → wollen.', 'will.'),
    examples: ['Sie **will** das UFO selbst gesehen haben.'],
  },
  {
    id: 'fix-quelle',
    type: 'error_correction',
    topic: 'quellen',
    concept: 'word-order',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Bevor man etwas teilt, man sollte die Quelle prüfen.',
    accepted: ['Bevor man etwas teilt, sollte man die Quelle prüfen.', 'Bevor man etwas teilt, sollte man die Quelle überprüfen.'],
    explanation: l('After a subordinate clause the main-clause verb comes first.', 'Yan cümleden sonra ana cümlenin fiili önce gelir.', 'Verb zuerst.'),
    examples: ['Bevor man etwas teilt, **sollte man** die Quelle prüfen.'],
  },
  {
    id: 'tr-falsch',
    type: 'translation',
    topic: 'manipulation',
    concept: 'fake',
    skill: 'writing',
    difficulty: 3,
    source: l('The false report spread very quickly.', 'Yalan haber çok hızlı yayıldı.', 'The false report spread very quickly.'),
    accepted: ['Die Falschmeldung verbreitete sich sehr schnell.', 'Die Falschmeldung hat sich sehr schnell verbreitet.', 'Die Falschmeldung verbreitete sich rasend schnell.'],
    explanation: l('sich verbreiten = to spread.', 'sich verbreiten = yayılmak.', 'verbreiten.'),
    examples: ['Die Falschmeldung **verbreitete sich** sehr schnell.'],
  },
  {
    id: 'tr-zitat',
    type: 'translation',
    topic: 'quellen',
    concept: 'context',
    skill: 'writing',
    difficulty: 3,
    source: l('The quote was taken out of context.', 'Alıntı bağlamından koparıldı.', 'The quote was taken out of context.'),
    accepted: ['Das Zitat wurde aus dem Zusammenhang gerissen.', 'Das Zitat wurde aus dem Kontext gerissen.'],
    explanation: l('aus dem Zusammenhang reißen – passive: wurde gerissen.', 'aus dem Zusammenhang reißen – edilgen: wurde gerissen.', 'gerissen.'),
    examples: ['Das Zitat **wurde** aus dem Zusammenhang **gerissen**.'],
  },
  {
    id: 'ordering-check',
    type: 'ordering',
    topic: 'quellen',
    concept: 'steps',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Order the steps of a fact check.', 'Bir doğruluk kontrolünün adımlarını sırala.', 'Ordne die Schritte.'),
    items: ['Danach recherchiert man, ob seriöse Medien darüber berichten.', 'Zuerst prüft man, wer den Beitrag veröffentlicht hat.', 'Erst dann entscheidet man, ob man den Beitrag teilt.', 'Anschließend überprüft man Fotos mit einer Rückwärtssuche.'],
    answer: ['Zuerst prüft man, wer den Beitrag veröffentlicht hat.', 'Danach recherchiert man, ob seriöse Medien darüber berichten.', 'Anschließend überprüft man Fotos mit einer Rückwärtssuche.', 'Erst dann entscheidet man, ob man den Beitrag teilt.'],
    explanation: l('Source → cross-check → images → decision.', 'Kaynak → çapraz kontrol → görseller → karar.', 'Schritte.'),
  },
  {
    id: 'dialog-oma',
    type: 'dialogue',
    topic: 'medienkompetenz',
    concept: 'react',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Onkel', de: 'Hast du gelesen? Ab nächster Woche soll Bargeld komplett verboten werden! Steht auf so einer Seite.' }],
    options: ['Das klingt unwahrscheinlich. Lass uns mal prüfen, ob seriöse Medien darüber berichten.', 'Dann muss ich sofort alles Geld abheben!', 'Steht im Internet, also stimmt.'],
    answer: 0,
    explanation: l('React calmly and suggest checking the source.', 'Sakin tepki ver ve kaynağı kontrol etmeyi öner.', 'prüfen.'),
  },
  {
    id: 'dialog-blase',
    type: 'dialogue',
    topic: 'medienkompetenz',
    concept: 'filter-bubble',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Freundin', de: 'Komisch, in meinem Feed sind alle meiner Meinung.' }],
    options: ['Vielleicht steckst du in einer Filterblase. Lies doch mal bewusst Medien mit anderen Perspektiven.', 'Dann hast du immer recht.', 'Filterblase ist ein Getränk.'],
    answer: 0,
    explanation: l('Explain the filter bubble and give advice.', 'Filtre balonunu açıkla ve tavsiye ver.', 'Filterblase.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-fake',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Text?',
    options: ['Wie sich Falschmeldungen verbreiten und wie man sie erkennt.', 'Wie man eine Zeitung gründet.', 'Wie Algorithmen programmiert werden.'],
    answer: 0,
    explanation: l('„Warum sich Fake News so schnell verbreiten …“', '„Warum sich Fake News so schnell verbreiten …“', 'Fake News.'),
  },
  {
    id: 'read-studie',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-fake',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was hat die Studie herausgefunden?',
    options: ['Falschmeldungen verbreiten sich schneller als wahre Nachrichten.', 'Wahre Nachrichten verbreiten sich schneller.', 'Es gibt keinen Unterschied.'],
    answer: 0,
    explanation: l('„… verbreiten sich Falschmeldungen deutlich schneller …“', '„… verbreiten sich Falschmeldungen deutlich schneller …“', 'schneller.'),
  },
  {
    id: 'read-gefuehl',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-fake',
    skill: 'reading',
    difficulty: 3,
    statement: 'Laut Text werden Falschmeldungen oft geteilt, weil sie starke Gefühle auslösen.',
    answer: true,
    explanation: l('„Sie lösen Empörung oder Angst aus …“', '„Sie lösen Empörung oder Angst aus …“', 'richtig.'),
  },
  {
    id: 'read-rat',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-fake',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was raten Experten?',
    options: ['kurz innezuhalten und die Quelle zu prüfen', 'sofort alles zu teilen', 'keine Nachrichten mehr zu lesen'],
    answer: 0,
    explanation: l('„… kurz innezuhalten und die Quelle zu prüfen.“', '„… kurz innezuhalten und die Quelle zu prüfen.“', 'innehalten.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-will',
    type: 'listening_choice',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'listening',
    difficulty: 3,
    audio: 'Der Influencer will mit dem Wundermittel zehn Kilo in einer Woche abgenommen haben.',
    question: l('Who makes the claim?', 'İddiayı kim ortaya atıyor?', 'Wer behauptet das?'),
    options: ['the influencer himself', 'a doctor', 'a study'],
    answer: 0,
    explanation: l('wollen + perfect infinitive = he claims it himself.', 'wollen + geçmiş mastar = kendisi iddia ediyor.', 'will.'),
  },
  {
    id: 'listen-soll',
    type: 'listening_choice',
    topic: 'manipulation',
    concept: 'distance',
    skill: 'listening',
    difficulty: 3,
    audio: 'Die Schauspielerin soll heimlich geheiratet haben. Eine Bestätigung gibt es bisher nicht.',
    question: l('How certain is the news?', 'Haber ne kadar kesin?', 'Wie sicher ist die Nachricht?'),
    options: ['It’s a rumour, not confirmed.', 'It is confirmed.', 'She denied it.'],
    answer: 0,
    explanation: l('soll + keine Bestätigung = rumour.', 'soll + keine Bestätigung = söylenti.', 'Gerücht.'),
  },
  {
    id: 'listen-foto',
    type: 'listening_choice',
    topic: 'quellen',
    concept: 'check',
    skill: 'listening',
    difficulty: 3,
    audio: 'Eine Rückwärtssuche hat gezeigt: Das angebliche Flutfoto stammt in Wahrheit aus dem Jahr 2013.',
    question: l('What did the reverse search show?', 'Tersine arama neyi gösterdi?', 'Was zeigte die Suche?'),
    options: ['The photo is old and used out of context.', 'The photo is current.', 'The photo was painted.'],
    answer: 0,
    explanation: l('Old photo, new false context.', 'Eski fotoğraf, yeni yanlış bağlam.', 'alt.'),
  },
  {
    id: 'listen-schule',
    type: 'listening_choice',
    topic: 'medienkompetenz',
    concept: 'education',
    skill: 'listening',
    difficulty: 2,
    audio: 'An unserer Schule gibt es seit diesem Jahr ein Fach Medienkompetenz. Die Schüler lernen dort, Quellen kritisch zu prüfen.',
    question: l('What do the pupils learn?', 'Öğrenciler ne öğreniyor?', 'Was lernen die Schüler?'),
    options: ['to check sources critically', 'to program apps', 'to write newspapers'],
    answer: 0,
    explanation: l('Quellen kritisch prüfen.', 'Quellen kritisch prüfen.', 'Quellen.'),
  },

  ...mkDrills(),
]

export const UNIT_C1_14_MEDIENKRITIK: CourseUnit = {
  level: 'C1',
  number: 14,
  slug: 'medienkritik',
  titleDe: 'Filterblasen und Fake News',
  title: l('Filter bubbles and fake news', 'Filtre balonları ve yalan haberler', 'Filterblasen und Fake News'),
  goal: l(
    'By the end of this unit you can recognise manipulation in the media, express distance from unproven claims (soll / will + perfect infinitive, angeblich) and explain how to check sources critically.',
    'Bu ünitenin sonunda medyadaki manipülasyonu tanıyabilir, kanıtlanmamış iddialara mesafe koyabilir (soll / will + geçmiş mastar, angeblich) ve kaynakların eleştirel olarak nasıl kontrol edileceğini açıklayabilirsin.',
    'Am Ende dieser Einheit gehst du kritisch mit Medien um.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'manipulation', label: l('Recognising manipulation', 'Manipülasyonu tanımak', 'Manipulation erkennen') },
    { key: 'medienkompetenz', label: l('Media literacy', 'Medya okuryazarlığı', 'Medienkompetenz') },
    { key: 'quellen', label: l('Checking sources critically', 'Kaynakları eleştirel kontrol etmek', 'Quellen prüfen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('True, false or manipulated?', 'Doğru, yanlış ya da manipüle edilmiş?', 'Wahr oder falsch?'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Distance with sollen and wollen', 'sollen ve wollen ile mesafe', 'Distanz mit sollen und wollen'),
          body: l(
            'sollen = others claim it: Der Minister soll gelogen haben (it is said that he lied). wollen = the person claims it about himself: Er will nichts gewusst haben (he claims he knew nothing). For the past use the perfect infinitive: participle + haben / sein.',
            'sollen = başkaları iddia ediyor: Der Minister soll gelogen haben (yalan söylediği söyleniyor). wollen = kişi kendisi hakkında iddia ediyor: Er will nichts gewusst haben (hiçbir şey bilmediğini iddia ediyor). Geçmiş için geçmiş mastar kullan: ortaç + haben / sein.',
            'sollen / wollen.'
          ),
          table: {
            head: [l('Sentence', 'Cümle', 'Satz'), l('Meaning', 'Anlam', 'Bedeutung')],
            rows: [
              ['Er soll reich sein.', 'Man sagt, er ist reich.'],
              ['Er soll gelogen haben.', 'Man sagt, er hat gelogen.'],
              ['Er will es gesehen haben.', 'Er behauptet, er hat es gesehen.'],
              ['Sie will unschuldig sein.', 'Sie behauptet, sie ist unschuldig.'],
            ],
          },
        },
        {
          title: l('Typical manipulation', 'Tipik manipülasyon', 'Typische Manipulation'),
          body: l(
            'Watch out for: reißerische Schlagzeilen (sensational headlines), quotes aus dem Zusammenhang gerissen, manipulated or old photos, missing sources, emotional language („Das verschweigen die Medien!“) and filter bubbles created by algorithms.',
            'Dikkat et: reißerische Schlagzeilen (sansasyonel manşetler), aus dem Zusammenhang gerissen (bağlamından koparılmış) alıntılar, manipüle edilmiş ya da eski fotoğraflar, eksik kaynaklar, duygusal dil („Das verschweigen die Medien!“) ve algoritmaların yarattığı filtre balonları.',
            'Manipulation.'
          ),
          examples: [
            { de: 'Das Foto zeigt **angeblich** eine Demo von heute.', translation: l('The photo allegedly shows a demo from today.', 'Fotoğraf güya bugünkü bir gösteriyi gösteriyor.', '') },
            { de: 'Das Zitat wurde **aus dem Zusammenhang gerissen**.', translation: l('The quote was taken out of context.', 'Alıntı bağlamından koparıldı.', '') },
          ],
        },
        {
          title: l('Checking sources', 'Kaynakları kontrol etmek', 'Quellen prüfen'),
          body: l(
            'Ask: Wer hat das veröffentlicht? (Impressum, author, date) – Berichten seriöse Medien darüber? – Ist das Bild echt? (reverse image search) – Gibt es einen Faktencheck? Only then share.',
            'Sor: Wer hat das veröffentlicht? (künye, yazar, tarih) – Berichten seriöse Medien darüber? – Ist das Bild echt? (tersine görsel arama) – Gibt es einen Faktencheck? Ancak ondan sonra paylaş.',
            'prüfen.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two flatmates look at a viral post.', 'İki ev arkadaşı viral bir gönderiye bakıyor.', 'Ein viraler Beitrag.'),
      dialogue: [
        { speaker: 'Lea', de: 'Schau mal: Ein Bürgermeister **soll** Flüchtlingen Luxuswohnungen geschenkt **haben**!', translation: l('Look: a mayor is said to have given refugees luxury flats!', 'Bak: Bir belediye başkanının mültecilere lüks daireler hediye ettiği söyleniyor!', '') },
        { speaker: 'Kerem', de: 'Hm, die **Schlagzeile** ist ziemlich **reißerisch**. Wer hat das veröffentlicht?', translation: l('Hm, the headline is pretty sensationalist. Who published it?', 'Hmm, manşet oldukça sansasyonel. Kim yayımlamış?', '') },
        { speaker: 'Lea', de: 'Keine Ahnung, es gibt kein **Impressum**. Aber es wurde schon 20.000 Mal geteilt.', translation: l('No idea, there’s no legal notice. But it’s already been shared 20,000 times.', 'Bilmiyorum, künye yok. Ama şimdiden 20.000 kez paylaşılmış.', '') },
        { speaker: 'Kerem', de: 'Das heißt gar nichts. Lass uns einen **Faktencheck** suchen.', translation: l('That means nothing. Let’s look for a fact check.', 'Bu hiçbir şey ifade etmez. Bir doğruluk kontrolü arayalım.', '') },
        { speaker: 'Lea', de: 'Oh. Hier steht: Die Meldung ist **falsch**, das Foto stammt aus einem Hotelprospekt.', translation: l('Oh. It says here: the report is false, the photo comes from a hotel brochure.', 'Oo. Burada yazıyor: Haber yanlış, fotoğraf bir otel broşüründen.', '') },
        { speaker: 'Kerem', de: 'Siehst du – klassische **Desinformation**. Erst **prüfen**, dann teilen.', translation: l('You see – classic disinformation. Check first, then share.', 'Gördün mü – klasik dezenformasyon. Önce kontrol et, sonra paylaş.', '') },
      ],
      examples: [
        { de: 'Er **soll** Geld genommen **haben**.', translation: l('He is said to have taken money.', 'Para aldığı söyleniyor.', '') },
        { de: 'Sie **will** nichts gewusst **haben**.', translation: l('She claims to have known nothing.', 'Hiçbir şey bilmediğini iddia ediyor.', '') },
        { de: 'Das ist eine **Falschmeldung**.', translation: l('That’s a false report.', 'Bu yalan bir haber.', '') },
        { de: 'Wir leben oft in einer **Filterblase**.', translation: l('We often live in a filter bubble.', 'Çoğu zaman bir filtre balonunda yaşıyoruz.', '') },
        { de: 'Man sollte die **Quelle überprüfen**.', translation: l('You should check the source.', 'Kaynağı kontrol etmek gerekir.', '') },
        { de: '**Seriöse** Medien trennen Nachricht und Meinung.', translation: l('Reputable media separate news and opinion.', 'Güvenilir medya haber ile yorumu ayırır.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Spot manipulation and distance.', 'Manipülasyonu ve mesafeyi fark et.', 'Manipulation erkennen.'),
      exercises: ['match-tricks', 'sort-serioes', 'mk-soll', 'mk-will', 'mk-angeblich', 'mc-soll', 'tf-filterblase', 'select-pruefen', 'image-blase'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Report critically.', 'Eleştirel biçimde aktar.', 'Kritisch berichten.'),
      exercises: [
        'fill-soll',
        'fill-ueberpruefen',
        'fill-angeblich',
        'build-algorithmus',
        'build-teilen',
        'build-medienkompetenz',
        'fix-soll',
        'fix-will',
        'fix-quelle',
        'tr-falsch',
        'tr-zitat',
        'ordering-check',
        'dialog-oma',
        'dialog-blase',
        'mk-quelle',
        'mk-zusammenhang',
        'mk-serioes',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Why fake news spreads so fast.', 'Yalan haberler neden bu kadar hızlı yayılıyor.', 'Warum Fake News sich verbreiten.'),
      passage: [
        '**Warum sich Fake News so schnell verbreiten** – Einer großen Studie zufolge verbreiten sich Falschmeldungen in sozialen Netzwerken deutlich schneller als wahre Nachrichten.',
        'Der Grund: Sie sind oft überraschend und emotional. Sie lösen Empörung oder Angst aus – und genau solche Inhalte werden besonders häufig geteilt.',
        'Algorithmen verstärken diesen Effekt, denn sie zeigen uns bevorzugt, was viele Reaktionen hervorruft. So entstehen **Filterblasen**, in denen kaum widersprechende Informationen ankommen.',
        'Experten raten deshalb, vor dem Teilen kurz innezuhalten und die Quelle zu prüfen. **Medienkompetenz** gilt heute als ebenso wichtig wie Lesen und Schreiben.',
      ],
      glossary: [
        { de: 'die Empörung', note: l('outrage', 'öfke, infial', 'starker Ärger') },
        { de: 'verstärken', note: l('to amplify', 'güçlendirmek', 'stärker machen') },
        { de: 'hervorrufen', note: l('to provoke, cause', 'yol açmak', 'auslösen') },
        { de: 'innehalten', note: l('to pause', 'durup düşünmek', 'kurz stoppen') },
      ],
      exercises: ['read-thema', 'read-studie', 'read-gefuehl', 'read-rat'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Rumours, claims and fact checks.', 'Söylentiler, iddialar ve doğruluk kontrolleri.', 'Gerüchte und Fakten.'),
      exercises: ['listen-will', 'listen-soll', 'listen-foto', 'listen-schule'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('A friend shares a dubious news item. Explain politely why you doubt it and how to check it.', 'Bir arkadaşın şüpheli bir haber paylaşıyor. Neden şüphelendiğini ve nasıl kontrol edilebileceğini kibarca açıkla.', 'Zweifel äußern.'),
      points: [
        l('Distance: „Das soll … haben / angeblich …“', 'Mesafe: „Das soll … haben / angeblich …“', 'Distanz'),
        l('A warning sign: no Impressum, reißerische Schlagzeile', 'Bir uyarı işareti: künye yok, sansasyonel manşet', 'Warnsignal'),
        l('How to check: Faktencheck, Rückwärtssuche', 'Nasıl kontrol edilir: doğruluk kontrolü, tersine arama', 'prüfen'),
        l('Advice: „Erst prüfen, dann teilen.“', 'Tavsiye: „Erst prüfen, dann teilen.“', 'Rat'),
      ],
      model: [
        'Der Politiker soll das gesagt haben – aber ich finde dafür keine seriöse Quelle.',
        'Die Seite hat kein Impressum, und die Schlagzeile ist sehr reißerisch.',
        'Ich habe das Foto per Rückwärtssuche geprüft: Es ist fünf Jahre alt.',
        'Lass uns lieber erst prüfen und dann teilen.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short guide for younger pupils (at least 6 sentences): „So erkennst du Fake News“. Use distance forms and name concrete steps.',
        'Küçük öğrenciler için kısa bir rehber yaz (en az 6 cümle): „So erkennst du Fake News“. Mesafe biçimleri kullan ve somut adımlar belirt.',
        'Ratgeber (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Distance (soll / will … haben, angeblich)', 'Mesafe (soll / will … haben, angeblich)', 'Distanz'), pattern: '(\\b(soll|sollen|will|wollen)\\b[^.]*\\b(haben|sein)\\b|[Aa]ngeblich)' },
        { label: l('Checking (Quelle, prüfen, Faktencheck)', 'Kontrol (Quelle, prüfen, Faktencheck)', 'prüfen'), pattern: '(Quelle|prüf|Faktencheck|Rückwärtssuche)' },
        { label: l('A warning sign (Impressum, Schlagzeile, Filterblase)', 'Bir uyarı işareti (Impressum, Schlagzeile, Filterblase)', 'Warnsignal'), pattern: '(Impressum|Schlagzeile|Filterblase|reißerisch|Zusammenhang)' },
      ],
      model: [
        'Im Internet liest man jeden Tag Meldungen, die nicht stimmen.',
        'Oft heißt es, ein Star soll etwas Schlimmes getan haben.',
        'Achte zuerst auf die Schlagzeile: Ist sie sehr reißerisch, solltest du misstrauisch werden.',
        'Prüfe dann die Quelle und schau, ob die Seite ein Impressum hat.',
        'Suche außerdem nach einem Faktencheck oder nach Berichten in seriösen Medien.',
        'Teile eine Nachricht erst, wenn du sicher bist, dass sie stimmt.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Distance and sources – 60 seconds.', 'Mesafe ve kaynaklar – 60 saniye.', 'Distanz – 60 Sekunden.'),
      seconds: 60,
      pool: [...MK.map(([id]) => `mk-${id}`), 'mc-soll'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('sollen + perfect infinitive = others claim it', 'sollen + geçmiş mastar = başkaları iddia ediyor', 'sollen'),
      l('wollen + perfect infinitive = the person claims it', 'wollen + geçmiş mastar = kişi kendisi iddia ediyor', 'wollen'),
      l('Manipulation: reißerisch, aus dem Zusammenhang gerissen, Filterblase', 'Manipülasyon: reißerisch, aus dem Zusammenhang gerissen, Filterblase', 'Manipulation'),
      l('Check sources: Impressum, Faktencheck, Rückwärtssuche', 'Kaynak kontrolü: Impressum, Faktencheck, Rückwärtssuche', 'Quellen'),
    ],
    mistakes: [
      { wrong: 'Er soll gestern gelogen.', right: 'Er soll gestern gelogen haben.', note: l('Perfect infinitive: participle + haben.', 'Geçmiş mastar: ortaç + haben.', 'haben.') },
      { wrong: 'Sie soll das gesehen haben, sagt sie selbst.', right: 'Sie will das gesehen haben.', note: l('Own claim → wollen.', 'Kendi iddiası → wollen.', 'wollen.') },
      { wrong: 'Das Foto zeigt tatsächlich … (unbewiesen)', right: 'Das Foto zeigt angeblich …', note: l('Unproven → angeblich.', 'Kanıtlanmamış → angeblich.', 'angeblich.') },
      { wrong: 'Das Zitat wurde aus dem Zusammenhalt gerissen.', right: 'Das Zitat wurde aus dem Zusammenhang gerissen.', note: l('Zusammenhang = context.', 'Zusammenhang = bağlam.', 'Zusammenhang.') },
    ],
  },
}
