import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Hypothese', emoji: '🔬', translation: l('hypothesis', 'hipotez', 'Annahme, die geprüft wird'), example: 'Die Hypothese lautet, dass Schlaf das Lernen verbessert.' },
  { word: 'es ist anzunehmen, dass …', emoji: '🤔', translation: l('it can be assumed that …', '… olduğu varsayılabilir', 'vermutlich'), example: 'Es ist anzunehmen, dass der Effekt bei Kindern stärker ist.' },
  { word: 'laut (+ Dat./Gen.)', emoji: '📖', translation: l('according to', '… göre', 'nach Angabe von'), example: 'Laut Müller (2021) steigt die Zahl der Fälle.' },
  { word: 'zufolge (+ Dat., nachgestellt)', emoji: '📚', translation: l('according to (placed after)', '… göre (sonra gelir)', 'nach Angabe von'), example: 'Der Studie zufolge schlafen Jugendliche zu wenig.' },
  { word: 'sich lässt … feststellen', emoji: '📊', translation: l('… can be observed', '… tespit edilebilir', 'man kann feststellen'), example: 'Es lässt sich feststellen, dass die Werte sinken.' },
  { word: 'untersuchen', emoji: '🔎', translation: l('to investigate, examine', 'incelemek, araştırmak', 'erforschen'), example: 'Die Arbeit untersucht den Einfluss von Musik.' },
  { word: 'belegen', emoji: '✅', translation: l('to prove, provide evidence', 'kanıtlamak, belgelemek', 'beweisen'), example: 'Die Daten belegen einen klaren Zusammenhang.' },
  { word: 'die Stichprobe', emoji: '🎯', translation: l('sample', 'örneklem', 'Auswahl von Personen'), example: 'Die Stichprobe umfasste 300 Studierende.' },
  { word: 'signifikant', emoji: '📈', translation: l('significant', 'anlamlı (istatistik)', 'statistisch bedeutsam'), example: 'Der Unterschied ist signifikant.' },
  { word: 'die Schlussfolgerung', emoji: '🧩', translation: l('conclusion', 'çıkarım, sonuç', 'Ergebnis des Denkens'), example: 'Daraus lässt sich folgende Schlussfolgerung ziehen.' },
  { word: 'im Rahmen (+ Gen.)', emoji: '🖼️', translation: l('within the scope of', '… kapsamında', 'innerhalb'), example: 'Im Rahmen dieser Arbeit werden drei Thesen geprüft.' },
  { word: 'die Quelle', emoji: '🔗', translation: l('source', 'kaynak', 'Herkunft eines Zitats'), example: 'Jedes Zitat braucht eine Quellenangabe.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Studie', gender: 'f', plural: 'die Studien', translation: l('study', 'araştırma', 'Studie') },
  { word: 'Ergebnis', gender: 'n', plural: 'die Ergebnisse', translation: l('result', 'sonuç', 'Ergebnis') },
  { word: 'Zitat', gender: 'n', plural: 'die Zitate', translation: l('quotation', 'alıntı', 'Zitat') },
  { word: 'Paraphrase', gender: 'f', plural: 'die Paraphrasen', translation: l('paraphrase', 'başka sözcüklerle anlatım', 'Paraphrase') },
  { word: 'Befragung', gender: 'f', plural: 'die Befragungen', translation: l('survey', 'anket', 'Befragung') },
  { word: 'Zusammenhang', gender: 'm', plural: 'die Zusammenhänge', translation: l('correlation, connection', 'ilişki, bağlantı', 'Zusammenhang') },
  { word: 'Forschungsstand', gender: 'm', translation: l('state of research', 'araştırmanın mevcut durumu', 'Forschungsstand') },
  { word: 'Abbildung', gender: 'f', plural: 'die Abbildungen', translation: l('figure', 'şekil', 'Abbildung') },
]

/** [id, sentence with gap, right, wrong] */
const WS: [string, string, string, [string, string]][] = [
  ['zufolge', 'Der aktuellen Studie ___ schlafen Jugendliche durchschnittlich sieben Stunden.', 'zufolge', ['laut', 'gemäß nach']],
  ['laesst', 'Aus den Daten ___ sich ein klarer Zusammenhang ableiten.', 'lässt', ['macht', 'gibt']],
  ['anzunehmen', 'Es ist ___, dass der Effekt bei älteren Menschen geringer ausfällt.', 'anzunehmen', ['annehmen', 'angenommen']],
  ['wird', 'Im zweiten Kapitel ___ der Forschungsstand dargestellt.', 'wird', ['ist', 'hat']],
  ['rahmen', 'Im ___ dieser Arbeit wird nur die Situation in Deutschland betrachtet.', 'Rahmen', ['Bild', 'Kreis']],
  ['belegen', 'Die Ergebnisse ___ die Hypothese nur teilweise.', 'bestätigen', ['bestätigt', 'bestätigend']],
]

function wsDrills(): Exercise[] {
  return WS.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `ws-${id}`,
      type: 'multiple_choice' as const,
      topic: 'unpersoenlich',
      concept: 'academic-form',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Academic German is impersonal: passive (wird dargestellt), sich lassen (lässt sich ableiten), es ist + zu-infinitive (es ist anzunehmen). Sources: laut + noun, noun + zufolge. Im Rahmen (+ genitive) = within the scope of.',
        'Akademik Almanca kişisizdir: edilgen (wird dargestellt), sich lassen (lässt sich ableiten), es ist + zu-mastar (es ist anzunehmen). Kaynaklar: laut + isim, isim + zufolge. Im Rahmen (+ Genitiv) = … kapsamında.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-funktion',
    type: 'matching',
    topic: 'zitieren',
    concept: 'functions',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Match the phrase and its function in an academic text.', 'İfadeyi akademik metindeki işleviyle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Die Hypothese lautet, …', right: 'Annahme formulieren' },
      { left: 'Laut Schmidt (2020) …', right: 'Quelle angeben' },
      { left: 'Im Folgenden wird … dargestellt.', right: 'Gliederung ankündigen' },
      { left: 'Daraus lässt sich schließen, …', right: 'Schlussfolgerung ziehen' },
      { left: 'Die Stichprobe umfasste …', right: 'Methode beschreiben' },
    ],
    explanation: l('Academic texts use fixed phrases for each step.', 'Akademik metinler her adım için kalıp ifadeler kullanır.', 'Funktionen.'),
  },
  {
    id: 'sort-stil',
    type: 'categorize',
    topic: 'unpersoenlich',
    concept: 'personal-impersonal',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Personal or academic (impersonal)?', 'Kişisel mi akademik (kişisiz) mi?', 'Persönlich oder wissenschaftlich?'),
    categories: ['persönlich 🙋', 'wissenschaftlich 🎓'],
    items: [
      { text: 'Ich glaube, dass …', category: 0 },
      { text: 'Es ist anzunehmen, dass …', category: 1 },
      { text: 'Wir haben 300 Leute gefragt.', category: 0 },
      { text: 'Es wurden 300 Personen befragt.', category: 1 },
      { text: 'Ich finde das Ergebnis komisch.', category: 0 },
      { text: 'Das Ergebnis lässt sich nur schwer erklären.', category: 1 },
    ],
    explanation: l('Academic style avoids „ich“ and opinions without evidence.', 'Akademik üslup „ich“ kullanmaktan ve kanıtsız görüşlerden kaçınır.', 'unpersönlich.'),
    practice: ['ws-laesst'],
  },
  {
    id: 'mc-hypothese',
    type: 'multiple_choice',
    topic: 'hypothesen',
    concept: 'formulate',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welcher Satz ist eine Hypothese?',
    options: ['Je mehr Zeit Kinder mit Lesen verbringen, desto größer ist ihr Wortschatz.', 'Kinder lesen gern Bücher, finde ich.', 'Die Studie wurde 2022 veröffentlicht.'],
    answer: 0,
    explanation: l('A hypothesis is a testable assumption about a relationship (je … desto).', 'Hipotez, bir ilişki hakkında test edilebilir bir varsayımdır (je … desto).', 'Hypothese.'),
    practice: ['fill-desto'],
  },
  {
    id: 'tf-zitat',
    type: 'true_false',
    topic: 'zitieren',
    concept: 'plagiarism',
    skill: 'reading',
    difficulty: 2,
    statement: 'Auch eine Paraphrase braucht eine Quellenangabe.',
    answer: true,
    explanation: l('Otherwise it counts as plagiarism.', 'Aksi hâlde intihal sayılır.', 'richtig.'),
  },
  {
    id: 'select-unpersoenlich',
    type: 'multiple_select',
    topic: 'unpersoenlich',
    concept: 'structures',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which structures make a text impersonal? Select all.', 'Hangi yapılar bir metni kişisiz yapar? Hepsini seç.', 'Unpersönliche Strukturen?'),
    options: ['Passiv (es wurde untersucht)', 'sich lassen (lässt sich zeigen)', 'ich-Form (ich zeige)', 'es ist + zu-Infinitiv (es ist anzunehmen)', 'Du-Anrede'],
    answers: [0, 1, 3],
    explanation: l('Passive, sich lassen and es ist + zu-infinitive hide the person.', 'Edilgen, sich lassen ve es ist + zu-mastar kişiyi gizler.', 'unpersönlich.'),
  },
  {
    id: 'image-studie',
    type: 'image_choice',
    topic: 'hypothesen',
    concept: 'data',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Abbildung zeigt einen Anstieg.',
    options: [
      { emoji: '📈', label: 'Anstieg' },
      { emoji: '📉', label: 'Rückgang' },
      { emoji: '📊', label: 'Vergleich' },
      { emoji: '🥧', label: 'Anteile' },
    ],
    answer: 0,
    explanation: l('der Anstieg = rise.', 'der Anstieg = artış.', 'Anstieg.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-desto',
    type: 'fill_blank',
    topic: 'hypothesen',
    concept: 'je-desto',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Je höher das Einkommen ist, ___ seltener sind die Befragten krank.',
    accepted: ['desto', 'umso'],
    base: 'je …',
    explanation: l('je + verb at the end, desto / umso + comparative + verb.', 'je + sonda fiil, desto / umso + karşılaştırma + fiil.', 'desto.'),
    examples: ['Je höher das Einkommen ist, **desto** seltener sind …'],
  },
  {
    id: 'fill-wurden',
    type: 'fill_blank',
    topic: 'unpersoenlich',
    concept: 'passive',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Für die Studie ___ 500 Erwachsene befragt.',
    accepted: ['wurden'],
    base: 'werden, Präteritum Passiv',
    explanation: l('Passive past plural: wurden + participle.', 'Edilgen geçmiş çoğul: wurden + ortaç.', 'wurden.'),
    examples: ['Für die Studie **wurden** 500 Erwachsene befragt.'],
  },
  {
    id: 'fill-laut',
    type: 'fill_blank',
    topic: 'zitieren',
    concept: 'source',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: '___ Becker (2019) nimmt die Lesekompetenz seit Jahren ab.',
    accepted: ['Laut', 'Nach'],
    base: 'Quelle angeben',
    explanation: l('laut / nach + author (year).', 'laut / nach + yazar (yıl).', 'Laut.'),
    examples: ['**Laut** Becker (2019) nimmt …'],
  },
  {
    id: 'build-hypothese',
    type: 'sentence_builder',
    topic: 'hypothesen',
    concept: 'formulate',
    skill: 'writing',
    difficulty: 3,
    chips: ['dass Bewegung', 'Die Hypothese lautet,', 'die Konzentration', 'fördert'],
    answers: [['Die Hypothese lautet,', 'dass Bewegung', 'die Konzentration', 'fördert']],
    translation: l('The hypothesis is that exercise promotes concentration.', 'Hipotez, hareketin konsantrasyonu desteklediğidir.', 'Die Hypothese lautet, dass Bewegung die Konzentration fördert.'),
    explanation: l('Die Hypothese lautet, dass … (verb at the end).', 'Die Hypothese lautet, dass … (fiil sonda).', 'Hypothese.'),
    examples: ['**Die Hypothese lautet**, dass Bewegung die Konzentration **fördert**.'],
  },
  {
    id: 'build-feststellen',
    type: 'sentence_builder',
    topic: 'unpersoenlich',
    concept: 'sich-lassen',
    skill: 'writing',
    difficulty: 3,
    chips: ['feststellen', 'Es lässt sich', 'zwischen den Gruppen', 'kein signifikanter Unterschied'],
    answers: [['Es lässt sich', 'kein signifikanter Unterschied', 'zwischen den Gruppen', 'feststellen'], ['Es lässt sich', 'zwischen den Gruppen', 'kein signifikanter Unterschied', 'feststellen']],
    translation: l('No significant difference between the groups can be found.', 'Gruplar arasında anlamlı bir fark tespit edilemiyor.', 'Es lässt sich kein signifikanter Unterschied zwischen den Gruppen feststellen.'),
    explanation: l('sich lassen + infinitive = can be done (impersonal).', 'sich lassen + mastar = yapılabilir (kişisiz).', 'sich lassen.'),
    examples: ['Es **lässt sich** kein signifikanter Unterschied **feststellen**.'],
  },
  {
    id: 'build-zufolge',
    type: 'sentence_builder',
    topic: 'zitieren',
    concept: 'source',
    skill: 'writing',
    difficulty: 3,
    chips: ['nutzen', 'Einer Umfrage zufolge', 'täglich soziale Medien', '90 Prozent der Jugendlichen'],
    answers: [['Einer Umfrage zufolge', 'nutzen', '90 Prozent der Jugendlichen', 'täglich soziale Medien']],
    translation: l('According to a survey, 90 percent of young people use social media daily.', 'Bir ankete göre gençlerin yüzde 90’ı her gün sosyal medya kullanıyor.', 'Einer Umfrage zufolge nutzen 90 Prozent der Jugendlichen täglich soziale Medien.'),
    explanation: l('zufolge comes after the noun (dative).', 'zufolge isimden sonra gelir (Dativ).', 'zufolge.'),
    examples: ['**Einer Umfrage zufolge** nutzen …'],
  },
  {
    id: 'fix-ich',
    type: 'error_correction',
    topic: 'unpersoenlich',
    concept: 'passive',
    skill: 'writing',
    difficulty: 3,
    sentence: 'Ich habe in dieser Arbeit drei Schulen untersucht.',
    accepted: ['In dieser Arbeit wurden drei Schulen untersucht.', 'In dieser Arbeit werden drei Schulen untersucht.', 'Drei Schulen wurden in dieser Arbeit untersucht.'],
    explanation: l('Avoid „ich“ – use the passive.', '„ich“ kullanmaktan kaçın – edilgen kullan.', 'Passiv.'),
    examples: ['In dieser Arbeit **wurden** drei Schulen **untersucht**.'],
  },
  {
    id: 'fix-zufolge',
    type: 'error_correction',
    topic: 'zitieren',
    concept: 'source',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Zufolge der Studie schlafen Studierende zu wenig.',
    accepted: ['Der Studie zufolge schlafen Studierende zu wenig.', 'Laut der Studie schlafen Studierende zu wenig.', 'Laut Studie schlafen Studierende zu wenig.'],
    explanation: l('zufolge is placed after the noun.', 'zufolge isimden sonra gelir.', 'nachgestellt.'),
    examples: ['**Der Studie zufolge** schlafen …'],
  },
  {
    id: 'fix-anzunehmen',
    type: 'error_correction',
    topic: 'hypothesen',
    concept: 'assumption',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Es ist annehmen, dass die Zahlen weiter steigen.',
    accepted: ['Es ist anzunehmen, dass die Zahlen weiter steigen.'],
    explanation: l('es ist + zu-infinitive: anzunehmen.', 'es ist + zu-mastar: anzunehmen.', 'anzunehmen.'),
    examples: ['Es ist **anzunehmen**, dass …'],
  },
  {
    id: 'tr-untersucht',
    type: 'translation',
    topic: 'unpersoenlich',
    concept: 'passive',
    skill: 'writing',
    difficulty: 3,
    source: l('This study examines the influence of music on learning.', 'Bu çalışma müziğin öğrenme üzerindeki etkisini inceliyor.', 'This study examines the influence of music on learning.'),
    accepted: ['Diese Studie untersucht den Einfluss von Musik auf das Lernen.', 'In dieser Studie wird der Einfluss von Musik auf das Lernen untersucht.', 'Diese Arbeit untersucht den Einfluss von Musik auf das Lernen.'],
    explanation: l('der Einfluss von … auf + accusative.', 'der Einfluss von … auf + Akkusativ.', 'Einfluss auf.'),
    examples: ['Diese Studie untersucht den **Einfluss** von Musik **auf das** Lernen.'],
  },
  {
    id: 'tr-belegen',
    type: 'translation',
    topic: 'hypothesen',
    concept: 'evidence',
    skill: 'writing',
    difficulty: 3,
    source: l('The data prove a clear connection.', 'Veriler açık bir bağlantıyı kanıtlıyor.', 'The data prove a clear connection.'),
    accepted: ['Die Daten belegen einen klaren Zusammenhang.', 'Die Daten belegen einen eindeutigen Zusammenhang.', 'Die Daten zeigen einen klaren Zusammenhang.'],
    explanation: l('belegen = to prove with evidence.', 'belegen = kanıtla göstermek.', 'belegen.'),
    examples: ['Die Daten **belegen** einen klaren Zusammenhang.'],
  },
  {
    id: 'ordering-aufbau',
    type: 'ordering',
    topic: 'hypothesen',
    concept: 'structure',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Order the parts of an abstract.', 'Bir özetin bölümlerini sırala.', 'Ordne das Abstract.'),
    items: ['Die Ergebnisse zeigen, dass Bewegungspausen die Konzentration signifikant verbessern.', 'Die vorliegende Studie untersucht den Einfluss von Bewegungspausen auf die Konzentration.', 'Daraus lässt sich schließen, dass Schulen mehr Bewegung einplanen sollten.', 'Dazu wurden 240 Schülerinnen und Schüler über acht Wochen beobachtet.'],
    answer: ['Die vorliegende Studie untersucht den Einfluss von Bewegungspausen auf die Konzentration.', 'Dazu wurden 240 Schülerinnen und Schüler über acht Wochen beobachtet.', 'Die Ergebnisse zeigen, dass Bewegungspausen die Konzentration signifikant verbessern.', 'Daraus lässt sich schließen, dass Schulen mehr Bewegung einplanen sollten.'],
    explanation: l('Aim → method → results → conclusion.', 'Amaç → yöntem → sonuçlar → çıkarım.', 'Aufbau.'),
  },
  {
    id: 'dialog-betreuer',
    type: 'dialogue',
    topic: 'unpersoenlich',
    concept: 'feedback',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Betreuerin', de: 'In Ihrer Hausarbeit steht oft „Ich finde“. Wie könnten Sie das ändern?' }],
    options: ['Ich könnte unpersönliche Formulierungen wie „Es ist anzunehmen, dass …“ verwenden.', 'Ich finde, ich finde das gut.', 'Ich könnte mehr „Ich finde“ schreiben.'],
    answer: 0,
    explanation: l('Replace personal opinions with impersonal phrasing.', 'Kişisel görüşleri kişisiz ifadelerle değiştir.', 'unpersönlich.'),
  },
  {
    id: 'dialog-quelle',
    type: 'dialogue',
    topic: 'zitieren',
    concept: 'source',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Kommilitone', de: 'Kann ich den Satz aus dem Buch einfach umformulieren und ohne Quelle übernehmen?' }],
    options: ['Nein, auch eine Paraphrase musst du mit einer Quellenangabe belegen.', 'Ja, umformuliert ist es dein eigener Gedanke.', 'Nur wenn das Buch alt ist.'],
    answer: 0,
    explanation: l('Paraphrases need a source too.', 'Başka sözcüklerle anlatım da kaynak ister.', 'Quelle.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-abstract',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was wird in der Studie untersucht?',
    options: ['der Zusammenhang zwischen Smartphone-Nutzung und Schlaf', 'die Geschichte des Smartphones', 'die Preise von Smartphones'],
    answer: 0,
    explanation: l('„… untersucht den Zusammenhang zwischen abendlicher Smartphone-Nutzung und Schlafqualität.“', '„… untersucht den Zusammenhang zwischen abendlicher Smartphone-Nutzung und Schlafqualität.“', 'Schlaf.'),
  },
  {
    id: 'read-stichprobe',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-abstract',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wie groß war die Stichprobe?',
    options: ['412 Studierende', '41 Studierende', '4.120 Studierende'],
    answer: 0,
    explanation: l('„Befragt wurden 412 Studierende …“', '„Befragt wurden 412 Studierende …“', '412.'),
  },
  {
    id: 'read-hypothese',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-abstract',
    skill: 'reading',
    difficulty: 3,
    statement: 'Die Hypothese wurde durch die Ergebnisse bestätigt.',
    answer: true,
    explanation: l('„Die Hypothese konnte bestätigt werden.“', '„Die Hypothese konnte bestätigt werden.“', 'richtig.'),
  },
  {
    id: 'read-einschraenkung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-abstract',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welche Einschränkung nennen die Autoren?',
    options: ['Es wurden nur Studierende befragt.', 'Die Studie war zu teuer.', 'Es gab zu viele Teilnehmende.'],
    answer: 0,
    explanation: l('„Einschränkend ist anzumerken, dass ausschließlich Studierende befragt wurden.“', '„Einschränkend ist anzumerken, dass ausschließlich Studierende befragt wurden.“', 'Einschränkung.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-vortrag',
    type: 'listening_choice',
    topic: 'hypothesen',
    concept: 'structure',
    skill: 'listening',
    difficulty: 3,
    audio: 'Im ersten Teil meines Vortrags stelle ich die Methode vor, im zweiten Teil die Ergebnisse.',
    question: l('What comes in the second part of the talk?', 'Konuşmanın ikinci bölümünde ne var?', 'Was kommt im zweiten Teil?'),
    options: ['the results', 'the method', 'the questions'],
    answer: 0,
    explanation: l('im zweiten Teil die Ergebnisse.', 'im zweiten Teil die Ergebnisse.', 'Ergebnisse.'),
  },
  {
    id: 'listen-signifikant',
    type: 'listening_choice',
    topic: 'hypothesen',
    concept: 'results',
    skill: 'listening',
    difficulty: 3,
    audio: 'Zwischen Männern und Frauen ließ sich kein signifikanter Unterschied feststellen.',
    question: l('What was the result?', 'Sonuç neydi?', 'Ergebnis?'),
    options: ['no significant difference between men and women', 'women scored much higher', 'men scored much higher'],
    answer: 0,
    explanation: l('kein signifikanter Unterschied = no significant difference.', 'kein signifikanter Unterschied = anlamlı fark yok.', 'kein Unterschied.'),
  },
  {
    id: 'listen-zitat',
    type: 'listening_choice',
    topic: 'zitieren',
    concept: 'source',
    skill: 'listening',
    difficulty: 3,
    audio: 'Wie Professorin Lang bereits 2018 gezeigt hat, verbessert regelmäßiges Lesen das Textverständnis.',
    question: l('Who showed that reading improves comprehension?', 'Okumanın anlamayı geliştirdiğini kim gösterdi?', 'Wer hat das gezeigt?'),
    options: ['Professor Lang', 'the speaker', 'nobody yet'],
    answer: 0,
    explanation: l('The speaker cites a source: Professorin Lang (2018).', 'Konuşan bir kaynak aktarıyor: Professorin Lang (2018).', 'Lang.'),
  },
  {
    id: 'listen-anzunehmen',
    type: 'listening_choice',
    topic: 'unpersoenlich',
    concept: 'assumption',
    skill: 'listening',
    difficulty: 3,
    audio: 'Es ist anzunehmen, dass sich der Trend in den nächsten Jahren fortsetzt. Belegt ist das allerdings noch nicht.',
    question: l('How certain is the statement?', 'İfade ne kadar kesin?', 'Wie sicher ist die Aussage?'),
    options: ['It’s an assumption, not yet proven.', 'It is proven.', 'It is clearly false.'],
    answer: 0,
    explanation: l('anzunehmen + noch nicht belegt = assumption.', 'anzunehmen + noch nicht belegt = varsayım.', 'Annahme.'),
  },

  ...wsDrills(),
]

export const UNIT_C1_12_WISSENSCHAFTSSPRACHE: CourseUnit = {
  level: 'C1',
  number: 12,
  slug: 'wissenschaftssprache',
  titleDe: 'Wissenschaftlich schreiben',
  title: l('Academic writing', 'Akademik yazım', 'Wissenschaftlich schreiben'),
  goal: l(
    'By the end of this unit you can formulate hypotheses (Die Hypothese lautet, dass …; je … desto), cite and paraphrase sources (laut, zufolge) and write in an impersonal academic style (passive, sich lassen, es ist anzunehmen).',
    'Bu ünitenin sonunda hipotez kurabilir (Die Hypothese lautet, dass …; je … desto), kaynakları aktarabilir ve başka sözcüklerle anlatabilir (laut, zufolge) ve kişisiz akademik üslupla yazabilirsin (edilgen, sich lassen, es ist anzunehmen).',
    'Am Ende dieser Einheit schreibst du im wissenschaftlichen Stil.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'hypothesen', label: l('Hypotheses and results', 'Hipotezler ve sonuçlar', 'Hypothesen und Ergebnisse') },
    { key: 'zitieren', label: l('Citing and paraphrasing', 'Alıntılama ve başka sözcüklerle anlatma', 'Zitieren und paraphrasieren') },
    { key: 'unpersoenlich', label: l('Impersonal style', 'Kişisiz üslup', 'Unpersönlicher Stil') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The language of seminar papers and studies.', 'Ödevlerin ve araştırmaların dili.', 'Sprache der Wissenschaft.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Impersonal style', 'Kişisiz üslup', 'Unpersönlicher Stil'),
          body: l(
            'Academic German avoids „ich“ and personal opinions. Instead: passive (Es wurden 300 Personen befragt), sich lassen + infinitive (Es lässt sich zeigen, dass …), es ist + zu-infinitive (Es ist anzunehmen, dass …), and man.',
            'Akademik Almanca „ich“ ve kişisel görüşlerden kaçınır. Bunun yerine: edilgen (Es wurden 300 Personen befragt), sich lassen + mastar (Es lässt sich zeigen, dass …), es ist + zu-mastar (Es ist anzunehmen, dass …) ve man.',
            'unpersönlich.'
          ),
          table: {
            head: [l('Personal', 'Kişisel', 'persönlich'), l('Academic', 'Akademik', 'wissenschaftlich')],
            rows: [
              ['Ich habe 300 Leute gefragt.', 'Es wurden 300 Personen befragt.'],
              ['Ich glaube, dass …', 'Es ist anzunehmen, dass …'],
              ['Man kann sehen, dass …', 'Es lässt sich feststellen, dass …'],
              ['Ich zeige im 2. Kapitel …', 'Im 2. Kapitel wird … dargestellt.'],
            ],
          },
        },
        {
          title: l('Hypotheses', 'Hipotezler', 'Hypothesen'),
          body: l(
            'A hypothesis is a testable assumption, often about a relationship: Die Hypothese lautet, dass … / Je mehr …, desto … / Es wird angenommen, dass … Results then confirm (bestätigen) or refute (widerlegen) it.',
            'Hipotez, genellikle bir ilişki hakkında test edilebilir bir varsayımdır: Die Hypothese lautet, dass … / Je mehr …, desto … / Es wird angenommen, dass … Sonuçlar onu doğrular (bestätigen) ya da çürütür (widerlegen).',
            'Hypothesen.'
          ),
          examples: [
            { de: '**Je** mehr Kinder lesen, **desto** größer ist ihr Wortschatz.', translation: l('The more children read, the larger their vocabulary.', 'Çocuklar ne kadar çok okursa kelime hazineleri o kadar büyür.', '') },
            { de: 'Die Hypothese **konnte bestätigt werden**.', translation: l('The hypothesis could be confirmed.', 'Hipotez doğrulanabildi.', '') },
          ],
        },
        {
          title: l('Citing and paraphrasing', 'Alıntı ve başka sözcüklerle anlatım', 'Zitieren und paraphrasieren'),
          body: l(
            'Name the source for quotations and paraphrases: laut Müller (2021) …, der Studie zufolge … (zufolge after the noun), wie Becker (2019) zeigt, … In paraphrases, reported speech in Konjunktiv I creates distance: Müller betont, die Zahl sei gestiegen.',
            'Alıntılar ve başka sözcüklerle anlatımlar için kaynağı belirt: laut Müller (2021) …, der Studie zufolge … (zufolge isimden sonra), wie Becker (2019) zeigt, … Başka sözcüklerle anlatımda Konjunktiv I ile dolaylı anlatım mesafe yaratır: Müller betont, die Zahl sei gestiegen.',
            'Quellen.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A student discusses her seminar paper with her supervisor.', 'Bir öğrenci seminer ödevini danışmanıyla konuşuyor.', 'In der Sprechstunde.'),
      dialogue: [
        { speaker: 'Professor', de: 'Worum geht es in Ihrer Arbeit, Frau Arslan?', translation: l('What is your paper about, Ms Arslan?', 'Çalışmanız ne hakkında, Bayan Arslan?', '') },
        { speaker: 'Elif', de: 'Ich **untersuche** den Zusammenhang zwischen Schlaf und Lernerfolg. **Die Hypothese lautet**, dass mehr Schlaf bessere Noten bewirkt.', translation: l('I’m examining the connection between sleep and learning success. The hypothesis is that more sleep leads to better grades.', 'Uyku ile öğrenme başarısı arasındaki bağlantıyı inceliyorum. Hipotez, daha fazla uykunun daha iyi notlara yol açtığıdır.', '') },
        { speaker: 'Professor', de: 'Gut. Und wie gehen Sie methodisch vor?', translation: l('Good. And what is your method?', 'İyi. Peki yöntem olarak nasıl ilerliyorsunuz?', '') },
        { speaker: 'Elif', de: 'Es **wurden** 150 Studierende **befragt**. Die **Stichprobe** ist allerdings recht klein.', translation: l('150 students were surveyed. The sample is rather small, though.', '150 öğrenciyle anket yapıldı. Örneklem ise oldukça küçük.', '') },
        { speaker: 'Professor', de: 'Das sollten Sie als Einschränkung nennen. Und im Text bitte kein „ich finde“ – schreiben Sie lieber „**es ist anzunehmen**“.', translation: l('You should mention that as a limitation. And no „I think“ in the text, please – rather write „it can be assumed“.', 'Bunu bir sınırlılık olarak belirtmelisiniz. Metinde de lütfen „bence“ yok – „varsayılabilir“ yazın.', '') },
        { speaker: 'Elif', de: 'Verstanden. Und **laut** Walker (2017) gibt es dazu schon erste Belege.', translation: l('Understood. And according to Walker (2017) there is already some initial evidence.', 'Anladım. Walker’a (2017) göre bu konuda ilk kanıtlar zaten var.', '') },
      ],
      examples: [
        { de: '**Es wurden** 500 Personen **befragt**.', translation: l('500 people were surveyed.', '500 kişiyle anket yapıldı.', '') },
        { de: '**Es lässt sich feststellen**, dass …', translation: l('It can be observed that …', 'Şu tespit edilebilir: …', '') },
        { de: '**Der Studie zufolge** …', translation: l('According to the study …', 'Araştırmaya göre …', '') },
        { de: '**Laut** Müller (2021) …', translation: l('According to Müller (2021) …', 'Müller’e (2021) göre …', '') },
        { de: '**Im Rahmen** dieser Arbeit …', translation: l('Within the scope of this paper …', 'Bu çalışma kapsamında …', '') },
        { de: 'Daraus **lässt sich schließen**, dass …', translation: l('From this one can conclude that …', 'Buradan şu sonuç çıkarılabilir: …', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Spot academic style.', 'Akademik üslubu fark et.', 'Wissenschaftlichen Stil erkennen.'),
      exercises: ['match-funktion', 'sort-stil', 'ws-zufolge', 'ws-laesst', 'ws-anzunehmen', 'mc-hypothese', 'tf-zitat', 'select-unpersoenlich', 'image-studie'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Write like a researcher.', 'Bir araştırmacı gibi yaz.', 'Wissenschaftlich formulieren.'),
      exercises: [
        'fill-desto',
        'fill-wurden',
        'fill-laut',
        'build-hypothese',
        'build-feststellen',
        'build-zufolge',
        'fix-ich',
        'fix-zufolge',
        'fix-anzunehmen',
        'tr-untersucht',
        'tr-belegen',
        'ordering-aufbau',
        'dialog-betreuer',
        'dialog-quelle',
        'ws-wird',
        'ws-rahmen',
        'ws-belegen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('The abstract of a study.', 'Bir araştırmanın özeti.', 'Ein Abstract.'),
      passage: [
        '**Abstract** – Die vorliegende Studie **untersucht** den Zusammenhang zwischen abendlicher Smartphone-Nutzung und Schlafqualität.',
        '**Die Hypothese lautet**, dass die Schlafqualität umso schlechter ist, je länger das Smartphone vor dem Einschlafen genutzt wird.',
        'Befragt wurden 412 Studierende. Es **lässt sich** ein **signifikanter** Zusammenhang **feststellen**: Die Hypothese konnte bestätigt werden.',
        'Einschränkend ist anzumerken, dass ausschließlich Studierende befragt wurden. **Es ist anzunehmen**, dass die Ergebnisse auf andere Altersgruppen nur bedingt übertragbar sind.',
      ],
      glossary: [
        { de: 'vorliegend', note: l('present (this)', 'mevcut, elimizdeki', 'diese') },
        { de: 'einschränkend', note: l('as a limitation', 'sınırlayıcı olarak', 'als Einschränkung') },
        { de: 'ausschließlich', note: l('exclusively', 'yalnızca', 'nur') },
        { de: 'bedingt', note: l('to a limited extent', 'sınırlı ölçüde', 'nur teilweise') },
      ],
      exercises: ['read-thema', 'read-stichprobe', 'read-hypothese', 'read-einschraenkung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Excerpts from academic talks.', 'Akademik konuşmalardan kesitler.', 'Aus Vorträgen.'),
      exercises: ['listen-vortrag', 'listen-signifikant', 'listen-zitat', 'listen-anzunehmen'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present a (fictional) research project in a seminar: topic, hypothesis, method, expected result.', 'Bir seminerde (kurgusal) bir araştırma projesi sun: konu, hipotez, yöntem, beklenen sonuç.', 'Forschungsprojekt vorstellen.'),
      points: [
        l('Topic: „In meinem Projekt wird … untersucht.“', 'Konu: „In meinem Projekt wird … untersucht.“', 'Thema'),
        l('Hypothesis: „Die Hypothese lautet, dass …“', 'Hipotez: „Die Hypothese lautet, dass …“', 'Hypothese'),
        l('Method: „Es werden … befragt.“', 'Yöntem: „Es werden … befragt.“', 'Methode'),
        l('Expectation: „Es ist anzunehmen, dass …“', 'Beklenti: „Es ist anzunehmen, dass …“', 'Erwartung'),
      ],
      model: [
        'In meinem Projekt wird der Einfluss von Musik auf die Konzentration untersucht.',
        'Die Hypothese lautet, dass ruhige Musik die Konzentration fördert.',
        'Dazu werden 100 Studierende in zwei Gruppen getestet.',
        'Es ist anzunehmen, dass die Gruppe mit Musik bessere Ergebnisse erzielt.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short abstract (at least 6 sentences) for a study on „Social Media und Wohlbefinden“. Use impersonal style, a hypothesis and a source.',
        '„Social Media und Wohlbefinden“ konulu bir araştırma için kısa bir özet yaz (en az 6 cümle). Kişisiz üslup, bir hipotez ve bir kaynak kullan.',
        'Abstract (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('A hypothesis (Hypothese, je … desto, angenommen)', 'Bir hipotez (Hypothese, je … desto, angenommen)', 'Hypothese'), pattern: '(Hypothese|\\b[Jj]e\\b[^.]*\\b(desto|umso)\\b|angenommen)' },
        { label: l('Impersonal style (passive or sich lassen)', 'Kişisiz üslup (edilgen ya da sich lassen)', 'unpersönlich'), pattern: '\\b(wurde|wurden|wird|werden|lässt sich|lassen sich)\\b' },
        { label: l('A source (laut, zufolge, nach … (Jahr))', 'Bir kaynak (laut, zufolge, nach … (yıl))', 'Quelle'), pattern: '([Ll]aut|zufolge|\\(\\d{4}\\))' },
      ],
      model: [
        'Die vorliegende Studie untersucht den Zusammenhang zwischen Social-Media-Nutzung und Wohlbefinden.',
        'Laut Weber (2020) fühlen sich viele Jugendliche nach langer Nutzung erschöpft.',
        'Die Hypothese lautet, dass das Wohlbefinden umso geringer ist, je länger soziale Medien genutzt werden.',
        'Dazu wurden 350 Personen zwischen 16 und 25 Jahren befragt.',
        'Es lässt sich ein signifikanter Zusammenhang feststellen.',
        'Es ist jedoch anzunehmen, dass weitere Faktoren eine Rolle spielen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Academic forms – 60 seconds.', 'Akademik yapılar – 60 saniye.', 'Wissenschaftssprache – 60 Sekunden.'),
      seconds: 60,
      pool: [...WS.map(([id]) => `ws-${id}`), 'mc-hypothese'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Impersonal: passive, sich lassen, es ist + zu-infinitive', 'Kişisiz: edilgen, sich lassen, es ist + zu-mastar', 'unpersönlich'),
      l('Hypotheses: Die Hypothese lautet, dass …; je … desto', 'Hipotezler: Die Hypothese lautet, dass …; je … desto', 'Hypothesen'),
      l('Sources: laut …, … zufolge, wie … zeigt', 'Kaynaklar: laut …, … zufolge, wie … zeigt', 'Quellen'),
      l('Paraphrases also need a source', 'Başka sözcüklerle anlatım da kaynak ister', 'Paraphrase'),
    ],
    mistakes: [
      { wrong: 'Zufolge der Studie …', right: 'Der Studie zufolge …', note: l('zufolge after the noun.', 'zufolge isimden sonra.', 'nachgestellt.') },
      { wrong: 'Es ist annehmen, dass …', right: 'Es ist anzunehmen, dass …', note: l('es ist + zu-infinitive.', 'es ist + zu-mastar.', 'zu.') },
      { wrong: 'Ich habe 300 Leute gefragt.', right: 'Es wurden 300 Personen befragt.', note: l('Impersonal passive.', 'Kişisiz edilgen.', 'Passiv.') },
      { wrong: 'Je mehr man liest, desto man versteht mehr.', right: 'Je mehr man liest, desto mehr versteht man.', note: l('desto + comparative + verb.', 'desto + karşılaştırma + fiil.', 'desto.') },
    ],
  },
}
