import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'der Zielkonflikt', emoji: '🎯', translation: l('conflict of goals, trade-off', 'hedef çatışması', 'zwei Ziele widersprechen sich'), example: 'Zwischen Klimaschutz und Wirtschaftswachstum besteht ein Zielkonflikt.' },
  { word: 'die CO₂-Steuer', emoji: '💨', translation: l('carbon tax', 'karbon vergisi', 'Abgabe auf CO₂'), example: 'Die CO₂-Steuer soll klimaschädliches Verhalten teurer machen.' },
  { word: 'die Energiewende', emoji: '☀️', translation: l('energy transition', 'enerji dönüşümü', 'Umstieg auf erneuerbare Energien'), example: 'Die Energiewende kommt langsamer voran als geplant.' },
  { word: 'klimaneutral', emoji: '🌍', translation: l('climate-neutral', 'iklim nötr', 'ohne Netto-Emissionen'), example: 'Deutschland will bis 2045 klimaneutral werden.' },
  { word: 'die Maßnahme', emoji: '🛠️', translation: l('measure', 'önlem', 'Schritt, Instrument'), example: 'Die Maßnahme greift zu kurz.' },
  { word: 'zu kurz greifen', emoji: '📏', translation: l('to fall short', 'yetersiz kalmak', 'nicht ausreichen'), example: 'Kritiker meinen, das Gesetz greife zu kurz.' },
  { word: 'sozial verträglich', emoji: '🤝', translation: l('socially acceptable', 'sosyal açıdan katlanılabilir', 'fair für alle'), example: 'Klimaschutz muss sozial verträglich gestaltet werden.' },
  { word: 'die Emissionen senken', emoji: '📉', translation: l('to reduce emissions', 'emisyonları azaltmak', 'weniger ausstoßen'), example: 'Der Verkehrssektor muss seine Emissionen deutlich senken.' },
  { word: 'die Folge / die Ursache', emoji: '🔁', translation: l('consequence / cause', 'sonuç / neden', 'Wirkung und Grund'), example: 'Hitzewellen sind eine Folge des Klimawandels.' },
  { word: 'sich auswirken auf (+ Akk.)', emoji: '➡️', translation: l('to affect', '… üzerinde etki etmek', 'Einfluss haben'), example: 'Höhere Preise wirken sich vor allem auf Geringverdiener aus.' },
  { word: 'der Anspruch / die Wirklichkeit', emoji: '🪞', translation: l('aspiration / reality', 'hedef / gerçek', 'Ziel und Realität'), example: 'Zwischen Anspruch und Wirklichkeit klafft eine Lücke.' },
  { word: 'das Klimageld', emoji: '💶', translation: l('climate dividend', 'iklim parası (geri ödeme)', 'Rückzahlung an Bürger'), example: 'Ein Klimageld könnte die Belastung ausgleichen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Ausstoß', gender: 'm', translation: l('output, emission', 'salım', 'Ausstoß') },
  { word: 'Treibhausgas', gender: 'n', plural: 'die Treibhausgase', translation: l('greenhouse gas', 'sera gazı', 'Treibhausgas') },
  { word: 'Erderwärmung', gender: 'f', translation: l('global warming', 'küresel ısınma', 'Erderwärmung') },
  { word: 'Belastung', gender: 'f', plural: 'die Belastungen', translation: l('burden', 'yük', 'Belastung') },
  { word: 'Verbot', gender: 'n', plural: 'die Verbote', translation: l('ban', 'yasak', 'Verbot') },
  { word: 'Anreiz', gender: 'm', plural: 'die Anreize', translation: l('incentive', 'teşvik', 'Anreiz') },
  { word: 'Wärmepumpe', gender: 'f', plural: 'die Wärmepumpen', translation: l('heat pump', 'ısı pompası', 'Wärmepumpe') },
  { word: 'Abkommen', gender: 'n', plural: 'die Abkommen', translation: l('agreement', 'anlaşma', 'Abkommen') },
]

/** [id, sentence with gap, right, wrong] */
const KP: [string, string, string, [string, string]][] = [
  ['dadurch', 'Die CO₂-Steuer verteuert Benzin. ___ fahren viele Menschen weniger Auto.', 'Dadurch', ['Dafür', 'Damit dass']],
  ['infolge', '___ der Dürre sind die Ernten stark zurückgegangen.', 'Infolge', ['Wegen dass', 'Weil']],
  ['fuehrt', 'Die steigende Temperatur ___ zu häufigeren Extremwetterereignissen.', 'führt', ['bringt', 'macht']],
  ['auswirken', 'Höhere Energiepreise wirken sich besonders stark ___ Familien mit geringem Einkommen aus.', 'auf', ['an', 'für']],
  ['greift', 'Das Klimapaket ___ nach Ansicht vieler Experten zu kurz.', 'greift', ['fasst', 'nimmt']],
  ['zielkonflikt', 'Zwischen günstiger Energie und Klimaschutz besteht ein ___.', 'Zielkonflikt', ['Zielpunkt', 'Zielort']],
]

function kpDrills(): Exercise[] {
  return KP.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `kp-${id}`,
      type: 'multiple_choice' as const,
      topic: 'zusammenhaenge',
      concept: 'cause-effect',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Explaining complex connections: dadurch (as a result), infolge + genitive (as a consequence of), führen zu + dative (to lead to), sich auswirken auf + accusative (to affect), zu kurz greifen (to fall short), der Zielkonflikt (trade-off).',
        'Karmaşık bağlantıları açıklamak: dadurch (bu sayede / bunun sonucunda), infolge + Genitiv (… sonucunda), führen zu + Dativ (… -e yol açmak), sich auswirken auf + Akkusativ (… -i etkilemek), zu kurz greifen (yetersiz kalmak), der Zielkonflikt (hedef çatışması).',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-instrumente',
    type: 'matching',
    topic: 'massnahmen',
    concept: 'instruments',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the climate measure and its mechanism.', 'İklim önlemini mekanizmasıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'CO₂-Steuer', right: 'macht Emissionen teurer' },
      { left: 'Verbot von Ölheizungen', right: 'schreibt etwas vor' },
      { left: 'Förderung von Wärmepumpen', right: 'schafft einen finanziellen Anreiz' },
      { left: 'Klimageld', right: 'gibt Einnahmen an Bürger zurück' },
      { left: 'Tempolimit', right: 'senkt den Verbrauch im Verkehr' },
    ],
    explanation: l('Price, ban, incentive, refund – four types of instruments.', 'Fiyat, yasak, teşvik, geri ödeme – dört tür araç.', 'Instrumente.'),
  },
  {
    id: 'sort-ursache',
    type: 'categorize',
    topic: 'zusammenhaenge',
    concept: 'cause-effect',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Cause or consequence of climate change?', 'İklim değişikliğinin nedeni mi sonucu mu?', 'Ursache oder Folge?'),
    categories: ['Ursache 🏭', 'Folge 🌡️'],
    items: [
      { text: 'Verbrennung von Kohle', category: 0 },
      { text: 'Hitzewellen', category: 1 },
      { text: 'Abholzung der Regenwälder', category: 0 },
      { text: 'steigender Meeresspiegel', category: 1 },
      { text: 'Massentierhaltung', category: 0 },
      { text: 'Ernteausfälle', category: 1 },
    ],
    explanation: l('Separating causes and consequences structures your explanation.', 'Nedenleri ve sonuçları ayırmak açıklamanı düzenler.', 'Ursache und Folge.'),
    practice: ['kp-infolge'],
  },
  {
    id: 'mc-zielkonflikt',
    type: 'multiple_choice',
    topic: 'zielkonflikte',
    concept: 'trade-off',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welcher Satz beschreibt einen Zielkonflikt?',
    options: ['Windräder liefern saubere Energie, gefährden aber Vögel und stören Anwohner.', 'Windräder liefern saubere Energie.', 'Viele Menschen mögen Windräder nicht.'],
    answer: 0,
    explanation: l('Two legitimate goals contradict each other: clean energy vs. nature/residents.', 'İki meşru hedef çelişiyor: temiz enerji ve doğa/sakinler.', 'Zielkonflikt.'),
    practice: ['fill-zwar'],
  },
  {
    id: 'tf-neutral',
    type: 'true_false',
    topic: 'massnahmen',
    concept: 'terms',
    skill: 'vocabulary',
    difficulty: 2,
    statement: '„Klimaneutral“ bedeutet, dass überhaupt keine Treibhausgase mehr ausgestoßen werden.',
    answer: false,
    explanation: l('It means net zero: remaining emissions are compensated.', 'Net sıfır demektir: kalan emisyonlar dengelenir.', 'netto null.'),
  },
  {
    id: 'select-sozial',
    type: 'multiple_select',
    topic: 'zielkonflikte',
    concept: 'social',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Which measures make climate protection more socially acceptable? Select all.', 'Hangi önlemler iklim korumasını sosyal açıdan daha katlanılabilir yapar? Hepsini seç.', 'Sozial verträglich?'),
    options: ['ein Klimageld für alle Bürger', 'günstigere Bus- und Bahntickets', 'höhere Steuern nur für Geringverdiener', 'Zuschüsse für Wärmepumpen bei kleinem Einkommen', 'Strompreise verdoppeln'],
    answers: [0, 1, 3],
    explanation: l('Refunds and targeted support reduce the burden on low incomes.', 'Geri ödemeler ve hedefli destek düşük gelirlilerin yükünü azaltır.', 'sozial.'),
  },
  {
    id: 'image-energie',
    type: 'image_choice',
    topic: 'massnahmen',
    concept: 'energy',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'erneuerbare Energie',
    options: [
      { emoji: '☀️', label: 'Solarenergie' },
      { emoji: '🛢️', label: 'Erdöl' },
      { emoji: '🏭', label: 'Kohlekraftwerk' },
      { emoji: '⛽', label: 'Benzin' },
    ],
    answer: 0,
    explanation: l('Solar energy is renewable.', 'Güneş enerjisi yenilenebilir.', 'erneuerbar.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-zwar',
    type: 'fill_blank',
    topic: 'zielkonflikte',
    concept: 'trade-off',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ein Tempolimit würde ___ Emissionen senken, aber viele Autofahrer lehnen es ab.',
    accepted: ['zwar'],
    base: '… aber',
    explanation: l('zwar … aber names both sides of a trade-off.', 'zwar … aber bir hedef çatışmasının iki yanını belirtir.', 'zwar.'),
    examples: ['Ein Tempolimit würde **zwar** Emissionen senken, **aber** …'],
  },
  {
    id: 'fill-fuehrt',
    type: 'fill_blank',
    topic: 'zusammenhaenge',
    concept: 'cause-effect',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Abholzung des Regenwaldes führt ___ einem Verlust der Artenvielfalt.',
    accepted: ['zu'],
    base: 'führen …',
    explanation: l('führen zu + dative (zu einem).', 'führen zu + Dativ (zu einem).', 'zu.'),
    examples: ['… führt **zu** einem Verlust …'],
  },
  {
    id: 'fill-vertraeglich',
    type: 'fill_blank',
    topic: 'zielkonflikte',
    concept: 'social',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Klimaschutz muss sozial ___ gestaltet werden, damit er akzeptiert wird.',
    accepted: ['verträglich', 'vertraeglich', 'gerecht'],
    base: 'fair für alle',
    explanation: l('sozial verträglich = socially acceptable.', 'sozial verträglich = sosyal açıdan katlanılabilir.', 'verträglich.'),
    examples: ['… sozial **verträglich** gestaltet …'],
  },
  {
    id: 'build-anspruch',
    type: 'sentence_builder',
    topic: 'massnahmen',
    concept: 'evaluate',
    skill: 'writing',
    difficulty: 3,
    chips: ['klafft', 'Zwischen Anspruch und Wirklichkeit', 'eine große Lücke', 'in der Klimapolitik'],
    answers: [['Zwischen Anspruch und Wirklichkeit', 'klafft', 'in der Klimapolitik', 'eine große Lücke'], ['Zwischen Anspruch und Wirklichkeit', 'klafft', 'eine große Lücke', 'in der Klimapolitik']],
    translation: l('In climate policy there is a big gap between aspiration and reality.', 'İklim politikasında hedef ile gerçek arasında büyük bir boşluk var.', 'Zwischen Anspruch und Wirklichkeit klafft in der Klimapolitik eine große Lücke.'),
    explanation: l('eine Lücke klafft = there is a gap.', 'eine Lücke klafft = bir boşluk var.', 'klaffen.'),
    examples: ['Zwischen Anspruch und Wirklichkeit **klafft** eine große Lücke.'],
  },
  {
    id: 'build-auswirken',
    type: 'sentence_builder',
    topic: 'zusammenhaenge',
    concept: 'effect',
    skill: 'writing',
    difficulty: 3,
    chips: ['auf ärmere Haushalte', 'Die höheren Preise', 'aus', 'wirken sich vor allem'],
    answers: [['Die höheren Preise', 'wirken sich vor allem', 'auf ärmere Haushalte', 'aus']],
    translation: l('The higher prices mainly affect poorer households.', 'Yüksek fiyatlar özellikle yoksul haneleri etkiliyor.', 'Die höheren Preise wirken sich vor allem auf ärmere Haushalte aus.'),
    explanation: l('sich auswirken auf – separable, „aus“ at the end.', 'sich auswirken auf – ayrılabilir, „aus“ sonda.', 'auswirken.'),
    examples: ['Die Preise **wirken sich** auf ärmere Haushalte **aus**.'],
  },
  {
    id: 'build-dadurch',
    type: 'sentence_builder',
    topic: 'zusammenhaenge',
    concept: 'cause-effect',
    skill: 'writing',
    difficulty: 3,
    chips: ['steigt', 'Dadurch', 'der Meeresspiegel', 'weltweit'],
    answers: [['Dadurch', 'steigt', 'der Meeresspiegel', 'weltweit'], ['Dadurch', 'steigt', 'weltweit', 'der Meeresspiegel']],
    translation: l('As a result, sea levels are rising worldwide.', 'Bunun sonucunda deniz seviyesi dünya çapında yükseliyor.', 'Dadurch steigt der Meeresspiegel weltweit.'),
    explanation: l('dadurch in position 1 → verb next.', 'dadurch 1. konumda → ardından fiil.', 'dadurch.'),
    examples: ['**Dadurch steigt** der Meeresspiegel weltweit.'],
  },
  {
    id: 'fix-fuehrt',
    type: 'error_correction',
    topic: 'zusammenhaenge',
    concept: 'cause-effect',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Der Klimawandel führt zu häufigere Dürren.',
    accepted: ['Der Klimawandel führt zu häufigeren Dürren.'],
    explanation: l('zu + dative plural → häufigeren Dürren.', 'zu + Dativ çoğul → häufigeren Dürren.', 'Dativ.'),
    examples: ['… führt zu **häufigeren** Dürren.'],
  },
  {
    id: 'fix-infolge',
    type: 'error_correction',
    topic: 'zusammenhaenge',
    concept: 'cause-effect',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Infolge dem Hochwasser mussten viele Menschen ihre Häuser verlassen.',
    accepted: ['Infolge des Hochwassers mussten viele Menschen ihre Häuser verlassen.'],
    explanation: l('infolge + genitive.', 'infolge + Genitiv.', 'Genitiv.'),
    examples: ['**Infolge des Hochwassers** mussten …'],
  },
  {
    id: 'fix-greift',
    type: 'error_correction',
    topic: 'massnahmen',
    concept: 'evaluate',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Das neue Gesetz greift zu lang.',
    accepted: ['Das neue Gesetz greift zu kurz.'],
    explanation: l('zu kurz greifen = to fall short (fixed phrase).', 'zu kurz greifen = yetersiz kalmak (kalıp).', 'kurz.'),
    examples: ['Das neue Gesetz greift zu **kurz**.'],
  },
  {
    id: 'tr-senken',
    type: 'translation',
    topic: 'massnahmen',
    concept: 'emissions',
    skill: 'writing',
    difficulty: 3,
    source: l('The transport sector must reduce its emissions significantly.', 'Ulaşım sektörü emisyonlarını önemli ölçüde azaltmalı.', 'The transport sector must reduce its emissions significantly.'),
    accepted: ['Der Verkehrssektor muss seine Emissionen deutlich senken.', 'Der Verkehrssektor muss seine Emissionen erheblich senken.', 'Der Verkehrssektor muss seine Emissionen deutlich reduzieren.'],
    explanation: l('Emissionen senken / reduzieren.', 'Emissionen senken / reduzieren.', 'senken.'),
    examples: ['Der Verkehrssektor muss seine Emissionen deutlich **senken**.'],
  },
  {
    id: 'tr-klimaneutral',
    type: 'translation',
    topic: 'massnahmen',
    concept: 'goals',
    skill: 'writing',
    difficulty: 2,
    source: l('Germany wants to become climate-neutral by 2045.', 'Almanya 2045’e kadar iklim nötr olmak istiyor.', 'Germany wants to become climate-neutral by 2045.'),
    accepted: ['Deutschland will bis 2045 klimaneutral werden.', 'Deutschland möchte bis 2045 klimaneutral werden.', 'Deutschland will bis zum Jahr 2045 klimaneutral werden.'],
    explanation: l('bis 2045 = by 2045.', 'bis 2045 = 2045’e kadar.', 'klimaneutral.'),
    examples: ['Deutschland will **bis 2045 klimaneutral** werden.'],
  },
  {
    id: 'ordering-kette',
    type: 'ordering',
    topic: 'zusammenhaenge',
    concept: 'chain',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Order the chain of effects.', 'Etki zincirini sırala.', 'Ordne die Wirkungskette.'),
    items: ['Dadurch erwärmt sich die Erdatmosphäre.', 'Bei der Verbrennung von Kohle entsteht CO₂.', 'Infolgedessen kommt es zu Ernteausfällen und steigenden Lebensmittelpreisen.', 'Die Erwärmung führt zu häufigeren Dürren.'],
    answer: ['Bei der Verbrennung von Kohle entsteht CO₂.', 'Dadurch erwärmt sich die Erdatmosphäre.', 'Die Erwärmung führt zu häufigeren Dürren.', 'Infolgedessen kommt es zu Ernteausfällen und steigenden Lebensmittelpreisen.'],
    explanation: l('Cause → effect → further effect → social consequence.', 'Neden → etki → ek etki → toplumsal sonuç.', 'Kette.'),
  },
  {
    id: 'dialog-steuer',
    type: 'dialogue',
    topic: 'zielkonflikte',
    concept: 'debate',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Nachbar', de: 'Die CO₂-Steuer ist doch nur Abzocke. Am Ende zahlen wir kleinen Leute.' }],
    options: ['Das Risiko besteht, ja. Deshalb wäre ein Klimageld sinnvoll, das die Einnahmen an alle zurückgibt.', 'Steuer ist Steuer, egal.', 'Kleine Leute zahlen nie Steuer.'],
    answer: 0,
    explanation: l('Acknowledge the concern, then propose a solution.', 'Kaygıyı kabul et, sonra bir çözüm öner.', 'Lösung.'),
  },
  {
    id: 'dialog-wind',
    type: 'dialogue',
    topic: 'zielkonflikte',
    concept: 'trade-off',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Bürgermeisterin', de: 'Wir wollen mehr Windräder bauen, aber die Anwohner protestieren.' }],
    options: ['Das ist ein klassischer Zielkonflikt. Vielleicht hilft es, die Anwohner finanziell zu beteiligen.', 'Dann bauen wir einfach Kohlekraftwerke.', 'Windräder sind für Vögel.'],
    answer: 0,
    explanation: l('Name the trade-off and suggest a compromise.', 'Hedef çatışmasını adlandır ve bir uzlaşma öner.', 'Zielkonflikt.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-klima',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Kommentar?',
    options: ['Um die Lücke zwischen Klimazielen und tatsächlicher Politik.', 'Um die Wettervorhersage.', 'Um den Bau eines Flughafens.'],
    answer: 0,
    explanation: l('„Zwischen Anspruch und Wirklichkeit …“', '„Zwischen Anspruch und Wirklichkeit …“', 'Lücke.'),
  },
  {
    id: 'read-verkehr',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-klima',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welcher Sektor verfehlt laut Text seine Ziele?',
    options: ['der Verkehr', 'die Energiewirtschaft', 'die Landwirtschaft'],
    answer: 0,
    explanation: l('„Vor allem der Verkehrssektor verfehlt seine Ziele …“', '„Vor allem der Verkehrssektor verfehlt seine Ziele …“', 'Verkehr.'),
  },
  {
    id: 'read-strom',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-klima',
    skill: 'reading',
    difficulty: 3,
    statement: 'Laut Text stammt inzwischen mehr als die Hälfte des Stroms aus erneuerbaren Quellen.',
    answer: true,
    explanation: l('„… mehr als die Hälfte des Stroms …“', '„… mehr als die Hälfte des Stroms …“', 'richtig.'),
  },
  {
    id: 'read-forderung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-klima',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was fordert der Autor?',
    options: ['Klimaschutz sozial gerecht zu gestalten, z. B. mit einem Klimageld', 'alle Klimaziele abzuschaffen', 'nur noch Verbote einzuführen'],
    answer: 0,
    explanation: l('„… ein Klimageld, das … zurückgibt.“', '„… ein Klimageld, das … zurückgibt.“', 'Klimageld.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-tempolimit',
    type: 'listening_choice',
    topic: 'massnahmen',
    concept: 'evaluate',
    skill: 'listening',
    difficulty: 3,
    audio: 'Ein Tempolimit auf Autobahnen würde jährlich mehrere Millionen Tonnen CO₂ einsparen – und es kostet praktisch nichts.',
    question: l('What is the speaker’s main argument?', 'Konuşanın ana argümanı nedir?', 'Hauptargument?'),
    options: ['big savings at almost no cost', 'it is very expensive', 'it has no effect'],
    answer: 0,
    explanation: l('Einsparung + kostet praktisch nichts.', 'Tasarruf + neredeyse hiç maliyet yok.', 'günstig.'),
  },
  {
    id: 'listen-pendler',
    type: 'listening_choice',
    topic: 'zielkonflikte',
    concept: 'social',
    skill: 'listening',
    difficulty: 3,
    audio: 'Für Pendler auf dem Land gibt es oft keine Alternative zum Auto. Eine höhere Spritsteuer trifft sie besonders hart.',
    question: l('Who is hit especially hard?', 'Kim özellikle ağır etkileniyor?', 'Wen trifft es besonders?'),
    options: ['commuters in rural areas', 'city cyclists', 'airlines'],
    answer: 0,
    explanation: l('Pendler auf dem Land = rural commuters.', 'Pendler auf dem Land = kırsal bölgedeki işe gidip gelenler.', 'Pendler.'),
  },
  {
    id: 'listen-waermepumpe',
    type: 'listening_choice',
    topic: 'massnahmen',
    concept: 'incentive',
    skill: 'listening',
    difficulty: 3,
    audio: 'Wer seine alte Ölheizung durch eine Wärmepumpe ersetzt, bekommt bis zu siebzig Prozent der Kosten erstattet.',
    question: l('What kind of instrument is this?', 'Bu ne tür bir araç?', 'Welches Instrument?'),
    options: ['a financial incentive', 'a ban', 'a tax'],
    answer: 0,
    explanation: l('Cost refund = incentive (Anreiz).', 'Maliyet iadesi = teşvik (Anreiz).', 'Anreiz.'),
  },
  {
    id: 'listen-abkommen',
    type: 'listening_choice',
    topic: 'massnahmen',
    concept: 'goals',
    skill: 'listening',
    difficulty: 3,
    audio: 'Im Pariser Abkommen haben sich die Staaten verpflichtet, die Erderwärmung möglichst auf 1,5 Grad zu begrenzen.',
    question: l('What is the goal of the Paris Agreement?', 'Paris Anlaşması’nın hedefi nedir?', 'Ziel?'),
    options: ['to limit warming to 1.5 degrees if possible', 'to stop all car traffic', 'to double energy production'],
    answer: 0,
    explanation: l('auf 1,5 Grad begrenzen.', 'auf 1,5 Grad begrenzen.', '1,5 Grad.'),
  },

  ...kpDrills(),
]

export const UNIT_C1_15_KLIMAPOLITIK: CourseUnit = {
  level: 'C1',
  number: 15,
  slug: 'klimapolitik',
  titleDe: 'Klimapolitik zwischen Anspruch und Wirklichkeit',
  title: l('Climate policy: aspiration and reality', 'İklim politikası: hedef ve gerçek', 'Klimapolitik'),
  goal: l(
    'By the end of this unit you can evaluate climate measures (CO₂-Steuer, Verbote, Anreize), name trade-offs (Zielkonflikte) and explain complex cause-and-effect chains with dadurch, infolge, führen zu and sich auswirken auf.',
    'Bu ünitenin sonunda iklim önlemlerini (CO₂-Steuer, yasaklar, teşvikler) değerlendirebilir, hedef çatışmalarını adlandırabilir ve dadurch, infolge, führen zu ve sich auswirken auf ile karmaşık neden-sonuç zincirlerini açıklayabilirsin.',
    'Am Ende dieser Einheit bewertest du Klimapolitik.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'massnahmen', label: l('Evaluating measures', 'Önlemleri değerlendirmek', 'Maßnahmen bewerten') },
    { key: 'zielkonflikte', label: l('Naming trade-offs', 'Hedef çatışmalarını adlandırmak', 'Zielkonflikte benennen') },
    { key: 'zusammenhaenge', label: l('Explaining complex connections', 'Karmaşık bağlantıları açıklamak', 'Zusammenhänge erklären') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Goals, measures, conflicts.', 'Hedefler, önlemler, çatışmalar.', 'Ziele und Konflikte.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Cause and effect', 'Neden ve sonuç', 'Ursache und Wirkung'),
          body: l(
            'Connect steps of a chain: führen zu + dative, verursachen, sich auswirken auf + accusative, dadurch / infolgedessen (adverbs, verb in position 2), infolge + genitive (preposition).',
            'Bir zincirin adımlarını bağla: führen zu + Dativ, verursachen, sich auswirken auf + Akkusativ, dadurch / infolgedessen (zarf, fiil 2. konumda), infolge + Genitiv (edat).',
            'Kausalität.'
          ),
          table: {
            head: [l('Structure', 'Yapı', 'Struktur'), l('Example', 'Örnek', 'Beispiel')],
            rows: [
              ['führen zu + D', 'Hitze führt zu Dürren.'],
              ['sich auswirken auf + A', 'Preise wirken sich auf Familien aus.'],
              ['dadurch / infolgedessen', 'Dadurch steigen die Kosten.'],
              ['infolge + G', 'Infolge der Dürre fallen Ernten aus.'],
            ],
          },
        },
        {
          title: l('Trade-offs', 'Hedef çatışmaları', 'Zielkonflikte'),
          body: l(
            'Two legitimate goals contradict each other: climate protection vs. low prices, wind energy vs. nature. Name them: Es besteht ein Zielkonflikt zwischen … und … / … zwar …, aber … / einerseits … andererseits.',
            'İki meşru hedef birbiriyle çelişir: iklim koruması ve düşük fiyatlar, rüzgâr enerjisi ve doğa. Onları adlandır: Es besteht ein Zielkonflikt zwischen … und … / … zwar …, aber … / einerseits … andererseits.',
            'Zielkonflikt.'
          ),
          examples: [
            { de: 'Es besteht ein **Zielkonflikt** zwischen Klimaschutz und bezahlbarer Energie.', translation: l('There is a trade-off between climate protection and affordable energy.', 'İklim koruması ile uygun fiyatlı enerji arasında bir hedef çatışması var.', '') },
            { de: 'Die Steuer senkt **zwar** Emissionen, belastet **aber** Geringverdiener.', translation: l('The tax does reduce emissions, but burdens low earners.', 'Vergi gerçi emisyonları azaltıyor ama düşük gelirlilere yük oluyor.', '') },
          ],
        },
        {
          title: l('Evaluating measures', 'Önlemleri değerlendirmek', 'Maßnahmen bewerten'),
          body: l(
            'Useful phrases: Die Maßnahme greift zu kurz / ist wirksam / ist sozial (un)verträglich / setzt die richtigen Anreize. Zwischen Anspruch und Wirklichkeit klafft eine Lücke.',
            'Faydalı ifadeler: Die Maßnahme greift zu kurz / ist wirksam / ist sozial (un)verträglich / setzt die richtigen Anreize. Zwischen Anspruch und Wirklichkeit klafft eine Lücke.',
            'Bewertung.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A TV talk show about the carbon tax.', 'Karbon vergisi hakkında bir TV programı.', 'Talkshow.'),
      dialogue: [
        { speaker: 'Moderator', de: 'Frau Dr. Lenz, wirkt die **CO₂-Steuer**?', translation: l('Dr Lenz, is the carbon tax working?', 'Dr. Lenz, karbon vergisi işe yarıyor mu?', '') },
        { speaker: 'Dr. Lenz', de: 'Ja. Sie verteuert fossile Energie. **Dadurch** lohnen sich klimafreundliche Alternativen.', translation: l('Yes. It makes fossil energy more expensive. As a result, climate-friendly alternatives pay off.', 'Evet. Fosil enerjiyi pahalılaştırıyor. Bu sayede iklim dostu alternatifler kârlı hale geliyor.', '') },
        { speaker: 'Herr Brandt', de: 'Aber die Preise **wirken sich** vor allem **auf** Pendler und Rentner **aus**. Das ist nicht **sozial verträglich**.', translation: l('But the prices mainly affect commuters and pensioners. That is not socially acceptable.', 'Ama fiyatlar özellikle işe gidip gelenleri ve emeklileri etkiliyor. Bu sosyal açıdan katlanılabilir değil.', '') },
        { speaker: 'Dr. Lenz', de: 'Das ist ein echter **Zielkonflikt**. Deshalb fordern wir ein **Klimageld**, das die Einnahmen zurückgibt.', translation: l('That is a real trade-off. That’s why we are calling for a climate dividend that returns the revenue.', 'Bu gerçek bir hedef çatışması. Bu yüzden gelirleri geri veren bir iklim parası talep ediyoruz.', '') },
        { speaker: 'Herr Brandt', de: 'Das klingt gut, aber bisher gibt es das nicht. Die Politik **greift zu kurz**.', translation: l('That sounds good, but it doesn’t exist yet. Policy falls short.', 'Kulağa hoş geliyor ama şimdiye kadar yok. Politika yetersiz kalıyor.', '') },
        { speaker: 'Moderator', de: 'Also eine Lücke zwischen **Anspruch und Wirklichkeit**.', translation: l('So a gap between aspiration and reality.', 'Yani hedef ile gerçek arasında bir boşluk.', '') },
      ],
      examples: [
        { de: 'Hitze **führt zu** Ernteausfällen.', translation: l('Heat leads to crop failures.', 'Sıcaklık ürün kayıplarına yol açıyor.', '') },
        { de: '**Infolge** der Dürre steigen die Preise.', translation: l('As a result of the drought, prices are rising.', 'Kuraklık sonucunda fiyatlar artıyor.', '') },
        { de: 'Das Gesetz **greift zu kurz**.', translation: l('The law falls short.', 'Yasa yetersiz kalıyor.', '') },
        { de: 'Wir müssen die **Emissionen senken**.', translation: l('We must reduce emissions.', 'Emisyonları azaltmalıyız.', '') },
        { de: 'Deutschland will **klimaneutral** werden.', translation: l('Germany wants to become climate-neutral.', 'Almanya iklim nötr olmak istiyor.', '') },
        { de: 'Förderprogramme setzen **Anreize**.', translation: l('Funding programmes create incentives.', 'Destek programları teşvik sağlıyor.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Measures, causes, conflicts.', 'Önlemler, nedenler, çatışmalar.', 'Maßnahmen und Ursachen.'),
      exercises: ['match-instrumente', 'sort-ursache', 'kp-dadurch', 'kp-infolge', 'kp-fuehrt', 'mc-zielkonflikt', 'tf-neutral', 'select-sozial', 'image-energie'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Explain and evaluate.', 'Açıkla ve değerlendir.', 'Erklären und bewerten.'),
      exercises: [
        'fill-zwar',
        'fill-fuehrt',
        'fill-vertraeglich',
        'build-anspruch',
        'build-auswirken',
        'build-dadurch',
        'fix-fuehrt',
        'fix-infolge',
        'fix-greift',
        'tr-senken',
        'tr-klimaneutral',
        'ordering-kette',
        'dialog-steuer',
        'dialog-wind',
        'kp-auswirken',
        'kp-greift',
        'kp-zielkonflikt',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A newspaper commentary.', 'Bir gazete yorumu.', 'Ein Kommentar.'),
      passage: [
        '**Zwischen Anspruch und Wirklichkeit** – Deutschland will bis 2045 klimaneutral werden. Doch zwischen diesem Ziel und der tatsächlichen Politik klafft eine Lücke.',
        'Zwar gibt es Fortschritte: Inzwischen stammt mehr als die Hälfte des Stroms aus erneuerbaren Quellen. Vor allem der Verkehrssektor verfehlt seine Ziele jedoch Jahr für Jahr.',
        'Hinzu kommt ein **Zielkonflikt**: Höhere CO₂-Preise senken die Emissionen, wirken sich aber besonders stark auf Haushalte mit geringem Einkommen aus. **Infolgedessen** sinkt die Akzeptanz.',
        'Klimaschutz muss deshalb sozial gerecht gestaltet werden – etwa durch ein **Klimageld**, das die Einnahmen pro Kopf an die Bürger zurückgibt.',
      ],
      glossary: [
        { de: 'klaffen', note: l('to gape (a gap)', 'açılmak (boşluk)', 'offen sein') },
        { de: 'verfehlen', note: l('to miss (a goal)', 'kaçırmak (hedefi)', 'nicht erreichen') },
        { de: 'die Akzeptanz', note: l('acceptance', 'kabul görme', 'Zustimmung') },
        { de: 'pro Kopf', note: l('per person', 'kişi başına', 'für jeden') },
      ],
      exercises: ['read-thema', 'read-verkehr', 'read-strom', 'read-forderung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Voices from the climate debate.', 'İklim tartışmasından sesler.', 'Stimmen zur Klimapolitik.'),
      exercises: ['listen-tempolimit', 'listen-pendler', 'listen-waermepumpe', 'listen-abkommen'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Evaluate one climate measure (e.g. a speed limit or a ban on combustion engines): effect, trade-off, your conclusion.', 'Bir iklim önlemini değerlendir (ör. hız sınırı ya da içten yanmalı motor yasağı): etki, hedef çatışması, sonucun.', 'Eine Maßnahme bewerten.'),
      points: [
        l('The effect: „… führt zu …“ / „Dadurch …“', 'Etki: „… führt zu …“ / „Dadurch …“', 'Wirkung'),
        l('The trade-off: „Es besteht ein Zielkonflikt …“', 'Hedef çatışması: „Es besteht ein Zielkonflikt …“', 'Zielkonflikt'),
        l('Who is affected: „… wirkt sich auf … aus“', 'Kim etkileniyor: „… wirkt sich auf … aus“', 'Betroffene'),
        l('Your evaluation: „… greift zu kurz / ist sinnvoll“', 'Değerlendirmen: „… greift zu kurz / ist sinnvoll“', 'Bewertung'),
      ],
      model: [
        'Ein Verbot neuer Verbrennungsmotoren führt langfristig zu deutlich weniger Emissionen im Verkehr.',
        'Es besteht jedoch ein Zielkonflikt zwischen Klimaschutz und bezahlbarer Mobilität.',
        'Elektroautos sind teurer, und das wirkt sich vor allem auf Familien mit wenig Geld aus.',
        'Deshalb halte ich das Verbot nur dann für sinnvoll, wenn es Zuschüsse für Geringverdiener gibt.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short commentary (at least 6 sentences): „Klimaschutz – zu teuer für die Bürger?“ Explain connections, name a trade-off and evaluate a measure.',
        'Kısa bir yorum yazısı yaz (en az 6 cümle): „Klimaschutz – zu teuer für die Bürger?“ Bağlantıları açıkla, bir hedef çatışmasını adlandır ve bir önlemi değerlendir.',
        'Kommentar (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Cause and effect (führt zu, dadurch, infolge, wirkt sich … aus)', 'Neden ve sonuç (führt zu, dadurch, infolge, wirkt sich … aus)', 'Kausalität'), pattern: '(führ\\p{Ll}* zu|[Dd]adurch|[Ii]nfolge|wirk\\p{Ll}* sich[^.]*aus)' },
        { label: l('A trade-off (Zielkonflikt, zwar … aber)', 'Bir hedef çatışması (Zielkonflikt, zwar … aber)', 'Zielkonflikt'), pattern: '(Zielkonflikt|\\bzwar\\b[^.]*\\baber\\b)' },
        { label: l('An evaluation (greift zu kurz, sinnvoll, verträglich, wirksam)', 'Bir değerlendirme (greift zu kurz, sinnvoll, verträglich, wirksam)', 'Bewertung'), pattern: '(zu kurz|sinnvoll|verträglich|wirksam|gerecht)' },
      ],
      model: [
        'Viele Bürger haben den Eindruck, dass Klimaschutz vor allem teuer ist.',
        'Tatsächlich führt die CO₂-Steuer zu höheren Preisen für Benzin und Heizöl.',
        'Dadurch werden Haushalte mit geringem Einkommen besonders stark belastet.',
        'Es besteht also ein Zielkonflikt zwischen Klimaschutz und sozialer Gerechtigkeit.',
        'Ein Klimageld, das die Einnahmen an alle zurückgibt, wäre jedoch eine sinnvolle Lösung.',
        'Ohne einen solchen Ausgleich greift die Klimapolitik zu kurz.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Cause and effect – 60 seconds.', 'Neden ve sonuç – 60 saniye.', 'Ursache und Wirkung – 60 Sekunden.'),
      seconds: 60,
      pool: [...KP.map(([id]) => `kp-${id}`), 'mc-zielkonflikt'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Cause and effect: führen zu, sich auswirken auf, dadurch, infolge', 'Neden-sonuç: führen zu, sich auswirken auf, dadurch, infolge', 'Kausalität'),
      l('Trade-offs: Es besteht ein Zielkonflikt zwischen … und …', 'Hedef çatışmaları: Es besteht ein Zielkonflikt zwischen … und …', 'Zielkonflikt'),
      l('Evaluation: greift zu kurz, sozial verträglich, setzt Anreize', 'Değerlendirme: greift zu kurz, sozial verträglich, setzt Anreize', 'Bewertung'),
      l('Climate terms: klimaneutral, Energiewende, CO₂-Steuer, Klimageld', 'İklim terimleri: klimaneutral, Energiewende, CO₂-Steuer, Klimageld', 'Begriffe'),
    ],
    mistakes: [
      { wrong: 'Infolge dem Hochwasser …', right: 'Infolge des Hochwassers …', note: l('infolge + genitive.', 'infolge + Genitiv.', 'Genitiv.') },
      { wrong: 'Das führt zu höhere Preise.', right: 'Das führt zu höheren Preisen.', note: l('zu + dative.', 'zu + Dativ.', 'Dativ.') },
      { wrong: 'Die Preise wirken sich an Familien aus.', right: 'Die Preise wirken sich auf Familien aus.', note: l('sich auswirken auf.', 'sich auswirken auf.', 'auf.') },
      { wrong: 'Das Gesetz greift zu lang.', right: 'Das Gesetz greift zu kurz.', note: l('Fixed phrase.', 'Kalıp.', 'kurz.') },
    ],
  },
}
