import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Gentrifizierung', emoji: '🏙️', translation: l('gentrification', 'soylulaştırma', 'Aufwertung eines Viertels'), example: 'Durch die Gentrifizierung steigen die Mieten im Viertel.' },
  { word: 'verdrängt werden', emoji: '📦', translation: l('to be pushed out', 'yerinden edilmek', 'wegziehen müssen'), example: 'Alteingesessene Bewohner werden aus ihren Wohnungen verdrängt.' },
  { word: 'bezahlbarer Wohnraum', emoji: '🏠', translation: l('affordable housing', 'uygun fiyatlı konut', 'günstige Wohnungen'), example: 'In Großstädten fehlt bezahlbarer Wohnraum.' },
  { word: 'die Verkehrswende', emoji: '🚲', translation: l('transport transition', 'ulaşım dönüşümü', 'weg vom Auto'), example: 'Die Verkehrswende braucht bessere Radwege.' },
  { word: 'der öffentliche Nahverkehr', emoji: '🚋', translation: l('public transport', 'toplu taşıma', 'Bus und Bahn'), example: 'Der öffentliche Nahverkehr soll ausgebaut werden.' },
  { word: 'die Bürgerbeteiligung', emoji: '🗳️', translation: l('citizen participation', 'vatandaş katılımı', 'Bürger entscheiden mit'), example: 'Bei dem Projekt gab es eine breite Bürgerbeteiligung.' },
  { word: 'die Mietpreisbremse', emoji: '🛑', translation: l('rent cap', 'kira artış freni', 'Begrenzung der Mieten'), example: 'Die Mietpreisbremse soll den Anstieg der Mieten dämpfen.' },
  { word: 'die Aufwertung', emoji: '📈', translation: l('upgrading, appreciation', 'değer artışı', 'wird attraktiver'), example: 'Die Aufwertung des Viertels hat Vor- und Nachteile.' },
  { word: 'nachverdichten', emoji: '🧱', translation: l('to build more densely', 'yoğunlaştırmak (yapılaşma)', 'mehr bauen auf wenig Fläche'), example: 'Statt neue Flächen zu versiegeln, sollte man nachverdichten.' },
  { word: 'die 15-Minuten-Stadt', emoji: '⏱️', translation: l('15-minute city', '15 dakikalık şehir', 'alles in 15 Minuten erreichbar'), example: 'In der 15-Minuten-Stadt ist alles zu Fuß erreichbar.' },
  { word: 'lebenswert', emoji: '🌳', translation: l('liveable', 'yaşanabilir', 'gut zum Leben'), example: 'Kopenhagen gilt als eine der lebenswertesten Städte.' },
  { word: 'mitbestimmen', emoji: '✋', translation: l('to have a say', 'söz sahibi olmak', 'mitentscheiden'), example: 'Anwohner sollten über die Planung mitbestimmen dürfen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Viertel', gender: 'n', plural: 'die Viertel', translation: l('neighbourhood', 'semt', 'Viertel') },
  { word: 'Anwohner', gender: 'm', plural: 'die Anwohner', translation: l('resident', 'bölge sakini', 'Anwohner') },
  { word: 'Investor', gender: 'm', plural: 'die Investoren', translation: l('investor', 'yatırımcı', 'Investor') },
  { word: 'Sozialwohnung', gender: 'f', plural: 'die Sozialwohnungen', translation: l('social housing flat', 'sosyal konut', 'Sozialwohnung') },
  { word: 'Grünfläche', gender: 'f', plural: 'die Grünflächen', translation: l('green space', 'yeşil alan', 'Grünfläche') },
  { word: 'Radweg', gender: 'm', plural: 'die Radwege', translation: l('cycle path', 'bisiklet yolu', 'Radweg') },
  { word: 'Stadtrat', gender: 'm', plural: 'die Stadträte', translation: l('city council', 'belediye meclisi', 'Stadtrat') },
  { word: 'Bebauungsplan', gender: 'm', plural: 'die Bebauungspläne', translation: l('development plan', 'imar planı', 'Bebauungsplan') },
]

/** [id, sentence with gap, right, wrong] */
const SE: [string, string, string, [string, string]][] = [
  ['verdraengt', 'Viele ältere Mieter werden durch die steigenden Preise aus dem Viertel ___.', 'verdrängt', ['verdrängen', 'verdrängend']],
  ['wohnraum', 'Die Stadt muss dringend mehr bezahlbaren ___ schaffen.', 'Wohnraum', ['Wohnräume', 'Wohnzimmer']],
  ['ausgebaut', 'Der Nahverkehr soll in den nächsten Jahren deutlich ___ werden.', 'ausgebaut', ['ausbauen', 'ausgebaute']],
  ['beteiligt', 'Die Bürger sollten frühzeitig an der Planung ___ werden.', 'beteiligt', ['beteiligen', 'teilgenommen']],
  ['anstatt', '___ neue Flächen zu versiegeln, sollte man bestehende Gebäude aufstocken.', 'Anstatt', ['Ohne dass', 'Damit']],
  ['waere', 'Eine autofreie Innenstadt ___ für Familien deutlich lebenswerter.', 'wäre', ['war', 'würde']],
]

function seDrills(): Exercise[] {
  return SE.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `se-${id}`,
      type: 'multiple_choice' as const,
      topic: 'mobilitaet',
      concept: 'urban-forms',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Urban planning language uses many passives (werden verdrängt, soll ausgebaut werden, sollten beteiligt werden), anstatt … zu (instead of) and Konjunktiv II for visions (wäre lebenswerter). Wohnraum is uncountable.',
        'Şehir planlama dili çok sayıda edilgen kullanır (werden verdrängt, soll ausgebaut werden, sollten beteiligt werden), anstatt … zu (… yerine) ve vizyonlar için Konjunktiv II (wäre lebenswerter). Wohnraum sayılamaz.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-begriffe',
    type: 'matching',
    topic: 'gentrifizierung',
    concept: 'terms',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the term and its explanation.', 'Terimi açıklamasıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Gentrifizierung', right: 'Viertel wird teurer, Bewohner ziehen weg' },
      { left: 'Mietpreisbremse', right: 'begrenzt Mieterhöhungen' },
      { left: 'Nachverdichtung', right: 'mehr Wohnungen auf vorhandener Fläche' },
      { left: 'Bürgerbeteiligung', right: 'Einwohner planen mit' },
      { left: '15-Minuten-Stadt', right: 'alles Wichtige zu Fuß erreichbar' },
    ],
    explanation: l('Key terms of urban development.', 'Kentsel gelişimin temel terimleri.', 'Begriffe.'),
  },
  {
    id: 'sort-folgen',
    type: 'categorize',
    topic: 'gentrifizierung',
    concept: 'pro-contra',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Positive or negative effect of gentrification?', 'Soylulaştırmanın olumlu mu olumsuz mu etkisi?', 'Positive oder negative Folge?'),
    categories: ['positiv ✅', 'negativ ⚠️'],
    items: [
      { text: 'sanierte Gebäude', category: 0 },
      { text: 'steigende Mieten', category: 1 },
      { text: 'neue Cafés und Geschäfte', category: 0 },
      { text: 'Verdrängung alter Bewohner', category: 1 },
      { text: 'mehr Sicherheit', category: 0 },
      { text: 'Verlust der sozialen Mischung', category: 1 },
    ],
    explanation: l('Gentrification has winners and losers.', 'Soylulaştırmanın kazananları ve kaybedenleri vardır.', 'Folgen.'),
    practice: ['se-verdraengt'],
  },
  {
    id: 'mc-beteiligung',
    type: 'multiple_choice',
    topic: 'beteiligung',
    concept: 'participation',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welches Beispiel zeigt echte Bürgerbeteiligung?',
    options: ['Anwohner entwickeln in Workshops gemeinsam mit Planern Ideen für einen neuen Park.', 'Die Stadt informiert per Zeitung über eine fertige Entscheidung.', 'Ein Investor kauft ein Grundstück.'],
    answer: 0,
    explanation: l('Real participation = co-deciding, not just being informed.', 'Gerçek katılım = birlikte karar vermek, sadece bilgilendirilmek değil.', 'Beteiligung.'),
    practice: ['fill-beteiligt'],
  },
  {
    id: 'tf-bremse',
    type: 'true_false',
    topic: 'gentrifizierung',
    concept: 'rent-cap',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Mietpreisbremse verbietet jede Mieterhöhung.',
    answer: false,
    explanation: l('It only limits increases for new contracts in tight markets.', 'Yalnızca sıkışık piyasalarda yeni sözleşmelerdeki artışları sınırlar.', 'falsch.'),
  },
  {
    id: 'select-lebenswert',
    type: 'multiple_select',
    topic: 'mobilitaet',
    concept: 'liveable',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('What makes a city more liveable? Select all.', 'Bir şehri daha yaşanabilir yapan nedir? Hepsini seç.', 'Was macht eine Stadt lebenswert?'),
    options: ['mehr Grünflächen', 'sichere Radwege', 'sechsspurige Straßen im Zentrum', 'guter öffentlicher Nahverkehr', 'weniger Spielplätze'],
    answers: [0, 1, 3],
    explanation: l('Green spaces, cycling and public transport.', 'Yeşil alanlar, bisiklet ve toplu taşıma.', 'lebenswert.'),
  },
  {
    id: 'image-tram',
    type: 'image_choice',
    topic: 'mobilitaet',
    concept: 'transport',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'der öffentliche Nahverkehr',
    options: [
      { emoji: '🚋', label: 'Straßenbahn' },
      { emoji: '🏎️', label: 'Rennwagen' },
      { emoji: '🛥️', label: 'Yacht' },
      { emoji: '🚁', label: 'Hubschrauber' },
    ],
    answer: 0,
    explanation: l('Tram = public transport.', 'Tramvay = toplu taşıma.', 'Nahverkehr.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-beteiligt',
    type: 'fill_blank',
    topic: 'beteiligung',
    concept: 'participation',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Anwohner wurden von Anfang an an der Planung ___.',
    accepted: ['beteiligt'],
    base: 'beteiligen (Passiv)',
    explanation: l('jemanden an etwas beteiligen – passive: wurden beteiligt.', 'jemanden an etwas beteiligen – edilgen: wurden beteiligt.', 'beteiligt.'),
    examples: ['Die Anwohner **wurden** an der Planung **beteiligt**.'],
  },
  {
    id: 'fill-anstatt',
    type: 'fill_blank',
    topic: 'mobilitaet',
    concept: 'alternative',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Anstatt neue Straßen ___ bauen, sollte die Stadt in Radwege investieren.',
    accepted: ['zu'],
    base: 'anstatt …',
    explanation: l('anstatt … zu + infinitive.', 'anstatt … zu + mastar.', 'zu.'),
    examples: ['Anstatt neue Straßen **zu** bauen, …'],
  },
  {
    id: 'fill-wende',
    type: 'fill_blank',
    topic: 'mobilitaet',
    concept: 'transition',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Verkehrs___ soll den Anteil des Autos in der Stadt deutlich senken.',
    accepted: ['wende'],
    base: 'Umstieg',
    explanation: l('die Verkehrswende = transport transition.', 'die Verkehrswende = ulaşım dönüşümü.', 'Verkehrswende.'),
    examples: ['Die **Verkehrswende** soll …'],
  },
  {
    id: 'build-verdraengt',
    type: 'sentence_builder',
    topic: 'gentrifizierung',
    concept: 'displacement',
    skill: 'writing',
    difficulty: 3,
    chips: ['werden', 'Langjährige Bewohner', 'aus ihrem Viertel verdrängt', 'zunehmend'],
    answers: [['Langjährige Bewohner', 'werden', 'zunehmend', 'aus ihrem Viertel verdrängt']],
    translation: l('Long-standing residents are increasingly being pushed out of their neighbourhood.', 'Uzun süredir oturanlar giderek semtlerinden ediliyor.', 'Langjährige Bewohner werden zunehmend aus ihrem Viertel verdrängt.'),
    explanation: l('Passive: werden … verdrängt.', 'Edilgen: werden … verdrängt.', 'Passiv.'),
    examples: ['Bewohner **werden** aus ihrem Viertel **verdrängt**.'],
  },
  {
    id: 'build-waere',
    type: 'sentence_builder',
    topic: 'mobilitaet',
    concept: 'vision',
    skill: 'writing',
    difficulty: 3,
    chips: ['wäre', 'Eine Stadt mit mehr Grün', 'für alle', 'lebenswerter'],
    answers: [['Eine Stadt mit mehr Grün', 'wäre', 'für alle', 'lebenswerter'], ['Eine Stadt mit mehr Grün', 'wäre', 'lebenswerter', 'für alle']],
    translation: l('A city with more green would be more liveable for everyone.', 'Daha yeşil bir şehir herkes için daha yaşanabilir olurdu.', 'Eine Stadt mit mehr Grün wäre für alle lebenswerter.'),
    explanation: l('Vision with Konjunktiv II: wäre.', 'Konjunktiv II ile vizyon: wäre.', 'wäre.'),
    examples: ['Eine Stadt mit mehr Grün **wäre** lebenswerter.'],
  },
  {
    id: 'build-mitbestimmen',
    type: 'sentence_builder',
    topic: 'beteiligung',
    concept: 'participation',
    skill: 'writing',
    difficulty: 3,
    chips: ['dürfen', 'Anwohner sollten', 'über neue Bauprojekte', 'mitbestimmen'],
    answers: [['Anwohner sollten', 'über neue Bauprojekte', 'mitbestimmen', 'dürfen']],
    translation: l('Residents should be allowed to have a say in new building projects.', 'Bölge sakinleri yeni inşaat projelerinde söz sahibi olabilmeli.', 'Anwohner sollten über neue Bauprojekte mitbestimmen dürfen.'),
    explanation: l('Two modal verbs: sollten … mitbestimmen dürfen.', 'İki kiplik fiil: sollten … mitbestimmen dürfen.', 'Modalverben.'),
    examples: ['Anwohner **sollten** … **mitbestimmen dürfen**.'],
  },
  {
    id: 'fix-wohnraum',
    type: 'error_correction',
    topic: 'gentrifizierung',
    concept: 'housing',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Es fehlen viele bezahlbare Wohnraum.',
    accepted: ['Es fehlt bezahlbarer Wohnraum.', 'Es fehlt viel bezahlbarer Wohnraum.', 'Es fehlen viele bezahlbare Wohnungen.'],
    explanation: l('Wohnraum is uncountable (singular) – or use Wohnungen.', 'Wohnraum sayılamaz (tekil) – ya da Wohnungen kullan.', 'Wohnraum.'),
    examples: ['Es **fehlt** bezahlbarer **Wohnraum**.'],
  },
  {
    id: 'fix-ausgebaut',
    type: 'error_correction',
    topic: 'mobilitaet',
    concept: 'passive',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das Radnetz soll bis 2030 ausbauen werden.',
    accepted: ['Das Radnetz soll bis 2030 ausgebaut werden.'],
    explanation: l('Modal + passive: participle + werden.', 'Modal + edilgen: ortaç + werden.', 'ausgebaut.'),
    examples: ['Das Radnetz soll **ausgebaut werden**.'],
  },
  {
    id: 'fix-beteiligt',
    type: 'error_correction',
    topic: 'beteiligung',
    concept: 'participation',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Bürger wurden bei der Planung nicht teilgenommen.',
    accepted: ['Die Bürger wurden an der Planung nicht beteiligt.', 'Die Bürger wurden bei der Planung nicht beteiligt.', 'Die Bürger haben an der Planung nicht teilgenommen.'],
    explanation: l('teilnehmen has no passive with a person subject → beteiligt werden.', 'teilnehmen kişi özneli edilgen olmaz → beteiligt werden.', 'beteiligt.'),
    examples: ['Die Bürger **wurden** an der Planung nicht **beteiligt**.'],
  },
  {
    id: 'tr-gentrifizierung',
    type: 'translation',
    topic: 'gentrifizierung',
    concept: 'rents',
    skill: 'writing',
    difficulty: 3,
    source: l('Gentrification is driving up rents in the neighbourhood.', 'Soylulaştırma semtteki kiraları yükseltiyor.', 'Gentrification is driving up rents in the neighbourhood.'),
    accepted: ['Die Gentrifizierung treibt die Mieten im Viertel in die Höhe.', 'Durch die Gentrifizierung steigen die Mieten im Viertel.', 'Die Gentrifizierung lässt die Mieten im Viertel steigen.'],
    explanation: l('in die Höhe treiben = to drive up.', 'in die Höhe treiben = yükseltmek.', 'Mieten.'),
    examples: ['Die Gentrifizierung **treibt** die Mieten **in die Höhe**.'],
  },
  {
    id: 'tr-viertel',
    type: 'translation',
    topic: 'mobilitaet',
    concept: 'fifteen-minutes',
    skill: 'writing',
    difficulty: 3,
    source: l('In a 15-minute city everything is reachable on foot.', '15 dakikalık bir şehirde her şeye yürüyerek ulaşılabilir.', 'In a 15-minute city everything is reachable on foot.'),
    accepted: ['In einer 15-Minuten-Stadt ist alles zu Fuß erreichbar.', 'In der 15-Minuten-Stadt ist alles zu Fuß erreichbar.'],
    explanation: l('zu Fuß erreichbar.', 'zu Fuß erreichbar.', 'erreichbar.'),
    examples: ['… ist alles **zu Fuß erreichbar**.'],
  },
  {
    id: 'ordering-viertel',
    type: 'ordering',
    topic: 'gentrifizierung',
    concept: 'process',
    skill: 'reading',
    difficulty: 3,
    promptL10n: l('Order the typical stages of gentrification.', 'Soylulaştırmanın tipik aşamalarını sırala.', 'Ordne die Phasen.'),
    items: ['Investoren kaufen Häuser und sanieren sie.', 'Künstler und Studierende ziehen wegen der günstigen Mieten in ein Viertel.', 'Alteingesessene können sich die Mieten nicht mehr leisten und ziehen weg.', 'Das Viertel wird angesagt, neue Cafés eröffnen.'],
    answer: ['Künstler und Studierende ziehen wegen der günstigen Mieten in ein Viertel.', 'Das Viertel wird angesagt, neue Cafés eröffnen.', 'Investoren kaufen Häuser und sanieren sie.', 'Alteingesessene können sich die Mieten nicht mehr leisten und ziehen weg.'],
    explanation: l('Pioneers → trend → investment → displacement.', 'Öncüler → moda → yatırım → yerinden edilme.', 'Phasen.'),
  },
  {
    id: 'dialog-anwohner',
    type: 'dialogue',
    topic: 'beteiligung',
    concept: 'participation',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Stadtplaner', de: 'Wir planen auf dem Parkplatz einen Wohnblock mit 200 Wohnungen.' }],
    options: ['Wir begrüßen neuen Wohnraum, möchten aber an der Planung beteiligt werden – vor allem, was Grünflächen angeht.', 'Parkplatz Wohnung nein.', 'Ist uns egal, macht was ihr wollt.'],
    answer: 0,
    explanation: l('Constructive: agree in principle, demand participation.', 'Yapıcı: ilke olarak katıl, katılım talep et.', 'Beteiligung.'),
  },
  {
    id: 'dialog-auto',
    type: 'dialogue',
    topic: 'mobilitaet',
    concept: 'debate',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Ladenbesitzer', de: 'Wenn die Parkplätze wegfallen, kommen keine Kunden mehr!' }],
    options: ['Studien zeigen eher das Gegenteil: Fußgänger und Radfahrer kaufen häufiger in kleinen Läden ein.', 'Kunden kommen nie.', 'Parkplätze sind nicht wichtig, weil nein.'],
    answer: 0,
    explanation: l('Counter with evidence.', 'Kanıtla karşılık ver.', 'Gegenargument.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-stadt',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in der Reportage?',
    options: ['Um ein Viertel, das sich durch Gentrifizierung stark verändert.', 'Um eine neue U-Bahn-Linie.', 'Um ein Fußballstadion.'],
    answer: 0,
    explanation: l('„Vom Arbeiterviertel zum Szenekiez …“', '„Vom Arbeiterviertel zum Szenekiez …“', 'Gentrifizierung.'),
  },
  {
    id: 'read-miete',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-stadt',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wie haben sich die Mieten entwickelt?',
    options: ['Sie haben sich in zehn Jahren fast verdoppelt.', 'Sie sind gesunken.', 'Sie sind gleich geblieben.'],
    answer: 0,
    explanation: l('„… haben sich die Mieten fast verdoppelt.“', '„… haben sich die Mieten fast verdoppelt.“', 'verdoppelt.'),
  },
  {
    id: 'read-frau',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-stadt',
    skill: 'reading',
    difficulty: 3,
    statement: 'Frau Schulte kann sich ihre Wohnung problemlos weiter leisten.',
    answer: false,
    explanation: l('„… muss sie nun ausziehen.“', '„… muss sie nun ausziehen.“', 'falsch.'),
  },
  {
    id: 'read-loesung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-stadt',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was hat die Stadt als Reaktion beschlossen?',
    options: ['Bei Neubauten muss ein Drittel Sozialwohnungen sein.', 'Alle Neubauten werden verboten.', 'Die Mieten werden halbiert.'],
    answer: 0,
    explanation: l('„… ein Drittel als Sozialwohnungen …“', '„… ein Drittel als Sozialwohnungen …“', 'Quote.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-paris',
    type: 'listening_choice',
    topic: 'mobilitaet',
    concept: 'fifteen-minutes',
    skill: 'listening',
    difficulty: 3,
    audio: 'Paris will zur 15-Minuten-Stadt werden: Schule, Arzt und Supermarkt sollen für alle in einer Viertelstunde zu Fuß erreichbar sein.',
    question: l('What is Paris aiming for?', 'Paris neyi hedefliyor?', 'Ziel von Paris?'),
    options: ['everything essential within a 15-minute walk', 'faster cars', 'more parking garages'],
    answer: 0,
    explanation: l('15-Minuten-Stadt.', '15-Minuten-Stadt.', 'zu Fuß.'),
  },
  {
    id: 'listen-dach',
    type: 'listening_choice',
    topic: 'gentrifizierung',
    concept: 'densify',
    skill: 'listening',
    difficulty: 3,
    audio: 'Anstatt am Stadtrand neue Felder zu bebauen, setzen wir auf Nachverdichtung: Wir stocken bestehende Häuser um ein bis zwei Etagen auf.',
    question: l('How does the city want to create housing?', 'Şehir nasıl konut yaratmak istiyor?', 'Wie entsteht Wohnraum?'),
    options: ['by adding floors to existing buildings', 'by building on fields outside the city', 'by demolishing old houses'],
    answer: 0,
    explanation: l('aufstocken = add storeys.', 'aufstocken = kat eklemek.', 'Nachverdichtung.'),
  },
  {
    id: 'listen-buergerrat',
    type: 'listening_choice',
    topic: 'beteiligung',
    concept: 'participation',
    skill: 'listening',
    difficulty: 3,
    audio: 'Im Bürgerrat haben fünfzig zufällig ausgewählte Einwohner Vorschläge für den neuen Marktplatz erarbeitet.',
    question: l('Who developed the proposals?', 'Önerileri kim hazırladı?', 'Wer hat Vorschläge erarbeitet?'),
    options: ['fifty randomly selected residents', 'the mayor alone', 'an investor'],
    answer: 0,
    explanation: l('Bürgerrat = citizens’ assembly.', 'Bürgerrat = vatandaş meclisi.', 'Bürgerrat.'),
  },
  {
    id: 'listen-rad',
    type: 'listening_choice',
    topic: 'mobilitaet',
    concept: 'transition',
    skill: 'listening',
    difficulty: 3,
    audio: 'Seit die Hauptstraße eine geschützte Radspur hat, ist der Radverkehr dort um vierzig Prozent gestiegen.',
    question: l('What happened after the protected bike lane was built?', 'Korumalı bisiklet şeridi yapıldıktan sonra ne oldu?', 'Was passierte?'),
    options: ['Cycling increased by 40 %.', 'Car traffic increased.', 'Nothing changed.'],
    answer: 0,
    explanation: l('um vierzig Prozent gestiegen.', 'um vierzig Prozent gestiegen.', '+40 %.'),
  },

  ...seDrills(),
]

export const UNIT_C1_20_STADTENTWICKLUNG: CourseUnit = {
  level: 'C1',
  number: 20,
  slug: 'stadtentwicklung',
  titleDe: 'Die Stadt der Zukunft',
  title: l('The city of the future', 'Geleceğin şehri', 'Die Stadt der Zukunft'),
  goal: l(
    'By the end of this unit you can discuss gentrification, housing and mobility, describe planning processes with the passive, express visions with Konjunktiv II and argue for citizen participation.',
    'Bu ünitenin sonunda soylulaştırma, konut ve ulaşımı tartışabilir, planlama süreçlerini edilgen yapıyla anlatabilir, vizyonları Konjunktiv II ile ifade edebilir ve vatandaş katılımını savunabilirsin.',
    'Am Ende dieser Einheit diskutierst du über die Stadt der Zukunft.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'gentrifizierung', label: l('Gentrification and housing', 'Soylulaştırma ve konut', 'Gentrifizierung und Wohnraum') },
    { key: 'mobilitaet', label: l('Mobility and liveable cities', 'Ulaşım ve yaşanabilir şehirler', 'Mobilität') },
    { key: 'beteiligung', label: l('Citizen participation', 'Vatandaş katılımı', 'Bürgerbeteiligung') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('How will we live tomorrow?', 'Yarın nasıl yaşayacağız?', 'Wie wohnen wir morgen?'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Passive in planning language', 'Planlama dilinde edilgen', 'Passiv in der Planungssprache'),
          body: l(
            'Planning texts focus on actions, not actors: Der Platz wird umgestaltet. With modal verbs: Der Nahverkehr soll ausgebaut werden / Die Bürger müssen beteiligt werden. State passive for results: Das Viertel ist saniert.',
            'Planlama metinleri eylemlere odaklanır, yapanlara değil: Der Platz wird umgestaltet. Kiplik fiillerle: Der Nahverkehr soll ausgebaut werden / Die Bürger müssen beteiligt werden. Sonuçlar için durum edilgeni: Das Viertel ist saniert.',
            'Passiv.'
          ),
          table: {
            head: [l('Active', 'Etken', 'Aktiv'), l('Passive', 'Edilgen', 'Passiv')],
            rows: [
              ['Die Stadt baut Radwege.', 'Radwege werden gebaut.'],
              ['Man soll den Nahverkehr ausbauen.', 'Der Nahverkehr soll ausgebaut werden.'],
              ['Investoren verdrängen Mieter.', 'Mieter werden verdrängt.'],
              ['Man hat die Bürger beteiligt.', 'Die Bürger wurden beteiligt.'],
            ],
          },
        },
        {
          title: l('Visions and alternatives', 'Vizyonlar ve alternatifler', 'Visionen und Alternativen'),
          body: l(
            'Visions with Konjunktiv II: Eine autofreie Innenstadt wäre lebenswerter. Es wäre denkbar, … zu … Alternatives with anstatt … zu / statt … zu: Anstatt Flächen zu versiegeln, sollte man nachverdichten.',
            'Konjunktiv II ile vizyonlar: Eine autofreie Innenstadt wäre lebenswerter. Es wäre denkbar, … zu … anstatt … zu / statt … zu ile alternatifler: Anstatt Flächen zu versiegeln, sollte man nachverdichten.',
            'Visionen.'
          ),
          examples: [
            { de: 'Mehr Grün **wäre** gut für das Klima.', translation: l('More green would be good for the climate.', 'Daha fazla yeşil iklim için iyi olurdu.', '') },
            { de: '**Anstatt** Parkplätze **zu** bauen, …', translation: l('Instead of building car parks, …', 'Otopark yapmak yerine …', '') },
          ],
        },
        {
          title: l('Gentrification', 'Soylulaştırma', 'Gentrifizierung'),
          body: l(
            'A cheap neighbourhood becomes trendy, investors renovate, rents rise and long-standing residents are pushed out (werden verdrängt). Instruments: Mietpreisbremse, Sozialwohnungsquote, Milieuschutz.',
            'Ucuz bir semt popüler olur, yatırımcılar yeniler, kiralar yükselir ve uzun süredir oturanlar yerinden edilir (werden verdrängt). Araçlar: Mietpreisbremse, sosyal konut kotası, Milieuschutz.',
            'Gentrifizierung.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A citizens’ meeting about a new housing project.', 'Yeni bir konut projesi hakkında vatandaş toplantısı.', 'Bürgerversammlung.'),
      dialogue: [
        { speaker: 'Stadträtin', de: 'Auf dem alten Bahngelände **sollen** 800 Wohnungen **gebaut werden**.', translation: l('800 flats are to be built on the old railway site.', 'Eski demiryolu arazisine 800 daire yapılması planlanıyor.', '') },
        { speaker: 'Anwohnerin', de: 'Und wie viele davon sind **bezahlbar**? Hier **werden** schon jetzt viele Familien **verdrängt**.', translation: l('And how many of them are affordable? Many families are already being pushed out here.', 'Peki kaçı uygun fiyatlı? Burada şimdiden birçok aile yerinden ediliyor.', '') },
        { speaker: 'Stadträtin', de: 'Ein Drittel wird als Sozialwohnungen vergeben. Außerdem wird der **Nahverkehr ausgebaut**.', translation: l('A third will be allocated as social housing. In addition, public transport will be expanded.', 'Üçte biri sosyal konut olarak verilecek. Ayrıca toplu taşıma genişletilecek.', '') },
        { speaker: 'Anwohner', de: 'Und die Grünflächen? **Anstatt** alles **zuzubauen**, brauchen wir auch einen Park.', translation: l('And the green spaces? Instead of building over everything, we also need a park.', 'Peki yeşil alanlar? Her yeri yapılaşmaya açmak yerine bir parka da ihtiyacımız var.', '') },
        { speaker: 'Stadträtin', de: 'Genau deshalb machen wir diese **Bürgerbeteiligung**. Ihre Vorschläge fließen in den Plan ein.', translation: l('That’s exactly why we are doing this citizen participation. Your proposals will be incorporated into the plan.', 'İşte tam bu yüzden bu vatandaş katılımını yapıyoruz. Önerileriniz plana dahil edilecek.', '') },
        { speaker: 'Anwohnerin', de: 'Ein Quartier mit Park und Straßenbahn **wäre** wirklich **lebenswert**.', translation: l('A neighbourhood with a park and a tram would be really liveable.', 'Parkı ve tramvayı olan bir mahalle gerçekten yaşanabilir olurdu.', '') },
      ],
      examples: [
        { de: 'Die Mieten **werden** in die Höhe **getrieben**.', translation: l('Rents are being driven up.', 'Kiralar yükseltiliyor.', '') },
        { de: 'Es fehlt **bezahlbarer Wohnraum**.', translation: l('There is a lack of affordable housing.', 'Uygun fiyatlı konut eksik.', '') },
        { de: 'Die Bürger **wurden beteiligt**.', translation: l('The citizens were involved.', 'Vatandaşlar sürece dahil edildi.', '') },
        { de: 'Die **Verkehrswende** braucht Radwege.', translation: l('The transport transition needs cycle paths.', 'Ulaşım dönüşümü bisiklet yollarına ihtiyaç duyar.', '') },
        { de: 'Eine autofreie Innenstadt **wäre** ruhiger.', translation: l('A car-free centre would be quieter.', 'Arabasız bir şehir merkezi daha sakin olurdu.', '') },
        { de: 'Anwohner wollen **mitbestimmen**.', translation: l('Residents want a say.', 'Bölge sakinleri söz sahibi olmak istiyor.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Terms and effects.', 'Terimler ve etkiler.', 'Begriffe und Folgen.'),
      exercises: ['match-begriffe', 'sort-folgen', 'se-verdraengt', 'se-wohnraum', 'se-ausgebaut', 'mc-beteiligung', 'tf-bremse', 'select-lebenswert', 'image-tram'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Plan and argue.', 'Planla ve tartış.', 'Planen und argumentieren.'),
      exercises: [
        'fill-beteiligt',
        'fill-anstatt',
        'fill-wende',
        'build-verdraengt',
        'build-waere',
        'build-mitbestimmen',
        'fix-wohnraum',
        'fix-ausgebaut',
        'fix-beteiligt',
        'tr-gentrifizierung',
        'tr-viertel',
        'ordering-viertel',
        'dialog-anwohner',
        'dialog-auto',
        'se-beteiligt',
        'se-anstatt',
        'se-waere',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A report from a changing neighbourhood.', 'Değişen bir semtten bir röportaj.', 'Reportage.'),
      passage: [
        '**Vom Arbeiterviertel zum Szenekiez** – Noch vor fünfzehn Jahren galt das Viertel als grau und günstig. Heute reihen sich hier Cafés, Galerien und Concept Stores aneinander.',
        'Die Kehrseite: In nur zehn Jahren haben sich die Mieten fast verdoppelt. Viele Häuser **wurden** von Investoren gekauft und luxussaniert.',
        'Frau Schulte wohnt seit 40 Jahren in derselben Wohnung. Nach der Sanierung soll ihre Miete um 60 Prozent steigen – nun muss sie ausziehen. „Ich **werde** aus meinem eigenen Viertel **verdrängt**“, sagt sie.',
        'Die Stadt hat reagiert: Bei Neubauten muss künftig ein Drittel als Sozialwohnungen vermietet werden. Kritiker halten das für zu spät.',
      ],
      glossary: [
        { de: 'der Kiez', note: l('neighbourhood (Berlin)', 'mahalle (Berlin)', 'Viertel') },
        { de: 'die Kehrseite', note: l('downside', 'madalyonun öbür yüzü', 'Nachteil') },
        { de: 'luxussanieren', note: l('to renovate into luxury flats', 'lüks olarak yenilemek', 'teuer renovieren') },
        { de: 'ausziehen', note: l('to move out', 'taşınmak (evden çıkmak)', 'die Wohnung verlassen') },
      ],
      exercises: ['read-thema', 'read-miete', 'read-frau', 'read-loesung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Urban projects from around Europe.', 'Avrupa’dan kentsel projeler.', 'Stadtprojekte.'),
      exercises: ['listen-paris', 'listen-dach', 'listen-buergerrat', 'listen-rad'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present your vision for your neighbourhood in 2040.', '2040’ta mahallen için vizyonunu sun.', 'Mein Viertel 2040.'),
      points: [
        l('Current problem: „Zurzeit fehlt …“', 'Mevcut sorun: „Zurzeit fehlt …“', 'Problem'),
        l('Vision: „… wäre …“', 'Vizyon: „… wäre …“', 'Vision'),
        l('Measures in the passive: „… sollte gebaut werden“', 'Edilgen önlemler: „… sollte gebaut werden“', 'Maßnahmen'),
        l('Participation: „Die Anwohner sollten …“', 'Katılım: „Die Anwohner sollten …“', 'Beteiligung'),
      ],
      model: [
        'Zurzeit fehlen in meinem Viertel bezahlbare Wohnungen und Grünflächen.',
        'Mein Viertel wäre 2040 autofrei und voller Bäume.',
        'Dafür sollten mehr Radwege gebaut und Parkplätze in Gärten umgewandelt werden.',
        'Vor allem aber sollten die Anwohner an allen Entscheidungen beteiligt werden.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a letter to the city council (at least 6 sentences) about a planned project in your neighbourhood. Describe the problem, make proposals and demand participation.',
        'Mahallendeki planlanan bir proje hakkında belediye meclisine bir mektup yaz (en az 6 cümle). Sorunu anlat, öneriler sun ve katılım talep et.',
        'Brief an den Stadtrat (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('A passive (wird / werden / soll … werden)', 'Bir edilgen (wird / werden / soll … werden)', 'Passiv'), pattern: '\\b(wird|werden|wurde|wurden)\\b[^.]*\\b(ge\\p{Ll}+t|ge\\p{Ll}+en|\\p{Ll}+iert|beteiligt|verdrängt|erhalten)\\b' },
        { label: l('A vision or proposal (wäre, sollte, könnte, anstatt … zu)', 'Bir vizyon ya da öneri (wäre, sollte, könnte, anstatt … zu)', 'Vorschlag'), pattern: '\\b(wäre|sollte|sollten|könnte|könnten|[Aa]nstatt|[Ss]tatt)\\b' },
        { label: l('Participation (beteiligt, mitbestimmen, Bürgerbeteiligung)', 'Katılım (beteiligt, mitbestimmen, Bürgerbeteiligung)', 'Beteiligung'), pattern: '(beteilig|mitbestimm|Bürgerbeteiligung|Mitsprache)' },
      ],
      model: [
        'Sehr geehrte Damen und Herren, mit Sorge habe ich erfahren, dass der Stadtpark bebaut werden soll.',
        'Der Park ist für viele Familien der einzige Ort zur Erholung.',
        'Natürlich wird dringend neuer Wohnraum gebraucht.',
        'Anstatt den Park zu opfern, sollten jedoch leer stehende Bürogebäude umgebaut werden.',
        'Außerdem wäre es wichtig, dass die Anwohner an der Planung beteiligt werden.',
        'Ich bitte Sie daher, eine Bürgerversammlung einzuberufen. Mit freundlichen Grüßen, Selin Aksoy',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Planning language – 60 seconds.', 'Planlama dili – 60 saniye.', 'Planungssprache – 60 Sekunden.'),
      seconds: 60,
      pool: [...SE.map(([id]) => `se-${id}`), 'mc-beteiligung'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Gentrification: Aufwertung, Verdrängung, Mietpreisbremse', 'Soylulaştırma: Aufwertung, Verdrängung, Mietpreisbremse', 'Gentrifizierung'),
      l('Passive with modals: soll ausgebaut werden', 'Kiplik fiillerle edilgen: soll ausgebaut werden', 'Passiv'),
      l('Visions: wäre lebenswerter; anstatt … zu', 'Vizyonlar: wäre lebenswerter; anstatt … zu', 'Visionen'),
      l('Participation: beteiligt werden, mitbestimmen', 'Katılım: beteiligt werden, mitbestimmen', 'Beteiligung'),
    ],
    mistakes: [
      { wrong: 'Das Radnetz soll ausbauen werden.', right: 'Das Radnetz soll ausgebaut werden.', note: l('Participle + werden.', 'Ortaç + werden.', 'Partizip.') },
      { wrong: 'Es fehlen viele Wohnraum.', right: 'Es fehlt viel Wohnraum.', note: l('Wohnraum is uncountable.', 'Wohnraum sayılamaz.', 'Singular.') },
      { wrong: 'Die Bürger wurden teilgenommen.', right: 'Die Bürger wurden beteiligt.', note: l('beteiligen in the passive.', 'Edilgende beteiligen.', 'beteiligt.') },
      { wrong: 'Anstatt Parkplätze bauen, …', right: 'Anstatt Parkplätze zu bauen, …', note: l('anstatt … zu.', 'anstatt … zu.', 'zu.') },
    ],
  },
}
