import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Stellung nehmen zu (+ Dat.)', emoji: '🗣️', translation: l('to take a position on', '… hakkında görüş bildirmek', 'seine Meinung sagen'), example: 'Ich möchte zu diesem Vorschlag Stellung nehmen.' },
  { word: 'Ich bin der festen Überzeugung, dass …', emoji: '💪', translation: l('I am firmly convinced that …', '… olduğuna kesinlikle inanıyorum', 'starke Meinung'), example: 'Ich bin der festen Überzeugung, dass Bildung kostenlos sein muss.' },
  { word: 'Befürworter wenden ein, …', emoji: '↩️', translation: l('supporters object that …', 'savunucular … diye itiraz ediyor', 'Gegenargument nennen'), example: 'Kritiker wenden ein, das sei zu teuer.' },
  { word: 'Dieses Argument greift zu kurz, …', emoji: '📏', translation: l('This argument falls short …', 'Bu argüman yetersiz kalıyor …', 'entkräften'), example: 'Dieses Argument greift jedoch zu kurz, denn …' },
  { word: 'entkräften', emoji: '🪫', translation: l('to refute, invalidate', 'çürütmek', 'widerlegen'), example: 'Dieses Gegenargument lässt sich leicht entkräften.' },
  { word: 'Zwar …, doch …', emoji: '⚖️', translation: l('Admittedly …, but …', 'Gerçi …, ama …', 'Zugeständnis + Widerspruch'), example: 'Zwar kostet das Geld, doch langfristig spart man.' },
  { word: 'Es liegt auf der Hand, dass …', emoji: '✋', translation: l('It is obvious that …', '… olduğu apaçık', 'offensichtlich'), example: 'Es liegt auf der Hand, dass wir handeln müssen.' },
  { word: 'nicht zuletzt', emoji: '🔚', translation: l('not least', 'son olarak ama önemli', 'auch wichtig'), example: 'Nicht zuletzt spielt auch die Gesundheit eine Rolle.' },
  { word: 'Aus diesen Gründen …', emoji: '🧾', translation: l('For these reasons …', 'Bu nedenlerle …', 'Schluss'), example: 'Aus diesen Gründen spreche ich mich für das Verbot aus.' },
  { word: 'sich für / gegen etwas aussprechen', emoji: '👍', translation: l('to speak out in favour of / against', '… lehine / aleyhine görüş bildirmek', 'dafür / dagegen sein'), example: 'Die Mehrheit spricht sich gegen die Reform aus.' },
  { word: 'überzeugend', emoji: '🎯', translation: l('convincing', 'ikna edici', 'glaubhaft'), example: 'Ihre Argumente sind überzeugend.' },
  { word: 'Dem kann ich nur bedingt zustimmen.', emoji: '🤏', translation: l('I can only partly agree with that.', 'Buna ancak kısmen katılabilirim.', 'teilweise zustimmen'), example: 'Dem kann ich nur bedingt zustimmen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Stellungnahme', gender: 'f', plural: 'die Stellungnahmen', translation: l('statement, position paper', 'görüş bildirisi', 'Stellungnahme') },
  { word: 'Gegenargument', gender: 'n', plural: 'die Gegenargumente', translation: l('counter-argument', 'karşı argüman', 'Gegenargument') },
  { word: 'Einwand', gender: 'm', plural: 'die Einwände', translation: l('objection', 'itiraz', 'Einwand') },
  { word: 'Überzeugung', gender: 'f', plural: 'die Überzeugungen', translation: l('conviction', 'kanaat', 'Überzeugung') },
  { word: 'Standpunkt', gender: 'm', plural: 'die Standpunkte', translation: l('point of view', 'bakış açısı', 'Standpunkt') },
  { word: 'Beleg', gender: 'm', plural: 'die Belege', translation: l('evidence, proof', 'kanıt', 'Beleg') },
  { word: 'Uniform', gender: 'f', plural: 'die Uniformen', translation: l('uniform', 'üniforma', 'Uniform') },
  { word: 'Leserbrief', gender: 'm', plural: 'die Leserbriefe', translation: l('letter to the editor', 'okur mektubu', 'Leserbrief') },
]

/** [id, sentence with gap, right, wrong] */
const SN: [string, string, string, [string, string]][] = [
  ['stellung', 'In meinem Beitrag möchte ich ___ der geplanten Schuluniform Stellung nehmen.', 'zu', ['über', 'für']],
  ['einwenden', 'Kritiker wenden ___, eine Uniform schränke die Individualität ein.', 'ein', ['an', 'aus']],
  ['greift', 'Dieses Argument ___ jedoch zu kurz, denn Individualität zeigt sich nicht nur in Kleidung.', 'greift', ['fasst', 'zieht']],
  ['doch', 'Zwar kostet eine Uniform zunächst Geld, ___ langfristig sparen Familien.', 'doch', ['denn', 'sondern']],
  ['aussprechen', 'Aus diesen Gründen spreche ich mich klar ___ eine Uniform aus.', 'für', ['zu', 'an']],
  ['hand', 'Es liegt auf der ___, dass teure Markenkleidung Druck erzeugt.', 'Hand', ['Linie', 'Seite']],
]

function snDrills(): Exercise[] {
  return SN.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `sn-${id}`,
      type: 'multiple_choice' as const,
      topic: 'position',
      concept: 'statement-phrases',
      skill: 'grammar' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Statement phrases: Stellung nehmen zu + dative, einwenden (separable: wenden ein), ein Argument greift zu kurz, zwar … doch / aber, sich für / gegen etwas aussprechen, es liegt auf der Hand.',
        'Görüş bildirme kalıpları: Stellung nehmen zu + Dativ, einwenden (ayrılabilir: wenden ein), ein Argument greift zu kurz, zwar … doch / aber, sich für / gegen etwas aussprechen, es liegt auf der Hand.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-funktion',
    type: 'matching',
    topic: 'position',
    concept: 'functions',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Match the phrase and its function in a statement.', 'İfadeyi görüş bildirisindeki işleviyle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Ich bin der festen Überzeugung, dass …', right: 'eigene Position' },
      { left: 'Kritiker wenden ein, …', right: 'Gegenposition nennen' },
      { left: 'Dieses Argument greift zu kurz, denn …', right: 'Gegenargument entkräften' },
      { left: 'Nicht zuletzt …', right: 'letztes Argument' },
      { left: 'Aus diesen Gründen …', right: 'Schlussfolgerung' },
    ],
    explanation: l('A statement moves from position to refutation to conclusion.', 'Görüş bildirisi görüşten çürütmeye ve sonuca ilerler.', 'Funktionen.'),
  },
  {
    id: 'sort-staerke',
    type: 'categorize',
    topic: 'position',
    concept: 'strength',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Strong or cautious opinion?', 'Güçlü mü temkinli mi görüş?', 'Stark oder vorsichtig?'),
    categories: ['stark 💪', 'vorsichtig 🤏'],
    items: [
      { text: 'Ich bin der festen Überzeugung, dass …', category: 0 },
      { text: 'Ich würde eher sagen, dass …', category: 1 },
      { text: 'Es liegt auf der Hand, dass …', category: 0 },
      { text: 'Dem kann ich nur bedingt zustimmen.', category: 1 },
      { text: 'Zweifellos …', category: 0 },
      { text: 'Möglicherweise …', category: 1 },
    ],
    explanation: l('Choose the strength of your wording consciously.', 'İfadenin gücünü bilinçli seç.', 'Stärke.'),
    practice: ['sn-hand'],
  },
  {
    id: 'mc-entkraeften',
    type: 'multiple_choice',
    topic: 'entkraeften',
    concept: 'refute',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Einwand: „Ein Tempolimit schränkt die Freiheit ein.“ Welche Antwort entkräftet ihn am besten?',
    options: ['Dieses Argument greift zu kurz: Auch Ampeln schränken Freiheit ein – zum Schutz aller.', 'Das ist falsch.', 'Freiheit ist mir egal.'],
    answer: 0,
    explanation: l('Refute with a reason and an analogy.', 'Gerekçe ve benzetmeyle çürüt.', 'entkräften.'),
    practice: ['fill-zwar'],
  },
  {
    id: 'tf-gegen',
    type: 'true_false',
    topic: 'entkraeften',
    concept: 'counter',
    skill: 'reading',
    difficulty: 2,
    statement: 'Eine überzeugende Stellungnahme ignoriert Gegenargumente.',
    answer: false,
    explanation: l('Naming and refuting counter-arguments makes you more convincing.', 'Karşı argümanları anmak ve çürütmek seni daha ikna edici yapar.', 'falsch.'),
  },
  {
    id: 'select-schluss',
    type: 'multiple_select',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Which sentences make a convincing conclusion? Select all.', 'Hangi cümleler ikna edici bir sonuç oluşturur? Hepsini seç.', 'Überzeugender Schluss?'),
    options: ['Aus diesen Gründen spreche ich mich klar für das Verbot aus.', 'Na ja, mal sehen.', 'Alles in allem überwiegen die Vorteile deutlich.', 'Es ist deshalb höchste Zeit zu handeln.', 'Ich weiß nicht so recht.'],
    answers: [0, 2, 3],
    explanation: l('A clear position plus a call to action.', 'Net bir görüş artı eyleme çağrı.', 'Schluss.'),
  },
  {
    id: 'image-position',
    type: 'image_choice',
    topic: 'position',
    concept: 'position',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Stellung beziehen',
    options: [
      { emoji: '🙋', label: 'sich positionieren' },
      { emoji: '🙈', label: 'wegschauen' },
      { emoji: '🤷', label: 'unentschlossen' },
      { emoji: '😴', label: 'schlafen' },
    ],
    answer: 0,
    explanation: l('Stellung beziehen = to take a stand.', 'Stellung beziehen = tavır almak.', 'Position.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-zwar',
    type: 'fill_blank',
    topic: 'entkraeften',
    concept: 'concession',
    skill: 'grammar',
    difficulty: 3,
    sentence: '___ ist der Umbau teuer, doch er zahlt sich in wenigen Jahren aus.',
    accepted: ['Zwar'],
    base: '…, doch …',
    explanation: l('Zwar …, doch … = concede, then counter.', 'Zwar …, doch … = kabul et, sonra itiraz et.', 'Zwar.'),
    examples: ['**Zwar** ist der Umbau teuer, **doch** …'],
  },
  {
    id: 'fill-ueberzeugung',
    type: 'fill_blank',
    topic: 'position',
    concept: 'own-position',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Ich bin der festen ___, dass jedes Kind ein Recht auf einen Kitaplatz hat.',
    accepted: ['Überzeugung', 'Ueberzeugung', 'Meinung', 'Ansicht'],
    base: 'starke Meinung',
    explanation: l('der festen Überzeugung sein (genitive).', 'der festen Überzeugung sein (Genitiv).', 'Überzeugung.'),
    examples: ['Ich bin der festen **Überzeugung**, dass …'],
  },
  {
    id: 'fill-zuletzt',
    type: 'fill_blank',
    topic: 'schluss',
    concept: 'last-argument',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Nicht ___ spielt auch der Umweltschutz eine wichtige Rolle.',
    accepted: ['zuletzt'],
    base: 'auch wichtig',
    explanation: l('nicht zuletzt = not least.', 'nicht zuletzt = son ama önemli olarak.', 'zuletzt.'),
    examples: ['**Nicht zuletzt** spielt auch …'],
  },
  {
    id: 'build-einwand',
    type: 'sentence_builder',
    topic: 'entkraeften',
    concept: 'counter',
    skill: 'writing',
    difficulty: 3,
    chips: ['eine solche Regel', 'Gegner wenden ein,', 'sei kaum kontrollierbar'],
    answers: [['Gegner wenden ein,', 'eine solche Regel', 'sei kaum kontrollierbar']],
    translation: l('Opponents object that such a rule would hardly be controllable.', 'Karşı çıkanlar böyle bir kuralın neredeyse denetlenemez olduğunu ileri sürüyor.', 'Gegner wenden ein, eine solche Regel sei kaum kontrollierbar.'),
    explanation: l('Report the objection with Konjunktiv I (sei).', 'İtirazı Konjunktiv I ile aktar (sei).', 'Konjunktiv I.'),
    examples: ['Gegner **wenden ein**, eine solche Regel **sei** kaum kontrollierbar.'],
  },
  {
    id: 'build-kurz',
    type: 'sentence_builder',
    topic: 'entkraeften',
    concept: 'refute',
    skill: 'writing',
    difficulty: 3,
    chips: ['greift jedoch', 'Dieses Argument', 'zu kurz'],
    answers: [['Dieses Argument', 'greift jedoch', 'zu kurz']],
    translation: l('However, this argument falls short.', 'Ancak bu argüman yetersiz kalıyor.', 'Dieses Argument greift jedoch zu kurz.'),
    explanation: l('zu kurz greifen = to fall short.', 'zu kurz greifen = yetersiz kalmak.', 'entkräften.'),
    examples: ['Dieses Argument **greift** jedoch **zu kurz**.'],
  },
  {
    id: 'build-gruende',
    type: 'sentence_builder',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'writing',
    difficulty: 3,
    chips: ['spreche ich mich', 'Aus diesen Gründen', 'gegen den Vorschlag aus'],
    answers: [['Aus diesen Gründen', 'spreche ich mich', 'gegen den Vorschlag aus']],
    translation: l('For these reasons I speak out against the proposal.', 'Bu nedenlerle öneriye karşı olduğumu belirtiyorum.', 'Aus diesen Gründen spreche ich mich gegen den Vorschlag aus.'),
    explanation: l('sich gegen etwas aussprechen – „aus“ at the end.', 'sich gegen etwas aussprechen – „aus“ sonda.', 'aussprechen.'),
    examples: ['Aus diesen Gründen **spreche** ich mich gegen den Vorschlag **aus**.'],
  },
  {
    id: 'fix-stellung',
    type: 'error_correction',
    topic: 'position',
    concept: 'own-position',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich möchte über das Thema Stellung nehmen.',
    accepted: ['Ich möchte zu dem Thema Stellung nehmen.', 'Ich möchte zum Thema Stellung nehmen.'],
    explanation: l('Stellung nehmen zu + dative.', 'Stellung nehmen zu + Dativ.', 'zu.'),
    examples: ['Ich möchte **zum** Thema Stellung nehmen.'],
  },
  {
    id: 'fix-zwar',
    type: 'error_correction',
    topic: 'entkraeften',
    concept: 'concession',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Zwar das Projekt ist teuer, doch es lohnt sich.',
    accepted: ['Zwar ist das Projekt teuer, doch es lohnt sich.', 'Das Projekt ist zwar teuer, doch es lohnt sich.'],
    explanation: l('Zwar in position 1 → verb next.', 'Zwar 1. konumda → ardından fiil.', 'Inversion.'),
    examples: ['**Zwar ist** das Projekt teuer, …'],
  },
  {
    id: 'fix-aussprechen',
    type: 'error_correction',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich spreche mich für ein Verbot.',
    accepted: ['Ich spreche mich für ein Verbot aus.'],
    explanation: l('sich aussprechen – don’t forget „aus“.', 'sich aussprechen – „aus“ unutma.', 'aus.'),
    examples: ['Ich spreche mich für ein Verbot **aus**.'],
  },
  {
    id: 'tr-hand',
    type: 'translation',
    topic: 'position',
    concept: 'own-position',
    skill: 'writing',
    difficulty: 3,
    source: l('It is obvious that we need more teachers.', 'Daha fazla öğretmene ihtiyacımız olduğu apaçık.', 'It is obvious that we need more teachers.'),
    accepted: ['Es liegt auf der Hand, dass wir mehr Lehrkräfte brauchen.', 'Es liegt auf der Hand, dass wir mehr Lehrer brauchen.', 'Es liegt auf der Hand, dass wir mehr Lehrerinnen und Lehrer brauchen.'],
    explanation: l('Es liegt auf der Hand, dass …', 'Es liegt auf der Hand, dass …', 'auf der Hand.'),
    examples: ['**Es liegt auf der Hand**, dass wir mehr Lehrkräfte brauchen.'],
  },
  {
    id: 'tr-bedingt',
    type: 'translation',
    topic: 'entkraeften',
    concept: 'partial',
    skill: 'writing',
    difficulty: 3,
    source: l('I can only partly agree with that.', 'Buna ancak kısmen katılabilirim.', 'I can only partly agree with that.'),
    accepted: ['Dem kann ich nur bedingt zustimmen.', 'Dem kann ich nur teilweise zustimmen.', 'Ich kann dem nur bedingt zustimmen.'],
    explanation: l('nur bedingt zustimmen (+ dative: dem).', 'nur bedingt zustimmen (+ Dativ: dem).', 'bedingt.'),
    examples: ['**Dem** kann ich nur **bedingt** zustimmen.'],
  },
  {
    id: 'ordering-stellungnahme',
    type: 'ordering',
    topic: 'schluss',
    concept: 'structure',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order the statement.', 'Görüş bildirisini sırala.', 'Ordne die Stellungnahme.'),
    items: ['Kritiker wenden ein, Uniformen schränkten die Individualität ein.', 'Ich spreche mich für Schuluniformen aus, weil sie Mobbing wegen Kleidung verringern.', 'Aus diesen Gründen sollten Schulen Uniformen zumindest testen.', 'Dieses Argument greift jedoch zu kurz, denn Persönlichkeit zeigt sich nicht in Markenkleidung.'],
    answer: ['Ich spreche mich für Schuluniformen aus, weil sie Mobbing wegen Kleidung verringern.', 'Kritiker wenden ein, Uniformen schränkten die Individualität ein.', 'Dieses Argument greift jedoch zu kurz, denn Persönlichkeit zeigt sich nicht in Markenkleidung.', 'Aus diesen Gründen sollten Schulen Uniformen zumindest testen.'],
    explanation: l('Position → counter-argument → refutation → conclusion.', 'Görüş → karşı argüman → çürütme → sonuç.', 'Aufbau.'),
  },
  {
    id: 'dialog-einwand',
    type: 'dialogue',
    topic: 'entkraeften',
    concept: 'refute',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Diskussionspartnerin', de: 'Ein Rauchverbot auf Spielplätzen ist doch Bevormundung!' }],
    options: ['Das sehe ich anders. Zwar schränkt es Raucher ein, doch der Schutz der Kinder wiegt schwerer.', 'Nein.', 'Rauchen ist Bevormundung ja.'],
    answer: 0,
    explanation: l('Disagree, concede, then outweigh.', 'Karşı çık, kabul et, sonra ağır bas.', 'entkräften.'),
  },
  {
    id: 'dialog-bedingt',
    type: 'dialogue',
    topic: 'position',
    concept: 'partial',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Kollege', de: 'Homeoffice sollte für alle verpflichtend werden.' }],
    options: ['Dem kann ich nur bedingt zustimmen – für viele Berufe ist das schlicht nicht möglich.', 'Ich stimme bedingt nur dem.', 'Absolut, Ärzte und Bäcker auch.'],
    answer: 0,
    explanation: l('Partial agreement with a reason.', 'Gerekçeli kısmi onay.', 'bedingt.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-leserbrief',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wozu nimmt die Verfasserin Stellung?',
    options: ['zum geplanten Handyverbot an Schulen', 'zu neuen Busfahrplänen', 'zu höheren Steuern'],
    answer: 0,
    explanation: l('„… zum geplanten Handyverbot …“', '„… zum geplanten Handyverbot …“', 'Handyverbot.'),
  },
  {
    id: 'read-position',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-leserbrief',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Welche Position vertritt sie?',
    options: ['Sie ist für das Verbot.', 'Sie ist gegen das Verbot.', 'Sie ist unentschieden.'],
    answer: 0,
    explanation: l('„… spreche ich mich klar für das Verbot aus.“', '„… spreche ich mich klar für das Verbot aus.“', 'dafür.'),
  },
  {
    id: 'read-einwand',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-leserbrief',
    skill: 'reading',
    difficulty: 3,
    statement: 'Die Verfasserin geht auf das Gegenargument der Erreichbarkeit im Notfall ein.',
    answer: true,
    explanation: l('„Kritiker wenden ein, Eltern müssten ihre Kinder im Notfall erreichen können.“', '„Kritiker wenden ein, Eltern müssten ihre Kinder im Notfall erreichen können.“', 'richtig.'),
  },
  {
    id: 'read-entkraeften',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-leserbrief',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wie entkräftet sie dieses Gegenargument?',
    options: ['Im Notfall kann man das Sekretariat anrufen.', 'Notfälle gibt es nicht.', 'Eltern brauchen ihre Kinder nicht zu erreichen.'],
    answer: 0,
    explanation: l('„… dafür gibt es das Schulsekretariat.“', '„… dafür gibt es das Schulsekretariat.“', 'Sekretariat.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-position',
    type: 'listening_choice',
    topic: 'position',
    concept: 'own-position',
    skill: 'listening',
    difficulty: 3,
    audio: 'Ich bin der festen Überzeugung, dass ein kostenloser Nahverkehr mehr Menschen zum Umsteigen bewegen würde.',
    question: l('What is the speaker’s position?', 'Konuşanın görüşü nedir?', 'Position?'),
    options: ['for free public transport', 'against public transport', 'undecided'],
    answer: 0,
    explanation: l('der festen Überzeugung = firmly convinced.', 'der festen Überzeugung = kesinlikle inanmak.', 'dafür.'),
  },
  {
    id: 'listen-gegen',
    type: 'listening_choice',
    topic: 'entkraeften',
    concept: 'counter',
    skill: 'listening',
    difficulty: 3,
    audio: 'Gegner wenden ein, das sei unbezahlbar. Doch schon heute zahlen wir Milliarden für Staus und Luftverschmutzung.',
    question: l('How does the speaker respond to the objection?', 'Konuşan itiraza nasıl cevap veriyor?', 'Wie reagiert die Person?'),
    options: ['by pointing to the costs of the status quo', 'by agreeing completely', 'by changing the topic'],
    answer: 0,
    explanation: l('Refutes the cost objection with other costs.', 'Maliyet itirazını başka maliyetlerle çürütüyor.', 'entkräften.'),
  },
  {
    id: 'listen-schluss',
    type: 'listening_choice',
    topic: 'schluss',
    concept: 'conclusion',
    skill: 'listening',
    difficulty: 3,
    audio: 'Aus all diesen Gründen appelliere ich an den Stadtrat, den Vorschlag noch in diesem Jahr umzusetzen.',
    question: l('What does the speaker want?', 'Konuşan ne istiyor?', 'Was will die Person?'),
    options: ['the proposal to be implemented this year', 'more time to think', 'the proposal to be rejected'],
    answer: 0,
    explanation: l('An appeal at the end: umsetzen.', 'Sonda bir çağrı: umsetzen.', 'Appell.'),
  },
  {
    id: 'listen-zwar',
    type: 'listening_choice',
    topic: 'entkraeften',
    concept: 'concession',
    skill: 'listening',
    difficulty: 3,
    audio: 'Zwar wäre eine Zuckersteuer für viele Hersteller unangenehm, doch die Folgekosten von Übergewicht sind weitaus höher.',
    question: l('What does the speaker think about a sugar tax?', 'Konuşan şeker vergisi hakkında ne düşünüyor?', 'Meinung zur Zuckersteuer?'),
    options: ['in favour, despite drawbacks for manufacturers', 'against it', 'it makes no difference'],
    answer: 0,
    explanation: l('zwar … doch → concession, then the stronger argument.', 'zwar … doch → kabul, sonra daha güçlü argüman.', 'dafür.'),
  },

  ...snDrills(),
]

export const UNIT_C1_22_STELLUNGNAHME: CourseUnit = {
  level: 'C1',
  number: 22,
  slug: 'stellungnahme',
  titleDe: 'Eine Stellungnahme schreiben',
  title: l('Writing a statement', 'Görüş bildirisi yazmak', 'Eine Stellungnahme schreiben'),
  goal: l(
    'By the end of this unit you can write a convincing statement on a controversial issue: take a clear position, name and refute counter-arguments (Kritiker wenden ein …, Dieses Argument greift zu kurz …) and close persuasively (Aus diesen Gründen spreche ich mich … aus).',
    'Bu ünitenin sonunda tartışmalı bir konuda ikna edici bir görüş bildirisi yazabilirsin: net bir tavır alır, karşı argümanları anar ve çürütür (Kritiker wenden ein …, Dieses Argument greift zu kurz …) ve ikna edici bir şekilde bitirirsin (Aus diesen Gründen spreche ich mich … aus).',
    'Am Ende dieser Einheit schreibst du überzeugende Stellungnahmen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'position', label: l('Taking a position', 'Tavır almak', 'Position beziehen') },
    { key: 'entkraeften', label: l('Refuting counter-arguments', 'Karşı argümanları çürütmek', 'Gegenpositionen entkräften') },
    { key: 'schluss', label: l('Concluding convincingly', 'İkna edici biçimde bitirmek', 'Überzeugend schließen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Exam task: take a stand.', 'Sınav görevi: tavır al.', 'Prüfungsaufgabe: Stellung nehmen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Structure of a statement', 'Görüş bildirisinin yapısı', 'Aufbau einer Stellungnahme'),
          body: l(
            'Introduction: topic and your position (Ich möchte zu … Stellung nehmen. Ich spreche mich für / gegen … aus.). Main part: two or three arguments with evidence, then a counter-argument and its refutation. Conclusion: summarise your position and make a demand or appeal.',
            'Giriş: konu ve görüşün (Ich möchte zu … Stellung nehmen. Ich spreche mich für / gegen … aus.). Ana bölüm: kanıtlı iki ya da üç argüman, sonra bir karşı argüman ve çürütülmesi. Sonuç: görüşünü özetle ve bir talep ya da çağrıda bulun.',
            'Aufbau.'
          ),
          table: {
            head: [l('Step', 'Adım', 'Schritt'), l('Phrase', 'İfade', 'Wendung')],
            rows: [
              ['Position', 'Ich bin der festen Überzeugung, dass …'],
              ['Argument', 'Erstens … / Hinzu kommt, dass … / Nicht zuletzt …'],
              ['Gegenargument', 'Kritiker wenden ein, … sei …'],
              ['Entkräften', 'Dieses Argument greift jedoch zu kurz, denn …'],
              ['Schluss', 'Aus diesen Gründen spreche ich mich … aus.'],
            ],
          },
        },
        {
          title: l('Refuting counter-arguments', 'Karşı argümanları çürütmek', 'Gegenargumente entkräften'),
          body: l(
            'First report the counter-argument fairly (often in Konjunktiv I: Kritiker wenden ein, das sei zu teuer). Then weaken it: Zwar …, doch … / Dieses Argument greift zu kurz, denn … / Dem lässt sich entgegenhalten, dass …',
            'Önce karşı argümanı adil biçimde aktar (çoğu zaman Konjunktiv I ile: Kritiker wenden ein, das sei zu teuer). Sonra zayıflat: Zwar …, doch … / Dieses Argument greift zu kurz, denn … / Dem lässt sich entgegenhalten, dass …',
            'entkräften.'
          ),
          examples: [
            { de: 'Kritiker **wenden ein**, das **sei** zu teuer.', translation: l('Critics object that it is too expensive.', 'Eleştirmenler bunun çok pahalı olduğunu ileri sürüyor.', '') },
            { de: '**Zwar** kostet es Geld, **doch** es spart langfristig.', translation: l('Admittedly it costs money, but it saves in the long run.', 'Gerçi para tutuyor ama uzun vadede tasarruf sağlıyor.', '') },
          ],
        },
        {
          title: l('Strength of wording', 'İfadenin gücü', 'Stärke der Formulierung'),
          body: l(
            'Strong: Ich bin der festen Überzeugung …, Es liegt auf der Hand …, zweifellos. Cautious: Ich würde eher sagen …, Dem kann ich nur bedingt zustimmen, möglicherweise. Combine both: strong for your main point, cautious for concessions.',
            'Güçlü: Ich bin der festen Überzeugung …, Es liegt auf der Hand …, zweifellos. Temkinli: Ich würde eher sagen …, Dem kann ich nur bedingt zustimmen, möglicherweise. İkisini birleştir: ana noktan için güçlü, kabuller için temkinli.',
            'Stärke.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A school parliament debates school uniforms.', 'Bir okul meclisi okul üniformalarını tartışıyor.', 'Schülerparlament.'),
      dialogue: [
        { speaker: 'Vorsitzende', de: 'Wer möchte zum Antrag „Schuluniform“ **Stellung nehmen**?', translation: l('Who would like to comment on the motion „school uniform“?', '„Okul üniforması“ önergesi hakkında kim görüş bildirmek ister?', '') },
        { speaker: 'Aylin', de: 'Ich. **Ich bin der festen Überzeugung**, dass Uniformen den Druck durch Markenkleidung verringern.', translation: l('Me. I am firmly convinced that uniforms reduce the pressure of brand-name clothes.', 'Ben. Üniformaların markalı giysi baskısını azalttığına kesinlikle inanıyorum.', '') },
        { speaker: 'Tom', de: 'Aber dann sehen doch alle gleich aus! Wo bleibt die Individualität?', translation: l('But then everyone looks the same! What about individuality?', 'Ama o zaman herkes aynı görünür! Bireysellik ne olacak?', '') },
        { speaker: 'Aylin', de: '**Zwar** sehen alle ähnlich aus, **doch** Persönlichkeit zeigt sich in Ideen, nicht im Pullover. **Dieses Argument greift** also **zu kurz**.', translation: l('Admittedly everyone looks similar, but personality shows in ideas, not in a jumper. So that argument falls short.', 'Gerçi herkes benzer görünür ama kişilik süveterde değil fikirlerde görünür. Yani bu argüman yetersiz kalıyor.', '') },
        { speaker: 'Tom', de: '**Dem kann ich nur bedingt zustimmen**. Kleidung ist für viele ein Ausdruck ihrer Identität.', translation: l('I can only partly agree with that. For many, clothing is an expression of their identity.', 'Buna ancak kısmen katılabilirim. Birçokları için giyim kimliğin bir ifadesidir.', '') },
        { speaker: 'Aylin', de: '**Aus diesen Gründen** schlage ich eine Testphase vor – **nicht zuletzt**, um Erfahrungen zu sammeln.', translation: l('For these reasons I propose a trial phase – not least to gain experience.', 'Bu nedenlerle bir deneme dönemi öneriyorum – özellikle deneyim kazanmak için.', '') },
      ],
      examples: [
        { de: 'Ich möchte **zu** dem Vorschlag **Stellung nehmen**.', translation: l('I would like to comment on the proposal.', 'Öneri hakkında görüş bildirmek istiyorum.', '') },
        { de: 'Gegner **wenden ein**, …', translation: l('Opponents object that …', 'Karşı çıkanlar … diye itiraz ediyor.', '') },
        { de: '**Es liegt auf der Hand**, dass …', translation: l('It is obvious that …', '… olduğu apaçık.', '') },
        { de: 'Dieses Argument lässt sich **entkräften**.', translation: l('This argument can be refuted.', 'Bu argüman çürütülebilir.', '') },
        { de: 'Ich **spreche** mich **dagegen aus**.', translation: l('I speak out against it.', 'Buna karşı olduğumu belirtiyorum.', '') },
        { de: 'Ihre Argumente sind **überzeugend**.', translation: l('Your arguments are convincing.', 'Argümanlarınız ikna edici.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('The building blocks of a statement.', 'Görüş bildirisinin yapı taşları.', 'Bausteine.'),
      exercises: ['match-funktion', 'sort-staerke', 'sn-stellung', 'sn-einwenden', 'sn-greift', 'mc-entkraeften', 'tf-gegen', 'select-schluss', 'image-position'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Argue, refute, conclude.', 'Tartış, çürüt, bitir.', 'Argumentieren.'),
      exercises: [
        'fill-zwar',
        'fill-ueberzeugung',
        'fill-zuletzt',
        'build-einwand',
        'build-kurz',
        'build-gruende',
        'fix-stellung',
        'fix-zwar',
        'fix-aussprechen',
        'tr-hand',
        'tr-bedingt',
        'ordering-stellungnahme',
        'dialog-einwand',
        'dialog-bedingt',
        'sn-doch',
        'sn-aussprechen',
        'sn-hand',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A model letter to the editor.', 'Örnek bir okur mektubu.', 'Ein Leserbrief.'),
      passage: [
        '**Leserbrief** – Zu Ihrem Artikel über das geplante Handyverbot an Schulen möchte ich Stellung nehmen. Als Lehrerin spreche ich mich klar für das Verbot aus.',
        'Erstens können sich Schülerinnen und Schüler ohne Smartphone deutlich besser konzentrieren. Hinzu kommt, dass in den Pausen wieder mehr miteinander gesprochen wird.',
        'Kritiker wenden ein, Eltern müssten ihre Kinder im Notfall erreichen können. Dieses Argument greift jedoch zu kurz, denn dafür gibt es das Schulsekretariat.',
        'Nicht zuletzt schützt ein Verbot vor Cybermobbing während des Unterrichts. Aus diesen Gründen appelliere ich an alle Schulen, das Verbot konsequent umzusetzen.',
      ],
      glossary: [
        { de: 'hinzu kommt, dass', note: l('in addition', 'buna ek olarak', 'außerdem') },
        { de: 'das Sekretariat', note: l('school office', 'okul sekreterliği', 'Büro') },
        { de: 'appellieren an', note: l('to appeal to', '… -e çağrıda bulunmak', 'auffordern') },
        { de: 'konsequent', note: l('consistently', 'tutarlı biçimde', 'ohne Ausnahme') },
      ],
      exercises: ['read-thema', 'read-position', 'read-einwand', 'read-entkraeften'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Statements in a public debate.', 'Kamusal bir tartışmada görüşler.', 'Stellungnahmen hören.'),
      exercises: ['listen-position', 'listen-gegen', 'listen-schluss', 'listen-zwar'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Take a stand on: „Sollte das Wahlalter auf 16 gesenkt werden?“', 'Şu konuda tavır al: „Sollte das Wahlalter auf 16 gesenkt werden?“', 'Wahlalter 16?'),
      points: [
        l('Your position: „Ich spreche mich … aus.“', 'Görüşün: „Ich spreche mich … aus.“', 'Position'),
        l('Two arguments', 'İki argüman', 'Argumente'),
        l('Counter-argument and refutation', 'Karşı argüman ve çürütme', 'Entkräften'),
        l('Conclusion: „Aus diesen Gründen …“', 'Sonuç: „Aus diesen Gründen …“', 'Schluss'),
      ],
      model: [
        'Ich spreche mich klar für ein Wahlalter von 16 Jahren aus.',
        'Jugendliche sind von politischen Entscheidungen wie dem Klimaschutz besonders lange betroffen.',
        'Kritiker wenden ein, sie seien noch nicht reif genug – dieses Argument greift jedoch zu kurz, denn Reife ist keine Frage des Alters.',
        'Aus diesen Gründen sollte das Wahlalter bundesweit gesenkt werden.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a statement (at least 6 sentences) on the topic „Sollten Plastikverpackungen in Supermärkten verboten werden?“ Take a position, refute one counter-argument and conclude convincingly.',
        '„Sollten Plastikverpackungen in Supermärkten verboten werden?“ konusunda bir görüş bildirisi yaz (en az 6 cümle). Tavır al, bir karşı argümanı çürüt ve ikna edici bir şekilde bitir.',
        'Stellungnahme (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('Your position (Überzeugung, spreche mich … aus, Stellung)', 'Görüşün (Überzeugung, spreche mich … aus, Stellung)', 'Position'), pattern: '(Überzeugung|spreche[^.]*\\baus\\b|Stellung)' },
        { label: l('A counter-argument and refutation (wenden ein, greift zu kurz, zwar … doch)', 'Bir karşı argüman ve çürütme (wenden ein, greift zu kurz, zwar … doch)', 'Entkräften'), pattern: '(wenden ein|zu kurz|\\b[Zz]war\\b[^.]*\\b(doch|aber)\\b|entgegenhalten)' },
        { label: l('A conclusion (aus diesen Gründen, deshalb, alles in allem)', 'Bir sonuç (aus diesen Gründen, deshalb, alles in allem)', 'Schluss'), pattern: '([Aa]us diesen Gründen|[Dd]eshalb|[Aa]lles in allem|[Aa]bschließend)' },
      ],
      model: [
        'Zur Frage, ob Plastikverpackungen in Supermärkten verboten werden sollten, möchte ich Stellung nehmen.',
        'Ich bin der festen Überzeugung, dass ein solches Verbot längst überfällig ist.',
        'Jedes Jahr landen Millionen Tonnen Plastik in den Meeren und gefährden Tiere und Menschen.',
        'Kritiker wenden ein, ohne Verpackung würden Lebensmittel schneller verderben.',
        'Zwar ist das bei manchen Produkten richtig, doch es gibt längst umweltfreundliche Alternativen.',
        'Aus diesen Gründen spreche ich mich klar für ein Verbot aus.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Statement phrases – 60 seconds.', 'Görüş kalıpları – 60 saniye.', 'Wendungen – 60 Sekunden.'),
      seconds: 60,
      pool: [...SN.map(([id]) => `sn-${id}`), 'mc-entkraeften'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Structure: position – arguments – counter-argument – refutation – conclusion', 'Yapı: görüş – argümanlar – karşı argüman – çürütme – sonuç', 'Aufbau'),
      l('Position: Ich bin der festen Überzeugung …; sich für / gegen … aussprechen', 'Görüş: Ich bin der festen Überzeugung …; sich für / gegen … aussprechen', 'Position'),
      l('Refuting: Kritiker wenden ein …; greift zu kurz; zwar … doch', 'Çürütme: Kritiker wenden ein …; greift zu kurz; zwar … doch', 'Entkräften'),
      l('Strength: es liegt auf der Hand vs. nur bedingt zustimmen', 'Güç: es liegt auf der Hand ve nur bedingt zustimmen', 'Stärke'),
    ],
    mistakes: [
      { wrong: 'Stellung nehmen über das Thema', right: 'Stellung nehmen zum Thema', note: l('zu + dative.', 'zu + Dativ.', 'zu.') },
      { wrong: 'Zwar das ist teuer, …', right: 'Zwar ist das teuer, …', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Inversion.') },
      { wrong: 'Ich spreche mich für ein Verbot.', right: 'Ich spreche mich für ein Verbot aus.', note: l('aussprechen – „aus“ at the end.', 'aussprechen – „aus“ sonda.', 'aus.') },
      { wrong: 'Kritiker wenden an, …', right: 'Kritiker wenden ein, …', note: l('einwenden.', 'einwenden.', 'ein.') },
    ],
  },
}
