import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'kriegen → erhalten', emoji: '📬', translation: l('to get → to receive', 'almak → teslim almak', 'umgangssprachlich → gehoben'), example: 'Ich hab deine Mail gekriegt. / Ich habe Ihre E-Mail erhalten.' },
  { word: 'kapieren → verstehen', emoji: '💡', translation: l('to get it → to understand', 'çakmak → anlamak', 'umgangssprachlich → neutral'), example: 'Kapierst du das? / Verstehen Sie das?' },
  { word: 'abhauen → sich entfernen', emoji: '🏃', translation: l('to clear off → to leave', 'tüymek → uzaklaşmak', 'umgangssprachlich → gehoben'), example: 'Der Dieb ist abgehauen. / Der Täter entfernte sich.' },
  { word: 'die Kohle → das Geld → die finanziellen Mittel', emoji: '💶', translation: l('dough → money → financial means', 'mangır → para → mali kaynaklar', 'drei Stilebenen'), example: 'Uns fehlen die finanziellen Mittel.' },
  { word: 'die Bude → die Wohnung → die Unterkunft', emoji: '🏠', translation: l('pad → flat → accommodation', 'ev (argo) → daire → konaklama', 'drei Stilebenen'), example: 'Eine Unterkunft wird gestellt.' },
  { word: 'quatschen → sich unterhalten', emoji: '💬', translation: l('to chat (colloquial) → to talk', 'gevezelik etmek → sohbet etmek', 'umgangssprachlich → neutral'), example: 'Wir haben stundenlang gequatscht.' },
  { word: 'bekommen → erhalten', emoji: '📨', translation: l('to get → to receive (formal)', 'almak → almak (resmî)', 'neutral → gehoben'), example: 'Sie erhalten die Unterlagen per Post.' },
  { word: 'Bescheid geben → mitteilen', emoji: '📢', translation: l('to let know → to inform', 'haber vermek → bildirmek', 'neutral → gehoben'), example: 'Bitte teilen Sie uns mit, ob Sie teilnehmen.' },
  { word: 'Ich hätte gern …', emoji: '🙏', translation: l('I would like …', '… isterdim', 'höflich'), example: 'Ich hätte gern eine Auskunft.' },
  { word: 'Wären Sie so freundlich, …?', emoji: '🎩', translation: l('Would you be so kind as to …?', '… lütfeder misiniz?', 'sehr höflich'), example: 'Wären Sie so freundlich, mir das Formular zu schicken?' },
  { word: 'angemessen', emoji: '⚖️', translation: l('appropriate', 'uygun', 'passend'), example: 'Der Ton war der Situation nicht angemessen.' },
  { word: 'salopp', emoji: '😎', translation: l('casual, sloppy (style)', 'laubali', 'sehr locker'), example: 'Der Ausdruck ist zu salopp für einen Brief.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Stilebene', gender: 'f', plural: 'die Stilebenen', translation: l('register, level of style', 'üslup düzeyi', 'Stilebene') },
  { word: 'Umgangssprache', gender: 'f', translation: l('colloquial language', 'günlük dil', 'Umgangssprache') },
  { word: 'Standardsprache', gender: 'f', translation: l('standard language', 'standart dil', 'Standardsprache') },
  { word: 'Ausdruck', gender: 'm', plural: 'die Ausdrücke', translation: l('expression', 'ifade', 'Ausdruck') },
  { word: 'Anrede', gender: 'f', plural: 'die Anreden', translation: l('form of address', 'hitap', 'Anrede') },
  { word: 'Unterkunft', gender: 'f', plural: 'die Unterkünfte', translation: l('accommodation', 'konaklama yeri', 'Unterkunft') },
  { word: 'Mittel', gender: 'n', plural: 'die Mittel', translation: l('means, funds', 'araç, kaynak', 'Mittel') },
  { word: 'Höflichkeit', gender: 'f', translation: l('politeness', 'nezaket', 'Höflichkeit') },
]

/** [id, sentence with gap (formal context), right, wrong] */
const ST: [string, string, string, [string, string]][] = [
  ['erhalten', 'Sehr geehrte Frau Weber, wir haben Ihre Bewerbung ___.', 'erhalten', ['gekriegt', 'abgekriegt']],
  ['mitteilen', 'Bitte ___ Sie uns bis Freitag mit, ob Sie an der Sitzung teilnehmen.', 'teilen', ['sagen', 'quatschen']],
  ['mittel', 'Leider fehlen der Stadt die finanziellen ___ für das Projekt.', 'Mittel', ['Kohlen', 'Kröten']],
  ['unterkunft', 'Für alle Teilnehmenden wird eine ___ gestellt.', 'Unterkunft', ['Bude', 'Penne']],
  ['verstehen', 'Wir hoffen, Sie ___ unsere Entscheidung.', 'verstehen', ['kapieren', 'checken']],
  ['entfernen', 'Der Täter konnte sich unerkannt vom Tatort ___.', 'entfernen', ['abhauen', 'verduften']],
]

function stDrills(): Exercise[] {
  return ST.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `st-${id}`,
      type: 'multiple_choice' as const,
      topic: 'stilebenen',
      concept: 'formal-word',
      skill: 'vocabulary' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'In formal texts use the neutral or elevated word. Colloquial words like kriegen, kapieren, abhauen, Kohle, Bude, checken do not fit official letters or reports.',
        'Resmî metinlerde nötr ya da yüksek üsluplu kelimeyi kullan. kriegen, kapieren, abhauen, Kohle, Bude, checken gibi günlük kelimeler resmî mektuplara ya da raporlara uymaz.',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-paare',
    type: 'matching',
    topic: 'synonyme',
    concept: 'pairs',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Match the colloquial word and its neutral equivalent.', 'Günlük kelimeyi nötr karşılığıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'kriegen', right: 'bekommen' },
      { left: 'kapieren', right: 'verstehen' },
      { left: 'quatschen', right: 'sich unterhalten' },
      { left: 'die Kohle', right: 'das Geld' },
      { left: 'die Bude', right: 'die Wohnung' },
    ],
    explanation: l('Same meaning, different register.', 'Aynı anlam, farklı üslup.', 'Synonyme.'),
  },
  {
    id: 'sort-ebene',
    type: 'categorize',
    topic: 'stilebenen',
    concept: 'classify',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Colloquial or elevated?', 'Günlük mü yüksek üslup mu?', 'Umgangssprachlich oder gehoben?'),
    categories: ['umgangssprachlich 😎', 'gehoben 🎩'],
    items: [
      { text: 'abhauen', category: 0 },
      { text: 'sich entfernen', category: 1 },
      { text: 'checken', category: 0 },
      { text: 'mitteilen', category: 1 },
      { text: 'die Kohle', category: 0 },
      { text: 'die finanziellen Mittel', category: 1 },
    ],
    explanation: l('Colloquial = friends, chats. Elevated = letters, reports, speeches.', 'Günlük = arkadaşlar, sohbet. Yüksek = mektup, rapor, konuşma.', 'Stilebenen.'),
    practice: ['st-entfernen'],
  },
  {
    id: 'mc-situation',
    type: 'multiple_choice',
    topic: 'angemessen',
    concept: 'situation',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Sie schreiben an die Personalabteilung. Welcher Satz passt?',
    options: ['Ich möchte Ihnen mitteilen, dass ich am Montag verhindert bin.', 'Ich kann am Montag leider nicht, sorry!', 'Montag klappt bei mir nicht, Leute.'],
    answer: 0,
    explanation: l('A formal letter needs a formal register: mitteilen, verhindert sein.', 'Resmî bir mektup resmî üslup ister: mitteilen, verhindert sein.', 'formell.'),
    practice: ['fill-mitteilen'],
  },
  {
    id: 'tf-locker',
    type: 'true_false',
    topic: 'angemessen',
    concept: 'situation',
    skill: 'reading',
    difficulty: 2,
    statement: 'In einer WhatsApp-Nachricht an einen guten Freund klingt „Sehr geehrter Herr Müller“ angemessen.',
    answer: false,
    explanation: l('Too formal for a friend – it sounds cold or ironic.', 'Bir arkadaş için fazla resmî – soğuk ya da alaycı gelir.', 'unpassend.'),
  },
  {
    id: 'select-formell',
    type: 'multiple_select',
    topic: 'angemessen',
    concept: 'polite',
    skill: 'vocabulary',
    difficulty: 3,
    promptL10n: l('Which phrases fit a formal email? Select all.', 'Hangi ifadeler resmî bir e-postaya uyar? Hepsini seç.', 'Was passt in eine formelle E-Mail?'),
    options: ['Wären Sie so freundlich, mir das Formular zu senden?', 'Schick mal das Formular rüber.', 'Ich wäre Ihnen dankbar, wenn …', 'Mit freundlichen Grüßen', 'Hau rein!'],
    answers: [0, 2, 3],
    explanation: l('Konjunktiv II and fixed formal phrases sound polite.', 'Konjunktiv II ve kalıplaşmış resmî ifadeler kibar durur.', 'formell.'),
  },
  {
    id: 'image-anzug',
    type: 'image_choice',
    topic: 'stilebenen',
    concept: 'formal',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'gehobener Stil',
    options: [
      { emoji: '🎩', label: 'gehoben' },
      { emoji: '🧢', label: 'locker' },
      { emoji: '🩳', label: 'salopp' },
      { emoji: '🛹', label: 'jugendlich' },
    ],
    answer: 0,
    explanation: l('gehoben = elevated, formal.', 'gehoben = yüksek, resmî üslup.', 'gehoben.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-mitteilen',
    type: 'fill_blank',
    topic: 'synonyme',
    concept: 'formal-word',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Hiermit möchten wir Ihnen ___, dass Ihr Antrag genehmigt wurde.',
    accepted: ['mitteilen'],
    base: 'Bescheid geben (formell)',
    explanation: l('Bescheid geben → mitteilen in formal letters.', 'Bescheid geben → resmî mektuplarda mitteilen.', 'mitteilen.'),
    examples: ['… möchten wir Ihnen **mitteilen**, dass …'],
  },
  {
    id: 'fill-erhalten',
    type: 'fill_blank',
    topic: 'synonyme',
    concept: 'formal-word',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Sie ___ die Unterlagen in den nächsten Tagen per Post.',
    accepted: ['erhalten', 'bekommen'],
    base: 'kriegen (formell)',
    explanation: l('kriegen → bekommen / erhalten.', 'kriegen → bekommen / erhalten.', 'erhalten.'),
    examples: ['Sie **erhalten** die Unterlagen …'],
  },
  {
    id: 'fill-waeren',
    type: 'fill_blank',
    topic: 'angemessen',
    concept: 'polite',
    skill: 'grammar',
    difficulty: 3,
    sentence: '___ Sie so freundlich, mir die Rechnung noch einmal zu schicken?',
    accepted: ['Wären', 'Waeren'],
    base: 'sein, Konjunktiv II',
    explanation: l('Very polite request: Wären Sie so freundlich, … zu …?', 'Çok kibar rica: Wären Sie so freundlich, … zu …?', 'Wären.'),
    examples: ['**Wären** Sie so freundlich, …?'],
  },
  {
    id: 'build-dankbar',
    type: 'sentence_builder',
    topic: 'angemessen',
    concept: 'polite',
    skill: 'writing',
    difficulty: 3,
    chips: ['wenn Sie mir', 'Ich wäre Ihnen', 'antworten könnten', 'dankbar,', 'bald'],
    answers: [['Ich wäre Ihnen', 'dankbar,', 'wenn Sie mir', 'bald', 'antworten könnten']],
    translation: l('I would be grateful if you could answer me soon.', 'Bana yakında cevap verebilirseniz minnettar olurum.', 'Ich wäre Ihnen dankbar, wenn Sie mir bald antworten könnten.'),
    explanation: l('Konjunktiv II makes requests polite.', 'Konjunktiv II ricaları kibar yapar.', 'höflich.'),
    examples: ['Ich **wäre** Ihnen dankbar, wenn Sie mir bald antworten **könnten**.'],
  },
  {
    id: 'build-mittel',
    type: 'sentence_builder',
    topic: 'synonyme',
    concept: 'formal-word',
    skill: 'writing',
    difficulty: 3,
    chips: ['nicht', 'Uns stehen', 'zur Verfügung', 'ausreichend finanzielle Mittel'],
    answers: [['Uns stehen', 'nicht', 'ausreichend finanzielle Mittel', 'zur Verfügung']],
    translation: l('We don’t have sufficient financial means available.', 'Elimizde yeterli mali kaynak yok.', 'Uns stehen nicht ausreichend finanzielle Mittel zur Verfügung.'),
    explanation: l('Formal version of „Wir haben nicht genug Kohle“.', '„Wir haben nicht genug Kohle“ cümlesinin resmî hâli.', 'formell.'),
    examples: ['Uns stehen nicht ausreichend **finanzielle Mittel** zur Verfügung.'],
  },
  {
    id: 'build-locker',
    type: 'sentence_builder',
    topic: 'stilebenen',
    concept: 'informal',
    skill: 'speaking',
    difficulty: 2,
    chips: ['echt', 'Hast du', 'gekriegt', 'meine Nachricht'],
    answers: [['Hast du', 'meine Nachricht', 'echt', 'gekriegt'], ['Hast du', 'echt', 'meine Nachricht', 'gekriegt']],
    translation: l('Did you really get my message?', 'Mesajımı gerçekten aldın mı?', 'Hast du meine Nachricht echt gekriegt?'),
    explanation: l('Among friends, kriegen and echt are fine.', 'Arkadaşlar arasında kriegen ve echt uygundur.', 'locker.'),
    examples: ['Hast du meine Nachricht echt **gekriegt**?'],
  },
  {
    id: 'fix-kohle',
    type: 'error_correction',
    topic: 'synonyme',
    concept: 'formal-word',
    skill: 'writing',
    difficulty: 3,
    sentence: 'Sehr geehrte Damen und Herren, leider fehlt uns die Kohle für das Projekt.',
    accepted: ['Sehr geehrte Damen und Herren, leider fehlt uns das Geld für das Projekt.', 'Sehr geehrte Damen und Herren, leider fehlen uns die finanziellen Mittel für das Projekt.', 'Sehr geehrte Damen und Herren, leider fehlen uns die Mittel für das Projekt.'],
    explanation: l('Kohle is colloquial → das Geld / die finanziellen Mittel.', 'Kohle günlük dildir → das Geld / die finanziellen Mittel.', 'Mittel.'),
    examples: ['… fehlen uns **die finanziellen Mittel** …'],
  },
  {
    id: 'fix-kapiert',
    type: 'error_correction',
    topic: 'synonyme',
    concept: 'formal-word',
    skill: 'writing',
    difficulty: 3,
    sentence: 'Sehr geehrter Herr Doktor, ich habe Ihre Erklärung leider nicht kapiert.',
    accepted: ['Sehr geehrter Herr Doktor, ich habe Ihre Erklärung leider nicht verstanden.'],
    explanation: l('kapieren → verstehen.', 'kapieren → verstehen.', 'verstanden.'),
    examples: ['… leider nicht **verstanden**.'],
  },
  {
    id: 'fix-gruss',
    type: 'error_correction',
    topic: 'angemessen',
    concept: 'closing',
    skill: 'writing',
    difficulty: 2,
    sentence: 'Wir bitten um Rückmeldung bis Freitag. Hau rein!',
    accepted: ['Wir bitten um Rückmeldung bis Freitag. Mit freundlichen Grüßen', 'Wir bitten um Rückmeldung bis Freitag. Mit freundlichen Grüßen!', 'Wir bitten um Rückmeldung bis Freitag. Freundliche Grüße'],
    explanation: l('Formal closing: Mit freundlichen Grüßen.', 'Resmî kapanış: Mit freundlichen Grüßen.', 'Gruß.'),
    examples: ['**Mit freundlichen Grüßen**'],
  },
  {
    id: 'tr-auskunft',
    type: 'translation',
    topic: 'angemessen',
    concept: 'polite',
    skill: 'writing',
    difficulty: 3,
    source: l('Would you be so kind as to send me the form?', 'Bana formu gönderme nezaketini gösterir misiniz?', 'Would you be so kind as to send me the form?'),
    accepted: ['Wären Sie so freundlich, mir das Formular zu schicken?', 'Wären Sie so freundlich, mir das Formular zu senden?', 'Wären Sie so nett, mir das Formular zu schicken?'],
    explanation: l('Wären Sie so freundlich, … zu + infinitive?', 'Wären Sie so freundlich, … zu + mastar?', 'höflich.'),
    examples: ['**Wären Sie so freundlich**, mir das Formular **zu schicken**?'],
  },
  {
    id: 'tr-abgehauen',
    type: 'translation',
    topic: 'stilebenen',
    concept: 'informal',
    skill: 'writing',
    difficulty: 3,
    source: l('After the party we cleared off quickly. (colloquial)', 'Partiden sonra hemen tüydük. (günlük dil)', 'After the party we cleared off quickly. (colloquial)'),
    accepted: ['Nach der Party sind wir schnell abgehauen.', 'Nach der Party sind wir sofort abgehauen.', 'Wir sind nach der Party schnell abgehauen.'],
    explanation: l('abhauen = colloquial for to leave; perfect with sein.', 'abhauen = gitmek için günlük kelime; Perfekt sein ile.', 'abgehauen.'),
    examples: ['Nach der Party **sind** wir schnell **abgehauen**.'],
  },
  {
    id: 'ordering-brief',
    type: 'ordering',
    topic: 'angemessen',
    concept: 'letter',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order the formal email.', 'Resmî e-postayı sırala.', 'Ordne die E-Mail.'),
    items: ['Mit freundlichen Grüßen, Aylin Demir', 'Sehr geehrte Frau Schulz,', 'Ich wäre Ihnen dankbar, wenn Sie mir die Unterlagen bis Freitag zusenden könnten.', 'vielen Dank für Ihre schnelle Rückmeldung.'],
    answer: ['Sehr geehrte Frau Schulz,', 'vielen Dank für Ihre schnelle Rückmeldung.', 'Ich wäre Ihnen dankbar, wenn Sie mir die Unterlagen bis Freitag zusenden könnten.', 'Mit freundlichen Grüßen, Aylin Demir'],
    explanation: l('Salutation → thanks → request → closing.', 'Hitap → teşekkür → rica → kapanış.', 'Aufbau.'),
  },
  {
    id: 'dialog-chef',
    type: 'dialogue',
    topic: 'angemessen',
    concept: 'situation',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Abteilungsleiterin', de: 'Frau Yılmaz, haben Sie meine Nachricht zum neuen Projekt erhalten?' }],
    options: ['Ja, vielen Dank. Ich habe sie gestern erhalten und schon gelesen.', 'Jo, hab ich gekriegt, passt schon.', 'Klar, Alter, hab ich gecheckt.'],
    answer: 0,
    explanation: l('Answer your boss in the standard/formal register.', 'Yöneticine standart/resmî üslupla cevap ver.', 'angemessen.'),
  },
  {
    id: 'dialog-freund',
    type: 'dialogue',
    topic: 'stilebenen',
    concept: 'informal',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Mitbewohner', de: 'Kommst du heute Abend mit ins Kino?' }],
    options: ['Klar, bin dabei! Wann geht’s los?', 'Hiermit teile ich Ihnen mit, dass ich teilnehme.', 'Sehr geehrter Mitbewohner, ich sage zu.'],
    answer: 0,
    explanation: l('With friends, a relaxed tone is natural.', 'Arkadaşlarla rahat bir ton doğaldır.', 'locker.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-stil',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Text?',
    options: ['Darum, dass man je nach Situation unterschiedlich spricht.', 'Um die Geschichte der deutschen Rechtschreibung.', 'Um Fehler in Fremdsprachen.'],
    answer: 0,
    explanation: l('„Niemand spricht immer gleich.“', '„Niemand spricht immer gleich.“', 'Situation.'),
  },
  {
    id: 'read-ebenen',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-stil',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Wie viele Stilebenen unterscheidet der Text grob?',
    options: ['drei', 'zwei', 'fünf'],
    answer: 0,
    explanation: l('Umgangssprache, Standardsprache, gehobene Sprache.', 'Umgangssprache, Standardsprache, gehobene Sprache.', 'drei.'),
  },
  {
    id: 'read-fehler',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-stil',
    skill: 'reading',
    difficulty: 3,
    statement: 'Laut Text ist zu förmliche Sprache unter Freunden immer höflich.',
    answer: false,
    explanation: l('„… wirkt unter Freunden schnell steif oder sogar ironisch.“', '„… wirkt unter Freunden schnell steif oder sogar ironisch.“', 'falsch.'),
  },
  {
    id: 'read-tipp',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-stil',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was empfiehlt der Text Lernenden?',
    options: ['Bei Unsicherheit die Standardsprache wählen.', 'Immer Umgangssprache benutzen.', 'Nur gehobene Sprache sprechen.'],
    answer: 0,
    explanation: l('„Wer unsicher ist, liegt mit der Standardsprache fast immer richtig.“', '„Wer unsicher ist, liegt mit der Standardsprache fast immer richtig.“', 'Standard.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-ansage',
    type: 'listening_choice',
    topic: 'stilebenen',
    concept: 'identify',
    skill: 'listening',
    difficulty: 2,
    audio: 'Sehr geehrte Fahrgäste, aufgrund einer Störung verzögert sich die Weiterfahrt um wenige Minuten.',
    question: l('Which register is this?', 'Bu hangi üslup?', 'Welche Stilebene?'),
    options: ['formal', 'colloquial', 'youth language'],
    answer: 0,
    explanation: l('Sehr geehrte Fahrgäste, aufgrund, sich verzögern → formal.', 'Sehr geehrte Fahrgäste, aufgrund, sich verzögern → resmî.', 'formell.'),
  },
  {
    id: 'listen-kumpel',
    type: 'listening_choice',
    topic: 'stilebenen',
    concept: 'identify',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ey, ich hab null Kohle mehr. Kannst du mir bis Montag zwanzig Euro leihen?',
    question: l('What does the speaker want?', 'Konuşan ne istiyor?', 'Was will die Person?'),
    options: ['to borrow money', 'to buy coal', 'to go out on Monday'],
    answer: 0,
    explanation: l('Kohle = money (colloquial).', 'Kohle = para (günlük dil).', 'Geld.'),
  },
  {
    id: 'listen-hoeflich',
    type: 'listening_choice',
    topic: 'angemessen',
    concept: 'polite',
    skill: 'listening',
    difficulty: 3,
    audio: 'Wären Sie so freundlich, das Fenster zu schließen? Es zieht ein wenig.',
    question: l('What is the speaker doing?', 'Konuşan ne yapıyor?', 'Was macht die Person?'),
    options: ['politely asking to close the window', 'complaining about noise', 'opening the window'],
    answer: 0,
    explanation: l('Wären Sie so freundlich … = a very polite request.', 'Wären Sie so freundlich … = çok kibar bir rica.', 'Bitte.'),
  },
  {
    id: 'listen-bude',
    type: 'listening_choice',
    topic: 'synonyme',
    concept: 'meaning',
    skill: 'listening',
    difficulty: 3,
    audio: 'Meine neue Bude ist zwar klein, aber total gemütlich und direkt im Zentrum.',
    question: l('What is the speaker talking about?', 'Konuşan neden bahsediyor?', 'Worüber spricht die Person?'),
    options: ['their new flat', 'a new shop', 'a market stall'],
    answer: 0,
    explanation: l('Bude = flat, room (colloquial).', 'Bude = ev, oda (günlük dil).', 'Wohnung.'),
  },

  ...stDrills(),
]

export const UNIT_C1_10_REGISTER_STIL: CourseUnit = {
  level: 'C1',
  number: 10,
  slug: 'register-stil',
  titleDe: 'Umgangssprache, Standard, gehoben',
  title: l('Colloquial, standard, elevated', 'Günlük, standart, yüksek üslup', 'Umgangssprache, Standard, gehoben'),
  goal: l(
    'By the end of this unit you can tell the three registers apart (kriegen – bekommen – erhalten), replace colloquial words with formal ones and choose the right tone for emails, conversations and official letters.',
    'Bu ünitenin sonunda üç üslup düzeyini ayırt edebilir (kriegen – bekommen – erhalten), günlük kelimeleri resmî olanlarla değiştirebilir ve e-postalar, konuşmalar ve resmî mektuplar için doğru tonu seçebilirsin.',
    'Am Ende dieser Einheit wählst du die passende Stilebene.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'stilebenen', label: l('The three registers', 'Üç üslup düzeyi', 'Stilebenen') },
    { key: 'synonyme', label: l('Synonyms in different registers', 'Farklı üsluplarda eş anlamlılar', 'Synonyme') },
    { key: 'angemessen', label: l('Appropriate wording', 'Uygun ifade', 'Angemessen formulieren') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('One meaning, three ways to say it.', 'Tek anlam, üç söyleyiş.', 'Eine Bedeutung, drei Stile.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Three registers', 'Üç üslup düzeyi', 'Drei Stilebenen'),
          body: l(
            'Colloquial (Umgangssprache): friends, family, chats. Standard (Standardsprache): work, shops, most situations. Elevated (gehoben): official letters, reports, speeches, literature.',
            'Günlük (Umgangssprache): arkadaşlar, aile, sohbetler. Standart (Standardsprache): iş, mağazalar, çoğu durum. Yüksek (gehoben): resmî mektuplar, raporlar, konuşmalar, edebiyat.',
            'Stilebenen.'
          ),
          table: {
            head: [l('Colloquial', 'Günlük', 'umgangssprachlich'), l('Standard', 'Standart', 'Standard'), l('Elevated', 'Yüksek', 'gehoben')],
            rows: [
              ['kriegen', 'bekommen', 'erhalten'],
              ['kapieren', 'verstehen', 'nachvollziehen'],
              ['abhauen', 'weggehen', 'sich entfernen'],
              ['die Kohle', 'das Geld', 'die finanziellen Mittel'],
              ['die Bude', 'die Wohnung', 'die Unterkunft'],
            ],
          },
        },
        {
          title: l('Polite formulas', 'Kibarlık kalıpları', 'Höflichkeitsformeln'),
          body: l(
            'Formal requests use Konjunktiv II and fixed phrases: Ich hätte gern …, Könnten Sie …?, Wären Sie so freundlich, … zu …?, Ich wäre Ihnen dankbar, wenn …',
            'Resmî ricalar Konjunktiv II ve kalıplar kullanır: Ich hätte gern …, Könnten Sie …?, Wären Sie so freundlich, … zu …?, Ich wäre Ihnen dankbar, wenn …',
            'Höflichkeit.'
          ),
          examples: [
            { de: '**Wären Sie so freundlich**, mir zu helfen?', translation: l('Would you be so kind as to help me?', 'Bana yardım etme nezaketini gösterir misiniz?', '') },
            { de: '**Ich wäre Ihnen dankbar, wenn** Sie bald antworten könnten.', translation: l('I would be grateful if you could answer soon.', 'Yakında cevap verebilirseniz minnettar olurum.', '') },
          ],
        },
        {
          title: l('Too formal is also wrong', 'Fazla resmî olmak da yanlış', 'Zu förmlich ist auch falsch'),
          body: l(
            'The right register depends on the situation. Elevated language among friends sounds stiff or ironic. If you are unsure, choose standard language – it is almost always acceptable.',
            'Doğru üslup duruma bağlıdır. Arkadaşlar arasında yüksek üslup katı ya da alaycı gelir. Emin değilsen standart dili seç – neredeyse her zaman uygundur.',
            'angemessen.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Emre tells his colleague about a phone call – then writes the official email.', 'Emre iş arkadaşına bir telefon görüşmesini anlatıyor – sonra resmî e-postayı yazıyor.', 'Zwei Versionen.'),
      dialogue: [
        { speaker: 'Emre', de: 'Stell dir vor, der Vermieter will **mehr Kohle** für die **Bude**!', translation: l('Imagine, the landlord wants more money for the flat!', 'Düşünsene, ev sahibi ev için daha fazla para istiyor!', '') },
        { speaker: 'Nina', de: 'Echt? Und hast du **kapiert**, warum?', translation: l('Really? And did you get why?', 'Gerçekten mi? Peki nedenini anladın mı?', '') },
        { speaker: 'Emre', de: 'Nicht wirklich. Ich schreib ihm jetzt eine Mail.', translation: l('Not really. I’m writing him an email now.', 'Pek değil. Şimdi ona bir e-posta yazıyorum.', '') },
        { speaker: 'Nina', de: 'Aber bitte nicht so! Schreib lieber: „Ich habe Ihr Schreiben **erhalten**, kann die Erhöhung jedoch **nicht nachvollziehen**.“', translation: l('But not like that, please! Better write: „I have received your letter, but I cannot understand the increase.“', 'Ama lütfen böyle değil! Şöyle yaz: „Mektubunuzu aldım, ancak artışı anlayamıyorum.“', '') },
        { speaker: 'Emre', de: 'Und am Ende: „**Ich wäre Ihnen dankbar, wenn** Sie mir die Gründe **mitteilen** könnten.“', translation: l('And at the end: „I would be grateful if you could tell me the reasons.“', 'Ve sonunda: „Gerekçeleri bana bildirebilirseniz minnettar olurum.“', '') },
        { speaker: 'Nina', de: 'Perfekt. Das klingt **angemessen**.', translation: l('Perfect. That sounds appropriate.', 'Mükemmel. Bu uygun görünüyor.', '') },
      ],
      examples: [
        { de: 'Ich hab’s **gekriegt**. → Ich habe es **erhalten**.', translation: l('I got it. → I have received it.', 'Aldım. → Teslim aldım.', '') },
        { de: '**Kapierst** du das? → **Verstehen** Sie das?', translation: l('Get it? → Do you understand?', 'Çaktın mı? → Anlıyor musunuz?', '') },
        { de: 'Er ist **abgehauen**. → Er hat sich **entfernt**.', translation: l('He cleared off. → He left.', 'Tüydü. → Uzaklaştı.', '') },
        { de: 'Wir haben keine **Kohle**. → Uns fehlen die **Mittel**.', translation: l('We have no dough. → We lack the funds.', 'Mangır yok. → Kaynağımız yok.', '') },
        { de: '**Gib mir Bescheid.** → Bitte **teilen Sie mir mit**, …', translation: l('Let me know. → Please inform me …', 'Haber ver. → Lütfen bana bildirin …', '') },
        { de: '**Hau rein!** → **Mit freundlichen Grüßen**', translation: l('See ya! → Kind regards', 'Hadi eyvallah! → Saygılarımla', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which register is it?', 'Hangi üslup?', 'Welche Stilebene?'),
      exercises: ['match-paare', 'sort-ebene', 'st-erhalten', 'st-mitteilen', 'st-mittel', 'mc-situation', 'tf-locker', 'select-formell', 'image-anzug'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Switch between registers.', 'Üsluplar arasında geçiş yap.', 'Stil wechseln.'),
      exercises: [
        'fill-mitteilen',
        'fill-erhalten',
        'fill-waeren',
        'build-dankbar',
        'build-mittel',
        'build-locker',
        'fix-kohle',
        'fix-kapiert',
        'fix-gruss',
        'tr-auskunft',
        'tr-abgehauen',
        'ordering-brief',
        'dialog-chef',
        'dialog-freund',
        'st-unterkunft',
        'st-verstehen',
        'st-entfernen',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A magazine column about style.', 'Üslup hakkında bir dergi köşe yazısı.', 'Eine Kolumne über Stil.'),
      passage: [
        '**Der richtige Ton** – Niemand spricht immer gleich. Mit Freunden reden wir anders als mit der Chefin, und ein Brief ans Amt klingt anders als eine Nachricht an die Familie.',
        'Grob unterscheidet man drei Stilebenen: die **Umgangssprache**, die **Standardsprache** und die **gehobene Sprache**. Wer „Kohle“ sagt, meint Geld – im Geschäftsbrief spricht man jedoch von „finanziellen Mitteln“.',
        'Fehler passieren in beide Richtungen: Umgangssprache im Bewerbungsschreiben wirkt respektlos. Zu förmliche Sprache **hingegen** wirkt unter Freunden schnell steif oder sogar ironisch.',
        'Für Lernende gilt eine einfache Regel: Wer unsicher ist, liegt mit der Standardsprache fast immer richtig.',
      ],
      glossary: [
        { de: 'das Amt', note: l('public authority', 'resmî daire', 'Behörde') },
        { de: 'respektlos', note: l('disrespectful', 'saygısız', 'ohne Respekt') },
        { de: 'steif', note: l('stiff', 'katı, resmî', 'nicht locker') },
        { de: 'richtig liegen', note: l('to be right', 'haklı olmak', 'recht haben') },
      ],
      exercises: ['read-thema', 'read-ebenen', 'read-fehler', 'read-tipp'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('From announcements to chats with friends.', 'Anonslardan arkadaş sohbetlerine.', 'Stilebenen hören.'),
      exercises: ['listen-ansage', 'listen-kumpel', 'listen-hoeflich', 'listen-bude'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Tell the same news twice: once to a friend, once to your boss – you can’t come to work tomorrow.', 'Aynı haberi iki kez anlat: bir kez bir arkadaşa, bir kez yöneticine – yarın işe gelemiyorsun.', 'Zwei Versionen.'),
      points: [
        l('To a friend: relaxed and short', 'Arkadaşa: rahat ve kısa', 'locker'),
        l('To your boss: polite form of address', 'Yöneticine: kibar hitap', 'Anrede'),
        l('Give a reason in both versions', 'İki versiyonda da sebep belirt', 'Grund'),
        l('Formal: offer a solution with Konjunktiv II', 'Resmî: Konjunktiv II ile çözüm öner', 'Lösung'),
      ],
      model: [
        'An Tom: Du, ich kann morgen nicht, mich hat’s voll erwischt – Grippe.',
        'An die Chefin: Guten Tag, Frau Berger, leider bin ich morgen krankheitsbedingt verhindert.',
        'Ich habe mir bereits einen Arzttermin geben lassen.',
        'Wenn es Ihnen recht ist, könnte ich die dringenden Aufgaben von zu Hause erledigen.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Rewrite this note as a formal email to the landlord (at least 6 sentences): „Hey, die Heizung in meiner Bude ist schon wieder kaputt. Mach das bitte schnell, sonst hau ich ab!“',
        'Bu notu ev sahibine resmî bir e-posta olarak yeniden yaz (en az 6 cümle): „Hey, die Heizung in meiner Bude ist schon wieder kaputt. Mach das bitte schnell, sonst hau ich ab!“',
        'Formelle E-Mail (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('A formal salutation (Sehr geehrte/r …)', 'Resmî bir hitap (Sehr geehrte/r …)', 'Anrede'), pattern: 'Sehr geehrte' },
        { label: l('A polite request (Konjunktiv II: wäre, könnten, würde)', 'Kibar bir rica (Konjunktiv II: wäre, könnten, würde)', 'Bitte'), pattern: '\\b(wäre|wären|könnten|würde|würden|hätte)\\b' },
        { label: l('A formal closing (Mit freundlichen Grüßen)', 'Resmî bir kapanış (Mit freundlichen Grüßen)', 'Gruß'), pattern: '(Mit freundlichen Grüßen|Freundliche Grüße)' },
      ],
      model: [
        'Sehr geehrter Herr Lang, leider muss ich Ihnen mitteilen, dass die Heizung in meiner Wohnung erneut ausgefallen ist.',
        'Das Problem besteht seit Montag.',
        'Bereits im letzten Monat musste die Heizung repariert werden.',
        'Da es inzwischen sehr kalt ist, ist die Situation kaum noch zumutbar.',
        'Ich wäre Ihnen daher dankbar, wenn Sie umgehend einen Techniker beauftragen könnten.',
        'Für Rückfragen stehe ich Ihnen gern zur Verfügung. Mit freundlichen Grüßen, Mehmet Kaya',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Choose the formal word – 60 seconds.', 'Resmî kelimeyi seç – 60 saniye.', 'Formelles Wort – 60 Sekunden.'),
      seconds: 60,
      pool: [...ST.map(([id]) => `st-${id}`), 'mc-situation'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Three registers: colloquial – standard – elevated', 'Üç üslup: günlük – standart – yüksek', 'Stilebenen'),
      l('kriegen → bekommen → erhalten; Kohle → Geld → Mittel', 'kriegen → bekommen → erhalten; Kohle → Geld → Mittel', 'Synonyme'),
      l('Polite requests with Konjunktiv II: Wären Sie so freundlich …?', 'Konjunktiv II ile kibar ricalar: Wären Sie so freundlich …?', 'Höflichkeit'),
      l('When unsure, use standard language', 'Emin değilsen standart dili kullan', 'Standard'),
    ],
    mistakes: [
      { wrong: 'Sehr geehrte Frau Weber, ich hab Ihre Mail gekriegt.', right: 'Sehr geehrte Frau Weber, ich habe Ihre E-Mail erhalten.', note: l('Formal letter → erhalten.', 'Resmî mektup → erhalten.', 'erhalten.') },
      { wrong: 'Uns fehlt die Kohle.', right: 'Uns fehlen die finanziellen Mittel.', note: l('Kohle is colloquial.', 'Kohle günlük dildir.', 'Mittel.') },
      { wrong: 'Wären Sie so freundlich, mir helfen?', right: 'Wären Sie so freundlich, mir zu helfen?', note: l('… so freundlich, … zu + infinitive.', '… so freundlich, … zu + mastar.', 'zu.') },
      { wrong: 'Hau rein! (in a formal email)', right: 'Mit freundlichen Grüßen', note: l('Formal closing.', 'Resmî kapanış.', 'Gruß.') },
    ],
  },
}
