import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Ich darf Sie herzlich begrüßen.', emoji: '👋', translation: l('Let me warmly welcome you.', 'Sizi içtenlikle selamlıyorum.', 'Begrüßung'), example: 'Meine Damen und Herren, ich darf Sie herzlich zu unserer Diskussion begrüßen.' },
  { word: 'Unser Thema heute lautet …', emoji: '📌', translation: l('Our topic today is …', 'Bugünkü konumuz …', 'Thema nennen'), example: 'Unser Thema heute lautet: Brauchen wir ein Tempolimit?' },
  { word: 'das Wort erteilen', emoji: '🎤', translation: l('to give the floor', 'söz vermek', 'jemanden sprechen lassen'), example: 'Ich erteile zunächst Frau Dr. Weiß das Wort.' },
  { word: 'Darf ich Sie kurz unterbrechen?', emoji: '✋', translation: l('May I interrupt you briefly?', 'Sizi kısaca bölebilir miyim?', 'höflich unterbrechen'), example: 'Darf ich Sie kurz unterbrechen? Wir müssen auf die Zeit achten.' },
  { word: 'Ich komme gleich auf Sie zurück.', emoji: '↩️', translation: l('I’ll come back to you in a moment.', 'Birazdan size döneceğim.', 'später drannehmen'), example: 'Herr Lange, ich komme gleich auf Sie zurück.' },
  { word: 'auf etwas eingehen', emoji: '🎯', translation: l('to respond to, address', '… -e değinmek', 'reagieren auf'), example: 'Könnten Sie bitte auf diesen Einwand eingehen?' },
  { word: 'zum Thema zurückkommen', emoji: '🔙', translation: l('to get back to the topic', 'konuya dönmek', 'nicht abschweifen'), example: 'Lassen Sie uns zum eigentlichen Thema zurückkommen.' },
  { word: 'Wenn ich kurz zusammenfassen darf: …', emoji: '🧾', translation: l('If I may briefly summarise: …', 'Kısaca özetleyebilirsem: …', 'Zwischenfazit'), example: 'Wenn ich kurz zusammenfassen darf: Beide Seiten wollen weniger Unfälle.' },
  { word: 'Wie stehen Sie dazu?', emoji: '❓', translation: l('What is your view on that?', 'Bu konuda ne düşünüyorsunuz?', 'Meinung erfragen'), example: 'Frau Kaya, wie stehen Sie dazu?' },
  { word: 'Einigkeit / Uneinigkeit besteht darin, dass …', emoji: '🤝', translation: l('There is (dis)agreement that …', '… konusunda uzlaşı / uzlaşmazlık var', 'Ergebnis'), example: 'Einigkeit besteht darin, dass mehr Radwege nötig sind.' },
  { word: 'Ich bitte um etwas mehr Ruhe.', emoji: '🤫', translation: l('Please, a little more quiet.', 'Biraz daha sessizlik rica ediyorum.', 'Ordnung herstellen'), example: 'Ich bitte um etwas mehr Ruhe, damit wir alle verstehen.' },
  { word: 'Ich danke Ihnen für die lebhafte Diskussion.', emoji: '🙏', translation: l('Thank you for the lively discussion.', 'Canlı tartışma için teşekkür ederim.', 'Abschluss'), example: 'Ich danke Ihnen allen für die lebhafte Diskussion.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Moderatorin', gender: 'f', plural: 'die Moderatorinnen', translation: l('moderator (f.)', 'moderatör (k.)', 'Moderatorin') },
  { word: 'Podiumsdiskussion', gender: 'f', plural: 'die Podiumsdiskussionen', translation: l('panel discussion', 'panel tartışması', 'Podiumsdiskussion') },
  { word: 'Redezeit', gender: 'f', translation: l('speaking time', 'konuşma süresi', 'Redezeit') },
  { word: 'Wortmeldung', gender: 'f', plural: 'die Wortmeldungen', translation: l('request to speak', 'söz isteme', 'Wortmeldung') },
  { word: 'Teilnehmerkreis', gender: 'm', translation: l('group of participants', 'katılımcı grubu', 'Teilnehmerkreis') },
  { word: 'Zwischenfazit', gender: 'n', translation: l('interim summary', 'ara özet', 'Zwischenfazit') },
  { word: 'Standpunkt', gender: 'm', plural: 'die Standpunkte', translation: l('standpoint', 'bakış açısı', 'Standpunkt') },
  { word: 'Publikum', gender: 'n', translation: l('audience', 'seyirci, dinleyici', 'Publikum') },
]

/** [id, sentence with gap, right, wrong] */
const MO: [string, string, string, [string, string]][] = [
  ['erteile', 'Ich ___ nun Herrn Professor Berg das Wort.', 'erteile', ['gebe ab', 'mache']],
  ['unterbrechen', 'Darf ich Sie kurz ___? Wir haben nur noch fünf Minuten.', 'unterbrechen', ['unterbrochen', 'abbrechen']],
  ['zurueck', 'Frau Öztürk, ich komme gleich auf Sie ___.', 'zurück', ['wieder', 'hin']],
  ['eingehen', 'Könnten Sie bitte direkt auf die Frage aus dem Publikum ___?', 'eingehen', ['angehen', 'ausgehen']],
  ['stehen', 'Herr Dr. Kim, wie ___ Sie zu diesem Vorschlag?', 'stehen', ['sitzen', 'finden']],
  ['besteht', 'Einigkeit ___ darin, dass die Innenstadt attraktiver werden muss.', 'besteht', ['steht', 'bestehen']],
]

function moDrills(): Exercise[] {
  return MO.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `mo-${id}`,
      type: 'multiple_choice' as const,
      topic: 'wort',
      concept: 'moderation-phrases',
      skill: 'speaking' as const,
      difficulty: 3 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        'Moderation phrases: jemandem das Wort erteilen, jemanden unterbrechen, auf jemanden zurückkommen, auf etwas eingehen, Wie stehen Sie zu …?, Einigkeit besteht darin, dass …',
        'Moderasyon kalıpları: jemandem das Wort erteilen, jemanden unterbrechen, auf jemanden zurückkommen, auf etwas eingehen, Wie stehen Sie zu …?, Einigkeit besteht darin, dass …',
        `→ ${right}`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-phasen',
    type: 'matching',
    topic: 'eroeffnen',
    concept: 'phases',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Match the phase of a discussion and a phrase.', 'Tartışmanın aşamasını bir ifadeyle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Eröffnung', right: 'Ich darf Sie herzlich begrüßen.' },
      { left: 'Thema vorstellen', right: 'Unser Thema heute lautet …' },
      { left: 'Wort erteilen', right: 'Frau Lenz, bitte.' },
      { left: 'Zwischenfazit', right: 'Wenn ich kurz zusammenfassen darf …' },
      { left: 'Abschluss', right: 'Ich danke Ihnen für die lebhafte Diskussion.' },
    ],
    explanation: l('A moderator guides through clear phases.', 'Moderatör net aşamalarla yönlendirir.', 'Phasen.'),
  },
  {
    id: 'sort-funktion',
    type: 'categorize',
    topic: 'wort',
    concept: 'steer',
    skill: 'reading',
    difficulty: 3,
    instructions: l('Does the moderator give the floor or interrupt / redirect?', 'Moderatör söz mü veriyor, yoksa bölüyor / yönlendiriyor mu?', 'Wort geben oder unterbrechen?'),
    categories: ['Wort geben 🎤', 'unterbrechen / lenken ✋'],
    items: [
      { text: 'Herr Lange, Sie haben das Wort.', category: 0 },
      { text: 'Darf ich Sie kurz unterbrechen?', category: 1 },
      { text: 'Wie stehen Sie dazu?', category: 0 },
      { text: 'Lassen Sie uns zum Thema zurückkommen.', category: 1 },
      { text: 'Bitte, Frau Kaya.', category: 0 },
      { text: 'Bitte fassen Sie sich kurz.', category: 1 },
    ],
    explanation: l('Moderators both open and limit the conversation.', 'Moderatörler konuşmayı hem açar hem sınırlar.', 'lenken.'),
    practice: ['mo-unterbrechen'],
  },
  {
    id: 'mc-hoeflich',
    type: 'multiple_choice',
    topic: 'wort',
    concept: 'interrupt',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Ein Gast spricht schon seit fünf Minuten. Was sagt die Moderatorin am besten?',
    options: ['Darf ich Sie hier kurz unterbrechen? Ich möchte auch Frau Kaya zu Wort kommen lassen.', 'Seien Sie jetzt still!', 'Sie reden zu viel, aufhören.'],
    answer: 0,
    explanation: l('Polite interruption + reason.', 'Kibar bölme + gerekçe.', 'höflich.'),
    practice: ['fill-wort'],
  },
  {
    id: 'tf-neutral',
    type: 'true_false',
    topic: 'ergebnisse',
    concept: 'neutral',
    skill: 'reading',
    difficulty: 2,
    statement: 'Eine gute Moderatorin vertritt in der Diskussion deutlich ihre eigene Meinung.',
    answer: false,
    explanation: l('A moderator stays neutral and steers.', 'Moderatör tarafsız kalır ve yönlendirir.', 'neutral.'),
  },
  {
    id: 'select-fazit',
    type: 'multiple_select',
    topic: 'ergebnisse',
    concept: 'summarise',
    skill: 'speaking',
    difficulty: 3,
    promptL10n: l('Which sentences fit a final summary? Select all.', 'Hangi cümleler bir kapanış özetine uyar? Hepsini seç.', 'Abschließendes Fazit?'),
    options: ['Einigkeit besteht darin, dass mehr investiert werden muss.', 'Uneinig sind sich die Gäste beim Thema Finanzierung.', 'Ich finde Herrn Lange am besten.', 'Wenn ich zusammenfassen darf: …', 'Das war langweilig.'],
    answers: [0, 1, 3],
    explanation: l('Name agreement and disagreement neutrally.', 'Uzlaşıyı ve uzlaşmazlığı tarafsızca belirt.', 'Fazit.'),
  },
  {
    id: 'image-mikro',
    type: 'image_choice',
    topic: 'wort',
    concept: 'floor',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'das Wort erteilen',
    options: [
      { emoji: '🎤', label: 'Mikrofon' },
      { emoji: '📺', label: 'Fernseher' },
      { emoji: '📞', label: 'Telefon' },
      { emoji: '📷', label: 'Kamera' },
    ],
    answer: 0,
    explanation: l('Giving the floor = handing over the microphone.', 'Söz vermek = mikrofonu uzatmak.', 'Mikrofon.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-wort',
    type: 'fill_blank',
    topic: 'wort',
    concept: 'floor',
    skill: 'vocabulary',
    difficulty: 3,
    sentence: 'Ich möchte nun Frau Kaya zu ___ kommen lassen.',
    accepted: ['Wort'],
    base: 'sprechen lassen',
    explanation: l('jemanden zu Wort kommen lassen = to let someone speak.', 'jemanden zu Wort kommen lassen = birine söz vermek.', 'Wort.'),
    examples: ['… Frau Kaya zu **Wort** kommen lassen.'],
  },
  {
    id: 'fill-begruessen',
    type: 'fill_blank',
    topic: 'eroeffnen',
    concept: 'welcome',
    skill: 'speaking',
    difficulty: 2,
    sentence: 'Meine Damen und Herren, ich darf Sie herzlich zu unserer Podiumsdiskussion ___.',
    accepted: ['begrüßen', 'begruessen'],
    base: 'Hallo sagen (formell)',
    explanation: l('Ich darf Sie herzlich begrüßen.', 'Ich darf Sie herzlich begrüßen.', 'begrüßen.'),
    examples: ['… ich darf Sie herzlich **begrüßen**.'],
  },
  {
    id: 'fill-zurueckkommen',
    type: 'fill_blank',
    topic: 'eroeffnen',
    concept: 'structure',
    skill: 'speaking',
    difficulty: 3,
    sentence: 'Lassen Sie uns bitte zum eigentlichen Thema ___.',
    accepted: ['zurückkommen', 'zurueckkommen', 'zurückkehren'],
    base: 'nicht abschweifen',
    explanation: l('zum Thema zurückkommen.', 'zum Thema zurückkommen.', 'zurückkommen.'),
    examples: ['… zum eigentlichen Thema **zurückkommen**.'],
  },
  {
    id: 'build-eroeffnung',
    type: 'sentence_builder',
    topic: 'eroeffnen',
    concept: 'topic',
    skill: 'speaking',
    difficulty: 3,
    chips: ['lautet', 'Unser Thema heute', '„Die Zukunft der Arbeit“'],
    answers: [['Unser Thema heute', 'lautet', '„Die Zukunft der Arbeit“']],
    translation: l('Our topic today is „The future of work“.', 'Bugünkü konumuz „Çalışmanın geleceği“.', 'Unser Thema heute lautet „Die Zukunft der Arbeit“.'),
    explanation: l('Unser Thema lautet … = Our topic is …', 'Unser Thema lautet … = Konumuz …', 'Thema.'),
    examples: ['Unser Thema heute **lautet**: …'],
  },
  {
    id: 'build-erteilen',
    type: 'sentence_builder',
    topic: 'wort',
    concept: 'floor',
    skill: 'speaking',
    difficulty: 3,
    chips: ['das Wort', 'Ich erteile', 'Frau Dr. Weiß', 'zunächst'],
    answers: [['Ich erteile', 'zunächst', 'Frau Dr. Weiß', 'das Wort'], ['Ich erteile', 'Frau Dr. Weiß', 'zunächst', 'das Wort']],
    translation: l('First I give the floor to Dr Weiß.', 'Önce Dr. Weiß’a söz veriyorum.', 'Ich erteile zunächst Frau Dr. Weiß das Wort.'),
    explanation: l('jemandem (dative) das Wort erteilen.', 'jemandem (Dativ) das Wort erteilen.', 'erteilen.'),
    examples: ['Ich **erteile** Frau Dr. Weiß **das Wort**.'],
  },
  {
    id: 'build-einigkeit',
    type: 'sentence_builder',
    topic: 'ergebnisse',
    concept: 'summarise',
    skill: 'speaking',
    difficulty: 3,
    chips: ['dass mehr Radwege', 'Einigkeit besteht darin,', 'nötig sind'],
    answers: [['Einigkeit besteht darin,', 'dass mehr Radwege', 'nötig sind']],
    translation: l('There is agreement that more cycle paths are needed.', 'Daha fazla bisiklet yolu gerektiği konusunda uzlaşı var.', 'Einigkeit besteht darin, dass mehr Radwege nötig sind.'),
    explanation: l('bestehen in + dative → darin, dass …', 'bestehen in + Dativ → darin, dass …', 'darin.'),
    examples: ['Einigkeit **besteht darin**, dass …'],
  },
  {
    id: 'fix-wort',
    type: 'error_correction',
    topic: 'wort',
    concept: 'floor',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich erteile Herrn Lange die Rede.',
    accepted: ['Ich erteile Herrn Lange das Wort.'],
    explanation: l('das Wort erteilen (fixed).', 'das Wort erteilen (kalıp).', 'Wort.'),
    examples: ['Ich erteile Herrn Lange **das Wort**.'],
  },
  {
    id: 'fix-eingehen',
    type: 'error_correction',
    topic: 'wort',
    concept: 'respond',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Könnten Sie bitte zu diesen Einwand eingehen?',
    accepted: ['Könnten Sie bitte auf diesen Einwand eingehen?'],
    explanation: l('eingehen auf + accusative.', 'eingehen auf + Akkusativ.', 'auf.'),
    examples: ['… **auf** diesen Einwand eingehen?'],
  },
  {
    id: 'fix-stehen',
    type: 'error_correction',
    topic: 'wort',
    concept: 'ask-opinion',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wie stehen Sie für diesen Vorschlag?',
    accepted: ['Wie stehen Sie zu diesem Vorschlag?'],
    explanation: l('stehen zu + dative.', 'stehen zu + Dativ.', 'zu.'),
    examples: ['Wie stehen Sie **zu diesem** Vorschlag?'],
  },
  {
    id: 'tr-unterbrechen',
    type: 'translation',
    topic: 'wort',
    concept: 'interrupt',
    skill: 'speaking',
    difficulty: 3,
    source: l('May I interrupt you briefly?', 'Sizi kısaca bölebilir miyim?', 'May I interrupt you briefly?'),
    accepted: ['Darf ich Sie kurz unterbrechen?', 'Darf ich Sie mal kurz unterbrechen?', 'Dürfte ich Sie kurz unterbrechen?'],
    explanation: l('Polite: Darf ich Sie kurz unterbrechen?', 'Kibar: Darf ich Sie kurz unterbrechen?', 'unterbrechen.'),
    examples: ['**Darf ich Sie kurz unterbrechen?**'],
  },
  {
    id: 'tr-danke',
    type: 'translation',
    topic: 'ergebnisse',
    concept: 'close',
    skill: 'speaking',
    difficulty: 3,
    source: l('Thank you all for the lively discussion.', 'Canlı tartışma için hepinize teşekkür ederim.', 'Thank you all for the lively discussion.'),
    accepted: ['Ich danke Ihnen allen für die lebhafte Diskussion.', 'Vielen Dank an alle für die lebhafte Diskussion.', 'Ich danke Ihnen allen für die lebendige Diskussion.'],
    explanation: l('danken für + accusative.', 'danken für + Akkusativ.', 'danken.'),
    examples: ['Ich **danke** Ihnen allen **für** die lebhafte Diskussion.'],
  },
  {
    id: 'ordering-ablauf',
    type: 'ordering',
    topic: 'eroeffnen',
    concept: 'phases',
    skill: 'speaking',
    difficulty: 3,
    promptL10n: l('Order the moderator’s sentences.', 'Moderatörün cümlelerini sırala.', 'Ordne die Moderation.'),
    items: ['Ich erteile zunächst Frau Dr. Weiß das Wort.', 'Meine Damen und Herren, ich darf Sie herzlich begrüßen.', 'Ich danke Ihnen allen für die lebhafte Diskussion.', 'Wenn ich kurz zusammenfassen darf: Einigkeit besteht beim Ziel, nicht beim Weg.'],
    answer: ['Meine Damen und Herren, ich darf Sie herzlich begrüßen.', 'Ich erteile zunächst Frau Dr. Weiß das Wort.', 'Wenn ich kurz zusammenfassen darf: Einigkeit besteht beim Ziel, nicht beim Weg.', 'Ich danke Ihnen allen für die lebhafte Diskussion.'],
    explanation: l('Welcome → floor → summary → thanks.', 'Selamlama → söz → özet → teşekkür.', 'Ablauf.'),
  },
  {
    id: 'dialog-abschweifen',
    type: 'dialogue',
    topic: 'eroeffnen',
    concept: 'structure',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Gast', de: '… und übrigens war ich letzten Sommer in Kopenhagen, das Essen dort war fantastisch …' }],
    options: ['Das klingt spannend, aber lassen Sie uns bitte zum Thema Radverkehr zurückkommen.', 'Erzählen Sie mehr vom Essen!', 'Ruhe jetzt!'],
    answer: 0,
    explanation: l('Politely bring the speaker back to the topic.', 'Konuşmacıyı kibarca konuya geri getir.', 'zurückkommen.'),
  },
  {
    id: 'dialog-streit',
    type: 'dialogue',
    topic: 'wort',
    concept: 'order',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Gast A', de: 'Das ist doch völliger Unsinn, was Sie da erzählen!' }],
    options: ['Herr Lange, ich bitte Sie, sachlich zu bleiben. Frau Kaya, möchten Sie direkt darauf eingehen?', 'Ja, das ist Unsinn.', 'Dann streiten Sie eben weiter.'],
    answer: 0,
    explanation: l('Calm the debate and pass the floor fairly.', 'Tartışmayı yatıştır ve sözü adil biçimde ver.', 'sachlich.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-moderation',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Worum geht es in dem Text?',
    options: ['um Tipps für eine gute Moderation', 'um eine Fernsehshow', 'um Präsentationstechnik mit Folien'],
    answer: 0,
    explanation: l('„Was macht eine gute Moderation aus?“', '„Was macht eine gute Moderation aus?“', 'Moderation.'),
  },
  {
    id: 'read-vorbereitung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-moderation',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was sollte man laut Text vor der Diskussion tun?',
    options: ['die Positionen der Gäste kennen und Leitfragen vorbereiten', 'die eigene Meinung festlegen', 'möglichst viele Gäste einladen'],
    answer: 0,
    explanation: l('„… die Positionen aller Gäste kennen und Leitfragen vorbereiten.“', '„… die Positionen aller Gäste kennen und Leitfragen vorbereiten.“', 'Vorbereitung.'),
  },
  {
    id: 'read-redezeit',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-moderation',
    skill: 'reading',
    difficulty: 3,
    statement: 'Laut Text sollte die Moderatorin darauf achten, dass alle Gäste ähnlich viel Redezeit bekommen.',
    answer: true,
    explanation: l('„… dass die Redezeit fair verteilt ist.“', '„… dass die Redezeit fair verteilt ist.“', 'richtig.'),
  },
  {
    id: 'read-ende',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-moderation',
    skill: 'reading',
    difficulty: 3,
    prompt: 'Was gehört laut Text ans Ende einer Moderation?',
    options: ['eine Zusammenfassung der Ergebnisse', 'die eigene Bewertung der Gäste', 'eine Abstimmung über den Sieger'],
    answer: 0,
    explanation: l('„Am Ende fasst sie die Ergebnisse zusammen …“', '„Am Ende fasst sie die Ergebnisse zusammen …“', 'Fazit.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-eroeffnung',
    type: 'listening_choice',
    topic: 'eroeffnen',
    concept: 'welcome',
    skill: 'listening',
    difficulty: 2,
    audio: 'Guten Abend, meine Damen und Herren. Ich darf Sie herzlich begrüßen. Unser Thema heute lautet: Soll Fleisch teurer werden?',
    question: l('What is the topic of the discussion?', 'Tartışmanın konusu nedir?', 'Thema?'),
    options: ['whether meat should become more expensive', 'vegetarian recipes', 'the price of vegetables'],
    answer: 0,
    explanation: l('Unser Thema heute lautet …', 'Unser Thema heute lautet …', 'Fleischpreis.'),
  },
  {
    id: 'listen-zurueck',
    type: 'listening_choice',
    topic: 'wort',
    concept: 'later',
    skill: 'listening',
    difficulty: 3,
    audio: 'Herr Petersen, ich sehe Ihre Wortmeldung. Ich komme gleich auf Sie zurück – zuerst ist Frau Nowak dran.',
    question: l('When will Mr Petersen speak?', 'Bay Petersen ne zaman konuşacak?', 'Wann spricht Herr Petersen?'),
    options: ['after Ms Nowak', 'right now', 'not at all'],
    answer: 0,
    explanation: l('Ich komme gleich auf Sie zurück = soon, after the next speaker.', 'Ich komme gleich auf Sie zurück = birazdan, sıradaki konuşmacıdan sonra.', 'später.'),
  },
  {
    id: 'listen-zwischenfazit',
    type: 'listening_choice',
    topic: 'ergebnisse',
    concept: 'summarise',
    skill: 'listening',
    difficulty: 3,
    audio: 'Wenn ich kurz zusammenfassen darf: Alle wollen weniger Verkehrstote. Uneinig sind Sie sich aber, ob ein Tempolimit der richtige Weg ist.',
    question: l('Where do the guests disagree?', 'Konuklar nerede anlaşamıyor?', 'Wo ist man uneinig?'),
    options: ['on whether a speed limit is the right way', 'on the goal of fewer road deaths', 'on everything'],
    answer: 0,
    explanation: l('Agreement on the goal, disagreement on the means.', 'Hedefte uzlaşı, araçta uzlaşmazlık.', 'Weg.'),
  },
  {
    id: 'listen-zeit',
    type: 'listening_choice',
    topic: 'wort',
    concept: 'interrupt',
    skill: 'listening',
    difficulty: 3,
    audio: 'Darf ich Sie hier kurz unterbrechen? Wir haben nur noch zehn Minuten und möchten auch Fragen aus dem Publikum hören.',
    question: l('Why does the moderator interrupt?', 'Moderatör neden bölüyor?', 'Warum unterbricht sie?'),
    options: ['because of time and audience questions', 'because she disagrees', 'because the guest is rude'],
    answer: 0,
    explanation: l('Time management + audience.', 'Zaman yönetimi + seyirci.', 'Zeit.'),
  },

  ...moDrills(),
]

export const UNIT_C1_23_MODERATION: CourseUnit = {
  level: 'C1',
  number: 23,
  slug: 'moderation',
  titleDe: 'Eine Diskussion moderieren',
  title: l('Moderating a discussion', 'Bir tartışmayı yönetmek', 'Eine Diskussion moderieren'),
  goal: l(
    'By the end of this unit you can open and structure a panel discussion, give the floor and interrupt politely (das Wort erteilen, Darf ich Sie kurz unterbrechen?), steer back to the topic and summarise the results neutrally.',
    'Bu ünitenin sonunda bir panel tartışmasını açabilir ve yapılandırabilir, kibarca söz verip bölebilir (das Wort erteilen, Darf ich Sie kurz unterbrechen?), konuya geri yönlendirebilir ve sonuçları tarafsızca özetleyebilirsin.',
    'Am Ende dieser Einheit moderierst du eine Diskussion.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'eroeffnen', label: l('Opening and structuring', 'Açmak ve yapılandırmak', 'Eröffnen und strukturieren') },
    { key: 'wort', label: l('Giving the floor and interrupting', 'Söz vermek ve bölmek', 'Wort erteilen und unterbrechen') },
    { key: 'ergebnisse', label: l('Summarising results', 'Sonuçları özetlemek', 'Ergebnisse zusammenfassen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('You lead the panel.', 'Paneli sen yönetiyorsun.', 'Sie leiten das Podium.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Phases of a moderation', 'Moderasyonun aşamaları', 'Phasen einer Moderation'),
          body: l(
            'Opening: welcome, topic, guests. Discussion: give the floor, ask questions, react to statements. Steering: interrupt politely, keep time, return to the topic. End: interim or final summary, thanks.',
            'Açılış: selamlama, konu, konuklar. Tartışma: söz ver, soru sor, ifadelere tepki ver. Yönlendirme: kibarca böl, zamana dikkat et, konuya dön. Kapanış: ara ya da son özet, teşekkür.',
            'Phasen.'
          ),
          table: {
            head: [l('Phase', 'Aşama', 'Phase'), l('Phrase', 'İfade', 'Wendung')],
            rows: [
              ['Eröffnung', 'Ich darf Sie herzlich begrüßen. Unser Thema lautet …'],
              ['Wort geben', 'Ich erteile Frau … das Wort. / Wie stehen Sie dazu?'],
              ['Lenken', 'Darf ich Sie kurz unterbrechen? / Zurück zum Thema …'],
              ['Fazit', 'Einigkeit besteht darin, dass … Uneinig sind Sie sich …'],
            ],
          },
        },
        {
          title: l('Polite steering', 'Kibar yönlendirme', 'Höflich lenken'),
          body: l(
            'Use Konjunktiv II and modal verbs to soften: Dürfte ich Sie kurz unterbrechen? Könnten Sie bitte direkt auf die Frage eingehen? Ich würde gern auch Frau … zu Wort kommen lassen. Always give a reason (time, fairness, topic).',
            'Yumuşatmak için Konjunktiv II ve kiplik fiiller kullan: Dürfte ich Sie kurz unterbrechen? Könnten Sie bitte direkt auf die Frage eingehen? Ich würde gern auch Frau … zu Wort kommen lassen. Her zaman bir gerekçe ver (zaman, adalet, konu).',
            'höflich.'
          ),
          examples: [
            { de: '**Darf ich Sie kurz unterbrechen?** Die Zeit läuft.', translation: l('May I interrupt briefly? Time is running out.', 'Kısaca bölebilir miyim? Zaman daralıyor.', '') },
            { de: '**Könnten Sie** bitte **auf** diesen Punkt **eingehen**?', translation: l('Could you please address this point?', 'Lütfen bu noktaya değinebilir misiniz?', '') },
          ],
        },
        {
          title: l('Staying neutral', 'Tarafsız kalmak', 'Neutral bleiben'),
          body: l(
            'The moderator does not take sides. Summarise positions fairly (Frau X betont …, Herr Y hält dagegen …), name agreement and disagreement (Einigkeit / Uneinigkeit besteht darin, dass …) and distribute speaking time equally.',
            'Moderatör taraf tutmaz. Görüşleri adil biçimde özetle (Frau X betont …, Herr Y hält dagegen …), uzlaşı ve uzlaşmazlığı belirt (Einigkeit / Uneinigkeit besteht darin, dass …) ve konuşma süresini eşit dağıt.',
            'neutral.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A panel discussion on a speed limit on motorways.', 'Otoyollarda hız sınırı hakkında bir panel tartışması.', 'Podiumsdiskussion Tempolimit.'),
      dialogue: [
        { speaker: 'Moderatorin', de: 'Guten Abend, **ich darf Sie herzlich begrüßen**. **Unser Thema heute lautet**: Brauchen wir ein Tempolimit? Frau Dr. Weiß, bitte.', translation: l('Good evening, let me warmly welcome you. Our topic today: do we need a speed limit? Dr Weiß, please.', 'İyi akşamlar, sizi içtenlikle selamlıyorum. Bugünkü konumuz: Hız sınırına ihtiyacımız var mı? Dr. Weiß, buyurun.', '') },
        { speaker: 'Dr. Weiß', de: 'Ein Tempolimit würde jährlich Millionen Tonnen CO₂ sparen und Leben retten.', translation: l('A speed limit would save millions of tonnes of CO₂ a year and save lives.', 'Hız sınırı her yıl milyonlarca ton CO₂ tasarrufu sağlar ve hayat kurtarır.', '') },
        { speaker: 'Herr Lange', de: 'Das ist doch reine Symbolpolitik! Unsere Autobahnen gehören zu den sichersten der Welt, und außerdem …', translation: l('That’s pure symbolic politics! Our motorways are among the safest in the world, and besides …', 'Bu tamamen sembolik politika! Otoyollarımız dünyanın en güvenlileri arasında, üstelik …', '') },
        { speaker: 'Moderatorin', de: '**Darf ich Sie kurz unterbrechen**, Herr Lange? **Ich komme gleich auf Sie zurück**. Frau Dr. Weiß, **wie stehen Sie zu** dem Vorwurf der Symbolpolitik?', translation: l('May I interrupt briefly, Mr Lange? I’ll come back to you in a moment. Dr Weiß, what is your view on the accusation of symbolic politics?', 'Kısaca bölebilir miyim, Bay Lange? Birazdan size döneceğim. Dr. Weiß, sembolik politika suçlamasına ne diyorsunuz?', '') },
        { speaker: 'Dr. Weiß', de: 'Symbolisch? Die Zahlen des Umweltbundesamts sprechen eine andere Sprache.', translation: l('Symbolic? The figures of the Federal Environment Agency tell a different story.', 'Sembolik mi? Federal Çevre Ajansı’nın rakamları başka bir şey söylüyor.', '') },
        { speaker: 'Moderatorin', de: '**Wenn ich kurz zusammenfassen darf**: **Einigkeit besteht darin**, dass Sicherheit wichtig ist – **uneinig** sind Sie sich über den Weg.', translation: l('If I may briefly summarise: there is agreement that safety matters – you disagree on the way.', 'Kısaca özetleyebilirsem: Güvenliğin önemli olduğu konusunda uzlaşı var – yol konusunda ise anlaşamıyorsunuz.', '') },
      ],
      examples: [
        { de: 'Ich **erteile** Herrn Berg **das Wort**.', translation: l('I give the floor to Mr Berg.', 'Bay Berg’e söz veriyorum.', '') },
        { de: '**Lassen Sie uns zum Thema zurückkommen.**', translation: l('Let’s get back to the topic.', 'Konuya dönelim.', '') },
        { de: 'Könnten Sie bitte **darauf eingehen**?', translation: l('Could you please respond to that?', 'Lütfen buna değinebilir misiniz?', '') },
        { de: '**Ich bitte um** etwas mehr **Ruhe**.', translation: l('A little more quiet, please.', 'Biraz daha sessizlik rica ediyorum.', '') },
        { de: 'Gibt es **Wortmeldungen** aus dem Publikum?', translation: l('Are there any requests to speak from the audience?', 'Seyircilerden söz isteyen var mı?', '') },
        { de: '**Ich danke Ihnen** für die lebhafte Diskussion.', translation: l('Thank you for the lively discussion.', 'Canlı tartışma için teşekkür ederim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('The moderator’s toolkit.', 'Moderatörün araç kutusu.', 'Werkzeuge der Moderation.'),
      exercises: ['match-phasen', 'sort-funktion', 'mo-erteile', 'mo-unterbrechen', 'mo-zurueck', 'mc-hoeflich', 'tf-neutral', 'select-fazit', 'image-mikro'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Lead the discussion.', 'Tartışmayı yönet.', 'Diskussion leiten.'),
      exercises: [
        'fill-wort',
        'fill-begruessen',
        'fill-zurueckkommen',
        'build-eroeffnung',
        'build-erteilen',
        'build-einigkeit',
        'fix-wort',
        'fix-eingehen',
        'fix-stehen',
        'tr-unterbrechen',
        'tr-danke',
        'ordering-ablauf',
        'dialog-abschweifen',
        'dialog-streit',
        'mo-eingehen',
        'mo-stehen',
        'mo-besteht',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A guide for moderators.', 'Moderatörler için bir rehber.', 'Ein Leitfaden.'),
      passage: [
        '**Was macht eine gute Moderation aus?** – Eine Moderatorin ist keine Teilnehmerin, sondern die Gastgeberin der Diskussion. Sie bleibt neutral und sorgt für einen fairen Ablauf.',
        'Gute Vorbereitung ist entscheidend: Man sollte die Positionen aller Gäste kennen und Leitfragen vorbereiten, die die Diskussion strukturieren.',
        'Während der Diskussion achtet die Moderatorin darauf, dass die Redezeit fair verteilt ist. Wer zu lange spricht, wird höflich, aber bestimmt unterbrochen.',
        'Am Ende fasst sie die Ergebnisse zusammen: Wo besteht Einigkeit, wo bleiben die Positionen gegensätzlich? Ein Dank an Gäste und Publikum rundet die Moderation ab.',
      ],
      glossary: [
        { de: 'die Gastgeberin', note: l('host (f.)', 'ev sahibi (k.)', 'lädt Gäste ein') },
        { de: 'die Leitfrage', note: l('guiding question', 'yönlendirici soru', 'wichtige Frage') },
        { de: 'bestimmt', note: l('firmly', 'kararlı bir şekilde', 'klar, entschieden') },
        { de: 'abrunden', note: l('to round off', 'tamamlamak', 'abschließen') },
      ],
      exercises: ['read-thema', 'read-vorbereitung', 'read-redezeit', 'read-ende'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Moderators at work.', 'İş başındaki moderatörler.', 'Moderation hören.'),
      exercises: ['listen-eroeffnung', 'listen-zurueck', 'listen-zwischenfazit', 'listen-zeit'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Open and close a panel discussion on „Sollte Fleisch teurer werden?“ with two guests.', 'İki konuklu bir panel tartışmasını açıp kapat: „Sollte Fleisch teurer werden?“', 'Eine Diskussion eröffnen und abschließen.'),
      points: [
        l('Welcome and topic', 'Selamlama ve konu', 'Eröffnung'),
        l('Introduce the guests and give the floor', 'Konukları tanıt ve söz ver', 'Wort erteilen'),
        l('A polite interruption', 'Kibar bir bölme', 'unterbrechen'),
        l('Summary and thanks', 'Özet ve teşekkür', 'Fazit'),
      ],
      model: [
        'Meine Damen und Herren, ich darf Sie herzlich begrüßen. Unser Thema heute lautet: Sollte Fleisch teurer werden?',
        'Bei mir sind eine Landwirtin und ein Ernährungswissenschaftler. Frau Haas, ich erteile Ihnen zuerst das Wort.',
        'Darf ich Sie kurz unterbrechen? Ich möchte auch Herrn Yılmaz zu Wort kommen lassen.',
        'Wenn ich zusammenfassen darf: Einigkeit besteht beim Tierwohl, uneinig sind Sie sich beim Preis. Ich danke Ihnen.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a moderation script (at least 6 sentences) for a discussion on „Sollen Schulen Handys verbieten?“: opening, giving the floor, one interruption and a summary.',
        '„Sollen Schulen Handys verbieten?“ tartışması için bir moderasyon metni yaz (en az 6 cümle): açılış, söz verme, bir bölme ve bir özet.',
        'Moderationsskript (mindestens 6 Sätze).'
      ),
      minSentences: 6,
      checks: [
        { label: l('An opening (begrüßen, Thema lautet)', 'Bir açılış (begrüßen, Thema lautet)', 'Eröffnung'), pattern: '(begrüßen|Thema[^.]*lautet|[Ww]illkommen)' },
        { label: l('Giving the floor or interrupting (das Wort, unterbrechen, wie stehen Sie)', 'Söz verme ya da bölme (das Wort, unterbrechen, wie stehen Sie)', 'Lenken'), pattern: '(das Wort|zu Wort|unterbrechen|[Ww]ie stehen Sie|eingehen)' },
        { label: l('A summary (zusammenfassen, Einigkeit, uneinig)', 'Bir özet (zusammenfassen, Einigkeit, uneinig)', 'Fazit'), pattern: '(zusammenfass|Einigkeit|[Uu]neinig|einig)' },
      ],
      model: [
        'Liebe Gäste, ich darf Sie herzlich begrüßen. Unser Thema heute lautet: Sollen Schulen Handys verbieten?',
        'Bei mir sind eine Schulleiterin und ein Schülersprecher.',
        'Frau Berger, ich erteile Ihnen zuerst das Wort: Warum haben Sie an Ihrer Schule ein Verbot eingeführt?',
        'Herr Aydın, wie stehen Sie zu diesem Verbot?',
        'Darf ich Sie kurz unterbrechen? Wir möchten auch Fragen aus dem Publikum hören.',
        'Wenn ich zusammenfassen darf: Einigkeit besteht beim Ziel, uneinig sind Sie sich über den Weg. Ich danke Ihnen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Moderation phrases – 60 seconds.', 'Moderasyon kalıpları – 60 saniye.', 'Moderation – 60 Sekunden.'),
      seconds: 60,
      pool: [...MO.map(([id]) => `mo-${id}`), 'mc-hoeflich'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Opening: Ich darf Sie herzlich begrüßen. Unser Thema lautet …', 'Açılış: Ich darf Sie herzlich begrüßen. Unser Thema lautet …', 'Eröffnung'),
      l('Floor: das Wort erteilen, zu Wort kommen lassen, Wie stehen Sie zu …?', 'Söz: das Wort erteilen, zu Wort kommen lassen, Wie stehen Sie zu …?', 'Wort'),
      l('Steering: Darf ich Sie kurz unterbrechen?, zum Thema zurückkommen', 'Yönlendirme: Darf ich Sie kurz unterbrechen?, zum Thema zurückkommen', 'Lenken'),
      l('Summary: Einigkeit / Uneinigkeit besteht darin, dass …', 'Özet: Einigkeit / Uneinigkeit besteht darin, dass …', 'Fazit'),
    ],
    mistakes: [
      { wrong: 'Ich erteile Ihnen die Rede.', right: 'Ich erteile Ihnen das Wort.', note: l('das Wort erteilen.', 'das Wort erteilen.', 'Wort.') },
      { wrong: 'Wie stehen Sie für den Vorschlag?', right: 'Wie stehen Sie zu dem Vorschlag?', note: l('stehen zu + dative.', 'stehen zu + Dativ.', 'zu.') },
      { wrong: 'Gehen Sie bitte zu dem Einwand ein.', right: 'Gehen Sie bitte auf den Einwand ein.', note: l('eingehen auf + accusative.', 'eingehen auf + Akkusativ.', 'auf.') },
      { wrong: 'Seien Sie still!', right: 'Darf ich Sie kurz unterbrechen?', note: l('Interrupt politely.', 'Kibarca böl.', 'höflich.') },
    ],
  },
}
