import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'sowohl … als auch', emoji: '➕', translation: l('both … and', 'hem … hem de', 'beides'), example: 'Ich spreche sowohl Englisch als auch Deutsch.' },
  { word: 'weder … noch', emoji: '🚫', translation: l('neither … nor', 'ne … ne de', 'keins von beiden'), example: 'Er trinkt weder Kaffee noch Tee.' },
  { word: 'entweder … oder', emoji: '🔀', translation: l('either … or', 'ya … ya da', 'eins von beiden'), example: 'Wir fahren entweder ans Meer oder in die Berge.' },
  { word: 'nicht nur … sondern auch', emoji: '🌟', translation: l('not only … but also', 'sadece … değil, … da', 'beides, mit Betonung'), example: 'Sie ist nicht nur klug, sondern auch witzig.' },
  { word: 'zwar … aber', emoji: '⚖️', translation: l('admittedly … but', 'gerçi … ama', 'Einschränkung'), example: 'Die Wohnung ist zwar klein, aber sehr gemütlich.' },
  { word: 'je … desto', emoji: '📈', translation: l('the more … the more', 'ne kadar … o kadar', 'Proportion'), example: 'Je mehr ich übe, desto besser werde ich.' },
  { word: 'der Vorteil', emoji: '👍', translation: l('advantage', 'avantaj', 'positiv'), example: 'Ein Vorteil ist der Preis.' },
  { word: 'der Nachteil', emoji: '👎', translation: l('disadvantage', 'dezavantaj', 'negativ'), example: 'Ein Nachteil ist die Lage.' },
  { word: 'die Lage', emoji: '📍', translation: l('location', 'konum', 'wo etwas liegt'), example: 'Die Lage der Wohnung ist perfekt.' },
  { word: 'gemütlich', emoji: '🛋️', translation: l('cosy', 'rahat, sıcak', 'angenehm'), example: 'Das Café ist klein, aber gemütlich.' },
  { word: 'die Entscheidung treffen', emoji: '✅', translation: l('to make a decision', 'karar vermek', 'entscheiden'), example: 'Wir müssen bald eine Entscheidung treffen.' },
  { word: 'vergleichen', emoji: '🔍', translation: l('to compare', 'karşılaştırmak', 'Unterschiede suchen'), example: 'Wir vergleichen zwei Angebote.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Vorteil', gender: 'm', plural: 'die Vorteile', translation: l('advantage', 'avantaj', 'Vorteil') },
  { word: 'Nachteil', gender: 'm', plural: 'die Nachteile', translation: l('disadvantage', 'dezavantaj', 'Nachteil') },
  { word: 'Lage', gender: 'f', plural: 'die Lagen', translation: l('location', 'konum', 'Lage') },
  { word: 'Angebot', gender: 'n', plural: 'die Angebote', translation: l('offer', 'teklif', 'Angebot') },
  { word: 'Wohnung', gender: 'f', plural: 'die Wohnungen', translation: l('flat', 'daire', 'Wohnung') },
  { word: 'Entscheidung', gender: 'f', plural: 'die Entscheidungen', translation: l('decision', 'karar', 'Entscheidung') },
]

/** [id, sentence with ___, right second part, two wrong parts] */
const PAIRS: [string, string, string, [string, string]][] = [
  ['sowohl', 'Sie spricht sowohl Spanisch ___ Portugiesisch.', 'als auch', ['noch', 'oder']],
  ['weder', 'Ich habe weder Zeit ___ Geld.', 'noch', ['als auch', 'oder']],
  ['entweder', 'Wir gehen entweder ins Kino ___ ins Theater.', 'oder', ['noch', 'sondern auch']],
  ['nichtnur', 'Das Hotel ist nicht nur günstig, ___ sehr sauber.', 'sondern auch', ['aber auch nicht', 'als auch']],
  ['zwar', 'Die Jacke ist zwar teuer, ___ sie ist sehr warm.', 'aber', ['oder', 'noch']],
  ['je', 'Je früher wir losfahren, ___ weniger Stau gibt es.', 'desto', ['als', 'so']],
]

function pairDrills(): Exercise[] {
  const meanings: Record<string, [string, string]> = {
    sowohl: ['both → sowohl … als auch', 'ikisi de → sowohl … als auch'],
    weder: ['neither … nor → weder … noch', 'ne … ne → weder … noch'],
    entweder: ['one of two → entweder … oder', 'ikisinden biri → entweder … oder'],
    nichtnur: ['both, with emphasis → nicht nur … sondern auch', 'ikisi de, vurgulu → nicht nur … sondern auch'],
    zwar: ['admitting a point + contrast → zwar … aber', 'bir noktayı kabul + karşıtlık → zwar … aber'],
    je: ['proportion → je + comparative …, desto + comparative', 'orantı → je + karşılaştırma …, desto + karşılaştırma'],
  }
  return PAIRS.map(([id, sentence, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `paar-${id}`,
      type: 'multiple_choice' as const,
      topic: id === 'je' || id === 'zwar' ? 'zwar-je' : 'paare',
      concept: `pair-${id}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`${meanings[id][0]}.`, `${meanings[id][1]}.`, `${right}.`),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-paare',
    type: 'matching',
    topic: 'paare',
    concept: 'pair-match',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Match the two parts.', 'İki parçayı eşleştir.', 'Ordne die zwei Teile zu.'),
    pairs: [
      { left: 'sowohl …', right: '… als auch' },
      { left: 'weder …', right: '… noch' },
      { left: 'entweder …', right: '… oder' },
      { left: 'nicht nur …', right: '… sondern auch' },
      { left: 'zwar …', right: '… aber' },
    ],
    explanation: l('Learn the pairs together – they always go as a set.', 'Çiftleri birlikte öğren – her zaman birlikte kullanılırlar.', 'Immer als Paar.'),
    practice: ['paar-sowohl', 'paar-weder'],
  },
  {
    id: 'sort-bedeutung',
    type: 'categorize',
    topic: 'paare',
    concept: 'pair-meaning',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('How many of the two things?', 'İki şeyden kaçı?', 'Wie viele von beiden?'),
    categories: ['beide', 'keins', 'eins'],
    items: [
      { text: 'sowohl Tee als auch Kaffee', category: 0 },
      { text: 'weder Tee noch Kaffee', category: 1 },
      { text: 'entweder Tee oder Kaffee', category: 2 },
      { text: 'nicht nur Tee, sondern auch Kaffee', category: 0 },
      { text: 'weder heute noch morgen', category: 1 },
      { text: 'entweder heute oder morgen', category: 2 },
    ],
    explanation: l('sowohl…als auch / nicht nur…sondern auch = both. weder…noch = none. entweder…oder = one.', 'sowohl…als auch / nicht nur…sondern auch = ikisi de. weder…noch = hiçbiri. entweder…oder = biri.', 'beide / keins / eins.'),
  },
  {
    id: 'mc-weder-kein',
    type: 'multiple_choice',
    topic: 'paare',
    concept: 'weder-negation',
    skill: 'grammar',
    difficulty: 3,
    prompt: 'Ich habe weder ein Auto ___ ein Fahrrad.',
    options: ['noch', 'noch kein', 'und kein'],
    answer: 0,
    explanation: l('weder … noch is already negative – no extra nicht/kein!', 'weder … noch zaten olumsuzdur – ekstra nicht/kein yok!', 'kein doppeltes Nein.'),
    examples: ['Ich habe **weder** ein Auto **noch** ein Fahrrad.'],
  },
  {
    id: 'tf-je',
    type: 'true_false',
    topic: 'zwar-je',
    concept: 'je-desto',
    skill: 'grammar',
    difficulty: 3,
    statement: 'Nach „je“ steht das Verb am Ende, nach „desto“ kommt direkt das Verb nach dem Komparativ.',
    answer: true,
    explanation: l('Je mehr ich lerne (verb at the end), desto besser spreche ich (desto + comparative + verb).', 'Je mehr ich lerne (fiil sonda), desto besser spreche ich (desto + karşılaştırma + fiil).', 'Je … lerne, desto … spreche ich.'),
    examples: ['**Je** mehr ich **lerne**, **desto** besser **spreche** ich.'],
  },
  {
    id: 'select-richtig',
    type: 'multiple_select',
    topic: 'paare',
    concept: 'pair-mixed',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche Sätze sind richtig?'),
    options: ['Er isst weder Fleisch noch Fisch.', 'Er isst weder Fleisch und Fisch.', 'Sie kann sowohl kochen als auch backen.', 'Entweder du kommst mit, oder du bleibst hier.', 'Nicht nur er, aber auch sie kommt.'],
    answers: [0, 2, 3],
    explanation: l('weder … noch, sowohl … als auch, entweder … oder, nicht nur … sondern auch.', 'weder … noch, sowohl … als auch, entweder … oder, nicht nur … sondern auch.', 'Die Paare.'),
  },
  {
    id: 'image-weder',
    type: 'image_choice',
    topic: 'paare',
    concept: 'weder-negation',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Er trinkt weder Alkohol noch Kaffee – nur Wasser.',
    options: [
      { emoji: '💧', label: 'Wasser' },
      { emoji: '🍺', label: 'Bier' },
      { emoji: '☕', label: 'Kaffee' },
      { emoji: '🍷', label: 'Wein' },
    ],
    answer: 0,
    explanation: l('weder … noch = neither … nor → only water.', 'weder … noch = ne … ne → sadece su.', 'nur Wasser.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-als-auch',
    type: 'fill_blank',
    topic: 'paare',
    concept: 'pair-sowohl',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Wohnung hat sowohl einen Balkon ___ einen Garten.',
    accepted: ['als auch'],
    base: 'sowohl … ?',
    explanation: l('sowohl … als auch.', 'sowohl … als auch.', 'als auch.'),
    examples: ['… **sowohl** einen Balkon **als auch** einen Garten.'],
  },
  {
    id: 'fill-sondern',
    type: 'fill_blank',
    topic: 'paare',
    concept: 'pair-nichtnur',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie spricht nicht nur Deutsch, ___ auch Japanisch.',
    accepted: ['sondern'],
    base: 'nicht nur … ? auch',
    explanation: l('nicht nur … sondern auch.', 'nicht nur … sondern auch.', 'sondern auch.'),
    examples: ['… **nicht nur** Deutsch, **sondern auch** Japanisch.'],
  },
  {
    id: 'fill-desto',
    type: 'fill_blank',
    topic: 'zwar-je',
    concept: 'je-desto',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Je länger ich in Berlin wohne, ___ besser gefällt mir die Stadt.',
    accepted: ['desto', 'umso'],
    base: 'je … ?',
    explanation: l('je … desto/umso.', 'je … desto/umso.', 'desto.'),
    examples: ['Je länger ich hier wohne, **desto** besser gefällt mir die Stadt.'],
  },
  {
    id: 'build-entweder',
    type: 'sentence_builder',
    topic: 'paare',
    concept: 'pair-entweder',
    skill: 'grammar',
    difficulty: 2,
    chips: ['oder', 'nach Italien', 'entweder', 'Wir fahren', 'nach Kroatien'],
    answers: [['Wir fahren', 'entweder', 'nach Italien', 'oder', 'nach Kroatien']],
    translation: l('We’re going either to Italy or to Croatia.', 'Ya İtalya’ya ya da Hırvatistan’a gidiyoruz.', 'Wir fahren entweder nach Italien oder nach Kroatien.'),
    explanation: l('entweder … oder between the two options.', 'entweder … oder iki seçeneğin arasında.', 'entweder … oder.'),
    examples: ['Wir fahren **entweder** nach Italien **oder** nach Kroatien.'],
  },
  {
    id: 'build-zwar',
    type: 'sentence_builder',
    topic: 'zwar-je',
    concept: 'pair-zwar',
    skill: 'grammar',
    difficulty: 3,
    chips: ['zwar', 'aber', 'Der Job ist', 'anstrengend,', 'er macht Spaß'],
    answers: [['Der Job ist', 'zwar', 'anstrengend,', 'aber', 'er macht Spaß']],
    translation: l('The job is tiring, but it’s fun.', 'İş gerçi yorucu ama eğlenceli.', 'Der Job ist zwar anstrengend, aber er macht Spaß.'),
    explanation: l('zwar (admitting) … , aber (contrast).', 'zwar (kabul) … , aber (karşıtlık).', 'zwar … aber.'),
    examples: ['Der Job ist **zwar** anstrengend, **aber** er macht Spaß.'],
  },
  {
    id: 'build-je',
    type: 'sentence_builder',
    topic: 'zwar-je',
    concept: 'je-desto',
    skill: 'grammar',
    difficulty: 3,
    chips: ['desto', 'Je mehr ich lese,', 'mein Wortschatz', 'größer', 'wird'],
    answers: [['Je mehr ich lese,', 'desto', 'größer', 'wird', 'mein Wortschatz']],
    translation: l('The more I read, the bigger my vocabulary gets.', 'Ne kadar çok okursam kelime dağarcığım o kadar büyüyor.', 'Je mehr ich lese, desto größer wird mein Wortschatz.'),
    explanation: l('desto + comparative + verb + subject.', 'desto + karşılaştırma + fiil + özne.', 'desto größer wird …'),
    examples: ['Je mehr ich lese, **desto größer wird** mein Wortschatz.'],
  },
  {
    id: 'fix-weder-nicht',
    type: 'error_correction',
    topic: 'paare',
    concept: 'weder-negation',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich mag weder Katzen noch keine Hunde.',
    accepted: ['Ich mag weder Katzen noch Hunde.'],
    explanation: l('weder … noch is already negative → no kein.', 'weder … noch zaten olumsuz → kein yok.', 'ohne kein.'),
    examples: ['Ich mag **weder** Katzen **noch** Hunde.'],
  },
  {
    id: 'fix-sowohl',
    type: 'error_correction',
    topic: 'paare',
    concept: 'pair-sowohl',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Er spielt sowohl Gitarre und Klavier.',
    accepted: ['Er spielt sowohl Gitarre als auch Klavier.'],
    explanation: l('sowohl … als auch (not und).', 'sowohl … als auch (und değil).', 'als auch.'),
    examples: ['Er spielt **sowohl** Gitarre **als auch** Klavier.'],
  },
  {
    id: 'fix-nicht-nur',
    type: 'error_correction',
    topic: 'paare',
    concept: 'pair-nichtnur',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das Essen war nicht nur billig, aber auch lecker.',
    accepted: ['Das Essen war nicht nur billig, sondern auch lecker.'],
    explanation: l('nicht nur … sondern auch.', 'nicht nur … sondern auch.', 'sondern auch.'),
    examples: ['… **nicht nur** billig, **sondern auch** lecker.'],
  },
  {
    id: 'tr-weder',
    type: 'translation',
    topic: 'paare',
    concept: 'pair-weder',
    skill: 'writing',
    difficulty: 2,
    source: l('I have neither time nor money.', 'Ne vaktim ne de param var.', 'I have neither time nor money.'),
    accepted: ['Ich habe weder Zeit noch Geld.'],
    explanation: l('weder … noch.', 'weder … noch.', 'weder … noch.'),
    examples: ['Ich habe **weder** Zeit **noch** Geld.'],
  },
  {
    id: 'tr-sowohl',
    type: 'translation',
    topic: 'paare',
    concept: 'pair-sowohl',
    skill: 'writing',
    difficulty: 2,
    source: l('She speaks both English and French.', 'Hem İngilizce hem de Fransızca konuşuyor.', 'She speaks both English and French.'),
    accepted: ['Sie spricht sowohl Englisch als auch Französisch.'],
    explanation: l('sowohl … als auch.', 'sowohl … als auch.', 'sowohl … als auch.'),
    examples: ['Sie spricht **sowohl** Englisch **als auch** Französisch.'],
  },
  {
    id: 'ordering-vergleich',
    type: 'ordering',
    topic: 'zwar-je',
    concept: 'pros-cons',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Build a balanced opinion.', 'Dengeli bir fikir kur.', 'Bilde eine ausgewogene Meinung.'),
    items: ['Am Ende nehmen wir die Wohnung in der Stadt.', 'Die Wohnung in der Stadt ist zwar teurer,', 'Deshalb haben wir uns entschieden:', 'aber sie hat sowohl eine gute Lage als auch einen Balkon.'],
    answer: ['Die Wohnung in der Stadt ist zwar teurer,', 'aber sie hat sowohl eine gute Lage als auch einen Balkon.', 'Deshalb haben wir uns entschieden:', 'Am Ende nehmen wir die Wohnung in der Stadt.'],
    explanation: l('Disadvantage (zwar) → advantages (aber, sowohl … als auch) → decision.', 'Dezavantaj (zwar) → avantajlar (aber, sowohl … als auch) → karar.', 'zwar … aber … deshalb.'),
  },
  {
    id: 'dialog-urlaub',
    type: 'dialogue',
    topic: 'paare',
    concept: 'pair-entweder',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Partner', de: 'Wohin fahren wir in den Ferien?' }],
    options: ['Entweder ans Meer oder in die Berge – du entscheidest!', 'Entweder ans Meer noch in die Berge.', 'Weder ans Meer oder in die Berge.'],
    answer: 0,
    explanation: l('Two options → entweder … oder.', 'İki seçenek → entweder … oder.', 'entweder … oder.'),
  },
  {
    id: 'dialog-restaurant',
    type: 'dialogue',
    topic: 'zwar-je',
    concept: 'pair-zwar',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freundin', de: 'Wie war das neue Restaurant?' }],
    options: ['Es war zwar teuer, aber das Essen war fantastisch.', 'Es war zwar teuer, sondern das Essen war gut.', 'Es war weder teuer aber gut.'],
    answer: 0,
    explanation: l('zwar … aber = admittedly …, but.', 'zwar … aber = gerçi …, ama.', 'zwar … aber.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-wohnung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-vergleich',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Welche Wohnungen vergleichen Lisa und Ben?',
    options: ['Eine in der Stadt und eine auf dem Land.', 'Zwei in der Stadt.', 'Zwei Häuser.'],
    answer: 0,
    explanation: l('„… entweder die Wohnung in der Stadt oder das Haus auf dem Land.“', '„… entweder die Wohnung in der Stadt oder das Haus auf dem Land.“', 'Stadt / Land.'),
  },
  {
    id: 'read-stadt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-vergleich',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist ein Vorteil der Stadtwohnung?',
    options: ['Sowohl Arbeit als auch Schule sind nah.', 'Sie ist sehr billig.', 'Sie hat einen großen Garten.'],
    answer: 0,
    explanation: l('„In der Stadt sind sowohl die Arbeit als auch die Schule nah.“', '„In der Stadt sind sowohl die Arbeit als auch die Schule nah.“', 'Arbeit und Schule nah.'),
  },
  {
    id: 'read-land',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-vergleich',
    skill: 'reading',
    difficulty: 2,
    statement: 'Auf dem Land gibt es einen Supermarkt in der Nähe.',
    answer: false,
    explanation: l('„Dort gibt es weder einen Supermarkt noch einen Bahnhof in der Nähe.“', '„Dort gibt es weder einen Supermarkt noch einen Bahnhof in der Nähe.“', 'weder … noch.'),
  },
  {
    id: 'read-entscheidung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-vergleich',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie haben sie sich entschieden?',
    options: ['Für die Stadt – obwohl sie teurer ist.', 'Für das Land.', 'Sie haben sich noch nicht entschieden.'],
    answer: 0,
    explanation: l('„Die Stadtwohnung ist zwar teurer, aber wir nehmen sie.“', '„Die Stadtwohnung ist zwar teurer, aber wir nehmen sie.“', 'Stadt.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-sowohl',
    type: 'listening_choice',
    topic: 'paare',
    concept: 'pair-sowohl',
    skill: 'listening',
    difficulty: 1,
    audio: 'In unserem Hotel gibt es sowohl einen Pool als auch eine Sauna.',
    question: l('What does the hotel have?', 'Otelde ne var?', 'Was hat das Hotel?'),
    options: ['pool and sauna', 'only a pool', 'neither'],
    answer: 0,
    explanation: l('sowohl … als auch = both.', 'sowohl … als auch = ikisi de.', 'beides.'),
  },
  {
    id: 'listen-weder',
    type: 'listening_choice',
    topic: 'paare',
    concept: 'pair-weder',
    skill: 'listening',
    difficulty: 2,
    audio: 'Leider kann ich weder am Samstag noch am Sonntag.',
    question: l('When can the person come?', 'Kişi ne zaman gelebilir?', 'Wann kann die Person?'),
    options: ['neither day', 'Saturday', 'Sunday'],
    answer: 0,
    explanation: l('weder … noch = neither.', 'weder … noch = hiçbiri.', 'keinen Tag.'),
  },
  {
    id: 'listen-je',
    type: 'listening_choice',
    topic: 'zwar-je',
    concept: 'je-desto',
    skill: 'listening',
    difficulty: 2,
    audio: 'Je früher du buchst, desto billiger ist der Flug.',
    question: l('How do you get a cheaper flight?', 'Daha ucuz uçuş nasıl bulunur?', 'Wie wird der Flug billiger?'),
    options: ['book early', 'book late', 'fly at night'],
    answer: 0,
    explanation: l('Je früher … desto billiger.', 'Ne kadar erken … o kadar ucuz.', 'früh buchen.'),
  },
  {
    id: 'listen-zwar',
    type: 'listening_choice',
    topic: 'zwar-je',
    concept: 'pair-zwar',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das Auto ist zwar schon alt, aber es fährt noch sehr gut.',
    question: l('What does the person think about the car?', 'Kişi araba hakkında ne düşünüyor?', 'Was denkt die Person über das Auto?'),
    options: ['old but still good', 'new and good', 'old and bad'],
    answer: 0,
    explanation: l('zwar alt, aber gut.', 'gerçi eski ama iyi.', 'alt, aber gut.'),
  },

  ...pairDrills(),
]

export const UNIT_B1_14_ZWEITEILIGE_KONNEKTOREN: CourseUnit = {
  level: 'B1',
  number: 14,
  slug: 'zweiteilige-konnektoren',
  titleDe: 'Sowohl … als auch',
  title: l('Both … and', 'Hem … hem de', 'Sowohl … als auch'),
  goal: l(
    'By the end of this unit you can compare options and weigh pros and cons with two-part connectors: sowohl … als auch, weder … noch, entweder … oder, nicht nur … sondern auch, zwar … aber, je … desto.',
    'Bu ünitenin sonunda iki parçalı bağlaçlarla seçenekleri karşılaştırıp artıları ve eksileri tartabilirsin: sowohl … als auch, weder … noch, entweder … oder, nicht nur … sondern auch, zwar … aber, je … desto.',
    'Am Ende dieser Einheit vergleichst du mit zweiteiligen Konnektoren.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'paare', label: l('sowohl, weder, entweder, nicht nur', 'sowohl, weder, entweder, nicht nur', 'zweiteilige Konnektoren') },
    { key: 'zwar-je', label: l('zwar … aber, je … desto', 'zwar … aber, je … desto', 'zwar … aber, je … desto') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Connectors that always come in pairs.', 'Her zaman çift olarak gelen bağlaçlar.', 'Konnektoren im Doppelpack.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Two-part connectors', 'İki parçalı bağlaçlar', 'Zweiteilige Konnektoren'),
          body: l('They connect two words or two parts of a sentence. Learn them as pairs.', 'İki kelimeyi ya da cümlenin iki kısmını bağlarlar. Çift olarak öğren.', 'Als Paar lernen.'),
          table: {
            head: [l('Connector', 'Bağlaç', 'Konnektor'), l('Meaning', 'Anlam', 'Bedeutung'), l('Example', 'Örnek', 'Beispiel')],
            rows: [
              ['sowohl … als auch', 'beides', 'sowohl Tee als auch Kaffee'],
              ['nicht nur … sondern auch', 'beides (betont)', 'nicht nur klug, sondern auch nett'],
              ['weder … noch', 'keins', 'weder Zeit noch Geld'],
              ['entweder … oder', 'eins von zwei', 'entweder heute oder morgen'],
              ['zwar … aber', 'Einschränkung', 'zwar teuer, aber gut'],
            ],
          },
          tip: l('weder … noch is already negative: never add nicht or kein!', 'weder … noch zaten olumsuzdur: asla nicht ya da kein ekleme!', 'kein doppeltes Nein.'),
        },
        {
          title: l('je … desto', 'je … desto', 'je … desto'),
          body: l(
            'Je + comparative + … + verb (end), desto/umso + comparative + verb + subject. Je mehr ich übe, desto besser spreche ich.',
            'Je + karşılaştırma + … + fiil (son), desto/umso + karşılaştırma + fiil + özne. Je mehr ich übe, desto besser spreche ich.',
            'Je mehr …, desto besser …'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Lisa and Ben have to choose between two homes.', 'Lisa ve Ben iki ev arasında seçim yapmak zorunda.', 'Lisa und Ben wählen eine Wohnung.'),
      dialogue: [
        { speaker: 'Lisa', de: 'Wir müssen uns entscheiden: **entweder** die Wohnung in der Stadt **oder** das Haus auf dem Land.', translation: l('We have to decide: either the flat in town or the house in the country.', 'Karar vermemiz lazım: ya şehirdeki daire ya da kırsaldaki ev.', '') },
        { speaker: 'Ben', de: 'Das Haus ist **zwar** größer, **aber** es gibt dort **weder** einen Supermarkt **noch** einen Bahnhof.', translation: l('The house is bigger, but there’s neither a supermarket nor a station there.', 'Ev gerçi daha büyük ama orada ne süpermarket ne de istasyon var.', '') },
        { speaker: 'Lisa', de: 'In der Stadt sind **sowohl** die Arbeit **als auch** die Schule nah.', translation: l('In town both work and school are close.', 'Şehirde hem iş hem de okul yakın.', '') },
        { speaker: 'Ben', de: 'Und die Wohnung hat **nicht nur** einen Balkon, **sondern auch** einen Aufzug.', translation: l('And the flat has not only a balcony but also a lift.', 'Daire sadece balkonlu değil, asansörlü de.', '') },
        { speaker: 'Lisa', de: 'Sie ist **zwar** teurer, **aber** **je** länger wir überlegen, **desto** klarer wird es mir.', translation: l('It’s more expensive, but the longer we think about it, the clearer it becomes to me.', 'Gerçi daha pahalı ama ne kadar uzun düşünürsek benim için o kadar netleşiyor.', '') },
        { speaker: 'Ben', de: 'Also: die Stadt! 🏙️', translation: l('So: the city! 🏙️', 'Yani: şehir! 🏙️', '') },
      ],
      examples: [
        { de: 'Ich spreche **sowohl** Türkisch **als auch** Deutsch.', translation: l('I speak both Turkish and German.', 'Hem Türkçe hem de Almanca konuşuyorum.', '') },
        { de: 'Er isst **weder** Fleisch **noch** Fisch.', translation: l('He eats neither meat nor fish.', 'Ne et ne de balık yiyor.', '') },
        { de: 'Wir fahren **entweder** heute **oder** morgen.', translation: l('We’re going either today or tomorrow.', 'Ya bugün ya da yarın gidiyoruz.', '') },
        { de: 'Sie ist **nicht nur** klug, **sondern auch** lustig.', translation: l('She’s not only clever but also funny.', 'Sadece akıllı değil, eğlenceli de.', '') },
        { de: 'Das Auto ist **zwar** alt, **aber** zuverlässig.', translation: l('The car is old, but reliable.', 'Araba gerçi eski ama güvenilir.', '') },
        { de: '**Je** mehr ich übe, **desto** besser werde ich.', translation: l('The more I practise, the better I get.', 'Ne kadar çok pratik yaparsam o kadar iyi oluyorum.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which pair? Both, none or one?', 'Hangi çift? İkisi de, hiçbiri ya da biri?', 'Welches Paar?'),
      exercises: ['match-paare', 'sort-bedeutung', 'paar-sowohl', 'paar-weder', 'mc-weder-kein', 'tf-je', 'select-richtig', 'image-weder', 'paar-entweder'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Compare and decide.', 'Karşılaştır ve karar ver.', 'Vergleiche und entscheide.'),
      exercises: [
        'fill-als-auch',
        'fill-sondern',
        'fill-desto',
        'build-entweder',
        'build-zwar',
        'build-je',
        'fix-weder-nicht',
        'fix-sowohl',
        'fix-nicht-nur',
        'tr-weder',
        'tr-sowohl',
        'ordering-vergleich',
        'dialog-urlaub',
        'dialog-restaurant',
        'paar-nichtnur',
        'paar-zwar',
        'paar-je',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Lisa writes about the big decision.', 'Lisa büyük kararı anlatıyor.', 'Lisa über die große Entscheidung.'),
      passage: [
        'Wir hatten zwei Möglichkeiten: **entweder** die Wohnung in der Stadt **oder** das Haus auf dem Land.',
        'Auf dem Land ist es **zwar** ruhig und grün, **aber** dort gibt es **weder** einen Supermarkt **noch** einen Bahnhof in der Nähe.',
        'In der Stadt sind **sowohl** die Arbeit **als auch** die Schule nah. Die Wohnung hat **nicht nur** einen Balkon, **sondern auch** einen Aufzug.',
        'Die Stadtwohnung ist **zwar** teurer, **aber** wir nehmen sie. **Je** länger wir dort wohnen, **desto** glücklicher sind wir!',
      ],
      glossary: [
        { de: 'die Möglichkeit', note: l('option, possibility', 'seçenek, olanak', 'Option') },
        { de: 'in der Nähe', note: l('nearby', 'yakında', 'nicht weit') },
        { de: 'der Aufzug', note: l('lift, elevator', 'asansör', 'Fahrstuhl') },
      ],
      exercises: ['read-wohnung', 'read-stadt', 'read-land', 'read-entscheidung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Both, none or one?', 'İkisi de, hiçbiri ya da biri?', 'Beides, keins oder eins?'),
      exercises: ['listen-sowohl', 'listen-weder', 'listen-je', 'listen-zwar'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Compare two options (city/country, bus/bike, two jobs …) and decide.', 'İki seçeneği karşılaştır (şehir/kırsal, otobüs/bisiklet, iki iş …) ve karar ver.', 'Vergleiche zwei Optionen.'),
      points: [
        l('„Option A ist zwar …, aber …“', '„A seçeneği gerçi …, ama …“', 'zwar … aber'),
        l('„Option B hat sowohl … als auch …“', '„B seçeneği hem … hem de …“', 'sowohl … als auch'),
        l('„Dort gibt es weder … noch …“', '„Orada ne … ne de … var“', 'weder … noch'),
        l('Decision: „Je …, desto …“ / „Deshalb nehme ich …“', 'Karar: „Je …, desto …“ / „Deshalb nehme ich …“', 'Entscheidung'),
      ],
      model: [
        'Ich fahre entweder mit dem Bus oder mit dem Fahrrad zur Arbeit.',
        'Der Bus ist zwar bequem, aber oft zu spät.',
        'Mit dem Fahrrad bin ich sowohl schneller als auch fitter.',
        'Je mehr ich Rad fahre, desto besser fühle ich mich – deshalb nehme ich das Fahrrad.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short text (at least 5 sentences): compare two cities, jobs or holidays – use at least three two-part connectors.',
        'Kısa bir metin yaz (en az 5 cümle): iki şehri, işi ya da tatili karşılaştır – en az üç iki parçalı bağlaç kullan.',
        'Schreib einen Vergleich (mindestens 5 Sätze) mit drei zweiteiligen Konnektoren.'
      ),
      minSentences: 5,
      checks: [
        { label: l('sowohl … als auch / nicht nur … sondern auch', 'sowohl … als auch / nicht nur … sondern auch', 'sowohl / nicht nur'), pattern: '(sowohl[^.!?]*als auch|nicht nur[^.!?]*sondern auch)' },
        { label: l('weder … noch / entweder … oder', 'weder … noch / entweder … oder', 'weder / entweder'), pattern: '(weder[^.!?]*noch|entweder[^.!?]*oder)' },
        { label: l('zwar … aber / je … desto', 'zwar … aber / je … desto', 'zwar / je'), pattern: '(zwar[^.!?]*aber|[Jj]e[^.!?]*(desto|umso))' },
      ],
      model: [
        'Ich möchte im Sommer entweder nach Spanien oder nach Norwegen reisen.',
        'Spanien ist zwar heiß, aber das Essen ist fantastisch.',
        'In Norwegen gibt es sowohl Berge als auch Fjorde.',
        'Norwegen ist leider weder billig noch warm.',
        'Je länger ich nachdenke, desto mehr freue ich mich auf Spanien!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Complete the pair – 60 seconds.', 'Çifti tamamla – 60 saniye.', 'Ergänze das Paar – 60 Sekunden.'),
      seconds: 60,
      pool: [...PAIRS.map(([id]) => `paar-${id}`), 'mc-weder-kein'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('sowohl … als auch · nicht nur … sondern auch (both)', 'sowohl … als auch · nicht nur … sondern auch (ikisi de)', 'beides'),
      l('weder … noch (neither … nor) – no extra negation', 'weder … noch (ne … ne) – ekstra olumsuzluk yok', 'keins'),
      l('entweder … oder (either … or)', 'entweder … oder (ya … ya da)', 'eins'),
      l('zwar … aber · je … desto', 'zwar … aber · je … desto', 'zwar / je'),
    ],
    mistakes: [
      { wrong: 'weder Tee noch keinen Kaffee', right: 'weder Tee noch Kaffee', note: l('No extra kein.', 'Ekstra kein yok.', 'kein kein.') },
      { wrong: 'sowohl Tee und Kaffee', right: 'sowohl Tee als auch Kaffee', note: l('als auch.', 'als auch.', 'als auch.') },
      { wrong: 'nicht nur …, aber auch …', right: 'nicht nur …, sondern auch …', note: l('sondern auch.', 'sondern auch.', 'sondern.') },
      { wrong: 'Je mehr ich lerne, desto ich werde besser.', right: 'Je mehr ich lerne, desto besser werde ich.', note: l('desto + comparative + verb.', 'desto + karşılaştırma + fiil.', 'desto besser werde ich.') },
    ],
  },
}
