import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'sich beschweren über', emoji: '😤', translation: l('to complain about', '… hakkında şikâyet etmek', 'sagen, dass man unzufrieden ist'), example: 'Ich möchte mich über den Service beschweren.' },
  { word: 'die Reklamation', emoji: '📦', translation: l('complaint (about goods)', 'ürün şikâyeti / iade talebi', 'man bringt kaputte Ware zurück'), example: 'Ich habe eine Reklamation.' },
  { word: 'kaputt / defekt', emoji: '💥', translation: l('broken / defective', 'bozuk / arızalı', 'funktioniert nicht'), example: 'Der Wasserkocher ist defekt.' },
  { word: 'umtauschen', emoji: '🔄', translation: l('to exchange', 'değiştirmek', 'gegen etwas anderes tauschen'), example: 'Kann ich die Hose umtauschen?' },
  { word: 'das Geld zurückbekommen', emoji: '💶', translation: l('to get a refund', 'parayı geri almak', 'Erstattung'), example: 'Ich möchte mein Geld zurückbekommen.' },
  { word: 'der Kassenbon', emoji: '🧾', translation: l('receipt', 'fiş', 'Quittung'), example: 'Haben Sie den Kassenbon noch?' },
  { word: 'die Garantie', emoji: '🛡️', translation: l('warranty', 'garanti', 'zwei Jahre Schutz'), example: 'Das Gerät hat zwei Jahre Garantie.' },
  { word: 'die Lieferung', emoji: '🚚', translation: l('delivery', 'teslimat', 'die Ware kommt'), example: 'Die Lieferung ist zu spät gekommen.' },
  { word: 'unzufrieden', emoji: '😞', translation: l('dissatisfied', 'memnuniyetsiz', 'nicht zufrieden'), example: 'Ich bin mit dem Hotel sehr unzufrieden.' },
  { word: 'Ich erwarte, dass …', emoji: '☝️', translation: l('I expect that …', '… -masını bekliyorum', 'Forderung'), example: 'Ich erwarte, dass Sie mir das Geld zurückzahlen.' },
  { word: 'Könnten Sie bitte …?', emoji: '🙏', translation: l('Could you please …?', '… -abilir misiniz lütfen?', 'höfliche Bitte'), example: 'Könnten Sie das bitte reparieren?' },
  { word: 'die Entschädigung', emoji: '🤝', translation: l('compensation', 'tazminat', 'Geld als Ausgleich'), example: 'Ich bitte um eine Entschädigung.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Beschwerde', gender: 'f', plural: 'die Beschwerden', translation: l('complaint', 'şikâyet', 'Beschwerde') },
  { word: 'Kunde', gender: 'm', plural: 'die Kunden', translation: l('customer', 'müşteri', 'Kunde') },
  { word: 'Ware', gender: 'f', plural: 'die Waren', translation: l('goods', 'mal, ürün', 'Ware') },
  { word: 'Bestellung', gender: 'f', plural: 'die Bestellungen', translation: l('order', 'sipariş', 'Bestellung') },
  { word: 'Rechnung', gender: 'f', plural: 'die Rechnungen', translation: l('invoice', 'fatura', 'Rechnung') },
  { word: 'Mangel', gender: 'm', plural: 'die Mängel', translation: l('defect', 'kusur', 'Mangel') },
  { word: 'Frist', gender: 'f', plural: 'die Fristen', translation: l('deadline', 'süre, mühlet', 'Frist') },
  { word: 'Kundenservice', gender: 'm', translation: l('customer service', 'müşteri hizmetleri', 'Kundenservice') },
]

/** [id, rude sentence, polite version, other wrong] */
const POLITE: [string, string, string, [string, string]][] = [
  ['reparieren', 'Reparieren Sie das!', 'Könnten Sie das bitte reparieren?', ['Sie reparieren das jetzt.', 'Das reparieren, sofort!']],
  ['geld', 'Ich will mein Geld!', 'Ich hätte gern mein Geld zurück.', ['Geld her!', 'Mein Geld ist weg.']],
  ['chef', 'Holen Sie den Chef!', 'Könnte ich bitte mit Ihrem Vorgesetzten sprechen?', ['Wo ist der Chef?', 'Der Chef soll kommen!']],
  ['schnell', 'Das muss schnell gehen!', 'Ich wäre Ihnen dankbar, wenn das schnell ginge.', ['Schnell, schnell!', 'Machen Sie schneller!']],
  ['falsch', 'Sie haben alles falsch gemacht!', 'Leider ist bei meiner Bestellung ein Fehler passiert.', ['Alles ist falsch!', 'Sie sind falsch.']],
]

function politeDrills(): Exercise[] {
  return POLITE.map(([id, rude, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `hoeflich-${id}`,
      type: 'multiple_choice' as const,
      topic: 'hoeflich-fordern',
      concept: 'polite-version',
      skill: 'speaking' as const,
      difficulty: 2 as const,
      prompt: `„${rude}“ – Wie sagt man das höflich?`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`Polite: „${right}“`, `Kibar: „${right}“`, `Höflich: „${right}“`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-reklamation',
    type: 'matching',
    topic: 'reklamation-wortschatz',
    concept: 'complaint-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match word and symbol.', 'Kelimeyi sembolle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'der Kassenbon', right: '🧾' },
      { left: 'umtauschen', right: '🔄' },
      { left: 'die Garantie', right: '🛡️' },
      { left: 'die Lieferung', right: '🚚' },
      { left: 'kaputt', right: '💥' },
    ],
    explanation: l('Words for complaints.', 'Şikâyet kelimeleri.', 'Reklamation.'),
  },
  {
    id: 'sort-problem-forderung',
    type: 'categorize',
    topic: 'beschwerdebrief',
    concept: 'problem-demand',
    skill: 'writing',
    difficulty: 2,
    instructions: l('Problem or demand?', 'Sorun mu talep mi?', 'Problem oder Forderung?'),
    categories: ['Problem', 'Forderung'],
    items: [
      { text: 'Das Paket kam zwei Wochen zu spät.', category: 0 },
      { text: 'Ich bitte Sie, mir den Betrag zu erstatten.', category: 1 },
      { text: 'Der Bildschirm hat einen Kratzer.', category: 0 },
      { text: 'Ich erwarte eine schnelle Antwort.', category: 1 },
      { text: 'Die Heizung funktioniert nicht.', category: 0 },
      { text: 'Bitte schicken Sie mir ein neues Gerät.', category: 1 },
    ],
    explanation: l('A complaint letter: first the problem, then the demand.', 'Şikâyet mektubu: önce sorun, sonra talep.', 'Problem → Forderung.'),
    practice: ['hoeflich-reparieren'],
  },
  {
    id: 'mc-ueber',
    type: 'multiple_choice',
    topic: 'reklamation-wortschatz',
    concept: 'beschweren-ueber',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Ich möchte mich ___ den Lärm beschweren.',
    options: ['über', 'für', 'an'],
    answer: 0,
    explanation: l('sich beschweren über + accusative.', 'sich beschweren über + Akk.', 'über.'),
    examples: ['Ich möchte mich **über** den Lärm beschweren.'],
    practice: ['fill-mich'],
  },
  {
    id: 'tf-kassenbon',
    type: 'true_false',
    topic: 'im-geschaeft',
    concept: 'shop-rules',
    skill: 'reading',
    difficulty: 1,
    statement: 'Wenn man etwas umtauschen möchte, braucht man meistens den Kassenbon.',
    answer: true,
    explanation: l('Shops usually ask for the receipt (Kassenbon).', 'Mağazalar genelde fiş (Kassenbon) ister.', 'Kassenbon.'),
  },
  {
    id: 'select-hoeflich',
    type: 'multiple_select',
    topic: 'hoeflich-fordern',
    concept: 'polite-forms',
    skill: 'speaking',
    difficulty: 2,
    promptL10n: l('Which sentences are polite? Select all.', 'Hangi cümleler kibar? Hepsini seç.', 'Welche Sätze sind höflich?'),
    options: ['Könnten Sie mir bitte helfen?', 'Ich hätte gern eine Erklärung.', 'Machen Sie das sofort!', 'Würden Sie das bitte prüfen?', 'Das ist Ihr Problem.'],
    answers: [0, 1, 3],
    explanation: l('Konjunktiv II = polite: könnten, hätte gern, würden.', 'Konjunktiv II = kibar: könnten, hätte gern, würden.', 'Konjunktiv II.'),
  },
  {
    id: 'image-defekt',
    type: 'image_choice',
    topic: 'im-geschaeft',
    concept: 'problem',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Das Handy geht nicht mehr an. Der Akku ist leer und lädt nicht.',
    options: [
      { emoji: '🪫', label: 'Akku defekt' },
      { emoji: '👕', label: 'Hose zu klein' },
      { emoji: '🍞', label: 'Brot alt' },
      { emoji: '🚚', label: 'Lieferung spät' },
    ],
    answer: 0,
    explanation: l('The battery is defective.', 'Batarya arızalı.', 'Akku defekt.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-mich',
    type: 'fill_blank',
    topic: 'reklamation-wortschatz',
    concept: 'beschweren-ueber',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich möchte ___ über die Lieferung beschweren.',
    accepted: ['mich'],
    base: 'sich beschweren',
    explanation: l('Reflexive verb: ich beschwere mich.', 'Dönüşlü fiil: ich beschwere mich.', 'mich.'),
    examples: ['Ich möchte **mich** über die Lieferung beschweren.'],
  },
  {
    id: 'fill-koennten',
    type: 'fill_blank',
    topic: 'hoeflich-fordern',
    concept: 'polite-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: '___ Sie mir bitte ein neues Gerät schicken?',
    accepted: ['Könnten', 'Würden'],
    base: 'können → Konjunktiv II',
    explanation: l('Polite request: Könnten Sie …?', 'Kibar rica: Könnten Sie …?', 'Könnten.'),
    examples: ['**Könnten** Sie mir bitte ein neues Gerät schicken?'],
  },
  {
    id: 'fill-umtauschen',
    type: 'fill_blank',
    topic: 'im-geschaeft',
    concept: 'exchange',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Jacke ist zu klein. Kann ich sie ___?',
    accepted: ['umtauschen'],
    base: 'tauschen …',
    explanation: l('umtauschen = to exchange.', 'umtauschen = değiştirmek.', 'umtauschen.'),
    examples: ['Kann ich sie **umtauschen**?'],
  },
  {
    id: 'build-erwarte',
    type: 'sentence_builder',
    topic: 'beschwerdebrief',
    concept: 'demand',
    skill: 'grammar',
    difficulty: 3,
    chips: ['zurückzahlen', 'dass', 'Ich erwarte,', 'Sie mir den Betrag'],
    answers: [['Ich erwarte,', 'dass', 'Sie mir den Betrag', 'zurückzahlen']],
    translation: l('I expect you to refund me the amount.', 'Tutarı bana geri ödemenizi bekliyorum.', 'Ich erwarte, dass Sie mir den Betrag zurückzahlen.'),
    explanation: l('dass → verb at the end (not separated).', 'dass → fiil sonda (ayrılmaz).', '… zurückzahlen.'),
    examples: ['Ich erwarte, dass Sie mir den Betrag **zurückzahlen**.'],
  },
  {
    id: 'build-dankbar',
    type: 'sentence_builder',
    topic: 'hoeflich-fordern',
    concept: 'polite-forms',
    skill: 'grammar',
    difficulty: 3,
    chips: ['wenn', 'Ich wäre Ihnen dankbar,', 'antworten würden', 'Sie bald'],
    answers: [['Ich wäre Ihnen dankbar,', 'wenn', 'Sie bald', 'antworten würden']],
    translation: l('I would be grateful if you replied soon.', 'Yakında cevap verirseniz minnettar olurum.', 'Ich wäre Ihnen dankbar, wenn Sie bald antworten würden.'),
    explanation: l('Very polite letter phrase with Konjunktiv II.', 'Konjunktiv II ile çok kibar mektup kalıbı.', 'Ich wäre Ihnen dankbar, wenn …'),
    examples: ['Ich wäre Ihnen dankbar, wenn Sie bald **antworten würden**.'],
  },
  {
    id: 'build-kaputt',
    type: 'sentence_builder',
    topic: 'im-geschaeft',
    concept: 'problem',
    skill: 'grammar',
    difficulty: 2,
    chips: ['gekauft,', 'aber', 'Ich habe den Föhn letzte Woche', 'er ist schon kaputt'],
    answers: [['Ich habe den Föhn letzte Woche', 'gekauft,', 'aber', 'er ist schon kaputt']],
    translation: l('I bought the hairdryer last week, but it’s already broken.', 'Saç kurutma makinesini geçen hafta aldım ama şimdiden bozuldu.', 'Ich habe den Föhn letzte Woche gekauft, aber er ist schon kaputt.'),
    explanation: l('Describe the problem: when bought + what is wrong.', 'Sorunu anlat: ne zaman alındı + ne sorun var.', 'Problem beschreiben.'),
    examples: ['Ich habe den Föhn letzte Woche gekauft, **aber** er ist schon kaputt.'],
  },
  {
    id: 'fix-beschweren',
    type: 'error_correction',
    topic: 'reklamation-wortschatz',
    concept: 'beschweren-ueber',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich beschwere über das Essen.',
    accepted: ['Ich beschwere mich über das Essen.'],
    explanation: l('Reflexive: sich beschweren → ich beschwere mich.', 'Dönüşlü: sich beschweren → ich beschwere mich.', 'mich.'),
    examples: ['Ich beschwere **mich** über das Essen.'],
  },
  {
    id: 'fix-haette',
    type: 'error_correction',
    topic: 'hoeflich-fordern',
    concept: 'polite-forms',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe gern mein Geld zurück.',
    accepted: ['Ich hätte gern mein Geld zurück.'],
    explanation: l('Polite wish: ich hätte gern.', 'Kibar istek: ich hätte gern.', 'hätte.'),
    examples: ['Ich **hätte** gern mein Geld zurück.'],
  },
  {
    id: 'fix-brief',
    type: 'error_correction',
    topic: 'beschwerdebrief',
    concept: 'letter-form',
    skill: 'writing',
    difficulty: 2,
    sentence: 'Sehr geehrte Damen und Herren, ich schreibe dir wegen meiner Bestellung.',
    accepted: ['Sehr geehrte Damen und Herren, ich schreibe Ihnen wegen meiner Bestellung.'],
    explanation: l('Formal letter → Sie / Ihnen, not du / dir.', 'Resmî mektup → Sie / Ihnen, du / dir değil.', 'Ihnen.'),
    examples: ['… ich schreibe **Ihnen** wegen meiner Bestellung.'],
  },
  {
    id: 'tr-umtauschen',
    type: 'translation',
    topic: 'im-geschaeft',
    concept: 'exchange',
    skill: 'writing',
    difficulty: 2,
    source: l('I would like to exchange these shoes.', 'Bu ayakkabıları değiştirmek istiyorum.', 'I would like to exchange these shoes.'),
    accepted: ['Ich möchte diese Schuhe umtauschen.', 'Ich würde diese Schuhe gern umtauschen.', 'Ich würde gern diese Schuhe umtauschen.'],
    explanation: l('Ich möchte … umtauschen.', 'Ich möchte … umtauschen.', 'umtauschen.'),
    examples: ['Ich möchte diese Schuhe **umtauschen**.'],
  },
  {
    id: 'tr-funktioniert',
    type: 'translation',
    topic: 'im-geschaeft',
    concept: 'problem',
    skill: 'writing',
    difficulty: 2,
    source: l('The printer doesn’t work.', 'Yazıcı çalışmıyor.', 'The printer doesn’t work.'),
    accepted: ['Der Drucker funktioniert nicht.', 'Der Drucker geht nicht.'],
    explanation: l('funktionieren = to work (machines).', 'funktionieren = çalışmak (makineler).', 'funktioniert nicht.'),
    examples: ['Der Drucker **funktioniert nicht**.'],
  },
  {
    id: 'ordering-brief',
    type: 'ordering',
    topic: 'beschwerdebrief',
    concept: 'letter-form',
    skill: 'writing',
    difficulty: 2,
    promptL10n: l('Put the complaint letter in order.', 'Şikâyet mektubunu sırala.', 'Ordne den Beschwerdebrief.'),
    items: ['Ich bitte Sie daher, mir ein neues Gerät zu schicken.', 'Sehr geehrte Damen und Herren,', 'am 3. Mai habe ich bei Ihnen eine Kaffeemaschine bestellt. Leider ist sie defekt angekommen.', 'Mit freundlichen Grüßen'],
    answer: ['Sehr geehrte Damen und Herren,', 'am 3. Mai habe ich bei Ihnen eine Kaffeemaschine bestellt. Leider ist sie defekt angekommen.', 'Ich bitte Sie daher, mir ein neues Gerät zu schicken.', 'Mit freundlichen Grüßen'],
    explanation: l('Greeting → problem → demand → closing.', 'Hitap → sorun → talep → kapanış.', 'Anrede → Problem → Forderung → Gruß.'),
  },
  {
    id: 'dialog-verkaeufer',
    type: 'dialogue',
    topic: 'im-geschaeft',
    concept: 'shop-dialogue',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Verkäufer', de: 'Guten Tag, wie kann ich Ihnen helfen?' }],
    options: ['Guten Tag, ich habe eine Reklamation. Der Toaster funktioniert nicht.', 'Ich will Toaster.', 'Helfen Sie mir nicht.'],
    answer: 0,
    explanation: l('Say what the problem is – clearly and politely.', 'Sorunu açık ve kibarca söyle.', 'Problem nennen.'),
  },
  {
    id: 'dialog-gutschein',
    type: 'dialogue',
    topic: 'im-geschaeft',
    concept: 'negotiate',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Verkäuferin', de: 'Geld zurück geht leider nicht. Ich kann Ihnen aber einen Gutschein geben.' }],
    options: ['Hm, das ist nicht ideal. Könnte ich das Gerät stattdessen umtauschen?', 'Gutschein ist Geld.', 'Nein. Tschüss.'],
    answer: 0,
    explanation: l('Politely negotiate an alternative.', 'Kibarca bir alternatif üzerinde pazarlık et.', 'Alternative vorschlagen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-grund',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-brief',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Warum schreibt Frau Demir?',
    options: ['Ihr Hotelzimmer war nicht wie beschrieben.', 'Sie möchte ein Zimmer buchen.', 'Sie hat etwas im Hotel vergessen.'],
    answer: 0,
    explanation: l('„… das Zimmer entsprach leider nicht der Beschreibung.“', '„… das Zimmer entsprach leider nicht der Beschreibung.“', 'Zimmer.'),
  },
  {
    id: 'read-probleme',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-brief',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welche Probleme gab es?',
    options: ['Kein Meerblick und eine laute Baustelle.', 'Das Essen war kalt.', 'Das Personal war unfreundlich.'],
    answer: 0,
    explanation: l('„Statt Meerblick … eine Baustelle … sehr laut.“', '„Statt Meerblick … eine Baustelle … sehr laut.“', 'Baustelle.'),
  },
  {
    id: 'read-rezeption',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-brief',
    skill: 'reading',
    difficulty: 2,
    statement: 'An der Rezeption hat man ihr sofort ein anderes Zimmer gegeben.',
    answer: false,
    explanation: l('„… hieß es, das Hotel sei ausgebucht.“', '„… hieß es, das Hotel sei ausgebucht.“', 'falsch.'),
  },
  {
    id: 'read-forderung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-brief',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was fordert Frau Demir?',
    options: ['30 Prozent des Preises zurück.', 'Eine kostenlose Woche.', 'Nichts, sie möchte nur informieren.'],
    answer: 0,
    explanation: l('„… erwarte ich, dass Sie mir 30 Prozent des Preises erstatten.“', '„… erwarte ich, dass Sie mir 30 Prozent des Preises erstatten.“', '30 Prozent.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-hose',
    type: 'listening_choice',
    topic: 'im-geschaeft',
    concept: 'exchange',
    skill: 'listening',
    difficulty: 1,
    audio: 'Die Hose ist leider zu klein. Kann ich sie gegen eine größere umtauschen?',
    question: l('What does the customer want?', 'Müşteri ne istiyor?', 'Was möchte die Kundin?'),
    options: ['a bigger size', 'a smaller size', 'a refund'],
    answer: 0,
    explanation: l('„gegen eine größere umtauschen“', '„gegen eine größere umtauschen“', 'größere.'),
  },
  {
    id: 'listen-garantie',
    type: 'listening_choice',
    topic: 'im-geschaeft',
    concept: 'shop-rules',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das Gerät hat noch Garantie. Wir schicken es zur Reparatur, das dauert etwa zwei Wochen.',
    question: l('What happens with the device?', 'Cihaza ne olacak?', 'Was passiert mit dem Gerät?'),
    options: ['It is sent for repair.', 'The customer gets a new one immediately.', 'Nothing – no warranty.'],
    answer: 0,
    explanation: l('„Wir schicken es zur Reparatur.“', '„Wir schicken es zur Reparatur.“', 'Reparatur.'),
  },
  {
    id: 'listen-hotline',
    type: 'listening_choice',
    topic: 'hoeflich-fordern',
    concept: 'polite-forms',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich warte jetzt seit drei Wochen auf meine Lieferung. Könnten Sie bitte nachsehen, wo das Paket ist?',
    question: l('What is the problem?', 'Sorun ne?', 'Was ist das Problem?'),
    options: ['The parcel hasn’t arrived.', 'The parcel is damaged.', 'The wrong item came.'],
    answer: 0,
    explanation: l('„seit drei Wochen auf meine Lieferung“', '„seit drei Wochen auf meine Lieferung“', 'Lieferung fehlt.'),
  },
  {
    id: 'listen-brief',
    type: 'listening_choice',
    topic: 'beschwerdebrief',
    concept: 'demand',
    skill: 'listening',
    difficulty: 2,
    audio: 'Bitte überweisen Sie mir den Betrag bis zum 15. Juni zurück. Sonst wende ich mich an die Verbraucherzentrale.',
    question: l('What is the deadline?', 'Son tarih ne?', 'Bis wann?'),
    options: ['15 June', '15 July', '5 June'],
    answer: 0,
    explanation: l('„bis zum 15. Juni“', '„bis zum 15. Juni“', '15. Juni.'),
  },

  ...politeDrills(),
]

export const UNIT_B1_21_REKLAMATION: CourseUnit = {
  level: 'B1',
  number: 21,
  slug: 'reklamation',
  titleDe: 'Ich möchte mich beschweren',
  title: l('I’d like to complain', 'Şikâyet etmek istiyorum', 'Ich möchte mich beschweren'),
  goal: l(
    'By the end of this unit you can return or exchange goods in a shop, complain politely but firmly, and write a formal complaint letter with problem, demand and deadline.',
    'Bu ünitenin sonunda mağazada ürün iade edebilir ya da değiştirebilir, kibar ama kararlı şikâyet edebilir ve sorun, talep ve süre içeren resmî bir şikâyet mektubu yazabilirsin.',
    'Am Ende dieser Einheit reklamierst du höflich und schreibst einen Beschwerdebrief.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'reklamation-wortschatz', label: l('Complaint vocabulary', 'Şikâyet kelimeleri', 'Wortschatz') },
    { key: 'im-geschaeft', label: l('In the shop', 'Mağazada', 'Im Geschäft') },
    { key: 'hoeflich-fordern', label: l('Polite demands', 'Kibar talepler', 'Höflich fordern') },
    { key: 'beschwerdebrief', label: l('Complaint letter', 'Şikâyet mektubu', 'Beschwerdebrief') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('When something goes wrong …', 'Bir şeyler ters gittiğinde …', 'Wenn etwas schiefgeht …'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Polite but firm', 'Kibar ama kararlı', 'Höflich, aber bestimmt'),
          body: l(
            'Use Konjunktiv II to stay polite: Könnten Sie …? / Würden Sie …? / Ich hätte gern … / Ich wäre Ihnen dankbar, wenn … For firm demands: Ich erwarte, dass … / Ich bitte Sie, … zu …',
            'Kibar kalmak için Konjunktiv II kullan: Könnten Sie …? / Würden Sie …? / Ich hätte gern … / Ich wäre Ihnen dankbar, wenn … Kararlı talepler için: Ich erwarte, dass … / Ich bitte Sie, … zu …',
            'Konjunktiv II + klare Forderung.'
          ),
          examples: [
            { de: '**Könnten** Sie das bitte reparieren?', translation: l('Could you please repair it?', 'Bunu tamir edebilir misiniz lütfen?', '') },
            { de: '**Ich erwarte, dass** Sie mir den Betrag erstatten.', translation: l('I expect you to refund the amount.', 'Tutarı iade etmenizi bekliyorum.', '') },
          ],
        },
        {
          title: l('The complaint letter', 'Şikâyet mektubu', 'Der Beschwerdebrief'),
          body: l(
            'Formal letter with Sie. Structure: greeting (Sehr geehrte Damen und Herren,) → what happened (date, product) → the problem → your demand + deadline → closing (Mit freundlichen Grüßen).',
            'Sie ile resmî mektup. Yapı: hitap (Sehr geehrte Damen und Herren,) → ne oldu (tarih, ürün) → sorun → talebin + süre → kapanış (Mit freundlichen Grüßen).',
            'Anrede → Sachverhalt → Problem → Forderung → Gruß.'
          ),
          table: {
            head: [l('Part', 'Bölüm', 'Teil'), l('Phrase', 'Kalıp', 'Redemittel')],
            rows: [
              ['Anlass', 'Am … habe ich … bestellt.'],
              ['Problem', 'Leider ist … defekt.'],
              ['Forderung', 'Ich bitte Sie, … zu …'],
              ['Frist', 'bis zum 15. Juni'],
            ],
          },
        },
        {
          title: l('sich beschweren über', 'sich beschweren über', 'sich beschweren über'),
          body: l(
            'Reflexive verb + über + accusative: Ich beschwere mich über den Lärm. Also: sich ärgern über, sich wundern über.',
            'Dönüşlü fiil + über + Akk: Ich beschwere mich über den Lärm. Ayrıca: sich ärgern über, sich wundern über.',
            'Reflexiv + über + Akk.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Yusuf brings back headphones that stopped working.', 'Yusuf çalışmayı bırakan kulaklığı geri getiriyor.', 'Kopfhörer kaputt.'),
      dialogue: [
        { speaker: 'Yusuf', de: 'Guten Tag. Ich habe eine **Reklamation**. Diese Kopfhörer habe ich vor einem Monat hier gekauft.', translation: l('Hello. I have a complaint. I bought these headphones here a month ago.', 'Merhaba. Bir şikâyetim var. Bu kulaklığı bir ay önce buradan aldım.', '') },
        { speaker: 'Verkäuferin', de: 'Was ist denn das Problem?', translation: l('What’s the problem?', 'Sorun nedir?', '') },
        { speaker: 'Yusuf', de: 'Auf der linken Seite höre ich nichts mehr. Sie sind **defekt**.', translation: l('I can’t hear anything on the left side anymore. They’re defective.', 'Sol tarafta artık hiçbir şey duymuyorum. Arızalı.', '') },
        { speaker: 'Verkäuferin', de: 'Haben Sie den **Kassenbon** dabei?', translation: l('Do you have the receipt with you?', 'Fişiniz yanınızda mı?', '') },
        { speaker: 'Yusuf', de: 'Ja, hier. **Könnten** Sie mir neue geben? Oder **ich hätte gern** mein **Geld zurück**.', translation: l('Yes, here. Could you give me new ones? Or I’d like my money back.', 'Evet, buyurun. Bana yenisini verebilir misiniz? Ya da paramı geri almak isterim.', '') },
        { speaker: 'Verkäuferin', de: 'Kein Problem, das ist ein **Garantiefall**. Ich tausche sie Ihnen sofort **um**.', translation: l('No problem, it’s covered by the warranty. I’ll exchange them right away.', 'Sorun değil, garanti kapsamında. Hemen değiştiriyorum.', '') },
      ],
      examples: [
        { de: 'Ich möchte **mich über** den Service **beschweren**.', translation: l('I’d like to complain about the service.', 'Hizmetten şikâyet etmek istiyorum.', '') },
        { de: 'Der Wasserkocher ist **defekt**.', translation: l('The kettle is defective.', 'Su ısıtıcısı arızalı.', '') },
        { de: 'Kann ich die Jacke **umtauschen**?', translation: l('Can I exchange the jacket?', 'Ceketi değiştirebilir miyim?', '') },
        { de: '**Könnten** Sie mir bitte helfen?', translation: l('Could you please help me?', 'Bana yardım edebilir misiniz lütfen?', '') },
        { de: '**Ich erwarte**, dass Sie bis Freitag antworten.', translation: l('I expect you to reply by Friday.', 'Cumaya kadar cevap vermenizi bekliyorum.', '') },
        { de: '**Ich wäre Ihnen dankbar**, wenn …', translation: l('I would be grateful if …', '… minnettar olurum.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Words, problems and polite forms.', 'Kelimeler, sorunlar ve kibar biçimler.', 'Wörter und höfliche Formen.'),
      exercises: ['match-reklamation', 'sort-problem-forderung', 'hoeflich-reparieren', 'hoeflich-geld', 'mc-ueber', 'tf-kassenbon', 'select-hoeflich', 'image-defekt', 'hoeflich-chef'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Complain in the shop and in writing.', 'Mağazada ve yazılı olarak şikâyet et.', 'Reklamieren – mündlich und schriftlich.'),
      exercises: [
        'fill-mich',
        'fill-koennten',
        'fill-umtauschen',
        'build-erwarte',
        'build-dankbar',
        'build-kaputt',
        'fix-beschweren',
        'fix-haette',
        'fix-brief',
        'tr-umtauschen',
        'tr-funktioniert',
        'ordering-brief',
        'dialog-verkaeufer',
        'dialog-gutschein',
        'hoeflich-schnell',
        'hoeflich-falsch',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A complaint to a hotel.', 'Bir otele yazılmış şikâyet.', 'Beschwerde an ein Hotel.'),
      passage: [
        '**Sehr geehrte Damen und Herren,** vom 2. bis 9. August habe ich in Ihrem Hotel ein Doppelzimmer mit Meerblick gebucht. Leider entsprach das Zimmer nicht der Beschreibung.',
        'Statt Meerblick hatten wir einen Blick auf eine **Baustelle**, die ab 7 Uhr morgens sehr laut war. Als ich mich an der Rezeption **beschwert habe**, hieß es, das Hotel sei ausgebucht.',
        'Wir haben deshalb kaum geschlafen und waren mit dem Urlaub sehr **unzufrieden**.',
        'Ich **erwarte**, dass Sie mir 30 Prozent des Preises erstatten. **Ich wäre Ihnen dankbar**, wenn Sie bis zum 31. August antworten würden. **Mit freundlichen Grüßen**, Ayşe Demir',
      ],
      glossary: [
        { de: 'entsprechen + Dativ', note: l('to correspond to', '… -e uymak', 'gleich sein wie') },
        { de: 'die Baustelle', note: l('building site', 'şantiye', 'hier wird gebaut') },
        { de: 'ausgebucht', note: l('fully booked', 'tamamen dolu', 'kein Zimmer frei') },
        { de: 'erstatten', note: l('to refund', 'iade etmek', 'Geld zurückgeben') },
      ],
      exercises: ['read-grund', 'read-probleme', 'read-rezeption', 'read-forderung'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('In the shop and on the hotline.', 'Mağazada ve müşteri hattında.', 'Im Geschäft und an der Hotline.'),
      exercises: ['listen-hose', 'listen-garantie', 'listen-hotline', 'listen-brief'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Role play: your new coffee machine leaks. Go back to the shop.', 'Canlandırma: yeni kahve makinen su sızdırıyor. Mağazaya geri dön.', 'Rollenspiel: Kaffeemaschine kaputt.'),
      points: [
        l('Say what you bought and when.', 'Ne aldığını ve ne zaman aldığını söyle.', 'Was, wann?'),
        l('Describe the problem.', 'Sorunu anlat.', 'Problem'),
        l('Make a polite request: „Könnten Sie …?“', 'Kibar bir rica: „Könnten Sie …?“', 'Bitte'),
        l('React to an offer (voucher? exchange?).', 'Bir teklife tepki ver (kupon? değişim?).', 'Reagieren'),
      ],
      model: [
        'Guten Tag, ich habe diese Kaffeemaschine letzte Woche hier gekauft.',
        'Leider läuft unten immer Wasser heraus.',
        'Könnten Sie mir bitte eine neue geben?',
        'Einen Gutschein möchte ich lieber nicht – ich hätte gern eine funktionierende Maschine.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a complaint email to an online shop (at least 5 sentences): your order arrived late and damaged.',
        'Bir online mağazaya şikâyet e-postası yaz (en az 5 cümle): siparişin geç ve hasarlı geldi.',
        'Schreib eine Beschwerde-E-Mail (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Formal greeting (Sehr geehrte …)', 'Resmî hitap (Sehr geehrte …)', 'Anrede'), pattern: 'Sehr geehrte' },
        { label: l('Polite Konjunktiv II (könnten / würden / hätte / wäre)', 'Kibar Konjunktiv II (könnten / würden / hätte / wäre)', 'Konjunktiv II'), pattern: '\\b([Kk]önnten|[Ww]ürden|hätte|wäre)\\b' },
        { label: l('A demand (Ich erwarte / Ich bitte Sie)', 'Bir talep (Ich erwarte / Ich bitte Sie)', 'Forderung'), pattern: '([Ii]ch erwarte|[Ii]ch bitte Sie)' },
        { label: l('Formal closing (Mit freundlichen Grüßen)', 'Resmî kapanış (Mit freundlichen Grüßen)', 'Gruß'), pattern: 'Mit freundlichen Grüßen' },
      ],
      model: [
        'Sehr geehrte Damen und Herren, am 4. März habe ich bei Ihnen eine Lampe bestellt.',
        'Leider kam die Lieferung erst nach drei Wochen an.',
        'Außerdem war das Glas der Lampe kaputt.',
        'Ich bitte Sie, mir eine neue Lampe zu schicken, oder ich hätte gern mein Geld zurück.',
        'Ich wäre Ihnen dankbar, wenn Sie bis zum 20. März antworten würden. Mit freundlichen Grüßen, Can Yıldız',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Say it politely! – 60 seconds.', 'Kibarca söyle! – 60 saniye.', 'Sag es höflich! – 60 Sekunden.'),
      seconds: 60,
      pool: [...POLITE.map(([id]) => `hoeflich-${id}`), 'mc-ueber'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Complaint words: Reklamation, defekt, umtauschen, Kassenbon, Garantie', 'Şikâyet kelimeleri: Reklamation, defekt, umtauschen, Kassenbon, Garantie', 'Wortschatz'),
      l('Polite requests: Könnten Sie …? · Ich hätte gern … · Ich wäre Ihnen dankbar, wenn …', 'Kibar ricalar: Könnten Sie …? · Ich hätte gern … · Ich wäre Ihnen dankbar, wenn …', 'Höflich bitten'),
      l('Firm demands: Ich erwarte, dass … · Ich bitte Sie, … zu …', 'Kararlı talepler: Ich erwarte, dass … · Ich bitte Sie, … zu …', 'Fordern'),
      l('Complaint letter: greeting → problem → demand → deadline → closing', 'Şikâyet mektubu: hitap → sorun → talep → süre → kapanış', 'Beschwerdebrief'),
    ],
    mistakes: [
      { wrong: 'Ich beschwere über das Essen.', right: 'Ich beschwere mich über das Essen.', note: l('Reflexive.', 'Dönüşlü.', 'mich.') },
      { wrong: 'Ich habe gern mein Geld zurück.', right: 'Ich hätte gern mein Geld zurück.', note: l('Konjunktiv II.', 'Konjunktiv II.', 'hätte.') },
      { wrong: 'Sehr geehrte Damen und Herren, ich schreibe dir …', right: '… ich schreibe Ihnen …', note: l('Formal = Sie.', 'Resmî = Sie.', 'Sie.') },
      { wrong: 'Reparieren Sie das!', right: 'Könnten Sie das bitte reparieren?', note: l('Too direct.', 'Fazla doğrudan.', 'zu direkt.') },
    ],
  },
}
