import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Wohnungsanzeige', emoji: '📄', translation: l('flat advert', 'ev ilanı', 'Text: Wohnung zu vermieten'), example: 'Ich habe eine interessante Wohnungsanzeige gefunden.' },
  { word: 'die Kaltmiete', emoji: '🧊', translation: l('rent without bills', 'aidatsız kira', 'Miete ohne Nebenkosten'), example: 'Die Kaltmiete beträgt 650 Euro.' },
  { word: 'die Nebenkosten', emoji: '🔥', translation: l('utility costs', 'ek giderler', 'Heizung, Wasser, Müll'), example: 'Die Nebenkosten sind ziemlich hoch.' },
  { word: 'die Kaution', emoji: '💰', translation: l('deposit', 'depozito', 'Sicherheit für den Vermieter'), example: 'Die Kaution beträgt drei Monatsmieten.' },
  { word: 'der Vermieter / die Vermieterin', emoji: '🔑', translation: l('landlord / landlady', 'ev sahibi', 'gibt die Wohnung'), example: 'Der Vermieter wohnt im Erdgeschoss.' },
  { word: 'der Mieter / die Mieterin', emoji: '🏠', translation: l('tenant', 'kiracı', 'wohnt zur Miete'), example: 'Die Mieter müssen die Hausordnung beachten.' },
  { word: 'die Besichtigung', emoji: '👀', translation: l('viewing', 'evi görme', 'man schaut die Wohnung an'), example: 'Die Besichtigung ist am Samstag um 10 Uhr.' },
  { word: 'der Mietvertrag', emoji: '✍️', translation: l('rental contract', 'kira sözleşmesi', 'Vertrag für die Wohnung'), example: 'Wir haben den Mietvertrag unterschrieben.' },
  { word: 'die Hausordnung', emoji: '📜', translation: l('house rules', 'apartman kuralları', 'Regeln im Haus'), example: 'Laut Hausordnung ist ab 22 Uhr Ruhe.' },
  { word: 'möbliert', emoji: '🛋️', translation: l('furnished', 'eşyalı', 'mit Möbeln'), example: 'Das Zimmer ist möbliert.' },
  { word: 'die WG (Wohngemeinschaft)', emoji: '👫', translation: l('shared flat', 'paylaşımlı ev', 'mehrere Leute teilen eine Wohnung'), example: 'Ich wohne in einer WG mit drei Leuten.' },
  { word: 'kündigen', emoji: '📤', translation: l('to give notice', 'sözleşmeyi feshetmek', 'den Vertrag beenden'), example: 'Ich habe meine alte Wohnung gekündigt.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Miete', gender: 'f', plural: 'die Mieten', translation: l('rent', 'kira', 'Miete') },
  { word: 'Altbau', gender: 'm', plural: 'die Altbauten', translation: l('old building', 'eski bina', 'Altbau') },
  { word: 'Neubau', gender: 'm', plural: 'die Neubauten', translation: l('new building', 'yeni bina', 'Neubau') },
  { word: 'Quadratmeter', gender: 'm', plural: 'die Quadratmeter', translation: l('square metre', 'metrekare', 'Quadratmeter') },
  { word: 'Erdgeschoss', gender: 'n', translation: l('ground floor', 'zemin kat', 'Erdgeschoss') },
  { word: 'Stockwerk', gender: 'n', plural: 'die Stockwerke', translation: l('floor, storey', 'kat', 'Stockwerk') },
  { word: 'Nachbar', gender: 'm', plural: 'die Nachbarn', translation: l('neighbour', 'komşu', 'Nachbar') },
  { word: 'Treppenhaus', gender: 'n', plural: 'die Treppenhäuser', translation: l('stairwell', 'merdiven boşluğu', 'Treppenhaus') },
]

/** [id, abbreviation, meaning, wrong meanings] */
const ABBR: [string, string, string, [string, string]][] = [
  ['zkb', 'ZKB', 'Zimmer, Küche, Bad', ['Zentrale Kaltmiete Bonus', 'Zimmer mit kleinem Balkon']],
  ['nk', 'NK', 'Nebenkosten', ['Neue Küche', 'Nicht kündbar']],
  ['eg', 'EG', 'Erdgeschoss', ['Einbauküche mit Garten', 'Eigentum gesucht']],
  ['ebk', 'EBK', 'Einbauküche', ['Erdgeschoss mit Balkon', 'Erste Besichtigung']],
  ['qm', 'qm / m²', 'Quadratmeter', ['Quartalsmiete', 'Qualität mittel']],
  ['wm', 'WM', 'Warmmiete (mit Nebenkosten)', ['Wohnung möbliert', 'Waschmaschine']],
]

function abbrDrills(): Exercise[] {
  return ABBR.map(([id, abbr, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `abk-${id}`,
      type: 'multiple_choice' as const,
      topic: 'anzeigen',
      concept: 'abbreviations',
      skill: 'reading' as const,
      difficulty: 1 as const,
      prompt: `Was bedeutet „${abbr}“ in einer Wohnungsanzeige?`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`${abbr} = ${right}.`, `${abbr} = ${right}.`, `${abbr} = ${right}.`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-wohnung',
    type: 'matching',
    topic: 'mieten',
    concept: 'renting-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match German and meaning.', 'Almancayı anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'die Kaution', right: 'deposit' },
      { left: 'die Besichtigung', right: 'viewing' },
      { left: 'der Mietvertrag', right: 'rental contract' },
      { left: 'die Nebenkosten', right: 'utility costs' },
      { left: 'kündigen', right: 'to give notice' },
    ],
    explanation: l('Key words for renting.', 'Kiralama için temel kelimeler.', 'Mietwortschatz.'),
  },
  {
    id: 'sort-regel',
    type: 'categorize',
    topic: 'hausordnung',
    concept: 'house-rules',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Typical house rules: allowed or not allowed?', 'Tipik apartman kuralları: serbest mi yasak mı?', 'Erlaubt oder verboten?'),
    categories: ['erlaubt ✅', 'nicht erlaubt ⛔'],
    items: [
      { text: 'Fahrräder im Fahrradkeller abstellen', category: 0 },
      { text: 'nach 22 Uhr laut Musik hören', category: 1 },
      { text: 'Müll in die richtige Tonne werfen', category: 0 },
      { text: 'Kinderwagen im Treppenhaus stehen lassen', category: 1 },
      { text: 'Wäsche im Trockenraum aufhängen', category: 0 },
      { text: 'auf dem Balkon grillen (mit Holzkohle)', category: 1 },
    ],
    explanation: l('Typical German house rules (Ruhezeiten, Treppenhaus frei, Müll).', 'Tipik Alman apartman kuralları (sessizlik saatleri, merdiven boş, çöp).', 'Hausordnung.'),
    practice: ['abk-zkb'],
  },
  {
    id: 'mc-warm',
    type: 'multiple_choice',
    topic: 'anzeigen',
    concept: 'rent-types',
    skill: 'vocabulary',
    difficulty: 2,
    prompt: 'Kaltmiete 700 €, Nebenkosten 150 € – die Warmmiete beträgt also ___.',
    options: ['850 €', '700 €', '550 €'],
    answer: 0,
    explanation: l('Warmmiete = Kaltmiete + Nebenkosten.', 'Warmmiete = Kaltmiete + Nebenkosten.', '700 + 150 = 850.'),
    practice: ['abk-wm'],
  },
  {
    id: 'tf-kaution',
    type: 'true_false',
    topic: 'mieten',
    concept: 'deposit',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Kaution bekommt man normalerweise zurück, wenn man auszieht und alles in Ordnung ist.',
    answer: true,
    explanation: l('The deposit is security – you get it back if nothing is damaged.', 'Depozito bir güvencedir – hasar yoksa geri alırsın.', 'Kaution zurück.'),
  },
  {
    id: 'select-besichtigung',
    type: 'multiple_select',
    topic: 'besichtigung',
    concept: 'viewing-questions',
    skill: 'speaking',
    difficulty: 2,
    promptL10n: l('Which are good questions at a viewing? Select all.', 'Ev görmede hangileri iyi sorular? Hepsini seç.', 'Gute Fragen bei der Besichtigung?'),
    options: ['Wie hoch sind die Nebenkosten?', 'Ab wann ist die Wohnung frei?', 'Wie alt sind Sie?', 'Sind Haustiere erlaubt?', 'Warum ist die Wand weiß?'],
    answers: [0, 1, 3],
    explanation: l('Ask about costs, date and rules.', 'Masrafları, tarihi ve kuralları sor.', 'Kosten, Termin, Regeln.'),
  },
  {
    id: 'image-wg',
    type: 'image_choice',
    topic: 'mieten',
    concept: 'renting-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Vier Studenten teilen sich eine Wohnung mit Küche und Bad.',
    options: [
      { emoji: '👫', label: 'WG' },
      { emoji: '🏰', label: 'Schloss' },
      { emoji: '🏨', label: 'Hotel' },
      { emoji: '⛺', label: 'Zelt' },
    ],
    answer: 0,
    explanation: l('WG = Wohngemeinschaft.', 'WG = paylaşımlı ev.', 'WG.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-betraegt',
    type: 'fill_blank',
    topic: 'anzeigen',
    concept: 'rent-types',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Kaltmiete ___ 600 Euro im Monat.',
    accepted: ['beträgt', 'kostet', 'liegt bei'],
    base: 'betragen',
    explanation: l('betragen = to amount to (formal).', 'betragen = tutmak (resmî).', 'beträgt.'),
    examples: ['Die Kaltmiete **beträgt** 600 Euro im Monat.'],
  },
  {
    id: 'fill-ob',
    type: 'fill_blank',
    topic: 'besichtigung',
    concept: 'indirect-question',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Können Sie mir sagen, ___ die Wohnung noch frei ist?',
    accepted: ['ob'],
    base: 'ja/nein-Frage',
    explanation: l('Indirect yes/no question → ob + verb at the end.', 'Dolaylı evet/hayır sorusu → ob + fiil sonda.', 'ob.'),
    examples: ['Können Sie mir sagen, **ob** die Wohnung noch frei ist?'],
  },
  {
    id: 'fill-gekuendigt',
    type: 'fill_blank',
    topic: 'mieten',
    concept: 'renting-words',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich habe meine alte Wohnung zum 31. März ___. (kündigen)',
    accepted: ['gekündigt'],
    base: 'kündigen',
    explanation: l('kündigen → hat gekündigt.', 'kündigen → hat gekündigt.', 'gekündigt.'),
    examples: ['Ich habe meine alte Wohnung **gekündigt**.'],
  },
  {
    id: 'build-ab-wann',
    type: 'sentence_builder',
    topic: 'besichtigung',
    concept: 'indirect-question',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ab wann', 'Ich wollte fragen,', 'frei ist', 'die Wohnung'],
    answers: [['Ich wollte fragen,', 'ab wann', 'die Wohnung', 'frei ist']],
    translation: l('I wanted to ask from when the flat is free.', 'Dairenin ne zamandan itibaren boş olduğunu sormak istedim.', 'Ich wollte fragen, ab wann die Wohnung frei ist.'),
    explanation: l('Indirect W-question: verb at the end.', 'Dolaylı soru: fiil sonda.', '… frei ist.'),
    examples: ['Ich wollte fragen, ab wann die Wohnung frei **ist**.'],
  },
  {
    id: 'build-interesse',
    type: 'sentence_builder',
    topic: 'anzeigen',
    concept: 'reply-ad',
    skill: 'writing',
    difficulty: 2,
    chips: ['an der Wohnung', 'großes Interesse', 'Ich habe', 'in der Goethestraße'],
    answers: [['Ich habe', 'großes Interesse', 'an der Wohnung', 'in der Goethestraße']],
    translation: l('I am very interested in the flat in Goethestraße.', 'Goethestraße’deki daireyle çok ilgileniyorum.', 'Ich habe großes Interesse an der Wohnung in der Goethestraße.'),
    explanation: l('Interesse an + dative.', 'Interesse an + Dativ.', 'Interesse an.'),
    examples: ['Ich habe großes **Interesse an** der Wohnung.'],
  },
  {
    id: 'build-darf',
    type: 'sentence_builder',
    topic: 'hausordnung',
    concept: 'house-rules',
    skill: 'grammar',
    difficulty: 2,
    chips: ['nicht', 'Im Treppenhaus', 'abstellen', 'darf man', 'Fahrräder'],
    answers: [['Im Treppenhaus', 'darf man', 'Fahrräder', 'nicht', 'abstellen'], ['Im Treppenhaus', 'darf man', 'nicht', 'Fahrräder', 'abstellen']],
    translation: l('You may not leave bikes in the stairwell.', 'Merdiven boşluğuna bisiklet bırakılamaz.', 'Im Treppenhaus darf man Fahrräder nicht abstellen.'),
    explanation: l('man darf … nicht + infinitive at the end.', 'man darf … nicht + sonda mastar.', 'darf … abstellen.'),
    examples: ['Im Treppenhaus **darf** man Fahrräder nicht **abstellen**.'],
  },
  {
    id: 'fix-interesse',
    type: 'error_correction',
    topic: 'anzeigen',
    concept: 'reply-ad',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich interessiere für die Wohnung.',
    accepted: ['Ich interessiere mich für die Wohnung.'],
    explanation: l('sich interessieren für → ich interessiere mich.', 'sich interessieren für → ich interessiere mich.', 'mich.'),
    examples: ['Ich interessiere **mich** für die Wohnung.'],
  },
  {
    id: 'fix-ob',
    type: 'error_correction',
    topic: 'besichtigung',
    concept: 'indirect-question',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich möchte wissen, ob ist ein Keller dabei.',
    accepted: ['Ich möchte wissen, ob ein Keller dabei ist.'],
    explanation: l('ob → verb at the end.', 'ob → fiil sonda.', '… dabei ist.'),
    examples: ['Ich möchte wissen, ob ein Keller dabei **ist**.'],
  },
  {
    id: 'fix-miete',
    type: 'error_correction',
    topic: 'mieten',
    concept: 'renting-words',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Der Mieter vermietet mir die Wohnung.',
    accepted: ['Der Vermieter vermietet mir die Wohnung.'],
    explanation: l('Vermieter = landlord (gives), Mieter = tenant (takes).', 'Vermieter = ev sahibi (verir), Mieter = kiracı (alır).', 'Vermieter.'),
    examples: ['Der **Vermieter** vermietet mir die Wohnung.'],
  },
  {
    id: 'tr-besichtigung',
    type: 'translation',
    topic: 'besichtigung',
    concept: 'viewing-questions',
    skill: 'writing',
    difficulty: 2,
    source: l('When can I view the flat?', 'Daireyi ne zaman görebilirim?', 'When can I view the flat?'),
    accepted: ['Wann kann ich die Wohnung besichtigen?', 'Wann kann ich die Wohnung ansehen?', 'Wann kann ich mir die Wohnung ansehen?'],
    explanation: l('besichtigen = to view.', 'besichtigen = (evi) görmek.', 'besichtigen.'),
    examples: ['Wann kann ich die Wohnung **besichtigen**?'],
  },
  {
    id: 'tr-haustiere',
    type: 'translation',
    topic: 'hausordnung',
    concept: 'house-rules',
    skill: 'writing',
    difficulty: 2,
    source: l('Are pets allowed?', 'Evcil hayvanlara izin var mı?', 'Are pets allowed?'),
    accepted: ['Sind Haustiere erlaubt?', 'Darf man Haustiere haben?'],
    explanation: l('erlaubt = allowed.', 'erlaubt = izinli.', 'erlaubt.'),
    examples: ['Sind Haustiere **erlaubt**?'],
  },
  {
    id: 'ordering-weg',
    type: 'ordering',
    topic: 'mieten',
    concept: 'process',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the steps of finding a flat in order.', 'Ev bulma adımlarını sırala.', 'Der Weg zur Wohnung.'),
    items: ['Ich unterschreibe den Mietvertrag.', 'Ich lese Wohnungsanzeigen im Internet.', 'Ich ziehe ein.', 'Ich gehe zur Besichtigung.', 'Ich schreibe dem Vermieter eine E-Mail.'],
    answer: ['Ich lese Wohnungsanzeigen im Internet.', 'Ich schreibe dem Vermieter eine E-Mail.', 'Ich gehe zur Besichtigung.', 'Ich unterschreibe den Mietvertrag.', 'Ich ziehe ein.'],
    explanation: l('Ad → email → viewing → contract → move in.', 'İlan → e-posta → görme → sözleşme → taşınma.', 'Anzeige → Besichtigung → Vertrag.'),
  },
  {
    id: 'dialog-besichtigung',
    type: 'dialogue',
    topic: 'besichtigung',
    concept: 'viewing-questions',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Vermieterin', de: 'So, das ist das Wohnzimmer. Haben Sie noch Fragen?' }],
    options: ['Ja, wie hoch sind denn die Nebenkosten ungefähr?', 'Ja, ich bin Wohnzimmer.', 'Nein, die Fragen sind hoch.'],
    answer: 0,
    explanation: l('Ask about the costs.', 'Masrafları sor.', 'Nebenkosten.'),
  },
  {
    id: 'dialog-nachbar',
    type: 'dialogue',
    topic: 'hausordnung',
    concept: 'neighbours',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Nachbar', de: 'Entschuldigung, Ihre Musik ist gestern bis Mitternacht sehr laut gewesen.' }],
    options: ['Oh, das tut mir leid. Das kommt nicht wieder vor.', 'Musik ist schön.', 'Mitternacht ist um zwölf.'],
    answer: 0,
    explanation: l('Apologise: Das tut mir leid. Das kommt nicht wieder vor.', 'Özür dile: Das tut mir leid. Das kommt nicht wieder vor.', 'Entschuldigen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-groesse',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie groß ist die Wohnung?',
    options: ['65 Quadratmeter.', '3 Quadratmeter.', '850 Quadratmeter.'],
    answer: 0,
    explanation: l('„3 ZKB, 65 m²“', '„3 ZKB, 65 m²“', '65 m².'),
  },
  {
    id: 'read-warm',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie viel muss man jeden Monat insgesamt bezahlen?',
    options: ['850 Euro.', '700 Euro.', '2100 Euro.'],
    answer: 0,
    explanation: l('Kaltmiete 700 € + NK 150 € = 850 €.', 'Kaltmiete 700 € + NK 150 € = 850 €.', '850 €.'),
  },
  {
    id: 'read-haustiere',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    statement: 'Man darf in der Wohnung einen Hund haben.',
    answer: false,
    explanation: l('„Keine Haustiere.“', '„Keine Haustiere.“', 'falsch.'),
  },
  {
    id: 'read-kontakt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-anzeige',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was soll man tun, wenn man Interesse hat?',
    options: ['Eine E-Mail mit kurzer Vorstellung schreiben.', 'Am Sonntag anrufen.', 'Direkt vorbeikommen.'],
    answer: 0,
    explanation: l('„Bitte nur per E-Mail mit kurzer Vorstellung.“', '„Bitte nur per E-Mail mit kurzer Vorstellung.“', 'E-Mail.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-termin',
    type: 'listening_choice',
    topic: 'besichtigung',
    concept: 'appointment',
    skill: 'listening',
    difficulty: 1,
    audio: 'Die Besichtigung ist am Donnerstag um 18 Uhr. Bitte bringen Sie eine Gehaltsbescheinigung mit.',
    question: l('What should you bring?', 'Yanında ne getirmelisin?', 'Was soll man mitbringen?'),
    options: ['proof of income', 'a passport photo', 'the deposit in cash'],
    answer: 0,
    explanation: l('„eine Gehaltsbescheinigung“ = proof of salary.', '„eine Gehaltsbescheinigung“ = maaş belgesi.', 'Gehaltsbescheinigung.'),
  },
  {
    id: 'listen-ruhe',
    type: 'listening_choice',
    topic: 'hausordnung',
    concept: 'house-rules',
    skill: 'listening',
    difficulty: 2,
    audio: 'Laut Hausordnung ist von 22 bis 7 Uhr Nachtruhe und am Sonntag den ganzen Tag.',
    question: l('When must it be quiet on Sundays?', 'Pazar günleri ne zaman sessiz olunmalı?', 'Wann ist sonntags Ruhe?'),
    options: ['all day', 'only in the morning', 'from 22:00'],
    answer: 0,
    explanation: l('„am Sonntag den ganzen Tag“', '„am Sonntag den ganzen Tag“', 'ganzen Tag.'),
  },
  {
    id: 'listen-kaution',
    type: 'listening_choice',
    topic: 'mieten',
    concept: 'deposit',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Kaution beträgt zwei Kaltmieten, also 1400 Euro. Die zahlen Sie vor dem Einzug.',
    question: l('How much is the deposit?', 'Depozito ne kadar?', 'Wie hoch ist die Kaution?'),
    options: ['1400 euros', '700 euros', '2100 euros'],
    answer: 0,
    explanation: l('„also 1400 Euro“', '„also 1400 Euro“', '1400 €.'),
  },
  {
    id: 'listen-wg',
    type: 'listening_choice',
    topic: 'mieten',
    concept: 'renting-words',
    skill: 'listening',
    difficulty: 2,
    audio: 'In unserer WG kochen wir oft zusammen. Das Putzen machen wir nach einem Plan.',
    question: l('How do they organise the cleaning?', 'Temizliği nasıl organize ediyorlar?', 'Wie wird geputzt?'),
    options: ['with a rota', 'a cleaner comes', 'nobody cleans'],
    answer: 0,
    explanation: l('„nach einem Plan“ = with a rota.', '„nach einem Plan“ = bir plana göre.', 'Putzplan.'),
  },

  ...abbrDrills(),
]

export const UNIT_B1_22_WOHNUNGSSUCHE: CourseUnit = {
  level: 'B1',
  number: 22,
  slug: 'wohnungssuche',
  titleDe: 'Die Wohnungssuche',
  title: l('Flat hunting', 'Ev arama', 'Die Wohnungssuche'),
  goal: l(
    'By the end of this unit you can understand flat adverts and their abbreviations, reply to an ad, ask the right questions at a viewing, understand the basics of a rental contract and the house rules.',
    'Bu ünitenin sonunda ev ilanlarını ve kısaltmalarını anlayabilir, bir ilana cevap yazabilir, ev görmede doğru soruları sorabilir, kira sözleşmesinin temellerini ve apartman kurallarını anlayabilirsin.',
    'Am Ende dieser Einheit findest du eine Wohnung in Deutschland.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'anzeigen', label: l('Flat adverts', 'Ev ilanları', 'Wohnungsanzeigen') },
    { key: 'besichtigung', label: l('The viewing', 'Ev görme', 'Besichtigung') },
    { key: 'mieten', label: l('Renting', 'Kiralama', 'Mieten') },
    { key: 'hausordnung', label: l('House rules', 'Apartman kuralları', 'Hausordnung') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Everything you need to rent a flat.', 'Ev kiralamak için gereken her şey.', 'Alles rund ums Mieten.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Reading flat adverts', 'Ev ilanlarını okumak', 'Wohnungsanzeigen lesen'),
          body: l(
            'Adverts use many abbreviations. Kaltmiete = rent only, Nebenkosten (NK) = heating, water, rubbish, Warmmiete = both together. The deposit (Kaution) is often 2–3 times the Kaltmiete.',
            'İlanlarda çok kısaltma kullanılır. Kaltmiete = sadece kira, Nebenkosten (NK) = ısınma, su, çöp, Warmmiete = ikisi birlikte. Depozito (Kaution) genelde Kaltmiete’nin 2–3 katıdır.',
            'Kaltmiete + NK = Warmmiete.'
          ),
          table: {
            head: [l('Abbreviation', 'Kısaltma', 'Abkürzung'), l('Meaning', 'Anlamı', 'Bedeutung')],
            rows: [
              ['3 ZKB', '3 Zimmer, Küche, Bad'],
              ['EBK', 'Einbauküche'],
              ['NK', 'Nebenkosten'],
              ['EG / 2. OG', 'Erdgeschoss / 2. Obergeschoss'],
              ['WM / KM', 'Warmmiete / Kaltmiete'],
            ],
          },
        },
        {
          title: l('Asking politely: indirect questions', 'Kibarca sormak: dolaylı sorular', 'Indirekte Fragen'),
          body: l(
            'At a viewing indirect questions sound more polite. W-question → W-word + verb at the end. Yes/no question → ob + verb at the end.',
            'Ev görmede dolaylı sorular daha kibar duyulur. Soru kelimeli soru → soru kelimesi + fiil sonda. Evet/hayır sorusu → ob + fiil sonda.',
            'Können Sie mir sagen, ob / wann …?'
          ),
          examples: [
            { de: 'Können Sie mir sagen, **wie hoch** die Nebenkosten **sind**?', translation: l('Can you tell me how high the utility costs are?', 'Ek giderlerin ne kadar olduğunu söyleyebilir misiniz?', '') },
            { de: 'Ich wollte fragen, **ob** Haustiere erlaubt **sind**.', translation: l('I wanted to ask whether pets are allowed.', 'Evcil hayvanlara izin olup olmadığını sormak istedim.', '') },
          ],
        },
        {
          title: l('House rules', 'Apartman kuralları', 'Die Hausordnung'),
          body: l(
            'Quiet hours (Ruhezeiten) are usually 22–7 h and on Sundays. Keep the stairwell free, separate rubbish, and in some buildings tenants take turns cleaning the stairs (Kehrwoche).',
            'Sessizlik saatleri (Ruhezeiten) genelde 22–7 arası ve pazar günleridir. Merdiven boşluğunu boş tut, çöpü ayır; bazı binalarda kiracılar sırayla merdiven temizliği yapar (Kehrwoche).',
            'Ruhezeiten, Treppenhaus, Müll.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Deniz is viewing a flat with the landlord Mr Weber.', 'Deniz, ev sahibi Bay Weber ile bir daireyi geziyor.', 'Besichtigung.'),
      dialogue: [
        { speaker: 'Herr Weber', de: 'Herzlich willkommen! Das hier ist die Küche – mit **Einbauküche**.', translation: l('Welcome! This is the kitchen – with a fitted kitchen.', 'Hoş geldiniz! Burası mutfak – ankastre mutfaklı.', '') },
        { speaker: 'Deniz', de: 'Sehr schön! Können Sie mir sagen, **wie hoch** die **Nebenkosten** **sind**?', translation: l('Very nice! Can you tell me how high the utility costs are?', 'Çok güzel! Ek giderlerin ne kadar olduğunu söyleyebilir misiniz?', '') },
        { speaker: 'Herr Weber', de: 'Etwa 150 Euro im Monat. Dazu kommt die **Kaution**: zwei Monatsmieten.', translation: l('About 150 euros a month. Plus the deposit: two months’ rent.', 'Ayda yaklaşık 150 Euro. Bir de depozito var: iki aylık kira.', '') },
        { speaker: 'Deniz', de: 'Und ich wollte fragen, **ob** ein Keller dabei **ist**.', translation: l('And I wanted to ask whether there is a cellar.', 'Bir de bodrum olup olmadığını sormak istedim.', '') },
        { speaker: 'Herr Weber', de: 'Ja, und einen Fahrradkeller gibt es auch. Im **Treppenhaus** dürfen leider keine Fahrräder stehen.', translation: l('Yes, and there is also a bike cellar. Unfortunately bikes are not allowed in the stairwell.', 'Evet, bisiklet bodrumu da var. Merdiven boşluğunda maalesef bisiklet duramaz.', '') },
        { speaker: 'Deniz', de: 'Kein Problem. Ich habe großes Interesse – wann könnte ich den **Mietvertrag** unterschreiben?', translation: l('No problem. I’m very interested – when could I sign the contract?', 'Sorun değil. Çok ilgileniyorum – sözleşmeyi ne zaman imzalayabilirim?', '') },
      ],
      examples: [
        { de: 'Die **Kaltmiete** beträgt 650 Euro.', translation: l('The basic rent is 650 euros.', 'Kira (aidatsız) 650 Euro.', '') },
        { de: 'Wann kann ich die Wohnung **besichtigen**?', translation: l('When can I view the flat?', 'Daireyi ne zaman görebilirim?', '') },
        { de: 'Können Sie mir sagen, **ob** die Wohnung noch frei **ist**?', translation: l('Can you tell me whether the flat is still free?', 'Dairenin hâlâ boş olup olmadığını söyleyebilir misiniz?', '') },
        { de: 'Ich interessiere **mich für** die Wohnung.', translation: l('I’m interested in the flat.', 'Daireyle ilgileniyorum.', '') },
        { de: 'Laut **Hausordnung** ist ab 22 Uhr Ruhe.', translation: l('According to the house rules it must be quiet from 10 pm.', 'Apartman kurallarına göre saat 22’den sonra sessizlik.', '') },
        { de: 'Ich habe die alte Wohnung **gekündigt**.', translation: l('I gave notice on my old flat.', 'Eski dairenin sözleşmesini feshettim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Decode the adverts and the rules.', 'İlanları ve kuralları çöz.', 'Anzeigen und Regeln verstehen.'),
      exercises: ['match-wohnung', 'sort-regel', 'abk-zkb', 'abk-nk', 'abk-eg', 'mc-warm', 'tf-kaution', 'select-besichtigung', 'image-wg'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Write to the landlord and ask questions.', 'Ev sahibine yaz ve sorular sor.', 'Anfragen und Fragen stellen.'),
      exercises: [
        'fill-betraegt',
        'fill-ob',
        'fill-gekuendigt',
        'build-ab-wann',
        'build-interesse',
        'build-darf',
        'fix-interesse',
        'fix-ob',
        'fix-miete',
        'tr-besichtigung',
        'tr-haustiere',
        'ordering-weg',
        'dialog-besichtigung',
        'dialog-nachbar',
        'abk-ebk',
        'abk-qm',
        'abk-wm',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A flat advert.', 'Bir ev ilanı.', 'Eine Wohnungsanzeige.'),
      passage: [
        '**Helle 3-Zimmer-Wohnung in Köln-Ehrenfeld** – 3 ZKB, 65 m², 2. OG, Altbau, Balkon, EBK.',
        'Kaltmiete 700 €, NK 150 €, **Kaution** 2100 €. Frei ab 1. Juni.',
        'Nur fünf Minuten zur U-Bahn, Supermarkt und Park um die Ecke. Nichtraucher bevorzugt, keine Haustiere.',
        '**Besichtigung** nach Vereinbarung. Bitte nur per E-Mail mit kurzer Vorstellung (Beruf, Einzugstermin) an wohnung.ehrenfeld@mail.de.',
      ],
      glossary: [
        { de: 'hell', note: l('bright', 'aydınlık', 'viel Licht') },
        { de: 'bevorzugt', note: l('preferred', 'tercih edilir', 'lieber') },
        { de: 'nach Vereinbarung', note: l('by arrangement', 'randevuyla', 'Termin ausmachen') },
        { de: 'der Einzugstermin', note: l('moving-in date', 'taşınma tarihi', 'wann man einzieht') },
      ],
      exercises: ['read-groesse', 'read-warm', 'read-haustiere', 'read-kontakt'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Viewings, rules and money.', 'Ev görme, kurallar ve para.', 'Termine, Regeln, Geld.'),
      exercises: ['listen-termin', 'listen-ruhe', 'listen-kaution', 'listen-wg'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('You are at a viewing. Ask the landlord at least four questions.', 'Ev görmedesin. Ev sahibine en az dört soru sor.', 'Stell bei der Besichtigung Fragen.'),
      points: [
        l('Costs: Nebenkosten, Kaution', 'Masraflar: Nebenkosten, Kaution', 'Kosten'),
        l('Date: „Ab wann …?“', 'Tarih: „Ab wann …?“', 'Termin'),
        l('Rules: pets, bikes …', 'Kurallar: evcil hayvan, bisiklet …', 'Regeln'),
        l('Use one indirect question: „Können Sie mir sagen, ob …?“', 'Bir dolaylı soru kullan: „Können Sie mir sagen, ob …?“', 'indirekte Frage'),
      ],
      model: [
        'Wie hoch sind die Nebenkosten ungefähr?',
        'Können Sie mir sagen, ab wann die Wohnung frei ist?',
        'Ich wollte auch fragen, ob ich eine Katze haben darf.',
        'Und gibt es einen Platz für mein Fahrrad?',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Reply to the advert from the reading text (at least 5 sentences): introduce yourself and ask for a viewing.',
        'Okuma metnindeki ilana cevap yaz (en az 5 cümle): kendini tanıt ve ev görme randevusu iste.',
        'Antworte auf die Anzeige (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Formal greeting (Sehr geehrte …)', 'Resmî hitap (Sehr geehrte …)', 'Anrede'), pattern: 'Sehr geehrte' },
        { label: l('Interest (Interesse an / interessiere mich für)', 'İlgi (Interesse an / interessiere mich für)', 'Interesse'), pattern: '(Interesse an|interessiere mich für)' },
        { label: l('Ask for a viewing (Besichtigung / besichtigen)', 'Ev görme iste (Besichtigung / besichtigen)', 'Besichtigung'), pattern: '[Bb]esichtig' },
        { label: l('Formal closing (Mit freundlichen Grüßen)', 'Resmî kapanış (Mit freundlichen Grüßen)', 'Gruß'), pattern: 'Mit freundlichen Grüßen' },
      ],
      model: [
        'Sehr geehrte Damen und Herren, ich habe großes Interesse an Ihrer Wohnung in Köln-Ehrenfeld.',
        'Ich heiße Deniz Kaya, bin 28 Jahre alt und arbeite als Ingenieurin.',
        'Ich bin Nichtraucherin und habe keine Haustiere.',
        'Ich könnte ab dem 1. Juni einziehen.',
        'Ich würde die Wohnung sehr gern besichtigen. Mit freundlichen Grüßen, Deniz Kaya',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Decode the abbreviations! – 60 seconds.', 'Kısaltmaları çöz! – 60 saniye.', 'Abkürzungen! – 60 Sekunden.'),
      seconds: 60,
      pool: [...ABBR.map(([id]) => `abk-${id}`), 'mc-warm'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Adverts: ZKB, EBK, NK, Kaltmiete / Warmmiete, Kaution', 'İlanlar: ZKB, EBK, NK, Kaltmiete / Warmmiete, Kaution', 'Anzeigen'),
      l('Viewing questions – also as indirect questions with ob / wann', 'Ev görme soruları – ob / wann ile dolaylı sorular olarak da', 'Besichtigung'),
      l('Renting: Mieter, Vermieter, Mietvertrag, kündigen', 'Kiralama: Mieter, Vermieter, Mietvertrag, kündigen', 'Mieten'),
      l('House rules: Ruhezeiten, Treppenhaus, Mülltrennung', 'Apartman kuralları: Ruhezeiten, Treppenhaus, Mülltrennung', 'Hausordnung'),
    ],
    mistakes: [
      { wrong: 'Ich interessiere für die Wohnung.', right: 'Ich interessiere mich für die Wohnung.', note: l('Reflexive.', 'Dönüşlü.', 'mich.') },
      { wrong: 'Ich möchte wissen, ob ist ein Keller dabei.', right: 'Ich möchte wissen, ob ein Keller dabei ist.', note: l('Verb at the end.', 'Fiil sonda.', 'Verb am Ende.') },
      { wrong: 'Der Mieter vermietet die Wohnung.', right: 'Der Vermieter vermietet die Wohnung.', note: l('Vermieter = landlord.', 'Vermieter = ev sahibi.', 'Vermieter.') },
      { wrong: 'Kaltmiete = alles inklusive', right: 'Warmmiete = Kaltmiete + Nebenkosten', note: l('Kalt = without bills.', 'Kalt = giderler hariç.', 'Kalt ohne NK.') },
    ],
  },
}
