import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'wurde gebaut', emoji: '🏰', translation: l('was built', 'inşa edildi', 'Passiv Präteritum'), example: 'Das Schloss wurde 1750 gebaut.' },
  { word: 'wurden zerstört', emoji: '💥', translation: l('were destroyed', 'yıkıldı', 'Passiv Präteritum Plural'), example: 'Viele Häuser wurden im Krieg zerstört.' },
  { word: 'muss gemacht werden', emoji: '📌', translation: l('must be done', 'yapılmalı', 'Passiv mit Modalverb'), example: 'Das Formular muss heute abgegeben werden.' },
  { word: 'kann repariert werden', emoji: '🔧', translation: l('can be repaired', 'tamir edilebilir', 'Passiv mit können'), example: 'Die Waschmaschine kann leider nicht repariert werden.' },
  { word: 'gründen', emoji: '🏛️', translation: l('to found', 'kurmak (şirket, şehir)', 'neu beginnen'), example: 'Die Stadt wurde im 12. Jahrhundert gegründet.' },
  { word: 'erfinden', emoji: '💡', translation: l('to invent', 'icat etmek', 'neu machen'), example: 'Das Auto wurde 1886 erfunden.' },
  { word: 'entdecken', emoji: '🔭', translation: l('to discover', 'keşfetmek', 'zum ersten Mal finden'), example: 'Amerika wurde 1492 von Kolumbus erreicht.' },
  { word: 'renovieren', emoji: '🎨', translation: l('to renovate', 'yenilemek', 'neu machen'), example: 'Das Rathaus wurde letztes Jahr renoviert.' },
  { word: 'das Jahrhundert', emoji: '🗓️', translation: l('century', 'yüzyıl', '100 Jahre'), example: 'Im 19. Jahrhundert wurde die Eisenbahn gebaut.' },
  { word: 'die Sehenswürdigkeit', emoji: '📸', translation: l('sight, attraction', 'görülmeye değer yer', 'was Touristen besuchen'), example: 'Die Burg ist die wichtigste Sehenswürdigkeit.' },
  { word: 'eröffnen', emoji: '✂️', translation: l('to open (officially)', 'açılış yapmak', 'zum ersten Mal öffnen'), example: 'Das Museum wurde 2010 eröffnet.' },
  { word: 'abreißen', emoji: '🚧', translation: l('to demolish', 'yıkmak', 'kaputt machen (Gebäude)'), example: 'Das alte Kino wurde abgerissen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Schloss', gender: 'n', plural: 'die Schlösser', translation: l('palace, castle', 'saray, şato', 'Schloss') },
  { word: 'Burg', gender: 'f', plural: 'die Burgen', translation: l('castle (fortress)', 'kale', 'Burg') },
  { word: 'Rathaus', gender: 'n', plural: 'die Rathäuser', translation: l('town hall', 'belediye binası', 'Rathaus') },
  { word: 'Brücke', gender: 'f', plural: 'die Brücken', translation: l('bridge', 'köprü', 'Brücke') },
  { word: 'Krieg', gender: 'm', plural: 'die Kriege', translation: l('war', 'savaş', 'Krieg') },
  { word: 'Mauer', gender: 'f', plural: 'die Mauern', translation: l('wall', 'duvar', 'Mauer') },
  { word: 'Formular', gender: 'n', plural: 'die Formulare', translation: l('form', 'form', 'Formular') },
]

/** [id, sentence with ___ for the aux, right aux, two wrong, type] */
const DRILLS: [string, string, string, [string, string], 'prt' | 'modal'][] = [
  ['burg', 'Die Burg ___ im 12. Jahrhundert gebaut.', 'wurde', ['wurden', 'wird'], 'prt'],
  ['haeuser', 'Viele Häuser ___ im Krieg zerstört.', 'wurden', ['wurde', 'werden'], 'prt'],
  ['telefon', 'Das Telefon ___ 1876 erfunden.', 'wurde', ['ist', 'würde'], 'prt'],
  ['bruecke', 'Die alte Brücke ___ 1990 abgerissen.', 'wurde', ['wurden', 'werde'], 'prt'],
  ['formular', 'Das Formular muss bis Freitag abgegeben ___.', 'werden', ['wird', 'worden'], 'modal'],
  ['auto', 'Das Auto kann leider nicht mehr repariert ___.', 'werden', ['wurde', 'wird'], 'modal'],
  ['zimmer', 'Die Zimmer müssen jeden Tag geputzt ___.', 'werden', ['wurden', 'sein'], 'modal'],
]

function auxDrills(): Exercise[] {
  return DRILLS.map(([id, sentence, right, wrong, type], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `pv-${id}`,
      type: 'multiple_choice' as const,
      topic: type === 'prt' ? 'passiv-praeteritum' : 'passiv-modal',
      concept: type === 'prt' ? (right === 'wurden' ? 'wurden' : 'wurde') : 'modal-werden',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation:
        type === 'prt'
          ? l(
              `Past passive: wurde (singular) / wurden (plural) + participle. Here: ${right}.`,
              `Geçmiş edilgen: wurde (tekil) / wurden (çoğul) + ortaç. Burada: ${right}.`,
              `Passiv Präteritum: ${right}.`
            )
          : l(
              'Passive with a modal verb: modal (position 2) + participle + werden (infinitive, at the very end).',
              'Modal fiilli edilgen: modal (2. sıra) + ortaç + werden (mastar, en sonda).',
              'Modalverb + Partizip + werden.'
            ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'sort-zeit',
    type: 'categorize',
    topic: 'passiv-praeteritum',
    concept: 'tense-recognize',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Passive now or in the past?', 'Şimdiki mi geçmiş mi edilgen?', 'Passiv jetzt oder früher?'),
    categories: ['Präsens', 'Präteritum'],
    items: [
      { text: 'Das Haus wird gebaut.', category: 0 },
      { text: 'Das Haus wurde gebaut.', category: 1 },
      { text: 'Die Briefe werden geschickt.', category: 0 },
      { text: 'Die Briefe wurden geschickt.', category: 1 },
      { text: 'Hier wird gearbeitet.', category: 0 },
      { text: 'Hier wurde gearbeitet.', category: 1 },
    ],
    explanation: l('wird/werden = now; wurde/wurden = past.', 'wird/werden = şimdi; wurde/wurden = geçmiş.', 'wurde = Vergangenheit.'),
    practice: ['pv-burg', 'pv-haeuser'],
  },
  {
    id: 'match-geschichte',
    type: 'matching',
    topic: 'passiv-praeteritum',
    concept: 'history-facts',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Match the event and the year.', 'Olayı yılla eşleştir.', 'Ordne Ereignis und Jahr zu.'),
    pairs: [
      { left: 'Die Berliner Mauer wurde gebaut.', right: '1961' },
      { left: 'Die Mauer wurde geöffnet.', right: '1989' },
      { left: 'Das Auto wurde erfunden.', right: '1886' },
      { left: 'Der Euro wurde eingeführt.', right: '2002 (Bargeld)' },
    ],
    explanation: l('History is often told in the past passive: wurde + participle.', 'Tarih çoğu zaman geçmiş edilgenle anlatılır: wurde + ortaç.', 'Geschichte im Passiv.'),
  },
  {
    id: 'mc-modal',
    type: 'multiple_choice',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Die Rechnung ___ bis Ende des Monats bezahlt werden.',
    options: ['muss', 'wird', 'wurde'],
    answer: 0,
    explanation: l('Obligation → muss … bezahlt werden.', 'Zorunluluk → muss … bezahlt werden.', 'muss … werden.'),
    examples: ['Die Rechnung **muss** bezahlt **werden**.'],
  },
  {
    id: 'tf-worden',
    type: 'true_false',
    topic: 'passiv-praeteritum',
    concept: 'perfekt-passiv',
    skill: 'grammar',
    difficulty: 3,
    statement: '„Das Haus ist 1900 gebaut worden“ ist auch richtig (Perfekt Passiv).',
    answer: true,
    explanation: l(
      'Perfekt passive: sein + participle + worden (not „geworden“!). In written texts the Präteritum (wurde gebaut) is more common.',
      'Perfekt edilgen: sein + ortaç + worden („geworden“ değil!). Yazılı metinlerde Präteritum (wurde gebaut) daha yaygındır.',
      'ist … gebaut worden.'
    ),
    examples: ['Das Haus **ist** 1900 **gebaut worden**.'],
  },
  {
    id: 'select-richtig',
    type: 'multiple_select',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche Sätze sind richtig?'),
    options: ['Das muss sofort gemacht werden.', 'Das muss sofort werden gemacht.', 'Hier darf nicht geraucht werden.', 'Die Bücher wurden verkauft.', 'Die Bücher wurde verkauft.'],
    answers: [0, 2, 3],
    explanation: l('Modal + participle + werden; plural → wurden.', 'Modal + ortaç + werden; çoğul → wurden.', 'gemacht werden; wurden.'),
  },
  {
    id: 'image-erfindung',
    type: 'image_choice',
    topic: 'geschichte',
    concept: 'inventions',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Diese Erfindung wurde 1440 von Gutenberg gemacht.',
    options: [
      { emoji: '📖', label: 'Buchdruck' },
      { emoji: '🚗', label: 'Auto' },
      { emoji: '💡', label: 'Glühbirne' },
      { emoji: '📞', label: 'Telefon' },
    ],
    answer: 0,
    explanation: l('Gutenberg → printing press (Buchdruck).', 'Gutenberg → matbaa (Buchdruck).', 'Buchdruck.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-wurde',
    type: 'fill_blank',
    topic: 'passiv-praeteritum',
    concept: 'wurde',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Das Museum ___ 2010 eröffnet.',
    accepted: ['wurde'],
    base: 'werden (Präteritum)',
    explanation: l('Singular, past → wurde.', 'Tekil, geçmiş → wurde.', 'wurde.'),
    examples: ['Das Museum **wurde** 2010 **eröffnet**.'],
  },
  {
    id: 'fill-gegruendet',
    type: 'fill_blank',
    topic: 'passiv-praeteritum',
    concept: 'participles',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Stadt wurde im Jahr 1237 ___. (gründen)',
    accepted: ['gegründet'],
    base: 'gründen',
    explanation: l('gründen → gegründet (-et after d).', 'gründen → gegründet (d’den sonra -et).', 'gegründet.'),
    examples: ['Die Stadt wurde 1237 **gegründet**.'],
  },
  {
    id: 'fill-werden',
    type: 'fill_blank',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Im Kino darf nicht telefoniert ___.',
    accepted: ['werden'],
    base: 'Passiv + Modalverb',
    explanation: l('darf … telefoniert werden.', 'darf … telefoniert werden.', 'werden.'),
    examples: ['Im Kino darf nicht **telefoniert werden**.'],
  },
  {
    id: 'build-wurde',
    type: 'sentence_builder',
    topic: 'passiv-praeteritum',
    concept: 'wurde',
    skill: 'grammar',
    difficulty: 2,
    chips: ['renoviert', 'letztes Jahr', 'wurde', 'Das Rathaus'],
    answers: [['Das Rathaus', 'wurde', 'letztes Jahr', 'renoviert']],
    translation: l('The town hall was renovated last year.', 'Belediye binası geçen yıl yenilendi.', 'Das Rathaus wurde letztes Jahr renoviert.'),
    explanation: l('wurde (2) … participle (end).', 'wurde (2) … ortaç (son).', 'wurde … renoviert.'),
    examples: ['Das Rathaus **wurde** letztes Jahr **renoviert**.'],
  },
  {
    id: 'build-modal',
    type: 'sentence_builder',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'grammar',
    difficulty: 3,
    chips: ['werden', 'sofort', 'gemacht', 'Das', 'muss'],
    answers: [['Das', 'muss', 'sofort', 'gemacht', 'werden']],
    translation: l('That must be done immediately.', 'Bunun hemen yapılması gerekiyor.', 'Das muss sofort gemacht werden.'),
    explanation: l('Modal (2) … participle + werden (end).', 'Modal (2) … ortaç + werden (son).', 'muss … gemacht werden.'),
    examples: ['Das **muss** sofort **gemacht werden**.'],
  },
  {
    id: 'build-von',
    type: 'sentence_builder',
    topic: 'passiv-praeteritum',
    concept: 'agent-past',
    skill: 'grammar',
    difficulty: 2,
    chips: ['von Picasso', 'Das Bild', 'gemalt', 'wurde'],
    answers: [['Das Bild', 'wurde', 'von Picasso', 'gemalt']],
    translation: l('The picture was painted by Picasso.', 'Resim Picasso tarafından yapıldı.', 'Das Bild wurde von Picasso gemalt.'),
    explanation: l('wurde + von + Dativ + participle.', 'wurde + von + Dativ + ortaç.', 'wurde von … gemalt.'),
    examples: ['Das Bild **wurde von** Picasso **gemalt**.'],
  },
  {
    id: 'fix-wurden',
    type: 'error_correction',
    topic: 'passiv-praeteritum',
    concept: 'wurden',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die Fenster wurde gestern geputzt.',
    accepted: ['Die Fenster wurden gestern geputzt.'],
    explanation: l('die Fenster (plural) → wurden.', 'die Fenster (çoğul) → wurden.', 'wurden.'),
    examples: ['Die Fenster **wurden** gestern geputzt.'],
  },
  {
    id: 'fix-geworden',
    type: 'error_correction',
    topic: 'passiv-praeteritum',
    concept: 'perfekt-passiv',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das Paket ist gestern geliefert geworden.',
    accepted: ['Das Paket ist gestern geliefert worden.', 'Das Paket wurde gestern geliefert.'],
    explanation: l('Perfekt passive: … geliefert worden (not geworden).', 'Perfekt edilgen: … geliefert worden (geworden değil).', 'worden.'),
    examples: ['Das Paket ist gestern geliefert **worden**.'],
  },
  {
    id: 'fix-modal-order',
    type: 'error_correction',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Küche muss werden geputzt.',
    accepted: ['Die Küche muss geputzt werden.'],
    explanation: l('Order at the end: participle + werden.', 'Sondaki sıra: ortaç + werden.', 'geputzt werden.'),
    examples: ['Die Küche muss **geputzt werden**.'],
  },
  {
    id: 'tr-wurde',
    type: 'translation',
    topic: 'passiv-praeteritum',
    concept: 'wurde',
    skill: 'writing',
    difficulty: 2,
    source: l('The bridge was built in 1890.', 'Köprü 1890’da inşa edildi.', 'The bridge was built in 1890.'),
    accepted: ['Die Brücke wurde 1890 gebaut.', 'Die Brücke wurde im Jahr 1890 gebaut.'],
    explanation: l('wurde … gebaut.', 'wurde … gebaut.', 'wurde gebaut.'),
    examples: ['Die Brücke **wurde** 1890 **gebaut**.'],
  },
  {
    id: 'tr-kann',
    type: 'translation',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'writing',
    difficulty: 3,
    source: l('The washing machine can’t be repaired.', 'Çamaşır makinesi tamir edilemez.', 'The washing machine can’t be repaired.'),
    accepted: ['Die Waschmaschine kann nicht repariert werden.', 'Die Waschmaschine kann nicht mehr repariert werden.'],
    explanation: l('kann … repariert werden.', 'kann … repariert werden.', 'kann … werden.'),
    examples: ['Die Waschmaschine **kann** nicht **repariert werden**.'],
  },
  {
    id: 'ordering-stadt',
    type: 'ordering',
    topic: 'geschichte',
    concept: 'history-order',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the history of the town in order.', 'Kasabanın tarihini sıraya koy.', 'Bring die Stadtgeschichte in Ordnung.'),
    items: ['1945: Viele Häuser wurden zerstört.', '1150: Die Stadt wurde gegründet.', '2015: Die Altstadt wurde renoviert.', '1680: Das Schloss wurde gebaut.'],
    answer: ['1150: Die Stadt wurde gegründet.', '1680: Das Schloss wurde gebaut.', '1945: Viele Häuser wurden zerstört.', '2015: Die Altstadt wurde renoviert.'],
    explanation: l('Chronological order: 1150 → 1680 → 1945 → 2015.', 'Kronolojik sıra: 1150 → 1680 → 1945 → 2015.', 'chronologisch.'),
  },
  {
    id: 'dialog-fuehrung',
    type: 'dialogue',
    topic: 'geschichte',
    concept: 'history-facts',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Tourist', de: 'Wie alt ist die Kirche?' }],
    options: ['Sie wurde im 14. Jahrhundert gebaut.', 'Sie baute im 14. Jahrhundert.', 'Sie wird im 14. Jahrhundert gebaut.'],
    answer: 0,
    explanation: l('Past passive: wurde … gebaut.', 'Geçmiş edilgen: wurde … gebaut.', 'wurde gebaut.'),
  },
  {
    id: 'dialog-regel',
    type: 'dialogue',
    topic: 'passiv-modal',
    concept: 'rules',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Neuer Kollege', de: 'Gibt es hier im Büro Regeln für die Küche?' }],
    options: ['Ja, das Geschirr muss sofort gespült werden.', 'Ja, das Geschirr muss sofort werden gespült.', 'Ja, das Geschirr wird sofort spülen.'],
    answer: 0,
    explanation: l('Rules → muss … gespült werden.', 'Kurallar → muss … gespült werden.', 'muss … werden.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-gruendung',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-heidelberg',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wann wurde die Universität gegründet?',
    options: ['1386.', '1693.', '1928.'],
    answer: 0,
    explanation: l('„1386 wurde hier die älteste Universität Deutschlands gegründet.“', '„1386 wurde hier die älteste Universität Deutschlands gegründet.“', '1386.'),
  },
  {
    id: 'read-schloss',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-heidelberg',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was passierte 1693 mit dem Schloss?',
    options: ['Es wurde zerstört.', 'Es wurde gebaut.', 'Es wurde verkauft.'],
    answer: 0,
    explanation: l('„1693 wurde das Schloss im Krieg schwer zerstört.“', '„1693 wurde das Schloss im Krieg schwer zerstört.“', 'zerstört.'),
  },
  {
    id: 'read-aufgebaut',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-heidelberg',
    skill: 'reading',
    difficulty: 2,
    statement: 'Das Schloss wurde komplett wieder aufgebaut.',
    answer: false,
    explanation: l('„Es wurde nie ganz wieder aufgebaut.“', '„Es wurde nie ganz wieder aufgebaut.“', 'nie ganz.'),
  },
  {
    id: 'read-heute',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-heidelberg',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was muss heute gemacht werden?',
    options: ['Die Ruine muss regelmäßig restauriert werden.', 'Das Schloss muss abgerissen werden.', 'Nichts.'],
    answer: 0,
    explanation: l('„Heute muss die Ruine regelmäßig restauriert werden.“', '„Heute muss die Ruine regelmäßig restauriert werden.“', 'restauriert werden.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-jahr',
    type: 'listening_choice',
    topic: 'passiv-praeteritum',
    concept: 'history-facts',
    skill: 'listening',
    difficulty: 2,
    audio: 'Der Kölner Dom wurde 1248 begonnen und erst 1880 fertiggestellt.',
    question: l('When was the cathedral finished?', 'Katedral ne zaman tamamlandı?', 'Wann wurde der Dom fertig?'),
    options: ['1880', '1248', '1948'],
    answer: 0,
    explanation: l('„erst 1880 fertiggestellt“', '„erst 1880 fertiggestellt“', '1880.'),
  },
  {
    id: 'listen-modal',
    type: 'listening_choice',
    topic: 'passiv-modal',
    concept: 'rules',
    skill: 'listening',
    difficulty: 2,
    audio: 'In diesem Raum darf nicht gegessen und nicht getrunken werden.',
    question: l('What is not allowed?', 'Ne yasak?', 'Was ist verboten?'),
    options: ['🍔🥤 eating and drinking', '📸 photos', '📱 phones'],
    answer: 0,
    explanation: l('„nicht gegessen und nicht getrunken“', '„nicht gegessen und nicht getrunken“', 'essen und trinken.'),
  },
  {
    id: 'listen-wurden',
    type: 'listening_choice',
    topic: 'passiv-praeteritum',
    concept: 'wurden',
    skill: 'listening',
    difficulty: 2,
    audio: 'Bei dem Sturm wurden drei Bäume umgerissen, aber zum Glück wurde niemand verletzt.',
    question: l('Was anyone hurt?', 'Yaralanan oldu mu?', 'Wurde jemand verletzt?'),
    options: ['No', 'Yes, three people'],
    answer: 0,
    explanation: l('„wurde niemand verletzt“ = nobody was hurt.', '„wurde niemand verletzt“ = kimse yaralanmadı.', 'niemand.'),
  },
  {
    id: 'listen-reparatur',
    type: 'listening_choice',
    topic: 'passiv-modal',
    concept: 'modal-werden',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ihr Handy kann repariert werden, aber das dauert etwa eine Woche.',
    question: l('Can the phone be repaired?', 'Telefon tamir edilebilir mi?', 'Kann das Handy repariert werden?'),
    options: ['Yes, in about a week', 'No', 'Yes, today'],
    answer: 0,
    explanation: l('„kann repariert werden … etwa eine Woche“', '„kann repariert werden … etwa eine Woche“', 'ja, eine Woche.'),
  },

  ...auxDrills(),
]

export const UNIT_B1_04_PASSIV_VERGANGENHEIT: CourseUnit = {
  level: 'B1',
  number: 4,
  slug: 'passiv-vergangenheit',
  titleDe: 'Das Haus wurde 1890 gebaut',
  title: l('The house was built in 1890', 'Ev 1890’da inşa edildi', 'Das Haus wurde 1890 gebaut'),
  goal: l(
    'By the end of this unit you can talk about history and rules with the passive: Präteritum (wurde gebaut), Perfekt (ist gebaut worden) and with modal verbs (muss gemacht werden).',
    'Bu ünitenin sonunda tarih ve kurallar hakkında edilgen çatıyla konuşabilirsin: Präteritum (wurde gebaut), Perfekt (ist gebaut worden) ve modal fiillerle (muss gemacht werden).',
    'Am Ende dieser Einheit sprichst du über Geschichte und Regeln im Passiv.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'passiv-praeteritum', label: l('wurde gebaut', 'wurde gebaut', 'Passiv Präteritum') },
    { key: 'passiv-modal', label: l('muss gemacht werden', 'muss gemacht werden', 'Passiv mit Modalverb') },
    { key: 'geschichte', label: l('History & sights', 'Tarih ve görülecek yerler', 'Geschichte') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Words for history, sights and rules.', 'Tarih, görülecek yerler ve kurallar için kelimeler.', 'Geschichte, Sehenswürdigkeiten, Regeln.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Passive in the past', 'Geçmişte edilgen', 'Passiv in der Vergangenheit'),
          body: l(
            'Präteritum: wurde/wurden + participle (common in texts). Perfekt: ist/sind + participle + worden (spoken). Note: worden, not geworden!',
            'Präteritum: wurde/wurden + ortaç (metinlerde yaygın). Perfekt: ist/sind + ortaç + worden (konuşma dili). Dikkat: worden, geworden değil!',
            'wurde gebaut · ist gebaut worden.'
          ),
          table: {
            head: [l('Tense', 'Zaman', 'Zeit'), l('Singular', 'Tekil', 'Singular'), l('Plural', 'Çoğul', 'Plural')],
            rows: [
              ['Präsens', 'Das Haus wird gebaut.', 'Die Häuser werden gebaut.'],
              ['Präteritum', 'Das Haus wurde gebaut.', 'Die Häuser wurden gebaut.'],
              ['Perfekt', 'Das Haus ist gebaut worden.', 'Die Häuser sind gebaut worden.'],
            ],
          },
        },
        {
          title: l('Passive with modal verbs', 'Modal fiilli edilgen', 'Passiv mit Modalverben'),
          body: l(
            'Modal verb (position 2) + … + participle + werden (end). Very common for rules and instructions: muss gemacht werden, kann repariert werden, darf nicht geraucht werden.',
            'Modal fiil (2. sıra) + … + ortaç + werden (son). Kurallar ve talimatlar için çok yaygın: muss gemacht werden, kann repariert werden, darf nicht geraucht werden.',
            'Modalverb … Partizip + werden.'
          ),
          examples: [
            { de: 'Das Formular **muss** unterschrieben **werden**.', translation: l('The form must be signed.', 'Formun imzalanması gerekiyor.', '') },
            { de: 'Hier **darf** nicht geparkt **werden**.', translation: l('Parking is not allowed here.', 'Buraya park edilemez.', '') },
          ],
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A city tour through Heidelberg.', 'Heidelberg’de bir şehir turu.', 'Stadtführung in Heidelberg.'),
      dialogue: [
        { speaker: 'Stadtführer', de: 'Willkommen in Heidelberg! Hier **wurde** 1386 die älteste Universität Deutschlands **gegründet**.', translation: l('Welcome to Heidelberg! Germany’s oldest university was founded here in 1386.', 'Heidelberg’e hoş geldiniz! Almanya’nın en eski üniversitesi 1386’da burada kuruldu.', '') },
        { speaker: 'Touristin', de: 'Und das Schloss? **Wurde** es auch damals **gebaut**?', translation: l('And the castle? Was it built back then too?', 'Peki şato? O da o zamanlar mı inşa edildi?', '') },
        { speaker: 'Stadtführer', de: 'Ungefähr. Aber 1693 **wurde** es im Krieg schwer **zerstört**.', translation: l('Roughly. But in 1693 it was badly destroyed in the war.', 'Aşağı yukarı. Ama 1693’te savaşta ağır hasar gördü.', '') },
        { speaker: 'Touristin', de: '**Ist** es danach wieder **aufgebaut worden**?', translation: l('Was it rebuilt afterwards?', 'Sonra yeniden inşa edildi mi?', '') },
        { speaker: 'Stadtführer', de: 'Nur teilweise. Heute **muss** die Ruine regelmäßig **restauriert werden**.', translation: l('Only partly. Today the ruin has to be restored regularly.', 'Sadece kısmen. Bugün harabenin düzenli olarak restore edilmesi gerekiyor.', '') },
        { speaker: 'Touristin', de: '**Darf** im Schloss **fotografiert werden**?', translation: l('Is photography allowed in the castle?', 'Şatoda fotoğraf çekilebilir mi?', '') },
        { speaker: 'Stadtführer', de: 'Draußen ja, im Museum leider nicht.', translation: l('Outside yes, in the museum unfortunately not.', 'Dışarıda evet, müzede maalesef hayır.', '') },
      ],
      examples: [
        { de: 'Die Burg **wurde** 1150 **gebaut**.', translation: l('The castle was built in 1150.', 'Kale 1150’de inşa edildi.', '') },
        { de: 'Viele Häuser **wurden** **zerstört**.', translation: l('Many houses were destroyed.', 'Birçok ev yıkıldı.', '') },
        { de: 'Das Paket **ist** gestern **geliefert worden**.', translation: l('The parcel was delivered yesterday.', 'Koli dün teslim edildi.', '') },
        { de: 'Das **muss** heute noch **gemacht werden**.', translation: l('That has to be done today.', 'Bunun bugün yapılması gerekiyor.', '') },
        { de: 'Das Auto **kann** nicht **repariert werden**.', translation: l('The car can’t be repaired.', 'Araba tamir edilemez.', '') },
        { de: 'Hier **darf** nicht **geraucht werden**.', translation: l('No smoking here.', 'Burada sigara içilmez.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('wurde, wurden, worden – or werden?', 'wurde, wurden, worden – yoksa werden mi?', 'wurde, wurden, worden?'),
      exercises: ['sort-zeit', 'pv-burg', 'pv-haeuser', 'match-geschichte', 'mc-modal', 'tf-worden', 'select-richtig', 'image-erfindung', 'pv-formular'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('History and rules.', 'Tarih ve kurallar.', 'Geschichte und Regeln.'),
      exercises: [
        'fill-wurde',
        'fill-gegruendet',
        'fill-werden',
        'build-wurde',
        'build-modal',
        'build-von',
        'fix-wurden',
        'fix-geworden',
        'fix-modal-order',
        'tr-wurde',
        'tr-kann',
        'ordering-stadt',
        'dialog-fuehrung',
        'dialog-regel',
        'pv-telefon',
        'pv-bruecke',
        'pv-auto',
        'pv-zimmer',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A text from a travel guide about Heidelberg.', 'Bir seyahat rehberinden Heidelberg hakkında bir metin.', 'Aus einem Reiseführer.'),
      passage: [
        '**Heidelberg** – 1386 **wurde** hier die älteste Universität Deutschlands **gegründet**.',
        'Das berühmte Schloss **wurde** im 13. Jahrhundert **gebaut**. 1693 **wurde** es im Krieg schwer **zerstört** und nie ganz wieder **aufgebaut**.',
        'Heute **muss** die Ruine regelmäßig **restauriert werden**. Jedes Jahr **wird** sie von über einer Million Touristen **besucht**.',
        'Tipp: Die Altstadt **kann** am besten zu Fuß **erkundet werden**.',
      ],
      glossary: [
        { de: 'die Ruine', note: l('ruin', 'harabe', 'kaputtes altes Gebäude') },
        { de: 'restaurieren', note: l('to restore', 'restore etmek', 'reparieren (alte Dinge)') },
        { de: 'erkunden', note: l('to explore', 'keşfetmek', 'kennenlernen') },
      ],
      exercises: ['read-gruendung', 'read-schloss', 'read-aufgebaut', 'read-heute'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('History, rules, repairs.', 'Tarih, kurallar, tamirler.', 'Geschichte, Regeln, Reparaturen.'),
      exercises: ['listen-jahr', 'listen-modal', 'listen-wurden', 'listen-reparatur'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Present a famous building or place from your country – like a city guide.', 'Ülkenden ünlü bir yapıyı ya da yeri tanıt – bir şehir rehberi gibi.', 'Stell eine Sehenswürdigkeit vor.'),
      points: [
        l('When was it built / founded? („… wurde … gebaut.“)', 'Ne zaman inşa edildi / kuruldu? („… wurde … gebaut.“)', 'Wann gebaut?'),
        l('What happened later? (zerstört, renoviert …)', 'Sonra ne oldu? (zerstört, renoviert …)', 'Was passierte?'),
        l('Today: „Heute wird es von … besucht.“', 'Bugün: „Heute wird es von … besucht.“', 'Heute'),
        l('A rule for visitors: „Dort darf/muss … werden.“', 'Ziyaretçiler için bir kural: „Dort darf/muss … werden.“', 'Regel'),
      ],
      model: [
        'Ich stelle die Hagia Sophia in Istanbul vor.',
        'Sie wurde im 6. Jahrhundert gebaut.',
        'Später wurde sie mehrmals umgebaut und renoviert.',
        'Heute wird sie jedes Jahr von Millionen Menschen besucht.',
        'Drinnen müssen die Schuhe ausgezogen werden.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short history of your town or a building (at least 5 sentences) – use the past passive and one rule with a modal verb.',
        'Kasabanın ya da bir yapının kısa tarihini yaz (en az 5 cümle) – geçmiş edilgeni ve modal fiilli bir kural kullan.',
        'Schreib eine kurze Geschichte deiner Stadt (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Past passive (wurde/wurden + participle)', 'Geçmiş edilgen (wurde/wurden + ortaç)', 'Passiv Präteritum'), pattern: '\\b(wurde|wurden)\\b[^.!?]*\\b\\p{Ll}+(t|en)[.!?]' },
        { label: l('Passive with modal (… werden.)', 'Modal fiilli edilgen (… werden.)', 'Passiv mit Modalverb'), pattern: '\\b(muss|müssen|kann|können|darf|dürfen|soll|sollen)\\b[^.!?]*\\b\\p{Ll}+(t|en) werden[.!?]' },
        { label: l('A year or century', 'Bir yıl ya da yüzyıl', 'Ein Jahr oder Jahrhundert'), pattern: '\\b(1\\d{3}|20\\d{2}|\\d{1,2}\\. Jahrhundert)\\b' },
      ],
      model: [
        'Meine Heimatstadt Bursa wurde vor über 2000 Jahren gegründet.',
        'Im 14. Jahrhundert wurde sie die erste Hauptstadt des Osmanischen Reiches.',
        'Viele schöne Moscheen und Bäder wurden damals gebaut.',
        'Die Altstadt wurde 2014 zum Weltkulturerbe erklärt.',
        'Heute muss sie gut geschützt werden.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('wurde, wurden or werden? – 60 seconds.', 'wurde, wurden ya da werden? – 60 saniye.', 'wurde, wurden oder werden? – 60 Sekunden.'),
      seconds: 60,
      pool: [...DRILLS.map(([id]) => `pv-${id}`), 'mc-modal'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Past passive: wurde/wurden + participle', 'Geçmiş edilgen: wurde/wurden + ortaç', 'Passiv Präteritum'),
      l('Perfekt passive: ist/sind + participle + worden', 'Perfekt edilgen: ist/sind + ortaç + worden', 'Passiv Perfekt'),
      l('Modal + participle + werden: muss gemacht werden', 'Modal + ortaç + werden: muss gemacht werden', 'Passiv mit Modalverb'),
      l('History vocabulary: gründen, bauen, zerstören, renovieren', 'Tarih kelimeleri: gründen, bauen, zerstören, renovieren', 'Geschichte'),
    ],
    mistakes: [
      { wrong: 'Die Häuser wurde zerstört.', right: 'Die Häuser wurden zerstört.', note: l('Plural → wurden.', 'Çoğul → wurden.', 'wurden.') },
      { wrong: 'Es ist gebaut geworden.', right: 'Es ist gebaut worden.', note: l('worden.', 'worden.', 'worden.') },
      { wrong: 'Das muss werden gemacht.', right: 'Das muss gemacht werden.', note: l('participle + werden.', 'ortaç + werden.', 'gemacht werden.') },
      { wrong: 'Die Stadt wurde gründet.', right: 'Die Stadt wurde gegründet.', note: l('Participle with ge-.', 'ge- ile ortaç.', 'gegründet.') },
    ],
  },
}
