import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'hatte … gemacht', emoji: '⏪', translation: l('had done', 'yapmıştı', 'Plusquamperfekt mit haben'), example: 'Ich hatte schon gegessen.' },
  { word: 'war … gegangen', emoji: '🚪', translation: l('had gone', 'gitmişti', 'Plusquamperfekt mit sein'), example: 'Der Zug war schon abgefahren.' },
  { word: 'nachdem', emoji: '➡️', translation: l('after (+ Plusquamperfekt)', '-dıktan sonra', 'zuerst das, dann das'), example: 'Nachdem ich gegessen hatte, ging ich spazieren.' },
  { word: 'schon / bereits', emoji: '✅', translation: l('already', 'zaten, çoktan', 'früher als erwartet'), example: 'Als ich ankam, war der Film schon zu Ende.' },
  { word: 'noch nicht', emoji: '⏳', translation: l('not yet', 'henüz değil', 'bis jetzt nicht'), example: 'Ich hatte noch nicht gefrühstückt.' },
  { word: 'vorher', emoji: '⬅️', translation: l('before, beforehand', 'önceden', 'davor'), example: 'Vorher hatte ich nie Sushi gegessen.' },
  { word: 'danach', emoji: '⏭️', translation: l('afterwards', 'ondan sonra', 'später'), example: 'Danach gingen wir ins Kino.' },
  { word: 'abfahren', emoji: '🚆', translation: l('to depart', 'kalkmak', 'losfahren'), example: 'Der Bus war schon abgefahren.' },
  { word: 'vergessen', emoji: '🤦', translation: l('to forget', 'unutmak', 'nicht mehr wissen'), example: 'Ich hatte meinen Schlüssel vergessen.' },
  { word: 'verlieren', emoji: '🔎', translation: l('to lose', 'kaybetmek', 'nicht mehr finden'), example: 'Sie hatte ihr Handy verloren.' },
  { word: 'die Reihenfolge', emoji: '🔢', translation: l('order, sequence', 'sıra', 'was zuerst, was danach'), example: 'Erzähl die Geschichte in der richtigen Reihenfolge.' },
  { word: 'die Vorgeschichte', emoji: '📜', translation: l('backstory', 'geçmiş, arka plan', 'was vorher passiert war'), example: 'Kennst du die Vorgeschichte?' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Schlüssel', gender: 'm', plural: 'die Schlüssel', translation: l('key', 'anahtar', 'Schlüssel') },
  { word: 'Zug', gender: 'm', plural: 'die Züge', translation: l('train', 'tren', 'Zug') },
  { word: 'Film', gender: 'm', plural: 'die Filme', translation: l('film', 'film', 'Film') },
  { word: 'Handy', gender: 'n', plural: 'die Handys', translation: l('mobile', 'cep telefonu', 'Handy') },
  { word: 'Reihenfolge', gender: 'f', plural: 'die Reihenfolgen', translation: l('order', 'sıra', 'Reihenfolge') },
  { word: 'Party', gender: 'f', plural: 'die Partys', translation: l('party', 'parti', 'Party') },
]

/** [id, sentence with ___ for the auxiliary, right, wrongA, wrongB, uses sein] */
const PQP: [string, string, string, string, string, boolean][] = [
  ['gegessen', 'Als ich nach Hause kam, ___ meine Familie schon gegessen.', 'hatte', 'war', 'hat', false],
  ['abgefahren', 'Als wir am Bahnhof ankamen, ___ der Zug schon abgefahren.', 'war', 'hatte', 'ist', true],
  ['vergessen', 'Ich konnte nicht in die Wohnung, weil ich meinen Schlüssel vergessen ___.', 'hatte', 'war', 'habe', false],
  ['angefangen', 'Der Film ___ schon angefangen, als wir ins Kino kamen.', 'hatte', 'war', 'hat', false],
  ['eingeschlafen', 'Die Kinder ___ schon eingeschlafen, als die Eltern zurückkamen.', 'waren', 'hatten', 'sind', true],
  ['gelernt', 'Nachdem sie drei Jahre Deutsch gelernt ___, zog sie nach Berlin.', 'hatte', 'war', 'hat', false],
]

function pqpDrills(): Exercise[] {
  return PQP.map(([id, sentence, right, wrongA, wrongB, sein], i) => {
    const options = [right, wrongA, wrongB]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `pqp-${id}`,
      type: 'multiple_choice' as const,
      topic: 'pqp-bildung',
      concept: sein ? 'pqp-war' : 'pqp-hatte',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: sein
        ? l(`Earlier past + sein verb → ${right} + participle (Plusquamperfekt).`, `Daha önceki geçmiş + sein fiili → ${right} + ortaç (Plusquamperfekt).`, `${right} + Partizip.`)
        : l(`Earlier past + haben verb → ${right} + participle (Plusquamperfekt).`, `Daha önceki geçmiş + haben fiili → ${right} + ortaç (Plusquamperfekt).`, `${right} + Partizip.`),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'mc-was-zuerst',
    type: 'multiple_choice',
    topic: 'vorzeitigkeit',
    concept: 'earlier-event',
    skill: 'reading',
    difficulty: 2,
    prompt: '„Als ich ankam, war der Bus schon abgefahren.“ – Was passierte zuerst?',
    promptL10n: l('What happened first?', 'Önce ne oldu?', 'Was passierte zuerst?'),
    options: ['Der Bus fuhr ab.', 'Ich kam an.', 'Beides gleichzeitig.'],
    answer: 0,
    explanation: l('Plusquamperfekt (war abgefahren) = the earlier event.', 'Plusquamperfekt (war abgefahren) = daha önceki olay.', 'Plusquamperfekt = zuerst.'),
    practice: ['pqp-abgefahren'],
  },
  {
    id: 'sort-hatte-war',
    type: 'categorize',
    topic: 'pqp-bildung',
    concept: 'pqp-aux',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('hatte or war?', 'hatte mı war mı?', 'hatte oder war?'),
    categories: ['hatte …', 'war …'],
    items: [
      { text: '… gegessen', category: 0 },
      { text: '… gefahren', category: 1 },
      { text: '… vergessen', category: 0 },
      { text: '… eingeschlafen', category: 1 },
      { text: '… gearbeitet', category: 0 },
      { text: '… gekommen', category: 1 },
    ],
    explanation: l('Same as the Perfekt: haben → hatte, sein → war.', 'Perfekt’teki gibi: haben → hatte, sein → war.', 'wie im Perfekt.'),
    practice: ['pqp-gegessen', 'pqp-eingeschlafen'],
  },
  {
    id: 'match-zeiten',
    type: 'matching',
    topic: 'pqp-bildung',
    concept: 'perfekt-pqp',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Perfekt → Plusquamperfekt.', 'Perfekt → Plusquamperfekt.', 'Perfekt → Plusquamperfekt.'),
    pairs: [
      { left: 'ich habe gegessen', right: 'ich hatte gegessen' },
      { left: 'er ist gegangen', right: 'er war gegangen' },
      { left: 'wir haben gelernt', right: 'wir hatten gelernt' },
      { left: 'sie sind gekommen', right: 'sie waren gekommen' },
    ],
    explanation: l('Change habe/bin to hatte/war; the participle stays the same.', 'habe/bin’i hatte/war yap; ortaç aynı kalır.', 'hatte / war + Partizip.'),
  },
  {
    id: 'tf-nachdem',
    type: 'true_false',
    topic: 'nachdem',
    concept: 'nachdem-tense',
    skill: 'grammar',
    difficulty: 3,
    statement: 'Nach „nachdem“ steht oft das Plusquamperfekt, wenn der Hauptsatz im Präteritum ist.',
    answer: true,
    explanation: l('Nachdem ich gegessen hatte (PQP), ging ich spazieren (Präteritum). The nachdem-action is earlier.', 'Nachdem ich gegessen hatte (PQP), ging ich spazieren (Präteritum). nachdem eylemi daha öncedir.', 'nachdem + PQP.'),
    examples: ['**Nachdem** ich gegessen **hatte**, ging ich spazieren.'],
  },
  {
    id: 'select-richtig',
    type: 'multiple_select',
    topic: 'pqp-bildung',
    concept: 'pqp-mixed',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche Sätze sind richtig?'),
    options: ['Ich hatte schon gefrühstückt.', 'Ich war schon gefrühstückt.', 'Er war nach Hause gegangen.', 'Wir hatten den Film schon gesehen.', 'Sie hatte schon abgefahren.'],
    answers: [0, 2, 3],
    explanation: l('frühstücken, sehen → hatte; gehen, abfahren → war.', 'frühstücken, sehen → hatte; gehen, abfahren → war.', 'hatte / war.'),
  },
  {
    id: 'image-zu-spaet',
    type: 'image_choice',
    topic: 'vorzeitigkeit',
    concept: 'earlier-event',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Als wir ins Kino kamen, hatte der Film schon angefangen.',
    options: [
      { emoji: '🎬⏰', label: 'zu spät' },
      { emoji: '🎟️😊', label: 'pünktlich' },
      { emoji: '🍿🕐', label: 'zu früh' },
      { emoji: '🏠', label: 'zu Hause' },
    ],
    answer: 0,
    explanation: l('The film had already started → they were late.', 'Film çoktan başlamıştı → geç kaldılar.', 'zu spät.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-hatte',
    type: 'fill_blank',
    topic: 'pqp-bildung',
    concept: 'pqp-hatte',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich war sehr müde, weil ich schlecht geschlafen ___.',
    accepted: ['hatte'],
    base: 'haben → PQP',
    explanation: l('Earlier than „war müde“ → hatte geschlafen.', '„war müde“dan daha önce → hatte geschlafen.', 'hatte.'),
    examples: ['…, weil ich schlecht geschlafen **hatte**.'],
  },
  {
    id: 'fill-war',
    type: 'fill_blank',
    topic: 'pqp-bildung',
    concept: 'pqp-war',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Als ich anrief, ___ sie schon ins Bett gegangen.',
    accepted: ['war'],
    base: 'sein → PQP',
    explanation: l('gehen → sein → war gegangen.', 'gehen → sein → war gegangen.', 'war.'),
    examples: ['Als ich anrief, **war** sie schon ins Bett **gegangen**.'],
  },
  {
    id: 'fill-nachdem',
    type: 'fill_blank',
    topic: 'nachdem',
    concept: 'nachdem-word',
    skill: 'grammar',
    difficulty: 2,
    sentence: '___ er die Prüfung bestanden hatte, feierte er mit Freunden.',
    accepted: ['Nachdem'],
    base: 'Konnektor',
    explanation: l('First the exam, then the party → Nachdem.', 'Önce sınav, sonra parti → Nachdem.', 'Nachdem.'),
    examples: ['**Nachdem** er die Prüfung bestanden **hatte**, feierte er.'],
  },
  {
    id: 'build-nachdem',
    type: 'sentence_builder',
    topic: 'nachdem',
    concept: 'nachdem-word-order',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ging', 'ich', 'Nachdem ich gefrühstückt hatte,', 'zur Arbeit'],
    answers: [['Nachdem ich gefrühstückt hatte,', 'ging', 'ich', 'zur Arbeit']],
    translation: l('After I had had breakfast, I went to work.', 'Kahvaltı yaptıktan sonra işe gittim.', 'Nachdem ich gefrühstückt hatte, ging ich zur Arbeit.'),
    explanation: l('nachdem-clause (PQP) first → verb (Präteritum), subject.', 'nachdem-cümlesi (PQP) başta → fiil (Präteritum), özne.', 'Nachdem …, ging ich …'),
    examples: ['Nachdem ich gefrühstückt **hatte**, **ging** ich zur Arbeit.'],
  },
  {
    id: 'build-schon',
    type: 'sentence_builder',
    topic: 'vorzeitigkeit',
    concept: 'pqp-schon',
    skill: 'grammar',
    difficulty: 2,
    chips: ['schon', 'alle Kekse', 'Mein Bruder', 'gegessen', 'hatte'],
    answers: [['Mein Bruder', 'hatte', 'schon', 'alle Kekse', 'gegessen']],
    translation: l('My brother had already eaten all the biscuits.', 'Kardeşim bütün kurabiyeleri çoktan yemişti.', 'Mein Bruder hatte schon alle Kekse gegessen.'),
    explanation: l('hatte (2) … participle (end).', 'hatte (2) … ortaç (son).', 'hatte … gegessen.'),
    examples: ['Mein Bruder **hatte** schon alle Kekse **gegessen**.'],
  },
  {
    id: 'build-weil',
    type: 'sentence_builder',
    topic: 'vorzeitigkeit',
    concept: 'pqp-subclause',
    skill: 'grammar',
    difficulty: 3,
    chips: ['verloren hatte', 'weil', 'Sie war traurig,', 'ihren Ring', 'sie'],
    answers: [['Sie war traurig,', 'weil', 'sie', 'ihren Ring', 'verloren hatte']],
    translation: l('She was sad because she had lost her ring.', 'Yüzüğünü kaybettiği için üzgündü.', 'Sie war traurig, weil sie ihren Ring verloren hatte.'),
    explanation: l('Subordinate clause: participle + hatte at the end.', 'Yan cümle: ortaç + hatte sonda.', '… verloren hatte.'),
    examples: ['…, weil sie ihren Ring **verloren hatte**.'],
  },
  {
    id: 'fix-hat-hatte',
    type: 'error_correction',
    topic: 'nachdem',
    concept: 'nachdem-tense',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Nachdem ich gegessen habe, ging ich spazieren.',
    accepted: ['Nachdem ich gegessen hatte, ging ich spazieren.'],
    explanation: l('Main clause in the past → nachdem + Plusquamperfekt (hatte).', 'Ana cümle geçmişte → nachdem + Plusquamperfekt (hatte).', 'hatte.'),
    examples: ['Nachdem ich gegessen **hatte**, ging ich spazieren.'],
  },
  {
    id: 'fix-hatte-war',
    type: 'error_correction',
    topic: 'pqp-bildung',
    concept: 'pqp-war',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Als ich ankam, hatte der Zug schon abgefahren.',
    accepted: ['Als ich ankam, war der Zug schon abgefahren.'],
    explanation: l('abfahren → sein → war abgefahren.', 'abfahren → sein → war abgefahren.', 'war.'),
    examples: ['…, **war** der Zug schon **abgefahren**.'],
  },
  {
    id: 'fix-nachdem-main',
    type: 'error_correction',
    topic: 'nachdem',
    concept: 'nachdem-word-order',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Nachdem wir die Wohnung geputzt hatten, wir haben Pizza bestellt.',
    accepted: ['Nachdem wir die Wohnung geputzt hatten, haben wir Pizza bestellt.', 'Nachdem wir die Wohnung geputzt hatten, bestellten wir Pizza.'],
    explanation: l('Clause first → verb, verb.', 'Yan cümle başta → fiil, fiil.', '…, haben wir …'),
    examples: ['…, **haben wir** Pizza bestellt.'],
  },
  {
    id: 'tr-schon',
    type: 'translation',
    topic: 'vorzeitigkeit',
    concept: 'pqp-schon',
    skill: 'writing',
    difficulty: 2,
    source: l('When I arrived, the film had already started.', 'Vardığımda film çoktan başlamıştı.', 'When I arrived, the film had already started.'),
    accepted: ['Als ich ankam, hatte der Film schon angefangen.', 'Als ich ankam, hatte der Film schon begonnen.', 'Als ich ankam, hatte der Film bereits angefangen.'],
    explanation: l('Als … ankam, hatte … angefangen.', 'Als … ankam, hatte … angefangen.', 'hatte … angefangen.'),
    examples: ['Als ich ankam, **hatte** der Film schon **angefangen**.'],
  },
  {
    id: 'tr-nachdem',
    type: 'translation',
    topic: 'nachdem',
    concept: 'nachdem-word',
    skill: 'writing',
    difficulty: 3,
    source: l('After she had finished work, she went home.', 'İşi bitirdikten sonra eve gitti.', 'After she had finished work, she went home.'),
    accepted: ['Nachdem sie die Arbeit beendet hatte, ging sie nach Hause.', 'Nachdem sie mit der Arbeit fertig war, ging sie nach Hause.', 'Nachdem sie die Arbeit beendet hatte, ist sie nach Hause gegangen.'],
    explanation: l('Nachdem … beendet hatte, ging sie …', 'Nachdem … beendet hatte, ging sie …', 'Nachdem …, ging sie …'),
    examples: ['**Nachdem** sie die Arbeit beendet **hatte**, **ging** sie nach Hause.'],
  },
  {
    id: 'ordering-pech',
    type: 'ordering',
    topic: 'vorzeitigkeit',
    concept: 'story-order',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('In which order did it really happen?', 'Gerçekte hangi sırayla oldu?', 'In welcher Reihenfolge passierte es wirklich?'),
    items: ['Ich kam zum Flughafen.', 'Ich hatte meinen Pass zu Hause vergessen.', 'Ich fuhr zurück nach Hause.', 'Mein Flug war weg.'],
    answer: ['Ich hatte meinen Pass zu Hause vergessen.', 'Ich kam zum Flughafen.', 'Ich fuhr zurück nach Hause.', 'Mein Flug war weg.'],
    explanation: l('The Plusquamperfekt event (vergessen) happened first.', 'Plusquamperfekt olayı (vergessen) önce oldu.', 'PQP = zuerst.'),
  },
  {
    id: 'dialog-warum',
    type: 'dialogue',
    topic: 'vorzeitigkeit',
    concept: 'pqp-subclause',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Chef', de: 'Warum sind Sie gestern nicht zur Besprechung gekommen?' }],
    options: ['Ich hatte die E-Mail leider nicht gelesen.', 'Ich war die E-Mail nicht gelesen.', 'Ich habe die E-Mail lesen hatte.'],
    answer: 0,
    explanation: l('Earlier than not coming → hatte … gelesen.', 'Gelmemekten önce → hatte … gelesen.', 'hatte … gelesen.'),
  },
  {
    id: 'dialog-party',
    type: 'dialogue',
    topic: 'vorzeitigkeit',
    concept: 'pqp-war',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freundin', de: 'Hast du Tom auf der Party gesehen?' }],
    options: ['Nein, als ich kam, war er schon nach Hause gegangen.', 'Nein, als ich kam, hatte er schon nach Hause gegangen.', 'Nein, als ich kam, ist er schon gegangen war.'],
    answer: 0,
    explanation: l('gehen → war gegangen.', 'gehen → war gegangen.', 'war gegangen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-was',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-pech',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was hatte Jonas zu Hause vergessen?',
    options: ['Seinen Reisepass.', 'Sein Handy.', 'Seinen Koffer.'],
    answer: 0,
    explanation: l('„… merkte ich, dass ich meinen Reisepass zu Hause vergessen hatte.“', '„… merkte ich, dass ich meinen Reisepass zu Hause vergessen hatte.“', 'Reisepass.'),
  },
  {
    id: 'read-zurueck',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-pech',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was war passiert, als er wieder am Flughafen war?',
    options: ['Das Flugzeug war schon abgeflogen.', 'Der Flug hatte Verspätung.', 'Er hatte seinen Koffer verloren.'],
    answer: 0,
    explanation: l('„Als ich zurück am Flughafen war, war das Flugzeug schon abgeflogen.“', '„Als ich zurück am Flughafen war, war das Flugzeug schon abgeflogen.“', 'abgeflogen.'),
  },
  {
    id: 'read-naechster',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-pech',
    skill: 'reading',
    difficulty: 2,
    statement: 'Jonas ist am nächsten Tag geflogen.',
    answer: true,
    explanation: l('„Nachdem ich ein neues Ticket gekauft hatte, flog ich am nächsten Morgen.“', '„Nachdem ich ein neues Ticket gekauft hatte, flog ich am nächsten Morgen.“', 'ja.'),
  },
  {
    id: 'read-lehre',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-pech',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was macht Jonas seitdem?',
    options: ['Er kontrolliert alles zweimal.', 'Er fliegt nicht mehr.', 'Er reist nur mit dem Zug.'],
    answer: 0,
    explanation: l('„Seitdem kontrolliere ich vor jeder Reise alles zweimal.“', '„Seitdem kontrolliere ich vor jeder Reise alles zweimal.“', 'zweimal kontrollieren.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-zuerst',
    type: 'listening_choice',
    topic: 'vorzeitigkeit',
    concept: 'earlier-event',
    skill: 'listening',
    difficulty: 2,
    audio: 'Als die Polizei kam, waren die Diebe schon geflohen.',
    question: l('Who was first?', 'Önce kim vardı / gitti?', 'Was passierte zuerst?'),
    options: ['the thieves fled', 'the police came'],
    answer: 0,
    explanation: l('„waren … geflohen“ = earlier.', '„waren … geflohen“ = daha önce.', 'Die Diebe flohen zuerst.'),
  },
  {
    id: 'listen-nachdem',
    type: 'listening_choice',
    topic: 'nachdem',
    concept: 'nachdem-word',
    skill: 'listening',
    difficulty: 2,
    audio: 'Nachdem wir den Kuchen gegessen hatten, haben wir Geschenke ausgepackt.',
    question: l('What did they do after the cake?', 'Pastadan sonra ne yaptılar?', 'Was machten sie nach dem Kuchen?'),
    options: ['🎁 opened presents', '💃 danced', '🎬 watched a film'],
    answer: 0,
    explanation: l('„Geschenke ausgepackt“', '„Geschenke ausgepackt“', 'Geschenke.'),
  },
  {
    id: 'listen-hatte',
    type: 'listening_choice',
    topic: 'pqp-bildung',
    concept: 'pqp-hatte',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich hatte vorher noch nie Sushi gegessen, aber es hat mir sofort geschmeckt.',
    question: l('Had the person eaten sushi before?', 'Kişi daha önce suşi yemiş miydi?', 'Hatte die Person vorher Sushi gegessen?'),
    options: ['No, never', 'Yes, often'],
    answer: 0,
    explanation: l('„noch nie … gegessen“', '„noch nie … gegessen“', 'nie.'),
  },
  {
    id: 'listen-verloren',
    type: 'listening_choice',
    topic: 'vorzeitigkeit',
    concept: 'pqp-subclause',
    skill: 'listening',
    difficulty: 2,
    audio: 'Sie konnte nicht bezahlen, weil sie ihr Portemonnaie im Bus verloren hatte.',
    question: l('Why couldn’t she pay?', 'Neden ödeyemedi?', 'Warum konnte sie nicht bezahlen?'),
    options: ['she had lost her purse', 'the card didn’t work', 'it was too expensive'],
    answer: 0,
    explanation: l('„ihr Portemonnaie … verloren hatte“', '„ihr Portemonnaie … verloren hatte“', 'Portemonnaie verloren.'),
  },

  ...pqpDrills(),
]

export const UNIT_B1_11_PLUSQUAMPERFEKT: CourseUnit = {
  level: 'B1',
  number: 11,
  slug: 'plusquamperfekt',
  titleDe: 'Nachdem ich gegessen hatte …',
  title: l('After I had eaten …', 'Yemek yedikten sonra …', 'Nachdem ich gegessen hatte …'),
  goal: l(
    'By the end of this unit you can tell stories with two levels of the past: the Plusquamperfekt (hatte/war + Partizip II) for what happened earlier – especially after nachdem.',
    'Bu ünitenin sonunda geçmişin iki katmanıyla hikâye anlatabilirsin: daha önce olanlar için Plusquamperfekt (hatte/war + Partizip II) – özellikle nachdem’den sonra.',
    'Am Ende dieser Einheit erzählst du mit dem Plusquamperfekt.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'pqp-bildung', label: l('hatte/war + Partizip II', 'hatte/war + Partizip II', 'Plusquamperfekt') },
    { key: 'nachdem', label: l('nachdem', 'nachdem', 'nachdem') },
    { key: 'vorzeitigkeit', label: l('What happened first?', 'Önce ne oldu?', 'Was passierte zuerst?') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The past before the past.', 'Geçmişten önceki geçmiş.', 'Die Vergangenheit vor der Vergangenheit.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Plusquamperfekt: hatte/war + Partizip II', 'Plusquamperfekt: hatte/war + Partizip II', 'Plusquamperfekt'),
          body: l(
            'When you tell a story in the past and want to say what had happened before, use the Plusquamperfekt: Präteritum of haben/sein + participle.',
            'Geçmişte bir hikâye anlatırken daha önce ne olduğunu söylemek istersen Plusquamperfekt kullan: haben/sein’ın Präteritum’u + ortaç.',
            'hatte/war + Partizip II.'
          ),
          table: {
            head: [l('Perfekt', 'Perfekt', 'Perfekt'), l('Plusquamperfekt', 'Plusquamperfekt', 'Plusquamperfekt')],
            rows: [
              ['ich habe gegessen', 'ich hatte gegessen'],
              ['du hast gearbeitet', 'du hattest gearbeitet'],
              ['er ist gegangen', 'er war gegangen'],
              ['wir sind gefahren', 'wir waren gefahren'],
            ],
          },
        },
        {
          title: l('Two levels of the past', 'Geçmişin iki katmanı', 'Zwei Ebenen der Vergangenheit'),
          body: l(
            'Earlier event → Plusquamperfekt. Later event → Präteritum/Perfekt. Als ich ankam (later), war der Zug schon abgefahren (earlier).',
            'Daha önceki olay → Plusquamperfekt. Sonraki olay → Präteritum/Perfekt. Als ich ankam (sonra), war der Zug schon abgefahren (önce).',
            'früher → PQP · später → Präteritum.'
          ),
        },
        {
          title: l('nachdem + Plusquamperfekt', 'nachdem + Plusquamperfekt', 'nachdem + Plusquamperfekt'),
          body: l('nachdem (after) introduces the earlier action: Nachdem ich gegessen hatte, ging ich spazieren. (Verb at the end, then verb, verb.)', 'nachdem (-dıktan sonra) daha önceki eylemi başlatır: Nachdem ich gegessen hatte, ging ich spazieren. (Fiil sonda, sonra fiil, fiil.)', 'Nachdem … hatte, ging ich …'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Jonas tells a friend about his unlucky holiday start.', 'Jonas bir arkadaşına şanssız tatil başlangıcını anlatıyor.', 'Jonas erzählt von seinem Pech.'),
      dialogue: [
        { speaker: 'Lea', de: 'Und, wie war der Urlaub in Spanien?', translation: l('So, how was the holiday in Spain?', 'Eee, İspanya’daki tatil nasıldı?', '') },
        { speaker: 'Jonas', de: 'Super – aber der Anfang war schrecklich! Am Flughafen merkte ich, dass ich meinen Pass zu Hause **vergessen hatte**.', translation: l('Great – but the start was terrible! At the airport I noticed I had forgotten my passport at home.', 'Harika – ama başlangıç korkunçtu! Havalimanında pasaportumu evde unuttuğumu fark ettim.', '') },
        { speaker: 'Lea', de: 'Oh nein! Und dann?', translation: l('Oh no! And then?', 'Olamaz! Sonra?', '') },
        { speaker: 'Jonas', de: 'Ich fuhr zurück. Als ich wieder am Flughafen war, **war** das Flugzeug schon **abgeflogen**.', translation: l('I went back. When I was back at the airport, the plane had already left.', 'Geri döndüm. Havalimanına tekrar geldiğimde uçak çoktan kalkmıştı.', '') },
        { speaker: 'Lea', de: 'Wie ärgerlich!', translation: l('How annoying!', 'Ne sinir bozucu!', '') },
        { speaker: 'Jonas', de: '**Nachdem** ich ein neues Ticket **gekauft hatte**, flog ich am nächsten Morgen. Seitdem kontrolliere ich alles zweimal!', translation: l('After I had bought a new ticket, I flew the next morning. Since then I check everything twice!', 'Yeni bir bilet aldıktan sonra ertesi sabah uçtum. O zamandan beri her şeyi iki kez kontrol ediyorum!', '') },
      ],
      examples: [
        { de: 'Ich **hatte** schon **gegessen**.', translation: l('I had already eaten.', 'Ben çoktan yemiştim.', '') },
        { de: 'Der Zug **war** schon **abgefahren**.', translation: l('The train had already left.', 'Tren çoktan kalkmıştı.', '') },
        { de: '**Nachdem** ich **gefrühstückt hatte**, ging ich los.', translation: l('After I had had breakfast, I left.', 'Kahvaltı yaptıktan sonra yola çıktım.', '') },
        { de: 'Sie war müde, weil sie schlecht **geschlafen hatte**.', translation: l('She was tired because she had slept badly.', 'Kötü uyuduğu için yorgundu.', '') },
        { de: 'Als wir kamen, **hatte** der Film schon **angefangen**.', translation: l('When we came, the film had already started.', 'Geldiğimizde film çoktan başlamıştı.', '') },
        { de: 'Ich **hatte** vorher nie Sushi **gegessen**.', translation: l('I had never eaten sushi before.', 'Daha önce hiç suşi yememiştim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('What happened first?', 'Önce ne oldu?', 'Was passierte zuerst?'),
      exercises: ['mc-was-zuerst', 'sort-hatte-war', 'match-zeiten', 'pqp-gegessen', 'pqp-abgefahren', 'tf-nachdem', 'select-richtig', 'image-zu-spaet', 'pqp-eingeschlafen'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Tell stories with two levels of the past.', 'Geçmişin iki katmanıyla hikâye anlat.', 'Erzähl mit zwei Zeitebenen.'),
      exercises: [
        'fill-hatte',
        'fill-war',
        'fill-nachdem',
        'build-nachdem',
        'build-schon',
        'build-weil',
        'fix-hat-hatte',
        'fix-hatte-war',
        'fix-nachdem-main',
        'tr-schon',
        'tr-nachdem',
        'ordering-pech',
        'dialog-warum',
        'dialog-party',
        'pqp-vergessen',
        'pqp-angefangen',
        'pqp-gelernt',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Jonas’s blog: „My worst holiday start“.', 'Jonas’un blogu: „En kötü tatil başlangıcım“.', 'Jonas’ Blog.'),
      passage: [
        'Im Juli wollte ich nach Barcelona fliegen. Am Flughafen merkte ich, dass ich meinen Reisepass zu Hause **vergessen hatte**!',
        'Ich nahm sofort ein Taxi nach Hause. Als ich zurück am Flughafen war, **war** das Flugzeug schon **abgeflogen**.',
        '**Nachdem** ich ein neues Ticket **gekauft hatte**, flog ich am nächsten Morgen. Das war teuer!',
        'Seitdem kontrolliere ich vor jeder Reise alles zweimal.',
      ],
      glossary: [
        { de: 'merken', note: l('to notice', 'fark etmek', 'bemerken') },
        { de: 'abfliegen', note: l('to take off (plane)', 'havalanmak', 'losfliegen') },
        { de: 'kontrollieren', note: l('to check', 'kontrol etmek', 'prüfen') },
      ],
      exercises: ['read-was', 'read-zurueck', 'read-naechster', 'read-lehre'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Which event came first?', 'Hangi olay önce oldu?', 'Was kam zuerst?'),
      exercises: ['listen-zuerst', 'listen-nachdem', 'listen-hatte', 'listen-verloren'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Tell about a day when something went wrong because you had forgotten or missed something.', 'Bir şeyi unuttuğun ya da kaçırdığın için bir şeylerin ters gittiği bir günü anlat.', 'Erzähl von einem Tag mit Pech.'),
      points: [
        l('What happened? (Präteritum/Perfekt)', 'Ne oldu? (Präteritum/Perfekt)', 'Was passierte?'),
        l('What had happened before? („Ich hatte … vergessen.“)', 'Daha önce ne olmuştu? („Ich hatte … vergessen.“)', 'Was war vorher passiert?'),
        l('„Als ich …, war/hatte … schon …“', '„Als ich …, war/hatte … schon …“', 'Als …, … schon …'),
        l('„Nachdem …, …“', '„Nachdem …, …“', 'Nachdem …'),
      ],
      model: [
        'Letzte Woche wollte ich ins Konzert gehen.',
        'Aber ich hatte die Tickets zu Hause vergessen!',
        'Als ich zurückkam, hatte das Konzert schon angefangen.',
        'Nachdem ich die Tickets gezeigt hatte, durfte ich trotzdem rein.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short story (at least 5 sentences) with the Plusquamperfekt and nachdem.',
        'Plusquamperfekt ve nachdem ile kısa bir hikâye yaz (en az 5 cümle).',
        'Schreib eine kurze Geschichte (mindestens 5 Sätze) mit Plusquamperfekt.'
      ),
      minSentences: 5,
      checks: [
        { label: l('hatte + participle', 'hatte + ortaç', 'hatte + Partizip'), pattern: '\\b(hatte|hattest|hatten|hattet)\\b[^.!?]*\\b\\p{Ll}*(ge|ver|be|er)\\p{Ll}+(t|en)\\b' },
        { label: l('war + participle', 'war + ortaç', 'war + Partizip'), pattern: '\\b(war|warst|waren|wart)\\b[^.!?]*\\b\\p{Ll}*ge\\p{Ll}+en\\b' },
        { label: l('nachdem', 'nachdem', 'nachdem'), pattern: '\\b[Nn]achdem\\b' },
      ],
      model: [
        'Letzten Samstag wollte ich meine Freundin überraschen.',
        'Ich hatte einen Kuchen gebacken und Blumen gekauft.',
        'Als ich bei ihr ankam, war sie schon weggefahren.',
        'Nachdem ich eine Stunde gewartet hatte, kam sie endlich zurück.',
        'Sie hatte bei mir geklingelt – um mich zu überraschen!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('hatte or war? – 60 seconds.', 'hatte mı war mı? – 60 saniye.', 'hatte oder war? – 60 Sekunden.'),
      seconds: 60,
      pool: [...PQP.map(([id]) => `pqp-${id}`), 'mc-was-zuerst'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Plusquamperfekt: hatte/war + Partizip II', 'Plusquamperfekt: hatte/war + Partizip II', 'Plusquamperfekt'),
      l('Earlier event → PQP, later event → Präteritum', 'Daha önceki olay → PQP, sonraki olay → Präteritum', 'Vorzeitigkeit'),
      l('nachdem + PQP, then verb, verb', 'nachdem + PQP, sonra fiil, fiil', 'nachdem'),
    ],
    mistakes: [
      { wrong: 'Nachdem ich gegessen habe, ging ich …', right: 'Nachdem ich gegessen hatte, ging ich …', note: l('Past → hatte.', 'Geçmiş → hatte.', 'hatte.') },
      { wrong: 'Der Zug hatte abgefahren.', right: 'Der Zug war abgefahren.', note: l('abfahren → sein.', 'abfahren → sein.', 'war.') },
      { wrong: 'Nachdem …, wir gingen …', right: 'Nachdem …, gingen wir …', note: l('Verb, verb.', 'Fiil, fiil.', 'Verb, Verb.') },
      { wrong: 'Ich hatte schon geschlaft.', right: 'Ich hatte schon geschlafen.', note: l('schlafen → geschlafen.', 'schlafen → geschlafen.', 'geschlafen.') },
    ],
  },
}
