import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Nachrichten', emoji: '📰', translation: l('the news', 'haberler', 'Infos über aktuelle Ereignisse'), example: 'Ich sehe jeden Abend die Nachrichten.' },
  { word: 'die Schlagzeile', emoji: '🗞️', translation: l('headline', 'manşet', 'Titel eines Artikels'), example: 'Die Schlagzeile war sehr dramatisch.' },
  { word: 'berichten über', emoji: '🎙️', translation: l('to report on', '… hakkında haber vermek', 'erzählen, informieren'), example: 'Die Zeitung berichtet über die Wahl.' },
  { word: 'laut + Dativ', emoji: '📊', translation: l('according to', '… -e göre', 'nach Angaben von'), example: 'Laut einer Studie lesen junge Leute weniger Zeitung.' },
  { word: 'die Umfrage', emoji: '📋', translation: l('survey', 'anket', 'man fragt viele Leute'), example: 'Eine Umfrage zeigt, dass …' },
  { word: 'die Hälfte', emoji: '🌓', translation: l('half', 'yarısı', '50 Prozent'), example: 'Die Hälfte der Befragten nutzt Instagram.' },
  { word: 'soziale Medien', emoji: '📱', translation: l('social media', 'sosyal medya', 'Instagram, TikTok …'), example: 'Viele informieren sich über soziale Medien.' },
  { word: 'die Falschmeldung', emoji: '🚩', translation: l('fake news', 'yalan haber', 'Fake News'), example: 'Man sollte Falschmeldungen nicht teilen.' },
  { word: 'teilen', emoji: '🔁', translation: l('to share', 'paylaşmak', 'weiterschicken'), example: 'Sie hat das Video geteilt.' },
  { word: 'die Quelle', emoji: '🔍', translation: l('source', 'kaynak', 'woher die Info kommt'), example: 'Prüf immer die Quelle!' },
  { word: 'zunehmen / abnehmen', emoji: '📈', translation: l('to increase / decrease', 'artmak / azalmak', 'mehr / weniger werden'), example: 'Die Zahl der Nutzer hat zugenommen.' },
  { word: 'die meisten', emoji: '👥', translation: l('most (people)', 'çoğu', 'mehr als die Hälfte'), example: 'Die meisten lesen Nachrichten am Handy.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Zeitung', gender: 'f', plural: 'die Zeitungen', translation: l('newspaper', 'gazete', 'Zeitung') },
  { word: 'Artikel', gender: 'm', plural: 'die Artikel', translation: l('article', 'makale', 'Artikel') },
  { word: 'Sendung', gender: 'f', plural: 'die Sendungen', translation: l('programme', 'yayın, program', 'Sendung') },
  { word: 'Studie', gender: 'f', plural: 'die Studien', translation: l('study', 'araştırma', 'Studie') },
  { word: 'Prozent', gender: 'n', plural: 'die Prozent', translation: l('per cent', 'yüzde', 'Prozent') },
  { word: 'Nutzer', gender: 'm', plural: 'die Nutzer', translation: l('user', 'kullanıcı', 'Nutzer') },
  { word: 'Beitrag', gender: 'm', plural: 'die Beiträge', translation: l('post, contribution', 'gönderi', 'Beitrag') },
  { word: 'Ereignis', gender: 'n', plural: 'die Ereignisse', translation: l('event', 'olay', 'Ereignis') },
]

/** [id, statistic phrase, meaning, wrong meanings] */
const STATS: [string, string, string, [string, string]][] = [
  ['haelfte', 'die Hälfte', '50 %', ['25 %', '75 %']],
  ['viertel', 'ein Viertel', '25 %', ['40 %', '50 %']],
  ['drittel', 'zwei Drittel', 'ca. 67 %', ['ca. 33 %', 'ca. 23 %']],
  ['jeder-zehnte', 'jeder Zehnte', '10 %', ['1 %', '90 %']],
  ['mehrheit', 'die Mehrheit', 'mehr als 50 %', ['weniger als 50 %', 'genau 50 %']],
]

function statDrills(): Exercise[] {
  return STATS.map(([id, phrase, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `stat-${id}`,
      type: 'multiple_choice' as const,
      topic: 'statistik',
      concept: 'fractions',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `„${phrase} der Befragten“ – wie viel ist das?`,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`${phrase} = ${right}.`, `${phrase} = ${right}.`, `${phrase} = ${right}.`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-medien',
    type: 'matching',
    topic: 'medien-wortschatz',
    concept: 'media-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match word and symbol.', 'Kelimeyi sembolle eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'die Schlagzeile', right: '🗞️' },
      { left: 'die Umfrage', right: '📋' },
      { left: 'die Falschmeldung', right: '🚩' },
      { left: 'teilen', right: '🔁' },
      { left: 'die Quelle', right: '🔍' },
    ],
    explanation: l('Media vocabulary.', 'Medya kelimeleri.', 'Medienwortschatz.'),
  },
  {
    id: 'sort-vor-nachteile',
    type: 'categorize',
    topic: 'soziale-medien',
    concept: 'pros-cons',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Social media: advantage or disadvantage?', 'Sosyal medya: avantaj mı dezavantaj mı?', 'Soziale Medien: Vorteil oder Nachteil?'),
    categories: ['Vorteil ➕', 'Nachteil ➖'],
    items: [
      { text: 'Man bleibt mit Freunden in Kontakt.', category: 0 },
      { text: 'Falschmeldungen verbreiten sich schnell.', category: 1 },
      { text: 'Man bekommt Infos sehr schnell.', category: 0 },
      { text: 'Man verbringt zu viel Zeit am Handy.', category: 1 },
      { text: 'Kleine Firmen können Werbung machen.', category: 0 },
      { text: 'Die Daten sind nicht sicher.', category: 1 },
    ],
    explanation: l('Pros and cons of social media.', 'Sosyal medyanın artı ve eksileri.', 'Vor- und Nachteile.'),
    practice: ['stat-haelfte'],
  },
  {
    id: 'mc-laut',
    type: 'multiple_choice',
    topic: 'nachrichten-verstehen',
    concept: 'laut-dativ',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Laut ___ Studie schlafen Jugendliche zu wenig.',
    options: ['einer', 'eine', 'einen'],
    answer: 0,
    explanation: l('laut + dative: laut einer Studie.', 'laut + yönelme (Dativ): laut einer Studie.', 'laut + Dativ.'),
    examples: ['Laut **einer** Studie schlafen Jugendliche zu wenig.'],
    practice: ['fill-laut'],
  },
  {
    id: 'tf-passiv-news',
    type: 'true_false',
    topic: 'nachrichten-verstehen',
    concept: 'news-passive',
    skill: 'grammar',
    difficulty: 2,
    statement: 'In Nachrichten liest man oft das Passiv: „Der Minister wurde gestern gewählt.“',
    answer: true,
    explanation: l('News often uses the passive (Präteritum): wurde gewählt, wurden verletzt.', 'Haberlerde sık sık edilgen (Präteritum) kullanılır: wurde gewählt, wurden verletzt.', 'Passiv in Nachrichten.'),
  },
  {
    id: 'select-quelle',
    type: 'multiple_select',
    topic: 'soziale-medien',
    concept: 'fake-news',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('How can you recognise fake news? Select all good tips.', 'Yalan haberi nasıl anlarsın? İyi ipuçlarının hepsini seç.', 'Wie erkennt man Falschmeldungen?'),
    options: ['die Quelle prüfen', 'nur die Schlagzeile lesen', 'andere Medien vergleichen', 'auf das Datum achten', 'sofort teilen'],
    answers: [0, 2, 3],
    explanation: l('Check the source, compare, check the date – and don’t share immediately.', 'Kaynağı kontrol et, karşılaştır, tarihe bak – ve hemen paylaşma.', 'Quelle, Vergleich, Datum.'),
  },
  {
    id: 'image-diagramm',
    type: 'image_choice',
    topic: 'statistik',
    concept: 'trend',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Zahl der Zeitungsleser hat stark abgenommen.',
    options: [
      { emoji: '📉', label: 'abgenommen' },
      { emoji: '📈', label: 'zugenommen' },
      { emoji: '➡️', label: 'gleich geblieben' },
      { emoji: '🔄', label: 'gewechselt' },
    ],
    answer: 0,
    explanation: l('abnehmen = to decrease 📉.', 'abnehmen = azalmak 📉.', 'abgenommen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-laut',
    type: 'fill_blank',
    topic: 'nachrichten-verstehen',
    concept: 'laut-dativ',
    skill: 'grammar',
    difficulty: 2,
    sentence: '___ einer Umfrage nutzen 80 Prozent der Jugendlichen TikTok.',
    accepted: ['Laut'],
    base: 'according to',
    explanation: l('Laut einer Umfrage …', 'Laut einer Umfrage …', 'Laut.'),
    examples: ['**Laut** einer Umfrage nutzen 80 Prozent der Jugendlichen TikTok.'],
  },
  {
    id: 'fill-zugenommen',
    type: 'fill_blank',
    topic: 'statistik',
    concept: 'trend',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Zahl der Online-Leser hat stark ___. (zunehmen)',
    accepted: ['zugenommen'],
    base: 'zunehmen',
    explanation: l('zunehmen → hat zugenommen (separable: zu-ge-nommen).', 'zunehmen → hat zugenommen (ayrılabilir: zu-ge-nommen).', 'zugenommen.'),
    examples: ['Die Zahl hat stark **zugenommen**.'],
  },
  {
    id: 'fill-berichtet',
    type: 'fill_blank',
    topic: 'nachrichten-verstehen',
    concept: 'berichten-ueber',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Die Zeitung berichtet ___ den Streik.',
    accepted: ['über'],
    base: 'berichten …',
    explanation: l('berichten über + accusative.', 'berichten über + belirtme (Akk).', 'über.'),
    examples: ['Die Zeitung berichtet **über** den Streik.'],
  },
  {
    id: 'build-umfrage',
    type: 'sentence_builder',
    topic: 'statistik',
    concept: 'describe-stats',
    skill: 'grammar',
    difficulty: 3,
    chips: ['dass', 'Die Umfrage zeigt,', 'Podcasts hören', 'die meisten', 'gern'],
    answers: [['Die Umfrage zeigt,', 'dass', 'die meisten', 'gern', 'Podcasts hören']],
    translation: l('The survey shows that most people like listening to podcasts.', 'Anket, çoğu kişinin podcast dinlemeyi sevdiğini gösteriyor.', 'Die Umfrage zeigt, dass die meisten gern Podcasts hören.'),
    explanation: l('… zeigt, dass … → verb at the end.', '… zeigt, dass … → fiil sonda.', 'dass … hören.'),
    examples: ['Die Umfrage zeigt, dass die meisten gern Podcasts **hören**.'],
  },
  {
    id: 'build-wurde',
    type: 'sentence_builder',
    topic: 'nachrichten-verstehen',
    concept: 'news-passive',
    skill: 'grammar',
    difficulty: 2,
    chips: ['eröffnet', 'wurde', 'Gestern', 'der neue Bahnhof'],
    answers: [['Gestern', 'wurde', 'der neue Bahnhof', 'eröffnet']],
    translation: l('Yesterday the new station was opened.', 'Dün yeni istasyon açıldı.', 'Gestern wurde der neue Bahnhof eröffnet.'),
    explanation: l('News passive: wurde … eröffnet.', 'Haber edilgeni: wurde … eröffnet.', 'wurde … eröffnet.'),
    examples: ['Gestern **wurde** der neue Bahnhof **eröffnet**.'],
  },
  {
    id: 'build-haelfte',
    type: 'sentence_builder',
    topic: 'statistik',
    concept: 'fractions',
    skill: 'grammar',
    difficulty: 2,
    chips: ['liest', 'Die Hälfte', 'keine Zeitung mehr', 'der Befragten'],
    answers: [['Die Hälfte', 'der Befragten', 'liest', 'keine Zeitung mehr']],
    translation: l('Half of those surveyed no longer read a newspaper.', 'Katılımcıların yarısı artık gazete okumuyor.', 'Die Hälfte der Befragten liest keine Zeitung mehr.'),
    explanation: l('die Hälfte is singular → liest.', 'die Hälfte tekildir → liest.', 'liest.'),
    examples: ['Die Hälfte der Befragten **liest** keine Zeitung mehr.'],
  },
  {
    id: 'fix-laut',
    type: 'error_correction',
    topic: 'nachrichten-verstehen',
    concept: 'laut-dativ',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Laut den Bericht steigen die Preise.',
    accepted: ['Laut dem Bericht steigen die Preise.'],
    explanation: l('laut + dative: dem Bericht.', 'laut + Dativ: dem Bericht.', 'dem Bericht.'),
    examples: ['Laut **dem** Bericht steigen die Preise.'],
  },
  {
    id: 'fix-teilen',
    type: 'error_correction',
    topic: 'soziale-medien',
    concept: 'fake-news',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie hat die Falschmeldung geteilen.',
    accepted: ['Sie hat die Falschmeldung geteilt.'],
    explanation: l('teilen → geteilt (regular).', 'teilen → geteilt (düzenli).', 'geteilt.'),
    examples: ['Sie hat die Falschmeldung **geteilt**.'],
  },
  {
    id: 'fix-meisten',
    type: 'error_correction',
    topic: 'statistik',
    concept: 'describe-stats',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Die meisten Leute liest Nachrichten online.',
    accepted: ['Die meisten Leute lesen Nachrichten online.'],
    explanation: l('die meisten Leute = plural → lesen.', 'die meisten Leute = çoğul → lesen.', 'lesen.'),
    examples: ['Die meisten Leute **lesen** Nachrichten online.'],
  },
  {
    id: 'tr-laut',
    type: 'translation',
    topic: 'nachrichten-verstehen',
    concept: 'laut-dativ',
    skill: 'writing',
    difficulty: 2,
    source: l('According to the news it will rain tomorrow.', 'Haberlere göre yarın yağmur yağacak.', 'According to the news it will rain tomorrow.'),
    accepted: ['Laut den Nachrichten regnet es morgen.', 'Laut den Nachrichten wird es morgen regnen.', 'Laut Nachrichten regnet es morgen.'],
    explanation: l('laut + dative plural: den Nachrichten.', 'laut + Dativ çoğul: den Nachrichten.', 'Laut den Nachrichten …'),
    examples: ['**Laut den** Nachrichten regnet es morgen.'],
  },
  {
    id: 'tr-quelle',
    type: 'translation',
    topic: 'soziale-medien',
    concept: 'fake-news',
    skill: 'writing',
    difficulty: 2,
    source: l('You should check the source.', 'Kaynağı kontrol etmelisin.', 'You should check the source.'),
    accepted: ['Du solltest die Quelle prüfen.', 'Man sollte die Quelle prüfen.', 'Du solltest die Quelle überprüfen.', 'Man sollte die Quelle überprüfen.'],
    explanation: l('die Quelle prüfen = to check the source.', 'die Quelle prüfen = kaynağı kontrol etmek.', 'die Quelle prüfen.'),
    examples: ['Du solltest **die Quelle prüfen**.'],
  },
  {
    id: 'ordering-grafik',
    type: 'ordering',
    topic: 'statistik',
    concept: 'describe-stats',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Describe a chart in the typical order.', 'Bir grafiği tipik sırayla anlat.', 'Grafikbeschreibung: Reihenfolge.'),
    items: ['An zweiter Stelle steht das Fernsehen mit 30 Prozent.', 'Die Grafik zeigt, wie sich junge Leute informieren.', 'Insgesamt sieht man, dass das Internet am wichtigsten ist.', 'Die meisten, nämlich 60 Prozent, nutzen das Internet.'],
    answer: ['Die Grafik zeigt, wie sich junge Leute informieren.', 'Die meisten, nämlich 60 Prozent, nutzen das Internet.', 'An zweiter Stelle steht das Fernsehen mit 30 Prozent.', 'Insgesamt sieht man, dass das Internet am wichtigsten ist.'],
    explanation: l('Topic → biggest value → next value → summary.', 'Konu → en büyük değer → sonraki değer → özet.', 'Thema → Werte → Fazit.'),
  },
  {
    id: 'dialog-gehoert',
    type: 'dialogue',
    topic: 'nachrichten-verstehen',
    concept: 'talk-news',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Hast du schon gehört? Die Bahn streikt morgen.' }],
    options: ['Echt? Woher weißt du das?', 'Ja, ich bin die Bahn.', 'Morgen ist Streik gestern.'],
    answer: 0,
    explanation: l('React and ask for the source: Woher weißt du das?', 'Tepki ver ve kaynağı sor: Woher weißt du das?', 'Woher weißt du das?'),
  },
  {
    id: 'dialog-medien',
    type: 'dialogue',
    topic: 'soziale-medien',
    concept: 'media-habits',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Interviewer', de: 'Wie informieren Sie sich über aktuelle Ereignisse?' }],
    options: ['Meistens lese ich Nachrichten in einer App, manchmal höre ich Radio.', 'Ich informiere Ereignis.', 'Aktuell ist es Montag.'],
    answer: 0,
    explanation: l('Describe your habits with frequency words.', 'Alışkanlıklarını sıklık kelimeleriyle anlat.', 'meistens, manchmal.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es in dem Text?',
    options: ['Wie sich junge Menschen informieren.', 'Wie man eine Zeitung druckt.', 'Wie teuer ein Handy ist.'],
    answer: 0,
    explanation: l('„Wie informieren sich junge Menschen?“', '„Wie informieren sich junge Menschen?“', 'Information.'),
  },
  {
    id: 'read-prozent',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie viele junge Leute lesen regelmäßig eine gedruckte Zeitung?',
    options: ['Nur jeder Zehnte.', 'Die Hälfte.', 'Die meisten.'],
    answer: 0,
    explanation: l('„Nur noch jeder Zehnte liest regelmäßig eine gedruckte Zeitung.“', '„Nur noch jeder Zehnte liest regelmäßig eine gedruckte Zeitung.“', 'jeder Zehnte.'),
  },
  {
    id: 'read-vertrauen',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die meisten jungen Leute vertrauen Nachrichten auf TikTok mehr als dem Fernsehen.',
    answer: false,
    explanation: l('„Trotzdem vertrauen die meisten den öffentlichen Sendern am meisten.“', '„Trotzdem vertrauen die meisten den öffentlichen Sendern am meisten.“', 'falsch.'),
  },
  {
    id: 'read-experten',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was empfehlen die Experten?',
    options: ['Medienkompetenz in der Schule.', 'Soziale Medien verbieten.', 'Mehr Zeitungen drucken.'],
    answer: 0,
    explanation: l('„Experten fordern deshalb mehr Medienkompetenz in der Schule.“', '„Experten fordern deshalb mehr Medienkompetenz in der Schule.“', 'Medienkompetenz.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-wetter',
    type: 'listening_choice',
    topic: 'nachrichten-verstehen',
    concept: 'news-passive',
    skill: 'listening',
    difficulty: 2,
    audio: 'Bei dem Unfall auf der A7 wurden zwei Personen leicht verletzt.',
    question: l('What happened?', 'Ne oldu?', 'Was ist passiert?'),
    options: ['Two people were slightly injured.', 'Two people were arrested.', 'Nobody was hurt.'],
    answer: 0,
    explanation: l('„wurden … leicht verletzt“', '„wurden … leicht verletzt“', 'verletzt.'),
  },
  {
    id: 'listen-umfrage',
    type: 'listening_choice',
    topic: 'statistik',
    concept: 'fractions',
    skill: 'listening',
    difficulty: 2,
    audio: 'Laut einer neuen Umfrage hören zwei Drittel der Deutschen regelmäßig Podcasts.',
    question: l('How many Germans listen to podcasts?', 'Kaç Alman podcast dinliyor?', 'Wie viele hören Podcasts?'),
    options: ['about two thirds', 'about a third', 'about a quarter'],
    answer: 0,
    explanation: l('„zwei Drittel“', '„zwei Drittel“', 'zwei Drittel.'),
  },
  {
    id: 'listen-falsch',
    type: 'listening_choice',
    topic: 'soziale-medien',
    concept: 'fake-news',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das Foto ist schon fünf Jahre alt. Es ist eine Falschmeldung – bitte nicht teilen!',
    question: l('What is the problem with the photo?', 'Fotoğrafla ilgili sorun ne?', 'Was ist das Problem?'),
    options: ['It is old – fake news.', 'It is too dark.', 'It is too big.'],
    answer: 0,
    explanation: l('„schon fünf Jahre alt … Falschmeldung“', '„schon fünf Jahre alt … Falschmeldung“', 'Falschmeldung.'),
  },
  {
    id: 'listen-trend',
    type: 'listening_choice',
    topic: 'statistik',
    concept: 'trend',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Zahl der Radiohörer ist in den letzten Jahren leicht gesunken.',
    question: l('What happened to the number of radio listeners?', 'Radyo dinleyicilerinin sayısına ne oldu?', 'Was ist passiert?'),
    options: ['It fell slightly.', 'It rose sharply.', 'It stayed the same.'],
    answer: 0,
    explanation: l('„leicht gesunken“ = fell slightly.', '„leicht gesunken“ = biraz düştü.', 'gesunken.'),
  },

  ...statDrills(),
]

export const UNIT_B1_20_MEDIEN_NACHRICHTEN: CourseUnit = {
  level: 'B1',
  number: 20,
  slug: 'medien-nachrichten',
  titleDe: 'Medien und Nachrichten',
  title: l('Media and news', 'Medya ve haberler', 'Medien und Nachrichten'),
  goal: l(
    'By the end of this unit you can understand short news items, describe surveys and charts (die Hälfte, die meisten, laut …), talk about your media habits and discuss social media and fake news.',
    'Bu ünitenin sonunda kısa haberleri anlayabilir, anketleri ve grafikleri anlatabilir (die Hälfte, die meisten, laut …), medya alışkanlıklarından bahsedebilir, sosyal medya ve yalan haberleri tartışabilirsin.',
    'Am Ende dieser Einheit verstehst du Nachrichten und beschreibst Statistiken.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'medien-wortschatz', label: l('Media vocabulary', 'Medya kelimeleri', 'Medienwortschatz') },
    { key: 'nachrichten-verstehen', label: l('Understanding news', 'Haberleri anlamak', 'Nachrichten verstehen') },
    { key: 'statistik', label: l('Surveys & charts', 'Anket & grafikler', 'Statistiken') },
    { key: 'soziale-medien', label: l('Social media', 'Sosyal medya', 'Soziale Medien') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Words from the world of news.', 'Haber dünyasından kelimeler.', 'Wörter aus den Nachrichten.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('The language of news', 'Haberlerin dili', 'Die Sprache der Nachrichten'),
          body: l(
            'News items are short and factual. Typical: passive in Präteritum (wurde eröffnet, wurden verletzt), laut + dative (laut der Polizei), and no personal opinions.',
            'Haberler kısa ve nesneldir. Tipik olanlar: Präteritum’da edilgen (wurde eröffnet, wurden verletzt), laut + Dativ (laut der Polizei) ve kişisel görüş yok.',
            'Passiv, laut + Dativ.'
          ),
          examples: [
            { de: 'Gestern **wurde** der Bahnhof **eröffnet**.', translation: l('Yesterday the station was opened.', 'Dün istasyon açıldı.', '') },
            { de: '**Laut der** Polizei gab es keine Verletzten.', translation: l('According to the police there were no injuries.', 'Polise göre yaralı yok.', '') },
          ],
        },
        {
          title: l('Describing statistics', 'İstatistik anlatmak', 'Statistiken beschreiben'),
          body: l(
            'Die Grafik zeigt … / Laut einer Umfrage … / Die meisten (plural verb) … / Die Hälfte, jeder Zehnte (singular verb) … / Die Zahl hat zugenommen / abgenommen.',
            'Die Grafik zeigt … / Laut einer Umfrage … / Die meisten (çoğul fiil) … / Die Hälfte, jeder Zehnte (tekil fiil) … / Die Zahl hat zugenommen / abgenommen.',
            'Grafik beschreiben.'
          ),
          table: {
            head: [l('German', 'Almanca', 'Deutsch'), l('Value', 'Değer', 'Wert')],
            rows: [
              ['die Mehrheit', '> 50 %'],
              ['die Hälfte', '50 %'],
              ['ein Drittel', 'ca. 33 %'],
              ['ein Viertel', '25 %'],
              ['jeder Zehnte', '10 %'],
            ],
          },
        },
        {
          title: l('Trends', 'Eğilimler', 'Entwicklungen'),
          body: l(
            'Up: steigen, zunehmen, wachsen. Down: sinken, abnehmen, zurückgehen. Same: gleich bleiben. Strength: leicht (slightly), stark (sharply).',
            'Yukarı: steigen, zunehmen, wachsen. Aşağı: sinken, abnehmen, zurückgehen. Aynı: gleich bleiben. Derece: leicht (biraz), stark (çok).',
            'steigen / sinken.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two friends talk about a viral video.', 'İki arkadaş viral bir video hakkında konuşuyor.', 'Ein virales Video.'),
      dialogue: [
        { speaker: 'Elif', de: 'Hast du das Video gesehen? Ein Hai im Rhein! Alle haben es **geteilt**.', translation: l('Have you seen the video? A shark in the Rhine! Everyone shared it.', 'Videoyu gördün mü? Ren Nehri’nde köpekbalığı! Herkes paylaştı.', '') },
        { speaker: 'Paul', de: 'Ja, aber das ist eine **Falschmeldung**. Die **Nachrichten** haben heute darüber **berichtet**.', translation: l('Yes, but it’s fake news. The news reported on it today.', 'Evet, ama yalan haber. Bugün haberlerde bundan bahsedildi.', '') },
        { speaker: 'Elif', de: 'Echt? Woher weißt du das?', translation: l('Really? How do you know?', 'Gerçekten mi? Nereden biliyorsun?', '') },
        { speaker: 'Paul', de: '**Laut** einem Experten **wurde** das Video am Computer **gemacht**.', translation: l('According to an expert the video was made on a computer.', 'Bir uzmana göre video bilgisayarda yapılmış.', '') },
        { speaker: 'Elif', de: 'Oh. Und ich habe es meiner ganzen Familie geschickt …', translation: l('Oh. And I sent it to my whole family …', 'Eyvah. Ben de bütün aileme gönderdim …', '') },
        { speaker: 'Paul', de: 'Kein Problem. Aber nächstes Mal prüf erst die **Quelle**!', translation: l('No problem. But next time check the source first!', 'Sorun değil. Ama bir dahaki sefere önce kaynağı kontrol et!', '') },
      ],
      examples: [
        { de: 'Die Zeitung **berichtet über** den Streik.', translation: l('The paper reports on the strike.', 'Gazete grev hakkında haber veriyor.', '') },
        { de: '**Laut einer Umfrage** …', translation: l('According to a survey …', 'Bir ankete göre …', '') },
        { de: '**Die Hälfte** der Befragten **liest** online.', translation: l('Half of those asked read online.', 'Katılımcıların yarısı çevrimiçi okuyor.', '') },
        { de: '**Die meisten** nutzen das Handy.', translation: l('Most use their phone.', 'Çoğu cep telefonunu kullanıyor.', '') },
        { de: 'Die Zahl hat **stark zugenommen**.', translation: l('The number has risen sharply.', 'Sayı çok arttı.', '') },
        { de: 'Gestern **wurde** ein neuer Präsident **gewählt**.', translation: l('Yesterday a new president was elected.', 'Dün yeni bir başkan seçildi.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Media words, numbers and trends.', 'Medya kelimeleri, sayılar ve eğilimler.', 'Medien, Zahlen, Trends.'),
      exercises: ['match-medien', 'sort-vor-nachteile', 'stat-haelfte', 'stat-viertel', 'mc-laut', 'tf-passiv-news', 'select-quelle', 'image-diagramm', 'stat-drittel'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Report, describe and discuss.', 'Haber ver, anlat ve tartış.', 'Berichten und beschreiben.'),
      exercises: [
        'fill-laut',
        'fill-zugenommen',
        'fill-berichtet',
        'build-umfrage',
        'build-wurde',
        'build-haelfte',
        'fix-laut',
        'fix-teilen',
        'fix-meisten',
        'tr-laut',
        'tr-quelle',
        'ordering-grafik',
        'dialog-gehoert',
        'dialog-medien',
        'stat-jeder-zehnte',
        'stat-mehrheit',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A short report about a study.', 'Bir araştırma hakkında kısa bir haber.', 'Bericht über eine Studie.'),
      passage: [
        '**Wie informieren sich junge Menschen?** Das wollte eine neue Studie wissen.',
        '**Laut der Studie** nutzen **die meisten** 14- bis 24-Jährigen vor allem soziale Medien. Nur noch **jeder Zehnte** liest regelmäßig eine gedruckte Zeitung.',
        'Trotzdem vertrauen die meisten den öffentlichen Sendern am meisten. Nachrichten auf TikTok halten nur **ein Viertel** der Befragten für zuverlässig.',
        'Ein Problem sind Falschmeldungen: Fast **die Hälfte** hat schon einmal eine geteilt, ohne es zu wissen. Experten fordern deshalb mehr Medienkompetenz in der Schule.',
      ],
      glossary: [
        { de: 'gedruckt', note: l('printed', 'basılı', 'auf Papier') },
        { de: 'vertrauen + Dativ', note: l('to trust', 'güvenmek', 'glauben, dass etwas stimmt') },
        { de: 'zuverlässig', note: l('reliable', 'güvenilir', 'man kann sich darauf verlassen') },
        { de: 'fordern', note: l('to demand', 'talep etmek', 'stark verlangen') },
      ],
      exercises: ['read-thema', 'read-prozent', 'read-vertrauen', 'read-experten'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Short radio news items.', 'Kısa radyo haberleri.', 'Kurznachrichten.'),
      exercises: ['listen-wetter', 'listen-umfrage', 'listen-falsch', 'listen-trend'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('How do you get your news – and what do you think of social media?', 'Haberleri nereden alıyorsun – ve sosyal medya hakkında ne düşünüyorsun?', 'Wie informierst du dich?'),
      points: [
        l('Your habits: „Meistens lese ich …“', 'Alışkanlıkların: „Meistens lese ich …“', 'Gewohnheiten'),
        l('An advantage of social media', 'Sosyal medyanın bir avantajı', 'Vorteil'),
        l('A disadvantage / fake news', 'Bir dezavantaj / yalan haber', 'Nachteil'),
        l('A tip: „Man sollte die Quelle prüfen.“', 'Bir ipucu: „Man sollte die Quelle prüfen.“', 'Tipp'),
      ],
      model: [
        'Meistens lese ich Nachrichten in einer App, abends sehe ich manchmal fern.',
        'Ein Vorteil von sozialen Medien ist, dass man Infos sehr schnell bekommt.',
        'Andererseits gibt es dort viele Falschmeldungen.',
        'Deshalb sollte man immer die Quelle prüfen, bevor man etwas teilt.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Describe this chart (at least 5 sentences): „How young people get their news: Internet 60 %, TV 25 %, radio 10 %, newspaper 5 %.“ Add your own opinion.',
        'Bu grafiği anlat (en az 5 cümle): „Gençler haberleri nereden alıyor: İnternet %60, TV %25, radyo %10, gazete %5.“ Kendi fikrini ekle.',
        'Beschreib die Grafik (mindestens 5 Sätze) und gib deine Meinung.'
      ),
      minSentences: 5,
      checks: [
        { label: l('Introduce the chart (Die Grafik zeigt …)', 'Grafiği tanıt (Die Grafik zeigt …)', 'Die Grafik zeigt'), pattern: '(Grafik|Statistik|Umfrage)' },
        { label: l('A number with Prozent', 'Prozent ile bir sayı', 'Prozent'), pattern: '\\d+ ?(Prozent|%)' },
        { label: l('A comparison word (die meisten / die Hälfte / am …)', 'Karşılaştırma kelimesi (die meisten / die Hälfte / am …)', 'Vergleich'), pattern: '([Dd]ie meisten|Hälfte|Viertel|Mehrheit|am \\p{Ll}+sten)' },
      ],
      model: [
        'Die Grafik zeigt, wie sich junge Leute informieren.',
        'Die meisten, nämlich 60 Prozent, nutzen das Internet.',
        'An zweiter Stelle steht das Fernsehen mit 25 Prozent.',
        'Nur 5 Prozent lesen noch eine Zeitung.',
        'Ich finde das schade, weil Zeitungen oft genauer berichten.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('How much is it? – 60 seconds.', 'Ne kadar? – 60 saniye.', 'Wie viel ist das? – 60 Sekunden.'),
      seconds: 60,
      pool: [...STATS.map(([id]) => `stat-${id}`), 'mc-laut'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('News: Nachrichten, Schlagzeile, berichten über, Quelle', 'Haber: Nachrichten, Schlagzeile, berichten über, Quelle', 'Nachrichten'),
      l('News passive: wurde eröffnet, wurden verletzt', 'Haber edilgeni: wurde eröffnet, wurden verletzt', 'Passiv'),
      l('Statistics: laut einer Umfrage, die meisten, die Hälfte, jeder Zehnte', 'İstatistik: laut einer Umfrage, die meisten, die Hälfte, jeder Zehnte', 'Statistiken'),
      l('Trends: zunehmen / abnehmen, steigen / sinken', 'Eğilimler: zunehmen / abnehmen, steigen / sinken', 'Trends'),
    ],
    mistakes: [
      { wrong: 'Laut den Bericht …', right: 'Laut dem Bericht …', note: l('laut + dative.', 'laut + Dativ.', 'Dativ.') },
      { wrong: 'Die meisten Leute liest …', right: 'Die meisten Leute lesen …', note: l('Plural verb.', 'Çoğul fiil.', 'Plural.') },
      { wrong: 'Die Hälfte lesen …', right: 'Die Hälfte liest …', note: l('die Hälfte = singular.', 'die Hälfte = tekil.', 'Singular.') },
      { wrong: 'Sie hat das Video geteilen.', right: 'Sie hat das Video geteilt.', note: l('Regular participle.', 'Düzenli ortaç.', 'geteilt.') },
    ],
  },
}
