import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'Meiner Meinung nach …', emoji: '💬', translation: l('In my opinion …', 'Bence …', 'Ich denke …'), example: 'Meiner Meinung nach ist das eine gute Idee.' },
  { word: 'Ich bin der Ansicht, dass …', emoji: '🧐', translation: l('I am of the view that …', '… görüşündeyim', 'Ich denke, dass …'), example: 'Ich bin der Ansicht, dass Schule später beginnen sollte.' },
  { word: 'Da stimme ich zu.', emoji: '👍', translation: l('I agree with that.', 'Buna katılıyorum.', 'Zustimmung'), example: 'Da stimme ich dir völlig zu.' },
  { word: 'Da bin ich anderer Meinung.', emoji: '👎', translation: l('I disagree.', 'Bu konuda farklı düşünüyorum.', 'Widerspruch'), example: 'Da bin ich anderer Meinung als du.' },
  { word: 'Das stimmt, aber …', emoji: '⚖️', translation: l('That’s true, but …', 'Doğru, ama …', 'teilweise Zustimmung'), example: 'Das stimmt, aber es ist auch teuer.' },
  { word: 'einerseits … andererseits', emoji: '🔀', translation: l('on the one hand … on the other hand', 'bir yandan … öte yandan', 'zwei Seiten'), example: 'Einerseits ist es praktisch, andererseits ist es teuer.' },
  { word: 'der Vorteil', emoji: '➕', translation: l('advantage', 'avantaj', 'etwas Positives'), example: 'Ein Vorteil ist, dass es schnell geht.' },
  { word: 'der Nachteil', emoji: '➖', translation: l('disadvantage', 'dezavantaj', 'etwas Negatives'), example: 'Ein Nachteil ist der hohe Preis.' },
  { word: 'überzeugen', emoji: '🎯', translation: l('to convince', 'ikna etmek', 'jemanden dazu bringen, etwas zu glauben'), example: 'Dein Argument überzeugt mich.' },
  { word: 'das Argument', emoji: '🗣️', translation: l('argument', 'argüman', 'Grund für eine Meinung'), example: 'Das ist ein gutes Argument.' },
  { word: 'Ich bin mir nicht sicher.', emoji: '🤔', translation: l('I’m not sure.', 'Emin değilim.', 'Unsicherheit'), example: 'Ich bin mir nicht sicher, ob das stimmt.' },
  { word: 'Zum Schluss …', emoji: '🏁', translation: l('Finally / To conclude …', 'Son olarak …', 'am Ende'), example: 'Zum Schluss möchte ich sagen, dass …' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Meinung', gender: 'f', plural: 'die Meinungen', translation: l('opinion', 'fikir', 'Meinung') },
  { word: 'Ansicht', gender: 'f', plural: 'die Ansichten', translation: l('view', 'görüş', 'Ansicht') },
  { word: 'Vorteil', gender: 'm', plural: 'die Vorteile', translation: l('advantage', 'avantaj', 'Vorteil') },
  { word: 'Nachteil', gender: 'm', plural: 'die Nachteile', translation: l('disadvantage', 'dezavantaj', 'Nachteil') },
  { word: 'Argument', gender: 'n', plural: 'die Argumente', translation: l('argument', 'argüman', 'Argument') },
  { word: 'Diskussion', gender: 'f', plural: 'die Diskussionen', translation: l('discussion', 'tartışma', 'Diskussion') },
  { word: 'Grund', gender: 'm', plural: 'die Gründe', translation: l('reason', 'sebep', 'Grund') },
  { word: 'Beispiel', gender: 'n', plural: 'die Beispiele', translation: l('example', 'örnek', 'Beispiel') },
]

const FUNCTIONS = ['Zustimmung 👍', 'Widerspruch 👎', 'Unsicherheit 🤔'] as const

/** [id, phrase, index of right function] */
const PHRASES: [string, string, 0 | 1 | 2][] = [
  ['recht', 'Da hast du völlig recht.', 0],
  ['sehe', 'Das sehe ich ganz anders.', 1],
  ['weiss', 'Ich weiß nicht so genau.', 2],
  ['genau', 'Genau, das finde ich auch.', 0],
  ['ueberzeugt', 'Das überzeugt mich nicht.', 1],
  ['kommt', 'Das kommt darauf an.', 2],
]

function phraseDrills(): Exercise[] {
  return PHRASES.map(([id, phrase, right], i) => {
    const options = [...FUNCTIONS]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `funktion-${id}`,
      type: 'multiple_choice' as const,
      topic: 'zustimmen-widersprechen',
      concept: 'phrase-function',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: `„${phrase}“ – Was drückt das aus?`,
      options: ordered,
      answer: ordered.indexOf(FUNCTIONS[right]),
      explanation: l(`„${phrase}“ → ${FUNCTIONS[right]}.`, `„${phrase}“ → ${FUNCTIONS[right]}.`, `→ ${FUNCTIONS[right]}.`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-meinung',
    type: 'matching',
    topic: 'meinung-aeussern',
    concept: 'opinion-phrases',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match German and meaning.', 'Almancayı anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'Meiner Meinung nach …', right: 'In my opinion …' },
      { left: 'Da stimme ich zu.', right: 'I agree.' },
      { left: 'Da bin ich anderer Meinung.', right: 'I disagree.' },
      { left: 'Ich bin mir nicht sicher.', right: 'I’m not sure.' },
      { left: 'Das stimmt, aber …', right: 'That’s true, but …' },
    ],
    explanation: l('Key phrases for discussions.', 'Tartışma için temel kalıplar.', 'Redemittel für Diskussionen.'),
  },
  {
    id: 'sort-vor-nachteil',
    type: 'categorize',
    topic: 'einerseits-andererseits',
    concept: 'pros-cons',
    skill: 'reading',
    difficulty: 2,
    instructions: l('Home office: advantage or disadvantage?', 'Evden çalışma: avantaj mı dezavantaj mı?', 'Homeoffice: Vorteil oder Nachteil?'),
    categories: ['Vorteil ➕', 'Nachteil ➖'],
    items: [
      { text: 'Man spart Zeit, weil man nicht pendeln muss.', category: 0 },
      { text: 'Man sieht die Kollegen selten.', category: 1 },
      { text: 'Man kann flexibel arbeiten.', category: 0 },
      { text: 'Arbeit und Freizeit sind nicht getrennt.', category: 1 },
      { text: 'Man spart Fahrtkosten.', category: 0 },
      { text: 'Man bewegt sich weniger.', category: 1 },
    ],
    explanation: l('Collecting pros and cons is the first step to an opinion.', 'Artıları ve eksileri toplamak bir fikre giden ilk adımdır.', 'Vor- und Nachteile.'),
    practice: ['funktion-recht'],
  },
  {
    id: 'mc-nach',
    type: 'multiple_choice',
    topic: 'meinung-aeussern',
    concept: 'meiner-meinung-nach',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Meiner Meinung nach ___ das Rauchen in Parks verboten werden.',
    options: ['sollte', 'ich finde', 'dass'],
    answer: 0,
    explanation: l('Meiner Meinung nach counts as position 1 → verb comes next.', 'Meiner Meinung nach 1. konum sayılır → sonra fiil gelir.', 'Position 2: Verb.'),
    examples: ['Meiner Meinung nach **sollte** das Rauchen in Parks verboten werden.'],
    practice: ['fill-meinung'],
  },
  {
    id: 'tf-einerseits',
    type: 'true_false',
    topic: 'einerseits-andererseits',
    concept: 'einerseits-word-order',
    skill: 'grammar',
    difficulty: 2,
    statement: 'Nach „einerseits“ und „andererseits“ steht das Verb direkt danach: „Einerseits ist es …, andererseits kostet es …“',
    answer: true,
    explanation: l('einerseits / andererseits take position 1 → verb in position 2.', 'einerseits / andererseits 1. konumda → fiil 2. konumda.', 'Verb auf Position 2.'),
  },
  {
    id: 'select-widerspruch',
    type: 'multiple_select',
    topic: 'zustimmen-widersprechen',
    concept: 'disagree',
    skill: 'speaking',
    difficulty: 2,
    promptL10n: l('Which sentences express (polite) disagreement? Select all.', 'Hangi cümleler (kibar) bir itirazı ifade ediyor? Hepsini seç.', 'Welche Sätze widersprechen?'),
    options: ['Da bin ich anderer Meinung.', 'Das sehe ich anders.', 'Da hast du recht.', 'Ich glaube nicht, dass das stimmt.', 'Genau!'],
    answers: [0, 1, 3],
    explanation: l('Disagreeing: Da bin ich anderer Meinung. / Das sehe ich anders. / Ich glaube nicht, dass …', 'İtiraz: Da bin ich anderer Meinung. / Das sehe ich anders. / Ich glaube nicht, dass …', 'Widerspruch.'),
  },
  {
    id: 'image-meinung',
    type: 'image_choice',
    topic: 'zustimmen-widersprechen',
    concept: 'phrase-function',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Das überzeugt mich nicht. Ich bin dagegen.',
    options: [
      { emoji: '👎', label: 'dagegen' },
      { emoji: '👍', label: 'dafür' },
      { emoji: '🤔', label: 'unsicher' },
      { emoji: '😴', label: 'egal' },
    ],
    answer: 0,
    explanation: l('dagegen = against.', 'dagegen = karşı.', 'dagegen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-meinung',
    type: 'fill_blank',
    topic: 'meinung-aeussern',
    concept: 'meiner-meinung-nach',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Meiner Meinung ___ ist Homeoffice sehr praktisch.',
    accepted: ['nach'],
    base: 'Meiner Meinung …',
    explanation: l('Fixed phrase: Meiner Meinung nach.', 'Kalıp: Meiner Meinung nach.', 'nach.'),
    examples: ['Meiner Meinung **nach** ist Homeoffice sehr praktisch.'],
  },
  {
    id: 'fill-andererseits',
    type: 'fill_blank',
    topic: 'einerseits-andererseits',
    concept: 'einerseits',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Einerseits ist die Stadt spannend, ___ ist sie sehr laut.',
    accepted: ['andererseits'],
    base: 'einerseits …',
    explanation: l('einerseits … andererseits.', 'einerseits … andererseits.', 'andererseits.'),
    examples: ['Einerseits ist die Stadt spannend, **andererseits** ist sie sehr laut.'],
  },
  {
    id: 'fill-zu',
    type: 'fill_blank',
    topic: 'zustimmen-widersprechen',
    concept: 'agree',
    skill: 'vocabulary',
    difficulty: 1,
    sentence: 'Da stimme ich dir völlig ___.',
    accepted: ['zu'],
    base: 'zustimmen',
    explanation: l('zustimmen is separable: Ich stimme dir zu.', 'zustimmen ayrılabilir: Ich stimme dir zu.', 'zu.'),
    examples: ['Da stimme ich dir völlig **zu**.'],
  },
  {
    id: 'build-ansicht',
    type: 'sentence_builder',
    topic: 'meinung-aeussern',
    concept: 'ansicht-dass',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ist', 'dass', 'Ich bin der Ansicht,', 'zu teuer', 'das Ticket'],
    answers: [['Ich bin der Ansicht,', 'dass', 'das Ticket', 'zu teuer', 'ist']],
    translation: l('I am of the view that the ticket is too expensive.', 'Biletin çok pahalı olduğu görüşündeyim.', 'Ich bin der Ansicht, dass das Ticket zu teuer ist.'),
    explanation: l('dass → verb at the end.', 'dass → fiil sonda.', '… zu teuer ist.'),
    examples: ['Ich bin der Ansicht, dass das Ticket zu teuer **ist**.'],
  },
  {
    id: 'build-einerseits',
    type: 'sentence_builder',
    topic: 'einerseits-andererseits',
    concept: 'einerseits-word-order',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ist', 'praktisch', 'Einerseits', 'das Auto'],
    answers: [['Einerseits', 'ist', 'das Auto', 'praktisch']],
    translation: l('On the one hand the car is practical.', 'Bir yandan araba pratik.', 'Einerseits ist das Auto praktisch.'),
    explanation: l('Einerseits + verb + subject.', 'Einerseits + fiil + özne.', 'Einerseits ist …'),
    examples: ['Einerseits **ist** das Auto praktisch.'],
  },
  {
    id: 'build-weil',
    type: 'sentence_builder',
    topic: 'begruenden',
    concept: 'reason',
    skill: 'grammar',
    difficulty: 2,
    chips: ['weil', 'gesund ist', 'Ich bin dafür,', 'es'],
    answers: [['Ich bin dafür,', 'weil', 'es', 'gesund ist']],
    translation: l('I am in favour because it is healthy.', 'Sağlıklı olduğu için destekliyorum.', 'Ich bin dafür, weil es gesund ist.'),
    explanation: l('Opinion + reason with weil (verb at the end).', 'Fikir + weil ile sebep (fiil sonda).', 'weil … ist.'),
    examples: ['Ich bin dafür, **weil** es gesund **ist**.'],
  },
  {
    id: 'fix-meinung',
    type: 'error_correction',
    topic: 'meinung-aeussern',
    concept: 'meiner-meinung-nach',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Nach meiner Meinung das ist richtig.',
    accepted: ['Meiner Meinung nach ist das richtig.', 'Nach meiner Meinung ist das richtig.'],
    explanation: l('Verb in position 2: Meiner Meinung nach ist das richtig.', 'Fiil 2. konumda: Meiner Meinung nach ist das richtig.', 'ist das richtig.'),
    examples: ['Meiner Meinung nach **ist** das richtig.'],
  },
  {
    id: 'fix-bin',
    type: 'error_correction',
    topic: 'zustimmen-widersprechen',
    concept: 'agree',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich bin einverstanden mit dir. Ich habe recht mit dir.',
    accepted: ['Ich bin einverstanden mit dir. Du hast recht.', 'Ich bin mit dir einverstanden. Du hast recht.'],
    explanation: l('You agree → the other person is right: Du hast recht.', 'Katılıyorsun → karşındaki haklı: Du hast recht.', 'Du hast recht.'),
    examples: ['**Du** hast recht.'],
  },
  {
    id: 'fix-andererseits',
    type: 'error_correction',
    topic: 'einerseits-andererseits',
    concept: 'einerseits-word-order',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Einerseits das Handy ist nützlich, andererseits es macht süchtig.',
    accepted: ['Einerseits ist das Handy nützlich, andererseits macht es süchtig.'],
    explanation: l('Verb right after einerseits / andererseits.', 'einerseits / andererseits’ten hemen sonra fiil.', 'ist … / macht …'),
    examples: ['Einerseits **ist** das Handy nützlich, andererseits **macht** es süchtig.'],
  },
  {
    id: 'tr-meinung',
    type: 'translation',
    topic: 'meinung-aeussern',
    concept: 'meiner-meinung-nach',
    skill: 'writing',
    difficulty: 2,
    source: l('In my opinion that is a good idea.', 'Bence bu iyi bir fikir.', 'In my opinion that is a good idea.'),
    accepted: ['Meiner Meinung nach ist das eine gute Idee.', 'Meiner Meinung nach ist das eine gute Idee!'],
    explanation: l('Meiner Meinung nach + verb.', 'Meiner Meinung nach + fiil.', 'ist das …'),
    examples: ['Meiner Meinung nach **ist** das eine gute Idee.'],
  },
  {
    id: 'tr-anders',
    type: 'translation',
    topic: 'zustimmen-widersprechen',
    concept: 'disagree',
    skill: 'writing',
    difficulty: 2,
    source: l('I see that differently.', 'Ben bunu farklı görüyorum.', 'I see that differently.'),
    accepted: ['Ich sehe das anders.', 'Das sehe ich anders.', 'Ich sehe das ganz anders.', 'Das sehe ich ganz anders.'],
    explanation: l('Das sehe ich anders.', 'Das sehe ich anders.', 'Das sehe ich anders.'),
    examples: ['Das **sehe** ich **anders**.'],
  },
  {
    id: 'ordering-argumentation',
    type: 'ordering',
    topic: 'begruenden',
    concept: 'structure',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Put the statement in order: opinion → reason → example → conclusion.', 'Görüşü sırala: fikir → sebep → örnek → sonuç.', 'Meinung → Grund → Beispiel → Schluss.'),
    items: ['Zum Beispiel kann man mit Freunden in der ganzen Welt sprechen.', 'Ich finde soziale Medien grundsätzlich positiv.', 'Deshalb bin ich dafür – aber mit Maß.', 'Sie helfen nämlich, Kontakte zu pflegen.'],
    answer: ['Ich finde soziale Medien grundsätzlich positiv.', 'Sie helfen nämlich, Kontakte zu pflegen.', 'Zum Beispiel kann man mit Freunden in der ganzen Welt sprechen.', 'Deshalb bin ich dafür – aber mit Maß.'],
    explanation: l('Opinion → reason (nämlich) → example (zum Beispiel) → conclusion (deshalb).', 'Fikir → sebep (nämlich) → örnek (zum Beispiel) → sonuç (deshalb).', 'Aufbau.'),
  },
  {
    id: 'dialog-teilweise',
    type: 'dialogue',
    topic: 'zustimmen-widersprechen',
    concept: 'partial',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Lena', de: 'Ein Auto ist auf dem Land einfach notwendig.' }],
    options: ['Das stimmt, aber man könnte auch öfter den Bus nehmen.', 'Das stimmt, aber Auto Bus.', 'Ich bin ein Auto.'],
    answer: 0,
    explanation: l('Partial agreement: Das stimmt, aber …', 'Kısmi katılım: Das stimmt, aber …', 'Das stimmt, aber …'),
  },
  {
    id: 'dialog-nachfragen',
    type: 'dialogue',
    topic: 'begruenden',
    concept: 'ask-reason',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Tom', de: 'Ich finde, Hausaufgaben sollten abgeschafft werden.' }],
    options: ['Interessant. Warum denkst du das?', 'Hausaufgaben sind Hausaufgaben.', 'Ja, morgen.'],
    answer: 0,
    explanation: l('Ask for a reason: Warum denkst du das? / Wie kommst du darauf?', 'Sebep sor: Warum denkst du das? / Wie kommst du darauf?', 'Warum?'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es in der Diskussion?',
    options: ['Um eine Vier-Tage-Woche.', 'Um Urlaub am Meer.', 'Um ein neues Handy.'],
    answer: 0,
    explanation: l('„Sollten wir alle nur noch vier Tage pro Woche arbeiten?“', '„Sollten wir alle nur noch vier Tage pro Woche arbeiten?“', 'Vier-Tage-Woche.'),
  },
  {
    id: 'read-jonas',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist Jonas’ Meinung?',
    options: ['Er ist dafür, weil man erholter ist.', 'Er ist dagegen, weil es zu teuer ist.', 'Er hat keine Meinung.'],
    answer: 0,
    explanation: l('„Ich bin klar dafür. Wer sich erholt, arbeitet besser.“', '„Ich bin klar dafür. Wer sich erholt, arbeitet besser.“', 'dafür.'),
  },
  {
    id: 'read-sabine',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    statement: 'Sabine sieht Vorteile und Nachteile.',
    answer: true,
    explanation: l('„Einerseits … andererseits …“', '„Einerseits … andererseits …“', 'ja.'),
  },
  {
    id: 'read-problem',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-forum',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welches Problem nennt Sabine?',
    options: ['In Krankenhäusern ist es schwer umzusetzen.', 'Die Leute haben zu viel Freizeit.', 'Die Woche hat zu viele Tage.'],
    answer: 0,
    explanation: l('„… in Krankenhäusern oder Geschäften ist das schwierig.“', '„… in Krankenhäusern oder Geschäften ist das schwierig.“', 'Krankenhäuser.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-dafuer',
    type: 'listening_choice',
    topic: 'meinung-aeussern',
    concept: 'opinion-phrases',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich bin der Ansicht, dass Schulessen kostenlos sein sollte.',
    question: l('What does the speaker think?', 'Konuşmacı ne düşünüyor?', 'Was denkt die Person?'),
    options: ['School meals should be free.', 'School meals are too cheap.', 'There should be no school meals.'],
    answer: 0,
    explanation: l('„… kostenlos sein sollte.“', '„… kostenlos sein sollte.“', 'kostenlos.'),
  },
  {
    id: 'listen-widerspruch',
    type: 'listening_choice',
    topic: 'zustimmen-widersprechen',
    concept: 'disagree',
    skill: 'listening',
    difficulty: 2,
    audio: 'Da muss ich dir widersprechen. Elektroautos sind nicht automatisch umweltfreundlich.',
    question: l('Does the speaker agree?', 'Konuşmacı katılıyor mu?', 'Stimmt die Person zu?'),
    options: ['No, they disagree.', 'Yes, completely.', 'They are unsure.'],
    answer: 0,
    explanation: l('„widersprechen“ = to contradict.', '„widersprechen“ = itiraz etmek.', 'Widerspruch.'),
  },
  {
    id: 'listen-einerseits',
    type: 'listening_choice',
    topic: 'einerseits-andererseits',
    concept: 'pros-cons',
    skill: 'listening',
    difficulty: 2,
    audio: 'Einerseits ist die Wohnung schön groß, andererseits ist sie ziemlich weit weg von der Arbeit.',
    question: l('What is the disadvantage of the flat?', 'Dairenin dezavantajı ne?', 'Was ist der Nachteil?'),
    options: ['It is far from work.', 'It is too small.', 'It is too expensive.'],
    answer: 0,
    explanation: l('„… weit weg von der Arbeit.“', '„… weit weg von der Arbeit.“', 'weit weg.'),
  },
  {
    id: 'listen-grund',
    type: 'listening_choice',
    topic: 'begruenden',
    concept: 'reason',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich bin gegen das Verbot, weil viele Menschen auf das Auto angewiesen sind.',
    question: l('Why is the speaker against the ban?', 'Konuşmacı yasağa neden karşı?', 'Warum ist die Person dagegen?'),
    options: ['Many people depend on their car.', 'Cars are cheap.', 'They like driving fast.'],
    answer: 0,
    explanation: l('„… auf das Auto angewiesen sind.“ (to depend on)', '„… auf das Auto angewiesen sind.“ (bağımlı olmak)', 'angewiesen.'),
  },

  ...phraseDrills(),
]

export const UNIT_B1_19_MEINUNG: CourseUnit = {
  level: 'B1',
  number: 19,
  slug: 'meinung',
  titleDe: 'Meinungen äußern und diskutieren',
  title: l('Giving opinions and discussing', 'Fikir belirtmek ve tartışmak', 'Meinungen äußern'),
  goal: l(
    'By the end of this unit you can give and justify your opinion, agree and disagree politely, weigh pros and cons with einerseits … andererseits and follow a short discussion.',
    'Bu ünitenin sonunda fikrini söyleyip gerekçelendirebilir, kibarca katılabilir ya da itiraz edebilir, einerseits … andererseits ile artıları ve eksileri tartabilir ve kısa bir tartışmayı takip edebilirsin.',
    'Am Ende dieser Einheit äußerst und begründest du deine Meinung.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'meinung-aeussern', label: l('Giving opinions', 'Fikir belirtmek', 'Meinung äußern') },
    { key: 'zustimmen-widersprechen', label: l('Agreeing & disagreeing', 'Katılmak & itiraz etmek', 'Zustimmen & widersprechen') },
    { key: 'einerseits-andererseits', label: l('Pros and cons', 'Artılar ve eksiler', 'Vor- und Nachteile') },
    { key: 'begruenden', label: l('Giving reasons', 'Gerekçelendirmek', 'Begründen') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Phrases for every discussion.', 'Her tartışma için kalıplar.', 'Redemittel für Diskussionen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Giving your opinion', 'Fikrini söylemek', 'Meinung äußern'),
          body: l(
            'Two kinds of phrases: (1) with dass → verb at the end: Ich finde / glaube / bin der Ansicht, dass … (2) as position 1 → verb comes next: Meiner Meinung nach ist … / Ich finde … gut.',
            'İki tür kalıp: (1) dass ile → fiil sonda: Ich finde / glaube / bin der Ansicht, dass … (2) 1. konum olarak → sonra fiil: Meiner Meinung nach ist … / Ich finde … gut.',
            'dass → Verb am Ende; Meiner Meinung nach → Verb auf Position 2.'
          ),
          examples: [
            { de: 'Ich bin der Ansicht, dass das zu teuer **ist**.', translation: l('I think that is too expensive.', 'Bunun çok pahalı olduğunu düşünüyorum.', '') },
            { de: 'Meiner Meinung nach **ist** das zu teuer.', translation: l('In my opinion that is too expensive.', 'Bence bu çok pahalı.', '') },
          ],
        },
        {
          title: l('Agreeing and disagreeing', 'Katılmak ve itiraz etmek', 'Zustimmen und widersprechen'),
          body: l(
            'Germans often disagree quite directly – but politely with a softener: Das stimmt, aber … / Da hast du recht, trotzdem … / Ich sehe das etwas anders.',
            'Almanlar oldukça doğrudan itiraz eder – ama yumuşatıcıyla kibarca: Das stimmt, aber … / Da hast du recht, trotzdem … / Ich sehe das etwas anders.',
            'Höflich widersprechen.'
          ),
          table: {
            head: [l('Agree', 'Katılmak', 'Zustimmen'), l('Partly', 'Kısmen', 'Teilweise'), l('Disagree', 'İtiraz', 'Widersprechen')],
            rows: [
              ['Da stimme ich zu.', 'Das stimmt, aber …', 'Das sehe ich anders.'],
              ['Du hast recht.', 'Im Prinzip ja, aber …', 'Da bin ich anderer Meinung.'],
              ['Genau!', 'Kommt darauf an.', 'Das überzeugt mich nicht.'],
            ],
          },
        },
        {
          title: l('einerseits … andererseits', 'einerseits … andererseits', 'einerseits … andererseits'),
          body: l(
            'Both words take position 1, so the verb follows immediately: Einerseits ist es praktisch, andererseits kostet es viel. Other structure words: zum Beispiel, außerdem, deshalb, zum Schluss.',
            'İki kelime de 1. konumdadır, bu yüzden fiil hemen gelir: Einerseits ist es praktisch, andererseits kostet es viel. Diğer yapı kelimeleri: zum Beispiel, außerdem, deshalb, zum Schluss.',
            'Verb direkt nach einerseits / andererseits.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Two flatmates discuss whether they should get rid of their TV.', 'İki ev arkadaşı televizyondan kurtulup kurtulmamayı tartışıyor.', 'Brauchen wir einen Fernseher?'),
      dialogue: [
        { speaker: 'Mia', de: '**Ich finde**, wir sollten den Fernseher verkaufen. Wir schauen sowieso alles am Laptop.', translation: l('I think we should sell the TV. We watch everything on the laptop anyway.', 'Bence televizyonu satmalıyız. Zaten her şeyi laptopta izliyoruz.', '') },
        { speaker: 'Can', de: '**Das stimmt, aber** Fußball schaue ich lieber auf dem großen Bildschirm.', translation: l('That’s true, but I prefer watching football on the big screen.', 'Doğru, ama futbolu büyük ekranda izlemeyi tercih ederim.', '') },
        { speaker: 'Mia', de: '**Einerseits** verstehe ich das. **Andererseits** steht er die meiste Zeit nur herum.', translation: l('On the one hand I understand. On the other hand it just stands around most of the time.', 'Bir yandan anlıyorum. Öte yandan çoğu zaman öylece duruyor.', '') },
        { speaker: 'Can', de: '**Da hast du recht.** Und wir hätten mehr Platz im Wohnzimmer.', translation: l('You’re right. And we’d have more space in the living room.', 'Haklısın. Hem salonda daha fazla yerimiz olur.', '') },
        { speaker: 'Mia', de: 'Genau! **Meiner Meinung nach** ist das ein gutes **Argument**.', translation: l('Exactly! In my opinion that’s a good argument.', 'Aynen! Bence bu iyi bir argüman.', '') },
        { speaker: 'Can', de: 'Okay, **du hast mich überzeugt**. Aber zur WM kaufen wir einen Beamer!', translation: l('Okay, you’ve convinced me. But for the World Cup we’ll buy a projector!', 'Tamam, beni ikna ettin. Ama Dünya Kupası için projeksiyon alıyoruz!', '') },
      ],
      examples: [
        { de: '**Meiner Meinung nach** ist das richtig.', translation: l('In my opinion that’s right.', 'Bence bu doğru.', '') },
        { de: 'Ich bin der Ansicht, **dass** wir mehr lesen sollten.', translation: l('I think we should read more.', 'Daha çok okumamız gerektiği görüşündeyim.', '') },
        { de: '**Da stimme ich** dir **zu**.', translation: l('I agree with you.', 'Sana katılıyorum.', '') },
        { de: '**Das sehe ich anders.**', translation: l('I see that differently.', 'Ben farklı görüyorum.', '') },
        { de: '**Einerseits** ist es billig, **andererseits** ist es langsam.', translation: l('On the one hand it’s cheap, on the other it’s slow.', 'Bir yandan ucuz, öte yandan yavaş.', '') },
        { de: 'Ein großer **Vorteil** ist die Zeit.', translation: l('A big advantage is the time.', 'Büyük bir avantaj zaman.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Agree, disagree or unsure?', 'Katılma, itiraz mı yoksa emin değil mi?', 'Zustimmung oder Widerspruch?'),
      exercises: ['match-meinung', 'sort-vor-nachteil', 'funktion-recht', 'funktion-sehe', 'funktion-weiss', 'mc-nach', 'tf-einerseits', 'select-widerspruch', 'image-meinung'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Say what you think – and why.', 'Ne düşündüğünü söyle – ve nedenini.', 'Sag deine Meinung.'),
      exercises: [
        'fill-meinung',
        'fill-andererseits',
        'fill-zu',
        'build-ansicht',
        'build-einerseits',
        'build-weil',
        'fix-meinung',
        'fix-bin',
        'fix-andererseits',
        'tr-meinung',
        'tr-anders',
        'ordering-argumentation',
        'dialog-teilweise',
        'dialog-nachfragen',
        'funktion-genau',
        'funktion-ueberzeugt',
        'funktion-kommt',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('An online discussion.', 'Bir çevrimiçi tartışma.', 'Eine Forumsdiskussion.'),
      passage: [
        '**Frage der Woche:** Sollten wir alle nur noch vier Tage pro Woche arbeiten?',
        '**Jonas, 29:** Ich bin klar dafür. Wer sich erholt, arbeitet besser. Außerdem hätten Familien mehr Zeit füreinander.',
        '**Sabine, 47:** **Einerseits** klingt das toll, **andererseits** frage ich mich, wer das bezahlen soll. In Büros mag das funktionieren, aber in Krankenhäusern oder Geschäften ist das schwierig.',
        '**Ali, 35:** **Da stimme ich** Sabine teilweise **zu**. Trotzdem sollte man es ausprobieren – **meiner Meinung nach** ist das die Zukunft.',
      ],
      glossary: [
        { de: 'sich erholen', note: l('to recover, to rest', 'dinlenmek', 'Pause machen') },
        { de: 'füreinander', note: l('for each other', 'birbirleri için', 'einer für den anderen') },
        { de: 'ausprobieren', note: l('to try out', 'denemek', 'testen') },
        { de: 'die Zukunft', note: l('the future', 'gelecek', 'was kommt') },
      ],
      exercises: ['read-thema', 'read-jonas', 'read-sabine', 'read-problem'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Opinions and reasons.', 'Fikirler ve sebepler.', 'Meinungen und Gründe.'),
      exercises: ['listen-dafuer', 'listen-widerspruch', 'listen-einerseits', 'listen-grund'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Topic: „Should mobile phones be banned in schools?“ Give your opinion.', 'Konu: „Okullarda cep telefonu yasaklanmalı mı?“ Fikrini söyle.', 'Handyverbot an Schulen?'),
      points: [
        l('Your opinion: „Meiner Meinung nach …“', 'Fikrin: „Meiner Meinung nach …“', 'Meinung'),
        l('One advantage and one disadvantage: „Einerseits … andererseits …“', 'Bir avantaj ve bir dezavantaj: „Einerseits … andererseits …“', 'einerseits … andererseits'),
        l('A reason: „…, weil …“', 'Bir sebep: „…, weil …“', 'weil'),
        l('A conclusion: „Deshalb bin ich dafür/dagegen.“', 'Sonuç: „Deshalb bin ich dafür/dagegen.“', 'Schluss'),
      ],
      model: [
        'Meiner Meinung nach sollte man Handys nicht ganz verbieten.',
        'Einerseits stören sie im Unterricht, andererseits kann man damit gut recherchieren.',
        'Ich bin für klare Regeln, weil Schüler lernen müssen, damit umzugehen.',
        'Deshalb bin ich gegen ein komplettes Verbot.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write your opinion in a forum (at least 5 sentences): „Is it better to live in the city or in the countryside?“',
        'Bir foruma fikrini yaz (en az 5 cümle): „Şehirde mi yoksa kırsalda mı yaşamak daha iyi?“',
        'Schreib deine Meinung (mindestens 5 Sätze): Stadt oder Land?'
      ),
      minSentences: 5,
      checks: [
        { label: l('An opinion phrase (Meiner Meinung nach / Ich finde / Ich bin der Ansicht)', 'Fikir kalıbı (Meiner Meinung nach / Ich finde / Ich bin der Ansicht)', 'Meinung'), pattern: '(Meiner Meinung nach|[Ii]ch finde|[Ii]ch bin der Ansicht|[Ii]ch glaube)' },
        { label: l('einerseits … andererseits', 'einerseits … andererseits', 'einerseits … andererseits'), pattern: '[Ee]inerseits[\\s\\S]*andererseits' },
        { label: l('A reason (weil / denn / deshalb)', 'Bir sebep (weil / denn / deshalb)', 'Grund'), pattern: '\\b(weil|denn|[Dd]eshalb|[Dd]arum)\\b' },
      ],
      model: [
        'Ich finde, dass beides Vorteile hat.',
        'Einerseits ist die Stadt spannend, andererseits ist sie oft laut und teuer.',
        'Auf dem Land ist die Luft besser, aber man braucht meistens ein Auto.',
        'Meiner Meinung nach ist eine kleine Stadt die beste Lösung, weil man dort Ruhe und gute Busse hat.',
        'Deshalb möchte ich später in einer Kleinstadt wohnen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Agree, disagree or unsure? – 60 seconds.', 'Katılma, itiraz, emin değil? – 60 saniye.', 'Zustimmung oder Widerspruch? – 60 Sekunden.'),
      seconds: 60,
      pool: [...PHRASES.map(([id]) => `funktion-${id}`), 'mc-nach'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Opinion: Meiner Meinung nach … · Ich bin der Ansicht, dass …', 'Fikir: Meiner Meinung nach … · Ich bin der Ansicht, dass …', 'Meinung äußern'),
      l('Agree / disagree: Da stimme ich zu. · Das sehe ich anders.', 'Katılmak / itiraz: Da stimme ich zu. · Das sehe ich anders.', 'Zustimmen / widersprechen'),
      l('Pros and cons: einerseits … andererseits, Vorteil / Nachteil', 'Artı ve eksiler: einerseits … andererseits, Vorteil / Nachteil', 'Vor- und Nachteile'),
      l('Structure: zum Beispiel, außerdem, deshalb, zum Schluss', 'Yapı: zum Beispiel, außerdem, deshalb, zum Schluss', 'Aufbau'),
    ],
    mistakes: [
      { wrong: 'Meiner Meinung nach das ist richtig.', right: 'Meiner Meinung nach ist das richtig.', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Position 2.') },
      { wrong: 'Ich habe recht mit dir.', right: 'Du hast recht.', note: l('The other person is right.', 'Karşındaki haklı.', 'Du hast recht.') },
      { wrong: 'Einerseits es ist gut …', right: 'Einerseits ist es gut …', note: l('Verb after einerseits.', 'einerseits’ten sonra fiil.', 'Verb danach.') },
      { wrong: 'Ich stimme dir.', right: 'Ich stimme dir zu.', note: l('zustimmen is separable.', 'zustimmen ayrılabilir.', 'zu am Ende.') },
    ],
  },
}
