import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Präsentation', emoji: '📊', translation: l('presentation', 'sunum', 'Vortrag mit Folien'), example: 'Morgen halte ich eine Präsentation.' },
  { word: 'einen Vortrag halten', emoji: '🎤', translation: l('to give a talk', 'konuşma yapmak', 'vor Publikum sprechen'), example: 'Sie hält einen Vortrag über Energie.' },
  { word: 'die Folie', emoji: '🖼️', translation: l('slide', 'slayt', 'eine Seite der Präsentation'), example: 'Auf dieser Folie sehen Sie eine Grafik.' },
  { word: 'die Gliederung', emoji: '🗂️', translation: l('outline, structure', 'ana hatlar', 'Aufbau'), example: 'Hier sehen Sie die Gliederung meines Vortrags.' },
  { word: 'Zuerst möchte ich …', emoji: '1️⃣', translation: l('First I would like to …', 'Önce … istiyorum', 'Anfang'), example: 'Zuerst möchte ich kurz mein Thema vorstellen.' },
  { word: 'Danach / Anschließend', emoji: '➡️', translation: l('after that / then', 'ardından', 'als Nächstes'), example: 'Anschließend zeige ich Ihnen ein Beispiel.' },
  { word: 'Zum Schluss', emoji: '🏁', translation: l('finally', 'son olarak', 'am Ende'), example: 'Zum Schluss fasse ich alles zusammen.' },
  { word: 'zusammenfassen', emoji: '📝', translation: l('to summarise', 'özetlemek', 'kurz wiederholen'), example: 'Ich fasse die wichtigsten Punkte zusammen.' },
  { word: 'das Publikum', emoji: '👥', translation: l('audience', 'dinleyiciler', 'die Zuhörer'), example: 'Das Publikum hat viele Fragen gestellt.' },
  { word: 'Vielen Dank für Ihre Aufmerksamkeit.', emoji: '🙏', translation: l('Thank you for your attention.', 'İlginiz için teşekkürler.', 'Ende der Präsentation'), example: 'Vielen Dank für Ihre Aufmerksamkeit!' },
  { word: 'Gute Frage!', emoji: '❓', translation: l('Good question!', 'Güzel soru!', 'Reaktion auf eine Frage'), example: 'Gute Frage! Darauf komme ich gleich.' },
  { word: 'Wie Sie hier sehen …', emoji: '👉', translation: l('As you can see here …', 'Burada gördüğünüz gibi …', 'auf etwas zeigen'), example: 'Wie Sie hier sehen, ist die Zahl gestiegen.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Vortrag', gender: 'm', plural: 'die Vorträge', translation: l('talk, lecture', 'konuşma, sunum', 'Vortrag') },
  { word: 'Thema', gender: 'n', plural: 'die Themen', translation: l('topic', 'konu', 'Thema') },
  { word: 'Einleitung', gender: 'f', plural: 'die Einleitungen', translation: l('introduction', 'giriş', 'Einleitung') },
  { word: 'Hauptteil', gender: 'm', plural: 'die Hauptteile', translation: l('main part', 'ana bölüm', 'Hauptteil') },
  { word: 'Zusammenfassung', gender: 'f', plural: 'die Zusammenfassungen', translation: l('summary', 'özet', 'Zusammenfassung') },
  { word: 'Grafik', gender: 'f', plural: 'die Grafiken', translation: l('chart', 'grafik', 'Grafik') },
  { word: 'Punkt', gender: 'm', plural: 'die Punkte', translation: l('point', 'nokta, madde', 'Punkt') },
  { word: 'Zuhörer', gender: 'm', plural: 'die Zuhörer', translation: l('listener', 'dinleyici', 'Zuhörer') },
]

const PARTS = ['Einleitung', 'Hauptteil', 'Schluss'] as const

/** [id, phrase, index of part] */
const PHRASES: [string, string, 0 | 1 | 2][] = [
  ['thema', 'In meiner Präsentation geht es um …', 0],
  ['beispiel', 'Ein gutes Beispiel dafür ist …', 1],
  ['zusammen', 'Ich fasse kurz zusammen: …', 2],
  ['gliederung', 'Mein Vortrag besteht aus drei Teilen.', 0],
  ['grafik', 'Wie Sie auf dieser Grafik sehen, …', 1],
  ['dank', 'Vielen Dank für Ihre Aufmerksamkeit.', 2],
]

function partDrills(): Exercise[] {
  return PHRASES.map(([id, phrase, right], i) => {
    const options = [...PARTS]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `teil-${id}`,
      type: 'multiple_choice' as const,
      topic: 'struktur',
      concept: 'presentation-parts',
      skill: 'speaking' as const,
      difficulty: 1 as const,
      prompt: `„${phrase}“ – In welchen Teil der Präsentation passt das?`,
      options: ordered,
      answer: ordered.indexOf(PARTS[right]),
      explanation: l(`→ ${PARTS[right]}.`, `→ ${PARTS[right]}.`, `→ ${PARTS[right]}.`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-praesentation',
    type: 'matching',
    topic: 'redemittel',
    concept: 'presentation-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match German and meaning.', 'Almancayı anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'die Folie', right: 'slide' },
      { left: 'die Gliederung', right: 'outline' },
      { left: 'zusammenfassen', right: 'to summarise' },
      { left: 'das Publikum', right: 'audience' },
      { left: 'einen Vortrag halten', right: 'to give a talk' },
    ],
    explanation: l('Presentation vocabulary.', 'Sunum kelimeleri.', 'Präsentation.'),
  },
  {
    id: 'sort-gut-schlecht',
    type: 'categorize',
    topic: 'struktur',
    concept: 'tips',
    skill: 'reading',
    difficulty: 1,
    instructions: l('Good or bad presentation habit?', 'İyi mi kötü mü sunum alışkanlığı?', 'Guter oder schlechter Tipp?'),
    categories: ['gut 👍', 'schlecht 👎'],
    items: [
      { text: 'Blickkontakt mit dem Publikum halten', category: 0 },
      { text: 'alles von den Folien ablesen', category: 1 },
      { text: 'langsam und deutlich sprechen', category: 0 },
      { text: 'zwanzig Sätze auf eine Folie schreiben', category: 1 },
      { text: 'vorher mehrmals üben', category: 0 },
      { text: 'die Zeit überziehen', category: 1 },
    ],
    explanation: l('Eye contact, slow speech, short slides, practise beforehand.', 'Göz teması, yavaş konuşma, kısa slaytlar, önceden prova.', 'Präsentationstipps.'),
    practice: ['teil-thema'],
  },
  {
    id: 'mc-zuerst',
    type: 'multiple_choice',
    topic: 'redemittel',
    concept: 'sequence',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Zuerst ___ ich Ihnen kurz das Projekt vor.',
    options: ['stelle', 'stellen', 'vorstelle'],
    answer: 0,
    explanation: l('vorstellen is separable: Zuerst stelle ich … vor.', 'vorstellen ayrılabilir: Zuerst stelle ich … vor.', 'stelle … vor.'),
    examples: ['Zuerst **stelle** ich Ihnen kurz das Projekt **vor**.'],
    practice: ['fill-anschliessend'],
  },
  {
    id: 'tf-ablesen',
    type: 'true_false',
    topic: 'struktur',
    concept: 'tips',
    skill: 'reading',
    difficulty: 1,
    statement: 'Bei einer guten Präsentation liest man den ganzen Text von den Folien ab.',
    answer: false,
    explanation: l('Better: keywords on the slides, speak freely.', 'Daha iyisi: slaytta anahtar kelimeler, serbest konuşma.', 'frei sprechen.'),
  },
  {
    id: 'select-fragen',
    type: 'multiple_select',
    topic: 'fragen-beantworten',
    concept: 'handle-questions',
    skill: 'speaking',
    difficulty: 2,
    promptL10n: l('Good reactions to a question from the audience? Select all.', 'Dinleyiciden gelen bir soruya iyi tepkiler? Hepsini seç.', 'Gute Reaktionen auf Fragen?'),
    options: ['Danke für die Frage.', 'Das weiß ich leider nicht genau, aber ich schaue gern nach.', 'Das habe ich doch schon gesagt!', 'Können Sie die Frage bitte wiederholen?', 'Keine Fragen, bitte.'],
    answers: [0, 1, 3],
    explanation: l('Thank, be honest, ask for repetition – stay polite.', 'Teşekkür et, dürüst ol, tekrar iste – kibar kal.', 'Höflich reagieren.'),
  },
  {
    id: 'image-folie',
    type: 'image_choice',
    topic: 'redemittel',
    concept: 'presentation-words',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Wie Sie auf dieser Folie sehen, ist der Umsatz gestiegen.',
    options: [
      { emoji: '📈', label: 'Grafik: steigt' },
      { emoji: '📉', label: 'Grafik: sinkt' },
      { emoji: '🗺️', label: 'Landkarte' },
      { emoji: '📷', label: 'Foto' },
    ],
    answer: 0,
    explanation: l('gestiegen = risen 📈.', 'gestiegen = arttı 📈.', 'gestiegen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-anschliessend',
    type: 'fill_blank',
    topic: 'redemittel',
    concept: 'sequence',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Zuerst erkläre ich das Problem. ___ zeige ich Ihnen eine Lösung.',
    accepted: ['Anschließend', 'Danach', 'Dann'],
    base: 'then',
    explanation: l('Sequence: zuerst → anschließend / danach → zum Schluss.', 'Sıra: zuerst → anschließend / danach → zum Schluss.', 'Anschließend.'),
    examples: ['**Anschließend** zeige ich Ihnen eine Lösung.'],
  },
  {
    id: 'fill-geht',
    type: 'fill_blank',
    topic: 'struktur',
    concept: 'introduce-topic',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'In meiner Präsentation ___ es um gesunde Ernährung.',
    accepted: ['geht'],
    base: 'es geht um',
    explanation: l('Es geht um … = It is about …', 'Es geht um … = … hakkında.', 'geht.'),
    examples: ['In meiner Präsentation **geht** es um gesunde Ernährung.'],
  },
  {
    id: 'fill-schluss',
    type: 'fill_blank',
    topic: 'redemittel',
    concept: 'sequence',
    skill: 'vocabulary',
    difficulty: 1,
    sentence: 'Zum ___ möchte ich noch einmal das Wichtigste zusammenfassen.',
    accepted: ['Schluss'],
    base: 'finally',
    explanation: l('Zum Schluss = finally.', 'Zum Schluss = son olarak.', 'Schluss.'),
    examples: ['Zum **Schluss** möchte ich das Wichtigste zusammenfassen.'],
  },
  {
    id: 'build-gliederung',
    type: 'sentence_builder',
    topic: 'struktur',
    concept: 'introduce-topic',
    skill: 'grammar',
    difficulty: 2,
    chips: ['aus drei Teilen', 'besteht', 'Meine Präsentation'],
    answers: [['Meine Präsentation', 'besteht', 'aus drei Teilen']],
    translation: l('My presentation consists of three parts.', 'Sunumum üç bölümden oluşuyor.', 'Meine Präsentation besteht aus drei Teilen.'),
    explanation: l('bestehen aus + dative.', 'bestehen aus + Dativ.', 'besteht aus.'),
    examples: ['Meine Präsentation **besteht aus** drei Teilen.'],
  },
  {
    id: 'build-wie-sehen',
    type: 'sentence_builder',
    topic: 'redemittel',
    concept: 'refer-to-slide',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ist die Zahl', 'Wie Sie hier sehen,', 'gestiegen', 'stark'],
    answers: [['Wie Sie hier sehen,', 'ist die Zahl', 'stark', 'gestiegen']],
    translation: l('As you can see here, the number has risen sharply.', 'Burada gördüğünüz gibi sayı çok arttı.', 'Wie Sie hier sehen, ist die Zahl stark gestiegen.'),
    explanation: l('Clause first → main clause starts with the verb.', 'Önce yan cümle → ana cümle fiille başlar.', 'ist … gestiegen.'),
    examples: ['Wie Sie hier sehen, **ist** die Zahl stark **gestiegen**.'],
  },
  {
    id: 'build-frage',
    type: 'sentence_builder',
    topic: 'fragen-beantworten',
    concept: 'handle-questions',
    skill: 'grammar',
    difficulty: 3,
    chips: ['später', 'darauf', 'Ich komme', 'gern', 'zurück'],
    answers: [['Ich komme', 'gern', 'später', 'darauf', 'zurück'], ['Ich komme', 'später', 'gern', 'darauf', 'zurück']],
    translation: l('I’ll gladly come back to that later.', 'Buna daha sonra memnuniyetle döneceğim.', 'Ich komme gern später darauf zurück.'),
    explanation: l('zurückkommen auf → darauf … zurück.', 'zurückkommen auf → darauf … zurück.', 'darauf zurück.'),
    examples: ['Ich komme gern später **darauf zurück**.'],
  },
  {
    id: 'fix-vorstellen',
    type: 'error_correction',
    topic: 'redemittel',
    concept: 'sequence',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Zuerst ich möchte mich vorstellen.',
    accepted: ['Zuerst möchte ich mich vorstellen.'],
    explanation: l('Verb in position 2: Zuerst möchte ich …', 'Fiil 2. konumda: Zuerst möchte ich …', 'möchte ich.'),
    examples: ['Zuerst **möchte ich** mich vorstellen.'],
  },
  {
    id: 'fix-besteht',
    type: 'error_correction',
    topic: 'struktur',
    concept: 'introduce-topic',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Der Vortrag besteht von drei Teilen.',
    accepted: ['Der Vortrag besteht aus drei Teilen.'],
    explanation: l('bestehen aus (not von).', 'bestehen aus (von değil).', 'aus.'),
    examples: ['Der Vortrag besteht **aus** drei Teilen.'],
  },
  {
    id: 'fix-dank',
    type: 'error_correction',
    topic: 'redemittel',
    concept: 'closing',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Vielen Dank für Ihre Achtung.',
    accepted: ['Vielen Dank für Ihre Aufmerksamkeit.'],
    explanation: l('Fixed phrase: Vielen Dank für Ihre Aufmerksamkeit.', 'Kalıp: Vielen Dank für Ihre Aufmerksamkeit.', 'Aufmerksamkeit.'),
    examples: ['Vielen Dank für Ihre **Aufmerksamkeit**.'],
  },
  {
    id: 'tr-thema',
    type: 'translation',
    topic: 'struktur',
    concept: 'introduce-topic',
    skill: 'writing',
    difficulty: 2,
    source: l('Today I would like to talk about electric cars.', 'Bugün elektrikli arabalar hakkında konuşmak istiyorum.', 'Today I would like to talk about electric cars.'),
    accepted: ['Heute möchte ich über Elektroautos sprechen.', 'Heute möchte ich über E-Autos sprechen.', 'Ich möchte heute über Elektroautos sprechen.', 'Heute möchte ich über Elektroautos reden.'],
    explanation: l('Heute möchte ich über … sprechen.', 'Heute möchte ich über … sprechen.', 'über … sprechen.'),
    examples: ['Heute **möchte** ich über Elektroautos **sprechen**.'],
  },
  {
    id: 'tr-fragen',
    type: 'translation',
    topic: 'fragen-beantworten',
    concept: 'handle-questions',
    skill: 'writing',
    difficulty: 2,
    source: l('Do you have any questions?', 'Sorunuz var mı?', 'Do you have any questions?'),
    accepted: ['Haben Sie Fragen?', 'Haben Sie noch Fragen?', 'Gibt es Fragen?', 'Gibt es noch Fragen?'],
    explanation: l('Haben Sie (noch) Fragen?', 'Haben Sie (noch) Fragen?', 'Fragen?'),
    examples: ['**Haben Sie** noch **Fragen**?'],
  },
  {
    id: 'ordering-vortrag',
    type: 'ordering',
    topic: 'struktur',
    concept: 'presentation-parts',
    skill: 'speaking',
    difficulty: 2,
    promptL10n: l('Put the presentation in order.', 'Sunumu sırala.', 'Ordne die Präsentation.'),
    items: ['Zum Schluss fasse ich die wichtigsten Punkte zusammen.', 'Guten Tag, mein Name ist Ali. Heute spreche ich über Fahrradstädte.', 'Vielen Dank für Ihre Aufmerksamkeit. Haben Sie Fragen?', 'Zuerst zeige ich Ihnen das Beispiel Kopenhagen.', 'Danach vergleiche ich Kopenhagen mit unserer Stadt.'],
    answer: ['Guten Tag, mein Name ist Ali. Heute spreche ich über Fahrradstädte.', 'Zuerst zeige ich Ihnen das Beispiel Kopenhagen.', 'Danach vergleiche ich Kopenhagen mit unserer Stadt.', 'Zum Schluss fasse ich die wichtigsten Punkte zusammen.', 'Vielen Dank für Ihre Aufmerksamkeit. Haben Sie Fragen?'],
    explanation: l('Greeting/topic → first → then → finally → thanks + questions.', 'Selam/konu → önce → sonra → son olarak → teşekkür + sorular.', 'Aufbau.'),
  },
  {
    id: 'dialog-frage',
    type: 'dialogue',
    topic: 'fragen-beantworten',
    concept: 'handle-questions',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Zuhörer', de: 'Wie viel kostet das Projekt eigentlich?' }],
    options: ['Gute Frage! Die genauen Zahlen zeige ich Ihnen gleich auf der nächsten Folie.', 'Das Projekt ist ein Projekt.', 'Fragen sind nicht erlaubt.'],
    answer: 0,
    explanation: l('Thank for the question and refer to later: Darauf komme ich gleich.', 'Soru için teşekkür et ve sonrasına yönlendir: Darauf komme ich gleich.', 'Gute Frage!'),
  },
  {
    id: 'dialog-nicht-wissen',
    type: 'dialogue',
    topic: 'fragen-beantworten',
    concept: 'dont-know',
    skill: 'speaking',
    difficulty: 3,
    lines: [{ speaker: 'Zuhörerin', de: 'Wie ist die Situation in Österreich?' }],
    options: ['Das weiß ich leider nicht genau. Ich kann es aber gern recherchieren und Ihnen schreiben.', 'Österreich ist schön.', 'Das ist eine dumme Frage.'],
    answer: 0,
    explanation: l('Honest and helpful: Das weiß ich leider nicht genau, aber …', 'Dürüst ve yardımsever: Das weiß ich leider nicht genau, aber …', 'ehrlich bleiben.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-tipp1',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wie viele Wörter sollten auf einer Folie stehen?',
    options: ['Nur wenige Stichwörter.', 'Der ganze Text.', 'Mindestens 100 Wörter.'],
    answer: 0,
    explanation: l('„Schreiben Sie nur Stichwörter auf die Folien.“', '„Schreiben Sie nur Stichwörter auf die Folien.“', 'Stichwörter.'),
  },
  {
    id: 'read-anfang',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie sollte man anfangen?',
    options: ['Mit einer Frage oder einer überraschenden Zahl.', 'Mit einer Entschuldigung.', 'Mit dem Schluss.'],
    answer: 0,
    explanation: l('„Beginnen Sie mit einer Frage oder einer überraschenden Zahl.“', '„Beginnen Sie mit einer Frage oder einer überraschenden Zahl.“', 'Frage / Zahl.'),
  },
  {
    id: 'read-nervoes',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 2,
    statement: 'Laut Text ist Nervosität ganz normal.',
    answer: true,
    explanation: l('„Nervosität ist normal – sogar Profis sind nervös.“', '„Nervosität ist normal – sogar Profis sind nervös.“', 'richtig.'),
  },
  {
    id: 'read-ueben',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was hilft gegen Nervosität?',
    options: ['Den Vortrag laut üben, zum Beispiel vor Freunden.', 'Schneller sprechen.', 'Keine Folien benutzen.'],
    answer: 0,
    explanation: l('„Üben Sie den Vortrag laut – am besten vor Freunden.“', '„Üben Sie den Vortrag laut – am besten vor Freunden.“', 'üben.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-thema',
    type: 'listening_choice',
    topic: 'struktur',
    concept: 'introduce-topic',
    skill: 'listening',
    difficulty: 1,
    audio: 'Guten Morgen! In meinem Vortrag geht es heute um das Thema Schlaf und Gesundheit.',
    question: l('What is the topic?', 'Konu ne?', 'Was ist das Thema?'),
    options: ['sleep and health', 'sport and health', 'food and sleep'],
    answer: 0,
    explanation: l('„Schlaf und Gesundheit“', '„Schlaf und Gesundheit“', 'Schlaf.'),
  },
  {
    id: 'listen-teile',
    type: 'listening_choice',
    topic: 'struktur',
    concept: 'presentation-parts',
    skill: 'listening',
    difficulty: 2,
    audio: 'Mein Vortrag hat drei Teile: Zuerst die Fakten, danach meine eigenen Erfahrungen und zum Schluss einige Tipps.',
    question: l('What comes second?', 'İkinci sırada ne var?', 'Was kommt als Zweites?'),
    options: ['personal experiences', 'facts', 'tips'],
    answer: 0,
    explanation: l('„danach meine eigenen Erfahrungen“', '„danach meine eigenen Erfahrungen“', 'Erfahrungen.'),
  },
  {
    id: 'listen-folie',
    type: 'listening_choice',
    topic: 'redemittel',
    concept: 'refer-to-slide',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wie Sie auf dieser Folie sehen, schlafen Jugendliche im Durchschnitt nur sechs Stunden.',
    question: l('How long do teenagers sleep on average?', 'Gençler ortalama ne kadar uyuyor?', 'Wie lange schlafen Jugendliche?'),
    options: ['six hours', 'eight hours', 'sixteen hours'],
    answer: 0,
    explanation: l('„nur sechs Stunden“', '„nur sechs Stunden“', 'sechs.'),
  },
  {
    id: 'listen-ende',
    type: 'listening_choice',
    topic: 'fragen-beantworten',
    concept: 'closing',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das war es von meiner Seite. Vielen Dank fürs Zuhören! Jetzt beantworte ich gern Ihre Fragen.',
    question: l('What happens next?', 'Sırada ne var?', 'Was passiert jetzt?'),
    options: ['questions from the audience', 'a break', 'a second presentation'],
    answer: 0,
    explanation: l('„Jetzt beantworte ich gern Ihre Fragen.“', '„Jetzt beantworte ich gern Ihre Fragen.“', 'Fragen.'),
  },

  ...partDrills(),
]

export const UNIT_B1_24_PRAESENTATION: CourseUnit = {
  level: 'B1',
  number: 24,
  slug: 'praesentation',
  titleDe: 'Präsentieren und diskutieren',
  title: l('Presenting and discussing', 'Sunum yapmak ve tartışmak', 'Präsentieren und diskutieren'),
  goal: l(
    'By the end of this unit you can structure a short presentation, use typical phrases (Zuerst möchte ich …, Wie Sie hier sehen …, Zum Schluss …), refer to slides and react calmly to questions – just like in the B1 speaking exam.',
    'Bu ünitenin sonunda kısa bir sunumu yapılandırabilir, tipik kalıpları kullanabilir (Zuerst möchte ich …, Wie Sie hier sehen …, Zum Schluss …), slaytlara atıf yapabilir ve sorulara sakin tepki verebilirsin – tıpkı B1 konuşma sınavındaki gibi.',
    'Am Ende dieser Einheit hältst du eine kurze Präsentation.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'struktur', label: l('Structure', 'Yapı', 'Aufbau') },
    { key: 'redemittel', label: l('Useful phrases', 'Faydalı kalıplar', 'Redemittel') },
    { key: 'fragen-beantworten', label: l('Answering questions', 'Soruları cevaplamak', 'Fragen beantworten') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Your toolbox for presentations.', 'Sunumlar için alet çantan.', 'Werkzeuge für Präsentationen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Three parts', 'Üç bölüm', 'Drei Teile'),
          body: l(
            'Einleitung: greet, name the topic, give the outline. Hauptteil: points, examples, slides. Schluss: summarise, give your opinion, thank and invite questions.',
            'Einleitung: selamla, konuyu söyle, ana hatları ver. Hauptteil: maddeler, örnekler, slaytlar. Schluss: özetle, fikrini söyle, teşekkür et ve soru davet et.',
            'Einleitung → Hauptteil → Schluss.'
          ),
          table: {
            head: [l('Part', 'Bölüm', 'Teil'), l('Phrase', 'Kalıp', 'Redemittel')],
            rows: [
              ['Einleitung', 'In meinem Vortrag geht es um …'],
              ['Gliederung', 'Zuerst … Danach … Zum Schluss …'],
              ['Hauptteil', 'Wie Sie hier sehen, …'],
              ['Schluss', 'Ich fasse zusammen: …'],
            ],
          },
        },
        {
          title: l('Word order with sequence words', 'Sıra kelimeleriyle kelime dizimi', 'Satzstellung'),
          body: l(
            'Zuerst, danach, anschließend, zum Schluss take position 1 → the verb comes next: Zuerst möchte ich … / Danach zeige ich … Separable verbs split: Ich stelle Ihnen das Projekt vor.',
            'Zuerst, danach, anschließend, zum Schluss 1. konumdadır → sonra fiil gelir: Zuerst möchte ich … / Danach zeige ich … Ayrılabilen fiiller ayrılır: Ich stelle Ihnen das Projekt vor.',
            'Zuerst möchte ich …'
          ),
          examples: [
            { de: '**Zuerst möchte ich** mich kurz vorstellen.', translation: l('First I’d like to introduce myself.', 'Önce kendimi kısaca tanıtmak istiyorum.', '') },
            { de: '**Danach zeige** ich Ihnen eine Grafik.', translation: l('After that I’ll show you a chart.', 'Ardından size bir grafik göstereceğim.', '') },
          ],
        },
        {
          title: l('Handling questions', 'Sorularla başa çıkmak', 'Mit Fragen umgehen'),
          body: l(
            'Thank: Danke für die Frage. Gain time: Gute Frage, darauf komme ich gleich. Not understood: Können Sie die Frage bitte wiederholen? Don’t know: Das weiß ich leider nicht genau, aber ich schaue gern nach.',
            'Teşekkür: Danke für die Frage. Zaman kazan: Gute Frage, darauf komme ich gleich. Anlamadın: Können Sie die Frage bitte wiederholen? Bilmiyorsun: Das weiß ich leider nicht genau, aber ich schaue gern nach.',
            'Höflich und ehrlich.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Ali presents in his German course: „Cycling cities“.', 'Ali Almanca kursunda sunum yapıyor: „Bisiklet şehirleri“.', 'Ali präsentiert.'),
      dialogue: [
        { speaker: 'Ali', de: 'Guten Tag! **In meinem Vortrag geht es um** Fahrradstädte. **Zuerst** zeige ich Ihnen Kopenhagen, **danach** unsere Stadt und **zum Schluss** meine Ideen.', translation: l('Hello! My talk is about cycling cities. First I’ll show you Copenhagen, then our city and finally my ideas.', 'Merhaba! Sunumum bisiklet şehirleri hakkında. Önce size Kopenhag’ı, sonra şehrimizi, son olarak da fikirlerimi göstereceğim.', '') },
        { speaker: 'Ali', de: '**Wie Sie auf dieser Folie sehen**, fahren in Kopenhagen 60 Prozent der Menschen mit dem Rad zur Arbeit.', translation: l('As you see on this slide, 60 per cent of people in Copenhagen cycle to work.', 'Bu slaytta gördüğünüz gibi Kopenhag’da insanların yüzde 60’ı işe bisikletle gidiyor.', '') },
        { speaker: 'Ali', de: '**Ich fasse zusammen:** Mehr Radwege machen eine Stadt gesünder und leiser. **Vielen Dank für Ihre Aufmerksamkeit!**', translation: l('To sum up: more cycle paths make a city healthier and quieter. Thank you for your attention!', 'Özetle: daha fazla bisiklet yolu şehri daha sağlıklı ve sessiz yapar. İlginiz için teşekkürler!', '') },
        { speaker: 'Lehrerin', de: 'Danke, Ali! Gibt es Fragen? – Ja, Marta?', translation: l('Thank you, Ali! Any questions? – Yes, Marta?', 'Teşekkürler Ali! Soru var mı? – Evet Marta?', '') },
        { speaker: 'Marta', de: 'Wer soll die neuen Radwege denn bezahlen?', translation: l('Who is supposed to pay for the new cycle paths?', 'Yeni bisiklet yollarını kim ödeyecek peki?', '') },
        { speaker: 'Ali', de: '**Gute Frage!** Das weiß ich nicht genau, aber in Kopenhagen hat die Stadt das bezahlt. **Ich schaue gern nach**, wie es bei uns wäre.', translation: l('Good question! I don’t know exactly, but in Copenhagen the city paid. I’ll gladly check how it would be here.', 'Güzel soru! Tam bilmiyorum ama Kopenhag’da parayı belediye ödedi. Bizde nasıl olacağına memnuniyetle bakarım.', '') },
      ],
      examples: [
        { de: '**In meinem Vortrag geht es um** Energie.', translation: l('My talk is about energy.', 'Sunumum enerji hakkında.', '') },
        { de: 'Mein Vortrag **besteht aus** drei Teilen.', translation: l('My talk has three parts.', 'Sunumum üç bölümden oluşuyor.', '') },
        { de: '**Zuerst möchte ich** das Problem erklären.', translation: l('First I’d like to explain the problem.', 'Önce sorunu açıklamak istiyorum.', '') },
        { de: '**Wie Sie hier sehen**, ist die Zahl gestiegen.', translation: l('As you see here, the number has risen.', 'Burada gördüğünüz gibi sayı arttı.', '') },
        { de: '**Ich fasse kurz zusammen.**', translation: l('Let me briefly summarise.', 'Kısaca özetliyorum.', '') },
        { de: '**Gute Frage!** Darauf komme ich gleich.', translation: l('Good question! I’ll get to that in a moment.', 'Güzel soru! Birazdan ona geleceğim.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Which phrase belongs where?', 'Hangi kalıp nereye ait?', 'Welcher Teil?'),
      exercises: ['match-praesentation', 'sort-gut-schlecht', 'teil-thema', 'teil-beispiel', 'teil-zusammen', 'mc-zuerst', 'tf-ablesen', 'select-fragen', 'image-folie'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Build and give your own presentation.', 'Kendi sunumunu kur ve yap.', 'Deine Präsentation.'),
      exercises: [
        'fill-anschliessend',
        'fill-geht',
        'fill-schluss',
        'build-gliederung',
        'build-wie-sehen',
        'build-frage',
        'fix-vorstellen',
        'fix-besteht',
        'fix-dank',
        'tr-thema',
        'tr-fragen',
        'ordering-vortrag',
        'dialog-frage',
        'dialog-nicht-wissen',
        'teil-gliederung',
        'teil-grafik',
        'teil-dank',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Tips for a good presentation.', 'İyi bir sunum için ipuçları.', 'Tipps für Präsentationen.'),
      passage: [
        '**Fünf Tipps für Ihre nächste Präsentation**',
        '1. Beginnen Sie mit einer Frage oder einer überraschenden Zahl – so wird das Publikum neugierig. 2. Schreiben Sie nur **Stichwörter** auf die Folien, keine ganzen Sätze.',
        '3. Halten Sie Blickkontakt und sprechen Sie langsam. 4. Nervosität ist normal – sogar Profis sind nervös. Üben Sie den Vortrag laut – am besten vor Freunden.',
        '5. **Fassen** Sie am Ende das Wichtigste **zusammen**. Dann erinnern sich die Zuhörer besser an Ihre Botschaft.',
      ],
      glossary: [
        { de: 'überraschend', note: l('surprising', 'şaşırtıcı', 'unerwartet') },
        { de: 'neugierig', note: l('curious', 'meraklı', 'möchte mehr wissen') },
        { de: 'das Stichwort', note: l('keyword', 'anahtar kelime', 'ein wichtiges Wort') },
        { de: 'die Botschaft', note: l('message', 'mesaj', 'was man sagen will') },
      ],
      exercises: ['read-tipp1', 'read-anfang', 'read-nervoes', 'read-ueben'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Parts of a real talk.', 'Gerçek bir sunumdan bölümler.', 'Ausschnitte aus einem Vortrag.'),
      exercises: ['listen-thema', 'listen-teile', 'listen-folie', 'listen-ende'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Give a 1-minute presentation: „Learning languages – online or in a course?“', '1 dakikalık bir sunum yap: „Dil öğrenmek – çevrimiçi mi kursta mı?“', 'Kurzpräsentation: Sprachen lernen.'),
      points: [
        l('Introduce the topic and outline.', 'Konuyu ve ana hatları tanıt.', 'Einleitung'),
        l('One advantage of each.', 'Her birinin bir avantajı.', 'Vorteile'),
        l('Your own experience.', 'Kendi deneyimin.', 'Erfahrung'),
        l('Summary + thanks + „Haben Sie Fragen?“', 'Özet + teşekkür + „Haben Sie Fragen?“', 'Schluss'),
      ],
      model: [
        'In meiner Präsentation geht es um die Frage, wie man am besten Sprachen lernt.',
        'Zuerst spreche ich über Online-Kurse: Man kann flexibel lernen, wann man will.',
        'Danach geht es um Präsenzkurse – dort kann man viel mehr sprechen.',
        'Ich fasse zusammen: Für mich ist eine Mischung ideal. Vielen Dank – haben Sie Fragen?',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write the script for a short presentation on a topic of your choice (at least 5 sentences).',
        'İstediğin bir konuda kısa bir sunumun metnini yaz (en az 5 cümle).',
        'Schreib das Skript für eine Kurzpräsentation (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Introduce the topic (geht es um / spreche ich über)', 'Konuyu tanıt (geht es um / spreche ich über)', 'Thema'), pattern: '(geht es um|spreche ich über|möchte ich über)' },
        { label: l('Sequence words (Zuerst … Danach / Anschließend)', 'Sıra kelimeleri (Zuerst … Danach / Anschließend)', 'Gliederung'), pattern: '[Zz]uerst[\\s\\S]*([Dd]anach|[Aa]nschließend|[Dd]ann)' },
        { label: l('A closing (Zum Schluss / zusammenfassen / Aufmerksamkeit)', 'Kapanış (Zum Schluss / zusammenfassen / Aufmerksamkeit)', 'Schluss'), pattern: '(Zum Schluss|zusammen|Aufmerksamkeit)' },
      ],
      model: [
        'Guten Tag, heute möchte ich über mein Hobby Fotografieren sprechen.',
        'Zuerst erzähle ich, wie ich angefangen habe.',
        'Danach zeige ich Ihnen einige meiner Lieblingsfotos.',
        'Zum Schluss gebe ich Ihnen drei einfache Tipps für bessere Handyfotos.',
        'Vielen Dank für Ihre Aufmerksamkeit!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Introduction, main part or conclusion? – 60 seconds.', 'Giriş, ana bölüm mü sonuç mu? – 60 saniye.', 'Welcher Teil? – 60 Sekunden.'),
      seconds: 60,
      pool: [...PHRASES.map(([id]) => `teil-${id}`), 'mc-zuerst'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Structure: Einleitung → Hauptteil → Schluss', 'Yapı: Einleitung → Hauptteil → Schluss', 'Aufbau'),
      l('Phrases: In meinem Vortrag geht es um … · Zuerst … Danach … Zum Schluss …', 'Kalıplar: In meinem Vortrag geht es um … · Zuerst … Danach … Zum Schluss …', 'Redemittel'),
      l('Slides: Wie Sie hier sehen, … · Auf dieser Folie …', 'Slaytlar: Wie Sie hier sehen, … · Auf dieser Folie …', 'Folien'),
      l('Questions: Gute Frage! · Darauf komme ich gleich. · Das weiß ich leider nicht genau.', 'Sorular: Gute Frage! · Darauf komme ich gleich. · Das weiß ich leider nicht genau.', 'Fragen'),
    ],
    mistakes: [
      { wrong: 'Zuerst ich möchte …', right: 'Zuerst möchte ich …', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Position 2.') },
      { wrong: 'besteht von drei Teilen', right: 'besteht aus drei Teilen', note: l('bestehen aus.', 'bestehen aus.', 'aus.') },
      { wrong: 'Vielen Dank für Ihre Achtung.', right: 'Vielen Dank für Ihre Aufmerksamkeit.', note: l('Fixed phrase.', 'Kalıp.', 'Aufmerksamkeit.') },
      { wrong: 'Ich vorstelle das Projekt.', right: 'Ich stelle das Projekt vor.', note: l('Separable verb.', 'Ayrılabilen fiil.', 'trennbar.') },
    ],
  },
}
