import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'wäre', emoji: '🌟', translation: l('would be (sein)', 'olsaydı (sein)', 'Konjunktiv II von sein'), example: 'Wenn ich reich wäre, würde ich reisen.' },
  { word: 'hätte', emoji: '💰', translation: l('would have (haben)', 'olsaydı, sahip olsaydı (haben)', 'Konjunktiv II von haben'), example: 'Wenn ich mehr Zeit hätte, würde ich Gitarre lernen.' },
  { word: 'würde + Infinitiv', emoji: '💭', translation: l('would + verb', '-ardı / -erdi', 'Konjunktiv II mit würde'), example: 'Ich würde gern am Meer wohnen.' },
  { word: 'könnte', emoji: '🦸', translation: l('could', '-ebilirdi', 'Konjunktiv II von können'), example: 'Wenn ich fliegen könnte, wäre ich jetzt in Paris.' },
  { word: 'müsste', emoji: '😓', translation: l('would have to', '-mek zorunda olurdu', 'Konjunktiv II von müssen'), example: 'Dann müsste ich nicht mehr arbeiten.' },
  { word: 'Wenn ich …, würde ich …', emoji: '🔀', translation: l('If I …, I would …', 'Eğer …-saydım, …-ardım', 'irreale Bedingung'), example: 'Wenn ich du wäre, würde ich das nicht machen.' },
  { word: 'Ich wünschte, …', emoji: '🌠', translation: l('I wish …', 'Keşke …', 'irrealer Wunsch'), example: 'Ich wünschte, es wäre schon Freitag.' },
  { word: 'Wenn … doch …!', emoji: '🙏', translation: l('If only …!', 'Keşke …!', 'Wunsch'), example: 'Wenn ich doch mehr Zeit hätte!' },
  { word: 'der Traum', emoji: '☁️', translation: l('dream', 'hayal', 'Wunsch'), example: 'Mein Traum ist ein Haus am Meer.' },
  { word: 'reich', emoji: '🤑', translation: l('rich', 'zengin', 'viel Geld'), example: 'Wenn ich reich wäre …' },
  { word: 'der Lottogewinn', emoji: '🎰', translation: l('lottery win', 'piyango ikramiyesi', 'Geld vom Lotto'), example: 'Was würdest du mit einem Lottogewinn machen?' },
  { word: 'unsichtbar', emoji: '👻', translation: l('invisible', 'görünmez', 'man kann es nicht sehen'), example: 'Wenn ich unsichtbar wäre, …' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Traum', gender: 'm', plural: 'die Träume', translation: l('dream', 'hayal', 'Traum') },
  { word: 'Wunsch', gender: 'm', plural: 'die Wünsche', translation: l('wish', 'dilek', 'Wunsch') },
  { word: 'Insel', gender: 'f', plural: 'die Inseln', translation: l('island', 'ada', 'Insel') },
  { word: 'Weltreise', gender: 'f', plural: 'die Weltreisen', translation: l('trip around the world', 'dünya turu', 'Weltreise') },
  { word: 'Zeit', gender: 'f', translation: l('time', 'zaman', 'Zeit') },
  { word: 'Geld', gender: 'n', translation: l('money', 'para', 'Geld') },
  { word: 'Haus', gender: 'n', plural: 'die Häuser', translation: l('house', 'ev', 'Haus') },
]

/** [id, sentence with ___, right, wrong A, wrong B, explanation key] */
const K2: [string, string, string, string, string, string][] = [
  ['waere-ich', 'Wenn ich reich ___, würde ich eine Weltreise machen.', 'wäre', 'war', 'bin', 'sein → wäre'],
  ['haette-ich', 'Wenn ich mehr Zeit ___, würde ich mehr lesen.', 'hätte', 'hatte', 'habe', 'haben → hätte'],
  ['wuerde-du', 'Was ___ du mit einer Million Euro machen?', 'würdest', 'wurdest', 'würdet', 'würde + du → würdest'],
  ['koennte-wir', 'Wenn wir fliegen ___, wären wir in einer Stunde in Rom.', 'könnten', 'konnten', 'können', 'können → könnten'],
  ['waere-es', 'Ich wünschte, es ___ schon Wochenende.', 'wäre', 'ist', 'war', 'Wunsch → wäre'],
  ['haette-er', 'Wenn er ein Auto ___, müsste er nicht mit dem Bus fahren.', 'hätte', 'hat', 'hattet', 'haben → hätte'],
  ['muesste-ich', 'Wenn ich im Lotto gewinnen würde, ___ ich nicht mehr arbeiten.', 'müsste', 'musste', 'muss', 'müssen → müsste'],
]

function k2Drills(): Exercise[] {
  return K2.map(([id, sentence, right, wrongA, wrongB, why], i) => {
    const options = [right, wrongA, wrongB]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `k2-${id}`,
      type: 'multiple_choice' as const,
      topic: 'k2-formen',
      concept: `k2-${right.replace(/(st|n|t)$/, '')}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Unreal → Konjunktiv II: ${why}. (Without umlaut it’s the past tense!)`,
        `Gerçek dışı → Konjunktiv II: ${why}. (Umlaut olmadan geçmiş zamandır!)`,
        `Konjunktiv II: ${why}.`
      ),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'sort-real',
    type: 'categorize',
    topic: 'real-irreal',
    concept: 'real-or-unreal',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Real or unreal (imagined)?', 'Gerçek mi gerçek dışı (hayal) mi?', 'Real oder irreal?'),
    categories: ['real', 'irreal'],
    items: [
      { text: 'Wenn ich Zeit habe, komme ich.', category: 0 },
      { text: 'Wenn ich Zeit hätte, würde ich kommen.', category: 1 },
      { text: 'Wenn es regnet, bleiben wir zu Hause.', category: 0 },
      { text: 'Wenn ich ein Vogel wäre, würde ich fliegen.', category: 1 },
      { text: 'Ich habe ein Auto.', category: 0 },
      { text: 'Ich wünschte, ich hätte ein Auto.', category: 1 },
    ],
    explanation: l('Indicative (habe, ist) = real/possible. Konjunktiv II (hätte, wäre, würde) = imagined, not true.', 'Bildirme kipi (habe, ist) = gerçek/olası. Konjunktiv II (hätte, wäre, würde) = hayal, gerçek değil.', 'Konjunktiv II = irreal.'),
    practice: ['k2-waere-ich', 'k2-haette-ich'],
  },
  {
    id: 'match-forms',
    type: 'matching',
    topic: 'k2-formen',
    concept: 'k2-table',
    skill: 'grammar',
    difficulty: 1,
    instructions: l('Infinitive → Konjunktiv II (ich).', 'Mastar → Konjunktiv II (ich).', 'Infinitiv → Konjunktiv II.'),
    pairs: [
      { left: 'sein', right: 'wäre' },
      { left: 'haben', right: 'hätte' },
      { left: 'können', right: 'könnte' },
      { left: 'müssen', right: 'müsste' },
      { left: 'werden', right: 'würde' },
    ],
    explanation: l('Past tense + umlaut: war → wäre, hatte → hätte, konnte → könnte, musste → müsste, wurde → würde.', 'Geçmiş zaman + umlaut: war → wäre, hatte → hätte, konnte → könnte, musste → müsste, wurde → würde.', 'Präteritum + Umlaut.'),
  },
  {
    id: 'mc-wuerde',
    type: 'multiple_choice',
    topic: 'bedingung',
    concept: 'wenn-wuerde',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Wenn ich am Meer wohnen würde, ___ ich jeden Tag schwimmen.',
    options: ['würde', 'werde', 'wurde'],
    answer: 0,
    explanation: l('Unreal consequence → würde + infinitive.', 'Gerçek dışı sonuç → würde + mastar.', 'würde … schwimmen.'),
    examples: ['…, **würde** ich jeden Tag **schwimmen**.'],
  },
  {
    id: 'tf-war-waere',
    type: 'true_false',
    topic: 'k2-formen',
    concept: 'k2-waere',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Wenn ich reich war, …“ ist ein irrealer Wunsch.',
    answer: false,
    explanation: l('war = past (I was). Unreal: wäre.', 'war = geçmiş (idim). Gerçek dışı: wäre.', 'wäre, nicht war.'),
    examples: ['Wenn ich reich **wäre**, …'],
  },
  {
    id: 'select-irreal',
    type: 'multiple_select',
    topic: 'real-irreal',
    concept: 'wishes',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences express an unreal wish? Select all.', 'Hangi cümleler gerçek dışı bir dileği ifade ediyor? Hepsini seç.', 'Welche Sätze sind irreale Wünsche?'),
    options: ['Ich wünschte, ich könnte fliegen.', 'Ich kann fliegen.', 'Wenn ich doch nur mehr Geld hätte!', 'Hätte ich doch mehr Zeit!', 'Ich habe viel Zeit.'],
    answers: [0, 2, 3],
    explanation: l('Wishes: Ich wünschte, … / Wenn … doch nur …! / Hätte ich doch …!', 'Dilekler: Ich wünschte, … / Wenn … doch nur …! / Hätte ich doch …!', 'irreale Wünsche.'),
  },
  {
    id: 'image-traum',
    type: 'image_choice',
    topic: 'bedingung',
    concept: 'dreams',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Wenn ich viel Geld hätte, würde ich auf einer Insel leben.',
    options: [
      { emoji: '🏝️', label: 'Insel' },
      { emoji: '🏔️', label: 'Berge' },
      { emoji: '🏙️', label: 'Großstadt' },
      { emoji: '🏜️', label: 'Wüste' },
    ],
    answer: 0,
    explanation: l('die Insel = island 🏝️.', 'die Insel = ada 🏝️.', 'Insel.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-haette',
    type: 'fill_blank',
    topic: 'k2-formen',
    concept: 'k2-haette',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wenn ich einen Garten ___, würde ich Tomaten pflanzen.',
    accepted: ['hätte'],
    base: 'haben',
    explanation: l('haben → hätte.', 'haben → hätte.', 'hätte.'),
    examples: ['Wenn ich einen Garten **hätte**, …'],
  },
  {
    id: 'fill-waere-du',
    type: 'fill_blank',
    topic: 'k2-formen',
    concept: 'k2-waere',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'An deiner Stelle ___ ich vorsichtig.',
    accepted: ['wäre'],
    base: 'sein',
    explanation: l('Advice → wäre: An deiner Stelle wäre ich vorsichtig.', 'Tavsiye → wäre: An deiner Stelle wäre ich vorsichtig.', 'wäre.'),
    examples: ['An deiner Stelle **wäre** ich vorsichtig.'],
  },
  {
    id: 'fill-koennte',
    type: 'fill_blank',
    topic: 'k2-formen',
    concept: 'k2-koennte',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich wünschte, ich ___ besser kochen. (können)',
    accepted: ['könnte'],
    base: 'können',
    explanation: l('können → könnte.', 'können → könnte.', 'könnte.'),
    examples: ['Ich wünschte, ich **könnte** besser kochen.'],
  },
  {
    id: 'build-wenn',
    type: 'sentence_builder',
    topic: 'bedingung',
    concept: 'wenn-wuerde',
    skill: 'grammar',
    difficulty: 3,
    chips: ['würde', 'ein Haus kaufen', 'ich', 'Wenn ich reich wäre,'],
    answers: [['Wenn ich reich wäre,', 'würde', 'ich', 'ein Haus kaufen']],
    translation: l('If I were rich, I would buy a house.', 'Zengin olsaydım bir ev alırdım.', 'Wenn ich reich wäre, würde ich ein Haus kaufen.'),
    explanation: l('wenn-clause (verb at the end) – verb, verb: …, würde ich …', 'wenn-cümlesi (fiil sonda) – fiil, fiil: …, würde ich …', 'Wenn …, würde ich …'),
    examples: ['Wenn ich reich **wäre**, **würde** ich ein Haus **kaufen**.'],
  },
  {
    id: 'build-wuensche',
    type: 'sentence_builder',
    topic: 'wuensche',
    concept: 'wishes',
    skill: 'grammar',
    difficulty: 2,
    chips: ['es', 'schon', 'wäre', 'Ich wünschte,', 'Sommer'],
    answers: [['Ich wünschte,', 'es', 'wäre', 'schon', 'Sommer']],
    translation: l('I wish it were summer already.', 'Keşke şimdiden yaz olsa.', 'Ich wünschte, es wäre schon Sommer.'),
    explanation: l('After „Ich wünschte,“ main-clause word order + Konjunktiv II.', '„Ich wünschte,“ sonrası ana cümle dizilimi + Konjunktiv II.', 'Ich wünschte, es wäre …'),
    examples: ['Ich wünschte, es **wäre** schon Sommer.'],
  },
  {
    id: 'build-doch',
    type: 'sentence_builder',
    topic: 'wuensche',
    concept: 'wishes',
    skill: 'grammar',
    difficulty: 3,
    chips: ['doch', 'mehr Zeit', 'Wenn', 'hätte', 'ich'],
    answers: [['Wenn', 'ich', 'doch', 'mehr Zeit', 'hätte']],
    end: '!',
    translation: l('If only I had more time!', 'Keşke daha çok vaktim olsa!', 'Wenn ich doch mehr Zeit hätte!'),
    explanation: l('Wish: Wenn … doch … + Konjunktiv II at the end.', 'Dilek: Wenn … doch … + sonda Konjunktiv II.', 'Wenn … doch … hätte!'),
    examples: ['Wenn ich **doch** mehr Zeit **hätte**!'],
  },
  {
    id: 'fix-wuerde-waere',
    type: 'error_correction',
    topic: 'bedingung',
    concept: 'wenn-wuerde',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wenn ich Zeit hätte, ich würde dich besuchen.',
    accepted: ['Wenn ich Zeit hätte, würde ich dich besuchen.'],
    explanation: l('After the wenn-clause: verb first → würde ich.', 'wenn-cümlesinden sonra: önce fiil → würde ich.', 'würde ich.'),
    examples: ['Wenn ich Zeit hätte, **würde ich** dich besuchen.'],
  },
  {
    id: 'fix-hatte',
    type: 'error_correction',
    topic: 'k2-formen',
    concept: 'k2-haette',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Wenn ich ein Auto hatte, würde ich ans Meer fahren.',
    accepted: ['Wenn ich ein Auto hätte, würde ich ans Meer fahren.'],
    explanation: l('Unreal → hätte (with umlaut).', 'Gerçek dışı → hätte (umlaut’lu).', 'hätte.'),
    examples: ['Wenn ich ein Auto **hätte**, …'],
  },
  {
    id: 'fix-wuerde-double',
    type: 'error_correction',
    topic: 'bedingung',
    concept: 'wenn-wuerde',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wenn ich reich sein würde, würde ich reisen.',
    accepted: ['Wenn ich reich wäre, würde ich reisen.'],
    explanation: l('With sein and haben use wäre/hätte, not „würde sein/haben“.', 'sein ve haben ile wäre/hätte kullan, „würde sein/haben“ değil.', 'wäre statt würde sein.'),
    examples: ['Wenn ich reich **wäre**, würde ich reisen.'],
  },
  {
    id: 'tr-waere',
    type: 'translation',
    topic: 'bedingung',
    concept: 'wenn-wuerde',
    skill: 'writing',
    difficulty: 3,
    source: l('If I were you, I would call her.', 'Senin yerinde olsam onu arardım.', 'If I were you, I would call her.'),
    accepted: ['Wenn ich du wäre, würde ich sie anrufen.', 'An deiner Stelle würde ich sie anrufen.'],
    explanation: l('Wenn ich du wäre, … / An deiner Stelle würde ich …', 'Wenn ich du wäre, … / An deiner Stelle würde ich …', 'Wenn ich du wäre, …'),
    examples: ['Wenn ich du **wäre**, **würde** ich sie **anrufen**.'],
  },
  {
    id: 'tr-wuensche',
    type: 'translation',
    topic: 'wuensche',
    concept: 'wishes',
    skill: 'writing',
    difficulty: 2,
    source: l('I wish I could speak German perfectly.', 'Keşke mükemmel Almanca konuşabilsem.', 'I wish I could speak German perfectly.'),
    accepted: ['Ich wünschte, ich könnte perfekt Deutsch sprechen.', 'Ich wünschte, ich könnte perfekt Deutsch.'],
    explanation: l('Ich wünschte, ich könnte …', 'Ich wünschte, ich könnte …', 'Ich wünschte, ich könnte …'),
    examples: ['Ich wünschte, ich **könnte** perfekt Deutsch sprechen.'],
  },
  {
    id: 'ordering-k2',
    type: 'ordering',
    topic: 'bedingung',
    concept: 'wenn-wuerde',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Build the sentence.', 'Cümleyi kur.', 'Bilde den Satz.'),
    items: ['würde', 'Wenn ich unsichtbar wäre,', 'ins Kino gehen', 'ich', 'ohne Ticket'],
    answer: ['Wenn ich unsichtbar wäre,', 'würde', 'ich', 'ohne Ticket', 'ins Kino gehen'],
    explanation: l('wenn-clause – würde – ich – … – infinitive.', 'wenn-cümlesi – würde – ich – … – mastar.', 'Wenn …, würde ich … gehen.'),
  },
  {
    id: 'dialog-lotto',
    type: 'dialogue',
    topic: 'bedingung',
    concept: 'dreams',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Freundin', de: 'Was würdest du machen, wenn du im Lotto gewinnen würdest?' }],
    options: ['Ich würde zuerst meinen Eltern ein Haus kaufen.', 'Ich werde zuerst meinen Eltern ein Haus kaufen.', 'Ich wurde zuerst ein Haus kaufen.'],
    answer: 0,
    explanation: l('Imagined → würde + infinitive.', 'Hayal → würde + mastar.', 'Ich würde …'),
  },
  {
    id: 'dialog-ratschlag',
    type: 'dialogue',
    topic: 'bedingung',
    concept: 'advice-k2',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollege', de: 'Mein Chef ist so unfreundlich. Soll ich kündigen?' }],
    options: ['An deiner Stelle würde ich zuerst mit ihm sprechen.', 'An deiner Stelle ich würde mit ihm sprechen.', 'An deiner Stelle werde ich mit ihm sprechen.'],
    answer: 0,
    explanation: l('Advice: An deiner Stelle würde ich …', 'Tavsiye: An deiner Stelle würde ich …', 'An deiner Stelle würde ich …'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-umfrage',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-umfrage',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was würde Lukas mit einer Million machen?',
    options: ['Eine Weltreise mit seiner Familie.', 'Ein Auto kaufen.', 'Nichts.'],
    answer: 0,
    explanation: l('„Ich würde mit meiner Familie eine Weltreise machen.“', '„Ich würde mit meiner Familie eine Weltreise machen.“', 'Weltreise.'),
  },
  {
    id: 'read-maria',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-umfrage',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was wünscht sich Maria?',
    options: ['Mehr Zeit für ihre Kinder.', 'Mehr Geld.', 'Ein größeres Haus.'],
    answer: 0,
    explanation: l('„Ich wünschte, ich hätte mehr Zeit für meine Kinder.“', '„Ich wünschte, ich hätte mehr Zeit für meine Kinder.“', 'Zeit für Kinder.'),
  },
  {
    id: 'read-arbeit',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-umfrage',
    skill: 'reading',
    difficulty: 2,
    statement: 'Herr Lange würde mit dem Geld aufhören zu arbeiten.',
    answer: false,
    explanation: l('„Ich würde weiter arbeiten – meine Arbeit macht mir Spaß.“', '„Ich würde weiter arbeiten – meine Arbeit macht mir Spaß.“', 'weiter arbeiten.'),
  },
  {
    id: 'read-superkraft',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-umfrage',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Welche Superkraft hätte Elif gern?',
    options: ['Sie würde gern alle Sprachen sprechen können.', 'Sie würde gern fliegen.', 'Sie wäre gern unsichtbar.'],
    answer: 0,
    explanation: l('„Wenn ich eine Superkraft hätte, würde ich alle Sprachen der Welt sprechen können.“', '„Wenn ich eine Superkraft hätte, würde ich alle Sprachen der Welt sprechen können.“', 'alle Sprachen.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-real',
    type: 'listening_choice',
    topic: 'real-irreal',
    concept: 'real-or-unreal',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wenn ich mehr Geld hätte, würde ich mir ein neues Fahrrad kaufen.',
    question: l('Does the person have a lot of money?', 'Kişinin çok parası var mı?', 'Hat die Person viel Geld?'),
    options: ['No', 'Yes'],
    answer: 0,
    explanation: l('„hätte“ = unreal → no.', '„hätte“ = gerçek dışı → hayır.', 'nein.'),
  },
  {
    id: 'listen-wunsch',
    type: 'listening_choice',
    topic: 'wuensche',
    concept: 'wishes',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich wünschte, ich müsste morgen nicht so früh aufstehen.',
    question: l('What is the wish?', 'Dilek ne?', 'Was ist der Wunsch?'),
    options: ['not to get up early', 'to go to bed early', 'to have a holiday'],
    answer: 0,
    explanation: l('„nicht so früh aufstehen“', '„nicht so früh aufstehen“', 'nicht früh aufstehen.'),
  },
  {
    id: 'listen-insel',
    type: 'listening_choice',
    topic: 'bedingung',
    concept: 'dreams',
    skill: 'listening',
    difficulty: 1,
    audio: 'Wenn ich auf einer einsamen Insel wäre, würde ich ein gutes Buch mitnehmen.',
    question: l('What would the person take?', 'Kişi ne götürürdü?', 'Was würde die Person mitnehmen?'),
    options: ['📖', '📱', '🎸'],
    answer: 0,
    explanation: l('„ein gutes Buch“', '„ein gutes Buch“', 'Buch.'),
  },
  {
    id: 'listen-koennte',
    type: 'listening_choice',
    topic: 'k2-formen',
    concept: 'k2-koennte',
    skill: 'listening',
    difficulty: 2,
    audio: 'Könnten Sie mir vielleicht kurz helfen?',
    question: l('What is this?', 'Bu ne?', 'Was ist das?'),
    options: ['a polite request', 'a wish about the past', 'an order'],
    answer: 0,
    explanation: l('Konjunktiv II is also used for polite requests.', 'Konjunktiv II kibar ricalar için de kullanılır.', 'höfliche Bitte.'),
  },

  ...k2Drills(),
]

export const UNIT_B1_05_KONJUNKTIV_WUENSCHE: CourseUnit = {
  level: 'B1',
  number: 5,
  slug: 'konjunktiv-wuensche',
  titleDe: 'Wenn ich reich wäre …',
  title: l('If I were rich …', 'Zengin olsaydım …', 'Wenn ich reich wäre …'),
  goal: l(
    'By the end of this unit you can talk about dreams, unreal conditions and wishes with the Konjunktiv II: wäre, hätte, könnte, müsste, würde + infinitive – and „Ich wünschte, …“.',
    'Bu ünitenin sonunda Konjunktiv II ile hayaller, gerçek dışı koşullar ve dilekler hakkında konuşabilirsin: wäre, hätte, könnte, müsste, würde + mastar – ve „Ich wünschte, …“.',
    'Am Ende dieser Einheit sprichst du über Träume und Wünsche im Konjunktiv II.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'k2-formen', label: l('wäre, hätte, könnte, würde', 'wäre, hätte, könnte, würde', 'Konjunktiv-II-Formen') },
    { key: 'real-irreal', label: l('Real or unreal?', 'Gerçek mi değil mi?', 'Real oder irreal?') },
    { key: 'bedingung', label: l('Wenn …, würde …', 'Wenn …, würde …', 'irreale Bedingungen') },
    { key: 'wuensche', label: l('Ich wünschte, …', 'Ich wünschte, …', 'Wünsche') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('The language of dreams and wishes.', 'Hayallerin ve dileklerin dili.', 'Die Sprache der Träume.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Konjunktiv II: the imagined world', 'Konjunktiv II: hayal dünyası', 'Konjunktiv II: die gedachte Welt'),
          body: l(
            'For things that are not true (yet): wäre (sein), hätte (haben), könnte, müsste, dürfte – and for most other verbs würde + infinitive.',
            'Gerçek olmayan (henüz) şeyler için: wäre (sein), hätte (haben), könnte, müsste, dürfte – ve diğer fiillerin çoğu için würde + mastar.',
            'wäre, hätte, könnte, müsste + würde + Infinitiv.'
          ),
          table: {
            head: [l('Person', 'Kişi', 'Person'), l('sein', 'sein', 'sein'), l('haben', 'haben', 'haben'), l('werden', 'werden', 'werden'), l('können', 'können', 'können')],
            rows: [
              ['ich', 'wäre', 'hätte', 'würde', 'könnte'],
              ['du', 'wärst', 'hättest', 'würdest', 'könntest'],
              ['er / sie', 'wäre', 'hätte', 'würde', 'könnte'],
              ['wir / sie / Sie', 'wären', 'hätten', 'würden', 'könnten'],
              ['ihr', 'wärt', 'hättet', 'würdet', 'könntet'],
            ],
          },
          tip: l('Don’t forget the umlaut: hatte (past) ≠ hätte (unreal)!', 'Umlaut’u unutma: hatte (geçmiş) ≠ hätte (gerçek dışı)!', 'hatte ≠ hätte.'),
        },
        {
          title: l('Unreal conditions', 'Gerçek dışı koşullar', 'Irreale Bedingungen'),
          body: l(
            'Wenn + Konjunktiv II (verb at the end), + Konjunktiv II in the main clause (verb, verb). With sein/haben use wäre/hätte, not „würde sein“.',
            'Wenn + Konjunktiv II (fiil sonda), + ana cümlede Konjunktiv II (fiil, fiil). sein/haben ile wäre/hätte kullan, „würde sein“ değil.',
            'Wenn ich … wäre, würde ich …'
          ),
          examples: [
            { de: 'Wenn ich Zeit **hätte**, **würde** ich mehr Sport **machen**.', translation: l('If I had time, I would do more sport.', 'Vaktim olsaydı daha çok spor yapardım.', '') },
            { de: 'Wenn ich du **wäre**, **würde** ich das nicht **tun**.', translation: l('If I were you, I wouldn’t do that.', 'Senin yerinde olsam bunu yapmazdım.', '') },
          ],
        },
        {
          title: l('Wishes', 'Dilekler', 'Wünsche'),
          body: l('Ich wünschte, ich hätte … / Wenn ich doch nur … wäre! / Hätte ich doch …!', 'Ich wünschte, ich hätte … / Wenn ich doch nur … wäre! / Hätte ich doch …!', 'Ich wünschte … / Wenn … doch …!'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Lunch break: colleagues dream about winning the lottery.', 'Öğle arası: iş arkadaşları piyango kazanmayı hayal ediyor.', 'Mittagspause: Lottoträume.'),
      dialogue: [
        { speaker: 'Lea', de: 'Heute ist der Jackpot bei 30 Millionen! Was **würdet** ihr **machen**, wenn ihr **gewinnen würdet**?', translation: l('Today the jackpot is 30 million! What would you do if you won?', 'Bugün ikramiye 30 milyon! Kazansanız ne yapardınız?', '') },
        { speaker: 'Kerem', de: 'Ich **würde** sofort **kündigen** und eine Weltreise **machen**!', translation: l('I’d quit immediately and travel around the world!', 'Hemen istifa edip dünya turuna çıkardım!', '') },
        { speaker: 'Anna', de: 'Ich nicht. Wenn ich so viel Geld **hätte**, **würde** ich ein kleines Café **eröffnen**.', translation: l('Not me. If I had so much money, I’d open a small café.', 'Ben öyle değil. O kadar param olsaydı küçük bir kafe açardım.', '') },
        { speaker: 'Lea', de: 'Schöne Idee! Und **wärst** du dann glücklicher?', translation: l('Nice idea! And would you be happier then?', 'Güzel fikir! Peki o zaman daha mutlu olur muydun?', '') },
        { speaker: 'Anna', de: 'Bestimmt. Dann **müsste** ich nie mehr Excel-Tabellen **machen**! 😄', translation: l('Definitely. Then I’d never have to do Excel spreadsheets again! 😄', 'Kesinlikle. O zaman bir daha asla Excel tablosu yapmak zorunda kalmazdım! 😄', '') },
        { speaker: 'Kerem', de: '**Ich wünschte**, wir **hätten** schon gewonnen …', translation: l('I wish we’d already won …', 'Keşke çoktan kazanmış olsaydık …', '') },
        { speaker: 'Lea', de: 'Na ja – dafür **müssten** wir erst mal ein Los **kaufen**!', translation: l('Well – for that we’d first have to buy a ticket!', 'Eh – bunun için önce bir bilet almamız gerekirdi!', '') },
      ],
      examples: [
        { de: 'Wenn ich reich **wäre**, **würde** ich reisen.', translation: l('If I were rich, I would travel.', 'Zengin olsaydım seyahat ederdim.', '') },
        { de: 'Wenn ich Zeit **hätte**, **käme** ich mit.', translation: l('If I had time, I would come along.', 'Vaktim olsaydı gelirdim.', '') },
        { de: 'Wenn wir fliegen **könnten**, …', translation: l('If we could fly, …', 'Uçabilseydik …', '') },
        { de: 'Dann **müsste** ich nicht arbeiten.', translation: l('Then I wouldn’t have to work.', 'O zaman çalışmak zorunda olmazdım.', '') },
        { de: '**Ich wünschte**, es **wäre** Sommer.', translation: l('I wish it were summer.', 'Keşke yaz olsa.', '') },
        { de: 'Wenn ich **doch** mehr Zeit **hätte**!', translation: l('If only I had more time!', 'Keşke daha çok vaktim olsa!', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Real or imagined?', 'Gerçek mi hayal mi?', 'Real oder gedacht?'),
      exercises: ['sort-real', 'match-forms', 'k2-waere-ich', 'k2-haette-ich', 'mc-wuerde', 'tf-war-waere', 'select-irreal', 'image-traum', 'k2-wuerde-du'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about your dreams and wishes.', 'Hayallerinden ve dileklerinden bahset.', 'Sprich über deine Träume.'),
      exercises: [
        'fill-haette',
        'fill-waere-du',
        'fill-koennte',
        'build-wenn',
        'build-wuensche',
        'build-doch',
        'fix-wuerde-waere',
        'fix-hatte',
        'fix-wuerde-double',
        'tr-waere',
        'tr-wuensche',
        'ordering-k2',
        'dialog-lotto',
        'dialog-ratschlag',
        'k2-koennte-wir',
        'k2-waere-es',
        'k2-haette-er',
        'k2-muesste-ich',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A magazine survey: „What would you do with a million euros?“', 'Bir dergi anketi: „Bir milyon euroyla ne yapardınız?“', 'Umfrage: Was würden Sie mit einer Million machen?'),
      passage: [
        '**Lukas, 34:** Ich **würde** mit meiner Familie eine Weltreise **machen** – ein ganzes Jahr lang!',
        '**Maria, 41:** Geld ist nicht alles. **Ich wünschte**, ich **hätte** mehr Zeit für meine Kinder.',
        '**Herr Lange, 58:** Ich **würde** weiter **arbeiten** – meine Arbeit macht mir Spaß. Aber ich **würde** meinen Enkeln das Studium **bezahlen**.',
        '**Elif, 19:** Geld ist langweilig! Wenn ich eine Superkraft **hätte**, **würde** ich alle Sprachen der Welt sprechen **können**.',
      ],
      glossary: [
        { de: 'ein ganzes Jahr lang', note: l('for a whole year', 'koca bir yıl boyunca', '12 Monate') },
        { de: 'die Enkel', note: l('grandchildren', 'torunlar', 'Kinder der Kinder') },
        { de: 'die Superkraft', note: l('superpower', 'süper güç', 'wie ein Superheld') },
      ],
      exercises: ['read-umfrage', 'read-maria', 'read-arbeit', 'read-superkraft'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Dreams, wishes and polite requests.', 'Hayaller, dilekler ve kibar ricalar.', 'Träume, Wünsche, Bitten.'),
      exercises: ['listen-real', 'listen-wunsch', 'listen-insel', 'listen-koennte'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Answer three „What would you do if …?“ questions.', 'Üç „… olsaydı ne yapardın?“ sorusuna cevap ver.', 'Beantworte drei „Was würdest du machen, wenn …?“-Fragen.'),
      points: [
        l('… you won a million euros?', '… bir milyon euro kazansaydın?', '… eine Million gewinnen würdest?'),
        l('… you could live anywhere?', '… istediğin yerde yaşayabilseydin?', '… überall wohnen könntest?'),
        l('… you were the mayor of your city?', '… şehrinin belediye başkanı olsaydın?', '… Bürgermeister wärst?'),
        l('One wish: „Ich wünschte, …“', 'Bir dilek: „Ich wünschte, …“', 'Ich wünschte …'),
      ],
      model: [
        'Wenn ich eine Million gewinnen würde, würde ich zuerst meiner Familie helfen.',
        'Wenn ich überall wohnen könnte, würde ich in Lissabon leben.',
        'Wenn ich Bürgermeisterin wäre, gäbe es mehr Parks und Fahrradwege.',
        'Ich wünschte, ich hätte mehr Zeit für meine Hobbys.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short text (at least 5 sentences): „Mein Traumleben“ – what would be different?',
        'Kısa bir metin yaz (en az 5 cümle): „Mein Traumleben“ – ne farklı olurdu?',
        'Schreib einen Text (mindestens 5 Sätze): „Mein Traumleben“.'
      ),
      minSentences: 5,
      checks: [
        { label: l('wäre or hätte', 'wäre ya da hätte', 'wäre oder hätte'), pattern: '\\b(wäre|wärst|wären|hätte|hättest|hätten)\\b' },
        { label: l('würde + infinitive', 'würde + mastar', 'würde + Infinitiv'), pattern: '\\bwürde(st|n|t)?\\b[^.!?]*\\b\\p{Ll}+en[.!?]' },
        { label: l('A wenn-clause', 'Bir wenn-cümlesi', 'Ein wenn-Satz'), pattern: '\\b[Ww]enn\\b' },
        { label: l('könnte / müsste', 'könnte / müsste', 'könnte / müsste'), pattern: '\\b(könnte|müsste|dürfte)(st|n|t)?\\b' },
      ],
      model: [
        'Wenn ich mein Traumleben hätte, würde ich in einem Haus am Meer wohnen.',
        'Ich müsste nicht mehr jeden Tag ins Büro fahren.',
        'Morgens würde ich am Strand joggen.',
        'Am Nachmittag könnte ich Bücher schreiben.',
        'Das wäre wirklich perfekt!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Konjunktiv II forms – 60 seconds.', 'Konjunktiv II biçimleri – 60 saniye.', 'Konjunktiv II – 60 Sekunden.'),
      seconds: 60,
      pool: [...K2.map(([id]) => `k2-${id}`), 'mc-wuerde'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('wäre, hätte, könnte, müsste, würde + infinitive', 'wäre, hätte, könnte, müsste, würde + mastar', 'Konjunktiv II'),
      l('Wenn ich … wäre/hätte, würde ich …', 'Wenn ich … wäre/hätte, würde ich …', 'irreale Bedingung'),
      l('Wishes: Ich wünschte, … / Wenn … doch …!', 'Dilekler: Ich wünschte, … / Wenn … doch …!', 'Wünsche'),
    ],
    mistakes: [
      { wrong: 'Wenn ich reich war, …', right: 'Wenn ich reich wäre, …', note: l('Umlaut!', 'Umlaut!', 'wäre.') },
      { wrong: 'Wenn ich Zeit hätte, ich würde …', right: 'Wenn ich Zeit hätte, würde ich …', note: l('Verb, verb.', 'Fiil, fiil.', 'Verb, Verb.') },
      { wrong: 'Wenn ich reich sein würde …', right: 'Wenn ich reich wäre …', note: l('sein → wäre.', 'sein → wäre.', 'wäre.') },
      { wrong: 'Ich wünschte, ich habe mehr Zeit.', right: 'Ich wünschte, ich hätte mehr Zeit.', note: l('Wish → Konjunktiv II.', 'Dilek → Konjunktiv II.', 'hätte.') },
    ],
  },
}
