import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Umwelt', emoji: '🌍', translation: l('environment', 'çevre', 'Natur um uns'), example: 'Wir müssen die Umwelt schützen.' },
  { word: 'der Klimawandel', emoji: '🌡️', translation: l('climate change', 'iklim değişikliği', 'das Klima ändert sich'), example: 'Der Klimawandel ist ein großes Problem.' },
  { word: 'Müll trennen', emoji: '♻️', translation: l('to separate rubbish', 'çöpü ayırmak', 'Recycling'), example: 'In Deutschland trennt man den Müll.' },
  { word: 'Energie sparen', emoji: '💡', translation: l('to save energy', 'enerji tasarrufu yapmak', 'weniger Strom'), example: 'Man sollte Energie sparen.' },
  { word: 'die Plastiktüte', emoji: '🛍️', translation: l('plastic bag', 'plastik poşet', 'Tasche aus Plastik'), example: 'Ich benutze keine Plastiktüten mehr.' },
  { word: 'umweltfreundlich', emoji: '🌱', translation: l('environmentally friendly', 'çevre dostu', 'gut für die Natur'), example: 'Fahrradfahren ist umweltfreundlich.' },
  { word: 'die Verschmutzung', emoji: '🏭', translation: l('pollution', 'kirlilik', 'schmutzige Luft / Wasser'), example: 'Die Luftverschmutzung in Städten ist hoch.' },
  { word: 'erneuerbare Energien', emoji: '☀️', translation: l('renewable energies', 'yenilenebilir enerji', 'Sonne, Wind, Wasser'), example: 'Erneuerbare Energien werden immer wichtiger.' },
  { word: 'öffentliche Verkehrsmittel', emoji: '🚋', translation: l('public transport', 'toplu taşıma', 'Bus, Bahn'), example: 'Ich nutze öffentliche Verkehrsmittel.' },
  { word: 'Man sollte …', emoji: '👉', translation: l('One should …', '… -malı', 'Vorschlag'), example: 'Man sollte weniger Fleisch essen.' },
  { word: 'Es wäre gut, wenn …', emoji: '💭', translation: l('It would be good if …', '… olsa iyi olurdu', 'Vorschlag mit Konjunktiv II'), example: 'Es wäre gut, wenn alle weniger fliegen würden.' },
  { word: 'verbieten / verboten', emoji: '🚫', translation: l('to ban / banned', 'yasaklamak / yasak', 'nicht erlaubt'), example: 'Plastikstrohhalme sind in der EU verboten.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Umwelt', gender: 'f', translation: l('environment', 'çevre', 'Umwelt') },
  { word: 'Klimawandel', gender: 'm', translation: l('climate change', 'iklim değişikliği', 'Klimawandel') },
  { word: 'Müll', gender: 'm', translation: l('rubbish', 'çöp', 'Müll') },
  { word: 'Energie', gender: 'f', plural: 'die Energien', translation: l('energy', 'enerji', 'Energie') },
  { word: 'Plastik', gender: 'n', translation: l('plastic', 'plastik', 'Plastik') },
  { word: 'Luft', gender: 'f', translation: l('air', 'hava', 'Luft') },
  { word: 'Strom', gender: 'm', translation: l('electricity', 'elektrik', 'Strom') },
  { word: 'Flasche', gender: 'f', plural: 'die Flaschen', translation: l('bottle', 'şişe', 'Flasche') },
]

/** [id, item, bin, wrong bins] – German recycling */
const BINS: [string, string, string, [string, string]][] = [
  ['zeitung', 'Wohin kommt eine alte Zeitung?', 'Papiermüll (blaue Tonne)', ['Biomüll (braune Tonne)', 'Restmüll (schwarze Tonne)']],
  ['joghurt', 'Wohin kommt ein leerer Joghurtbecher?', 'Gelber Sack / Gelbe Tonne', ['Papiermüll (blaue Tonne)', 'Glascontainer']],
  ['bananen', 'Wohin kommt eine Bananenschale?', 'Biomüll (braune Tonne)', ['Gelber Sack / Gelbe Tonne', 'Glascontainer']],
  ['glas', 'Wohin kommt ein leeres Marmeladenglas?', 'Glascontainer', ['Restmüll (schwarze Tonne)', 'Papiermüll (blaue Tonne)']],
  ['batterie', 'Wohin kommen alte Batterien?', 'Sammelstelle im Supermarkt', ['Restmüll (schwarze Tonne)', 'Biomüll (braune Tonne)']],
]

function binDrills(): Exercise[] {
  return BINS.map(([id, question, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `muell-${id}`,
      type: 'multiple_choice' as const,
      topic: 'muell',
      concept: 'recycling',
      skill: 'vocabulary' as const,
      difficulty: 1 as const,
      prompt: question,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`→ ${right}.`, `→ ${right}.`, `→ ${right}.`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-umwelt',
    type: 'matching',
    topic: 'umwelt-wortschatz',
    concept: 'env-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match word and symbol.', 'Kelimeyi sembolle eşleştir.', 'Ordne Wort und Symbol zu.'),
    pairs: [
      { left: 'Müll trennen', right: '♻️' },
      { left: 'Energie sparen', right: '💡' },
      { left: 'der Klimawandel', right: '🌡️' },
      { left: 'erneuerbare Energien', right: '☀️' },
      { left: 'öffentliche Verkehrsmittel', right: '🚋' },
    ],
    explanation: l('Basic environmental vocabulary.', 'Temel çevre kelimeleri.', 'Umweltwortschatz.'),
  },
  {
    id: 'sort-gut-schlecht',
    type: 'categorize',
    topic: 'umwelt-wortschatz',
    concept: 'eco-behaviour',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Good or bad for the environment?', 'Çevre için iyi mi kötü mü?', 'Gut oder schlecht für die Umwelt?'),
    categories: ['gut 🌱', 'schlecht 🏭'],
    items: [
      { text: 'mit dem Fahrrad fahren', category: 0 },
      { text: 'jeden Tag Fleisch essen', category: 1 },
      { text: 'regionale Produkte kaufen', category: 0 },
      { text: 'oft fliegen', category: 1 },
      { text: 'Licht ausmachen', category: 0 },
      { text: 'Plastiktüten benutzen', category: 1 },
    ],
    explanation: l('Typical eco-friendly and not-so-friendly habits.', 'Tipik çevre dostu ve pek dost olmayan alışkanlıklar.', 'umweltfreundlich oder nicht.'),
    practice: ['muell-zeitung'],
  },
  {
    id: 'mc-sollte',
    type: 'multiple_choice',
    topic: 'vorschlaege',
    concept: 'man-sollte',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Man ___ öfter mit dem Fahrrad fahren.',
    options: ['sollte', 'sollten', 'solltest'],
    answer: 0,
    explanation: l('man + sollte (like er/sie/es).', 'man + sollte (er/sie/es gibi).', 'man sollte.'),
    examples: ['Man **sollte** öfter mit dem Fahrrad fahren.'],
    practice: ['fill-waere'],
  },
  {
    id: 'tf-passiv',
    type: 'true_false',
    topic: 'passiv-sachtext',
    concept: 'passive-recognize',
    skill: 'grammar',
    difficulty: 2,
    statement: '„In Deutschland wird der Müll getrennt.“ ist ein Passivsatz.',
    answer: true,
    explanation: l('wird + getrennt = passive. In factual texts the passive is very common.', 'wird + getrennt = edilgen. Bilgi metinlerinde edilgen çok yaygındır.', 'Passiv.'),
  },
  {
    id: 'select-vorschlag',
    type: 'multiple_select',
    topic: 'vorschlaege',
    concept: 'suggestions',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are suggestions? Select all.', 'Hangi cümleler öneri? Hepsini seç.', 'Welche Sätze sind Vorschläge?'),
    options: ['Man sollte weniger Auto fahren.', 'Es wäre gut, wenn es mehr Radwege gäbe.', 'Gestern bin ich Rad gefahren.', 'Wie wäre es mit einem autofreien Sonntag?', 'Das Auto ist rot.'],
    answers: [0, 1, 3],
    explanation: l('Suggestions: Man sollte …, Es wäre gut, wenn …, Wie wäre es mit …?', 'Öneriler: Man sollte …, Es wäre gut, wenn …, Wie wäre es mit …?', 'Vorschläge.'),
  },
  {
    id: 'image-pfand',
    type: 'image_choice',
    topic: 'muell',
    concept: 'pfand',
    skill: 'vocabulary',
    difficulty: 2,
    prompt: 'Für diese Flaschen bekommt man Pfand zurück.',
    options: [
      { emoji: '🍾', label: 'Pfandflaschen' },
      { emoji: '🍌', label: 'Bananenschale' },
      { emoji: '📰', label: 'Zeitung' },
      { emoji: '🔋', label: 'Batterie' },
    ],
    answer: 0,
    explanation: l('das Pfand = deposit: you get money back for bottles.', 'das Pfand = depozito: şişeler için para geri alırsın.', 'Pfand.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-waere',
    type: 'fill_blank',
    topic: 'vorschlaege',
    concept: 'es-waere-gut',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Es ___ gut, wenn die Busse öfter fahren würden.',
    accepted: ['wäre'],
    base: 'sein → Konjunktiv II',
    explanation: l('Suggestion: Es wäre gut, wenn …', 'Öneri: Es wäre gut, wenn …', 'Es wäre gut …'),
    examples: ['Es **wäre** gut, wenn die Busse öfter fahren würden.'],
  },
  {
    id: 'fill-getrennt',
    type: 'fill_blank',
    topic: 'passiv-sachtext',
    concept: 'passive-form',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Glas wird nach Farben ___. (trennen)',
    accepted: ['getrennt'],
    base: 'trennen',
    explanation: l('Passive: wird + getrennt.', 'Edilgen: wird + getrennt.', 'getrennt.'),
    examples: ['Glas wird nach Farben **getrennt**.'],
  },
  {
    id: 'fill-sparen',
    type: 'fill_blank',
    topic: 'umwelt-wortschatz',
    concept: 'env-words',
    skill: 'vocabulary',
    difficulty: 1,
    sentence: 'Wenn man das Licht ausmacht, kann man Energie ___.',
    accepted: ['sparen'],
    base: 'Energie …',
    explanation: l('Energie sparen = to save energy.', 'Energie sparen = enerji tasarrufu.', 'sparen.'),
    examples: ['… kann man Energie **sparen**.'],
  },
  {
    id: 'build-sollte',
    type: 'sentence_builder',
    topic: 'vorschlaege',
    concept: 'man-sollte',
    skill: 'grammar',
    difficulty: 2,
    chips: ['kaufen', 'regionale Produkte', 'sollte', 'Man'],
    answers: [['Man', 'sollte', 'regionale Produkte', 'kaufen']],
    translation: l('One should buy regional products.', 'Yöresel ürünler alınmalı.', 'Man sollte regionale Produkte kaufen.'),
    explanation: l('man sollte + infinitive at the end.', 'man sollte + sonda mastar.', 'Man sollte … kaufen.'),
    examples: ['Man **sollte** regionale Produkte **kaufen**.'],
  },
  {
    id: 'build-waere',
    type: 'sentence_builder',
    topic: 'vorschlaege',
    concept: 'es-waere-gut',
    skill: 'grammar',
    difficulty: 3,
    chips: ['gäbe', 'wenn', 'Es wäre schön,', 'es', 'mehr Radwege'],
    answers: [['Es wäre schön,', 'wenn', 'es', 'mehr Radwege', 'gäbe']],
    translation: l('It would be nice if there were more cycle paths.', 'Daha fazla bisiklet yolu olsa güzel olurdu.', 'Es wäre schön, wenn es mehr Radwege gäbe.'),
    explanation: l('es gibt → es gäbe (Konjunktiv II), verb at the end.', 'es gibt → es gäbe (Konjunktiv II), fiil sonda.', '… mehr Radwege gäbe.'),
    examples: ['Es wäre schön, wenn es mehr Radwege **gäbe**.'],
  },
  {
    id: 'build-passiv',
    type: 'sentence_builder',
    topic: 'passiv-sachtext',
    concept: 'passive-form',
    skill: 'grammar',
    difficulty: 2,
    chips: ['recycelt', 'werden', 'In Deutschland', 'viele Flaschen'],
    answers: [['In Deutschland', 'werden', 'viele Flaschen', 'recycelt']],
    translation: l('In Germany many bottles are recycled.', 'Almanya’da birçok şişe geri dönüştürülüyor.', 'In Deutschland werden viele Flaschen recycelt.'),
    explanation: l('Passive plural: werden … recycelt.', 'Çoğul edilgen: werden … recycelt.', 'werden … recycelt.'),
    examples: ['In Deutschland **werden** viele Flaschen **recycelt**.'],
  },
  {
    id: 'fix-sollten',
    type: 'error_correction',
    topic: 'vorschlaege',
    concept: 'man-sollte',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Man sollten weniger fliegen.',
    accepted: ['Man sollte weniger fliegen.'],
    explanation: l('man → sollte (singular).', 'man → sollte (tekil).', 'man sollte.'),
    examples: ['Man **sollte** weniger fliegen.'],
  },
  {
    id: 'fix-wenn',
    type: 'error_correction',
    topic: 'vorschlaege',
    concept: 'es-waere-gut',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Es wäre gut, wenn mehr Leute würden Rad fahren.',
    accepted: ['Es wäre gut, wenn mehr Leute Rad fahren würden.'],
    explanation: l('wenn → verb at the very end: … Rad fahren würden.', 'wenn → fiil en sonda: … Rad fahren würden.', '… fahren würden.'),
    examples: ['…, wenn mehr Leute Rad **fahren würden**.'],
  },
  {
    id: 'fix-umwelt',
    type: 'error_correction',
    topic: 'umwelt-wortschatz',
    concept: 'env-words',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Wir müssen die Umwelt schützt.',
    accepted: ['Wir müssen die Umwelt schützen.'],
    explanation: l('müssen + infinitive: schützen.', 'müssen + mastar: schützen.', 'schützen.'),
    examples: ['Wir müssen die Umwelt **schützen**.'],
  },
  {
    id: 'tr-sollte',
    type: 'translation',
    topic: 'vorschlaege',
    concept: 'man-sollte',
    skill: 'writing',
    difficulty: 2,
    source: l('One should separate rubbish.', 'Çöp ayrıştırılmalı.', 'One should separate rubbish.'),
    accepted: ['Man sollte den Müll trennen.', 'Man sollte Müll trennen.'],
    explanation: l('Man sollte … trennen.', 'Man sollte … trennen.', 'Man sollte … trennen.'),
    examples: ['Man **sollte** den Müll **trennen**.'],
  },
  {
    id: 'tr-umweltfreundlich',
    type: 'translation',
    topic: 'umwelt-wortschatz',
    concept: 'env-words',
    skill: 'writing',
    difficulty: 2,
    source: l('Cycling is environmentally friendly.', 'Bisiklet sürmek çevre dostudur.', 'Cycling is environmentally friendly.'),
    accepted: ['Fahrradfahren ist umweltfreundlich.', 'Radfahren ist umweltfreundlich.', 'Rad fahren ist umweltfreundlich.'],
    explanation: l('umweltfreundlich = eco-friendly.', 'umweltfreundlich = çevre dostu.', 'umweltfreundlich.'),
    examples: ['Fahrradfahren ist **umweltfreundlich**.'],
  },
  {
    id: 'ordering-argument',
    type: 'ordering',
    topic: 'vorschlaege',
    concept: 'argument',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('Build a short argument: problem → reason → suggestion → result.', 'Kısa bir argüman kur: sorun → sebep → öneri → sonuç.', 'Problem → Grund → Vorschlag → Ergebnis.'),
    items: ['Deshalb sollte man öfter Bus und Bahn nehmen.', 'Die Luft in vielen Städten ist schlecht.', 'So würde die Luft wieder sauberer werden.', 'Ein Grund dafür ist der viele Autoverkehr.'],
    answer: ['Die Luft in vielen Städten ist schlecht.', 'Ein Grund dafür ist der viele Autoverkehr.', 'Deshalb sollte man öfter Bus und Bahn nehmen.', 'So würde die Luft wieder sauberer werden.'],
    explanation: l('Problem → reason → suggestion → result.', 'Sorun → sebep → öneri → sonuç.', 'Struktur einer Argumentation.'),
  },
  {
    id: 'dialog-vorschlag',
    type: 'dialogue',
    topic: 'vorschlaege',
    concept: 'suggestions',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollege', de: 'Was können wir im Büro für die Umwelt tun?' }],
    options: ['Wie wäre es, wenn wir weniger drucken würden?', 'Wir drucken alles zweimal.', 'Die Umwelt ist im Büro.'],
    answer: 0,
    explanation: l('Suggestion: Wie wäre es, wenn …?', 'Öneri: Wie wäre es, wenn …?', 'Wie wäre es …?'),
  },
  {
    id: 'dialog-meinung',
    type: 'dialogue',
    topic: 'vorschlaege',
    concept: 'opinion-env',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freundin', de: 'Findest du, dass man Inlandsflüge verbieten sollte?' }],
    options: ['Ich finde, es wäre sinnvoll, weil der Zug oft genauso schnell ist.', 'Ich finde, verbieten Flug Zug.', 'Ja, ich fliege.'],
    answer: 0,
    explanation: l('Opinion + reason with Konjunktiv II.', 'Fikir + Konjunktiv II ile sebep.', 'Meinung + Grund.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-problem',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worüber schreibt der Artikel?',
    options: ['Über Plastikmüll im Meer.', 'Über Luftverschmutzung.', 'Über teure Lebensmittel.'],
    answer: 0,
    explanation: l('„Jedes Jahr landen Millionen Tonnen Plastik im Meer.“', '„Jedes Jahr landen Millionen Tonnen Plastik im Meer.“', 'Plastik im Meer.'),
  },
  {
    id: 'read-tiere',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was passiert mit den Tieren?',
    options: ['Viele Tiere fressen das Plastik.', 'Die Tiere sammeln das Plastik.', 'Nichts.'],
    answer: 0,
    explanation: l('„Viele Fische und Vögel fressen das Plastik und werden krank.“', '„Viele Fische und Vögel fressen das Plastik und werden krank.“', 'fressen Plastik.'),
  },
  {
    id: 'read-eu',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    statement: 'In der EU sind manche Plastikprodukte verboten.',
    answer: true,
    explanation: l('„Seit 2021 sind in der EU zum Beispiel Plastikstrohhalme verboten.“', '„Seit 2021 sind in der EU zum Beispiel Plastikstrohhalme verboten.“', 'ja.'),
  },
  {
    id: 'read-tipp',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-artikel',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was schlägt der Artikel vor?',
    options: ['Eigene Taschen und Flaschen benutzen.', 'Mehr Plastik kaufen.', 'Nicht mehr ans Meer fahren.'],
    answer: 0,
    explanation: l('„Jeder sollte eigene Taschen und Flaschen benutzen.“', '„Jeder sollte eigene Taschen und Flaschen benutzen.“', 'eigene Taschen.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-tipp',
    type: 'listening_choice',
    topic: 'vorschlaege',
    concept: 'man-sollte',
    skill: 'listening',
    difficulty: 1,
    audio: 'Man sollte beim Zähneputzen das Wasser abdrehen. So spart man viel Wasser.',
    question: l('What should you do?', 'Ne yapmalısın?', 'Was sollte man machen?'),
    options: ['turn off the water', 'brush less', 'buy bottled water'],
    answer: 0,
    explanation: l('„das Wasser abdrehen“', '„das Wasser abdrehen“', 'Wasser abdrehen.'),
  },
  {
    id: 'listen-muell',
    type: 'listening_choice',
    topic: 'muell',
    concept: 'recycling',
    skill: 'listening',
    difficulty: 2,
    audio: 'Verpackungen aus Plastik gehören in den gelben Sack, Essensreste in die Biotonne.',
    question: l('Where do food leftovers go?', 'Yemek artıkları nereye gider?', 'Wohin kommen Essensreste?'),
    options: ['organic bin', 'yellow bag', 'paper bin'],
    answer: 0,
    explanation: l('„Essensreste in die Biotonne“', '„Essensreste in die Biotonne“', 'Biotonne.'),
  },
  {
    id: 'listen-waere',
    type: 'listening_choice',
    topic: 'vorschlaege',
    concept: 'es-waere-gut',
    skill: 'listening',
    difficulty: 2,
    audio: 'Es wäre toll, wenn die Stadt mehr Bäume pflanzen würde.',
    question: l('What does the speaker wish for?', 'Konuşmacı ne diliyor?', 'Was wünscht sich die Person?'),
    options: ['more trees', 'more cars', 'more shops'],
    answer: 0,
    explanation: l('„mehr Bäume pflanzen“', '„mehr Bäume pflanzen“', 'mehr Bäume.'),
  },
  {
    id: 'listen-passiv',
    type: 'listening_choice',
    topic: 'passiv-sachtext',
    concept: 'passive-recognize',
    skill: 'listening',
    difficulty: 2,
    audio: 'In unserer Stadt wird der Strom zu achtzig Prozent aus Sonne und Wind gewonnen.',
    question: l('Where does most of the electricity come from?', 'Elektriğin çoğu nereden geliyor?', 'Woher kommt der meiste Strom?'),
    options: ['sun and wind', 'coal', 'nuclear power'],
    answer: 0,
    explanation: l('„aus Sonne und Wind“', '„aus Sonne und Wind“', 'Sonne und Wind.'),
  },

  ...binDrills(),
]

export const UNIT_B1_18_UMWELT: CourseUnit = {
  level: 'B1',
  number: 18,
  slug: 'umwelt',
  titleDe: 'Umwelt und Klima',
  title: l('Environment and climate', 'Çevre ve iklim', 'Umwelt und Klima'),
  goal: l(
    'By the end of this unit you can talk about environmental problems, understand factual texts in the passive, separate rubbish the German way and make suggestions: Man sollte …, Es wäre gut, wenn …',
    'Bu ünitenin sonunda çevre sorunlarından bahsedebilir, edilgen çatılı bilgi metinlerini anlayabilir, çöpü Alman usulü ayırabilir ve önerilerde bulunabilirsin: Man sollte …, Es wäre gut, wenn …',
    'Am Ende dieser Einheit sprichst du über Umwelt und machst Vorschläge.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'umwelt-wortschatz', label: l('Environment vocabulary', 'Çevre kelimeleri', 'Umweltwortschatz') },
    { key: 'muell', label: l('Recycling in Germany', 'Almanya’da geri dönüşüm', 'Mülltrennung') },
    { key: 'vorschlaege', label: l('Suggestions', 'Öneriler', 'Vorschläge') },
    { key: 'passiv-sachtext', label: l('Passive in texts', 'Metinlerde edilgen', 'Passiv in Sachtexten') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Words for talking about our planet.', 'Gezegenimiz hakkında konuşmak için kelimeler.', 'Wörter für unseren Planeten.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Making suggestions', 'Önerilerde bulunmak', 'Vorschläge machen'),
          body: l(
            'Man sollte … (one should) – Es wäre gut/sinnvoll, wenn … würde/gäbe (it would be good if …) – Wie wäre es mit …? / Wie wäre es, wenn …? – Wir könnten …',
            'Man sollte … (… -malı) – Es wäre gut/sinnvoll, wenn … würde/gäbe (… olsa iyi olurdu) – Wie wäre es mit …? / Wie wäre es, wenn …? – Wir könnten …',
            'Man sollte … · Es wäre gut, wenn …'
          ),
          examples: [
            { de: 'Man **sollte** weniger Fleisch **essen**.', translation: l('One should eat less meat.', 'Daha az et yenmeli.', '') },
            { de: 'Es **wäre** gut, wenn es mehr Radwege **gäbe**.', translation: l('It would be good if there were more cycle paths.', 'Daha fazla bisiklet yolu olsa iyi olurdu.', '') },
          ],
        },
        {
          title: l('Passive in factual texts', 'Bilgi metinlerinde edilgen', 'Passiv in Sachtexten'),
          body: l(
            'Newspaper and information texts often use the passive (Unit 03–04): Der Müll wird getrennt. Plastik wurde verboten. Die Umwelt muss geschützt werden.',
            'Gazete ve bilgi metinleri sık sık edilgen kullanır (Ünite 03–04): Der Müll wird getrennt. Plastik wurde verboten. Die Umwelt muss geschützt werden.',
            'wird/wurde/muss … werden.'
          ),
        },
        {
          title: l('Recycling in Germany', 'Almanya’da geri dönüşüm', 'Mülltrennung in Deutschland'),
          body: l(
            'Gelber Sack/Gelbe Tonne: packaging (plastic, cans). Blaue Tonne: paper. Braune Tonne: organic waste. Glascontainer: glass (by colour). Schwarze Tonne: everything else. Pfand: deposit on bottles.',
            'Gelber Sack/Gelbe Tonne: ambalaj (plastik, kutu). Blaue Tonne: kâğıt. Braune Tonne: organik atık. Glascontainer: cam (renge göre). Schwarze Tonne: geri kalan her şey. Pfand: şişe depozitosu.',
            'Gelb, Blau, Braun, Glas, Schwarz.'
          ),
          table: {
            head: [l('Bin', 'Çöp kutusu', 'Tonne'), l('What goes in', 'Ne atılır', 'Was kommt rein?')],
            rows: [
              ['Gelbe Tonne', 'Plastik, Dosen, Verpackungen'],
              ['Blaue Tonne', 'Papier, Karton'],
              ['Braune Tonne', 'Obst, Gemüse, Essensreste'],
              ['Glascontainer', 'Gläser, Flaschen (ohne Pfand)'],
              ['Schwarze Tonne', 'Restmüll'],
            ],
          },
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('A neighbour explains recycling to Amir, who has just moved in.', 'Bir komşu yeni taşınan Amir’e geri dönüşümü anlatıyor.', 'Mülltrennung für Neue.'),
      dialogue: [
        { speaker: 'Amir', de: 'Entschuldigung, wohin kommt eigentlich der Joghurtbecher?', translation: l('Excuse me, where does the yoghurt pot actually go?', 'Affedersiniz, yoğurt kabı aslında nereye atılıyor?', '') },
        { speaker: 'Frau Huber', de: 'In die **gelbe Tonne**. Hier **wird** der Müll genau **getrennt**!', translation: l('In the yellow bin. Here rubbish is separated carefully!', 'Sarı kutuya. Burada çöp çok dikkatli ayrıştırılıyor!', '') },
        { speaker: 'Amir', de: 'Und die Bananenschale?', translation: l('And the banana peel?', 'Peki muz kabuğu?', '') },
        { speaker: 'Frau Huber', de: 'Die kommt in die **Biotonne**. Und Flaschen mit **Pfand** bringen Sie zurück in den Supermarkt.', translation: l('That goes in the organic bin. And you take deposit bottles back to the supermarket.', 'O organik çöpe gidiyor. Depozitolu şişeleri de süpermarkete geri götürüyorsunuz.', '') },
        { speaker: 'Amir', de: 'Das ist kompliziert, aber gut für die **Umwelt**. Bei uns **sollte man** das auch machen.', translation: l('That’s complicated, but good for the environment. People should do that back home too.', 'Karmaşık ama çevre için iyi. Bizde de bunu yapmak lazım.', '') },
        { speaker: 'Frau Huber', de: 'Genau! **Es wäre** schön, **wenn** alle so mitmachen **würden**.', translation: l('Exactly! It would be nice if everybody joined in like that.', 'Aynen! Herkes böyle katılsa güzel olurdu.', '') },
      ],
      examples: [
        { de: 'Wir müssen die **Umwelt** schützen.', translation: l('We must protect the environment.', 'Çevreyi korumalıyız.', '') },
        { de: 'Der Müll **wird getrennt**.', translation: l('Rubbish is separated.', 'Çöp ayrıştırılıyor.', '') },
        { de: 'Man **sollte** Energie **sparen**.', translation: l('One should save energy.', 'Enerji tasarrufu yapılmalı.', '') },
        { de: 'Es **wäre** gut, wenn weniger Leute **fliegen würden**.', translation: l('It would be good if fewer people flew.', 'Daha az insan uçsa iyi olurdu.', '') },
        { de: 'Fahrradfahren ist **umweltfreundlich**.', translation: l('Cycling is eco-friendly.', 'Bisiklet sürmek çevre dostu.', '') },
        { de: 'Plastiktüten **wurden verboten**.', translation: l('Plastic bags were banned.', 'Plastik poşetler yasaklandı.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Environment words, recycling and suggestions.', 'Çevre kelimeleri, geri dönüşüm ve öneriler.', 'Umwelt, Mülltrennung, Vorschläge.'),
      exercises: ['match-umwelt', 'sort-gut-schlecht', 'muell-zeitung', 'muell-bananen', 'mc-sollte', 'tf-passiv', 'select-vorschlag', 'image-pfand', 'muell-glas'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Make suggestions for a greener life.', 'Daha yeşil bir yaşam için önerilerde bulun.', 'Mach Vorschläge.'),
      exercises: [
        'fill-waere',
        'fill-getrennt',
        'fill-sparen',
        'build-sollte',
        'build-waere',
        'build-passiv',
        'fix-sollten',
        'fix-wenn',
        'fix-umwelt',
        'tr-sollte',
        'tr-umweltfreundlich',
        'ordering-argument',
        'dialog-vorschlag',
        'dialog-meinung',
        'muell-joghurt',
        'muell-batterie',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A short newspaper article about plastic.', 'Plastik hakkında kısa bir gazete makalesi.', 'Ein Zeitungsartikel über Plastik.'),
      passage: [
        '**Plastik im Meer** – Jedes Jahr landen Millionen Tonnen Plastik im Meer.',
        'Viele Fische und Vögel fressen das Plastik und werden krank. Ein Teil davon **wird** sogar von Menschen **gegessen** – über den Fisch.',
        'Seit 2021 **sind** in der EU zum Beispiel Plastikstrohhalme und Plastikteller **verboten**.',
        'Aber auch jeder Einzelne kann etwas tun: Jeder **sollte** eigene Taschen und Flaschen **benutzen**. **Es wäre** gut, **wenn** wir alle weniger Verpackung kaufen **würden**.',
      ],
      glossary: [
        { de: 'landen', note: l('to end up', 'son bulmak, varmak', 'ankommen') },
        { de: 'fressen', note: l('to eat (animals)', 'yemek (hayvanlar)', 'essen (Tiere)') },
        { de: 'der Strohhalm', note: l('straw', 'pipet', 'zum Trinken') },
        { de: 'jeder Einzelne', note: l('every individual', 'her birey', 'jede Person') },
      ],
      exercises: ['read-problem', 'read-tiere', 'read-eu', 'read-tipp'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Tips, recycling and wishes.', 'İpuçları, geri dönüşüm ve dilekler.', 'Tipps, Mülltrennung, Wünsche.'),
      exercises: ['listen-tipp', 'listen-muell', 'listen-waere', 'listen-passiv'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('What do you do for the environment – and what should change in your city?', 'Çevre için ne yapıyorsun – ve şehrinde ne değişmeli?', 'Was tust du für die Umwelt?'),
      points: [
        l('Your habits: „Ich trenne …, ich fahre …“', 'Alışkanlıkların: „Ich trenne …, ich fahre …“', 'Gewohnheiten'),
        l('A problem: „In meiner Stadt ist … ein Problem.“', 'Bir sorun: „In meiner Stadt ist … ein Problem.“', 'Problem'),
        l('A suggestion: „Man sollte …“', 'Bir öneri: „Man sollte …“', 'Man sollte …'),
        l('A wish: „Es wäre gut, wenn …“', 'Bir dilek: „Es wäre gut, wenn …“', 'Es wäre gut …'),
      ],
      model: [
        'Ich trenne meinen Müll und kaufe oft auf dem Markt ein.',
        'In meiner Stadt ist der Verkehr ein großes Problem.',
        'Man sollte die Busse billiger machen.',
        'Es wäre gut, wenn es mehr sichere Radwege gäbe.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a forum post (at least 5 sentences): „What can everyone do for the environment?“',
        'Bir forum yazısı yaz (en az 5 cümle): „Herkes çevre için ne yapabilir?“',
        'Schreib einen Forumsbeitrag (mindestens 5 Sätze): Was kann jeder für die Umwelt tun?'
      ),
      minSentences: 5,
      checks: [
        { label: l('Man sollte …', 'Man sollte …', 'Man sollte …'), pattern: '\\b[Mm]an sollte\\b' },
        { label: l('Es wäre gut/sinnvoll, wenn …', 'Es wäre gut/sinnvoll, wenn …', 'Es wäre …, wenn'), pattern: '[Ee]s wäre \\p{Ll}+, wenn' },
        { label: l('An environment word (Umwelt, Müll, Energie, Plastik …)', 'Bir çevre kelimesi (Umwelt, Müll, Energie, Plastik …)', 'Umweltwort'), pattern: '(Umwelt|Müll|Energie|Plastik|Klima|Strom|Verpackung)' },
      ],
      model: [
        'Ich finde, dass jeder etwas für die Umwelt tun kann.',
        'Man sollte zum Beispiel den Müll richtig trennen.',
        'Außerdem kann man Energie sparen, wenn man das Licht ausmacht.',
        'Es wäre gut, wenn mehr Menschen mit dem Fahrrad fahren würden.',
        'Und beim Einkaufen sollte man weniger Plastik kaufen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Which bin? – 60 seconds.', 'Hangi kutu? – 60 saniye.', 'Welche Tonne? – 60 Sekunden.'),
      seconds: 60,
      pool: [...BINS.map(([id]) => `muell-${id}`), 'mc-sollte'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Environment: Umwelt, Klimawandel, Müll trennen, Energie sparen', 'Çevre: Umwelt, Klimawandel, Müll trennen, Energie sparen', 'Umweltwortschatz'),
      l('Recycling: gelbe / blaue / braune Tonne, Glas, Pfand', 'Geri dönüşüm: gelbe / blaue / braune Tonne, Glas, Pfand', 'Mülltrennung'),
      l('Suggestions: Man sollte … · Es wäre gut, wenn … · Wie wäre es mit …?', 'Öneriler: Man sollte … · Es wäre gut, wenn … · Wie wäre es mit …?', 'Vorschläge'),
      l('Passive in texts: wird getrennt, wurde verboten', 'Metinlerde edilgen: wird getrennt, wurde verboten', 'Passiv'),
    ],
    mistakes: [
      { wrong: 'Man sollten …', right: 'Man sollte …', note: l('man → singular.', 'man → tekil.', 'sollte.') },
      { wrong: 'Es wäre gut, wenn mehr Leute würden Rad fahren.', right: 'Es wäre gut, wenn mehr Leute Rad fahren würden.', note: l('Verb at the end.', 'Fiil sonda.', 'Verb am Ende.') },
      { wrong: 'Wir müssen die Umwelt schützt.', right: 'Wir müssen die Umwelt schützen.', note: l('Infinitive.', 'Mastar.', 'Infinitiv.') },
      { wrong: 'Der Joghurtbecher kommt in die Biotonne.', right: 'Der Joghurtbecher kommt in die gelbe Tonne.', note: l('Packaging → yellow.', 'Ambalaj → sarı.', 'gelbe Tonne.') },
    ],
  },
}
