import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'die Gesellschaft', emoji: '👥', translation: l('society', 'toplum', 'alle Menschen zusammen'), example: 'Unsere Gesellschaft wird immer älter.' },
  { word: 'sich engagieren', emoji: '🙋', translation: l('to get involved', 'gönüllü olarak katılmak', 'aktiv mithelfen'), example: 'Sie engagiert sich im Sportverein.' },
  { word: 'ehrenamtlich', emoji: '🤲', translation: l('voluntary, unpaid', 'gönüllü', 'ohne Geld'), example: 'Er arbeitet ehrenamtlich bei der Tafel.' },
  { word: 'der Verein', emoji: '⚽', translation: l('club, association', 'dernek, kulüp', 'Gruppe mit gleichem Hobby'), example: 'In Deutschland gibt es über 600.000 Vereine.' },
  { word: 'die Tradition', emoji: '🎎', translation: l('tradition', 'gelenek', 'Brauch'), example: 'Das ist eine alte Tradition.' },
  { word: 'feiern', emoji: '🎉', translation: l('to celebrate', 'kutlamak', 'ein Fest machen'), example: 'Wie feiert man bei euch Neujahr?' },
  { word: 'die Gleichberechtigung', emoji: '⚖️', translation: l('equal rights', 'eşitlik', 'gleiche Rechte'), example: 'Gleichberechtigung ist im Grundgesetz garantiert.' },
  { word: 'die Integration', emoji: '🤝', translation: l('integration', 'uyum, entegrasyon', 'Teil der Gesellschaft werden'), example: 'Sprache ist wichtig für die Integration.' },
  { word: 'im Vergleich zu', emoji: '🔁', translation: l('compared to', '… ile karşılaştırıldığında', 'verglichen mit'), example: 'Im Vergleich zu meinem Land ist alles pünktlicher.' },
  { word: 'während (Kontrast)', emoji: '↔️', translation: l('whereas', '… iken', 'Gegensatz'), example: 'Während man in Deutschland Geschenke am 24. öffnet, macht man das bei uns am 25.' },
  { word: 'unterstützen', emoji: '🫶', translation: l('to support', 'desteklemek', 'helfen'), example: 'Der Verein unterstützt alte Menschen.' },
  { word: 'die Vielfalt', emoji: '🌈', translation: l('diversity', 'çeşitlilik', 'viele verschiedene'), example: 'Die kulturelle Vielfalt in Berlin ist groß.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Ehrenamt', gender: 'n', plural: 'die Ehrenämter', translation: l('volunteer work', 'gönüllü iş', 'Ehrenamt') },
  { word: 'Brauch', gender: 'm', plural: 'die Bräuche', translation: l('custom', 'adet', 'Brauch') },
  { word: 'Fest', gender: 'n', plural: 'die Feste', translation: l('festival, party', 'bayram, kutlama', 'Fest') },
  { word: 'Unterschied', gender: 'm', plural: 'die Unterschiede', translation: l('difference', 'fark', 'Unterschied') },
  { word: 'Gemeinsamkeit', gender: 'f', plural: 'die Gemeinsamkeiten', translation: l('thing in common', 'ortak nokta', 'Gemeinsamkeit') },
  { word: 'Rentner', gender: 'm', plural: 'die Rentner', translation: l('pensioner', 'emekli', 'Rentner') },
  { word: 'Generation', gender: 'f', plural: 'die Generationen', translation: l('generation', 'kuşak', 'Generation') },
  { word: 'Recht', gender: 'n', plural: 'die Rechte', translation: l('right', 'hak', 'Recht') },
]

/** [id, festival question, right, wrong] */
const FESTE: [string, string, string, [string, string]][] = [
  ['advent', 'Was macht man in Deutschland im Advent?', 'Man zündet jeden Sonntag eine Kerze am Adventskranz an.', ['Man färbt Eier.', 'Man trägt Kostüme auf der Straße.']],
  ['ostern', 'Was suchen Kinder an Ostern?', 'Bunte Eier und Schokolade.', ['Einen Weihnachtsbaum.', 'Kürbisse.']],
  ['karneval', 'Was passiert beim Karneval in Köln?', 'Man verkleidet sich und feiert auf der Straße.', ['Man bleibt still zu Hause.', 'Man fastet einen Monat.']],
  ['silvester', 'Wie feiert man Silvester?', 'Mit Feuerwerk um Mitternacht.', ['Mit Ostereiern.', 'Mit einem Laternenumzug.']],
  ['martin', 'Was machen Kinder am Martinstag?', 'Sie gehen mit Laternen durch die Straßen.', ['Sie bekommen Zeugnisse.', 'Sie feiern Geburtstag.']],
]

function festDrills(): Exercise[] {
  return FESTE.map(([id, question, right, wrong], i) => {
    const options = [right, ...wrong]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `fest-${id}`,
      type: 'multiple_choice' as const,
      topic: 'traditionen',
      concept: 'german-festivals',
      skill: 'reading' as const,
      difficulty: 1 as const,
      prompt: question,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`→ ${right}`, `→ ${right}`, `→ ${right}`),
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-gesellschaft',
    type: 'matching',
    topic: 'ehrenamt',
    concept: 'society-words',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match German and meaning.', 'Almancayı anlamıyla eşleştir.', 'Ordne zu.'),
    pairs: [
      { left: 'ehrenamtlich', right: 'voluntary' },
      { left: 'der Verein', right: 'club' },
      { left: 'unterstützen', right: 'to support' },
      { left: 'die Vielfalt', right: 'diversity' },
      { left: 'die Gesellschaft', right: 'society' },
    ],
    explanation: l('Words about society.', 'Toplumla ilgili kelimeler.', 'Gesellschaft.'),
  },
  {
    id: 'sort-gleich-anders',
    type: 'categorize',
    topic: 'vergleichen',
    concept: 'compare-phrases',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Similarity or difference?', 'Benzerlik mi fark mı?', 'Gemeinsamkeit oder Unterschied?'),
    categories: ['Gemeinsamkeit =', 'Unterschied ≠'],
    items: [
      { text: 'genauso wie', category: 0 },
      { text: 'im Gegensatz zu', category: 1 },
      { text: 'ähnlich wie', category: 0 },
      { text: 'während …, …', category: 1 },
      { text: 'auch bei uns', category: 0 },
      { text: 'ganz anders als', category: 1 },
    ],
    explanation: l('Phrases for comparing cultures.', 'Kültürleri karşılaştırma kalıpları.', 'Vergleichen.'),
    practice: ['fest-advent'],
  },
  {
    id: 'mc-engagiert',
    type: 'multiple_choice',
    topic: 'ehrenamt',
    concept: 'sich-engagieren',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Mein Bruder engagiert ___ in einem Tierheim.',
    options: ['sich', 'ihn', 'ihm'],
    answer: 0,
    explanation: l('sich engagieren is reflexive: er engagiert sich.', 'sich engagieren dönüşlüdür: er engagiert sich.', 'sich.'),
    examples: ['Mein Bruder engagiert **sich** in einem Tierheim.'],
    practice: ['fill-fuer'],
  },
  {
    id: 'tf-waehrend',
    type: 'true_false',
    topic: 'vergleichen',
    concept: 'waehrend-contrast',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Während“ kann einen Gegensatz ausdrücken. Das Verb steht dann am Ende des Nebensatzes.',
    answer: true,
    explanation: l('Während man hier früh isst, isst man bei uns spät. → verb at the end.', 'Während man hier früh isst, isst man bei uns spät. → fiil sonda.', 'Nebensatz.'),
  },
  {
    id: 'select-ehrenamt',
    type: 'multiple_select',
    topic: 'ehrenamt',
    concept: 'volunteering',
    skill: 'vocabulary',
    difficulty: 2,
    promptL10n: l('Which activities are volunteer work? Select all.', 'Hangi etkinlikler gönüllü iş? Hepsini seç.', 'Was ist ein Ehrenamt?'),
    options: ['bei der Freiwilligen Feuerwehr helfen', 'Kindern kostenlos Nachhilfe geben', 'im Supermarkt als Kassierer arbeiten', 'Senioren im Altenheim besuchen', 'als Arzt im Krankenhaus arbeiten'],
    answers: [0, 1, 3],
    explanation: l('Ehrenamt = unpaid work for others.', 'Ehrenamt = başkaları için ücretsiz iş.', 'unbezahlt.'),
  },
  {
    id: 'image-tafel',
    type: 'image_choice',
    topic: 'ehrenamt',
    concept: 'volunteering',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Bei der Tafel verteilen Ehrenamtliche Lebensmittel an Menschen mit wenig Geld.',
    options: [
      { emoji: '🥫', label: 'Lebensmittel verteilen' },
      { emoji: '🎸', label: 'Musik machen' },
      { emoji: '🏊', label: 'schwimmen' },
      { emoji: '💻', label: 'programmieren' },
    ],
    answer: 0,
    explanation: l('die Tafel = food bank.', 'die Tafel = gıda bankası.', 'Tafel.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-fuer',
    type: 'fill_blank',
    topic: 'ehrenamt',
    concept: 'sich-engagieren',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Sie engagiert sich ___ den Umweltschutz.',
    accepted: ['für'],
    base: 'sich engagieren …',
    explanation: l('sich engagieren für + accusative.', 'sich engagieren für + Akk.', 'für.'),
    examples: ['Sie engagiert sich **für** den Umweltschutz.'],
  },
  {
    id: 'fill-vergleich',
    type: 'fill_blank',
    topic: 'vergleichen',
    concept: 'compare-phrases',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Im ___ zu Spanien isst man in Deutschland früh zu Abend.',
    accepted: ['Vergleich'],
    base: 'compared to',
    explanation: l('Im Vergleich zu …', 'Im Vergleich zu …', 'Vergleich.'),
    examples: ['Im **Vergleich** zu Spanien isst man in Deutschland früh.'],
  },
  {
    id: 'fill-waehrend',
    type: 'fill_blank',
    topic: 'vergleichen',
    concept: 'waehrend-contrast',
    skill: 'grammar',
    difficulty: 3,
    sentence: '___ man in Deutschland „Prost“ sagt, sagt man in der Türkei „Şerefe“.',
    accepted: ['Während'],
    base: 'Gegensatz',
    explanation: l('Während = whereas (contrast).', 'Während = … iken (karşıtlık).', 'Während.'),
    examples: ['**Während** man in Deutschland „Prost“ sagt, …'],
  },
  {
    id: 'build-waehrend',
    type: 'sentence_builder',
    topic: 'vergleichen',
    concept: 'waehrend-contrast',
    skill: 'grammar',
    difficulty: 3,
    chips: ['feiert man bei uns', 'Während man hier Weihnachten', 'feiert,', 'eher Neujahr'],
    answers: [['Während man hier Weihnachten', 'feiert,', 'feiert man bei uns', 'eher Neujahr']],
    translation: l('Whereas people here celebrate Christmas, we celebrate New Year more.', 'Burada Noel kutlanırken bizde daha çok yılbaşı kutlanır.', 'Während man hier Weihnachten feiert, feiert man bei uns eher Neujahr.'),
    explanation: l('Subordinate clause first → main clause starts with the verb.', 'Önce yan cümle → ana cümle fiille başlar.', 'Verb – Komma – Verb.'),
    examples: ['Während man hier Weihnachten **feiert**, **feiert** man bei uns eher Neujahr.'],
  },
  {
    id: 'build-verein',
    type: 'sentence_builder',
    topic: 'ehrenamt',
    concept: 'volunteering',
    skill: 'grammar',
    difficulty: 2,
    chips: ['seit zwei Jahren', 'ehrenamtlich', 'Ich trainiere', 'eine Kindermannschaft'],
    answers: [['Ich trainiere', 'seit zwei Jahren', 'ehrenamtlich', 'eine Kindermannschaft']],
    translation: l('I’ve been coaching a children’s team as a volunteer for two years.', 'İki yıldır gönüllü olarak bir çocuk takımını çalıştırıyorum.', 'Ich trainiere seit zwei Jahren ehrenamtlich eine Kindermannschaft.'),
    explanation: l('Time – manner – object (TeKaMoLo).', 'Zaman – biçim – nesne (TeKaMoLo).', 'TeKaMoLo.'),
    examples: ['Ich trainiere **seit zwei Jahren ehrenamtlich** eine Kindermannschaft.'],
  },
  {
    id: 'build-sowohl',
    type: 'sentence_builder',
    topic: 'argumente',
    concept: 'collect-arguments',
    skill: 'grammar',
    difficulty: 3,
    chips: ['als auch', 'Ein Ehrenamt hilft sowohl', 'den anderen', 'einem selbst'],
    answers: [['Ein Ehrenamt hilft sowohl', 'den anderen', 'als auch', 'einem selbst']],
    translation: l('Volunteering helps both others and yourself.', 'Gönüllülük hem başkalarına hem de kişinin kendisine yardımcı olur.', 'Ein Ehrenamt hilft sowohl den anderen als auch einem selbst.'),
    explanation: l('sowohl … als auch (Unit 14).', 'sowohl … als auch (Ünite 14).', 'sowohl … als auch.'),
    examples: ['Ein Ehrenamt hilft **sowohl** den anderen **als auch** einem selbst.'],
  },
  {
    id: 'fix-engagiere',
    type: 'error_correction',
    topic: 'ehrenamt',
    concept: 'sich-engagieren',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich engagiere für Flüchtlinge.',
    accepted: ['Ich engagiere mich für Flüchtlinge.', 'Ich engagiere mich für Geflüchtete.'],
    explanation: l('Reflexive: ich engagiere mich.', 'Dönüşlü: ich engagiere mich.', 'mich.'),
    examples: ['Ich engagiere **mich** für Flüchtlinge.'],
  },
  {
    id: 'fix-waehrend',
    type: 'error_correction',
    topic: 'vergleichen',
    concept: 'waehrend-contrast',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Während die Deutschen pünktlich sind, wir kommen oft später.',
    accepted: ['Während die Deutschen pünktlich sind, kommen wir oft später.'],
    explanation: l('After the comma the main clause starts with the verb.', 'Virgülden sonra ana cümle fiille başlar.', 'kommen wir.'),
    examples: ['Während die Deutschen pünktlich sind, **kommen wir** oft später.'],
  },
  {
    id: 'fix-als',
    type: 'error_correction',
    topic: 'vergleichen',
    concept: 'compare-phrases',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Bei uns ist das Familienleben ganz anders wie hier.',
    accepted: ['Bei uns ist das Familienleben ganz anders als hier.'],
    explanation: l('anders als (not wie).', 'anders als (wie değil).', 'anders als.'),
    examples: ['… ganz anders **als** hier.'],
  },
  {
    id: 'tr-verein',
    type: 'translation',
    topic: 'ehrenamt',
    concept: 'volunteering',
    skill: 'writing',
    difficulty: 2,
    source: l('I am a member of a sports club.', 'Bir spor kulübünün üyesiyim.', 'I am a member of a sports club.'),
    accepted: ['Ich bin Mitglied in einem Sportverein.', 'Ich bin Mitglied eines Sportvereins.', 'Ich bin in einem Sportverein.'],
    explanation: l('Mitglied in einem Verein.', 'Mitglied in einem Verein.', 'Mitglied.'),
    examples: ['Ich bin **Mitglied** in einem Sportverein.'],
  },
  {
    id: 'tr-tradition',
    type: 'translation',
    topic: 'traditionen',
    concept: 'traditions',
    skill: 'writing',
    difficulty: 2,
    source: l('In my country we celebrate Ramadan Feast.', 'Benim ülkemde Ramazan Bayramı kutlanır.', 'In my country we celebrate the Ramadan Feast.'),
    accepted: ['In meinem Land feiern wir das Zuckerfest.', 'In meinem Land feiert man das Zuckerfest.', 'In meinem Land feiern wir Ramadan.', 'In meinem Land feiern wir das Ramadanfest.'],
    explanation: l('In meinem Land feiern wir … (inversion after In meinem Land).', 'In meinem Land feiern wir … (In meinem Land’dan sonra devrik).', 'feiern wir.'),
    examples: ['In meinem Land **feiern wir** das Zuckerfest.'],
  },
  {
    id: 'ordering-pro-contra',
    type: 'ordering',
    topic: 'argumente',
    concept: 'collect-arguments',
    skill: 'writing',
    difficulty: 3,
    promptL10n: l('Order a short pro/contra text: question → pro → contra → own opinion.', 'Kısa bir artı/eksi metni sırala: soru → artı → eksi → kendi fikri.', 'Frage → Pro → Contra → Meinung.'),
    items: ['Andererseits haben viele Menschen dafür keine Zeit.', 'Sollte ein soziales Jahr für alle Pflicht sein?', 'Ich finde deshalb, dass es freiwillig bleiben sollte.', 'Einerseits lernen junge Leute dabei viel fürs Leben.'],
    answer: ['Sollte ein soziales Jahr für alle Pflicht sein?', 'Einerseits lernen junge Leute dabei viel fürs Leben.', 'Andererseits haben viele Menschen dafür keine Zeit.', 'Ich finde deshalb, dass es freiwillig bleiben sollte.'],
    explanation: l('Question → pro → contra → own opinion.', 'Soru → artı → eksi → kendi fikri.', 'Erörterung.'),
  },
  {
    id: 'dialog-tradition',
    type: 'dialogue',
    topic: 'traditionen',
    concept: 'traditions',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Gibt es bei euch auch so etwas wie Weihnachten?' }],
    options: ['Nicht genau, aber wir haben das Zuckerfest. Da besuchen wir die ganze Familie.', 'Ja, Weihnachten ist im Dezember.', 'Nein, wir haben keine Gesellschaft.'],
    answer: 0,
    explanation: l('Compare and explain your own tradition.', 'Karşılaştır ve kendi geleneğini açıkla.', 'Vergleichen und erklären.'),
  },
  {
    id: 'dialog-mitmachen',
    type: 'dialogue',
    topic: 'ehrenamt',
    concept: 'volunteering',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Nachbar', de: 'Wir suchen noch Helfer für das Straßenfest am Samstag. Hast du Lust?' }],
    options: ['Gern! Was müsste ich denn machen?', 'Samstag ist ein Tag.', 'Ich bin ein Straßenfest.'],
    answer: 0,
    explanation: l('Accept and ask what to do.', 'Kabul et ve ne yapacağını sor.', 'Zusagen + nachfragen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-wer',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-portrait',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Was macht Gerda Brandt?',
    options: ['Sie hilft Migranten beim Deutschlernen.', 'Sie arbeitet als Lehrerin an einer Schule.', 'Sie leitet einen Sportverein.'],
    answer: 0,
    explanation: l('„… hilft sie Zugewanderten beim Deutschlernen.“', '„… hilft sie Zugewanderten beim Deutschlernen.“', 'Deutschlernen.'),
  },
  {
    id: 'read-geld',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-portrait',
    skill: 'reading',
    difficulty: 1,
    statement: 'Gerda bekommt für ihre Arbeit Geld.',
    answer: false,
    explanation: l('„… ehrenamtlich …“ = unpaid.', '„… ehrenamtlich …“ = ücretsiz.', 'falsch.'),
  },
  {
    id: 'read-warum',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-portrait',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum macht sie das?',
    options: ['Sie wollte nach der Rente etwas Sinnvolles tun.', 'Sie musste es machen.', 'Sie wollte Türkisch lernen.'],
    answer: 0,
    explanation: l('„Nach meiner Rente wollte ich etwas Sinnvolles tun.“', '„Nach meiner Rente wollte ich etwas Sinnvolles tun.“', 'sinnvoll.'),
  },
  {
    id: 'read-zurueck',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-portrait',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was bekommt Gerda zurück?',
    options: ['Neue Freundschaften und viel Dankbarkeit.', 'Einen Preis von der Stadt.', 'Einen bezahlten Job.'],
    answer: 0,
    explanation: l('„Ich bekomme so viel zurück: Freundschaften, Dankbarkeit …“', '„Ich bekomme so viel zurück: Freundschaften, Dankbarkeit …“', 'Freundschaften.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-feuerwehr',
    type: 'listening_choice',
    topic: 'ehrenamt',
    concept: 'volunteering',
    skill: 'listening',
    difficulty: 1,
    audio: 'In vielen Dörfern gibt es nur eine Freiwillige Feuerwehr. Die Feuerwehrleute arbeiten ehrenamtlich.',
    question: l('Who works in the volunteer fire brigade?', 'Gönüllü itfaiyede kim çalışır?', 'Wer arbeitet bei der Freiwilligen Feuerwehr?'),
    options: ['unpaid volunteers', 'only professionals', 'soldiers'],
    answer: 0,
    explanation: l('„ehrenamtlich“', '„ehrenamtlich“', 'ehrenamtlich.'),
  },
  {
    id: 'listen-vergleich',
    type: 'listening_choice',
    topic: 'vergleichen',
    concept: 'waehrend-contrast',
    skill: 'listening',
    difficulty: 2,
    audio: 'Während man in Deutschland Geburtstage nicht vorher feiert, ist das bei uns kein Problem.',
    question: l('What is the difference?', 'Fark ne?', 'Was ist der Unterschied?'),
    options: ['Celebrating birthdays early', 'The number of guests', 'Birthday presents'],
    answer: 0,
    explanation: l('In Germany you don’t celebrate a birthday before the day.', 'Almanya’da doğum günü önceden kutlanmaz.', 'nicht vorher feiern.'),
  },
  {
    id: 'listen-generation',
    type: 'listening_choice',
    topic: 'argumente',
    concept: 'society-topics',
    skill: 'listening',
    difficulty: 2,
    audio: 'In unserem Mehrgenerationenhaus wohnen Studenten und Rentner zusammen und helfen sich gegenseitig.',
    question: l('Who lives together?', 'Kimler birlikte yaşıyor?', 'Wer wohnt zusammen?'),
    options: ['students and pensioners', 'only families', 'only students'],
    answer: 0,
    explanation: l('„Studenten und Rentner“', '„Studenten und Rentner“', 'Jung und Alt.'),
  },
  {
    id: 'listen-gleich',
    type: 'listening_choice',
    topic: 'argumente',
    concept: 'society-topics',
    skill: 'listening',
    difficulty: 2,
    audio: 'Frauen verdienen in Deutschland im Durchschnitt immer noch etwa achtzehn Prozent weniger als Männer.',
    question: l('What is the topic?', 'Konu ne?', 'Was ist das Thema?'),
    options: ['the gender pay gap', 'unemployment', 'tax rates'],
    answer: 0,
    explanation: l('Women earn less than men → Gleichberechtigung.', 'Kadınlar erkeklerden az kazanıyor → eşitlik.', 'Gleichberechtigung.'),
  },

  ...festDrills(),
]

export const UNIT_B1_23_GESELLSCHAFT: CourseUnit = {
  level: 'B1',
  number: 23,
  slug: 'gesellschaft',
  titleDe: 'Gesellschaft und Zusammenleben',
  title: l('Society and living together', 'Toplum ve birlikte yaşam', 'Gesellschaft und Zusammenleben'),
  goal: l(
    'By the end of this unit you can talk about volunteering and clubs, compare traditions in Germany and your country (im Vergleich zu, während …), and collect pro and contra arguments on social topics.',
    'Bu ünitenin sonunda gönüllülük ve dernekler hakkında konuşabilir, Almanya ve kendi ülkendeki gelenekleri karşılaştırabilir (im Vergleich zu, während …) ve toplumsal konularda artı ve eksi argümanları toplayabilirsin.',
    'Am Ende dieser Einheit sprichst du über Ehrenamt und vergleichst Kulturen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'ehrenamt', label: l('Volunteering', 'Gönüllülük', 'Ehrenamt') },
    { key: 'traditionen', label: l('Traditions', 'Gelenekler', 'Traditionen') },
    { key: 'vergleichen', label: l('Comparing cultures', 'Kültürleri karşılaştırmak', 'Vergleichen') },
    { key: 'argumente', label: l('Social topics & arguments', 'Toplumsal konular & argümanlar', 'Argumente') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Living together in Germany.', 'Almanya’da birlikte yaşamak.', 'Zusammenleben in Deutschland.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Volunteering in Germany', 'Almanya’da gönüllülük', 'Ehrenamt in Deutschland'),
          body: l(
            'About one in three Germans volunteers: in sports clubs, the volunteer fire brigade, food banks (Tafel), with refugees or the elderly. Key verb: sich engagieren für + accusative.',
            'Yaklaşık her üç Almandan biri gönüllü çalışır: spor kulüplerinde, gönüllü itfaiyede, gıda bankalarında (Tafel), mültecilerle veya yaşlılarla. Temel fiil: sich engagieren für + Akk.',
            'sich engagieren für.'
          ),
          examples: [
            { de: 'Sie **engagiert sich für** den Tierschutz.', translation: l('She is involved in animal welfare.', 'Hayvan hakları için gönüllü çalışıyor.', '') },
            { de: 'Er arbeitet **ehrenamtlich** bei der Tafel.', translation: l('He volunteers at the food bank.', 'Gıda bankasında gönüllü çalışıyor.', '') },
          ],
        },
        {
          title: l('Comparing cultures', 'Kültürleri karşılaştırmak', 'Kulturen vergleichen'),
          body: l(
            'Similarity: genauso wie, ähnlich wie, auch bei uns. Difference: anders als, im Gegensatz zu, im Vergleich zu. Contrast clause: während + verb at the end.',
            'Benzerlik: genauso wie, ähnlich wie, auch bei uns. Fark: anders als, im Gegensatz zu, im Vergleich zu. Karşıtlık cümlesi: während + fiil sonda.',
            'Gemeinsamkeiten und Unterschiede.'
          ),
          table: {
            head: [l('Phrase', 'Kalıp', 'Redemittel'), l('Example', 'Örnek', 'Beispiel')],
            rows: [
              ['genauso wie', 'Bei uns ist es genauso wie hier.'],
              ['anders als', 'Das ist anders als bei uns.'],
              ['im Gegensatz zu', 'im Gegensatz zu Deutschland'],
              ['während', 'Während man hier …, …'],
            ],
          },
        },
        {
          title: l('während: time or contrast', 'während: zaman ya da karşıtlık', 'während: Zeit oder Gegensatz'),
          body: l(
            'In Unit 10 während meant „while“ (at the same time). It can also mean „whereas“: Während es in Deutschland kalt ist, ist es bei uns warm. The verb goes to the end in both cases.',
            'Ünite 10’da während „-iken“ (aynı anda) anlamındaydı. „Oysa, … iken“ anlamına da gelebilir: Während es in Deutschland kalt ist, ist es bei uns warm. İki durumda da fiil sona gider.',
            'während = Gegensatz.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('At a neighbourhood festival Selin talks to her neighbour Klaus.', 'Mahalle şenliğinde Selin komşusu Klaus ile konuşuyor.', 'Beim Nachbarschaftsfest.'),
      dialogue: [
        { speaker: 'Klaus', de: 'Schön, dass du da bist! Das ganze Fest organisieren wir **ehrenamtlich**.', translation: l('Great that you’re here! We organise the whole festival as volunteers.', 'Gelmen çok güzel! Bütün şenliği gönüllü olarak düzenliyoruz.', '') },
        { speaker: 'Selin', de: 'Toll! Bist du in einem **Verein**?', translation: l('Great! Are you in a club?', 'Harika! Bir dernekte misin?', '') },
        { speaker: 'Klaus', de: 'Ja, im Bürgerverein. Wir **engagieren uns für** die Nachbarschaft.', translation: l('Yes, in the residents’ association. We’re committed to the neighbourhood.', 'Evet, mahalle derneğinde. Mahalle için çalışıyoruz.', '') },
        { speaker: 'Selin', de: '**Im Vergleich zu** meiner Heimat ist hier alles so organisiert! **Während** man bei uns einfach spontan **feiert**, plant man hier alles.', translation: l('Compared to my home country everything is so organised here! Whereas we just celebrate spontaneously, here everything is planned.', 'Memleketime kıyasla burada her şey çok düzenli! Bizde öylece kendiliğinden kutlanırken burada her şey planlanıyor.', '') },
        { speaker: 'Klaus', de: '(lacht) Das stimmt. Aber das Essen teilen wir **genauso wie** ihr.', translation: l('(laughs) That’s true. But we share the food just like you do.', '(güler) Doğru. Ama yemeği tıpkı sizin gibi paylaşıyoruz.', '') },
        { speaker: 'Selin', de: 'Dann bringe ich nächstes Jahr Börek mit – und helfe beim Aufbau!', translation: l('Then next year I’ll bring börek – and help set up!', 'O zaman seneye börek getiririm – kurulumda da yardım ederim!', '') },
      ],
      examples: [
        { de: 'Er **engagiert sich** im Sportverein.', translation: l('He is active in the sports club.', 'Spor kulübünde aktif.', '') },
        { de: 'Sie hilft **ehrenamtlich** im Altenheim.', translation: l('She volunteers at the care home.', 'Huzurevinde gönüllü yardım ediyor.', '') },
        { de: '**Im Vergleich zu** Italien isst man hier früh.', translation: l('Compared to Italy people eat early here.', 'İtalya’ya kıyasla burada erken yemek yeniyor.', '') },
        { de: '**Während** man hier Geschenke am 24. **öffnet**, …', translation: l('Whereas people here open presents on the 24th, …', 'Burada hediyeler 24’ünde açılırken …', '') },
        { de: 'Bei uns ist das **ganz anders als** hier.', translation: l('With us it’s completely different from here.', 'Bizde bu buradan çok farklı.', '') },
        { de: 'Die **Vielfalt** in der Stadt gefällt mir.', translation: l('I like the diversity in the city.', 'Şehirdeki çeşitliliği seviyorum.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Volunteering, festivals and comparisons.', 'Gönüllülük, bayramlar ve karşılaştırmalar.', 'Ehrenamt, Feste, Vergleiche.'),
      exercises: ['match-gesellschaft', 'sort-gleich-anders', 'fest-advent', 'fest-ostern', 'mc-engagiert', 'tf-waehrend', 'select-ehrenamt', 'image-tafel', 'fest-karneval'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Compare, explain and argue.', 'Karşılaştır, açıkla ve tartış.', 'Vergleichen und argumentieren.'),
      exercises: [
        'fill-fuer',
        'fill-vergleich',
        'fill-waehrend',
        'build-waehrend',
        'build-verein',
        'build-sowohl',
        'fix-engagiere',
        'fix-waehrend',
        'fix-als',
        'tr-verein',
        'tr-tradition',
        'ordering-pro-contra',
        'dialog-tradition',
        'dialog-mitmachen',
        'fest-silvester',
        'fest-martin',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A portrait from the local newspaper.', 'Yerel gazeteden bir portre.', 'Ein Porträt.'),
      passage: [
        '**Gerda Brandt, 71, Sprachpatin** – Seit fünf Jahren hilft sie Zugewanderten beim Deutschlernen. Jeden Dienstag trifft sie sich mit zwei Frauen aus Syrien und Afghanistan.',
        'Sie macht das **ehrenamtlich**, also ohne Geld. „Nach meiner Rente wollte ich etwas Sinnvolles tun“, erzählt sie.',
        '**Während** ihre Freundinnen reisen oder im Garten arbeiten, übt sie mit ihren „Schülerinnen“ Arztgespräche oder Briefe an Ämter.',
        '„Ich bekomme so viel zurück: Freundschaften, Dankbarkeit – und ich habe sogar gelernt, wie man Baklava macht!“',
      ],
      glossary: [
        { de: 'die Sprachpatin', note: l('language mentor', 'dil mentoru', 'hilft beim Sprachenlernen') },
        { de: 'Zugewanderte', note: l('immigrants', 'göçmenler', 'Menschen aus anderen Ländern') },
        { de: 'sinnvoll', note: l('meaningful', 'anlamlı', 'mit Sinn') },
        { de: 'das Amt', note: l('public office', 'resmî daire', 'Behörde') },
      ],
      exercises: ['read-wer', 'read-geld', 'read-warum', 'read-zurueck'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Clubs, customs and society.', 'Dernekler, adetler ve toplum.', 'Vereine, Bräuche, Gesellschaft.'),
      exercises: ['listen-feuerwehr', 'listen-vergleich', 'listen-generation', 'listen-gleich'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Compare a festival or tradition from your country with Germany.', 'Ülkendeki bir bayram veya geleneği Almanya ile karşılaştır.', 'Vergleiche ein Fest.'),
      points: [
        l('Name the festival and when it is.', 'Bayramın adını ve ne zaman olduğunu söyle.', 'Was, wann?'),
        l('What people do.', 'İnsanların ne yaptığını anlat.', 'Was macht man?'),
        l('A similarity: „genauso wie …“', 'Bir benzerlik: „genauso wie …“', 'Gemeinsamkeit'),
        l('A difference: „Während …, …“', 'Bir fark: „Während …, …“', 'Unterschied'),
      ],
      model: [
        'In der Türkei feiern wir das Zuckerfest am Ende des Ramadan.',
        'Wir besuchen die ganze Familie, und die Kinder bekommen Süßigkeiten.',
        'Das ist genauso wie Weihnachten hier – die Familie ist am wichtigsten.',
        'Während man hier Geschenke unter den Baum legt, küssen wir den Älteren die Hand.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write a short text (at least 5 sentences): „Should everyone do volunteer work?“ Give arguments for and against and your opinion.',
        'Kısa bir metin yaz (en az 5 cümle): „Herkes gönüllü çalışmalı mı?“ Artı ve eksi argümanlar ve kendi fikrini yaz.',
        'Sollte jeder ein Ehrenamt haben? (mindestens 5 Sätze)'
      ),
      minSentences: 5,
      checks: [
        { label: l('Ehrenamt / ehrenamtlich / sich engagieren', 'Ehrenamt / ehrenamtlich / sich engagieren', 'Ehrenamt'), pattern: '([Ee]hrenamt|engagier)' },
        { label: l('Pro and contra (einerseits … andererseits / aber / jedoch)', 'Artı ve eksi (einerseits … andererseits / aber / jedoch)', 'Pro & Contra'), pattern: '([Aa]ndererseits|\\baber\\b|jedoch|[Tt]rotzdem)' },
        { label: l('Your opinion (Ich finde / Meiner Meinung nach)', 'Fikrin (Ich finde / Meiner Meinung nach)', 'Meinung'), pattern: '([Ii]ch finde|Meiner Meinung nach|[Ii]ch bin der Ansicht|[Ii]ch glaube)' },
      ],
      model: [
        'Viele Menschen in Deutschland arbeiten ehrenamtlich.',
        'Einerseits hilft ein Ehrenamt der Gesellschaft, und man lernt neue Leute kennen.',
        'Andererseits haben viele Menschen wegen Arbeit und Familie wenig Zeit.',
        'Meiner Meinung nach sollte ein Ehrenamt freiwillig bleiben.',
        'Trotzdem finde ich es schön, wenn man sich ein paar Stunden im Monat engagiert.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('German festivals – 60 seconds.', 'Alman bayramları – 60 saniye.', 'Feste in Deutschland – 60 Sekunden.'),
      seconds: 60,
      pool: [...FESTE.map(([id]) => `fest-${id}`), 'mc-engagiert'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Volunteering: Ehrenamt, ehrenamtlich, Verein, sich engagieren für', 'Gönüllülük: Ehrenamt, ehrenamtlich, Verein, sich engagieren für', 'Ehrenamt'),
      l('German festivals: Advent, Ostern, Karneval, Silvester, Martinstag', 'Alman bayramları: Advent, Ostern, Karneval, Silvester, Martinstag', 'Feste'),
      l('Comparing: genauso wie, anders als, im Vergleich zu, während', 'Karşılaştırma: genauso wie, anders als, im Vergleich zu, während', 'Vergleichen'),
      l('Pro / contra texts on social topics', 'Toplumsal konularda artı / eksi metinleri', 'Pro und Contra'),
    ],
    mistakes: [
      { wrong: 'Ich engagiere für Flüchtlinge.', right: 'Ich engagiere mich für Flüchtlinge.', note: l('Reflexive.', 'Dönüşlü.', 'mich.') },
      { wrong: 'Während …, wir kommen später.', right: 'Während …, kommen wir später.', note: l('Verb first after the comma.', 'Virgülden sonra önce fiil.', 'Verb zuerst.') },
      { wrong: 'anders wie hier', right: 'anders als hier', note: l('anders als.', 'anders als.', 'als.') },
      { wrong: 'In meinem Land wir feiern …', right: 'In meinem Land feiern wir …', note: l('Verb in position 2.', 'Fiil 2. konumda.', 'Position 2.') },
    ],
  },
}
