import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'dem ich helfe', emoji: '🤝', translation: l('whom I help (masc./neut. Dativ)', 'yardım ettiğim (eril/nötr Dativ)', 'Relativpronomen Dativ m/n'), example: 'Der Nachbar, dem ich helfe, ist 90.' },
  { word: 'der ich danke', emoji: '🙏', translation: l('whom I thank (fem. Dativ)', 'teşekkür ettiğim (dişil Dativ)', 'Relativpronomen Dativ f'), example: 'Die Ärztin, der ich danke, war super.' },
  { word: 'denen', emoji: '👥', translation: l('to whom (plural Dativ)', 'onlara (çoğul Dativ)', 'Relativpronomen Dativ Plural'), example: 'Die Freunde, denen ich schreibe, wohnen in Wien.' },
  { word: 'in der ich wohne', emoji: '🏙️', translation: l('in which I live', 'içinde yaşadığım', 'Präposition + Relativpronomen'), example: 'Die Stadt, in der ich wohne, ist klein.' },
  { word: 'mit dem ich arbeite', emoji: '💼', translation: l('with whom I work', 'birlikte çalıştığım', 'mit + Dativ'), example: 'Der Kollege, mit dem ich arbeite, ist nett.' },
  { word: 'für den ich …', emoji: '🎁', translation: l('for whom I … (Akk.)', 'kimin için … (Akk.)', 'für + Akkusativ'), example: 'Der Freund, für den ich das Geschenk kaufe, hat Geburtstag.' },
  { word: 'wo', emoji: '📍', translation: l('where (after places)', 'nerede (yerlerden sonra)', 'Relativadverb für Orte'), example: 'Das ist das Café, wo wir uns kennengelernt haben.' },
  { word: 'was', emoji: '❗', translation: l('what, which (after alles, etwas, das)', 'ne (alles, etwas, das sonrası)', 'nach alles, etwas, nichts, das'), example: 'Das ist alles, was ich weiß.' },
  { word: 'die Heimatstadt', emoji: '🏡', translation: l('home town', 'memleket', 'Stadt, aus der man kommt'), example: 'Meine Heimatstadt liegt am Meer.' },
  { word: 'sich erinnern an', emoji: '💭', translation: l('to remember', 'hatırlamak', 'nicht vergessen'), example: 'Das ist ein Tag, an den ich mich gern erinnere.' },
  { word: 'aufwachsen', emoji: '🌱', translation: l('to grow up', 'büyümek', 'als Kind leben'), example: 'Das Dorf, in dem ich aufgewachsen bin, ist klein.' },
  { word: 'vertrauen', emoji: '🫂', translation: l('to trust (+ Dativ)', 'güvenmek (+ Dativ)', 'glauben, dass jemand ehrlich ist'), example: 'Sie ist eine Person, der ich vertraue.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Stadt', gender: 'f', plural: 'die Städte', translation: l('city', 'şehir', 'Stadt') },
  { word: 'Café', gender: 'n', plural: 'die Cafés', translation: l('café', 'kafe', 'Café') },
  { word: 'Kollege', gender: 'm', plural: 'die Kollegen', translation: l('colleague', 'iş arkadaşı', 'Kollege') },
  { word: 'Freundin', gender: 'f', plural: 'die Freundinnen', translation: l('friend', 'arkadaş', 'Freundin') },
  { word: 'Haus', gender: 'n', plural: 'die Häuser', translation: l('house', 'ev', 'Haus') },
  { word: 'Firma', gender: 'f', plural: 'die Firmen', translation: l('company', 'şirket', 'Firma') },
  { word: 'Dorf', gender: 'n', plural: 'die Dörfer', translation: l('village', 'köy', 'Dorf') },
]

/** [id, sentence with ___, right pronoun, explanation key] */
const DAT_DRILLS: [string, string, string, string][] = [
  ['m', 'Der Nachbar, ___ ich manchmal helfe, ist schon 90 Jahre alt.', 'dem', 'helfen + Dativ, der Nachbar (m) → dem'],
  ['f', 'Die Lehrerin, ___ ich viel verdanke, geht in Rente.', 'der', 'verdanken + Dativ, die Lehrerin (f) → der'],
  ['n', 'Das Kind, ___ der Hund gehört, sucht ihn überall.', 'dem', 'gehören + Dativ, das Kind (n) → dem'],
  ['pl', 'Die Gäste, ___ das Essen nicht geschmeckt hat, haben sich beschwert.', 'denen', 'schmecken + Dativ, Plural → denen'],
  ['prep-f', 'Die Firma, bei ___ ich arbeite, ist in Hamburg.', 'der', 'bei + Dativ, die Firma (f) → der'],
  ['prep-m', 'Der Kollege, mit ___ ich das Büro teile, ist sehr ruhig.', 'dem', 'mit + Dativ, der Kollege (m) → dem'],
  ['prep-akk', 'Die Freundin, für ___ ich den Kuchen backe, hat heute Geburtstag.', 'die', 'für + Akkusativ, die Freundin (f) → die'],
  ['prep-pl', 'Das sind die Kollegen, von ___ ich dir erzählt habe.', 'denen', 'von + Dativ, Plural → denen'],
]

function datDrills(): Exercise[] {
  return DAT_DRILLS.map(([id, sentence, right, why], i) => {
    const pool = ['dem', 'der', 'denen', 'den', 'die'].filter((p) => p !== right)
    const near: Record<string, [string, string]> = {
      dem: ['den', 'der'],
      der: ['die', 'dem'],
      denen: ['den', 'die'],
      die: ['der', 'den'],
    }
    const options = [right, ...(near[right] ?? [pool[0], pool[1]])]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    return {
      id: `reldat-${id}`,
      type: 'multiple_choice' as const,
      topic: id.startsWith('prep') ? 'rel-praeposition' : 'rel-dativ',
      concept: `reldat-${id}`,
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(`${why}.`, `${why}.`, `${why}.`),
      examples: [sentence.replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-table',
    type: 'matching',
    topic: 'rel-dativ',
    concept: 'rel-dat-table',
    skill: 'grammar',
    difficulty: 2,
    instructions: l('Match noun and Dativ relative pronoun.', 'İsmi ve Dativ ilgi zamirini eşleştir.', 'Ordne Nomen und Relativpronomen im Dativ zu.'),
    pairs: [
      { left: 'der Mann, …', right: '… dem ich helfe' },
      { left: 'die Frau, …', right: '… der ich helfe' },
      { left: 'das Kind, …', right: '… dem ich helfe' },
      { left: 'die Leute, …', right: '… denen ich helfe' },
    ],
    explanation: l('Dativ: dem (m/n), der (f), denen (plural – not „den“!).', 'Dativ: dem (eril/nötr), der (dişil), denen (çoğul – „den“ değil!).', 'dem, der, dem, denen.'),
    practice: ['reldat-m', 'reldat-pl'],
  },
  {
    id: 'mc-denen',
    type: 'multiple_choice',
    topic: 'rel-dativ',
    concept: 'denen',
    skill: 'grammar',
    difficulty: 3,
    prompt: 'Das sind die Nachbarn, ___ wir unseren Schlüssel geben.',
    options: ['denen', 'den', 'die'],
    answer: 0,
    explanation: l('geben + Dativ (person), plural → denen. The article „den“ is NOT the relative pronoun here.', 'geben + Dativ (kişi), çoğul → denen. Artikel „den“ burada ilgi zamiri DEĞİLDİR.', 'Plural Dativ → denen.'),
    examples: ['…, **denen** wir unseren Schlüssel geben.'],
  },
  {
    id: 'sort-akk-dat',
    type: 'categorize',
    topic: 'rel-dativ',
    concept: 'rel-akk-or-dat',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('Which relative pronoun? (der Mann)', 'Hangi ilgi zamiri? (der Mann)', 'Welches Relativpronomen? (der Mann)'),
    categories: ['den', 'dem'],
    items: [
      { text: 'der Mann, ___ ich sehe', category: 0 },
      { text: 'der Mann, ___ ich helfe', category: 1 },
      { text: 'der Mann, ___ ich anrufe', category: 0 },
      { text: 'der Mann, ___ ich danke', category: 1 },
      { text: 'der Mann, für ___ ich arbeite', category: 0 },
      { text: 'der Mann, mit ___ ich spreche', category: 1 },
    ],
    explanation: l('The verb or preposition decides: sehen, anrufen, für → Akk (den). helfen, danken, mit → Dativ (dem).', 'Fiil ya da edat belirler: sehen, anrufen, für → Akk (den). helfen, danken, mit → Dativ (dem).', 'Verb/Präposition entscheidet.'),
  },
  {
    id: 'mc-wo',
    type: 'multiple_choice',
    topic: 'wo-was',
    concept: 'rel-wo',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das ist das Café, ___ wir uns zum ersten Mal getroffen haben.',
    options: ['wo', 'was', 'wer'],
    answer: 0,
    explanation: l('After a place you can use wo (= in dem).', 'Bir yerden sonra wo (= in dem) kullanılabilir.', 'Ort → wo / in dem.'),
    examples: ['Das ist das Café, **wo** (= in dem) wir uns getroffen haben.'],
  },
  {
    id: 'mc-was',
    type: 'multiple_choice',
    topic: 'wo-was',
    concept: 'rel-was',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Das ist alles, ___ ich weiß.',
    options: ['was', 'das', 'wo'],
    answer: 0,
    explanation: l('After alles, etwas, nichts, vieles, das → was.', 'alles, etwas, nichts, vieles, das sonrası → was.', 'alles, was …'),
    examples: ['Das ist alles, **was** ich weiß.'],
  },
  {
    id: 'tf-praep',
    type: 'true_false',
    topic: 'rel-praeposition',
    concept: 'prep-first',
    skill: 'grammar',
    difficulty: 2,
    statement: 'In „Die Stadt, in der ich wohne“ steht die Präposition vor dem Relativpronomen.',
    answer: true,
    explanation: l('The preposition comes first: in der, mit dem, für den. Never at the end like in English!', 'Edat önce gelir: in der, mit dem, für den. Asla İngilizcedeki gibi sonda değil!', 'Präposition zuerst.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-in-dem',
    type: 'fill_blank',
    topic: 'rel-praeposition',
    concept: 'reldat-prep-n',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das Dorf, in ___ ich aufgewachsen bin, hat nur 500 Einwohner.',
    accepted: ['dem'],
    base: 'das Dorf, in + Dativ',
    explanation: l('in (Wo?) + Dativ, das Dorf → dem.', 'in (Wo?) + Dativ, das Dorf → dem.', 'in dem.'),
    examples: ['Das Dorf, in **dem** ich aufgewachsen bin, …'],
  },
  {
    id: 'fill-der',
    type: 'fill_blank',
    topic: 'rel-dativ',
    concept: 'reldat-f',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Meine Schwester ist die Person, ___ ich am meisten vertraue.',
    accepted: ['der'],
    base: 'vertrauen + Dativ',
    explanation: l('vertrauen + Dativ, die Person (f) → der.', 'vertrauen + Dativ, die Person (dişil) → der.', 'der.'),
    examples: ['…, **der** ich am meisten vertraue.'],
  },
  {
    id: 'fill-was',
    type: 'fill_blank',
    topic: 'wo-was',
    concept: 'rel-was',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Gibt es etwas, ___ ich für dich tun kann?',
    accepted: ['was'],
    base: 'etwas',
    explanation: l('etwas → was.', 'etwas → was.', 'etwas, was …'),
    examples: ['Gibt es etwas, **was** ich für dich tun kann?'],
  },
  {
    id: 'build-mit-dem',
    type: 'sentence_builder',
    topic: 'rel-praeposition',
    concept: 'reldat-prep-m',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ich', 'mit dem', 'ist ein alter Freund', 'Der Mann,', 'gesprochen habe'],
    answers: [['Der Mann,', 'mit dem', 'ich', 'gesprochen habe', 'ist ein alter Freund']],
    translation: l('The man I spoke to is an old friend.', 'Konuştuğum adam eski bir arkadaş.', 'Der Mann, mit dem ich gesprochen habe, ist ein alter Freund.'),
    explanation: l('Preposition + relative pronoun at the start of the clause, verb at its end.', 'Edat + ilgi zamiri cümlenin başında, fiil sonunda.', 'mit dem … gesprochen habe.'),
    examples: ['Der Mann, **mit dem** ich gesprochen habe, ist ein alter Freund.'],
  },
  {
    id: 'build-an-den',
    type: 'sentence_builder',
    topic: 'rel-praeposition',
    concept: 'reldat-prep-akk',
    skill: 'grammar',
    difficulty: 3,
    chips: ['mich', 'an den', 'gern erinnere', 'ich', 'Das war ein Tag,'],
    answers: [['Das war ein Tag,', 'an den', 'ich', 'mich', 'gern erinnere']],
    translation: l('That was a day I like to remember.', 'Bu, hatırlamayı sevdiğim bir gündü.', 'Das war ein Tag, an den ich mich gern erinnere.'),
    explanation: l('sich erinnern an + Akkusativ → an den (der Tag).', 'sich erinnern an + Akkusativ → an den (der Tag).', 'an den.'),
    examples: ['Das war ein Tag, **an den** ich mich gern erinnere.'],
  },
  {
    id: 'build-denen',
    type: 'sentence_builder',
    topic: 'rel-dativ',
    concept: 'denen',
    skill: 'grammar',
    difficulty: 3,
    chips: ['geholfen hast', 'Wie heißen die Leute,', 'du', 'denen'],
    answers: [['Wie heißen die Leute,', 'denen', 'du', 'geholfen hast']],
    end: '?',
    translation: l('What are the names of the people you helped?', 'Yardım ettiğin insanların adları ne?', 'Wie heißen die Leute, denen du geholfen hast?'),
    explanation: l('helfen + Dativ, plural → denen.', 'helfen + Dativ, çoğul → denen.', 'denen.'),
    examples: ['Wie heißen die Leute, **denen** du geholfen hast?'],
  },
  {
    id: 'fix-den-denen',
    type: 'error_correction',
    topic: 'rel-dativ',
    concept: 'denen',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Die Kinder, den ich Nachhilfe gebe, sind sehr fleißig.',
    accepted: ['Die Kinder, denen ich Nachhilfe gebe, sind sehr fleißig.'],
    explanation: l('Plural Dativ relative pronoun = denen.', 'Çoğul Dativ ilgi zamiri = denen.', 'denen.'),
    examples: ['Die Kinder, **denen** ich Nachhilfe gebe, …'],
  },
  {
    id: 'fix-englisch',
    type: 'error_correction',
    topic: 'rel-praeposition',
    concept: 'prep-first',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das ist die Frau, die ich mit spreche.',
    accepted: ['Das ist die Frau, mit der ich spreche.'],
    explanation: l('Preposition first: mit der (not „die … mit“ as in English).', 'Edat önce: mit der (İngilizcedeki gibi „die … mit“ değil).', 'mit der.'),
    examples: ['Das ist die Frau, **mit der** ich spreche.'],
  },
  {
    id: 'fix-das-was',
    type: 'error_correction',
    topic: 'wo-was',
    concept: 'rel-was',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Das ist das Beste, das ich je gegessen habe.',
    accepted: ['Das ist das Beste, was ich je gegessen habe.'],
    explanation: l('After superlatives used as nouns (das Beste) → was.', 'İsim olarak kullanılan en üstünlüklerden sonra (das Beste) → was.', 'das Beste, was …'),
    examples: ['Das ist das Beste, **was** ich je gegessen habe.'],
  },
  {
    id: 'tr-in-der',
    type: 'translation',
    topic: 'rel-praeposition',
    concept: 'reldat-prep-f',
    skill: 'writing',
    difficulty: 3,
    source: l('The city I live in is very green.', 'Yaşadığım şehir çok yeşil.', 'The city I live in is very green.'),
    accepted: ['Die Stadt, in der ich wohne, ist sehr grün.', 'Die Stadt, in der ich lebe, ist sehr grün.'],
    explanation: l('in der (die Stadt, Dativ).', 'in der (die Stadt, Dativ).', 'in der ich wohne.'),
    examples: ['Die Stadt, **in der** ich wohne, ist sehr grün.'],
  },
  {
    id: 'tr-alles-was',
    type: 'translation',
    topic: 'wo-was',
    concept: 'rel-was',
    skill: 'writing',
    difficulty: 2,
    source: l('That’s all I need.', 'İhtiyacım olan tek şey bu.', 'That’s all I need.'),
    accepted: ['Das ist alles, was ich brauche.'],
    explanation: l('alles, was …', 'alles, was …', 'alles, was ich brauche.'),
    examples: ['Das ist alles, **was** ich brauche.'],
  },
  {
    id: 'ordering-rel',
    type: 'ordering',
    topic: 'rel-praeposition',
    concept: 'prep-first',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Build the relative clause.', 'İlgi cümlesini kur.', 'Bilde den Relativsatz.'),
    items: ['ich', 'arbeite', 'bei der', 'seit zwei Jahren'],
    answer: ['bei der', 'ich', 'seit zwei Jahren', 'arbeite'],
    explanation: l('preposition + pronoun – subject – … – verb.', 'edat + zamir – özne – … – fiil.', 'bei der ich seit zwei Jahren arbeite.'),
  },
  {
    id: 'dialog-heimat',
    type: 'dialogue',
    topic: 'rel-praeposition',
    concept: 'reldat-prep-n',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Kollegin', de: 'Woher kommst du eigentlich genau?' }],
    options: ['Aus einem kleinen Dorf, in dem es nur eine Straße gibt!', 'Aus einem kleinen Dorf, das ich wohne.', 'Aus einem kleinen Dorf, in das es nur eine Straße gibt.'],
    answer: 0,
    explanation: l('in (Wo?) + Dativ → in dem.', 'in (Wo?) + Dativ → in dem.', 'in dem.'),
  },
  {
    id: 'dialog-wer',
    type: 'dialogue',
    topic: 'rel-dativ',
    concept: 'reldat-m',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Freund', de: 'Wer ist Herr Klein?' }],
    options: ['Der Nachbar, dem ich immer die Post bringe.', 'Der Nachbar, den ich immer die Post bringe.', 'Der Nachbar, der ich immer die Post bringe.'],
    answer: 0,
    explanation: l('bringen + Dativ (person) → dem.', 'bringen + Dativ (kişi) → dem.', 'dem.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-stadt',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-heimat',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Wo ist Yasemin aufgewachsen?',
    options: ['In einer Stadt am Schwarzen Meer.', 'In Berlin.', 'In einem Dorf in den Bergen.'],
    answer: 0,
    explanation: l('„Trabzon, die Stadt, in der ich aufgewachsen bin, liegt am Schwarzen Meer.“', '„Trabzon, die Stadt, in der ich aufgewachsen bin, liegt am Schwarzen Meer.“', 'am Schwarzen Meer.'),
  },
  {
    id: 'read-oma',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-heimat',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wer ist die wichtigste Person in ihrer Kindheit?',
    options: ['Ihre Oma, der sie alles erzählen konnte.', 'Ihr Lehrer.', 'Ihre Schwester.'],
    answer: 0,
    explanation: l('„… meine Oma, der ich alles erzählen konnte.“', '„… meine Oma, der ich alles erzählen konnte.“', 'die Oma.'),
  },
  {
    id: 'read-markt',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-heimat',
    skill: 'reading',
    difficulty: 2,
    statement: 'Der Markt, auf dem sie mit ihrer Oma einkaufte, existiert nicht mehr.',
    answer: false,
    explanation: l('„Den Markt, auf dem wir … einkauften, gibt es immer noch.“', '„Den Markt, auf dem wir … einkauften, gibt es immer noch.“', 'gibt es noch.'),
  },
  {
    id: 'read-vermisst',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-heimat',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was vermisst sie in Deutschland am meisten?',
    options: ['Das Meer und den Tee, den man überall trinkt.', 'Das Wetter.', 'Ihre Arbeit.'],
    answer: 0,
    explanation: l('„Was ich hier am meisten vermisse, ist das Meer – und der Tee …“', '„Was ich hier am meisten vermisse, ist das Meer – und der Tee …“', 'Meer und Tee.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-mit-wem',
    type: 'listening_choice',
    topic: 'rel-praeposition',
    concept: 'reldat-prep-f',
    skill: 'listening',
    difficulty: 2,
    audio: 'Das ist die Kollegin, mit der ich jeden Morgen Kaffee trinke.',
    question: l('What do they do together?', 'Birlikte ne yapıyorlar?', 'Was machen sie zusammen?'),
    options: ['☕ drink coffee', '🏃 go jogging', '🚌 take the bus'],
    answer: 0,
    explanation: l('„mit der ich jeden Morgen Kaffee trinke“', '„mit der ich jeden Morgen Kaffee trinke“', 'Kaffee.'),
  },
  {
    id: 'listen-denen',
    type: 'listening_choice',
    topic: 'rel-dativ',
    concept: 'denen',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Touristen, denen ich den Weg erklärt habe, kamen aus Japan.',
    question: l('Which pronoun do you hear?', 'Hangi zamiri duyuyorsun?', 'Welches Pronomen hörst du?'),
    options: ['denen', 'den', 'die'],
    answer: 0,
    explanation: l('„denen ich den Weg erklärt habe“', '„denen ich den Weg erklärt habe“', 'denen.'),
  },
  {
    id: 'listen-wo',
    type: 'listening_choice',
    topic: 'wo-was',
    concept: 'rel-wo',
    skill: 'listening',
    difficulty: 1,
    audio: 'Das ist der Park, wo ich jeden Sonntag jogge.',
    question: l('What does the person do in the park?', 'Kişi parkta ne yapıyor?', 'Was macht die Person im Park?'),
    options: ['🏃', '📖', '🧺'],
    answer: 0,
    explanation: l('joggen 🏃.', 'koşu 🏃.', 'joggen.'),
  },
  {
    id: 'listen-was',
    type: 'listening_choice',
    topic: 'wo-was',
    concept: 'rel-was',
    skill: 'listening',
    difficulty: 2,
    audio: 'Es gibt nichts, was mich mehr ärgert als Unpünktlichkeit.',
    question: l('What annoys the person most?', 'Kişiyi en çok ne sinirlendiriyor?', 'Was ärgert die Person am meisten?'),
    options: ['unpunctuality', 'noise', 'bad food'],
    answer: 0,
    explanation: l('„Unpünktlichkeit“ = being late.', '„Unpünktlichkeit“ = geç kalmak.', 'Unpünktlichkeit.'),
  },

  ...datDrills(),
]

export const UNIT_B1_02_RELATIVSAETZE_DATIV: CourseUnit = {
  level: 'B1',
  number: 2,
  slug: 'relativsaetze-dativ',
  titleDe: 'Die Stadt, in der ich wohne',
  title: l('The city I live in', 'Yaşadığım şehir', 'Die Stadt, in der ich wohne'),
  goal: l(
    'By the end of this unit you can use relative clauses in the Dativ (dem, der, denen), with prepositions (in der, mit dem, für den) and with wo and was – to talk about places and people that are important to you.',
    'Bu ünitenin sonunda Dativ’de (dem, der, denen), edatlarla (in der, mit dem, für den) ve wo ile was ile ilgi cümleleri kurabilir, senin için önemli yerler ve insanlar hakkında konuşabilirsin.',
    'Am Ende dieser Einheit benutzt du Relativsätze im Dativ und mit Präpositionen.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'rel-dativ', label: l('dem, der, denen', 'dem, der, denen', 'Relativpronomen im Dativ') },
    { key: 'rel-praeposition', label: l('in der, mit dem …', 'in der, mit dem …', 'Präposition + Relativpronomen') },
    { key: 'wo-was', label: l('wo & was', 'wo ve was', 'wo & was') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Relative clauses for people and places that matter.', 'Önemli insanlar ve yerler için ilgi cümleleri.', 'Relativsätze für wichtige Menschen und Orte.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('All relative pronouns', 'Tüm ilgi zamirleri', 'Alle Relativpronomen'),
          body: l(
            'Relative pronouns look like the definite article – except in the Dativ plural: denen (not den).',
            'İlgi zamirleri belirli artikele benzer – Dativ çoğul hariç: denen (den değil).',
            'Wie der Artikel – Dativ Plural: denen.'
          ),
          table: {
            head: [l('', '', ''), l('maskulin', 'eril', 'maskulin'), l('feminin', 'dişil', 'feminin'), l('neutral', 'nötr', 'neutral'), l('Plural', 'çoğul', 'Plural')],
            rows: [
              ['Nominativ', 'der', 'die', 'das', 'die'],
              ['Akkusativ', 'den', 'die', 'das', 'die'],
              ['Dativ', 'dem', 'der', 'dem', 'denen'],
            ],
          },
        },
        {
          title: l('Preposition + relative pronoun', 'Edat + ilgi zamiri', 'Präposition + Relativpronomen'),
          body: l(
            'If the verb needs a preposition, it comes first – the case depends on the preposition: in der (Dativ), mit dem (Dativ), für den (Akk.), an den (sich erinnern an + Akk.).',
            'Fiil bir edat gerektiriyorsa edat önce gelir – hal edata bağlıdır: in der (Dativ), mit dem (Dativ), für den (Akk.), an den (sich erinnern an + Akk.).',
            'Präposition zuerst, Kasus von der Präposition.'
          ),
          examples: [
            { de: 'Die Firma, **bei der** ich arbeite, …', translation: l('The company I work for …', 'Çalıştığım şirket …', '') },
            { de: 'Der Freund, **für den** ich koche, …', translation: l('The friend I’m cooking for …', 'Yemek pişirdiğim arkadaş …', '') },
          ],
        },
        {
          title: l('wo and was', 'wo ve was', 'wo und was'),
          body: l(
            'Places: wo can replace in dem/in der: das Café, wo wir … After alles, etwas, nichts, vieles, das and superlatives (das Beste): was.',
            'Yerler: wo, in dem/in der yerine kullanılabilir: das Café, wo wir … alles, etwas, nichts, vieles, das ve en üstünlüklerden (das Beste) sonra: was.',
            'Ort → wo · alles/etwas/nichts → was.'
          ),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('Yasemin shows her German friend photos of her home town.', 'Yasemin Alman arkadaşına memleketinin fotoğraflarını gösteriyor.', 'Yasemin zeigt Fotos ihrer Heimatstadt.'),
      dialogue: [
        { speaker: 'Yasemin', de: 'Schau, das ist Trabzon, die Stadt, **in der** ich aufgewachsen bin.', translation: l('Look, that’s Trabzon, the city I grew up in.', 'Bak, bu Trabzon, büyüdüğüm şehir.', '') },
        { speaker: 'Nina', de: 'Wie schön! Und wer ist die alte Frau, **mit der** du da tanzt?', translation: l('How lovely! And who’s the old woman you’re dancing with?', 'Ne güzel! Peki dans ettiğin yaşlı kadın kim?', '') },
        { speaker: 'Yasemin', de: 'Das ist meine Oma, **der** ich als Kind alles erzählt habe.', translation: l('That’s my grandma, whom I told everything as a child.', 'O benim babaannem, çocukken ona her şeyi anlatırdım.', '') },
        { speaker: 'Nina', de: 'Und dieses Café hier?', translation: l('And this café here?', 'Peki buradaki kafe?', '') },
        { speaker: 'Yasemin', de: 'Das ist das Café, **wo** ich meinen Mann kennengelernt habe. Er war der Kellner, **dem** ich jeden Tag zu viel Trinkgeld gegeben habe! 😄', translation: l('That’s the café where I met my husband. He was the waiter I gave too big a tip every day! 😄', 'Kocamla tanıştığım kafe. Her gün çok fazla bahşiş verdiğim garsondu! 😄', '') },
        { speaker: 'Nina', de: 'Das ist das Süßeste, **was** ich heute gehört habe!', translation: l('That’s the sweetest thing I’ve heard today!', 'Bugün duyduğum en tatlı şey bu!', '') },
      ],
      examples: [
        { de: 'Der Nachbar, **dem** ich helfe, ist 90.', translation: l('The neighbour I help is 90.', 'Yardım ettiğim komşu 90 yaşında.', '') },
        { de: 'Die Ärztin, **der** ich vertraue, …', translation: l('The doctor I trust …', 'Güvendiğim doktor …', '') },
        { de: 'Die Freunde, **denen** ich schreibe, …', translation: l('The friends I write to …', 'Yazdığım arkadaşlar …', '') },
        { de: 'Die Stadt, **in der** ich wohne, …', translation: l('The city I live in …', 'Yaşadığım şehir …', '') },
        { de: 'Der Kollege, **mit dem** ich arbeite, …', translation: l('The colleague I work with …', 'Birlikte çalıştığım iş arkadaşı …', '') },
        { de: 'Das ist alles, **was** ich weiß.', translation: l('That’s all I know.', 'Bildiğim her şey bu.', '') },
        { de: 'Das Café, **wo** wir uns getroffen haben, …', translation: l('The café where we met …', 'Buluştuğumuz kafe …', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Dativ, prepositions, wo and was.', 'Dativ, edatlar, wo ve was.', 'Dativ, Präpositionen, wo und was.'),
      exercises: ['match-table', 'reldat-m', 'reldat-f', 'mc-denen', 'sort-akk-dat', 'mc-wo', 'mc-was', 'tf-praep', 'reldat-prep-f'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about places and people.', 'Yerler ve insanlar hakkında konuş.', 'Sprich über Orte und Menschen.'),
      exercises: [
        'fill-in-dem',
        'fill-der',
        'fill-was',
        'build-mit-dem',
        'build-an-den',
        'build-denen',
        'fix-den-denen',
        'fix-englisch',
        'fix-das-was',
        'tr-in-der',
        'tr-alles-was',
        'ordering-rel',
        'dialog-heimat',
        'dialog-wer',
        'reldat-n',
        'reldat-pl',
        'reldat-prep-m',
        'reldat-prep-akk',
        'reldat-prep-pl',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Yasemin writes about her home town.', 'Yasemin memleketini anlatıyor.', 'Yasemin schreibt über ihre Heimatstadt.'),
      passage: [
        'Trabzon, die Stadt, **in der** ich aufgewachsen bin, liegt am Schwarzen Meer.',
        'Die wichtigste Person in meiner Kindheit war meine Oma, **der** ich alles erzählen konnte.',
        'Den Markt, **auf dem** wir jeden Samstag zusammen einkauften, gibt es immer noch. Dort riecht es nach Fisch, Haselnüssen und Tee.',
        '**Was** ich hier in Deutschland am meisten vermisse, ist das Meer – und der Tee, **den** man dort überall trinkt.',
      ],
      glossary: [
        { de: 'das Schwarze Meer', note: l('the Black Sea', 'Karadeniz', 'Meer im Norden der Türkei') },
        { de: 'die Haselnuss', note: l('hazelnut', 'fındık', 'Nuss') },
        { de: 'vermissen', note: l('to miss', 'özlemek', 'fehlen') },
      ],
      exercises: ['read-stadt', 'read-oma', 'read-markt', 'read-vermisst'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Listen for the relative pronouns.', 'İlgi zamirlerine kulak ver.', 'Hör auf die Relativpronomen.'),
      exercises: ['listen-mit-wem', 'listen-denen', 'listen-wo', 'listen-was'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Talk about your home town and the people who were important in your childhood.', 'Memleketinden ve çocukluğunda önemli olan insanlardan bahset.', 'Sprich über deine Heimatstadt.'),
      points: [
        l('„Die Stadt, in der ich aufgewachsen bin, …“', '„Die Stadt, in der ich aufgewachsen bin, …“', 'in der'),
        l('A person: „…, dem/der ich …“', 'Bir kişi: „…, dem/der ich …“', 'dem/der'),
        l('A place: „…, wo wir …“', 'Bir yer: „…, wo wir …“', 'wo'),
        l('„Was ich am meisten vermisse, ist …“', '„Was ich am meisten vermisse, ist …“', 'was'),
      ],
      model: [
        'Die Stadt, in der ich aufgewachsen bin, heißt Konya.',
        'Mein Onkel war der Mensch, dem ich am meisten vertraut habe.',
        'Es gab einen Park, wo wir jeden Abend Fußball gespielt haben.',
        'Was ich am meisten vermisse, ist das Essen meiner Mutter.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write about a place that is important to you (at least 5 sentences). Use relative clauses with prepositions, wo or was.',
        'Senin için önemli bir yer hakkında yaz (en az 5 cümle). Edatlı ilgi cümleleri, wo ya da was kullan.',
        'Schreib über einen wichtigen Ort (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Preposition + relative pronoun (in der, mit dem …)', 'Edat + ilgi zamiri (in der, mit dem …)', 'Präposition + Relativpronomen'), pattern: ', (in|mit|bei|von|zu|auf|an|für|über|aus) (dem|der|den|denen|die|das)\\b' },
        { label: l('A Dativ relative pronoun (dem, der, denen)', 'Bir Dativ ilgi zamiri (dem, der, denen)', 'Relativpronomen im Dativ'), pattern: ',( \\p{Ll}+)? (dem|denen)\\b|, der (ich|du|er|sie|wir|man)\\b' },
        { label: l('wo or was as relative word', 'İlgi kelimesi olarak wo ya da was', 'wo oder was'), pattern: ', (wo|was) |^Was |[.!?] Was ' },
      ],
      model: [
        'Der Ort, an den ich am liebsten denke, ist das Haus meiner Großeltern.',
        'Es steht in einem kleinen Dorf, in dem es nur einen Laden gibt.',
        'Hinter dem Haus gibt es einen Garten, wo wir im Sommer immer gegessen haben.',
        'Mein Opa, dem der Garten gehört, pflanzt dort Tomaten und Paprika.',
        'Das ist alles, was ich für einen perfekten Sommer brauche.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Relative pronouns – 60 seconds.', 'İlgi zamirleri – 60 saniye.', 'Relativpronomen – 60 Sekunden.'),
      seconds: 60,
      pool: [...DAT_DRILLS.map(([id]) => `reldat-${id}`), 'mc-denen', 'mc-was', 'mc-wo'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('Dativ: dem, der, dem, denen', 'Dativ: dem, der, dem, denen', 'Dativ'),
      l('Preposition first: in der, mit dem, für den', 'Edat önce: in der, mit dem, für den', 'Präposition + Relativpronomen'),
      l('wo for places; was after alles, etwas, nichts, das Beste', 'Yerler için wo; alles, etwas, nichts, das Beste’den sonra was', 'wo / was'),
    ],
    mistakes: [
      { wrong: 'die Leute, den ich helfe', right: 'die Leute, denen ich helfe', note: l('Plural Dativ → denen.', 'Çoğul Dativ → denen.', 'denen.') },
      { wrong: 'die Frau, die ich mit spreche', right: 'die Frau, mit der ich spreche', note: l('Preposition first.', 'Edat önce.', 'Präposition zuerst.') },
      { wrong: 'alles, das ich weiß', right: 'alles, was ich weiß', note: l('alles → was.', 'alles → was.', 'was.') },
      { wrong: 'der Mann, den ich helfe', right: 'der Mann, dem ich helfe', note: l('helfen + Dativ.', 'helfen + Dativ.', 'dem.') },
    ],
  },
}
