import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'um … zu', emoji: '🎯', translation: l('in order to', '… için (aynı özne)', 'Ziel, gleiches Subjekt'), example: 'Ich lerne Deutsch, um in Berlin zu studieren.' },
  { word: 'damit', emoji: '🤝', translation: l('so that', '… sın diye (farklı özne)', 'Ziel, anderes Subjekt'), example: 'Ich spreche langsam, damit du mich verstehst.' },
  { word: 'Wozu?', emoji: '❓', translation: l('What for?', 'Ne için?', 'Frage nach dem Ziel'), example: 'Wozu brauchst du das Geld?' },
  { word: 'das Ziel', emoji: '🏁', translation: l('goal', 'hedef', 'was man erreichen will'), example: 'Mein Ziel ist ein Job in Wien.' },
  { word: 'erreichen', emoji: '🥇', translation: l('to reach, achieve', 'ulaşmak, başarmak', 'schaffen'), example: 'Um mein Ziel zu erreichen, lerne ich jeden Tag.' },
  { word: 'sparen', emoji: '🐷', translation: l('to save (money)', 'biriktirmek', 'Geld nicht ausgeben'), example: 'Ich spare, um ein Auto zu kaufen.' },
  { word: 'sich vorbereiten auf', emoji: '📚', translation: l('to prepare for', '… -e hazırlanmak', 'fertig machen für'), example: 'Ich bereite mich auf die Prüfung vor.' },
  { word: 'sich verbessern', emoji: '📈', translation: l('to improve', 'gelişmek', 'besser werden'), example: 'Um mich zu verbessern, lese ich viel.' },
  { word: 'die Nachhilfe', emoji: '👩‍🏫', translation: l('tutoring', 'özel ders', 'Extra-Unterricht'), example: 'Mein Sohn bekommt Nachhilfe, damit er besser wird.' },
  { word: 'der Wecker', emoji: '⏰', translation: l('alarm clock', 'çalar saat', 'weckt dich'), example: 'Ich stelle den Wecker, damit ich nicht verschlafe.' },
  { word: 'verschlafen', emoji: '😴', translation: l('to oversleep', 'uyuya kalmak', 'zu lange schlafen'), example: 'Ich habe heute verschlafen.' },
  { word: 'die Gesundheit', emoji: '❤️', translation: l('health', 'sağlık', 'gesund sein'), example: 'Ich jogge, um etwas für meine Gesundheit zu tun.' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Ziel', gender: 'n', plural: 'die Ziele', translation: l('goal', 'hedef', 'Ziel') },
  { word: 'Prüfung', gender: 'f', plural: 'die Prüfungen', translation: l('exam', 'sınav', 'Prüfung') },
  { word: 'Geld', gender: 'n', translation: l('money', 'para', 'Geld') },
  { word: 'Wecker', gender: 'm', plural: 'die Wecker', translation: l('alarm clock', 'çalar saat', 'Wecker') },
  { word: 'Gesundheit', gender: 'f', translation: l('health', 'sağlık', 'Gesundheit') },
  { word: 'Nachhilfe', gender: 'f', translation: l('tutoring', 'özel ders', 'Nachhilfe') },
]

/** [id, main clause, purpose clause with um…zu, purpose clause with damit, which is right] */
const PURPOSE: [string, string, string, string, 'um' | 'damit'][] = [
  ['spare', 'Ich spare Geld,', 'um ein Auto zu kaufen.', 'damit ich ein Auto kaufe.', 'um'],
  ['langsam', 'Ich spreche langsam,', 'um dich zu verstehen.', 'damit du mich verstehst.', 'damit'],
  ['wecker', 'Ich stelle den Wecker,', 'um nicht zu verschlafen.', 'damit ich nicht verschlafe.', 'um'],
  ['nachhilfe', 'Die Eltern bezahlen Nachhilfe,', 'um bessere Noten zu bekommen.', 'damit ihr Sohn bessere Noten bekommt.', 'damit'],
  ['joggen', 'Er joggt jeden Morgen,', 'um fit zu bleiben.', 'damit er fit bleibt.', 'um'],
  ['schluessel', 'Ich gebe dir den Schlüssel,', 'um in die Wohnung zu kommen.', 'damit du in die Wohnung kommst.', 'damit'],
]

function purposeDrills(): Exercise[] {
  return PURPOSE.map(([id, main, umZu, damit, right], i) => {
    const sameSubject = right === 'um'
    const options = [`${main} ${umZu}`, `${main} ${damit}`]
    // In same-subject cases both are grammatical; damit with the same subject is possible but um…zu is preferred.
    const correct = sameSubject ? 0 : 1
    const rotation = i % 2
    const ordered = rotation ? [options[1], options[0]] : options
    return {
      id: `ziel-${id}`,
      type: 'multiple_choice' as const,
      topic: 'um-oder-damit',
      concept: sameSubject ? 'same-subject' : 'different-subject',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: main,
      promptL10n: l('Which version is best?', 'Hangi versiyon en iyisi?', 'Welche Version passt am besten?'),
      options: ordered,
      answer: ordered.indexOf(options[correct]),
      explanation: sameSubject
        ? l('Same subject in both parts → um … zu is the natural choice.', 'İki kısımda aynı özne → doğal seçim um … zu.', 'gleiches Subjekt → um … zu.')
        : l('Different subjects (ich – du / die Eltern – der Sohn) → damit.', 'Farklı özneler (ich – du / die Eltern – der Sohn) → damit.', 'anderes Subjekt → damit.'),
      examples: [`${main} **${sameSubject ? umZu : damit}**`],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-ziel',
    type: 'matching',
    topic: 'um-zu',
    concept: 'purpose-meaning',
    skill: 'reading',
    difficulty: 1,
    instructions: l('Match the action and the purpose.', 'Eylemi amaçla eşleştir.', 'Ordne Handlung und Ziel zu.'),
    pairs: [
      { left: 'Ich gehe in die Bäckerei, …', right: '… um Brot zu kaufen.' },
      { left: 'Ich lerne Deutsch, …', right: '… um in Deutschland zu arbeiten.' },
      { left: 'Ich trinke Kaffee, …', right: '… um wach zu bleiben.' },
      { left: 'Ich spare Geld, …', right: '… um eine Reise zu machen.' },
    ],
    explanation: l('um … zu + infinitive at the end = in order to.', 'um … zu + sonda mastar = … için.', 'um … zu.'),
    practice: ['ziel-spare', 'ziel-joggen'],
  },
  {
    id: 'sort-subjekt',
    type: 'categorize',
    topic: 'um-oder-damit',
    concept: 'um-or-damit',
    skill: 'grammar',
    difficulty: 3,
    instructions: l('um … zu or damit?', 'um … zu mu damit mi?', 'um … zu oder damit?'),
    categories: ['um … zu', 'damit'],
    items: [
      { text: 'Ich lerne viel, … ich die Prüfung bestehe.', category: 0 },
      { text: 'Ich erkläre es dir, … du es verstehst.', category: 1 },
      { text: 'Sie fährt nach Spanien, … sie Spanisch lernt.', category: 0 },
      { text: 'Wir kaufen ein großes Auto, … die Kinder Platz haben.', category: 1 },
      { text: 'Er macht Sport, … er fit bleibt.', category: 0 },
      { text: 'Ich rufe an, … meine Mutter sich keine Sorgen macht.', category: 1 },
    ],
    explanation: l(
      'Same subject → better um … zu (Ich lerne viel, um die Prüfung zu bestehen). Different subject → only damit.',
      'Aynı özne → um … zu daha iyi (Ich lerne viel, um die Prüfung zu bestehen). Farklı özne → yalnızca damit.',
      'gleiches Subjekt → um … zu · verschieden → damit.'
    ),
  },
  {
    id: 'mc-wozu',
    type: 'multiple_choice',
    topic: 'um-zu',
    concept: 'wozu',
    skill: 'grammar',
    difficulty: 2,
    prompt: '___ brauchst du so viel Geld? – Um ein Haus zu kaufen.',
    options: ['Wozu', 'Wo', 'Wie'],
    answer: 0,
    explanation: l('Question about the purpose → Wozu? (Answer with um … zu / damit.)', 'Amaç sorusu → Wozu? (um … zu / damit ile cevap.)', 'Wozu? → um … zu.'),
    examples: ['**Wozu** brauchst du das Geld?'],
  },
  {
    id: 'tf-damit-ende',
    type: 'true_false',
    topic: 'damit',
    concept: 'damit-verb-end',
    skill: 'grammar',
    difficulty: 1,
    statement: 'Nach „damit“ steht das Verb am Ende (wie bei weil und dass).',
    answer: true,
    explanation: l('damit is a subordinating conjunction → verb at the end.', 'damit bir yan cümle bağlacıdır → fiil sonda.', 'Verb am Ende.'),
    examples: ['…, damit du mich **verstehst**.'],
  },
  {
    id: 'select-correct',
    type: 'multiple_select',
    topic: 'um-zu',
    concept: 'um-zu-form',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Which sentences are correct? Select all.', 'Hangi cümleler doğru? Hepsini seç.', 'Welche Sätze sind richtig?'),
    options: ['Ich jogge, um fit zu bleiben.', 'Ich jogge, um ich fit bleibe.', 'Ich spare, um nach Japan zu reisen.', 'Er lernt, damit er die Prüfung besteht.', 'Ich lerne, damit zu bestehen.'],
    answers: [0, 2, 3],
    explanation: l('um … zu: no subject, zu + infinitive at the end. damit: subject + verb at the end.', 'um … zu: özne yok, sonda zu + mastar. damit: özne + sonda fiil.', 'um … zu ohne Subjekt; damit mit Subjekt.'),
  },
  {
    id: 'image-ziel',
    type: 'image_choice',
    topic: 'um-zu',
    concept: 'purpose-meaning',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Ich spare jeden Monat 100 Euro, um im Sommer ans Meer zu fahren.',
    options: [
      { emoji: '🏖️', label: 'Urlaub am Meer' },
      { emoji: '🚗', label: 'Auto' },
      { emoji: '🏠', label: 'Haus' },
      { emoji: '💻', label: 'Laptop' },
    ],
    answer: 0,
    explanation: l('The purpose: a holiday by the sea 🏖️.', 'Amaç: deniz kenarında tatil 🏖️.', 'Urlaub am Meer.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-um',
    type: 'fill_blank',
    topic: 'um-zu',
    concept: 'um-zu-form',
    skill: 'grammar',
    difficulty: 1,
    sentence: 'Ich gehe in die Bibliothek, ___ in Ruhe zu lernen.',
    accepted: ['um'],
    base: 'um / damit',
    explanation: l('Same subject + zu-infinitive → um.', 'Aynı özne + zu’lu mastar → um.', 'um … zu.'),
    examples: ['…, **um** in Ruhe **zu lernen**.'],
  },
  {
    id: 'fill-damit',
    type: 'fill_blank',
    topic: 'damit',
    concept: 'different-subject',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich schreibe dir die Adresse auf, ___ du sie nicht vergisst.',
    accepted: ['damit'],
    base: 'um / damit',
    explanation: l('ich – du: different subjects → damit.', 'ich – du: farklı özneler → damit.', 'damit.'),
    examples: ['…, **damit** du sie nicht **vergisst**.'],
  },
  {
    id: 'fill-zu-trennbar',
    type: 'fill_blank',
    topic: 'um-zu',
    concept: 'um-zu-separable',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich stehe um sechs auf, um pünktlich ___. (ankommen)',
    accepted: ['anzukommen'],
    base: 'an|kommen',
    explanation: l('Separable → anzukommen.', 'Ayrılabilen → anzukommen.', 'anzukommen.'),
    examples: ['…, um pünktlich **anzukommen**.'],
  },
  {
    id: 'build-um',
    type: 'sentence_builder',
    topic: 'um-zu',
    concept: 'um-zu-form',
    skill: 'grammar',
    difficulty: 2,
    chips: ['zu finden', 'um', 'Ich lerne Deutsch,', 'einen besseren Job'],
    answers: [['Ich lerne Deutsch,', 'um', 'einen besseren Job', 'zu finden']],
    translation: l('I’m learning German to find a better job.', 'Daha iyi bir iş bulmak için Almanca öğreniyorum.', 'Ich lerne Deutsch, um einen besseren Job zu finden.'),
    explanation: l('um – … – zu + infinitive (end).', 'um – … – zu + mastar (son).', 'um … zu finden.'),
    examples: ['Ich lerne Deutsch, **um** einen besseren Job **zu finden**.'],
  },
  {
    id: 'build-damit',
    type: 'sentence_builder',
    topic: 'damit',
    concept: 'damit-verb-end',
    skill: 'grammar',
    difficulty: 3,
    chips: ['die Kinder', 'damit', 'ruhig schlafen', 'Wir sprechen leise,', 'können'],
    answers: [['Wir sprechen leise,', 'damit', 'die Kinder', 'ruhig schlafen', 'können']],
    translation: l('We speak quietly so that the children can sleep peacefully.', 'Çocuklar rahat uyuyabilsin diye sessiz konuşuyoruz.', 'Wir sprechen leise, damit die Kinder ruhig schlafen können.'),
    explanation: l('damit – subject – … – verb(s) at the end.', 'damit – özne – … – sonda fiil(ler).', 'damit … können.'),
    examples: ['…, **damit** die Kinder ruhig schlafen **können**.'],
  },
  {
    id: 'build-um-first',
    type: 'sentence_builder',
    topic: 'um-zu',
    concept: 'um-zu-first',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ich', 'jeden Tag', 'lerne', 'Um die Prüfung zu bestehen,'],
    answers: [['Um die Prüfung zu bestehen,', 'lerne', 'ich', 'jeden Tag']],
    translation: l('To pass the exam, I study every day.', 'Sınavı geçmek için her gün çalışıyorum.', 'Um die Prüfung zu bestehen, lerne ich jeden Tag.'),
    explanation: l('um…zu-clause first = position 1 → verb, verb.', 'um…zu-cümlesi başta = 1. pozisyon → fiil, fiil.', '…, lerne ich …'),
    examples: ['Um die Prüfung zu bestehen, **lerne** ich jeden Tag.'],
  },
  {
    id: 'fix-um-subjekt',
    type: 'error_correction',
    topic: 'um-oder-damit',
    concept: 'different-subject',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Ich erkläre es noch einmal, um du es verstehst.',
    accepted: ['Ich erkläre es noch einmal, damit du es verstehst.'],
    explanation: l('Different subject → damit.', 'Farklı özne → damit.', 'damit.'),
    examples: ['…, **damit** du es verstehst.'],
  },
  {
    id: 'fix-zu-fehlt',
    type: 'error_correction',
    topic: 'um-zu',
    concept: 'um-zu-form',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich fahre nach München, um meine Tante besuchen.',
    accepted: ['Ich fahre nach München, um meine Tante zu besuchen.'],
    explanation: l('um … zu + infinitive – don’t forget zu.', 'um … zu + mastar – zu’yu unutma.', 'zu besuchen.'),
    examples: ['…, um meine Tante **zu besuchen**.'],
  },
  {
    id: 'fix-damit-ende',
    type: 'error_correction',
    topic: 'damit',
    concept: 'damit-verb-end',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich gebe dir mein Handy, damit du kannst deine Mutter anrufen.',
    accepted: ['Ich gebe dir mein Handy, damit du deine Mutter anrufen kannst.'],
    explanation: l('damit → verb at the end: … anrufen kannst.', 'damit → fiil sonda: … anrufen kannst.', '… anrufen kannst.'),
    examples: ['…, damit du deine Mutter **anrufen kannst**.'],
  },
  {
    id: 'tr-um',
    type: 'translation',
    topic: 'um-zu',
    concept: 'um-zu-form',
    skill: 'writing',
    difficulty: 2,
    source: l('I’m saving money to buy a car.', 'Araba almak için para biriktiriyorum.', 'I’m saving money to buy a car.'),
    accepted: ['Ich spare Geld, um ein Auto zu kaufen.'],
    explanation: l('…, um … zu kaufen.', '…, um … zu kaufen.', 'um … zu kaufen.'),
    examples: ['Ich spare Geld, **um** ein Auto **zu kaufen**.'],
  },
  {
    id: 'tr-damit',
    type: 'translation',
    topic: 'damit',
    concept: 'different-subject',
    skill: 'writing',
    difficulty: 3,
    source: l('I’m speaking slowly so that you understand me. (du)', 'Beni anlayasın diye yavaş konuşuyorum. (du)', 'I’m speaking slowly so that you understand me. (du)'),
    accepted: ['Ich spreche langsam, damit du mich verstehst.'],
    explanation: l('…, damit du mich verstehst.', '…, damit du mich verstehst.', 'damit du mich verstehst.'),
    examples: ['Ich spreche langsam, **damit** du mich **verstehst**.'],
  },
  {
    id: 'ordering-ziel',
    type: 'ordering',
    topic: 'um-zu',
    concept: 'um-zu-form',
    skill: 'grammar',
    difficulty: 2,
    promptL10n: l('Build the purpose clause.', 'Amaç cümlesini kur.', 'Bilde den Finalsatz.'),
    items: ['zu verbessern', 'mein Deutsch', 'um'],
    answer: ['um', 'mein Deutsch', 'zu verbessern'],
    explanation: l('um – object – zu + infinitive.', 'um – nesne – zu + mastar.', 'um … zu verbessern.'),
  },
  {
    id: 'dialog-wozu',
    type: 'dialogue',
    topic: 'um-zu',
    concept: 'wozu',
    skill: 'speaking',
    difficulty: 1,
    lines: [{ speaker: 'Kollegin', de: 'Wozu machst du den Excel-Kurs?' }],
    options: ['Um bessere Chancen im Job zu haben.', 'Um ich bessere Chancen habe.', 'Damit bessere Chancen zu haben.'],
    answer: 0,
    explanation: l('Short answer: Um … zu …', 'Kısa cevap: Um … zu …', 'Um … zu haben.'),
  },
  {
    id: 'dialog-damit',
    type: 'dialogue',
    topic: 'damit',
    concept: 'different-subject',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Mutter', de: 'Warum schreibst du mir eine Nachricht?' }],
    options: ['Damit du weißt, dass ich gut angekommen bin.', 'Um du weißt, dass ich angekommen bin.', 'Damit zu wissen, dass ich angekommen bin.'],
    answer: 0,
    explanation: l('ich (write) – du (know) → damit.', 'ich (yazıyorum) – du (biliyorsun) → damit.', 'Damit du weißt …'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-warum',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Warum hört Omar deutsche Podcasts?',
    options: ['Um sein Hörverstehen zu verbessern.', 'Um einzuschlafen.', 'Damit seine Frau Deutsch lernt.'],
    answer: 0,
    explanation: l('„Ich höre jeden Tag deutsche Podcasts, um mein Hörverstehen zu verbessern.“', '„Ich höre jeden Tag deutsche Podcasts, um mein Hörverstehen zu verbessern.“', 'Hörverstehen.'),
  },
  {
    id: 'read-tandem',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Warum trifft er sich mit Paul?',
    options: ['Damit beide eine Sprache üben können.', 'Um Fußball zu spielen.', 'Um zu arbeiten.'],
    answer: 0,
    explanation: l('„… damit wir beide üben können: Ich spreche Deutsch, Paul Arabisch.“', '„… damit wir beide üben können: Ich spreche Deutsch, Paul Arabisch.“', 'beide üben.'),
  },
  {
    id: 'read-zettel',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 2,
    statement: 'Omar klebt Zettel an Möbel, um neue Wörter zu lernen.',
    answer: true,
    explanation: l('„Um neue Wörter zu lernen, klebe ich Zettel an die Möbel.“', '„Um neue Wörter zu lernen, klebe ich Zettel an die Möbel.“', 'ja.'),
  },
  {
    id: 'read-ziel',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-tipps',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist Omars Ziel?',
    options: ['Als Ingenieur in Deutschland zu arbeiten.', 'Deutschlehrer zu werden.', 'Nach Syrien zurückzugehen.'],
    answer: 0,
    explanation: l('„Mein Ziel ist, als Ingenieur in Deutschland zu arbeiten.“', '„Mein Ziel ist, als Ingenieur in Deutschland zu arbeiten.“', 'Ingenieur.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-um',
    type: 'listening_choice',
    topic: 'um-zu',
    concept: 'purpose-meaning',
    skill: 'listening',
    difficulty: 1,
    audio: 'Ich fahre heute in die Stadt, um ein Geschenk für meine Mutter zu kaufen.',
    question: l('Why is the person going to town?', 'Kişi neden şehre gidiyor?', 'Warum fährt die Person in die Stadt?'),
    options: ['🎁 to buy a present', '🍽️ to eat', '🎬 to see a film'],
    answer: 0,
    explanation: l('„um ein Geschenk … zu kaufen“', '„um ein Geschenk … zu kaufen“', 'Geschenk.'),
  },
  {
    id: 'listen-damit',
    type: 'listening_choice',
    topic: 'damit',
    concept: 'different-subject',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich lasse das Licht an, damit die Kinder keine Angst haben.',
    question: l('Why is the light left on?', 'Işık neden açık bırakılıyor?', 'Warum bleibt das Licht an?'),
    options: ['so that the children aren’t afraid', 'to read', 'because it’s broken'],
    answer: 0,
    explanation: l('„damit die Kinder keine Angst haben“', '„damit die Kinder keine Angst haben“', 'keine Angst.'),
  },
  {
    id: 'listen-wozu',
    type: 'listening_choice',
    topic: 'um-zu',
    concept: 'wozu',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wozu brauchst du einen neuen Laptop? – Um von zu Hause zu arbeiten.',
    question: l('What is the laptop for?', 'Dizüstü bilgisayar ne için?', 'Wozu ist der Laptop?'),
    options: ['working from home', 'gaming', 'school'],
    answer: 0,
    explanation: l('„Um von zu Hause zu arbeiten.“', '„Um von zu Hause zu arbeiten.“', 'Homeoffice.'),
  },
  {
    id: 'listen-wecker',
    type: 'listening_choice',
    topic: 'um-zu',
    concept: 'same-subject',
    skill: 'listening',
    difficulty: 2,
    audio: 'Ich stelle zwei Wecker, um morgen bloß nicht zu verschlafen.',
    question: l('Why two alarm clocks?', 'Neden iki çalar saat?', 'Warum zwei Wecker?'),
    options: ['not to oversleep', 'to wake the children', 'because one is broken'],
    answer: 0,
    explanation: l('„um … nicht zu verschlafen“', '„um … nicht zu verschlafen“', 'nicht verschlafen.'),
  },

  ...purposeDrills(),
]

export const UNIT_B1_08_UM_ZU_DAMIT: CourseUnit = {
  level: 'B1',
  number: 8,
  slug: 'um-zu-damit',
  titleDe: 'Ich lerne, um …',
  title: l('I’m learning in order to …', '… için öğreniyorum', 'Ich lerne, um …'),
  goal: l(
    'By the end of this unit you can talk about goals and purposes with um … zu (same subject) and damit (different subject), and ask „Wozu?“.',
    'Bu ünitenin sonunda um … zu (aynı özne) ve damit (farklı özne) ile hedeflerden ve amaçlardan bahsedebilir, „Wozu?“ diye sorabilirsin.',
    'Am Ende dieser Einheit sprichst du über Ziele mit um … zu und damit.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'um-zu', label: l('um … zu', 'um … zu', 'um … zu') },
    { key: 'damit', label: l('damit', 'damit', 'damit') },
    { key: 'um-oder-damit', label: l('um … zu or damit?', 'um … zu mu damit mi?', 'um … zu oder damit?') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Words for goals and purposes.', 'Hedefler ve amaçlar için kelimeler.', 'Wörter für Ziele.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('um … zu: same subject', 'um … zu: aynı özne', 'um … zu: gleiches Subjekt'),
          body: l(
            'If the person who acts and the person with the goal are the same: um + … + zu + infinitive at the end. No subject in the um-clause!',
            'Eylemi yapan ve hedefi olan kişi aynıysa: um + … + sonda zu + mastar. um-cümlesinde özne yok!',
            'Gleiches Subjekt → um … zu.'
          ),
          examples: [{ de: 'Ich lerne Deutsch, **um** in Deutschland **zu arbeiten**.', translation: l('I learn German (in order) to work in Germany.', 'Almanya’da çalışmak için Almanca öğreniyorum.', '') }],
        },
        {
          title: l('damit: different subject', 'damit: farklı özne', 'damit: anderes Subjekt'),
          body: l(
            'If the subjects are different, use damit + subject + … + verb at the end. damit is also possible with the same subject, but um … zu sounds better.',
            'Özneler farklıysa damit + özne + … + sonda fiil kullan. damit aynı özneyle de mümkündür ama um … zu daha iyi duyulur.',
            'Anderes Subjekt → damit.'
          ),
          table: {
            head: [l('Main clause', 'Ana cümle', 'Hauptsatz'), l('Purpose', 'Amaç', 'Ziel')],
            rows: [
              ['Ich lerne viel,', 'um die Prüfung zu bestehen. (ich – ich)'],
              ['Ich erkläre es dir,', 'damit du es verstehst. (ich – du)'],
              ['Die Eltern zahlen Nachhilfe,', 'damit der Sohn bessere Noten bekommt.'],
            ],
          },
        },
        {
          title: l('Wozu? – the question', 'Wozu? – soru', 'Wozu? – die Frage'),
          body: l('Ask about the purpose with Wozu? (What for?). Answer: Um … zu … / Damit …', 'Amacı Wozu? (Ne için?) ile sor. Cevap: Um … zu … / Damit …', 'Wozu? → Um … zu / Damit …'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('In the German course: everyone talks about their goals.', 'Almanca kursunda: herkes hedeflerinden bahsediyor.', 'Im Deutschkurs: Ziele.'),
      dialogue: [
        { speaker: 'Lehrer', de: '**Wozu** lernen Sie Deutsch, Frau Chen?', translation: l('What are you learning German for, Ms Chen?', 'Almancayı ne için öğreniyorsunuz Bayan Chen?', '') },
        { speaker: 'Frau Chen', de: '**Um** in Deutschland Medizin **zu studieren**. Ich brauche B2.', translation: l('To study medicine in Germany. I need B2.', 'Almanya’da tıp okumak için. B2’ye ihtiyacım var.', '') },
        { speaker: 'Lehrer', de: 'Und Sie, Herr Rossi?', translation: l('And you, Mr Rossi?', 'Ya siz Bay Rossi?', '') },
        { speaker: 'Herr Rossi', de: 'Meine Frau ist Deutsche. Ich lerne, **damit** ich mit ihrer Familie sprechen **kann** – und **damit** meine Schwiegermutter mich **versteht**! 😄', translation: l('My wife is German. I’m learning so that I can talk to her family – and so that my mother-in-law understands me! 😄', 'Eşim Alman. Ailesiyle konuşabileyim diye öğreniyorum – ve kayınvalidem beni anlasın diye! 😄', '') },
        { speaker: 'Lehrer', de: 'Sehr gute Gründe! Was machen Sie, **um** schneller Fortschritte **zu machen**?', translation: l('Very good reasons! What do you do to make faster progress?', 'Çok iyi sebepler! Daha hızlı ilerlemek için ne yapıyorsunuz?', '') },
        { speaker: 'Frau Chen', de: 'Ich sehe deutsche Serien mit Untertiteln, **um** mein Hörverstehen **zu trainieren**.', translation: l('I watch German series with subtitles to train my listening.', 'Dinlediğimi anlama becerimi geliştirmek için Almanca dizileri altyazılı izliyorum.', '') },
      ],
      examples: [
        { de: 'Ich spare, **um** ein Auto **zu kaufen**.', translation: l('I’m saving to buy a car.', 'Araba almak için biriktiriyorum.', '') },
        { de: 'Er joggt, **um** fit **zu bleiben**.', translation: l('He jogs to stay fit.', 'Formda kalmak için koşuyor.', '') },
        { de: 'Ich spreche langsam, **damit** du mich **verstehst**.', translation: l('I speak slowly so that you understand me.', 'Beni anlayasın diye yavaş konuşuyorum.', '') },
        { de: 'Wir sind leise, **damit** das Baby **schläft**.', translation: l('We’re quiet so that the baby sleeps.', 'Bebek uyusun diye sessiziz.', '') },
        { de: '**Wozu** brauchst du das?', translation: l('What do you need that for?', 'Buna ne için ihtiyacın var?', '') },
        { de: '**Um** die Prüfung **zu bestehen**, lerne ich jeden Tag.', translation: l('To pass the exam I study every day.', 'Sınavı geçmek için her gün çalışıyorum.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('um … zu or damit?', 'um … zu mu damit mi?', 'um … zu oder damit?'),
      exercises: ['match-ziel', 'sort-subjekt', 'ziel-spare', 'ziel-langsam', 'mc-wozu', 'tf-damit-ende', 'select-correct', 'image-ziel', 'ziel-wecker'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Talk about your goals.', 'Hedeflerinden bahset.', 'Sprich über deine Ziele.'),
      exercises: [
        'fill-um',
        'fill-damit',
        'fill-zu-trennbar',
        'build-um',
        'build-damit',
        'build-um-first',
        'fix-um-subjekt',
        'fix-zu-fehlt',
        'fix-damit-ende',
        'tr-um',
        'tr-damit',
        'ordering-ziel',
        'dialog-wozu',
        'dialog-damit',
        'ziel-nachhilfe',
        'ziel-joggen',
        'ziel-schluessel',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('Omar shares his tips for learning German.', 'Omar Almanca öğrenme ipuçlarını paylaşıyor.', 'Omars Lerntipps.'),
      passage: [
        'Mein Ziel ist, als Ingenieur in Deutschland **zu arbeiten**. Dafür brauche ich gutes Deutsch.',
        'Ich höre jeden Tag deutsche Podcasts, **um** mein Hörverstehen **zu verbessern**.',
        '**Um** neue Wörter **zu lernen**, klebe ich Zettel an die Möbel – „der Schrank“, „das Fenster“ …',
        'Und jeden Mittwoch treffe ich mich mit Paul, **damit** wir beide üben **können**: Ich spreche Deutsch, Paul Arabisch.',
      ],
      glossary: [
        { de: 'dafür', note: l('for that', 'bunun için', 'für dieses Ziel') },
        { de: 'das Hörverstehen', note: l('listening comprehension', 'dinlediğini anlama', 'Hören und verstehen') },
        { de: 'der Zettel', note: l('note, slip of paper', 'not kâğıdı', 'kleines Papier') },
        { de: 'kleben', note: l('to stick', 'yapıştırmak', 'befestigen') },
      ],
      exercises: ['read-warum', 'read-tandem', 'read-zettel', 'read-ziel'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Why do people do things?', 'İnsanlar neden bir şeyler yapar?', 'Warum machen Menschen etwas?'),
      exercises: ['listen-um', 'listen-damit', 'listen-wozu', 'listen-wecker'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Talk about three goals and what you do to reach them.', 'Üç hedeften ve onlara ulaşmak için ne yaptığından bahset.', 'Sprich über drei Ziele.'),
      points: [
        l('Goal 1 + „Um … zu …, mache ich …“', '1. hedef + „Um … zu …, mache ich …“', 'Ziel 1'),
        l('Goal 2 + „…, um … zu …“', '2. hedef + „…, um … zu …“', 'Ziel 2'),
        l('Something you do for others: „…, damit meine Familie …“', 'Başkaları için yaptığın bir şey: „…, damit meine Familie …“', 'damit …'),
      ],
      model: [
        'Um gesünder zu leben, gehe ich jeden Morgen spazieren.',
        'Ich lerne Deutsch, um in Deutschland zu studieren.',
        'Ich arbeite am Wochenende, damit meine Kinder später studieren können.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Write your „learning tips“ for other German learners (at least 5 sentences) – with um … zu and damit.',
        'Diğer Almanca öğrencileri için „öğrenme ipuçlarını“ yaz (en az 5 cümle) – um … zu ve damit ile.',
        'Schreib Lerntipps (mindestens 5 Sätze) mit um … zu und damit.'
      ),
      minSentences: 5,
      checks: [
        { label: l('um … zu', 'um … zu', 'um … zu'), pattern: '\\b[Uu]m\\b[^.!?,]*\\bzu \\p{Ll}+en\\b|\\b[Uu]m\\b[^.!?,]*\\b\\p{Ll}+zu\\p{Ll}+en\\b' },
        { label: l('damit', 'damit', 'damit'), pattern: '\\b[Dd]amit\\b' },
        { label: l('Verb at the end after damit', 'damit’ten sonra fiil sonda', 'Verb am Ende nach damit'), pattern: '[Dd]amit\\b[^.!?]*\\b\\p{Ll}+(t|st|en|e|n|ann|ss)[.!?]' },
      ],
      model: [
        'Hier sind meine besten Lerntipps!',
        'Um neue Wörter zu lernen, schreibe ich sie auf kleine Karten.',
        'Ich sehe Serien auf Deutsch, um mein Hörverstehen zu trainieren.',
        'Ich spreche mit meinen Nachbarn, damit sie mich korrigieren können.',
        'Und ich lerne jeden Tag zehn Minuten, um nichts zu vergessen.',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('um … zu or damit? – 60 seconds.', 'um … zu mu damit mi? – 60 saniye.', 'um … zu oder damit? – 60 Sekunden.'),
      seconds: 60,
      pool: [...PURPOSE.map(([id]) => `ziel-${id}`), 'mc-wozu'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('um … zu + infinitive (same subject)', 'um … zu + mastar (aynı özne)', 'um … zu'),
      l('damit + subject + verb at the end (different subject)', 'damit + özne + sonda fiil (farklı özne)', 'damit'),
      l('Wozu? – What for?', 'Wozu? – Ne için?', 'Wozu?'),
    ],
    mistakes: [
      { wrong: '…, um du verstehst.', right: '…, damit du verstehst.', note: l('Different subject → damit.', 'Farklı özne → damit.', 'damit.') },
      { wrong: '…, um ein Auto kaufen.', right: '…, um ein Auto zu kaufen.', note: l('Don’t forget zu.', 'zu’yu unutma.', 'zu!') },
      { wrong: '…, damit du kannst kommen.', right: '…, damit du kommen kannst.', note: l('Verb at the end.', 'Fiil sonda.', 'Verb am Ende.') },
      { wrong: '…, um ich die Prüfung bestehe.', right: '…, um die Prüfung zu bestehen.', note: l('No subject after um.', 'um’dan sonra özne yok.', 'kein Subjekt.') },
    ],
  },
}
