import type { CourseUnit, Exercise, VocabItem } from '../types'
import { l } from '../l10n'

const VOCAB: VocabItem[] = [
  { word: 'ein größeres Auto', emoji: '🚙', translation: l('a bigger car', 'daha büyük bir araba', 'Komparativ + Endung'), example: 'Wir brauchen ein größeres Auto.' },
  { word: 'die schnellere Verbindung', emoji: '🚄', translation: l('the faster connection', 'daha hızlı bağlantı', 'Komparativ als Attribut'), example: 'Ich nehme die schnellere Verbindung.' },
  { word: 'der billigste Flug', emoji: '✈️', translation: l('the cheapest flight', 'en ucuz uçuş', 'Superlativ als Attribut'), example: 'Wir suchen den billigsten Flug.' },
  { word: 'je … desto', emoji: '📈', translation: l('the … the …', 'ne kadar … o kadar', 'Proportion'), example: 'Je billiger, desto besser.' },
  { word: 'die Umfrage', emoji: '📋', translation: l('survey', 'anket', 'Fragen an viele Leute'), example: 'Laut einer Umfrage …' },
  { word: 'die Hälfte', emoji: '🌓', translation: l('half', 'yarı', '50 %'), example: 'Die Hälfte der Befragten fährt Fahrrad.' },
  { word: 'ein Drittel / ein Viertel', emoji: '🥧', translation: l('a third / a quarter', 'üçte bir / dörtte bir', '33 % / 25 %'), example: 'Ein Drittel der Deutschen hat ein Haustier.' },
  { word: 'Prozent', emoji: '💯', translation: l('per cent', 'yüzde', '%'), example: '40 Prozent der Kinder spielen ein Instrument.' },
  { word: 'die Mehrheit / die Minderheit', emoji: '👥', translation: l('majority / minority', 'çoğunluk / azınlık', 'die meisten / wenige'), example: 'Die Mehrheit ist dafür.' },
  { word: 'steigen / sinken', emoji: '📉', translation: l('to rise / to fall', 'artmak / düşmek', 'mehr / weniger werden'), example: 'Die Preise steigen jedes Jahr.' },
  { word: 'immer mehr', emoji: '⏫', translation: l('more and more', 'gittikçe daha çok', 'wachsend'), example: 'Immer mehr Menschen arbeiten von zu Hause.' },
  { word: 'die Grafik', emoji: '📊', translation: l('chart, graph', 'grafik', 'Bild mit Zahlen'), example: 'Die Grafik zeigt, dass …' },
]

const MORE_VOCAB: VocabItem[] = [
  { word: 'Umfrage', gender: 'f', plural: 'die Umfragen', translation: l('survey', 'anket', 'Umfrage') },
  { word: 'Hälfte', gender: 'f', plural: 'die Hälften', translation: l('half', 'yarı', 'Hälfte') },
  { word: 'Mehrheit', gender: 'f', plural: 'die Mehrheiten', translation: l('majority', 'çoğunluk', 'Mehrheit') },
  { word: 'Grafik', gender: 'f', plural: 'die Grafiken', translation: l('chart', 'grafik', 'Grafik') },
  { word: 'Flug', gender: 'm', plural: 'die Flüge', translation: l('flight', 'uçuş', 'Flug') },
  { word: 'Verbindung', gender: 'f', plural: 'die Verbindungen', translation: l('connection', 'bağlantı', 'Verbindung') },
  { word: 'Preis', gender: 'm', plural: 'die Preise', translation: l('price', 'fiyat', 'Preis') },
]

/** [id, sentence with ___, right, wrongA, wrongB, rule] */
const ATTR: [string, string, string, string, string, string][] = [
  ['groesseres', 'Wir brauchen ein ___ Auto. (groß)', 'größeres', 'größer', 'größere', 'ein + das-word → comparative + -es'],
  ['schnellere', 'Ich nehme die ___ Verbindung. (schnell)', 'schnellere', 'schneller', 'schnelleren', 'die (Akk f) → comparative + -e'],
  ['billigsten', 'Wir suchen den ___ Flug. (billig)', 'billigsten', 'billigste', 'am billigsten', 'den (Akk m) → superlative + -en'],
  ['beste', 'Das ist das ___ Restaurant der Stadt. (gut)', 'beste', 'besten', 'am besten', 'das (Nom n) → superlative + -e'],
  ['aelteren', 'Sie wohnt bei ihrem ___ Bruder. (alt)', 'älteren', 'älter', 'ältere', 'Dativ → comparative + -en'],
  ['hoechste', 'Die Zugspitze ist der ___ Berg Deutschlands. (hoch)', 'höchste', 'höchsten', 'hochste', 'der (Nom m) → superlative + -e'],
]

function attrDrills(): Exercise[] {
  return ATTR.map(([id, sentence, right, wrongA, wrongB, rule], i) => {
    const options = [right, wrongA, wrongB]
    const rotation = i % 3
    const ordered = [...options.slice(rotation), ...options.slice(0, rotation)]
    const sup = /sten|ste$/.test(right)
    return {
      id: `attr-${id}`,
      type: 'multiple_choice' as const,
      topic: 'komparativ-attribut',
      concept: sup ? 'sup-attr' : 'comp-attr',
      skill: 'grammar' as const,
      difficulty: 2 as const,
      prompt: sentence,
      options: ordered,
      answer: ordered.indexOf(right),
      explanation: l(
        `Before a noun the comparative/superlative takes the normal adjective ending: ${rule}.`,
        `İsimden önce karşılaştırma/en üstünlük normal sıfat ekini alır: ${rule}.`,
        `${rule}.`
      ),
      examples: [sentence.replace(/ \(.*\)$/, '').replace('___', `**${right}**`)],
    }
  })
}

const EXERCISES: Exercise[] = [
  // --- Practice 1: recognise -------------------------------------------
  {
    id: 'match-prozent',
    type: 'matching',
    topic: 'statistik',
    concept: 'fractions',
    skill: 'vocabulary',
    difficulty: 1,
    instructions: l('Match the words and the numbers.', 'Kelimeleri sayılarla eşleştir.', 'Ordne Wörter und Zahlen zu.'),
    pairs: [
      { left: 'die Hälfte', right: '50 %' },
      { left: 'ein Drittel', right: '33 %' },
      { left: 'ein Viertel', right: '25 %' },
      { left: 'drei Viertel', right: '75 %' },
      { left: 'die Mehrheit', right: 'mehr als 50 %' },
    ],
    explanation: l('Fractions and expressions for statistics.', 'İstatistik için kesirler ve ifadeler.', 'Statistik-Wortschatz.'),
  },
  {
    id: 'sort-trend',
    type: 'categorize',
    topic: 'statistik',
    concept: 'trends',
    skill: 'vocabulary',
    difficulty: 2,
    instructions: l('Going up or going down?', 'Artıyor mu azalıyor mu?', 'Steigend oder sinkend?'),
    categories: ['📈 mehr', '📉 weniger'],
    items: [
      { text: 'Die Preise steigen.', category: 0 },
      { text: 'Die Zahl ist gesunken.', category: 1 },
      { text: 'Immer mehr Menschen …', category: 0 },
      { text: 'Immer weniger Kinder …', category: 1 },
      { text: 'Die Zahl hat sich verdoppelt.', category: 0 },
      { text: 'Der Anteil ist zurückgegangen.', category: 1 },
    ],
    explanation: l('steigen, sich verdoppeln, immer mehr ↗ – sinken, zurückgehen, immer weniger ↘.', 'steigen, sich verdoppeln, immer mehr ↗ – sinken, zurückgehen, immer weniger ↘.', 'steigen ↗ / sinken ↘.'),
  },
  {
    id: 'mc-am-der',
    type: 'multiple_choice',
    topic: 'komparativ-attribut',
    concept: 'sup-attr',
    skill: 'grammar',
    difficulty: 2,
    prompt: 'Welcher Zug ist ___? – Der ICE.',
    options: ['am schnellsten', 'der schnellste', 'schnellste'],
    answer: 0,
    explanation: l('After sein without a noun: am …sten. Before a noun: der schnellste Zug.', 'İsim olmadan sein’den sonra: am …sten. İsimden önce: der schnellste Zug.', 'am schnellsten.'),
    examples: ['Der ICE ist **am schnellsten**. – Der ICE ist **der schnellste** Zug.'],
    practice: ['attr-billigsten'],
  },
  {
    id: 'tf-je',
    type: 'true_false',
    topic: 'je-desto',
    concept: 'je-desto-order',
    skill: 'grammar',
    difficulty: 2,
    statement: '„Je früher, desto besser“ ist ein vollständiger und richtiger Ausdruck.',
    answer: true,
    explanation: l('Short form without verbs – very common in speech.', 'Fiilsiz kısa biçim – konuşmada çok yaygın.', 'Je früher, desto besser.'),
  },
  {
    id: 'select-richtig',
    type: 'multiple_select',
    topic: 'komparativ-attribut',
    concept: 'comp-attr',
    skill: 'grammar',
    difficulty: 3,
    promptL10n: l('Which are correct? Select all.', 'Hangileri doğru? Hepsini seç.', 'Was ist richtig? Wähle alle.'),
    options: ['eine bessere Idee', 'ein besser Job', 'die größten Städte', 'mit dem neueren Handy', 'der am schnellsten Zug'],
    answers: [0, 2, 3],
    explanation: l('Comparative/superlative before a noun = normal adjective endings: bessere, größten, neueren.', 'İsimden önce karşılaştırma/en üstünlük = normal sıfat ekleri: bessere, größten, neueren.', 'Adjektivendung!'),
  },
  {
    id: 'image-grafik',
    type: 'image_choice',
    topic: 'statistik',
    concept: 'trends',
    skill: 'vocabulary',
    difficulty: 1,
    prompt: 'Die Zahl der Radfahrer ist stark gestiegen.',
    options: [
      { emoji: '📈', label: 'gestiegen' },
      { emoji: '📉', label: 'gesunken' },
      { emoji: '➡️', label: 'gleich geblieben' },
      { emoji: '❓', label: 'unbekannt' },
    ],
    answer: 0,
    explanation: l('gestiegen = risen 📈.', 'gestiegen = arttı 📈.', 'gestiegen.'),
  },

  // --- Practice 2: use -------------------------------------------------
  {
    id: 'fill-groesseren',
    type: 'fill_blank',
    topic: 'komparativ-attribut',
    concept: 'comp-attr',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Wir suchen eine Wohnung mit einem größer___ Balkon.',
    accepted: ['en'],
    base: 'Dativ',
    explanation: l('mit + Dativ → einem größeren Balkon.', 'mit + Dativ → einem größeren Balkon.', 'größeren.'),
    examples: ['… mit einem **größeren** Balkon.'],
  },
  {
    id: 'fill-desto',
    type: 'fill_blank',
    topic: 'je-desto',
    concept: 'je-desto-order',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Je mehr Sport ich mache, ___ besser schlafe ich.',
    accepted: ['desto', 'umso'],
    base: 'je …',
    explanation: l('je … desto / umso.', 'je … desto / umso.', 'desto.'),
    examples: ['Je mehr Sport ich mache, **desto** besser schlafe ich.'],
  },
  {
    id: 'fill-haelfte',
    type: 'fill_blank',
    topic: 'statistik',
    concept: 'fractions',
    skill: 'vocabulary',
    difficulty: 2,
    sentence: 'Fast die ___ der Deutschen (48 %) macht im Sommer Urlaub.',
    accepted: ['Hälfte'],
    base: '≈ 50 %',
    explanation: l('about 50 % → fast die Hälfte.', 'yaklaşık %50 → fast die Hälfte.', 'Hälfte.'),
    examples: ['Fast **die Hälfte** der Deutschen …'],
  },
  {
    id: 'build-je',
    type: 'sentence_builder',
    topic: 'je-desto',
    concept: 'je-desto-order',
    skill: 'grammar',
    difficulty: 3,
    chips: ['ist', 'desto', 'Je länger man wartet,', 'teurer', 'der Flug'],
    answers: [['Je länger man wartet,', 'desto', 'teurer', 'ist', 'der Flug']],
    translation: l('The longer you wait, the more expensive the flight is.', 'Ne kadar uzun beklersen uçuş o kadar pahalı oluyor.', 'Je länger man wartet, desto teurer ist der Flug.'),
    explanation: l('desto + comparative + verb + subject.', 'desto + karşılaştırma + fiil + özne.', 'desto teurer ist …'),
    examples: ['Je länger man wartet, **desto teurer ist** der Flug.'],
  },
  {
    id: 'build-umfrage',
    type: 'sentence_builder',
    topic: 'statistik',
    concept: 'describe-stats',
    skill: 'grammar',
    difficulty: 2,
    chips: ['arbeiten', 'Laut der Umfrage', 'von zu Hause', 'immer mehr Menschen'],
    answers: [['Laut der Umfrage', 'arbeiten', 'immer mehr Menschen', 'von zu Hause']],
    translation: l('According to the survey, more and more people work from home.', 'Ankete göre giderek daha fazla insan evden çalışıyor.', 'Laut der Umfrage arbeiten immer mehr Menschen von zu Hause.'),
    explanation: l('Laut … (position 1) → verb next.', 'Laut … (1. pozisyon) → ardından fiil.', 'Laut … arbeiten …'),
    examples: ['**Laut der Umfrage** arbeiten **immer mehr** Menschen von zu Hause.'],
  },
  {
    id: 'build-beste',
    type: 'sentence_builder',
    topic: 'komparativ-attribut',
    concept: 'sup-attr',
    skill: 'grammar',
    difficulty: 2,
    chips: ['der beste', 'ist', 'Das', 'Döner', 'in Berlin'],
    answers: [['Das', 'ist', 'der beste', 'Döner', 'in Berlin']],
    translation: l('That’s the best kebab in Berlin.', 'Bu Berlin’deki en iyi döner.', 'Das ist der beste Döner in Berlin.'),
    explanation: l('der beste (Nom m, -e).', 'der beste (Nom eril, -e).', 'der beste Döner.'),
    examples: ['Das ist **der beste** Döner in Berlin.'],
  },
  {
    id: 'fix-attr',
    type: 'error_correction',
    topic: 'komparativ-attribut',
    concept: 'comp-attr',
    skill: 'grammar',
    difficulty: 2,
    sentence: 'Ich suche eine billiger Wohnung.',
    accepted: ['Ich suche eine billigere Wohnung.'],
    explanation: l('Before the noun: comparative + ending → billigere.', 'İsimden önce: karşılaştırma + ek → billigere.', 'billigere.'),
    examples: ['Ich suche eine **billigere** Wohnung.'],
  },
  {
    id: 'fix-am',
    type: 'error_correction',
    topic: 'komparativ-attribut',
    concept: 'sup-attr',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Das ist das am teuersten Hotel der Stadt.',
    accepted: ['Das ist das teuerste Hotel der Stadt.'],
    explanation: l('Before a noun no „am“: das teuerste Hotel.', 'İsimden önce „am“ yok: das teuerste Hotel.', 'das teuerste Hotel.'),
    examples: ['Das ist **das teuerste** Hotel der Stadt.'],
  },
  {
    id: 'fix-desto',
    type: 'error_correction',
    topic: 'je-desto',
    concept: 'je-desto-order',
    skill: 'grammar',
    difficulty: 3,
    sentence: 'Je mehr ich lerne, desto ich verstehe mehr.',
    accepted: ['Je mehr ich lerne, desto mehr verstehe ich.'],
    explanation: l('desto + comparative + verb + subject.', 'desto + karşılaştırma + fiil + özne.', 'desto mehr verstehe ich.'),
    examples: ['Je mehr ich lerne, **desto mehr verstehe** ich.'],
  },
  {
    id: 'tr-groesser',
    type: 'translation',
    topic: 'komparativ-attribut',
    concept: 'comp-attr',
    skill: 'writing',
    difficulty: 2,
    source: l('We need a bigger flat.', 'Daha büyük bir daireye ihtiyacımız var.', 'We need a bigger flat.'),
    accepted: ['Wir brauchen eine größere Wohnung.'],
    explanation: l('eine größere Wohnung (Akk f).', 'eine größere Wohnung (Akk dişil).', 'eine größere Wohnung.'),
    examples: ['Wir brauchen eine **größere** Wohnung.'],
  },
  {
    id: 'tr-je',
    type: 'translation',
    topic: 'je-desto',
    concept: 'je-desto-order',
    skill: 'writing',
    difficulty: 3,
    source: l('The earlier, the better.', 'Ne kadar erken o kadar iyi.', 'The earlier, the better.'),
    accepted: ['Je früher, desto besser.', 'Je früher, umso besser.', 'Je früher, desto besser!'],
    explanation: l('Short form: Je früher, desto besser.', 'Kısa biçim: Je früher, desto besser.', 'Je früher, desto besser.'),
    examples: ['**Je** früher, **desto** besser.'],
  },
  {
    id: 'ordering-grafik',
    type: 'ordering',
    topic: 'statistik',
    concept: 'describe-chart',
    skill: 'reading',
    difficulty: 2,
    promptL10n: l('How do you describe a chart? Put the steps in order.', 'Bir grafik nasıl anlatılır? Adımları sıraya koy.', 'Wie beschreibt man eine Grafik?'),
    items: ['Am meisten benutzen die Leute das Fahrrad.', 'Die Grafik zeigt, wie die Menschen zur Arbeit fahren.', 'Insgesamt fahren immer weniger Menschen mit dem Auto.', 'An zweiter Stelle steht der Bus.'],
    answer: ['Die Grafik zeigt, wie die Menschen zur Arbeit fahren.', 'Am meisten benutzen die Leute das Fahrrad.', 'An zweiter Stelle steht der Bus.', 'Insgesamt fahren immer weniger Menschen mit dem Auto.'],
    explanation: l('Topic → biggest value → next → summary.', 'Konu → en büyük değer → sonraki → özet.', 'Thema → Spitze → Platz 2 → Fazit.'),
  },
  {
    id: 'dialog-hotel',
    type: 'dialogue',
    topic: 'komparativ-attribut',
    concept: 'comp-attr',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Rezeption', de: 'Ist das Zimmer in Ordnung?' }],
    options: ['Es ist leider zu laut. Haben Sie ein ruhigeres Zimmer?', 'Es ist zu laut. Haben Sie ein ruhiger Zimmer?', 'Es ist zu laut. Haben Sie das am ruhigsten Zimmer?'],
    answer: 0,
    explanation: l('ein ruhigeres Zimmer (comparative + -es).', 'ein ruhigeres Zimmer (karşılaştırma + -es).', 'ein ruhigeres Zimmer.'),
  },
  {
    id: 'dialog-statistik',
    type: 'dialogue',
    topic: 'statistik',
    concept: 'describe-stats',
    skill: 'speaking',
    difficulty: 2,
    lines: [{ speaker: 'Lehrerin', de: 'Was zeigt die Grafik?' }],
    options: ['Sie zeigt, dass immer mehr junge Leute vegetarisch essen.', 'Sie zeigt, dass immer mehr junge Leute essen vegetarisch.', 'Sie zeigt immer mehr vegetarisch.'],
    answer: 0,
    explanation: l('zeigt, dass … + verb at the end.', 'zeigt, dass … + fiil sonda.', 'dass … essen.'),
  },

  // --- Reading --------------------------------------------------------
  {
    id: 'read-thema',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 1,
    prompt: 'Worum geht es in der Studie?',
    options: ['Wie die Deutschen zur Arbeit fahren.', 'Was die Deutschen essen.', 'Wo die Deutschen Urlaub machen.'],
    answer: 0,
    explanation: l('„… wie die Deutschen zur Arbeit kommen.“', '„… wie die Deutschen zur Arbeit kommen.“', 'Arbeitsweg.'),
  },
  {
    id: 'read-auto',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Wie viele fahren mit dem Auto?',
    options: ['Etwa die Hälfte.', 'Ein Viertel.', 'Fast alle.'],
    answer: 0,
    explanation: l('„Etwa die Hälfte fährt noch mit dem Auto.“', '„Etwa die Hälfte fährt noch mit dem Auto.“', 'die Hälfte.'),
  },
  {
    id: 'read-rad',
    type: 'true_false',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 2,
    statement: 'Die Zahl der Radfahrer ist in den letzten Jahren gesunken.',
    answer: false,
    explanation: l('„Die Zahl der Radfahrer ist stark gestiegen.“', '„Die Zahl der Radfahrer ist stark gestiegen.“', 'gestiegen.'),
  },
  {
    id: 'read-grund',
    type: 'multiple_choice',
    topic: 'reading',
    concept: 'reading-studie',
    skill: 'reading',
    difficulty: 2,
    prompt: 'Was ist das Fazit der Studie?',
    options: ['Je näher man wohnt, desto öfter fährt man Rad.', 'Je mehr man verdient, desto öfter fährt man Bus.', 'Niemand fährt gern Rad.'],
    answer: 0,
    explanation: l('„Je näher die Menschen an ihrer Arbeit wohnen, desto öfter fahren sie mit dem Rad.“', '„Je näher die Menschen an ihrer Arbeit wohnen, desto öfter fahren sie mit dem Rad.“', 'je näher, desto öfter.'),
  },

  // --- Listening -----------------------------------------------------
  {
    id: 'listen-prozent',
    type: 'listening_choice',
    topic: 'statistik',
    concept: 'fractions',
    skill: 'listening',
    difficulty: 2,
    audio: 'Etwa ein Viertel der Befragten liest jeden Tag ein Buch.',
    question: l('How many read every day?', 'Kaç kişi her gün okuyor?', 'Wie viele lesen jeden Tag?'),
    options: ['about 25 %', 'about 50 %', 'about 75 %'],
    answer: 0,
    explanation: l('ein Viertel = 25 %.', 'ein Viertel = %25.', '25 %.'),
  },
  {
    id: 'listen-je',
    type: 'listening_choice',
    topic: 'je-desto',
    concept: 'je-desto-order',
    skill: 'listening',
    difficulty: 2,
    audio: 'Je wärmer es draußen ist, desto mehr Eis verkaufen wir.',
    question: l('When do they sell more ice cream?', 'Ne zaman daha çok dondurma satıyorlar?', 'Wann verkaufen sie mehr Eis?'),
    options: ['when it’s warmer', 'when it’s colder', 'at weekends'],
    answer: 0,
    explanation: l('je wärmer … desto mehr.', 'ne kadar sıcak … o kadar çok.', 'wenn es wärmer ist.'),
  },
  {
    id: 'listen-attr',
    type: 'listening_choice',
    topic: 'komparativ-attribut',
    concept: 'sup-attr',
    skill: 'listening',
    difficulty: 2,
    audio: 'Wir haben das günstigste Angebot genommen, nicht das schnellste.',
    question: l('Which offer did they take?', 'Hangi teklifi seçtiler?', 'Welches Angebot haben sie genommen?'),
    options: ['the cheapest', 'the fastest', 'the most expensive'],
    answer: 0,
    explanation: l('„das günstigste Angebot“', '„das günstigste Angebot“', 'das günstigste.'),
  },
  {
    id: 'listen-trend',
    type: 'listening_choice',
    topic: 'statistik',
    concept: 'trends',
    skill: 'listening',
    difficulty: 2,
    audio: 'Die Zahl der Menschen, die Zeitung lesen, geht seit Jahren zurück.',
    question: l('What is happening?', 'Ne oluyor?', 'Was passiert?'),
    options: ['fewer people read newspapers', 'more people read newspapers', 'nothing changes'],
    answer: 0,
    explanation: l('zurückgehen = go down.', 'zurückgehen = azalmak.', 'weniger.'),
  },

  ...attrDrills(),
]

export const UNIT_B1_16_JE_DESTO: CourseUnit = {
  level: 'B1',
  number: 16,
  slug: 'je-desto',
  titleDe: 'Je mehr, desto besser',
  title: l('The more, the better', 'Ne kadar çok, o kadar iyi', 'Je mehr, desto besser'),
  goal: l(
    'By the end of this unit you can use comparatives and superlatives before nouns (ein größeres Auto, der billigste Flug), describe statistics and trends (die Hälfte, steigen, immer mehr) and express proportions with je … desto.',
    'Bu ünitenin sonunda karşılaştırma ve en üstünlüğü isimden önce kullanabilir (ein größeres Auto, der billigste Flug), istatistikleri ve eğilimleri anlatabilir (die Hälfte, steigen, immer mehr) ve je … desto ile orantı ifade edebilirsin.',
    'Am Ende dieser Einheit beschreibst du Vergleiche und Statistiken.'
  ),
  minutes: [20, 25],
  topics: [
    { key: 'komparativ-attribut', label: l('ein größeres …, der beste …', 'ein größeres …, der beste …', 'Komparativ als Attribut') },
    { key: 'je-desto', label: l('je … desto', 'je … desto', 'je … desto') },
    { key: 'statistik', label: l('Statistics & trends', 'İstatistik ve eğilimler', 'Statistiken') },
  ],
  vocabulary: [...VOCAB, ...MORE_VOCAB],
  exercises: EXERCISES,
  mastery: { minAnswered: 0.7, minAccuracy: 0.7 },
  sections: [
    {
      key: 'discover',
      kind: 'discover',
      title: l('Discover', 'Keşfet', 'Entdecken'),
      intro: l('Comparing – and talking about numbers.', 'Karşılaştırmak – ve sayılar hakkında konuşmak.', 'Vergleichen und Zahlen.'),
      cards: VOCAB,
    },
    {
      key: 'understand',
      kind: 'understand',
      title: l('Understand', 'Anla', 'Verstehen'),
      rules: [
        {
          title: l('Comparative & superlative before a noun', 'İsimden önce karşılaştırma ve en üstünlük', 'Komparativ & Superlativ vor dem Nomen'),
          body: l(
            'Before a noun they take the normal adjective endings (A2!): ein größeres Auto, die schnellere Verbindung, der billigste Flug, mit dem besten Freund. No „am“ before a noun!',
            'İsimden önce normal sıfat eklerini alırlar (A2!): ein größeres Auto, die schnellere Verbindung, der billigste Flug, mit dem besten Freund. İsimden önce „am“ yok!',
            'Adjektivendung; kein am.'
          ),
          table: {
            head: [l('After sein', 'sein’den sonra', 'nach sein'), l('Before a noun', 'İsimden önce', 'vor dem Nomen')],
            rows: [
              ['Das Auto ist größer.', 'ein größeres Auto'],
              ['Dieser Flug ist am billigsten.', 'der billigste Flug'],
              ['Sie ist am besten.', 'die beste Schülerin'],
            ],
          },
        },
        {
          title: l('Describing statistics', 'İstatistikleri anlatmak', 'Statistiken beschreiben'),
          body: l(
            'Die Grafik zeigt, dass … – Laut einer Umfrage … – die Hälfte / ein Drittel / ein Viertel / 40 Prozent der … – die Mehrheit – steigen / sinken / zurückgehen – immer mehr / immer weniger.',
            'Die Grafik zeigt, dass … – Laut einer Umfrage … – die Hälfte / ein Drittel / ein Viertel / 40 Prozent der … – die Mehrheit – steigen / sinken / zurückgehen – immer mehr / immer weniger.',
            'Redemittel für Grafiken.'
          ),
        },
        {
          title: l('je … desto (review)', 'je … desto (tekrar)', 'je … desto (Wiederholung)'),
          body: l('Je + comparative … verb (end), desto + comparative + verb + subject. Short: Je früher, desto besser.', 'Je + karşılaştırma … fiil (son), desto + karşılaştırma + fiil + özne. Kısa: Je früher, desto besser.', 'Je …, desto …'),
        },
      ],
    },
    {
      key: 'context',
      kind: 'context',
      title: l('See it in context', 'Bağlamda gör', 'Im Kontext'),
      scene: l('In the German course: describing a chart for the B1 exam.', 'Almanca kursunda: B1 sınavı için bir grafiği anlatmak.', 'Im Kurs: eine Grafik beschreiben.'),
      dialogue: [
        { speaker: 'Lehrerin', de: 'Was zeigt die Grafik, Ahmet?', translation: l('What does the chart show, Ahmet?', 'Grafik ne gösteriyor Ahmet?', '') },
        { speaker: 'Ahmet', de: 'Die Grafik zeigt, wie die Deutschen zur Arbeit fahren. **Die Hälfte** fährt noch mit dem Auto.', translation: l('The chart shows how Germans get to work. Half still go by car.', 'Grafik Almanların işe nasıl gittiğini gösteriyor. Yarısı hâlâ arabayla gidiyor.', '') },
        { speaker: 'Lehrerin', de: 'Und was hat sich verändert?', translation: l('And what has changed?', 'Peki ne değişti?', '') },
        { speaker: 'Ahmet', de: 'Die Zahl der Radfahrer **ist** stark **gestiegen**. **Immer mehr** Menschen nehmen das Fahrrad.', translation: l('The number of cyclists has risen sharply. More and more people take the bike.', 'Bisikletlilerin sayısı çok arttı. Giderek daha fazla insan bisiklet kullanıyor.', '') },
        { speaker: 'Lehrerin', de: 'Warum, glauben Sie?', translation: l('Why, do you think?', 'Sizce neden?', '') },
        { speaker: 'Ahmet', de: '**Je teurer** das Benzin wird, **desto mehr** Leute fahren Rad. Es ist **die günstigste** und **gesündeste** Lösung.', translation: l('The more expensive petrol gets, the more people cycle. It’s the cheapest and healthiest solution.', 'Benzin pahalılaştıkça daha çok insan bisiklete biniyor. En ucuz ve en sağlıklı çözüm bu.', '') },
      ],
      examples: [
        { de: 'Wir brauchen **ein größeres** Auto.', translation: l('We need a bigger car.', 'Daha büyük bir arabaya ihtiyacımız var.', '') },
        { de: 'Das ist **der billigste** Flug.', translation: l('That’s the cheapest flight.', 'Bu en ucuz uçuş.', '') },
        { de: '**Die Hälfte** der Befragten ist dafür.', translation: l('Half of those surveyed are in favour.', 'Ankete katılanların yarısı lehte.', '') },
        { de: 'Die Preise **steigen**.', translation: l('Prices are rising.', 'Fiyatlar artıyor.', '') },
        { de: '**Immer mehr** Menschen arbeiten online.', translation: l('More and more people work online.', 'Giderek daha fazla insan çevrimiçi çalışıyor.', '') },
        { de: '**Je** früher, **desto** besser.', translation: l('The earlier, the better.', 'Ne kadar erken o kadar iyi.', '') },
      ],
    },
    {
      key: 'practice-recognize',
      kind: 'practice',
      title: l('Practice 1 · Recognise', 'Pratik 1 · Tanı', 'Übung 1 · Erkennen'),
      intro: l('Comparing and statistics.', 'Karşılaştırma ve istatistik.', 'Vergleiche und Statistik.'),
      exercises: ['match-prozent', 'sort-trend', 'attr-groesseres', 'attr-schnellere', 'mc-am-der', 'tf-je', 'select-richtig', 'image-grafik', 'attr-billigsten'],
    },
    {
      key: 'practice-use',
      kind: 'practice',
      title: l('Practice 2 · Use', 'Pratik 2 · Kullan', 'Übung 2 · Anwenden'),
      intro: l('Compare and describe numbers.', 'Karşılaştır ve sayıları anlat.', 'Vergleiche und beschreibe Zahlen.'),
      exercises: [
        'fill-groesseren',
        'fill-desto',
        'fill-haelfte',
        'build-je',
        'build-umfrage',
        'build-beste',
        'fix-attr',
        'fix-am',
        'fix-desto',
        'tr-groesser',
        'tr-je',
        'ordering-grafik',
        'dialog-hotel',
        'dialog-statistik',
        'attr-beste',
        'attr-aelteren',
        'attr-hoechste',
      ],
    },
    {
      key: 'reading',
      kind: 'reading',
      title: l('Reading', 'Okuma', 'Lesen'),
      intro: l('A short article about a study.', 'Bir çalışma hakkında kısa bir makale.', 'Ein Artikel über eine Studie.'),
      passage: [
        'Eine neue Studie zeigt, wie die Deutschen zur Arbeit kommen.',
        'Etwa **die Hälfte** fährt noch mit dem Auto, **ein Viertel** nimmt Bus oder Bahn.',
        'Die Zahl der Radfahrer **ist** in den letzten zehn Jahren stark **gestiegen** – vor allem in **größeren** Städten.',
        'Das Fazit: **Je näher** die Menschen an ihrer Arbeit wohnen, **desto öfter** fahren sie mit dem Rad.',
      ],
      glossary: [
        { de: 'die Studie', note: l('study', 'araştırma', 'wissenschaftliche Untersuchung') },
        { de: 'vor allem', note: l('above all', 'özellikle', 'besonders') },
        { de: 'das Fazit', note: l('conclusion', 'sonuç', 'Ergebnis') },
      ],
      exercises: ['read-thema', 'read-auto', 'read-rad', 'read-grund'],
    },
    {
      key: 'listening',
      kind: 'listening',
      title: l('Listening', 'Dinleme', 'Hören'),
      intro: l('Numbers, trends and comparisons.', 'Sayılar, eğilimler ve karşılaştırmalar.', 'Zahlen, Trends, Vergleiche.'),
      exercises: ['listen-prozent', 'listen-je', 'listen-attr', 'listen-trend'],
    },
    {
      key: 'speaking',
      kind: 'speaking',
      title: l('Speaking', 'Konuşma', 'Sprechen'),
      prompt: l('Describe a chart (imagine one): „How people in your city spend their free time“.', 'Bir grafiği anlat (hayal et): „Şehrindeki insanlar boş zamanlarını nasıl geçiriyor“.', 'Beschreib eine Grafik.'),
      points: [
        l('„Die Grafik zeigt, …“', '„Die Grafik zeigt, …“', 'Thema'),
        l('Biggest group: „Die meisten …“ / „Die Hälfte …“', 'En büyük grup: „Die meisten …“ / „Die Hälfte …“', 'größte Gruppe'),
        l('A trend: „Immer mehr / weniger …“', 'Bir eğilim: „Immer mehr / weniger …“', 'Trend'),
        l('Your conclusion: „Je …, desto …“', 'Sonucun: „Je …, desto …“', 'Fazit'),
      ],
      model: [
        'Die Grafik zeigt, was die Menschen in Köln in ihrer Freizeit machen.',
        'Die meisten – etwa 60 Prozent – treffen Freunde.',
        'Ein Drittel macht regelmäßig Sport.',
        'Immer weniger Menschen gehen ins Kino, weil Streaming billiger ist.',
        'Ich glaube: Je jünger die Leute sind, desto mehr Zeit verbringen sie online.',
      ],
    },
    {
      key: 'writing',
      kind: 'writing',
      title: l('Writing', 'Yazma', 'Schreiben'),
      prompt: l(
        'Compare two offers (two flats, phones, holidays …) in a short text (at least 5 sentences).',
        'İki teklifi (iki daire, telefon, tatil …) kısa bir metinde karşılaştır (en az 5 cümle).',
        'Vergleiche zwei Angebote (mindestens 5 Sätze).'
      ),
      minSentences: 5,
      checks: [
        { label: l('Comparative before a noun (ein größeres …)', 'İsimden önce karşılaştırma (ein größeres …)', 'Komparativ vor Nomen'), pattern: '\\b(ein|eine|einen|einem|einer|der|die|das|den|dem)\\s+\\p{Ll}+er(e|en|es|er)\\s+\\p{Lu}' },
        { label: l('Superlative before a noun (der billigste …)', 'İsimden önce en üstünlük (der billigste …)', 'Superlativ vor Nomen'), pattern: '\\b(der|die|das|den|dem)\\s+\\p{Ll}+(s|e)?ste(n)?\\s+\\p{Lu}' },
        { label: l('je … desto', 'je … desto', 'je … desto'), pattern: '[Jj]e\\b[^.!?]*\\b(desto|umso)\\b' },
      ],
      model: [
        'Ich vergleiche zwei Handys: das Phone X und das Galaxy Y.',
        'Das Phone X hat eine bessere Kamera und einen größeren Speicher.',
        'Das Galaxy Y ist aber das günstigere Modell.',
        'Für mich ist der niedrigste Preis am wichtigsten.',
        'Je billiger das Handy ist, desto mehr Geld habe ich für den Urlaub!',
      ],
    },
    {
      key: 'speed',
      kind: 'timed',
      title: l('Speed round', 'Hız turu', 'Schnellrunde'),
      intro: l('Comparative endings – 60 seconds.', 'Karşılaştırma ekleri – 60 saniye.', 'Endungen – 60 Sekunden.'),
      seconds: 60,
      pool: [...ATTR.map(([id]) => `attr-${id}`), 'mc-am-der'],
    },
    {
      key: 'review',
      kind: 'review',
      title: l('Review', 'Tekrar', 'Wiederholung'),
      intro: l(
        'Your mistakes in this unit – with the correct form. Practise them once more now.',
        'Bu ünitedeki hataların – doğru biçimleriyle. Şimdi bir kez daha çalış.',
        'Deine Fehler in dieser Einheit – mit der richtigen Form. Übe sie jetzt noch einmal.'
      ),
    },
    { key: 'summary', kind: 'summary', title: l('Mastery', 'Ustalık', 'Abschluss') },
  ],
  summary: {
    learned: [
      l('ein größeres Auto, der billigste Flug (adjective endings)', 'ein größeres Auto, der billigste Flug (sıfat ekleri)', 'Komparativ/Superlativ als Attribut'),
      l('Statistics: die Hälfte, ein Drittel, Prozent, die Mehrheit', 'İstatistik: die Hälfte, ein Drittel, Prozent, die Mehrheit', 'Statistik'),
      l('Trends: steigen, sinken, immer mehr / weniger', 'Eğilimler: steigen, sinken, immer mehr / weniger', 'Trends'),
      l('je … desto', 'je … desto', 'je … desto'),
    ],
    mistakes: [
      { wrong: 'eine billiger Wohnung', right: 'eine billigere Wohnung', note: l('Ending needed.', 'Ek gerekli.', 'Endung!') },
      { wrong: 'das am teuersten Hotel', right: 'das teuerste Hotel', note: l('No am before a noun.', 'İsimden önce am yok.', 'ohne am.') },
      { wrong: 'Die Preise steigern.', right: 'Die Preise steigen.', note: l('steigen (intransitive).', 'steigen (geçişsiz).', 'steigen.') },
      { wrong: '…, desto ich verstehe mehr.', right: '…, desto mehr verstehe ich.', note: l('desto + comparative + verb.', 'desto + karşılaştırma + fiil.', 'desto mehr verstehe ich.') },
    ],
  },
}
